### PR TITLE
Add plugin: Remember View State

### PR DESCRIPTION
**Pull request by clehene**
# I am submitting a new Community Plugin

## Repo URL

https://github.com/clehene/obsidian-remember-view-state/

Link to my plugin:

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "Remember the view state of your tabs. When you reopen Obsidian, the cursor every editor will be placed at the last position you left it",](https://github.com/clehene/obsidian-remember-view-state/blob/4f5906deff76452fae454fd3dc8c5c917ba3a29f/manifest.json#L6)
That second sentence makes no gramatical sense, also please don't include "Obsidian" in the description.

Remove the `styles.css` file from your release, since it's empty it's just unnecessary bloat.

[import {ScrollInfo} from "codemirror";](https://github.com/clehene/obsidian-remember-view-state/blob/4f5906deff76452fae454fd3dc8c5c917ba3a29f/main.ts#L13)
Remove this unused import

[// Remember to rename these classes and interfaces!](https://github.com/clehene/obsidian-remember-view-state/blob/4f5906deff76452fae454fd3dc8c5c917ba3a29f/main.ts#L15)
Remove this comment

[mySetting: string;](https://github.com/clehene/obsidian-remember-view-state/blob/4f5906deff76452fae454fd3dc8c5c917ba3a29f/main.ts#L18), [mySetting: 'default',](https://github.com/clehene/obsidian-remember-view-state/blob/4f5906deff76452fae454fd3dc8c5c917ba3a29f/main.ts#L23)
Remove this sample code.

[console.log("Loading tabs", this.settings.tabs)](https://github.com/clehene/obsidian-remember-view-state/blob/4f5906deff76452fae454fd3dc8c5c917ba3a29f/main.ts#L62-L63), [console.log('setting cursor for tab', index, view.getDisplayText(), viewId, tabState)](https://github.com/clehene/obsidian-remember-view-state/blob/4f5906deff76452fae454fd3dc8c5c917ba3a29f/main.ts#L76), [console.log('>>>> setting scroll for tab', index, view.getDisplayText(), viewId, scroll)](https://github.com/clehene/obsidian-remember-view-state/blob/4f5906deff76452fae454fd3dc8c5c917ba3a29f/main.ts#L78), [console.log('Saving tabs', this.settings.tabs)](https://github.com/clehene/obsidian-remember-view-state/blob/4f5906deff76452fae454fd3dc8c5c917ba3a29f/main.ts#L113)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

**Comment by clehene** [comment]
Thanks @joethei

> ✅  ["description": "Remember the view state of your tabs. When you reopen Obsidian, the cursor every editor will be placed at the last position you left it",](https://github.com/clehene/obsidian-remember-view-state/blob/4f5906deff76452fae454fd3dc8c5c917ba3a29f/manifest.json#L6) That second sentence makes no gramatical sense, also please don't include "Obsidian" in the description.


> ✅ Remove the `styles.css` file from your release, since it's empty it's just unnecessary bloat.
> 
> ✅ [import {ScrollInfo} from "codemirror";](https://github.com/clehene/obsidian-remember-view-state/blob/4f5906deff76452fae454fd3dc8c5c917ba3a29f/main.ts#L13) Remove this unused import
> 
>✅  [// Remember to rename these classes and interfaces!](https://github.com/clehene/obsidian-remember-view-state/blob/4f5906deff76452fae454fd3dc8c5c917ba3a29f/main.ts#L15) Remove this comment
> 
> ✅ [mySetting: string;](https://github.com/clehene/obsidian-remember-view-state/blob/4f5906deff76452fae454fd3dc8c5c917ba3a29f/main.ts#L18), [mySetting: 'default',](https://github.com/clehene/obsidian-remember-view-state/blob/4f5906deff76452fae454fd3dc8c5c917ba3a29f/main.ts#L23) Remove this sample code.
> 
>✅  [console.log("Loading tabs", this.settings.tabs)](https://github.com/clehene/obsidian-remember-view-state/blob/4f5906deff76452fae454fd3dc8c5c917ba3a29f/main.ts#L62-L63), [console.log('setting cursor for tab', index, view.getDisplayText(), viewId, tabState)](https://github.com/clehene/obsidian-remember-view-state/blob/4f5906deff76452fae454fd3dc8c5c917ba3a29f/main.ts#L76), [console.log('>>>> setting scroll for tab', index, view.getDisplayText(), viewId, scroll)](https://github.com/clehene/obsidian-remember-view-state/blob/4f5906deff76452fae454fd3dc8c5c917ba3a29f/main.ts#L78), [console.log('Saving tabs', this.settings.tabs)](https://github.com/clehene/obsidian-remember-view-state/blob/4f5906deff76452fae454fd3dc8c5c917ba3a29f/main.ts#L113) Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

**Comment by clehene** [comment]
@joethei do you need anything else from me or is this good to go?

**Comment by liamcain** [comment]
- [markdownView.editor.getCursor()](https://github.com/clehene/obsidian-remember-view-state/blob/b50450e804f41117a419822ae8883ebbb9605ce4/main.ts#L97) No need to try to get this info from the editor. You should be using [`getEphemeralState`](<https://github.com/obsidianmd/obsidian-api/blob/df9434bec6883bd32727f61b1ed1336f7663d0e4/obsidian.d.ts#L4855C5-L4855C22>) instead. It's a public API and you can get it from all views, not just Markdown views.
- [index](https://github.com/clehene/obsidian-remember-view-state/blob/b50450e804f41117a419822ae8883ebbb9605ce4/main.ts#L99) You are indexing based on the `index` which is not a safe assumption that the view order will stay the same. If you reorder the tabs (which might not change the active leaf), you'll need to rebuild the entire list. Instead you should be keying your data off the view ID, which is stable.
- [active-leaf-change', this.handleActiveLeafChange](https://github.com/clehene/obsidian-remember-view-state/blob/b50450e804f41117a419822ae8883ebbb9605ce4/main.ts#L28) if you are only interested in restoring the tab state when reopening Obsidian, there's no need to track all this on every leaf change. Just register a 'quit' event handler that saves the ephemeral state on close. Then when the plugin loads, attempt to restore the state to each tab, based on the view ID.

**Comment by clehene** [comment]
1.7.2 broke the plugin. I fixed it, will try to get time to push changes and make another release and PR

**Pull request closed without merging**
