### PR TITLE
Add plugin ImageResizer

### PR DESCRIPTION
**Pull request by maoxiaoke**
## I am submitting a new Community Plugin
Repo URL
Link to my plugin:
https://github.com/maoxiaoke/image-resizer

## Release Checklist
 I have tested the plugin on
 - [x] Windows
 - [x] macOS
 - [x] Linux
 - [ ] Android (if applicable)
 - [] (if applicable)
 My GitHub release contains all required files
 - [x] main.js
 - [x] manifest.json
 - [x] styles.css (optional)
 GitHub release name matches the exact version number specified in my manifest.json (Note: Use the exact version number, don't include a prefix v)
 - [x] The id in my manifest.json matches the id in the community-plugins.json file.
 - [x] My README.md describes the plugin's purpose and provides clear usage instructions.
 - [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
 - [x] I have added a license in the LICENSE file.
 - [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
- [x] I have given proper attribution to these other projects in my README.md.

### CODE REVIEW

**Comment by joethei** [comment]
@maoxiaoke please fix the validation error above.

**Comment by maoxiaoke** [comment]
> @maoxiaoke please fix the validation error above.

All validation errors passed

**Comment by maoxiaoke** [comment]
@joethei All validation errors passed.

**Comment by joethei** [comment]
[This plugin allow you resize your notes of Obsidian.](https://github.com/maoxiaoke/image-resizer/blob/1c51d72f626b36b3e5622a62a335e7006076c416/README.md#L5)
This text is missing the part about images.

You should move all all code files into a separate `src` folder, that makes it easier to review and maintain.

[MyPlugin](https://github.com/maoxiaoke/image-resizer/blob/1c51d72f626b36b3e5622a62a335e7006076c416/main.ts#L15)
Rename this class.

[containerEl.createEl("h3", { text: "Image Resizer Settings" });](https://github.com/maoxiaoke/image-resizer/blob/1c51d72f626b36b3e5622a62a335e7006076c416/main.ts#L132-L133)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[export const debounce = <T extends (...args: any[]) => void>(](https://github.com/maoxiaoke/image-resizer/blob/1c51d72f626b36b3e5622a62a335e7006076c416/helpers.ts#L1-L10)
The Obsidian API already has this function.


[addStyle() {](https://github.com/maoxiaoke/image-resizer/blob/1c51d72f626b36b3e5622a62a335e7006076c416/main.ts#L18-L37)
Put the CSS code into the `styles.css` file, and remove all this code.

[export const collectSizeArbitraryValues = (texts: string[]) => {](https://github.com/maoxiaoke/image-resizer/blob/1c51d72f626b36b3e5622a62a335e7006076c416/helpers.ts#L15-L40)
I also dislike this approach of parsing the entire note content and modifying the CSS accordingly.
Instead, you should use a [Decoration](https://docs.obsidian.md/Plugins/Editor/Decorations) which only applies to image elements and set the variable there.


It looks like your plugin does not support reading view, you should consider adding a markdown post processor for that: <https://docs.obsidian.md/Plugins/Editor/Markdown+post+processing>

**Pull request closed without merging**
