### PR TITLE
Add plugin: ManicTime

### PR DESCRIPTION
**Pull request by manictime**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/manictime/manictime-obsidian

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "This extension sends path of active file to locally installed ManicTime client",](https://github.com/manictime/manictime-obsidian/blob/2cdbaf6628170cb26cffcbef18260142311dceff/manifest.json#L6)
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This is a plugin for Obsidian that does ..." in your description.

[this.app.workspace.on('active-leaf-change', () => this.sendData());](https://github.com/manictime/manictime-obsidian/blob/2cdbaf6628170cb26cffcbef18260142311dceff/main.ts#L14-L17)
Events need to be registered, so they can be properly unloaded when the plugin is disabled. <https://docs.obsidian.md/Plugins/Events>

**Comment by manictime** [comment]
The issues have been fixed.

**Comment by liamcain** [comment]
- [serverManager](https://github.com/manictime/manictime-obsidian/blob/8279924e36d71c4275c4b5daf226b72715aa2522/main.ts#L55) Server manager shouldn't be wrapped in a IIFE. This means that it's lifecycle management is completely independent from the plugin. If the plugin is disabled, it won't be properly cleaned up. Instead, you should either move this into the Plugin class, or make a separate class with a cleanup function to ensure that the interval is removed when the plugin is disabled.

**Comment by tilen-fiser** [comment]
Issue was fixed. The interval is removed when plugin is disabled.

**Pull request closed without merging**
