### PR TITLE
add auto upload image plugin for lsky

### PR DESCRIPTION
**Pull request by NekoTarou**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:https://github.com/NekoTarou/lskypro-auto-upload

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[Copyright (c) 2021 Kirill Gavrilov](https://github.com/NekoTarou/lskypro-auto-upload/blob/e6ab9e0f383aa7e96a164b00e77402987532a5a7/LICENSE#L3)
Replace this with your own info.

["description": "This plugin uploads images from your clipboard to lskypro",](https://github.com/NekoTarou/lskypro-auto-upload/blob/e6ab9e0f383aa7e96a164b00e77402987532a5a7/manifest.json#L6)
We have recently published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This plugin" in your description.

[let leaf = this.app.workspace.activeLeaf;](https://github.com/NekoTarou/lskypro-auto-upload/blob/e6ab9e0f383aa7e96a164b00e77402987532a5a7/src/main.ts#L80)
`activeLeaf` is deprecated and should not be used.

This plugin heavily relies on the `fs` and `path` libraries, I would recommend using the Obsidian
Vault API instead.
<https://docs.obsidian.md/Plugins/Vault>

Your translation files contain references to "PicGo", you can remove those.

**Comment by NekoTarou** [comment]
Thanks for helping me point out the problem. The following issues have been adjusted:
1. Information in LICENSE
2. Description information
3. Deprecated calling activeLeaf
4. The fs module is removed and replaced by Vault API

It should be noted that I did not remove the path module because there are some places that need to calculate the path of the file

**Comment by joethei** [comment]
[export function getOS() {](https://github.com/NekoTarou/lskypro-auto-upload/blob/179e939732e8d89012f9165a33076cd309beaaec/src/utils.ts#L28-L39)
You can use [`Platform`](https://github.com/obsidianmd/obsidian-api/blob/583ba39e3f6c0546de5e5e8742256a60e2d78ebc/obsidian.d.ts#L2641-L2714) from the Obsidian API instead.

[clipboard.read("FileNameW");](https://github.com/NekoTarou/lskypro-auto-upload/blob/179e939732e8d89012f9165a33076cd309beaaec/src/utils.ts#L61)
Use `navigator.clipboard.readText` instead of relying on electron API's.

**Comment by NekoTarou** [comment]
[export function getOS() {](https://github.com/NekoTarou/lskypro-auto-upload/blob/179e939732e8d89012f9165a33076cd309beaaec/src/utils.ts#L28-L39)
This function is not used and has been removed。

[clipboard.read("FileNameW");](https://github.com/NekoTarou/lskypro-auto-upload/blob/179e939732e8d89012f9165a33076cd309beaaec/src/utils.ts#L61)
Use ClipboardEvent to get the contents of the clipboard，this code here has been removed

**Comment by NekoTarou** [comment]
resolve code conflicts

**Comment by NekoTarou** [comment]
Add entry at the end and resolve code conflicts

**Comment by marcusolsson** [comment]
[this.settings = Object.assign(DEFAULT_SETTINGS, await this.loadData());](https://github.com/NekoTarou/lskypro-auto-upload/blob/91d917ebf1fb66bf5c251aa9b56f8dbb3a9f9509/src/main.ts#L42)
You're mutating the default settings object here, which may not be what you want. Consider `this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());`.

**Comment by NekoTarou** [comment]
Adjust the function to get the default configuration,and version upgrades

[this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());](https://github.com/NekoTarou/lskypro-auto-upload/blob/2cc6b2ba59bd4e71bcc80946421eb9d93918ee0a/src/main.ts#L42)

**Comment by liamcain** [comment]
- [getActiveFile](https://github.com/NekoTarou/lskypro-auto-upload/blob/2cc6b2ba59bd4e71bcc80946421eb9d93918ee0a/src/main.ts#L197) this function can return null. Make sure to handle that case.
-

**Pull request merged**
