### PR TITLE
Add plugin `show-hidden-files`

### PR DESCRIPTION
**Pull request by polyipseity**
# I am submitting a new Community Plugin

Previous: https://github.com/obsidianmd/obsidian-releases/pull/1959

Finally got the time to fix up the approach: https://github.com/polyipseity/obsidian-show-hidden-files/blob/b77499dd1bcb0e2ad03631fafa2c6b069fa68f45/sources/show-hidden-files.ts

## Repo URL

Link to my plugin: https://github.com/polyipseity/obsidian-show-hidden-files

## Release Checklist
- [x] I have tested the plugin on
  - [x] Windows
  - [x] macOS
  - [x] Linux
  - [x] Android _(if applicable)_
  - [x] iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[super.onload()](https://github.com/polyipseity/obsidian-show-hidden-files/blob/51362d8a93fe00af34a2be648aa38ad0a699b00a/sources/main.ts#L61)
Not needed.

[child.register(() => { self.clearTimeout(id) })](https://github.com/polyipseity/obsidian-show-hidden-files/blob/51362d8a93fe00af34a2be648aa38ad0a699b00a/sources/main.ts#L72)
If you haven't seen it, there is already a `registerTimeout` function in the API.

[if (inSet(Platform.DESKTOP, Platform.CURRENT)) {](https://github.com/polyipseity/obsidian-show-hidden-files/blob/51362d8a93fe00af34a2be648aa38ad0a699b00a/sources/show-hidden-files.ts#L141)
Obsidian already has a its own `Platform` class, no need to reinvent the wheel.
`ìf (Platform.isDesktopApp)`

**Comment by polyipseity** [comment]
> [super.onload()](https://github.com/polyipseity/obsidian-show-hidden-files/blob/51362d8a93fe00af34a2be648aa38ad0a699b00a/sources/main.ts#L61) Not needed.

Removed.

> [child.register(() => { self.clearTimeout(id) })](https://github.com/polyipseity/obsidian-show-hidden-files/blob/51362d8a93fe00af34a2be648aa38ad0a699b00a/sources/main.ts#L72) If you haven't seen it, there is already a `registerTimeout` function in the API.

I have found only `Plugin#registerInterval` but not `Plugin#registerTimeout` in both [`obsidian.d.ts`](https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts) and the developer console.

> [if (inSet(Platform.DESKTOP, Platform.CURRENT)) {](https://github.com/polyipseity/obsidian-show-hidden-files/blob/51362d8a93fe00af34a2be648aa38ad0a699b00a/sources/show-hidden-files.ts#L141) Obsidian already has a its own `Platform` class, no need to reinvent the wheel. `ìf (Platform.isDesktopApp)`

Made `Platform#CURRENT` detect the platform by directly using the `Platform` from `obsidian` instead, so now the custom `Platform` is just a simple wrapper over the Obsidian one. The custom `Platform` has additional functions like ensuring the current platform is checked:
```ts
// @ts-expect-error
await adapter.reconcileFileInternal<typeof Platform.CURRENT>(realPath, path)

if (inSet(Platform.DESKTOP, Platform.CURRENT)) {
  // No errors
  await adapter.reconcileFileInternal<typeof Platform.CURRENT>(realPath, path)
}
```

**Comment by joethei** [comment]
> I have found only Plugin#registerInterval but not Plugin#registerTimeout in both [obsidian.d.ts](https://github.com/obsidianmd/obsidian-api/blob/910e2d61e0f0ec9d7f1ff7ce82c53674fba5c905/obsidian.d.ts) and the developer console. Seems like I am supposed to do it myself? https://github.com/obsidianmd/obsidian-api/issues/101

Whoops, gave the wrong info here, sorry.

**Comment by liamcain** [comment]
Hi @polyipseity, really great job on this plugin! It looks amazing and well-built. This approach looks a lot cleaner and less hacky than the first approach.

Unfortunately, we're still not comfortable with this being in the community plugin list given how it deeply it hooks into the file system and patches the file system adapter. We're concerned that this will cause issues with Obsidian Sync or create breakages down the line as Obsidian core code changes and drifts away from the plugin.

That said, there's clearly a large population of users that are interested in using this plugin, so feel free to announce it on Discord and/or forum and continue to distribute it via Github. Users can download and install the plugin manually at their own risk.

**Pull request closed without merging**
