### PR TITLE
Add plugin: OpenAPI Renderer

### PR DESCRIPTION
**Pull request by Ssentiago**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Ssentiago/openapi-renderer

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Ssentiago** [comment]
updated

**Comment by Ssentiago** [comment]
i have fixed this

**Comment by Ssentiago** [comment]
Okay, I'll fix it and update the PR when I do.

**Comment by Ssentiago** [comment]
updated

**Comment by joethei** [comment]
[title: 'Toggle OpenAPI Renderer Server',](https://github.com/Ssentiago/openapi-renderer/blob/d71591f3387b045cf10eb370a1d5bd242027c610/src/UI/buttonFactory.ts#L39), [.setName('UI Customization')](https://github.com/Ssentiago/openapi-renderer/blob/d71591f3387b045cf10eb370a1d5bd242027c610/src/settings/UISettings.ts#L33), [this.utils.createLocationToggle(renderDetails, 'Toolbar Button',](https://github.com/Ssentiago/openapi-renderer/blob/d71591f3387b045cf10eb370a1d5bd242027c610/src/settings/UISettings.ts#L92), [this.utils.createLocationToggle(renderDetails, 'Statusbar Button',](https://github.com/Ssentiago/openapi-renderer/blob/d71591f3387b045cf10eb370a1d5bd242027c610/src/settings/UISettings.ts#L94), [this.utils.createLocationToggle(refreshDetails, 'Toolbar Button',](https://github.com/Ssentiago/openapi-renderer/blob/d71591f3387b045cf10eb370a1d5bd242027c610/src/settings/UISettings.ts#L104), [this.utils.createLocationToggle(refreshDetails, 'Statusbar Button',](https://github.com/Ssentiago/openapi-renderer/blob/d71591f3387b045cf10eb370a1d5bd242027c610/src/settings/UISettings.ts#L106), [this.utils.createLocationToggle(serverDetails, 'Toolbar Button',](https://github.com/Ssentiago/openapi-renderer/blob/d71591f3387b045cf10eb370a1d5bd242027c610/src/settings/UISettings.ts#L60), [this.utils.createLocationToggle(serverDetails, 'Statusbar Button',](https://github.com/Ssentiago/openapi-renderer/blob/d71591f3387b045cf10eb370a1d5bd242027c610/src/settings/UISettings.ts#L62). [.setName('Server Status')](https://github.com/Ssentiago/openapi-renderer/blob/d71591f3387b045cf10eb370a1d5bd242027c610/src/settings/serverSettings.ts#L31)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[console.log(this.plugin.settings)](https://github.com/Ssentiago/openapi-renderer/blob/d71591f3387b045cf10eb370a1d5bd242027c610/src/settings/UISettings.ts#L44)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[.setName('Server settings')](https://github.com/Ssentiago/openapi-renderer/blob/d71591f3387b045cf10eb370a1d5bd242027c610/src/settings/serverSettings.ts#L27), [.setName('Rendering settings')](https://github.com/Ssentiago/openapi-renderer/blob/d71591f3387b045cf10eb370a1d5bd242027c610/src/settings/renderSettings.ts#L37)
[Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

[this.utils.createLocationToggle(serverDetails, 'Ribbon Button',](https://github.com/Ssentiago/openapi-renderer/blob/d71591f3387b045cf10eb370a1d5bd242027c610/src/settings/UISettings.ts#L58-L59), [this.utils.createLocationToggle(renderDetails, 'Ribbon Button',](https://github.com/Ssentiago/openapi-renderer/blob/d71591f3387b045cf10eb370a1d5bd242027c610/src/settings/UISettings.ts#L90-L91)
As of v1.1.0 of Obsidian, the ribbon can be customized within Obsidian. So users can choose what items to include and in what order all in one place. Because of this, we're recommending that new plugins avoid introducing their own toggles for ribbon items.

[<link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@3/swagger-ui.css">](https://github.com/Ssentiago/openapi-renderer/blob/d71591f3387b045cf10eb370a1d5bd242027c610/src/rendering/openAPIRender.ts#L120), [<script src="https://unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>](https://github.com/Ssentiago/openapi-renderer/blob/d71591f3387b045cf10eb370a1d5bd242027c610/src/rendering/openAPIRender.ts#L129-L130)
These resources should not be loaded externally, but rather bundled with the plugin.

[.obsidian/plugins/openapi-renderer/logs](https://github.com/Ssentiago/openapi-renderer/blob/d71591f3387b045cf10eb370a1d5bd242027c610/src/pluginLogging/loggingManager.ts#L14)
The configuration folder is not necessarily `.obsidian` it can be configured by the user.
Use this instead: `this.appContext.plugin.manifest.dir`

**Comment by Ssentiago** [comment]
Okay, I'll fix that

**Pull request merged**
