### PR TITLE
Adding VC Pilot Plugin

### PR DESCRIPTION
**Pull request by OmarHedeya95**
A plugin that can summarize notes about startups and VCs (GPT-4) and automatically push them to Affinity (CRM)

Updated the manifest.json

Please switch to **Preview** and select one of the following links:

* [Community Plugin](?template=plugin.md)

## Release Checklist
Release Checklist
 - [x] I have tested the plugin on
    - [x] macOS
- [x] My GitHub release contains all required files
   - [x] main.js
   - [x] manifest.json
   - [x] styles.css (optional)
-[x] GitHub release name matches the exact version number specified in my manifest.json (Note: Use the exact version number, don't include a prefix v)
 - [x] The id in my manifest.json matches the id in the community-plugins.json file.
 - [x] My README.md describes the plugin's purpose and provides clear usage instructions.
 - [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
- [x] I have given proper attribution to these other projects in my README.md.

### CODE REVIEW

**Comment by OmarHedeya95** [comment]
I just updated the manifest.json file

**Comment by OmarHedeya95** [comment]
Just removed the "v" from the releae version name. Should be correct now

**Comment by OmarHedeya95** [comment]
Thanks a lot for the feedback. I implemented the requested changes now

**Comment by OmarHedeya95** [comment]
Following up shortly here

**Comment by joethei** [comment]
Please remove the main.js file from the repo and add it to your .gitignore - compiled release files shouldn't get mixed with source code in your commits and should go to the releases files instead.

**Comment by joethei** [comment]
[.quote {](https://github.com/OmarHedeya95/vc-copilot/blob/d457f8b151c249b74663a4cac29f1f9bb10cd7bd/styles.css#L1)
[.heading {](https://github.com/OmarHedeya95/vc-copilot/blob/d457f8b151c249b74663a4cac29f1f9bb10cd7bd/styles.css#L10)
These class names are pretty generic, would recommend making them more unique.

[import * as fs from 'fs';](https://github.com/OmarHedeya95/vc-copilot/blob/d457f8b151c249b74663a4cac29f1f9bb10cd7bd/src/main.ts#L3-L4)
Unused imports.
These imports are only available from a nodeJS runtime, which means that this would throw errors on Mobile (that's a problem since you have `isDesktopOnly` marked as `false` in your manifest.json file.


[scriptPath_AI = this.settings.vaultPath + '.obsidian/plugins/vc_copilot'](https://github.com/OmarHedeya95/vc-copilot/blob/d457f8b151c249b74663a4cac29f1f9bb10cd7bd/src/main.ts#L447)
Looks like this setting is also unused.

[console.log(`Title: ${title}`)](https://github.com/OmarHedeya95/vc-copilot/blob/d457f8b151c249b74663a4cac29f1f9bb10cd7bd/src/main.ts#L146-L147)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[containerEl.createEl('h2', {text: 'Settings for your copilot'});](https://github.com/OmarHedeya95/vc-copilot/blob/d457f8b151c249b74663a4cac29f1f9bb10cd7bd/src/main.ts#L550)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)
[Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

[submitButton.style.position = 'absolute';](https://github.com/OmarHedeya95/vc-copilot/blob/d457f8b151c249b74663a4cac29f1f9bb10cd7bd/src/modal.ts#L31)
You should avoid assigning styles via JavaScript or in HTML and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets.

[let r: any = await request({](https://github.com/OmarHedeya95/vc-copilot/blob/d457f8b151c249b74663a4cac29f1f9bb10cd7bd/src/utils.ts#L61-L66)
Alternatively you can use:
```ts
 const r = await request({
	url: full_url,
	method: "GET",
	headers: headers
});
 
const response = r.json();
```
Also you should not type `r` as `any´ here.

**Comment by ericaxu** [comment]
Hi there, to keep things tidy, we're going to temporarily close plugin PRs after a month of inactivity.

Feel free to tell us to re-open it when you're ready to continue. Thanks for your understanding!

**Pull request closed without merging**
