### PR TITLE
Add plugin: Slides Extended

### PR DESCRIPTION
**Pull request by ebullient**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/ebullient/obsidian-slides-extended

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by ebullient** [comment]
/skip

- "You should not cast this, instead use a instanceof check to make sure that it's actually a file/folder" is a bad regex match. Not what the code is doing.

- "You should avoid assigning styles via JavaScript or in HTML and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets." I can't follow this, as the styles are being applied to reveal.js / slide elements, not to Obsidian UI / page-styled elements.

**Comment by joethei** [comment]
Oh, first result is actually correct, just using the wrong message.
FileSystemAdapter is only a thing on desktop, and we might decide to add additional adapters for different OSes at some point.(I know that the plugin is desktop only)
You should do an instance of check here.

**Comment by ebullient** [comment]
> Oh, first result is actually correct, just using the wrong message. FileSystemAdapter is only a thing on desktop, and we might decide to add additional adapters for different OSes at some point.(I know that the plugin is desktop only) You should do an instance of check here.

Ok. Fixed.

**Comment by joethei** [comment]
["description": "Create markdown-based presentations using reveal.js in Obsidian",](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/manifest.json#L6)
The description should not include the word "Obsidian"

["minAppVersion": "0.16.0",](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

[id: 'open-slides-extended-preview',](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-Plugin.ts#L74), [id: 'reload-slides-extended-preview',](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-Plugin.ts#L80), [id: 'stop-server-slides-extended-preview',](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-Plugin.ts#L91), [id: 'start-server-slides-extended-preview',](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-Plugin.ts#L96)
Don't include the plugin id in the command id, Obsidian will make sure that there are no conflicts with other plugins.

[this.addRibbonIcon('slides', 'Show Slide Preview', async () => {](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-Plugin.ts#L69), [name: 'Show Slide Preview',](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-Plugin.ts#L75), [name: 'Reload Slide Preview',](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-Plugin.ts#L81), [name: 'Stop Slide Preview Server',](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-Plugin.ts#L92), [name: 'Start Slide Preview Server',](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-Plugin.ts#L97), [.setTitle('Print Presentation')](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/reveal/revealPreviewView.ts#L55)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[this.app.workspace.detachLeavesOfType(REVEAL_PREVIEW_VIEW);](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-Plugin.ts#L230), [this.app.workspace](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-Plugin.ts#L253-L255)
Do not detach leaves with your custom view here, this is an antipattern, see: <https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Don't+detach+leaves+in+%60onunload%60>
Instead, only create a new leaf, if there is not one already.

[containerEl.createEl('h2', { text: 'General settings' });](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-SettingTab.ts#L35)
[Don't use a "general" heading in your settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[containerEl.createEl('h2', { text: 'Slide Settings' });](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-SettingTab.ts#L149), [containerEl.createEl('h2', { text: 'Plugins' });](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-SettingTab.ts#L225-L226)
For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```


[containerEl.createEl('h2', { text: 'Slide Settings' });](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-SettingTab.ts#L149)
[Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

[Suggest.ts](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/obsidian/suggesters/Suggest.ts)
This file should no longer be used, implement a `AbstractInputSuggest` instead.

---

[Copyright (c) 2016](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/plugin/reveal.js-elapsed-time-bar/LICENSE#L3)
Not entirely sure if you can find the original source, but if you can, fix this copyright.

**Comment by ebullient** [comment]
> [Copyright (c) 2016](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/plugin/reveal.js-elapsed-time-bar/LICENSE#L3) Not entirely sure if you can find the original source, but if you can, fix this copyright.

This is not how copyrights work, especially as I don't own the original. The _first_ date is the one that matters, not the last.

**Comment by ebullient** [comment]
- [ ] ["description": "Create markdown-based presentations using reveal.js in Obsidian",](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/manifest.json#L6) The description should not include the word "Obsidian"
- [ ] ["minAppVersion": "0.16.0",](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/manifest.json#L5) You are using newer API's, set this to the latest public build number.
- [ ] [id: 'open-slides-extended-preview',](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-Plugin.ts#L74), [id: 'reload-slides-extended-preview',](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-Plugin.ts#L80), [id: 'stop-server-slides-extended-preview',](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-Plugin.ts#L91), [id: 'start-server-slides-extended-preview',](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-Plugin.ts#L96) Don't include the plugin id in the command id, Obsidian will make sure that there are no conflicts with other plugins.
- [ ] [this.addRibbonIcon('slides', 'Show Slide Preview', async () => {](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-Plugin.ts#L69), [name: 'Show Slide Preview',](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-Plugin.ts#L75), [name: 'Reload Slide Preview',](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-Plugin.ts#L81), [name: 'Stop Slide Preview Server',](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-Plugin.ts#L92), [name: 'Start Slide Preview Server',](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-Plugin.ts#L97), [.setTitle('Print Presentation')](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/reveal/revealPreviewView.ts#L55) [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)
- [ ] [this.app.workspace.detachLeavesOfType(REVEAL_PREVIEW_VIEW);](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-Plugin.ts#L230), [this.app.workspace](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-Plugin.ts#L253-L255) Do not detach leaves with your custom view here, this is an antipattern, see: https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Don't+detach+leaves+in+%60onunload%60 Instead, only create a new leaf, if there is not one already.
- [ ] [containerEl.createEl('h2', { text: 'General settings' });](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-SettingTab.ts#L35) [Don't use a "general" heading in your settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)
- [ ] [containerEl.createEl('h2', { text: 'Slide Settings' });](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-SettingTab.ts#L149), [containerEl.createEl('h2', { text: 'Plugins' });](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-SettingTab.ts#L225-L226)
    > ```ts
    > new Setting(containerEl).setName('name here').setHeading();
    > ``` 
- [ ] [containerEl.createEl('h2', { text: 'Slide Settings' });](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/advancedSlides-SettingTab.ts#L149) [Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

- [ ] [Suggest.ts](https://github.com/ebullient/obsidian-slides-extended/blob/526eef72acbc0867ca0d1d06b6ba0651211878b8/src/obsidian/suggesters/Suggest.ts) This file should no longer be used, implement a `AbstractInputSuggest` instead.

**Comment by joethei** [comment]
> This is not how copyrights work, especially as I don't own the original. The first date is the one that matters, not the last.
I flagged this because there is no name associated with that copyright, which could be the author of the original plugin messing up, but alas that is not the case.
Anyway, just ignore that one.

**Pull request merged**
