### PR TITLE
Add plugin: Cloud Atlas

### PR DESCRIPTION
**Pull request by muness**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/cloud-atlas-ai/obsidian-client/

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by muness** [comment]
Applied the changes. Will close and reopen to trigger a new scan.

**Comment by joethei** [comment]
["version": "0.9.0beta",](https://github.com/cloud-atlas-ai/obsidian-client/blob/5b287927599ded7cf243880a57a903d2cdb7cbff/manifest.json#L4)
Don't use a beta release here.

["description": "Interoperability between Obsidian and Cloud Atlas",](https://github.com/cloud-atlas-ai/obsidian-client/blob/5b287927599ded7cf243880a57a903d2cdb7cbff/manifest.json#L6)
And what features does it offer?
Avoid the word "Obsidian" in descriptions.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[let noticeTimeout: NodeJS.Timeout;](https://github.com/cloud-atlas-ai/obsidian-client/blob/5b287927599ded7cf243880a57a903d2cdb7cbff/src/main.ts#L70)
You should use a regular `number` here and call the `window.setTimeout` function where this is used.

[const response = await fetch(](https://github.com/cloud-atlas-ai/obsidian-client/blob/5b287927599ded7cf243880a57a903d2cdb7cbff/src/main.ts#L483), and more
Use the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

[name: `Run Canvas Flow`,](https://github.com/cloud-atlas-ai/obsidian-client/blob/5b287927599ded7cf243880a57a903d2cdb7cbff/src/main.ts#L962), [name: `Run ${flow} Flow`,](https://github.com/cloud-atlas-ai/obsidian-client/blob/5b287927599ded7cf243880a57a903d2cdb7cbff/src/main.ts#L998)
"Flow" should be lowercase.

[containerEl.createEl("h2", { text: "OpenAI" });](https://github.com/cloud-atlas-ai/obsidian-client/blob/5b287927599ded7cf243880a57a903d2cdb7cbff/src/settings.ts#L81), [containerEl.createEl("h2", { text: "AzureAI" });](https://github.com/cloud-atlas-ai/obsidian-client/blob/5b287927599ded7cf243880a57a903d2cdb7cbff/src/settings.ts#L117), [containerEl.createEl("h2", { text: "Cloud Atlas" });](https://github.com/cloud-atlas-ai/obsidian-client/blob/5b287927599ded7cf243880a57a903d2cdb7cbff/src/settings.ts#L171), [containerEl.createEl("h2", { text: "LLM" });](https://github.com/cloud-atlas-ai/obsidian-client/blob/5b287927599ded7cf243880a57a903d2cdb7cbff/src/settings.ts#L229), [containerEl.createEl("h2", { text: "Wikify" });](https://github.com/cloud-atlas-ai/obsidian-client/blob/5b287927599ded7cf243880a57a903d2cdb7cbff/src/settings.ts#L314), [containerEl.createEl("h2", { text: "Canvas Flows" });](https://github.com/cloud-atlas-ai/obsidian-client/blob/5b287927599ded7cf243880a57a903d2cdb7cbff/src/settings.ts#L319)
For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```

[const contents = readFileSync(`${basePath}/${path}`);](https://github.com/cloud-atlas-ai/obsidian-client/blob/5b287927599ded7cf243880a57a903d2cdb7cbff/src/utils.ts#L96)
Use the `readBinary` function from the Obsidian API instead.



----
Optional changes:

[import { randomUUID } from "crypto";](https://github.com/cloud-atlas-ai/obsidian-client/blob/5b287927599ded7cf243880a57a903d2cdb7cbff/src/canvas.ts#L1)
Use a different dependency to generate UUID's and together with some of the changes above, the plugin should be mobile compatible.

**Comment by durch** [comment]
> 
> Optional changes:
> 
> [import { randomUUID } from "crypto";](https://github.com/cloud-atlas-ai/obsidian-client/blob/5b287927599ded7cf243880a57a903d2cdb7cbff/src/canvas.ts#L1) Use a different dependency to generate UUID's and together with some of the changes above, the plugin should be mobile compatible.

@joethei what are the requirements for this to be mobile compatible, would something like [uuid](https://www.npmjs.com/package/uuid) work, do we need it to be browser compatible, `wasm` compatible or something else  to satisfy the mobile requirement?

**Comment by muness** [comment]
@joethei review feedback addressed, thank you!

**Comment by muness** [comment]
Thanks for the review, @liamcain , requests implemented in 1.0.0 https://github.com/cloud-atlas-ai/obsidian-client/releases/tag/1.0.0

**Comment by joethei** [comment]
Could you please rebase this pr?

**Comment by muness** [comment]
> Could you please rebase this pr?

done!

**Pull request merged**
