### PR TITLE
Add plugin: Watched-Metadata

### PR DESCRIPTION
**Pull request by NailAhmed**
## Repo URL

Link to my plugin: [Watched Metadata Plugin](https://github.com/NailAhmed/Watched-Metadata.git)

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
- [x] GitHub release name matches the exact version number specified in my manifest.json (_Note: Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at [Obsidian Developer Policies](https://docs.obsidian.md/Developer+policies), and have assessed my plugin's adherence to these policies.
- [x] I have read the tips in [Plugin Guidelines](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines) and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using. I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by NailAhmed** [comment]
@ObsidianReviewBot

Hello! I have addressed all the requested changes:

- Removed unsafe `innerHTML` and `outerHTML` usage.
- Moved inline styles to a separate CSS file.

Could you please review my PR again? Thank you!

**Comment by joethei** [comment]
The data.json file should be removed from the repo.

["authorUrl": "",](https://github.com/NailAhmed/Watched-Metadata/blob/e6b2006e0d978db24d2999435336b9d8a9980245/manifest.json#L9)
This needs to be filled, if you don't have a website use your GitHub profile url.

["fundingUrl": "",](https://github.com/NailAhmed/Watched-Metadata/blob/e6b2006e0d978db24d2999435336b9d8a9980245/manifest.json#L10)
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link remove this line.

["styles": "styles.css"](https://github.com/NailAhmed/Watched-Metadata/blob/e6b2006e0d978db24d2999435336b9d8a9980245/manifest.json#L12)
That's not a part of the manifest spec, remove it.

[const headerTab = tabsEl.createEl("button", { text: "Header Groups" });](https://github.com/NailAhmed/Watched-Metadata/blob/e6b2006e0d978db24d2999435336b9d8a9980245/main.ts#L181), [const commandTab = tabsEl.createEl("button", { text: "Command Groups", cls: "mod-setting-tab" });](https://github.com/NailAhmed/Watched-Metadata/blob/e6b2006e0d978db24d2999435336b9d8a9980245/main.ts#L182), [containerEl.createEl("h2", { text: "Header Replacement Groups" });](https://github.com/NailAhmed/Watched-Metadata/blob/e6b2006e0d978db24d2999435336b9d8a9980245/main.ts#L217), [containerEl.createEl("h2", { text: "Header Replacement Groups" });](https://github.com/NailAhmed/Watched-Metadata/blob/e6b2006e0d978db24d2999435336b9d8a9980245/main.ts#L217), [const addHeaderGroupButton = containerEl.createEl("button", { text: "Add Header Group" });](https://github.com/NailAhmed/Watched-Metadata/blob/e6b2006e0d978db24d2999435336b9d8a9980245/main.ts#L223), [containerEl.createEl("h2", { text: "Command Execution Groups" });](https://github.com/NailAhmed/Watched-Metadata/blob/e6b2006e0d978db24d2999435336b9d8a9980245/main.ts#L238), [const addCommandGroupButton = containerEl.createEl("button", { text: "Add Command Group" });](https://github.com/NailAhmed/Watched-Metadata/blob/e6b2006e0d978db24d2999435336b9d8a9980245/main.ts#L244), [.setName(`Header Group ${index + 1}`)](https://github.com/NailAhmed/Watched-Metadata/blob/e6b2006e0d978db24d2999435336b9d8a9980245/main.ts#L262), [const removeButton = groupEl.createEl("button", { text: "Remove Group", cls: "mod-warning" });](https://github.com/NailAhmed/Watched-Metadata/blob/e6b2006e0d978db24d2999435336b9d8a9980245/main.ts#L286), [.setName(`Command Group ${index + 1}`)](https://github.com/NailAhmed/Watched-Metadata/blob/e6b2006e0d978db24d2999435336b9d8a9980245/main.ts#L301), [const removeButton = groupEl.createEl("button", { text: "Remove Group", cls: "mod-warning" });](https://github.com/NailAhmed/Watched-Metadata/blob/e6b2006e0d978db24d2999435336b9d8a9980245/main.ts#L326)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)


[containerEl.createEl("h2", { text: "Header Replacement Groups" });](https://github.com/NailAhmed/Watched-Metadata/blob/e6b2006e0d978db24d2999435336b9d8a9980245/main.ts#L217), [containerEl.createEl("h2", { text: "Command Execution Groups" });](https://github.com/NailAhmed/Watched-Metadata/blob/e6b2006e0d978db24d2999435336b9d8a9980245/main.ts#L238)
For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```

**Comment by NailAhmed** [comment]
All required changes have been made. Please review the updates.

**Comment by joethei** [comment]
[.heading-h2](https://github.com/NailAhmed/Watched-Metadata/blob/80a28ff0433d81df62c6856ff8284683be4f3f54/styles.css#L7-L10)
Please don't change the styling of settings headings.

**Comment by NailAhmed** [comment]
I have removed the custom styling from the settings headings as requested. The .heading-h2 class and related styles have been eliminated from main.ts and styles.css.

Please review the changes and let me know if anything else is needed.

Thank you!

**Comment by joethei** [comment]
Please fix that typo in your repo

**Comment by NailAhmed** [comment]
Hi,

I have fixed the plugin ID mismatch issue. The `id` in `manifest.json` is now corrected from `wathced-metadata` to `watched-metadata`. The latest GitHub release also includes this fix.

Please review the changes and let me know if anything else is needed.

Thank you!

**Comment by NailAhmed** [comment]
Hi,

I have fixed the plugin ID mismatch issue. The id in manifest.json is now corrected from wathced-metadata to watched-metadata. The latest GitHub release also includes this fix.

Please review the changes and let me know if anything else is needed.

Thank you!

**Comment by NailAhmed** [comment]
@joethei, hello! I have fixed the issue you pointed out and updated the PR. Please take another look when you have the time. Thank you for your help!

**Pull request merged**
