### PR TITLE
Add Obsidian Plugin Manager plugin

### PR DESCRIPTION
**Pull request by ohm-en**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/ohm-en/obsidian-plugin-manager

## Release Checklist
- [X] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS [Awaiting Mac user feedback]
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.org describes the plugin's purpose and provides clear usage instructions. [Could be improved upon though.]
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Please include your source code in the repository, not just in the releases.

**Comment by ohm-en** [comment]
Hey @joethei, I appreciate the note. I've added a tangled version of the code to the repository in `.obsidian/plugins/src/main.js`. This was compiled from the README.org file using org-babel-tangle. And yes, this is everything. I am not currently transpiling from any other source aside from my literate document, README.org.

See commit [here](https://github.com/ohm-en/obsidian-plugin-manager/commit/4f3a50fdebad70b3e15286ed9f95c92b9dc9ae94).

**Comment by ericaxu** [comment]
Hi @ohm-en , can you fix the errors please?

**Comment by joethei** [comment]
Sorry for taking so long to review this.

["description": "Extends plugin management of Obsidian.MD",](https://github.com/ohm-en/obsidian-plugin-manager/blob/c6416af8958aa05cea0c254f8e46517b8c163493/manifest.json#L6)
We have recently published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This is a plugin for Obsidian" in your description.

[MySettingTab](https://github.com/ohm-en/obsidian-plugin-manager/blob/c6416af8958aa05cea0c254f8e46517b8c163493/README.org#L227)
You should rename this.

**Pull request merged**
