### PR TITLE
Add James Lemony's theme

### PR DESCRIPTION
**Pull request by JamesLemony**
https://github.com/JamesLemony/obsidian_vibrant/tree/main

### CODE REVIEW

**Comment by ericaxu** [comment]
Hi James, `demo1` doesn't seem to be an PNG file, could you double check that please?

**Comment by JamesLemony** [comment]
Sorry for that. Because I was running Linux, everything worked flawlessly even though there was no file extension. Now, the file is an proper PNG file!

**Comment by ericaxu** [comment]
Great! 

One minor thing: you might want to make the screenshot smaller while keeping the 16:9 aspect ratio. That would make your theme load faster in the theme store. You can still include high resolution screenshots in your README.

We recommend using a screenshot of size 512px by 288px as the featured screenshot to minimize loading time.

**Comment by JamesLemony** [comment]
I have added a smaller resolution file as you have requested. Now demo1.png is a 512*288px. I am sorry, this is my first time for something like this. I hope I am not taking your time too much.

**Pull request merged**
