### PR TITLE
Add chat-stream plugin

### PR DESCRIPTION
**Pull request by rpggio**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/rpggio/obsidian-chat-stream

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[export const sleep = (ms: number) => new Promise(r => setTimeout(r, ms))](https://github.com/rpggio/obsidian-chat-stream/blob/63ab53fec86f43853856f379774cbf37384c5473/src/utils.ts#L10)
Obsidian already exports a function with the same name that does the same thing.

**Comment by marcusolsson** [comment]
[if (!requireApiVersion("1.1.10")) {](https://github.com/rpggio/obsidian-chat-stream/blob/e2d42bafab29bc58166fe7dc2310809de0512915/src/ChatStreamPlugin.ts#L25-L28)
This should be handled by the `versions.json`. 

[containerEl.createEl("h3", {](https://github.com/rpggio/obsidian-chat-stream/blob/e2d42bafab29bc58166fe7dc2310809de0512915/src/settings/SettingsTab.ts#L25-L27)
https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.

[.setName('Max Response Tokens')](https://github.com/rpggio/obsidian-chat-stream/blob/e2d42bafab29bc58166fe7dc2310809de0512915/src/settings/SettingsTab.ts#L88)
https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI

**Comment by rpggio** [comment]
The guideline issues above have been addressed in the latest release.

**Comment by marcusolsson** [comment]
Could you address the issues above (and I'll merge this)?

**Comment by rpggio** [comment]
[Latest release](https://github.com/rpggio/obsidian-chat-stream/releases/tag/1.2.2) is good to go.
Thanks, Marcus!

**Pull request merged**
