### PR TITLE
Add Typing Assistant

### PR DESCRIPTION
**Pull request by Jambo2018**
add  a new plugin named 'Typing Assistant' 

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Jambo2018/notion-assistant-plugin

## Release Checklist
- [X] I have tested the plugin on
  - [X]  Windows
  - [X]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by ericaxu** [comment]
Hi @Jambo2018 , did you resolve the code review comments?

**Comment by Jambo2018** [comment]
> did you resolve the code review comments

Yes, I have done my best to improve all the details mentioned in the review comments and also resolved the code conflicts in JSON by the way

**Comment by joethei** [comment]
[MyPlugin](https://github.com/Jambo2018/notion-assistant-plugin/blob/47d2706eb3942fffcacf26138ac5c668901fb25f/main.ts#L9)
Rename this class,

[this.app.workspace.on("active-leaf-change", () => {](https://github.com/Jambo2018/notion-assistant-plugin/blob/47d2706eb3942fffcacf26138ac5c668901fb25f/main.ts#L219)
Don't forget to register this event: https://docs.obsidian.md/Plugins/Events

[contentEl.createEl("h1", { text: "Insert A Link Bookmark" });](https://github.com/Jambo2018/notion-assistant-plugin/blob/47d2706eb3942fffcacf26138ac5c668901fb25f/src/link-input-modal.ts#L22)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[export const debounce = (fn: Function, delay: number) => {](https://github.com/Jambo2018/notion-assistant-plugin/blob/47d2706eb3942fffcacf26138ac5c668901fb25f/src/util.ts#L62-L71)
Obsidian already includes a function with this name & functionality.

**Comment by Jambo2018** [comment]
> [MyPlugin](https://github.com/Jambo2018/notion-assistant-plugin/blob/47d2706eb3942fffcacf26138ac5c668901fb25f/main.ts#L9) Rename this class,
> 
> [this.app.workspace.on("active-leaf-change", () => {](https://github.com/Jambo2018/notion-assistant-plugin/blob/47d2706eb3942fffcacf26138ac5c668901fb25f/main.ts#L219) Don't forget to register this event: https://docs.obsidian.md/Plugins/Events
> 
> [contentEl.createEl("h1", { text: "Insert A Link Bookmark" });](https://github.com/Jambo2018/notion-assistant-plugin/blob/47d2706eb3942fffcacf26138ac5c668901fb25f/src/link-input-modal.ts#L22) [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)
> 
> [export const debounce = (fn: Function, delay: number) => {](https://github.com/Jambo2018/notion-assistant-plugin/blob/47d2706eb3942fffcacf26138ac5c668901fb25f/src/util.ts#L62-L71) Obsidian already includes a function with this name & functionality.

I have completed the modifications based on the feedback, please review again

**Comment by liamcain** [comment]
- [scrollArea?.addEventListener](https://github.com/Jambo2018/notion-assistant-plugin/blob/323c1d832d7f430fe4bd31d423588b36586e3543/main.ts#L239) this will add a new eventlistener every time the view gets focused. This means switching between tabs will cause more and more event listeners to be created.
- [document.body.appendChild(this.menu);](https://github.com/Jambo2018/notion-assistant-plugin/blob/323c1d832d7f430fe4bd31d423588b36586e3543/src/command-menu.ts#L88) these are never cleaned up either
- [this.commands = new CommandMenu](https://github.com/Jambo2018/notion-assistant-plugin/blob/323c1d832d7f430fe4bd31d423588b36586e3543/main.ts#L230) this approach doesn't really make sense since you're going to continue creating more and more commandMenus every time the user switches between tabs.

**Comment by Jambo2018** [comment]
> * [scrollArea?.addEventListener](https://github.com/Jambo2018/notion-assistant-plugin/blob/323c1d832d7f430fe4bd31d423588b36586e3543/main.ts#L239) this will add a new eventlistener every time the view gets focused. This means switching between tabs will cause more and more event listeners to be created.
> * [document.body.appendChild(this.menu);](https://github.com/Jambo2018/notion-assistant-plugin/blob/323c1d832d7f430fe4bd31d423588b36586e3543/src/command-menu.ts#L88) these are never cleaned up either
> * [this.commands = new CommandMenu](https://github.com/Jambo2018/notion-assistant-plugin/blob/323c1d832d7f430fe4bd31d423588b36586e3543/main.ts#L230) this approach doesn't really make sense since you're going to continue creating more and more commandMenus every time the user switches between tabs.

Thank you, I did overlook the issue of singletons. I have resolved the issue of duplicate menu creation under multiple tabs and repositioned the menu. Could you please review it

**Comment by liamcain** [comment]
Looks better!

**Pull request merged**
