### PR TITLE
Add global-search-and-replace

### PR DESCRIPTION
**Pull request by MahmoudFawzyKhalil**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/MahmoudFawzyKhalil/obsidian-global-search-and-replace/

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[id: "snr-search-and-replace",](https://github.com/MahmoudFawzyKhalil/obsidian-global-search-and-replace/blob/11fb0133bec35823b2737852e7c70aa7f1e4cf4d/src/main.ts#L22)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

[this.app = app;](https://github.com/MahmoudFawzyKhalil/obsidian-global-search-and-replace/blob/11fb0133bec35823b2737852e7c70aa7f1e4cf4d/src/domain/file-operator.ts#L22)
It's highly discouraged that you use the global app instance in your plugin. It's currently accessible from the global context for debugging purposes, and might be removed in the future. Instead, you should use the reference to App that you have from your plugin instance.

**Comment by MahmoudFawzyKhalil** [comment]
Thanks for reviewing my PR.

I created a new release (0.1.1) addressing these comments.

**Comment by MahmoudFawzyKhalil** [comment]
Thank you for merging and for the suggestions. 

I worry with `cachedRead()` if I get a stale result and get the matching range from that result if that would cause me to modify the file in an unintended way?

**Comment by liamcain** [comment]
That's true. The main issue though is that the file could still change between the search and the replace action. So it might make sense to use cachedRead when doing the previewing, and read (as in re-reading the file) when doing the actual replacement.

**Pull request merged**
