### PR TITLE
Code::Stats

### PR DESCRIPTION
**Pull request by Miskamyasa**
# I am submitting a new Community Plugin

The [Code::Stats](https://codestats.net/) plugin for Obsidian allows you to track your coding progress and earn XP for writing markdown in the Obsidian editor. With this plugin, you can send XP data to your Code::Stats account.

## Repo URL

[Link to plugin repo](https://github.com/Miskamyasa/obsidian-codestats)

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Miskamyasa** [comment]
Reopen after conflicts

**Comment by joethei** [comment]
["id": "codestats-obsidian",](https://github.com/Miskamyasa/obsidian-codestats/blob/59e7e23b67bc2ed355535bf497cddc3d970af4a1/manifest.json#L2)
Remove `obsidian` from this.

["description": "Code::Stats (https://codestats.net) plugin for Obsidian (https://obsidian.md)",]
Please use the description you submitted here.

[ id: 'open-codestats-key-modal',](https://github.com/Miskamyasa/obsidian-codestats/blob/59e7e23b67bc2ed355535bf497cddc3d970af4a1/src/main.ts#L27)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include `codestats` here.

**Comment by Miskamyasa** [comment]
> ["id": "codestats-obsidian",](https://github.com/Miskamyasa/obsidian-codestats/blob/59e7e23b67bc2ed355535bf497cddc3d970af4a1/manifest.json#L2) Remove `obsidian` from this.
> 
> ["description": "Code::Stats (https://codestats.net) plugin for Obsidian (https://obsidian.md)",] Please use the description you submitted here.
> 
> [ id: 'open-codestats-key-modal',](https://github.com/Miskamyasa/obsidian-codestats/blob/59e7e23b67bc2ed355535bf497cddc3d970af4a1/src/main.ts#L27) Obsidian will automatically prefix the command id with the plugin id, you don't need to include `codestats` here.

Done

**Comment by Miskamyasa** [comment]
> * [this.addCommand](https://github.com/Miskamyasa/obsidian-codestats/blob/29e218e84579af7ebfff1755c5ff87b056d14d92/src/main.ts#L26) I'm not sure this command is necessary. You can already configure the API key from the Settings tab, you might want to just get rid of the APIKeyModal entirely. It's not adding much benefit.
> 
>     * [registerDomEvent](https://github.com/Miskamyasa/obsidian-codestats/blob/29e218e84579af7ebfff1755c5ff87b056d14d92/src/main.ts#L42) you might want to listen for "editor-change" instead (https://github.com/obsidianmd/obsidian-api/blob/583ba39e3f6c0546de5e5e8742256a60e2d78ebc/obsidian.d.ts#L4277) that way you are only listening to actual modifications and not things like using Search or Command palette, etc.
> 
>     * [statusBarItemEl](https://github.com/Miskamyasa/obsidian-codestats/blob/29e218e84579af7ebfff1755c5ff87b056d14d92/src/main.ts#L36) This statusbar element is not doing anything. Did you mean to hook it up to show some stats?

Using "registerDomEvent" is a great idea, i'll use it, but else are blocking issues?

**Comment by liamcain** [comment]
Your plugin doesn't pass validation because if the id mismatch. It won't be installable until that is fixed.

**Pull request closed without merging**
