### PR TITLE
Add Feather Theme

### PR DESCRIPTION
**Pull request by MFdev-coder**
# I am submitting a new community theme

## Repo URL
Link to my theme : https://github.com/mfdev-coder/obsidian-feather

## Theme Checklist

- [x] -  My repo contains all required files (please _do not_ add them to this `obsidian-releases` repo).
    - [x]  `manifest.json`
    - [x]  `theme.css`
    - [x]  The screenshot file (16:9 aspect ratio, recommended size is 512px by 288px for fast loading).
- [x]  I have indicated which modes (dark, light, or both) are compatible with my theme.
- [x]  I have added a license in the LICENSE file.
- [x]  My project respects and is compatible with the original license of any code from other themes that I'm using. I have given proper attribution to these other themes in my `README.md`.

### CODE REVIEW

**Comment by lishid** [comment]
This isn't the place to advertise for your theme, so you don't need to format it nicely. You can advertise it in other places once it gets merged into the repo. And please don't close and create new PRs - stick to this one, you can edit it.

Also please follow the instructions on using the checklist template. See what other theme submissions look like:
https://github.com/obsidianmd/obsidian-releases/pull/2087

**Comment by MFdev-coder** [comment]
I think I've done everything right but, if there are any mistakes please let me know

**Comment by joethei** [comment]
You have not, please follow the below,

> Also please follow the instructions on using the checklist template. See what other theme submissions look like:
https://github.com/obsidianmd/obsidian-releases/pull/2087

**Comment by MFdev-coder** [comment]
I think it should work now .

###### sorry for the inconvenience 🙂

**Pull request merged**
