### PR TITLE
Add Daily Notes Viewer Plugin

### PR DESCRIPTION
**Pull request by Johnson0907**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Johnson0907/obsidian-daily-notes-viewer

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/Johnson0907/obsidian-daily-notes-viewer/blob/dd893fc30d180b231e54ee5f53490096339e486e/src/index.ts#L59
You should make sure that `createOrUpdateViewer` is debounced, so you don't end up doing it multiple times per second when a series of events happen close together.

**Comment by lishid** [comment]
https://github.com/Johnson0907/obsidian-daily-notes-viewer/blob/dd893fc30d180b231e54ee5f53490096339e486e/src/util.ts#L53
I also suggest doing a `cachedRead` here and only write the file if it has changed - this would avoid an extra disk write.

**Comment by Johnson0907** [comment]
The source code has been updated.

**Comment by lishid** [comment]
https://github.com/Johnson0907/obsidian-daily-notes-viewer/blob/720f6e48acef67f40fd9784fcb231be0a52d6087/src/index.ts#L59
This is incorrect - and it doesn't work. You need to create the function itself as debounced, and from here you just need to call the debounced function.

https://github.com/Johnson0907/obsidian-daily-notes-viewer/blob/720f6e48acef67f40fd9784fcb231be0a52d6087/src/util.ts#L50
Here you are creating the string `${beginning}\n${fileText}` three times - should set it into a variable first (before the if-else condition) and reuse the variable.

**Comment by Johnson0907** [comment]
Thanks for your guidance, the source code has been updated.

**Comment by lishid** [comment]
Hmmmm

https://github.com/Johnson0907/obsidian-daily-notes-viewer/blob/c65798ebcdeed0355b2ca8405ad637f85fa6dc51/src/index.ts#L101
That's still not quite it - you're creating a timer variable here that's always 0, and then clearing that, which doesn't have an effect. But we are getting close.

You need to do this:

```ts
delayCreateOrUpdateViewer = debounce(() => createOrUpdateViewer(this.app, this.settings), 1000);
```

**Comment by Johnson0907** [comment]
I've updated the source code, but I'm not sure if it's correct. Please check it out. Thanks again.

**Comment by lishid** [comment]
You can import `debounce` from `obsidian`.

**Comment by Johnson0907** [comment]
Thanks for the reminder, I have updated the source code.

**Comment by lishid** [comment]
Hmm ok looks good to merge. One last thing I think we should improve - the plugin's description says: "Help you to review your daily notes like in roam research"

I think a lot of users may not know what that means (or haven't used Roam), so perhaps change the description so it better explain what this plugin exactly does instead?

**Comment by lishid** [comment]
The description is also in this PR so let me know when you get it changed and I can have it merged!

**Pull request merged**
