### PR TITLE
Add Ticktick

### PR DESCRIPTION
**Pull request by viduycheung**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/viduycheung/ticktick-obsidian

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
What is TickTick, how does one use your plugin?
Please create a proper readme.

[id: "ticktick-create-task",](https://github.com/viduycheung/ticktick-obsidian/blob/7e0a4249b90b883f7d3acd11d71bdcc403d1ab48/main.ts#L56)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

[callback: () => {](https://github.com/viduycheung/ticktick-obsidian/blob/7e0a4249b90b883f7d3acd11d71bdcc403d1ab48/main.ts#L58)
Use a `editorCallback` here: https://docs.obsidian.md/Plugins/User+interface/Commands#Editor+commands

[containerEl.createEl("h2", { text: "Settings for TickTick Plugin" });](https://github.com/viduycheung/ticktick-obsidian/blob/7e0a4249b90b883f7d3acd11d71bdcc403d1ab48/main.ts#L335)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by viduycheung** [comment]
https://github.com/viduycheung/ticktick-obsidian/commits/1.0.0

**Comment by viduycheung** [comment]
> Your command only does something if there is a active editor avaiable, so it makes sense to move it to a editorCallback Also, add an error message if the user is not logged in.

The command can allow you to create a task without editor info when no active editor is available

https://github.com/obsidianmd/obsidian-releases/assets/53415256/e19deb6b-0f6d-45fb-9c6d-1dcddffd1f5d

and it has notice when triggering the command that the user is not login

https://github.com/obsidianmd/obsidian-releases/assets/53415256/281f2363-4a2d-4ede-8319-c478ccc871ec

**Comment by liamcain** [comment]
- [isDesktopOnly](https://github.com/viduycheung/ticktick-obsidian/blob/199f5eeb7e2df3fbe60990349c1d8e569c8236a3/manifest.json#L10) Your plugin won't run on mobile since we don't use electron. You won't have access to electron/remote so the import will fail.
- [registerInterval](https://github.com/viduycheung/ticktick-obsidian/blob/199f5eeb7e2df3fbe60990349c1d8e569c8236a3/main.ts#L79) UX: you might want to make this optional behind a user setting.

**Comment by viduycheung** [comment]
> * [isDesktopOnly](https://github.com/viduycheung/ticktick-obsidian/blob/199f5eeb7e2df3fbe60990349c1d8e569c8236a3/manifest.json#L10) Your plugin won't run on mobile since we don't use electron. You won't have access to electron/remote so the import will fail.
> * [registerInterval](https://github.com/viduycheung/ticktick-obsidian/blob/199f5eeb7e2df3fbe60990349c1d8e569c8236a3/main.ts#L79) UX: you might want to make this optional behind a user setting.

done

**Pull request merged**
