### PR TITLE
Add plugin: Evernote Decryptor

### PR DESCRIPTION
**Pull request by rcmdnk**
Add Evernote Decryptor plugin

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/rcmdnk/obsidian-evernote-decryptor

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "Obsidian Plugin for encrypted data imported from Evernote.",](https://github.com/rcmdnk/obsidian-evernote-decryptor/blob/4fc4e776e22b66f51d9938d576089760282f8837/manifest.json#L6)
Avoid including sentences like "Plugin for Obsidian that ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[import { pbkdf2Sync, createHmac, timingSafeEqual, createDecipheriv } from 'crypto';](https://github.com/rcmdnk/obsidian-evernote-decryptor/blob/4fc4e776e22b66f51d9938d576089760282f8837/src/CryptoUtils.ts#L1)
These imports are only available from a Node.js runtime, which means that this will throw errors on Mobile (that's a problem since you have `isDesktopOnly` marked as `false` in your manifest.json file.

**Comment by rcmdnk** [comment]
@joethei 
Thanks for the comment.
The description was fixed
and isDesktopOnly is set to false in the plugin repository.

**Comment by liamcain** [comment]
- [if (e.key === 'Enter') {](https://github.com/rcmdnk/obsidian-evernote-decryptor/blob/504045d2a8aece7e000361a1c3342a36e283480d/src/PasswordModal.ts#L22) you should add e.preventDefault() to ensure the "enter" doesn't trigger anything else in the app.

**Comment by rcmdnk** [comment]
@liamcain 
Thanks.
`e.preventDefault()` was implemented in new release (1.0.1).

**Pull request merged**
