### PR TITLE
Add plugin: RPG Stat Tracker

### PR DESCRIPTION
**Pull request by name**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/name/obsidian-rpg

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
- [x] I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by name** [comment]
Damn. I'll fix these tomorrow.

**Comment by name** [comment]
image

**Comment by name** [comment]
Removed 'main.js' and updated the .gitignore, thanks!

**Comment by joethei** [comment]
[containerEl.createEl('h3', { text: 'RPG settings' });](https://github.com/name/obsidian-rpg/blob/8ac869a15c4246fa2b931b4c713523c61d63fcd8/main.ts#L96)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[.setName('Reset XP and level')](https://github.com/name/obsidian-rpg/blob/8ac869a15c4246fa2b931b4c713523c61d63fcd8/main.ts#L123-L133)
This should be a button, not a toggle.

---

[lastLoad: number;](https://github.com/name/obsidian-rpg/blob/8ac869a15c4246fa2b931b4c713523c61d63fcd8/main.ts#L4), [lastLoad: Date.now(),](https://github.com/name/obsidian-rpg/blob/8ac869a15c4246fa2b931b4c713523c61d63fcd8/main.ts#L14), [this.settings.lastLoad = Date.now();](https://github.com/name/obsidian-rpg/blob/8ac869a15c4246fa2b931b4c713523c61d63fcd8/main.ts#L32)
What is this used for?

**Comment by name** [comment]
Thanks, I've made the relevant amendments.

The 'lastLoad: number;, lastLoad: Date.now(),, this.settings.lastLoad = Date.now();' were going to be for another feature, but it's not ytet added so I've stripped them out for the time being.

**Pull request merged**
