### PR TITLE
Add plugin: Tiff Viewer

### PR DESCRIPTION
**Pull request by ullmannJan**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/ullmannJan/obsidian-tiff-viewer/

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by ullmannJan** [comment]
I implemented everything. Maybe this triggers the bot to reevaluate?

**Comment by joethei** [comment]
It looks like there are 11 pieces of feedback that have not been implemented yet.
The bot will only do stuff once all of them are implemented.

**Comment by ullmannJan** [comment]
ok, but I think I corrected all those mistakes. I noticed that the bot is not correctly identifying the console.log statements but is narrowing it down in several problems. So problems [4-8] in the console.log section belong to the same console.log statement. But probably the bot only flags one of them as resolved. What should I do?

**Comment by joethei** [comment]
Ah, let me check and make those then

**Comment by joethei** [comment]
["description": "View .tif(f) files in Obsidian by generating duplicates in form of .tif(f).png",](https://github.com/ullmannJan/obsidian-tiff-viewer/blob/d54b01087feff3cb4566c10acbea4fcc461add2e/manifest.json#L6)
Remove the `in Obsidian` part, it should be obvious that this is for Obsidian.

[if (file.name === tiffFilePath) {](https://github.com/ullmannJan/obsidian-tiff-viewer/blob/d54b01087feff3cb4566c10acbea4fcc461add2e/src/SuperModal.ts#L69)
Use the `getFirstLinkpathDest` function instead: <https://docs.obsidian.md/Reference/TypeScript+API/MetadataCache/getFirstLinkpathDest>

**Comment by ullmannJan** [comment]
Thanks, everything is implemented.

**Pull request merged**
