### PR TITLE
Add plugin: Nexus AI Chat Importer

### PR DESCRIPTION
**Pull request by Superkikim**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Superkikim/nexus-ai-chat-importer

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[Copyright (c) 2023 [Your Name or Your Organization's Name]](https://github.com/Superkikim/nexus-ai-chat-importer/blob/378044759bf7d5bbb7431d02abd24722f6095992/LICENSE.md#L3)
Fill this and update the year.

["manifest": "manifest.json",](https://github.com/Superkikim/nexus-ai-chat-importer/blob/378044759bf7d5bbb7431d02abd24722f6095992/manifest.json#L7), ["dependencies": [],](https://github.com/Superkikim/nexus-ai-chat-importer/blob/378044759bf7d5bbb7431d02abd24722f6095992/manifest.json#L8), ["themeSupport": false,](https://github.com/Superkikim/nexus-ai-chat-importer/blob/378044759bf7d5bbb7431d02abd24722f6095992/manifest.json#L10), ["license": "MIT"](https://github.com/Superkikim/nexus-ai-chat-importer/blob/378044759bf7d5bbb7431d02abd24722f6095992/manifest.json#L13)
Not a valid part of the manifest, remove this.

["description": "A plugin to import AI Chat conversations exports.",](https://github.com/Superkikim/nexus-ai-chat-importer/blob/378044759bf7d5bbb7431d02abd24722f6095992/manifest.json#L12)
Avoid including sentences like "This is a plugin that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.


[this.settings = {](https://github.com/Superkikim/nexus-ai-chat-importer/blob/378044759bf7d5bbb7431d02abd24722f6095992/src/main.ts#L66-L72)
Don't initialize the settings object in the constructor, it's already being initialized correctly in `onload`

[name: "Reset Catalogs",](https://github.com/Superkikim/nexus-ai-chat-importer/blob/378044759bf7d5bbb7431d02abd24722f6095992/src/main.ts#L205), ["Open Link", // Title](https://github.com/Superkikim/nexus-ai-chat-importer/blob/378044759bf7d5bbb7431d02abd24722f6095992/src/main.ts#L315), [.setName("Nexus AI Chat Importer Folder")](https://github.com/Superkikim/nexus-ai-chat-importer/blob/378044759bf7d5bbb7431d02abd24722f6095992/src/main.ts#L1059), [.setName("Add Date Prefix to Filenames")](https://github.com/Superkikim/nexus-ai-chat-importer/blob/378044759bf7d5bbb7431d02abd24722f6095992/src/main.ts#L1072), [.setName("Date Format")](https://github.com/Superkikim/nexus-ai-chat-importer/blob/378044759bf7d5bbb7431d02abd24722f6095992/src/main.ts#L1087), [content += this.generateTable("Created Notes", this.created, "✨", [](https://github.com/Superkikim/nexus-ai-chat-importer/blob/378044759bf7d5bbb7431d02abd24722f6095992/src/main.ts#L1243), [content += this.generateTable("Updated Notes", this.updated, "🔄", [](https://github.com/Superkikim/nexus-ai-chat-importer/blob/378044759bf7d5bbb7431d02abd24722f6095992/src/main.ts#L1251), [content += this.generateTable("Skipped Notes", this.skipped, "⏭️", [](https://github.com/Superkikim/nexus-ai-chat-importer/blob/378044759bf7d5bbb7431d02abd24722f6095992/src/main.ts#L1259), [content += this.generateTable("Failed Imports", this.failed, "🚫", [](https://github.com/Superkikim/nexus-ai-chat-importer/blob/378044759bf7d5bbb7431d02abd24722f6095992/src/main.ts#L1267)


[await this.app.vault.adapter.remove(](https://github.com/Superkikim/nexus-ai-chat-importer/blob/378044759bf7d5bbb7431d02abd24722f6095992/src/main.ts#L978-L980)
Don't just delete this file, the better approach would be:
```ts
await this.saveData(DEFAULT_SETTINGS);
```

[const response = await fetch(url, { method: "HEAD" });](https://github.com/Superkikim/nexus-ai-chat-importer/blob/378044759bf7d5bbb7431d02abd24722f6095992/src/utils.ts#L163)
Use the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

[importing conversations with your favorite AI chat application](https://github.com/Superkikim/nexus-ai-chat-importer/blob/378044759bf7d5bbb7431d02abd24722f6095992/README.md#L10)
Your code is only for ChatGPT, so this sentence is wrong.

**Comment by Superkikim** [comment]
Hi @joethei , 

Thx for the great and clear feedback. It's appreciated. You quoted the below lines, but there are no recommendation. Did you miss something I need to improve ? 

> [name: "Reset Catalogs",](https://github.com/Superkikim/nexus-ai-chat-importer/blob/378044759bf7d5bbb7431d02abd24722f6095992/src/main.ts#L205), ["Open Link", // Title](https://github.com/Superkikim/nexus-ai-chat-importer/blob/378044759bf7d5bbb7431d02abd24722f6095992/src/main.ts#L315), [.setName("Nexus AI Chat Importer Folder")](https://github.com/Superkikim/nexus-ai-chat-importer/blob/378044759bf7d5bbb7431d02abd24722f6095992/src/main.ts#L1059), [.setName("Add Date Prefix to Filenames")](https://github.com/Superkikim/nexus-ai-chat-importer/blob/378044759bf7d5bbb7431d02abd24722f6095992/src/main.ts#L1072), [.setName("Date Format")](https://github.com/Superkikim/nexus-ai-chat-importer/blob/378044759bf7d5bbb7431d02abd24722f6095992/src/main.ts#L1087), [content += this.generateTable("Created Notes", this.created, "✨", , [content += this.generateTable("Updated Notes", this.updated, "🔄", , [content += this.generateTable("Skipped Notes", this.skipped, "⏭️", , [content += this.generateTable("Failed Imports", this.failed, "🚫",

All other changed have been applied.

Cheers

**Comment by joethei** [comment]
The visible text should use sentence case.

**Comment by Superkikim** [comment]
Thank you. All changes applied.

Cheers

Akim

**Pull request merged**
