### PR TITLE
Add plugin: Continuous Mode

### PR DESCRIPTION
**Pull request by gasparschott**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

https://github.com/gasparschott/obsidian-continuous-mode

## Release Checklist
- [X] I have tested the plugin on
  - [ ]  Windows
  - [X]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by gasparschott** [comment]
Error fixed, all requested changes made.

**Comment by liamcain** [comment]
- [leafArrowNavigation](https://github.com/gasparschott/obsidian-continuous-mode/blob/79da545424219e92cef717ee76d7d5877b6f9432/main.js#L109) I think you're missing a check to see if a property is in focus.
- [rearranged](https://github.com/gasparschott/obsidian-continuous-mode/blob/79da545424219e92cef717ee76d7d5877b6f9432/main.js#L101) this is not a safe way to rearrange the elements. There's a utility function that we provide in the Obsidian API: [setChildrenInPlace](https://github.com/obsidianmd/obsidian-api/blob/bbb696aeb8bf5126bf2ecbf84fc8284fe133bc20/obsidian.d.ts#L51C9-L51C27) that should help for rearranging the elements efficiently.

**Comment by gasparschott** [comment]
Thanks, I'll look into these issues.

**Comment by gasparschott** [comment]
Requested changes made (I believe).

**Comment by gasparschott** [comment]
Bump.

**Pull request merged**
