### PR TITLE
Add plugin: Interactive Code Blocks

### PR DESCRIPTION
**Pull request by ernstbolt**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [x ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [x ] `main.js`
  - [x ] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x ] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x ] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x ] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x ] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x ] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x ] I have added a license in the LICENSE file.
- [x ] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["name": "Windesheim's Interactive Code Blocks",](https://github.com/Windesheim-HBO-ICT/Obsidian-Interactive-Code-Block-Plugin/blob/67b45dd1858f2836b35944518b51518b77161a13/manifest.json#L3), ["description": "Preview Windeheim's interactive code block in obsidian!",](https://github.com/Windesheim-HBO-ICT/Obsidian-Interactive-Code-Block-Plugin/blob/67b45dd1858f2836b35944518b51518b77161a13/manifest.json#L6)
I don't see a reason to include the name "Windesheim" in the name & description.
Also please don't include "Obsidian" in the description.

[script.src = "https://cdn.jsdelivr.net/gh/windesheim-hbo-ict/deeltaken@latest/CodeBlock/codeBlockLite.js"](https://github.com/Windesheim-HBO-ICT/Obsidian-Interactive-Code-Block-Plugin/blob/67b45dd1858f2836b35944518b51518b77161a13/main.ts#L8)
This should not be loaded externally, but bundled into the plugin, including all of it's dependencies.
Also, that external dependency is setting `innerHTML` in a lot of places, without the need to.
A bunch of strings are also in dutch, while the plugin readme is in english.

Also, it's not documented that your plugin only works in reading mode, please add that.

**Comment by joethei** [comment]
[<style>](https://github.com/Windesheim-HBO-ICT/Obsidian-Interactive-Code-Block-Plugin/blob/598554e73761165bf7208bbd32f38563bd8cac17/codeBlockLite.js#L53-L124)
This should be in the `styles.css` file, not loaded via innerHTML.

[<div class="flexCol">](https://github.com/Windesheim-HBO-ICT/Obsidian-Interactive-Code-Block-Plugin/blob/598554e73761165bf7208bbd32f38563bd8cac17/codeBlockLite.js#L125-L139)
And this should also not be using innerHTML.
Please see our guidelines: <https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%60innerHTML%60%2C+%60outerHTML%60+and+%60insertAdjacentHTML%60>

[await fetch('http://localhost:8080/code', {](https://github.com/Windesheim-HBO-ICT/Obsidian-Interactive-Code-Block-Plugin/blob/598554e73761165bf7208bbd32f38563bd8cac17/codeBlockLite.js#L177)
Use the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

**Comment by ItsSiem** [comment]
I've removed the last innerHTML uses. The styles can not be moved to the styles.css file because they are used within the shadowDOM of the webcomponent.

**Comment by joethei** [comment]
[console.log(output);](https://github.com/Windesheim-HBO-ICT/Obsidian-Interactive-Code-Block-Plugin/blob/09a6d38213824f0e2817aa1581c91ec24c29083d/codeBlockLite.js#L292)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

**Comment by ItsSiem** [comment]
I have removed the `console.log`

**Pull request merged**
