### PR TITLE
Note content pusher

### PR DESCRIPTION
**Pull request by lizard-heart**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/lizard-heart/obsidian-note-content-pusher

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lizard-heart** [comment]
Thank you for the feedback. I have resolved the changes suggested in the newest release.

**Comment by liamcain** [comment]
[var filesWithName](https://github.com/lizard-heart/obsidian-note-content-pusher/blob/13b1eeb3867611c651c046beafa121c127e3789a/src/main.ts#L103) you still have many instances of `var`. You can just replace all instances of `var` with `let`. In javascript, `var` has some often unintended behavior, so it's almost always a better idea to use `let`.

> https://github.com/lizard-heart/obsidian-note-content-pusher/blob/b8ac45708a00e7afdd3f6b7feddca032756a80f8/src/main.ts#L95-L125 you should be able to simplify all of this code by just using [getFirstLinkpathDest](https://github.com/obsidianmd/obsidian-api/blob/9bb30633586c6649474b2affdf5b87efdd86498f/obsidian.d.ts#L2075). You'll be able to find the best file match without having to loop through all of the files yourself.

It looks like this wasn't addressed. Did you run into issues using [getFirstLinkpathDest](https://github.com/obsidianmd/obsidian-api/blob/9bb30633586c6649474b2affdf5b87efdd86498f/obsidian.d.ts#L2075)?

**Comment by lizard-heart** [comment]
Yes, I wasn't able to get `getFirstLinkpathDest` to work with exactly the behavior I wanted. I have updated the newest release (1.0.4) to change all instances of `var` to `let`.

**Comment by liamcain** [comment]
Hi, I'm really sorry for such a long wait getting this merged! This pull request slipped through the cracks and I didn't see your last comment about it being ready for re-review.

**Pull request merged**
