### PR TITLE
added obsidian-list-modified

### PR DESCRIPTION
**Pull request by franciskafieh**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/franciskafieh/obsidian-list-modified

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/franciskafieh/obsidian-list-modified/blob/bbd60aeb42a2f113a9495a477e1f14180af68e62/src/main.ts#L42
This isn't needed since you already registered the event with the component system.

https://github.com/franciskafieh/obsidian-list-modified/blob/bbd60aeb42a2f113a9495a477e1f14180af68e62/src/main.ts#L51
You can just use `this.app` here.

https://github.com/franciskafieh/obsidian-list-modified/blob/bbd60aeb42a2f113a9495a477e1f14180af68e62/src/main.ts#L85
Possible race condition here. You read the file into a class-shared field, and fire off a function with no parameters. What if another modify event happens at the same time? Your modify events aren't awaited for by anything, therefore they are all ran concurrently. This means there's a chance something happens here and the reference to `dailyFileContent`, `dailyFileCache`, `activeFileCache`, and `dailyFile` gets changed from another run of the modify function.

At the very least, you should use function-scope variables and pass them around to various helper functions, to ensure you're always dealing with the same set of files. For better safety, you should also serialize your `modify` event handlers so at most one is running at any time (You can use a promise-based queue where you always await for the last execution with `prevPromise.then(nextCallback, nextCallback)` ).

https://github.com/franciskafieh/obsidian-list-modified/blob/bbd60aeb42a2f113a9495a477e1f14180af68e62/src/main.ts#L57
You shouldn't cast here - instead you should do an `instanceof` check.

**Comment by franciskafieh** [comment]
All these issues should be fixed. feel free to let me know if there's anything else you would like me to do! thanks so much!!

**Comment by lishid** [comment]
https://github.com/franciskafieh/obsidian-list-modified/blob/9490de023fdd762d5d00fee5bd2285b3c6c46a74/src/main.ts#L74
This is quite inefficient because this function will go through every single link in the whole vault. You should use `MetadataCache.resolvedLinks` instead to check for connectedness between two notes.

**Comment by franciskafieh** [comment]
Will fix, thanks!

**Pull request merged**
