### PR TITLE
Add plugin: Active note to window title

### PR DESCRIPTION
**Pull request by jplattel**
This plugin sets the window title to include the current open note

### CODE REVIEW

**Comment by lishid** [comment]
Maybe restore the original window title on unload?

**Comment by jplattel** [comment]
Oh that's a good one, will fix that! :)

**Comment by liamcain** [comment]
@jplattel you'll need to rebase

**Comment by jplattel** [comment]
Ugh, doing this in the Github interfaces results in the whole file being rewritten.. I'll just open a new one..

**Pull request closed without merging**
