### PR TITLE
Add plugin: Fight Note

### PR DESCRIPTION
**Pull request by Loac**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Loac/obsidian-fight-note

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["fundingUrl": "",](https://github.com/Loac/obsidian-fight-note/blob/57d951ef35145a0bdb5cd5cfe0241b2011035f58/manifest.json#L9)
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link remove this line.

[export async function loadFont(): Promise<void> {](https://github.com/Loac/obsidian-fight-note/blob/57d951ef35145a0bdb5cd5cfe0241b2011035f58/src/fight-note.ts#L14-L24)
The font should be loaded from CSS as a base64 encoded data uri.

**Comment by Loac** [comment]
> The font should be loaded from CSS as a base64 encoded data uri.

I dumb. Forgot that the font can be load by CSS. Fix it. Please, check release 1.0.1.

**Comment by OpTi9** [comment]
Damn, good job dude! Your plugin looks way cooler and complete than mine ;)

**Comment by Loac** [comment]
Thanks!

**Pull request merged**
