### PR TITLE
add Obsidian TikZJax

### PR DESCRIPTION
**Pull request by artisticat1**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/artisticat1/obsidian-tikzjax

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by liamcain** [comment]
- [this.registerEvent(this.app.workspace.on("window-open", (win, window) => {](https://github.com/artisticat1/obsidian-tikzjax/blob/72411dfb93390c5d372da8906ed34e898e718408/main.ts#L19-L21) Obsidian should copy over all `<script>` elements from the parent window, so I don't think it's necessary to add special handling here for popout windows

**Comment by artisticat1** [comment]
> Obsidian should copy over all `<script>` elements from the parent window, so I don't think it's necessary to add special handling here for popout windows. Let me know if that's not the behavior you're seeing though.

I see! I'm not seeing my plugin's `<script>` get copied over into new windows that are opened; the plugin only works in popout windows if I add this "window-open" listener. I'm running v0.16.2 if that helps.

**Comment by liamcain** [comment]
Do you mind rebasing this pull request and I can merge it?

**Comment by liamcain** [comment]
@artisticat1 do you mind rebasing this pull request and moving your plugin entry to the bottom of the list? We use the list order to establish the "release order" when sorting plugins in the plugin gallery.

**Comment by artisticat1** [comment]
I accidentally closed this PR, but I opened another one here. [https://github.com/obsidianmd/obsidian-releases/pull/1174](https://github.com/obsidianmd/obsidian-releases/pull/1174)

**Pull request closed without merging**
