### PR TITLE
Add plugin: Recently Added Files

### PR DESCRIPTION
**Pull request by Lemon695**
> # I am submitting a new Community Plugin
> ## Repo URL
> Link to my plugin:
> https://github.com/Lemon695/obsidian-recently-added-files
> 
> ## Release Checklist
> * [x]  I have tested the plugin on
>   
>   * [ ]   Windows
>   * [x]   macOS
>   * [ ]   Linux
>   * [ ]   Android _(if applicable)_
>   * [x]   iOS _(if applicable)_
> * [x]  My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
>   
>   * [x]  `main.js`
>   * [x]  `manifest.json`
>   * [x]  `styles.css` _(optional)_
> * [x]  GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
> * [x]  该 `id` in my `manifest.json` matches the `id` 在 `community-plugins.json` file.
> * [x]  My README.md describes the plugin's purpose 和 provides clear usage instructions.
> * [x]  I have read the developer policies at https://docs.obsidian.md/Developer+policies, 和 have assessed my plugins's adherence to these policies.
> * [x]  I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
> * [x]  I have added a license in the LICENSE file.
> * [x]  My project respects 和 is compatible with the original license of any code from other plugins that I'm using.
>   I have given proper attribution to these other projects in my `README.md`。

### CODE REVIEW

**Comment by Lemon695** [comment]
Updates have been applied，thank you

**Comment by Lemon695** [comment]
@ObsidianReviewBot I've fixed the issues

**Comment by joethei** [comment]
[# Obsidian New Files](https://github.com/Lemon695/obsidian-new-files/blob/616268a827bad274dcd862794a07ddfd8884e10a/README.md#L1)
Naming something "Obsidian xyz" is reserved for first party products we create, please change this header.

["minAppVersion": "1.0.0",](https://github.com/Lemon695/obsidian-new-files/blob/616268a827bad274dcd862794a07ddfd8884e10a/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

[return 'New Files';](https://github.com/Lemon695/obsidian-new-files/blob/616268a827bad274dcd862794a07ddfd8884e10a/src/main.ts#L88)
[Avoid "options" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings) 

[id: 'new-files-open',](https://github.com/Lemon695/obsidian-new-files/blob/616268a827bad274dcd862794a07ddfd8884e10a/src/main.ts#L311)
Don't prefix the command id with the plugin id, Obsidian will make sure that there are no conflicts with other plugins.

[((this.app.workspace as unknown) as WorkspaceWithHoverSource).unregisterHoverLinkSource(](https://github.com/Lemon695/obsidian-new-files/blob/616268a827bad274dcd862794a07ddfd8884e10a/src/main.ts#L364-L366)
This is not needed, Obsidian does that automatically when a plugin is unloaded.

**Comment by Lemon695** [comment]
@joethei I have released a v1.0.5 according to your suggestions, thank you

> [# Obsidian New Files](https://github.com/Lemon695/obsidian-new-files/blob/616268a827bad274dcd862794a07ddfd8884e10a/README.md#L1) Naming something "Obsidian xyz" is reserved for first party products we create, please change this header.
> 
> ["minAppVersion": "1.0.0",](https://github.com/Lemon695/obsidian-new-files/blob/616268a827bad274dcd862794a07ddfd8884e10a/manifest.json#L5) You are using newer API's, set this to the latest public build number.
> 
> [return 'New Files';](https://github.com/Lemon695/obsidian-new-files/blob/616268a827bad274dcd862794a07ddfd8884e10a/src/main.ts#L88) [Avoid "options" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)
> 
> [id: 'new-files-open',](https://github.com/Lemon695/obsidian-new-files/blob/616268a827bad274dcd862794a07ddfd8884e10a/src/main.ts#L311) Don't prefix the command id with the plugin id, Obsidian will make sure that there are no conflicts with other plugins.
> 
> [((this.app.workspace as unknown) as WorkspaceWithHoverSource).unregisterHoverLinkSource(](https://github.com/Lemon695/obsidian-new-files/blob/616268a827bad274dcd862794a07ddfd8884e10a/src/main.ts#L364-L366) This is not needed, Obsidian does that automatically when a plugin is unloaded.

**Comment by joethei** [comment]
[interface WorkspaceWithHoverSource extends Workspace {](https://github.com/Lemon695/obsidian-recently-added-files/blob/f2fbbd458bc38e01adcc80c575eb88568908621c/src/main.ts#L34-L42), 
Use the `registerHoverLinkSource` function that is public on the Plugin class.

[return '';](https://github.com/Lemon695/obsidian-recently-added-files/blob/f2fbbd458bc38e01adcc80c575eb88568908621c/src/main.ts#L72)
There needs to be something here.

**Comment by Lemon695** [comment]
> [interface WorkspaceWithHoverSource extends Workspace {](https://github.com/Lemon695/obsidian-recently-added-files/blob/f2fbbd458bc38e01adcc80c575eb88568908621c/src/main.ts#L34-L42), Use the `registerHoverLinkSource` function that is public on the Plugin class.
> 
> [return '';](https://github.com/Lemon695/obsidian-recently-added-files/blob/f2fbbd458bc38e01adcc80c575eb88568908621c/src/main.ts#L72) There needs to be something here.

@joethei I have released v1.0.6 to fix the use of the `registerHoverLinkSource` function, thank you

**Pull request merged**
