### PR TITLE
New Plugin: Folder Index

### PR DESCRIPTION
**Pull request by turulix**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/turulix/obsidian-folder-index

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/turulix/obsidian-folder-index/blob/8d9bfadc01dbb3c252c32326f6a5bc70750799b6/src/modules/FolderNoteModule.ts#L27
Here you should check whether `evt.target instanceof HTMLElement` and if not just return.

https://github.com/turulix/obsidian-folder-index/blob/8d9bfadc01dbb3c252c32326f6a5bc70750799b6/src/main.ts#L34
You should unload the `folderNodeModule` in your onunload.

https://github.com/turulix/obsidian-folder-index/blob/8d9bfadc01dbb3c252c32326f6a5bc70750799b6/src/modules/FolderNoteModule.ts#L82
activeLeaf might be null or it might be pinned, instead you should use `getLeaf()`.

https://github.com/turulix/obsidian-folder-index/blob/8d9bfadc01dbb3c252c32326f6a5bc70750799b6/src/modules/FolderNoteModule.ts#L109
Be careful here because this event is fired for every file and folder inside a nesting structure when you rename the top-level folder.

https://github.com/turulix/obsidian-folder-index/blob/8d9bfadc01dbb3c252c32326f6a5bc70750799b6/src/main.ts#L35
Good effort on reverse engineering the graph module! I think given the way you're overwriting the graph could be problematic with future updates though.

I would suggest having the graph component disabled by default and making the setting a global killswitch to not even load the graph related things.

**Comment by turulix** [comment]
Thank  you for the suggestions. I will fix them when i have time  :)

**Comment by turulix** [comment]
The problems should be fixed now :)

**Comment by lishid** [comment]
https://github.com/turulix/obsidian-folder-index/blob/8962faf7b72254dc558a3e27e8ec9a3594f6d661/src/main.ts#L65
Missing a null check for graphManipulator here. Otherwise everything else looks good!

**Comment by lishid** [comment]
Oh before I merge, you need to move your plugin to be the last item in the list.

**Comment by turulix** [comment]
All done :)

**Pull request merged**
