### PR TITLE
Add plugin: PlotManager

### PR DESCRIPTION
**Pull request by dldisud**
I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/dldisud/obsidian-plotmanager

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[name: 'Create Plot Point',](https://github.com/dldisud/obsidian-plotmaster/blob/6951ec7a99ed1373ba69eb0ef37a4d10db14e2a1/main.js#L26), [name: 'Create Character',](https://github.com/dldisud/obsidian-plotmaster/blob/6951ec7a99ed1373ba69eb0ef37a4d10db14e2a1/main.js#L32), [plotPointsEl.createEl('h3', { text: 'Plot Points' });](https://github.com/dldisud/obsidian-plotmaster/blob/6951ec7a99ed1373ba69eb0ef37a4d10db14e2a1/main.js#L111), [visualizationEl.createEl('h3', { text: 'Story Visualization' });](https://github.com/dldisud/obsidian-plotmaster/blob/6951ec7a99ed1373ba69eb0ef37a4d10db14e2a1/main.js#L199)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[return 'plotmaster-view';](https://github.com/dldisud/obsidian-plotmaster/blob/6951ec7a99ed1373ba69eb0ef37a4d10db14e2a1/main.js#L99)
Remove `-view`

**Comment by dldisud** [comment]
Please check it out

**Comment by joethei** [comment]
['Plot Points' → 'Plot points'](https://github.com/dldisud/obsidian-plotmaster/blob/b47abd2f35c2b01be9ef4c1ab5006b8ed3268ef7/main.js#L31-L57)
Remove this text, this is not valid in a JavaScript file.

**Comment by dldisud** [comment]
Please check it out

**Comment by dldisud** [comment]
Please check it out

**Comment by dldisud** [comment]
Please check it out

**Comment by dldisud** [comment]
hello?..

**Comment by dldisud** [comment]
> ["description": "플롯 작성을 위한 최고의 도구",](https://github.com/dldisud/obsidian-plotmaster/blob/704a87abba5cbe27f158f9b6d1f7e96470e4a9b8/manifest.json#L6) 순위를 암시하는 단어를 사용하지 마세요. 여기에 따라야 할 플러그인 설명에 대한 가이드를 게시했습니다: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
> 
> [if (!( await vault.adapter.exists(folderPath))) {](https://github.com/dldisud/obsidian-plotmaster/blob/704a87abba5cbe27f158f9b6d1f7e96470e4a9b8/main.js#L52), [const workName = this.promptForWorkName()을 기다립니다;](https://github.com/dldisud/obsidian-plotmaster/blob/704a87abba5cbe27f158f9b6d1f7e96470e4a9b8/main.js#L68-L71), [const characterPath = ;](https://github.com/dldisud/obsidian-plotmaster/blob/704a87abba5cbe27f158f9b6d1f7e96470e4a9b8/main.js#L108) [사용자 정의 경로를 정리하는 데 사용합니다.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+%60normalizePath()%60+to+clean+up+user-defined+paths)
> 
> [plotPointsEl.createEl('h5', { text: '플롯 포인트' });](https://github.com/dldisud/obsidian-plotmaster/blob/704a87abba5cbe27f158f9b6d1f7e96470e4a9b8/main.js#L303) [UI에서 문장 대/소문자 사용](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)
> 
> [addImprovedVisualizationStyles() {](https://github.com/dldisud/obsidian-plotmaster/blob/704a87abba5cbe27f158f9b6d1f7e96470e4a9b8/main.js#L329-L370) 이것은 코드를 통해 로드되지 않고 파일에 있어야 합니다.`styles.css`

I modified it, but when will you check it?

**Comment by dldisud** [comment]
Please tell me if I'm wrong if I'm wrong if I'm right if I'm wrong. I'm frustrated because I haven't said anything for days and there's no response even if I modify the code.

**Pull request closed without merging**
