### PR TITLE
Add Directive Athena Documentation

### PR DESCRIPTION
**Pull request by DirectiveAthena**
# I am submitting a new Community Theme

## Repo URL

Link to my theme: https://github.com/DirectiveAthena/Documentation_Theme

## Theme checklist

- [x] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo)
  - [x] `obsidian.css`
  - [x] The screenshot file
- [x] I have indicated which modes (dark, light, or both) are compatible with my theme
- [x] I have added a license in the LICENSE file
- [x] If my repo is not using the `master` branch, please indicate in `community-themes.json` with `"branch": "main"`.

### CODE REVIEW

**Comment by ericaxu** [comment]
Hi there, thanks for your submission! For the screenshot, could you take a screenshot of Obsidian the app after applying your theme, please? Thanks!

**Comment by DirectiveAthena** [comment]
Okay, no problem. 
I have updated the example.png to be a view of the theme in obsidian.
Is there anything else I need to add?

**Comment by DirectiveAthena** [comment]
> Hi there, thanks for your submission! For the screenshot, could you take a screenshot of Obsidian the app after applying your theme, please? Thanks!

**Comment by DirectiveAthena** [comment]
Sorry, I miss clicked!
Github didn't give me a warning and it auto closed. I am very sorry

**Comment by lishid** [comment]
@ericaxu Anything blocking this?

**Comment by ericaxu** [comment]
> Sorry, I miss clicked! Github didn't give me a warning and it auto closed. I am very sorry

No worries!

The theme seems very specific though; or maybe I missed something that the screenshot didn't showcase. There wasn't much info in the README though. If you can give us some background on the project that would be a lot better, things like what motivated you to make this theme and what's the goal of it.

You can check out some recently merged themes for examples.

**Comment by DirectiveAthena** [comment]
Oh yeah I fully understand it.
I am making a full documentation for a list of applications (front- and backend) that I am making for my own story development software. The documentation is currently on github in a public repo (https://github.com/DirectiveAthena/Documentation). 
The reason I made my own theme, and not use another from the community is because I gave myself this whole mantra of "If I can do it myself, I'm going to try and do it myself" for the entire project I am creating from scratch.

I was actually pointed here by the Obsidian Members Group Discord server, as I had asked a question there, involving me having the entire .obsidian folder in that documentation repo, and somewhere feeling this was not the way to go. This way people could choose if they use the theme or not.

The theme itself is set up in a way that with a simple cssclass in the YAML, the entire page is styled in a way that corresponds to the colour scheme of that application's logo

I can give you some more pictures too:
image
image
image

I know Obsidian themselves also has an option to host your documentation, but I don't have a lot of spare money laying around, therefor the Documentation itself is currently on github. I plan on eventually doing this through Obsidian, in the future though.

I hope this explained it a bit more, and if there is any other information I need to provide, I'll try to answer as quick as I can.

**Comment by ericaxu** [comment]
Thank you, that does answer my question. Seems like it's more about functionality than the looks which was why I didn't get it. Overall it looks too similar to the default dark theme but I see where you coming from now.

I think it fits more into the future snippet collection/store, rather than the theme store we have right now. If you're not in a rush to submit, maybe you can wait a bit for that to happen? The snippet store is more intended for functional snippets like this.

**Comment by DirectiveAthena** [comment]
> Thank you, that does answer my question. Seems like it's more about functionality than the looks which was why I didn't get it. Overall it looks too similar to the default dark theme but I see where you coming from now.
> 
> I think it fits more into the future snippet collection/store, rather than the theme store we have right now. If you're not in a rush to submit, maybe you can wait a bit for that to happen? The snippet store is more intended for functional snippets like this.

Okay sure! From the sounds of it, it does indeed fit the snippets stuff a bit more. Will wait until that comes out, and in the mean time find another solution to share this along my documentation

**Pull request closed without merging**
