### PR TITLE
Add typewriter mode plugin

### PR DESCRIPTION
**Pull request by davisriedel**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/davisriedel/obsidian-typewriter-mode

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[protected override commandTitle = "Toggle Typewriter Scrolling On/Off";](https://github.com/davisriedel/obsidian-typewriter-mode/blob/a72e9f2656ab5bc2fa360d5d37b25e0b57e497fc/src/features/TypewriterScroll.ts#L9)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by sigrunixia** [comment]
Hi @davisriedel! Have you had a chance to make the first set of changes requested?

**Comment by davisriedel** [comment]
Hey @sigrunixia, yes, I changed all the ui labels in the new version [https://github.com/davisriedel/obsidian-typewriter-mode](https://github.com/davisriedel/obsidian-typewriter-mode). Do I have to do something else in this PR?

**Comment by sigrunixia** [comment]
> Hey @sigrunixia, yes, I changed all the ui labels in the new version [davisriedel/obsidian-typewriter-mode](https://github.com/davisriedel/obsidian-typewriter-mode). Do I have to do something else in this PR?

Nope! I didn't see an extra commit after the comments so just making sure they were in. :) You are good to be reviewed.

**Pull request merged**
