### PR TITLE
Add plugin: Metadata Auto Classifier

### PR DESCRIPTION
**Pull request by GoBeromsu**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/GoBeromsu/Metadata-Auto-Classifier

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by GoBeromsu** [comment]
I moved css properties to style.css :)

[refactor : move css property to css files · GoBeromsu/Metadata-Auto-Classifier@8901674](https://github.com/GoBeromsu/Metadata-Auto-Classifier/commit/890167473337842b3c9d9ced1f11f36395c8844e)

**Comment by joethei** [comment]
["fundingUrl": "https://your-funding-url.com",](https://github.com/GoBeromsu/Metadata-Auto-Classifier/blob/d1f909f9e46749e458aa3c7209e9f283af699a0c/manifest.json#L9)
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link remove this line.

[hotkeys: [{ modifiers: ["Mod"], key: "A" }]](https://github.com/GoBeromsu/Metadata-Auto-Classifier/blob/d1f909f9e46749e458aa3c7209e9f283af699a0c/src/main.ts#L36)
We recommend against providing a default hotkey when possible. The reason being that it's easy to pick a hotkey that a user already has configured and they could get confused when that key doesn't do what they expect. Also, it's hard choosing a safe default hotkey that's available for all operating systems & does not conflict with existing plugins.

[const content = await this.app.vault.read(file);](https://github.com/GoBeromsu/Metadata-Auto-Classifier/blob/d1f909f9e46749e458aa3c7209e9f283af699a0c/src/metaDataManager.ts#L75-L77)
Replace this with the below, and remove the `parseFrontMatter` function
```ts
return this.app.metadataCache.getFileCache(file)?.frontmatter?.[key];
```

['Fetch All Tags',](https://github.com/GoBeromsu/Metadata-Auto-Classifier/blob/d1f909f9e46749e458aa3c7209e9f283af699a0c/src/setting/tagSetting.ts#L27), ['Number of Options to Select',](https://github.com/GoBeromsu/Metadata-Auto-Classifier/blob/d1f909f9e46749e458aa3c7209e9f283af699a0c/src/setting/frontmatterSettings.ts#L21), [.setName('Frontmatter Name')](https://github.com/GoBeromsu/Metadata-Auto-Classifier/blob/d1f909f9e46749e458aa3c7209e9f283af699a0c/src/setting/frontmatterSettings.ts#L31), [.setName('API Provider')](https://github.com/GoBeromsu/Metadata-Auto-Classifier/blob/d1f909f9e46749e458aa3c7209e9f283af699a0c/src/setting/apiSetting.ts#L23), [.setName('API Key')](https://github.com/GoBeromsu/Metadata-Auto-Classifier/blob/d1f909f9e46749e458aa3c7209e9f283af699a0c/src/setting/apiSetting.ts#L41), [.setName('Max Tokens')](https://github.com/GoBeromsu/Metadata-Auto-Classifier/blob/d1f909f9e46749e458aa3c7209e9f283af699a0c/src/setting/apiSetting.ts#L78)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[containerEl.createEl('h3', { text: 'Tag Settings' });](https://github.com/GoBeromsu/Metadata-Auto-Classifier/blob/d1f909f9e46749e458aa3c7209e9f283af699a0c/src/setting/tagSetting.ts#L7), [containerEl.createEl('h2', { text: 'Tag Settings' });](https://github.com/GoBeromsu/Metadata-Auto-Classifier/blob/d1f909f9e46749e458aa3c7209e9f283af699a0c/src/setting/index.ts#L56), [containerEl.createEl('h2', { text: 'Frontmatter Settings' });](https://github.com/GoBeromsu/Metadata-Auto-Classifier/blob/d1f909f9e46749e458aa3c7209e9f283af699a0c/src/setting/index.ts#L72)For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```
and [avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

[console.log('Raw API response:', responseRaw);](https://github.com/GoBeromsu/Metadata-Auto-Classifier/blob/d1f909f9e46749e458aa3c7209e9f283af699a0c/src/api/apiHandler.ts#L21), [console.log('Processed API response:', { resOutput, resReliability });](https://github.com/GoBeromsu/Metadata-Auto-Classifier/blob/d1f909f9e46749e458aa3c7209e9f283af699a0c/src/api/apiHandler.ts#L23)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

**Comment by GoBeromsu** [comment]
I have taken your request!
[Release v1.0.8 · GoBeromsu/Metadata-Auto-Classifier](https://github.com/GoBeromsu/Metadata-Auto-Classifier/releases/tag/v1.0.8)

**Comment by joethei** [comment]
The release name/url cannot contain `v`

**Comment by GoBeromsu** [comment]
Thank you for your answer I changed my version name :)

[Release 1.1.2 · GoBeromsu/Metadata-Auto-Classifier](https://github.com/GoBeromsu/Metadata-Auto-Classifier/releases/tag/1.1.2)

**Comment by GoBeromsu** [comment]
I updated version name :) and refactored few things

[Releases · GoBeromsu/Metadata-Auto-Classifier](https://github.com/GoBeromsu/Metadata-Auto-Classifier/releases)

image

**Comment by GoBeromsu** [comment]
I updated version name :) and refactored few things sir @joethei 

[Releases · GoBeromsu/Metadata-Auto-Classifier](https://github.com/GoBeromsu/Metadata-Auto-Classifier/releases)

image

**Comment by GoBeromsu** [comment]
And, I removed the v in all of release name and tag 

image

**Pull request closed without merging**
