### PR TITLE
Add plugin: Live Variables

### PR DESCRIPTION
**Pull request by HamzaBenyazid**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/HamzaBenyazid/obsidian-live-variables
## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "A plugin that allows you to define variables in your note's properties and reuse them throughout your content.",](https://github.com/HamzaBenyazid/obsidian-live-variables/blob/4a6d2da0310443bfd4581aee3ca050f404dc355e/manifest.json#L6)
Avoid including sentences like "This is a plugin that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[interface LiveVariableSettings {](https://github.com/HamzaBenyazid/obsidian-live-variables/blob/4a6d2da0310443bfd4581aee3ca050f404dc355e/main.ts#L3-L9), [await this.loadSettings();](https://github.com/HamzaBenyazid/obsidian-live-variables/blob/4a6d2da0310443bfd4581aee3ca050f404dc355e/main.ts#L25), [async loadSettings() {](https://github.com/HamzaBenyazid/obsidian-live-variables/blob/4a6d2da0310443bfd4581aee3ca050f404dc355e/main.ts#L85-L89)
You are not making use of settings, remove this.

[name: 'Insert Live Variable',](https://github.com/HamzaBenyazid/obsidian-live-variables/blob/4a6d2da0310443bfd4581aee3ca050f404dc355e/main.ts#L36)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)


[this.app.workspace.on("file-open", (file)=>{](https://github.com/HamzaBenyazid/obsidian-live-variables/blob/4a6d2da0310443bfd4581aee3ca050f404dc355e/main.ts#L28-L32)
This will fail if the user has multiple files open at the same time.

[let file = view.file;](https://github.com/HamzaBenyazid/obsidian-live-variables/blob/4a6d2da0310443bfd4581aee3ca050f404dc355e/main.ts#L41)
This can fail if there is no file present, I would recommend adding a early exit if there is no file in the view

**Comment by HamzaBenyazid** [comment]
Fixed this issues in 1.0.1 release

**Comment by joethei** [comment]
[properties: FrontMatterCache | undefined;](https://github.com/HamzaBenyazid/obsidian-live-variables/blob/8bf132bba8a8dd288c7b833e46f0ff6c9c4ac560/main.ts#L4)
You should not use global variables whenever possible, read here why: http://wiki.c2.com/?GlobalVariablesAreBad

**Comment by HamzaBenyazid** [comment]
Replaced global variables with local variables in release [1.0.2](https://github.com/HamzaBenyazid/obsidian-live-variables/releases/tag/1.0.2)

**Comment by joethei** [comment]
[let properties: FrontMatterCache | undefined;](https://github.com/HamzaBenyazid/obsidian-live-variables/blob/3b829abf8e029fc399e730716ef129ca80982e46/main.ts#L15)
This still acts like a global variable in this context.

**Comment by HamzaBenyazid** [comment]
I think it can't be avoided. I need to store the previous state of the properties and compare it with the new state to know which property is changed and what is the new value, so I need to initialize it on "workspace active-leaf-change" event and use it in "metadataCache changed" event . I can't think of any other way to do this.

**Pull request merged**
