### PR TITLE
Add Locksidian plugin

### PR DESCRIPTION
**Pull request by uthvah**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/SineCrepusculum/locksidian

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "A plugin that adds in-app password protection to your vault.",](https://github.com/SineCrepusculum/locksidian/blob/4b58c908a47c1a1db9d941406be2f8934fed5f08/manifest.json#L6)
We have recently published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "A plugin that" in your description.

["authorUrl": "",](https://github.com/SineCrepusculum/locksidian/blob/4b58c908a47c1a1db9d941406be2f8934fed5f08/manifest.json#L8)
If you don't have a website use your GH profile here.

["fundingUrl": "",](https://github.com/SineCrepusculum/locksidian/blob/4b58c908a47c1a1db9d941406be2f8934fed5f08/manifest.json#L9)
If you don't have one, omit this.

[containerEl.createEl('h2', { text: 'Locksidian Settings' });](https://github.com/SineCrepusculum/locksidian/blob/4b58c908a47c1a1db9d941406be2f8934fed5f08/main.ts#L126)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by SineCrepusculum** [comment]
Any updates?

**Comment by joethei** [comment]
[videoEl.src = 'https://raw.githubusercontent.com/SineCrepusculum/locksidian/main/bg.mp4';](https://github.com/uthvah/locksidian/blob/314caf608018d7174a87cbdcaab6284ce9a19bd3/main.ts#L44)
Plugins should not use remote services unless required for functionality, if you want to include a image you should base64 encode it and include it via CSS, like this example for themes: <https://docs.obsidian.md/Themes/App+themes/Embed+fonts+and+images+in+your+theme>

**Comment by ericaxu** [comment]
Hi there, to keep things tidy, we're going to temporarily close plugin PRs after a month of inactivity.

Feel free to tell us to re-open it when you're ready to continue and we'll reopen the PR right away. Thanks for your understanding!

**Pull request closed without merging**
