### PR TITLE
Add obsidian-echarts plugin.

### PR DESCRIPTION
**Pull request by cumany**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/cumany/obsidian-echarts

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
-[x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by liamcain** [comment]
[//@ts-ignore](https://github.com/cumany/obsidian-echarts/blob/24a1a32eac579f47dff2ae1f107d6a83f286fe58/src/renderer.ts#L135) Why are these 2 ts-ignore's needed?

[params.name](https://github.com/cumany/obsidian-echarts/blob/24a1a32eac579f47dff2ae1f107d6a83f286fe58/src/renderer.ts#L138-L139) Sourcepath shouldn't be the same as the destination path. It should be either the path of the currently active file or `""`.

[search(searchWord)](https://github.com/cumany/obsidian-echarts/blob/24a1a32eac579f47dff2ae1f107d6a83f286fe58/src/renderer.ts#L133-L134) It's also somewhat hacky but you can also do this with:

```ts
this.app.internalPlugins.getPluginById('global-search')?.instance.openGlobalSearch('');
```

[const editor = this.app.workspace.activeLeaf.view.editor](https://github.com/cumany/obsidian-echarts/blob/24a1a32eac579f47dff2ae1f107d6a83f286fe58/src/modal.ts#L28-L29) Using `activeLeaf` is deprecated. Instead, you should use `const view = this.app.workspace.getActiveViewOfType(MarkdownView)`. And then check that view !== null.

[`export default class ChartsCreator`](https://github.com/cumany/obsidian-echarts/blob/24a1a32eac579f47dff2ae1f107d6a83f286fe58/src/chartsCreator.ts#L4) This class doesn't seem very useful. I think you can get rid of it.

**Comment by liamcain** [comment]
Hi @cumany, do you mind rebasing and removing the last 2 commits? There are unwanted changes in them. I can resolve the conflicts for you afterwards.

**Comment by cumany** [comment]
> Hi @cumany, do you mind rebasing and removing the last 2 commits? There are unwanted changes in them. I can resolve the conflicts for you afterwards.

sorry， i revert the commit，I don't know if this is the right way to do it

**Comment by liamcain** [comment]
In the obsidian-releases repo, try running the following:

```sh
git reset --hard HEAD~2
git push -f
```

**Comment by liamcain** [comment]
Looks like you have a typo in your github tag: `0.03`. This should be `0.0.3`.

image

**Comment by cumany** [comment]
> Looks like you have a typo in your github tag: `0.03`. This should be `0.0.3`.
> 
> image

ok  ， i fixed

**Pull request merged**
