### PR TITLE
Add plugin: Status Bar Organizer

### PR DESCRIPTION
**Pull request by Opisek**
# I am submitting a new Community Plugin
This plugin allows easy reordering of elements in the status bar, as well as toggling their visibility, which persists even after restarting Obsidian.

## Repo URL
Link to my plugin:
https://github.com/Opisek/obsidian-statusbar-organizer

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Opisek** [comment]
/skip

**Usage of `var` and `titleSpan.innerHTML = formattedName;`:**
Agreed and fixed. I was going to change the `innerHTML` usage here anyway, and as for the `var`, I have no idea how that slipped through.

**Usage of `innerHTML` elsewhere:**
I disagree with the checks. All the use-cases of `innerHTML` can be broken down to:
- `foo.innerHTML = '';` - poses absolutely no security threat
- `foo.innerHTML = bar.innerHTML;` - not a vulnerability either; if you assume that foo.innerHTML will be malicious after this assignment, then `bar.innerHTML` was already malicious before my plugin even started. Cannot simply be replaced with copying `textContent`, as different plugins structure their status bar elements differently.

**CSS in JS:**
I disagree with the checks. "Styles" are being set in JavaScript to dynamically change the position of elements e.g.
`foo.style.top = bar + "px";`
This is not something that can be moved in CSS.

**Comment by Opisek** [comment]
I changed whatever was applicable. The other suggestions can not be implemented due to reasons stated in my previous comment. I kindly ask for a review. @joethei

**Comment by joethei** [comment]
[statusBar.innerHTML = "";](https://github.com/Opisek/obsidian-statusbar-organizer/blob/bc51306f3b53e141f3f813c75930b1c90e2353d2/main.ts#L119)
Use the `.empty()` function instead.

**Comment by Opisek** [comment]
Done

**Pull request merged**
