### PR TITLE
Add Sync Calendar plugin

### PR DESCRIPTION
**Pull request by dexin-qi**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [obsidian-sync-calendar](https://github.com/dexin-qi/obsidian-sync-calendar)

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
You should make it more obvious that your plugin only works with Google Calendar.

Also, please mention that your plugin relies on the _Dataview_ plugin to be intalled for certain functionality, a user would only find out by a cryptic error message.

What's the reasoning behind the proxy setting?
Obsidian will automatically use the proxy set in the operating system, so this should not be needed.

[.setDesc("Enter how many weeks ago did you concerned.")](https://github.com/dustinksi/obsidian-sync-calendar/blob/ce2791ddd49421e6419d5eec22904c2569014222/main.ts#L277)
This description sounds wrong, you should reword this.

**Comment by dustinksi** [comment]
Thank you for your valuable feedback on my calendar syncing plugin. I have updated the plugin based on your suggestions:

- Added dependency on Dataview plugin to [README](https://github.com/dustinksi/obsidian-sync-calendar/blob/691e9269870b2baa8cf0279d5fcb6350fd875510/README.md?plain=1#L12)
- Update README's [title](https://github.com/dustinksi/obsidian-sync-calendar/blob/691e9269870b2baa8cf0279d5fcb6350fd875510/README.md?plain=1#L1), [Intro](https://github.com/dustinksi/obsidian-sync-calendar/blob/691e9269870b2baa8cf0279d5fcb6350fd875510/README.md?plain=1#L5) and [manifests](https://github.com/dustinksi/obsidian-sync-calendar/blob/691e9269870b2baa8cf0279d5fcb6350fd875510/manifest.json#L6) to clarify that my plugin only works with Google Calendar.
- Removed proxy setting option as it was redundant
- Improved wording of some [descriptions](https://github.com/dustinksi/obsidian-sync-calendar/blob/691e9269870b2baa8cf0279d5fcb6350fd875510/main.ts#L177) on the settings page

The updated plugin has been committed. I appreciate you taking the time to review my plugin and help me improve it.

**Comment by marcusolsson** [comment]
["description": "An Obsidian plugin that synchronizes google events from the calendar and manages them like tasks.",](https://github.com/dustinksi/obsidian-sync-calendar/blob/691e9269870b2baa8cf0279d5fcb6350fd875510/manifest.json#L6)
[Keep plugin descriptions short and simple](https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple), for example "Synchronize events from Google Calendar and manage them like tasks.".

["name": "Sync Calendar",](https://github.com/dustinksi/obsidian-sync-calendar/blob/691e9269870b2baa8cf0279d5fcb6350fd875510/manifest.json#L3)
Are you planning to add support for other calendar services? If not, maybe clarify that it's a plugin specifically for Google Calendar.

Update the settings tab to follow the guidelines for UI text.
[UI text](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#UI+text)

[this.titleEl.innerText = "Calendar Sync Result";](https://github.com/dustinksi/obsidian-sync-calendar/blob/691e9269870b2baa8cf0279d5fcb6350fd875510/modals/syncResult.ts#L16)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[import type { Moment } from 'moment';](https://github.com/dustinksi/obsidian-sync-calendar/blob/691e9269870b2baa8cf0279d5fcb6350fd875510/TodoSerialization/Todo.ts#L1)
Use the moment library in `obsidian` instead.
```ts
import {moment} from 'obsidian';
moment(date).format(format);
```

**Comment by dexin-qi** [comment]
@marcusolsson Thanks for your advice! I've updated the [manifest.json](https://github.com/dexin-qi/obsidian-sync-calendar/blob/main/manifest.json) and followed the guidelines for UI text to update [the settings tabs](https://github.com/dexin-qi/obsidian-sync-calendar/blob/fc8c3e6b387d2a2da78c05136291b8ec7bb3c279/main.ts#L158).

**Comment by liamcain** [comment]
- [ribbonIconEl](https://github.com/dexin-qi/obsidian-sync-calendar/blob/fc8c3e6b387d2a2da78c05136291b8ec7bb3c279/main.ts#L84) you can remove this
- [mannual](https://github.com/dexin-qi/obsidian-sync-calendar/blob/fc8c3e6b387d2a2da78c05136291b8ec7bb3c279/main.ts#L81) typo: 'manual'

**Pull request merged**
