### PR TITLE
Add plugin: I18N

### PR DESCRIPTION
**Pull request by 0011000000110010**
# I am submitting a new Community Plugin
## Repo URL
https://github.com/0011000000110010/obsidian-i18n

Link to my plugin:

## Release Checklist
* [x]  I have tested the plugin on
* [x]   Windows
* [ ]   macOS
* [ ]   Linux
* [ ]   Android _(if applicable)_
* [ ]   iOS _(if applicable)_
* [x]  My GitHub release contains all required files
* [x]  `main.js`
  * [x]  `manifest.json`
  * [x]  `styles.css` _(optional)_
  * [x]  GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
* [x]  该 `id` in my `manifest.json` matches the `id` 在 `community-plugins.json` file.
* [x]  My README.md describes the plugin's purpose and provides clear usage instructions.
* [x]  I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
* [x]  I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
* [x]  I have added a license in the LICENSE file.
* [x]  My project respects and is compatible with the original license of any code from other plugins that I'm using.
  I have given proper attribution to these other projects in my `README.md`。

### CODE REVIEW

**Comment by joethei** [comment]
["description": "To internationalize the Obsidian plugin",](https://github.com/0011000000110010/obsidian-i18n/blob/a42330e9124d2a4b0d28c0ecad9e5a1f9b6414dd/manifest.json#L5)
Remove "Obsidian" from the description, and make sure that the description makes sense in English.
It does not make sense atm because it's talking about a singular undefined plugin.

["authorUrl": "",](https://github.com/0011000000110010/obsidian-i18n/blob/a42330e9124d2a4b0d28c0ecad9e5a1f9b6414dd/manifest.json#L7)
Fill this, if you don't have a website put your GH profile url here.

["fundingUrl": "",](https://github.com/0011000000110010/obsidian-i18n/blob/a42330e9124d2a4b0d28c0ecad9e5a1f9b6414dd/manifest.json#L8)
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link remove this.

Your manifest is currently missing a value for `minAppVersion`, please add it.

[import * as path from 'path';](https://github.com/0011000000110010/obsidian-i18n/blob/a42330e9124d2a4b0d28c0ecad9e5a1f9b6414dd/src/main.ts#L1-L3)
These imports are only available from a Node.js runtime, which means that this will throw errors on Mobile (that's a problem since you have `isDesktopOnly` marked as `false` in your manifest.json file.

[this.basePath = path.normalize(this.app.vault.adapter.basePath);](https://github.com/0011000000110010/obsidian-i18n/blob/a42330e9124d2a4b0d28c0ecad9e5a1f9b6414dd/src/main.ts#L76)
`basePath` is also only a thing on desktop, and `if(file instanceof FileSystemAdapter) basePath = this.app.vault.adapter.getBasePath()` instead.

[const command = `powershell.exe -Command "ii ${pluginDir}"`;](https://github.com/0011000000110010/obsidian-i18n/blob/a42330e9124d2a4b0d28c0ecad9e5a1f9b6414dd/src/main.ts#L322)
This will only work on Windows, but I don't see any validations about this.

 
[export interface Plugin {](https://github.com/0011000000110010/obsidian-i18n/blob/a42330e9124d2a4b0d28c0ecad9e5a1f9b6414dd/src/types.ts#L2-L14)
The `PluginManifest` interface for this already exists.

[console.log(I18n)](https://github.com/0011000000110010/obsidian-i18n/blob/a42330e9124d2a4b0d28c0ecad9e5a1f9b6414dd/src/settings/ui/i18n-template.ts#L7)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[containerEl.createEl('h2', { text: t('SETTING_BASE_TITLE') });](https://github.com/0011000000110010/obsidian-i18n/blob/a42330e9124d2a4b0d28c0ecad9e5a1f9b6414dd/src/settings/ui/index.ts#L30)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[containerEl.createEl('h2', { text: t('SETTING_LDT_TITLE') });](https://github.com/0011000000110010/obsidian-i18n/blob/a42330e9124d2a4b0d28c0ecad9e5a1f9b6414dd/src/settings/ui/index.ts#L35), [containerEl.createEl('h2', { text: t('SETTING_NDT_TITLE') });](https://github.com/0011000000110010/obsidian-i18n/blob/a42330e9124d2a4b0d28c0ecad9e5a1f9b6414dd/src/settings/ui/index.ts#L39), [containerEl.createEl('h2', { text: t('SETTING_NIT_TITLE') });](https://github.com/0011000000110010/obsidian-i18n/blob/a42330e9124d2a4b0d28c0ecad9e5a1f9b6414dd/src/settings/ui/index.ts#L43)
For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```

**Comment by 0011000000110010** [comment]
Already modified and completed.

import * as path from 'path';
I have changed the value of `isDesktopOnly` to `true`, but I'm not sure if this resolves the issue.

LDT, NDT, and NIT are abbreviations for certain words.

**Comment by joethei** [comment]
The last one is not about the naming for those, it's about you using H2's

**Comment by 0011000000110010** [comment]
Ok, what else do I need to do then?

**Comment by joethei** [comment]
We had some further discussion about your plugin, and I am afraid we can't accept it.

We are not comfortable with a plugin modifying the source files of another plugin.
Sorry about that!

**Comment by dangehub** [comment]
> We had some further discussion about your plugin, and I am afraid we can't accept it.
> 
> We are not comfortable with a plugin modifying the source files of another plugin. Sorry about that!

Hello, I have just read the [Developer policies - Developer Documentation](https://docs.obsidian.md/Developer+policies), and it seems that you did not initially require one plugin to not modify another plugin. 

Moreover, at the beginning of this PR thread, you were actively asking the author to make modifications. 

May I ask what led to the final decision?

Of course, we can understand that modifications by one plugin to another may introduce security issues and stability problems. However, the plugins I use daily, such as livesync/remotelysave, also pose certain system risks. 

If possible, I hope you can provide suggestions for improvement rather than directly telling the author, "this is over" 

After all, using one's preferred language in a daily software greatly increases user comfort, and currently, Obsidian has not standardized i18n for plugins, so we have to solve this issue on our own.

Appreciate your hardworking.

**Pull request closed without merging**
