### PR TITLE
Update community-plugins.json

### PR DESCRIPTION
**Pull request by alvaro-cas**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/alvaro-cas/kindle-csv-converter-obsidian

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[id: 'kindle-csv-converter',](https://github.com/alvaro-cas/kindle-csv-converter-obsidian/blob/0a46287142b33090b6538806e1eb675f04783cc4/main.ts#L15)
This id does not need to be unique, I would recommend an id of `choose-file`, Obsidian will automatically prepend this with the plugin id.


[const files = (this.app.vault.adapter as any).files as AdapterFile[];](https://github.com/alvaro-cas/kindle-csv-converter-obsidian/blob/0a46287142b33090b6538806e1eb675f04783cc4/settings.ts#L40-L44)
Don't do this, do this instead.
```ts
for (let file of this.app.vault.getAllLoadedFiles()) {
            if (file instanceof TFolder) {
                files.push(file);
            }
        }
```

[import { Modal, Notice, setIcon } from 'obsidian';](https://github.com/alvaro-cas/kindle-csv-converter-obsidian/blob/0a46287142b33090b6538806e1eb675f04783cc4/modal_read.ts#L1-L4)
I would recommend sticking to one import style.

[document.createElement('input');](https://github.com/alvaro-cas/kindle-csv-converter-obsidian/blob/0a46287142b33090b6538806e1eb675f04783cc4/modal_read.ts#L31)
Use `activeDocument` instead, as `document` is only for the main window.

[fs.createReadStream(input.files[0]['path']);](https://github.com/alvaro-cas/kindle-csv-converter-obsidian/blob/0a46287142b33090b6538806e1eb675f04783cc4/modal_read.ts#L35)
Where would this file be located?
If its inside the vault I recommend using `app.vault.readCached(tfile);`



## Style Nitpicks:

I would generally recommend moving all code files into a separate `src` folder, that makes it easier to review and maintain.

[kindleCsvPlugin](https://github.com/alvaro-cas/kindle-csv-converter-obsidian/blob/0a46287142b33090b6538806e1eb675f04783cc4/main.ts#L6)
[kindleSettings](https://github.com/alvaro-cas/kindle-csv-converter-obsidian/blob/0a46287142b33090b6538806e1eb675f04783cc4/main.ts#L29)
[reader](https://github.com/alvaro-cas/kindle-csv-converter-obsidian/blob/0a46287142b33090b6538806e1eb675f04783cc4/main.ts#L21)
Classes are generally named with the first letter in caps.

**Comment by alvaro-cas** [comment]
- Where would this file be located?
This is the .csv input file, so it can be anywhere outside the vault depending on where the user download it.

The other requested changes are already updated in the [plugin repo](https://github.com/alvaro-cas/kindle-csv-converter-obsidian/). Thank you for reviewing my code! 😃

**Comment by liamcain** [comment]
[view](https://github.com/alvaro-cas/kindle-csv-converter-obsidian/blob/645bd2b2932a49e9c0f7c1822cf705e71b8d2756/main.ts#L20) why is the command only available if the active view is a markdown file? Seems like it doesn't matter what the active file is

**Comment by alvaro-cas** [comment]
Yeah, actually it doesn't matter. I thought the command could not trigger at all, but actually I checked and I think it also works on other views not sure why. Do I remove that?

**Comment by liamcain** [comment]
I think it would make more sense if you remove the check.

**Pull request merged**
