### PR TITLE
Add Flashcard Generator

### PR DESCRIPTION
**Pull request by chloedia**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/chloedia/Obsidian_Quiz_Generator

## Release Checklist
- [ ] I have tested the plugin on
  - [X]  Windows
  - [X]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ X My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by ericaxu** [comment]
Please add a link to your repo.

**Comment by chloedia** [comment]
Fixing previous Pull request (add main.js and manifest.json in the release + link to the repo)

**Comment by joethei** [comment]
["description": "This is a quiz generator plugin for Obsidian. This plugin let's you generate important questions on your note.",](https://github.com/chloedia/Obsidian_Quiz_Generator/blob/eed0c532564d5827c681e799b7cca8b81c2ce3d1/manifest.json#L6)
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This is a plugin for Obsidian" in your description.

[if (!checking) {](https://github.com/chloedia/Obsidian_Quiz_Generator/blob/eed0c532564d5827c681e799b7cca8b81c2ce3d1/src/main.ts#L134-L138)
I don't think that using the status bar is a good way to show progress in this case.

[containerEl.createEl("h2", {](https://github.com/chloedia/Obsidian_Quiz_Generator/blob/eed0c532564d5827c681e799b7cca8b81c2ce3d1/src/main.ts#L176-L178)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[contentEl.createEl("h1", { text: "New Document Path" });](https://github.com/chloedia/Obsidian_Quiz_Generator/blob/eed0c532564d5827c681e799b7cca8b81c2ce3d1/src/set_path.ts#L18)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by chloedia** [comment]
* [x] The description has been updated
* [x] I removed the the status bar update
* [x] I removed headings
* [x] I changed the new file prompt to one respecting the guidelines

**Pull request merged**
