### PR TITLE
Add Checkbox Reorder plugin

### PR DESCRIPTION
**Pull request by Erl-koenig**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Erl-koenig/obsidian-checkboxReorder

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Erl-koenig** [comment]
updated repo name

**Comment by joethei** [comment]
["description": "This obsidian plugin automatically puts checked checkboxes to the end of the according list. ",](https://github.com/Erl-koenig/obsidian-checkboxReorder/blob/179bb49a9019972098fc5716a38ed0a8d1cbde35/manifest.json#L6)
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This is a plugin for Obsidian" in your description.

[callback: () => this.reorderCheckboxes()](https://github.com/Erl-koenig/obsidian-checkboxReorder/blob/179bb49a9019972098fc5716a38ed0a8d1cbde35/main.ts#L10)
Use an editorCallback here instead: <https://docs.obsidian.md/Plugins/User+interface/Commands#Editor+commands>

**Comment by Erl-koenig** [comment]
updated description and using editorCallback instead

**Comment by Erl-koenig** [comment]
@joethei Is there an update regarding this pull request?

**Pull request merged**
