### PR TITLE
Youtube Timestamp Notes Plugin

### PR DESCRIPTION
**Pull request by juliang22**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/juliang22/ObsidianTimestampNotes

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by juliang22** [comment]
Updated plugin and will submit newer version

**Comment by ericaxu** [comment]
Please add to bottom of the plugin list instead of the top, thanks!

**Comment by juliang22** [comment]
> Please add to bottom of the plugin list instead of the top, thanks!

Just fixed 👍

**Comment by liamcain** [comment]
https://github.com/juliang22/ObsidianYoutubeTimestampNotes/blob/fc588573d04b38e419e0127224c6c9aa6b278bef/main.ts#L6 You can remove "mySetting"

https://github.com/juliang22/ObsidianYoutubeTimestampNotes/blob/fc588573d04b38e419e0127224c6c9aa6b278bef/main.ts#L29 Nevermind, it looks like you're using `mySetting`? That was meant to just be an example name. Your property should have a more descriptive name so it's clear what it's for.

https://github.com/juliang22/ObsidianYoutubeTimestampNotes/blob/fc588573d04b38e419e0127224c6c9aa6b278bef/main.ts#L7 `player` should not be on the `settings` object. Your Settings object needs to be serializable to JSON so it should only include values that need to be persisted to the user's settings file.

https://github.com/juliang22/ObsidianYoutubeTimestampNotes/blob/fc588573d04b38e419e0127224c6c9aa6b278bef/main.ts#L134 No need to save settings on unload. Your settings should already be up to date.

https://github.com/juliang22/ObsidianYoutubeTimestampNotes/blob/fc588573d04b38e419e0127224c6c9aa6b278bef/main.ts#L151 currURL also shouldn't live in the settings object. This should be an instance variable on the YoutubeView class. if you want to serialize the url to the workspace, you can add a `getState` and `setState` method to your View subclass.

https://github.com/juliang22/ObsidianYoutubeTimestampNotes/blob/fc588573d04b38e419e0127224c6c9aa6b278bef/view/YoutubeView.tsx#L2 You might want to look at `Preact` as a lighterweight alternative to React. It should be completely compatible, just means users will have less to download.

https://github.com/juliang22/ObsidianYoutubeTimestampNotes/blob/fc588573d04b38e419e0127224c6c9aa6b278bef/view/YoutubeView.tsx#L28 You probably want a more meaningful display text here.

https://github.com/juliang22/ObsidianYoutubeTimestampNotes/blob/fc588573d04b38e419e0127224c6c9aa6b278bef/YTContainer.tsx#L1 Nitpick, you might want this file inside your `view/` folder

https://github.com/juliang22/ObsidianYoutubeTimestampNotes/blob/fc588573d04b38e419e0127224c6c9aa6b278bef/YTContainer.tsx#L30 why do you need the ts-ignore?

**Comment by juliang22** [comment]
> https://github.com/juliang22/ObsidianYoutubeTimestampNotes/blob/fc588573d04b38e419e0127224c6c9aa6b278bef/main.ts#L6 You can remove "mySetting"
> 
> https://github.com/juliang22/ObsidianYoutubeTimestampNotes/blob/fc588573d04b38e419e0127224c6c9aa6b278bef/main.ts#L29 Nevermind, it looks like you're using `mySetting`? That was meant to just be an example name. Your property should have a more descriptive name so it's clear what it's for.
> 
> https://github.com/juliang22/ObsidianYoutubeTimestampNotes/blob/fc588573d04b38e419e0127224c6c9aa6b278bef/main.ts#L7 `player` should not be on the `settings` object. Your Settings object needs to be serializable to JSON so it should only include values that need to be persisted to the user's settings file.
> 
> https://github.com/juliang22/ObsidianYoutubeTimestampNotes/blob/fc588573d04b38e419e0127224c6c9aa6b278bef/main.ts#L134 No need to save settings on unload. Your settings should already be up to date.
> 
> https://github.com/juliang22/ObsidianYoutubeTimestampNotes/blob/fc588573d04b38e419e0127224c6c9aa6b278bef/main.ts#L151 currURL also shouldn't live in the settings object. This should be an instance variable on the YoutubeView class. if you want to serialize the url to the workspace, you can add a `getState` and `setState` method to your View subclass.
> 
> https://github.com/juliang22/ObsidianYoutubeTimestampNotes/blob/fc588573d04b38e419e0127224c6c9aa6b278bef/view/YoutubeView.tsx#L2 You might want to look at `Preact` as a lighterweight alternative to React. It should be completely compatible, just means users will have less to download.
> 
> https://github.com/juliang22/ObsidianYoutubeTimestampNotes/blob/fc588573d04b38e419e0127224c6c9aa6b278bef/view/YoutubeView.tsx#L28 You probably want a more meaningful display text here.
> 
> https://github.com/juliang22/ObsidianYoutubeTimestampNotes/blob/fc588573d04b38e419e0127224c6c9aa6b278bef/YTContainer.tsx#L1 Nitpick, you might want this file inside your `view/` folder
> 
> https://github.com/juliang22/ObsidianYoutubeTimestampNotes/blob/fc588573d04b38e419e0127224c6c9aa6b278bef/YTContainer.tsx#L30 why do you need the ts-ignore?


Addressed all your changes! Also ended up implementing some new settings for choosing colors, made it compatible for multiple players, not just YouTube (and changed the name accordingly), and implemented some better error handling. 

I couldn't figure out how to get preact working for some reason, I'll try again at a later point. Thanks for the review! Lmk if there is more to be done.

**Review by liamcain — APPROVED** [review]

**Comment by juliang22** [comment]
Sorry, totally forgot to update the title on the community plugins json (now that it can play other video types I removed YouTube from the plugin name). Thanks for the additional review!

**Comment by liamcain** [comment]
Hi, sorry for the delay in reviewing! I took another look and found a few more things.

image
you might want to update the "About" section on your plugin 😄 

https://github.com/juliang22/ObsidianTimestampNotes/blob/e18bc345d397a86308f46817a3807af0f01bdb57/main.ts#L121 you should `return` after showing the error.

https://github.com/juliang22/ObsidianTimestampNotes/blob/e18bc345d397a86308f46817a3807af0f01bdb57/settings.ts#L18-L19 you have the default value for these as "white" but white isn't one of the colors in your color map

https://github.com/juliang22/ObsidianTimestampNotes/blob/e18bc345d397a86308f46817a3807af0f01bdb57/main.ts#L20 validateURL returns a string but it looks like you aren't doing anything with that string when you call `validateURL`

https://github.com/juliang22/ObsidianTimestampNotes/blob/e18bc345d397a86308f46817a3807af0f01bdb57/main.ts#L43 you're calling `activateView` without passing in an editor. This causes an error to get thrown within the functions since it's actually expecting an editor to exist. I noticed since I tried out the plugin and it threw errors when trying to paste in an invalid URL.

**Comment by juliang22** [comment]
> Hi, sorry for the delay in reviewing! I took another look and found a few more things.
> 
> image
> 
> you might want to update the "About" section on your plugin 😄
> https://github.com/juliang22/ObsidianTimestampNotes/blob/e18bc345d397a86308f46817a3807af0f01bdb57/main.ts#L121 you should `return` after showing the error.
> 
> https://github.com/juliang22/ObsidianTimestampNotes/blob/e18bc345d397a86308f46817a3807af0f01bdb57/settings.ts#L18-L19 you have the default value for these as "white" but white isn't one of the colors in your color map
> 
> https://github.com/juliang22/ObsidianTimestampNotes/blob/e18bc345d397a86308f46817a3807af0f01bdb57/main.ts#L20 validateURL returns a string but it looks like you aren't doing anything with that string when you call `validateURL`
> 
> https://github.com/juliang22/ObsidianTimestampNotes/blob/e18bc345d397a86308f46817a3807af0f01bdb57/main.ts#L43 you're calling `activateView` without passing in an editor. This causes an error to get thrown within the functions since it's actually expecting an editor to exist. I noticed since I tried out the plugin and it threw errors when trying to paste in an invalid URL.
> 
> https://github.com/juliang22/ObsidianTimestampNotes/blob/e18bc345d397a86308f46817a3807af0f01bdb57/view/VideoView.tsx#L23 I also suggest you add a `getIcon` function to your view. Something like the "youtube" or the "video" icon should work well (bonus points if you can switch between the 2 depending on the video that's playing!) ([list of icons you can choose from that are builtin to Obsidian](https://lucide.dev/?search=video))

Thanks for the review! Totally missed the color error, great find! Ended up just removing the ribbon button to insert the link—it made the code messier as there would be instances with or without an editor present (depending on if the link was opened with the hotkey or ribbon) and also its way easier just to use the hotkey. Thanks for the edits, it should be ready to go!

**Pull request merged**
