### PR TITLE
Add plugin: Edge TTS

### PR DESCRIPTION
**Pull request by travisvn**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [https://github.com/travisvn/obsidian-edge-tts](https://github.com/travisvn/obsidian-edge-tts)

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by travisvn** [comment]
> Thank you for your submission, an automated scan of your plugin code's revealed the following issues:
> 
> ### Optional
> [[1](https://github.com/travisvn/obsidian-edge-tts/blob/1a808586ab8c944f1b8e03ccfaa9ba6b39812440/main.ts#L58)]:We recommend against providing a default hotkey when possible. The reason being that it's easy to pick a hotkey that a user already has configured and they could get confused when that key doesn't do what they expect. Also, it's hard choosing a safe default hotkey that's available for all operating systems.
> 
> Do NOT open a new PR for re-validation.

Updated to remove default hotkey 👍

**Comment by travisvn** [comment]
@joethei Would you mind helping me out here? I keep having to "Resolve conflicts" as new plugins get added 😵‍💫

**Comment by joethei** [comment]
Ignore the conflicts, I'll handle those when merging.

**Comment by travisvn** [comment]
> Ignore the conflicts, I'll handle those when merging.

That makes much more sense. Thank you

**Comment by joethei** [comment]
To make the manual review process and future plugin maintenance more efficient, we recommend that you move all source code files into a `src` directory.

[.setting-item-description {](https://github.com/travisvn/obsidian-edge-tts/blob/d87eca7610a5a0a0a4dfbc26b1ac2c096b5a5414/styles.css#L5)
Please don't overwrite core styling in a plugin, add another class/data attribute so it only applies to your plugin.

[if (this.settings.showRibbonIcon) {](https://github.com/travisvn/obsidian-edge-tts/blob/d87eca7610a5a0a0a4dfbc26b1ac2c096b5a5414/main.ts#L49), [addPluginRibbonIcon(): void {](https://github.com/travisvn/obsidian-edge-tts/blob/d87eca7610a5a0a0a4dfbc26b1ac2c096b5a5414/main.ts#L61-L69), [removePluginRibbonIcon(): void {](https://github.com/travisvn/obsidian-edge-tts/blob/d87eca7610a5a0a0a4dfbc26b1ac2c096b5a5414/main.ts#L71-L76)

[name: 'Read Note Aloud',](https://github.com/travisvn/obsidian-edge-tts/blob/d87eca7610a5a0a0a4dfbc26b1ac2c096b5a5414/main.ts#L56), 

[callback: () => this.readNoteAloud()](https://github.com/travisvn/obsidian-edge-tts/blob/d87eca7610a5a0a0a4dfbc26b1ac2c096b5a5414/main.ts#L57)

**Comment by travisvn** [comment]
> To make the manual review process and future plugin maintenance more efficient, we recommend that you move all source code files into a `src` directory.
> 
> [.setting-item-description {](https://github.com/travisvn/obsidian-edge-tts/blob/d87eca7610a5a0a0a4dfbc26b1ac2c096b5a5414/styles.css#L5) Please don't overwrite core styling in a plugin, add another class/data attribute so it only applies to your plugin.
> 
> [if (this.settings.showRibbonIcon) {](https://github.com/travisvn/obsidian-edge-tts/blob/d87eca7610a5a0a0a4dfbc26b1ac2c096b5a5414/main.ts#L49), [addPluginRibbonIcon(): void {](https://github.com/travisvn/obsidian-edge-tts/blob/d87eca7610a5a0a0a4dfbc26b1ac2c096b5a5414/main.ts#L61-L69), [removePluginRibbonIcon(): void {](https://github.com/travisvn/obsidian-edge-tts/blob/d87eca7610a5a0a0a4dfbc26b1ac2c096b5a5414/main.ts#L71-L76), [// Ribbon icon toggle setting](https://github.com/travisvn/obsidian-edge-tts/blob/d87eca7610a5a0a0a4dfbc26b1ac2c096b5a5414/main.ts#L239-L255) As of v1.1.0 of Obsidian, the ribbon can be customized within Obsidian. So users can choose what items to include and in what order all in one place. Because of this, we're recommending that new plugins avoid introducing their own toggles for ribbon items.
> 
> [name: 'Read Note Aloud',](https://github.com/travisvn/obsidian-edge-tts/blob/d87eca7610a5a0a0a4dfbc26b1ac2c096b5a5414/main.ts#L56), [.setName('Select Voice')](https://github.com/travisvn/obsidian-edge-tts/blob/d87eca7610a5a0a0a4dfbc26b1ac2c096b5a5414/main.ts#L203), [.setName('Show Notices')](https://github.com/travisvn/obsidian-edge-tts/blob/d87eca7610a5a0a0a4dfbc26b1ac2c096b5a5414/main.ts#L259), [.setName('Custom Voice')](https://github.com/travisvn/obsidian-edge-tts/blob/d87eca7610a5a0a0a4dfbc26b1ac2c096b5a5414/main.ts#L228) [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)
> 
> [callback: () => this.readNoteAloud()](https://github.com/travisvn/obsidian-edge-tts/blob/d87eca7610a5a0a0a4dfbc26b1ac2c096b5a5414/main.ts#L57) This should be a [editor command](https://docs.obsidian.md/Plugins/User+interface/Commands#Editor%20commands)
> 
> [console.log('Audio playback started');](https://github.com/travisvn/obsidian-edge-tts/blob/d87eca7610a5a0a0a4dfbc26b1ac2c096b5a5414/main.ts#L123) Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.
> 
> [containerEl.createEl('h2', { text: 'Edge TTS Plugin Options' });](https://github.com/travisvn/obsidian-edge-tts/blob/d87eca7610a5a0a0a4dfbc26b1ac2c096b5a5414/main.ts#L185-L199) [Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)


- [x] Move source code files to src/ directory
- [x] Remove overriding styles
- [x] Remove toggle for ribbon item
- [x] Change language to use sentence case
- [x] Change callback to editorCallback
- [x] Add dev environment check before logging unnecessarily
- [x] Remove top level heading in settings tab

Went through and made every change you recommended. 

Thank you for your review 👍

**Comment by travisvn** [comment]
Oops meant to tag you @joethei 

Hopefully can finally get this merged 🙂

**Pull request merged**
