### PR TITLE
Add plugin: Serendipity

### PR DESCRIPTION
**Pull request by ggauravr**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/ggauravr/obsidian-serendipity-plugin/

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[Copyright (c) [year] [fullname]](https://github.com/ggauravr/obsidian-serendipity-plugin/blob/92c4ed57b9e74d165e7d6f7041f607b0581e9648/LICENSE.md#L3)
Fill this.

["minAppVersion": "0.15.0",](https://github.com/ggauravr/obsidian-serendipity-plugin/blob/92c4ed57b9e74d165e7d6f7041f607b0581e9648/manifest.json#L5)
You are using newer API's, set this to the latest public build number.


["fundingUrl": "",](https://github.com/ggauravr/obsidian-serendipity-plugin/blob/92c4ed57b9e74d165e7d6f7041f607b0581e9648/manifest.json#L9)
If you don't have one remove this line.

[const sourceDirectory = this.app.vault.getAbstractFileByPath(this.settings.sourceDirectory);](https://github.com/ggauravr/obsidian-serendipity-plugin/blob/92c4ed57b9e74d165e7d6f7041f607b0581e9648/main.ts#L49-L51)
[Use `normalizePath` to clean up user defined paths](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+%60normalizePath()%60+to+clean+up+user-defined+paths)

[containerEl.createEl('h2', { text: 'Serenditpity Settings' });](https://github.com/ggauravr/obsidian-serendipity-plugin/blob/92c4ed57b9e74d165e7d6f7041f607b0581e9648/settings.ts#L17)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[.setName('Source Directory')](https://github.com/ggauravr/obsidian-serendipity-plugin/blob/92c4ed57b9e74d165e7d6f7041f607b0581e9648/settings.ts#L20), [.setName('Exclude Directory')](https://github.com/ggauravr/obsidian-serendipity-plugin/blob/92c4ed57b9e74d165e7d6f7041f607b0581e9648/settings.ts#L32)

[.modal {](https://github.com/ggauravr/obsidian-serendipity-plugin/blob/92c4ed57b9e74d165e7d6f7041f607b0581e9648/styles.css#L1), [.modal-content {](https://github.com/ggauravr/obsidian-serendipity-plugin/blob/92c4ed57b9e74d165e7d6f7041f607b0581e9648/styles.css#L5), [.modal-close-button {](https://github.com/ggauravr/obsidian-serendipity-plugin/blob/92c4ed57b9e74d165e7d6f7041f607b0581e9648/styles.css#L10), [.modal-header {](https://github.com/ggauravr/obsidian-serendipity-plugin/blob/92c4ed57b9e74d165e7d6f7041f607b0581e9648/styles.css#L14)
Please don't overwrite core styling in a plugin, add another class/data attribute so it only applies to your plugin.

[// TODO: Add 'components" as expected as the last argument. app console warns about potential memory issues of using "this"](https://github.com/ggauravr/obsidian-serendipity-plugin/blob/92c4ed57b9e74d165e7d6f7041f607b0581e9648/main.ts#L124)
This comment is no longer neccessary.


---

[const component = new Component();](https://github.com/ggauravr/obsidian-serendipity-plugin/blob/92c4ed57b9e74d165e7d6f7041f607b0581e9648/main.ts#L121)
Call `component.unload()` in the modals `onClose()` function.

**Comment by ggauravr** [comment]
All the review comments have been addressed

**Comment by ggauravr** [comment]
@joethei - Tagging again, as a reminder, since the changes requested have been addressed.

**Comment by liamcain** [comment]
- [read](https://github.com/ggauravr/obsidian-serendipity-plugin/blob/5e49409b37e99d61218d4da2c73f6f9d25341f4a/main.ts#L104) This can use [cachedRead](https://github.com/obsidianmd/obsidian-api/blob/9bb30633586c6649474b2affdf5b87efdd86498f/obsidian.d.ts#L3373) instead of read. It will be faster since it doesn't need to read the file from disk.
- [containerEl.addClass('serendipity-modal-container');](https://github.com/ggauravr/obsidian-serendipity-plugin/blob/5e49409b37e99d61218d4da2c73f6f9d25341f4a/main.ts#L106-L107) you should move this code into your constructor. That will avoid the content changing while the modal is already on screen.

**Pull request merged**
