### PR TITLE
chore: add yet another obsidian synchronizer plugin

### PR DESCRIPTION
**Pull request by mahyarmirrashed**
# Request to add Yet Another Obsidian Synchronizer (YAOS) Plugin

## Repo URL

Link to my plugin: https://github.com/mahyarmirrashed/yaos

Mobile is not applicable for the current release.

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[id: `${PLUGIN_NAME.toLowerCase()}-show-unmerged`,](https://github.com/mahyarmirrashed/yaos/blob/099aa3215a6bf960ba923a3cfadb8b0394874437/src/main.ts#L31)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

[return (this.app.vault.adapter as FileSystemAdapter).getBasePath();](https://github.com/mahyarmirrashed/yaos/blob/099aa3215a6bf960ba923a3cfadb8b0394874437/src/main.ts#L45)
You should check if it is a `FileSystemAdapter` before casting, in case we update the classes.

**Comment by mahyarmirrashed** [comment]
@joethei I have made the changes as requested. Please let me know if there are other changes that you would like me to make.

**Comment by mahyarmirrashed** [comment]
@joethei Is there anything else that I should do to get this plugin approved?

**Comment by mahyarmirrashed** [comment]
Hi @joethei , it's been about a month and I just wanted to follow up!

**Comment by liamcain** [comment]
Sorry for the delay in reviewing your plugin. Looks good to me! Thanks for your patience.

**Pull request merged**
