### PR TITLE
Add "MLIR Syntax Highlight" plugin

### PR DESCRIPTION
**Pull request by Lewuathe**
# I am submitting a new Community Plugin

## Repo URL

https://github.com/Lewuathe/obsidian-mlir-syntax-highlight

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[async onload() {](https://github.com/Lewuathe/obsidian-mlir-syntax-highlight/blob/ebedea07bb0ac65273c63ebdca9728ea7fc33443/main.ts#L11-L20)
Use this instead:
```ts
this.app.workspace.onLayoutReady(() => {
	this.refreshLeaves();
});
```

**Comment by Lewuathe** [comment]
@joethei Thanks for the quick review. I have updated the plugin to use the `onLayoutReady` accordingly and published 0.0.6 as the latest.

https://github.com/Lewuathe/obsidian-mlir-syntax-highlight/blob/main/main.ts#L11-L13

**Comment by liamcain** [comment]
- [onLayoutReady](https://github.com/Lewuathe/obsidian-mlir-syntax-highlight/blob/7477479cf71cd87849988015e8b5ea8196e45e92/main.ts#L11) This isn't how the onLayoutReady api works. You'll want to call onLayoutReady from within the onload function.

**Comment by Lewuathe** [comment]
I have released new version with the fix for the proper `onLayoutReady` usage. 
https://github.com/Lewuathe/obsidian-mlir-syntax-highlight/releases/tag/0.0.7

@liamcain Could you take a look it again when you get a chance?

**Pull request closed without merging**
