### PR TITLE
Add plugin ai-assistant

### PR DESCRIPTION
**Pull request by nguyenvanduocit**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/nguyenvanduocit/obsidian-ai-assistant

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using. I have given proper attribution to these other projects in my `README.md`.

Please switch to **Preview** and select one of the following links:

* [Community Plugin](?template=plugin.md)
* [Community Theme](?template=theme.md)

### CODE REVIEW

**Comment by joethei** [comment]
[id: 'ai-complete',](https://github.com/nguyenvanduocit/obsidian-ai-assistant/blob/ac11ad40bedbc7439fe2fd75b69b2144ac6c928e/src/main.ts#L115)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to do it yourself.

[this.app.workspace.on('editor-menu', (menu, editor, view) => {](https://github.com/nguyenvanduocit/obsidian-ai-assistant/blob/ac11ad40bedbc7439fe2fd75b69b2144ac6c928e/src/main.ts#L154)
Wrap this in a `this.registerEvent()` so it gets properly unloaded.

[VIEW_TYPE_EXAMPLE](https://github.com/nguyenvanduocit/obsidian-ai-assistant/blob/ac11ad40bedbc7439fe2fd75b69b2144ac6c928e/src/main.ts#L36)
You should rename this variable. it's also duplicated here: [export const ViewType = 'ai-assistant-view'](https://github.com/nguyenvanduocit/obsidian-ai-assistant/blob/ac11ad40bedbc7439fe2fd75b69b2144ac6c928e/src/CanvasView.ts#L5)



---
**No need to fix the following:**

Not using semicolons in JavaScript/TypeScript code can lead to rare, hard to debug issues, here is a pretty good article about it:
<https://flaviocopes.com/javascript-automatic-semicolon-insertion>

**Comment by nguyenvanduocit** [comment]
Almost feedback is updated, but can not fix the command-id, because of typescript, so I make it more unique.

> [id: 'ai-complete',](https://github.com/nguyenvanduocit/obsidian-ai-assistant/blob/ac11ad40bedbc7439fe2fd75b69b2144ac6c928e/src/main.ts#L115)

**Comment by joethei** [comment]
Sorry could you explain why?
Just change the id from `ai-complete` to `complete`

**Comment by nguyenvanduocit** [comment]
I really appreciate your time in this community, but I don't think I'm suitable to continue submitting this plugin, I find it a bit difficult for me and I really don't have much patience on that. Your work is great.

**Pull request closed without merging**
