### PR TITLE
Add plugin: List Cycler

### PR DESCRIPTION
**Pull request by LandonSchropp**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/LandonSchropp/obsidian-list-cycler

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_ 
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "Cycles between different types of lists and checkboxes in Obisidan",](https://github.com/LandonSchropp/obsidian-list-cycler/blob/358f807f878bebff9d443d5ad49b61a77af08019/manifest.json#L6)
Avoid including sentences like "This is a plugin for Obsidian that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[name: "Remove List",](https://github.com/LandonSchropp/obsidian-list-cycler/blob/358f807f878bebff9d443d5ad49b61a77af08019/src/main.ts#L29), [name: "Convert to Bullet List",](https://github.com/LandonSchropp/obsidian-list-cycler/blob/358f807f878bebff9d443d5ad49b61a77af08019/src/main.ts#L36), [name: "Convert to Number List",](https://github.com/LandonSchropp/obsidian-list-cycler/blob/358f807f878bebff9d443d5ad49b61a77af08019/src/main.ts#L43), [name: "Convert to Task List",](https://github.com/LandonSchropp/obsidian-list-cycler/blob/358f807f878bebff9d443d5ad49b61a77af08019/src/main.ts#L50), [name: `Cycle ${group.name} Forward`,](https://github.com/LandonSchropp/obsidian-list-cycler/blob/358f807f878bebff9d443d5ad49b61a77af08019/src/main.ts#L72), [name: `Cycle ${group.name} Backward`,](https://github.com/LandonSchropp/obsidian-list-cycler/blob/358f807f878bebff9d443d5ad49b61a77af08019/src/main.ts#L83), [.setName("Add a New Group")](https://github.com/LandonSchropp/obsidian-list-cycler/blob/358f807f878bebff9d443d5ad49b61a77af08019/src/settings/settings-view.ts#L76), [button.setButtonText("Add Group").](https://github.com/LandonSchropp/obsidian-list-cycler/blob/358f807f878bebff9d443d5ad49b61a77af08019/src/settings/settings-view.ts#L79), [.setPlaceholder("List Item")](https://github.com/LandonSchropp/obsidian-list-cycler/blob/358f807f878bebff9d443d5ad49b61a77af08019/src/settings/list-item-settings-view.ts#L95), [this.customizeExtraButton(button, "arrow-up", "Move Up", this.isFirstListItem, () => {});](https://github.com/LandonSchropp/obsidian-list-cycler/blob/358f807f878bebff9d443d5ad49b61a77af08019/src/settings/list-item-settings-view.ts#L102), [this.customizeExtraButton(button, "arrow-down", "Move Down", this.isLastListItem, () => {});](https://github.com/LandonSchropp/obsidian-list-cycler/blob/358f807f878bebff9d443d5ad49b61a77af08019/src/settings/list-item-settings-view.ts#L106), [modal.titleEl.setText("Are You Sure?");](https://github.com/LandonSchropp/obsidian-list-cycler/blob/358f807f878bebff9d443d5ad49b61a77af08019/src/settings/confirm-delete-modal.ts#L17)

[const titleSetting = new Setting(this.containerEl)](https://github.com/LandonSchropp/obsidian-list-cycler/blob/358f807f878bebff9d443d5ad49b61a77af08019/src/settings/settings-view.ts#L60-L68)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[export class ConfirmDeleteModal {](https://github.com/LandonSchropp/obsidian-list-cycler/blob/358f807f878bebff9d443d5ad49b61a77af08019/src/settings/confirm-delete-modal.ts#L4-L51)
Why are you doing it this way instead of extending the Modal class?

**Comment by LandonSchropp** [comment]
I've updated the description in accordance with the guidelines.

> Why are you doing it this way instead of extending the Modal class?

I was leaning into the principle of [favoring composition over inheritance](https://sheldonrcohen.medium.com/favoring-composition-over-inheritance-ff2ece6b7b4e).

**Comment by LandonSchropp** [comment]
@joethei Quick question while I have you:

I've started developing my Obsidian plugins in a [monorepo](https://github.com/LandonSchropp/obsidian-plugins) instead of individual GitHub repos. This makes it a little easier for me to maintain them since I only have to worry about creating one environment instead of many.

Do you guys support monorepos for community plugins? If so, how should I structure the releases?

**Comment by joethei** [comment]
No, monorepos are not supported.

**Comment by joethei** [comment]
You have not applied fixes for most of my feedback.

**Comment by LandonSchropp** [comment]
I can't really tell from your feedback what you'd like me to do.

I updated the description as you suggested. I can't read the formatting on your reply.

**Comment by joethei** [comment]
Refactor the ConfirmDeleteModal to use inheritance.

And update your UI strings to use sentence case.

**Pull request closed without merging**
