### PR TITLE
add local plantuml provider

### PR DESCRIPTION
**Pull request by joethei**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/joethei/obsidian-local-plantuml

## Release Checklist
- [X] I have tested the plugin on
  - [X]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/joethei/obsidian-local-plantuml/blob/ec2d4a2db2e2592262732a8e8610bfafe3bc0e88/main.ts#L115
Your plugin doesn't seem to do anything in Obsidian as far as I can see in the code. Am I missing something?

There are two functions to generate diagrams through an external process call, but I don't see them used anywhere.

**Comment by joethei** [comment]
Yes, this plugin is useless by itself, the methods are being called by the plantuml plugin if this plugin is installed.

Without this plugin a remote server is used for rendering. 

This separation is to keep the main plugin mobile compatible.

**Comment by lishid** [comment]
Oh I see! You can use `require()` directly in your code selectively so that you don't need a second plugin.

Instead of importing the NodeJS packages directly at the top of the file, you could instead import it inside a function like this:

```ts
function doSomeNodeStuff() {
  let fs = require('fs');
  ..
}
```

Since the require will never be called unless you call the function, it will work on mobile as long as you don't call the function (test for `Platform.isDesktopApp`)

**Comment by joethei** [comment]
Ah, that works perfectly, thank you for letting me know of this.

**Pull request closed without merging**
