### PR TITLE
Add plugin: Header Counter

### PR DESCRIPTION
**Pull request by nancyel**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/nancyel/header-counter

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[this.addRibbonIcon("dice", "Header Counter", () => {](https://github.com/nancyel/header-counter/blob/18e580ac0598364efe501a33358726a01f00caee/main.ts#L27)
Use a different icon: https://docs.obsidian.md/Plugins/User+interface/Icons

[// If the plugin hooks up any global DOM events (on parts of the app that doesn't belong to this plugin)](https://github.com/nancyel/header-counter/blob/18e580ac0598364efe501a33358726a01f00caee/main.ts#L40-L49)
Remove the sample plugin code you don't need.

[name: "Count Headers",](https://github.com/nancyel/header-counter/blob/18e580ac0598364efe501a33358726a01f00caee/main.ts#L53), [name: "Compute Header Summary",](https://github.com/nancyel/header-counter/blob/18e580ac0598364efe501a33358726a01f00caee/main.ts#L72), [contentEl.createEl("h2", { text: "Enter Header Level (1-6)" });](https://github.com/nancyel/header-counter/blob/18e580ac0598364efe501a33358726a01f00caee/main.ts#L168), [.setName("Default Header Level")](https://github.com/nancyel/header-counter/blob/18e580ac0598364efe501a33358726a01f00caee/main.ts#L226)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[if (checking) {](https://github.com/nancyel/header-counter/blob/18e580ac0598364efe501a33358726a01f00caee/main.ts#L55-L57), [if (checking) {](https://github.com/nancyel/header-counter/blob/18e580ac0598364efe501a33358726a01f00caee/main.ts#L74-L76)
The checks here serve no purpose, you should check the condititions instead of using using the notices here: [new Notice("Active view is not a Markdown view.");](https://github.com/nancyel/header-counter/blob/18e580ac0598364efe501a33358726a01f00caee/main.ts#L108), [new Notice("No active leaf found.");](https://github.com/nancyel/header-counter/blob/18e580ac0598364efe501a33358726a01f00caee/main.ts#L102), [new Notice("No active leaf found.");](https://github.com/nancyel/header-counter/blob/18e580ac0598364efe501a33358726a01f00caee/main.ts#L125), [new Notice("Active view is not a Markdown view.");](https://github.com/nancyel/header-counter/blob/18e580ac0598364efe501a33358726a01f00caee/main.ts#L131)

[const activeLeaf = this.app.workspace.getLeaf();](https://github.com/nancyel/header-counter/blob/18e580ac0598364efe501a33358726a01f00caee/main.ts#L100), [const activeLeaf = this.app.workspace.getLeaf();](https://github.com/nancyel/header-counter/blob/18e580ac0598364efe501a33358726a01f00caee/main.ts#L123)
This should be a call to `this.app.workspace.getActiveViewOfType(MarkdownView)` instead.

[containerEl.createEl("h2", { text: "General Settings" });](https://github.com/nancyel/header-counter/blob/18e580ac0598364efe501a33358726a01f00caee/main.ts#L223)
[Don't use a "general" heading in your settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by nancyel** [comment]
Thanks for the detailed feedback! The code has been updated

**Comment by joethei** [comment]
[showRibbonIcon: boolean;](https://github.com/nancyel/header-counter/blob/69c9627403995f1ac177e0016a8c2d6c2cff45fc/main.ts#L15), [showRibbonIcon: true,](https://github.com/nancyel/header-counter/blob/69c9627403995f1ac177e0016a8c2d6c2cff45fc/main.ts#L20), [if (this.settings.showRibbonIcon) {](https://github.com/nancyel/header-counter/blob/69c9627403995f1ac177e0016a8c2d6c2cff45fc/main.ts#L33), [new Setting(this.containerEl)](https://github.com/nancyel/header-counter/blob/69c9627403995f1ac177e0016a8c2d6c2cff45fc/main.ts#L250-L287)
As of v1.1.0 of Obsidian, the ribbon can be customized within Obsidian. So users can choose what items to include and in what order all in one place. Because of this, we're recommending that new plugins avoid introducing their own toggles for ribbon items.

[if (checking) {](https://github.com/nancyel/header-counter/blob/69c9627403995f1ac177e0016a8c2d6c2cff45fc/main.ts#L51-L53), [if (checking) {](https://github.com/nancyel/header-counter/blob/69c9627403995f1ac177e0016a8c2d6c2cff45fc/main.ts#L70-L72)
This code is still useless, better would be:
```ts
const view = this.app.workspace.getActiveViewOfType(MarkdownView);
if (checking) {
	return !!view;
}
```
And then pass that view reference into the function below.

[if (!(view instanceof MarkdownView)) {](https://github.com/nancyel/header-counter/blob/69c9627403995f1ac177e0016a8c2d6c2cff45fc/main.ts#L98-L101), [if (!(view instanceof MarkdownView)) {](https://github.com/nancyel/header-counter/blob/69c9627403995f1ac177e0016a8c2d6c2cff45fc/main.ts#L116-L119)
This also serves no purpose, it's already guaranteed to be a MarkdownView because of the line above.

[new Notice(`Header Summary: ${JSON.stringify(headerSummary)}`);](https://github.com/nancyel/header-counter/blob/69c9627403995f1ac177e0016a8c2d6c2cff45fc/main.ts#L132)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[this.containerEl.createEl("h2", { text: "Settings" });](https://github.com/nancyel/header-counter/blob/69c9627403995f1ac177e0016a8c2d6c2cff45fc/main.ts#L215)
Please don't use a settings header line this, see the guidelines: [Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by nancyel** [comment]
Thanks again for the feedback with links! Changes have been made.

**Comment by joethei** [comment]
[const view = this.app.workspace.getActiveViewOfType(](https://github.com/nancyel/header-counter/blob/1dcf1368ad28dde522d7195b4f552a300cc41580/main.ts#L95-L97), [const view = this.app.workspace.getActiveViewOfType(](https://github.com/nancyel/header-counter/blob/1dcf1368ad28dde522d7195b4f552a300cc41580/main.ts#L110-L112)
As mentioned before, you should pass in the view instance you have from the command instead of retrieving it here.

[new Setting(this.containerEl).setName("Header counter").setHeading();](https://github.com/nancyel/header-counter/blob/1dcf1368ad28dde522d7195b4f552a300cc41580/main.ts#L207)
I also mentioned twice already that there should not be a header here.
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Pull request merged**
