### PR TITLE
Add plugin: Date Inserter

### PR DESCRIPTION
**Pull request by namikaze-40p**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/namikaze-40p/obsidian-date-inserter

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[Copyright (c) 2023 Lorenzo](https://github.com/namikaze-40p/obsidian-date-inserter/blob/5cf8c84db56ecb38f89ac631d8758e335e65403c/LICENSE#L3)
The year is wrong (also check that the name is correct)

["description": "This plugin can insert a date at the cursor position using a calendar.",](https://github.com/namikaze-40p/obsidian-date-inserter/blob/5cf8c84db56ecb38f89ac631d8758e335e65403c/manifest.json#L6)
Avoid including sentences like "This is a plugin that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

The hardcoded strings in your plugin are english, while you have some dynamic strings, for which there are currently only Japanese version available.
You should have all parts of your plugin translatable, and provide a english version of the dynamic strings.

**Comment by namikaze-40p** [comment]
@joethei
Thanks for the review and merge!
However, there was a typo in [this commit](https://github.com/obsidianmd/obsidian-releases/commit/3a34f407907ba4907773826a91d67165a3cdcb0b#diff-3ce999c674f451146be9000351de965fbb63c3397f70991ad617d6e9e468e5b7R10612).
What should I do in this case?

- Current: `"description": "nsert a date at the cursor position using a calendar.",`
- Right: `"description": "Insert a date at the cursor position using a calendar.",`

**Comment by joethei** [comment]
Ooops. fixed.

**Comment by namikaze-40p** [comment]
@joethei 
Thanks!

**Pull request merged**
