### PR TITLE
Adding obsidian-tab-complete plugin to community-plugins.json list

### PR DESCRIPTION
**Pull request by adaviloper**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/adaviloper/obsidian-tab-complete

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by adaviloper** [comment]
Release has been updated to include the missing files.

**Comment by adaviloper** [comment]
Are there plans to add `.idea` or `.code` to the `.gitignore` list?

**Comment by joethei** [comment]
Why are you asking?

**Comment by liamcain** [comment]
Is this still meant to be marked as a Draft?

**Comment by adaviloper** [comment]
@liamcain Yes, I'm still working on a few edge cases that popped up recently. Is it better to just close this for the time being?

**Comment by liamcain** [comment]
Yes, please. Feel free to reopen it as soon as it's ready!

**Pull request closed without merging**
