### PR TITLE
Add plugin: Hierarchical Outgoing Links

### PR DESCRIPTION
**Pull request by jasonmotylinski**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
The first image in your readme should showcase the plugin, as that is what the Bot in the #updates channel in Discord uses.

["minAppVersion": "0.15.0",](https://github.com/jasonmotylinski/hierarchical-outgoing-links/blob/ce18a1cd0339d8b8fe9b615ca9dbbb0a13d012c7/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

[// Remember to rename these classes and interfaces!](https://github.com/jasonmotylinski/hierarchical-outgoing-links/blob/ce18a1cd0339d8b8fe9b615ca9dbbb0a13d012c7/src/main.ts#L4)
Remove this comment

[return "Hierarchical Outgoing Links View";](https://github.com/jasonmotylinski/hierarchical-outgoing-links/blob/ce18a1cd0339d8b8fe9b615ca9dbbb0a13d012c7/src/view.ts#L25)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI) and remove the "View" suffix.

[this.append_links(pane, "Unresolved Links", unresolvedHierarchy);](https://github.com/jasonmotylinski/hierarchical-outgoing-links/blob/ce18a1cd0339d8b8fe9b615ca9dbbb0a13d012c7/src/view.ts#L42)
Also use sentence case here.

**Comment by jasonmotylinski** [comment]
Published a version 1.0.12 of the plugin to address the requested changes:
- Changed the first image of the README to showcase the plugin
- Bumped the minAppVersion to 1.15.2
- Removed the lingering code comment
- Changed the two UI string elements to use sentence case

**Comment by joethei** [comment]
[ return "Display hierarchical outgoing links";](https://github.com/jasonmotylinski/hierarchical-outgoing-links/blob/f0ec12f7650672d743bd0803f57ef5d4e855dd6d/src/view.ts#L25)
"Display" makes no sense here, it should just be "Hierarchical outgoing links"

**Comment by jasonmotylinski** [comment]
Fixed!
[return "Hierarchical outgoing links";](https://github.com/jasonmotylinski/hierarchical-outgoing-links/blob/6764c49e1cfbbbf8c047a0a6c2695c0cf2f3c168/src/view.ts#L25)

**Pull request merged**
