### PR TITLE
Add Style Text Plugin

### PR DESCRIPTION
**Pull request by juanjoarranz**
# I am submitting a new Community Plugin

## Repo URL
[Link to plugin repo](https://github.com/juanjoarranz/style-text-obsidian-plugin)

## Release Checklist
- [x] I have tested the plugin on
	- [x] Windows
	- [x] macOS
	- [x] Linux
	- [ ] Android (if applicable)
	- [ ] iOS (if applicable)
- [x] My GitHub release contains all required files
	- [x] main.js
	- [x] manifest.json
	- [x] styles.css (optional)
- [x] GitHub release name matches the exact version number specified in my manifest.json (Note: Use the exact version number, don't include a prefix v)
- [x] The id in my manifest.json matches the id in the community-plugins.json file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using. I have given proper attribution to these other projects in my README.md.

### CODE REVIEW

**Comment by joethei** [comment]
Please fill the pull request template.

**Comment by juanjoarranz** [comment]
> Please fill the pull request template.

Done

**Comment by joethei** [comment]
[containerEl.createEl('h1', { text: 'Style Text' });](https://github.com/juanjoarranz/style-text-obsidian-plugin/blob/2509adc03d8fea70dfd5ef0343edb51fe29d6443/src/settings.ts#L25-L27)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by juanjoarranz** [comment]
> [containerEl.createEl('h1', { text: 'Style Text' });](https://github.com/juanjoarranz/style-text-obsidian-plugin/blob/2509adc03d8fea70dfd5ef0343edb51fe29d6443/src/settings.ts#L25-L27) [Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

Done

**Pull request merged**
