### PR TITLE
Add plugin: AI File Organizer 2000

### PR DESCRIPTION
**Pull request by ashgansh**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/different-ai/file-organizer-2000

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

I apologize for the double PR in advance, I somehow could not figure out how to correctly update the previous one after I finished resolving the merge conflicts.

### CODE REVIEW

**Comment by joethei** [comment]
You should move all code files into a separate `src` folder, that makes it easier to review and maintain.

[import moment from "moment";](https://github.com/different-ai/file-organizer-2000/blob/2a3b7d6fae91c34b721fb915bfb06bd5e935d902/index.ts#L5)
Import from the Obsidian package instead, `import {moment} from 'obsidian';`

[defaultDestinationPath = "Ava/Processed";](https://github.com/different-ai/file-organizer-2000/blob/2a3b7d6fae91c34b721fb915bfb06bd5e935d902/index.ts#L12-L15)
Why are those folder paths starting with `Ava` ?

[name: "Oranize Current File",](https://github.com/different-ai/file-organizer-2000/blob/2a3b7d6fae91c34b721fb915bfb06bd5e935d902/index.ts#L467)
Typo

[name: "Append to Similar File",](https://github.com/different-ai/file-organizer-2000/blob/2a3b7d6fae91c34b721fb915bfb06bd5e935d902/index.ts#L478), [.setName("Inbox Folder")](https://github.com/different-ai/file-organizer-2000/blob/2a3b7d6fae91c34b721fb915bfb06bd5e935d902/FileOrganizerSettingTab.ts#L32), [.setName("Organization Logs")](https://github.com/different-ai/file-organizer-2000/blob/2a3b7d6fae91c34b721fb915bfb06bd5e935d902/FileOrganizerSettingTab.ts#L47), [.setName("Similar Tags")](https://github.com/different-ai/file-organizer-2000/blob/2a3b7d6fae91c34b721fb915bfb06bd5e935d902/FileOrganizerSettingTab.ts#L61), [.setName("Attachments Folder")](https://github.com/different-ai/file-organizer-2000/blob/2a3b7d6fae91c34b721fb915bfb06bd5e935d902/FileOrganizerSettingTab.ts#L75), [.setName("File Organizer Log Folder")](https://github.com/different-ai/file-organizer-2000/blob/2a3b7d6fae91c34b721fb915bfb06bd5e935d902/FileOrganizerSettingTab.ts#L90) and more
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[containerEl.createEl("h2", { text: "Features" });](https://github.com/different-ai/file-organizer-2000/blob/2a3b7d6fae91c34b721fb915bfb06bd5e935d902/FileOrganizerSettingTab.ts#L44), [containerEl.createEl("h2", { text: "Folder Configuration" });](https://github.com/different-ai/file-organizer-2000/blob/2a3b7d6fae91c34b721fb915bfb06bd5e935d902/FileOrganizerSettingTab.ts#L72), [containerEl.createEl("h2", { text: "Experimental Features" });](https://github.com/different-ai/file-organizer-2000/blob/2a3b7d6fae91c34b721fb915bfb06bd5e935d902/FileOrganizerSettingTab.ts#L119)
For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```

[const response = await fetch("https://api.openai.com/v1/chat/completions", {](https://github.com/different-ai/file-organizer-2000/blob/2a3b7d6fae91c34b721fb915bfb06bd5e935d902/modules/name.ts#L19), [const response = await fetch("https://api.openai.com/v1/chat/completions", {](https://github.com/different-ai/file-organizer-2000/blob/2a3b7d6fae91c34b721fb915bfb06bd5e935d902/modules/text.ts#L19), [const response = await fetch("https://api.openai.com/v1/chat/completions", {](https://github.com/different-ai/file-organizer-2000/blob/2a3b7d6fae91c34b721fb915bfb06bd5e935d902/modules/vision.ts#L26)
Use the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

**Comment by ashgansh** [comment]
alright done :)

> Why are those folder paths starting with Ava ?

was just a little nod to the [first obsidian plugin i worked on](https://github.com/different-ai/file-organizer-2000), but just changed it :)

**Comment by ashgansh** [comment]
@joethei any update?

**Comment by joethei** [comment]
Please be patient, the second review still needs to be done.
Also, you don't need to keep fixing the merge conflicts, we will do that when the review is done.

**Comment by liamcain** [comment]
- [likeley](https://github.com/different-ai/file-organizer-2000/blob/45b4df04d1e1f2d7f3780dd5b27b109d61c34159/README.md#L4) small typo here
- [likeley](https://github.com/different-ai/file-organizer-2000/blob/45b4df04d1e1f2d7f3780dd5b27b109d61c34159/README.md#L4) `files`?
- [file](https://github.com/different-ai/file-organizer-2000/blob/45b4df04d1e1f2d7f3780dd5b27b109d61c34159/README.md#L25) typo
- [Please enter your API Key in the settings of the OCR plugin](https://github.com/different-ai/file-organizer-2000/blob/45b4df04d1e1f2d7f3780dd5b27b109d61c34159/src/index.ts#L416) why does it say "OCR plugin" here?
- [allMarkdownFilePaths](https://github.com/different-ai/file-organizer-2000/blob/45b4df04d1e1f2d7f3780dd5b27b109d61c34159/src/index.ts#L357) looks like this is unused?
- [This CSS file will be included with your plugin, and](https://github.com/different-ai/file-organizer-2000/blob/45b4df04d1e1f2d7f3780dd5b27b109d61c34159/styles.css#L3) looks like you bundle a CSS file with your plugin but it's not used. Maybe just remove the reference to styles.css from your build output so this doesn't get generated and downloaded by Obsidian each time you create a new release.
- [validateAPIKey](https://github.com/different-ai/file-organizer-2000/blob/45b4df04d1e1f2d7f3780dd5b27b109d61c34159/src/index.ts#L47) this is throwing an Error but you're not catching it anywhere. You should wrap this in a try/catch and ensure that the error is surfaced to the user at some point, otherwise it will fail silently.

**Comment by ashgansh** [comment]
will fix all of these over the w-e thanks @liamcain

**Pull request merged**
