### PR TITLE
Add plugin: Peerdraft

### PR DESCRIPTION
**Pull request by schlundd**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/peerdraft/obsidian-plugin

## Release Checklist
- [X] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [X]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by schlundd** [comment]
Check failed because I was not a public member of the org. Should be fixed now.

**Comment by schlundd** [comment]
One additional note: The project page says that you need an account. However, this is not enforced, yet. The plugin just works.

**Comment by joethei** [comment]
["fundingUrl": "https://www.peerdraft.app",](https://github.com/peerdraft/obsidian-plugin/blob/66e8089220939c9fc2b4de3ef1847ceaff855beb/manifest.json#L9)
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link omit this.
["author": "Taskbone",](https://github.com/peerdraft/obsidian-plugin/blob/66e8089220939c9fc2b4de3ef1847ceaff855beb/manifest.json#L7)

[checkCallback: (checking: boolean) => {](https://github.com/peerdraft/obsidian-plugin/blob/66e8089220939c9fc2b4de3ef1847ceaff855beb/src/main.ts#L21), [checkCallback: (checking: boolean) => {](https://github.com/peerdraft/obsidian-plugin/blob/66e8089220939c9fc2b4de3ef1847ceaff855beb/src/main.ts#L58)
Use a `editorCallback` here.

[getSettings(plugin).then(settings => {](https://github.com/peerdraft/obsidian-plugin/blob/66e8089220939c9fc2b4de3ef1847ceaff855beb/src/main.ts#L32)
[prefer async/await over Promise](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Prefer%20async/await%20over%20Promise)

[item.setTitle("Copy Link")](https://github.com/peerdraft/obsidian-plugin/blob/66e8089220939c9fc2b4de3ef1847ceaff855beb/src/statusbar.ts#L12)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

---

[{ color: '#30bced', light: '#30bced33' },](https://github.com/peerdraft/obsidian-plugin/blob/66e8089220939c9fc2b4de3ef1847ceaff855beb/src/editor.ts#L10-L17)
Shouldn't it be `dark´ and `light` ?
Or is that required by one of the dependencies?

**Comment by schlundd** [comment]
Thanks for making me aware of editorCallback.

Should all be fixed now.

**Comment by schlundd** [comment]
Ah, forgot one instance of checkCallback. Wait...

**Comment by schlundd** [comment]
All done.

**Comment by liamcain** [comment]
- [initDocument](https://github.com/peerdraft/obsidian-plugin/blob/6cab08079074cc710096c4fb8d8d34d001dd7277/src/document.ts#L16) I'm not seeing any error handling. What happens if the user is not authenticated and they trigger any of the commands?
- [plugin.addStatusBarItem](https://github.com/peerdraft/obsidian-plugin/blob/6cab08079074cc710096c4fb8d8d34d001dd7277/src/statusbar.ts#L30) why are you managing more than one statusbar? wouldn't it be much easier to just update one statusbar? They you don't risk the statusbar items moving in the statusbar (since newer statusbar items will be added to the left, this will make the order unpredictable)
- [onunload](https://github.com/peerdraft/obsidian-plugin/blob/6cab08079074cc710096c4fb8d8d34d001dd7277/src/main.ts#L63) unload will not be called when the user quits Obsidian, only when the plugin is disabled. You'll need to add a 'quit' event handler for this to be properly cleaned up.

**Pull request merged**
