### PR TITLE
add Obsidian Chevereto Image Uploader

### PR DESCRIPTION
**Pull request by kkzzhizhou**
# I am submitting a new Community Plugin
## Repo URL
Link to my plugin: https://github.com/kkzzhizhou/obsidian-chevereto-image-uploader
## Release Checklist
- [x] I have tested this on Windows only.
- [x] My GitHub release contains all required files
  - [x]  main.js
  - [x] manifest.json
- [x] GitHub release name matches the exact version number specified in my manifest.json (Note: Use the exact version number, don't include a prefix v) 
- [x] The id in my manifest.json matches the id in the community-plugins.json file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/kkzzhizhou/obsidian-chevereto-image-uploader/blob/4c3e32e6b2fda4e82ed81a476f82b5f64cf95494/src/main.ts#L67
Instead of hooking onto CodeMirror, you can now use `paste` and `drop` events from `Workspace`, which helps avoid dependency on CodeMirror 5's API and also makes sure that your plugin doesn't have to manage overriding paste/drop handlers.

**Comment by lishid** [comment]
Let me know once you upgrade your plugin to use the new handlers and we can continue the review from there.

**Comment by lishid** [comment]
There's been a very similar plugin you can inspire from here: https://github.com/jordanhandy/obsidian-cloudinary-uploader/blob/main/src/main.ts

**Comment by kkzzhizhou** [comment]
> There's been a very similar plugin you can inspire from here: https://github.com/jordanhandy/obsidian-cloudinary-uploader/blob/main/src/main.ts

thanks for reply. I will check that later.

**Comment by ericaxu** [comment]
Hi there, to keep things tidy, we're going to temporarily close plugin PRs after a month of inactivity.

Feel free to tell us to re-open it when you're ready to continue. Thanks for your understanding!

**Comment by kkzzhizhou** [comment]
> Hi there, to keep things tidy, we're going to temporarily close plugin PRs after a month of inactivity.
> 
> Feel free to tell us to re-open it when you're ready to continue. Thanks for your understanding!

I have already fix the code that you told. Please reopen the pr to check again. Thank you.

**Comment by lishid** [comment]
https://github.com/jordanhandy/obsidian-cloudinary-uploader/blob/2cab25efd73dc752de314b17af8408e9314dbf55/src/main.ts#L42
This logic seems faulty - if `files.length` is equal to 0 then it shouldn't be able to access `files[0]`.

https://github.com/jordanhandy/obsidian-cloudinary-uploader/blob/2cab25efd73dc752de314b17af8408e9314dbf55/src/main.ts#L47
Need to move this up one line.

https://github.com/jordanhandy/obsidian-cloudinary-uploader/blob/2cab25efd73dc752de314b17af8408e9314dbf55/src/main.ts#L79
You don't want to do this - because `editor-paste` runs for every paste event. Doing so will break regular pasting text.

https://github.com/jordanhandy/obsidian-cloudinary-uploader/blob/2cab25efd73dc752de314b17af8408e9314dbf55/src/main.ts#L90
Instead of using `getValue()` and `split('\n')`, you should use `getLine()` and `lineCount`.

**Comment by kkzzhizhou** [comment]
> https://github.com/jordanhandy/obsidian-cloudinary-uploader/blob/2cab25efd73dc752de314b17af8408e9314dbf55/src/main.ts#L42 This logic seems faulty - if `files.length` is equal to 0 then it shouldn't be able to access `files[0]`.
> 
> https://github.com/jordanhandy/obsidian-cloudinary-uploader/blob/2cab25efd73dc752de314b17af8408e9314dbf55/src/main.ts#L47 Need to move this up one line.
> 
> https://github.com/jordanhandy/obsidian-cloudinary-uploader/blob/2cab25efd73dc752de314b17af8408e9314dbf55/src/main.ts#L79 You don't want to do this - because `editor-paste` runs for every paste event. Doing so will break regular pasting text.
> 
> https://github.com/jordanhandy/obsidian-cloudinary-uploader/blob/2cab25efd73dc752de314b17af8408e9314dbf55/src/main.ts#L90 Instead of using `getValue()` and `split('\n')`, you should use `getLine()` and `lineCount`.

Thanks for your reply.

The list above belong to the plugin https://github.com/jordanhandy/obsidian-cloudinary-uploader.

My plugin is https://github.com/kkzzhizhou/obsidian-chevereto-image-uploader. the main.ts is https://github.com/kkzzhizhou/obsidian-chevereto-image-uploader/blob/main/src/main.ts

I test the plugin in my windows. it work well. if any question about the plugin，i glad to listen.

**Comment by lishid** [comment]
Oops! My bad, I clicked the wrong link 🤦

**Comment by lishid** [comment]
https://github.com/kkzzhizhou/obsidian-chevereto-image-uploader/blob/d64de3deb281f1571e12452fcc3e4495ca8cd45b/src/main.ts#L49 
This check should be `files.length > 0 && files[0].type.startsWith("image")`.

Actually, you should also check for `file.type.startsWith("image")` for each file as well.

https://github.com/kkzzhizhou/obsidian-chevereto-image-uploader/blob/d64de3deb281f1571e12452fcc3e4495ca8cd45b/src/main.ts#L51
Need to move this up one line.

https://github.com/kkzzhizhou/obsidian-chevereto-image-uploader/blob/d64de3deb281f1571e12452fcc3e4495ca8cd45b/src/main.ts#L89

Instead of using getValue() and split('\n'), you can directly iterate the lines of the document using `lineCount()` and `getLine()`.

**Comment by kkzzhizhou** [comment]
> https://github.com/kkzzhizhou/obsidian-chevereto-image-uploader/blob/d64de3deb281f1571e12452fcc3e4495ca8cd45b/src/main.ts#L49 This check should be `files.length > 0 && files[0].type.startsWith("image")`.
> 
> Actually, you should also check for `file.type.startsWith("image")` for each file as well.
> 
> https://github.com/kkzzhizhou/obsidian-chevereto-image-uploader/blob/d64de3deb281f1571e12452fcc3e4495ca8cd45b/src/main.ts#L51 Need to move this up one line.
> 
> https://github.com/kkzzhizhou/obsidian-chevereto-image-uploader/blob/d64de3deb281f1571e12452fcc3e4495ca8cd45b/src/main.ts#L89
> 
> Instead of using getValue() and split('\n'), you can directly iterate the lines of the document using `lineCount()` and `getLine()`.

Thanks for your advise.

I have already update the code. see here:  https://github.com/kkzzhizhou/obsidian-chevereto-image-uploader/blob/main/src/main.ts

**Comment by lishid** [comment]
https://github.com/kkzzhizhou/obsidian-chevereto-image-uploader/blob/bf829d59c04a71a28bfadb0847f5c571dea6175e/src/main.ts#L47
Here I highly suggest adding a check for `if (evt.defaultPrevented) return;` so that if the image is already uploaded by another plugin first, you don't process it twice.

**Pull request merged**
