### PR TITLE
Add Folder Focus Mode Plugin

### PR DESCRIPTION
**Pull request by grochowski**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/grochowski/obsidian-folder-focus-mode

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by aidenlx** [comment]
I think maybe your plugin shares something in common with [alx-folder-note's focus folder feature](https://github.com/aidenlx/alx-folder-note/releases/tag/0.12.2)?

**Comment by liamcain** [comment]
https://github.com/grochowski/obsidian-folder-focus-mode/blob/699eaa00d1c8da88a884effc9e859e083aa36f62/main.ts#L51-L53 I don't think this logic is correct. You're looping over the list of registered file explorers for each iteration of the outer loop. The `registeredFileExplorers` var isn't doing anything here so I think you want to just get rid of inner loop and perform the operations on `fileExplorer.view`.

https://github.com/grochowski/obsidian-folder-focus-mode/blob/699eaa00d1c8da88a884effc9e859e083aa36f62/main.ts#L84-L86 same here.

https://github.com/grochowski/obsidian-folder-focus-mode/blob/699eaa00d1c8da88a884effc9e859e083aa36f62/main.ts#L139 getActiveFile can return null. You might want to use `checkCallback` here instead so that this command can only be run when there is an active file.

https://github.com/grochowski/obsidian-folder-focus-mode/blob/699eaa00d1c8da88a884effc9e859e083aa36f62/main.ts#L3 `path` is a node library so this might break on mobile, I'm not positive since I see you're also installing it from npm, but I think it's still an issue.

https://github.com/grochowski/obsidian-folder-focus-mode/blob/699eaa00d1c8da88a884effc9e859e083aa36f62/main.ts#L88 you should use `const` instead of `var` here

**Comment by grochowski** [comment]
@liamcain thanks for the feedback! resolved mentioned issues in new release (0.9.2) - also, I've checked it on mobile and now it works just right :)

**Review by liamcain — APPROVED** [review]
Changes look good! This will get merged shortly.

**Pull request merged**
