### PR TITLE
Adding the Enlightenment plugin

### PR DESCRIPTION
**Pull request by ryanjamurphy**
# [x] I am submitting a new Community Plugin

## Repo URL

https://www.github.com/ryanjamurphy/enlightenment-obsidian

## Release Checklist

- [x] I have tested this on ~~Windows,~~ macOS~~, and Linux~~ _(if applicable)_
    - We should probably add "mobile" to this checklist!
- [x] Github release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] Github release name matches the exact version number specified in your manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.

### CODE REVIEW

**Comment by ericaxu** [comment]
https://github.com/ryanjamurphy/enlightenment-obsidian/blob/master/main.ts#L3

Does this work? I think you only need the path part. Make it `<path fill="currentColor" stroke="currentColor" d="..."/>`.

According to the API file, the parameter `svgContent` is
> the content of the SVG, without the <svg>. Must fit viewBox="0 0 100 100".`

https://github.com/ryanjamurphy/enlightenment-obsidian/blob/master/main.ts#L53
Nit: single quotes please for consistency.

Otherwise looks good to me! 👍

**Comment by lishid** [comment]
https://github.com/ryanjamurphy/enlightenment-obsidian/blob/master/.DS_Store
Add this to your `.gitignore`?

https://github.com/ryanjamurphy/enlightenment-obsidian/blob/1aa5c92aa235294f841e50f41674e39cc310f01c/main.ts#L50
This command says "across all panes" but it still checks for an active pane. Maybe just make it a regular `callback` rather than a `checkCallback`.

https://github.com/ryanjamurphy/enlightenment-obsidian/blob/1aa5c92aa235294f841e50f41674e39cc310f01c/main.ts#L112
Why are you creating an empty style element here? Doesn't seem to do anything.

**Comment by ericaxu** [comment]
Will be reopened when the comments get resolved.

**Comment by ryanjamurphy** [comment]
(misclicked when I deleted that branch. Oops.)

Finally getting back to this! Let me know if I need to re-add it for you to review.

@ericaxu:
> Does this work? I think you only need the path part. Make it <path fill="currentColor" stroke="currentColor" d="..."/>.

I tried to remove the cruft. Lemme know? Starting at https://github.com/ryanjamurphy/enlightenment-obsidian/blob/master/main.ts#L3.

> Nit: single quotes please for consistency.

Fixed!

@lishid: 

> Add this to your .gitignore?

Done, sorry.

> This command says "across all panes" but it still checks for an active pane. Maybe just make it a regular callback rather than a checkCallback.

Done!

> Why are you creating an empty style element here? Doesn't seem to do anything.

The idea was to make sure that element existed, then to add classes to it. (The next line appends the empty style to `head` then, later in the function, I add an ID to the appended element. Open to better ideas!

**Pull request closed without merging**
