### PR TITLE
Add Grandfather plugin

### PR DESCRIPTION
**Pull request by noatpad**
# [x] I am submitting a new Community Plugin

## Repo URL

https://github.com/noatpad/obsidian-grandfather

## Release Checklist

- [x] I have tested this on ~~Windows~~, **macOS**, and ~~Linux~~ _(if applicable)_
- [x] Github release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - `styles.css` _(optional)_
- [x] Github release name matches the exact version number specified in your manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.

### CODE REVIEW

**Comment by ericaxu** [comment]
Interesting plugin! Looks good to me.

Just curious, why did you name it "Grandfather"?

**Comment by lishid** [comment]
https://github.com/noatpad/obsidian-grandfather/blob/ce2045641d8712321c0b52eab718485fa25ca904/src/main.ts#L11
Not sure where you picked up this code, the recommended way to load settings is now `Object.assign` (see https://github.com/obsidianmd/obsidian-sample-plugin/blob/c228a7022301e4a74614a67570d38ed2e2e05a71/main.ts#L60)

Also, yeah, very curious about the plugin name.

**Comment by noatpad** [comment]
The line for loading settings was just an alternate way I thought of doing it, haha. Just changed it to the recommended way, so that should do it.

And the name is actually just a lil' wordplay from me, with "Grandfather" just being a lil' nod to a grandfather clock. I like naming things a bit cryptically that way, haha

**Comment by lishid** [comment]
> The line for loading settings was just an alternate way I thought of doing it, haha. Just changed it to the recommended way, so that should do it.

We used to do it the old way, but it's actually a bit different in that the default settings wouldn't be properly upgraded when you add new items to the object:
```ts
// If loadData returns an object with {firstSetting}, but your plugin has two 
// settings {firstSetting, secondSetting}, you will now run into secondSetting is undefined
this.settings = await this.loadData() || DEFAULT_SETTINGS;
```

**Pull request merged**
