### PR TITLE
Add plugin Heading Level Indent

### PR DESCRIPTION
**Pull request by svonjoi**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [svonjoi/obsidian-heading-level-indent](https://github.com/svonjoi/obsidian-heading-level-indent)

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by svonjoi** [comment]
changed authorUrl

**Comment by svonjoi** [comment]
check again

**Comment by joethei** [comment]
Have you tested that this works in popout windows?
`document` refers to the main window, `activeDocument` will refer to whatever window is currently focused.

**Comment by svonjoi** [comment]
> Have you tested that this works in popout windows? `document` refers to the main window, `activeDocument` will refer to whatever window is currently focused.

You mean popups from plugin [hover editor](https://github.com/nothingislost/obsidian-hover-editor)? It works in popup's but in order to apply margins on the fly while scrolling, the popup or main window must be focused.
I've tested with `activeDocument` and it has the same effect

**Comment by joethei** [comment]
No, I mean Obsidian's pop-out windows: <https://help.obsidian.md/User+interface/Pop-out+windows>

**Comment by svonjoi** [comment]
> No, I mean Obsidian's pop-out windows: https://help.obsidian.md/User+interface/Pop-out+windows

Yes it works, the same behaviour as in case with hover editor

**Comment by svonjoi** [comment]
> No, I mean Obsidian's pop-out windows: https://help.obsidian.md/User+interface/Pop-out+windows

Released 1.0.2 with the fix. Thanks for the indication

**Comment by liamcain** [comment]
- [app](https://github.com/svonjoi/obsidian-heading-level-indent/blob/e102682d0ca690be684152f485dbc2985064fdd9/src/main.ts#L69) This should be this.app, I think you're accidentally using the global app object here.

**Comment by svonjoi** [comment]
> * [app](https://github.com/svonjoi/obsidian-heading-level-indent/blob/e102682d0ca690be684152f485dbc2985064fdd9/src/main.ts#L69) This should be this.app, I think you're accidentally using the global app object here.

Yes, thanks for the help

**Pull request merged**
