### PR TITLE
Add plugin: File Explorer Reload

### PR DESCRIPTION
**Pull request by mnaoumov**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

https://github.com/mnaoumov/obsidian-file-explorer-reload

## Release Checklist
- [X] I have tested the plugin on
  - [X]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [X] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Can you link to a bug report for the issue you are attempting to fix?
I can't find a fitting one.

[import * as fsPromises from "fs/promises";](https://github.com/mnaoumov/obsidian-file-explorer-reload/blob/284594ddb20f52d8ee6d876d09368f0b0b3b9a94/FileExplorerReloadPlugin.ts#L8)
This import is available from a Node.js runtime, which means that this will throw errors on Mobile (that's a problem since you have `isDesktopOnly` marked as `false` in your manifest.json file.

[const dir = this.app.vault.getAbstractFileByPath(directoryPath) as TFolder;](https://github.com/mnaoumov/obsidian-file-explorer-reload/blob/284594ddb20f52d8ee6d876d09368f0b0b3b9a94/FileExplorerReloadPlugin.ts#L46)
This should never be casted, always do a `instanceof` check to confirm that it's actually a directory.

**Comment by joethei** [comment]
Also, have you restarted your computer recently?

**Comment by mnaoumov** [comment]
@joethei 

1. I created a [bug report](https://forum.obsidian.md/t/sometimes-changes-made-outside-of-obsidian-are-not-reflected-in-the-files-pane/73451) and added the link to it in the plugin's `README`.
2. Yes, good point, switched to `isDesktopOnly = true` in the release 1.2.0
3. Yes, good point, changed in the release 1.2.0

**Comment by liamcain** [comment]
Thanks for surfacing the bug and creating a testing vault. And nice job with the plugin! I don't think we want to introduce this plugin to the list of Community plugins though since it's our hope to solve the problem on our end without a plugin making calls to private APIs within the file system adapter.

We will investigate further to see if we can find the root cause. Hope you understand!

**Comment by liamcain** [comment]
Hopefully when users encounter a bug in Obsidian, their first instinct isn't to look for a plugin that safely patches into the internals of the app to fix the bug. Instead, they should go through the forums or official communication channels so that we can better understand the total breadth of who is affected by the bug and get more useful metrics and debugging information.

We would rather not promote these workarounds.

**Comment by mnaoumov** [comment]
@liamcain I found the root cause for the bug, the plugin intended to workaround, and provided the suggestion for the team how to fix it.

https://forum.obsidian.md/t/sometimes-changes-made-outside-of-obsidian-are-not-reflected-in-the-files-pane/73451/6

**Comment by DeanLemans** [comment]
bump

**Pull request closed without merging**
