### PR TITLE
add table-of-contents plugin

### PR DESCRIPTION
**Pull request by hipstersmoothie**

### CODE REVIEW

**Comment by lishid** [comment]
Pretty cool! Couple of suggestions:

https://github.com/hipstersmoothie/obsidian-plugin-toc/blob/95b3f849df512cbec7d364ca0420212bb2839be1/src/main.ts#L106
I don't think this is needed here.

https://github.com/hipstersmoothie/obsidian-plugin-toc/blob/95b3f849df512cbec7d364ca0420212bb2839be1/src/main.ts#L112
Don't use this - instead use `Workspace.getActiveViewOfType(MarkdownView)`.

https://github.com/hipstersmoothie/obsidian-plugin-toc/blob/95b3f849df512cbec7d364ca0420212bb2839be1/src/create-toc.ts#L51
You may be interested in our indexed version of headings, which are actually parsed from the markdown, so you don't run into the cases where your regex recognizes headings that are in fenced code blocks. Look for `App.metadataCache.getFileCache(file)`

**Comment by hipstersmoothie** [comment]
I've made all the changes you wanted! That heading cache really made the code a bit more straightforward. Thanks for the tips!

**Comment by lishid** [comment]
Ok getting close 👍 

https://github.com/hipstersmoothie/obsidian-plugin-toc/blob/62f9b667da555e28e628c479d5d75712c9ce62c7/src/main.ts#L113
Same as your other plugin - do a truthy check here and rename `activeLeaf` to `activeView`.

https://github.com/hipstersmoothie/obsidian-plugin-toc/blob/62f9b667da555e28e628c479d5d75712c9ce62c7/src/main.ts#L121
Seems like you're doing `getActiveFile` twice here. Not sure what the intent here but would be worth checking the logic here about what you'd want to be not null. You can also use `activeView.file` to get the view's file too as a shortcut.

https://github.com/hipstersmoothie/obsidian-plugin-toc/blob/62f9b667da555e28e628c479d5d75712c9ce62c7/src/main.ts#L139
This function seems very similar to the previous one. Might be worth combining the two?

**Comment by hipstersmoothie** [comment]
All changes pushed!

**Comment by lishid** [comment]
Cool looks good. I've merged the PR!

Probably missed this comment by the way:
> You can also use `activeView.file` to get the view's file too as a shortcut.
https://github.com/hipstersmoothie/obsidian-plugin-toc/blob/0272c76969b128ed9c6a0a93aec61fd9e2fe9564/src/main.ts#L150

**Comment by hipstersmoothie** [comment]
Pushed an update for that too. Thanks for the code reviews!

**Pull request merged**
