### PR TITLE
Add plugin: SwiftLaTeX Render

### PR DESCRIPTION
**Pull request by gboyd068**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/gboyd068/obsidian-swiftlatex-render

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[console.log("Using cached PDF: ", md5Hash);](https://github.com/gboyd068/obsidian-swiftlatex-render/blob/98f7f0d665f68fde9bec6881dbbac216cc81bff7/main.ts#L163), [console.log("Rendering PDF: ", md5Hash);](https://github.com/gboyd068/obsidian-swiftlatex-render/blob/98f7f0d665f68fde9bec6881dbbac216cc81bff7/main.ts#L170)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[containerEl.createEl('h2', { text: 'SwiftLaTeX Render Settings' });](https://github.com/gboyd068/obsidian-swiftlatex-render/blob/98f7f0d665f68fde9bec6881dbbac216cc81bff7/main.ts#L342)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[.setName('Package Fetching URL')](https://github.com/gboyd068/obsidian-swiftlatex-render/blob/98f7f0d665f68fde9bec6881dbbac216cc81bff7/main.ts#L345)

[PdfTeXEngine](https://github.com/gboyd068/obsidian-swiftlatex-render/blob/98f7f0d665f68fde9bec6881dbbac216cc81bff7/PdfTeXEngine.js), [swiftlatexpdftex.worker.js](https://github.com/gboyd068/obsidian-swiftlatex-render/blob/master/swiftlatexpdftex.worker.js)
These files are compiled/transpiled, which we don't review.
Where can I find the original code?

**Comment by gboyd068** [comment]
Thanks, I will make those small changes.
As mentioned in my readme, the source code for the compiled files is in https://github.com/gboyd068/SwiftLaTeX

**Comment by joethei** [comment]
["description": "Render LaTeX inline using a SwiftLaTeX, a WebAssembly LaTeX compiler.",](https://github.com/gboyd068/obsidian-swiftlatex-render/blob/b8c6264c28fc56aeb5a8bb2fc2cb5a932d13b879/manifest.json#L6)
This should be a description of what the plugin is doing, not how it's doing it.
"using a SwiftLaTeX, a WebAssembly LaTeX compiler." can be removed.
And you are also not rendering it inline, as the plugin is using a codeblock.

**Comment by gboyd068** [comment]
Hi @joethei, I have made that change. Is there any way that I can help the review process for the source of the compiled code? For example, would it be preferable to you if all of the source code was in one repo, rather than spread out over the two I have provided?

**Pull request merged**
