### PR TITLE
Add plugin: Shiki Highlighter

### PR DESCRIPTION
**Pull request by mProjectsCode**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/mProjectsCode/obsidian-shiki-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by mProjectsCode** [comment]
/skip

`.obsidian` and the `console.log`-s are in repo automation code and not code that is bundled into the plugin.

The string set to `.innerHTML` comes straight from a HTML AST library, so it's safe to assume that this write to `.innerHTML` is safe.

**Comment by joethei** [comment]
Some screenshots would be nice.
(also a small hint, the first image in the readme gets used by Botsidian in the #updates channel)

[Copyright (c) 2023 Moritz Jung](https://github.com/mProjectsCode/obsidian-shiki-plugin/blob/d43529d246ed7acd7f470d986521e32a329b551d/LICENSE#L3)
Year.

**Comment by mProjectsCode** [comment]
Fixed the year in the license, will add some screenshots later.
Thanks for the quick review. :)

**Comment by mProjectsCode** [comment]
I added an example image to the readme.

**Pull request merged**
