### PR TITLE
Add plugin: Collapse Linked Mentions

### PR DESCRIPTION
**Pull request by n810K**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/n810K/obsidian-collapse-linked-mentions

## Release Checklist
- [x] I have tested the plugin on
  - [X]  Windows
  - [X]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [X] `main.js`
  - [X] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [X] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[document.getElementById('my-plugin-style')](https://github.com/n810K/obsidian-collapse-linked-mentions/blob/24217d404b1d2b9411fdfca306e8fc6a351e4c72/main.ts#L31), [style.id = 'my-plugin-style';](https://github.com/n810K/obsidian-collapse-linked-mentions/blob/24217d404b1d2b9411fdfca306e8fc6a351e4c72/main.ts#L34)
This is too generic.

[containerEl.createEl('h2', { text: 'Collapse Linked Mentions Settings' });](https://github.com/n810K/obsidian-collapse-linked-mentions/blob/24217d404b1d2b9411fdfca306e8fc6a351e4c72/main.ts#L82-L83)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[.setName('Minimum Height')](https://github.com/n810K/obsidian-collapse-linked-mentions/blob/24217d404b1d2b9411fdfca306e8fc6a351e4c72/main.ts#L85)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by n810K** [comment]
@joethei 
1) https://github.com/n810K/obsidian-collapse-linked-mentions/blob/50698d2a380bc73f062661f8e491a19ab4fac5aa/main.ts#L31C1-L31C95 - Resolved
2) https://github.com/n810K/obsidian-collapse-linked-mentions/blob/50698d2a380bc73f062661f8e491a19ab4fac5aa/main.ts#L34 - Resolved
3) https://github.com/n810K/obsidian-collapse-linked-mentions/blob/50698d2a380bc73f062661f8e491a19ab4fac5aa/main.ts#L82 - Resolved
4) https://github.com/n810K/obsidian-collapse-linked-mentions/blob/50698d2a380bc73f062661f8e491a19ab4fac5aa/main.ts#L85 - Resolved

**Comment by joethei** [comment]
[ containerEl.createEl('h2', { text: 'Collapse Linked Mentions' });](https://github.com/n810K/obsidian-collapse-linked-mentions/blob/50698d2a380bc73f062661f8e491a19ab4fac5aa/main.ts#L82)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by n810K** [comment]
@joethei Resolved again. Sorry about that

**Pull request merged**
