### PR TITLE
Add link heading range

### PR DESCRIPTION
**Pull request by Limezy**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/AnthropologieBiblique/link-heading-range

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by liamcain** [comment]
Hi @Limezy, this is a cool plugin. One thing you might want to consider though: `[[page#heading1#heading2]]` already has a meaning in Obsidian. It creates a nested link. It allows for linking in a document that looks like this:

```md
# Page 1
## Summary

lorem ipsum

# Page 2
## Summary

lorem ipsum
```

In this document, you can link to `[[#Page 1#Summary]]` or `[[#Page2#Summary]]`.

For this reason, I wonder if it makes sense to change the syntax to something else.

If you're okay with overriding the default Obsidian behavior, you might want to make a note somewhere in the README about this tradeoff.

**Comment by Limezy** [comment]
Hi @liamcain, many thanks for your review and sorry for my late reply - lots of things going on at work at the moment.
I was completely unaware of the fact that the grammar [[#...#...]] already existed. I will try to check in depth whether there are potential conflicts with my plugin proposal, and either amend the grammar of the link to heading range, either be clear in the README about what are the changes to be expected.
Please give me a few more days for that !

**Comment by Limezy** [comment]
Hi @liamcain, 

I'm not forgetting this WIP ! I was very fortunate that @Mallioch has offered his help to develop this plugin.
He is much more professional than me and has already managed to get a version working on Live Preview 👍 

We have discussed about the issue you have raised. Our plan is currently to change from the [[...#...#...]] syntax to the [[...#...>...]] syntax. Do you see any problem with that ?

We will wait for the PR https://github.com/AnthropologieBiblique/link-heading-range/pull/4 to be merged and then come back here to get the plugin into the official list !

Thanks again for your wait and advice

**Comment by liamcain** [comment]
I think switching to > is fine!

**Comment by ericaxu** [comment]
@Limezy Hi! Is there any update on this?

**Comment by Mallioch** [comment]
You can expect some updates from me on this soon.

**Comment by Limezy** [comment]
Hi @ericaxu sorry for the long wait. I got some help very nicely proposed by @Mallioch and we decided not to push that plugin to the community repo before he lands his much better and improved version !

**Comment by ericaxu** [comment]
Thank you! Was doing some spring cleaning and want to make sure the open PRs are actually active :)

**Comment by ericaxu** [comment]
> Hi @ericaxu sorry for the long wait. I got some help very nicely proposed by @Mallioch and we decided not to push that plugin to the community repo before he lands his much better and improved version !

Since it would take some time, to keep things tidy, we're going to temporarily close plugin PRs after a month of inactivity.

This by no means mean you shouldn't continue working on this project! Feel free to tell us to re-open it when you're ready to continue. Thanks for your understanding!

**Comment by Mallioch** [comment]
It's all good. Working on it with an eye on another plugin at the moment.

**Comment by ericaxu** [comment]
> It's all good. Working on it with an eye on another plugin at the moment.

Excellent! Ping us any time if you want to reopen this PR.

**Pull request closed without merging**
