### PR TITLE
Add theme: mono black (monochrome, charcoal)

### PR DESCRIPTION
**Pull request by ZeChArtiahSaher**
finally a fully black monochrome theme

## Repo URL

https://github.com/ZeChArtiahSaher/obsidian-mono-black

## Theme checklist

- [x] My repo contains all required files (please do not add them to this obsidian-releases repo).

    - [x] manifest.json
    - [x] theme.css
    - [x] The screenshot file (16:9 aspect ratio, recommended size is 512px by 288px for fast loading).

- [x] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my theme's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Themes/App+themes/Theme+guidelines and have self-reviewed my theme to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other themes that I'm using. I have given proper attribution to these other themes in my README.md.

### CODE REVIEW

**Comment by ZeChArtiahSaher** [comment]
meow

**Comment by joethei** [comment]
Some screenshots in the readme would be nice.

["authorUrl": "none"](https://github.com/ZeChArtiahSaher/obsidian-mono-black/blob/07d80c3f392f825921dd1b25fe38475fc298d47e/manifest.json#L6)
Add the link to your GitHub profile here.

**Comment by ZeChArtiahSaher** [comment]
Added authorUrl, added a screenshot to repo. Thank you

**Comment by ZeChArtiahSaher** [comment]
Actually I have one more question is it okay later down the line to push something named obsidian-mono? That will have both white and black themes. Currently I just have one but I realized for completeness it would make sense not to call it black later :D

**Comment by joethei** [comment]
You can't have Obsidian in the name, other than that you can do that.
Just keep in mind that updating the theme name of this one is now is no longer possible.

**Comment by ZeChArtiahSaher** [comment]
okay!

**Comment by ZeChArtiahSaher** [comment]
yeah I mean like I will just have a repo mirror and it will be called like **mono** or something.

**Pull request merged**
