### PR TITLE
Add plugin: Typefully

### PR DESCRIPTION
**Pull request by dsebastien**
# I am submitting a new Community Plugin

## Repo URL
Link to my plugin: https://github.com/dsebastien/obsidian-typefully

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by dsebastien** [comment]
I've changed the plugin id to `typefully` and released v1.2.7: https://github.com/dsebastien/obsidian-typefully/releases/tag/1.2.7

**Comment by dsebastien** [comment]
Hello,

I have renamed the plugin class name, and I have released version 1.2.8.

I have kept the command name as is, because the name is actually important. Users need to know what the command will actually do, which is sending data to the Typefully service in this case.

**Comment by joethei** [comment]
In the command pallete and in the hotkey settings the command will show up as: `Typefully: Publish the current note to Typefully`
That can be shortened to just be `Typefully: Publish the current note`

**Comment by dsebastien** [comment]
Good point! I've released v1.2.9 to fix that. It should be available in a few minutes

**Comment by joethei** [comment]
[export const getFileTags = (file: TFile | null, app: App): string[] => {](https://github.com/dsebastien/obsidian-typefully/blob/05bca8111cf72be7517406a51d7217fc755e7af0/apps/plugin/src/app/utils/get-file-tags.fn.ts#L8-L32)
There is the [`getAllTags`](https://docs.obsidian.md/Reference/TypeScript+API/getAllTags) function which does the same.

[imgEl.src =](https://github.com/dsebastien/obsidian-typefully/blob/05bca8111cf72be7517406a51d7217fc755e7af0/apps/plugin/src/app/settingTab/index.ts#L183-L184)
This should be bundled into the plugin, not loaded externally.

**Comment by dsebastien** [comment]
I am using the getAllTags function. My function is just changing the output to the form I need elsewhere in the app.

**Comment by dsebastien** [comment]
Hello @joethei, could you take a look at this PR?
There's another plugin I'd like to propose soon :))

**Comment by dsebastien** [comment]
I sill have hope for this plugin, but it feels quite lonely here :)

**Pull request merged**
