### PR TITLE
Add PostgreSQL plugin

### PR DESCRIPTION
**Pull request by clouedoc**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/clouedoc/postgresql-obsidian

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by liamcain** [comment]
[export class SampleModal](https://github.com/clouedoc/postgresql-obsidian/blob/6c55b3b9937d9417348ec47fbd3d351728fe434e/src/classes/sample-modal.ts#L3) this can be removed

[const dv: DataviewApi = getAPI();](https://github.com/clouedoc/postgresql-obsidian/blob/38cfeba2ffba8fd82083ecba5932dd65618c3262/src/classes/postgresql-plugin.ts#L17) This will fail if your plugin loads before dataview. You should only call this after Obsidian has fully loaded. You can just move this the command callback

[this.app.workspace.getActiveFile()](https://github.com/clouedoc/postgresql-obsidian/blob/38cfeba2ffba8fd82083ecba5932dd65618c3262/src/classes/postgresql-plugin.ts#L25) this can be null, you should add a check for that.

---

Can you add more information to the readme about how a user should setup the database? I was assuming you were using a local DB while looking at the code but then I noticed your readme uses a db as a service.

**Comment by clouedoc** [comment]
@liamcain `this.app.workspace.getActiveFile()` TypeScript definition should indicate that the file can be null.
Do you think that I could propose this change?

I updated the plugin to apply your suggestions. Would you mind reviewing my latest commit?

**Comment by lishid** [comment]
> @liamcain `this.app.workspace.getActiveFile()` TypeScript definition should indicate that the file can be null.
> Do you think that I could propose this change?

It already does:
```ts
getActiveFile(): TFile | null;
```
https://github.com/obsidianmd/obsidian-api/blob/4583a6b8305b05139c6b1bf226ad15e50a9a5987/obsidian.d.ts#L3809

**Comment by clouedoc** [comment]
@lishid you're right

I found out that the default `tsconfig.json` does not include the `strict` and `strictNullChecks` option, which led to this programming error.

Maybe there should be a disclaimer in the README.md of [obsidian-sample-plugin](https://github.com/obsidianmd/obsidian-sample-plugin)?

Or even better, these options should be enabled by default for new plugins.

**Comment by lishid** [comment]
> I found out that the default tsconfig.json does not include the strict and strictNullChecks option, which led to this programming error.

I've added it!

**Pull request merged**
