### PR TITLE
Add CardBoard plugin

### PR DESCRIPTION
**Pull request by roovo**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/roovo/obsidian-card-board

## Release Checklist

- [x] I have tested this on Windows, macOS, and Linux _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/roovo/obsidian-card-board/blob/67a7ec7217a033a9db3e308184777bef5ce432dc/typescript/view.ts#L13

You can use the `moment` exported by `obsidian` so that you don't end up bundling a copy of Moment.js in your plugin output.

**Comment by lishid** [comment]
Also, amazing that you have the plugin mostly written in Elm!

**Comment by roovo** [comment]
Thanks most muchly - I'll incorporate the moment suggestion into the next release :) I do need to spend some time getting the size down as it does seem rather big, so this will help for sure!

**Comment by roovo** [comment]
...and elm is great fun! - been looking for something to develop in it for a while :)

**Pull request merged**
