### PR TITLE
Feat: add ZettelGPT plugin info

### PR DESCRIPTION
**Pull request by OverRaddit**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/OverRaddit/ZettelGPT

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by OverRaddit** [comment]
.

**Comment by joethei** [comment]
Please make it clear in your readme that your plugin:
- requires an account with OpenAI
- might require payment to use the OpenAI API
- uploads note content to OpenAI servers
as per our new developer policies: <https://docs.obsidian.md/Developer+policies>

[hotkeys](https://github.com/OverRaddit/ZettelGPT/blob/dd4c7a3e04da5510b31e7659f36866b37c6745f5/main.ts#L45-L49)
[Avoid setting a default hotkey for commands](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+setting+a+default+hotkey+for+commands)

[mySetting: string;](https://github.com/OverRaddit/ZettelGPT/blob/dd4c7a3e04da5510b31e7659f36866b37c6745f5/src/Setting.ts#L6)
You can remove this setting.

**Comment by OverRaddit** [comment]
@joethei Thank you for reviewing my code! I was really looking forward to your review, and I've quickly fixed the issues you mentioned and brought it up to date.

**Comment by joethei** [comment]
> Please be aware that this plugin uploads note content to OpenAI servers as per Obsidian's new developer policies. Read the full developer policies [here](https://docs.obsidian.md/Developer+policies).

This sentence does not make sense, you should remove any references of our polices, you just need to mention that the plugin uploads note content to be compliant with our polices.

**Comment by OverRaddit** [comment]
@joethei I revised the sentence in the "Setup" section to remove the reference to Obsidian's policies and emphasize that the plugin uploads note content to be compliant with the policies.

**Comment by OverRaddit** [comment]
@joethei 
I apologize for the hassle. I've modified the README.md with only the sentence you mentioned.

**Comment by liamcain** [comment]
- [read](https://github.com/OverRaddit/ZettelGPT/blob/a795cb1bf1189cac6ccf5853f90ac7af7f9b7ecf/main.ts#L233) you should use [cachedRead](https://github.com/obsidianmd/obsidian-api/blob/9bb30633586c6649474b2affdf5b87efdd86498f/obsidian.d.ts#L3373) instead. It will be faster and avoid reading the file from disk
- [read](https://github.com/OverRaddit/ZettelGPT/blob/a795cb1bf1189cac6ccf5853f90ac7af7f9b7ecf/main.ts#L214) same here
- [getMostRecentLeaf](https://github.com/OverRaddit/ZettelGPT/blob/a795cb1bf1189cac6ccf5853f90ac7af7f9b7ecf/main.ts#L92) you should use [`getLeaf`](https://github.com/obsidianmd/obsidian-api/blob/902badd38ba907689f0917d7b193f7e33d1284fe/obsidian.d.ts#L3964) here instead. That will properly handle edge cases like pinned tabs.
- [OpenAI API Key](https://github.com/OverRaddit/ZettelGPT/blob/a795cb1bf1189cac6ccf5853f90ac7af7f9b7ecf/src/Setting.ts#L30) nit: We recommend that settings use [Sentence case](https://en.wiktionary.org/wiki/sentence_case) for their names. So this would become "OpenAI API key"

**Comment by joethei** [comment]
Hi @OverRaddit,
Do you still intend on submitting this plugin?

**Comment by liamcain** [comment]
- [getMostRecentLeaf](https://github.com/OverRaddit/ZettelGPT/blob/a795cb1bf1189cac6ccf5853f90ac7af7f9b7ecf/main.ts#L92) you shouldn't use getMostRecentLeaf for opening files. This will ignore things like "pinned" tabs and will cause an inconsistent experience for users. Instead you should use [`getLeaf`](https://github.com/obsidianmd/obsidian-api/blob/902badd38ba907689f0917d7b193f7e33d1284fe/obsidian.d.ts#L3964) here.
- [read](https://github.com/OverRaddit/ZettelGPT/blob/a795cb1bf1189cac6ccf5853f90ac7af7f9b7ecf/main.ts#L233) you can use [cachedRead](https://github.com/obsidianmd/obsidian-api/blob/9bb30633586c6649474b2affdf5b87efdd86498f/obsidian.d.ts#L3373) instead, it will be faster and avoid reading the file from disk

**Pull request merged**
