### PR TITLE
Add plugin: HackMD Sync

### PR DESCRIPTION
**Pull request by thor314**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/thor314/hackmd-obsidian

## Release Checklist
- I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_ - deleted
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using. I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by thor314** [comment]
the review team COOKS 

inspired

**Comment by joethei** [comment]
[.modal-button-container {](https://github.com/thor314/hackmd-obsidian/blob/c0a66cda3c28e20330c12e6e39eaa080dfb73d89/styles.css#L1)
Please don't overwrite core styling in a plugin, add another class/data attribute so it only applies to your plugin.

["dateReleased": "2024-10-29",](https://github.com/thor314/hackmd-obsidian/blob/c0a66cda3c28e20330c12e6e39eaa080dfb73d89/manifest.json#L4)
Not a valid value in the manifest, remove it.

[id: 'hackmd-push',](https://github.com/thor314/hackmd-obsidian/blob/c0a66cda3c28e20330c12e6e39eaa080dfb73d89/src/main.ts#L45), [id: 'hackmd-pull',](https://github.com/thor314/hackmd-obsidian/blob/c0a66cda3c28e20330c12e6e39eaa080dfb73d89/src/main.ts#L51), [id: 'hackmd-force-push'](https://github.com/thor314/hackmd-obsidian/blob/c0a66cda3c28e20330c12e6e39eaa080dfb73d89/src/main.ts#L57), [id: 'hackmd-force-pull',](https://github.com/thor314/hackmd-obsidian/blob/c0a66cda3c28e20330c12e6e39eaa080dfb73d89/src/main.ts#L65), [id: 'hackmd-copy-url',](https://github.com/thor314/hackmd-obsidian/blob/c0a66cda3c28e20330c12e6e39eaa080dfb73d89/src/main.ts#L73), [id: 'hackmd-delete',](https://github.com/thor314/hackmd-obsidian/blob/c0a66cda3c28e20330c12e6e39eaa080dfb73d89/src/main.ts#L79)
Don't prefix the command id with the plugin id, Obsidian will make sure that there are no conflicts with other plugins.


[name: 'Push to HackMD',](https://github.com/thor314/hackmd-obsidian/blob/c0a66cda3c28e20330c12e6e39eaa080dfb73d89/src/main.ts#L46), [name: 'Pull from HackMD',](https://github.com/thor314/hackmd-obsidian/blob/c0a66cda3c28e20330c12e6e39eaa080dfb73d89/src/main.ts#L52), [name: 'Force Push to HackMD',](https://github.com/thor314/hackmd-obsidian/blob/c0a66cda3c28e20330c12e6e39eaa080dfb73d89/src/main.ts#L58), [name: 'Force Pull from HackMD',](https://github.com/thor314/hackmd-obsidian/blob/c0a66cda3c28e20330c12e6e39eaa080dfb73d89/src/main.ts#L66), [name: 'Copy HackMD URL',](https://github.com/thor314/hackmd-obsidian/blob/c0a66cda3c28e20330c12e6e39eaa080dfb73d89/src/main.ts#L74)
You can also remove `HackMD` from here, it's unnecessaryduplication, as the command will show up as `HackMD Sync: Push to HackMD`

[.setName('Access Token')](https://github.com/thor314/hackmd-obsidian/blob/c0a66cda3c28e20330c12e6e39eaa080dfb73d89/src/settings.ts#L62), [.setName('Default Read Permission')](https://github.com/thor314/hackmd-obsidian/blob/c0a66cda3c28e20330c12e6e39eaa080dfb73d89/src/settings.ts#L85), [.setName('Default Write Permission')](https://github.com/thor314/hackmd-obsidian/blob/c0a66cda3c28e20330c12e6e39eaa080dfb73d89/src/settings.ts#L104), [.setName('Default Comment Permission')](https://github.com/thor314/hackmd-obsidian/blob/c0a66cda3c28e20330c12e6e39eaa080dfb73d89/src/settings.ts#L123), [{ value: NotePermissionRole.OWNER, label: 'Owner Only' },](https://github.com/thor314/hackmd-obsidian/blob/c0a66cda3c28e20330c12e6e39eaa080dfb73d89/src/settings.ts#L90-L91), [{ value: NotePermissionRole.OWNER, label: 'Owner Only' },](https://github.com/thor314/hackmd-obsidian/blob/c0a66cda3c28e20330c12e6e39eaa080dfb73d89/src/settings.ts#L109-L110), [{ value: CommentPermissionType.OWNERS, label: 'Owners Only' },](https://github.com/thor314/hackmd-obsidian/blob/c0a66cda3c28e20330c12e6e39eaa080dfb73d89/src/settings.ts#L130-L131)

**Comment by thor314** [comment]
> [.setName('Access Token')](https://github.com/thor314/hackmd-obsidian/blob/c0a66cda3c28e20330c12e6e39eaa080dfb73d89/src/settings.ts#L62), [.setName('Default Read Permission')](https://github.com/thor314/hackmd-obsidian/blob/c0a66cda3c28e20330c12e6e39eaa080dfb73d89/src/settings.ts#L85), [.setName('Default Write Permission')](https://github.com/thor314/hackmd-obsidian/blob/c0a66cda3c28e20330c12e6e39eaa080dfb73d89/src/settings.ts#L104), [.setName('Default Comment Permission')](https://github.com/thor314/hackmd-obsidian/blob/c0a66cda3c28e20330c12e6e39eaa080dfb73d89/src/settings.ts#L123), [{ value: NotePermissionRole.OWNER, label: 'Owner Only' },](https://github.com/thor314/hackmd-obsidian/blob/c0a66cda3c28e20330c12e6e39eaa080dfb73d89/src/settings.ts#L90-L91), [{ value: NotePermissionRole.OWNER, label: 'Owner Only' },](https://github.com/thor314/hackmd-obsidian/blob/c0a66cda3c28e20330c12e6e39eaa080dfb73d89/src/settings.ts#L109-L110), [{ value: CommentPermissionType.OWNERS, label: 'Owners Only' },](https://github.com/thor314/hackmd-obsidian/blob/c0a66cda3c28e20330c12e6e39eaa080dfb73d89/src/settings.ts#L130-L131)

Did you want me to do something to these?

**Comment by joethei** [comment]
Whoops, yeah:
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[name: 'Force Push',](https://github.com/thor314/hackmd-obsidian/blob/9dea547709340d5e14839e6ae1b65422146c6f4e/src/main.ts#L56), [name: 'Force Pull',](https://github.com/thor314/hackmd-obsidian/blob/9dea547709340d5e14839e6ae1b65422146c6f4e/src/main.ts#L64), [name: 'Delete Remote',](https://github.com/thor314/hackmd-obsidian/blob/9dea547709340d5e14839e6ae1b65422146c6f4e/src/main.ts#L78), [title: "Delete HackMD Note",](https://github.com/thor314/hackmd-obsidian/blob/9dea547709340d5e14839e6ae1b65422146c6f4e/src/modal.ts#L152), [.setName('Read Permission')](https://github.com/thor314/hackmd-obsidian/blob/9dea547709340d5e14839e6ae1b65422146c6f4e/src/settings.ts#L64), [.setName('Write Permission')](https://github.com/thor314/hackmd-obsidian/blob/9dea547709340d5e14839e6ae1b65422146c6f4e/src/settings.ts#L82), [.setName('Comment Permission')](https://github.com/thor314/hackmd-obsidian/blob/9dea547709340d5e14839e6ae1b65422146c6f4e/src/settings.ts#L101),

**Comment by thor314** [comment]
@joethei addressed sentence case, force pushed to my repo

**Pull request merged**
