### PR TITLE
Add plugin: Settings Management

### PR DESCRIPTION
**Pull request by xhuajin**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/xhuajin/obsidian-settings-management

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["name": "Settings Options Management",](https://github.com/xhuajin/obsidian-settings-options-management/blob/f59ccbf656a53c795df6ef9005bc1ed705e526ca/manifest.json#L3)
Remove "Options", it makes no sense here, since "Settings" is already in the name.
Also, the plugin is not doing any "Management" it's just displaying some settings differently.

["description": "Allows you to better manage your settings options panel.",](https://github.com/xhuajin/obsidian-settings-options-management/blob/f59ccbf656a53c795df6ef9005bc1ed705e526ca/manifest.json#L6)
Same here, also, a description should not start with "Allows you"

[// Remember to rename these classes and interfaces!](https://github.com/xhuajin/obsidian-settings-options-management/blob/f59ccbf656a53c795df6ef9005bc1ed705e526ca/src/main.ts#L6)
Remove this comment.

[console.log(`floating toc disable loading on mobile`);](https://github.com/xhuajin/obsidian-settings-options-management/blob/f59ccbf656a53c795df6ef9005bc1ed705e526ca/src/main.ts#L39)

[addIcon('toggle-none', '<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-toggle-left"><rect width="20" height="12" x="2" y="6" rx="6" ry="6"/><circle cx="12" cy="12" r="2"/></svg>')](https://github.com/xhuajin/obsidian-settings-options-management/blob/f59ccbf656a53c795df6ef9005bc1ed705e526ca/src/main.ts#L91)
Obsidian already includes Lucide, no need to add this icon here.

**Comment by xhuajin** [comment]
Hi @joethei, i fix those requests in v1.0.1

I check the lucide and i can't find the 'toggle-center' or 'toggle-none' icon. Lucide just provide 'toggle-left' and 'toggle-right' icon. I need a toggle icon that circle in the middle to represent the state that have enabled plugins and disabled plugins at the same time when toggle-right represent show enabled plugins, toggle-left represent show disabled plugins.

I change i name and id from 'Settings Options Mnagement' to 'Settings Management'. Also, I add some new function to reflect the "Management".

**Comment by joethei** [comment]
[if (Platform.isMobileApp || this.app.isMobile) {](https://github.com/xhuajin/obsidian-settings-management/blob/f3600f4bd2d392948b160c19028b049159f289e3/src/main.ts#L54-L57)
You can remove this conditions, as `isDesktopOnly` is already set.

**Comment by xhuajin** [comment]
Get it. I remove it.

**Pull request merged**
