### PR TITLE
Add plugin: Local GPT

### PR DESCRIPTION
**Pull request by pfrankov**
# I am submitting a new Community Plugin

## Repo URL
Link to my plugin: https://github.com/pfrankov/obsidian-local-gpt

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
What sets your plugin apart from the existing Ollama plugin?

[id: 'local-gpt-context-menu',](https://github.com/pfrankov/obsidian-local-gpt/blob/e029e4f00df2e56247dd54e3d776459724582e8c/src/main.ts#L20)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

[.setName("Default Model")](https://github.com/pfrankov/obsidian-local-gpt/blob/e029e4f00df2e56247dd54e3d776459724582e8c/src/LocalGPTSettingTab.ts#L35), [.setName("Reset Actions")](https://github.com/pfrankov/obsidian-local-gpt/blob/e029e4f00df2e56247dd54e3d776459724582e8c/src/LocalGPTSettingTab.ts#L182)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by pfrankov** [comment]
Thank you for the review!
I've updated the repo according your comments: https://github.com/pfrankov/obsidian-local-gpt

The Ollama plugin inspired the creation of my plugin, but even so, my plugin has many improvements:
- It's a context menu instead of command palette, it's more like Notion AI's style, which is a dealbreaker for me to use such type of plugins.
- The `Default model` field works as expected (in Ollama plugin doesn't)
- It has better processing of LLM's response.
- It has animated loader as a plugin that not affect the history.
- It has better UI for creation new prompts.
- The prompts themselves have been carefully tuned and tested on different models.

**Comment by liamcain** [comment]
- [wrap.innerHTML = this.text](https://github.com/pfrankov/obsidian-local-gpt/blob/188deeae6d86e6a417789478e79e1dc5c28128e6/src/spinnerPlugin.ts#L24) [innerHTML is a potential security risk](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#avoid-innerhtml-outerhtml-and-insertadjacenthtml)
- [wrap.innerHTML = wrap.innerHTML.trimEnd() + span.outerHTML.trim();](https://github.com/pfrankov/obsidian-local-gpt/blob/188deeae6d86e6a417789478e79e1dc5c28128e6/src/spinnerPlugin.ts#L34) you can just use `appendChild` instead

**Comment by pfrankov** [comment]
> * [wrap.innerHTML = this.text](https://github.com/pfrankov/obsidian-local-gpt/blob/188deeae6d86e6a417789478e79e1dc5c28128e6/src/spinnerPlugin.ts#L24) [innerHTML is a potential security risk](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#avoid-innerhtml-outerhtml-and-insertadjacenthtml)
> * [wrap.innerHTML = wrap.innerHTML.trimEnd() + span.outerHTML.trim();](https://github.com/pfrankov/obsidian-local-gpt/blob/188deeae6d86e6a417789478e79e1dc5c28128e6/src/spinnerPlugin.ts#L34) you can just use `appendChild` instead

`appendChild` creates redundant new line. In both cases `innerHTML` is the only option

**Comment by pfrankov** [comment]
@liamcain but you're right. There is too dangerous to execute everything from remote server
Fixed in https://github.com/pfrankov/obsidian-local-gpt/commit/cf8c08718405a056a6386a74314738b156ad21a7

**Pull request merged**
