### PR TITLE
Add plugin: Dictionary translator

### PR DESCRIPTION
**Pull request by grover572**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/grover572/obsidian-Dictionary-translator

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by grover572** [comment]
I am submitting a new Community Plugin:Dictionary translator

**Comment by grover572** [comment]
I have made changes,please recheck.

**Comment by joethei** [comment]
There is some documentation missing, there is no mention of the recording/playback feature in the readme.

["minAppVersion": "0.15.0",](https://github.com/grover572/obsidian-Dictionary-translator/blob/4cc5fcd8e5517a61bfafffa4f69a2b12338c0d86/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

["description": "This plugin helps you to quickly underline word translations and insert word cards in your notes.",](https://github.com/grover572/obsidian-Dictionary-translator/blob/4cc5fcd8e5517a61bfafffa4f69a2b12338c0d86/manifest.json#L6)
Avoid including sentences like "This is a plugin that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[import "main.css"](https://github.com/grover572/obsidian-Dictionary-translator/blob/4cc5fcd8e5517a61bfafffa4f69a2b12338c0d86/src/main.ts#L6-L7)
Why is this here?
It should be removed.

[containerEl.createEl("h1", {text: "Dictionary Settings"});](https://github.com/grover572/obsidian-Dictionary-translator/blob/4cc5fcd8e5517a61bfafffa4f69a2b12338c0d86/src/setting.ts#L48)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[{{ isRecording ? 'Stop Record' : 'Start Record' }}](https://github.com/grover572/obsidian-Dictionary-translator/blob/4cc5fcd8e5517a61bfafffa4f69a2b12338c0d86/src/translate/modal/TranslationModalComponent.vue#L81)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)
Also, why is that not in the i18n strings?

["goback": "Go Back",](https://github.com/grover572/obsidian-Dictionary-translator/blob/4cc5fcd8e5517a61bfafffa4f69a2b12338c0d86/src/langs/en.json#L5), ["connect_test_success": "Connect Success",](https://github.com/grover572/obsidian-Dictionary-translator/blob/4cc5fcd8e5517a61bfafffa4f69a2b12338c0d86/src/langs/en.json#L21-L23), ["attach": "Attach Folder",](https://github.com/grover572/obsidian-Dictionary-translator/blob/4cc5fcd8e5517a61bfafffa4f69a2b12338c0d86/src/langs/en.json#L29), ["show_link": "Show Web site",](https://github.com/grover572/obsidian-Dictionary-translator/blob/4cc5fcd8e5517a61bfafffa4f69a2b12338c0d86/src/langs/en.json#L32), ["show_radio": "Show Radio",](https://github.com/grover572/obsidian-Dictionary-translator/blob/4cc5fcd8e5517a61bfafffa4f69a2b12338c0d86/src/langs/en.json#L34), ["save_radio_fail": "Save radio Failed,Please check your network"](https://github.com/grover572/obsidian-Dictionary-translator/blob/4cc5fcd8e5517a61bfafffa4f69a2b12338c0d86/src/langs/en.json#L41)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)


["play_error": "Play failure,please replay",](https://github.com/grover572/obsidian-Dictionary-translator/blob/4cc5fcd8e5517a61bfafffa4f69a2b12338c0d86/src/langs/en.json#L39)
This should be `retry` instead of `retry`

**Comment by grover572** [comment]
@joethei Thank you for your review. I will fix it. Thanks again.

**Pull request merged**
