### PR TITLE
Add plugin obsidian-queryallthethings

### PR DESCRIPTION
**Pull request by sytone**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/sytone/obsidian-queryallthethings

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Please follow the pull request template.

**Comment by sytone** [comment]
Somehow missed the template. Sorry for the inconvenience. 

I have updated the template and checked off all the main pieces. 

There are some things not following guidelines due to the nature of the plugin and not wanting to duplicate any internal obsidian logic. 

Let me know if you have any further questions and I will follow up. 

Thanks!

**Comment by joethei** [comment]
["description": "A plugin that allows you to make SQL queries against the internal data of obsidian and render it how you want.",](https://github.com/sytone/obsidian-queryallthethings/blob/8c5cbace556a221ad53d5076e3d798c3c33ded0e/manifest.json#L6)
We have recently published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This is a plugin that" in your description.

[const ribbonIconElement = this.addRibbonIcon('dice', 'Refresh QATT Tables', (evt: MouseEvent) => {](https://github.com/sytone/obsidian-queryallthethings/blob/8c5cbace556a221ad53d5076e3d798c3c33ded0e/src/main.ts#L79-L83)
You should choose a better icon, most from <https://lucide.dev/> will work.

[// Perform additional things with the ribbon](https://github.com/sytone/obsidian-queryallthethings/blob/8c5cbace556a221ad53d5076e3d798c3c33ded0e/src/main.ts#L84-L89)
Remove this.

[const parsedCodeBlock = parse(codeBlockContent);](https://github.com/sytone/obsidian-queryallthethings/blob/8c5cbace556a221ad53d5076e3d798c3c33ded0e/src/QattCodeBlock.ts#L29)
Obsidian already provides a `parseYaml` function, internally it also uses the `yaml` package.

[id: 'qatt-force-codeblock-refresh',](https://github.com/sytone/obsidian-queryallthethings/blob/8c5cbace556a221ad53d5076e3d798c3c33ded0e/src/handlers/CommandHandler.ts#L16)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

**Comment by sytone** [comment]
Updated description and code to reflect comments made here. Also updated description in this PR to match the manifest and package.

Commit with changes: https://github.com/sytone/obsidian-queryallthethings/commit/6ffff69bdef63e5a9d97dc45257ae592c146dbd1

Released Version: 0.5.1

**Comment by sytone** [comment]
Checking to see if there are any more items needing cover.

**Comment by sytone** [comment]
Checking in to see if anything needs updating.

**Pull request merged**
