### PR TITLE
Add plugin: AnyBlock

### PR DESCRIPTION
**Pull request by LincZero**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/LincZero/obsidian-any-block

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[td.innerHTML = item.content.replace(/\n/g,"<br/>")](https://github.com/LincZero/obsidian-any-block/blob/de82a2abe470c42331959494fe10fcbd7a6129e0/src/svelte/GeneratorListTable.svelte#L66)
[Avoid using `innerHTML`](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#avoid-innerhtml-outerhtml-and-insertadjacenthtml)

[attr: {"style": "overflow-x:scroll; transform:scaleY(-1); white-space: nowrap"}](https://github.com/LincZero/obsidian-any-block/blob/de82a2abe470c42331959494fe10fcbd7a6129e0/src/replace/abProcessor.ts#L102)
You should avoid assigning styles via JavaScript and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets

[RelpaceRender](https://github.com/LincZero/obsidian-any-block/blob/de82a2abe470c42331959494fe10fcbd7a6129e0/src/manager2/replaceRenderChild.ts#L4)
Typo

[.addDropdown((component)=>{](https://github.com/LincZero/obsidian-any-block/blob/de82a2abe470c42331959494fe10fcbd7a6129e0/src/config/ABSettingTab.ts#L138-L147)
Using a toggle would be better here.


As an aside not using semicolons in JavaScript/TypeScript code can lead to rare, hard to debug issues, here is a pretty good article about it:
<https://flaviocopes.com/javascript-automatic-semicolon-insertion>

**Comment by LincZero** [comment]
I don't want to use semicolons in JavaScript/TypeScript and I know how to avoid the possible error of  not using semicolons.

**Comment by joethei** [comment]
Okay, good, this is just an aside, no need to change it.
I mainly mention it because some devs are not aware of the possible consequences.

**Comment by LincZero** [comment]
It's been almost two months. How long will the review take?

**Comment by liamcain** [comment]
Sorry for the delay in reviewing. I appreciate your patience as we get through all these plugins.

**Pull request merged**
