### PR TITLE
Added Askify to Community Plugin

### PR DESCRIPTION
**Pull request by helloworldkr**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/helloworldkr/Askify-Obsidian-Sync

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[// Remember to rename these classes and interfaces!](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/09d777c99625a2e1c9b47ac9826e0c63b64abc7a/main.ts#L22)
Please do this.

['dice'](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/09d777c99625a2e1c9b47ac9826e0c63b64abc7a/main.ts#L55)
Would recommend a different icon: <https://marcus.se.net/obsidian-plugin-docs/user-interface/icons>

[// Perform additional things with the ribbon](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/09d777c99625a2e1c9b47ac9826e0c63b64abc7a/main.ts#L123-L177)
Remove this.

[var axios = require('axios');](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/09d777c99625a2e1c9b47ac9826e0c63b64abc7a/main.ts#L181-L198)
Use `requestUrl` from the Obsidian API instead, you can use `response.arrayBuffer()` to get the raw data.

[https.get(fileUrl).on('response', function (response) {](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/09d777c99625a2e1c9b47ac9826e0c63b64abc7a/main.ts#L204-L221)
The same can be done here.

**Comment by helloworldkr** [comment]
@joethei 

[// Perform additional things with the ribbon](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/09d777c99625a2e1c9b47ac9826e0c63b64abc7a/main.ts#L123-L177)
Do I need to remove the lines below the comment 
or just the comment

**Comment by joethei** [comment]
Everything I've selected, starting from there to the end of the onload method.

It's coming from the sample plugin and you have not changed anything it, so it's useless.

**Comment by helloworldkr** [comment]
Hi @joethei ,
I have made all the requested changes.
Please let me know if anything else is required or if I did not do anything correctly.

**Comment by helloworldkr** [comment]
Hi @joethei  ,
I have made all the requested changes.
Please let me know if anything else is required or if I did not do anything correctly.

**Comment by joethei** [comment]
Sorry for leaving you waiting

[Copyright (c) <year> <copyright holders>](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/84bfa3bca42f2c6d3169d88c776f68510aeb8e2c/LICENSE.md?plain=1#L3)
Update this.

["authorUrl": "https://askify.vidoe",](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/84bfa3bca42f2c6d3169d88c776f68510aeb8e2c/manifest.json#L8)
Typo

[var request = require('request')](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/84bfa3bca42f2c6d3169d88c776f68510aeb8e2c/main.ts#L16)
Please stick to one import style.

[// Remember to rename these classes and interfaces!](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/84bfa3bca42f2c6d3169d88c776f68510aeb8e2c/main.ts#L25)
This has not been done.

[mySetting: string;](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/84bfa3bca42f2c6d3169d88c776f68510aeb8e2c/main.ts#L28)
Change this name to something that makes sense in your plugin.

[addIcon("circle",svgIcon);](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/84bfa3bca42f2c6d3169d88c776f68510aeb8e2c/main.ts#L63)
Lucide already contains an icon with that name, you can just get rid of this line and the preceding one.

[if(mySettingValue==''){](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/84bfa3bca42f2c6d3169d88c776f68510aeb8e2c/main.ts#L71)
`mySettingValue` is an object, not a string, so this will never be true.

[console.log('Value of "mySettingKey":', mySettingValue);](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/84bfa3bca42f2c6d3169d88c776f68510aeb8e2c/main.ts#LL76C5-L76C5)
[console.log("current sync key is "+ sync_key);](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/84bfa3bca42f2c6d3169d88c776f68510aeb8e2c/main.ts#LL87C9-L87C9)
Don't log setting values, especially if it's an API key as is the case here.

[const fs = require('fs');](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/84bfa3bca42f2c6d3169d88c776f68510aeb8e2c/main.ts#L79)
Unused and unnecessary, as already imported.

[https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/84bfa3bca42f2c6d3169d88c776f68510aeb8e2c/main.ts#L90C4-L91](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/84bfa3bca42f2c6d3169d88c776f68510aeb8e2c/main.ts#L90C4-L91)
Please don't log unnecessarily into the console.

[await vault.createFolder('Askify')](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/84bfa3bca42f2c6d3169d88c776f68510aeb8e2c/main.ts#L112)
Check first if that folder exists, with `this.app.vault.getAbstractFileByPath('Askify') instanceof TFolder`


[for (let i = 0; i < files.length; i++)](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/84bfa3bca42f2c6d3169d88c776f68510aeb8e2c/main.ts#L96-L99)
Don't do this, if there just happens to be a note of the same name in the vault it will get deleted, also iterating over all files in the vault is inefficient.
Since you're always creating notes in the `Askify` folder, you can instead do this:
```ts
const file = this.app.vault.getAbstractFileByPath(`Askify/${fileName}.md`)
if (file) {
    this.app.vault.delete(file);
}
```

[for (let i = 0; i < files2.length; i++) {](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/84bfa3bca42f2c6d3169d88c776f68510aeb8e2c/main.ts#LL127C1-L131C5)
What should this code do?
This will not delete the ZIP file, it will delete the note that was just synced.


> [var axios = require('axios');](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/09d777c99625a2e1c9b47ac9826e0c63b64abc7a/main.ts#L181-L198)
Use `requestUrl` from the Obsidian API instead, you can use `response.arrayBuffer()` to get the raw data.

This has not been done everywhere.

[fileData = await requestUrl({url: fileUrl}).arrayBuffer;](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/84bfa3bca42f2c6d3169d88c776f68510aeb8e2c/main.ts#LL172C39-L172C39)
This will not work, what you need to do is:
```
const response = await requestUrl(...);
fileData = response.arrayBuffer;
```

[class SampleModal extends Modal {](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/84bfa3bca42f2c6d3169d88c776f68510aeb8e2c/main.ts#L207-L225)
This can get removed as it's not used.

**Comment by liamcain** [comment]
- [SampleSettingTab](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/84bfa3bca42f2c6d3169d88c776f68510aeb8e2c/main.ts#L227) you should rename this class
- [SampleModal](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/84bfa3bca42f2c6d3169d88c776f68510aeb8e2c/main.ts#L207) this class is unused. You can remove it
- [axios](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/84bfa3bca42f2c6d3169d88c776f68510aeb8e2c/main.ts#L144) axios is unused
- [const path = require('path');](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/84bfa3bca42f2c6d3169d88c776f68510aeb8e2c/main.ts#L20-L21) unused imports
- [mySetting](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/84bfa3bca42f2c6d3169d88c776f68510aeb8e2c/main.ts#L32) you should give your settings a more identifiable name. Looks like mySetting should be something like apiKey instead.
- [mySetting](https://github.com/helloworldkr/Askify-Obsidian-Sync/blob/84bfa3bca42f2c6d3169d88c776f68510aeb8e2c/main.ts#L32) this is not a safe way to look for files to get deleted. This could end up causing way more files to get deleted than intended since "contains" will only do a partial string match. Instead, you should use [`getAbstractFileByPath`](https://github.com/obsidianmd/obsidian-api/blob/902badd38ba907689f0917d7b193f7e33d1284fe/obsidian.d.ts#L3612)

**Comment by helloworldkr** [comment]
@joethei 
Thanks a lot for the detailed review with suggested.

@liamcain 

Thank you for taking the time to review my code and provide feedback. I have carefully addressed all of the requested changes, and I hope that the new changes meet your expectations.

Please let me know if there are any additional changes or improvements that you would like me to make. I will ensure that the code meets the required standards.

Thank you again for the help.

**Comment by helloworldkr** [comment]
@joethei
@liamcain 
How do I release a new update to my plugin or does it obsidian automatically takes up the latest release tag.

**Pull request merged**
