### PR TITLE
Add plugin: Latex Render

### PR DESCRIPTION
**Pull request by jvsteiner**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/jvsteiner/obsidian-latex-render

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by jvsteiner** [comment]
hi, thank you for considering my submission

**Comment by joethei** [comment]
["minAppVersion": "1",](https://github.com/jvsteiner/obsidian-latex-render/blob/fa3160599c847a727a89f10a53efc9c924eaca79/manifest.json#L5)
That's not a valid version number.

["description": "",](https://github.com/jvsteiner/obsidian-latex-render/blob/fa3160599c847a727a89f10a53efc9c924eaca79/manifest.json#L6)
This needs to be filled.

[console.log("Loading cache", this.settings.cacheFolder);](https://github.com/jvsteiner/obsidian-latex-render/blob/fa3160599c847a727a89f10a53efc9c924eaca79/main.ts#L73), [console.log("Using cached SVG: ", md5Hash);](https://github.com/jvsteiner/obsidian-latex-render/blob/fa3160599c847a727a89f10a53efc9c924eaca79/main.ts#L153), [console.log("Rendering SVG: ", md5Hash);](https://github.com/jvsteiner/obsidian-latex-render/blob/fa3160599c847a727a89f10a53efc9c924eaca79/main.ts#L159)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[containerEl.createEl("h2", {](https://github.com/jvsteiner/obsidian-latex-render/blob/fa3160599c847a727a89f10a53efc9c924eaca79/main.ts#L402-L404)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by jvsteiner** [comment]
Thank you for the comments, the changes have been made, and an updated release has been published.

**Comment by joethei** [comment]
["description": "A plugin to render snippets of latex code in the editor as SVG files.",](https://github.com/jvsteiner/obsidian-latex-render/blob/b8c9f74bd64532daa17946fbc3643290af490ec6/manifest.json#L6C2-L6C89)
Avoid including sentences like "This is a plugin that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

**Comment by jvsteiner** [comment]
fixed

**Pull request merged**
