### PR TITLE
Add CodeBlock Tabs plugin 

### PR DESCRIPTION
**Pull request by JeminMau**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/JeminMau/obsidian-codeblock-tabs

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.
- [x] enabled Issues in my repo.(fixed)

### CODE REVIEW

**Comment by JeminMau** [comment]
Fixed.

**Review by JeminMau — COMMENTED** [review]
fixed

**Comment by JeminMau** [comment]
Please uninstall to remove data.json && install aganin, I have changed settings data format.

**Comment by liamcain** [comment]
- [var](https://github.com/JeminMau/Obsidian-CodeBlock-Tabs/blob/f516c9cb3660fb360639a506b59b9f1d319e9625/main.ts#L150) I recommend you change all instances of `var` to either `const` or `let`. `var` has function-level scope, so it can easily lead to bugs if you're not careful. Here's a pretty good guide with examples of why not to use `var`: [why `var` is obsolete](https://javascript.plainenglish.io/4-reasons-why-var-is-considered-obsolete-in-modern-javascript-a30296b5f08f)

**Pull request merged**
