### PR TITLE
Add Smort.io Plugin

### PR DESCRIPTION
**Pull request by getsmort**
This plugin lets you import [Smort.io](https://www.smort.io) articles to Obsidian. Smort.io lets you easily edit, annotate and share articles.

This is adapted from the [Pluck plugin](https://github.com/obsidianmd/obsidian-releases/pull/336) with the only differences being css changes and requesting Smort's API. 

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/SmortApp/obsidian-smort

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/SmortApp/obsidian-smort/blob/1187a65f5ff7d9a31db7939cdeaecb1099fab432/main.ts#L37
You should use `requestUrl` from `obsidian` instead of an electron API for this. That would make your request bypass CORS and also work on mobile, and also without you having to manually manage response chunks.

**Comment by saiabishek1** [comment]
@lishid I've released a new 1.0.1 version using `requestUrl` instead of Electron request

**Comment by getsmort** [comment]
@lishid I've released 1.0.1 which uses `requestUrl` instead of Electron

**Comment by lishid** [comment]
https://github.com/SmortApp/obsidian-smort/blob/a962b1df32d74db22e5523622fb8d38b27f2fc46/main.ts#L57
Recommend rewriting this part using async-await instead of `.then` and `.catch`.

**Pull request merged**
