### PR TITLE
Add Awesome Image plugin

### PR DESCRIPTION
**Pull request by AwesomeDog**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/AwesomeDog/obsidian-awesome-image

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[const activeFile = this.app.workspace.getActiveFile();](https://github.com/AwesomeDog/obsidian-awesome-image/blob/e753615c318ea86cf76990063931c4f93aa3a87f/src/main.ts#L30)
Please note that `getActiveFile` returns the last active file when no file is active.
This can lead to unintended consequences.

[const fileData = await this.app.vault.adapter.readBinary(file.path);](https://github.com/AwesomeDog/obsidian-awesome-image/blob/e753615c318ea86cf76990063931c4f93aa3a87f/src/main.ts#L66)
[Prefer the Vault API over the Adapter API](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#prefer-the-vault-api-over-the-adapter-api)

[document.on('click', this.imgSelector, this.clickImage);](https://github.com/AwesomeDog/obsidian-awesome-image/blob/e753615c318ea86cf76990063931c4f93aa3a87f/src/main.ts#L223-L225)
This will break in pop-out windows.
Use `activeDocument` instead, you will also need to listen to a few window related events to properly handle this.

['markdown' !== activeView.getViewType()](https://github.com/AwesomeDog/obsidian-awesome-image/blob/e753615c318ea86cf76990063931c4f93aa3a87f/src/ui/galleryNavbarView.ts#L41)
This check is unnecessary.

Sometimes you do use semicolons to terminate statements, sometimes you don't.
I would recommend sticking to one or the other
Not using semicolons in JavaScript/TypeScript code can lead to rare, hard to debug issues, here is a pretty good article about it:
<https://flaviocopes.com/javascript-automatic-semicolon-insertion>

**Comment by AwesomeDog** [comment]
> [const activeFile = this.app.workspace.getActiveFile();](https://github.com/AwesomeDog/obsidian-awesome-image/blob/e753615c318ea86cf76990063931c4f93aa3a87f/src/main.ts#L30) Please note that `getActiveFile` returns the last active file when no file is active. This can lead to unintended consequences.
> 
> [const fileData = await this.app.vault.adapter.readBinary(file.path);](https://github.com/AwesomeDog/obsidian-awesome-image/blob/e753615c318ea86cf76990063931c4f93aa3a87f/src/main.ts#L66) [Prefer the Vault API over the Adapter API](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#prefer-the-vault-api-over-the-adapter-api)
> 
> [document.on('click', this.imgSelector, this.clickImage);](https://github.com/AwesomeDog/obsidian-awesome-image/blob/e753615c318ea86cf76990063931c4f93aa3a87f/src/main.ts#L223-L225) This will break in pop-out windows. Use `activeDocument` instead, you will also need to listen to a few window related events to properly handle this.
> 
> ['markdown' !== activeView.getViewType()](https://github.com/AwesomeDog/obsidian-awesome-image/blob/e753615c318ea86cf76990063931c4f93aa3a87f/src/ui/galleryNavbarView.ts#L41) This check is unnecessary.
> 
> Sometimes you do use semicolons to terminate statements, sometimes you don't. I would recommend sticking to one or the other Not using semicolons in JavaScript/TypeScript code can lead to rare, hard to debug issues, here is a pretty good article about it: https://flaviocopes.com/javascript-automatic-semicolon-insertion

Thank you. I've updated this package and made a new release that addresses these comments (except a few design decisions).

**Comment by liamcain** [comment]
- [this.app.vault.on("create",](https://github.com/AwesomeDog/obsidian-awesome-image/blob/793aa0a86e395814c3b2428b2ee9481c07b5a2dd/src/main.ts#L53) you'll want to move this to inside an [`onLayoutReady`](https://github.com/obsidianmd/obsidian-api/blob/9bb30633586c6649474b2affdf5b87efdd86498f/obsidian.d.ts#L3626) callback. It's a but unintuitive but the "create" event is fired for every file in the vault when the vault is first loading. Putting it inside onLayoutReady will postpone attaching the event listener until after the vault has loaded so it will only be called for newly initialized files.

**Comment by AwesomeDog** [comment]
> * [this.app.vault.on("create",](https://github.com/AwesomeDog/obsidian-awesome-image/blob/793aa0a86e395814c3b2428b2ee9481c07b5a2dd/src/main.ts#L53) you'll want to move this to inside an [`onLayoutReady`](https://github.com/obsidianmd/obsidian-api/blob/9bb30633586c6649474b2affdf5b87efdd86498f/obsidian.d.ts#L3626) callback. It's a but unintuitive but the "create" event is fired for every file in the vault when the vault is first loading. Putting it inside onLayoutReady will postpone attaching the event listener until after the vault has loaded so it will only be called for newly initialized files.

Thank you. I've updated this package and made a new release that addresses these comments.

**Pull request closed without merging**
