### PR TITLE
add Obsidian Mermaid plugin

### PR DESCRIPTION
**Pull request by dartungar**
Add Obsidian Mermaid plugin: improved Mermaid.js experience for Obsidian: visual toolbar with common elements (with more functions to come)

# I am submitting a new Community Plugin

## Repo URL
Link to my plugin:
https://github.com/dartungar/obsidian-mermaid

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by liamcain** [comment]
- [showNotice](https://github.com/dartungar/obsidian-mermaid/blob/4ae94e7f37ef1b244fea869d4e22d39eb7467fb0/main.ts#L76) there's no benefit to having this function on the plugin
- [svg](https://github.com/dartungar/obsidian-mermaid/blob/4ae94e7f37ef1b244fea869d4e22d39eb7467fb0/src/ui/toolbarView/viewHelpers.ts#L86) I think you should call [sanitizeHTMLToDom](https://github.com/obsidianmd/obsidian-api/blob/6b2138aa28fb6d6f58f78e6fabec02186fdc0f82/obsidian.d.ts#L2977) just in case there's the possibility of DOM injection from the mermaid svg value.
- [click](https://github.com/dartungar/obsidian-mermaid/blob/4ae94e7f37ef1b244fea869d4e22d39eb7467fb0/main.ts#L26) this is not a reliable way to get keep track of the current editor. If you're targeting Obsidian v1.1 or newer, you can use the [`activeEditor`](https://github.com/obsidianmd/obsidian-api/blob/38dd22168d2925086371bfc59e36fd9121527a39/obsidian.d.ts#L4009). That should stay up to date automatically so you can remove the logic around managing your own active editor reference.

**Comment by dartungar** [comment]
@liamcain thanks for the review! I've dealt with first 2 points. As for using `activeEditor` - I've switched to it, but still have to rely on a separate variable for tracking it, since clicking on custom view makes `activeEditor` null (since there is no active editor in custom view).

**Comment by liamcain** [comment]
> As for using activeEditor - I've switched to it, but still have to rely on a separate variable for tracking it, since clicking on custom view makes activeEditor null (since there is no active editor in custom view).

In that case, you should add a listener on the [`active-leaf-change`](https://github.com/obsidianmd/obsidian-api/blob/38dd22168d2925086371bfc59e36fd9121527a39/obsidian.d.ts#L4202) event. Then check if the new leaf has an editor associated with it and update your activeEditor inside there. Using document click event won't work if the user switches views via hotkey or another another interaction.

**Comment by dartungar** [comment]
@liamcain that makes sense, thanks! I've changed the code accordingly: https://github.com/dartungar/obsidian-mermaid/blob/b0d3cecf004190d3b866cdb70134e47fc5c8e837/main.ts#L30

**Comment by liamcain** [comment]
Looks good. One more small thing. We're asking plugins to avoid using the word "Obsidian" in their plugin name to avoid over-saturating the brand name and reserve the naming for first-party plugins (see: Obsidian Publish, Obsidian Sync). Would you mind renaming this plugin, could just be something like "Mermaid Improved"

**Comment by dartungar** [comment]
@liamcain sure, done it!

**Comment by liamcain** [comment]
Thanks!

**Pull request merged**
