### PR TITLE
remove block reference counts from community plugins

### PR DESCRIPTION
**Pull request by shabegom**
Block Reference Counts is no longer maintained and has a bug that causes issues on link renaming.

### CODE REVIEW

**Comment by joethei** [comment]
The diff you created is pretty big,
it seems like you touched every line with an autoformatter.

Can you try and undo that?

**Comment by shabegom** [comment]
ugh, yeah sorry

**Comment by shabegom** [comment]
wow, that was more painful than it should have been. @joethei should be fixed.

**Comment by joethei** [comment]
thank you

**Pull request merged**
