### PR TITLE
Add plugin: Aloud

### PR DESCRIPTION
**Pull request by adrianlyjak**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/adrianlyjak/obsidian-aloud-tts

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [X]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [X]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [X] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by adrianlyjak** [comment]
/skip

I've corrected to use a stylesheet and conform to obsidian standard conventions, and use obsidian css variables where applicable. This includes many that the bot didn't mention ones that were using react styles.

The bot identified styles all belong to a single component. They are part of a dynamic animation for a speech synthesis icon. The css height controls the bars shape according to the audio volume. I extracted the other static styles there to a class 🤷 

This is the animation (rightmost component)

image

**Comment by adrianlyjak** [comment]
@joethei when can I expect a review of this plugin? Is there anything more I can do to help move this forward?

**Comment by joethei** [comment]
["description": "Highlight and speak text from your notes. Converts Text To Speech in real-time using lifelike voices from OpenAI. Just add your OpenAI API key.",](https://github.com/adrianlyjak/obsidian-aloud-tts/blob/65d67aed248ad1b981ad6044cc19e72610bcd87c/manifest.json#L6)
The last sentence should not be included in the description

["fundingUrl": "",](https://github.com/adrianlyjak/obsidian-aloud-tts/blob/65d67aed248ad1b981ad6044cc19e72610bcd87c/manifest.json#L9)
Omit this if you don't have one

[id: "tts-play-selection",](https://github.com/adrianlyjak/obsidian-aloud-tts/blob/65d67aed248ad1b981ad6044cc19e72610bcd87c/src/obsidian/TTSPlugin.ts#L49), [id: "tts-resume",](https://github.com/adrianlyjak/obsidian-aloud-tts/blob/65d67aed248ad1b981ad6044cc19e72610bcd87c/src/obsidian/TTSPlugin.ts#L66), [id: "tts-pause",](https://github.com/adrianlyjak/obsidian-aloud-tts/blob/65d67aed248ad1b981ad6044cc19e72610bcd87c/src/obsidian/TTSPlugin.ts#L79)
You don't need to prefix command it's with anything, you can remove the `tts-`

[.setTitle(`${MARKETING_NAME}: Play Selection`)](https://github.com/adrianlyjak/obsidian-aloud-tts/blob/65d67aed248ad1b981ad6044cc19e72610bcd87c/src/obsidian/TTSPlugin.ts#L38), [new Notice("No Text Selected To Speak");](https://github.com/adrianlyjak/obsidian-aloud-tts/blob/65d67aed248ad1b981ad6044cc19e72610bcd87c/src/obsidian/ObsidianBridge.ts#L73), [new Notice("No Text Selected To Speak");](https://github.com/adrianlyjak/obsidian-aloud-tts/blob/65d67aed248ad1b981ad6044cc19e72610bcd87c/src/obsidian/ObsidianBridge.ts#L104), [tooltip="Play Selection"](https://github.com/adrianlyjak/obsidian-aloud-tts/blob/65d67aed248ad1b981ad6044cc19e72610bcd87c/src/components/PlayerView.tsx#L34), [tooltip="Cancel Playback"](https://github.com/adrianlyjak/obsidian-aloud-tts/blob/65d67aed248ad1b981ad6044cc19e72610bcd87c/src/components/PlayerView.tsx#L86)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[const headers = await fetch(settings.OPENAI_API_URL + "/v1/audio/speech", {](https://github.com/adrianlyjak/obsidian-aloud-tts/blob/65d67aed248ad1b981ad6044cc19e72610bcd87c/src/player/openai.ts#L7), [const headers = await fetch(settings.OPENAI_API_URL + "/v1/models", {](https://github.com/adrianlyjak/obsidian-aloud-tts/blob/65d67aed248ad1b981ad6044cc19e72610bcd87c/src/player/openai.ts#L33)
Use the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

[export function arrayBufferToBase64(buffer: ArrayBuffer) {](https://github.com/adrianlyjak/obsidian-aloud-tts/blob/65d67aed248ad1b981ad6044cc19e72610bcd87c/src/util/misc.ts#L1-L9), [export function debounce<T extends unknown[]>(](https://github.com/adrianlyjak/obsidian-aloud-tts/blob/65d67aed248ad1b981ad6044cc19e72610bcd87c/src/util/misc.ts#L119-L132)
There are already functions of the same name & function in the Obsidian API.

**Comment by adrianlyjak** [comment]
@joethei thanks for the detailed review! I made your requested changes

**Comment by liamcain** [comment]
- [obsidian](https://github.com/adrianlyjak/obsidian-aloud-tts/blob/a97663893fc13b09a2e6089a77bbe07065eb4a8a/README.md#L3) Obsidian should be capitalized
- [Converts Text To](https://github.com/adrianlyjak/obsidian-aloud-tts/blob/a97663893fc13b09a2e6089a77bbe07065eb4a8a/README.md#L3) `Converts text to`
- [Open AI](https://github.com/adrianlyjak/obsidian-aloud-tts/blob/a97663893fc13b09a2e6089a77bbe07065eb4a8a/README.md#L8) `OpenAI`
- [sentence-by-sentance](https://github.com/adrianlyjak/obsidian-aloud-tts/blob/a97663893fc13b09a2e6089a77bbe07065eb4a8a/README.md#L12) typo

**Pull request merged**
