### PR TITLE
added obsidian-reloader to community plugins

### PR DESCRIPTION
**Pull request by o-su**
# I am submitting a new Community Plugin

## Repo URL
Link to my plugin: https://github.com/o-su/obsidian-file-reloader

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Please fill the pull request template.

**Comment by o-su** [comment]
added PR template

**Comment by liamcain** [comment]
Could you provide more information about what this plugin does and its use case in the README? The code doesn't seem to match the current description so I'm wondering if I'm missing something.

**Comment by o-su** [comment]
@liamcain I have obsidian vault stored on a network drive. When I edit the md file on one pc, the change does not automatically appear in obsidian on the other pc without restarting the application. This plugin is a workaround for this issue.

**Comment by liamcain** [comment]
My best guess for why this workaround is happening is because revealLeaf causes a "focus" event to trigger on the active window. But even then, I don't understand why that would cause the file to be processed. Given that this is a very specific use case that's for your own personal use, I don't think it should be included in the list of community plugins. If you can provide some more information or explanation as to the root cause of the bug, then maybe we can patch this into Core Obsidian instead of having it as a plugin.

**Comment by ericaxu** [comment]
Hi there, to keep things tidy, we're going to temporarily close plugin PRs after a month of inactivity.

Feel free to tell us to re-open it when you're ready to continue. Thanks for your understanding!

**Pull request closed without merging**
