### PR TITLE
Add plugin: Enhanced Symbols Prettifier

### PR DESCRIPTION
**Pull request by noam-sc**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/noam-sc/obsidian-enhanced-symbols-prettifier

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls. (I may have a bad file organization with my `.ts` files)
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

This is my first plugin release, don't hesitate to provide feedback or suggestions for improvements.

### CODE REVIEW

**Comment by joethei** [comment]
[MIT License](https://github.com/noam-sc/obsidian-enhanced-symbols-prettifier/blob/670a142bd0465f80a658a5bd510a3de2ac05c64c/LICENSE#L1-L3), ["author": "Noam Schmitt",](https://github.com/noam-sc/obsidian-enhanced-symbols-prettifier/blob/670a142bd0465f80a658a5bd510a3de2ac05c64c/manifest.json#L7)
Please credit the original author here.

[id: 'symbols-prettifier-format-symbols',](https://github.com/noam-sc/obsidian-enhanced-symbols-prettifier/blob/670a142bd0465f80a658a5bd510a3de2ac05c64c/src/main.ts#L16)
Remove the `symbols-prettifier` prefix here.

[symbol.s](https://github.com/noam-sc/obsidian-enhanced-symbols-prettifier/blob/670a142bd0465f80a658a5bd510a3de2ac05c64c/src/main.ts#L117)
This should be symbols or symbol`s

[const view = this.app.workspace.getActiveViewOfType(MarkdownView);](https://github.com/noam-sc/obsidian-enhanced-symbols-prettifier/blob/670a142bd0465f80a658a5bd510a3de2ac05c64c/src/main.ts#L121)
To get the active editor use `this.app.workspace.activeEditor?.editor`
This will mean that the plugin will also work in Canvas.

**Comment by noam-sc** [comment]
Thanks for the review.

I have fixed all the issues. However, changing `getActiveViewOfType(MarkdownView)` to `activeEditor` didn't get the plugin to work in canvas.
I shall investigate this issue later.

**Comment by noam-sc** [comment]
I fixed the support on canvas mode. 

Turns out the event listener was set on the wrong element (it was [window instead of document](https://github.com/noam-sc/obsidian-enhanced-symbols-prettifier/commit/cba817e605b2a24b29124f14575b672fdf5c5216))

It should be all good now

**Comment by noam-sc** [comment]
Hey @joethei , do you have any updates on the validation process? Thank you.

**Pull request merged**
