### PR TITLE
Add plugin: Interactivity

### PR DESCRIPTION
**Pull request by ichichikin**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/ichichikin/obsidian-plugin-interactivity

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["authorUrl": "",](https://github.com/ichichikin/obsidian-plugin-interactivity/blob/7b2fa76949847f3ce8cb8f1349294f2d38d4209a/manifest.json#L3)
This needs to be filled, you can use your GH profile url.

["description": "The Interactivity plugin allows you to run any executables inside your Obsidian notes.",](https://github.com/ichichikin/obsidian-plugin-interactivity/blob/7b2fa76949847f3ce8cb8f1349294f2d38d4209a/manifest.json#L4)
Don't include "plugin" in the description, it should be self evident that this is a plugin.

["minAppVersion": "0.12.17",](https://github.com/ichichikin/obsidian-plugin-interactivity/blob/7b2fa76949847f3ce8cb8f1349294f2d38d4209a/manifest.json#L7)
You are using newer API's, set this to the latest public build number.


["@types/node": "^20.1.7",](https://github.com/ichichikin/obsidian-plugin-interactivity/blob/7b2fa76949847f3ce8cb8f1349294f2d38d4209a/package.json#L7-L552)
Why all these dependencies?
Remove all that are not actually used.

[// Remember to rename these classes and interfaces!](https://github.com/ichichikin/obsidian-plugin-interactivity/blob/7b2fa76949847f3ce8cb8f1349294f2d38d4209a/main.ts#L3)
Remove this comment.

[id: 'interactivity-execute',](https://github.com/ichichikin/obsidian-plugin-interactivity/blob/7b2fa76949847f3ce8cb8f1349294f2d38d4209a/main.ts#L73), [id: 'interactivity-restart',](https://github.com/ichichikin/obsidian-plugin-interactivity/blob/7b2fa76949847f3ce8cb8f1349294f2d38d4209a/main.ts#L195)
Remove the prefix, this should just be `execute`/`restart`.


[this.app.vault['adapter']['basePath'] + '/' + this.app.vault['configDir'] + '/plugins/interactivity/1'](https://github.com/ichichikin/obsidian-plugin-interactivity/blob/7b2fa76949847f3ce8cb8f1349294f2d38d4209a/main.ts#L278)
This should be 
```ts
if (this.app.vault.adapter instanceof FileSystemAdapter) {
	const p = normalizePath(this.app.vault.adapter.getBasePath() + '/' + this.manifest.dir + '/1');
```


[containerEl.createEl('h2', {text: 'Interactivity settings'});](https://github.com/ichichikin/obsidian-plugin-interactivity/blob/7b2fa76949847f3ce8cb8f1349294f2d38d4209a/main.ts#L366)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by ichichikin** [comment]
@joethei, thank you for detailed comments. All is fixed.

**Comment by joethei** [comment]
[containerEl.createEl('h2', { text: 'Settings' });](https://github.com/ichichikin/obsidian-plugin-interactivity/blob/63b0097e787e8f3ec0eab3c14aec705200b3bfc4/main.ts#L361)
[Don't use a "general" heading in your settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by ichichikin** [comment]
@joethei, fixed

**Comment by ichichikin** [comment]
@joethei, a kindly reminder

**Pull request merged**
