### PR TITLE
Add bionic reading plugin.

### PR DESCRIPTION
**Pull request by Quorafind**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Quorafind/Obsidian-Bionic-Reading

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by liamcain** [comment]
Hmm, I'm not sure how/why this pull request got closed. Github doesn't even say when it happened! I reopened it and can review it tomorrow.

**Comment by Quorafind** [comment]
No worried. Tks for reopening this . 🥰

**Comment by liamcain** [comment]
Okay, so... November 3 is a little bit later than September 22 😬. Sorry for the long wait. I'm looking at this now.

@Quorafind As for why this pull request was closed, I figured out the issue. This is a pull request from your `master` branch. You can't have multiple pull requests from the same branch, so this pull request got closed when you opened a pull request for a different plugin. I tried to rebase this pull request for you but I wasn't able to since this branch is now used for the Double-Click Tab plugin. Do you mind resubmitted this plugin on a new branch? That will make it easier to rebase and merge.

**Comment by liamcain** [comment]
Actually, I'll just close this pull request for now since it's not reachable anymore.

**Comment by Quorafind** [comment]
@liamcain I will fork master again and then create multile branches to match your need(and make review more effciently)

**Comment by liamcain** [comment]
Great, thanks!

**Pull request closed without merging**
