### PR TITLE
Add Habit Calendar Plugin

### PR DESCRIPTION
**Pull request by hedonihilist**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/hedonihilist/obsidian-habit-calendar

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by hedonihilist** [comment]
Thanks for spending time reviewing my plugin. This plugin uses `innerHTML` in 

https://github.com/hedonihilist/obsidian-habit-calendar/blob/0887d8b4f537c66b1aa1f41cacb48cf9da83192c/main.ts#L263

but it's guarded by an `enableHTML` setting, which is `false` by default. This will give the freedom of editing DOM to the users knowing what they are doing. 

If the plugin still violates the principles, I will dop this feature in the next PR

**Comment by hedonihilist** [comment]
> 

Sorry I forgot to delete the `obsidian.d.ts` file. It's there for reference when writing code.

**Comment by liamcain** [comment]
- [const pm = source.match](https://github.com/hedonihilist/obsidian-habit-calendar/blob/ebda8f16fca903b114c5788c77e8ed93bcb2cecf/main.ts#L182) looks like this section can be removed, I don't think it's doing anything, right?
- [innerHTML](https://github.com/hedonihilist/obsidian-habit-calendar/blob/ebda8f16fca903b114c5788c77e8ed93bcb2cecf/main.ts#L263) Even though it's guarded behind a flag, I still recommend wrapping `input` in [sanitizeHTMLToDom](https://github.com/obsidianmd/obsidian-api/blob/6b2138aa28fb6d6f58f78e6fabec02186fdc0f82/obsidian.d.ts#L2977) for added security

**Comment by hedonihilist** [comment]
> * [const pm = source.match](https://github.com/hedonihilist/obsidian-habit-calendar/blob/ebda8f16fca903b114c5788c77e8ed93bcb2cecf/main.ts#L182) looks like this section can be removed, I don't think it's doing anything, right?
> * [innerHTML](https://github.com/hedonihilist/obsidian-habit-calendar/blob/ebda8f16fca903b114c5788c77e8ed93bcb2cecf/main.ts#L263) Even though it's guarded behind a flag, I still recommend wrapping `input` in [sanitizeHTMLToDom](https://github.com/obsidianmd/obsidian-api/blob/6b2138aa28fb6d6f58f78e6fabec02186fdc0f82/obsidian.d.ts#L2977) for added security

Thanks for spending time reviewing my plugin. I will clean the unused code and check out the `sanitizeHTMLToDom` api, which I didn't know before.

**Pull request merged**
