### PR TITLE
Add title index plugin

### PR DESCRIPTION
**Pull request by renmu123**
# [x] I am submitting a new Community Plugin

## Repo URL
https://github.com/renmu123/obsidian-markdown-index

## Release Checklist

- [x] I have tested this on Windows
- [x] Github release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - `styles.css` _(optional)_
- [x] Github release name matches the exact version number specified in your manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.

### CODE REVIEW

**Comment by renmu123** [comment]
thanks for your review.l have fixed them

**Comment by lishid** [comment]
https://github.com/renmu123/obsidian-markdown-index/blob/9ab57c9998119129c61f9fc3832271e53fb158e8/main.ts#L4

This should be TitleCase like `TitleIndexPlugin`. Also, any reason why it isn't `MarkdownIndexPlugin`?

https://github.com/renmu123/obsidian-markdown-index/blob/9ab57c9998119129c61f9fc3832271e53fb158e8/markdownIndex.ts#L8

Since your code isn't a lot, why not just move all of these functions into your main plugin class? I don't see the need to instantiate a new copy of MarkdownIndex with `new MarkdownIndex()` every time the command executes either way.

**Comment by lishid** [comment]
Ah my bad, it seems that your repo is named obsidian-markdown-index but the plugin is actually title-index.

**Comment by lishid** [comment]
Let's merge it like this - class renames shouldn't matter, so you can do that later if you wish.

**Pull request merged**
