### PR TITLE
Add plugin: Github Copilot

### PR DESCRIPTION
**Pull request by Pierrad**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Pierrad/obsidian-github-copilot/tree/1.0.0

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(not applicable)_
  - [ ]  iOS _(not applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Pierrad** [comment]
/skip

I made the required changes 24h ago but the bot did not review again my repo.

**Comment by joethei** [comment]
Where is the actual code for the files in the "copilot" folder?
Also, these files should not be packaged as a zip, but instead bundled into the `main.js` file.

["minAppVersion": "0.15.0",](https://github.com/Pierrad/obsidian-github-copilot/blob/6ce93dc0d83ca68b8839e95fb02e0646e8355254/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

[.setName("Node Path")](https://github.com/Pierrad/obsidian-github-copilot/blob/6ce93dc0d83ca68b8839e95fb02e0646e8355254/src/settings/CopilotPluginSettingTab.ts#L33)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[new Setting(containerEl)](https://github.com/Pierrad/obsidian-github-copilot/blob/6ce93dc0d83ca68b8839e95fb02e0646e8355254/src/settings/CopilotPluginSettingTab.ts#L47-L57)
This should not be a setting, users can enable & disable the plugin from the community settings tab.

**Comment by Pierrad** [comment]
Hi, 
The code for the files in the copilot folder comes from the [official neovim repository](https://github.com/github/copilot.vim/tree/release/dist), these are the files needed to run the [Copilot AI LSP & model](https://github.com/features/copilot).

I packaged the folder as zip because I don't think that I can bundle the model and agent into a single js file (I think if it was possible they would have done it when releasing the code in the official repository).

I was thinking that everything from the release would be downloaded and installed when using the plugin from the marketplace, it is not the case? 
  
The copilot classic extension (from VSCode, Jetbrains IDE) allows you to enable & disable the autocompletions from the bottom status bar with the copilot icon without needing to go to the extension manager to enable & disable the plugin. That is why I made this settings in the settings page and in the status bar. 

I will make the others changes requested.

Thanks

**Comment by Pierrad** [comment]
Hi @joethei, did you have some time to check my respond ?

**Comment by Pierrad** [comment]
Hi @joethei, can you check my changes again please?

**Comment by joethei** [comment]
No, only the `manifest.json`, `main.js` and `styles.css` are downloaded from the release, everything else is ignored.

And remove that setting.

**Comment by Pierrad** [comment]
Hi @joethei,

Can you review my code please?

I removed the setting from the setting tab. (see [this commit](https://github.com/Pierrad/obsidian-github-copilot/commit/46384841d2f617944ffb488a65a830e1f934ab0f))

Also I implement a way to download copilot from my latest release (here's [the commit](https://github.com/Pierrad/obsidian-github-copilot/commit/9f17347427875a786c46f7bd6b378f38ae6f6158)). 

According to the developer policies in the documentation, I updated the README to inform user that there's a folder that will be downloaded and that they need network connection.

**Comment by Pierrad** [comment]
Hi @joethei, can you check my changes please? Thanks

**Comment by joethei** [comment]
The files should be bundled into the `main.js`, not downloaded separately.

**Comment by Pierrad** [comment]
Hi @joethei, I managed to bundled the needed copilot files into the main.js. [Here's the commit](https://github.com/Pierrad/obsidian-github-copilot/commit/d53c92bc1c44361e746a4fe9eedc889cf2a7ac0e) for the review.

**Comment by Pierrad** [comment]
Hi @joethei, can you review my changes please?

**Pull request merged**
