### PR TITLE
Add plugin: InfraNodus AI Graph View

### PR DESCRIPTION
**Pull request by deemeetree**
Add infranodus-graph-view plugin

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/noduslabs/infranodus-obsidian-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by deemeetree** [comment]
Note, I added access to the original uncompiled repo for @joethei so he can review the code: 
https://github.com/noduslabs/infranodus-obsidian

**Comment by deemeetree** [comment]
@joethei Could you please tell us what changes should be made and why installation is not recommended? There is no information about this in this pull request from you. Thank you!

**Comment by deemeetree** [comment]
@joethei if it's a reference to the fact that `main.js` should be added to `.gitignore`, this change has been made. Thanks!

**Comment by joethei** [comment]
I've created an issue on the repo with the requested changes.

**Comment by deemeetree** [comment]
@joethei  the changes you requested were implemented. 

The new release is published on https://github.com/noduslabs/infranodus-obsidian-plugin/releases/tag/0.6.5 

Your issue is for your convenience here: https://github.com/noduslabs/infranodus-obsidian/issues/54

The source code repo (with the access for you): https://github.com/noduslabs/infranodus-obsidian

Thank you!

**Comment by deemeetree** [comment]
@joethei FYI I pushed the requested changes and the latest release is https://github.com/noduslabs/infranodus-obsidian-plugin/releases/tag/0.6.8

**Comment by deemeetree** [comment]
@joethei Could you please tell us when you plan to review the corrections to the plugin or shall I just submit a new request? Our users are waiting and your forum says it usually takes a few days, but I submitted a correction 2 weeks ago already... Thank you!

**Comment by deemeetree** [comment]
Please do not close, was waiting for a response for @joethei and now implementing the changes

**Comment by deemeetree** [comment]
Dear @joethei we did all the updates you required, you can find the latest build on https://github.com/noduslabs/infranodus-obsidian-plugin 

Also resolved all the issues you had on https://github.com/noduslabs/infranodus-obsidian/issues/54

**Pull request merged**
