### PR TITLE
Add plugin: Send Note

### PR DESCRIPTION
**Pull request by jvsteiner**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [send-note](https://github.com/jvsteiner/send-note/)

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by jvsteiner** [comment]
amending based on bot feedback

**Comment by joethei** [comment]
[.setName("Custom Image URL")](https://github.com/jvsteiner/send-note/blob/aaf8de4f5a23d14eee66f4ad0baeaa7814293ee1/src/settings.ts#L205), [.setName("Query String Value")](https://github.com/jvsteiner/send-note/blob/aaf8de4f5a23d14eee66f4ad0baeaa7814293ee1/src/settings.ts#L241)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[new Setting(containerEl).setName("Upload options").setHeading();](https://github.com/jvsteiner/send-note/blob/aaf8de4f5a23d14eee66f4ad0baeaa7814293ee1/src/settings.ts#L269), [new Setting(containerEl).setName("Note options").setHeading();](https://github.com/jvsteiner/send-note/blob/aaf8de4f5a23d14eee66f4ad0baeaa7814293ee1/src/settings.ts#L280-L281)
[Avoid "options" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

[export function arrayBufferToBase64 (buffer: ArrayBuffer): string {](https://github.com/jvsteiner/send-note/blob/aaf8de4f5a23d14eee66f4ad0baeaa7814293ee1/src/crypto.ts#L35-L46)
Obsidian already exports functions for both of these, with the same name even.

[const pluginVersion = require("../manifest.json").version;](https://github.com/jvsteiner/send-note/blob/aaf8de4f5a23d14eee66f4ad0baeaa7814293ee1/src/api.ts#L8)
You can get the version in the manifest from the plugin instance `<instance>.manifest.version`

**Comment by jvsteiner** [comment]
changes made in latest release @joethei https://github.com/jvsteiner/send-note/releases/tag/0.8.32

**Comment by joethei** [comment]
You missed the first one.

**Comment by jvsteiner** [comment]
sorry - fixed now

**Comment by joethei** [comment]
[.setName("AWS Access Key ID")](https://github.com/jvsteiner/send-note/blob/ef60504b10346caf3d4512933e3f325fca5f3cd9/src/settings.ts#L90C7-L90C36), [.setName("AWS Secret Key")](https://github.com/jvsteiner/send-note/blob/ef60504b10346caf3d4512933e3f325fca5f3cd9/src/settings.ts#L104C7-L104C33), [.setName("S3 Bucket")](https://github.com/jvsteiner/send-note/blob/ef60504b10346caf3d4512933e3f325fca5f3cd9/src/settings.ts#L131), [  .setName("Custom S3 Endpoint")](https://github.com/jvsteiner/send-note/blob/ef60504b10346caf3d4512933e3f325fca5f3cd9/src/settings.ts#L166C5-L166C37), [.setName("S3 Path Style URLs")](https://github.com/jvsteiner/send-note/blob/ef60504b10346caf3d4512933e3f325fca5f3cd9/src/settings.ts#L183C7-L183C37)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by jvsteiner** [comment]
ok, fixed again

**Pull request merged**
