### PR TITLE
Add plugin: Smart Gantt

### PR DESCRIPTION
**Pull request by nhannht**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/nhannht/obsidian-smart-gantt

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["author": "Obsidian",](https://github.com/nhannht/obsidian-smart-gantt/blob/57a86dbed5263c1a039158d17b8f246b7c875596/manifest.json#L7)
Update this.

["minAppVersion": "0.0.8",](https://github.com/nhannht/obsidian-smart-gantt/blob/57a86dbed5263c1a039158d17b8f246b7c875596/manifest.json#L5)
That is way too low, set this to the latest public build number.

[this.registerObsidianProtocolHandler("hello", async (_e) => {](https://github.com/nhannht/obsidian-smart-gantt/blob/57a86dbed5263c1a039158d17b8f246b7c875596/main.tsx#L21-L23)
Remove this.

[this.app.workspace.detachLeavesOfType("smart-gantt")](https://github.com/nhannht/obsidian-smart-gantt/blob/57a86dbed5263c1a039158d17b8f246b7c875596/main.tsx#L32)
Do not detach leaves with your custom view here, this is an antipattern, see: <https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Don't+detach+leaves+in+%60onunload%60>
Instead, only create a new leaf, if there is not one already.

[return "Smart Gantt View";](https://github.com/nhannht/obsidian-smart-gantt/blob/57a86dbed5263c1a039158d17b8f246b7c875596/src/SmartGanttReactView.tsx#L48)
Remove `View` here.

[import mermaid from "mermaid";](https://github.com/nhannht/obsidian-smart-gantt/blob/57a86dbed5263c1a039158d17b8f246b7c875596/src/SmartGanttMainReactComponent.tsx#L2)
Instead of importing Mermaid, use the [laodMermaid](https://docs.obsidian.md/Reference/TypeScript+API/loadMermaid) function from the API, to avoid version drift.

**Comment by nhannht** [comment]
Thank you.

**Comment by nhannht** [comment]
Sorry, I cannot understand how to solve the conflict in the `community-plugins.json` file when if it keeps receiving changes from other sources every day. 🙇

**Comment by joethei** [comment]
You don't need to fix the merge conflicts, we will do that once the plugin is ready to be merged.

[mermaid.initialize](https://github.com/nhannht/obsidian-smart-gantt/blob/f7bc19ee74cb72ecce082dd84647a4246628a5b3/src/SmartGanttMainReactComponent.tsx#L14-L19)
This should not be necessary, mermaid.initialize is already being called by the `loadMermaid` function internally.
Or are there settings that need to be changed for the plugin to work correctly.

**Comment by nhannht** [comment]
I also have no idea about the error:
```
Error: fatal: couldn't find remote ref refs/pull/3368/merge
```

Follow this [thread](https://forum.obsidian.md/t/plugin-validation-fails-couldnt-find-remote-ref/78863) I guess I will wait for you to manually check it

**Pull request merged**
