### PR TITLE
Add plugin: BookFusion

### PR DESCRIPTION
**Pull request by skillachie**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/BookFusion/obsidian-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by skillachie** [comment]
Do we need to do anything else to trigger the bot to review?

**Comment by joethei** [comment]
[Elevate your Obsidian workflow with the [BookFusion](https://www.bookfusion.com/) plugin,](https://github.com/BookFusion/obsidian-plugin/blob/23492684d4af9daa4f6c05583928db67b48caeff/README.md#L5)
You should make it more obvious in this part of the README that Bookfusion is a external service.
(And thanks for including the disclosures at the end)

["description": "Import your BookFusion highlights into Obsidian.",](https://github.com/BookFusion/obsidian-plugin/blob/23492684d4af9daa4f6c05583928db67b48caeff/manifest.json#L6), 
Remove "Obsidian" here, you can replace it with "your vault" for example.

**Comment by skillachie** [comment]
@joethei   Thank you for the suggestions.  We have made the requested changes and pushed a new release.   No problem re the disclosures we tried to follow the suggested guidelines.

**Comment by skillachie** [comment]
@joethei It seems the bot did not detect that the changes were made yesterday. Could you check?

**Pull request merged**
