### PR TITLE
Adds obsidian-embedded-note-titles

### PR DESCRIPTION
**Pull request by mgmeyers**
# I am submitting a new Community Plugin

## Repo URL

https://github.com/mgmeyers/obsidian-embedded-note-titles

## Release Checklist

- [x] I have tested this on Windows, macOS, and Linux _(if applicable)_
- [x] Github release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - `styles.css` _(optional)_
- [x] Github release name matches the exact version number specified in your manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.

### CODE REVIEW

**Comment by liamcain** [comment]
https://github.com/mgmeyers/obsidian-embedded-note-titles/blob/62666d803fa27ac1502901e4df335b278fbf3963/src/main.ts#L31 not positive on the timing of things, but this might make more sense onLayoutReady

https://github.com/mgmeyers/obsidian-embedded-note-titles/blob/62666d803fa27ac1502901e4df335b278fbf3963/src/HeadingsManager.ts#L248 you can use the debounce function for this.

https://github.com/mgmeyers/obsidian-embedded-note-titles/blob/62666d803fa27ac1502901e4df335b278fbf3963/src/getMatchedCSSRules.ts#L90 small performance thing - since you are only using this in one spot, why not reverse the sort here since you're immediately calling `reverse()` on it currently

**Comment by mgmeyers** [comment]
Thanks again, @liamcain ! Updates here: https://github.com/mgmeyers/obsidian-embedded-note-titles/commit/23f958b8d6c1b4803a13aebabdfaaccf7e0ed6d0

Re: `onLayoutReady` vs `layout-change`: I trigger `layout-change` on line 33 to invoke the handler I bound above on line 12. I use `layout-change` there, because it will tell me when the user has navigated to a new note, move a note into a different pane, etc. Basically, there are a handful of scenarios where the plugin needs to regenerate the H1 tags, and `layout-change` seemed to work better than the other events I tried.

**Comment by liamcain** [comment]
> Re: onLayoutReady vs layout-change: I trigger layout-change on line 33 to invoke the handler I bound above on line 12.

Sorry, I realize I wasn't super clear with what I meant here. I was just referring to you triggering layout-change _before_ the layout is ready. It's probably fine, but I was just suggesting you wrap the `this.app.workspace.trigger("layout-change");` part in onLayoutReady is all.

---

Changes look good! I still can't get over how much work probably went into making this plugin though 😮 I looked at the main.ts hoping to find a psuedo-element injected, not a whole CSS parser!

**Comment by mgmeyers** [comment]
Oh 💡 ! I see. I'll test out onLayoutReady, that seems like a sensible precaution to me.

**Comment by mgmeyers** [comment]
Thanks @liamcain! onLayoutReady works just fine. I've updated the release.

**Review by liamcain — APPROVED** [review]

**Pull request merged**
