### PR TITLE
Add Tag & Word cloud plugin

### PR DESCRIPTION
**Pull request by joethei**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/joethei/obsidian-tagcloud

## Release Checklist
- [ ] I have tested the plugin on
  - [X]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [X]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/joethei/obsidian-tagcloud/blob/52dd7c4adf06bce50ef8ca530d9e4ed0c7110143/src/main.ts#L170
Recommend using cachedRead to get better performance here.

https://github.com/joethei/obsidian-tagcloud/blob/52dd7c4adf06bce50ef8ca530d9e4ed0c7110143/src/main.ts#L238
Hmm reading and parsing every markdown file in the vault is quite an expensive operation to be done on vault startup every time. Perhaps it would be better to lazily compute it when you have a block being rendered?

**Comment by joethei** [comment]
> Hmm reading and parsing every markdown file in the vault is quite an expensive operation to be done on vault startup every time. Perhaps it would be better to lazily compute it when you have a block being rendered?

I explicitly chose to do this as a vault wide scan is really time intensive(takes ~25 minutes in my test vault with ~12.000 files, so not normal use)

I have implemented your other suggestion, currently testing it for any differences.

**Comment by lishid** [comment]
> I explicitly chose to do this as a vault wide scan is really time intensive(takes ~25 minutes in my test vault with ~12.000 files, so not normal use)

Oh wow! Would it make more sense to cache your results to a file (and identified by file path/size/mtime) and re-compute only changed files from last run? I would also suggest running the profiler to see what in your processing pipeline takes so long.

**Comment by lishid** [comment]
If I had to guess, it's your replace chain, which generates a lot of intermediate large strings - might be better to split the file by line and run the replacements instead.

**Comment by joethei** [comment]
I did improve the performance a bit(down to 14 minutes now), and added a cache,
so the data will only be calculated if there where changes.

**Pull request merged**
