### PR TITLE
add Harmonic theme

### PR DESCRIPTION
**Pull request by Thiews**
# I am submitting a new Community Theme

## Repo URL

Link to my theme: https://github.com/Thiews/Obsidian-Harmonic

## Theme checklist

- [x] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo)
  - [x] `obsidian.css`
  - [x] The screenshot file
- [x] I have indicated which modes (dark, light, or both) are compatible with my theme
- [x] I have added a license in the LICENSE file
- [x] If my repo is not using the `master` branch, please indicate in `community-themes.json` with `"branch": "main"`.

### CODE REVIEW

**Comment by eleanorkonik** [comment]
Here's the repo URL: https://github.com/Thiews/Obsidian-Harmonic

**Comment by Thiews** [comment]
> Here's the repo URL: https://github.com/Thiews/Obsidian-Harmonic

I put the url in the comment ! Sorry for forgetting to write it !

**Comment by Thiews** [comment]
Is there anything I have to do ?

**Comment by ericaxu** [comment]
Looks amazing, thanks for your submission!

**Comment by Thiews** [comment]
Thank you, love the app, you have done an awesome job !

**Pull request merged**
