### PR TITLE
Add Micro Mike

### PR DESCRIPTION
**Pull request by ThisTheThe**
https://github.com/ThisTheThe/MicroMike

- [x] My repo contains all required files (please do not add them to this obsidian-releases repo).
	- [x] obsidian.css
	- [x] The screenshot file.
- [x] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other themes that I'm using.
- [x] I have given proper attribution to these other themes in my README.md.

### CODE REVIEW

**Comment by ericaxu** [comment]
@ThisTheThe Sorry for the slow review process, we've been busy with a big design overhaul in the recently released v1.0 of Obsidian. Now that 1.0 has been released and Obsidian's UI has undergone some sweeping changes, we are asking all theme entries to confirm that their theme is compatible with the latest version of Obsidian.

**Comment by ThisTheThe** [comment]
I have updated the skin to support 1.0. Review at your convenience.

**Comment by ThisTheThe** [comment]
Are there any problems preventing this skin from being added?

**Comment by ericaxu** [comment]
One minor thing: you might want to make the screenshot smaller while keeping the 16:9 aspect ratio. That would make your theme load faster in the theme store. You can still include high resolution screenshots in your README.

We recommend using a screenshot of size 512px by 288px as the featured screenshot to minimize loading time.

**Comment by ericaxu** [comment]
Hi there, to keep things tidy, we're going to temporarily close plugin PRs after a month of inactivity.

Feel free to tell us to re-open it when you're ready to continue. Thanks for your understanding!

**Comment by ThisTheThe** [comment]
I've addressed this now.

**Comment by ericaxu** [comment]
Thanks!

**Pull request merged**
