### PR TITLE
Add plugin: R.E.L.A.X.

### PR DESCRIPTION
**Pull request by Syr0**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/Syr0/R.E.L.A.X./ 

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
  - [ ] dunno if the /nodes/ mofules are included. es_build was used.
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [ ] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Syr0** [comment]
New Version: 1.3.4

**Comment by Syr0** [comment]
updated missing files....

**Comment by joethei** [comment]
Please remove the `main.js` file from the repo and add it to your .gitignore. Compiled release files shouldn't get mixed with source code in your commits and should go to the releases files instead.

[[1](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L250)][[2](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L250)][[3](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L251)][[4](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L251)][[5](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L262)][[6](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L262)][[7](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L264)][[8](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L264)][[9](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L289)][[10](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L289)][[11](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L292)][[12](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L292)][[13](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L295)][[14](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L295)][[15](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L311)][[16](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L311)][[17](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L312)][[18](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L312)][[19](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L313)][[20](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L313)][[21](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L323)][[22](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L323)][[23](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L324)][[24](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L324)][[25](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L328)][[26](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L328)][[27](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L329)][[28](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L329)][[29](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L396)][[30](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L396)][[31](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L397)][[32](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L397)][[33](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L400)][[34](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L400)][[35](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L410)][[36](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L410)][[37](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L429)][[38](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L429)][[39](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L430)][[40](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L430)][[41](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L431)][[42](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L431)][[43](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L454)][[44](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L454)]:You should avoid assigning styles via JavaScript or in HTML and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets.

[[1](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L664)][[2](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L683)][[3](https://github.com/Syr0/R.E.L.A.X./blob/e6b7a504ad30292fe3e1b472eb6eaa27b24d0e6a/main.ts#L687)]:You should not cast this, instead use a `instanceof` check.

[Copyright (c) 2023](https://github.com/Syr0/R.E.L.A.X./blob/9c4b5295b246ec96204c8acd22246d6ad300eaff/LICENSE#L3)
This is missing your name.

["description": "Plugin encloses multiple custom Regex with double square brackets.Selections, files, or even recursively all files in a folder",](https://github.com/Syr0/R.E.L.A.X./blob/9c4b5295b246ec96204c8acd22246d6ad300eaff/manifest.json#L6)
Remove the word `Plugin`

[.setName("Ignore Links")](https://github.com/Syr0/R.E.L.A.X./blob/9c4b5295b246ec96204c8acd22246d6ad300eaff/main.ts#L437), [.setName("Ignore Code Blocks")](https://github.com/Syr0/R.E.L.A.X./blob/9c4b5295b246ec96204c8acd22246d6ad300eaff/main.ts#L473), [.setName("Reset Defaults")](https://github.com/Syr0/R.E.L.A.X./blob/9c4b5295b246ec96204c8acd22246d6ad300eaff/main.ts#L500)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[id: "Relax-command"](https://github.com/Syr0/R.E.L.A.X./blob/9c4b5295b246ec96204c8acd22246d6ad300eaff/main.ts#L538)
Remove the `-command` suffix.

[this.app.workspace.activeLeaf](https://github.com/Syr0/R.E.L.A.X./blob/9c4b5295b246ec96204c8acd22246d6ad300eaff/main.ts#L634)
Avoid using this.

**Comment by Syr0** [comment]
Updated.

- CSS
- Description
- Version
- "Plugin"
- "Command"
- sentence case
- could not remove activeleaf usage. tried to change it a bit

**Comment by Syr0** [comment]
update available.

**Comment by Syr0** [comment]
waiting for review for more then 2 weeks already. Getting annoyed by constantly having to update the community json.

**Comment by Syr0** [comment]
3  weeks already

**Comment by liamcain** [comment]
- [this.app.workspace.on("editor-menu", (menu, editor, view) => {](https://github.com/Syr0/R.E.L.A.X./blob/78241667f1edbead0f3f3f5f140592b9da9ca858/main.ts#L740) you can combine this with the earlier editor-menu callback
- [getLeaf](https://github.com/Syr0/R.E.L.A.X./blob/78241667f1edbead0f3f3f5f140592b9da9ca858/main.ts#L805) you should not be calling getLeaf here since that will possibly create a new leaf. If you are looking for the active file, you should use [`getActiveFile`](https://github.com/obsidianmd/obsidian-api/blob/38dd22168d2925086371bfc59e36fd9121527a39/obsidian.d.ts#L4146)
- [.read(noteFile);](https://github.com/Syr0/R.E.L.A.X./blob/78241667f1edbead0f3f3f5f140592b9da9ca858/main.ts#L819) instead of calling read+modify, you should use [process](https://github.com/obsidianmd/obsidian-api/blob/bbb696aeb8bf5126bf2ecbf84fc8284fe133bc20/obsidian.d.ts#L900) to atomically read and write the new file contents to disk.

**Comment by Syr0** [comment]
Recheck for update?

**Pull request merged**
