### PR TITLE
add Obsidian ibook plugin

### PR DESCRIPTION
**Pull request by bingryan**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/bingryan/obsidian-ibook-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[id: 'ibook-export-command',](https://github.com/bingryan/obsidian-ibook-plugin/blob/eb37dfd9e97a6cf3846514389fb98ed4d257fd37/src/plugin.ts#L20)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

[html2markdown(html: string) {](https://github.com/bingryan/obsidian-ibook-plugin/blob/eb37dfd9e97a6cf3846514389fb98ed4d257fd37/src/export.ts#L82-L84)
Obsidian exposes the [`htmlToMarkdown`](https://github.com/obsidianmd/obsidian-api/blob/bceb489fc25ceba5973119d6e57759d64850f90d/obsidian.d.ts#L1629-L1633) function for this, its using turndown internally also.

**Comment by bingryan** [comment]
@joethei Thanks for your suggestion, I have fixed it 🤓

**Comment by liamcain** [comment]
- [trigger("file-open")](https://github.com/bingryan/obsidian-ibook-plugin/blob/5b2505dbabe7129a8effd2e0aef0dbd8bec87b45/src/plugin.ts#L25) [`file-open`](https://github.com/obsidianmd/obsidian-api/blob/ec589e9762a1d7e2faad01f894cb34c41b10ecaf/obsidian.d.ts#L4189) file-open should also pass in the currently open file. I don't recommend using this approach for refreshing the view since it will have unintended side-effects (many views in the app will react to the file-open event). What are you trying to accomplish with this line exactly?

**Comment by bingryan** [comment]
> 

i want to refresh the left sidebar

**Comment by bingryan** [comment]
> * [trigger("file-open")](https://github.com/bingryan/obsidian-ibook-plugin/blob/5b2505dbabe7129a8effd2e0aef0dbd8bec87b45/src/plugin.ts#L25) [`file-open`](https://github.com/obsidianmd/obsidian-api/blob/ec589e9762a1d7e2faad01f894cb34c41b10ecaf/obsidian.d.ts#L4189) file-open should also pass in the currently open file. I don't recommend using this approach for refreshing the view since it will have unintended side-effects (many views in the app will react to the file-open event). What are you trying to accomplish with this line exactly?

this.app.workspace.trigger("file-explorer:refresh");

a better expression?

**Comment by liamcain** [comment]
The file explorer view should automatically refresh with the newly created file without needing to trigger a refresh automatically. Is this not the behavior you're seeing?

> this.app.workspace.trigger("file-explorer:refresh");

I don't understand. This event doesn't exist.

**Comment by bingryan** [comment]
> The file explorer view should automatically refresh with the newly created file without needing to trigger a refresh automatically. Is this not the behavior you're seeing?

When I was developing, after `export` command action , The ibook directory(the target directory where I generated the document) already existed in the vault , but the left sidebar was not refresh and show this directory. so I added an event to avoid my target directory doesn't show up after command action.

**Comment by bingryan** [comment]
I closed all plugins in the development environment , find: file explorer view automatically refresh 

I have delete that code

**Comment by liamcain** [comment]
Okay, so it sounds like everything is working fine without that code?

**Comment by bingryan** [comment]
> Okay, so it sounds like everything is working fine without that code. Is that right?

yes🤓

**Pull request merged**
