### PR TITLE
Add plugin: Floating Highlights

### PR DESCRIPTION
**Pull request by KarthikRaju391**
# I am submitting a new Community Plugin
## Repo URL
Link to my plugin: https://github.com/KarthikRaju391/obsidian-float

## Release Checklist

- [ ] I have tested the plugin on
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] My GitHub release contains all the required files
  - [x] main.js
  - [x] manifest.json
  - [x] styles.css (optional)
- [x] GitHub release name matches the exact version number specified in my manifest.json (Note: Use the exact version number, don't include a prefix v)
- [x] The id in my manifest.json matches the id in the community-plugins.json file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by joethei** [comment]
Please fill the Pull Request template,
you can edit it by clicking the link in your original comment

**Comment by KarthikRaju391** [comment]
I have filled the Pull Request template @joethei

**Comment by joethei** [comment]
["fundingUrl": "",](https://github.com/KarthikRaju391/obsidian-float/blob/4e82d1f30b7f2fa74fab23b68e3cd641c3c96480/manifest.json#L9)
Remove this line if you don't have one

[// Remember to rename these classes and interfaces!](https://github.com/KarthikRaju391/obsidian-float/blob/4e82d1f30b7f2fa74fab23b68e3cd641c3c96480/main.ts#L3-L8)
Remove this since you don't use it.

**Comment by KarthikRaju391** [comment]
@joethei, I have made the changes you requested in my repo.

**Comment by liamcain** [comment]
- [MyPlugin](https://github.com/KarthikRaju391/obsidian-float/blob/2043d73791c1868feed63909ae5649e90878ee16/main.ts#L8) I recommend renaming the class of your plugin to something more unique
- [MyPluginSettings](https://github.com/KarthikRaju391/obsidian-float/blob/2043d73791c1868feed63909ae5649e90878ee16/main.ts#L3) you can remove this since it's not used.
- [focus](https://github.com/KarthikRaju391/obsidian-float/blob/2043d73791c1868feed63909ae5649e90878ee16/styles.css#L10) I suggest making this class name more unique so that it doesn't clash with any other plugins that might create an element with the class ".focus"

**Comment by KarthikRaju391** [comment]
Hi @liamcain, I have made the necessary changes to my repo. Do let me know if there are any more changes. Thanks!

**Comment by liamcain** [comment]
@KarthikRaju391 looks like your manifest.json file is pointing to the wrong release here: https://github.com/KarthikRaju391/obsidian-float/blob/c0a248aeb0d050913d75d68f02f20666b1fa656a/manifest.json#L4

Also, did you delete your old 1.0.0 release? I suggest just creating new releases instead of deleting old ones.

**Comment by KarthikRaju391** [comment]
Hi @liamcain, sorry I forgot about the manifest.json. And coming to the releases, I just updated the old one, I'll just fix that and let you know

**Comment by KarthikRaju391** [comment]
Hi @liamcain, I have created a new release and updated the old release to have the old binary files and updated the manifest.json file point to the latest release.

**Pull request merged**
