### PR TITLE
Enable Solarized theme for v1.0.0

### PR DESCRIPTION
**Pull request by harmtemolder**
I am submitting an update to my theme, enabling it for v1.0.0 according to [1.0 Theme Migration Guide](https://forum.obsidian.md/t/1-0-theme-migration-guide/42537).

Link to my theme: https://github.com/Slowbad/obsidian-solarized

### CODE REVIEW

**Comment by ericaxu** [comment]
Have you talked to Slowbad and see if they want to keep their name? I'm not familiar with the transfer of ownership and if that has happened, would love to have more context.

One minor thing: you might want to make the screenshot smaller while keeping the 16:9 aspect ratio. That would make your theme load faster in the theme store. You can still include high resolution screenshots in your README.

We recommend using a screenshot of size 512px by 288px as the featured screenshot to minimize loading time.

**Comment by harmtemolder** [comment]
I haven't talked to Slowbad in a while, so emailed him just now. Let's wait for their reaction.

The featured screenshot should be 512x288: https://github.com/Slowbad/obsidian-solarized/blob/main/screenshot.png. Is it larger for you?

**Comment by harmtemolder** [comment]
I've discussed with Slowbad, and they will transfer the repository to my account. So instead of https://github.com/Slowbad/obsidian-solarized it will then be https://github.com/harmtemolder/obsidian-solarized. I'll change this PR accordingly

**Comment by ericaxu** [comment]
> I haven't talked to Slowbad in a while, so emailed them just now. Let's wait for their reaction.
> 
> The featured screenshot should be 512x288: https://github.com/Slowbad/obsidian-solarized/blob/main/screenshot.png. Is it larger for you?

Oops, my bad! Sounds good!

https://github.com/harmtemolder/obsidian-solarized isn't accessible though, did you make it private?

**Comment by harmtemolder** [comment]
Yes, I know, sorry about that. Slowbad agreed to transfer the repository, but hasn't actually transferred it yet. I'll update you here when they do.

**Comment by ericaxu** [comment]
Thanks. Please unmark it draft once you're ready too.

**Comment by harmtemolder** [comment]
Slowbad has come through: the repository is now available here: https://github.com/harmtemolder/obsidian-solarized

**Comment by ericaxu** [comment]
Great, sounds good!

**Pull request merged**
