### PR TITLE
Add plugin: Relay

### PR DESCRIPTION
**Pull request by dtkav**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/No-Instructions/Relay

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(n/a)_
  - [ ]  iOS _(n/a)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by dtkav** [comment]
> Thank you for your submission, an automated scan of your plugin code's revealed the following issues:
> 
> ### Required
> 
> [[1](https://github.com/no-instructions/relay/blob/2f29277694105ae04b6df82d25f0abab139d0058/src/obsidian-api/Vault.ts#L44)]:You should not cast this, instead use a `instanceof` check to make sure that it's actually the adapter you expect.
> 
> [[1](https://github.com/no-instructions/relay/blob/2f29277694105ae04b6df82d25f0abab139d0058/src/ui/Banner.ts#L40)][[2](https://github.com/no-instructions/relay/blob/2f29277694105ae04b6df82d25f0abab139d0058/src/ui/Banner.ts#L60)]:Using `innerHTML`, `outerHTML` or similar API's is a security risk. Instead, use the DOM API or the Obsidian helper functions: <https://docs.obsidian.md/Plugins/User+interface/HTML+elements>
> 
> [[1](https://github.com/no-instructions/relay/blob/2f29277694105ae04b6df82d25f0abab139d0058/__tests__/TestTokenStore.ts#L24)][[2](https://github.com/no-instructions/relay/blob/2f29277694105ae04b6df82d25f0abab139d0058/__tests__/TestTokenStore.ts#L85)][[3](https://github.com/no-instructions/relay/blob/2f29277694105ae04b6df82d25f0abab139d0058/__tests__/TestTokenStore.ts#L88)][[4](https://github.com/no-instructions/relay/blob/2f29277694105ae04b6df82d25f0abab139d0058/__tests__/TestTokenStore.ts#L105)][[5](https://github.com/no-instructions/relay/blob/2f29277694105ae04b6df82d25f0abab139d0058/__tests__/TestTokenStore.ts#L106)][[6](https://github.com/no-instructions/relay/blob/2f29277694105ae04b6df82d25f0abab139d0058/__tests__/TestTokenStore.ts#L137)][[7](https://github.com/no-instructions/relay/blob/2f29277694105ae04b6df82d25f0abab139d0058/__tests__/TestTokenStore.ts#L140)][[8](https://github.com/no-instructions/relay/blob/2f29277694105ae04b6df82d25f0abab139d0058/src/LoginManager.ts#L37)][[9](https://github.com/no-instructions/relay/blob/2f29277694105ae04b6df82d25f0abab139d0058/src/LoginManager.ts#L117)][[10](https://github.com/no-instructions/relay/blob/2f29277694105ae04b6df82d25f0abab139d0058/src/LiveTokenStore.ts#L34)][[11](https://github.com/no-instructions/relay/blob/2f29277694105ae04b6df82d25f0abab139d0058/src/LiveTokenStore.ts#L93)][[12](https://github.com/no-instructions/relay/blob/2f29277694105ae04b6df82d25f0abab139d0058/src/HasProvider.ts#L86)][[13](https://github.com/no-instructions/relay/blob/2f29277694105ae04b6df82d25f0abab139d0058/src/RelayManager.ts#L717)][[14](https://github.com/no-instructions/relay/blob/2f29277694105ae04b6df82d25f0abab139d0058/src/SharedFolder.ts#L149)][[15](https://github.com/no-instructions/relay/blob/2f29277694105ae04b6df82d25f0abab139d0058/src/Document.ts#L20)][[16](https://github.com/no-instructions/relay/blob/2f29277694105ae04b6df82d25f0abab139d0058/src/y-codemirror.next/LiveEditPlugin.ts#L42)][[17](https://github.com/no-instructions/relay/blob/2f29277694105ae04b6df82d25f0abab139d0058/src/NetworkStatus.ts#L17)][[18](https://github.com/no-instructions/relay/blob/2f29277694105ae04b6df82d25f0abab139d0058/src/main.ts#L70)][[19](https://github.com/no-instructions/relay/blob/2f29277694105ae04b6df82d25f0abab139d0058/src/main.ts#L235)][[20](https://github.com/no-instructions/relay/blob/2f29277694105ae04b6df82d25f0abab139d0058/src/main.ts#L251)]:You should consider limiting the number of `console.log`s in your code, to not pollute the dev console.
> 
> 
> 
> ---
> 
> ### Optional
> 
> [[1](https://github.com/no-instructions/relay/blob/2f29277694105ae04b6df82d25f0abab139d0058/src/LiveViews.ts#L394)][[2](https://github.com/no-instructions/relay/blob/2f29277694105ae04b6df82d25f0abab139d0058/src/ui/SettingsTab.ts#L26)][[3](https://github.com/no-instructions/relay/blob/2f29277694105ae04b6df82d25f0abab139d0058/src/main.ts#L218)]:Casting to `any` should be avoided as much as possible.
> 
> 
> 
> ---
> 
> 
> 
> Do <b>NOT</b> open a new PR for re-validation.
> Once you have pushed all of the required changes to your repo, the bot will update the labels on this PR within 6 hours.
> If you think some of the required changes are incorrect, please comment with `/skip` and the reason why you think the results are incorrect.

fixed

**Comment by dtkav** [comment]
/skip there are some console.log calls in tests and a single place where logging is enabled dynamically via `{ "debugging": true"}` settings.

**Comment by dtkav** [comment]
@joethei apologies for the ping -- I haven't been able to get @ObsidianReviewBot to re-run.

Things I tried:
- Pushing code to my repo and waiting 6 hours
- Pushing a new tag & release and waiting 6 hours

I also have a purposeful runtime-enabled console.log for debugging so I ended up commenting `/skip`.

I'm unsure of next steps. I assume I need the `ready for review` tag, but I don't know how to get it.

Thank you

**Comment by joethei** [comment]
[To our knowledge, Relay is the only Obsidian plugin that makes use of CRDTs.](https://github.com/No-Instructions/Relay/blob/405058ffc9b7f40fcf44af2e83ed67f91a4066d3/README.md#L27)
All of the collaboration plugins I've reviewed so far use yjs in some form, so this is incorrect.

[import moment from "moment";](https://github.com/No-Instructions/Relay/blob/405058ffc9b7f40fcf44af2e83ed67f91a4066d3/src/SharedFolder.ts#L15)
Use `import {moment} from "obsidian";` instead.

[contentEl.createEl("h2", { text: "Share Settings" });](https://github.com/No-Instructions/Relay/blob/405058ffc9b7f40fcf44af2e83ed67f91a4066d3/src/ui/FolderSharing.ts#L35), [item.setTitle("Unshare Folder")](https://github.com/No-Instructions/Relay/blob/405058ffc9b7f40fcf44af2e83ed67f91a4066d3/src/ui/FolderMenu.ts#L35), [item.setTitle("Copy Share Key").onClick(() =>](https://github.com/No-Instructions/Relay/blob/405058ffc9b7f40fcf44af2e83ed67f91a4066d3/src/ui/FolderMenu.ts#L47), [item.setTitle("Share Folder")](https://github.com/No-Instructions/Relay/blob/405058ffc9b7f40fcf44af2e83ed67f91a4066d3/src/ui/FolderMenu.ts#L62), [.then(() => new Notice("Invite Link Copied"))](https://github.com/No-Instructions/Relay/blob/405058ffc9b7f40fcf44af2e83ed67f91a4066d3/src/components/ManageRelay.svelte#L154), [name="Folder Name"](https://github.com/No-Instructions/Relay/blob/405058ffc9b7f40fcf44af2e83ed67f91a4066d3/src/components/AddToVaultModalContent.svelte#L27), [name="Folder Location"](https://github.com/No-Instructions/Relay/blob/405058ffc9b7f40fcf44af2e83ed67f91a4066d3/src/components/AddToVaultModalContent.svelte#L34)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by dtkav** [comment]
Great, thank you!
I have:
- Removed that statement from the readme
- Migrated to using obsidian's moment
- Removed unused files (FileMenu.ts, FolderSharing.ts)
- Updated sentence case in remaining places ("Invite link copied", "Folder name", "Folder location")

I'm going to do a bit of testing with BRAT and then I will push a new stable release shortly.

**Comment by dtkav** [comment]
> [To our knowledge, Relay is the only Obsidian plugin that makes use of CRDTs.](https://github.com/No-Instructions/Relay/blob/405058ffc9b7f40fcf44af2e83ed67f91a4066d3/README.md#L27) All of the collaboration plugins I've reviewed so far use yjs in some form, so this is incorrect.
> 
> [import moment from "moment";](https://github.com/No-Instructions/Relay/blob/405058ffc9b7f40fcf44af2e83ed67f91a4066d3/src/SharedFolder.ts#L15) Use `import {moment} from "obsidian";` instead.
> 
> [contentEl.createEl("h2", { text: "Share Settings" });](https://github.com/No-Instructions/Relay/blob/405058ffc9b7f40fcf44af2e83ed67f91a4066d3/src/ui/FolderSharing.ts#L35), [item.setTitle("Unshare Folder")](https://github.com/No-Instructions/Relay/blob/405058ffc9b7f40fcf44af2e83ed67f91a4066d3/src/ui/FolderMenu.ts#L35), [item.setTitle("Copy Share Key").onClick(() =>](https://github.com/No-Instructions/Relay/blob/405058ffc9b7f40fcf44af2e83ed67f91a4066d3/src/ui/FolderMenu.ts#L47), [item.setTitle("Share Folder")](https://github.com/No-Instructions/Relay/blob/405058ffc9b7f40fcf44af2e83ed67f91a4066d3/src/ui/FolderMenu.ts#L62), [.then(() => new Notice("Invite Link Copied"))](https://github.com/No-Instructions/Relay/blob/405058ffc9b7f40fcf44af2e83ed67f91a4066d3/src/components/ManageRelay.svelte#L154), [name="Folder Name"](https://github.com/No-Instructions/Relay/blob/405058ffc9b7f40fcf44af2e83ed67f91a4066d3/src/components/AddToVaultModalContent.svelte#L27), [name="Folder Location"](https://github.com/No-Instructions/Relay/blob/405058ffc9b7f40fcf44af2e83ed67f91a4066d3/src/components/AddToVaultModalContent.svelte#L34) [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

fixed and released

Thank you @joethei

**Comment by dtkav** [comment]
> One more thing:
> [`<h1>Relay</h1>`](https://github.com/No-Instructions/Relay/blob/a6a20fdd6ec8eb159810a87c8d5a8c05f119c038/src/components/LoggedIn.svelte#L27)
> [Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

Fixed!

**Pull request merged**
