### PR TITLE
Add plugin: Notification Controller

### PR DESCRIPTION
**Pull request by juan-miii**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/juan-miii/obsidian-notice-plugin

## Release Checklist
- [ ] I have tested the plugin on
  - [X]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [X] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by juan-miii** [comment]
Added the release and tag

**Comment by juan-miii** [comment]
Sorry for any inconvenience.

**Comment by joethei** [comment]
["description": "Manages notifications at Obsidian startup.",](https://github.com/juan-miii/obsidian-notice-plugin/blob/8d684ed14dba877556b0584718f5dd625d62ad49/manifest.json#L6)
Avoid including "Obsidian" in your description, it should be self-evident that this is a plugin for Obsidian.

**Comment by juan-miii** [comment]
@joethei I have done the proposed changes, you can now check them. Thank you for dedicating time to this revision.

**Comment by joethei** [comment]
You have not made the change in the plugin manifest, please do so.

**Pull request merged**
