### PR TITLE
Added lukauskas/obsidian-highlighter-theme

### PR DESCRIPTION
**Pull request by lukauskas**
Sharing my theme.

### CODE REVIEW

**Comment by ericaxu** [comment]
Thank you for the PR!

Since you're using the `main` branch, can you add that please?

**Comment by lukauskas** [comment]
> Since you're using the `main` branch, can you add that please?

Well spotted! I didn't realise it myself ...  6fb8801 should fix it.

**Comment by ericaxu** [comment]
I'll just add it myself since resolving the conflict is too much trouble... Thanks for sharing your theme!

**Comment by ericaxu** [comment]
Added in https://github.com/obsidianmd/obsidian-releases/commit/7ba32cb4408748b5831f963ea0badc13aea41b09. Thanks!

**Pull request closed without merging**
