### PR TITLE
add linked-data-vocabularies

### PR DESCRIPTION
**Pull request by kometenstaub**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/kometenstaub/obsidian-linked-data-vocabularies

## Release Checklist

- [x] I have tested this on Windows and Linux
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by kometenstaub** [comment]
Please only merge this together with #616 because this submission depends on the helper plugin.

**Comment by lishid** [comment]
https://github.com/kometenstaub/obsidian-linked-data-vocabularies/blob/89f3b0e836fc8d09ae29f72a1f70279a4b555479/src/main.ts#L46
Please don't do this - this could eventually become incompatible with Obsidian Core if we do need to make changes to this. What I recommend you to do instead, is to force overwrite the command name after calling the base class's addCommand function, instead of writing your copy of the addCommand function.

https://github.com/kometenstaub/obsidian-linked-data-vocabularies/blob/89f3b0e836fc8d09ae29f72a1f70279a4b555479/src/main.ts#L72
Not sure what this timeout is for, but if it's essential I'd recommend adding a comment to explain why it's necessary.

https://github.com/kometenstaub/obsidian-linked-data-vocabularies/blob/89f3b0e836fc8d09ae29f72a1f70279a4b555479/src/main.ts#L86
Maybe destroy the worker once it's done?

**Comment by kometenstaub** [comment]
> https://github.com/kometenstaub/obsidian-linked-data-vocabularies/blob/89f3b0e836fc8d09ae29f72a1f70279a4b555479/src/main.ts#L46
> Please don't do this - this could eventually become incompatible with Obsidian Core if we do need to make changes to this. What I recommend you to do instead, is to force overwrite the command name after calling the base class's addCommand function, instead of writing your copy of the addCommand function.

I hope I did this correctly.
https://github.com/kometenstaub/obsidian-linked-data-vocabularies/blob/accbf96aae358409f027a5c9856b0d9cab7fdacb/src/main.ts#L45

> https://github.com/kometenstaub/obsidian-linked-data-vocabularies/blob/89f3b0e836fc8d09ae29f72a1f70279a4b555479/src/main.ts#L72
> Not sure what this timeout is for, but if it's essential I'd recommend adding a comment to explain why it's necessary.

I removed it.
https://github.com/kometenstaub/obsidian-linked-data-vocabularies/blob/accbf96aae358409f027a5c9856b0d9cab7fdacb/src/main.ts#L65

> https://github.com/kometenstaub/obsidian-linked-data-vocabularies/blob/89f3b0e836fc8d09ae29f72a1f70279a4b555479/src/main.ts#L86
> Maybe destroy the worker once it's done?

Done.
https://github.com/kometenstaub/obsidian-linked-data-vocabularies/blob/accbf96aae358409f027a5c9856b0d9cab7fdacb/src/main.ts#L77

Please don't merge this yet, I still have to make the changes for #616.

**Comment by lishid** [comment]
> I hope I did this correctly.

You'll want to keep a reference to your command name at the beginning of the function, because super.addCommand will mutate the command name, so you'll end up with a duplicate string.

https://github.com/kometenstaub/obsidian-linked-data-vocabularies/blob/accbf96aae358409f027a5c9856b0d9cab7fdacb/src/main.ts#L16
I didn't seem to find the worker script in the repo, is it generated from some sources?

**Comment by kometenstaub** [comment]
Re the worker script:
It is here https://github.com/kometenstaub/obsidian-linked-data-vocabularies/blob/accbf96aae358409f027a5c9856b0d9cab7fdacb/src/workers/readJson.worker.ts

The import is like that because that's how the esbuild inline worker plugin works.

**Comment by kometenstaub** [comment]
https://github.com/kometenstaub/obsidian-linked-data-vocabularies/blob/9476e914a4d401e1fb82a683f628510e7fafb285/src/main.ts#L51

I have fixed the command name. I didn't notice it before because I had set a hotkey for it. A new release is out.

**Comment by kometenstaub** [comment]
I also rebased the branch on `master`, so that this and #616 are next to each other when sorted by recency.

**Pull request merged**
