### PR TITLE
Add Obsidian reading comments plugin

### PR DESCRIPTION
**Pull request by BumbrT**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/BumbrT/obsidian-reading-comments

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [ x] `main.js`
  - [x ] `manifest.json`
  - [x ] `styles.css` _(optional)_
- [ x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by liamcain** [comment]
- [currentNote: MarkdownView](https://github.com/BumbrT/obsidian-reading-comments/blob/c2b1bb2e794aa8967aee5776ff169871da149b8b/src/obsidianPlugin.ts#L14) you shouldn't be trying to manage a reference to the active view yourself. This will prevent the view from being properly recycled from memory when its supposed to. If you just want the last open focused, then you can use [`getActiveFile`](https://github.com/obsidianmd/obsidian-api/blob/38dd22168d2925086371bfc59e36fd9121527a39/obsidian.d.ts#L4146). This should give you the same thing you're trying to capture. Then you can just get the file contents by reading the TFile instead of using getViewData()

**Comment by BumbrT** [comment]
> * [currentNote: MarkdownView](https://github.com/BumbrT/obsidian-reading-comments/blob/c2b1bb2e794aa8967aee5776ff169871da149b8b/src/obsidianPlugin.ts#L14) you shouldn't be trying to manage a reference to the active view yourself. This will prevent the view from being properly recycled from memory when its supposed to. If you just want the last open focused, then you can use [`getActiveFile`](https://github.com/obsidianmd/obsidian-api/blob/38dd22168d2925086371bfc59e36fd9121527a39/obsidian.d.ts#L4146). This should give you the same thing you're trying to capture. Then you can just get the file contents by reading the TFile instead of using getViewData()

Hi, Thanks for comment. Is it possible to get file view by TFile, returned by "getActiveFile". After cleanup reference to current note, cant implement logic to navigate in file by click in my plugin window.

**Comment by liamcain** [comment]
You can check if `app.workspace.activeEditor instanceof MarkdownView`.

**Comment by BumbrT** [comment]
Tried this way, but when i click something in my plugin window, `app.workspace.activeEditor` is always null :(

**Comment by liamcain** [comment]
Ah, sorry. That was a bad suggestion on my part then. For now I suggest you use the private API:

```ts
let view = workspace.getActiveFileView();
```

You'll need to tsignore it but it should get you the view you're looking for.

**Comment by BumbrT** [comment]
Thank you, published new version with this active file/view reference approach.

**Pull request merged**
