### PR TITLE
Add "Set Mobile Theme"

### PR DESCRIPTION
**Pull request by selfire1**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/selfire1/obsidian-set-mobile-theme

## Release Checklist

- [x] I have tested this on Windows, macOS, and Linux _(if applicable)_ (Note: Not tested on Windows!)
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by ericaxu** [comment]
Great theme, thanks for the submission!

**Comment by phibr0** [comment]
@ericaxu This is actually a Plugin which probably should have been reviewed.

In fact there are some potential Issues:

https://github.com/selfire1/obsidian-set-mobile-theme/blob/main/main.ts#L71
Not sure if there's any undefined behavior if you try to set a theme that was deleted (The "internal" Theme is set to it anyway, but it looks like the default theme, because other themes also just override the default one). For example if I delete the theme I had set for Desktop on my phone and then switch to Desktop again.

https://github.com/selfire1/obsidian-set-mobile-theme/blob/main/main.ts#L18
You are setting the Theme to something that might not be available on the device.

https://github.com/selfire1/obsidian-set-mobile-theme/blob/main/main.ts#L44
You probably want to await this, even though it wouldn't change anything

**Comment by ericaxu** [comment]
@selfire1 Sorry I accidentally merged this thinking it was your "Obsidian You" theme. It doesn't seem like I can undo the merge, so could you copy paste the PR and submit it again? So sorry!!

**Comment by selfire1** [comment]
No worries! I'll submit another PR and will also get started on the aforementioned improvements. Thank you!

**Pull request merged**
