### PR TITLE
Add obsidian-bmo-chatbot-plugin

### PR DESCRIPTION
**Pull request by longy2k**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/longy2k/obsidian-bmo-chatbot

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
What sets your plugin apart from the other existing Chat-GPT/GPT-3 plugins?

If there is more than one `.ts` file, I generally recommend moving all code files into a separate `src` folder, that makes it easier to review and maintain.

[description](https://github.com/longy2k/obsidian-bmo-chatbot/blob/ac02844302003584f8a9be1a4ca72fca2e0d97a1/manifest.json#L6)
Please update this description following our new guidelines: <https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple>

[this.app.workspace.detachLeavesOfType(VIEW_TYPE_EXAMPLE);](https://github.com/longy2k/obsidian-bmo-chatbot/blob/ac02844302003584f8a9be1a4ca72fca2e0d97a1/main.ts#L65)
[Don't detach leaves in `onunload`](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Don't+detach+leaves+in+%60onunload%60)

[export const VIEW_TYPE_EXAMPLE = "example-view";](https://github.com/longy2k/obsidian-bmo-chatbot/blob/ac02844302003584f8a9be1a4ca72fca2e0d97a1/view.ts#LL6C49-L6C49)
Update this.

[userMessage.style.display = "inline-block";](https://github.com/longy2k/obsidian-bmo-chatbot/blob/ac02844302003584f8a9be1a4ca72fca2e0d97a1/view.ts#L110)
You should avoid assigning styles via JavaScript and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets

[await fetch('...')](https://github.com/longy2k/obsidian-bmo-chatbot/blob/ac02844302003584f8a9be1a4ca72fca2e0d97a1/view.ts#LL264C12-L264C89)
I would recommend using the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

[containerEl.createEl('h2', {text: 'Settings for obsidian-bmo-chatbot'});](https://github.com/longy2k/obsidian-bmo-chatbot/blob/ac02844302003584f8a9be1a4ca72fca2e0d97a1/settings.ts#L18)
You should use a better title.

**Comment by longy2k** [comment]
Hello,

I believe I satisfied most of the changes requested.

I was not able to change fetch to requestUrl or request since I am not sure how the text streams based on the current functionality. If there is a way to stream text using requestUrl or request, please let me know.

I also moved most styles in javascript to css. However, I want to allow the user to customize their chatbot which requires modifying the backgroundColors using javascript.

I hope I did not miss anything else, if I did, please let me know, I will be happy to clean it up :)

---

**What sets your plugin apart from the other existing Chat-GPT/GPT-3 plugins?**

BMO Chatbot aims to enhance the user's experience by offering a high level of customization. Users can effortlessly personalize their username and chatbot's name. They can also have the freedom to change the interface background colors to match the user's preferences. BMO Chatbot also supports drop-in REST API such as LocalAI (currently in progress), allowing you to seamlessly integrate your own self-hosted language models (LLMs) and create a customized conversational experience.

I hope that BMO Chatbot can provide a solution that prioritizes both ease of use and enhances the overall user experience.

**Comment by liamcain** [comment]
- [var](https://github.com/longy2k/obsidian-bmo-chatbot/blob/9e59a45ebe9c1682f136a99e5672a8b2a46c4151/src/view.ts#L17) I recommend you change all instances of `var` to either `const` or `let`. `var` has function-level scope, so it can easily lead to bugs if you're not careful. Here's a pretty good guide with examples of why not to use `var`: [why `var` is obsolete](https://javascript.plainenglish.io/4-reasons-why-var-is-considered-obsolete-in-modern-javascript-a30296b5f08f).
- [Background Color for Chatbot Container](https://github.com/longy2k/obsidian-bmo-chatbot/blob/9e59a45ebe9c1682f136a99e5672a8b2a46c4151/src/settings.ts#L203) I think it's better if you just expose CSS variables for customizing the styling of your view. This will be a more consistent user experience for Obsidian users. It will also simplify your code a lot since you won't need to keep parsing the settings every time you set up your view. It will also work well with light/dark mode since you can provide defaults for both modes without any extra work.

**Comment by joethei** [comment]
Hi @longy2k,

Do you still intend on submitting this plugin?

**Comment by longy2k** [comment]
> Hi @longy2k,
> 
> Do you still intend on submitting this plugin?

Hello,

Yes, I would like to continue this plugin as soon as I can.

I will try to update this plugin within the following week!

Thanks

**Review by longy2k — COMMENTED** [review]
Change adjusted.

**Pull request merged**
