### PR TITLE
Add plugin: OnlyWorlds Builder

### PR DESCRIPTION
**Pull request by tmoosting**
# I am submitting a new Community Plugin

## Repo URL
 
Link to my plugin: https://github.com/OnlyWorlds/obsidian-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by tmoosting** [comment]
Handled all required and optional issues

**Comment by liamcain** [comment]
- [Handlebars.registerHelper('linkify',](https://github.com/OnlyWorlds/obsidian-plugin/blob/a27db9cb680120d7abed07ecde8e7a8879edce35/main.ts#L44) looks like this is duplicated belo

**Comment by tmoosting** [comment]
Hi Liam,
Thank you for your attention & time. This is not an environment I am very familiar with so I appreciate your pointers.
I made changes accordingly, except for two cases:
1. I did not manage to use the Vault API for the second of those suggestions (5th bullet point, "same here" , for ImportWorldCommand). In this case, a file is accessed from the plugin files, not from the vault itself, so as I eventually assumed, I should not use the vault API for this. If I nonetheless should, please advise the relative path I should use with getAbstractFileByPath. 
2. Regarding the section pattern with getFileCache (8th bullet point): this piece of codes is meant to parse a specific JSON structure I have, from data that is directly inputted by the user, so I do not think I can use the cache for this. Again, please advise if I misunderstand.

**Comment by liamcain** [comment]
Sorry for the long delay getting back to this. Your changes look good to me!

**Comment by liamcain** [comment]
Plugin added here: https://github.com/obsidianmd/obsidian-releases/commit/727da498181fc9b92863b17430979316b79d0192

**Pull request closed without merging**
