### PR TITLE
Added Vextab to community-plugins.json

### PR DESCRIPTION
**Pull request by luigman**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/luigman/obsidian-vextab

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[@import "https://fonts.googleapis.com/css?family=Inter&display=swap";](https://github.com/luigman/obsidian-vextab/blob/7e43feeef165c65ac3cc148c414369a9f1e143dd/main.css#L1)
[@import url('https://fonts.googleapis.com/css?family=Inter&display=swap');](https://github.com/luigman/obsidian-vextab/blob/7e43feeef165c65ac3cc148c414369a9f1e143dd/styles.css#L9)
"Inter" is already in Obsidian by default, no need to import it.
This would also break on devices without internet connection.


[import {VexTab, Artist, Vex} from './vextab-dist/main.prod';](https://github.com/luigman/obsidian-vextab/blob/7e43feeef165c65ac3cc148c414369a9f1e143dd/main.ts#L2)
Why are you importing vextab from this folder, instead of the one you have included in your dependencies?

**Comment by luigman** [comment]
> "Inter" is already in Obsidian by default, no need to import it.

Thanks, I removed those imports. I'll create a new release with the changes from this PR.

> Why are you importing vextab from this folder, instead of the one you have included in your dependencies?

There is an [open issue with the VexTab API](https://github.com/0xfe/vextab/issues/106). Changing that line to
```
import {VexTab, Artist, Vex} from 'vextab';
```
results in
```
Import "VexTab" will always be undefined because the file "node_modules/vextab/dist/main.prod.js" has no exports
```
(and similar errors for Artist and Vex). Until this issue is resolved, I planned on including a manual build of VexTab in my repo and updating it periodically. [The last comment](https://github.com/0xfe/vextab/issues/106#issuecomment-1085036982) on the issue describes a similar workaround.

**Comment by liamcain** [comment]
- [editButton.style.float = "right"](https://github.com/luigman/obsidian-vextab/blob/aa9be48af7888749691af49041009a9d8d37360f/main.ts#L86-L89) You should avoid assigning styles via javascript. Instead, just add a class to the element and move all these styles into CSS so that they are more easily adaptable by themes.

**Comment by luigman** [comment]
Thanks @liamcain. I made your suggested changes and resolved the merge conflicts.

**Pull request merged**
