### PR TITLE
Add plugin: Custom save

### PR DESCRIPTION
**Pull request by HananoshikaYomaru**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/HananoshikaYomaru/obsidian-custom-save

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by HananoshikaYomaru** [comment]
The name in LICENSE is `Yeung Man Lung Ken` which is my real name on passport. Don't ask me to change it.

**Comment by joethei** [comment]
["description": "Add custom save actions to obsidian",](https://github.com/HananoshikaYomaru/obsidian-custom-save/blob/fb387ed8cd7dce710fcae8b9af080ff924df0271/manifest.json#L6)
That description (along with the one in your readme) is a bit confusing, I would suggest something like:
> Run any commands when you 
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[console.log("loaded: ", loadedData);](https://github.com/HananoshikaYomaru/obsidian-custom-save/blob/fb387ed8cd7dce710fcae8b9af080ff924df0271/src/SettingManager.ts#L60), and more
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

---

[hotkeys: [](https://github.com/HananoshikaYomaru/obsidian-custom-save/blob/fb387ed8cd7dce710fcae8b9af080ff924df0271/src/main.ts#L32-L37)
Won't this conflict with the default save action, if one does not change the hotkey settings?
(Yes, I know that it's included in the instructions to change it, but users might not read that part)

**Comment by HananoshikaYomaru** [comment]
Ok I will update the setting to make it easier for people to follow. I will also remove the default hotkey. For obsidian, if there is hotkey crash, only the last only will have effect. So you are right, if they don't update there might be a problem. But since two commands are just save command, there won't be problem. But I will change it anyway.

**Comment by HananoshikaYomaru** [comment]
sorry the name of this plugin might need to be changed. I am planning to expand on this plugin.

**Comment by HananoshikaYomaru** [comment]
After thinking a bit, I don't think I will remove the default hot key from the command because it makes sense that if the command is a save command then it should be Mod + S. Instead I added a warning if there is crash of hot key.

CleanShot 2023-11-29 at 20 35 47@2x
 

CleanShot 2023-11-29 at 20 35 22@2x

And I don't plan to change the name of the plugin because I don't have time to expand the scope of this plugin. It is okay to leave it for now. 

I have fixed all issues. so please review again.

**Pull request merged**
