### PR TITLE
Add plugin: TeamDynamix

### PR DESCRIPTION
**Pull request by rukas**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/rukas/obsidian-teamdynamix

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by rukas** [comment]
I'm not sure what the issue is here. `main.ts` is attached to my [latest release ](https://github.com/rukas/obsidian-teamdynamix/releases/tag/1.0.2)

**Comment by joethei** [comment]
[Copyright (c) 2021 Martin Schenck and Clare Macrae](https://github.com/rukas/obsidian-teamdynamix/blob/29418c007cbeb2c17928e2834cc499a6385ebf3b/LICENSE#L3)
Update this with your own info.

[name: 'Replace TeamDynamix Item IDs With Links',](https://github.com/rukas/obsidian-teamdynamix/blob/29418c007cbeb2c17928e2834cc499a6385ebf3b/src/main.ts#L14)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[containerEl.createEl('h1', { text: 'TeamDynamix' });](https://github.com/rukas/obsidian-teamdynamix/blob/29418c007cbeb2c17928e2834cc499a6385ebf3b/src/main.ts#L87-L88)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[let fileContents = await app.vault.read(file)](https://github.com/rukas/obsidian-teamdynamix/blob/29418c007cbeb2c17928e2834cc499a6385ebf3b/src/updateFileFromServer.ts#L7)
I highly recommend using the Editor interface when possible. Modifying the file as a string and using `vault.modify` might seem easier, but it has a number of downsides:
- Information like the user's cursor position, selections, and any folded content is lost
- It's less efficient. Using the editor allows you to make short positional edits very quickly.

**Comment by liamcain** [comment]
- [updateFileFromServer](https://github.com/rukas/obsidian-teamdynamix/blob/29418c007cbeb2c17928e2834cc499a6385ebf3b/src/main.ts#L28) this function always uses the active file. If you're listening for the file-open event, then you should pass in a TFile to this function to ensure that the file you're operating on is the correct file
- [re-read file contents to reduce race condition after slow server call](https://github.com/rukas/obsidian-teamdynamix/blob/29418c007cbeb2c17928e2834cc499a6385ebf3b/src/updateFileFromServer.ts#L24) you should use process() instead for this exact reason <https://github.com/obsidianmd/obsidian-api/blob/bbb696aeb8bf5126bf2ecbf84fc8284fe133bc20/obsidian.d.ts#L900>
- https://github.com/obsidianmd/obsidian-api/blob/bbb696aeb8bf5126bf2ecbf84fc8284fe133bc20/obsidian.d.ts#L900 you're reading and writing inside this for-loop. You should instead only read the file once, apply all modifications to the fileContents, then write once. Or, as joethei recommended above, you should use the editor interface

**Comment by rukas** [comment]
Thank you for the feedback. I've addressed the issues you mentioned in the [latest release](https://github.com/rukas/obsidian-teamdynamix/releases/tag/1.0.6) of the plugin.  Please let me know if there is further improvements that need to be made.

**Comment by rukas** [comment]
Hi @joethei and @liamcain can you please review the changes I've made?

**Pull request closed without merging**
