### PR TITLE
Add Hide Sidebars When Narrow

### PR DESCRIPTION
**Pull request by mybuddymichael**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/mybuddymichael/obsidian-hide-sidebars-when-narrow

## Release Checklist

- [ ] I have tested this on Windows, macOS, and Linux _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by mybuddymichael** [comment]
I have tested this on macOS, but not Windows or Linux.

**Comment by lishid** [comment]
https://github.com/mybuddymichael/obsidian-hide-sidebars-when-narrow/blob/166d3b44d4a45bb1aaa4cb3914550cfc55aea609/main.ts#L18
I don't think you need to wrap everything in the layout ready - at least you can load settings in your onload directly, with an await, as well as registering the settings tab.

https://github.com/mybuddymichael/obsidian-hide-sidebars-when-narrow/blob/166d3b44d4a45bb1aaa4cb3914550cfc55aea609/main.ts#L25
This timeout is probably not what you want to do  - I think you're looking for the `debounce` function that you can import from `obsidian`.

https://github.com/mybuddymichael/obsidian-hide-sidebars-when-narrow/blob/166d3b44d4a45bb1aaa4cb3914550cfc55aea609/main.ts#L32
I'd recommend using `innerWidth` since `outerWidth` will include the window border as well as things like the debugger window.

**Comment by mybuddymichael** [comment]
Thanks for the review. I believe I've addressed all of these.

**Comment by mybuddymichael** [comment]
I don't have access to a Windows or Linux machine with Obsidian. Do I need to find folks who have those who can help me test before I check that off?

**Pull request merged**
