### PR TITLE
Add obsidian-user-plugins reference

### PR DESCRIPTION
**Pull request by mnowotnik**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/mnowotnik/obsidian-user-plugins

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by liamcain** [comment]
https://github.com/mnowotnik/obsidian-user-plugins/blob/04cec150455394fec3b80ae4a017ebc335ea9e0c/manifest.json#L8 I don't think this plugin will run on mobile

1. You're using `path` which is a node.js library
2. You're using `window.require` which won't run on mobile

Maybe just mark this as desktopOnly for now.

https://github.com/mnowotnik/obsidian-user-plugins/blob/04cec150455394fec3b80ae4a017ebc335ea9e0c/src/main.ts#L34 this function can throw. You should catch the error and continue

https://github.com/mnowotnik/obsidian-user-plugins/blob/731482b427b287cb53f069e604ac23cb0bfe8537/src/main.ts#L72 I recommend also just prefixing this with your plugin name (`[obsidian-user-plugins]`) to make it easier to filter the console

**Comment by mnowotnik** [comment]
@liamcain 
I fixed it according to your specifications.
- removed dep on path and require
- tested it on mobile - works
- catching all the errors and logging
- prefixed logs with the plugin name

**Review by liamcain — APPROVED** [review]

**Comment by liamcain** [comment]
Hi, sorry for the delay! Plugin looks good to me, should be available in the plugin gallery shortly.

**Comment by holroy** [comment]
Is there any reason this plugin is not released until the public yet? If really like to have this functionality available.

**Comment by mnowotnik** [comment]
> Is there any reason this plugin is not released until the public yet? If really like to have this functionality available.

@holroy I haven't looked into this plugin in a while, but last I checked it had been released to community plugins. Please check.

**Comment by holroy** [comment]
My bad, I searched for "Users plugin" and it didn't show,  and when I continued my search and found it only "ready for review" in this list I  thought it wasn't ready. Neither did I notice the "Merged" tag on the top, nor that it is called "User plugins" with singular "User" and plural on "Plugins"...

**Pull request merged**
