### PR TITLE
Add theme: MistyMauve

### PR DESCRIPTION
**Pull request by RaveSplash**
brought to you by RaveSplash

# I am submitting a new Community Theme

## Repo URL

Link to my theme: 

## Theme checklist

- [x ] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo).
  - [x] `manifest.json`
  - [x] `theme.css`
  - [x] The screenshot file (16:9 aspect ratio, recommended size is 512px by 288px for fast loading).
- [x] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my theme's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Themes/App+themes/Theme+guidelines and have self-reviewed my theme to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other themes that I'm using. I have given proper attribution to these other themes in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[`@import url(...`](https://github.com/RaveSplash/obsidian-misty-mauve/blob/bcea282001483270427db98ea98604b3be6eafdf/theme.css#L1-L2)
As per our [developer policies](https://docs.obsidian.md/Developer+policies) themes are not allowed to load assets from the web, you can read this guide on how to load fonts instead: https://docs.obsidian.md/Themes/App+themes/Embed+fonts+and+images+in+your+theme

**Comment by RaveSplash** [comment]
Thanks for the update an advice

**Comment by RaveSplash** [comment]
> [`@import url(...`](https://github.com/RaveSplash/obsidian-misty-mauve/blob/bcea282001483270427db98ea98604b3be6eafdf/theme.css#L1-L2) As per our [developer policies](https://docs.obsidian.md/Developer+policies) themes are not allowed to load assets from the web, you can read this guide on how to load fonts instead: https://docs.obsidian.md/Themes/App+themes/Embed+fonts+and+images+in+your+theme

Hi @joethei , i already make changes to my code and push it into my own repositories. After that, should i also push my code to patch-1 branch? I'm sorry abit confuse on this

**Comment by joethei** [comment]
You push that code into the repository of your theme, then mention here that you have made the change.

**Comment by RaveSplash** [comment]
> You push that code into the repository of your theme, then mention here that you have made the change.

Oh ok, @joethei I already push my updated code into my repository. 

P.S : Sorry for being a newbie , but thanks for your explanation. 😬

**Pull request merged**
