### PR TITLE
Add plugin: Gemini Scribe

### PR DESCRIPTION
**Pull request by allenhutchison**
Add obsidian-gemini plugin.

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/allenhutchison/obsidian-gemini

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [X]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [X]  iOS _(if applicable)_
- [X] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [X] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by allenhutchison** [comment]
Will address the automated checks.

**Comment by allenhutchison** [comment]
Updated to remove the reference to innerHTML and replace with textContent. However it's important to point out that this was only ever used to pass context to the model.

**Comment by allenhutchison** [comment]
Thanks for the review. I've updated the source to respond to your comments, and published a new release with those changes.

**Comment by allenhutchison** [comment]
Fixed automated checks and have responded to reviews. What is the next step here?

**Comment by joethei** [comment]
The bot should have changed the labels, not sure why it did not.
I'll re-review shortly, after that I'll either request some more changes, or merge.

**Pull request merged**
