### PR TITLE
Add plugin: Custom new file name

### PR DESCRIPTION
**Pull request by homu-konamilk**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/homu-konamilk/obsidian-custom-new-file-name/tree/main

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["name": "Custom New File Name",](https://github.com/homu-konamilk/obsidian-custom-new-file-name/blob/0729b6bafc6115eec371beb6deacf711c324ff95/manifest.json#L3)
This should be in sentence case.

["minAppVersion": "0.9.7",](https://github.com/homu-konamilk/obsidian-custom-new-file-name/blob/0729b6bafc6115eec371beb6deacf711c324ff95/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

[item.setTitle('New Note (with Custom Name)')](https://github.com/homu-konamilk/obsidian-custom-new-file-name/blob/0729b6bafc6115eec371beb6deacf711c324ff95/main.ts#L25), [.setName('New File Name Format')](https://github.com/homu-konamilk/obsidian-custom-new-file-name/blob/0729b6bafc6115eec371beb6deacf711c324ff95/main.ts#L116)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by homu-konamilk** [comment]
Thank you for your review.

> ["name": "Custom New File Name",](https://github.com/homu-konamilk/obsidian-custom-new-file-name/blob/0729b6bafc6115eec371beb6deacf711c324ff95/manifest.json#L3)
> This should be in sentence case.

I noticed other plugins use Title Case. Is there a specific reason for preferring sentence case here?

> ["minAppVersion": "0.9.7",](https://github.com/homu-konamilk/obsidian-custom-new-file-name/blob/0729b6bafc6115eec371beb6deacf711c324ff95/manifest.json#L5)
> You are using newer API's, set this to the latest public build number.

I've updated this to the latest public build number as advised.

> [item.setTitle('New Note (with Custom Name)')](https://github.com/homu-konamilk/obsidian-custom-new-file-name/blob/0729b6bafc6115eec371beb6deacf711c324ff95/main.ts#L25), [.setName('New File Name Format')](https://github.com/homu-konamilk/obsidian-custom-new-file-name/blob/0729b6bafc6115eec371beb6deacf711c324ff95/main.ts#L116)
> [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

I've adjusted these to use sentence case.

---

I've updated the repository with these adjustments. Please have a look.

**Comment by homu-konamilk** [comment]
Hi @joethei 
Have you had a chance to look at the updates? Thanks!

**Comment by homu-konamilk** [comment]
> ["name": "Custom New File Name",](https://github.com/homu-konamilk/obsidian-custom-new-file-name/blob/0729b6bafc6115eec371beb6deacf711c324ff95/manifest.json#L3)
This should be in sentence case.

fixed

**Pull request merged**
