### PR TITLE
Add plugin: Abbrlink

### PR DESCRIPTION
**Pull request by Hoshino-Yumetsuki**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [https://github.com/Hoshino-Yumetsuki/obsidian-plugin-abbrlink](https://github.com/Hoshino-Yumetsuki/obsidian-plugin-abbrlink)

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["repo": "Hoshino-Yumetsuki/obsidian-plugin-abbrlink"](https://github.com/Hoshino-Yumetsuki/obsidian-plugin-abbrlink/blob/aa404fed389c13eb8e255a96e5daa44d3a0e3555/manifest.json#L11)
This is not a valid part of the manifest, remove it.

[# Obsidian Abbrlink](https://github.com/Hoshino-Yumetsuki/obsidian-plugin-abbrlink/blob/aa404fed389c13eb8e255a96e5daa44d3a0e3555/README.md#L1), [# Obsidian Abbrlink](https://github.com/Hoshino-Yumetsuki/obsidian-plugin-abbrlink/blob/aa404fed389c13eb8e255a96e5daa44d3a0e3555/README.zh-CN.md#L1-L2)
Naming something "Obsidian xyz" is reserved for first party products we create, please change this header.

[import * as crypto from 'crypto'](https://github.com/Hoshino-Yumetsuki/obsidian-plugin-abbrlink/blob/aa404fed389c13eb8e255a96e5daa44d3a0e3555/src/main.ts#L2)
This import is only available from a Node.js runtime, which means that this will throw errors on Mobile (that's a problem since you have `isDesktopOnly` marked as `false` in your manifest.json file.

[if (content.startsWith('---')) {](https://github.com/Hoshino-Yumetsuki/obsidian-plugin-abbrlink/blob/aa404fed389c13eb8e255a96e5daa44d3a0e3555/src/main.ts#L106-L122)
Use the `processFrontMatter` function from the Obsidian API, you will need to increase your `minAppVersion` in the manifest for that.

[containerEl.createEl('h2', { text: 'Abbrlink' })](https://github.com/Hoshino-Yumetsuki/obsidian-plugin-abbrlink/blob/aa404fed389c13eb8e255a96e5daa44d3a0e3555/src/main.ts#L195)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[containerEl.createEl('h3', { text: '基本设置' })](https://github.com/Hoshino-Yumetsuki/obsidian-plugin-abbrlink/blob/aa404fed389c13eb8e255a96e5daa44d3a0e3555/src/main.ts#L197)
There should not be a header for "General Settings"

[containerEl.createEl('h3', { text: '自动化选项' })](https://github.com/Hoshino-Yumetsuki/obsidian-plugin-abbrlink/blob/aa404fed389c13eb8e255a96e5daa44d3a0e3555/src/main.ts#L212), [Avoid "options" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

[containerEl.createEl('h3', { text: '自动化选项' })](https://github.com/Hoshino-Yumetsuki/obsidian-plugin-abbrlink/blob/aa404fed389c13eb8e255a96e5daa44d3a0e3555/src/main.ts#L212)m [containerEl.createEl('h3', { text: '高级选项' })](https://github.com/Hoshino-Yumetsuki/obsidian-plugin-abbrlink/blob/aa404fed389c13eb8e255a96e5daa44d3a0e3555/src/main.ts#L238), 
For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```

**Comment by Hoshino-Yumetsuki** [comment]
> ["repo": "Hoshino-Yumetsuki/obsidian-plugin-abbrlink"](https://github.com/Hoshino-Yumetsuki/obsidian-plugin-abbrlink/blob/aa404fed389c13eb8e255a96e5daa44d3a0e3555/manifest.json#L11) This is not a valid part of the manifest, remove it.
> 
> [# Obsidian Abbrlink](https://github.com/Hoshino-Yumetsuki/obsidian-plugin-abbrlink/blob/aa404fed389c13eb8e255a96e5daa44d3a0e3555/README.md#L1), [# Obsidian Abbrlink](https://github.com/Hoshino-Yumetsuki/obsidian-plugin-abbrlink/blob/aa404fed389c13eb8e255a96e5daa44d3a0e3555/README.zh-CN.md#L1-L2) Naming something "Obsidian xyz" is reserved for first party products we create, please change this header.
> 
> [import * as crypto from 'crypto'](https://github.com/Hoshino-Yumetsuki/obsidian-plugin-abbrlink/blob/aa404fed389c13eb8e255a96e5daa44d3a0e3555/src/main.ts#L2) This import is only available from a Node.js runtime, which means that this will throw errors on Mobile (that's a problem since you have marked as in your manifest.json file.`isDesktopOnly``false`
> 
> [if (content.startsWith('---')) {](https://github.com/Hoshino-Yumetsuki/obsidian-plugin-abbrlink/blob/aa404fed389c13eb8e255a96e5daa44d3a0e3555/src/main.ts#L106-L122) Use the function from the Obsidian API, you will need to increase your in the manifest for that.`processFrontMatter``minAppVersion`
> 
> [containerEl.createEl('h2', { text: 'Abbrlink' })](https://github.com/Hoshino-Yumetsuki/obsidian-plugin-abbrlink/blob/aa404fed389c13eb8e255a96e5daa44d3a0e3555/src/main.ts#L195) [Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)
> 
> [containerEl.createEl('h3', { text: '基本设置' })](https://github.com/Hoshino-Yumetsuki/obsidian-plugin-abbrlink/blob/aa404fed389c13eb8e255a96e5daa44d3a0e3555/src/main.ts#L197) There should not be a header for "General Settings"
> 
> [containerEl.createEl('h3', { text: '自动化选项' })](https://github.com/Hoshino-Yumetsuki/obsidian-plugin-abbrlink/blob/aa404fed389c13eb8e255a96e5daa44d3a0e3555/src/main.ts#L212), [Avoid "options" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)
> 
> [containerEl.createEl('h3', { text: '自动化选项' })](https://github.com/Hoshino-Yumetsuki/obsidian-plugin-abbrlink/blob/aa404fed389c13eb8e255a96e5daa44d3a0e3555/src/main.ts#L212)m [containerEl.createEl('h3', { text: '高级选项' })](https://github.com/Hoshino-Yumetsuki/obsidian-plugin-abbrlink/blob/aa404fed389c13eb8e255a96e5daa44d3a0e3555/src/main.ts#L238), For section headings in settings use:
> 
> ```ts
> new Setting(containerEl).setName('name here').setHeading();
> ```

Thanks for the feedback, I've fixed the above issue in the new changes.

- Regarding the encryption feature, the code has been updated to use the browser's native Web Crypto API instead of the Node.js crypto module, which ensures that it works properly on mobile devices.
- Regarding frontmatter, I have now changed to using the `processFrontMatter` method provided by the Obsidian API.
- The `setHeading()` method was used to create a section header.
- Remove the invalid "repo" field from the manifest.json.
- Modify the titles in `README.md` and `README.zh-CN.md` to avoid using the "Obsidian" prefix.

**Comment by joethei** [comment]
["minAppVersion": "0.15.0",](https://github.com/Hoshino-Yumetsuki/obsidian-plugin-abbrlink/blob/843168ed09ceefcf790c942a960bb169718b5b7e/manifest.json#L5)
You are using newer API's increase this to at least 1.1.0

**Comment by Hoshino-Yumetsuki** [comment]
> ["minAppVersion": "0.15.0",](https://github.com/Hoshino-Yumetsuki/obsidian-plugin-abbrlink/blob/843168ed09ceefcf790c942a960bb169718b5b7e/manifest.json#L5) You are using newer API's increase this to at least 1.1.0

Ok, I've made the change.

**Pull request merged**
