### PR TITLE
Add Daily Journal plugin

### PR DESCRIPTION
**Pull request by palenshus**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/palenshus/obsidian-plugin-daily-journal

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[return 'On This Day';](https://github.com/palenshus/obsidian-plugin-daily-journal/blob/a6674bd0c1e95fcd8213675e2a62d46960f98c65/src/OnThisDayView.ts#L39)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[containerEl.createEl('h2', { text: "Settings for 'Daily Journal' plugin." });](https://github.com/palenshus/obsidian-plugin-daily-journal/blob/a6674bd0c1e95fcd8213675e2a62d46960f98c65/src/SettingTab.ts#L18)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)
[Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

Why is your plugin marked as desktop only?
I don't see a reason for it.

**Comment by palenshus** [comment]
> Why is your plugin marked as desktop only? I don't see a reason for it.

I figured the UI would be too busy on a mobile app with that sidebar showing, though admittedly I haven't used the mobile app before so perhaps it's handled more gracefully than I'm imagining. That said, the new entry functionality would still be useful on mobile, so I'll remove that restriction...

**Comment by palenshus** [comment]
Addressed PR comments with 0.1.1 release

**Comment by palenshus** [comment]
@joethei, ping, thanks!

**Comment by palenshus** [comment]
Hi @liamcain, anything I can do to help get this reviewed?

**Comment by liamcain** [comment]
- [this.app.workspace.getActiveViewOfType(MarkdownView)?.editor](https://github.com/palenshus/obsidian-plugin-daily-journal/blob/565d8d8dd5b14f63bda5844b849732385e8354ea/src/main.ts#L60) you should use [`activeEditor`](https://github.com/obsidianmd/obsidian-api/blob/38dd22168d2925086371bfc59e36fd9121527a39/obsidian.d.ts#L4009) instead.
- [registerDomEvent](https://github.com/palenshus/obsidian-plugin-daily-journal/blob/565d8d8dd5b14f63bda5844b849732385e8354ea/src/main.ts#L58) the recommended way of doing this would be to add a codemirror editor extension instead of trying to manage the DOM state yourself. https://docs.obsidian.md/Plugins/Editor/Editor+extensions
- [editor](https://github.com/palenshus/obsidian-plugin-daily-journal/blob/565d8d8dd5b14f63bda5844b849732385e8354ea/src/main.ts#L61) you should also ensure that editor.hasFocus() since there can be an active editor but something else has focus (like a modal)

**Comment by palenshus** [comment]
Geez I've been reading the documentation for state fields for the past half hour and this is looking really complicated. Would it work for me just to get rid of the Enter key monitoring and replace it with a palette command?

**Comment by liamcain** [comment]
- [this.settings](https://github.com/palenshus/obsidian-plugin-daily-journal/blob/565d8d8dd5b14f63bda5844b849732385e8354ea/src/main.ts#L51) I suggest passing the plugin instance to the View instead of the settings instance. If you reload the settings data, the view will have a stale instance of the settings.
- [console](https://github.com/palenshus/obsidian-plugin-daily-journal/blob/565d8d8dd5b14f63bda5844b849732385e8354ea/src/OnThisDayView.ts#L33) remove this console.log
- [window](https://github.com/palenshus/obsidian-plugin-daily-journal/blob/565d8d8dd5b14f63bda5844b849732385e8354ea/src/OnThisDayView.ts#L30) you should use `this.rootEl.win` instead of `window` since "window" actually references the main window and your view might appear in a popout window.
- [setTimeout](https://github.com/palenshus/obsidian-plugin-daily-journal/blob/565d8d8dd5b14f63bda5844b849732385e8354ea/src/OnThisDayView.ts#L30) you should also register this timeout so that its cleared when the plugin is unloaded

**Comment by ericaxu** [comment]
To keep things tidy, we're going to close issues that we don't hear back after a month of inactivity.

Feel free to tell us to re-open it when you're ready to reply and we'll reopen the issue right away. Thanks for your understanding!

**Pull request closed without merging**
