### PR TITLE
Add poker to community plugins

### PR DESCRIPTION
**Pull request by mAAdhaTTah**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/mAAdhaTTah/obsidian-poker

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
License has been added

**Comment by joethei** [comment]
["description": "Renders poker hands in Obsidian.",](https://github.com/mAAdhaTTah/obsidian-poker/blob/94c5075b67eab80fb50c31d9037e031526487bed/manifest.json#L6)
We have recently published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This is a plugin for Obsidian" in your description.

**Comment by mAAdhaTTah** [comment]
@joethei The description you copied doesn't say that anymore. Should it just be "renders poker hands"?

**Comment by mAAdhaTTah** [comment]
@joethei Updated the description

**Comment by joethei** [comment]
The description in the `manifest.json` also needs to be updated.

**Comment by mAAdhaTTah** [comment]
@joethei Fixed & published a new version.

**Pull request merged**
