### PR TITLE
Add plugin: whichkey

### PR DESCRIPTION
**Pull request by AlexSpradling**
# I am submitting a new Community Plugin

## Repo URL

https://github.com/AlexSpradling/obsidian-which-key.git
Link to my plugin:

## Release Checklist
- [x ] I have tested the plugin on
  - [x ]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x ] `main.js`
  - [ x] `manifest.json`
  - [ x] `styles.css` _(optional)_
- [x ] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x ] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x ] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x ] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x ] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x ] I have added a license in the LICENSE file.
- [x ] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Review by Malia00019 — APPROVED** [review]

**Comment by joethei** [comment]
Please add the actual code into the repository, I only see it in the releases.

**Comment by AlexSpradling** [comment]
Hi, 

`main.js` is pushed. I removed it from the repo per your bots instructions noted above.

**Comment by AlexSpradling** [comment]
> [module.exports = class WhichKeyPlugin extends Plugin {](https://github.com/AlexSpradling/obsidian-which-key/blob/50746d79e0f20483257348fec860501d7f91eadb/main.js#L91-L114) This code is duplicated below,
> 
> [name: 'Open WhichKey Modal',](https://github.com/AlexSpradling/obsidian-which-key/blob/50746d79e0f20483257348fec860501d7f91eadb/main.js#L124) Remove "Modal"
> 
> [const keyBindingsPath = path.join(this.app.vault.adapter.basePath, 'keybindings.json');](https://github.com/AlexSpradling/obsidian-which-key/blob/50746d79e0f20483257348fec860501d7f91eadb/main.js#L134-L135), [const keyBindingsPath = path.join(this.app.vault.adapter.basePath, 'keybindings.json');](https://github.com/AlexSpradling/obsidian-which-key/blob/50746d79e0f20483257348fec860501d7f91eadb/main.js#L145-L146) This should be done using the adapter, which removes the reliance on the `fs` and `path` packages and would make this plugin mobile compatible.
> 
> [keyBindingsPath: 'keybindings.json',](https://github.com/AlexSpradling/obsidian-which-key/blob/50746d79e0f20483257348fec860501d7f91eadb/main.js#L157) This setting value is never used.
> 
> [containerEl.createEl('h1', { text: 'Edit Keybindings' });](https://github.com/AlexSpradling/obsidian-which-key/blob/50746d79e0f20483257348fec860501d7f91eadb/main.js#L240) There should not be a top level heading in settings.
> 
> [containerEl.createEl('h1', { text: 'Commands' });](https://github.com/AlexSpradling/obsidian-which-key/blob/50746d79e0f20483257348fec860501d7f91eadb/main.js#L316), For section headings in settings use:
> 
> ```ts
> new Setting(containerEl).setName('name here').setHeading();
> ```
> 
> [containerEl.createEl('h1', { text: 'Edit Keybindings' });](https://github.com/AlexSpradling/obsidian-which-key/blob/50746d79e0f20483257348fec860501d7f91eadb/main.js#L240),[.setName('Keybindings Path')](https://github.com/AlexSpradling/obsidian-which-key/blob/50746d79e0f20483257348fec860501d7f91eadb/main.js#L248) [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI), [.setName('Save Keybindings')](https://github.com/AlexSpradling/obsidian-which-key/blob/50746d79e0f20483257348fec860501d7f91eadb/main.js#L299)

Thank you for your review! Changes pushed.

**Comment by AlexSpradling** [comment]
> > [module.exports = class WhichKeyPlugin extends Plugin {](https://github.com/AlexSpradling/obsidian-which-key/blob/50746d79e0f20483257348fec860501d7f91eadb/main.js#L91-L114) This code is duplicated below,
> > [name: 'Open WhichKey Modal',](https://github.com/AlexSpradling/obsidian-which-key/blob/50746d79e0f20483257348fec860501d7f91eadb/main.js#L124) Remove "Modal"
> > [const keyBindingsPath = path.join(this.app.vault.adapter.basePath, 'keybindings.json');](https://github.com/AlexSpradling/obsidian-which-key/blob/50746d79e0f20483257348fec860501d7f91eadb/main.js#L134-L135), [const keyBindingsPath = path.join(this.app.vault.adapter.basePath, 'keybindings.json');](https://github.com/AlexSpradling/obsidian-which-key/blob/50746d79e0f20483257348fec860501d7f91eadb/main.js#L145-L146) This should be done using the adapter, which removes the reliance on the `fs` and `path` packages and would make this plugin mobile compatible.
> > [keyBindingsPath: 'keybindings.json',](https://github.com/AlexSpradling/obsidian-which-key/blob/50746d79e0f20483257348fec860501d7f91eadb/main.js#L157) This setting value is never used.
> > [containerEl.createEl('h1', { text: 'Edit Keybindings' });](https://github.com/AlexSpradling/obsidian-which-key/blob/50746d79e0f20483257348fec860501d7f91eadb/main.js#L240) There should not be a top level heading in settings.
> > [containerEl.createEl('h1', { text: 'Commands' });](https://github.com/AlexSpradling/obsidian-which-key/blob/50746d79e0f20483257348fec860501d7f91eadb/main.js#L316), For section headings in settings use:
> > ```ts
> > new Setting(containerEl).setName('name here').setHeading();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [containerEl.createEl('h1', { text: 'Edit Keybindings' });](https://github.com/AlexSpradling/obsidian-which-key/blob/50746d79e0f20483257348fec860501d7f91eadb/main.js#L240),[.setName('Keybindings Path')](https://github.com/AlexSpradling/obsidian-which-key/blob/50746d79e0f20483257348fec860501d7f91eadb/main.js#L248) [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI), [.setName('Save Keybindings')](https://github.com/AlexSpradling/obsidian-which-key/blob/50746d79e0f20483257348fec860501d7f91eadb/main.js#L299)
> 
> Thank you for your review! Changes pushed.

Please let me know if there's anything else I can modify.

**Comment by joethei** [comment]
Where is the code now?
It seems that the repo got deleted.
If you want to continue with your submission, please create a new PR.

**Pull request closed without merging**
