### PR TITLE
Add plugin: Media Notes

### PR DESCRIPTION
**Pull request by jemstelos**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/jemstelos/obsidian-media-notes

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by jemstelos** [comment]
Hey there! The code lines called out here are setting styles that are based off of user settings, and must therefore be controlled via Javascript.

e.g the user is able to go to the settings to select the color of the background and media bar, and the height or width of the player.

Please let me know if this meets the requirements for this rule to be skipped. Thank you
/skip

**Comment by jemstelos** [comment]
hey @joethei! please let me know if there's any action or clarification I can make on this. I provided the justification and /skip to the automated review, but not sure if that skipped moving to the human review process. Thank you!

**Comment by joethei** [comment]
To make the manual review process and future plugin maintenance more efficient, we recommend that you move all source code files into a `src` directory.

[.setName("Default Split View")](https://github.com/jemstelos/obsidian-media-notes/blob/35ab631fb4e5980e7d946b4857eee7d253490dea/main.tsx#L466)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by jemstelos** [comment]
Thank you, I'll be sure to do so for future plugin development. I moved all code files into a src directory, addressed the comment on using sentence case in the UI, and published a new release 1.0.1.

**Pull request merged**
