### PR TITLE
Add Smart Mentions Plugin

### PR DESCRIPTION
**Pull request by Tobey-Jinc**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Tobey-Jinc/obsidian-smart-mentions

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
You can remove `obsidian` from the plugin ID, its unnecessary.

Why is your plugin marked as desktop only?
I see you used to use the `fs` package, but I don't see it being used anywhere.

[LinkedMentions](https://github.com/Tobey-Jinc/obsidian-smart-mentions/blob/fb1173dbe92b4a98131048ec1802e9a0c1765fca/main.ts#L11) `LinkedMention` would be a better name, since this only one mention.

**Comment by liamcain** [comment]
- [if (view != null && view.file.extension === "md")](https://github.com/Tobey-Jinc/obsidian-smart-mentions/blob/fb1173dbe92b4a98131048ec1802e9a0c1765fca/main.ts#L247-L248) this is just a bit of feedback on the code style. This function could be a lot more readable if you used [early returns](https://dev.to/yvonnickfrin/devtips-use-early-returns-to-avoid-nested-conditions-4i51) instead of so many nested ifs.
- [folderNote](https://github.com/Tobey-Jinc/obsidian-smart-mentions/blob/fb1173dbe92b4a98131048ec1802e9a0c1765fca/main.ts#L7) why is this defined at the plugin root? I recommend returning the folderNode from `findFolderNote`. Even if the function is recursive, you can still have it return the string.
- [folders.push("k1s128865adg⇎f12sdk42fjgk↻gas4dfkjg234sdfquytwe8r↨")](https://github.com/Tobey-Jinc/obsidian-smart-mentions/blob/fb1173dbe92b4a98131048ec1802e9a0c1765fca/main.ts#L165) what is this hack for?
- [this.app.workspace.on('file-open'](https://github.com/Tobey-Jinc/obsidian-smart-mentions/blob/fb1173dbe92b4a98131048ec1802e9a0c1765fca/main.ts#L417) you probably also want to listen for [`metadataCache.on('resolve')`](https://github.com/obsidianmd/obsidian-api/blob/902badd38ba907689f0917d7b193f7e33d1284fe/obsidian.d.ts#L2337)
- [extra_mention](https://github.com/Tobey-Jinc/obsidian-smart-mentions/blob/fb1173dbe92b4a98131048ec1802e9a0c1765fca/main.ts#L395) Instead of creating `obsidian://` links, I suggest you just create a span with a click handler that calls `(evt: MouseEvent) => getLeaf(Keymap.isModEvent(evt)).openLinkText(linkToFile)`. It will be more functional and allow users to open the file in a new tab, new split, or new window based on the modifiers that they click. It will also be a lot simpler since you don't need to generate or sanitize the links manually.

**Comment by joethei** [comment]
Hi @Tobey-Jinc ,
I just wanted to confirm that you've seen Liams comment with the requested changes.
Do you still intend on submitting this plugin?

**Comment by ericaxu** [comment]
Hi there, to keep things tidy, we're going to temporarily close plugin PRs after a month of inactivity.

Feel free to tell us to re-open it when you're ready to continue. Thanks for your understanding!

**Pull request closed without merging**
