### PR TITLE
adding mermaid-themes plugin

### PR DESCRIPTION
**Pull request by jvsteiner**
# I am submitting a new Community Plugin

## Repo URL

[Link to my plugin:](https://github.com/jvsteiner/mermaid-themes)

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "This is an Obsidian plugin that makes it easy to apply custom mermaid.js themes and apply other tweaks.](https://github.com/jvsteiner/mermaid-themes/blob/fb424511f23ed130af60492c526b6cb815ce25c7/manifest.json#L6)
We have recently published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This is a plugin for Obsidian" in your description.

**Comment by jvsteiner** [comment]
fixed description

**Comment by marcusolsson** [comment]
[containerEl.createEl("h2", { text: "Settings for Mermaid Themes" });](https://github.com/jvsteiner/mermaid-themes/blob/07cfcb6eb73367f55836cd50901fc5c07856f9f2/main.ts#L129)
https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#UI+text

nit: I can't find any instructions in the README (or in the plugin) on how to actually create a Mermaid theme. Easy enough to Google, but still.

**Comment by jvsteiner** [comment]
You're not wrong, but my thought was that this plugin doesn't matter to anyone who doesn't already need to make a mermaid theme.  I'm not sure I want take responsibility for documenting mermaid...

**Comment by marcusolsson** [comment]
Could you add a link to https://mermaid.js.org/config/theming.html?

**Comment by jvsteiner** [comment]
done, and released

**Pull request merged**
