### PR TITLE
Add plugin: Vim IM Control

### PR DESCRIPTION
**Pull request by hideakitai**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/hideakitai/obsidian-vim-im-control

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "Obsidian plugin to switch Input Method when `InsertLeave` and `InsertEnter`. Supports macOS, Windows, and Linux.",](https://github.com/hideakitai/obsidian-vim-im-control/blob/1d89b1dfa8d2b528d678f04956266c37b6d03330/manifest.json#L6)
Avoid including sentences like "This is a plugin for Obsidian that does ..." in your description.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[this.app.workspace.on("file-open", this.registerWorkspaceEvent);](https://github.com/hideakitai/obsidian-vim-im-control/blob/1d89b1dfa8d2b528d678f04956266c37b6d03330/main.ts#L67)
Events need to be registered, so they can be properly unloaded when the plugin is disabled. <https://docs.obsidian.md/Plugins/Events>

[containerEl.createEl("h1", { text: "Vim IM Control Settings" });](https://github.com/hideakitai/obsidian-vim-im-control/blob/1d89b1dfa8d2b528d678f04956266c37b6d03330/main.ts#L311)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[.setName("Async Switch")](https://github.com/hideakitai/obsidian-vim-im-control/blob/1d89b1dfa8d2b528d678f04956266c37b6d03330/main.ts#L347)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[containerEl.createEl("h3", { text: "Async Switch" });](https://github.com/hideakitai/obsidian-vim-im-control/blob/1d89b1dfa8d2b528d678f04956266c37b6d03330/main.ts#L345), [containerEl.createEl("h3", { text: "Status Bar Message" });](https://github.com/hideakitai/obsidian-vim-im-control/blob/1d89b1dfa8d2b528d678f04956266c37b6d03330/main.ts#L358)
Remove these headings, just add a divider to seperate from the OS settings.

**Comment by hideakitai** [comment]
@joethei Thank you for your review. I've fixed and released 0.1.1. Please review this PR again.

**Comment by hideakitai** [comment]
Is there any other blocker for this pull request?  @joethei

**Comment by liamcain** [comment]
- [vim-mode-change](https://github.com/hideakitai/obsidian-vim-im-control/blob/2210ec1f23f8e0db456fe4279af933a79b0d949e/main.ts#L123) file-open gets called when you switch to a new file, but that might not be when the editor was created. If you have 2 tabs open and switch between them, the file-open event will continue to fire each time. This means you'll end up with duplicate event handlers here. You will likely need to figure out a different way to dedupe this. For example, you could keep a WeakSet of editor instances that you've seen so far and only register the event if you haven't seen the editor yet.
- [getActiveMarkdownView](https://github.com/hideakitai/obsidian-vim-im-control/blob/2210ec1f23f8e0db456fe4279af933a79b0d949e/main.ts#L131) small note: this won't work for Canvas, which creates editor instances when editing embedded canvas cards.

**Comment by hideakitai** [comment]
@liamcain Thank you for your review. 

> [vim-mode-change](https://github.com/hideakitai/obsidian-vim-im-control/blob/2210ec1f23f8e0db456fe4279af933a79b0d949e/main.ts#L123) file-open gets called when you switch to a new file, but that might not be when the editor was created. If you have 2 tabs open and switch between them, the file-open event will continue to fire each time. This means you'll end up with duplicate event handlers here. You will likely need to figure out a different way to dedupe this. For example, you could keep a WeakSet of editor instances that you've seen so far and only register the event if you haven't seen the editor yet.

I fixed it as shown in [this p-r](https://github.com/hideakitai/obsidian-vim-im-control/pull/1/files). Please check it out.

> [getActiveMarkdownView](https://github.com/hideakitai/obsidian-vim-im-control/blob/2210ec1f23f8e0db456fe4279af933a79b0d949e/main.ts#L131) small note: this won't work for Canvas, which creates editor instances when editing embedded canvas cards.

I got it, thank you!

**Comment by liamcain** [comment]
> new Set<CodeMirror.Editor>();

By using a set, you are creating a memory leak where editors will never get released from memory even when they are destroyed. This is why I recommended a WeakSet <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet> which will not hold those references in memory.

**Comment by hideakitai** [comment]
@liamcain I thought I had set it to WeakSet, but I was completely wrong... Thanks for pointing that out! Fixed by [0b99fec](https://github.com/hideakitai/obsidian-vim-im-control/pull/3/commits/0b99fec4264e969b5e9812cf11f7f102f7c5df8b) and released v0.1.3

**Pull request merged**
