### PR TITLE
Add community plugin with Marp Slide

### PR DESCRIPTION
**Pull request by samuele-cozzi**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/samuele-cozzi/obsidian-marp-slides

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by samuele-cozzi** [comment]
# I am submitting a new Community Plugin

## Repo URL


Link to my plugin:

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

**Comment by joethei** [comment]
What sets your plugin appart from the other Marp plugin(https://obsidian.md/plugins?search=marp) ?: 

[ribbonIconEl.addClass('my-plugin-ribbon-class');](https://github.com/samuele-cozzi/obsidian-marp-slides/blob/312b80d83e44adedf18a7015cc28ebc18c83db4f/src/main.ts#L27)
Remove this.

[id: 'marp-slides-preview',](https://github.com/samuele-cozzi/obsidian-marp-slides/blob/312b80d83e44adedf18a7015cc28ebc18c83db4f/src/main.ts#L30)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

[console.log('Chrome Path: ' + value);](https://github.com/samuele-cozzi/obsidian-marp-slides/blob/312b80d83e44adedf18a7015cc28ebc18c83db4f/src/main.ts#L175)
Don't log setting changes.

**Comment by samuele-cozzi** [comment]
Ops! I'm sorry, the actual plugin is quite new, and I hadn't seen it yet :( So I have tried to integrate some features (relative path images, Linux support) into the existing plugin. But I have seen that the actual plugin has a different approach for export using [cli](https://github.com/marp-team/marp-cli) (npx commands), while this plugin uses the [api](https://github.com/marp-team/marp-cli#api-experimental).

The other comments are fixed

**Comment by yhatt** [comment]
What is the status of this review request?

I'm the author of Marp. This plugin looks like better than existing one: No need to install external tools for exporting slide, e.g. Node.js.

**Comment by samuele-cozzi** [comment]
I fixed what was required.

**Comment by samuele-cozzi** [comment]
I fixed the conflicts in community-plugins.json

**Comment by liamcain** [comment]
Really sorry for such a long wait with reviewing this plugin!! We fell really behind on reviews the last month or so, that's my fault.

Excited to have this in the community plugin list. Thanks for your patience 🙏

**Pull request merged**
