### PR TITLE
Add plugin: syncread-assistant

### PR DESCRIPTION
**Pull request by flyer1b**
update community-plugins.json

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:https://github.com/flyer1b/LightRead-master

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [ ] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by mmmykhailo** [comment]
Nobody understand what your plugin is used for because you wrote everything in your native language, lol

**Comment by joethei** [comment]
Please link to the LightReading app in your readme, I can't find anything of that name with a quick web search.

["description": "a plugin for lightread to sync articles to obsidian",](https://github.com/flyer1b/LightRead-master/blob/a9711c43f144b7e391fc89c6b684e7e038d2fb9f/manifest.json#L6)
Avoid including sentences like "This is a plugin for Obsidian that does ..." in your description.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

["fundingUrl": "http//www.relaxone.cn",](https://github.com/flyer1b/LightRead-master/blob/a9711c43f144b7e391fc89c6b684e7e038d2fb9f/manifest.json#L9)
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link omit this.

[// Remember to rename these classes and interfaces!](https://github.com/flyer1b/LightRead-master/blob/a9711c43f144b7e391fc89c6b684e7e038d2fb9f/main.ts#L4)
Please actually do this.

[// Perform additional things with the ribbon](https://github.com/flyer1b/LightRead-master/blob/a9711c43f144b7e391fc89c6b684e7e038d2fb9f/main.ts#L37-L96)
Remove all this sample code.

[class SampleModal extends Modal {](https://github.com/flyer1b/LightRead-master/blob/a9711c43f144b7e391fc89c6b684e7e038d2fb9f/main.ts#L112-L126)
Also remove this sample code.

[const res = await fetch('http://129.226.195.147:5050/login/', {](https://github.com/flyer1b/LightRead-master/blob/a9711c43f144b7e391fc89c6b684e7e038d2fb9f/main.ts#L171)
Use the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

[function sanitizeFilename(filename: string): string {](https://github.com/flyer1b/LightRead-master/blob/a9711c43f144b7e391fc89c6b684e7e038d2fb9f/main.ts#L294-L296)
Use the `normalzePath` function instead.

**Comment by flyer1b** [comment]
all change,and request review again.

**Comment by liamcain** [comment]
- [var](https://github.com/flyer1b/LightRead-master/blob/ed90231d4dd52f2cc23835a794265083ac1d0724/main.ts#L171) I recommend you change all instances of `var` to either `const` or `let`. `var` has function-level scope, so it can easily lead to bugs if you're not careful.
- [var](https://github.com/flyer1b/LightRead-master/blob/ed90231d4dd52f2cc23835a794265083ac1d0724/main.ts#L181) down here too
- [while(true)](https://github.com/flyer1b/LightRead-master/blob/ed90231d4dd52f2cc23835a794265083ac1d0724/main.ts#L204) you are using a do-while loop but since the condition is `true` there's no reason to use a do-while loop over a regular `while` loop

**Comment by flyer1b** [comment]
> * [var](https://github.com/flyer1b/LightRead-master/blob/ed90231d4dd52f2cc23835a794265083ac1d0724/main.ts#L171) I recommend you change all instances of `var` to either `const` or `let`. `var` has function-level scope, so it can easily lead to bugs if you're not careful.
> * [var](https://github.com/flyer1b/LightRead-master/blob/ed90231d4dd52f2cc23835a794265083ac1d0724/main.ts#L181) down here too
> * [while(true)](https://github.com/flyer1b/LightRead-master/blob/ed90231d4dd52f2cc23835a794265083ac1d0724/main.ts#L204) you are using a do-while loop but since the condition is `true` there's no reason to use a do-while loop over a regular `while` loop

image
I was used normalizePath function ,but it also throw error:
"File name cannot contain any of the following characters:\/"

**Comment by flyer1b** [comment]
@joethei @liamcain How to update plugins? What are the steps？

**Pull request merged**
