### PR TITLE
Add plugin: Image Magician

### PR DESCRIPTION
**Pull request by luxmargos**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/luxmargos/obsidian-image-magician-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by luxmargos** [comment]
I have now updated to version 0.1.4

/skip

I have fixed most of the issues based on the guidance from @ObsidianReviewBot. However, a few cases have been enhanced or left as they are. Please see the following explanations.

* This class is only available on desktop, which means that this will throw errors on mobile (that's a problem since you have isDesktopOnly marked as false in your manifest.json file.
  * Explanation: I updated the code case by case for whether it's on desktop or mobile, so there will be no error.

* You should avoid assigning styles via JavaScript or in HTML and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets.
  * Explanation: That is an intended code to position an element dynamically.

**Comment by luxmargos** [comment]
I have now updated to version 0.1.5, including /skip within my code lines.

**Comment by joethei** [comment]
[process.env.NODE_ENV === "development"](https://github.com/luxmargos/obsidian-image-magician-plugin/blob/56cfcba4b990a0014043697693bb5583b5599704/src/main.ts#L126)
`process` is only available on desktop, this will crash your plugin on mobile.

[id: "imgk-plugin-export-image",](https://github.com/luxmargos/obsidian-image-magician-plugin/blob/56cfcba4b990a0014043697693bb5583b5599704/src/main.ts#L203), [id: "imgk-plugin-process-auto-export",](https://github.com/luxmargos/obsidian-image-magician-plugin/blob/56cfcba4b990a0014043697693bb5583b5599704/src/main.ts#L235), [id: "imgk-plugin-process-auto-export-forced",](https://github.com/luxmargos/obsidian-image-magician-plugin/blob/56cfcba4b990a0014043697693bb5583b5599704/src/main.ts#L243)
Don't prefix the command id with the plugin id, that will happen internally automatically.

[findValutFile](https://github.com/luxmargos/obsidian-image-magician-plugin/blob/56cfcba4b990a0014043697693bb5583b5599704/src/vault_util.ts#L28)
Typo.

[let result = files.find((f: TFile) => {](https://github.com/luxmargos/obsidian-image-magician-plugin/blob/56cfcba4b990a0014043697693bb5583b5599704/src/vault_util.ts#L35-L38)
[Avoid iterating all files to find a file by its path]https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+iterating+all+files+to+find+a+file+by+its+path.

[// I think this is the link search behaviour of obsidian](https://github.com/luxmargos/obsidian-image-magician-plugin/blob/56cfcba4b990a0014043697693bb5583b5599704/src/vault_util.ts#L39-L45)
To find a file if you are only given a linkpath, use this function: <https://docs.obsidian.md/Reference/TypeScript+API/MetadataCache/getFirstLinkpathDest>

**Comment by luxmargos** [comment]
I have now updated version 0.1.6, with fixes are applied.

**Pull request merged**
