### PR TITLE
Add Media Sync plugin

### PR DESCRIPTION
**Pull request by fnya**
Add Media Sync for Obsidian Plugin.

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/fnya/media-sync

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by fnya** [comment]
Fix below issue.
> Please don't use the word Obsidian in your plugin name since it's redundant and adds clutter to the plugin list.

**Comment by joethei** [comment]
Fill your readme, I have no idea how to use it, or what it does.

[MyPluginSettings](https://github.com/fnya/media-sync/blob/13520fce3a9a1a6c02c69f17f991b3e3f388c717/main.ts#L4)
[MyPlugin](https://github.com/fnya/media-sync/blob/13520fce3a9a1a6c02c69f17f991b3e3f388c717/main.ts#L12)
Rename these

["Media Sync for Obsidian"](https://github.com/fnya/media-sync/blob/13520fce3a9a1a6c02c69f17f991b3e3f388c717/main.ts#L24)
Remove the "for Obsidian", that should be obvious.

[async loadSettings() {](https://github.com/fnya/media-sync/blob/13520fce3a9a1a6c02c69f17f991b3e3f388c717/main.ts#L31-L37)
Your plugin does not have any settings, remove this code.

[const files = app.vault.getFiles().filter((file) => file.extension === "md");](https://github.com/fnya/media-sync/blob/13520fce3a9a1a6c02c69f17f991b3e3f388c717/src/modules.ts#L36)
Use the `getMarkdownFiles` function from the API.

[const fileSystemAdapter = app.vault.adapter as FileSystemAdapter;](https://github.com/fnya/media-sync/blob/13520fce3a9a1a6c02c69f17f991b3e3f388c717/src/modules.ts#L38)
The FileSystemAdapter is only available on desktop, you should [prefer the Vault API over the Adapter API](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#prefer-the-vault-api-over-the-adapter-api)

**Comment by fnya** [comment]
@joethei 
Thank you for your review.
I have corrected the information you have indicated and would be happy to review it again.
https://github.com/fnya/media-sync/releases/tag/0.0.3

**Comment by fnya** [comment]
@joethei 
Thank you for your confirmation and merge!

**Pull request merged**
