### PR TITLE
feat: add Telegram Sync plugin

### PR DESCRIPTION
**Pull request by soberhacker**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:  [obsidian-telegram-sync](https://github.com/soberhacker/obsidian-telegram-sync)

## Release Checklist
- [ x ] I have tested the plugin on
  - [ x ]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [ x ] `main.js`
  - [ x ] `manifest.json`
  - [ x ] `styles.css` _(optional)_
- [ x ] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [ x ] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [ x ] My README.md describes the plugin's purpose and provides clear usage instructions.
- [ x ] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [ x ] I have added a license in the LICENSE file.
- [ x ] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["author": "soberHacker🍃🧘💻",](https://github.com/soberhacker/obsidian-telegram-sync/blob/92749e5df2bd5744cdff4475f803a9521e15eb4a/manifest.json#L7)
Please don't use emoji here.

[export function formatDateTime(date: Date, format: string): string {](https://github.com/soberhacker/obsidian-telegram-sync/blob/92749e5df2bd5744cdff4475f803a9521e15eb4a/src/utils/dateUtils.ts#L1)
Use the moment library instead:
```ts
import {moment} from 'obsidian';
moment(date).format(format);
```
You can learn more here: <https://momentjs.com/docs/#/displaying/format/>

[await this.app.vault.adapter.mkdir(specificFolder);](https://github.com/soberhacker/obsidian-telegram-sync/blob/92749e5df2bd5744cdff4475f803a9521e15eb4a/src/telegram/messageHandlers.ts#L75)
Use `this.app.vault.createFolder(specificFolder)` instead.

[await this.app.vault.adapter.writeBinary(filePath, fileByteArray);](https://github.com/soberhacker/obsidian-telegram-sync/blob/92749e5df2bd5744cdff4475f803a9521e15eb4a/src/telegram/messageHandlers.ts#LL98C75-L98C75)
Use `this.app.vault.modifyBinary()` instead.

**Comment by soberhacker** [comment]
Hi @joethei,
Thank you for your feedback. I fixed all that you recommended to fix.

**Comment by marcusolsson** [comment]
[let telegramMdFile = this.app.vault.getAbstractFileByPath(telegramMdPath) as TFile;](https://github.com/soberhacker/obsidian-telegram-sync/blob/ab18ca3d30963b8f8ef0aaaa3d7af8f521eccaeb/src/main.ts#L88) and [const templateFile = this.app.vault.getAbstractFileByPath(templatePath) as TFile;](https://github.com/soberhacker/obsidian-telegram-sync/blob/ab18ca3d30963b8f8ef0aaaa3d7af8f521eccaeb/src/main.ts#L63)
[Use normalizePath() to clean up user-defined paths](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+%60normalizePath()%60+to+clean+up+user-defined+paths)

[.setName("New Notes Location")](https://github.com/soberhacker/obsidian-telegram-sync/blob/ab18ca3d30963b8f8ef0aaaa3d7af8f521eccaeb/src/settings/Settings.ts#L97)
Obsidian uses [Sentence case](https://en.wiktionary.org/wiki/sentence_case) for the user interface, i.e. "New notes location".

[versions.json](https://github.com/soberhacker/obsidian-telegram-sync/blob/ab18ca3d30963b8f8ef0aaaa3d7af8f521eccaeb/versions.json#L1-L9)
nit: You don't need to create an entry for every Obsidian version. You only need to add an entry when a different Obsidian version would break your plugin. In your case, all Obsidian versions use the same plugin version, so you only need to keep the first entry.

**Comment by soberhacker** [comment]
All done in new release
https://github.com/soberhacker/obsidian-telegram-sync/releases/tag/1.5.0

Thank you @marcusolsson for taking the time to review my Pull Request

**Comment by soberhacker** [comment]
@liamcain 
Done
https://github.com/soberhacker/obsidian-telegram-sync/releases/tag/1.6.1

Maybe this time I'll be successful 😂😂😂

**Pull request merged**
