### PR TITLE
Added Just Share Please

### PR DESCRIPTION
**Pull request by Ellpeck**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Ellpeck/ObsidianJustSharePlease

Docs/website: https://jsp.ellpeck.de

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions. *Kind of? I'd prefer to have them only on the website due to maintainability, but if it's a proper requirement to have them in the README also, I can definitely include them.*
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`. *(N/A)*

### CODE REVIEW

**Comment by joethei** [comment]
[this.containerEl.createEl("h2", {text: "Just Share Please Settings"});](https://github.com/Ellpeck/ObsidianJustSharePlease/blob/0c6d1f286b907c65c13fe0b33efca4a2e5e7ede7/src/settings-tab.ts#L16)
[Don't include a header with the plugin name in settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[.setName("Strip Frontmatter")](https://github.com/Ellpeck/ObsidianJustSharePlease/blob/0c6d1f286b907c65c13fe0b33efca4a2e5e7ede7/src/settings-tab.ts#L34)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[let file = this.plugin.app.vault.getAbstractFileByPath(shared.path) as TFile;](https://github.com/Ellpeck/ObsidianJustSharePlease/blob/0c6d1f286b907c65c13fe0b33efca4a2e5e7ede7/src/view.ts#L20)
Check if that file is a `TFile`, don't cast blindly.

[$content = file_get_contents(get_markdown_path($query["id"]));](https://github.com/Ellpeck/ObsidianJustSharePlease/blob/0c6d1f286b907c65c13fe0b33efca4a2e5e7ede7/server/public/share.php#L23)
This allows anyone to ready any file on the host server, just set `id` to `../../../filehere.xyz` for example.

**Comment by Ellpeck** [comment]
Plugin changes are implemented now! Sorry that I didn't catch those. I used [this seemingly older file](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md) for reviewing since that's the one I used when publishing my previous plugins - probably missed a link to the new one and just sought this one out on my own.

About the server issue: I don't know which is more embarrassing, the fact that I made that mistake in the first place, or the fact that the friends I asked to review the code didn't catch it either - oh God. Should be all fixed now, though!

**Comment by liamcain** [comment]
- [frontmatter](https://github.com/Ellpeck/ObsidianJustSharePlease/blob/dcfe7e6f3da8b249da4f98c93fee59383928731d/src/settings-tab.ts#L33) I would consider renaming this setting to "Include file properties" and flipping the value. I think that's a bit more user friendly than "strip frontmatter" which is a bit more technical. You could even include a link to https://help.obsidian.md/Editing+and+formatting/Properties for bonus points

**Comment by Ellpeck** [comment]
That's a good point, thanks! I think I made that configuration before properties were properly introduced into Obsidian? I'll put it on my to-do list either way, though!

**Pull request merged**
