### PR TITLE
Add plugin: Smart Templates

### PR DESCRIPTION
**Pull request by brianpetro**
Add Smart Templates

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/brianpetro/obsidian-smart-templates

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Review by brianpetro — COMMENTED** [review]
move to end

**Review by brianpetro — COMMENTED** [review]
added isDesktopOnly false

**Comment by brianpetro** [comment]
The license is in the repo; does it need to be in the release, too?

smart-temnplates license

**Review by brianpetro — COMMENTED** [review]
updated release with changed manifest

**Review by brianpetro — COMMENTED** [review]
fix json

**Comment by joethei** [comment]
[console.log("Initializing");](https://github.com/brianpetro/obsidian-smart-templates/blob/3f3f844b31a6665d7b439c016f27ad09ec2411bf/main.js#L39), [console.log("Loaded settings");](https://github.com/brianpetro/obsidian-smart-templates/blob/3f3f844b31a6665d7b439c016f27ad09ec2411bf/main.js#L45), [console.log("Created smart env");](https://github.com/brianpetro/obsidian-smart-templates/blob/3f3f844b31a6665d7b439c016f27ad09ec2411bf/main.js#L49), [console.log("Loaded smart templates");](https://github.com/brianpetro/obsidian-smart-templates/blob/3f3f844b31a6665d7b439c016f27ad09ec2411bf/main.js#L51), [console.log("Added setting tab");](https://github.com/brianpetro/obsidian-smart-templates/blob/3f3f844b31a6665d7b439c016f27ad09ec2411bf/main.js#L53), [console.log("Added commands");](https://github.com/brianpetro/obsidian-smart-templates/blob/3f3f844b31a6665d7b439c016f27ad09ec2411bf/main.js#L55-L56), [console.log(this.settings.var_prompts);](https://github.com/brianpetro/obsidian-smart-templates/blob/3f3f844b31a6665d7b439c016f27ad09ec2411bf/main.js#L143), [console.log(ctx);](https://github.com/brianpetro/obsidian-smart-templates/blob/3f3f844b31a6665d7b439c016f27ad09ec2411bf/main.js#L210), [console.log(template_content);](https://github.com/brianpetro/obsidian-smart-templates/blob/3f3f844b31a6665d7b439c016f27ad09ec2411bf/main.js#L222), [console.log(template_frontmatter);](https://github.com/brianpetro/obsidian-smart-templates/blob/3f3f844b31a6665d7b439c016f27ad09ec2411bf/main.js#L224), [console.log(resp);](https://github.com/brianpetro/obsidian-smart-templates/blob/3f3f844b31a6665d7b439c016f27ad09ec2411bf/main.js#L236), [console.log("Loading settings");](https://github.com/brianpetro/obsidian-smart-templates/blob/3f3f844b31a6665d7b439c016f27ad09ec2411bf/main.js#L294), [else console.log("Model settings already loaded");](https://github.com/brianpetro/obsidian-smart-templates/blob/3f3f844b31a6665d7b439c016f27ad09ec2411bf/main.js#L312)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.
There is also more logging in the `smart-templates` and `smart-environment` dependencies that should get removed.

[id: 'smart-templates-update-commands',](https://github.com/brianpetro/obsidian-smart-templates/blob/3f3f844b31a6665d7b439c016f27ad09ec2411bf/main.js#L186), [id: `smart-template-${format_command_name(template.name)}`,](https://github.com/brianpetro/obsidian-smart-templates/blob/3f3f844b31a6665d7b439c016f27ad09ec2411bf/main.js#L198)
Remove the `smart-template(s)` prefixes.

[name: 'Refresh Commands (adds/removes templates from commands)',](https://github.com/brianpetro/obsidian-smart-templates/blob/3f3f844b31a6665d7b439c016f27ad09ec2411bf/main.js#L187), [data-name="Model Platform"](https://github.com/brianpetro/obsidian-smart-templates/blob/3f3f844b31a6665d7b439c016f27ad09ec2411bf/smart_templates_model_settings.ejs#L2), [data-name="Model Name"](https://github.com/brianpetro/obsidian-smart-templates/blob/3f3f844b31a6665d7b439c016f27ad09ec2411bf/smart_templates_model_settings.ejs#L12), [data-name="Refresh Models List"](https://github.com/brianpetro/obsidian-smart-templates/blob/3f3f844b31a6665d7b439c016f27ad09ec2411bf/smart_templates_model_settings.ejs#L20), [data-name="Templates Folder"](https://github.com/brianpetro/obsidian-smart-templates/blob/3f3f844b31a6665d7b439c016f27ad09ec2411bf/smart_templates_settings.ejs#L11)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[if(!(await this.main.app.vault.adapter.exists('.obsidian/plugins/smart-connections/data.json'))) return false;](https://github.com/brianpetro/obsidian-smart-templates/blob/3f3f844b31a6665d7b439c016f27ad09ec2411bf/main.js#L329-L330), [const config_file = await this.main.app.vault.adapter.read('.obsidian/plugins/smart-connections/data.json');](https://github.com/brianpetro/obsidian-smart-templates/blob/3f3f844b31a6665d7b439c016f27ad09ec2411bf/main.js#L374)
The config folder is not neccessarily `.obsidian` it can be chosen by the user, use `this.vault.configDir`

[<h1>Smart Templates</h1>](https://github.com/brianpetro/obsidian-smart-templates/blob/3f3f844b31a6665d7b439c016f27ad09ec2411bf/smart_templates_settings.ejs#L2)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by brianpetro** [comment]
@joethei all of the above has been addressed in the latest version `1.0.37`

Thanks 🌴

**Pull request merged**
