### PR TITLE
Add plugin: Unofficial Fabric Integration

### PR DESCRIPTION
**Pull request by chasebank87**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/chasebank87/unofficial-fabric-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["minAppVersion": "0.15.0",](https://github.com/chasebank87/unofficial-fabric-plugin/blob/3b350af3c044dbcef65b67600fc7bac7ad4871a7/manifest.json#L5)

["fundingUrl": "https://github.com/chasebank87/unofficial-fabric-plugin.git",](https://github.com/chasebank87/unofficial-fabric-plugin/blob/3b350af3c044dbcef65b67600fc7bac7ad4871a7/manifest.json#L9)
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link remove this line.

["css": "styles.css"](https://github.com/chasebank87/unofficial-fabric-plugin/blob/3b350af3c044dbcef65b67600fc7bac7ad4871a7/manifest.json#L11)
This is not a valid part of the manifest, remove it.

[if (os.platform() === 'win32') {](https://github.com/chasebank87/unofficial-fabric-plugin/blob/3b350af3c044dbcef65b67600fc7bac7ad4871a7/main.ts#L75), [const platform = os.platform();](https://github.com/chasebank87/unofficial-fabric-plugin/blob/3b350af3c044dbcef65b67600fc7bac7ad4871a7/main.ts#L526)
Use `Platform.isWin`/`Platform.isLinux`/`Platform.isMacOS` instead.

[attr: { src: 'https://github.com/danielmiessler/fabric/blob/main/images/fabric-logo-gif.gif?raw=true' }](https://github.com/chasebank87/unofficial-fabric-plugin/blob/3b350af3c044dbcef65b67600fc7bac7ad4871a7/main.ts#L184)
This should not be loaded from the server, but rather bundled into the plugin.

[const currentNoteBtn = this.buttonsContainer.createEl('button', { text: 'Current Note', cls: 'fabric-button current-note' });](https://github.com/chasebank87/unofficial-fabric-plugin/blob/3b350af3c044dbcef65b67600fc7bac7ad4871a7/main.ts#L194), [.setName ('Fabric Path')](https://github.com/chasebank87/unofficial-fabric-plugin/blob/3b350af3c044dbcef65b67600fc7bac7ad4871a7/main.ts#L434), [.setName('FFmpeg Path')](https://github.com/chasebank87/unofficial-fabric-plugin/blob/3b350af3c044dbcef65b67600fc7bac7ad4871a7/main.ts#L445), [.setName('Output Folder')](https://github.com/chasebank87/unofficial-fabric-plugin/blob/3b350af3c044dbcef65b67600fc7bac7ad4871a7/main.ts#L461), [.setName('Test Fabric Installation')](https://github.com/chasebank87/unofficial-fabric-plugin/blob/3b350af3c044dbcef65b67600fc7bac7ad4871a7/main.ts#L472), [.setName('Test FFmpeg Installation')](https://github.com/chasebank87/unofficial-fabric-plugin/blob/3b350af3c044dbcef65b67600fc7bac7ad4871a7/main.ts#L496)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[containerEl.createEl('h2', { text: 'Fabric Settings' });](https://github.com/chasebank87/unofficial-fabric-plugin/blob/3b350af3c044dbcef65b67600fc7bac7ad4871a7/main.ts#L431)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by chasebank87** [comment]
Requested changes were made.

**Comment by chasebank87** [comment]
Ive made the changes requested.  Not sure why the status isnt changing?

**Comment by joethei** [comment]
`minAppVersion` was not updated, and it looks like I forgot to add a reason why it needs to be changed, updated my comment above.

**Comment by chasebank87** [comment]
Updated minAppVersion

**Pull request merged**
