### PR TITLE
Add Mado Miniflow Theme

### PR DESCRIPTION
**Pull request by hydescarf**
# I am submitting a new Community Theme

## Repo URL

Link to my theme: https://github.com/hydescarf/Obsidian-Theme-Mado-Miniflow

## Theme checklist

- [x] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo).
  - [x] `obsidian.css`
  - [x] The screenshot file.
- [x] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other themes that I'm using.
      I have given proper attribution to these other themes in my `README.md`.
- [x] If my repo is not using the `master` branch, please indicate in `community-themes.json` with `"branch": "main"`.

### CODE REVIEW

**Comment by ericaxu** [comment]
Great theme! I love the waves at the bottom.

One suggestion: maybe you want to consider giving it a different name? "Minimal" is the name of another popular theme, and I don't want people get confused.

**Comment by hydescarf** [comment]
Oh damn, I actually like the rhythm on this name :(. And thank you!
Noted, I'm gonna take some time to come up with a name later.

By the way, is there any alternative word you can suggest for the word minimal?

**Comment by hydescarf** [comment]
I have changed the name to Mado Miniflow, and hopefully I did the commit editing right, please have a check and let me know if there's any other issue left!

**Comment by ericaxu** [comment]
> I have changed the name to Mado Miniflow, and hopefully I did the commit editing right, please have a check and let me know if there's any other issue left!

Awesome! Looks good to me. If you don't mind posting it to our Discord (there's an #update channel to announce new themes if you claim the "developer" role here https://discord.com/channels/686053708261228577/702717892533157999/830492034807758859), I think many users will appreciate this pretty theme!

**Comment by hydescarf** [comment]
Thank you for the merge and suggestion! Let me have a check on that place then :D

**Pull request merged**
