### PR TITLE
Add plugin: Image Inline

### PR DESCRIPTION
**Pull request by ZackaryW**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/ZackaryW/obsidian-image-inline

## Release Checklist
- [ ] I have tested the plugin on
  - [X ]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [X] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by ZackaryW** [comment]
closing initial pull request due to main branch update https://github.com/obsidianmd/obsidian-releases/pull/2898

**Comment by joethei** [comment]
Why is your plugin marked as desktop only?
I don't see any reason for it to be.

[id: 'convert-image-to-base64-hotkey',](https://github.com/ZackaryW/obsidian-image-inline/blob/7d4908b5140f344cb5a0d3e29d1d4896107f8086/src/main.ts#L25), [name: 'Convert Image to Base64 (Hotkey)',](https://github.com/ZackaryW/obsidian-image-inline/blob/7d4908b5140f344cb5a0d3e29d1d4896107f8086/src/main.ts#L26)
Remove the "Hotkey" portion.

[hotkeys: [{ modifiers: ["Ctrl", "Alt"], key: "v" }],](https://github.com/ZackaryW/obsidian-image-inline/blob/7d4908b5140f344cb5a0d3e29d1d4896107f8086/src/main.ts#L27)
While there's no hard rule against it, we recommend against providing a default hotkey when possible. The reason being that it's easy to pick a hotkey that a user already has configured and they could get confused when that key doesn't do what they expect. Also, it's hard choosing a safe default hotkey that's available for all operating systems & does not conflict with existing plugins.

[callback: () => this.handleHotkeyCommand(),](https://github.com/ZackaryW/obsidian-image-inline/blob/7d4908b5140f344cb5a0d3e29d1d4896107f8086/src/main.ts#L28)
use a editorCallback to make sure that command will only show up if there is an active editor.
https://docs.obsidian.md/Plugins/User+interface/Commands#Editor+commands

[const editor = activeView.editor;](https://github.com/ZackaryW/obsidian-image-inline/blob/7d4908b5140f344cb5a0d3e29d1d4896107f8086/src/main.ts#L92)
And use that editor instance passed there here.


[async convertBlobToBase64(blob: Blob): Promise<string> {](https://github.com/ZackaryW/obsidian-image-inline/blob/7d4908b5140f344cb5a0d3e29d1d4896107f8086/src/main.ts#L78)
Instead of this function use:
```ts
arrayBufferToBase64(await getBlobArrayBuffer(blob));
```

[containerEl.createEl('h2', { text: 'Settings for Image to Base64 Plugin' });](https://github.com/ZackaryW/obsidian-image-inline/blob/7d4908b5140f344cb5a0d3e29d1d4896107f8086/src/main.ts#L121)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by ZackaryW** [comment]
@joethei Thanks for the advice. I have updated the project according to the guidelines. Please let me know what else needs improvement.

**Comment by ZackaryW** [comment]
updated, thank you

**Comment by ZackaryW** [comment]
updated, thank you @ObsidianReviewBot

**Pull request merged**
