### PR TITLE
Add SynthWave theme

### PR DESCRIPTION
**Pull request by marcoluzi**
# I am submitting a new Community Theme

## Repo URL

Link to my theme: https://github.com/marcoluzi/obsidian-synthwave

## Theme checklist

- [x] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo).
  - [x] `obsidian.css`
  - [x] The screenshot file.
- [x] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other themes that I'm using.
      I have given proper attribution to these other themes in my `README.md`.

### CODE REVIEW

**Comment by ericaxu** [comment]
@marcoluzi Sorry for the slow review process, we've been busy with a big design overhaul in the recently released v1.0 of Obsidian. Now that 1.0 has been released and Obsidian's UI has undergone some sweeping changes, we are asking all theme entries to confirm that their theme is compatible with the latest version of Obsidian.

**Comment by marcoluzi** [comment]
Thanks for the reply @ericaxu :)
Will have a look at it as soon as possible.

**Comment by marcoluzi** [comment]
@ericaxu 
I updated the theme. It is now compatible with v1.0.
https://github.com/marcoluzi/obsidian-synthwave

**Comment by ericaxu** [comment]
> @ericaxu I updated the theme. It is now compatible with v1.0. https://github.com/marcoluzi/obsidian-synthwave

Great, thanks!

One minor thing: you might want to make the screenshot smaller while keeping the 16:9 aspect ratio. That would make your theme load faster in the theme store. You can still include high resolution screenshots in your README.

We recommend using a screenshot of size 512px by 288px as the featured screenshot to minimize loading time.

**Comment by marcoluzi** [comment]
@ericaxu 
I updated the screenshot resolution.
https://github.com/marcoluzi/obsidian-synthwave/commit/20c58f3eb52ae34581a9c5ef790bbd4c6857397e

**Comment by ericaxu** [comment]
Thank you for your work! <3

**Pull request merged**
