### PR TITLE
Add Bulk open selected links plugin

### PR DESCRIPTION
**Pull request by autohub7**
# I am submitting a new Community Plugin

## Repo URL
Link to my plugin:
https://github.com/autohub7/obsidian-open-selected-links

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["author": "Obsidian",](https://github.com/autohub7/obsidian-open-selected-links/blob/d79b4cf3d78d2a59b3f19f7ffc8bf26f27b7e7fe/manifest.json#L7-L8)
Please use your name for `author`, and use a website link for `authorUrl`, if you do not have a website, use the link to your GitHub profile.

**Comment by autohub7** [comment]
@joethei Thank you for taking your time to review. I updated the manifest

**Comment by liamcain** [comment]
- [var](https://github.com/autohub7/obsidian-open-selected-links/blob/225cf52294086696fb9b6446ee4d977acbff255b/main.ts#L29) I recommend you change all instances of `var` to either `const` or `let`. `var` has function-level scope, so it can easily lead to bugs if you're not careful.

**Comment by autohub7** [comment]
I'll update it in the next release. Thanks for reviewing it

**Pull request merged**
