### PR TITLE
Add email-block-plugin plugin to community-plugins

### PR DESCRIPTION
**Pull request by joleaf**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/joleaf/obsidian-email-block-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by liamcain** [comment]
- [getActiveFile](https://github.com/joleaf/obsidian-email-block-plugin/blob/08ed247d01cdc20cb867d1f35412959865bd51f2/main.ts#L92) I think you're better off using [`getAbstractFileByPath`](https://github.com/obsidianmd/obsidian-api/blob/902badd38ba907689f0917d7b193f7e33d1284fe/obsidian.d.ts#L3612) and finding the file via the ctx.sourcePath instead of assuming that the file being rendered is the activeFile.
- [""](https://github.com/joleaf/obsidian-email-block-plugin/blob/08ed247d01cdc20cb867d1f35412959865bd51f2/main.ts#L123) you are passing in empty string for the source path. This should be ctx.sourcePath instead. A way you can test to make sure this is correct is to try it on an "ambiguous" link. So if you have two files with the same name in different folders, it's important to know the current file that you're linking from so that the link lookup can be find the correct file.

**Comment by joleaf** [comment]
Thank you @liamcain ! I appreciate your comments and suggestions, thank you!
I fixed both issues and hope that the plugin is okay now.

**Comment by liamcain** [comment]
Sorry, one more small thing: https://github.com/joleaf/obsidian-email-block-plugin/commit/dba36786a973e95879bf42962ec92c96c57d5352#diff-564c860307257bfac9176f554a35aa858c350a59d75c0dcd0a5d63a480805bd0R93

I know it's a bit weird since the second parameter calls for the sourcePath, but in this case you actually want to pass "" as the second parameter. The sourcePath in this case will be a full path from the vault root, meaning the sourcePath would be the vault root or "" for short.

**Comment by joleaf** [comment]
@liamcain Okay lol :D Thank you again for the review! This is fixed as well.

**Comment by liamcain** [comment]
Maybe you forgot to push? I don't see any changes since 0.3.1

**Comment by joleaf** [comment]
-.-  yes, now it is pushed..

**Pull request merged**
