### PR TITLE
Add T9R theme

### PR DESCRIPTION
**Pull request by vidar-tech**
# I am submitting a new Community Theme

## Repo URL

Link to my theme:  https://github.com/The9Realms/obsidian-t9r

## Theme checklist

- [x] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo).
  - [x] `obsidian.css`
  - [x] The screenshot file.
- [x] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other themes that I'm using.
      I have given proper attribution to these other themes in my `README.md`.

### CODE REVIEW

**Comment by VidarSec** [comment]
?

**Comment by VidarSec** [comment]
Is this pull also processed?

**Comment by ericaxu** [comment]
Hi @VidarSec , sorry about the wait!

Have you tested your theme on 1.0? If it works please let me know so I can merge it!

One minor thing: you might want to make the screenshot smaller while keeping the 16:9 aspect ratio. That would make your theme load faster in the theme store. You can still include high resolution screenshots in your README.

We recommend using a screenshot of size 512px by 288px as the featured screenshot to minimize loading time.

**Comment by joethei** [comment]
Hi @VidarSec do you still intent on submitting this theme?

**Comment by VidarSec** [comment]
@joethei sure

**Comment by ericaxu** [comment]
> @joethei sure

Can you confirm the theme works well on Obsidian 1.0+?

If so we can merge it. Screenshot size reduction is also recommended!

**Comment by joethei** [comment]
This theme currently does not have the new required structure.
See here for our migration guide: https://forum.obsidian.md/t/1-0-theme-migration-guide/42537

**Pull request closed without merging**
