### PR TITLE
Update community-plugins.json

### PR DESCRIPTION
**Pull request by Quorafind**
Add a new plugin

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [https://github.com/Quorafind/Obsidian-Big-Calendar](https://github.com/Quorafind/Obsidian-Big-Calendar)

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by lishid** [comment]
Apologies for the late review!

https://github.com/Quorafind/Obsidian-Big-Calendar/blob/5b087620d89a9351ae13558b973276c96b8bb455/src/index.ts#L10
Here I don't think you should use either global values.

`app` is a debug variable that's there to facilitate debugging, but it shouldn't be relied upon to get a reference to Obsidian's app object. You get a reference of `app` passed to your plugin, which can be passed to various parts of your plugin.

`plugin` is such a common name that you'll likely run into issues if another plugin uses it, and you might leak memory if you assign it but don't clean it up properly.

https://github.com/Quorafind/Obsidian-Big-Calendar/blob/5b087620d89a9351ae13558b973276c96b8bb455/src/data/constants.ts#L1
You should consider selecting more unique names here, perhaps "big-calendar" (and also `-view` is probably not necessary).

https://github.com/Quorafind/Obsidian-Big-Calendar/blob/5b087620d89a9351ae13558b973276c96b8bb455/src/index.ts#L77
You should use `leaf.setState({type: MY_VIEW_TYPE})` instead of creating a view object manually. Doing it this way helps properly manage the lifecycle of the leaf, such as saving the workspace after this change, updating the navigation history, etc.

https://github.com/Quorafind/Obsidian-Big-Calendar/blob/5b087620d89a9351ae13558b973276c96b8bb455/src/ui/BigCalendarView.tsx#L190
It seems that you are re-parsing every single daily note on a timer. That's going to be very performance intensive especially when the number of daily notes gets large.

You'll want to keep a copy of the previously parsed daily notes, and only re-parse it if it has changed (`tfile.stat.mtime` is different). That will help tremendously with the wasted CPU cycles constantly re reading each file.

https://github.com/Quorafind/Obsidian-Big-Calendar/blob/5b087620d89a9351ae13558b973276c96b8bb455/src/ui/BigCalendarView.tsx#L3
Should also import moment from obsidian instead of moment, to avoid a duplicate copy being imported.

https://github.com/Quorafind/Obsidian-Big-Calendar/blob/5b087620d89a9351ae13558b973276c96b8bb455/src/bigCalendar.ts#L53
Shouldn't you be un-mounting the react component here, which has its own intervals being registered in the `componentWillUnmount`?

https://github.com/Quorafind/Obsidian-Big-Calendar/blob/5b087620d89a9351ae13558b973276c96b8bb455/src/utils.ts#L10
This exists as `Math.clamp` https://github.com/obsidianmd/obsidian-api/blob/c148c24b30dc68d9835820b4169b95d3a038a0f6/obsidian.d.ts#L27

**Comment by Quorafind** [comment]
> Apologies for the late review!
> 
> https://github.com/Quorafind/Obsidian-Big-Calendar/blob/5b087620d89a9351ae13558b973276c96b8bb455/src/index.ts#L10 Here I don't think you should use either global values.
> 
> `app` is a debug variable that's there to facilitate debugging, but it shouldn't be relied upon to get a reference to Obsidian's app object. You get a reference of `app` passed to your plugin, which can be passed to various parts of your plugin.
> 

Fixed, Check: https://github.com/Quorafind/Obsidian-Big-Calendar/blob/main/src/index.ts

> `plugin` is such a common name that you'll likely run into issues if another plugin uses it, and you might leak memory if you assign it but don't clean it up properly.
> 

Fixed.  

> https://github.com/Quorafind/Obsidian-Big-Calendar/blob/5b087620d89a9351ae13558b973276c96b8bb455/src/data/constants.ts#L1 You should consider selecting more unique names here, perhaps "big-calendar" (and also `-view` is probably not necessary).
> 

Fixed. Check: https://github.com/Quorafind/Obsidian-Big-Calendar/blob/main/src/constants.ts

> https://github.com/Quorafind/Obsidian-Big-Calendar/blob/5b087620d89a9351ae13558b973276c96b8bb455/src/index.ts#L77 You should use `leaf.setState({type: MY_VIEW_TYPE})` instead of creating a view object manually. Doing it this way helps properly manage the lifecycle of the leaf, such as saving the workspace after this change, updating the navigation history, etc.
> 

Fixed. Check: https://github.com/Quorafind/Obsidian-Big-Calendar/blob/main/src/index.ts

> https://github.com/Quorafind/Obsidian-Big-Calendar/blob/5b087620d89a9351ae13558b973276c96b8bb455/src/ui/BigCalendarView.tsx#L190 It seems that you are re-parsing every single daily note on a timer. That's going to be very performance intensive especially when the number of daily notes gets large.
> 

Remove all timer, use react hook instead.

> You'll want to keep a copy of the previously parsed daily notes, and only re-parse it if it has changed (`tfile.stat.mtime` is different). That will help tremendously with the wasted CPU cycles constantly re reading each file.
> 

Use redux to refresh new files(if have) instead. 

> https://github.com/Quorafind/Obsidian-Big-Calendar/blob/5b087620d89a9351ae13558b973276c96b8bb455/src/ui/BigCalendarView.tsx#L3 Should also import moment from obsidian instead of moment, to avoid a duplicate copy being imported.
> 

Removed, or used import from Obsidian instead.

> https://github.com/Quorafind/Obsidian-Big-Calendar/blob/5b087620d89a9351ae13558b973276c96b8bb455/src/bigCalendar.ts#L53 Shouldn't you be un-mounting the react component here, which has its own intervals being registered in the `componentWillUnmount`?
> 

Remove, don't use class anymore.

> https://github.com/Quorafind/Obsidian-Big-Calendar/blob/5b087620d89a9351ae13558b973276c96b8bb455/src/utils.ts#L10 This exists as `Math.clamp` https://github.com/obsidianmd/obsidian-api/blob/c148c24b30dc68d9835820b4169b95d3a038a0f6/obsidian.d.ts#L27

Remove whole file. Don't use it anymore.

**Comment by lishid** [comment]
I don't have permission to your PR branch to merge this conflict; give me permission or fix the merge?

**Comment by Quorafind** [comment]
image

Is this ok? I don't know how to fix pr.... Close and then open this again?

**Comment by lishid** [comment]
Ok it seems like you deleted the PR branch for `obsidian-releases`:
image
I guess you can fork this repo again and then re-apply the changes in your clone, then I can merge that one.

**Comment by Quorafind** [comment]
Close via https://github.com/obsidianmd/obsidian-releases/pull/799

**Pull request closed without merging**
