### PR TITLE
Add plugin: Frontmatter generator

### PR DESCRIPTION
**Pull request by HananoshikaYomaru**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/HananoshikaYomaru/Obsidian-Frontmatter-Generator

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[element.innerHTML = result.error.message;](https://github.com/HananoshikaYomaru/Obsidian-Frontmatter-Generator/blob/55330aee9b11ee1b1da136845559d0d5743953f4/src/utils/setRealTimePreview.ts#L14)
[element.innerHTML = JSON.stringify(result.object, null, 2);](https://github.com/HananoshikaYomaru/Obsidian-Frontmatter-Generator/blob/55330aee9b11ee1b1da136845559d0d5743953f4/src/utils/setRealTimePreview.ts#L19)
[Avoid using `innerHTML`](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%60innerHTML%60%2C+%60outerHTML%60+and+%60insertAdjacentHTML%60)


[.setName("Frontmatter Template")](https://github.com/HananoshikaYomaru/Obsidian-Frontmatter-Generator/blob/55330aee9b11ee1b1da136845559d0d5743953f4/src/ui/SettingTab.ts#L81)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[realTimePreview.style.textAlign = "left";](https://github.com/HananoshikaYomaru/Obsidian-Frontmatter-Generator/blob/55330aee9b11ee1b1da136845559d0d5743953f4/src/ui/SettingTab.ts#L85-L88)
You should avoid assigning styles via JavaScript or in HTML and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets.

**Comment by HananoshikaYomaru** [comment]
@joethei the comments has been resolved. Please review again. 

https://github.com/HananoshikaYomaru/Obsidian-Frontmatter-Generator/releases/tag/1.0.9

**Comment by HananoshikaYomaru** [comment]
@joethei sorry for pinging you. But I don't want this to onhold too long.

**Comment by liamcain** [comment]
- [Runing](https://github.com/HananoshikaYomaru/Obsidian-Frontmatter-Generator/blob/e71f57102d589efd2a1aea59ca86a47a5cd4b8b8/src/main.ts#L216) typo
- [for (const eventRef of this.eventRefs) {](https://github.com/HananoshikaYomaru/Obsidian-Frontmatter-Generator/blob/e71f57102d589efd2a1aea59ca86a47a5cd4b8b8/src/main.ts#L353-L355) this is unnecessary. You already register the eventRefs with the plugin, they will be unloaded automatically.


You have a lot of unused code in your plugin which makes it hard to review (its hard to trace what utils are used for this plugin or just copied from another plugin). In the future, could you please make sure to remove unused utils?

**Comment by HananoshikaYomaru** [comment]
@liamcain Thank you so much. Absolutely, I will remove the unused code. Sorry for not being considerate. But thanks for approving it.

**Pull request merged**
