### PR TITLE
Add plugin: Generate Block ID

### PR DESCRIPTION
**Pull request by SH3LLco**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/SH3LLco/obsidian-generate-block-id

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by SH3LLco** [comment]
im not sure what happened, but this pull request somehow conflicted with mine, they overlapped my json and broke my validation https://github.com/obsidianmd/obsidian-releases/pull/3833

**Comment by joethei** [comment]
I've fixed this, please don't fix any of the merge conflicts yourself, I'll do that when the plugin is ready to merge.

**Comment by SH3LLco** [comment]
> I've fixed this, please don't fix any of the merge conflicts yourself, I'll do that when the plugin is ready to merge.

THANK YOU!

**Comment by SH3LLco** [comment]
> Thank you for your submission, an automated scan of your plugin code's revealed the following issues:
> ### Required
> 
> [[1](https://github.com/SH3LLco/obsidian-generate-block-id/blob/da8ad22fe8305506946a64c3d459c2172fe01602/main.js)]:Please remove the `main.js` file from the repo and add it to your .gitignore. Compiled release files shouldn't get mixed with source code in your commits and should go to the releases files instead.
> 
> [[1](https://github.com/SH3LLco/obsidian-generate-block-id/blob/da8ad22fe8305506946a64c3d459c2172fe01602/src/main copy.ts#L13)][[2](https://github.com/SH3LLco/obsidian-generate-block-id/blob/da8ad22fe8305506946a64c3d459c2172fe01602/src/main.ts#L12)]:The command name should not include the plugin name.
> ### Optional
> 
> [[1](https://github.com/SH3LLco/obsidian-generate-block-id/blob/da8ad22fe8305506946a64c3d459c2172fe01602/src/main copy.ts#L17)][[2](https://github.com/SH3LLco/obsidian-generate-block-id/blob/da8ad22fe8305506946a64c3d459c2172fe01602/src/main.ts#L16)][[3](https://github.com/SH3LLco/obsidian-generate-block-id/blob/da8ad22fe8305506946a64c3d459c2172fe01602/src/src.old/main.ts#L17)][[4](https://github.com/SH3LLco/obsidian-generate-block-id/blob/da8ad22fe8305506946a64c3d459c2172fe01602/src/src.old/og/src/main.ts#L17)]:We recommend against providing a default hotkey when possible. The reason being that it's easy to pick a hotkey that a user already has configured and they could get confused when that key doesn't do what they expect. Also, it's hard choosing a safe default hotkey that's available for all operating systems.
> 
> Do NOT open a new PR for re-validation. Once you have pushed all of the required changes to your repo, the bot will update the labels on this PR within 6 hours. If you think some of the required changes are incorrect, please comment with `/skip` and the reason why you think the results are incorrect.

/skip optional

Reason: The hotkey is empty

**Comment by SH3LLco** [comment]
Just let me know what i need to do on my end. Im new to this whole pull request process.

**Comment by joethei** [comment]
Remove the `data.json` file fron the repo and add it to the `.gitignore`
Remove the `styles.css` file from your release, since it's empty it's just unnecessary bloat.
Also remove the `main.js` from the `src` folder and add it to the `gitignore`, release assets should not be included with the source code.
Also clean up the `src` folder, most of those files should not be in there, but rather in the reood of the repo.


["description": "Ribbon and command palette to generate a human-readable block ID based on header structure. If no headers are present it uses file name. Each block is generated with sequential numbers.",](https://github.com/SH3LLco/obsidian-generate-block-id/blob/ab9c333dc5517d92605a826c7b37bda0b99c8871/src/manifest.json#L6)
You don't need to mention the ribbon and command palette, that should be in the README.

[const { Plugin, MarkdownView, setIcon } = require('obsidian');](https://github.com/SH3LLco/obsidian-generate-block-id/blob/ab9c333dc5517d92605a826c7b37bda0b99c8871/src/main.ts#L1)
Use the ECMAScript syntax.

[const activeLeaf = this.app.workspace.activeLeaf;](https://github.com/SH3LLco/obsidian-generate-block-id/blob/ab9c333dc5517d92605a826c7b37bda0b99c8871/src/main.ts#L21)
`activeLeaf` is deprecated, to get the active editor use `this.app.workspace.activeEditor?.editor`

**Pull request closed without merging**
