### PR TITLE
Add Liquid Templates plugin

### PR DESCRIPTION
**Pull request by oeN**
# [ ] I am submitting a new Community Plugin

## Repo URL

https://github.com/oeN/liquid-template

## Release Checklist

- [ ] I have tested this on Windows, macOS, and Linux _(if applicable)_
  - [x] Windows
  - [ ] macOS
  - [ ] Linux  
- [x] Github release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - `styles.css` _(optional)_
- [x] Github release name matches the exact version number specified in your manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/oeN/liquid-template/blob/8ac98d233754d0bdbd08593f94ca55ddfa3489f2/main.ts#L27
Please unhook your event when unloading your plugin, using `workspace.iterateCodeMirrors`.

https://github.com/oeN/liquid-template/blob/8ac98d233754d0bdbd08593f94ca55ddfa3489f2/suggest/template-suggest.ts#L77
Should probably filter by extension here as well.

**Comment by oeN** [comment]
Thank you, I'll make the changes tonight 😄

**Comment by oeN** [comment]
modifications are done https://github.com/oeN/liquid-template/pull/1/files

**Comment by lishid** [comment]
https://github.com/oeN/liquid-template/blob/8187dfb364c69cd9b3c74149a9ca975cfc0dde18/utils.ts#L6
Might want to rename the function to reflect that it's getting markdown files too.

**Pull request merged**
