### PR TITLE
Add plugin: Multi Properties

### PR DESCRIPTION
**Pull request by fez-github**
> # I am submitting a new Community Plugin
> ## Repo URL
> 
> Link to my plugin: https://github.com/fez-github/obsidian-multi-tag
> ## Release Checklist
> 
>     * [ ]  I have tested the plugin on
>       
>       * [x]   Windows
>       * [ ]   macOS
>       * [ ]   Linux
>       * [ ]   Android _(if applicable)_
>       * [ ]   iOS _(if applicable)_
> 
>     * [x]  My GitHub release contains all required files
>       
>       * [x]  `main.js`
>       * [x]  `manifest.json`
>       * [x]  `styles.css` _(optional)_
> 
>     * [x]  GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
> 
>     * [x]  The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
> 
>     * [x]  My README.md describes the plugin's purpose and provides clear usage instructions.
> 
>     * [x]  I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
> 
>     * [x]  I have added a license in the LICENSE file.
> 
>     * [x]  My project respects and is compatible with the original license of any code from other plugins that I'm using.
>       I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by tu2-atmanand** [comment]
image

1. Correct the indentation
2. Remove the comma at the end.

Hope that helps😊

**Comment by joethei** [comment]
[.setTitle("Add Props to Folder's Notes")](https://github.com/fez-github/obsidian-multi-properties/blob/a6bd67b4c7b5e6472933fcf25b8570bb44ea59b0/src/main.ts#L20), [.setTitle("Add Props to Selected Files")](https://github.com/fez-github/obsidian-multi-properties/blob/a6bd67b4c7b5e6472933fcf25b8570bb44ea59b0/src/main.ts#L33)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)


[console.log({ props });](https://github.com/fez-github/obsidian-multi-properties/blob/a6bd67b4c7b5e6472933fcf25b8570bb44ea59b0/src/main.ts#L99-L100)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

**Comment by fez-github** [comment]
Sentence case has been implemented, and all relevant console.logs have been either deleted or commented out.
[.setTitle("Add props to folder's notes")](https://github.com/fez-github/obsidian-multi-properties/blob/c6e5c04c577025e8158c8e02828d50bda7a2eea7/src/main.ts#L19)
[.setTitle("Add props to selected files")](https://github.com/fez-github/obsidian-multi-properties/blob/c6e5c04c577025e8158c8e02828d50bda7a2eea7/src/main.ts#L32)

**Comment by liamcain** [comment]
- [Conditions are here in case user has spelled "tags" differently.  Any other way to solve this?](https://github.com/fez-github/obsidian-multi-tag/blob/29cd46a4d6e72ae05d8a4ce1680e204ef6e015c9/src/main.ts#L112) you can use parseFrontmatterTags <https://github.com/obsidianmd/obsidian-api/blob/791214a68d0dc322b88e5abce617bdf603cc2a2d/obsidian.d.ts#L2780> to handle this. It will check all spellings and variations.

**Pull request merged**
