### PR TITLE
Add plugin: DIDA(滴答清单)

### PR DESCRIPTION
**Pull request by viduycheung**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/viduycheung/dida-obsidian

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by viduycheung** [comment]
fixed

**Comment by joethei** [comment]
Why did you create a new plugin for this?
Wouldn't it be a better idea to just offer a configuration option in the settings?

**Comment by viduycheung** [comment]
> Why did you create a new plugin for this? Wouldn't it be a better idea to just offer a configuration option in the settings?

DIDA and TickTick are different services designed for different regions. The majority of users aren’t aware of the other service. Adding an option to switch between services could cause confusion and make the plugin more challenging to search.

**Comment by joethei** [comment]
I don't see the issue in that, update the name & description to include both names and add a configuration option at the top to select the service used.

**Comment by viduycheung** [comment]
Our team has deliberated on whether to create a new plugin or introduce an option to switch accounts. We believe that developing a new plugin would be the most effective method to provide this feature to DIDA users. However, is it not permissible within Obsidian’s guidelines to have two plugins with similar functionality but different account servers?

**Comment by joethei** [comment]
We want to avoid having multiple plugins that share the same functionality.
The only difference I found between the two plugins is the configuration, which means that the plugins are very similar to each other.

**Comment by how2051** [comment]
If this patch isn't allowed to be merged, can I just download some files of yr repository and install it manually? If so, what should I do, what files to download and move to where? @viduycheung

**Comment by viduycheung** [comment]
> If this patch isn't allowed to be merged, can I just download some files of yr repository and install it manually? If so, what should I do, what files to download and move to where? @viduycheung

You can fork the https://github.com/viduycheung/dida-obsidian and run it locally.

https://docs.obsidian.md/Plugins/Getting+started/Build+a+plugin#Step+2+Build+the+plugin

**Pull request closed without merging**
