### PR TITLE
Add plugin: Vikunja Sync

### PR DESCRIPTION
**Pull request by Heiss**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Heiss/obsidian-vikunja-plugin/releases

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Heiss** [comment]
/skip The console.log calls are for debugging and already behind a toggle, so the dev console will not be polluted by default.

**Comment by joethei** [comment]
["description": "Integrates Vikunja into Obsidian as Task Management Platform.",](https://github.com/Heiss/obsidian-vikunja-plugin/blob/9ef73cdce008f9c934fa001b2855be9d1b04abe5/manifest.json#L6)
Don't include "Obsidian" in the description, and use sentence case.

[const statusBarItemEl = this.addStatusBarItem();](https://github.com/Heiss/obsidian-vikunja-plugin/blob/9ef73cdce008f9c934fa001b2855be9d1b04abe5/main.ts#L101-L102)
Remove this sample code.

[new Setting(containerEl).setHeading().setName('Vikunja Settings').setDesc('Settings to connect to Vikunja.');](https://github.com/Heiss/obsidian-vikunja-plugin/blob/9ef73cdce008f9c934fa001b2855be9d1b04abe5/src/settings/settingTab.ts#L70)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[.setName("Access Token")](https://github.com/Heiss/obsidian-vikunja-plugin/blob/9ef73cdce008f9c934fa001b2855be9d1b04abe5/src/settings/settingTab.ts#L101-L102), [.setName("Cron Interval")](https://github.com/Heiss/obsidian-vikunja-plugin/blob/9ef73cdce008f9c934fa001b2855be9d1b04abe5/src/settings/settingTab.ts#L233)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[new Setting(containerEl).setHeading()](https://github.com/Heiss/obsidian-vikunja-plugin/blob/9ef73cdce008f9c934fa001b2855be9d1b04abe5/src/settings/settingTab.ts#L136-L137)
[Don't add a "general" heading to your settings tab](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section)

[.setName("Check for updates on startUp")](https://github.com/Heiss/obsidian-vikunja-plugin/blob/9ef73cdce008f9c934fa001b2855be9d1b04abe5/src/settings/settingTab.ts#L454)
it's "startup"

**Comment by Heiss** [comment]
@joethei Thanks for the feedback.

Fixed it in tag [1.0.5](https://github.com/Heiss/obsidian-vikunja-plugin/releases/tag/1.0.5).

I do not know, why github closed this PR, but it was a mistake. :)

**Comment by joethei** [comment]
The description was not changed.

**Comment by Heiss** [comment]
> The description was not changed.

ahhh i fooled myself. Should now be fixed. Released in tag 1.0.7.

**Pull request merged**
