### PR TITLE
Add plugin: Math Indicator Changer

### PR DESCRIPTION
**Pull request by Ori-Replication**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Ori-Replication/obsidian-math-indicator-changer

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[interface MathIndicatorChangerSettings {](https://github.com/Ori-Replication/obsidian-math-indicator-changer/blob/d527d19fd84a69a237845f73484317358cf6ec5b/main.ts#L3-L9), [settings: MathIndicatorChangerSettings;](https://github.com/Ori-Replication/obsidian-math-indicator-changer/blob/d527d19fd84a69a237845f73484317358cf6ec5b/main.ts#L12), [async loadSettings() {](https://github.com/Ori-Replication/obsidian-math-indicator-changer/blob/d527d19fd84a69a237845f73484317358cf6ec5b/main.ts#L95-L101), [await this.loadSettings();](https://github.com/Ori-Replication/obsidian-math-indicator-changer/blob/d527d19fd84a69a237845f73484317358cf6ec5b/main.ts#L15)
Your plugin does not have any settings, remove this code.

[this.addRibbonIcon('dollar-sign', 'Change Math Indicator'](https://github.com/Ori-Replication/obsidian-math-indicator-changer/blob/d527d19fd84a69a237845f73484317358cf6ec5b/main.ts#L17), [name: 'Change Math Indicator',](https://github.com/Ori-Replication/obsidian-math-indicator-changer/blob/d527d19fd84a69a237845f73484317358cf6ec5b/main.ts#L44)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by joethei** [comment]
[name: 'Change Math Indicator',](https://github.com/Ori-Replication/obsidian-math-indicator-changer/blob/9f55a26f0b99c548ce3de57644f86d035112482e/main.ts#L32)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by Ori-Replication** [comment]
what the...

**Comment by joethei** [comment]
Still waiting on this:

[name: 'Change Math Indicator',](https://github.com/Ori-Replication/obsidian-math-indicator-changer/blob/9f55a26f0b99c548ce3de57644f86d035112482e/main.ts#L32)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Pull request merged**
