### PR TITLE
Add  Floating TOC Plugin

### PR DESCRIPTION
**Pull request by cumany**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: 
https://github.com/cumany/obsidian-floating-toc-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Please credit the original author in the "author" field here and in your manifest.

["minAppVersion": "0.14.0",](https://github.com/cumany/obsidian-floating-toc-plugin/blob/bc2de32b662e9dd480d62653b7485ae5ca7c9d7e/manifest.json#L5)
Have you tested that your plugin is compatible with this version?

[if (app.workspace.layoutReady) app.workspace.trigger("parse-style-settings");](https://github.com/cumany/obsidian-floating-toc-plugin/blob/bc2de32b662e9dd480d62653b7485ae5ca7c9d7e/src/main.ts#L272)
Please use:
```ts
app.workspace.onLayoutReady(() => {
    //your code
});
```
instead.

[if(prelist)  atag.innerHTML = prelist + par.innerHTML.replace(regex, '');](https://github.com/cumany/obsidian-floating-toc-plugin/blob/bc2de32b662e9dd480d62653b7485ae5ca7c9d7e/src/components/floatingtocUI.ts#L36-L37)
Avoid using `innerHTML`: https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#avoid-innerhtml-outerhtml-and-insertadjacenthtml

[openFileToLine](https://github.com/cumany/obsidian-floating-toc-plugin/blob/bc2de32b662e9dd480d62653b7485ae5ca7c9d7e/src/components/floatingtocUI.ts#L75), [foldheader](https://github.com/cumany/obsidian-floating-toc-plugin/blob/bc2de32b662e9dd480d62653b7485ae5ca7c9d7e/src/components/floatingtocUI.ts#L83), [CreatToc](https://github.com/cumany/obsidian-floating-toc-plugin/blob/bc2de32b662e9dd480d62653b7485ae5ca7c9d7e/src/components/floatingtocUI.ts#L105)
I would recommend choosing one naming strategy and sticking to it.

**Comment by cumany** [comment]
> Please credit the original author in the "author" field here and in your manifest.
> 
> ["minAppVersion": "0.14.0",](https://github.com/cumany/obsidian-floating-toc-plugin/blob/bc2de32b662e9dd480d62653b7485ae5ca7c9d7e/manifest.json#L5) Have you tested that your plugin is compatible with this version?
> 
> [if (app.workspace.layoutReady) app.workspace.trigger("parse-style-settings");](https://github.com/cumany/obsidian-floating-toc-plugin/blob/bc2de32b662e9dd480d62653b7485ae5ca7c9d7e/src/main.ts#L272) Please use:
> 
> ```ts
> app.workspace.onLayoutReady(() => {
>     //your code
> });
> ```
> 
> instead.
> 
> [if(prelist) atag.innerHTML = prelist + par.innerHTML.replace(regex, '');](https://github.com/cumany/obsidian-floating-toc-plugin/blob/bc2de32b662e9dd480d62653b7485ae5ca7c9d7e/src/components/floatingtocUI.ts#L36-L37) Avoid using `innerHTML`: https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#avoid-innerhtml-outerhtml-and-insertadjacenthtml
> 
> [openFileToLine](https://github.com/cumany/obsidian-floating-toc-plugin/blob/bc2de32b662e9dd480d62653b7485ae5ca7c9d7e/src/components/floatingtocUI.ts#L75), [foldheader](https://github.com/cumany/obsidian-floating-toc-plugin/blob/bc2de32b662e9dd480d62653b7485ae5ca7c9d7e/src/components/floatingtocUI.ts#L83), [CreatToc](https://github.com/cumany/obsidian-floating-toc-plugin/blob/bc2de32b662e9dd480d62653b7485ae5ca7c9d7e/src/components/floatingtocUI.ts#L105) I would recommend choosing one naming strategy and sticking to it.

["minAppVersion": "0.14.0",](https://github.com/cumany/obsidian-floating-toc-plugin/blob/bc2de32b662e9dd480d62653b7485ae5ca7c9d7e/manifest.json#L5)
Have you tested that your plugin is compatible with this version?  

Yes, I've tested it and it works fine.

Other issues, I have revised and resubmitted

**Comment by liamcain** [comment]
- [app](https://github.com/cumany/obsidian-floating-toc-plugin/blob/e6d4384c5bbce53e892fbdef3d7b8ce2b34dd960/src/main.ts#L103) Do not rely on the global `app` object. It's better to pass the `app` object from your plugin instance. Or better yet, just pass the MarkdownView in.
- [globalThis](https://github.com/cumany/obsidian-floating-toc-plugin/blob/e6d4384c5bbce53e892fbdef3d7b8ce2b34dd960/src/main.ts#L242) please don't pollute the global namespace. This can just be an instance variable on your plugin class.
- [view](https://github.com/cumany/obsidian-floating-toc-plugin/blob/e6d4384c5bbce53e892fbdef3d7b8ce2b34dd960/src/components/floatingtocUI.ts#L183) view could be null here.

**Comment by cumany** [comment]
@liamcain 

> [app](https://github.com/cumany/obsidian-floating-toc-plugin/blob/e6d4384c5bbce53e892fbdef3d7b8ce2b34dd960/src/main.ts#L103) Do not rely on the global app object. It's better to pass the app object from your plugin instance. Or better yet, just pass the MarkdownView in.

I changed the parameters and now pass the app object directly from the plugin instance

>  [globalThis](https://github.com/cumany/obsidian-floating-toc-plugin/blob/e6d4384c5bbce53e892fbdef3d7b8ce2b34dd960/src/main.ts#L242) please don't pollute the global namespace. This can just be an instance variable on your plugin class.

I removed this way of writing and wrote the instance variables in the plugin class.

>[view](https://github.com/cumany/obsidian-floating-toc-plugin/blob/e6d4384c5bbce53e892fbdef3d7b8ce2b34dd960/src/components/floatingtocUI.ts#L183) view could be null here.

Indeed, I added a check for whether the view is empty or not

**Pull request merged**
