### PR TITLE
Add plugin: Ridian

### PR DESCRIPTION
**Pull request by MichelNivard**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/MichelNivard/Ridian

## Release Checklist
- [X] I have tested the plugin on
  - [X]  Windows
  - [X]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [X] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["authorUrl":"https://github.com/MichelNivard/Ridian"](https://github.com/MichelNivard/Ridian/blob/fa8bee5b9a29087fdc4c6ff95ca2781c1ea6d718/manifest.json#L1)
The `authorUrl` should not go to the GH repository of the plugin.

[body {](https://github.com/MichelNivard/Ridian/blob/fa8bee5b9a29087fdc4c6ff95ca2781c1ea6d718/styles.css#L4-L15), [.HyperMD-codeblock.HyperMD-codeblock-bg.cm-line {](https://github.com/MichelNivard/Ridian/blob/fa8bee5b9a29087fdc4c6ff95ca2781c1ea6d718/styles.css#L29-L32)
Please don't overwrite core styling in a plugin, add another class/data attribute so it only applies to your plugin.

[this.detachViews();](https://github.com/MichelNivard/Ridian/blob/fa8bee5b9a29087fdc4c6ff95ca2781c1ea6d718/src/CombinedPlugin.ts#L53)
Do not detach leaves with your custom view in `onunload`, this is an antipattern, see: <https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Don't+detach+leaves+in+%60onunload%60>

[name: 'Run Current Code Chunk',](https://github.com/MichelNivard/Ridian/blob/fa8bee5b9a29087fdc4c6ff95ca2781c1ea6d718/src/CombinedPlugin.ts#L99), [name: 'Export Note with Quarto',](https://github.com/MichelNivard/Ridian/blob/fa8bee5b9a29087fdc4c6ff95ca2781c1ea6d718/src/CombinedPlugin.ts#L117), ['Run Current Code Chunk'](https://github.com/MichelNivard/Ridian/blob/fa8bee5b9a29087fdc4c6ff95ca2781c1ea6d718/src/FloatingMenu.ts#L68), ['Export Note with Quarto'](https://github.com/MichelNivard/Ridian/blob/fa8bee5b9a29087fdc4c6ff95ca2781c1ea6d718/src/FloatingMenu.ts#L75), [.setName('Quarto Executable Path')](https://github.com/MichelNivard/Ridian/blob/fa8bee5b9a29087fdc4c6ff95ca2781c1ea6d718/src/SettingsTab.ts#L64), [.setName('Enable Floating Menu')](https://github.com/MichelNivard/Ridian/blob/fa8bee5b9a29087fdc4c6ff95ca2781c1ea6d718/src/SettingsTab.ts#L78)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[console.log(`Executing command: ${fullCommandId}`);](https://github.com/MichelNivard/Ridian/blob/fa8bee5b9a29087fdc4c6ff95ca2781c1ea6d718/src/CombinedPlugin.ts#L240), [console.log('Temporary Directory:', tempDir);](https://github.com/MichelNivard/Ridian/blob/fa8bee5b9a29087fdc4c6ff95ca2781c1ea6d718/src/RCodeEvaluator.ts#L446-L448)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[button.setAttribute('aria-label', tooltip);](https://github.com/MichelNivard/Ridian/blob/fa8bee5b9a29087fdc4c6ff95ca2781c1ea6d718/src/FloatingMenu.ts#L134-L135)
Use the `setTooltip` function from the API.

[if (process.platform === 'darwin') {](https://github.com/MichelNivard/Ridian/blob/fa8bee5b9a29087fdc4c6ff95ca2781c1ea6d718/src/PathUtils.ts#L11-L15), [if (process.platform === 'win32') {](https://github.com/MichelNivard/Ridian/blob/fa8bee5b9a29087fdc4c6ff95ca2781c1ea6d718/src/PathUtils.ts#L72), [process.platform === 'win32'](https://github.com/MichelNivard/Ridian/blob/fa8bee5b9a29087fdc4c6ff95ca2781c1ea6d718/src/RCodeEvaluator.ts#L217)
Use the Platform API from Obsidian instead.

[containerEl.createEl('h2', { text: 'R Integration Settings' });](https://github.com/MichelNivard/Ridian/blob/fa8bee5b9a29087fdc4c6ff95ca2781c1ea6d718/src/SettingsTab.ts#L33)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[new Notice('R executable path updated successfully.');](https://github.com/MichelNivard/Ridian/blob/fa8bee5b9a29087fdc4c6ff95ca2781c1ea6d718/src/SettingsTab.ts#L45), [new Notice('RStudio Pandoc path updated successfully.');](https://github.com/MichelNivard/Ridian/blob/fa8bee5b9a29087fdc4c6ff95ca2781c1ea6d718/src/SettingsTab.ts#L59), [new Notice('Quarto executable path updated successfully.');](https://github.com/MichelNivard/Ridian/blob/fa8bee5b9a29087fdc4c6ff95ca2781c1ea6d718/src/SettingsTab.ts#L73), [new Notice('Floating Menu Enabled.');](https://github.com/MichelNivard/Ridian/blob/fa8bee5b9a29087fdc4c6ff95ca2781c1ea6d718/src/SettingsTab.ts#L86), [new Notice('Floating Menu Disabled.');](https://github.com/MichelNivard/Ridian/blob/fa8bee5b9a29087fdc4c6ff95ca2781c1ea6d718/src/SettingsTab.ts#L89)
Please don't show notices here, especially when changing the settings that are text, since that will just keep spamming notices.

**Comment by joethei** [comment]
All you need to do is wait.
If the bot has not changed the labels in the next 24 hours, leave another comment here so I can check on it's status.

**Comment by MichelNivard** [comment]
Hm, i dont think the bot picked this up labels weren't changed (or I am inpatient, in which case I am sorry)

**Comment by joethei** [comment]
You missed this one: https://github.com/MichelNivard/Ridian/blob/fa8bee5b9a29087fdc4c6ff95ca2781c1ea6d718/src/RCodeEvaluator.ts#L217

**Pull request merged**
