### PR TITLE
Add plugin: Open Sidebar on Hover

### PR DESCRIPTION
**Pull request by AnAngryRaven**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/AnAngryRaven/obsidian-open-sidebar-on-hover

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by liamcain** [comment]
Hi @AnAngryRaven just wanted to check in and see if you saw the comments made by our automated review system. I took a peak and everything else looks okay, so just changing the `var`s to `let` should be enough and I'll merge this.

**Comment by AnAngryRaven** [comment]
@liamcain Ah, apologies!! I did indeed, though I see why I had given myself a few days (then subsequently forgot.. 😞) to think things over.

The `delayTime` variable should be easily changed, and I'll be sure to do that. The trickier one is the `isHovering` variable, as I guess I'm essentially inducing a race condition. From what I remember, certain areas of the leftSplit (the title bar surrounding the files, search, and bookmark buttons) aren't actually considered part of the overall document, meaning things like `mouseleave` don't work as expected. So this was the solution I came up to get around that.

From my understanding of `let`, it wouldn't really be possible to use anything other than `var`, as the variable needs to be accessed throughout different scopes. Though I wouldn't be surprised if there's a different way to do it that I just haven't seen yet, so I'll still see what I can do 🙂‍↕️

It has just occurred to me that this probably isn't actually intended behaviour to begin with though, so perhaps a bug report would be more appropriate...

**Comment by liamcain** [comment]
For `isHovering`, it looks like you can just change `var` to `let`. It should work exactly as expected.

**Comment by AnAngryRaven** [comment]
Ahh, apologies!! Appears as though I misunderstood all of the explanations of how let works.. have now changed them accordingly

**Pull request merged**
