### PR TITLE
Submission: Theme Design Utilities Plugin

### PR DESCRIPTION
**Pull request by chrisgrieser**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/chrisgrieser/obsidian-theme-design-utilities

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/chrisgrieser/obsidian-theme-design-utilities/blob/5bd9d59faf67bd09033c710c5e06dbf6ce873c14/main.ts#L27
This can be better expressed as

```ts
this.app.emulateMobile(!this.app.isMobile);
```

https://github.com/chrisgrieser/obsidian-theme-design-utilities/blob/5bd9d59faf67bd09033c710c5e06dbf6ce873c14/main.ts#L47
Duplicate?

**Comment by chrisgrieser** [comment]
> ```ts
> this.app.emulateMobile(!this.app.isMobile);
> ```
👀 You are totally right.

Both things fixed.

**Comment by lishid** [comment]
You are so quick!

**Comment by chrisgrieser** [comment]
I was just at my computer coding (next plugin 😅) already, so fixing was no problem :) 

Thanks for the Admission!

**Pull request merged**
