### PR TITLE
Adding obsidian-testing-vault plugin to help plugin developers make u…

### PR DESCRIPTION
**Pull request by pedersen**
…seful and safe vaults for testing purposes.

# I am submitting a new Community Plugin

## pedersen/obsidian-testing-vault

Link to my plugin:

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [X]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by pedersen** [comment]
> I would generally recommend moving all code files into a separate `src` folder, that makes it easier to review and maintain.
> 
> [id: 'testing-vault-single-note',](https://github.com/pedersen/obsidian-testing-vault/blob/0295ff43461f936f1b79ec0a903983fe9de57dbf/main.ts#L22) Obsidian will automatically prefix the command id with the plugin id.

Thank you. I've updated this package and made a new release that addresses these comments.

**Comment by liamcain** [comment]
- [await this.app.vault.delete](https://github.com/pedersen/obsidian-testing-vault/blob/fc52e45cc26ffb34e452721b7e6edf165df6914e/src/main.ts#L15) this doesn't do what you're expecting it to. This just maps each file to a promise, but it doesn't actually wait for each promise to resolve before executing the next one. If you're trying to run this in serial, you should use a regular for loop instead of map.
- [getFiles](https://github.com/pedersen/obsidian-testing-vault/blob/fc52e45cc26ffb34e452721b7e6edf165df6914e/src/main.ts#L14) I don't think you want to use getFiles here. If you ever extend this to also create folders, they won't be cleaned up too. You probably want to use getRoot() and iterate over all the top folders children and delete those.

**Comment by pedersen** [comment]
Thank you. I've updated the testing vault to remove async/await, as well as making the destroyVault method recursive.

**Comment by pedersen** [comment]
Thank you. I have removed `obsidian-` from the plugin id.

**Comment by pedersen** [comment]
I've just published a new version using the fixed id. Will close and reopen to see if validation will now pass.

**Pull request merged**
