### PR TITLE
Add plugin: Sets

### PR DESCRIPTION
**Pull request by Canna71**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Canna71/obsidian-sets

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Bluemoondragon07** [comment]
Wow, this plugin looks amazing! I've always dreamed of an Anytype-based plugin; thank you for making it come true!

**Comment by joethei** [comment]
[this.app.workspace.on(](https://github.com/Canna71/obsidian-sets/blob/3da76661137fdd5996c6c6bb90dcb76e78838e06/src/main.tsx#L73-L82)
Events need to be registered, so they can be properly unloaded when the plugin is disabled, or alternatively use the `.off´ function in `onunload` <https://docs.obsidian.md/Plugins/Events>

[id: "sets-open-sidebar",](https://github.com/Canna71/obsidian-sets/blob/3da76661137fdd5996c6c6bb90dcb76e78838e06/src/main.tsx#L125) [id: "sets-new-type",](https://github.com/Canna71/obsidian-sets/blob/3da76661137fdd5996c6c6bb90dcb76e78838e06/src/main.tsx#L133), and more
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

[name: "Open Sets Sidebar",](https://github.com/Canna71/obsidian-sets/blob/3da76661137fdd5996c6c6bb90dcb76e78838e06/src/main.tsx#L126), [name: "Create New Type",](https://github.com/Canna71/obsidian-sets/blob/3da76661137fdd5996c6c6bb90dcb76e78838e06/src/main.tsx#L134) and many more
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[this.app.workspace.detachLeavesOfType(SETS_VIEW);](https://github.com/Canna71/obsidian-sets/blob/3da76661137fdd5996c6c6bb90dcb76e78838e06/src/main.tsx#L247)
Do not detach leaves with your custom view in `onunload`, this is an antipattern, see: <https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Don't+detach+leaves+in+%60onunload%60>

[this.app.workspace.detachLeavesOfType(SETS_VIEW);](https://github.com/Canna71/obsidian-sets/blob/3da76661137fdd5996c6c6bb90dcb76e78838e06/src/main.tsx#L276)
Also don't detach here, instead, check if there is already a leaf, and either do nothing, or focus on it, depending on where this is called from.

[obsidian-ex.d.ts](https://github.com/Canna71/obsidian-sets/blob/3da76661137fdd5996c6c6bb90dcb76e78838e06/src/obsidian-ex.d.ts)
Please credit the source of this file.

[addRibbonIcon: boolean;](https://github.com/Canna71/obsidian-sets/blob/3da76661137fdd5996c6c6bb90dcb76e78838e06/src/Settings.ts#L17)
As of v1.1.0 of Obsidian, the ribbon can be customized within Obsidian. So users can choose what items to include and in what order all in one place. Because of this, we're recommending that new plugins avoid introducing their own toggles for ribbon items.

[app.workspace.getActiveViewOfType(MarkdownView);](https://github.com/Canna71/obsidian-sets/blob/3da76661137fdd5996c6c6bb90dcb76e78838e06/src/Utils/saveDataIntoBlock.ts#L10)
It's highly discouraged that you use the global app instance in your plugin. It's currently accessible from the global context for debugging purposes, and might be removed in the future. Instead, you should use the reference to App that you have from your plugin instance.

**Comment by Canna71** [comment]
Thanks a lot for your validation and hard work, most of all because I could have avoided most of that in the first place.
I guess I fixed that now...

**Comment by liamcain** [comment]
- [this.app.workspace.off](https://github.com/Canna71/obsidian-sets/blob/cd9baed210d44061beeb8adec71dc500ec706c92/src/main.tsx#L242) you already registered the event handlers with the plugin, which means they will be removed automatically when the plugin is disabled. You can remove these .off() calls.
- [patchView](https://github.com/Canna71/obsidian-sets/blob/cd9baed210d44061beeb8adec71dc500ec706c92/src/main.tsx#L89) this looks unused. Also I'm not sure what it does, is it copied from another plugin?
- [app.vault.adapter.files](https://github.com/Canna71/obsidian-sets/blob/cd9baed210d44061beeb8adec71dc500ec706c92/src/Utils/getFolders.ts#L5) [`getAllLoadedFiles`](https://github.com/obsidianmd/obsidian-api/blob/902badd38ba907689f0917d7b193f7e33d1284fe/obsidian.d.ts#L3684) and loop through with instanceof TFolder

**Pull request merged**
