### PR TITLE
Add plugin: PDF2Image

### PR DESCRIPTION
**Pull request by RasmusAChr**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/rasmusachr/pdf2images

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by RasmusAChr** [comment]
Changes have been made to the latest release to accomodate the required changes made by ObsidianReviewBot.

**Review by RasmusAChr — COMMENTED** [review]
Moved my plugin to the bottom after file was updated with new plugins.

**Comment by RasmusAChr** [comment]
@joethei, can you help here?

**Review by RasmusAChr — COMMENTED** [review]
Fixed json

**Comment by joethei** [comment]
[PDFWORKER = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.9.359/pdf.worker.min.js';](https://github.com/RasmusAChr/PDF2Images/blob/702317379c1694279ccc75e90318f8fe358d2c69/main.ts#L29)
Normally should be embedded in the plugin, not loaded externally.
In this case, you can use [loadPdfJs](https://docs.obsidian.md/Reference/TypeScript+API/loadPdfJs) to get access to the PDF.js instance that Obsidian is using.

[name: 'Convert PDF to Images',](https://github.com/RasmusAChr/PDF2Images/blob/702317379c1694279ccc75e90318f8fe358d2c69/main.ts#L42), [Convert PDF to Images'](https://github.com/RasmusAChr/PDF2Images/blob/702317379c1694279ccc75e90318f8fe358d2c69/main.ts#L74), [.setName('Image Quality')](https://github.com/RasmusAChr/PDF2Images/blob/702317379c1694279ccc75e90318f8fe358d2c69/main.ts#L333), [.setName('Image Insertion Method')](https://github.com/RasmusAChr/PDF2Images/blob/702317379c1694279ccc75e90318f8fe358d2c69/main.ts#L349), [.setName('Header Size')](https://github.com/RasmusAChr/PDF2Images/blob/702317379c1694279ccc75e90318f8fe358d2c69/main.ts#L376), [.setName('Header Extraction Sensitivity')](https://github.com/RasmusAChr/PDF2Images/blob/702317379c1694279ccc75e90318f8fe358d2c69/main.ts#L393), [.setName('Empty Line after image')](https://github.com/RasmusAChr/PDF2Images/blob/702317379c1694279ccc75e90318f8fe358d2c69/main.ts#L409), [.setName('Attachment Folder Path')](https://github.com/RasmusAChr/PDF2Images/blob/702317379c1694279ccc75e90318f8fe358d2c69/main.ts#L431)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[callback: () => {](https://github.com/RasmusAChr/PDF2Images/blob/702317379c1694279ccc75e90318f8fe358d2c69/main.ts#L43)
This should be a [conditional command](https://docs.obsidian.md/Plugins/User+interface/Commands#Conditional+commands)

[enableRibbonButton: boolean;](https://github.com/RasmusAChr/PDF2Images/blob/702317379c1694279ccc75e90318f8fe358d2c69/main.ts#L8), [if (this.settings.enableRibbonButton) {](https://github.com/RasmusAChr/PDF2Images/blob/702317379c1694279ccc75e90318f8fe358d2c69/main.ts#L72), [// Enable Ribbon button setting](https://github.com/RasmusAChr/PDF2Images/blob/702317379c1694279ccc75e90318f8fe358d2c69/main.ts#L418-L428)
As of v1.1.0 of Obsidian, the ribbon can be customized within Obsidian. So users can choose what items to include and in what order all in one place. Because of this, we're recommending that new plugins avoid introducing their own toggles for ribbon items.

[this.app.fileManager.getNewFileParent('').path](https://github.com/RasmusAChr/PDF2Images/blob/702317379c1694279ccc75e90318f8fe358d2c69/main.ts#L101)
Use [getAvailablePathForAttachment](https://docs.obsidian.md/Reference/TypeScript+API/FileManager/getAvailablePathForAttachment) instead.

[.addText(text => {](https://github.com/RasmusAChr/PDF2Images/blob/702317379c1694279ccc75e90318f8fe358d2c69/main.ts#L433-L462)
This should be using a `AbstractInputSuggest` and the `addSearch` function. instead of a separate modal.

**Comment by RasmusAChr** [comment]
Thanks @joethei for your time and review. I have released a new version based on the requested changes. Here is the updated plugin: https://github.com/RasmusAChr/PDF2Images/compare/1.2.4...1.2.5

**Comment by joethei** [comment]
[name: 'Convert pdf to images',](https://github.com/RasmusAChr/PDF2Images/blob/eca536f1dc91e4dfa8e64b0979faed6efb803497/main.ts#L41)
PDF is a name and is capitalized as "PDF"

**Comment by RasmusAChr** [comment]
Sorry for the oversight @joethei. The requested change has been published with the new version: https://github.com/RasmusAChr/PDF2Images/compare/1.2.5...1.2.6

**Pull request merged**
