### PR TITLE
Add plugin: Markpilot

### PR DESCRIPTION
**Pull request by taichimaeda**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/taichimaeda/markpilot

## Release Checklist

- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS (I only have macOS...)
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by taichimaeda** [comment]
Hi, I've updated the tag name of my release from `v1.0.2` to `1.0.2` - how could I run the check again?

**Comment by taichimaeda** [comment]
I've made changes requested by the bot and resolved conflicts in `community-plugins.json`. 

Looking forward to hearing from Obsidian team!

**Comment by joethei** [comment]
[checkCallback: (checking: boolean) => {](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/main.ts#L48-L51), [checkCallback: (checking: boolean) => {](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/main.ts#L61-L64), [checkCallback: (checking: boolean) => {](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/main.ts#L74-L77), [checkCallback: (checking: boolean) => {](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/main.ts#L88-L91), [checkCallback: (checking: boolean) => {](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/main.ts#L102-L105), [checkCallback: (checking: boolean) => {](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/main.ts#L119-L122), [checkCallback: (checking: boolean) => {](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/main.ts#L132-L135)
It makes no sense for these to be `checkCallback`s, then can just be regular callbacks instead.

[async deactivateView() {](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/main.ts#L169-L176)
Do not detach leaves with your custom view here, this is an antipattern, see: <https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Don't+detach+leaves+in+%60onunload%60>
Instead, only create a new leaf, if there is not one already.

[containerEl.createEl('h2', { text: 'OpenAI' });](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/settings.ts#L91), [containerEl.createEl('h2', { text: 'Inline completions' });](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/settings.ts#L103), [containerEl.createEl('h2', { text: 'Chat view' });](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/settings.ts#L229), [containerEl.createEl('h2', { text: 'Cache' });](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/settings.ts#L293), [containerEl.createEl('h2', { text: 'Usage' });](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/settings.ts#L308)
For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```

[.setName('Monthly Limit')](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/settings.ts#L311), [.setName('Monthly Costs')](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/settings.ts#L329)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[export function sleep(duration: number): Promise<void> {](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/utils.ts#L2-L4)
This is already a function Obsidian exports.

[css={css`](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/chat/components/ChatItem.tsx#L11-L23), [css={css`](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/chat/components/ChatItem.tsx#L34-L65), [css={css`](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/chat/components/ChatItem.tsx#L70-L86)
You should avoid assigning styles via JavaScript or in HTML and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets.
You should also make use of the CSS variables Obsidian provides to make the plugin look good across many different themes.
https://docs.obsidian.md/Reference/CSS+variables/CSS+variables

**Comment by taichimaeda** [comment]
Thanks for the review! Here's the changes made requested:

---

> [checkCallback: (checking: boolean) => {](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/main.ts#L48-L51), [checkCallback: (checking: boolean) => {](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/main.ts#L61-L64), [checkCallback: (checking: boolean) => {](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/main.ts#L74-L77), [checkCallback: (checking: boolean) => {](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/main.ts#L88-L91), [checkCallback: (checking: boolean) => {](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/main.ts#L102-L105), [checkCallback: (checking: boolean) => {](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/main.ts#L119-L122), [checkCallback: (checking: boolean) => {](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/main.ts#L132-L135)
It makes no sense for these to be checkCallbacks, then can just be regular callbacks instead.

[callback: () =>{](https://github.com/taichimaeda/markpilot/blob/f96dd51e0b1e938897f02704d4e593d3ea8bcd6a/src/main.ts#L49C5-L117C8)
Changed to `callback`, not `checkCallback`.

> [async deactivateView() {](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/main.ts#L169-L176)
Do not detach leaves with your custom view here, this is an antipattern, see: https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Don't+detach+leaves+in+%60onunload%60
Instead, only create a new leaf, if there is not one already.

[this.addCommand({](https://github.com/taichimaeda/markpilot/blob/f96dd51e0b1e938897f02704d4e593d3ea8bcd6a/src/main.ts#L87C5-L99C8)

"Clear chat history" command no longer reloads view by detaching/attaching again, instead it now calls a hook exposed by the `App` component.

"Disable chat view" commands still calls `deactivateView()`, but in my opinion this is the expected behaviour.

> [containerEl.createEl('h2', { text: 'OpenAI' });](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/settings.ts#L91), [containerEl.createEl('h2', { text: 'Inline completions' });](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/settings.ts#L103), [containerEl.createEl('h2', { text: 'Chat view' });](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/settings.ts#L229), [containerEl.createEl('h2', { text: 'Cache' });](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/settings.ts#L293), [containerEl.createEl('h2', { text: 'Usage' });](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/settings.ts#L308)
For section headings in settings use:

[new Setting(containerEl).setName('OpenAI').setHeading();](https://github.com/taichimaeda/markpilot/blob/f96dd51e0b1e938897f02704d4e593d3ea8bcd6a/src/settings.ts#L91C5-L92C1)
[new Setting(containerEl).setName('Inline completions').setHeading();](https://github.com/taichimaeda/markpilot/blob/f96dd51e0b1e938897f02704d4e593d3ea8bcd6a/src/settings.ts#L103C4-L103C73)
[new Setting(containerEl).setName('Chat view').setHeading();](https://github.com/taichimaeda/markpilot/blob/f96dd51e0b1e938897f02704d4e593d3ea8bcd6a/src/settings.ts#L229C5-L229C64)
[new Setting(containerEl).setName('Cache').setHeading();](https://github.com/taichimaeda/markpilot/blob/f96dd51e0b1e938897f02704d4e593d3ea8bcd6a/src/settings.ts#L293C4-L293C60)
[new Setting(containerEl).setName('Usage').setHeading();](https://github.com/taichimaeda/markpilot/blob/f96dd51e0b1e938897f02704d4e593d3ea8bcd6a/src/settings.ts#L308C5-L309C1)

Changed to `new Setting(containerEl).setName('name here').setHeading();`.

> [.setName('Monthly Limit')](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/settings.ts#L311), [.setName('Monthly Costs')](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/settings.ts#L329)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[new Setting(containerEl).setName('Monthly limit')](https://github.com/taichimaeda/markpilot/blob/f96dd51e0b1e938897f02704d4e593d3ea8bcd6a/src/settings.ts#L310C5-L333C1)

Changed to sentence cases as requested.

> [export function sleep(duration: number): Promise {](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/utils.ts#L2-L4)
This is already a function Obsidian exports.

[utils.ts](https://github.com/taichimaeda/markpilot/blob/f96dd51e0b1e938897f02704d4e593d3ea8bcd6a/src/utils.ts#L1)

I noticed this function is no longer used in the latest version so removed it.

> [css={css](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/chat/components/ChatItem.tsx#L11-L23), [css={css](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/chat/components/ChatItem.tsx#L34-L65), [css={css`](https://github.com/taichimaeda/markpilot/blob/55d6ba439fc17d6151849f2f6f023936b4d86ebb/src/chat/components/ChatItem.tsx#L70-L86)
You should avoid assigning styles via JavaScript or in HTML and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets.
You should also make use of the CSS variables Obsidian provides to make the plugin look good across many different themes.
https://docs.obsidian.md/Reference/CSS+variables/CSS+variables

[styles.css](https://github.com/taichimaeda/markpilot/blob/f96dd51e0b1e938897f02704d4e593d3ea8bcd6a/styles.css#L1)

Moved all CSS-in-JS to `styles.css` - apart from these two lines:

[style={{ height: `${numRows + 1.5}rem` }}](https://github.com/taichimaeda/markpilot/blob/f96dd51e0b1e938897f02704d4e593d3ea8bcd6a/src/chat/components/ChatBox.tsx#L20C9-L20C50)
[style={{ height: `${numRows + 1.5}rem` }}](https://github.com/taichimaeda/markpilot/blob/f96dd51e0b1e938897f02704d4e593d3ea8bcd6a/src/chat/components/ChatBox.tsx#L40)

which I think are best to keep in JS because it's tricky to sync the `textarea`'s height and send button's position in sync with pure CSS.

---

Hope this looks ok

**Pull request merged**
