### PR TITLE
Add entry for plugin "Execute Code".

### PR DESCRIPTION
**Pull request by twibiral**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/twibiral/obsidian-execute-code

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/twibiral/obsidian-execute-code/blob/e63d36875267ea56cb7dd6a30496ccb4f4859f40/main.ts#L34
This is not a great way to achieve this functionality. You should instead use `registerMarkdownPostProcessor.

https://github.com/twibiral/obsidian-execute-code/blob/e63d36875267ea56cb7dd6a30496ccb4f4859f40/main.ts#L113
I suggest using `original-fs` instead of `fs` here (because of Electron) and also using `fs.promises` instead of dealing with callbacks.

https://github.com/twibiral/obsidian-execute-code/blob/e63d36875267ea56cb7dd6a30496ccb4f4859f40/main.ts#L237
See this tip: https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#avoid-innerhtml-outerhtml-and-insertadjacenthtml

**Comment by lishid** [comment]
https://github.com/reorx/obsidian-paste-image-rename/blob/b60f2d7cded3b8f1fab9e05c37bc43147af2dc43/src/main.ts#L122
You might also want to check if the user is using markdown links instead of wikilinks.

https://github.com/reorx/obsidian-paste-image-rename/blob/b60f2d7cded3b8f1fab9e05c37bc43147af2dc43/src/main.ts#L184
Input variables needs to be sanitized here.

https://github.com/reorx/obsidian-paste-image-rename/blob/b60f2d7cded3b8f1fab9e05c37bc43147af2dc43/src/main.ts#L168
You can get a lot of the properties you're using `path` for from the file: file.basename, file.extension, file.parent.path. If you absolutely need to use `path` from nodejs then you must mark your plugin as desktop only in your manifest.json file because it won't work on mobile.

https://github.com/reorx/obsidian-paste-image-rename/blob/b60f2d7cded3b8f1fab9e05c37bc43147af2dc43/src/main.ts#L142
This has a memory leak here where you keep the reference of all the modals that has ever existed, even after they were closed.

**Comment by twibiral** [comment]
> https://github.com/twibiral/obsidian-execute-code/blob/e63d36875267ea56cb7dd6a30496ccb4f4859f40/main.ts#L34 This is not a great way to achieve this functionality. You should instead use `registerMarkdownPostProcessor.
> 
> https://github.com/twibiral/obsidian-execute-code/blob/e63d36875267ea56cb7dd6a30496ccb4f4859f40/main.ts#L113 I suggest using `original-fs` instead of `fs` here (because of Electron) and also using `fs.promises` instead of dealing with callbacks.
> 
> https://github.com/twibiral/obsidian-execute-code/blob/e63d36875267ea56cb7dd6a30496ccb4f4859f40/main.ts#L237 See this tip: https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#avoid-innerhtml-outerhtml-and-insertadjacenthtml

@lishid thanks for the suggestions, I appreciate them! All except the last one were implemented in [release 0.3.1](https://github.com/twibiral/obsidian-execute-code/releases/tag/v0.3.1).

**Comment by lishid** [comment]
Sounds good, let me know when you complete the innerHTML change and we can have it merged.

**Comment by twibiral** [comment]
@lishid I completed it.

**Pull request merged**
