### PR TITLE
Add JichouP/obsidian-marp-plugin

### PR DESCRIPTION
**Pull request by JichouP**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: <https://github.com/JichouP/obsidian-marp-plugin>

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[id: 'marp-open-preview',](https://github.com/JichouP/obsidian-marp-plugin/blob/2ab9fe3e813445e488350da9b28feb2dd701ccd0/src/main.ts#L33)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

**Comment by liamcain** [comment]
- [FileState](https://github.com/JichouP/obsidian-marp-plugin/blob/2ab9fe3e813445e488350da9b28feb2dd701ccd0/src/fileState.ts#L3) instead of making this a global state for the plugin, I suggest you make this a viewState. That will have a lot of benefits:
  - You'll be able to have multiple previews at once
  - The file will get serialized to the layout so reopening Obsidian so the view can be restored with the same state
  - you could make it work like our existing sidebar views. The preview could reflect the currently focused leaf and pinning it would freeze the state to a given file.

**Comment by JichouP** [comment]
@joethei 
I didn't know that.
I removed the prefix in this PR. <https://github.com/JichouP/obsidian-marp-plugin/pull/2>

**Comment by JichouP** [comment]
@liamcain 
Thanks for pointing this out.
The `registerEvent` has been fixed in this PR. <https://github.com/JichouP/obsidian-marp-plugin/pull/4>

However, for the `FileState`, I have no idea how to pass the `viewState` to the `PreviewView`.
Is it possible to pass the `state` in the following way?
And if so, how do I reference it from `PreviewView`?
``js
setViewState(
  {
    type: MARP_PREVIEW_VIEW_TYPE,
    active: true,
    state: {
      file: ...
    }
  }
)
```

Or did you intend to create a property `this.fileState` and a method `this.setFileState` on `PreviewView` to access the state?

**Comment by liamcain** [comment]
So, I was writing up a response to this when I realized there really isn't enough documentation about storing state on the view. So I wrote up a long post about it here: <https://liamca.in/Obsidian/API+FAQ/views/persisting+your+view+state>

Anything you pass into `state` from setViewState will get passed into `setState` on the View.

**Comment by JichouP** [comment]
@liamcain and @joethei 
Thank you very much for your kind attention.
And now that `viewState` works, I have created a new release `1.0.1`!
<https://github.com/JichouP/obsidian-marp-plugin/releases/tag/1.0.1>

I hope you will take a look at it when you are free.

**Comment by liamcain** [comment]
Merging since I think it's fine to go in now, but I left a comment on the latest commit. You shouldn't need to be calling setState yourself.

**Pull request merged**
