### PR TITLE
Add plugin: Ayanite

### PR DESCRIPTION
**Pull request by jemstelos**
# I am submitting a new Community Plugin

I've granted access to the full repository source code, and written up a detailed walkthrough for the Obsidian team reviewers. Please let me know if there's anything else required for the review process.

Link to my plugin: https://github.com/jemstelos/ayanite (placeholder)

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [ ] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by jemstelos** [comment]
/skip these should not be relevant as they are on the sample plugin placeholder.

@joethei please let me know if you have everything you need for the review!

**Comment by joethei** [comment]
You should remove the sample plugin from the public repo, the only files that should be there are: `manifest.json`, and `versions.json`

Also, the release needs to contain your actual plugin release, not the sample plugin.

Your README is missing a lot of information how to use the plugin.

["description": "A powerful AI chat interface for leveraging GPT models in an integrated learning environment",](https://github.com/jemstelos/obsidian-ayanite/blob/4536eace054b9893be51a2f16e999a6e71157bdb/manifest.json#L6)
The description needs to include "(Closed source)"

All other issues have been left in an issue on the repo.

**Comment by jemstelos** [comment]
Hey @joethei! I cleaned up unused code files, updated the README and manifest, and created a new release with plugin release. I also addressed all comments from your issue review. Please let me know if there are any additional actions required!

**Comment by jemstelos** [comment]
Hi @joethei, hoping to bump this up for your review as it's been a while from the initial push! Thank you in advance!

**Comment by jemstelos** [comment]
@joethei apologies for the confusion, I've reopened this original pull request as per your guidance. Thank you again!

**Comment by jemstelos** [comment]
hey @joethei, the code changes from your [review](https://github.com/jemstelos/ayanite/issues/1) have been addressed and are ready to review. thank you!

**Comment by joethei** [comment]
Sorry for the delay!

**Pull request merged**
