### PR TITLE
obsidian-rpg-manager added to community-plugins.json

### PR DESCRIPTION
**Pull request by carlonicora**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/carlonicora/obsidian-rpg-manager

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
While it is allowed, having `obsdian` in the plugin ID is unnecessary.
Also isn't it usually written as RPG and not Rpg ?

You have quite a few instances of `//@ts-ignore` in your code, if you can try to eliminate as many as you can.

Since you use the Dataview API a lot I would add some sort of notification/error message when Dataview is not installed.

[declare module 'obsidian'](https://github.com/carlonicora/obsidian-rpg-manager/blob/285f81a8a6ec2701405ea6563a4530ce9aeac1bd/src/api.ts#L8)
Any reason why this is here and not with the other typing?

**Comment by carlonicora** [comment]
Hi,
I will update the plugin updating the name, checking the ts-ignore and merging the obsidian in the other typings

**Comment by carlonicora** [comment]
Updated the plugin with the following:
- ID Updated to `rpg-manager`
- name updated to `RPG Manager`
- updated minAppVersion to `0.15.9`
- many `//@ts-ignore` have been removed (with the exclusion of Factories

Question (it is my first submission): do I have to create a new pull request with the updated ID?

Carlo

**Comment by joethei** [comment]
no, you don't need to resubmit

**Comment by liamcain** [comment]
- [this](https://github.com/carlonicora/obsidian-rpg-manager/blob/0c25fb5c9d4c19e21ec10d822c68198e34634678/src/main.ts#L43) I think these event subscriptions would be simpler if you `bind(this)` first, then debounce that function. Something like:

```ts
		this.refreshViews = debounce(this.refreshViews.bind(this), 500, true);
		this.registerEvent(this.app.metadataCache.on('resolved', this.refreshViews);
```

- [private initialiseRoots() {](https://github.com/carlonicora/obsidian-rpg-manager/blob/0c25fb5c9d4c19e21ec10d822c68198e34634678/src/api.ts#L23) I think you can just use [`getBasePath`](https://github.com/obsidianmd/obsidian-api/blob/6b2138aa28fb6d6f58f78e6fabec02186fdc0f82/obsidian.d.ts#L1217). Or, if you are just after the full path of the attachmentFolderPath, then use `getFullPath`.
- [attachmentFolderPath](https://github.com/carlonicora/obsidian-rpg-manager/blob/0c25fb5c9d4c19e21ec10d822c68198e34634678/src/api.ts#L58) You should use `getAttachmentPathConfig()` instead since it takes into account the user's "attachment folder" preference.
- [nse = (abstractFile ? true : false);](https://github.com/carlonicora/obsidian-rpg-manager/blob/0c25fb5c9d4c19e21ec10d822c68198e34634678/src/api.ts#L67) This ternary doesn't do anything since abstractFile is always truthy

**Comment by carlonicora** [comment]
Hi @liamcain 
Thanks for the feedback and the changes requested.

Version 0.3.16 updated.

**Changes applied**:
- debounce for subscriptions refactored in main.js
- useless ternary removed
- removed the attachmentFolderPath (was doing the same thing as calling `getAttachmentPathConfig()`

**HOWEVER...**
In terms of the `initialiseRoot`, I am using the function to provide the same functionalities on desktop AND mobile. By using `getBasePath` or `getFullPath`, the path I am getting is not able to display the images with the full path.
If I use a relative path for the images, the images simply don't work as they are prepended by `app://obsidian.md/`.
If I use the full path the images are still not displayed.
In the `initialiseRoot` I read the filename including the filesystem part, which allows Obsidian to read the image directly from the correct path.

The difference is something like this:
## getBasePath
DesktopUri: /Users/XXX/Library/Mobile Documents/iCloud~md~obsidian/Documents/VAULE/ATTACHMENTFOLDER/IMAGE
Image works in src in Desktop: **NO**
MobileUri: EMPTY
Image works in src in Mobile: **NO**

## getFullPath
DesktopUri: /Users/XXX/Library/Mobile Documents/iCloud~md~obsidian/Documents/VAULE/ATTACHMENTFOLDER/IMAGE
Image works in src in Desktop: **NO**
MobileUri: Documents/VAULT/ATTACHMENTFOLDER/IMAGE
Image works in src in Mobile: **NO**

## initialiseRoot
DesktopUri: app://local/Users/XXX/Library/Mobile%20Documents/iCloud~md~obsidian/Documents/VAULT/ATTACHMENTFOLDER/IMAGE
Image works in src in Desktop: **YES**
MobileUri: capacitor://localhost/capacitor_file/private/var/mobile/Library/Mobile%20Documents/iCloud~md~obsidian/Documents/VAULT/ATTACHMENTFOLDER/IMAGE
Image works in src in Mobile: **YES**

Maybe I am missing something, but in my digging in the Obsidian API I didn't manage to find a solution to this. If I am making a mistake somewhere without realising, please do let me know and I will update the code to simplify it.

Ciao
Carlo

**Comment by liamcain** [comment]
Oh, okay. I'll double-check on the initialiseRoot issue. Maybe there's a helper function we can expose to make this easier for plugins. Otherwise, everything else looks good, nice job!

**Pull request merged**
