### PR TITLE
Add plugin: Remotely Secure

### PR DESCRIPTION
**Pull request by sboesen**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/sboesen/remotely-secure

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
  - [x] I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by sboesen** [comment]
Updated to enable github issues on the repo.

**Comment by joethei** [comment]
What sets your plugin apart from the original remotely-save plugin?
Please make that clear in the readme.

[log.info(plan.mixedStates); // for debugging](https://github.com/sboesen/remotely-secure/blob/1d200370f6a3b493abb134945b0593e7619bb062/src/main.ts#L302)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[`${this.app.vault.configDir}/plugins/${this.manifest.dir}`;](https://github.com/sboesen/remotely-secure/blob/1d200370f6a3b493abb134945b0593e7619bb062/src/main.ts#L1020)
This path is wrong, `manifest.dir` already includes the rest.

[import * as path from "path";](https://github.com/sboesen/remotely-secure/blob/1d200370f6a3b493abb134945b0593e7619bb062/src/misc.ts#L2)
This import is only available from a Node.js runtime, which means that this will throw errors on Mobile (that's a problem since you have `isDesktopOnly` marked as `false` in your manifest.json file.

[return window.moment(x).format() as string;](https://github.com/sboesen/remotely-secure/blob/1d200370f6a3b493abb134945b0593e7619bb062/src/misc.ts#L345)
Import `moment` from the Obsidian API instead of taking it from `window`

[await fetch](https://github.com/sboesen/remotely-secure/blob/1d200370f6a3b493abb134945b0593e7619bb062/src/remoteForDropbox.ts#L215)
Use the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

[const rsp2 = JSON.parse(rsp1);](https://github.com/sboesen/remotely-secure/blob/1d200370f6a3b493abb134945b0593e7619bb062/src/remoteForOnedrive.ts#L141)
Use `requestUrl` above, and then you can use `rsp1.json()` instead of this code.

[containerEl.createEl("h1", { text: "Remotely Secure" });](https://github.com/sboesen/remotely-secure/blob/1d200370f6a3b493abb134945b0593e7619bb062/src/settings.ts#L675)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[const { eye, eyeOff } = getEyesElements();](https://github.com/sboesen/remotely-secure/blob/1d200370f6a3b493abb134945b0593e7619bb062/src/settings.ts#L642-L651)
[Avoid using `innerHTML`](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%60innerHTML%60%2C+%60outerHTML%60+and+%60insertAdjacentHTML%60), instead use the `setIcon` function from the Obsidian API, no need to import lucide yourself.

[await mkdirpInVault(r.key, vault); /* should be unnecessary */](https://github.com/sboesen/remotely-secure/blob/1d200370f6a3b493abb134945b0593e7619bb062/src/sync.ts#L1129)
Why is this done if it's unnecessary?

**Comment by sboesen** [comment]
Thank you for the review and feedback! I've updated the [readme](https://github.com/sboesen/remotely-secure#remotely-secure) to call out the differences more clearly and am taking the time to update the plugin to address these issues. Will post another comment once I have an updated PR.

**Comment by sboesen** [comment]
Updated to address your feedback, please let me know if there is any additional feedback. I broke up the commits for each piece of feedback called out. Please see code at [679c1429](https://github.com/sboesen/remotely-secure/commit/679c1429abee8b15460d6bf55ebc99c15874b2a6) for latest version.

**Pull request merged**
