### PR TITLE
Add TTS plugin

### PR DESCRIPTION
**Pull request by joethei**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/joethei/obsidian-tts

## Release Checklist
- [X] I have tested the plugin on
  - [X]  Windows
  - [X]  macOS
  - [X]  Linux
  - [ ]  Android _(if applicable)_
  - [X]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/joethei/obsidian-tts/blob/2b879928d2319118ceed4eabc64b8bf592b0f202/src/main.ts#L22
You can throw an error here and Obsidian should automatically cancel the plugin loading. You're also continuing execution here instead of returning...

https://github.com/joethei/obsidian-tts/blob/2b879928d2319118ceed4eabc64b8bf592b0f202/src/main.ts#L32
Here you'll want to perform this check regardless of the value of `checking`, because there are possible cases where your callback is called when `checking` is false (where you'd pass null to `play`). You should also check for a truthy value rather than `undefined` because it may return `null` instead.

**Comment by joethei** [comment]
Thanks for spotting the first one, have addressed your comments now.
The one thing I am not too happy about is the double negation I had to use here https://github.com/joethei/obsidian-tts/blob/23cc414b8e4707b0bff52ad7babb59a9fad79fdb/src/main.ts#L34, if you know a better way lmk.

**Comment by lishid** [comment]
> The one thing I am not too happy about is the double negation I had to use here https://github.com/joethei/obsidian-tts/blob/23cc414b8e4707b0bff52ad7babb59a9fad79fdb/src/main.ts#L34, if you know a better way lmk.

Double negation works fine (we use it often too) to convert things into booleans. Here specifically you can return true because of the boolean logic two lines above, but I have a suggestion that applies to all of your `checkCallback`s. Specifically, your checkCallbacks should perform the check and also return true/false regardless of the checking variable.

The other commands (Stop playback, pause playback) are also missing the `isSpeaking` check when it's called - I don't know if that's going to be a problem when you call `stop` when it's not speaking.

Try to follow the code flow in the guide my Marcus here: https://marcus.se.net/obsidian-plugin-docs/guides/commands#conditional-commands
Doing it this way makes sure that you are covered in both cases.

```ts
checkCallback(checking: boolean) => {
  if (condition satisfied) {
    if (!checking) {
      // Perform action
    }
    return true;
  }
  // optionally return false
}
```

**Comment by joethei** [comment]
> The other commands (Stop playback, pause playback) are also missing the `isSpeaking` check when it's called - I don't know if that's going to be a problem when you call `stop` when it's not speaking.

There is a check in the service for this when calling the method.

Also, TIL of `editorCallback`, seems to make the play command a lot easier.

Adressed those issues now.

**Comment by lishid** [comment]
> There is a check in the service for this when calling the method.

Yeah I'm guessing it's probably ok regardless. The recommended function would be something like this:

```ts
if (this.ttsService.isSpeaking()) {
    if (!checking) this.ttsService.stop();
    return true;
}
```

**Pull request merged**
