### PR TITLE
Add plugin: ii

### PR DESCRIPTION
**Pull request by wish5115**
I am submitting a new Community Plugin
---

Repo URL
---
Link to my plugin: https://github.com/wish5115/obsidian-ii-quicker

Release Checklist
---

- [x] I have tested the plugin on
    - [x] Windows
    - [x] macOS
    - [ ] Linux
    - [x] Android (if applicable)
    - [x] iOS (if applicable)

- [x] My GitHub release contains all required files
    - [x] main.js
    - [x] manifest.json
    - [x] styles.css (optional)

- [x] GitHub release name matches the exact version number specified in my manifest.json (Note: Use the exact version number, don't include a prefix v)
 - [x] The id in my manifest.json matches the id in the community-plugins.json file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
- [x] I have given proper attribution to these other projects in my README.md.

### CODE REVIEW

**Comment by wish5115** [comment]
> Do NOT open a new PR for re-validation.
Once you have pushed all of the required changes to your repo, the bot will update the labels on this PR within 6 hours.
If you think some of the required changes are incorrect, please comment with /skip and the reason why you think the results are incorrect.

Thanks for your comments and guidance, I will change it carefully. So should I now go ahead and submit on this current pr, or should I do it on the first one?

Also, I'm wondering why I can't get to this page by clicking on the Community Plugin link?

**Comment by joethei** [comment]
Please follow the pull request template

**Comment by wish5115** [comment]
> Please follow the pull request template

Thank you for your reply!

I didn't understand exactly what that meant, I did follow the official tutorial step by step to submit and I'm not sure what my problem is? Can you help point out exactly why? For example, where is the request template not being followed?

**Comment by wish5115** [comment]
> Please follow the pull request template

I'm guessing you might be referring to what's in the Release Checklist, indeed I've seen others submit with that. But how do I access this Release Checklist? Where is the entry point? I can't get to it by clicking on the Community Plugin link above, I don't know why? Even after changing browsers? Am I doing something wrong? Can you tell me?

**Comment by wish5115** [comment]
> Please follow the pull request template

**Is it that I have to return this submission to draft and then resubmit it with the following?**


I am submitting a new Community Plugin
Repo URL
Link to my plugin: https://github.com/wish5115/obsidian-ii-quicker

Release Checklist
 I have tested the plugin on

 Windows
 macOS
 Linux
 Android (if applicable)
 iOS (if applicable)
 My GitHub release contains all required files

 main.js
 manifest.json
 styles.css (optional)
 GitHub release name matches the exact version number specified in my manifest.json (Note: Use the exact version number, don't include a prefix v)

 The id in my manifest.json matches the id in the community-plugins.json file.

 My README.md describes the plugin's purpose and provides clear usage instructions.

 I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.

 I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.

 I have added a license in the LICENSE file.

 My project respects and is compatible with the original license of any code from other plugins that I'm using.

 I have given proper attribution to these other projects in my README.md.

**Comment by wish5115** [comment]
> Please follow the pull request template

I've changed the submission template in this submission

**Comment by wish5115** [comment]
> Please follow the pull request template

I've changed the submission template in this submission

**Comment by joethei** [comment]
Your plugin does too many things at once, inserting stuff has no relationship to zen mode, and inserting CSS and JS snippets is not related to either.
It should be split up 
There are plugins/core features for each of those, so I don't really see a reason to accept this.

**Comment by wish5115** [comment]
/skip

This has been unresponsive and, have to keep resolving conflicts, can I close and resubmit?

image

**Comment by joethei** [comment]
We handle the conflicts once the plugin is ready to be merged, you don't need to keep fixing them.

Could you please explain what sets your plugin apart from the core features/other community plugins?
I can see that you removed some of the features I mentioned above, but I still see significant overlap with core features/other community plugins.

**Comment by wish5115** [comment]
> We handle the conflicts once the plugin is ready to be merged, you don't need to keep fixing them.
> 
> Could you please explain what sets your plugin apart from the core features/other community plugins? I can see that you removed some of the features I mentioned above, but I still see significant overlap with core features/other community plugins.

Thanks for the reply! 

This plugin features the following:

1. The /ii command allows you to group commonly used insertion commands together for easy viewing and selection.

2. This plugin more than some other plugins does not have Markdown code, such as audio and video insertion, embedded web pages, anchor points, superscripts, subscripts, left-centre-right alignment, variables, footnotes, HTML comments, etc.

3. **And the main thing is that it can customize their insertion commands, which makes it easy for users to expand the insertion of some personalized text**.

**Comment by joethei** [comment]
["minAppVersion": "0.15.0",](https://github.com/wish5115/obsidian-ii-quicker/blob/23c6e2c209aa1bdd1f00a8bb6ac7cff204eded31/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

["description": "The main feature of this plugin is to quickly insert common Markdown code and HTML code. And you can customize your own insertion commands.",](https://github.com/wish5115/obsidian-ii-quicker/blob/23c6e2c209aa1bdd1f00a8bb6ac7cff204eded31/manifest.json#L6)
Avoid including sentences like "This is a plugin that does ..." in your description, it should be self-evident that this is a plugin.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

["authorUrl": "https://forum.obsidian.md/u/wilsons/",](https://github.com/wish5115/obsidian-ii-quicker/blob/23c6e2c209aa1bdd1f00a8bb6ac7cff204eded31/manifest.json#L8)
This should be the link to your GitHub profile.

["fundingUrl": "",](https://github.com/wish5115/obsidian-ii-quicker/blob/23c6e2c209aa1bdd1f00a8bb6ac7cff204eded31/manifest.json#L9)
Remove this line if you don't have one.

["Quick insert markdown code":"Quickly insert Markdown code",](https://github.com/wish5115/obsidian-ii-quicker/blob/23c6e2c209aa1bdd1f00a8bb6ac7cff204eded31/src/lang/locale/en.ts#L41-L89)
There are still a bunch of strings left over that should be removed.

["Show color picker modal":"Show Color Selector",](https://github.com/wish5115/obsidian-ii-quicker/blob/23c6e2c209aa1bdd1f00a8bb6ac7cff204eded31/src/lang/locale/en.ts#L57), ["Common color codes":"Common Color Codes",](https://github.com/wish5115/obsidian-ii-quicker/blob/23c6e2c209aa1bdd1f00a8bb6ac7cff204eded31/src/lang/locale/en.ts#L59), ["Date format":"Date Formatting",](https://github.com/wish5115/obsidian-ii-quicker/blob/23c6e2c209aa1bdd1f00a8bb6ac7cff204eded31/src/lang/locale/en.ts#L73), ["Time format":"Time Formatting",](https://github.com/wish5115/obsidian-ii-quicker/blob/23c6e2c209aa1bdd1f00a8bb6ac7cff204eded31/src/lang/locale/en.ts#L75) and more
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by wish5115** [comment]
/skip

It's all been modified as you requested.

The rest of the language fields are now useful.

**Pull request merged**
