### PR TITLE
Add plugin: Adjacency Matrix Exporter

### PR DESCRIPTION
**Pull request by danielegrazzini**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Please remove the `main.js` file from the repo and add it to your .gitignore - compiled release files shouldn't get mixed with source code in your commits and should go to the releases files instead.

[Copyright (c) 2021 SkepticMystic](https://github.com/danielegrazzini/adjacency-matrix-exporter/blob/8c77f64557f7d3b98b493112458b43c4a2c658ed/LICENSE#L3)
Update this.

[console.log(data);](https://github.com/danielegrazzini/adjacency-matrix-exporter/blob/8c77f64557f7d3b98b493112458b43c4a2c658ed/main.ts#L294)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

**Comment by danielegrazzini** [comment]
I removed the main.js file from the repository and added it to .gitignore

I updated the MIT license

In this specific case the check I do on the console is necessary to highlight errors before they are exported to the CSV file

**Comment by danielegrazzini** [comment]
Hi Johannes,
I wanted to ask you how the changes to the code that I think should be made in the future will work once the validation procedure is finished. Can I make changes to the current version and the system will automatically absorb them?
If I make a new release with added features or added additional code, will I have to make a pull request again?

Thanks for your clarifications

Best Reguards

Daniele

**Comment by joethei** [comment]
Just create a new release with the changes.
You don't need to create a new PR for any future updates.

**Comment by danielegrazzini** [comment]
Now do I have to do anything else to continue validating the plugin? or should I wait?

**Comment by joethei** [comment]
Just wait for the second review.

**Comment by danielegrazzini** [comment]
is the second revision not done by you?

**Comment by joethei** [comment]
nope

**Comment by danielegrazzini** [comment]
ok! Thanks for your informations! Have a good evening!

**Comment by danielegrazzini** [comment]
Johannes can you help me to move on the second review?
no one has come forward yet.....

**Comment by joethei** [comment]
Please have patience, I can't give any ETAs on when the second review will happen, as it depends heavily on the workload of the team.

**Comment by liamcain** [comment]
> I removed the main.js file from the repository and added it to .gitignore

Did you forget to push these changes?

> I updated the MIT license

I am not seeing this updated anywhere

**Comment by liamcain** [comment]
- [innerHTML](https://github.com/danielegrazzini/adjacency-matrix-exporter/blob/8c77f64557f7d3b98b493112458b43c4a2c658ed/main.ts#L327) Do not use innerHTML here. [innerHTML is a potential security risk](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#avoid-innerhtml-outerhtml-and-insertadjacenthtml). setText or innerText will work just fine.

**Comment by danielegrazzini** [comment]
Hi Liam sorry but I'm not very expert on github. can you help me? What do I need to do to push the changes I've made

**Comment by danielegrazzini** [comment]
I replaced innerText with innerHTML. Can you see this update?

**Comment by danielegrazzini** [comment]
I'll send you an image of actions that i made. I hope it is useful
changes

**Comment by danielegrazzini** [comment]
I tried to insert the changes. I don't know if I did as well as I told you, I'm seeing github for the first time....

**Comment by danielegrazzini** [comment]
Liam I'll send you the link where you find the right changes:
I don't know what else to do....
https://github.com/danielegrazzini/adjacency-matrix-exporter/tree/main

**Comment by liamcain** [comment]
Merged. Thank you for updating and for your patience while we get through all the reviews.

**Pull request merged**
