### PR TITLE
Add Indentation Lines Plugin for lists

### PR DESCRIPTION
**Pull request by Arch-Storm**
# [x] I am submitting a new Community Plugin

## Repo URL

[Arch-Storm/obsidian-indent-lines](https://github.com/Arch-Storm/obsidian-indent-lines)

## Release Checklist

- [x] I have tested this on Windows, macOS, and Linux _(if applicable)_
- [x] Github release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] Github release name matches the exact version number specified in your manifest.json
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.

### CODE REVIEW

**Comment by ericaxu** [comment]
Is the `main.js` compiled from `main.ts` somewhere? It would be much easier to review the source instead the compiled file.

Thanks!

**Comment by Arch-Storm** [comment]
Sry for that! It should be in the repo now. I've also optimized the code a lot!

**Comment by ericaxu** [comment]
https://github.com/Arch-Storm/obsidian-indent-lines/blob/main/main.ts#L5
Looks like the command doesn't do anything, I think you can just delete this part if you rely on `styles.css` to do most of the work.

Otherwise looks good!

**Comment by Arch-Storm** [comment]
Never worked with TS nor the api before, so thanks for helping!
Everything should be finished for the first release now.

**Comment by ericaxu** [comment]
Thanks for resolving it! I'm not sure if the `main.js` is mandatory if you just want to apply the CSS, I'll let @lishid review it.

Thanks again!

**Comment by lishid** [comment]
You should add main.js to your .gitignore and remove it from the repo - it's only needed in the GitHub releases.

**Pull request merged**
