### PR TITLE
Add plugin: Import Attachments+

### PR DESCRIPTION
**Pull request by alberti42**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/alberti42/obsidian-import-attachments-plus

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[name: "Move File to Vault as Link",](https://github.com/alberti42/obsidian-import-attachments-plus/blob/e0b95ff3b0d3a5b63d9b977ccea23679bd1cfe3b/src/main.ts#L182), [name: "Move File to Vault as Embedded",](https://github.com/alberti42/obsidian-import-attachments-plus/blob/e0b95ff3b0d3a5b63d9b977ccea23679bd1cfe3b/src/main.ts#L192), [name: "Copy File to Vault as Link",](https://github.com/alberti42/obsidian-import-attachments-plus/blob/e0b95ff3b0d3a5b63d9b977ccea23679bd1cfe3b/src/main.ts#L202), [name: "Copy File to Vault as Embedded",](https://github.com/alberti42/obsidian-import-attachments-plus/blob/e0b95ff3b0d3a5b63d9b977ccea23679bd1cfe3b/src/main.ts#L212), [name: "Open Attachments Folder",](https://github.com/alberti42/obsidian-import-attachments-plus/blob/e0b95ff3b0d3a5b63d9b977ccea23679bd1cfe3b/src/main.ts#L222), [container.createEl('h2', { text: 'Import Files' });](https://github.com/alberti42/obsidian-import-attachments-plus/blob/e0b95ff3b0d3a5b63d9b977ccea23679bd1cfe3b/src/ImportAttachmentsModal.ts#L80), [container.createEl('h2', { text: 'Import Files' });](https://github.com/alberti42/obsidian-import-attachments-plus/blob/e0b95ff3b0d3a5b63d9b977ccea23679bd1cfe3b/src/ImportAttachmentsModal.ts#L203), [container.createEl('h2', { text: 'Import Files' });](https://github.com/alberti42/obsidian-import-attachments-plus/blob/e0b95ff3b0d3a5b63d9b977ccea23679bd1cfe3b/src/ImportAttachmentsModal.ts#L297), [container.createEl('h2', { text: 'Import Files' });](https://github.com/alberti42/obsidian-import-attachments-plus/blob/e0b95ff3b0d3a5b63d9b977ccea23679bd1cfe3b/src/ImportAttachmentsModal.ts#L366)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[containerEl.createEl('h2', { text: 'Settings for Import Attachments+ Plugin' });](https://github.com/alberti42/obsidian-import-attachments-plus/blob/e0b95ff3b0d3a5b63d9b977ccea23679bd1cfe3b/src/main.ts#L824)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[containerEl.createEl('h3', { text: 'Import options' });](https://github.com/alberti42/obsidian-import-attachments-plus/blob/e0b95ff3b0d3a5b63d9b977ccea23679bd1cfe3b/src/main.ts#L826), [containerEl.createEl('h3', { text: 'Attachment folder configuration' });](https://github.com/alberti42/obsidian-import-attachments-plus/blob/e0b95ff3b0d3a5b63d9b977ccea23679bd1cfe3b/src/main.ts#L915)
[Avoid "options" & "configuration" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

[containerEl.createEl('h3', { text: 'Import options' });](https://github.com/alberti42/obsidian-import-attachments-plus/blob/e0b95ff3b0d3a5b63d9b977ccea23679bd1cfe3b/src/main.ts#L826), [containerEl.createEl('h3', { text: 'Attachment folder configuration' });](https://github.com/alberti42/obsidian-import-attachments-plus/blob/e0b95ff3b0d3a5b63d9b977ccea23679bd1cfe3b/src/main.ts#L915), [containerEl.createEl('h3', { text: 'Attachment opening' });](https://github.com/alberti42/obsidian-import-attachments-plus/blob/e0b95ff3b0d3a5b63d9b977ccea23679bd1cfe3b/src/main.ts#L1000), [containerEl.createEl('h3', { text: 'Attachment management' });](https://github.com/alberti42/obsidian-import-attachments-plus/blob/e0b95ff3b0d3a5b63d9b977ccea23679bd1cfe3b/src/main.ts#L1037), [containerEl.createEl('h3', { text: 'Display of attachment folders' });](https://github.com/alberti42/obsidian-import-attachments-plus/blob/e0b95ff3b0d3a5b63d9b977ccea23679bd1cfe3b/src/main.ts#L1072)
For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```


[const os = navigator.platform.toUpperCase();](https://github.com/alberti42/obsidian-import-attachments-plus/blob/e0b95ff3b0d3a5b63d9b977ccea23679bd1cfe3b/src/main.ts#L1003)
use `Platform.isMacOS`

**Comment by alberti42** [comment]
Thanks for the feedback. I made all the changes and created a new release, 1.1.7.

**Comment by alberti42** [comment]
Dear @joethei 
Thanks for reviewing the plugin. I made the changes requested. Shall I simply wait, or there is something more I need to do? 
Meanwhile, I released a new version of the plugin 1.1.8.
Best, Andrea

**Review by alberti42 — COMMENTED** [review]
Add Import Attachments+ plugin

**Comment by joethei** [comment]
[import * as path from "path"; // Node.js path module to handle path operations](https://github.com/alberti42/obsidian-import-attachments-plus/blob/bbbd2855262db8db8d9f670a4f8cbf33e6f43681/src/ImportAttachmentsModal.ts#L18), [import { ParsedPath } from "path";](https://github.com/alberti42/obsidian-import-attachments-plus/blob/bbbd2855262db8db8d9f670a4f8cbf33e6f43681/src/main.ts#L35-L38), [import * as path from 'path'; // Standard import for the path module](https://github.com/alberti42/obsidian-import-attachments-plus/blob/bbbd2855262db8db8d9f670a4f8cbf33e6f43681/src/patchFileManager.ts#L9), [import * as path from 'path';](https://github.com/alberti42/obsidian-import-attachments-plus/blob/bbbd2855262db8db8d9f670a4f8cbf33e6f43681/src/patchOpenFile.ts#L5), [import { promises as fs } from 'fs';  // This imports the promises API from fs](https://github.com/alberti42/obsidian-import-attachments-plus/blob/bbbd2855262db8db8d9f670a4f8cbf33e6f43681/src/utils.ts#L2-L3)
These imports are only available from a Node.js runtime, which means that this will throw errors on Mobile (that's a problem since you have `isDesktopOnly` marked as `false` in your manifest.json file.

**Comment by alberti42** [comment]
> [import * as path from "path"; // Node.js path module to handle path operations](https://github.com/alberti42/obsidian-import-attachments-plus/blob/bbbd2855262db8db8d9f670a4f8cbf33e6f43681/src/ImportAttachmentsModal.ts#L18), [import { ParsedPath } from "path";](https://github.com/alberti42/obsidian-import-attachments-plus/blob/bbbd2855262db8db8d9f670a4f8cbf33e6f43681/src/main.ts#L35-L38), [import * as path from 'path'; // Standard import for the path module](https://github.com/alberti42/obsidian-import-attachments-plus/blob/bbbd2855262db8db8d9f670a4f8cbf33e6f43681/src/patchFileManager.ts#L9), [import * as path from 'path';](https://github.com/alberti42/obsidian-import-attachments-plus/blob/bbbd2855262db8db8d9f670a4f8cbf33e6f43681/src/patchOpenFile.ts#L5), [import { promises as fs } from 'fs'; // This imports the promises API from fs](https://github.com/alberti42/obsidian-import-attachments-plus/blob/bbbd2855262db8db8d9f670a4f8cbf33e6f43681/src/utils.ts#L2-L3) These imports are only available from a Node.js runtime, which means that this will throw errors on Mobile (that's a problem since you have `isDesktopOnly` marked as `false` in your manifest.json file.

Thanks @joethei for the feedback. I extensively checked the code and found no problem to run over mobile applications.

-1 I added to `function monkeyPatchConsole(plugin: ImportAttachments)` to `development` environment, which allows the developer to log in `data.json` all console messages. I monitored the plugin on mobiles and found no problem with it.
-2 All functions relying on node.fs are not executed on mobiles because they are inside block `if(Platform.isDesktopApp)`.
-3 I want the plugin to run over mobiles because there are some functionalities not relying on node.js that are important to have on mobiles. Namely, it is important to hide the attachment folder, if the user wishes so.
-4 I am not sure what other option I have. I only see two alternatives that are very involved. (A) Produce a second plugin for mobile only. (B) Make use of dynamical loading of node.js libraries. However, this seems unnecessary since no error is produced at the moment by the import commands on mobiles.

**Comment by alberti42** [comment]
To speed up the review process, I set the new version to be **isDesktopOnly: true**.

**Pull request merged**
