### PR TITLE
Add "JS Engine Plugin" Plugin

### PR DESCRIPTION
**Pull request by mProjectsCode**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/mProjectsCode/obsidian-js-engine-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by mProjectsCode** [comment]
Doing this will make this plugin name and id inconsistent with my other plugins...

**Comment by joethei** [comment]
["fundingUrl": "",](https://github.com/mProjectsCode/obsidian-js-engine-plugin/blob/ccf6193d3a20fe772781490f9d3bccd20efc5276/manifest.json#L9)
Omit this if you don't have this.

[containerEl.createEl('h2', { text: 'JS Engine Settings' });](https://github.com/mProjectsCode/obsidian-js-engine-plugin/blob/ccf6193d3a20fe772781490f9d3bccd20efc5276/src/Settings.ts#L25)
[Don't include a header with the plugin name in your settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[containerEl.createEl('p', { text: 'Currently Empty, but there will be stuff here later.' });](https://github.com/mProjectsCode/obsidian-js-engine-plugin/blob/ccf6193d3a20fe772781490f9d3bccd20efc5276/src/Settings.ts#L26)
Don't add the settings tab, add it once the plugin has settings.

**Comment by mProjectsCode** [comment]
I implemented all those changes

**Comment by mProjectsCode** [comment]
Any update on this?

**Pull request merged**
