### PR TITLE
Add plugin: Project Tasks

### PR DESCRIPTION
**Pull request by paulpaterson**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/paulpaterson/obsidian-project-tasks

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by paulpaterson** [comment]
I think I pushed all the changes to my repo but I maybe I am missing something. I made the changes requested.

**Comment by joethei** [comment]
The [1] is a link, click it and it will take you to the problematic line.

**Comment by paulpaterson** [comment]
Thanks! That helped. This was in the settings dialog. I changed it now.

**Comment by joethei** [comment]
[# Obsidian Project Tasks Plugin](https://github.com/paulpaterson/obsidian-project-tasks/blob/472c02d1b6b0df4369cc4477a72fca19d48fee88/README.md#L1)
Naming something "Obsidian xyz" is reserved for first party products we create, please change this header.

[name: "Set project ids on Selection",](https://github.com/paulpaterson/obsidian-project-tasks/blob/472c02d1b6b0df4369cc4477a72fca19d48fee88/main.ts#L19), [name: "Set project ids on Block",](https://github.com/paulpaterson/obsidian-project-tasks/blob/472c02d1b6b0df4369cc4477a72fca19d48fee88/main.ts#L31), [name: "Clear project ids on Selection",](https://github.com/paulpaterson/obsidian-project-tasks/blob/472c02d1b6b0df4369cc4477a72fca19d48fee88/main.ts#L56), [name: "Clear project ids on Block",](https://github.com/paulpaterson/obsidian-project-tasks/blob/472c02d1b6b0df4369cc4477a72fca19d48fee88/main.ts#L68)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by paulpaterson** [comment]
Many thanks! I made these changes and pushed them.

**Pull request merged**
