### PR TITLE
Take a swing with Lumberjack 🪓🪵

### PR DESCRIPTION
**Pull request by ryanjamurphy**
# Log your thoughts! Lumberjack adds URL commands to help you axe inefficiency and get right to writing.

## Repo URL

https://www.github.com/ryanjamurphy/lumberjack-obsidian

## Release Checklist

- [x] I have tested this on macOS, iOS, and iPadOS. Are there any other platforms???
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.
- [ ] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by ryanjamurphy** [comment]
misclicked on close.

._.

**Comment by ryanjamurphy** [comment]
Sorry, I was making some pretty dramatic changes to the codebase just now as you were reviewing. 😬

The two `getActiveViewOfType` issues are fixed. See e.g., https://github.com/ryanjamurphy/lumberjack-obsidian/blob/ec62073a4ad1448088880b1a6b0b88097dd48122/main.ts#L102

Re: `editor.eachLines()`: I have removed the need to read the text at all. Reading the cached headings now instead.

Re: the missing `if` braces: fixed!

**Comment by lishid** [comment]
https://github.com/ryanjamurphy/lumberjack-obsidian/blob/1cb821a85c4f17ee78e32372e1a0c9fb2be02226/main.ts#L58
Weird. This shouldn't really be necessary since Obsidian already runs decodeURIComponent on it.

https://github.com/ryanjamurphy/lumberjack-obsidian/blob/1cb821a85c4f17ee78e32372e1a0c9fb2be02226/main.ts#L101
This will error out since you will be attempting to read `.editor` on null. Check for null on the view first.

**Comment by ryanjamurphy** [comment]
Fixed both of these! 

> https://github.com/ryanjamurphy/lumberjack-obsidian/blob/1cb821a85c4f17ee78e32372e1a0c9fb2be02226/main.ts#L58 Weird. This shouldn't really be necessary since Obsidian already runs decodeURIComponent on it.

Removed the extra decodeURIComponent.

> https://github.com/ryanjamurphy/lumberjack-obsidian/blob/1cb821a85c4f17ee78e32372e1a0c9fb2be02226/main.ts#L101 This will error out since you will be attempting to read `.editor` on null. Check for null on the view first.

Fixed. I think! See e.g., https://github.com/ryanjamurphy/lumberjack-obsidian/blob/83a69bcbc94c7345a6f665feedb70e7bc0eed424/main.ts#L101 / https://github.com/ryanjamurphy/lumberjack-obsidian/commit/83a69bcbc94c7345a6f665feedb70e7bc0eed424

**Pull request merged**
