### PR TITLE
Add plugin: Movie DB

### PR DESCRIPTION
**Pull request by drshajul**
A plugin to search for Movies or Episodes with trailers and adding them to Obsidian

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/shajul/obsidian-movie-db

## Release Checklist
- [x ] I have tested the plugin on
  - [x ]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ x]  Android _(if applicable)_
  - [ x]  iOS _(if applicable)_
- [ x] My GitHub release contains all required files
  - [ x] `main.js`
  - [ x] `manifest.json`
  - [ x] `styles.css` _(optional)_
- [ x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [ x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [ x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [ x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [ x] I have added a license in the LICENSE file.
- [ x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
What sets your plugin apart from the original?
Looking at the commits, I can only see one tiny bugfix that should have been contributed to the original plugin.

**Comment by shajul** [comment]
I have pull request to the original. But it is pending for long.

**Comment by joethei** [comment]
When I compare the code, I just don't see any functional differences between the two plugins.
Please point out the concrete lines of code you changed that warrant this PR.

**Comment by shajul** [comment]
This [PR by me](https://github.com/onuraycicek/obsidian-movie/pulls) was created a month ago. If merged, the original repo will work again. But right now, the original repo is broken as I said earlier.

The new repo does not look big on changes, cause already some important functionality has been pulled from my repo. See [Commits](https://github.com/onuraycicek/obsidian-movie/commits/master).

If still you want to keep the broken original repo, just delete my PR.

**Comment by joethei** [comment]
Please have patience with them, you opened this PR 19 days after submitting the PR to the plugin repo, which is not a lot of time for a personal project.

If they do not respond in the next few months, then you can create a new PR here to take over the existing entry.

**Pull request closed without merging**
