### PR TITLE
Add plugin: Relay.md

### PR DESCRIPTION
**Pull request by xeroc**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/relay-md/relay-md-obsidian-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by xeroc** [comment]
Please exclude the "duplicate" pull request. It took me 30 minutes trying to figure out why your pipeline fails for awkward reasons, only to become frustrated and give up on the pr. Then figured out it couldn't merge with upstream/master and tried again after fixing merge conflicts.

**Comment by joethei** [comment]
Please remove the `main.js` file from the repo and add it to your .gitignore. Compiled release files shouldn't get mixed with source code in your commits and should go to the releases files instead.

Your readme should contain more information, currently one has to visit the website to get a clue what the plugin does.

["repo": "relay-md/relay-md-obsidian-plugin",](https://github.com/relay-md/relay-md-obsidian-plugin/blob/89fb005a2a5549be8373e42a8960433d3c2cc499/manifest.json#L10)
This is not a part of the manifest spec, remove it.

[id: "relay-md-send-current-active-file",](https://github.com/relay-md/relay-md-obsidian-plugin/blob/89fb005a2a5549be8373e42a8960433d3c2cc499/src/main.ts#L46)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

[name: "Relay.md: Send current open file",](https://github.com/relay-md/relay-md-obsidian-plugin/blob/89fb005a2a5549be8373e42a8960433d3c2cc499/src/main.ts#L47)
Also don't prefix the command name, it will currently show up as `Relay.md: Relay.md: Send current open file` in the command pallete / hotkey list.

[this.app.vault.on('modify', (file: TAbstractFile) => {](https://github.com/relay-md/relay-md-obsidian-plugin/blob/89fb005a2a5549be8373e42a8960433d3c2cc499/src/main.ts#L65-L74)
Events need to be registered, so they can be properly unloaded when the plugin is disabled. <https://docs.obsidian.md/Plugins/Events>

[// FIXME: There is no way to check if a folder exists, so we just try create them](https://github.com/relay-md/relay-md-obsidian-plugin/blob/89fb005a2a5549be8373e42a8960433d3c2cc499/src/main.ts#L98)
There is: `this.app.vault.getAbstractFileByPath(folder)`, and check if the result is `instanceof TFolder`

**Comment by xeroc** [comment]
Excellent feedback, thank you. Will get to it asap

**Comment by xeroc** [comment]
Ready to go.

**Comment by xeroc** [comment]
I made changes according to the request above.
Do I take care of resolving merge conflicts or is that something the devs take care off themselves?

**Comment by liamcain** [comment]
- [==](https://github.com/relay-md/relay-md-obsidian-plugin/blob/569bfa65d16a782fa9324d3f64f7a31b20466887/src/main.ts#L285) should be `===`
- [api_key: '00000000-0000-0000-0000-000000000000',](https://github.com/relay-md/relay-md-obsidian-plugin/blob/569bfa65d16a782fa9324d3f64f7a31b20466887/src/main.ts#L24) I don't recommend including this in the default settings. The default API key should just be `''` and you can check that the API key is present before making any API calls.
- [activeFile.path.startsWith(this.settings.vault_base_folder)](https://github.com/relay-md/relay-md-obsidian-plugin/blob/569bfa65d16a782fa9324d3f64f7a31b20466887/src/main.ts#L201) this should check for base_folder + "/" to avoid false positives
- [if (!metadata || !metadata.frontmatter) {](https://github.com/relay-md/relay-md-obsidian-plugin/blob/569bfa65d16a782fa9324d3f64f7a31b20466887/src/main.ts#L211) move this check before calling cachedRead to avoid wasted work
- [try {](https://github.com/relay-md/relay-md-obsidian-plugin/blob/569bfa65d16a782fa9324d3f64f7a31b20466887/src/main.ts#L189) nit: this shouldn't all be inside the try catch, only code that can throw errors should be inside the try catch
- [try {](https://github.com/relay-md/relay-md-obsidian-plugin/blob/569bfa65d16a782fa9324d3f64f7a31b20466887/src/main.ts#L189) your send_document function uses the metadataCache. The metadataCache updates asynchronously so it won't be up to date immediately after a user modifies a file. If it's important that you have the up to date metadata, then you shouldn't be relying on the "modify" vault event. Instead, you should be listening for `MetadataCache.on('changed') <https://github.com/obsidianmd/obsidian-api/blob/bbb696aeb8bf5126bf2ecbf84fc8284fe133bc20/obsidian.d.ts#L2595>

**Comment by xeroc** [comment]
> * [==](https://github.com/relay-md/relay-md-obsidian-plugin/blob/569bfa65d16a782fa9324d3f64f7a31b20466887/src/main.ts#L285) should be `===`
> 
> * [api_key: '00000000-0000-0000-0000-000000000000',](https://github.com/relay-md/relay-md-obsidian-plugin/blob/569bfa65d16a782fa9324d3f64f7a31b20466887/src/main.ts#L24) I don't recommend including this in the default settings. The default API key should just be `''` and you can check that the API key is present before making any API calls.
> 
> * [activeFile.path.startsWith(this.settings.vault_base_folder)](https://github.com/relay-md/relay-md-obsidian-plugin/blob/569bfa65d16a782fa9324d3f64f7a31b20466887/src/main.ts#L201) this should check for base_folder + "/" to avoid false positives
> 
> * [if (!metadata || !metadata.frontmatter) {](https://github.com/relay-md/relay-md-obsidian-plugin/blob/569bfa65d16a782fa9324d3f64f7a31b20466887/src/main.ts#L211) move this check before calling cachedRead to avoid wasted work
> 
> * [try {](https://github.com/relay-md/relay-md-obsidian-plugin/blob/569bfa65d16a782fa9324d3f64f7a31b20466887/src/main.ts#L189) nit: this shouldn't all be inside the try catch, only code that can throw errors should be inside the try catch

> * [try {](https://github.com/relay-md/relay-md-obsidian-plugin/blob/569bfa65d16a782fa9324d3f64f7a31b20466887/src/main.ts#L189) your send_document function uses the metadataCache. The metadataCache updates asynchronously so it won't be up to date immediately after a user modifies a file. If it's important that you have the up to date metadata, then you shouldn't be relying on the "modify" vault event. Instead, you should be listening for `MetadataCache.on('changed') https://github.com/obsidianmd/obsidian-api/blob/bbb696aeb8bf5126bf2ecbf84fc8284fe133bc20/obsidian.d.ts#L2595


Thanks. I updated those items.

**Comment by liamcain** [comment]
Looks like the changes are only on your develop branch and not actually released

**Comment by xeroc** [comment]
> Looks like the changes are only on your develop branch and not actually released

Apologize, a release is in the pipeline and a release should be tagged by 10am UTC, today.

**Comment by xeroc** [comment]
Happy new year.

The release was created a few weeks ago. Please inform me of any additional information or assistance required to facilitate further progress.

**Comment by xeroc** [comment]
rebased the pr so it can be merged more easily.
Appreciate further feeback ...

**Comment by liamcain** [comment]
Sorry, we've been off to a slow start with plugin reviews this year. Thanks for implementing the requested changes. Looks good!

**Comment by liamcain** [comment]
Merged in this commit: https://github.com/obsidianmd/obsidian-releases/commit/417e842cbbaa79d971714e186e9bb9948183251c

**Pull request closed without merging**
