### PR TITLE
Add Obsidian-Memos Plugin to Market

### PR DESCRIPTION
**Pull request by Quorafind**
Add a new plugin

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [https://github.com/Quorafind/Obsidian-Memos](https://github.com/Quorafind/Obsidian-Memos)

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/Quorafind/Obsidian-Memos/blob/b6bef56c62ff10929b1f72fa1bf2ae2a9468de8b/src/index.ts#L175
You need to run the querySelector inside your view's contentEl rather than globally, because this will catch the wrong textarea if another plugin happens to have one.

https://github.com/Quorafind/Obsidian-Memos/blob/b6bef56c62ff10929b1f72fa1bf2ae2a9468de8b/src/memos.ts#L25
Move all of these registration to your view's onOpen function. You shouldn't be registering things in the constructor yet.

https://github.com/Quorafind/Obsidian-Memos/blob/b6bef56c62ff10929b1f72fa1bf2ae2a9468de8b/src/memos.ts#L118
Don't do this here, do it in your plugin's onload.

https://github.com/Quorafind/Obsidian-Memos/blob/b6bef56c62ff10929b1f72fa1bf2ae2a9468de8b/src/obComponents/obPinQuery.ts#L3
Use `moment` from `obsidian` instead of importing it from moment. This way you don't import a copy of that library as a copy in your plugin. (See if there's other imports in other files too)

https://github.com/Quorafind/Obsidian-Memos/blob/b6bef56c62ff10929b1f72fa1bf2ae2a9468de8b/src/obComponents/obPinQuery.ts#L48
Use `vault.read` if you plan to modify the file contents. Use `cachedRead` when you want to display the information only.
There's a couple of other places in other files as well that you should address.

**Comment by Quorafind** [comment]
> https://github.com/Quorafind/Obsidian-Memos/blob/b6bef56c62ff10929b1f72fa1bf2ae2a9468de8b/src/index.ts#L175 You need to run the querySelector inside your view's contentEl rather than globally, because this will catch the wrong textarea if another plugin happens to have one.
> 

Fixed. You can verify it in https://github.com/Quorafind/Obsidian-Memos/pull/73/files

> https://github.com/Quorafind/Obsidian-Memos/blob/b6bef56c62ff10929b1f72fa1bf2ae2a9468de8b/src/memos.ts#L25 Move all of these registration to your view's onOpen function. You shouldn't be registering things in the constructor yet.
> 

Fixed. You can verify it in https://github.com/Quorafind/Obsidian-Memos/pull/73/files

> https://github.com/Quorafind/Obsidian-Memos/blob/b6bef56c62ff10929b1f72fa1bf2ae2a9468de8b/src/memos.ts#L118 Don't do this here, do it in your plugin's onload.
> 

Fixed. You can verify it in https://github.com/Quorafind/Obsidian-Memos/pull/73/files

> https://github.com/Quorafind/Obsidian-Memos/blob/b6bef56c62ff10929b1f72fa1bf2ae2a9468de8b/src/obComponents/obPinQuery.ts#L3 Use `moment` from `obsidian` instead of importing it from moment. This way you don't import a copy of that library as a copy in your plugin. (See if there's other imports in other files too)
> 

Fixed. You can verify it in https://github.com/Quorafind/Obsidian-Memos/pull/73/files

> https://github.com/Quorafind/Obsidian-Memos/blob/b6bef56c62ff10929b1f72fa1bf2ae2a9468de8b/src/obComponents/obPinQuery.ts#L48 Use `vault.read` if you plan to modify the file contents. Use `cachedRead` when you want to display the information only. There's a couple of other places in other files as well that you should address.

Fixed. You can verify it in https://github.com/Quorafind/Obsidian-Memos/pull/73/files

**Comment by lishid** [comment]
Try using an auto formatter to normalize the whitespaces in your code.
image


https://github.com/Quorafind/Obsidian-Memos/blob/6bb006c2fa3626f685b4e60de42cecde6db5102f/src/services/dailyNotesService.ts#L6
https://github.com/Quorafind/Obsidian-Memos/blob/6f556f4bd6979401373e2f53b97656efcffabfb3/src/obComponents/createMemoInDailyNote.ts#L1
Two more `moment` :)

https://github.com/Quorafind/Obsidian-Memos/blob/dce1a82f2efee31e1ce557b6b0f58d1b437af123/src/index.ts#L168
I think the code you have right now for opening and focusing on the pane is overly complicated.
Here's how I suggest improving it:

```ts
  async openMemos() {
    const workspace = this.app.workspace;
    workspace.detachLeavesOfType(MEMOS_VIEW_TYPE);
    let leaf = workspace.getLeaf(!Platform.isMobile && workspace.activeLeaf && 
                                 (workspace.activeLeaf.view instanceof FileView));
    await leaf.setViewState({ type: MEMOS_VIEW_TYPE });
    workspace.revealLeaf(leaf);
    if (FocusOnEditor !== false) {
      leaf.view.containerEl.querySelector('textarea').focus();
    }
  }
  focusOnEditor() {
    const workspace = this.app.workspace;
    const leaves = workspace.getLeavesOfType(MEMOS_VIEW_TYPE);
    if (leaves .length > 0) {
      let leaf = leaves[0];
      workspace.setActiveLeaf(leaf);
      leaf.view.containerEl.querySelector('textarea').focus();
    } else {
      this.openMemos();
    }
  }
```

**Comment by lishid** [comment]
https://github.com/Quorafind/Obsidian-Memos/blob/dce1a82f2efee31e1ce557b6b0f58d1b437af123/src/index.ts#L123
Also here you're testing `.length` against null/undefined, but you probably intend for `> 0`?

**Comment by Quorafind** [comment]
> https://github.com/Quorafind/Obsidian-Memos/blob/dce1a82f2efee31e1ce557b6b0f58d1b437af123/src/index.ts#L123 Also here you're testing `.length` against null/undefined, but you probably intend for `> 0`?
> 
> Wait you already tested it a few lines above!

Sorry, I found this is useless, don't need it in code. So I deleted it.



> Try using an auto formatter to normalize the whitespaces in your code. image
> 
> https://github.com/Quorafind/Obsidian-Memos/blob/6bb006c2fa3626f685b4e60de42cecde6db5102f/src/services/dailyNotesService.ts#L6 https://github.com/Quorafind/Obsidian-Memos/blob/6f556f4bd6979401373e2f53b97656efcffabfb3/src/obComponents/createMemoInDailyNote.ts#L1 Two more `moment` :)
> 
> https://github.com/Quorafind/Obsidian-Memos/blob/dce1a82f2efee31e1ce557b6b0f58d1b437af123/src/index.ts#L168 I think the code you have right now for opening and focusing on the pane is overly complicated. Here's how I suggest improving it:
> 
> ```ts
>   async openMemos() {
>     const workspace = this.app.workspace;
>     workspace.detachLeavesOfType(MEMOS_VIEW_TYPE);
>     let leaf = workspace.getLeaf(!Platform.isMobile && workspace.activeLeaf && 
>                                  (workspace.activeLeaf.view instanceof FileView));
>     await leaf.setViewState({ type: MEMOS_VIEW_TYPE });
>     workspace.revealLeaf(leaf);
>     if (FocusOnEditor !== false) {
>       leaf.view.containerEl.querySelector('textarea').focus();
>     }
>   }
>   focusOnEditor() {
>     const workspace = this.app.workspace;
>     const leaves = workspace.getLeavesOfType(MEMOS_VIEW_TYPE);
>     if (leaves .length > 0) {
>       let leaf = leaves[0];
>       workspace.setActiveLeaf(leaf);
>       leaf.view.containerEl.querySelector('textarea').focus();
>     } else {
>       this.openMemos();
>     }
>   }
> ```

All the code is formatted now.

The `createMemoInDailyNote.ts` have been removed because it is useless in code now.

https://github.com/Quorafind/Obsidian-Memos/pull/74/files

**Pull request merged**
