### PR TITLE
Add plugin: Daily Statistics

### PR DESCRIPTION
**Pull request by yefengr**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [ ] `main.js`
  - [ ] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by yefengr** [comment]
> [import moment from "moment/moment";](https://github.com/yefengr/obsidian-daily-statistics/blob/d585e2fe91946f19eb30a16880701a7a613d075a/src/ui/calendar/Calendar.vue#L70), [import moment from "moment";](https://github.com/yefengr/obsidian-daily-statistics/blob/d585e2fe91946f19eb30a16880701a7a613d075a/src/data/StatisticsDataManager.ts#L3)
Import moment from Obsidian, like in the example above.

I think it's more convenient to use the Moment package directly. Your components lack documentation, and I don't know how to use them.

> [styles.css](https://github.com/yefengr/obsidian-daily-statistics/blob/d585e2fe91946f19eb30a16880701a7a613d075a/styles.css#L1-L2)
This file should not be minified here, it's okay to minify it in the release, but not in the repo.

The styles.css file is generated by the build tool and has been removed.

Other issues have been corrected.
@joethei

**Comment by yefengr** [comment]
Following your instructions, I imported moment from obsidian: `import { moment } from "obsidian"`;
However, there are issues.
image
image

@joethei

**Comment by yefengr** [comment]
@joethei help me！

**Comment by joethei** [comment]
That looks to be caused by your build config, I cannot reproduce with the default config from the sample plugin.

**Comment by yefengr** [comment]
I can't solve this problem, can it be put on the shelf directly?
@joethei

**Comment by joethei** [comment]
No, I cannot accept this plugin in it's current state.

**Comment by liamcain** [comment]
Hi, I'm taking over some plugin reviews while joethei is on sick leave. The plugin looks good to me, I see that joethei encouraged you to use the moment package bundled with Obsidian. I think it's okay to merge this first and we can try to get the import figured out afterward.

---

What steps did you go through to replace the import? As joethei mentioned, `import { moment } from 'obsidian';` should work, but maybe try removing the moment package from your package.json and package-lock.json files first to see if there's a conflict.

Also, can you try `window.moment()` instead, and does that work?

**Comment by yefengr** [comment]
@liamcain 
Thank you for your understanding. 
In fact, I am not very skilled in front-end development, which is why such issues have occurred. 
When I have some free time later, I will try to resolve these issues.

**Pull request merged**
