### PR TITLE
plugin: add PKMer plugin to obsidian

### PR DESCRIPTION
**Pull request by windily-cloud**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [Pkmer-Obsidian](https://github.com/PKM-er/Pkmer-Obsidian)

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by windily-cloud** [comment]
Looks like I don't have to worry about the error.........😣

image

**Comment by joethei** [comment]
The validation needs to pass at least once.

**Comment by windily-cloud** [comment]
> The validation needs to pass at least once.

Okay, I guess I did something right, ha ha😊！

**Comment by joethei** [comment]
after careful consideration we have decided not to allow this plugin into the official community plugins list. The reason why is that it creates a way for developers to bypass the [developer policies](https://docs.obsidian.md/Developer+policies).

Users are free to install any plugin manually. The purpose of the community directory is to enforce certain precautions around security, disclosures, licensing, etc. The PKMer marketplace creates a loophole that we are not comfortable with. Currently PKMer crawls the official list of approved plugins/themes, but there's no way to ensure that unapproved plugins/themes cannot be added.

In the future we hope to address some of the limitations with the official plugin/theme directory that your plugin aims to solve. In the meantime, users can always install PKMer manually if they want to.

Sorry to be the bearer of bad news. I hope our reasoning makes sense to you.

**Pull request closed without merging**
