### PR TITLE
Add plugin: Canvas LLM Extender

### PR DESCRIPTION
**Pull request by Phasip**
# I am submitting a new Community Plugin
## Repo URL

Link to my plugin: https://github.com/Phasip/obsidian-canvas-llm-extender
## Release Checklist
* [x]  I have tested the plugin on
  * [x]   Windows
  * [x]   macOS
  * [x]   Linux
  * [ ]   Android _(if applicable)_
  * [ ]   iOS _(if applicable)_
* [x]  My GitHub release contains all required files
  * [x]  `main.js`
  * [x]  `manifest.json`
  * [x]  `styles.css` _(optional)_
* [x]  GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
* [x]  The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
* [x]  My README.md describes the plugin's purpose and provides clear usage instructions.
* [x]  I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
* [x]  I have added a license in the LICENSE file.
* [x]  My project respects and is compatible with the original license of any code from other plugins that I'm using.
  I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Please follow the pull request template.

**Comment by Phasip** [comment]
Done, added to initial msg.

These points could also be added to https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins
Not sure where the Template is supposed to appear, i copied this from some other approved pull request.

**Comment by joethei** [comment]
It's described here, in the 5. point: <https://docs.obsidian.md/Plugins/Releasing/Submit+your+plugin#Step+3+Submit+your+plugin+for+review>

[this.app.workspace.on("canvas:node-menu", (menu: Menu, node: unknown) => {](https://github.com/Phasip/obsidian-canvas-llm-extender/blob/0b4f03e1406848824c05c868a2c0ce26b13648f8/src/main.ts#L32-L41)
Events need to be registered, so they can be properly unloaded when the plugin is disabled. <https://docs.obsidian.md/Plugins/Events>

[// eslint-disable-next-line @typescript-eslint/no-empty-function](https://github.com/Phasip/obsidian-canvas-llm-extender/blob/0b4f03e1406848824c05c868a2c0ce26b13648f8/src/main.ts#L46)
Just remove the function.

[console.log("LineHeight is ",lineHeight, "Width is ",width, " Linewidth: ",lineWidth)](https://github.com/Phasip/obsidian-canvas-llm-extender/blob/0b4f03e1406848824c05c868a2c0ce26b13648f8/src/obsidian-canvas-utils.ts#L118)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[containerEl.createEl('h2', { text: 'Canvas LLM Extender Settings' });](https://github.com/Phasip/obsidian-canvas-llm-extender/blob/0b4f03e1406848824c05c868a2c0ce26b13648f8/src/settings.ts#L33)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[.setName("OpenAI Temperature")](https://github.com/Phasip/obsidian-canvas-llm-extender/blob/0b4f03e1406848824c05c868a2c0ce26b13648f8/src/settings.ts#L63)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[.setPlaceholder("gpt-3.5-turbo")](https://github.com/Phasip/obsidian-canvas-llm-extender/blob/0b4f03e1406848824c05c868a2c0ce26b13648f8/src/settings.ts#L54)
You can use `DEFAULT_SETTINGS.model` here instead, so you don't have to update this string in two places should the default ever change.
Same for the other placeholders.

[incomming](https://github.com/Phasip/obsidian-canvas-llm-extender/blob/0b4f03e1406848824c05c868a2c0ce26b13648f8/src/settings.ts#L18)
Typo.

---

[.setPlaceholder("sk-I0VQMCAgUGxlYXNlIERvbid0IFN0ZWFsIE15IFNlY3JldC4K")](https://github.com/Phasip/obsidian-canvas-llm-extender/blob/0b4f03e1406848824c05c868a2c0ce26b13648f8/src/settings.ts#L40)
Is that a valid API key?
If so, delete it on the OpenAI site, before someone scrapes and uses it.


[// TODO: Obsidian maybe has a setting field built for numbers?](https://github.com/Phasip/obsidian-canvas-llm-extender/blob/0b4f03e1406848824c05c868a2c0ce26b13648f8/src/settings.ts#L68)
No, not really, you could use a slider instead.

**Comment by Phasip** [comment]
Thanks for a great review, all suggestions have been implemented and a new version issued.
The key is not a real key.
```
$ echo "I0VQMCAgUGxlYXNlIERvbid0IFN0ZWFsIE15IFNlY3JldC4K" | base64 -d
#EP0  Please Don't Steal My Secret.
```
(Maybe I should use sentence case there too)

**Pull request merged**
