### PR TITLE
Add plugin: Scripture Indexer

### PR DESCRIPTION
**Pull request by jdrbrn**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/jdrbrn/obsidian-scripture-indexer

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Remove the `styles.css` file from your release, since it's empty it's just unnecessary bloat.

["minAppVersion": "0.15.0",](https://github.com/jdrbrn/obsidian-scripture-indexer/blob/b623f231d41cea4b6f65be36e260de61d935fc96/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

[name: 'Index All Files',](https://github.com/jdrbrn/obsidian-scripture-indexer/blob/b623f231d41cea4b6f65be36e260de61d935fc96/main.ts#L66), [name: 'Index This File',](https://github.com/jdrbrn/obsidian-scripture-indexer/blob/b623f231d41cea4b6f65be36e260de61d935fc96/main.ts#L74), [name: 'Reset Index',](https://github.com/jdrbrn/obsidian-scripture-indexer/blob/b623f231d41cea4b6f65be36e260de61d935fc96/main.ts#L85)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[this.IndexFile(this.app.vault.getFileByPath(file.path)!);](https://github.com/jdrbrn/obsidian-scripture-indexer/blob/b623f231d41cea4b6f65be36e260de61d935fc96/main.ts#L98), [this.IndexFile(this.app.vault.getFileByPath(file.path)!);](https://github.com/jdrbrn/obsidian-scripture-indexer/blob/b623f231d41cea4b6f65be36e260de61d935fc96/main.ts#L115)
Don't assume that a file exists, always check.

**Comment by jdrbrn** [comment]
Thanks for the code review! I believe the necessary changes have all been made. Please let me know if there's anything else.

As a follow up question, why should I check for files existing in the situations you linked? From my understanding of the documentation those events should only be triggered on file changes and return files that do exist. Is there a possibility that they return a file that doesn't exist (or is a folder as a TAbstractFile says it could represent)? Or is it just a best practices thing? Thanks again for your help.

**Comment by liamcain** [comment]
- [Could be different than the previously loaded one if data was synced after plugin was loaded](https://github.com/jdrbrn/obsidian-scripture-indexer/blob/717ff91aebe8e54c2f6adce6279dd147fd54be42/main.ts#L148) If settings were loaded after the plugin, then you can use onExternalSettingsChange (<https://github.com/obsidianmd/obsidian-api/blob/df9434bec6883bd32727f61b1ed1336f7663d0e4/obsidian.d.ts#L3088>). I highly recommend not loading settings here. This means reading from the filesystem on every edit, which is way more computationally expensive than it needs to be.
- [this.saveSettings](https://github.com/jdrbrn/obsidian-scripture-indexer/blob/717ff91aebe8e54c2f6adce6279dd147fd54be42/main.ts#L160) you should also [debounce](https://github.com/obsidianmd/obsidian-api/blob/1b4f6e2e5753c8ac2d538bc5d55c38f228450cb2/obsidian.d.ts#L772) your saveSettings method.
- [await files.forEach(file => this.ScrapeFile(file))](https://github.com/jdrbrn/obsidian-scripture-indexer/blob/717ff91aebe8e54c2f6adce6279dd147fd54be42/main.ts#L140) this is not configured correctly. `ScrapeFile` is async, so to properly wait for it to get called on every file in the vault, you need to `await` each call to `ScrapeFile`. Something like would be better:

```ts
for (let file of files) {
  await this.ScrapeFile(file)
}
```

**Comment by jdrbrn** [comment]
Thanks for the advice.

- Updated to use the onExternalSettingsChange function and removed the manual reloading of the settings file
- Debounced the saveSettings method and also most cases of WriteIndex as it's a similar idea, just writing to an actual note not the settings file
- Updated IndexAllFiles to properly scrape files async

**Pull request merged**
