### PR TITLE
Add Obsidian Pangu Plugin

### PR DESCRIPTION
**Pull request by Natumsol**
# [x] I am submitting a new Community Plugin

https://github.com/Natumsol/obsidian-pangu

## Release Checklist

- [x] I have tested this on Windows, macOS,
- [x] Github release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
- [x] Github release name matches the exact version number specified in your manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.

### CODE REVIEW

**Comment by ericaxu** [comment]
https://github.com/Natumsol/obsidian-pangu/blob/master/main.ts#L12
Nit: you might want to change the name?

https://github.com/Natumsol/obsidian-pangu/blob/master/main.ts#L53
I think it's better to set a hotkey for the Obsidian command you registered, so that the user can change it. Hard-coding it might cause conflicts.

https://github.com/Natumsol/obsidian-pangu/blob/master/main.ts#L77
Nit: might want to change this name too

Otherwise looks good to me! I'm sure Chinese users will enjoy this plugin.

**Comment by lishid** [comment]
https://github.com/Natumsol/obsidian-pangu/blob/0f246e70decca781288336e98b68e03861309280/main.ts#L46

Use `workspace.getActiveViewOfType(MarkdownView)` and do a null check after.

**Comment by Natumsol** [comment]
> https://github.com/Natumsol/obsidian-pangu/blob/master/main.ts#L12
> Nit: you might want to change the name?
> 
> https://github.com/Natumsol/obsidian-pangu/blob/master/main.ts#L53
> I think it's better to set a hotkey for the Obsidian command you registered, so that the user can change it. Hard-coding it might cause conflicts.
> 
> https://github.com/Natumsol/obsidian-pangu/blob/master/main.ts#L77
> Nit: might want to change this name too
> 
> Otherwise looks good to me! I'm sure Chinese users will enjoy this plugin.


Thank you for the suggestion, the problem has been fixed.😀

**Comment by Natumsol** [comment]
> https://github.com/Natumsol/obsidian-pangu/blob/0f246e70decca781288336e98b68e03861309280/main.ts#L46
> 
> Use `workspace.getActiveViewOfType(MarkdownView)` and do a null check after.

Thank you for the suggestion, the problem has been fixed.😀

**Comment by lishid** [comment]
https://github.com/Natumsol/obsidian-pangu/blob/11fbf130bab188f70878502dcdf572f44364e637/main.ts#L36
I think you can use `activeLeafView.editor` to make your plugin mobile-friendly. This would make use of our proxy object for the editor, which uses `CodeMirror.Editor` on desktop and CodeMirror 6's API on mobile.

If you cannot make it work with the Editor API and must use CodeMirror 5's API, you should change your manifest to indicate that your plugin is desktop-only: https://github.com/Natumsol/obsidian-pangu/blob/11fbf130bab188f70878502dcdf572f44364e637/manifest.json#L9

https://github.com/Natumsol/obsidian-pangu/blob/11fbf130bab188f70878502dcdf572f44364e637/formatUtil.ts#L138
I think there's probably better ways to do this, possibly with better performance. Maybe something like
`content.replace(/[\uFF10-\uFF19]/g, (c) => String.fromCharCode(c.charCodeAt(0)-0xFF10));`. Probably something similar for the alphabets.

**Comment by Natumsol** [comment]
> https://github.com/Natumsol/obsidian-pangu/blob/11fbf130bab188f70878502dcdf572f44364e637/main.ts#L36
> I think you can use `activeLeafView.editor` to make your plugin mobile-friendly. This would make use of our proxy object for the editor, which uses `CodeMirror.Editor` on desktop and CodeMirror 6's API on mobile.
> 
> If you cannot make it work with the Editor API and must use CodeMirror 5's API, you should change your manifest to indicate that your plugin is desktop-only: https://github.com/Natumsol/obsidian-pangu/blob/11fbf130bab188f70878502dcdf572f44364e637/manifest.json#L9
> 
> https://github.com/Natumsol/obsidian-pangu/blob/11fbf130bab188f70878502dcdf572f44364e637/formatUtil.ts#L138
> I think there's probably better ways to do this, possibly with better performance. Maybe something like
> `content.replace(/[\uFF10-\uFF19]/g, (c) => String.fromCharCode(c.charCodeAt(0)-0xFF10));`. Probably something similar for the alphabets.

Thanks for your reply!

I don't have a mobile test environment yet, so I'll set it to `desktopOnly` for now 🤣.

PS: The string replacement function has been optimized~

```js

  replaceFullNumbersAndChars(content: string): string {
    // 替换全角数字 & 全角英文
    // Ａ -> A
    // ０ -> 0
    return content.replace(/[\uFF10-\uFF19\uFF21-\uFF5A]/g, c => String.fromCharCode(c.charCodeAt(0) - 0xfee0));
  }
```

**Comment by lishid** [comment]
> I don't have a mobile test environment yet, so I'll set it to desktopOnly for now 🤣.

You should still test with the new `editor` API instead of using the discouraged `cmEditor` API so that you know it works on desktop.

**Pull request merged**
