### PR TITLE
Add plugin: AI Curriculum Maker

### PR DESCRIPTION
**Pull request by ACSancheZ**
# I am submitting a new Community Plugin
### Repo URL

Link to my plugin: [https://github.com/ACSancheZ/prof-match-ai](https://github.com/ACSancheZ/prof-match-ai)
### Release Checklist

I have tested the plugin on

- [x] Windows
- [ ] macOS
- [x] Linux
- [ ] Android (if applicable)
- [ ] iOS (if applicable)

My GitHub release contains all required files

- [x] main.js
- [x] manifest.json
- [ ] styles.css (optional)

- [x] GitHub release name matches the exact version number specified in my manifest.json (Note: Use the exact version number, don't include a prefix v)
- [x] The id in my manifest.json matches the id in the community-plugins.json file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
- [x] I have given proper attribution to these other projects in my README.md.

### CODE REVIEW

**Comment by ACSancheZ** [comment]
Fix GitHub Actions to publish main.js and package.json

**Comment by joethei** [comment]
[Copyright (c) [year] [fullname]](https://github.com/ACSancheZ/prof-match-ai/blob/f2c4aaf2880d2896e9c3bba1d9f8c20bb3b49f7c/LICENSE#L3)
Fill this.

["name": "IA Curriculum Maker",](https://github.com/ACSancheZ/prof-match-ai/blob/f2c4aaf2880d2896e9c3bba1d9f8c20bb3b49f7c/manifest.json#L3)
The README says "AI" but this says "IA", which one is correct.

["authorUrl": "https://www.sancheztoni.com",](https://github.com/ACSancheZ/prof-match-ai/blob/f2c4aaf2880d2896e9c3bba1d9f8c20bb3b49f7c/manifest.json#L8-L9)
This website does not work.

[console.log("Loading Professional Experience Summary plugin");](https://github.com/ACSancheZ/prof-match-ai/blob/f2c4aaf2880d2896e9c3bba1d9f8c20bb3b49f7c/main.ts#L15)
Wrong plugin name.

[name: "Generate Summary",](https://github.com/ACSancheZ/prof-match-ai/blob/f2c4aaf2880d2896e9c3bba1d9f8c20bb3b49f7c/main.ts#L21), [new Notice("Registered Job Description in the Chat GPT context");](https://github.com/ACSancheZ/prof-match-ai/blob/f2c4aaf2880d2896e9c3bba1d9f8c20bb3b49f7c/src/prof-match-ia.ts#L63), [new Notice(`Get Job Experience: '${summary.fileName}' summarized.`);](https://github.com/ACSancheZ/prof-match-ai/blob/f2c4aaf2880d2896e9c3bba1d9f8c20bb3b49f7c/src/prof-match-ia.ts#L77), [.setName("Job Experience Folder")](https://github.com/ACSancheZ/prof-match-ai/blob/f2c4aaf2880d2896e9c3bba1d9f8c20bb3b49f7c/src/plugin-settings.ts#L44), [.setName("Curriculum Templates Folder")](https://github.com/ACSancheZ/prof-match-ai/blob/f2c4aaf2880d2896e9c3bba1d9f8c20bb3b49f7c/src/plugin-settings.ts#L57), [.setName("Job Opportunities Folder")](https://github.com/ACSancheZ/prof-match-ai/blob/f2c4aaf2880d2896e9c3bba1d9f8c20bb3b49f7c/src/plugin-settings.ts#L70), [.setName("Output Folder")](https://github.com/ACSancheZ/prof-match-ai/blob/f2c4aaf2880d2896e9c3bba1d9f8c20bb3b49f7c/src/plugin-settings.ts#L83), [.setName("Chat GPT Model")](https://github.com/ACSancheZ/prof-match-ai/blob/f2c4aaf2880d2896e9c3bba1d9f8c20bb3b49f7c/src/plugin-settings.ts#L114), [.setName("Prompt to identify the Job Description")](https://github.com/ACSancheZ/prof-match-ai/blob/f2c4aaf2880d2896e9c3bba1d9f8c20bb3b49f7c/src/plugin-settings.ts#L127), [.setName("Prompt to summiraze one Job Experience")](https://github.com/ACSancheZ/prof-match-ai/blob/f2c4aaf2880d2896e9c3bba1d9f8c20bb3b49f7c/src/plugin-settings.ts#L142)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[console.log("Getting Summaries.");](https://github.com/ACSancheZ/prof-match-ai/blob/f2c4aaf2880d2896e9c3bba1d9f8c20bb3b49f7c/src/prof-match-ia.ts#L28)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[setTimeout(() => {}, 20000); // 20 seconds](https://github.com/ACSancheZ/prof-match-ai/blob/f2c4aaf2880d2896e9c3bba1d9f8c20bb3b49f7c/src/prof-match-ia.ts#L62)
Why is this necessary?

[containerEl.createEl("h2", {](https://github.com/ACSancheZ/prof-match-ai/blob/f2c4aaf2880d2896e9c3bba1d9f8c20bb3b49f7c/src/plugin-settings.ts#L39-L41)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[containerEl.createEl("h2", {](https://github.com/ACSancheZ/prof-match-ai/blob/f2c4aaf2880d2896e9c3bba1d9f8c20bb3b49f7c/src/plugin-settings.ts#L96-L98)
For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```
and [avoid "configurations" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

**Comment by ACSancheZ** [comment]
Hi Johannes,

Thank you for the wonderful work to Obsidian!

I have a question about the folling topic:
"name": "IA Curriculum Maker",
<https://github.com/ACSancheZ/prof-match-ai/blob/f2c4aaf2880d2896e9c3bba1d9f8c20bb3b49f7c/manifest.json#L3>
The README says "AI" but this says "IA", which one is correct.
- The correct answer is AI (Artificial Intelligence). I misspell it due my
native language. To maintain coherence I may change the id from
"ia-cv-maker" to "ai-cv-maker", should I create a new PR or update it?

The observations below were fixed.

All the best.

*Antonio Sanchez*
Cel: +34 684-332476
Skype: aacsanchez
Linked-in: https://www.linkedin.com/in/antoniocsanchez/

"O principal objetivo das pessoas nesse século é a busca por sentido" -
Guilherme Freire
"Loucura é viver a vida assim sem aventura"



Em seg., 17 de jun. de 2024 às 15:30, Johannes Theiner <
***@***.***> escreveu:

**Comment by joethei** [comment]
Update this PR.

**Comment by ACSancheZ** [comment]
> Update this PR.

Done!

**Comment by joethei** [comment]
The website linked in the `authorUrl` and `fundingUrl` still does not work.

**Pull request closed without merging**
