### PR TITLE
Add Discordian theme

### PR DESCRIPTION
**Pull request by radekkozak**
Signed-off-by: Radek Kozak <radoslaw.kozak@gmail.com>

### CODE REVIEW

**Comment by ericaxu** [comment]
Amazing theme! Do you want to add [the plugin](https://github.com/radekkozak/discordian-plugin) as well?

**Comment by radekkozak** [comment]
Thank you for the kind word Erica @ericaxu  ! As to plugin - yes - that would be lovely ! 

I saw the conflict with recent changes - not sure what's your policy here but as it is my own branch i resolved via force push so you could maintain clean commit history. Hope that's ok ;)

**Comment by ericaxu** [comment]
Looks good! There's a missing comma in `community-css-themes.json` around line 327, could you fix that before I can merge it? Thanks!

**Comment by radekkozak** [comment]
Ah yes, indeed, missed it somehow - sorry for that. All should be corrected now

**Comment by ericaxu** [comment]
Great, thanks!

**Pull request merged**
