### PR TITLE
Add plugin: Fontsource

### PR DESCRIPTION
**Pull request by ayuhito**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/fontsource/obsidian-fontsource

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[# Obsidian Fontsource](https://github.com/fontsource/obsidian-fontsource/blob/b55b0989ef24d876852777e8bc186c04b3f3e9e6/README.md#L1)
Please don't call it "Obsidian Fontsource" here.

[containerEl.createEl('h3', { text: 'Imported fonts' });](https://github.com/fontsource/obsidian-fontsource/blob/b55b0989ef24d876852777e8bc186c04b3f3e9e6/src/settings.ts#L58)
For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```

**Comment by ayuhito** [comment]
Hi @joethei, I addressed all other concerns in my latest commits and replaced the old release with the fixes.

> [# Obsidian Fontsource](https://github.com/fontsource/obsidian-fontsource/blob/b55b0989ef24d876852777e8bc186c04b3f3e9e6/README.md#L1) Please don't call it "Obsidian Fontsource" here.

I feel I do need to distinguish the repository itself from the [main repository](https://github.com/fontsource/fontsource). Can you suggest a typical alternative for situations like this?

**Comment by joethei** [comment]
"Fontsource for Obsidian" would be one way to name it.

**Comment by ayuhito** [comment]
I've made the appropriate changes. Thanks for your input!

**Pull request merged**
