### PR TITLE
Add plugin: Embed & Edit Code

### PR DESCRIPTION
**Pull request by GavinRigsby**
# I am submitting a new Community Plugin

## Repo URL

https://github.com/GavinRigsby/obsidian-embed-and-edit-code

Link to my plugin:

## Release Checklist
- [X] I have tested the plugin on
  - [X]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [X] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by GavinRigsby** [comment]
For not using innerhtml [[1](https://github.com/gavinrigsby/obsidian-embed-and-edit-code/blob/a73a9d556a04628f27ec1540591b72e3b085fc6e/src/main.ts#L399)] cold not be updated as svg is not valid for createEl.

If there is another way that I can supply my SVG to my button's html content let me know. 
This svg is static and does not pose a security issue as no user input is included.

**Comment by joethei** [comment]
You can just do `setIcon(refreshButton, 'refresh-cw')`
https://docs.obsidian.md/Plugins/User+interface/Icons

**Comment by GavinRigsby** [comment]
> You can just do `setIcon(refreshButton, 'refresh-cw')` https://docs.obsidian.md/Plugins/User+interface/Icons

Trying this in my code for my codeblock it does some weird filling. 
Copying the SVG resulting from this refresh-ccw to the page for obsidian to parse it shows correctly. 
I will try some other Icons but there is some bug in how the codeblock is handling the svg.

image

**Comment by GavinRigsby** [comment]
Fixed the issue by adding a new custom Icon that does not have this issue (will remove if bug is resolved in the future).

**Pull request closed without merging**
