### PR TITLE
Adding Everblush Theme

### PR DESCRIPTION
**Pull request by Mangeshrex**
[Everblush](https://github.com/Everblush) Everblush is an Independent Theme and Dark theme made for productive work experience. 

## Preview 
Sat Apr 23 07:35:21 PM IST 2022

### CODE REVIEW

**Comment by ericaxu** [comment]
I only saw `preview.png` but no `preview-everblush.png`. Could you either update the PR or your repository? Thanks.

**Comment by Mangeshrex** [comment]
you want me to change the name of while to preview-everblush.png?

**Comment by ericaxu** [comment]
> you want me to change the name of while to preview-everblush.png?

The file referenced in the "screenshot" field doesn't exist under https://github.com/Everblush/Obsidian

Please fix either the PR or your repo so the screenshot can show up in the store, thank you!

**Comment by Mangeshrex** [comment]
Ohh so you want me to add a good screenshot?

**Comment by ericaxu** [comment]
> Ohh so you want me to add a good screenshot?

No, we just need consistent names. In your repo it's called `preview.png` but in the JSON file you wrote `preview-everblush.png`.

Nevermind, I'll just merge it and fix it myself.

**Comment by Mangeshrex** [comment]
Aaa you could have just told json file and repo file names differ. I just got confused. 
Sorry btw

**Comment by tingmelvin** [comment]
@Mangeshrex Is the removal of your Obsidian theme/your repo permanent by the way? If so, I'll request for Everblush to be removed from the `.json`.

**Comment by Mangeshrex** [comment]
ahh i just wanted to add my theme to the marketplace idk whether if its done or not

**Pull request merged**
