### PR TITLE
Add Tenki Plugin

### PR DESCRIPTION
**Pull request by ms3056**
# I am submitting a new Community Plugin

## Repo URL
ms3056/Tenki

Link to my plugin: https://github.com/ms3056/Tenki

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["authorUrl": "",](https://github.com/ms3056/Tenki/blob/871245f72697ca67db12a83ebdeca44bbb718b0c/manifest.json#L8)
This should always be set, if you don't have a website use your GitHub profile.

[--background: #1c2732;](https://github.com/ms3056/Tenki/blob/871245f72697ca67db12a83ebdeca44bbb718b0c/styles.css#L2-L14)
These variable names are too generic, you should make them unique to your plugin.
You should also see if you can find one of the inbuild variables for your case, if a user uses a community theme your plugin has a higher chance of adapting to it's color scheme.
<https://docs.obsidian.md/Reference/CSS+variables/CSS+variables>

[font-family: "Roboto", sans-serif;](https://github.com/ms3056/Tenki/blob/871245f72697ca67db12a83ebdeca44bbb718b0c/styles.css#L19)
Same thing with your font here, and many of the paddings & margins.

[const checkLayoutInterval = setInterval(async () => {](https://github.com/ms3056/Tenki/blob/871245f72697ca67db12a83ebdeca44bbb718b0c/main.ts#L93-L107)
This can be simplified to the below, no need to check on an interval:
```ts
this.app.workspace.onLayoutReady(async () => {
    await this.initView();
});
```

[const response = await axios.get<WeatherAPIResponse>(WEATHER_API_URL);](https://github.com/ms3056/Tenki/blob/871245f72697ca67db12a83ebdeca44bbb718b0c/main.ts#L190)
I would recommend using the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

[const currentIconImg = document.createElement("img");](https://github.com/ms3056/Tenki/blob/871245f72697ca67db12a83ebdeca44bbb718b0c/main.ts#L236-L240)
This could also be written as (you don't need to change this):
```ts
createEl('img', {cls: 'current-icon', attr: {src: `http:${currentIcon}`, alt: 'Weather Icon'}});
```

**Comment by ms3056** [comment]
Changes made - please review.

**Comment by joethei** [comment]
Hi, sorry for the delay,

[function debounce(func: (...args: any[]) => void, wait: number) {](https://github.com/ms3056/Tenki/blob/73e5023325502576dadea352fffc3e4d1b2395e7/main.ts#L33-L47)
The Obsidian API already includes a function of the same name that does the same.

[updateInterval: NodeJS.Timeout | null = null;](https://github.com/ms3056/Tenki/blob/73e5023325502576dadea352fffc3e4d1b2395e7/main.ts#L89)
Use a regular number here, and use `window.setTimeout` everywhere.

[const checkLayoutInterval = setInterval(async () => {](https://github.com/ms3056/Tenki/blob/73e5023325502576dadea352fffc3e4d1b2395e7/main.ts#L121-L127)
Remove this code.

[cls: "recent-files-donation",](https://github.com/ms3056/Tenki/blob/73e5023325502576dadea352fffc3e4d1b2395e7/main.ts#L532)
Wrong class name.
Also, the donation information is usually at the bottom of the settings.

**Comment by ms3056** [comment]
#2110 

In addition to the requested changes below I made a slight change to the refresh code.

[function debounce(func: (...args: any[]) => void, wait: number) {](https://github.com/ms3056/Tenki/blob/73e5023325502576dadea352fffc3e4d1b2395e7/main.ts#L33-L47)
The Obsidian API already includes a function of the same name that does the same.

Response: code change implemented in 0.7.5

[updateInterval: NodeJS.Timeout | null = null;](https://github.com/ms3056/Tenki/blob/73e5023325502576dadea352fffc3e4d1b2395e7/main.ts#L89)
Use a regular number here, and use window.setTimeout everywhere.

Response: code change implemented in 0.7.5

[const checkLayoutInterval = setInterval(async () => {](https://github.com/ms3056/Tenki/blob/73e5023325502576dadea352fffc3e4d1b2395e7/main.ts#L121-L127)
Remove this code.

Response: code change implemented in 0.7.5

[cls: "recent-files-donation",](https://github.com/ms3056/Tenki/blob/73e5023325502576dadea352fffc3e4d1b2395e7/main.ts#L532)
Wrong class name.
Also, the donation information is usually at the bottom of the settings.

Response: code change implemented in 0.7.5

**Pull request merged**
