### PR TITLE
plugin: obsidian-underline

### PR DESCRIPTION
**Pull request by Benature**
# [x] I am submitting a new Community Plugin

## Repo URL
https://github.com/Benature/obsidian-underline

## Release Checklist

- [ ] I have tested this on Windows, macOS, and Linux _(if applicable)_
- [x] Github release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - `styles.css` _(optional)_
- [x] Github release name matches the exact version number specified in your manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.

### CODE REVIEW

**Comment by ericaxu** [comment]
https://github.com/Benature/obsidian-underline/blob/main/main.ts#L6
Did you mean to delete this?

https://github.com/Benature/obsidian-underline/blob/main/main.ts#L26
Did you want to continue to automatically put clipboard text between `<u>` and `</u>`?

https://github.com/Benature/obsidian-underline/blob/main/main.ts#L26
I think it would be better if the caret position would be adjusted to be between `<u>` and `</u>`. What do you think?

**Comment by Benature** [comment]
1. yes, I've deleted this line
2. no, and I've deleted `clipboard` related code
3. yes, I've updated the code so the cursor position will be between `<u>` and `</u>` if no text is selected.

thank you

**Comment by ericaxu** [comment]
Looks good to me! Albeit I haven't tested it.

@lishid please take a look and see if it's ready.

**Comment by Benature** [comment]
@lishid Thanks for your review.

I've updated the code and released it under 0.0.3

**Pull request merged**
