### PR TITLE
add Hide Sidebars on Window Resize plugin

### PR DESCRIPTION
**Pull request by NomarCub**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/NomarCub/obsidian-hide-sidebars-on-window-resize

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Since this is a fork of a existing unmaintained plugin,
could you try and contact the author,
if they are maybe open to transfering the existing plugin entry over to your repo?

**Comment by NomarCub** [comment]
I tried before [here](https://github.com/mybuddymichael/obsidian-hide-sidebars-when-narrow/pull/5), but he wasn't responsive since April.

I left a comment again, but if he doesn't respond in like a week I see no reason to try more.

**Comment by NomarCub** [comment]
The week has passed. Should this be a new plugin then, or a continuation of the old entry?

**Comment by joethei** [comment]
You are free to take over the old plugin entry, as long as you keep the credits to the original author in the author field.
You can just change the entry in this PR.

**Comment by NomarCub** [comment]
Should the author stay the same, or could it be like `"author": "NomarCub, Michael Hanson"`?
Does the id need to be the same to keep continuity?
Should the new repo start with the next semver patch (1.0.3) for continuity?

**Comment by joethei** [comment]
Use something like the second version for the author field.
Keep the ID, so users of the old plugin can update.
And do use a higher version number for the release,

**Comment by NomarCub** [comment]
I think it's done.

**Comment by liamcain** [comment]
- [this.registerDomEvent(window, 'resize', (_) => {](https://github.com/NomarCub/obsidian-hide-sidebars-on-window-resize/blob/076f52b963ed59fa0f1c15083a47a48a156c0bda/src/main.ts#L18-L20) there's a `"resize"` event in the API if you want to use that instead. It is already debounced so it could simplify your code a little bit. <https://github.com/obsidianmd/obsidian-api/blob/ff121cd409350d3afe39b08420f468d8aaee925e/obsidian.d.ts#L3867>

**Pull request merged**
