### PR TITLE
Add Quick note plugin

### PR DESCRIPTION
**Pull request by jamesgreenblue**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/jamesgreenblue/obsidian-quicknote

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by jamesgreenblue** [comment]
Also, is [Add 'Quick note' quick action to Obsidian app icon on iOS Home Screen and App Library #1](https://github.com/jamesgreenblue/obsidian-quicknote/issues/1) technically achievable from an Obsidian plug-in?

I've searched around and can't find any clues so would be incredibly grateful for Obsidian dev insight (either here or on the issue directly). If it is possible please point me in the direction of documentation or sample code that I can work from.

**Comment by joethei** [comment]
> Also, is https://github.com/jamesgreenblue/obsidian-quicknote/issues/1 technically achievable from an Obsidian plug-in?
No, that's no possible from a plugin.


[id: "jgb-create-quick-note",](https://github.com/jamesgreenblue/obsidian-quicknote/blob/a70903b3009bccb1f52001c9b58925a53cdb2097/main.js#L28)
The id does not have to be unique, Obsidian will automatically prefix it with the plugin id internally.

[containerEl.createEl("h1", {](https://github.com/jamesgreenblue/obsidian-quicknote/blob/a70903b3009bccb1f52001c9b58925a53cdb2097/main.js#L81-L83)
[Avoid adding a top-level heading in the settings tab, such as the name of your plugin](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by jamesgreenblue** [comment]
Hi @joethei, thank you for your review – I have implemented the requested changes and released [1.0.1](https://github.com/jamesgreenblue/obsidian-quicknote/releases/tag/1.0.1)

**Comment by 6txri** [comment]
Hi @jamesgreenblue, great work—seriously!

One MAJOR improvement would be the ability to use a keyboard shortcut when away from the Obsidian app and be able to pop up the quick note, instead of having to go down in the dock and right click the Obsidian app. Would that be possible? I tried making it work using the Mac's System Settings along Obsidian's hotkeys, but wasn't able to. 

Many thanks in advance!

**Pull request merged**
