### PR TITLE
Add plugin: Sync to Hugo

### PR DESCRIPTION
**Pull request by crayhuang**
Repo URL

Link to my plugin: https://github.com/crayhuang/Obsidian-Hugo-Sync

Release Checklist

I have tested the plugin on
Windows
macOS
Linux
Android (if applicable)
iOS (if applicable)
My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
main.js
manifest.json
styles.css (optional)
GitHub release name matches the exact version number specified in my manifest.json (Note: Use the exact version number, don't include a prefix v)
The id in my manifest.json matches the id in the community-plugins.json file.
My README.md describes the plugin's purpose and provides clear usage instructions.
I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
I have added a license in the LICENSE file.
My project respects and is compatible with the original license of any code from other plugins that I'm using.
I have given proper attribution to these other projects in my README.md.

### CODE REVIEW

**Comment by joethei** [comment]
What sets your plugin apart from the other Hugo related plugins?

Remove the `node_modules` folder from the repo and add it to the `.gitignore`, it should never be uploaded to git.

["main": "main.js",](https://github.com/crayhuang/Obsidian-Hugo-Sync/blob/8efaaeb9e43ce3e00c5d0090e10f1c2fb98f78a1/manifest.json#L10-L11)
These are not valid inside of a manifest file, remove them.

[import * as fs from 'fs';](https://github.com/crayhuang/Obsidian-Hugo-Sync/blob/8efaaeb9e43ce3e00c5d0090e10f1c2fb98f78a1/main.ts#L2-L3)
These imports are only available from a Node.js runtime, which means that this will throw errors on Mobile (that's a problem since you have `isDesktopOnly` marked as `false` in your manifest.json file.

[console.log('Syncing selected files to Hugo...');](https://github.com/crayhuang/Obsidian-Hugo-Sync/blob/8efaaeb9e43ce3e00c5d0090e10f1c2fb98f78a1/main.ts#L63), [console.log('Starting to sync file:', file.name);](https://github.com/crayhuang/Obsidian-Hugo-Sync/blob/8efaaeb9e43ce3e00c5d0090e10f1c2fb98f78a1/main.ts#L128), [console.log(`Synced file: ${file.name}`);](https://github.com/crayhuang/Obsidian-Hugo-Sync/blob/8efaaeb9e43ce3e00c5d0090e10f1c2fb98f78a1/main.ts#L135), 

[containerEl.createEl('h2', {text: this.plugin.lang.settings.pluginName});](https://github.com/crayhuang/Obsidian-Hugo-Sync/blob/8efaaeb9e43ce3e00c5d0090e10f1c2fb98f78a1/main.ts#L238)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[new Setting(containerEl)](https://github.com/crayhuang/Obsidian-Hugo-Sync/blob/8efaaeb9e43ce3e00c5d0090e10f1c2fb98f78a1/main.ts#L273-L283)
Get the configured language via the below and remove this code:
```ts
import {moment} from "obsidian";
moment.locale();
```

**Comment by crayhuang** [comment]
> What sets your plugin apart from the other Hugo related plugins?
> 
> Remove the `node_modules` folder from the repo and add it to the `.gitignore`, it should never be uploaded to git.
> 
> ["main": "main.js",](https://github.com/crayhuang/Obsidian-Hugo-Sync/blob/8efaaeb9e43ce3e00c5d0090e10f1c2fb98f78a1/manifest.json#L10-L11) These are not valid inside of a manifest file, remove them.
> 
> [import * as fs from 'fs';](https://github.com/crayhuang/Obsidian-Hugo-Sync/blob/8efaaeb9e43ce3e00c5d0090e10f1c2fb98f78a1/main.ts#L2-L3) These imports are only available from a Node.js runtime, which means that this will throw errors on Mobile (that's a problem since you have `isDesktopOnly` marked as `false` in your manifest.json file.
> 
> [console.log('Syncing selected files to Hugo...');](https://github.com/crayhuang/Obsidian-Hugo-Sync/blob/8efaaeb9e43ce3e00c5d0090e10f1c2fb98f78a1/main.ts#L63), [console.log('Starting to sync file:', file.name);](https://github.com/crayhuang/Obsidian-Hugo-Sync/blob/8efaaeb9e43ce3e00c5d0090e10f1c2fb98f78a1/main.ts#L128), [console.log(`Synced file: ${file.name}`);](https://github.com/crayhuang/Obsidian-Hugo-Sync/blob/8efaaeb9e43ce3e00c5d0090e10f1c2fb98f78a1/main.ts#L135),
> 
> [containerEl.createEl('h2', {text: this.plugin.lang.settings.pluginName});](https://github.com/crayhuang/Obsidian-Hugo-Sync/blob/8efaaeb9e43ce3e00c5d0090e10f1c2fb98f78a1/main.ts#L238) [Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)
> 
> [new Setting(containerEl)](https://github.com/crayhuang/Obsidian-Hugo-Sync/blob/8efaaeb9e43ce3e00c5d0090e10f1c2fb98f78a1/main.ts#L273-L283) Get the configured language via the below and remove this code:
> 
> ```ts
> import {moment} from "obsidian";
> moment.locale();
> ```

I have already handled these feedback. Please help to check it again

**Comment by crayhuang** [comment]
> What sets your plugin apart from the other Hugo related plugins?
> 
> Remove the `node_modules` folder from the repo and add it to the `.gitignore`, it should never be uploaded to git.
> 
> ["main": "main.js",](https://github.com/crayhuang/Obsidian-Hugo-Sync/blob/8efaaeb9e43ce3e00c5d0090e10f1c2fb98f78a1/manifest.json#L10-L11) These are not valid inside of a manifest file, remove them.
> 
> [import * as fs from 'fs';](https://github.com/crayhuang/Obsidian-Hugo-Sync/blob/8efaaeb9e43ce3e00c5d0090e10f1c2fb98f78a1/main.ts#L2-L3) These imports are only available from a Node.js runtime, which means that this will throw errors on Mobile (that's a problem since you have `isDesktopOnly` marked as `false` in your manifest.json file.
> 
> [console.log('Syncing selected files to Hugo...');](https://github.com/crayhuang/Obsidian-Hugo-Sync/blob/8efaaeb9e43ce3e00c5d0090e10f1c2fb98f78a1/main.ts#L63), [console.log('Starting to sync file:', file.name);](https://github.com/crayhuang/Obsidian-Hugo-Sync/blob/8efaaeb9e43ce3e00c5d0090e10f1c2fb98f78a1/main.ts#L128), [console.log(`Synced file: ${file.name}`);](https://github.com/crayhuang/Obsidian-Hugo-Sync/blob/8efaaeb9e43ce3e00c5d0090e10f1c2fb98f78a1/main.ts#L135),
> 
> [containerEl.createEl('h2', {text: this.plugin.lang.settings.pluginName});](https://github.com/crayhuang/Obsidian-Hugo-Sync/blob/8efaaeb9e43ce3e00c5d0090e10f1c2fb98f78a1/main.ts#L238) [Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)
> 
> [new Setting(containerEl)](https://github.com/crayhuang/Obsidian-Hugo-Sync/blob/8efaaeb9e43ce3e00c5d0090e10f1c2fb98f78a1/main.ts#L273-L283) Get the configured language via the below and remove this code:
> 
> ```ts
> import {moment} from "obsidian";
> moment.locale();
> ```

Hi there

Could you give me a response? Thanks

**Comment by joethei** [comment]
You have not removed all of the `console.log` call's I have flagged.

**Comment by crayhuang** [comment]
> You have not removed all of the `console.log` call's I have flagged.

I have removed all of th econsole.log already. Please check.

**Comment by joethei** [comment]
sorry for the delay.

[ "repo": "https://github.com/crayhuang/Obsidian-Hugo-Sync"]( "repo": "https://github.com/crayhuang/Obsidian-Hugo-Sync")
This is not valid in the manifest, remove it.

**Comment by crayhuang** [comment]
> sorry for the delay.
> 
> [ "repo": "https://github.com/crayhuang/Obsidian-Hugo-Sync"](https://github.com/crayhuang/Obsidian-Hugo-Sync/blob/4a5c7d5d34ff5e71ebed5e2f315f7bc387a3b21e/manifest.json#L10) This is not valid in the manifest, remove it.

Already removed. Please check again.

**Pull request merged**
