### PR TITLE
Add plugin: Letterboxd Diary RSS Sync

### PR DESCRIPTION
**Pull request by Fleker**
I've created my first Obsidian plugin which works in a development vault and I'd like to submit it to the directory.

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Fleker/letterboxd-for-obsidian

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [~] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Fleker** [comment]
I have adjusted these fields.

**Comment by joethei** [comment]
["minAppVersion": "0.15.0",](https://github.com/Fleker/letterboxd-for-obsidian/blob/d6de8f791fd16c14027b886d7203dc5f0cc1c70a/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

["description": "This is a way to sync your Letterboxd diary plugin to Obsidian",](https://github.com/Fleker/letterboxd-for-obsidian/blob/d6de8f791fd16c14027b886d7203dc5f0cc1c70a/manifest.json#L6)
Avoid including sentences like "This is a plugin for Obsidian that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[const { XMLParser } = require("fast-xml-parser");](https://github.com/Fleker/letterboxd-for-obsidian/blob/d6de8f791fd16c14027b886d7203dc5f0cc1c70a/main.ts#L3)
Stick to one import style

[// Remember to rename these classes and interfaces!](https://github.com/Fleker/letterboxd-for-obsidian/blob/d6de8f791fd16c14027b886d7203dc5f0cc1c70a/main.ts#L4)
Remove this comment.

[username: 'default'](https://github.com/Fleker/letterboxd-for-obsidian/blob/d6de8f791fd16c14027b886d7203dc5f0cc1c70a/main.ts#L47)
This should be empty by default

[id: 'letterboxd-sync',](https://github.com/Fleker/letterboxd-for-obsidian/blob/d6de8f791fd16c14027b886d7203dc5f0cc1c70a/main.ts#L57)
No need to make this unique to your plugin, Obsidian will automatically make sure that this does not conflict with other plugins.

[name: 'Sync Letterboxd Diary',](https://github.com/Fleker/letterboxd-for-obsidian/blob/d6de8f791fd16c14027b886d7203dc5f0cc1c70a/main.ts#L58)
This can also be shorter, atm it will show up as `Letterboxd Diary RSS Sync: Sync Letterboxd Diary` in the command pallete or settings

[.setName('Letterboxd Username')](https://github.com/Fleker/letterboxd-for-obsidian/blob/d6de8f791fd16c14027b886d7203dc5f0cc1c70a/main.ts#L116)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by Fleker** [comment]
Thank you for your prompt feedback. I've made these minor changes to my plugin and released a new version.

**Comment by Fleker** [comment]
Fixed [the latest release](https://github.com/Fleker/letterboxd-for-obsidian/releases/tag/1.0.8) with the required files.

**Pull request merged**
