### PR TITLE
Add plugin: Todo.txt Codeblocks

### PR DESCRIPTION
**Pull request by benjamonnguyen**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/benjamonnguyen/obsidian-todotxt-codeblocks

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
- [x] I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[Copyright (c) [year] [fullname]](https://github.com/benjamonnguyen/obsidian-todotxt-codeblocks/blob/aeac664aa2fbf2ad243e42a154454030785b6817/LICENSE#L3)
Please fill this.

[static NAME = 'obsidian-todotxt-codeblocks';](https://github.com/benjamonnguyen/obsidian-todotxt-codeblocks/blob/aeac664aa2fbf2ad243e42a154454030785b6817/src/main.ts#L19)
Please use the actual plugin name here, and not the repo name.

[id: 'create-new-todotxt-task-cmd',](https://github.com/benjamonnguyen/obsidian-todotxt-codeblocks/blob/aeac664aa2fbf2ad243e42a154454030785b6817/src/command/createNewTaskCmd.ts#L7)
You don't need to include the plugin identifier here, the id can just be `create-new-task`

**Comment by benjamonnguyen** [comment]
@joethei Thanks for the review, I've resolved the change requests.

**Comment by liamcain** [comment]
- [await this.saveData(this.settings).then(](https://github.com/benjamonnguyen/obsidian-todotxt-codeblocks/blob/3da757dee037f5c5783249b54608e3e680dea1d8/src/main.ts#L84) why are you mixing async/await with .then()? If you're using await, you can omit the promise chaining. Also, there's really no reason your readonly version of settings needs to be assigned _after_ the save resolves
- [this.registerDomEvent(document, 'keyup', (event: KeyboardEvent) => {](https://github.com/benjamonnguyen/obsidian-todotxt-codeblocks/blob/3da757dee037f5c5783249b54608e3e680dea1d8/src/main.ts#L47) you should remove this. This isn't related to your plugin and will interact with all buttons in the app and will likely cause hard to track down bugs

**Comment by benjamonnguyen** [comment]
@liamcain The UX feels really clunky without the "Enter" to submit behavior, especially when creating many todos.

I've added a check in case the "mod-cta" class shows up anywhere else:
```js
this.registerDomEvent(document, 'keyup', (event: KeyboardEvent) => {
	const modalSubmitBtn = (
		document.getElementsByClassName('todotxt-modal').item(0) as HTMLElement | null
	)
		?.getElementsByClassName('mod-cta')
		.item(0) as HTMLButtonElement | null;
	if (modalSubmitBtn && event.key === 'Enter') {
		modalSubmitBtn.click();
	}
});
```

Let me know if this is acceptable.

**Comment by liamcain** [comment]
Oh, I didn't understand what it was for. If this is for a modal, you should use Modal.scope <https://github.com/obsidianmd/obsidian-api/blob/249eb773347588f4e9fec7c600e1904cd9240fcb/obsidian.d.ts#L2606>

Something like this:

```
		scope.register([], 'Enter', (evt: KeyboardEvent) => {
			if (evt.isComposing) {
				return;
			}
				const actionBtn = document
					.getElementsByClassName('mod-cta')
					.item(0) as HTMLButtonElement | null;
				actionBtn?.click();
		});
```

You can add that to your base modal class

**Comment by benjamonnguyen** [comment]
@liamcain Thanks! I've pushed the changes and updated my release

**Pull request merged**
