### PR TITLE
Add plugin: Gistr

### PR DESCRIPTION
**Pull request by Aetherinox**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Aetherinox/obsidian-gistr

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Aetherinox** [comment]
Just a note, noticed others submitting addons and it going through the process of renaming the plugin and doing the initial checks. It appears mine has not gone through that yet. Not sure if the actions are just busy.

**Comment by joethei** [comment]
[elm.createEl( "h1", { text: lng( "cfg_modal_title" ) } )](https://github.com/Aetherinox/obsidian-gistr/blob/1a25031a62314e424cad9e7eccd27e35be3e4924/src/main.ts#L213)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[const Tab_GN = elm.createEl( "h2", { text: lng( "cfg_tab_ge_title" ), cls: `gistr-settings-header${ this.Hide_General?" isfold" : "" }` } )](https://github.com/Aetherinox/obsidian-gistr/blob/1a25031a62314e424cad9e7eccd27e35be3e4924/src/main.ts#L250), 

For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```

[cfg_tab_ge_title:                   'General Settings',](https://github.com/Aetherinox/obsidian-gistr/blob/1a25031a62314e424cad9e7eccd27e35be3e4924/src/lang/locale/en.ts#L19), [cfg_tab_ge_header:                  'General settings for Gistr.',](https://github.com/Aetherinox/obsidian-gistr/blob/1a25031a62314e424cad9e7eccd27e35be3e4924/src/lang/locale/en.ts#L20)
[Don't use a "general" heading in your settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[cfg_tab_og_title:                   'OpenGist Settings',](https://github.com/Aetherinox/obsidian-gistr/blob/1a25031a62314e424cad9e7eccd27e35be3e4924/src/lang/locale/en.ts#L21), [cfg_tab_gh_title:                   'Github Settings',](https://github.com/Aetherinox/obsidian-gistr/blob/1a25031a62314e424cad9e7eccd27e35be3e4924/src/lang/locale/en.ts#L23)
[Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

[cfg_tab_ge_keyword_name:            'Trigger Keyword',](https://github.com/Aetherinox/obsidian-gistr/blob/1a25031a62314e424cad9e7eccd27e35be3e4924/src/lang/locale/en.ts#L26), [cfg_tab_og_cblk_light_name:         'Codeblock Background Color (Light)',](https://github.com/Aetherinox/obsidian-gistr/blob/1a25031a62314e424cad9e7eccd27e35be3e4924/src/lang/locale/en.ts#L33), [cfg_tab_og_cblk_light_name:         'Codeblock Background Color (Light)',](https://github.com/Aetherinox/obsidian-gistr/blob/1a25031a62314e424cad9e7eccd27e35be3e4924/src/lang/locale/en.ts#L33), [cfg_tab_og_sb_light_name:           'Scrollbar Track Color (Light)',](https://github.com/Aetherinox/obsidian-gistr/blob/1a25031a62314e424cad9e7eccd27e35be3e4924/src/lang/locale/en.ts#L37), [cfg_tab_og_sb_dark_name:            'Scrollbar Track Color (Dark)',](https://github.com/Aetherinox/obsidian-gistr/blob/1a25031a62314e424cad9e7eccd27e35be3e4924/src/lang/locale/en.ts#L39), [cfg_tab_og_padding_top_name:        'Top Padding',](https://github.com/Aetherinox/obsidian-gistr/blob/1a25031a62314e424cad9e7eccd27e35be3e4924/src/lang/locale/en.ts#L41), [cfg_tab_og_padding_bottom_name:     'Bottom Padding',](https://github.com/Aetherinox/obsidian-gistr/blob/1a25031a62314e424cad9e7eccd27e35be3e4924/src/lang/locale/en.ts#L43), [cfg_tab_og_theme_name:              'Color Theme',](https://github.com/Aetherinox/obsidian-gistr/blob/1a25031a62314e424cad9e7eccd27e35be3e4924/src/lang/locale/en.ts#L45), [cfg_tab_su_gs_name:                 'Getting Started',](https://github.com/Aetherinox/obsidian-gistr/blob/1a25031a62314e424cad9e7eccd27e35be3e4924/src/lang/locale/en.ts#L64), [gs_btn_settings_open:               'Open Settings',](https://github.com/Aetherinox/obsidian-gistr/blob/1a25031a62314e424cad9e7eccd27e35be3e4924/src/lang/locale/en.ts#L95), [base_underdev_title:                'Feature Under Development',](https://github.com/Aetherinox/obsidian-gistr/blob/1a25031a62314e424cad9e7eccd27e35be3e4924/src/lang/locale/en.ts#L97)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by Aetherinox** [comment]
Revisions made.

**Comment by joethei** [comment]
Please remove the `dist` folder from the repo and add it to your .gitignore. Compiled release files shouldn't get mixed with source code in your commits and should go to the releases files instead.

**Comment by Aetherinox** [comment]
Done

**Pull request merged**
