### PR TITLE
Added Plugin Groups to Community-plugins.json

### PR DESCRIPTION
**Pull request by Mocca101**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
[Plugin Groups Github](https://github.com/Mocca101/obsidian-plugin-groups
)
## Release Checklist
- [X] I have tested the plugin on
  - [X]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [X]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by liamcain** [comment]
- [app](https://github.com/Mocca101/obsidian-plugin-groups/blob/949c1dbb2b47a3b0c01b44cfea5ea664890baa04/src/Managers/PluginManager.ts#L124) It's highly discouraged that you use the global app instance in your plugin. It's currently accessible from the global context for debugging purposes, and might be removed in the future. Instead, you should use the reference to App that you have from your plugin instance.
- [...installedPlugins](https://github.com/Mocca101/obsidian-plugin-groups/blob/949c1dbb2b47a3b0c01b44cfea5ea664890baa04/src/Managers/PluginManager.ts#L49) filter already creates a copy of the list, no need to clone the list first
- [window.performance.now() / 1000](https://github.com/Mocca101/obsidian-plugin-groups/blob/949c1dbb2b47a3b0c01b44cfea5ea664890baa04/main.ts#L33) performance.now is more expensive than Date.now, so unless you need the precision, I suggest you switch to Date.now()

**Comment by Mocca101** [comment]
Thanks for the notes! I've adressed them and they will be in the next release.
Unfortunately I need [window.performance.now() / 1000](https://github.com/Mocca101/obsidian-plugin-groups/blob/949c1dbb2b47a3b0c01b44cfea5ea664890baa04/main.ts#L33) for now. As I haven't found another way to find out how long obsidian has been running ( it is used to check how long obsidian has been running as to not enable "startup" plugins when plugin-groups is being enabled while Obsidian has already been in use for some time e.g. when dis-/re-enabling the plugin). If there is a better way please let me know!

**Comment by liamcain** [comment]
You're saying that `Date.now()` doesn't work for your use case?

**Comment by Mocca101** [comment]
Unfortunately no, Date.now() gives me the current time (since the epoch), but for this usecase I need the time that has passed since Obsidian has started. 
If there is a way to get that or the timestamp of when Obsidian has started I could use that.

**Pull request merged**
