### PR TITLE
Add Nostr Writer plugin 

### PR DESCRIPTION
**Pull request by jamesmagoo**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [https://github.com/jamesmagoo/nostr-writer](https://github.com/jamesmagoo/nostr-writer)

## Release Checklist

- [x]  I have tested the plugin on
    - [ ]  Windows
    - [x]  macOS
    - [ ]  Linux
    - [ ]  Android _(if applicable)_
    - [ ]  iOS _(if applicable)_
- [x]  My GitHub release contains all required files
    - [x]  `main.js`
    - [x]  `manifest.json`
    - [ ]  `styles.css` _(optional)_
- [x]  GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x]  The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x]  My README.md describes the plugin's purpose and provides clear usage instructions.
- [x]  I have read the tips in [https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md) and have self-reviewed my plugin to avoid these common pitfalls.
- [x]  I have added a license in the LICENSE file.
- [x]  My project respects and is compatible with the original license of any code from other plugins that I'm using.  
    I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Please follow the pull request template.

**Comment by jamesmagoo** [comment]
Johannes - please see release 1.0.1 with updates as per your comments & review.

**Comment by jamesmagoo** [comment]
Hey Guys, thanks for your work on this so far! I really appreciate it.

I've got a dumb question - how would changing my repo name to "nostr-writer" effect future releases (or this release) ? I believe it would be easier for me developing locally to have a repo name that matches my manifest.json and this PR ID...

**Comment by jamesmagoo** [comment]
Hey , I messed up a merge 🫣 Could you help me fix this?

**Comment by jamesmagoo** [comment]
Hey guys 😃 is there any update on this?

**Comment by jamesmagoo** [comment]
Hi @joethei , hope you are well & thanks for your work on this so far. Is there any update on this? When will it be available on the plugin store?

**Comment by jamesmagoo** [comment]
Hi @ericaxu - What do I need to do to get this merged & on the plugin store? Or is it just waiting for final review? If I have messed up anywhere I am happy to open a new PR , I'd just like an update. Many thanks - James

**Comment by jamesmagoo** [comment]
🙏

**Comment by liamcain** [comment]
- [getMostRecentLeaf](https://github.com/jamesmagoo/nostr-writer/blob/7df0db45f26dd505f0c1c6af58507c67b90ffed2/src/PublishedView.ts#L141) you shouldn't use getMostRecentLeaf here. Instead you should use getLeaf(). It will take care of if the file is pinned or not for you. It also handles a few other edge cases so it's best to use it for consistency.
- [find((f](https://github.com/jamesmagoo/nostr-writer/blob/7df0db45f26dd505f0c1c6af58507c67b90ffed2/src/PublishedView.ts#L139) it's better to use [`getAbstractFileByPath`](https://github.com/obsidianmd/obsidian-api/blob/902badd38ba907689f0917d7b193f7e33d1284fe/obsidian.d.ts#L3612) instead.

**Comment by jamesmagoo** [comment]
Thanks Liam 🤝

**Pull request merged**
