### PR TITLE
Add plugin: Backlink Cache

### PR DESCRIPTION
**Pull request by mnaoumov**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

https://github.com/mnaoumov/obsidian-backlink-cache

## Release Checklist
- [X] I have tested the plugin on
  - [X]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by liamcain** [comment]
- [getBacklinksForFile](https://github.com/mnaoumov/obsidian-backlink-cache/blob/1838cc0854cc86c5705d6f5239ec8951a32b6fa1/BacklinkCachePlugin.ts#L25) you are monkeypatching getBacklinksForFile but not restoring the original version of the function on unload.

What's the benefit of having this plugin added to the plugin directory? Also what plugins are benefiting from this?

**Comment by mnaoumov** [comment]
> * [getBacklinksForFile](https://github.com/mnaoumov/obsidian-backlink-cache/blob/1838cc0854cc86c5705d6f5239ec8951a32b6fa1/BacklinkCachePlugin.ts#L25) you are monkeypatching getBacklinksForFile but not restoring the original version of the function on unload.
> 

I restore on unload. https://github.com/mnaoumov/obsidian-backlink-cache/blob/master/BacklinkCachePlugin.ts#L70


> What's the benefit of having this plugin added to the plugin directory?

It speeds up Backlinks pane heavily. Also it is helpful for other plugin development, scripting in Developer Console, dataviewjs, Templater, CustomJS

> Also what plugins are benefiting from this?

Based on the code search, the following plugins using that undocumented function

- https://github.com/mnaoumov/obsidian-smart-rename - that's also my plugin
- https://github.com/tadashi-aikawa/obsidian-another-quick-switcher
- https://github.com/jensmtg/influx
- https://github.com/ivan-lednev/obsidian-persistent-links
- https://github.com/deepfates/silicon
- https://github.com/iiz00/obsidian-multiple-notes-outline
- https://github.com/Canna71/obsidian-sets
- https://github.com/jwir3/obsidian-contacts-ng
- https://github.com/mickeydarrenlau/pushkit-darren
- https://github.com/lucasew/obsidian-metadump
- https://github.com/hyfen/obsidian-mention-suggester
- https://github.com/aoout/obsidian-highlighter
- https://github.com/kenlim/influx
- https://github.com/mrjackphil/obsidian-crosslink-between-notes
- https://github.com/fukunee/obsidian-link-master
- https://github.com/HananoshikaYomaru/obsidian-run

**Comment by mnaoumov** [comment]
> Hi there, as this PR has not seen any activity in the last 30 days, it will be closed in 30 days unless there are any updates.

That's beyond my control, I replied to the maintainer's question, and just waiting for his response

**Comment by mnaoumov** [comment]
@liamcain thanks for your feedback. In my last release I addressed some of performance concerns

**Pull request merged**
