### PR TITLE
Add plugin: Clever Search

### PR DESCRIPTION
**Pull request by yan42685**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/yan42685/obsidian-clever-search

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by yan42685** [comment]
/skip

The issues pointed out are very helpful for refining my code, and I have made most of the suggested modifications. However, some of the validations don't seem entirely applicable to the current state of my plugin.

**Limiting the number of `console.log`**
The `console.log` are primarily in the `jest` testing code. Additionally, other logging functions like `console.debug` are filtered using logLevel defined at `src/utils/logger.ts`, which defaults to the `info` log level and allows for custom log level settings. Only minimal information will be printed, avoiding interference with users and other plugin developers.

**Casting to `any`**
This seems necessary in the cases you've identified. If there's a better approach, please let me know, and I will make the changes.

**Assigning styles via JavaScript**
I've provided style setting options in the stylesettings plugin, allowing users to choose their preferred effects. Also, the amount of code that needs to be changed is substantial, and restructuring it might introduce new issues.

**Comment by yan42685** [comment]
Will close and reopen to trigger a new scan.

**Comment by joethei** [comment]
Your manifest is missing the `authorUrl` field.

[this.containerEl.style.display = "block";](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/main.ts#L65-L67), [this.containerEl.style.zIndex = "20";](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/ui/floating-window.ts#L58-L73), [closeButton.innerText = "✖";](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/ui/floating-window.ts#L76-L79)
This should be in the CSS file.

[static sleep(ms: number) {](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/utils/my-lib.ts#L77-L79)
The Obsidian API already exports this as a function.

[const myRemoteDirUrl1 =](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/utils/web/assets-provider.ts#L13-L16), [const tiktokenSourceUrl = unpkgUrl + "@dqbd/tiktoken@1.0.7/tiktoken_bg.wasm";](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/utils/web/assets-provider.ts#L20)
These assets should be bundled and not loaded seperately.

[import { debounce } from "throttle-debounce";](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/ui/MountedModal.svelte#L21)
The Obsidian API already has a `debounce` function.

[new Setting(devSettingContent)](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/services/obsidian/setting-manager.ts#L278-L288)
This should be at the end and not in the middle of the settings.

[const allAbstractFiles = getInstance(Vault).getAllLoadedFiles();](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/services/obsidian/setting-manager.ts#L348-L354)
Use the `getFileByPath` function to check if a file exists, instead of this.

[id: "cs-in-file-search-floating-window",](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/services/obsidian/command-registry.ts#L36), [id: "clever-search-triggerTest",](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/services/obsidian/command-registry.ts#L43), [id: "clever-search-in-file",](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/services/obsidian/command-registry.ts#L53), [id: "cs-toggle-privacy-mode",](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/services/obsidian/command-registry.ts#L65), [id: "clever-search-in-vault",](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/services/obsidian/command-registry.ts#L73), [id: "cs-in-file-search-with-omnisearch-query",](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/services/obsidian/command-registry.ts#L82)
Don't prefix the command id with the plugin id, Obsidian will make sure that there are no conflicts with other plugins.

["Excluded files": "Excluded files",](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/services/obsidian/translations/locale/en.ts#L35), ["Follow Obsidian Excluded Files": "Follow Obsidian Excluded Files",](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/services/obsidian/translations/locale/en.ts#L37), ["For Development": "For Development",](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/services/obsidian/translations/locale/en.ts#L49), ["Support the Project": "Support the Project",](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/services/obsidian/translations/locale/en.ts#L59)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by yan42685** [comment]
> Your manifest is missing the `authorUrl` field.
> 
> [this.containerEl.style.display = "block";](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/main.ts#L65-L67), [this.containerEl.style.zIndex = "20";](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/ui/floating-window.ts#L58-L73), [closeButton.innerText = "✖";](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/ui/floating-window.ts#L76-L79) This should be in the CSS file.
> 
> [static sleep(ms: number) {](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/utils/my-lib.ts#L77-L79) The Obsidian API already exports this as a function.
> 
> [const myRemoteDirUrl1 =](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/utils/web/assets-provider.ts#L13-L16), [const tiktokenSourceUrl = unpkgUrl + "@dqbd/tiktoken@1.0.7/tiktoken_bg.wasm";](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/utils/web/assets-provider.ts#L20) These assets should be bundled and not loaded seperately.
> 
> [import { debounce } from "throttle-debounce";](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/ui/MountedModal.svelte#L21) The Obsidian API already has a `debounce` function.
> 
> [new Setting(devSettingContent)](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/services/obsidian/setting-manager.ts#L278-L288) This should be at the end and not in the middle of the settings.
> 
> [const allAbstractFiles = getInstance(Vault).getAllLoadedFiles();](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/services/obsidian/setting-manager.ts#L348-L354) Use the `getFileByPath` function to check if a file exists, instead of this.
> 
> [id: "cs-in-file-search-floating-window",](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/services/obsidian/command-registry.ts#L36), [id: "clever-search-triggerTest",](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/services/obsidian/command-registry.ts#L43), [id: "clever-search-in-file",](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/services/obsidian/command-registry.ts#L53), [id: "cs-toggle-privacy-mode",](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/services/obsidian/command-registry.ts#L65), [id: "clever-search-in-vault",](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/services/obsidian/command-registry.ts#L73), [id: "cs-in-file-search-with-omnisearch-query",](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/services/obsidian/command-registry.ts#L82) Don't prefix the command id with the plugin id, Obsidian will make sure that there are no conflicts with other plugins.
> 
> ["Excluded files": "Excluded files",](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/services/obsidian/translations/locale/en.ts#L35), ["Follow Obsidian Excluded Files": "Follow Obsidian Excluded Files",](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/services/obsidian/translations/locale/en.ts#L37), ["For Development": "For Development",](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/services/obsidian/translations/locale/en.ts#L49), ["Support the Project": "Support the Project",](https://github.com/yan42685/obsidian-clever-search/blob/415d46f5a6e8e82508f9550386297920e8786f02/src/services/obsidian/translations/locale/en.ts#L59) [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

Thank you for your feedback 😃. I've made the changes as you suggested, but I ran into a bit of a snag. I'm not too familiar with build tools, so I'm unsure how to bundle everything together. Also, it might be better to download to the `userData` directory, right? This way, multiple vaults can share the assets, which would save space.

**Comment by joethei** [comment]
Downloading these files is not recommended, and it will not work on all platforms.
There is a plugin for esbuild that you need to add to be able to bundle .wasm files.

**Comment by yan42685** [comment]
> Downloading these files is not recommended, and it will not work on all platforms. There is a plugin for esbuild that you need to add to be able to bundle .wasm files.

I agree with your point; the plugin you mentioned earlier might be `esbuild-plugin-wasm`. However, `Clever Search` also offers a semantic search feature, which requires the use of a total of 972MB `.zip` files (including `.exe` and embedding models); it seems that ultimately, downloading is necessary. Additionally, I've noticed that a community-released plugin employs the same downloading approach as mine and is compatible with multiple platforms. You can find it here: https://github.com/aidenlx/cm-chs-patch/blob/main/src/install-guide.ts. Please consider allowing me to utilize the same method for downloading assets.

**Comment by joethei** [comment]
Hi, sorry for the late reply,

I don't see any code for Windows specifically, so it seems to me that the file get's downloaded no matter the OS.
The code that is OS independent should be bundled with the plugin.

As for that other plugin, when it was initially submitted everything was bundled, they changed that later.

**Comment by yan42685** [comment]
Hi Joethei,

Transitioning from downloading to bundling would require too many code changes for me, and it's quite difficult for me given my limited abilities. I don't have confidence that I won't encounter issues during the modification process. Therefore, I plan to remove the dependency on OS-independent assets, so they won't need to be downloaded automatically. Would this approach be acceptable?

**Pull request closed without merging**
