### PR TITLE
Add plugin: Cluster

### PR DESCRIPTION
**Pull request by lorens-osman-dev**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/lorens-osman-dev/cluster

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
What do you mean by clustering?
Your README is not clear about that.

[// add status bar text](https://github.com/JackBarker7/obsidian-latexocr/blob/b254c408617bec670ee7968e4e764144a6db6345/main.ts#L21-L24
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link omit this.

[name: "new_brother",](https://github.com/lorens-osman-dev/cluster/blob/2b8346e79b25d343f5426cb7b2b4dd939f23009a/main.ts#L19), [name: "new_son",](https://github.com/lorens-osman-dev/cluster/blob/2b8346e79b25d343f5426cb7b2b4dd939f23009a/main.ts#L28), [name: "new_cluster",](https://github.com/lorens-osman-dev/cluster/blob/2b8346e79b25d343f5426cb7b2b4dd939f23009a/main.ts#L37), [name: "delete_active_note",](https://github.com/lorens-osman-dev/cluster/blob/2b8346e79b25d343f5426cb7b2b4dd939f23009a/main.ts#L46)
Remove the slashes and [use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[/[CLUSTERS]](https://github.com/lorens-osman-dev/cluster/blob/2b8346e79b25d343f5426cb7b2b4dd939f23009a/main.ts#L74)
This folder name will cause problems on Windows, remove `\[]`

[// 1 - Container Element](https://github.com/lorens-osman-dev/cluster/blob/2b8346e79b25d343f5426cb7b2b4dd939f23009a/src/createFamily/svg.ts#L6-L52)
Instead of all this code you can simply do the following, Obsidian already includes the lucide icon set:
```ts
 const con = document.createEl('div');
setIcon(con, 'baby');
return con;
```
Same with all the other functions in this class.

[console.log(evt)](https://github.com/lorens-osman-dev/cluster/blob/2b8346e79b25d343f5426cb7b2b4dd939f23009a/src/createFamily/familyModal.ts#L75)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.


[const getActiveFile = app.workspace.getActiveFile();](https://github.com/lorens-osman-dev/cluster/blob/2b8346e79b25d343f5426cb7b2b4dd939f23009a/src/createFamily/familyModal.ts#L77)
It's highly discouraged that you use the global app instance in your plugin. It's currently accessible from the global context for debugging purposes, and might be removed in the future. Instead, you should use the reference to App that you have from your plugin instance.

**Comment by lorens-osman-dev** [comment]
I fixed the requested changes, Did i need to make another pull request on  [community-plugins.json](https://github.com/lorens-osman-dev/obsidian-releases/blob/master/community-plugins.json) ?

----------------------------
What do you mean by clustering?
Your README is not clear about that.
[done] extra information was added to README

-------------------------------

[// add status bar text](https://github.com/JackBarker7/obsidian-latexocr/blob/b254c408617bec670ee7968e4e764144a6db6345/main.ts#L21-L24
This is meant for links to services like Buy me a coffee, GitHub sponsors and so on, if you don't have such a link omit this.
[done] I don't have such a link, So i omitted this.

-------------------------------

 name: "new_brother",, name: "new_son",, name: "new_cluster",, name: "delete_active_note",
Remove the slashes and use sentence case in UI
[done] slashes removed and sentence case in UI used.

-------------------------------

/[CLUSTERS]
This folder name will cause problems on Windows, remove \[]
[done] removed \[]

-------------------------------

// 1 - Container Element
Instead of all this code you can simply do the following, Obsidian already includes the lucide icon set:

const con = document.createEl('div');
setIcon(con, 'baby');
return con;
Same with all the other functions in this class.
[done] for all lucide icons setIcon() function used, for none lucide icons addIcon() function used

-------------------------------

console.log(evt)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.
[done] unnecessary logging removed .

-------------------------------

const getActiveFile = app.workspace.getActiveFile();
It's highly discouraged that you use the global app instance in your plugin. It's currently accessible from the global context for debugging purposes, and might be removed in the future. Instead, you should use the reference to App that you have from your plugin instance.
[done]

**Comment by lorens-osman-dev** [comment]
Did i need to open new PR ?

**Comment by joethei** [comment]
No, just be patient

**Comment by liamcain** [comment]
- [this.app](https://github.com/lorens-osman-dev/cluster/blob/58003c16c73a8adc17f54c0ab1e2f83b4bfbedb1/src/createFamily/buttons.ts#L12) `this` doesn't exist, you're in a top level function. This is likely defaulting to the `global` obj which is an anti-pattern.
- [this.app.workspace.iterateAllLeaves((leaf: WorkspaceLeaf) => {](https://github.com/lorens-osman-dev/cluster/blob/58003c16c73a8adc17f54c0ab1e2f83b4bfbedb1/src/createFamily/buttons.ts#L17-L21) what is this code doing? This seems to just be finding any markdown leaf. Why? Do you mean to access `activeLeaf`? You probably want to use getActiveViewOfType(MarkdownView) instead.
- [this.app.vault.adapter.exists](https://github.com/lorens-osman-dev/cluster/blob/58003c16c73a8adc17f54c0ab1e2f83b4bfbedb1/src/createFamily/buttons.ts#L218) [`getAbstractFileByPath`](https://github.com/obsidianmd/obsidian-api/blob/902badd38ba907689f0917d7b193f7e33d1284fe/obsidian.d.ts#L3612) [Prefer the Vault API over the Adapter API](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#prefer-the-vault-api-over-the-adapter-api)
- [this.app](https://github.com/lorens-osman-dev/cluster/blob/58003c16c73a8adc17f54c0ab1e2f83b4bfbedb1/src/createFamily/coloringTreePanel.ts#L10) you keep assigning to `this` but you're inside a top-level function here
- https://github.com/obsidianmd/obsidian-api/blob/9754fc87dd9a417f198a5cad7f08959206d2f69c/obsidian.d.ts#L4166 you should move the file to the trash instead of deleting it https://github.com/obsidianmd/obsidian-api/blob/9754fc87dd9a417f198a5cad7f08959206d2f69c/obsidian.d.ts#L4166
- [this.app](https://github.com/lorens-osman-dev/cluster/blob/58003c16c73a8adc17f54c0ab1e2f83b4bfbedb1/src/createFamily/familyModal.ts#L360) `this.app` doesn't exist. This might work because its falling back to the `global.app` instance, but this is deprecated. You should pass `app` into the function instead

**Comment by joethei** [comment]
["description": "Cluster plugin mainly designed to simplify the process of note clustering on mobile devices and work well on PCs ether",](https://github.com/lorens-osman-dev/cluster/blob/247ba5d5e314423d143eea534f60078a6e0a19a4/manifest.json#L6)
The description should not contain the word "plugin"
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

**Comment by lorens-osman-dev** [comment]
What should I do now ? open new PR with new corrected information ?

best

**Comment by joethei** [comment]
No, update this one

**Comment by lorens-osman-dev** [comment]
[Done] ["description": "Cluster plugin mainly designed to simplify the process of note clustering on mobile devices and work well on PCs ether",](https://github.com/lorens-osman-dev/cluster/blob/247ba5d5e314423d143eea534f60078a6e0a19a4/manifest.json#L6)

**Pull request merged**
