### PR TITLE
Release of Database plugin!

### PR DESCRIPTION
**Pull request by RafaelGB**
# I am submitting a new Community Plugin
## Repo URL
Link to my plugin: [obsidian-db-folder](https://github.com/RafaelGB/obsidian-db-folder)
## Release Checklist
- [X] I have tested this on macOS, and Linux
- [ ] I have tested this on IOS and android
- [x] I have tested this on Windows
- [X] My GitHub release contains all required files
    - [X] 'main.]s'
    - [X] 'manifest.json'
    - [X] 'styles.css'
- [X] GitHub release name matches the exact version number specified in my manifest.json
- [X] The "id' in my "manifest.json" matches the 'ld in the 'community-plugins.json"file.
- [X] README clearly describes the plugins purpose and provides clear usage instructions.
- [X] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by liamcain** [comment]
Yay! Very excited to see this plugin being submitted 🥳 

I found a couple small things worth pointing out but let me know when this is ready to go in.

---

https://github.com/RafaelGB/obsidian-db-folder/blob/0f22eeb9e3ad4e37260c1c0db17b5a69c9e4cc01/src/components/Cell.tsx#L83 I think you also want to add an eventhandler to blur the field on enter. _Or_ if you want to allow newlines in fields, then you'll need to replace the `<br>s` with newlines in the `onChange`. Currently, pressing enter spits out HTML into the YAML which I don't think is the desired behavior.

https://github.com/RafaelGB/obsidian-db-folder/blob/98f664ceb020b4d433c7d40061739e693d8d46d9/src/components/Header.tsx#L104 okay, this isn't really PR feedback, but I really think you should expand the headermenu here. That way you can immediately name the new heading after clicking the plus.

https://github.com/RafaelGB/obsidian-db-folder/blob/7486ceb69d05ed966d31c1bec6312b8e85a85872/src/services/FileManagerService.ts#L68 You can use `getAbstractFileByPath` instead then just check that the result is instanceof TFile

https://github.com/RafaelGB/obsidian-db-folder/blob/7486ceb69d05ed966d31c1bec6312b8e85a85872/src/helpers/FileContent.ts#L54-L62 why not just return `this.object()[line_number]` here?

https://github.com/RafaelGB/obsidian-db-folder/blob/7486ceb69d05ed966d31c1bec6312b8e85a85872/src/helpers/FileContent.ts#L50 I don't think you really need the real_array object at all. But you definitely don't need it here, since you already wrapped your response from inside `object()`

image
 the "new button is misaligned

**Comment by RafaelGB** [comment]
Thanks for the feedback!
comments behind:

1. added blur on enter keydown. About html on yaml is the desired behaviour  because a new line breaks the yaml parse. I didn't find a better way to do it
2. To achieve this its not trivial  but I will add it to the backlog, I thinks its a good idea.
3. OMG how I did not know about this method! change done
4 & 5. All that class is a technical debt of my templater user scripts... fixed obliterating that real_array

All this changes will be published with version 0.2.1, let me finish some visual bugs before press that merge button

**Comment by RafaelGB** [comment]
0.2.1 was released with the cemented changes

I think its a stable version

**Comment by liamcain** [comment]
Thanks for making those fixes. I did some more poking around with the plugin. Since it's a lot of code I just some testing instead of digging though the code. There were a few bugs I'd recommend fixing before this codes in. Let me know when you'd like me to take another look.

---

I think one of the recent changes caused a regression in the column rearrange. As you start to drag, the column jumps to the top left. Still functional though

https://user-images.githubusercontent.com/693981/167314152-32546f51-91fd-4bf9-b670-95029c39db2f.mov

Also seems like something broke when you press "+" to add a column. The new column location seems to be unpredictable, sometimes it's to the right, other times to the left

https://user-images.githubusercontent.com/693981/167314571-2d3765ea-7e94-42df-9441-b618d872a8ab.mov

Clicking "Insert Right" if there's already a column with that name causes the table to crash:

https://user-images.githubusercontent.com/693981/167314707-b0af97f1-291d-4c76-9cc0-ecd02b10fdb7.mov

<details>
<summary>Stack Trace</summary>

```
react-dom.development.js:11340 Uncaught Error: Duplicate columns were found with ids: "newColumn5" in the columns array above
    at Object.useTable (eval at <anonymous> (app.js:1:1), <anonymous>:4023:17)
    at Table (eval at <anonymous> (app.js:1:1), <anonymous>:91501:122)
    at renderWithHooks (eval at <anonymous> (app.js:1:1), <anonymous>:27122:19)
    at updateFunctionComponent (eval at <anonymous> (app.js:1:1), <anonymous>:29493:21)
    at beginWork (eval at <anonymous> (app.js:1:1), <anonymous>:31200:17)
    at HTMLUnknownElement.callCallback (eval at <anonymous> (app.js:1:1), <anonymous>:16085:15)
    at Object.invokeGuardedCallbackDev (eval at <anonymous> (app.js:1:1), <anonymous>:16134:17)
    at invokeGuardedCallback (eval at <anonymous> (app.js:1:1), <anonymous>:16196:32)
    at beginWork$1 (eval at <anonymous> (app.js:1:1), <anonymous>:36090:8)
    at performUnitOfWork (eval at <anonymous> (app.js:1:1), <anonymous>:34905:13)
```
</details>

---

A few other UX suggestions:

- I suggest adding an event handler to create a new row on <kbd>Enter</kbd>
- To center the icons in the header, you should add `line-height: 1` to the `.svg-icon` class
image
- "+ New" button is missing `display: flex; align-items: center` on the div

**Comment by RafaelGB** [comment]
thank you for the testing and feedback!
I will work on it this week. About the amount of code I am working on unitary testing with jest-mock-extended, jest & @testing-library/react as well

**Comment by RafaelGB** [comment]
The changed requested were fixed excepting the problem with add column button when you DnD to the right another one.

I tried to separate that column out of DnD context but its not trivial. I will try to fix it with future versions.
The changes were included in 0.3.0 with the new feature of data view filters

https://github.com/RafaelGB/obsidian-db-folder/releases/tag/0.3.0

If you think that its enough to merge I think its ready. So much work to do with testing. That will be my next objective

**Comment by RafaelGB** [comment]
The [current version](https://github.com/RafaelGB/obsidian-db-folder/releases/tag/1.1.0) adds link support inside text columns with onFocus onBlur render of obsidian Markdown. The community around the plugin is growing every day =)

If some change is necessary to publish the plugin let me know. I am commenting as code as possible to facilitate review

**Review by liamcain — APPROVED** [review]
Okay, just doing another quick round of testing:

image

seeing this error when clicking "new database folder"

image

I would recommend calling these properties "date" and "datetime" instead of "calendar" and "calendar time."

---

Anyway, I think this is probably fine to go in. I don't see any blockers.

**Comment by RafaelGB** [comment]
I already change the label of that options and improve the creation of databases to add the default values. With the parser of Marshall/Unmarshall properties if someone removes it or with new versions we add another configs or remove them it will be modified automatically and that message of undefined is show and added.

with 1.2.3 will be included =)

BTW the [roadmap](https://github.com/RafaelGB/obsidian-db-folder/projects/1) grew a lot, I am very excited to be able to contribute to this wonderful application

**Comment by RafaelGB** [comment]
1.1.3 Out with the last changes requested added

**Comment by RafaelGB** [comment]
Would anything else be needed for publication?

**Comment by liamcain** [comment]
Hi @RafaelGB, thank you for your patience! Everything looks good to me; I've just asked @lishid to take a look before this goes in

**Comment by RafaelGB** [comment]
@liamcain No rush, as long as it takes.I just want to deliver it as best as possible :)

**Comment by RafaelGB** [comment]
With 1.6.0 after hard work I think its ready =)

**Comment by lishid** [comment]
I don't see any major red flags. It is a fairly complicated plugin so I can't audit everything. Given that you're doing a lot of monkey-patching and working around core stuff, some of it might be fragile, but I'm sure there's no other way and you already know the risks.

Small nits:

https://github.com/RafaelGB/obsidian-db-folder/blob/dfd38e5d0eaacc9cae8a00058e348c51edd536b5/src/main.ts#L205
See this tip: https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#avoid-accessing-workspaceactiveleaf-directly

https://github.com/RafaelGB/obsidian-db-folder/blob/dfd38e5d0eaacc9cae8a00058e348c51edd536b5/src/main.ts#L231
`file` here should be typed `TAbstractFile` right?

https://github.com/RafaelGB/obsidian-db-folder/blob/dfd38e5d0eaacc9cae8a00058e348c51edd536b5/src/main.ts#L274
Doesn't seem like this does anything?

**Comment by RafaelGB** [comment]
@lishid thanks for the feedback! this week I will work on those comments.

The monkey patches I take the reference of Kanban plugin. Its a custom view too and looked like as a solid idea.

The dead code of keyboard is a skeleton of future features already into the roadmap, but I can comment it until is ready.

I will @ you when its reviewed =)

**Pull request merged**
