### PR TITLE
Add plugin: AI Summarize

### PR DESCRIPTION
**Pull request by RavenWits**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/RavenWits/obsidian-ai-summarize

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Review by RavenWits — COMMENTED** [review]
Fixed the repo link

**Review by RavenWits — COMMENTED** [review]
Added misssing files in the release

**Comment by joethei** [comment]
["minAppVersion": "0.15.0",](https://github.com/RavenWits/obsidian-ai-summarize/blob/4d14e4e6a83fb1c5a9329ff0c9e105f5e3c9d5b8/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

["author": "ALP SARIYER",](https://github.com/RavenWits/obsidian-ai-summarize/blob/4d14e4e6a83fb1c5a9329ff0c9e105f5e3c9d5b8/manifest.json#L7)
Caps

["donation": "https://buymeacoffee.com/ravenwits",](https://github.com/RavenWits/obsidian-ai-summarize/blob/4d14e4e6a83fb1c5a9329ff0c9e105f5e3c9d5b8/manifest.json#L13)
Remove this.

[updateSummary(md: string, newSummary: string): Record<string, string> {](https://github.com/RavenWits/obsidian-ai-summarize/blob/4d14e4e6a83fb1c5a9329ff0c9e105f5e3c9d5b8/src/plugin/main.ts#L20-L74)
Use the [processFrontMatter](https://docs.obsidian.md/Reference/TypeScript+API/FileManager/processFrontMatter) API instead of manually modifying the YAML.

[id: 'ai-summarize-summarize-selection',](https://github.com/RavenWits/obsidian-ai-summarize/blob/4d14e4e6a83fb1c5a9329ff0c9e105f5e3c9d5b8/src/plugin/main.ts#L128)
Don't prefix the command id with the plugin id, Obsidian will make sure that there are no conflicts with other plugins.

[name: 'Summarize Selection',](https://github.com/RavenWits/obsidian-ai-summarize/blob/4d14e4e6a83fb1c5a9329ff0c9e105f5e3c9d5b8/src/plugin/main.ts#L129), [.setTitle('AI Summarize')](https://github.com/RavenWits/obsidian-ai-summarize/blob/4d14e4e6a83fb1c5a9329ff0c9e105f5e3c9d5b8/src/plugin/main.ts#L161), [.setName('Max Tokens')](https://github.com/RavenWits/obsidian-ai-summarize/blob/4d14e4e6a83fb1c5a9329ff0c9e105f5e3c9d5b8/src/settings/settings.ts#L48), [.setName('Default Prompt')](https://github.com/RavenWits/obsidian-ai-summarize/blob/4d14e4e6a83fb1c5a9329ff0c9e105f5e3c9d5b8/src/settings/settings.ts#L61), [.setName('Summary in the Frontmatter')](https://github.com/RavenWits/obsidian-ai-summarize/blob/4d14e4e6a83fb1c5a9329ff0c9e105f5e3c9d5b8/src/settings/settings.ts#L74)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[const response = await fetch(url, requestOptions);](https://github.com/RavenWits/obsidian-ai-summarize/blob/4d14e4e6a83fb1c5a9329ff0c9e105f5e3c9d5b8/src/plugin/gpt.ts#L22)
Use the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

[containerEl.createEl('h2', { text: 'General Settings - AI Summarize' });](https://github.com/RavenWits/obsidian-ai-summarize/blob/4d14e4e6a83fb1c5a9329ff0c9e105f5e3c9d5b8/src/settings/settings.ts#L31)
There should not be a top level heading in settings.

[containerEl.createEl('h5', { text: 'KNOW HOW:' });](https://github.com/RavenWits/obsidian-ai-summarize/blob/4d14e4e6a83fb1c5a9329ff0c9e105f5e3c9d5b8/src/settings/settings.ts#L83), [containerEl.createEl('h5', { text: 'SUPPORT:' });](https://github.com/RavenWits/obsidian-ai-summarize/blob/4d14e4e6a83fb1c5a9329ff0c9e105f5e3c9d5b8/src/settings/settings.ts#L88)
For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```

**Comment by RavenWits** [comment]
Hey @joethei , appreciate your thorough review. I've addressed all your points except for the utilization of `requestUrl` over `fetch`. Upon examination, it seems that the `requestUrl` function lacks support for data streaming and handling the response, which could be crucial given the absence of a character selection limit in the plugin. Considering this, I opted for `fetch` to ensure a smoother processing experience for users, particularly with larger request bodies indicating the user that AI is working.

I'm curious if there's a documented approach within Obsidian to enable streaming in this context. If not, would you still recommend switching to `fetch` despite this consideration? Your insights would be invaluable. 

Thanks again for your dedication and time invested in the review. 
Cheers!

**Pull request merged**
