### PR TITLE
Add Pieces for Developers Plugin

### PR DESCRIPTION
**Pull request by mark-at-pieces**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/pieces-app/obsidian-pieces

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lishid** [comment]
If you are submitting from a GitHub org, you need to be a public member of the org.

**Comment by mark-at-pieces** [comment]
> If you are submitting from a GitHub org, you need to be a public member of the org.

thank you, got it now!

**Comment by randy-at-pieces** [comment]
Here is a link to our site's documentation as well: https://docs.pieces.app/extensions-plugins/obsidian 

Thank you!

**Comment by randy-at-pieces** [comment]
@joethei @marcusolsson @liamcain All of you should have access now! :)

**Comment by tsavo-at-pieces** [comment]
Awesome, thanks all! Super exciting 👍

**Comment by tsavo-at-pieces** [comment]
Something fun to break up all the coding! (not to say crushing some code is not fun 😅)... But yea - made a supercut video highlighting the plugins MVP features, (almost) timed with an energizing beat 😎⚡️ 

Thanks to all for helping us get this out there... if you can't tell by the video, we're pretty excited for where this could go!

**Comment by tsavo-at-pieces** [comment]
Amazing! Thank you all so much 🙏 This means a lot to us!

**Pull request merged**
