### PR TITLE
Add plugin: Title renamer

### PR DESCRIPTION
**Pull request by stroiman**
Add stroiman-title-renamer plugin

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/stroiman/obsidian-title-sync

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by stroiman** [comment]
Argh, there were uncommitted changes to manifest file

**Comment by stroiman** [comment]
Hmm fixed the manifest and made a new version and a new release. Doesn't seem like I need to change this PR?

**Comment by joethei** [comment]
What sets this plugin apart from the "Filename Heading Sync" plugin?

["id": "stroiman-title-renamer",](https://github.com/stroiman/obsidian-title-sync/blob/86b363808692f50574dd6e2f9f1ba065240301db/manifest.json#L2)
Remov the "stroiman" prefix.

["description": "Syncrhonise title in markdown when note is renamed",](https://github.com/stroiman/obsidian-title-sync/blob/86b363808692f50574dd6e2f9f1ba065240301db/manifest.json#L6)
Typo

**Comment by stroiman** [comment]
> What sets this plugin apart from the "Filename Heading Sync" plugin?

"Filename Heading Sync" seems to have a different philosophy, that you ALWAY want a heading in the markdown synced to the file. So if modifying the file contents, it will rename the file. I don't share this philosophy. There are many reasons for not having the heading in markdown be equal to file name. 

- The title may contain illegal filename characters (which Filename Heading Sync just strips).
- I might want multiple notes with the same heading in markdown. E.g. a note on the concept on "Domain-driven Design", and a note on the book on the same name, I would have as two files (probably with a "(book)" on the latter)

Also, "Filename Heading Sync" plugin _by default_ inserts an H1 when opening a file, if none exists, which is not desired. If I didn't add one to a file, I don't want it. In particular, for template files.

My philosophy is, if the heading in the file is not equal to the file name, it's probably a deliberate action, so leave it alone.

> ["id": "stroiman-title-renamer",](https://github.com/stroiman/obsidian-title-sync/blob/86b363808692f50574dd6e2f9f1ba065240301db/manifest.json#L2) Remov the "stroiman" prefix.

Done

> ["description": "Syncrhonise title in markdown when note is renamed",](https://github.com/stroiman/obsidian-title-sync/blob/86b363808692f50574dd6e2f9f1ba065240301db/manifest.json#L6) Typo

Thanks, done.

**Comment by stroiman** [comment]
p.s. I added a link to "Filename Heading Sync" in the readme file, to help users choose which fits their own workflow better.

**Pull request merged**
