### PR TITLE
Add 'Focus Mode' plugin.

### PR DESCRIPTION
**Pull request by ryanpcmcquen**
- [X] I am submitting a new Community Plugin

## Repo URL

https://github.com/ryanpcmcquen/obsidian_focus_mode

Focus Mode demo

## Release Checklist

- [x] I have tested this on Windows
- [X] I have tested this on macOS
- [x] I have tested this on Linux

- [X] Github release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css`
- [X] Github release name matches the exact version number specified in your manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] README clearly describes the plugins purpose and provides clear usage instructions.

### CODE REVIEW

**Comment by ryanpcmcquen** [comment]
Oh wait, my release only contains `main.ts`, not `main.js`. Looks like the default `.gitignore` excludes it ... am I supposed to manually add that?

**Comment by lishid** [comment]
You should upload the built files to your Releases tab instead of pushing it into the repo - edit this release: https://github.com/ryanpcmcquen/obsidian_focus_mode/releases/tag/1.0.0

**Comment by ryanpcmcquen** [comment]
@lishid, thanks for the reply! Does it _only_ need those 3 files?

**Comment by ryanpcmcquen** [comment]
Also, is there a naming convention for that, for instance, would this name work:

```
obsidian_focus_mode__1.0.0.zip
```

**Comment by ryanpcmcquen** [comment]
Oh, or is the expectation that I just manually include those files?

**Comment by lishid** [comment]
Yeah, check out how the other plugins do it in the releases section :)

**Comment by ryanpcmcquen** [comment]
@lishid, done!

**Comment by ryanpcmcquen** [comment]
@lishid or @ericaxu, anything else I can do on this to help? I don't have access to the other platforms now, but since the code here operates on the DOM, it should be universal.

**Comment by ryanpcmcquen** [comment]
Got access to a Windows machine and tested there, will try to find a Linux comp or user.

**Comment by ryanpcmcquen** [comment]
Tested on Linux (Kubuntu 20.04/AppImage 0.11.13):
Screenshot_20210508_084415

**Comment by ryanpcmcquen** [comment]
Windows screenshot for posterity:
windows_obsidian_focus_mode

**Comment by ryanpcmcquen** [comment]
@lishid thanks for the solid review! Done:
https://github.com/ryanpcmcquen/obsidian_focus_mode/commit/fe47027c9ed9a4c4fedc118c7dd7451d4e57f360

**Comment by lishid** [comment]
I've changed your plugin ID from using underscores to using dashes. Once you update them in your repo, I'll merge the PR 👍

**Comment by ryanpcmcquen** [comment]
@lishid done! Despite the fact that I love underscores, consistency (should) always win!

**Pull request merged**
