### PR TITLE
Obsidian daily notes new tab

### PR DESCRIPTION
**Pull request by reorx**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/reorx/obsidian-daily-notes-new-tab

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - ~~`styles.css` _(optional)_~~
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by reorx** [comment]
The plugin has been updated to 1.1.1 to work on Windows system

**Comment by reorx** [comment]
The plugin has been updated to 1.1.2 to fix the problem caused by no `folder` is set in daily notes settings.

Additionally, it has been tested under Fedora Linux Desktop 33.

**Comment by reorx** [comment]
Hey @liamcain, any chance to take a look at this plugin and give some advice? Many thanks ☺️

**Comment by liamcain** [comment]
Just a heads up, but this functionality already exists in the [Periodic Notes](https://obsidian.md/plugins?search=periodic%20notes) plugin .

You can click the "Open Today" ribbon button while holding down ctrl (or command on MacOS) to open the note in a new tab: 
image. 

Let me know if you'd still like me to review the code though!

**Comment by reorx** [comment]
Hi @liamcain, thanks for the reply. What you said is the way I used to open daily notes in a new tab, but I am a keyboard guy, I want my high-frequency actions to be called by keyboard shortcuts, so "new tab" has to be a command to fulfill my needs.

And this plugin is more than this. It can find and focus on the already opened one to avoid redundancy; it can add color to the daily note to make it outstanding. Last but not least, it can extend the time of the day so that when you use this plugin at 01:00, it will still show the correct note you want.

> Let me know if you'd still like me to review the code though!

Yes, only if you find it interesting and have time :)

**Comment by reorx** [comment]
@lishid Thanks for the review and guidance ☺️

**Pull request merged**
