### PR TITLE
Add auto-hide-cursor plugin

### PR DESCRIPTION
**Pull request by moismat**
# I am submitting a new Community Plugin

## Repo URL

https://github.com/moismat/obsidian-auto-hide-cursor

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["fundingUrl": "",](https://github.com/moismat/obsidian-auto-hide-cursor/blob/1fe92e084e409709c45ec8c0ab4fc2d7227a1275/manifest.json#L9)
If you don't have one omit this.

Why is this plugin marked as desktop only?
I don't see any reason for it, and you say you already tested on mobile.

[document.body.addEventListener(](https://github.com/moismat/obsidian-auto-hide-cursor/blob/1fe92e084e409709c45ec8c0ab4fc2d7227a1275/main.ts#L5-L19)
Instead of this use the following:
```ts
this.registerDomEvent(document, "scroll", () => {
...
});
```
And remove the code in `onunload` that removes the event listeners, as Obsidian will handle this when using the `registerDomEvent` function.

Your plugin won't work in pop-out windows.
See here how to update your plugin to support pop out windows:
<https://forum.obsidian.md/t/plugin-developers-how-to-update-your-plugin-to-support-pop-out-windows/40228>

**Comment by moismat** [comment]
hey @joethei , updated  [here](https://github.com/moismat/obsidian-auto-hide-cursor/pull/1/files#r1186104600) 😄

**Comment by moismat** [comment]
updated. now also works on popout windows 😄

**Comment by liamcain** [comment]
- [layout-change](https://github.com/moismat/obsidian-auto-hide-cursor/blob/7ab81ea3950ed07830dae358b0660da0601c63f8/main.ts#L8) instead of doing this on every layout change (which can happen frequently and will mean that the listener will get registered more than it needs to), you should change this to [`window-open`](https://github.com/obsidianmd/obsidian-api/blob/902badd38ba907689f0917d7b193f7e33d1284fe/obsidian.d.ts#L4102). That way it will only register it for new pop-out windows.

**Pull request merged**
