### PR TITLE
Add plugin: Class Relation Visualization

### PR DESCRIPTION
**Pull request by Cold-dragon7**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Cold-dragon7/Obsidian-Class-Relation-Visualization

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Your README is very sparse, please add more information what your plugin does, and how to use it.
Also add screenshots.

[let relationArr = ['상', '합', '집'];](https://github.com/Cold-dragon7/Obsidian-Class-Relation-Visualization/blob/f24aa02d8c53f86d6acf817378c0f2c1dd2e4e65/src/ClassRelationView.ts#L86)
For example, it's not documented that these characters need to be used.

Remove the `styles.css` file from your release, since it's empty it's just unnecessary bloat that Obsidian would download.

["description": "Class relation expression test",](https://github.com/Cold-dragon7/Obsidian-Class-Relation-Visualization/blob/f24aa02d8c53f86d6acf817378c0f2c1dd2e4e65/manifest.json#L6)
That description makes no sense, We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[await this.loadSettings();](https://github.com/Cold-dragon7/Obsidian-Class-Relation-Visualization/blob/f24aa02d8c53f86d6acf817378c0f2c1dd2e4e65/src/main.ts#L18)
Your plugin does not have settings, so remove this loading code.

[name: 'Open Class Relation View',](https://github.com/Cold-dragon7/Obsidian-Class-Relation-Visualization/blob/f24aa02d8c53f86d6acf817378c0f2c1dd2e4e65/src/main.ts#L27), [return 'Class Relation View';](https://github.com/Cold-dragon7/Obsidian-Class-Relation-Visualization/blob/f24aa02d8c53f86d6acf817378c0f2c1dd2e4e65/src/ClassRelationView.ts#L24)

[let relationArr = ['상', '합', '집'];](https://github.com/Cold-dragon7/Obsidian-Class-Relation-Visualization/blob/f24aa02d8c53f86d6acf817378c0f2c1dd2e4e65/src/ClassRelationView.ts#L86), [f(char == '상')](https://github.com/Cold-dragon7/Obsidian-Class-Relation-Visualization/blob/f24aa02d8c53f86d6acf817378c0f2c1dd2e4e65/src/ClassRelationView.ts#L92), [else if(char == '합')](https://github.com/Cold-dragon7/Obsidian-Class-Relation-Visualization/blob/f24aa02d8c53f86d6acf817378c0f2c1dd2e4e65/src/ClassRelationView.ts#L94)
Please stay consistent in the language used in your plugin.

[.fill('#87CEEB')](https://github.com/Cold-dragon7/Obsidian-Class-Relation-Visualization/blob/f24aa02d8c53f86d6acf817378c0f2c1dd2e4e65/src/ClassRelationMap.ts#L360), [.fill('blue')](https://github.com/Cold-dragon7/Obsidian-Class-Relation-Visualization/blob/f24aa02d8c53f86d6acf817378c0f2c1dd2e4e65/src/ClassRelationMap.ts#L380), [({ color: 'black'](https://github.com/Cold-dragon7/Obsidian-Class-Relation-Visualization/blob/f24aa02d8c53f86d6acf817378c0f2c1dd2e4e65/src/ClassRelationMap.ts#L361), [.stroke('gray').fill('white')](https://github.com/Cold-dragon7/Obsidian-Class-Relation-Visualization/blob/f24aa02d8c53f86d6acf817378c0f2c1dd2e4e65/src/ClassRelationMap.ts#L439), [color: 'gray'](https://github.com/Cold-dragon7/Obsidian-Class-Relation-Visualization/blob/f24aa02d8c53f86d6acf817378c0f2c1dd2e4e65/src/ClassRelationMap.ts#L442), [color: 'gray'](https://github.com/Cold-dragon7/Obsidian-Class-Relation-Visualization/blob/f24aa02d8c53f86d6acf817378c0f2c1dd2e4e65/src/ClassRelationMap.ts#L463), ['white' : 'gray'](https://github.com/Cold-dragon7/Obsidian-Class-Relation-Visualization/blob/f24aa02d8c53f86d6acf817378c0f2c1dd2e4e65/src/ClassRelationMap.ts#L481)
Use the CSS variables for colors here, so that this looks good across many different themes, and with both dark and lightmode.
https://docs.obsidian.md/Reference/CSS+variables/Foundations/Colors

**Comment by joethei** [comment]
[- '상속 관계', '합성 관계', '집합 관계' categories for class relations. Relations consist of links to other class files.](https://github.com/Cold-dragon7/Obsidian-Class-Relation-Visualization/blob/6b2b44adc07b372f6c82bc54441add2e5af15d60/README.md?plain=1#L6)
Please use the english names here, as they are in the plugin.

**Comment by Cold-dragon7** [comment]
Thank you for your comment. I edited my plugin and README.md.

**Comment by Cold-dragon7** [comment]
Please review it again, collaborator.

**Comment by Cold-dragon7** [comment]
Appreciate for your help!

**Pull request merged**
