### PR TITLE
add markmind plugin

### PR DESCRIPTION
**Pull request by MarkMindCkm**
# [ ] I am submitting a new Community Plugin 

## Repo URL
<https://github.com/MarkMindCkm/obsidian-markmind>

main functions:
- mindmap
- outline
- pdf annotator

this plugin is not open source

## Release Checklist

- [x] I have tested this on Windows, macOS, and Linux _(if applicable)_
- [x] Github release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] Github release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.
- [x] I have added a license in the LICENSE file

### CODE REVIEW

**Comment by lishid** [comment]
Can you update the plugin description in the PR to show that this is closed source? I'm thinking of adding something like `(Closed Source)`, at least until we have a dedicated flag for this kind of plugins.

Also, do you want me to take a look at your source privately for suggestions?

**Comment by MarkMindCkm** [comment]
> Can you update the plugin description in the PR to show that this is closed source? I'm thinking of adding something like `(Closed Source)`, at least until we have a dedicated flag for this kind of plugins.
> 
> Also, do you want me to take a look at your source privately for suggestions?

I have invite you to the project

**Comment by lishid** [comment]
Cool, I will continue the review in your repo as an issue. Will update back here once we're all done.

**Comment by MarkMindCkm** [comment]
> Cool, I will continue the review in your repo as an issue. Will update back here once we're all done.

I have fix issues of this project

**Pull request merged**
