### PR TITLE
Add Fast Image Cleaner plugin

### PR DESCRIPTION
**Pull request by martinniee**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist

- [x]    I have tested the plugin on
    - [x]    Windows
    - [ ]    macOS
    - [ ]    Linux
    - [ ]    Android _(if applicable)_
    - [ ]    iOS _(if applicable)_
- [x]    My GitHub release contains all required files
    - [x]    `main.js`
    - [x]    `manifest.json`
    - [x]    `styles.css` _(optional)_
- [x]    GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x]    The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x]    My README.md describes the plugin's purpose and provides clear usage instructions.
- [x]    I have read the tips in [https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md) and have self-reviewed my plugin to avoid these common pitfalls.
- [x]    I have added a license in the LICENSE file.
- [x]    My project respects and is compatible with the original license of any code from other plugins that I'm using.  
	I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[app.workspace.on(](https://github.com/martinniee/Obsidian-fast-image-cleaner/blob/e278b8fb3abd6d5b84f5326cbd9e1a3049f09e2b/src/main.ts#L27-L44)
Wrap these calls in `this.registerEvent()` so they get unloaded properly when the plugin gets disabled.

[this.registerInterval(](https://github.com/martinniee/Obsidian-fast-image-cleaner/blob/e278b8fb3abd6d5b84f5326cbd9e1a3049f09e2b/src/main.ts#L46-L48)
Remove this.

[logs.innerHTML = this.getLog();](https://github.com/martinniee/Obsidian-fast-image-cleaner/blob/e278b8fb3abd6d5b84f5326cbd9e1a3049f09e2b/src/modals.ts#L47)
[Avoid using `innerHTML`](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#avoid-innerhtml-outerhtml-and-insertadjacenthtml)

**Comment by martinniee** [comment]
@joethei  
Thanks for your helpful advice and I have updated code following your advice.

**Comment by liamcain** [comment]
It's not part of the public API, but you might want to use this.app.fileManager.promptForDeletion(file: TAbstractFile) instead.

That will use the user's preference for how they want files to be deleted (such as put in system trash bin).

**Comment by martinniee** [comment]
> It's not part of the public API, but you might want to use this.app.fileManager.promptForDeletion(file: TAbstractFile) instead.
> 
> That will use the user's preference for how they want files to be deleted (such as put in system trash bin).

Thanks for you precious advice

**Pull request merged**
