### PR TITLE
Add media-extended

### PR DESCRIPTION
**Pull request by AidenLx**
# [x] I am submitting a new Community Theme

## Repo URL

[alx-plugins/media-extended](https://github.com/alx-plugins/media-extended)

## Release Checklist

- [x] I have tested this on Windows, macOS
- [x] Github release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - `styles.css` _(optional)_
- [x] Github release name matches the exact version number specified in your manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.

### CODE REVIEW

**Comment by lishid** [comment]
Please auto format your code so that spaces are normalized.

https://github.com/alx-plugins/media-extended/blob/60e3f83dcddee64674dcb030329c643a1f3c31e2/src/main.ts#L77
Could use the createFragment helper: https://github.com/obsidianmd/obsidian-api/blob/dbfa19ad7aa6557f0ecff962065c3f540bc77e27/obsidian.d.ts#L153
Combine that with createEl('br') should help simplify this a bit.

https://github.com/alx-plugins/media-extended/blob/60e3f83dcddee64674dcb030329c643a1f3c31e2/src/processor.ts#L26
I wouldn't recommend using URL() to parse the href, it could throw exceptions.
Instead, use our linktext parser: https://github.com/obsidianmd/obsidian-api/blob/dbfa19ad7aa6557f0ecff962065c3f540bc77e27/obsidian.d.ts#L1914

https://github.com/alx-plugins/media-extended/blob/60e3f83dcddee64674dcb030329c643a1f3c31e2/src/processor.ts#L47
Contains here is probably not accurate. You'll probably want to resolve it first to a TFile using metadataCache.getFirstLinkpathDest, then compare it directly with:
```
if(leaf.view instanceof FileView && leaf.view.file === matchedFile);
```

https://github.com/alx-plugins/media-extended/blob/60e3f83dcddee64674dcb030329c643a1f3c31e2/src/processor.ts#L56
Could extract this code into a util since  you're using it twice.

https://github.com/alx-plugins/media-extended/blob/60e3f83dcddee64674dcb030329c643a1f3c31e2/src/processor.ts#L62
Check for null here.

https://github.com/alx-plugins/media-extended/blob/60e3f83dcddee64674dcb030329c643a1f3c31e2/src/processor.ts#L65
Prefer to use instanceof here instead just to be sure.

https://github.com/alx-plugins/media-extended/blob/60e3f83dcddee64674dcb030329c643a1f3c31e2/src/processor.ts#L134
https://github.com/alx-plugins/media-extended/blob/60e3f83dcddee64674dcb030329c643a1f3c31e2/src/processor.ts#L177
Same as above.

**Comment by AidenLx** [comment]
Thank you for the code review! I've opened a new [review](https://github.com/alx-plugins/media-extended/tree/review) branch with all the improvements suggested. I will merge it into main and release a new version as soon as the pull request is accepted.

**Comment by AidenLx** [comment]
By the way, is there a way in Obsidian to inject javascript code into <iframe>? I've been trying to add playback control to the video from external video hosts as well, but not every video host offers iframe API as comprehensive as Youtube, which allows advanced controls outside <iframe>, so I have to inject `mutationObserver` into the player inside <iframe> to do so. 

Now the access to iframe content is blocked by cross-origin policy, for example, `<iframe>.contentWindow.document` throws `Uncaught DOMException: Blocked a frame with origin "app://obsidian.md" from accessing a cross-origin frame.`

**Comment by lishid** [comment]
> By the way, is there a way in Obsidian to access content inside <iframe>? I've been trying to add playback control to the video from external video hosts as well, but not every video host offers iframe API as comprehensive as Youtube, which allows advanced controls outside <iframe>, so I have to inject `mutationObserver` into the player inside <iframe> to do so.
> 
> Now the access to iframe content is blocked by cross-origin policy, for example, `<iframe>.contentWindow.document` throws `Uncaught DOMException: Blocked a frame with origin "app://obsidian.md" from accessing a cross-origin frame.`

Unfortunately due to browser security restrictions there's no way to access anything in the iframe that has an external src. We've tried to do it too (originally to inject styles) but couldn't find a way either.

**Comment by lishid** [comment]
https://github.com/alx-plugins/media-extended/blob/ad392ca9863c298dead9f3773c65cad193ccf584/src/settings.ts#L34
What I meant was to use the callback in createFragment to avoid you having to create an extra function:
```ts
desc: createFragment(descEl => {
  descEl.appendText(...);
  ...
})
```
https://github.com/alx-plugins/media-extended/blob/ad392ca9863c298dead9f3773c65cad193ccf584/src/settings.ts#L38
`descEl.createEl("br");` 😄 

https://github.com/alx-plugins/media-extended/blob/ad392ca9863c298dead9f3773c65cad193ccf584/src/processor.ts#L56
This might return null.

https://github.com/alx-plugins/media-extended/blob/ad392ca9863c298dead9f3773c65cad193ccf584/src/processor.ts#L76
Don't throw an error here; just exit gracefully (or if you really want the user to know, show a Notice).

https://github.com/alx-plugins/media-extended/blob/ad392ca9863c298dead9f3773c65cad193ccf584/src/processor.ts#L83
Same here, I'd recommend just ignoring the else because you can't do much. Your error just becomes an uncaught exception with nothing handling it.

https://github.com/alx-plugins/media-extended/blob/ad392ca9863c298dead9f3773c65cad193ccf584/src/MFParse.ts#L22
Maybe put a null check on the player here just in case.

**Comment by AidenLx** [comment]
Done! 
Thanks for the explanation! [This](https://github.com/alx-plugins/media-extended/commit/b2f15e6409cd95fdb537a7fdd971479c3d4afa36) is way more elegant to add HTML elements 👍

For the player null checks, I put them in [here](https://github.com/alx-plugins/media-extended/blob/461efe1499f444b9fe884bdfb19d9e4958796608/src/processor.ts#L80) and [here](https://github.com/alx-plugins/media-extended/blob/461efe1499f444b9fe884bdfb19d9e4958796608/src/processor.ts#L95)

**Comment by lishid** [comment]
> For the player null checks, I put them in here and here
That's a rather convoluted way of null checking IMO. Do you have a reason to avoid doing it inside the `bindTimeSpan` function?

**Comment by AidenLx** [comment]
No particular reason, I think it may fit Typescript checks more? I've changed it as you suggested.

**Comment by lishid** [comment]
LGTM. I'll have it merged once the merge conflict is fixed 👍

**Comment by AidenLx** [comment]
Done!

**Pull request merged**
