### PR TITLE
Add plugin: File Explorer Customizer

### PR DESCRIPTION
**Pull request by azaol-aegnor**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/azaol-aegnor/obsidian-fec

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by azaol-aegnor** [comment]
It should be fixed 😸

**Comment by liamcain** [comment]
Hi @azaol-aegnor, it looks like the source code for this plugin is not committed to the repository. In order for the plugin to be approved, the code needs to be reviewed by our team.

**Comment by azaol-aegnor** [comment]
Hello @liamcain, I wrote the JS file directly, there's no source apart from the `main.js` and `styles.css` attached on the release. Should I just copy them into the repo?

**Comment by joethei** [comment]
If you want to be included, yes to both.
As you seem to have started from a already compiled plugin your code is not that great to read.

We generally recommend starting from the [Sample plugin](https://github.com/obsidianmd/obsidian-sample-plugin) which is written in typescript.

**Comment by nhan000** [comment]
@azaol-aegnor This's a bummer :( I've been looking forward to your plugin just to add guidelines to the File Explorer. Any chance you could work on this earlier? :(

**Comment by nhan000** [comment]
@azaol-aegnor Thanks a lot! :D

**Pull request closed without merging**
