### PR TITLE
add Split Pane View Helper plugin

### PR DESCRIPTION
**Pull request by luckman212**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/luckman212/obsidian-split-pane-view

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android
  - [ ]  iOS
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css`
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
- [x] I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by luckman212** [comment]
Forum link: https://forum.obsidian.md/t/viewing-note-in-side-by-side-mode-how-to-create-a-new-note-and-have-it-replace-the-current-view-instead-of-opening-a-new-tab/

**Comment by liamcain** [comment]
- [interface View {](https://github.com/luckman212/obsidian-split-pane-view/blob/4474c6f6c5e9784294eaa6d79cc372fe113e4b03/main.ts#L17-L19) This is a bad assumption to make. Not all views have a TFile. Only FileViews do. [`FileView`](https://github.com/obsidianmd/obsidian-api/blob/cb7d2d94ecce1f668a2eb99901d8c26267e56eaf/obsidian.d.ts#L1354) is available in the API, so I think you are better off doing something like `if (view instanceof FileView) { /* it's safe to assume view.file exists here */ }`
- [ribbonIconEl.addClass('split-view-plugin-ribbon-class');](https://github.com/luckman212/obsidian-split-pane-view/blob/4474c6f6c5e9784294eaa6d79cc372fe113e4b03/main.ts#L51) you can remove this line, it's not used for anything
- [getMostRecentMDLeaf](https://github.com/luckman212/obsidian-split-pane-view/blob/4474c6f6c5e9784294eaa6d79cc372fe113e4b03/main.ts#L98) I don't think you want to be using getMostRecentLeaf here. Instead you should `let view = use getActiveViewOfType(MarkdownView)`. Then you can access the leaf from `view.leaf`.
- [mrl.id](https://github.com/luckman212/obsidian-split-pane-view/blob/4474c6f6c5e9784294eaa6d79cc372fe113e4b03/main.ts#L74) I don't think you really want to be accessing the ID here either. You have an instance of the leaf, no need to compare IDs, you can just do an equality check using the leaf.
- [getMostRecentMDLeaf](https://github.com/luckman212/obsidian-split-pane-view/blob/4474c6f6c5e9784294eaa6d79cc372fe113e4b03/main.ts#L120) I think you are better off using getActiveViewOfType(MarkdownView) here as well.
- [getLeavesOfType](https://github.com/luckman212/obsidian-split-pane-view/blob/4474c6f6c5e9784294eaa6d79cc372fe113e4b03/main.ts#L111) This will get all leaves, including leaves in the sidebar or in popout windows. I think what you want to do instead is iterate over all leaves, and check if it has the same root as the current leaf ([getRoot](https://github.com/obsidianmd/obsidian-api/blob/cb7d2d94ecce1f668a2eb99901d8c26267e56eaf/obsidian.d.ts#L4287))

**Comment by joethei** [comment]
Hi @luckman212,
I just wanted to confirm that you've seen Liams comment with the requested changes.
Do you still intend on submitting this plugin?

**Comment by luckman212** [comment]
@joethei Yes I did see his reply (thanks @liamcain!) but haven't had the time to update the plugin yet. Yes I do plan to rewrite some portions of it as soon as I have a little time. But first I am trying to complete my Debug Logger plugin which should be done by the end of today hopefully.

**Comment by ericaxu** [comment]
Hi @luckman212 , do you still intend to submit this?

**Comment by luckman212** [comment]
Yes!

**Comment by ericaxu** [comment]
> Yes!

Thank you! Was doing some spring cleaning and want to make sure the open PRs are actually active :)

**Comment by ericaxu** [comment]
Hi there, to keep things tidy, we're going to temporarily close plugin PRs after a month of inactivity.

This by no means mean you shouldn't continue working on this project! Feel free to tell us to re-open it when you're ready to continue. Thanks for your understanding!

**Pull request closed without merging**
