### PR TITLE
Adds 'obsidian-habit-tracker' to community plugin list.

### PR DESCRIPTION
**Pull request by duoani**
# I am submitting a new Community Plugin

## Repo URL

[duoani/obsidian-habit-tracker: This plguin for Obsidian creates a simple month view for visualizing your punch records.](https://github.com/duoani/obsidian-habit-tracker)

## Release Checklist

- [x] I have tested this on Windows
- [x] Github release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] Github release name matches the exact version number specified in your manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/duoani/obsidian-habit-tracker/blob/47939b7f3baef059eec3babdd1fdf86d162e5400/main.ts#L51

Since your renderer doesn't actually add anything that needs to be cleaned up, you can probably do all of this inside the callback from `registerMarkdownCodeBlockProcessor` directly, instead of adding a child with a tracked lifecycle and not doing anything in `onunload`. You can leave it like this if you want, it'll just cost a tad bit of extra performance to keep track of your rendered block's class.

Everything else looks great!

**Comment by duoani** [comment]
Thanks for your review. l have refactor my code and removed render child.

**Comment by lishid** [comment]
Ok, that looks good. One more thing I missed in the last review:

https://github.com/duoani/obsidian-habit-tracker/blob/47939b7f3baef059eec3babdd1fdf86d162e5400/main.ts#L103
While using innerHTML is very convenient, it's highly insecure and can lead to DOM injection attacks because it is easy to forget to sanitize user content.

I would recommend refactoring the code here to build up your DOM elements, instead of using a string HTML. There are some convenience methods that Obsidian provides, which will help with this. You can also use something like svelte to build up your DOM.

```ts
// Create detached element
let tableEl = createEl('table');
// Create element and append to parent
let childEl = parentEl.createEl('p', {cls: 'some-css-class', text: 'some inner text'});
// Shortcuts for div and span
let childDiv = parentElement.createDiv({cls: 'css-class', text: 'some inner text'});
let childSpan = parentElement.createSpan({cls: 'css-class', text: 'some inner text'});
```

**Comment by duoani** [comment]
You're right, I'll find more detail of these APIs.

**Comment by duoani** [comment]
> Ok, that looks good. One more thing I missed in the last review:
> 
> https://github.com/duoani/obsidian-habit-tracker/blob/47939b7f3baef059eec3babdd1fdf86d162e5400/main.ts#L103
> While using innerHTML is very convenient, it's highly insecure and can lead to DOM injection attacks because it is easy to forget to sanitize user content.
> 
> I would recommend refactoring the code here to build up your DOM elements, instead of using a string HTML. There are some convenience methods that Obsidian provides, which will help with this. You can also use something like svelte to build up your DOM.
> 
> ```ts
> // Create detached element
> let tableEl = createEl('table');
> // Create element and append to parent
> let childEl = parentEl.createEl('p', {cls: 'some-css-class', text: 'some inner text'});
> // Shortcuts for div and span
> let childDiv = parentElement.createDiv({cls: 'css-class', text: 'some inner text'});
> let childSpan = parentElement.createSpan({cls: 'css-class', text: 'some inner text'});
> ```

I'd done that.

**Comment by lishid** [comment]
Hmm did you have the change on a dev branch? I'm not seeing changes on master.

**Comment by duoani** [comment]
> Hmm did you have the change on a dev branch? I'm not seeing changes on master.

I am **SO SORRY** for waiting you time. I just `git push --tags` but I didn't know that it just push tags. I had pushed to master already.

**Comment by lishid** [comment]
Looks good!

**Pull request merged**
