### PR TITLE
Add obsidian-query-language plugin

### PR DESCRIPTION
**Pull request by jplattel**
This plugin allows a use to query the vault in ways that are different from the normal query block.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/jplattel/obsidian-query-language/blob/cd8772ff5e0fe2d2278b7da826d0f65e3203723f/src/main.ts#L22

These two clauses do two very different things depending on `layoutReady`...

https://github.com/jplattel/obsidian-query-language/blob/cd8772ff5e0fe2d2278b7da826d0f65e3203723f/src/renderer.ts#L17
Not too sure about the implementation details of your search algorithm, but you can make this function `async` or just return a `Promise<..>`, and run your query asynchronously for better responsiveness.

https://github.com/jplattel/obsidian-query-language/blob/cd8772ff5e0fe2d2278b7da826d0f65e3203723f/src/renderer.ts#L31
You're defining a scoped `result` here that can't be used outside.

**Comment by jplattel** [comment]
Thanks for the feedback I'm not that well versed with Typescript yet, will look into the things you mentioned! :)

**Comment by lishid** [comment]
Hey @jplattel , anything I can help with this?

**Comment by jplattel** [comment]
Hey @lishid thanks, I just didn't have the time to implement your suggestions yet... Will do that at the end of the week. Do you want me to close it and re-open when I got things fixed? :)

**Comment by lishid** [comment]
Oh no, on worries. I was just checking in to make sure my suggestions were clear and actionable. Feel free to ping me on discord if you need help when you have time :)

**Comment by jplattel** [comment]
Just updated the plugin to fix the things you mentioned! :)

**Comment by lishid** [comment]
Seems like your merge overwrote the whole file with a line ending change. Any chance you can fix it? If not we can always open a new PR.

**Comment by jplattel** [comment]
Oh wow, didn't notice that, I did it through the Github interface itself and assumed that would do things correctly (which it didn't...)

Will close this one and create a new one :)

**Pull request closed without merging**
