### PR TITLE
Add Move Folder plugin

### PR DESCRIPTION
**Pull request by piotryordanov**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist

- [x] I have tested this on Windows, macOS, and Linux _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by pjeby** [comment]
You did not include a link to your repository in your submission.

You have also not actually published a Github *release* of your plugin, or even tagged it for release.  (The repo page shows zero tags and zero releases.)

Next, your README file does not clearly describe the purpose or provide clear usage instructions.  (A video is not usage instructions, and I had to watch it several times to get even a bare idea of what was going on; the README doesn't even say that it adds a *command* to move folders, or that it operates on the folder containing the active file, just that it "allows" you to move "a folder".)  And even after reading some of the code, I'm still not sure what it means to "go over parent directories beyond the current directory".

The plugin is called "Move Folder", but in actuality it *copies* the folder, and optionally deletes it.  This is an important distinction because copying and deletion *will not update Obsidian links*, so a user who takes the plugin name at face value may end up breaking links in their repository due to the lack of movement.  (It will also disrupt the operation of other plugins that track the location of notes, since they will see new notes and deleted notes, but not any *moved* notes.)

Finally, your plugin itself is using `fs` and `path` operations instead of Vault methods: this means it will not work on Obsidian mobile, and even if it were doing a rename instead of copy, Obsidian would see this as the external creation and deletion of files, again disrupting the operation of plugins that watch for rename operations inside Obsidian.

If the intention is to be a copy-and-maybe-delete operation, then instead of working with `fs`  and `path`, you should implement this plugin's functionality *entirely* using the Obsidian Vault's `createFolder()`, `getAbstractFileByPath()`, `copy()`, and `trash()` methods, which would make it compatible with Obsidian mobile.

However, you should probably decide whether your plugin is really intended to move folders, or copy them, and make sure the name matches what it actually does.  Copying and moving are entirely different operations in Obsidian, and you should not claim your plugin "moves" notes if it actually copies them, as users can and will experience corruption of links or loss of other plugin functionality if they assume this works the same as normal folder moves inside Obsidian.

If the intent is to provide an actual "move folder" operation, you should use the FileManager `renameFile()` method, passing in the folder object to be moved and its desired new path in the vault.  For example, `app.fileManager.renameFile(activeFile.parent, destinationFolder.path + "/" + activeFile.parent.name)` would move the current note's enclosing folder to just inside `destinationFolder`, *and* update any Obsidian links to the file(s) being moved, as well as notifying other plugins that the move happened, so they can update anything they need to as well.

For the convenience of future reviewers, please edit the issue description to include a link to your plugin repository.  You will also need to make a Github release with the proper files, in order for anyone to be able to install or test your plugin.

**Comment by piotryordanov** [comment]
Thank you so much for taking the time to give me such an in depth review. 

I will make the necessary changes then make a pull request.

**Comment by pjeby** [comment]
You do not need to make a new pull request, just update the description of this one to link to your plugin, and add a comment when it is ready for the next review.

**Comment by ericaxu** [comment]
Hi there, to keep things tidy, we're going to temporarily close plugin PRs after a month of inactivity.

Feel free to tell us to re-open it when you're ready to continue. Thanks for your understanding!

**Pull request closed without merging**
