### PR TITLE
Add ghost-fade-focus plugin.

### PR DESCRIPTION
**Pull request by skipadu**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/skipadu/obsidian-ghost-fade-focus

## Release Checklist

- [x] I have tested this on  **macOS**  _Windows & Linux not tested_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/skipadu/obsidian-ghost-fade-focus/blob/5229cec96ad83a5f22a96579846acd83306504a9/src/main.ts#L33
Please unhook this event when your plugin unloads in the `onunload()` function. You can use the `iterateCodeMirrors` to go through the currently available editors.

**Comment by lishid** [comment]
You should also cleanup everything (class names) when unloading.

**Comment by skipadu** [comment]
I released new version, [`1.0.1`](https://github.com/skipadu/obsidian-ghost-fade-focus/releases/tag/1.0.1), where these issues mentioned should be solved.
Is it okay now?

**Comment by lishid** [comment]
https://github.com/skipadu/obsidian-ghost-fade-focus/blob/1a82808fcf0d7d9fa89a6ebbac86fa17d8ff8bc3/src/main.ts#L26

I think this should be a regular `callback` instead of an `editorCallback`.

https://github.com/skipadu/obsidian-ghost-fade-focus/blob/1a82808fcf0d7d9fa89a6ebbac86fa17d8ff8bc3/src/main.ts#L95

I don't think passing this parameter in is necessary since you can query it in this function from `cm`.

---
Both are small issues, so I'll have it merged now and you can fix it later.

**Comment by skipadu** [comment]
> Both are small issues, so I'll have it merged now and you can fix it later.

Thanks for the findings! I will try to address these issues on next release version.

**Pull request merged**
