### PR TITLE
Add Golden Topaz theme

### PR DESCRIPTION
**Pull request by shaggyfeng**
# [x] I am submitting a new Community Theme

## Repo URL

(https://github.com/shaggyfeng/obsidian-Golden-Topaz-theme)

# [ ] I am submitting a new Community Plugin

## Release Checklist

- [ ] I have tested this on Windows, macOS, and Linux _(if applicable)_
- [ ] Github release contains all required files
  - [ ] `main.js`
  - [ ] `manifest.json`
  - `styles.css` _(optional)_
- [ ] Github release name matches the exact version number specified in your manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [ ] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [ ] README clearly describes the plugins purpose and provides clear usage instructions.

### CODE REVIEW

**Comment by ericaxu** [comment]
Nice theme! Could you add a static screenshot to your repo, like a `png` file? Thanks!

**Comment by shaggyfeng** [comment]
> Nice theme! Could you add a static screenshot to your repo, like a `png` file? Thanks!

Thanks. Added a `png` file.

**Comment by ericaxu** [comment]
> > Nice theme! Could you add a static screenshot to your repo, like a `png` file? Thanks!
> 
> Thanks. Added a `png` file.

Thanks!

Could you update the `screenshot` field please? And perhaps rename it to English just to be consistent with the rest of the file? Thanks!

**Comment by shaggyfeng** [comment]
> > > Nice theme! Could you add a static screenshot to your repo, like a `png` file? Thanks!
> > 
> > 
> > Thanks. Added a `png` file.
> 
> Thanks!
> 
> Could you update the `screenshot` field please? And perhaps rename it to English just to be consistent with the rest of the file? Thanks!

Sure thing. I updated the screenshot.png. Thank you for the instruction.

**Comment by shaggyfeng** [comment]
> > > Nice theme! Could you add a static screenshot to your repo, like a `png` file? Thanks!
> > 
> > 
> > Thanks. Added a `png` file.
> 
> Thanks!
> 
> Could you update the `screenshot` field please? And perhaps rename it to English just to be consistent with the rest of the file? Thanks!

Sorry, I was so noob. I just updated the field.

**Comment by ericaxu** [comment]
> > > > Nice theme! Could you add a static screenshot to your repo, like a `png` file? Thanks!
> > > 
> > > 
> > > Thanks. Added a `png` file.
> > 
> > 
> > Thanks!
> > Could you update the `screenshot` field please? And perhaps rename it to English just to be consistent with the rest of the file? Thanks!
> 
> Sorry, I was so noob. I just updated the field.

Looks perfect!

One last small thing, did you mean "Mouth on Cloud" in the author field? I guess that might be the case since your forum name is that.

**Comment by shaggyfeng** [comment]
> > > > > Nice theme! Could you add a static screenshot to your repo, like a `png` file? Thanks!
> > > > 
> > > > 
> > > > Thanks. Added a `png` file.
> > > 
> > > 
> > > Thanks!
> > > Could you update the `screenshot` field please? And perhaps rename it to English just to be consistent with the rest of the file? Thanks!
> > 
> > 
> > Sorry, I was so noob. I just updated the field.
> 
> Looks perfect!
> 
> One last small thing, did you mean "Mouth on Cloud" in the author field? I guess that might be the case since your forum name is that.

Yes, you are right.

**Comment by ericaxu** [comment]
> Yes, you are right.

Would you like to change it or should we change it after merging? @shaggyfeng

**Comment by shaggyfeng** [comment]
> > Yes, you are right.
> 
> Would you like to change it or should we change it after merging? @shaggyfeng

Please change it for me. That would be great. Thank you very much.

**Pull request merged**
