### PR TITLE
Add plugin: sync-to-xlog

### PR DESCRIPTION
**Pull request by Otto-J**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

https://github.com/Otto-J/sync-to-xlog

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Please follow the pull request template.

**Comment by Otto-J** [comment]
> Please follow the pull request template.

Sue. Done.

**Comment by joethei** [comment]
[Copyright (c) [year] [fullname]](https://github.com/Otto-J/sync-to-xlog/blob/46d3b0d49fe6c9e7132d130c78bf20c95fc0e999/LICENSE#L3)
Please fill this

["description": "A plugin let you sync your obsidian vault with xlog",](https://github.com/Otto-J/sync-to-xlog/blob/46d3b0d49fe6c9e7132d130c78bf20c95fc0e999/manifest.json#L6)
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "A plugin that does ..." in your description.

[SampleSettingTab](https://github.com/Otto-J/sync-to-xlog/blob/46d3b0d49fe6c9e7132d130c78bf20c95fc0e999/src/starterIndex.ts#L49)
Rename this class.

[onst addOrUpdateFrontMatter = async (obj: Record<string, string>) => {](https://github.com/Otto-J/sync-to-xlog/blob/46d3b0d49fe6c9e7132d130c78bf20c95fc0e999/src/utils.ts#L9-L51)
Use the `processFrontmatter` function instead: <https://github.com/obsidianmd/obsidian-api/blob/master/CHANGELOG.md#new-metadata-api>

[const response = await fetch(](https://github.com/Otto-J/sync-to-xlog/blob/46d3b0d49fe6c9e7132d130c78bf20c95fc0e999/src/model.ts#L28)
Use the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

[export const http = axios.create({](https://github.com/Otto-J/sync-to-xlog/blob/46d3b0d49fe6c9e7132d130c78bf20c95fc0e999/src/model.ts#L4-L7)
Same here, 

[<h1 class="H1">Obsidian Sync Xlog</h1>](https://github.com/Otto-J/sync-to-xlog/blob/46d3b0d49fe6c9e7132d130c78bf20c95fc0e999/src/ui/settings.vue#L2-L4)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[console.log("save");](https://github.com/Otto-J/sync-to-xlog/blob/46d3b0d49fe6c9e7132d130c78bf20c95fc0e999/src/ui/settings.vue#L138)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

**Comment by Otto-J** [comment]
- [x] MIT text fill
- [ ] change desc
- [ ] rename settingtab
- [ ] change frontmatter code
- [ ] use requeseturl,remote axios and fetch
- [x] remove setting heading text
- [x] remove useless console

**Comment by Otto-J** [comment]
All thing done. 

https://github.com/Otto-J/sync-to-xlog/releases

**Comment by Otto-J** [comment]
> [Copyright (c) [year] [fullname]](https://github.com/Otto-J/sync-to-xlog/blob/46d3b0d49fe6c9e7132d130c78bf20c95fc0e999/LICENSE#L3) Please fill this
> 
> ["description": "A plugin let you sync your obsidian vault with xlog",](https://github.com/Otto-J/sync-to-xlog/blob/46d3b0d49fe6c9e7132d130c78bf20c95fc0e999/manifest.json#L6) We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple. Avoid including sentences like "A plugin that does ..." in your description.
> 
> [SampleSettingTab](https://github.com/Otto-J/sync-to-xlog/blob/46d3b0d49fe6c9e7132d130c78bf20c95fc0e999/src/starterIndex.ts#L49) Rename this class.
> 
> [onst addOrUpdateFrontMatter = async (obj: Record<string, string>) => {](https://github.com/Otto-J/sync-to-xlog/blob/46d3b0d49fe6c9e7132d130c78bf20c95fc0e999/src/utils.ts#L9-L51) Use the `processFrontmatter` function instead: https://github.com/obsidianmd/obsidian-api/blob/master/CHANGELOG.md#new-metadata-api
> 
> [const response = await fetch(](https://github.com/Otto-J/sync-to-xlog/blob/46d3b0d49fe6c9e7132d130c78bf20c95fc0e999/src/model.ts#L28) Use the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.
> 
> [export const http = axios.create({](https://github.com/Otto-J/sync-to-xlog/blob/46d3b0d49fe6c9e7132d130c78bf20c95fc0e999/src/model.ts#L4-L7) Same here,
> 
> # Obsidian Sync Xlog
> 
> [Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)
> [console.log("save");](https://github.com/Otto-J/sync-to-xlog/blob/46d3b0d49fe6c9e7132d130c78bf20c95fc0e999/src/ui/settings.vue#L138) Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

Done. Can you review agigin？I think it is better than before.

**Pull request merged**
