### PR TITLE
Add Custom Font Plugin

### PR DESCRIPTION
**Pull request by pourmand1376**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/pourmand1376/obsidian-custom-font

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by pourmand1376** [comment]
Okay. I'll do these as soon as possible.

**Comment by joethei** [comment]
["fundingUrl_comment": "",](https://github.com/pourmand1376/obsidian-custom-font/blob/1ac287c5b5fcf5265bc5457c4adf37ce907c0827/manifest.json#L9)
That's not something Obsidian is using.

**Comment by pourmand1376** [comment]
> ["fundingUrl_comment": "",](https://github.com/pourmand1376/obsidian-custom-font/blob/1ac287c5b5fcf5265bc5457c4adf37ce907c0827/manifest.json#L9) That's not something Obsidian is using.

Thanks. I fixed that.

**Comment by pourmand1376** [comment]
Hi @joethei, 

Is there anything else I should do or change?

**Comment by liamcain** [comment]
- [createElement](https://github.com/pourmand1376/obsidian-custom-font/blob/3cce92805d4d415d0abb07b8d899756f64720c9d/main.ts#L32) you're not cleaning up any of these added style elements on plugin unload. This means users will not be able to disable the plugin completely without restarting the app

**Comment by pourmand1376** [comment]
Thanks. I added the `unload` method.

**Pull request merged**
