### PR TITLE
Add new plugin "Markdown to Slack message"

### PR DESCRIPTION
**Pull request by idreamer**
# Repo URL
- Link to my plugin: https://github.com/idreamer/markdown-to-slack-message

# Release Checklist

- [x] I have tested the plugin on
    - [ ] Windows
    - [x] macOS
    - [ ] Linux
    - [ ] Android (if applicable)
    - [ ] iOS (if applicable)

- [x] My GitHub release contains all required files
    - [x] main.js
    - [x] manifest.json
    - [x] styles.css (optional)
 
- [x] GitHub release name matches the exact version number specified in my manifest.json (Note: Use the exact version number, don't include a prefix v)
- [x] The id in my manifest.json matches the id in the community-plugins.json file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
- [x] I have given proper attribution to these other projects in my README.md.

### CODE REVIEW

**Comment by joethei** [comment]
["author": "Obsidian",](https://github.com/idreamer/markdown-to-slack-message/blob/7a9872d3f2e3312f15802f20b02cb51d0da12a9f/manifest.json#L7)
Update this with your own name.

["description": "This plugin converts a markdown note to the Slack message blocks that enables you to send to your slack",](https://github.com/idreamer/markdown-to-slack-message/blob/7a9872d3f2e3312f15802f20b02cb51d0da12a9f/manifest.json#L6)
We have recently published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This plugin" in your description.

**Comment by idreamer** [comment]
@joethei thanks for your feedback. could you review this pr again?

**Comment by joethei** [comment]
Hi there, sorry for the delay,

Since you don't have any settings in your plugin, you should remove all references to them.

**Comment by idreamer** [comment]
> Hi there, sorry for the delay,
> 
> Since you don't have any settings in your plugin, you should remove all references to them.

Thanks for this feedback. I updated the codes.

**Pull request merged**
