### PR TITLE
Add plugin: Focus Tracker

### PR DESCRIPTION
**Pull request by jeetsukumaran**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/jeetsukumaran/obsidian-focus-tracker

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [X]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [X] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[async getFrontmatter(path: string): Promise<{[key: string]: any}> {](https://github.com/jeetsukumaran/obsidian-focus-tracker/blob/e56b3eff6060aef4d4f57c3494913c234ad8bbfc/src/FocusTracker.ts#L316-L335)
To get the parsed frontmatter use `this.app.metadataCache.getFileCache(file).frontmatter`

**Comment by joethei** [comment]
Could you please explain why you did that change, and then reverted that again?

**Comment by jeetsukumaran** [comment]
> Could you please explain why you did that change, and then reverted that again?

This was a mistake -- I was debugging something else.

I re-implemented the change in the latest release.

Sorry for the confusion.

**Comment by jeetsukumaran** [comment]
> Could you please explain why you did that change, and then reverted that again?

Update: actually, it turns out that there is a functional difference.

When I use:

```
return await this.app.metadataCache.getFileCache(file)?.frontmatter || {};
```

The cache is not updated quickly enough to reflect changes made by to the frontmatter when clicking on an element (as can be seen in release 1.0.4). This results in the display being out of sync.

In release 1.0.5, I re-re-re-reverted :) back to extracting  the string and parsing:

```
            return await this.app.vault.read(file).then((result) => {
                const frontmatter = result.split("---")[1];
                if (!frontmatter) {
                    return {};
                }
                return parseYaml(frontmatter);
            });
```

and you can see the clicks work as expected, as the yaml updates immediately.

**Pull request merged**
