### PR TITLE
Add plugin: Flow

### PR DESCRIPTION
**Pull request by tavva**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/tavva/flow-release

(Note that the source code is not public. I have invited joethei to the source repo.)

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by tavva** [comment]
This is ready for review again

**Comment by tavva** [comment]
@joethei Do you know when this is likely to be reviewed again? (roughly, I'm not in a hurry :)

**Comment by liamcain** [comment]
joethei@ is still out on sick leave, he can take a look when he gets back, otherwise you can invite me to the repo and I'll take a look today.

**Comment by tavva** [comment]
Hi both, checking the status of the review. Thanks!

**Comment by tavva** [comment]
@liamcain @joethei  Hi both, hope all is well. Pinging to check the status of this and to keep the PR open – let me know if there's anything I need to do.

**Pull request merged**
