### PR TITLE
Add 'Translate' plugin

### PR DESCRIPTION
**Pull request by Fevol**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Fevol/obsidian-translate

## Release Checklist
- [X] I have tested the plugin on
  - [X]  Windows
  - [ ]  macOS
  - [X]  Linux
  - [X]  Android _(if applicable)_
  - [X]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Fevol** [comment]
Let me know if I need to change the name or ID, I've seen some comments that adding `obsidian-` is unnecessary.
Currently, there are three other translation plugins:
- `language-translator`: [Language Translator](https://github.com/twentytwokhz/language-translator)
- `obsidian-translator`: [Translator](https://github.com/luhaifeng666/obsidian-translator)
- `deepl`: [DeepL](https://github.com/friebetill/obsidian-deepl)

**Comment by liamcain** [comment]
> Let me know if I need to change the name or ID, I've seen some comments that adding obsidian- is unnecessary.

Yeah, we usually point out that you don't need the 'obsidian-' prefix since all it does it make it harder for users to find the plugin folder inside .obsidian/plugins/. Otherwise it's not a big deal.

> I could change the name to Rosetta Translate to differentiate from the other plugins, though that name might also be confusing for people searching the plugin.

It's up to you if you'd prefer a more unique name. It usually makes it more helpful for users to refer to your plugin if the name is more unique. But I can understand wanting something short and sweet too.

Code LGTM, this can go in whenever. Let me know if you'd like to fix the ID first though. You'll need to change it here and in your repo manifest.json. And you'll need update the latest release with the updated manifest.json (or alternatively cut a new release).

**Comment by Fevol** [comment]
Thank you for the review @liamcain!

For the name: I haven't been able to come up with a name that is both more descriptive, and is not easily confusable with already existing services, so I think I'm going to keep it as is.

As for the ID, am I allowed to shorten it to just `translate`?

**Comment by liamcain** [comment]
> As for the ID, am I allowed to shorten it to just translate?

Sure! As long as it's not already taken, it's fair game.

**Pull request merged**
