### PR TITLE
Add plugin: create folder notes with dropdown

### PR DESCRIPTION
**Pull request by SturdyShawn**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["main": "main.js"](https://github.com/SturdyShawn/Create-folder-notes-with-dropdown/blob/837f782d2d1a7be96512b58e007879ab097209b2/manifest.json#L10)
This is not a valid manifest entry, remove it.

['Auto Folder Creator'](https://github.com/SturdyShawn/Create-folder-notes-with-dropdown/blob/837f782d2d1a7be96512b58e007879ab097209b2/main.js#L6), [name: 'Create New File with Folders',](https://github.com/SturdyShawn/Create-folder-notes-with-dropdown/blob/837f782d2d1a7be96512b58e007879ab097209b2/main.js#L13), ['Create New File'](https://github.com/SturdyShawn/Create-folder-notes-with-dropdown/blob/837f782d2d1a7be96512b58e007879ab097209b2/main.js#L43), ['File Name: '](https://github.com/SturdyShawn/Create-folder-notes-with-dropdown/blob/837f782d2d1a7be96512b58e007879ab097209b2/main.js#L47), ['First Level Folder:',](https://github.com/SturdyShawn/Create-folder-notes-with-dropdown/blob/837f782d2d1a7be96512b58e007879ab097209b2/main.js#L60), ['Second Level Folder (Optional):',](https://github.com/SturdyShawn/Create-folder-notes-with-dropdown/blob/837f782d2d1a7be96512b58e007879ab097209b2/main.js#L70), ['Third Level Folder (Optional):',](https://github.com/SturdyShawn/Create-folder-notes-with-dropdown/blob/837f782d2d1a7be96512b58e007879ab097209b2/main.js#L80), [text: 'Create File',](https://github.com/SturdyShawn/Create-folder-notes-with-dropdown/blob/837f782d2d1a7be96512b58e007879ab097209b2/main.js#L87)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by SturdyShawn** [comment]
I've finished the required modifications. I deleted the original release and create a new release with the same tag 1.0.0

**Comment by joethei** [comment]
You got a syntax error in your manifest, the last comma has to be removed.

**Comment by SturdyShawn** [comment]
Sorry for this stupid mistake and thanks for your time!

**Pull request merged**
