### PR TITLE
Linked Data Helper plugin

### PR DESCRIPTION
**Pull request by kometenstaub**
# I am submitting a new Community Plugin

This plugin prepares the data needed for the Linked Data Vocabularies plugin, so this PR needs to be merged together with #1907.
This plugin was already once in the community plugins.

## Repo URL

Link to my plugin: https://github.com/kometenstaub/linked-data-helper

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by ericaxu** [comment]
Closing for testing...

**Comment by liamcain** [comment]
- [attachmentFolderPath](https://github.com/kometenstaub/linked-data-helper/blob/ce3a564cd99bc598134ba89d79d5a7d827bc145b/src/methods/methods-loc.ts#L56) this should use getAvailablePathForAttachments instead. Otherwise you won't properly handle "Same folder as current file"

**Comment by kometenstaub** [comment]
> [attachmentFolderPath](https://github.com/kometenstaub/linked-data-helper/blob/ce3a564cd99bc598134ba89d79d5a7d827bc145b/src/methods/methods-loc.ts#L56) this should use getAvailablePathForAttachments instead. Otherwise you won't properly handle "Same folder as current file"

That should take care of it, I think? Because it tells the user when they have chosen that setting that they need to input a path themselves.

https://github.com/kometenstaub/linked-data-helper/blob/ce3a564cd99bc598134ba89d79d5a7d827bc145b/src/settings.ts#L103-L110

**Comment by kometenstaub** [comment]
But in the settings it could be more gracefully handled with the API you provided.

**Pull request merged**
