### PR TITLE
added Note Timer plugin to community-plugins.json

### PR DESCRIPTION
**Pull request by davidvdev**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: davidvdev/obsidian-note-timer

## Release Checklist

- [ x ] I have tested this on Windows, macOS, and Linux _(if applicable)_
- [ x ] My GitHub release contains all required files
  - [ x ] `main.js`
  - [ x ] `manifest.json`
  - [ x ] `styles.css` _(optional)_
- [ x ] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [ x ] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [ x ] README clearly describes the plugins purpose and provides clear usage instructions.
- [ x ] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/davidvdev/obsidian-note-timer/blob/8558b1f6bd23fc9acbc9fc8b5d78fcdaf5c0ce08/main.ts#L63

Note that this may not always be the file that the markdown renderer has rendered. This can happen when you have multiple panes open and the active focused pane isn't the one that contains your code block. You can find the source file path from the markdown processor's context object, from which you can find the TFile from vault.

**Comment by davidvdev** [comment]
I believe this is now fixed in release [0.1.2](https://github.com/davidvdev/obsidian-note-timer/releases/tag/0.1.2). Please let me know if not, and I'll get it corrected!

**Comment by lishid** [comment]
https://github.com/davidvdev/obsidian-note-timer/blob/a60be1205e20475b549838a34ca4bba034809ce1/main.ts#L35
See: https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#avoid-iterating-all-files-to-find-a-file-by-its-path

Also, I'd recommend adding some error handling in case the file you're looking for somehow no longer exists.

**Comment by ericaxu** [comment]
Hi there, to keep things tidy, we're going to temporarily close plugin PRs after a month of inactivity.

Feel free to tell us to re-open it when you're ready to continue. Thanks for your understanding!

**Pull request closed without merging**
