### PR TITLE
Update community-plugins.json

### PR DESCRIPTION
**Pull request by Cleoche**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Cleoche/obsidian-callout-integrator

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  iPadOS
  - [x]  Android
  - [x]  iOS
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[MyPlugin](https://github.com/Cleoche/obsidian-callout-integrator/blob/40296362e6ab752e2ca962e433ea847540a1f3f4/main.ts#L4)
Rename this to something more unique.

**Comment by liamcain** [comment]
- [var](https://github.com/Cleoche/obsidian-callout-integrator/blob/d4ddc888817c4927c8b77b8fefdfb89beef179fd/main.ts#L11) I recommend you change all instances of `var` to either `const` or `let`. `var` has function-level scope, so it can easily lead to bugs if you're not careful. Here's a pretty good guide with examples of why not to use `var`: [why `var` is obsolete](https://javascript.plainenglish.io/4-reasons-why-var-is-considered-obsolete-in-modern-javascript-a30296b5f08f)
- [var](https://github.com/Cleoche/obsidian-callout-integrator/blob/d4ddc888817c4927c8b77b8fefdfb89beef179fd/main.ts#L21) same here

**Comment by liamcain** [comment]
Hi @Cleoche, I merged this before realizing that there is no "Author" field in your plugin entry. I manually added one here:

https://github.com/obsidianmd/obsidian-releases/commit/730de8aa10eab9f8c4ef44c469c3877850e1e1bc

Let me know if you'd prefer to have a different name associated with the plugin. Thanks!

**Comment by Cleoche** [comment]
When I try to install my plugin through the "browse community plugins" thing in the app, I get a "Plugin ID Mismatch" error. Any ideas on how to fix this? I looked and the ID is consistent across the manifest.json, package.json, and community-plugins.json.

**Comment by liamcain** [comment]
@Cleoche The plugin ID is mismatched in the latest Github Release: <https://github.com/Cleoche/obsidian-callout-integrator/releases/tag/1.0.2>.

The plugin ID in the manifest.json file here is "obsidian-callout-integrator." You'll need to either make a new release with the fixed plugin ID, or just reupload the manifest.json file with the corrected ID.

**Comment by Cleoche** [comment]
ah, yes I see the issue now. thank you for your time.

**Pull request merged**
