### PR TITLE
Add plugin: Three Noun Prompts

### PR DESCRIPTION
**Pull request by jamespeachh**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [https://github.com/jamespeachh/three-noun-prompts](https://github.com/jamespeachh/three-noun-prompts)

## Release Checklist

- [x]  I have tested the plugin on
    - [x]  Windows
    - [x]  macOS
    - [x]  Linux
    - [ ]  Android _(if applicable)_
    - [ ]  iOS _(if applicable)_
- [x]  My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
    - [x]  `main.js`
    - [x]  `manifest.json`
    - [ ]  `styles.css` _(optional)_
- [x]  GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x]  The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x]  My README.md describes the plugin's purpose and provides clear usage instructions.
- [x]  I have read the developer policies at [https://docs.obsidian.md/Developer+policies](https://docs.obsidian.md/Developer+policies), and have assessed my plugins's adherence to these policies.
- [x]  I have read the tips in [https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines) and have self-reviewed my plugin to avoid these common pitfalls.
- [x]  I have added a license in the LICENSE file.
- [x]  My project respects and is compatible with the original license of any code from other plugins that I'm using.  
    I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Where is the actual source code?
Did you write your code in the ``main.js` file?
In that case it should be on the repo, the bot flagged that wrongly.

**Comment by jamespeachh** [comment]
I will fix this right now. I was very confused when i got that comment from the bot LOL.

**Comment by jamespeachh** [comment]
> Where is the actual source code? Did you write your code in the ``main.js` file? In that case it should be on the repo, the bot flagged that wrongly.
fixed!

**Comment by joethei** [comment]
[let file = vault.getAbstractFileByPath(this.settings.noteTitle + ".md");](https://github.com/jamespeachh/Three-Noun-Prompts/blob/1121aaf7496eed777eefd5ce2d881243adc58ba7/main.js#L37), [file = await vault.create(this.settings.noteTitle + ".md", "# Initial Header\n");](https://github.com/jamespeachh/Three-Noun-Prompts/blob/1121aaf7496eed777eefd5ce2d881243adc58ba7/main.js#L40), [const file = this.app.vault.getAbstractFileByPath(this.settings.noteTitle + ".md");](https://github.com/jamespeachh/Three-Noun-Prompts/blob/1121aaf7496eed777eefd5ce2d881243adc58ba7/main.js#L53)
[Use `normalizePath` to clean up user defined paths](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+%60normalizePath()%60+to+clean+up+user-defined+paths)

[`${this.app.vault.configDir}/plugins/three-noun-prompts/word-list.json`](https://github.com/jamespeachh/Three-Noun-Prompts/blob/1121aaf7496eed777eefd5ce2d881243adc58ba7/main.js#L145)
That should be bundled into the plugin, Obsidian will not download the file from your release.

[.setName('Secret Key')](https://github.com/jamespeachh/Three-Noun-Prompts/blob/1121aaf7496eed777eefd5ce2d881243adc58ba7/main.js#L175), [.setName('Note Title')](https://github.com/jamespeachh/Three-Noun-Prompts/blob/1121aaf7496eed777eefd5ce2d881243adc58ba7/main.js#L186), [.setPlaceholder('Header Timer Note')](https://github.com/jamespeachh/Three-Noun-Prompts/blob/1121aaf7496eed777eefd5ce2d881243adc58ba7/main.js#L189), [.setName('Update Interval')](https://github.com/jamespeachh/Three-Noun-Prompts/blob/1121aaf7496eed777eefd5ce2d881243adc58ba7/main.js#L197), [.setName("Enable Historical List")](https://github.com/jamespeachh/Three-Noun-Prompts/blob/1121aaf7496eed777eefd5ce2d881243adc58ba7/main.js#L213)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[new Setting(containerEl)](https://github.com/jamespeachh/Three-Noun-Prompts/blob/1121aaf7496eed777eefd5ce2d881243adc58ba7/main.js#L224-L234)
There should not be a save button in settings, settings should be applied right after they have been changed.

**Pull request merged**
