### PR TITLE
Add plugin: Persian Calendar

### PR DESCRIPTION
**Pull request by maleknejad**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/maleknejad/obsidian-persian-calendar/

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
To make the manual review process and future plugin maintenance more efficient, we recommend that you move all source code files into a `src directory.

["description": "Persian Calendar plugin for managing periodic notes based on persian solar (Shamsi) calendar.",](https://github.com/maleknejad/obsidian-persian-calendar/blob/b310775cbcf553fadb218e9d4ca42f87f658d229/manifest.json#L6)
Remove "plugin" from the description, it should be obvious that this is a plugin.

["fundingUrl": {](https://github.com/maleknejad/obsidian-persian-calendar/blob/b310775cbcf553fadb218e9d4ca42f87f658d229/manifest.json#L9-L13)
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link omit this section.

[console.error('Persian Calendar view is not open. Please open the Persian Calendar first.');](https://github.com/maleknejad/obsidian-persian-calendar/blob/b310775cbcf553fadb218e9d4ca42f87f658d229/main.ts#L24), [console.error('Persian Calendar view is not open.');](https://github.com/maleknejad/obsidian-persian-calendar/blob/b310775cbcf553fadb218e9d4ca42f87f658d229/main.ts#L83), [console.error('Persian Calendar view is not open. Please open the Persian Calendar first.');](https://github.com/maleknejad/obsidian-persian-calendar/blob/b310775cbcf553fadb218e9d4ca42f87f658d229/main.ts#L103), [console.error('Persian Calendar view is not open. Please open the Persian Calendar first.');](https://github.com/maleknejad/obsidian-persian-calendar/blob/b310775cbcf553fadb218e9d4ca42f87f658d229/main.ts#L121), [console.error('Persian Calendar view is not open.');](https://github.com/maleknejad/obsidian-persian-calendar/blob/b310775cbcf553fadb218e9d4ca42f87f658d229/main.ts#L135)
This should be shown to the user in a Notice, very few users know to check the console for errors.

**Comment by maleknejad** [comment]
Thanks, i've changed everything you asked for, please check it again.

**Comment by joethei** [comment]
["fundingUrl": {](https://github.com/maleknejad/obsidian-persian-calendar/blob/075528b21eea64c6f4d30b5bbca79ad804d25667/manifest.json#L9-L10)
Remove this section completely.

**Comment by maleknejad** [comment]
done. please check it again

**Pull request merged**
