### PR TITLE
Update community-plugins.json

### PR DESCRIPTION
**Pull request by gaetanmuck**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [gaetanmuck/obsidian-flashcard-learning](https://github.com/gaetanmuck/obsidian-flashcard-learning)

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[Flascard](https://github.com/gaetanmuck/obsidian-flashcard-learning/blob/10d60b2cb769f39d6bbf3fb5709bef0e6aa26720/src/main.ts#L28)
Typo, also we recommend using sentence case for command names.

**Comment by gaetanmuck** [comment]
Typo and case corrected

**Comment by liamcain** [comment]
- [replaceSelection](https://github.com/gaetanmuck/obsidian-flashcard-learning/blob/68fdcaefa314f0c01a8ec14e661bb2aa447e6151/src/main.ts#L31) calling replaceSelection multiple times risk overriding the previous selection. I suspect this worked while testing since your selection was empty, but if you select text and then this code executes, then only the last text will appear. Instead, you should concatenate the text into one string first and call replaceSelection once.

**Comment by gaetanmuck** [comment]
`replaceSelection` is now only called once: [see code here](https://github.com/gaetanmuck/obsidian-flashcard-learning/blob/cae316e7191f966d2e16b6f697747b008ccf6c21/src/main.ts#L31)

**Pull request merged**
