### PR TITLE
Add Deep Work Theme

### PR DESCRIPTION
**Pull request by nikbrunner**
# I am submitting a new Community Theme

## Repo URL
Link to my theme: [nikbrunner/obsidian-deep-work-theme](https://github.com/nikbrunner/obsidian-deep-work-theme)

## Theme checklist
- [x] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo)
  - [x] `obsidian.css`
  - [x] The screenshot file
- [x] I have indicated which modes (dark, light, or both) are compatible with my theme
- [x] I have added a license in the LICENSE file
- [x] If my repo is not using the `master` branch, please indicate in `community-themes.json` with `"branch": "main"`.
- [x] Come up with a generic name which does not include "GitHub" directly

### CODE REVIEW

**Comment by ericaxu** [comment]
Great theme, thanks for adding it!

Since GitHub is the name of another popular product, would you mind renaming the theme (the name in the store, the repo name should be fine) into something more generic like Octocat? Thank you for considering it!

**Comment by nikbrunner** [comment]
Yes thank you. 🙏 😊 I am happy if I can contribute a little bit to Obsidian, since I am a monetary supporter for over a year now.
I was afraid, that using the name could be an issue. I need to think of something else, which also allows user to find it, when looking for a "GitHub"-like theme.

**Comment by nikbrunner** [comment]
@ericaxu 
Changed the name to something more generic, that I hope that fits your request. 😊

**Comment by ericaxu** [comment]
Great, merged!

**Pull request merged**
