### PR TITLE
Add contacts-ng plugin.

### PR DESCRIPTION
**Pull request by jwir3**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/jwir3/obsidian-contacts-ng

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  ~Android _(if applicable)_~
  - [ ]  ~iOS _(if applicable)_~
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["author": "Scott Johnson",](https://github.com/jwir3/obsidian-contacts-ng/blob/3c7e2756dca8fc0d2346b9b6a055d127206e7565/manifest.json#L7)
Credit the author of the original plugin here too.

[this.app.workspace.detachLeavesOfType(CONTACTS_VIEW_CONFIG.type);](https://github.com/jwir3/obsidian-contacts-ng/blob/3c7e2756dca8fc0d2346b9b6a055d127206e7565/src/main.ts#L47)
Do not detach leaves with your custom view in `onunload`, this is an antipattern, see: <https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Don't+detach+leaves+in+%60onunload%60>

[table.innerHTML = `](https://github.com/jwir3/obsidian-contacts-ng/blob/3c7e2756dca8fc0d2346b9b6a055d127206e7565/src/ui/sidebar/components/ContactTableView.tsx#L23-L51)
[Avoid using `innerHTML`](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%60innerHTML%60%2C+%60outerHTML%60+and+%60insertAdjacentHTML%60)

[containerEl.createEl('h2', { text: 'Settings for "Contacts NextGen" plugin.' });](https://github.com/jwir3/obsidian-contacts-ng/blob/3c7e2756dca8fc0d2346b9b6a055d127206e7565/src/settings/settings.ts#L45)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[.setName("Update Last Contact Date")](https://github.com/jwir3/obsidian-contacts-ng/blob/3c7e2756dca8fc0d2346b9b6a055d127206e7565/src/settings/settings.ts#L59)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)


[if (!folder) {](https://github.com/jwir3/obsidian-contacts-ng/blob/3c7e2756dca8fc0d2346b9b6a055d127206e7565/src/file/file.ts#L22)
You should check if `!folder instanceof TFolder` here instead.

[join(folderPath, `Contact ${findNextFileNumber(folderPath, vault)}.md`)), getNewFileContent(plugin))](https://github.com/jwir3/obsidian-contacts-ng/blob/3c7e2756dca8fc0d2346b9b6a055d127206e7565/src/file/file.ts#L27)
You can just join them with a `/`, then your plugin will also be mobile compatible.
No need to import from `path` for that.

[.then(createdFile => openFile(createdFile, workspace));](https://github.com/jwir3/obsidian-contacts-ng/blob/3c7e2756dca8fc0d2346b9b6a055d127206e7565/src/file/file.ts#L28)
[Prefer async/await over Promise](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Prefer+async%2Fawait+over+Promise)

**Comment by jwir3** [comment]
Hi @joethei:

> ["author": "Scott Johnson",](https://github.com/jwir3/obsidian-contacts-ng/blob/3c7e2756dca8fc0d2346b9b6a055d127206e7565/manifest.json#L7)
Credit the author of the original plugin here too.

Can I put in two separate "author" keys? Or should I just do something like this:
```
"author": "Scott Johnson and Vadim Beskrovnov"
```

**Comment by joethei** [comment]
the `author` property only accepts a string, so yes, do something like that.

**Comment by ericaxu** [comment]
Hi there, to keep things tidy, we're going to temporarily close plugin PRs after a month of inactivity.

Feel free to tell us to re-open it when you're ready to continue and we'll reopen the PR right away. Thanks for your understanding!

**Pull request closed without merging**
