### PR TITLE
Add Voice plugin

### PR DESCRIPTION
**Pull request by chrisurf**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: 
https://github.com/chrisurf/obsidian-voice

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["fundingUrl": "https://github.com/chrisurf",](https://github.com/chrisurf/obsidian-voice/blob/2168a5edc23cb37f9f8427898994c92a39d6562e/manifest.json#L8)
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link omit this.

[const pollyService = new PollyService(](https://github.com/chrisurf/obsidian-voice/blob/2168a5edc23cb37f9f8427898994c92a39d6562e/src/main.ts#L20-L29)
It looks like settings aren't applied, as this uses hard-coded values.

[content = await this.app.vault.cachedRead(activeView.file);](https://github.com/chrisurf/obsidian-voice/blob/2168a5edc23cb37f9f8427898994c92a39d6562e/src/main.ts#L54)
Since you alredy have a reference to the editor you can also use `editor.getValue()` here.

[this.ribbonIconEl.innerHTML =](https://github.com/chrisurf/obsidian-voice/blob/2168a5edc23cb37f9f8427898994c92a39d6562e/src/main.ts#L83-L85)
[Avoid using `innerHTML`](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%60innerHTML%60%2C+%60outerHTML%60+and+%60insertAdjacentHTML%60)
Use the `setIcon` function instead: `this.ribbonIconEl.setIcon('refresh-ccw')`;

[console.log("Play command");](https://github.com/chrisurf/obsidian-voice/blob/2168a5edc23cb37f9f8427898994c92a39d6562e/src/main.ts#L115)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[containerEl.createEl("h2", { text: "General Settings" });](https://github.com/chrisurf/obsidian-voice/blob/2168a5edc23cb37f9f8427898994c92a39d6562e/src/main.ts#L156)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)
[Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

**Comment by chrisurf** [comment]
> Only use headings under settings if you have more than one section.

I've implemented your feedback and committed a new release 0.0.2.

Except, I'm not able to replicate: [const pollyService = new PollyService(](https://github.com/chrisurf/obsidian-voice/blob/2168a5edc23cb37f9f8427898994c92a39d6562e/src/main.ts#L20-L29)
Global settings are initialised from the `../data.json` and passed onto the constructor.  Updating the voice setting changes it on the fly. Do you get any error message that you can share?

**Comment by joethei** [comment]
Ah, I see, you should not read from the `data.json` in your own code, the save & load settings functions already handle that part.


You also forgot about these two: https://github.com/chrisurf/obsidian-voice/blob/b4197962902d234c09c7ff83badee864eae1bab9/src/main.ts#L126-L134

**Comment by chrisurf** [comment]
> Ah, I see, you should not read from the `data.json` in your own code, the save & load data functions already handle that part.
> 
> You also forgot about these two: https://github.com/chrisurf/obsidian-voice/blob/b4197962902d234c09c7ff83badee864eae1bab9/src/main.ts#L126-L134

Thanks for the explanation. I have amended the coded an committed a new release 0.0.3.

**Comment by chrisurf** [comment]
@joethei in case someone plans to test the plugin, an AWS account is required. I can provide AWS testing credentials, if needed. Feel free to reach me, if I can help with aws test access. Could this be helpful?

**Comment by joethei** [comment]
Hi, sorry for the delay,

You should remove the `data.json` from your repo and add it to the `.gitignore`

[containerEl.createEl("h2", { text: "General" });](https://github.com/chrisurf/obsidian-voice/blob/8311ec6f5639e3e10901471ffba503a8bbc24e52/src/main.ts#L158)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[import { Readable } from "stream";](https://github.com/chrisurf/obsidian-voice/blob/8311ec6f5639e3e10901471ffba503a8bbc24e52/src/PollyService.ts#L2)
These imports are only available from a Node.js runtime, which means that this will throw errors on Mobile (that's a problem since you have `isDesktopOnly` marked as `false` in your manifest.json file.
I would suggest adding a polyfill.

**Comment by chrisurf** [comment]
> imports

@joethei I've implemented the changes and published the new release 0.0.4.

**Pull request merged**
