### PR TITLE
Add plugin: Toggle Readable line length

### PR DESCRIPTION
**Pull request by drichardson**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/drichardson/obsidian-toggle-readable-line-length

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by drichardson** [comment]
> [[1](https://github.com/drichardson/obsidian-toggle-readable-line-length/blob/9fbad961cb8d801345f588e6d4e5b387116714c6/main.ts#L6)]:Adding command to the command ID is not necessary, please remove it.

I get that in general, but in this case the command name and the plugin name are actually the same. I'll change it to comply with the bot overlord though.

**Comment by drichardson** [comment]
For the second point, removing `-command`. If that's the case, why does the template have `-command` suffix? I know I generally try to follow whatever conventions exist so having it there is confusion if it's supposed to be removed.

https://github.com/obsidianmd/obsidian-sample-plugin/blob/e60294b9506f44c407b214f2a4c20f22f1b9bec6/main.ts#L40

**Comment by drichardson** [comment]
Pushed changes to my repo in https://github.com/drichardson/obsidian-toggle-readable-line-length/pull/11 and https://github.com/drichardson/obsidian-toggle-readable-line-length/pull/10

**Comment by drichardson** [comment]
Retagged with 1.0.1 https://github.com/drichardson/obsidian-toggle-readable-line-length/releases/tag/1.0.1

**Comment by joethei** [comment]
The command name is still the same as the plugin name

**Comment by drichardson** [comment]
@joethei The only thing this plugin does and will ever do is toggle the readable line length. 

Changing the plugin name would make it harder to find in the plugin list. 

Are you suggesting making the command name just "Toggle"?

**Comment by joethei** [comment]
Correct, otherwise it will show up as `Toggle Readable line length: Toggle Readable line length` on the command pallete and in the hotkey settings, which is unnecessary duplication.

**Comment by drichardson** [comment]
@joethei incorporated the change

**Comment by drichardson** [comment]
https://github.com/drichardson/obsidian-toggle-readable-line-length/releases/tag/1.0.2 has the command name change

**Pull request merged**
