### PR TITLE
Add Obsidian Orthography plugin

### PR DESCRIPTION
**Pull request by denisoed**
# Obsidian plugin to check & fix orthography errors in text

https://github.com/denisoed/obsidian-orthography

* Search for spelling errors in the text
* Displaying options for correcting word mistakes
* Correct a word mistake in one click

### CODE REVIEW

**Comment by lishid** [comment]
Very cool!

Couple of suggestions:

#### https://github.com/denisoed/obsidian-orthography/blob/c7ceb8d1f774bc671ac9428cf9b9c29b4b505062/src/orthography/orthographyChecker.ts#L64

I suggest you use this way to get a reference to the CodeMirror instance: https://github.com/obsidianmd/obsidian-releases/pull/129#issuecomment-766304053

#### https://github.com/denisoed/obsidian-orthography/blob/c7ceb8d1f774bc671ac9428cf9b9c29b4b505062/src/main.ts#L11

Please add an `onunload()` function to cleanup/disable your plugin.

#### https://github.com/denisoed/obsidian-orthography/blob/c7ceb8d1f774bc671ac9428cf9b9c29b4b505062/src/main.ts#L13

You might be interested in [our built-in event emitter](https://github.com/obsidianmd/obsidian-api/blob/7f3927722e1bdd791119727236a12bb10763dd04/obsidian.d.ts#L636) which seems to be very similar to your Dispatcher.

**Comment by denisoed** [comment]
@lishid Hi ;)

1. I'll change it later. https://github.com/denisoed/obsidian-orthography/issues/2
2. Added onunload hook https://github.com/denisoed/obsidian-orthography/commit/bab8782b15d5f8a5bc39701e4d07ee4d985112cd
3. Removed my Dispacher, used obsidian Events https://github.com/denisoed/obsidian-orthography/commit/8279c05ddbb3de3064ebd5f4c3a247c12a38fd98

**Comment by lishid** [comment]
Looks great. Let me know if you want the PR merged now or after you finish with https://github.com/denisoed/obsidian-orthography/issues/2

Might need to fix the merge request as well.

**Comment by denisoed** [comment]
@lishid Please, merge this PR

I will take up this task later https://github.com/denisoed/obsidian-orthography/issues/2

**Comment by denisoed** [comment]
@lishid Will the hotkeys change field be added to the API for settings?

image

**Comment by lishid** [comment]
Not sure what you did for the merge but it seems to have rewritten the whole file: https://github.com/obsidianmd/obsidian-releases/pull/130/files
Any chance you can fix that? Worst case we can open a new PR.

> Will you add a field to change hotkeys in the Setting API?
Unlikely for now, since it's not just a single component but the whole hotkeys modal is involved in managing the hotkeys.

**Comment by denisoed** [comment]
@lishid Created new PR https://github.com/obsidianmd/obsidian-releases/pull/135 ;)

**Pull request closed without merging**
