### PR TITLE
Added plugin cloudinary1.1.0

### PR DESCRIPTION
**Pull request by uday-samsani**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/uday-samsani/obsidian-cloudinary

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Please describe in your readme how your plugin set's itself apart from the original one.

["description": "This plugin allows you to upload content(images, videos, audio) to Cloudinary and insert(copy or drag both) them into your notes.",](https://github.com/uday-samsani/obsidian-cloudinary/blob/8fd2fb08121dddb21079385287c146b402dc7927/manifest.json#L4)
We have recently published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This is a plugin" in your description.

["author": "Uday Samsani",](https://github.com/uday-samsani/obsidian-cloudinary/blob/8fd2fb08121dddb21079385287c146b402dc7927/manifest.json#L5)
Please credit the original author here too.

[Copyright (c) 2021 Jordan Handy](https://github.com/uday-samsani/obsidian-cloudinary/blob/8fd2fb08121dddb21079385287c146b402dc7927/LICENSE#L3)
Add your own information here.

[const {data} = await axios({](https://github.com/uday-samsani/obsidian-cloudinary/blob/8fd2fb08121dddb21079385287c146b402dc7927/src/main.ts#L124-L128)
I would recommend using the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

[new Notice("Cloudinary plugin is loaded", 5000)](https://github.com/uday-samsani/obsidian-cloudinary/blob/8fd2fb08121dddb21079385287c146b402dc7927/src/main.ts#L228) and [new Notice("Cloudinary plugin is unloaded", 5000)](https://github.com/uday-samsani/obsidian-cloudinary/blob/8fd2fb08121dddb21079385287c146b402dc7927/src/main.ts#L238)
These notices are unnecessary.

[href: "https://silentvoid13.github.io/Templater/",](https://github.com/uday-samsani/obsidian-cloudinary/blob/8fd2fb08121dddb21079385287c146b402dc7927/src/Settings/settings.ts#L95)
This is the wrong link.

**Comment by uday-samsani** [comment]
Changes from original plugin from Jordan Handy
- I have added various upload preset and folder based upload strategies
- I have added support for various content types
- I have also added content based tranformations
- I have added Drag and drop support
- I have also added few quality of life imporvements such as upload status in status bar, validation for settings, error logs and notices

I am also have future plans to add few more features such as dashboard for uploaded files in settings tab, delete option for uploaded files, and also delete on files and delete on link deletion. The features are not yet fully developed but I am thinking to add those as well in near future

**Comment by uday-samsani** [comment]
Hello @marcusolsson is there any issue with the pr, let me know if there is anything I need to change

**Comment by uday-samsani** [comment]
@joethei The pr status have not changed since long time by @marcusolsson can you re assign the pr if possible or let the person know this pr is active

**Comment by uday-samsani** [comment]
@joethei @marcusolsson can you see and check the pr, it has been stale since weeks.

**Comment by uday-samsani** [comment]
Necessary changes which are requested are done

**Comment by uday-samsani** [comment]
@marcusolsson I have changed the changes in question to follow the obsidian standards.

**Pull request merged**
