### PR TITLE
feat: obsidian-scroll-to-top-plugin

### PR DESCRIPTION
**Pull request by cloudhao1999**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/cloudhao1999/obsidian-scroll-to-top-plugin

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by cloudhao1999** [comment]
Some functions of the previous plug-in were not perfect, so pr was cancelled. Now I submit it again. I'm sorry

**Comment by ericaxu** [comment]
[editor && editor.exec('goStart');](https://github.com/cloudhao1999/obsidian-scroll-to-top-plugin/blob/781990a41c33b4a7e4e4ac282cf56fbde99fa90e/main.ts#L20)
If `markdownView` is not null, these are not nullable

[if (topWidget)](https://github.com/cloudhao1999/obsidian-scroll-to-top-plugin/blob/781990a41c33b4a7e4e4ac282cf56fbde99fa90e/main.ts#L54)
Under what case would `topWidget` be null?

[onClick(() => {](https://github.com/cloudhao1999/obsidian-scroll-to-top-plugin/blob/781990a41c33b4a7e4e4ac282cf56fbde99fa90e/main.ts#L60-L62)
You should be able to just do `onClick(fn)`

[if (this.maxValue < this.currentValue) return](https://github.com/cloudhao1999/obsidian-scroll-to-top-plugin/blob/781990a41c33b4a7e4e4ac282cf56fbde99fa90e/main.ts#L96)
You have semicolon on most lines but not some lines, maybe consider using an auto-formatter?

[id: 'scrollToTop'](https://github.com/cloudhao1999/obsidian-scroll-to-top-plugin/blob/781990a41c33b4a7e4e4ac282cf56fbde99fa90e/main.ts#L105)
Keep a reference instead using an id if you can. If you must use an id, consider a more unique one.

[id: 'scrollToBottom',](https://github.com/cloudhao1999/obsidian-scroll-to-top-plugin/blob/781990a41c33b4a7e4e4ac282cf56fbde99fa90e/main.ts#L116)
Same as above

[.setName('Change tooltip text of scroll to top button')](https://github.com/cloudhao1999/obsidian-scroll-to-top-plugin/blob/781990a41c33b4a7e4e4ac282cf56fbde99fa90e/main.ts#L221)
Name should be shorter than description

Otherwise looks good, thanks for submitting your plugin!

**Comment by cloudhao1999** [comment]
> 

Thank you very much for your suggestion, which has been implemented in the just submitted version 1.3.1🚀 [Release 1.3.1](https://github.com/cloudhao1999/obsidian-scroll-to-top-plugin/releases/tag/1.3.1)

**Comment by ericaxu** [comment]
> > 
> 
> Thank you very much for your suggestion, which has been implemented in the just submitted version 1.3.1🚀 [Release 1.3.1](https://github.com/cloudhao1999/obsidian-scroll-to-top-plugin/releases/tag/1.3.1)

Thanks for your quick update!

@liamcain If you don't spot major issues I can merge it. Thanks!

**Comment by liamcain** [comment]
- [crateScrollElement](https://github.com/cloudhao1999/obsidian-scroll-to-top-plugin/blob/5e47510b5b39753ddf7830e06937d794a57b11ca/main.ts#L54) typo: create
- [preview.getScroll() + 5](https://github.com/cloudhao1999/obsidian-scroll-to-top-plugin/blob/5e47510b5b39753ddf7830e06937d794a57b11ca/main.ts#L45) you could probably choose a larger interval than 5 for scrolling, right?
- [aviable](https://github.com/cloudhao1999/obsidian-scroll-to-top-plugin/blob/5e47510b5b39753ddf7830e06937d794a57b11ca/main.ts#L299) typo: available
- [aviable](https://github.com/cloudhao1999/obsidian-scroll-to-top-plugin/blob/5e47510b5b39753ddf7830e06937d794a57b11ca/main.ts#L280) typo
- [MyPlugin](https://github.com/cloudhao1999/obsidian-scroll-to-top-plugin/blob/5e47510b5b39753ddf7830e06937d794a57b11ca/main.ts#L13) you should rename your plugin class
- [crateScrollElement](https://github.com/cloudhao1999/obsidian-scroll-to-top-plugin/blob/5e47510b5b39753ddf7830e06937d794a57b11ca/main.ts#L54) you're only creating a scroll to top/bottom button in the main window, if you also want to create the buttons in pop-out windows, you'll need to listen for [`window-open`](https://github.com/obsidianmd/obsidian-api/blob/902badd38ba907689f0917d7b193f7e33d1284fe/obsidian.d.ts#L4102) and create the buttons for that window instance
- [if (this.maxValue < this.currentValue) return;](https://github.com/cloudhao1999/obsidian-scroll-to-top-plugin/blob/5e47510b5b39753ddf7830e06937d794a57b11ca/main.ts#L113-L114) you should reset the `currentValue` as soon as the query successes. But actually, instead of doing this query, I think you should just call `createButton` inside [`onLayoutReady`](https://github.com/obsidianmd/obsidian-api/blob/9bb30633586c6649474b2affdf5b87efdd86498f/obsidian.d.ts#L3626). It's a much better way to check if the workspace has loaded. Basically you'll just put the following in your onload function:
```ts
	async onload() {
                (...all the other stuff)

                this.workspace.onLayoutReady(() => {
                   this.createButton();
                });
	}
```

**Comment by cloudhao1999** [comment]
> * pop-out windows

Thank you very much for your advice. As a new contact with obsidian plug-in development, I have a lot of things I don't know. The latest version 1.4.0 has been modified, thanks again 😊

**Comment by cloudhao1999** [comment]
> 

Thank you very much for your advice. As a new contact with obsidian plug-in development, I have a lot of things I don't know. The latest version 1.4.0 has been modified, thanks again 😊

**Pull request merged**
