### PR TITLE
Add plugin: Persistent Key-Value Store

### PR DESCRIPTION
**Pull request by iamrecursion**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/iamrecursion/obsidian-pkvs

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by iamrecursion** [comment]
Oops! Forgot to attach things to the release!

**Comment by joethei** [comment]
["description": "Provides a persistent key-value store for use in scripts in Obsidian.",](https://github.com/iamrecursion/obsidian-pkvs/blob/1a3b6a5f5821dc6db23a0ed3927837904c932c5f/manifest.json#L6)
You can remove the `in Obsidian` part.

[name: "PKVS: Persist Data",](https://github.com/iamrecursion/obsidian-pkvs/blob/1a3b6a5f5821dc6db23a0ed3927837904c932c5f/main.ts#L52)
Remove the Prefix, this will read as `Persistent Key-Value Store: PKVS: Persist Data` on the command pallete

[this.app.workspace.on("quit", async (_: Tasks) => {](https://github.com/iamrecursion/obsidian-pkvs/blob/1a3b6a5f5821dc6db23a0ed3927837904c932c5f/main.ts#L61-L63)
Don't forget to register this event.

[containerEl.createEl("h3", { text: "Performance" });](https://github.com/iamrecursion/obsidian-pkvs/blob/1a3b6a5f5821dc6db23a0ed3927837904c932c5f/main.ts#L105)
There should not be a top level header in settings.

**Comment by iamrecursion** [comment]
Made the fixes in 1.0.2.

**Comment by iamrecursion** [comment]
Accidentally uploaded the TypeScript main instead. Should be good now.

**Comment by iamrecursion** [comment]
Is there anything I need to do to get this ball rolling again? There's a proper release cut now.

**Pull request merged**
