### PR TITLE
Add plugin: Browser Interface

### PR DESCRIPTION
**Pull request by jason-lieb**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/jason-lieb/obsidian-browser-interface-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
To make the manual review process and future plugin maintenance more efficient, we recommend that you move all source code files into a `src` directory.

["minAppVersion": "0.15.0",](https://github.com/jason-lieb/obsidian-browser-interface-plugin/blob/6d5bd83b9316c092da0c1872059c1cbb244c3572/manifest.json#L5)
You are using newer API's, set this to the latest public build number.


["description": "A plugin for Obsidian that allows you to interact with the browser",](https://github.com/jason-lieb/obsidian-browser-interface-plugin/blob/6d5bd83b9316c092da0c1872059c1cbb244c3572/manifest.json#L6)
Avoid including sentences like "This is a plugin for Obsidian that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

["fundingUrl": "",](https://github.com/jason-lieb/obsidian-browser-interface-plugin/blob/6d5bd83b9316c092da0c1872059c1cbb244c3572/manifest.json#L9)
If you don't have one omit this.

[const metaBind = this.app.plugins.plugins['obsidian-meta-bind-plugin']](https://github.com/jason-lieb/obsidian-browser-interface-plugin/blob/6d5bd83b9316c092da0c1872059c1cbb244c3572/main.ts#L25-L26)
You should show a message to the user if metabind is not installed.

[actions: [{type: 'command', command: 'browser-interface-plugin:open-window'}],](https://github.com/jason-lieb/obsidian-browser-interface-plugin/blob/6d5bd83b9316c092da0c1872059c1cbb244c3572/main.ts#L40), [actions: [{type: 'command', command: 'browser-interface-plugin:open-tab'}],](https://github.com/jason-lieb/obsidian-browser-interface-plugin/blob/6d5bd83b9316c092da0c1872059c1cbb244c3572/main.ts#L46), [actions: [{type: 'command', command: 'browser-interface-plugin:delete-tab'}],](https://github.com/jason-lieb/obsidian-browser-interface-plugin/blob/6d5bd83b9316c092da0c1872059c1cbb244c3572/main.ts#L52)
The plugin ID part of the command id is no longer correct.

[name: 'Open Window',](https://github.com/jason-lieb/obsidian-browser-interface-plugin/blob/6d5bd83b9316c092da0c1872059c1cbb244c3572/main.ts#L70), [name: 'Open Tab',](https://github.com/jason-lieb/obsidian-browser-interface-plugin/blob/6d5bd83b9316c092da0c1872059c1cbb244c3572/main.ts#L81), [name: 'Delete Tab',](https://github.com/jason-lieb/obsidian-browser-interface-plugin/blob/6d5bd83b9316c092da0c1872059c1cbb244c3572/main.ts#L97), [button.setButtonText('Clear Directory').onClick(async () => {](https://github.com/jason-lieb/obsidian-browser-interface-plugin/blob/6d5bd83b9316c092da0c1872059c1cbb244c3572/settings.ts#L27), [button.setButtonText('Set Directory').onClick(async () => {](https://github.com/jason-lieb/obsidian-browser-interface-plugin/blob/6d5bd83b9316c092da0c1872059c1cbb244c3572/settings.ts#L45)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by jason-lieb** [comment]
@joethei Thanks for the review. I just created a new release that addresses all your requested changes. How can I request another review?

**Comment by jason-lieb** [comment]
@joethei Can I get another review? Thanks

**Comment by jason-lieb** [comment]
@joethei Can I get another review? Thanks

**Comment by jason-lieb** [comment]
@joethei Can I get another review? Thanks

**Comment by joethei** [comment]
Sorry for the delay.
["description": "Save and reopen browser tabs using your Obsidian vault and a browser extension.",](https://github.com/jason-lieb/obsidian-browser-interface-plugin/blob/bd1e62c49e851d9efbd375ae2005d03e1afc504c/manifest.json#L6)
Please don't include "Obsidian" in the description.

**Comment by jason-lieb** [comment]
@joethei I just fixed the description. Can I get another review? Thanks

**Comment by jason-lieb** [comment]
@joethei I just fixed the description. Can I get another review? Thanks

**Comment by jason-lieb** [comment]
@joethei Can I get another review?

**Comment by jason-lieb** [comment]
@joethei Can I get another review?

**Pull request merged**
