### PR TITLE
Add plugin: Syrinscape Online Player

### PR DESCRIPTION
**Pull request by scooper4711**
Syrinscape is a TTRPG tool for ambient sounds. This plugin will allow GMs to control the Syrinscape online player from inside of notes, triggering moods and one-shot sounds.

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/scooper4711/obsidian-syrinscape

## Release Checklist
- [X] I have tested the plugin on
  - [ ]  Windows
  - [X]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [X]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [X] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by scooper4711** [comment]
@joethei - I keep rebasing to eliminate merge conflicts in the PR in order to make your review easier. Is that something you want/expect me to do? Or does that make your job more difficult?

**Comment by joethei** [comment]
You don't need to keep rebasing, I will do that before merging.

**Comment by joethei** [comment]
[authToken: 'insert-your-auth-token-here',](https://github.com/scooper4711/obsidian-syrinscape/blob/a3cb6acbeafc7ae98233d259cecb461448b9f555/src/main.ts#L16)
This should not be the default, it should be empty by default.

[const response = await fetch(apiUrl, {](https://github.com/scooper4711/obsidian-syrinscape/blob/a3cb6acbeafc7ae98233d259cecb461448b9f555/src/main.ts#L134)
Use the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

[containerEl.createEl('h2', { text: 'Syrinscape Plugin Settings' });](https://github.com/scooper4711/obsidian-syrinscape/blob/a3cb6acbeafc7ae98233d259cecb461448b9f555/src/SyrinscapeSettingsTab.ts#L18)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[.setName('Auth Token')](https://github.com/scooper4711/obsidian-syrinscape/blob/a3cb6acbeafc7ae98233d259cecb461448b9f555/src/SyrinscapeSettingsTab.ts#L26), [.setName('Cache Age')](https://github.com/scooper4711/obsidian-syrinscape/blob/a3cb6acbeafc7ae98233d259cecb461448b9f555/src/SyrinscapeSettingsTab.ts#L38), [.setName('Trigger Word')](https://github.com/scooper4711/obsidian-syrinscape/blob/a3cb6acbeafc7ae98233d259cecb461448b9f555/src/SyrinscapeSettingsTab.ts#L51), [.setName('Clear Remote Links')](https://github.com/scooper4711/obsidian-syrinscape/blob/a3cb6acbeafc7ae98233d259cecb461448b9f555/src/SyrinscapeSettingsTab.ts#L70), [.setButtonText('Clear Remote Links')](https://github.com/scooper4711/obsidian-syrinscape/blob/a3cb6acbeafc7ae98233d259cecb461448b9f555/src/SyrinscapeSettingsTab.ts#L73)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by scooper4711** [comment]
@joethei  - do I remove the 'changes requested' labels, or do you? I have addressed your comments, closed and re-opened the MR and thought perhaps the bot would make the changes.

**Comment by joethei** [comment]
The bot rescans every couple of hours, and will update the labels if all of the required changes have been made.

**Pull request merged**
