### PR TITLE
Add Copilot plugin

### PR DESCRIPTION
**Pull request by logancyang**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/logancyang/obsidian-copilot

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
What sets your plugin apart from the other existing Chat-GPT plugins?

[id: 'copilot-chat-toggle-window',](https://github.com/logancyang/obsidian-copilot/blob/f440e96b32f7c47609506aa1a9106b05554457ba/src/main.ts#L35)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

[onst res = await fetch](https://github.com/logancyang/obsidian-copilot/blob/f440e96b32f7c47609506aa1a9106b05554457ba/src/openAiStream.ts#L46)
Use `requestUrl` from the Obsidian API instead.

[export const formatDateTime = (now: Date, timezone: 'local' | 'utc' = 'local') => {](https://github.com/logancyang/obsidian-copilot/blob/f440e96b32f7c47609506aa1a9106b05554457ba/src/utils.ts#L23-L40)
Instead of this use moment, which Obsidian exports:
```ts
import {moment} from "obsidian";
moment().format("YYYY_MM_DD-HH_mm");
```

**Comment by logancyang** [comment]
@joethei Thanks for the review! I have some questions regarding the changes, but first let me answer your question.

> What sets your plugin apart from the other existing Chat-GPT plugins?

This plugin is a fully-featured ChatGPT UI as a side panel inside Obsidian. Users can interact with ChatGPT and pass texts between the chat UI and the note seamlessly without ever switching away from Obsidian, customize the params for calling OpenAI API. And it has support for various prompts (customizable prompts next) to make powerful AI features native in Obsidian. Personally I've been using custom ChatGPT UI apps on the web and on my mac, but I feel it helps me a lot if I don't need to switch back and forth, manually copying stuff and constructing prompts in another UI. I didn't find an existing plugin that fits this need yet, so I built this plugin to help my own workflow. Hopefully it may help others too.

There are more details and demos on the readme of this project: https://github.com/logancyang/obsidian-copilot

---

I removed the plugin id from the command ids. Questions about the other 2 comments:

1. I tried switching from `fetch` to `requestUrl`, but couldn't figure out how to keep the support for streaming. Since the response of ChatGPT can be quite slow and verbose (especially in the case of GPT4), it's a much better user experience to see the response streamed out than waiting for the full message. Is there a way to support that with `requestUrl`? I also don't see how it can support the abort signal.

2. I switched to using `moment` from `obsidian` for the util, thanks for the suggestion! But just curious, when I try testing using jest, the utils.test.ts complains about not having the `obsidian` module. I tried a bit to make a mock but couldn't figure out the right way. Also didn't see an example from other repos. What's the best practice to make tests for a plugin?

I'm quite new to this, would love to learn more. Thanks in advance!

**Comment by logancyang** [comment]
@joethei thanks for the answer in Discord! I addressed the reviews and updated the repo to release 1.1.1. Please let me know if there's anything else.

I added more descriptions and included more gifs as example usage for this plugin. I see some other GPT-related plugins but the goal of this project is to be the most straightforward and seamless integration of ChatGPT inside Obsidian. Any more suggestions are welcome!

**Comment by liamcain** [comment]
Hi @logancyang, I noticed that while the plugin is named "Copilot" in the plugin submission, you refer to the plugin as "Obsidian Copilot" in places throughout the app as well as in some of the marketing content. Hi, we're asking plugins to avoid calling themselves "Obsidian X" to reserve the naming convention for first-party plugins (see: Obsidian Publish, Obsidian Sync).

**Comment by logancyang** [comment]
Thank you @liamcain ! Sorry for the late reply as I was traveling last week. Will change it to "Copilot for Obsidian" instead!

**Pull request merged**
