### PR TITLE
add obsidian-quiet-outline to community-plugins.json

### PR DESCRIPTION
**Pull request by guopenghui**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/guopenghui/obsidian-quiet-outline

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/guopenghui/obsidian-quiet-outline/blob/b632c71d8a46ac466de7997959af914c0e4a9214/src/plugin.ts#L31
Don't do this - you would cause the app to unnecessarily load the mathjax module even when no mathjax is used by the user.

**Comment by lishid** [comment]
https://github.com/guopenghui/obsidian-quiet-outline/blob/b632c71d8a46ac466de7997959af914c0e4a9214/src/plugin.ts#L34
You shouldn't need to do this if you set your CSS properly. Seems like you're doing a lot of work to find out about the theme... Would be easy to do as a simple css selector.

https://github.com/guopenghui/obsidian-quiet-outline/blob/b632c71d8a46ac466de7997959af914c0e4a9214/src/plugin.ts#L140
You are not cleaning up this MutationObserver when your plugin is unloaded. That would cause a memory leak due to this being bound on document.body.

https://github.com/guopenghui/obsidian-quiet-outline/blob/b632c71d8a46ac466de7997959af914c0e4a9214/src/plugin.ts#L73
You should use the heading information in Obsidian's metadata cache instead - it has the actual markdown parsed headings with the content text and document position. This way you don't risk computing based on wrong parsing information (such as code blocks possibly having `~~~` as the delimiter.

https://github.com/guopenghui/obsidian-quiet-outline/blob/b632c71d8a46ac466de7997959af914c0e4a9214/src/plugin.ts#L101
Debounce takes an integer for milliseconds, this should be 300 instead.

https://github.com/guopenghui/obsidian-quiet-outline/blob/b632c71d8a46ac466de7997959af914c0e4a9214/src/plugin.ts#L107
This isn't necessary.

https://github.com/guopenghui/obsidian-quiet-outline/blob/b632c71d8a46ac466de7997959af914c0e4a9214/src/Outline.vue#L134
You should use [Obsidian's proper sanitizer](https://github.com/obsidianmd/obsidian-api/blob/c01fc3074deeb3dfc6ee02546d113b448735b294/obsidian.d.ts#L2682) to avoid DOM injection - your security check can easily by bypassed with `<div onload="javascript code"></div>`.

**Comment by lishid** [comment]
https://github.com/guopenghui/obsidian-quiet-outline/commit/a771c34a5f7a02812025ecbdb3b42646836b44f5#diff-e04e17442fb95f758ea1b52e11a812bb8dcffb844997fb4ccf95b422a5d64d8fR118
That's a good first step, however you should run the sanitizer last (after you run the stuff through marked).

**Comment by guopenghui** [comment]
> [guopenghui/obsidian-quiet-outline@a771c34#diff-e04e17442fb95f758ea1b52e11a812bb8dcffb844997fb4ccf95b422a5d64d8fR118](https://github.com/guopenghui/obsidian-quiet-outline/commit/a771c34a5f7a02812025ecbdb3b42646836b44f5#diff-e04e17442fb95f758ea1b52e11a812bb8dcffb844997fb4ccf95b422a5d64d8fR118) That's a good first step, however you should run the sanitizer last (after you run the stuff through marked).

There is a problem: 
If use sanitizer last, `<mjx-container>` (generated by renderMathjax) will be removed and latex formula doesn't look right.  I think it may be enough to sanitize the user input part (`option.label`) only.

**Comment by lishid** [comment]
Ah yes you are right, mathjax will get stripped. I think you can keep mathjax out of the sanitizer.

**Pull request merged**
