### PR TITLE
Add "GitHub like" theme 

### PR DESCRIPTION
**Pull request by sergey900553**
# [ ] I am submitting a new Community Theme

## Repo URL
https://github.com/sergey900553/obsidian_githublike_theme

### CODE REVIEW

**Comment by ericaxu** [comment]
Thanks for the pull request!

I'm curious why is it called GitHub like theme? 😄

**Comment by sergey900553** [comment]
I made a theme for myself with a github color palette in dark mode . Without thinking twice, I decided to share. I didn't really think about the name, you can change it to any. 

(these 2 colors are main)
image

**Comment by ericaxu** [comment]
Got it!

Sorry just noticed another issue, please request to change our themes file instead of adding your CSS file.

Example PR: https://github.com/obsidianmd/obsidian-releases/pull/302

I hope that helps!

**Comment by sergey900553** [comment]
Sorry, I'm a newbie. It seems to have fixed it.

**Comment by sergey900553** [comment]
Why do I have a branch conflict if I have not changed anything during this time?  Do I need to do something?

**Comment by lishid** [comment]
@ericaxu I fixed the merge conflict. Please merge once you're ready.

**Comment by sergey900553** [comment]
Wanted to download a theme via obsidian, but it's not there yet. And this conflict remained, do I need to do something?

**Comment by sergey900553** [comment]
As I said, you can change at your discretion

**Pull request merged**
