### PR TITLE
Add plugin: Folder Tabulation

### PR DESCRIPTION
**Pull request by SpeedaRJ**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/SpeedaRJ/obsidian_folder_tabulation/

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by SpeedaRJ** [comment]
> ### Required
> [[1](https://github.com/SpeedaRJ/obsidian_folder_tabulation/blob/b5e960280f04d418c0de8b52e9f027076c69c586/src/helper.ts#L166)][[2](https://github.com/SpeedaRJ/obsidian_folder_tabulation/blob/b5e960280f04d418c0de8b52e9f027076c69c586/src/helper.ts#L167)]:You should avoid assigning styles via JavaScript or in HTML and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets. /skip I can't really find a good way to implement this differently, some of the plugins I took as reference also handle color assignment in the same way. I understand that the purpouse of this requirement is to enable better theming, but this particular piece of code provides exactly that: Configuration of colors and only colors that can be set to anything from any theme or differentely.

**Comment by joethei** [comment]
A screenshot / GIF in the README would be nice.

[nextFileColor: "#b3b3b3",](https://github.com/SpeedaRJ/obsidian_folder_tabulation/blob/9a116ec184570c9266bce8a279cb2d2106e7f581/main.ts#L13-L14)
This would be better if you would use a accent color from: https://docs.obsidian.md/Reference/CSS+variables/Foundations/Colors
Then it's automatically looking good with any theme, and users don't need to change any settings by default.
If they want it to look different, they can write a CSS snippet.

**Comment by SpeedaRJ** [comment]
Hello @joethei, 
I'm sorry this took a while longer than I expected due to personal issues, I have updated the code-base and documentation with the requested changes.
If there's anything else need of changing please let me know.

**Comment by joethei** [comment]
[# Obsidian File Tabulation Plugin](https://github.com/SpeedaRJ/obsidian_folder_tabulation/blob/0956c056cb16d415a7814a27d7b66b0ed6735d10/README.md?plain=1#L1)
Naming something "Obsidian xyz" is reserved for first party products we create, please change this header.

**Comment by SpeedaRJ** [comment]
The title of the README file has been updated.

**Pull request merged**
