### PR TITLE
Add plugin: Geulo

### PR DESCRIPTION
**Pull request by zzunebye**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/zzunebye/obsidian-google-liked-video

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by zzunebye** [comment]
- [ ] [1]:Please remove anything from the sample plugin that you don't need.
- [ ] [1][2][3][4][5][6][7]:You should avoid assigning styles via JavaScript or in HTML and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets.
- [ ] [1]:Remember to rename the sample classes to something that makes sense to your plugin. If there are any errors, Obsidian will spit out this class name, so this will be important for users to debug if they need to.
- [ ] [1][2][3][4][5][6][7][8][9][10][11][12][13][14][15][16][17][18][19][20]:You should consider limiting the number of console.logs in your code, to not pollute the dev console.

**Comment by joethei** [comment]
["description": "Allows you to fetch all the YouTube videos you have liked, search and sort them with multiple sort options, and add them to your daily note.",](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/manifest.json#L6)
Avoid including sentences like "This allows you to ...." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[googleClientId: '2833248109-o6ap9n7tlsp2kno0tojefnsb15i1ecgl.apps.googleusercontent.com',](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/main.ts#L10-L11)
This should be empty by default.

[name: 'Open Youtube Liked Video List View',](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/main.ts#L47), [name: 'Open Youtube Liked Video Setting',](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/main.ts#L55)

[// This adds a status bar item to the bottom of the app. Does not work on mobile apps.](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/main.ts#L63-L72)
Please remove this sample code.

[res.end("Authentication successful! Please return to obsidian.");](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/auth.ts#L78)
Please use the proper capitalization of "Obsidian"

[container.createEl("h1", { text: "Liked Videos" });](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/views/LikedVideoListPane.tsx#L93), [.setName('Fetch Limit')](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/views/GoogleLikedVideoSettingTab.ts#L46), [.setName('Client Secret')](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/views/GoogleLikedVideoSettingTab.ts#L79-L80), [setName('Fetch All Liked Videos so far and add to LocalStorage')](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/views/GoogleLikedVideoSettingTab.ts#L137), [.setButtonText('Full Scan')](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/views/GoogleLikedVideoSettingTab.ts#L139), [.setName('Fetch All Liked Videos so far, compare to the stored videos and filter/add the new videos to LocalStorage')](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/views/GoogleLikedVideoSettingTab.ts#L178), [.setName('Clear LocalStorage')](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/views/GoogleLikedVideoSettingTab.ts#L303), [setButtonText('Clear Stored Liked Videos in Local Storage')](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/views/GoogleLikedVideoSettingTab.ts#L305), [item.setTitle("Add to Daily Note");](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/ui/VideoCard.tsx#L44), [item.setTitle("Display Video Info");](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/ui/VideoCard.tsx#L60)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[.setDesc('Client Secret on your own')](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/views/GoogleLikedVideoSettingTab.ts#L80)
This sentence makes no sense.

**Comment by zzunebye** [comment]
> ["description": "Allows you to fetch all the YouTube videos you have liked, search and sort them with multiple sort options, and add them to your daily note.",](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/manifest.json#L6)
> 
> Avoid including sentences like "This allows you to ...." in your description, it should be self-evident that this is a plugin for Obsidian.
> 
> We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
> 
> 
> 
> [googleClientId: '2833248109-o6ap9n7tlsp2kno0tojefnsb15i1ecgl.apps.googleusercontent.com',](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/main.ts#L10-L11)
> 
> This should be empty by default.
> 
> 
> 
> [name: 'Open Youtube Liked Video List View',](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/main.ts#L47), [name: 'Open Youtube Liked Video Setting',](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/main.ts#L55)
> 
> 
> 
> [// This adds a status bar item to the bottom of the app. Does not work on mobile apps.](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/main.ts#L63-L72)
> 
> Please remove this sample code.
> 
> 
> 
> [res.end("Authentication successful! Please return to obsidian.");](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/auth.ts#L78)
> 
> Please use the proper capitalization of "Obsidian"
> 
> 
> 
> [container.createEl("h1", { text: "Liked Videos" });](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/views/LikedVideoListPane.tsx#L93), [.setName('Fetch Limit')](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/views/GoogleLikedVideoSettingTab.ts#L46), [.setName('Client Secret')](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/views/GoogleLikedVideoSettingTab.ts#L79-L80), [setName('Fetch All Liked Videos so far and add to LocalStorage')](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/views/GoogleLikedVideoSettingTab.ts#L137), [.setButtonText('Full Scan')](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/views/GoogleLikedVideoSettingTab.ts#L139), [.setName('Fetch All Liked Videos so far, compare to the stored videos and filter/add the new videos to LocalStorage')](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/views/GoogleLikedVideoSettingTab.ts#L178), [.setName('Clear LocalStorage')](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/views/GoogleLikedVideoSettingTab.ts#L303), [setButtonText('Clear Stored Liked Videos in Local Storage')](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/views/GoogleLikedVideoSettingTab.ts#L305), [item.setTitle("Add to Daily Note");](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/ui/VideoCard.tsx#L44), [item.setTitle("Display Video Info");](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/ui/VideoCard.tsx#L60)
> 
> [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)
> 
> 
> 
> [.setDesc('Client Secret on your own')](https://github.com/zzunebye/obsidian-google-liked-video/blob/f58b71bd461ac8438a6cc0c79d75de857da8baa6/src/views/GoogleLikedVideoSettingTab.ts#L80)
> 
> This sentence makes no sense.
> 
> 
> 
> 

Hi @joethei, thank you for the detailed comment! The mentioned points that doesn't follow the guideline are changed, but are all the css styles better move to css files?

**Comment by zzunebye** [comment]
Hi @joethei, I created a new release.

**Comment by liamcain** [comment]
[localStorage](https://github.com/zzunebye/obsidian-google-liked-video/blob/b04d641736b4ab339bbce740ed3f24772dd9c0e6/src/storage.ts#L58) Just a heads up, localStorage is shared across all vaults, so you might prefer to use `app.loadLocalStorage` and `app.saveLocalStorage` which prefixes the localStorage key with an identifier to make it unique per vault. Those APIs aren't public yet, but I think it's safe enough for you to use them and just add a tsignore.

**Comment by zzunebye** [comment]
> [localStorage](https://github.com/zzunebye/obsidian-google-liked-video/blob/b04d641736b4ab339bbce740ed3f24772dd9c0e6/src/storage.ts#L58) Just a heads up, localStorage is shared across all vaults, so you might prefer to use `app.loadLocalStorage` and `app.saveLocalStorage` which prefixes the localStorage key with an identifier to make it unique per vault. Those APIs aren't public yet, but I think it's safe enough for you to use them and just add a tsignore.
> 
> Otherwise, everything else looks good to me. Nice job!

Awesome. I'll take a look for the next version.

**Pull request merged**
