### PR TITLE
add "recipe-grabber" plugin

### PR DESCRIPTION
**Pull request by seethroughdev**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/seethroughdev/obsidian-recipe-grabber

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by seethroughdev** [comment]
Updated release with source files.

**Comment by joethei** [comment]
["description": "This plugin allows you to quickly grab the contents of an online recipe. Customize the output. And preserve the metadata for when you want to go back to the source.",](https://github.com/seethroughdev/obsidian-recipe-grabber/blob/0b760fa6d44845d9261095127c848da8f88323c9/manifest.json#L6-L7)
We have recently published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This is a plugin for Obsidian" in your description.

If there is more than one `.ts` file, I generally recommend moving all code files into a separate src folder, that makes it easier to review and maintain.

[c.PLUGIN_NAME](https://github.com/seethroughdev/obsidian-recipe-grabber/blob/0b760fa6d44845d9261095127c848da8f88323c9/main.ts#L24)
Can use `this.manifest.name` instead.

[callback: () => {](https://github.com/seethroughdev/obsidian-recipe-grabber/blob/0b760fa6d44845d9261095127c848da8f88323c9/main.ts#L42)
You should use a `editorCallback` here instead, then the command will only be available if there is an active editor.

**Comment by seethroughdev** [comment]
Thanks so much @joethei .

- [x] [description updated](https://github.com/seethroughdev/obsidian-recipe-grabber/blob/761ad9c2c8cb275b49e0afefa01873faa430a04f/manifest.json#L6)
- [x] [moved all ts files to `src`](https://github.com/seethroughdev/obsidian-recipe-grabber/tree/master/src)
- [x] [remove `c.PLUGIN_NAME` in favor of `this.manifest`](https://github.com/seethroughdev/obsidian-recipe-grabber/blob/master/src/main.ts#L26)
- [x] [Replaced `callback` with `editorCallback`in modal command](https://github.com/seethroughdev/obsidian-recipe-grabber/blob/master/src/main.ts#L50)

Please let me know if there's anything I can do!

**Comment by seethroughdev** [comment]
Any advice for next steps here? Thanks.

**Comment by seethroughdev** [comment]
Any advice for next steps here @joethei? Thanks.

**Comment by marcusolsson** [comment]
- https://github.com/seethroughdev/obsidian-recipe-grabber/blob/6c9f9f79862dcedae8176e6ca22b4c5ef137e802/src/settings.ts#L26
  https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#UI+text
- https://github.com/seethroughdev/obsidian-recipe-grabber/blob/6c9f9f79862dcedae8176e6ca22b4c5ef137e802/src/settings.ts#L63
  Avoid logging normal behavior. If this is used for debugging while developing, consider disabling it in the final build.

**Comment by seethroughdev** [comment]
All changes were made above. Thanks.

**Pull request merged**
