### PR TITLE
Add plugin: Fast Image Auto Uploader

### PR DESCRIPTION
**Pull request by eust-w**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/eust-w/obsidian-image-auto-upload

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by eust-w** [comment]
> #### Hello!
> **I found the following issues in your plugin submission**
> 
> **Errors:**
> 
> ❌ The `authorUrl` field in your manifest should not point to the GitHub repository of the plugin.
> 
> This check was done automatically. Do NOT open a new PR for re-validation. Instead, to trigger this check again, make a change to your PR and wait a few minutes, or close and re-open it.

fixed

**Comment by eust-w** [comment]
> Thank you for your submission, an automated scan of your plugin code's revealed the following issues:
> 
> ### Required
> [[1](https://github.com/eust-w/obsidian-image-auto-upload/blob/7a8fdfedca1c0930c0ba1e20570504956d775b19/src/main.ts#L91)]:You should not cast this, instead use a `instanceof` check to make sure that it's actually the adapter you expect.
> 
> Do NOT open a new PR for re-validation. Once you have pushed all of the required changes to your repo, the bot will update the labels on this PR within 6 hours. If you think some of the required changes are incorrect, please comment with `/skip` and the reason why you think the results are incorrect.

thx，fixed

**Comment by joethei** [comment]
["description": "This plugin uploads images from your clipboard by goPic",](https://github.com/eust-w/obsidian-image-auto-upload/blob/7900f452eaecb8d3ebe1a8b749075259e0764e38/manifest.json#L6)
Avoid including sentences like "This is a plugin that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.


[new Notice("The selected file is not a valid TFile");](https://github.com/eust-w/obsidian-image-auto-upload/blob/7900f452eaecb8d3ebe1a8b749075259e0764e38/src/main.ts#L75)
This error message is not user friendly, instead only add the menu item if the selected file is a `TFile`

[containerEl.createEl("h2", { text: t("Plugin Settings") });](https://github.com/eust-w/obsidian-image-auto-upload/blob/7900f452eaecb8d3ebe1a8b749075259e0764e38/src/setting.ts#L34)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[console.log('Uploading file:', file.name);](https://github.com/eust-w/obsidian-image-auto-upload/blob/7900f452eaecb8d3ebe1a8b749075259e0764e38/src/uploader.ts#L54), [console.log("uploadFileByDataraw", filelistRaw);](https://github.com/eust-w/obsidian-image-auto-upload/blob/7900f452eaecb8d3ebe1a8b749075259e0764e38/src/uploader.ts#L72-L73), [console.log("command", command);](https://github.com/eust-w/obsidian-image-auto-upload/blob/7900f452eaecb8d3ebe1a8b749075259e0764e38/src/uploader.ts#L95), [console.log("mdView:",mdView)](https://github.com/eust-w/obsidian-image-auto-upload/blob/7900f452eaecb8d3ebe1a8b749075259e0764e38/src/utils.ts#L22-L23), [console.log("editor:",editor)](https://github.com/eust-w/obsidian-image-auto-upload/blob/7900f452eaecb8d3ebe1a8b749075259e0764e38/src/utils.ts#L32)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

["Samba": "Samba Storage",](https://github.com/eust-w/obsidian-image-auto-upload/blob/7900f452eaecb8d3ebe1a8b749075259e0764e38/src/lang/locale/en.ts#L5-L6), ["Gopic path": "gopic Program Path",](https://github.com/eust-w/obsidian-image-auto-upload/blob/7900f452eaecb8d3ebe1a8b749075259e0764e38/src/lang/locale/en.ts#L8-L9), ["Network Domain Black List": "Network Domain Blacklist",](https://github.com/eust-w/obsidian-image-auto-upload/blob/7900f452eaecb8d3ebe1a8b749075259e0764e38/src/lang/locale/en.ts#L17-L18)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by eust-w** [comment]
Hi @joethei 

Thanks for your detailed feedback. I've made the requested changes as follows(https://github.com/eust-w/obsidian-image-auto-upload/commit/febe67b32ed91d83bbbc6fe6884ecc4e4cd225b0):

Updated the plugin description to be more concise:

"description": "This plugin uploads images from your clipboard by goPic".
Improved error handling for invalid TFile selections:

Modified the logic to only add the menu item if the selected file is a valid TFile.
Removed the top-level heading in the settings tab:

Removed containerEl.createEl("h2", { text: t("Plugin Settings") });.
Reduced unnecessary console logging and added conditional logging for development:

Wrapped console logs with a development check.
Updated UI text to use sentence case:

Changed "Samba": "Samba Storage", "Gopic path": "gopic Program Path", and "Network Domain Black List": "Network Domain Blacklist".
Please review the changes and let me know if any further adjustments are needed.

Thanks!

**Pull request merged**
