### PR TITLE
Add plugin: Rich Foot

### PR DESCRIPTION
**Pull request by jparkerweb**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/jparkerweb/rich-foot

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "Obsidian plugin that adds backlink tags and created/modified dates to the footer of your notes.",](https://github.com/jparkerweb/rich-foot/blob/3f76aa4e381aa9ad5e5afb003e9ee34102ea6700/manifest.json#L6)
Avoid including sentences like "Obsidian plugin that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

["stylesheets": ["styles.css"]](https://github.com/jparkerweb/rich-foot/blob/3f76aa4e381aa9ad5e5afb003e9ee34102ea6700/manifest.json#L11)
This is not a valid part of the manifest, remove it.

[.setting-item {](https://github.com/jparkerweb/rich-foot/blob/3f76aa4e381aa9ad5e5afb003e9ee34102ea6700/styles.css#L130-L156)
These CSS classes are too generic, add another class/data attribute so it only applies to your plugin.

[containerEl.createEl('h1', { text: 'Rich Foot Settings' });](https://github.com/jparkerweb/rich-foot/blob/3f76aa4e381aa9ad5e5afb003e9ee34102ea6700/src/main.js#L147-L161)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.), the example should also not be there, the README already contains that information.

[.setName('Excluded Folders')](https://github.com/jparkerweb/rich-foot/blob/3f76aa4e381aa9ad5e5afb003e9ee34102ea6700/src/main.js#L164)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by jparkerweb** [comment]
@joethei I have addressed all your comments.

thank you

**Comment by joethei** [comment]
[ // Add the title](https://github.com/jparkerweb/rich-foot/blob/526cb8456f314a4bb3105771a4ec1f6da5638d9e/src/main.js#L149-L154)
This should not exist, see the guidelines I linked to above.

**Comment by jparkerweb** [comment]
@joethei 
I removed the title from settings
should be all set now

thank you

**Pull request merged**
