### PR TITLE
OpenWeather API plugin

### PR DESCRIPTION
**Pull request by willasm**
# I am submitting a new Community Plugin

## Repo URL
https://github.com/willasm/obsidian-open-weather

Link to my plugin:
https://github.com/willasm/obsidian-open-weather/releases/tag/1.1.0

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Hi @willasm do you still intend on submitting this plugin?
Please fix the validation errors so we can review it.

**Comment by willasm** [comment]
@joethei 
I have no idea how to fix this. Any edits I make do nothing as the `mark as resolved` button remains greyed out. 
This is the second time I have added this plugin with the other entry [here](https://github.com/obsidianmd/obsidian-releases/pull/1461#issue-1508530152). I added this second entry after updating the plugin, but I don't think I was supposed to do that? At any rate I have no idea what I need to do to fix this...

Just remove both entries as I have no idea on how to fix this issue and it just to frustrating trying to get this to work after three months of trying.

**Comment by I-Pch** [comment]
Sorry, I'm by no means a dev' (I've just been waiting patiently for this plugin to be added 😇 ) but wouldn't you just need to change a few things in your `manifest.json`
  
- This line [here](https://github.com/willasm/obsidian-open-weather/blob/421518f4e9d9ab931d6c64663d79d7d4a00a9165/manifest.json#L2) and remove `obsidian` from the `id` (so maybe replacing the current `id` (`obsidian-open-weather`) by `open-weather` ?) 

And also 
- This line [here](https://github.com/willasm/obsidian-open-weather/blob/421518f4e9d9ab931d6c64663d79d7d4a00a9165/manifest.json#L8) where the `authorUrl` points to the repro (`https://github.com/willasm/obsidian-open-weather`) instead of your profile (`https://github.com/willasm`)

?

(Sorry if this is stupid 😇 )

**Comment by willasm** [comment]
@I-Pch Made the changes but still getting an error. Like I said I have no idea how to fix this..
Leaving this here in case someone knows how to fix this, otherwise I give up on trying to submit this plugin.

**Comment by I-Pch** [comment]
> otherwise I give up on trying to submit this plugin.

Yes, I got that feeling reading your reply earlier and it made me sad 😔 (hence why I intervened and tried to help).

The reason the validation fails now for this PR is at least different now 😁 ! 
So you already solved that part of the puzzle here @willasm 🙌 !

The seems to fail because the plugin doesn't appears in the right place in the `community-plugins.json` (it should be added at the end, after the last entry which is the plugin `Vextab` at the moment), from what the validation bot says 😊 .

I sadly have no idea how to fix this specific validation issue 😔, so I'll keep my fingers crossed, hoping that someone more knowledgeable on the matter will help and guide you here 😊

**Comment by willasm** [comment]
@I-Pch Thanks for your encouragement. The plugin has now been added to the community plugins lst.

**Comment by I-Pch** [comment]
@willasm: Awesome 🙌 ! I'm very glad to know it all worked out in the end 😁 !

**Pull request closed without merging**
