### PR TITLE
Add plugin: Fit

### PR DESCRIPTION
**Pull request by joshuakto**
# I am submitting a new Community Plugin

## Repo URL
Link to my plugin: [fit](https://github.com/joshuakto/fit)

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [X]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [X] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
What sets your plugin apart from the "GitHub Sync", "Yet Another Obsidian Synchronizer" and "Git Integration" plugins?

["description": "File gIT - a barebone git system for files in obsidian",](https://github.com/joshuakto/fit/blob/e77d5c32802508bd3ae79ffbbbea92f1354a83c6/manifest.json#L6)
Remove "Obsidian" here

[pat: "<Personal-Access-Token>",](https://github.com/joshuakto/fit/blob/e77d5c32802508bd3ae79ffbbbea92f1354a83c6/main.ts#L18-L20)
The default for these should be a empty string.

[const DEFAULT_SETTINGS: FitSettings = {](https://github.com/joshuakto/fit/blob/e77d5c32802508bd3ae79ffbbbea92f1354a83c6/main.ts#L17-L24), [const DEFAULT_MOBILE_SETTINGS: FitSettings = {](https://github.com/joshuakto/fit/blob/e77d5c32802508bd3ae79ffbbbea92f1354a83c6/main.ts#L26-L34)
What is the difference between these two?

[this.registerInterval(window.setInterval(async () => {](https://github.com/joshuakto/fit/blob/e77d5c32802508bd3ae79ffbbbea92f1354a83c6/main.ts#L303-L312)
Either remove this code, or make the messages visible to the user, as checking the dev console is not that common.

["minAppVersion": "0.15.0",](https://github.com/joshuakto/fit/blob/e77d5c32802508bd3ae79ffbbbea92f1354a83c6/manifest.json#L5)
You are using API's that did not exist back then, set this to the latest public build number.

**Comment by joshuakto** [comment]
Thanks for the review @joethei ! I have completed all action items following the advices (all changes in release 1.0.7, and updated README to differentiate this plugin from others).

**Comment by joethei** [comment]
I don't see either one of those 3 plugins mentioned.
As far as I am concerned, your plugin is currently way to similar to them to be accepted

**Comment by joethei** [comment]
Please add that information to the readme.

**Comment by joshuakto** [comment]
Added: [README](https://github.com/joshuakto/fit/blob/master/README.md)

**Pull request merged**
