### PR TITLE
Add plugin: Color Highlighter

### PR DESCRIPTION
**Pull request by heatherpiper**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://www.github.com/heatherpiper/color-highlighter

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by heatherpiper** [comment]
/skip

5: This inline style is necessary for the settings UI layout. It's applied conditionally to a dynamically created element and is specific to the settings interface.

19: This inline style is necessary for proper rendering of Dataview inline query results. It's applied only to specific elements identified during document processing and can't be reliably targeted with a static CSS selector.

All other changes have been made and should be picked up by the bot shortly.

**Comment by joethei** [comment]
Remove the `main.js` file from your `src` folder.

**Comment by heatherpiper** [comment]
`main.js` has been removed.

**Comment by liamcain** [comment]
- [await this.app.vault.modify(activeFile, newContent);](https://github.com/heatherpiper/color-highlighter/blob/17b3e527258de0fd07838eeebe83de99489be08c/main.ts#L196) don't attempt to parse and modify the frontmatter manually. There are race conditions and edge cases that are easy to run into. You should use [`processFrontmatter`](<https://github.com/obsidianmd/obsidian-api/blob/df9434bec6883bd32727f61b1ed1336f7663d0e4/obsidian.d.ts#L1450>) instead
- [refreshAllViews](https://github.com/heatherpiper/color-highlighter/blob/17b3e527258de0fd07838eeebe83de99489be08c/main.ts#L82) this is getting called a bit too aggressively. You really shouldn't need to iterate through every open leaf and rerender it. A better way to handle this is to use a MarkdownRenderChild and add it to current context <https://github.com/obsidianmd/obsidian-api/blob/df9434bec6883bd32727f61b1ed1336f7663d0e4/obsidian.d.ts#L2260>. You can then have your component register itself to metadataCache.on('changed') and see if it needs to be redrawn. Similarly with the editor extensions. You 
- [leaf.view.previewMode.rerender(true);](https://github.com/heatherpiper/color-highlighter/blob/17b3e527258de0fd07838eeebe83de99489be08c/main.ts#L95) You should not be calling this.
- [this.app.workspace.iterateAllLeaves](https://github.com/heatherpiper/color-highlighter/blob/17b3e527258de0fd07838eeebe83de99489be08c/main.ts#L69) you should not use rebuildView. Instead, you should call updateOptions, which will automatically reload all views in the workspace <https://github.com/obsidianmd/obsidian-api/blob/df9434bec6883bd32727f61b1ed1336f7663d0e4/obsidian.d.ts#L4675>
- [refreshAllViews](https://github.com/heatherpiper/color-highlighter/blob/17b3e527258de0fd07838eeebe83de99489be08c/main.ts#L78) why are you calling refresh views right after rebuilding the views? This shouldn't be necessary either if you're using updateOptions.

**Pull request closed without merging**
