### PR TITLE
Add plugin: Differential ZIP Backup

### PR DESCRIPTION
**Pull request by vrtmrz**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/vrtmrz/diffzip

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [-] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[const w = await app.vault.adapter.list(path);](https://github.com/vrtmrz/diffzip/blob/61cb9c6b3fbf3dc12afca2f7e985429353de7e21/main.ts#L118)
It's highly discouraged that you use the global app instance in your plugin. It's currently accessible from the global context for debugging purposes, and might be removed in the future. Instead, you should use the reference to App that you have from your plugin instance.

**Comment by vrtmrz** [comment]
Thank you for the review and for pointing it out.
I could not notice this, but thanks to the review, I have fixed this!
Would you mind if I ask you to review it again?

**Comment by joethei** [comment]
["description": "Back our vault up with the least storage.",](https://github.com/vrtmrz/diffzip/blob/3830c6c1b59673f3a2932334150515ec9bf0297b/manifest.json#L6)
Don't use absolutes here.

**Comment by vrtmrz** [comment]
I appreciate the review!
Fixed exaggerations, please review it again.

**Pull request merged**
