### PR TITLE
Add Tree-Leaf Plugin

### PR DESCRIPTION
**Pull request by obsidian-canzi**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:https://github.com/obsidian-canzi/Obsidian-Tree-Leaf

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by liamcain** [comment]
- [getActiveViewOfType](https://github.com/obsidian-canzi/Obsidian-Tree-Leaf/blob/514806f0807dd2ef7bb80f8b53090aca42c7a87d/main.ts#L213) you can use [`activeEditor`](https://github.com/obsidianmd/obsidian-api/blob/38dd22168d2925086371bfc59e36fd9121527a39/obsidian.d.ts#L4009) instead, which will work inside Canvas
- [SampleModal](https://github.com/obsidian-canzi/Obsidian-Tree-Leaf/blob/514806f0807dd2ef7bb80f8b53090aca42c7a87d/main.ts#L245) this looks unused, you can remove it
- [SampleSettingTab](https://github.com/obsidian-canzi/Obsidian-Tree-Leaf/blob/514806f0807dd2ef7bb80f8b53090aca42c7a87d/main.ts#L261) you should rename this class so it's not called "SampleSettingTab"
- [onmouseover](https://github.com/obsidian-canzi/Obsidian-Tree-Leaf/blob/514806f0807dd2ef7bb80f8b53090aca42c7a87d/main.ts#L348) remove this
- [quick-preview](https://github.com/obsidian-canzi/Obsidian-Tree-Leaf/blob/514806f0807dd2ef7bb80f8b53090aca42c7a87d/main.ts#L313) you shouldn't listen for quick-preview here. That is called very frequently when a user is editing a file, so this will be very expensive to redraw the view on each keystroke.
- [var](https://github.com/obsidian-canzi/Obsidian-Tree-Leaf/blob/514806f0807dd2ef7bb80f8b53090aca42c7a87d/main.ts#L165) I recommend you change all instances of `var` to either `const` or `let`. `var` has function-level scope, so it can easily lead to bugs if you're not careful. Here's a pretty good guide with examples of why not to use `var`: [why `var` is obsolete](https://javascript.plainenglish.io/4-reasons-why-var-is-considered-obsolete-in-modern-javascript-a30296b5f08f)
- [onpen-canvaFile](https://github.com/obsidian-canzi/Obsidian-Tree-Leaf/blob/514806f0807dd2ef7bb80f8b53090aca42c7a87d/main.ts#L90) typo: open-canvas-file
- [getAbstractFileByPath](https://github.com/obsidian-canzi/Obsidian-Tree-Leaf/blob/514806f0807dd2ef7bb80f8b53090aca42c7a87d/main.ts#L94) I don't see any logic handling when this file doesn't exist.
- [000000.canvas](https://github.com/obsidian-canzi/Obsidian-Tree-Leaf/blob/514806f0807dd2ef7bb80f8b53090aca42c7a87d/main.ts#L94) what is this filename supposed to be? Is this file supposed to exist already?

**Comment by joethei** [comment]
Hi @obsidian-canzi,
I just wanted to confirm that you've seen Liams comment with the requested changes.
Do you still intend on submitting this plugin?

**Comment by obsidian-canzi** [comment]
> 你好@奥西迪安-坎子， 我只是想确认一下，你已经看到利亚姆评论与要求的变化。 你还打算提交这个插件吗？

Hello, I hope the plug-in developed by myself can enter the community. Unfortunately, my English level is as poor as that of javascript. I can't understand what's wrong with the plug-in code or what doesn't meet the requirements. I can't fix the plug-in for the time being.

**Comment by liamcain** [comment]
If there's anything I can clarify, just ask me. I linked to each spot in your code where I found a small issue. Most things that I pointed out were related to variable names but there are a couple of larger issues that I think should get fixed before this can be merged in.

**Comment by ericaxu** [comment]
Hi there, to keep things tidy, we're going to temporarily close plugin PRs after a month of inactivity.

Feel free to tell us to re-open it when you're ready to continue. Thanks for your understanding!

**Pull request closed without merging**
