### PR TITLE
Add plugin: Colored Tags Wrangler

### PR DESCRIPTION
**Pull request by AndreasSas**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/code-of-chaos/obsidian-colored_tags_wrangler

## Release Checklist
- [X] I have tested the plugin on
  - [X]  Windows
  - [ ]  macOS (I do not own a macOS device)
  - [ ]  Linux (I do not own a Linux device)
  - [X]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[import MyPlugin](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/blob/5fb8e34cc0358666aa380fd05f5ba58245d8369c/src/styles/style_manager.ts#L4-L5)
This import is using the wrong class name.

[.setName("Custom Color Tags")](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/blob/5fb8e34cc0358666aa380fd05f5ba58245d8369c/src/settings/setting_tab.ts#L49), [.setButtonText("Add New Tag")](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/blob/5fb8e34cc0358666aa380fd05f5ba58245d8369c/src/settings/setting_tab.ts#L53) and more

[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by AndreasSas** [comment]
- [x] MyPlugin has been removed
- [x] Sentence case in UI has been applied

Made the changes, and assembled them in the latest version [0.3.1](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/releases/tag/0.3.1)

**Comment by AndreasSas** [comment]
Hey there, I know reviews of these can take a long time, but I was wondering if there is something I can do to make the process easier?
I've been updating the project frequently, does that cause issues?

**Comment by liamcain** [comment]
- [saveSettings](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/blob/c431774e32d51825d98083b7c1288258a8d78556/src/event_handlers/EventHandlerMetadataChange.ts#L70) I don't think you need to save settings every time the metadata updates. This will get pretty expensive. Consider debouncing this whole function call at the very least.

**Pull request merged**
