### PR TITLE
Add plugin: Mermaid Zoom Drag

### PR DESCRIPTION
**Pull request by gitcpy**
A plugin to add zoom and drag functionality to Mermaid diagrams

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by gitcpy** [comment]
To share a plugin that could help you zoom and drag mermaid diagrams. It is useful when your Mermaid diagram too large to display completely in your md file.

**Comment by gitcpy** [comment]
Add .gitignore file

**Comment by joethei** [comment]
[main.js](https://github.com/gitcpy/mermaid-zoom-drag/blob/ba576401f91a090730d11dfab9890c0fa70e12cf/.gitignore#L2)
Since all your code is in that file it should not be in the `.gitignore`.
(Sorry, the bot sometimes flags this even if it's incorrect)

["description": "A plugin to add zoom and drag functionality to Mermaid diagrams",](https://github.com/gitcpy/mermaid-zoom-drag/blob/ba576401f91a090730d11dfab9890c0fa70e12cf/manifest.json#L6)
Avoid including sentences like "This is a plugin that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[const ver = "4.0.36";](https://github.com/gitcpy/mermaid-zoom-drag/blob/ba576401f91a090730d11dfab9890c0fa70e12cf/main.js#L3)
The version can be read from the manifest using `this.manifest.version` inside of the console.log call.

Your plugin does not support popout widnows atm, see here how to update your plugin to support pop out windows:
<https://obsidian.md/blog/how-to-update-plugins-to-support-pop-out-windows/>

---

[container.addEventListener('wheel', (event) => {](https://github.com/gitcpy/mermaid-zoom-drag/blob/ba576401f91a090730d11dfab9890c0fa70e12cf/main.js#L100), [container.addEventListener('mousedown', (event) => {](https://github.com/gitcpy/mermaid-zoom-drag/blob/ba576401f91a090730d11dfab9890c0fa70e12cf/main.js#L124), [container.addEventListener('mousemove', (event) => {](https://github.com/gitcpy/mermaid-zoom-drag/blob/ba576401f91a090730d11dfab9890c0fa70e12cf/main.js#L136), [container.addEventListener('mouseup', () => {](https://github.com/gitcpy/mermaid-zoom-drag/blob/ba576401f91a090730d11dfab9890c0fa70e12cf/main.js#L144), [container.addEventListener('mouseleave', () => {](https://github.com/gitcpy/mermaid-zoom-drag/blob/ba576401f91a090730d11dfab9890c0fa70e12cf/main.js#L151)
It should not be neccessary to register these events when reacting to the `resize` and `layout-change` events.

**Comment by gitcpy** [comment]
Thanks for your advices.


I am a fresher in obsidian, and also in programming a js plugin.&nbsp;


Following your advices, I commented "main.js" in .gitignore, and modified the description, the way to get version, and also removed the resize event.&nbsp;


But I am comfused about popout windows atm. Do you mean to support that to display messages about infos, errors, or debugs?&nbsp;


Yours sincerely.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Johannes ***@***.***&gt;; 
发送时间: 2024年7月27日(星期六) 凌晨1:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [obsidianmd/obsidian-releases] Add plugin: Mermaid Zoom Drag (PR #3948)














 
main.js
 Since all your code is in that file it should not be in the .gitignore.
 (Sorry, the bot sometimes flags this even if it's incorrect)
 
"description": "A plugin to add zoom and drag functionality to Mermaid diagrams",
 Avoid including sentences like "This is a plugin that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
 We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
 
const ver = "4.0.36";
 The version can be read from the manifest using this.manifest.version inside of the console.log call.
 
Your plugin does not support popout widnows atm, see here how to update your plugin to support pop out windows:
 https://obsidian.md/blog/how-to-update-plugins-to-support-pop-out-windows/
 
 
container.addEventListener('wheel', (event) =&gt; {, container.addEventListener('mousedown', (event) =&gt; {, container.addEventListener('mousemove', (event) =&gt; {, container.addEventListener('mouseup', () =&gt; {, container.addEventListener('mouseleave', () =&gt; {
 It should not be neccessary to register these events when reacting to the resize and layout-change events.

**Comment by gitcpy** [comment]
I am sorry to reply again. 


I think I understad the meaning of "support pop out windows".

Some plugins will pop out windows to display the md file, that is the conditon which my plugin should support for.

And I did found that my plugin did work in pop out windows. 

So I will fix it.

Thanks again.
&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "obsidianmd/obsidian-releases"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月27日(星期六) 凌晨1:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [obsidianmd/obsidian-releases] Add plugin: Mermaid Zoom Drag (PR #3948)





 
main.js
 Since all your code is in that file it should not be in the .gitignore.
 (Sorry, the bot sometimes flags this even if it's incorrect)
 
"description": "A plugin to add zoom and drag functionality to Mermaid diagrams",
 Avoid including sentences like "This is a plugin that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
 We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
 
const ver = "4.0.36";
 The version can be read from the manifest using this.manifest.version inside of the console.log call.
 
Your plugin does not support popout widnows atm, see here how to update your plugin to support pop out windows:
 https://obsidian.md/blog/how-to-update-plugins-to-support-pop-out-windows/
 
 
container.addEventListener('wheel', (event) =&gt; {, container.addEventListener('mousedown', (event) =&gt; {, container.addEventListener('mousemove', (event) =&gt; {, container.addEventListener('mouseup', () =&gt; {, container.addEventListener('mouseleave', () =&gt; {
 It should not be neccessary to register these events when reacting to the resize and layout-change events.

**Comment by liamcain** [comment]
How are the changes coming along? Are you having trouble adding support for pop-out windows? I see the resize event listener is still there too.

**Comment by gitcpy** [comment]
Thanks for your reply.&nbsp;
I checked my plugin code , and I did forget to del resize evt.
Now I deleted it and also deleleted the layout-change evt, and now I released 4.0.38.&nbsp;
But I still don't understand that there is no popout windows in my plugin and I didn't use "instanceof", 
why do i have to support and what should I do?&nbsp;
I submitted once more just now.
I hope it will go well, and bring you less trouble.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "obsidianmd/obsidian-releases"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月24日(星期六) 凌晨5:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [obsidianmd/obsidian-releases] Add plugin: Mermaid Zoom Drag (PR #3948)





 
How are the changes coming along? Are you having trouble adding support for pop-out windows? I see the resize event listener is still there too.

**Comment by liamcain** [comment]
> But I still don't understand that there is no popout windows in my plugin and I didn't use "instanceof",
why do i have to support and what should I do?&nbsp;

Popout windows are a feature of Obsidian. If your plugin does not support pop-out windows, users will have a worse experience while using your plugin. It's important for us to maintain a level of quality when doing this plugin review.

Your plugin still contains references to "document" which won't work for users that use pop-out windows. I think this plugin will work a lot more reliably if you switch to using a postprocessor. https://github.com/obsidianmd/obsidian-api/blob/df9434bec6883bd32727f61b1ed1336f7663d0e4/obsidian.d.ts#L2221

You can register a post processor which will run code every time that Obsidian renders a mermaid graph. From there, you can attach your extra elements and event listeners. Let me know if you have any questions!

**Pull request closed without merging**
