### PR TITLE
Add plugin: Reason

### PR DESCRIPTION
**Pull request by jshph**
# I am submitting a new Community Plugin

## Repo URL

https://www.reason.garden/

Link to my plugin: https://github.com/jshph/obsidian-reason

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by jshph** [comment]
Hi Obsidian team, as this plugin is open source, closed core, please let me know who I may give access to review the closed source code!

**Comment by jshph** [comment]
Update - I have decided to make the plugin fully open source. I have also updated the reason.garden site with detailed documentation of the API.

**Comment by joethei** [comment]
[async getNodeContents(nodeFile: any): Promise<any[]> {](https://github.com/jshph/obsidian-reason/blob/0edf4f21e3369c8fec93e5b3ff22c465160659be/src/source/retrieve/DataviewCandidateRetriever.ts#L89)
The first type here should be `string | TFile´

[.setName('Model Config')](https://github.com/jshph/obsidian-reason/blob/0edf4f21e3369c8fec93e5b3ff22c465160659be/src/settings/SettingsTab.ts#L18)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[.setName('Debug output')](https://github.com/jshph/obsidian-reason/blob/0edf4f21e3369c8fec93e5b3ff22c465160659be/src/settings/SettingsTab.ts#L54)
This setting should be the last one in the list.

[let canvasFile = this.app.vault.getAbstractFileByPath(canvasPath) as TFile](https://github.com/jshph/obsidian-reason/blob/0edf4f21e3369c8fec93e5b3ff22c465160659be/src/notebook/TemplateSaver.ts#L157)
Don't cast this, always do a `instanceof´ check to make sure that it's actually a file.

I see multiple uses of the Dataview API, but no error handling in case Dataview is not installed.
Please add that.

**Comment by jshph** [comment]
Thanks so much for the review @joethei ! will get to it soon as I can.

**Comment by jshph** [comment]
@joethei PR comments have been addressed, thanks again!

**Comment by jshph** [comment]
@joethei What would be the process for closed-sourcing this plugin after it's already been released? It's an option I'm considering at the moment, not seeing too much contribution activity.

**Comment by jshph** [comment]
@joethei thanks, I'd be fine for the current version of the plugin to be distributed under the same license. Hypothetically, just considering future updates to the plugin would be under closed source

**Pull request merged**
