### PR TITLE
add a enhancing mind map plugin

### PR DESCRIPTION
**Pull request by MarkMindCkm**
# [ ] I am submitting a new Community Plugin

## Repo URL
<https://github.com/MarkMindCkm/obsidian-enhancing-mindmap>

## Release Checklist

- [x] I have tested this on Windows, macOS, and Linux _(if applicable)_
- [x] Github release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] Github release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.
- [x] I have added a license in the LICENSE file

### CODE REVIEW

**Comment by lishid** [comment]
Sorry for the late review!

https://github.com/MarkMindCkm/obsidian-enhancing-mindmap/blob/e6a0f62308b4f72f34204d3d6755cdc420b0caef/src/main.ts#L62
Did you mean to detach these views on unload?

https://github.com/MarkMindCkm/obsidian-enhancing-mindmap/blob/e6a0f62308b4f72f34204d3d6755cdc420b0caef/src/main.ts#L213
This should be possible from the file-menu event, no?

https://github.com/MarkMindCkm/obsidian-enhancing-mindmap/releases/tag/0.0.5
Could reduce your bundle size from 2.5mb down to 1mb if you strip the sourcemaps for release. That'll help with memory usage :)

**Comment by MarkMindCkm** [comment]
> Sorry for the late review!
> 
> https://github.com/MarkMindCkm/obsidian-enhancing-mindmap/blob/e6a0f62308b4f72f34204d3d6755cdc420b0caef/src/main.ts#L62
> Did you mean to detach these views on unload?
> 
> https://github.com/MarkMindCkm/obsidian-enhancing-mindmap/blob/e6a0f62308b4f72f34204d3d6755cdc420b0caef/src/main.ts#L213
> This should be possible from the file-menu event, no?
> 
> https://github.com/MarkMindCkm/obsidian-enhancing-mindmap/releases/tag/0.0.5
> Could reduce your bundle size from 2.5mb down to 1mb if you strip the sourcemaps for release. That'll help with memory usage :)



Thank you for your review, @lishid . It's very appreciated.

I have addressed the feedback in this commit:
https://github.com/MarkMindCkm/obsidian-enhancing-mindmap/commit/a3514c6a66eb712f37cb07dbed52341044b4afb3

**Comment by lishid** [comment]
Nice, that's a good step.

You can get the leaf passed in from that menu instead of getting it from the activeLeaf (which is nullable!)
You might want to test the file-menu's source property for `pane-more-options` if you want to restrict the location of your menu.
https://github.com/MarkMindCkm/obsidian-enhancing-mindmap/commit/a3514c6a66eb712f37cb07dbed52341044b4afb3#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3dR141
This is the definition of the event:
https://github.com/obsidianmd/obsidian-api/blob/b0aa06eab03d8c39c0733949da5aa1edc2084b01/obsidian.d.ts#L3375

https://github.com/MarkMindCkm/obsidian-enhancing-mindmap/commit/a3514c6a66eb712f37cb07dbed52341044b4afb3#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3dR60
I think you can simplify this further if you wish by using `Workspace.detachLeavesOfType`.

**Comment by MarkMindCkm** [comment]
> Nice, that's a good step.
> 
> You can get the leaf passed in from that menu instead of getting it from the activeLeaf (which is nullable!)
> You might want to test the file-menu's source property for `pane-more-options` if you want to restrict the location of your menu.
> [MarkMindCkm/obsidian-enhancing-mindmap@a3514c6#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3dR141](https://github.com/MarkMindCkm/obsidian-enhancing-mindmap/commit/a3514c6a66eb712f37cb07dbed52341044b4afb3#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3dR141)
> This is the definition of the event:
> https://github.com/obsidianmd/obsidian-api/blob/b0aa06eab03d8c39c0733949da5aa1edc2084b01/obsidian.d.ts#L3375
> 
> [MarkMindCkm/obsidian-enhancing-mindmap@a3514c6#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3dR60](https://github.com/MarkMindCkm/obsidian-enhancing-mindmap/commit/a3514c6a66eb712f37cb07dbed52341044b4afb3#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3dR60)
> I think you can simplify this further if you wish by using `Workspace.detachLeavesOfType`.

thanks , I have fix these issues:
https://github.com/MarkMindCkm/obsidian-enhancing-mindmap/commit/62a62684da184f0a70ba65fc817794be1f3a7d2b

**Comment by danieltomasz** [comment]
The plugin doesn't update to newer versions in the Obsidian  community plugins https://github.com/MarkMindCkm/obsidian-enhancing-mindmap/issues/14

**Pull request merged**
