### PR TITLE
Added Tab Rotator plugin

### PR DESCRIPTION
**Pull request by autohub7**
# I am submitting a new Community Plugin
## Repo URL
Link to my plugin: https://github.com/autohub7/obsidian-tab-rotator

## Release Checklist
* [x]  I have tested the plugin on
  * [x]   Windows
  * [x]   macOS
  * [ ]   Linux
  * [ ]   Android _(if applicable)_
  * [x]   iOS _(if applicable)_
* [x]  My GitHub release contains all required files
  * [x]  `main.js`
  * [x]  `manifest.json`
  * [ ]  `styles.css` _(optional)_
* [x]  GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
* [x]  The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
* [x]  My README.md describes the plugin's purpose and provides clear usage instructions.
* [x]  I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
* [x]  I have added a license in the LICENSE file.
* [x]  My project respects and is compatible with the original license of any code from other plugins that I'm using.
  I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by autohub7** [comment]
I just added 1.0.3 in the repo

**Comment by liamcain** [comment]
- [iterateAllLeaves](https://github.com/autohub7/obsidian-tab-rotator/blob/2cbc0d6eb3c34cd03b4e9f92f385e8cf80ae8e75/main.ts#L111) Do you want to be iterating over all the leaves in the window or just the tabs in the current split? If you just want to iterate over tabs in the current split, you might be better off with the (private api) `let tabContainer = workspace.activeLeaf.parent` and finding the next leaf within the list of `tabContainer.children`

**Comment by autohub7** [comment]
It'd better to iterate over all the leaves (opened tabs) not only the current split

**Comment by autohub7** [comment]
@liamcain No, somehow it's automatically closed. I'm working on adding an option to rotate only on the current split

**Comment by autohub7** [comment]
Since my another PR is the same forked obsidian-release forked repo below, I'll create a new PR for Tab Rotator plugin with a new fork

https://github.com/obsidianmd/obsidian-releases/pull/1843

**Pull request closed without merging**
