### PR TITLE
Add "Obsidian Antidote Plugin"

### PR DESCRIPTION
**Pull request by Samuel-Martineau**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [Samuel-Martineau/obsidian-antidote-plugin](https://github.com/Samuel-Martineau/obsidian-antidote-plugin) 

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Samuel-Martineau** [comment]
Humm… I don't understand what happened here. I am quite certain there are no typos in the repo name. Furthermore, running the script locally does not throw these errors…

**Comment by Lisandra-dev** [comment]
> Humm… I don't understand what happened here. I am quite certain there are no typos in the repo name. Furthermore, running the script locally does not throw these errors…

Your repo is in private

**Comment by Samuel-Martineau** [comment]
I fixed it, thank you. I hadn't noticed.

**Comment by joethei** [comment]
Are you aware of the other Antidote plugin that is currently waiting for review?
See #1511, maybe you two can collaborate.

Including the word `Plugin` in your plugin name is unnecessary, I would suggest something like `Antidote Integration`
Including `obsidian` and `plugin` in the plugin ID is unnecessary.

**Comment by Samuel-Martineau** [comment]
Yes, I'm currently communicating with the author of the other plugin. My implementation will soon be merged into his. I will now close this pull request.

**Pull request closed without merging**
