### PR TITLE
Add Mousewheel Image zoom plugin

### PR DESCRIPTION
**Pull request by nicojeske**
# I am submitting a new Community Plugin

## Repo URL
Link to my plugin: https://github.com/nicojeske/mousewheel-image-zoom

## Release Checklist

- [x] I have tested this on Windows, macOS, and Linux _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/nicojeske/mousewheel-image-zoom/blob/44f84c3a73395f63aa00fadde57fee2298bb61b8/main.ts#L25
This doesn't seem used (and probably shouldn't be here anyway).

https://github.com/nicojeske/mousewheel-image-zoom/blob/44f84c3a73395f63aa00fadde57fee2298bb61b8/main.ts#L29
Rather than using keydown/keyup, you can use `WheelEvent.ctrlKey/altKey/shiftKey` to check whether your key is held down. This does however prevent you from using any keycode, but I highly doubt anyone would use non-modifier keys for this.

https://github.com/nicojeske/mousewheel-image-zoom/blob/44f84c3a73395f63aa00fadde57fee2298bb61b8/main.ts#L68
Make your function async and use await here instead of `.then()`.

https://github.com/nicojeske/mousewheel-image-zoom/blob/44f84c3a73395f63aa00fadde57fee2298bb61b8/main.ts#L144
Make sure you do this in your plugin's onunload function.

https://github.com/nicojeske/mousewheel-image-zoom/blob/44f84c3a73395f63aa00fadde57fee2298bb61b8/main.ts#L157
Should rename this class.

**Comment by nicojeske** [comment]
Thank you very much for your feedback.
I refactored the corresponding parts in my code and published a new release of the plugin.

**Comment by nicojeske** [comment]
This approach works flawlesslyand is now implemented.

https://github.com/nicojeske/mousewheel-image-zoom/blob/ff04ca15227edcfb97eefadfaf6ed144185dc12b/main.ts#L114

**Comment by nicojeske** [comment]
Hello there!

I recently added support for resizing online images that are linked in Obsidian.

Let me know if there is anything else standing in the way of officially releasing the plugin.

**Comment by lishid** [comment]
I'm so sorry I fixed the merge conflict but forgot to perform the actual merge!

**Comment by nicojeske** [comment]
No problem!

Thanks for merging :)

**Pull request merged**
