### PR TITLE
Add Sidebar Toggler to Community Plugins

### PR DESCRIPTION
**Pull request by chrisgrieser**
# I am submitting a new Community Plugin
Sidebar Toggler allows finer control over the Obsidian sidebars. Provides URI commands for people using window managers.

## Repo URL

Link to my plugin: https://github.com/chrisgrieser/obsidian-sidebar-toggler

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
- [ ] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [ ] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [ x My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by chrisgrieser** [comment]
> Regarding the URL schema, why not have `showLeft=true&showRight=false`? It's non-standard to require 2 arguments for a single purpose (`side` & `show`) and the current form won't let you toggle both sidebars in a single call. So if you want to toggle both sidebars, you need 2 URIs

Ah, that's actually way smarter than my implementation. Implemented in latest release, and changed Readme accordingly.

**Comment by liamcain** [comment]
Looks like you didn't push the changes to the README.

**Comment by chrisgrieser** [comment]
oops, you are right. pushed updated readme.

**Comment by chrisgrieser** [comment]
I just noticed: this seems to have been merged into the branch or something? It's not in the community plugins

**Comment by joethei** [comment]
It's the other way around,
Liam merged the current version of the repo into your copy probably to avoid a merge conflict.

**Comment by chrisgrieser** [comment]
does that mean I have to do something or does Liam have to do something? (I just merged obsidianmd:master into my branch again, if that was the issue holding everything up)

**Comment by joethei** [comment]
@liamcain just needs to press the merge button now if I read his previous messages correctly

**Comment by liamcain** [comment]
Ah, sorry. I thought I merged this! The merge commit was just me fixing the merge conflict.

**Pull request merged**
