### PR TITLE
Add plugin: CoCo AskAI

### PR DESCRIPTION
**Pull request by yamfeel**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/yamfeel/coco-askai

This is a closed-source Obsidian plugin.
Provide a simplified multi-window AI interaction method.
obsidian developer can check the project code.

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Please give me access to the source code so I can review it.

**Comment by yamfeel** [comment]
> Please give me access to the source code so I can review it.

Sure, I've just sent you an invitation to access the repository. Looking forward to your review! Thanks~ https://github.com/yamfeel/coco-askai-source

**Comment by yamfeel** [comment]
@joethei Thank you for your feedback. I've made the necessary updates to address your concerns. https://github.com/yamfeel/coco-askai-source/issues/1#issuecomment-1936996427

**Comment by yamfeel** [comment]
@joethei  Hello! This has been handled. Thank you!
https://github.com/yamfeel/coco-askai-source/issues/1#issuecomment-1974293687

**Pull request merged**
