### PR TITLE
Update community-plugins.json

### PR DESCRIPTION
**Pull request by Clemens-E**
# I am submitting a new Community Plugin

## Repo URL

https://github.com/Clemens-E/obsidian-languagetool-plugin

## Release Checklist

- [x] I have tested this on Windows and Linux
- [ ] I have tested this on macOS
- [x] Github release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] Github release name matches the exact version number specified in your manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.

### CODE REVIEW

**Comment by lishid** [comment]
Cool plugin! Couple of suggestions:

https://github.com/Clemens-E/obsidian-languagetool-plugin/blob/6dffd3609a1046112a6a5d8b96739759ef9cbe46/src/index.ts#L77
Maybe also use await here instead of mixing promise callbacks?

https://github.com/Clemens-E/obsidian-languagetool-plugin/blob/6dffd3609a1046112a6a5d8b96739759ef9cbe46/src/index.ts#L126
Seems like you'll be attaching multiple copies of this event handler when you run detection multiple times.

**Comment by Clemens-E** [comment]
Good catch with the event.
I fixed both issues, can you check again?

**Comment by lishid** [comment]
I probably missed this in the first pass, but:

https://github.com/Clemens-E/obsidian-languagetool-plugin/blob/0ab9fdab5d8ba9b222689cd22179635dafeb7972/src/index.ts#L61
view could be empty here if the user is focused on a non-markdown pane. Probably a good idea to check for truthiness.

https://github.com/Clemens-E/obsidian-languagetool-plugin/blob/0ab9fdab5d8ba9b222689cd22179635dafeb7972/src/index.ts#L62
Actually, you're registering a click handler for the entire app - you should probably check that the click event's target is within the editor's bounds. I'd recommend using [`node.contains(otherNode)`](https://developer.mozilla.org/en-US/docs/Web/API/Node/contains) to check that.

https://github.com/Clemens-E/obsidian-languagetool-plugin/blob/0ab9fdab5d8ba9b222689cd22179635dafeb7972/src/index.ts#L88
Same as above.

https://github.com/Clemens-E/obsidian-languagetool-plugin/blob/0ab9fdab5d8ba9b222689cd22179635dafeb7972/src/index.ts#L101
Same as above, view could be null.

**Comment by Clemens-E** [comment]
updated again, lmk if there is anything else

**Comment by lishid** [comment]
LGTM, will merge as soon as the merge conflict is resolved.

**Pull request merged**
