### PR TITLE
Add plugin: obsidotion

### PR DESCRIPTION
**Pull request by p32929**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/p32929/obsidotion

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by p32929** [comment]
is there anything I need to do here?

**Comment by p32929** [comment]
is there anything I need to do here? @joethei

**Comment by joethei** [comment]
[console.log = function () { };](https://github.com/p32929/obsidotion/blob/34d70d84f3f68c13ec90cb5f6e09ede7e2e1f8e0/main.ts#L2)
This overwrites the logging of all plugins, remove this and remove the `console.log` call's in your code.

[// Position ribbon buttons at the bottom](https://github.com/p32929/obsidotion/blob/34d70d84f3f68c13ec90cb5f6e09ede7e2e1f8e0/main.ts#L52-L57)
Please don't do this, users can set the order of the ribbon icons in the settings or by dragging them around, a plugin should not overwrite this behavior.

[containerEl.createEl('h2', { text: 'Settings for Obsidian to Notion plugin.' });](https://github.com/p32929/obsidotion/blob/34d70d84f3f68c13ec90cb5f6e09ede7e2e1f8e0/main.ts#L123)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[.setName('Convert Tags')](https://github.com/p32929/obsidotion/blob/34d70d84f3f68c13ec90cb5f6e09ede7e2e1f8e0/main.ts#L148), 
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[yaml.stringify(frontmatter)](https://github.com/p32929/obsidotion/blob/34d70d84f3f68c13ec90cb5f6e09ede7e2e1f8e0/DownloadFromNotion.ts#L77), [yaml.stringify(yamlObj)](https://github.com/p32929/obsidotion/blob/34d70d84f3f68c13ec90cb5f6e09ede7e2e1f8e0/Upload2Notion.ts#L152)
Use `stringifyYaml` from the Obsidian API.

[const yamlObj = yamlFrontMatter.loadFront(markdown) as any;](https://github.com/p32929/obsidotion/blob/34d70d84f3f68c13ec90cb5f6e09ede7e2e1f8e0/Upload2Notion.ts#L146)
To get the parsed frontmatter of a file use `this.plugin.app.metadataCache.getFileCache(file)?.frontmatter`

**Comment by p32929** [comment]
Okay, I'll make the changes and comment here. Thanks

**Comment by p32929** [comment]
I have updated the files/codes accordingly. Thanks

**Comment by p32929** [comment]
Hi, is there anything else I need to update here? 
@joethei

**Comment by joethei** [comment]
[Copyright (c) 2024 Fayaz Bin Salam](https://github.com/p32929/obsidotion/blob/de2097fe7e2567b9869f8319f9f97f1b3a9fb4ee/LICENSE#L3), ["author": "p32929",](https://github.com/p32929/obsidotion/blob/de2097fe7e2567b9869f8319f9f97f1b3a9fb4ee/manifest.json#L7)
Please credit the developer that wrote the original plugin code here and in the README.

["minAppVersion": "0.15.0",](https://github.com/p32929/obsidotion/blob/de2097fe7e2567b9869f8319f9f97f1b3a9fb4ee/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

["description": "a simple obsidian plugin that syncs from/to obsidian/notion",](https://github.com/p32929/obsidotion/blob/de2097fe7e2567b9869f8319f9f97f1b3a9fb4ee/manifest.json#L6)
Avoid including sentences like "This is a plugin for Obsidian that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[async updateYamlInfo(notionID: string, url: string, file: TFile, filePath: string) {](https://github.com/p32929/obsidotion/blob/de2097fe7e2567b9869f8319f9f97f1b3a9fb4ee/Upload2Notion.ts#L140-L150)
To update the frontmatter use the `processFrontmatter` function.

**Comment by p32929** [comment]
about the copywright, Fayaz Bin Salam is my original name and p32929 is my github username. & I am the original developer. do I still have to change anything in the copywright section?

& the rest, I'll update after I get the answer to my question. Thanks

**Comment by joethei** [comment]
Your plugin is a fork of another plugin, please credit the author of that plugin.

**Comment by joethei** [comment]
There are many similarities in code and in the naming of functions between your plugin and this one: https://github.com/EasyChris/obsidian-to-notion

**Comment by p32929** [comment]
okay, but I dont think its something I need to credit the dev of https://github.com/EasyChris/obsidian-to-notion

**Pull request closed without merging**
