### PR TITLE
Add plugin: Dataview Serializer

### PR DESCRIPTION
**Pull request by dsebastien**
# I am submitting a new Community Plugin

## Repo URL
Link to my plugin: https://github.com/dsebastien/obsidian-dataview-serializer

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by dsebastien** [comment]
Hello,

I have extracted the styles as requested. I have kept the `as` cast, because I did a check using `instanceof` just before. I cast for type safety.

**Comment by dsebastien** [comment]
Hello. Is there anything I can do to move this PR forward?

**Comment by joethei** [comment]
Please mention that Dataview needs to be installed in your README.

**Comment by dsebastien** [comment]
Done

**Comment by dsebastien** [comment]
Hello. Is there anything more to do?

**Comment by dsebastien** [comment]
Hello @joethei. I'm sorry to insist, but is there anything more I can do? I fully understand the pressure you must be under with all the open PRs, so please don't be offended. I'd just love to be able to share more news about this plugin :)

**Pull request merged**
