### PR TITLE
Add Content Linker Plugin

### PR DESCRIPTION
**Pull request by Medill-East**
Added content linker into community-plugins.json

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/Medill-East/obsidian-content-linker

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
- [x] I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Medill-East** [comment]
Hi~ Thanks for the review~
Already updated it as required :)

**Comment by liamcain** [comment]
- [loadDataFromVault](https://github.com/Medill-East/obsidian-content-linker/blob/89dfa09b569dcfe20bfe1c4856f59fa068f07479/main.ts#L54) Please use loadData() and saveData from the Obsidian API for storing your data (https://github.com/obsidianmd/obsidian-api/blob/249eb773347588f4e9fec7c600e1904cd9240fcb/obsidian.d.ts#L2982). This allows the data to be compatible with syncing platforms like Obsidian Sync

**Comment by Medill-East** [comment]
Thanks for the info!
Hi @joethei ~ I am not sure why you removed the "changes requested" tag.. I guess I still need to do the changes from using loadDataFromVault() to the official loadData() function? no?

**Comment by joethei** [comment]
Yes, those should still be fixed.
The label change is done by a script, it must have malfunctioned.
Sorry about that.

**Comment by Medill-East** [comment]
Got it, no worries, thanks for the explanation :) Will try to update as requested~

**Comment by Medill-East** [comment]
Hi, I have updated it according to the request, could you please review it again, thanks!

**Pull request merged**
