### PR TITLE
Add plugin: Command Tracker

### PR DESCRIPTION
**Pull request by namikaze-40p**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/namikaze-40p/obsidian-command-tracker

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by namikaze-40p** [comment]
/skip
This “command” is part of the command name, so I don't think it's necessary to exclude it.

**Comment by namikaze-40p** [comment]
@joethei 
The [pipeline](https://github.com/obsidianmd/obsidian-releases/actions/runs/10386131942/job/28756741441#step:3:12) for “/skip” failed.
Could you tell me how to respond when you have the time?

**Comment by joethei** [comment]
[containerEl.createEl('h2').setText('Command Tracker - Settings');](https://github.com/namikaze-40p/obsidian-command-tracker/blob/6169e326e128b865017fb7fb4d4dd5373df19bf7/src/settings.ts#L63)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[div.createEl('h6', { text: 'Command Tracker View' });](https://github.com/namikaze-40p/obsidian-command-tracker/blob/6169e326e128b865017fb7fb4d4dd5373df19bf7/src/view.ts#L123)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by namikaze-40p** [comment]
@joethei 
Thanks for the review!
I have fixed the following. Could you review it again?

---
> [containerEl.createEl('h2').setText('Command Tracker - Settings');](https://github.com/namikaze-40p/obsidian-command-tracker/blob/6169e326e128b865017fb7fb4d4dd5373df19bf7/src/settings.ts#L63)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

I fixed it in [this commit](https://github.com/namikaze-40p/obsidian-command-tracker/commit/2d4c461abebf2be8b29d6c87dfc325db7a4bb2ab).

---
> [div.createEl('h6', { text: 'Command Tracker View' });](https://github.com/namikaze-40p/obsidian-command-tracker/blob/6169e326e128b865017fb7fb4d4dd5373df19bf7/src/view.ts#L123)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

I fixed it in [this commit](https://github.com/namikaze-40p/obsidian-command-tracker/commit/f4459dc8a7029e8326ae580750034015cddfb472).

---

**Pull request merged**
