### PR TITLE
add new timelines-pro plugin

### PR DESCRIPTION
**Pull request by SaiRS**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/x-ideas/timelines-pro

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[Copyright (c) 2014 SINTEF-9012](https://github.com/x-ideas/timelines-pro/blob/51f8d41b23dae046d56d1e50fa3e9e9d64fe3f15/LICENSE.txt#L3)
Update this with your own info.

[id: 'render-timelines-pro',](https://github.com/x-ideas/timelines-pro/blob/51f8d41b23dae046d56d1e50fa3e9e9d64fe3f15/src/main.ts#L71)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

[name: 'Render Timeline ',](https://github.com/x-ideas/timelines-pro/blob/51f8d41b23dae046d56d1e50fa3e9e9d64fe3f15/src/main.ts#L72)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[this.app.workspace.detachLeavesOfType(TIMELINE_PANEL);](https://github.com/x-ideas/timelines-pro/blob/51f8d41b23dae046d56d1e50fa3e9e9d64fe3f15/src/main.ts#L102)
Do not detach leaves with your custom view in `onunload`, this is an antipattern, see: <https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Don't+detach+leaves+in+%60onunload%60>

[containerEl.createEl('h2', { text: 'Obsidian Timelines Settings' });](https://github.com/x-ideas/timelines-pro/blob/51f8d41b23dae046d56d1e50fa3e9e9d64fe3f15/src/settings.ts#L17)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)
[Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

[item.setTitle(`重命名: "${eventTag}"`);](https://github.com/x-ideas/timelines-pro/blob/51f8d41b23dae046d56d1e50fa3e9e9d64fe3f15/src/ui/timeline-manage/index.ts#L71)
You should stick to one language.

**Comment by SaiRS** [comment]
@joethei I made the changes as requested!

**Comment by ericaxu** [comment]
@SaiRS Hi, did you submit it somewhere else or do you no longer want to submit this plugin?

**Comment by SaiRS** [comment]
> @SaiRS Hi, did you submit it somewhere else or do you no longer want to submit this plugin?

I am still maintaining this project, and now it is only used in my personal obsidian project, and I have the idea of ​​submitting a plugin later, but before that, I think it will take some time to do a more comprehensive verification, such as UI interaction, Performance testing (this is also the reason why sentry was submitted before)

**Pull request closed without merging**
