### PR TITLE
Add File Cleaner plugin

### PR DESCRIPTION
**Pull request by Johnson0907**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Johnson0907/obsidian-file-cleaner

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/Johnson0907/obsidian-file-cleaner/blob/a02b5ba31ebbfa1cb02fe75116d814bb90b35696/main.ts#L21
You can use the new for-of loops here like this:

```ts
for (let file of files) {
	if (file.stat.size === 0) {
		cleanFiles.push(file);
	}
}
```

https://github.com/Johnson0907/obsidian-file-cleaner/blob/a02b5ba31ebbfa1cb02fe75116d814bb90b35696/main.ts#L30
Same as above.

https://github.com/Johnson0907/obsidian-file-cleaner/blob/a02b5ba31ebbfa1cb02fe75116d814bb90b35696/main.ts#L32
Here you should add `await`, and you will also need to make your function `async () => {`.

**Comment by Johnson0907** [comment]
Thanks for your guidance, the code is updated.

**Comment by lishid** [comment]
https://github.com/Johnson0907/obsidian-file-cleaner/blob/46c5fc0816b4cc6c26df5a05a25c8e5ee2581b56/main.ts#L32
Don't make it run async like that because it won't be awaited for properly. You should add the async keyword to the top level function here: https://github.com/Johnson0907/obsidian-file-cleaner/blob/46c5fc0816b4cc6c26df5a05a25c8e5ee2581b56/main.ts#L15

**Comment by Johnson0907** [comment]
I have updated the code, thanks.

**Comment by lishid** [comment]
Looks good. You should avoid using `var` and always use `let` or `const`.

**Comment by Johnson0907** [comment]
I am not a computer major, this is my first time learning to program to achieve my own needs.
I got so much from obsidian. Thank you very much for your guidance.

**Pull request merged**
