### PR TITLE
Add plugin: Simple Todo

### PR DESCRIPTION
**Pull request by elliotxx**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/elliotxx/obsidian-simple-todo

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by elliotxx** [comment]
@joethei Excuse me, can you help review this PR

**Comment by joethei** [comment]
To make the manual review process and future plugin maintenance more efficient, we recommend that you move all source code files into a `src` directory.

[# Obsidian Simple Todo](https://github.com/elliotxx/obsidian-simple-todo/blob/1d87a587a041fd5259ff746736a10655193efc5c/README.md#L1)
Naming something "Obsidian xyz" is reserved for first party products we create, please change this header.

["description": "A minimalist text-based todo manager (Text-Based GTD) plugin for efficient task management.",](https://github.com/elliotxx/obsidian-simple-todo/blob/1d87a587a041fd5259ff746736a10655193efc5c/manifest.json#L6)
Don't include "plugin" in the description.

[import moment from 'moment';](https://github.com/elliotxx/obsidian-simple-todo/blob/1d87a587a041fd5259ff746736a10655193efc5c/main.ts#L2)
Import this from the Obsidian package instead.

[if (!dir) {](https://github.com/elliotxx/obsidian-simple-todo/blob/1d87a587a041fd5259ff746736a10655193efc5c/main.ts#L628)
This check should be `if (dir instanceof TFolder)`, as `getAbstractFileByPath` could also return a `TFile`.

[new Setting(containerEl)](https://github.com/elliotxx/obsidian-simple-todo/blob/1d87a587a041fd5259ff746736a10655193efc5c/settings.ts#L25-L41)
This should not be a setting, get the locale configured in the Obsidian settings with `moment.locale();`

[// 添加重新加载命令的方法](https://github.com/elliotxx/obsidian-simple-todo/blob/1d87a587a041fd5259ff746736a10655193efc5c/main.ts#L677-L718)
Then you can also remove this code, as one needs to restart Obsidian for the language setting to be applied.


[inProgress: "In Progress",](https://github.com/elliotxx/obsidian-simple-todo/blob/1d87a587a041fd5259ff746736a10655193efc5c/i18n/locales/en.ts#L11), [unknown: "Unknown Status"](https://github.com/elliotxx/obsidian-simple-todo/blob/1d87a587a041fd5259ff746736a10655193efc5c/i18n/locales/en.ts#L13), [name: "Toggle Todo Status",](https://github.com/elliotxx/obsidian-simple-todo/blob/1d87a587a041fd5259ff746736a10655193efc5c/i18n/locales/en.ts#L26), [name: "Reschedule Previous Todos",](https://github.com/elliotxx/obsidian-simple-todo/blob/1d87a587a041fd5259ff746736a10655193efc5c/i18n/locales/en.ts#L30), [name: "Archive Completed Todos",](https://github.com/elliotxx/obsidian-simple-todo/blob/1d87a587a041fd5259ff746736a10655193efc5c/i18n/locales/en.ts#L37)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[<h3>变更前后对比</h3>](https://github.com/elliotxx/obsidian-simple-todo/blob/1d87a587a041fd5259ff746736a10655193efc5c/components/TodoDiffViewer.tsx#L32), [<button className="mod-cta" onClick={onConfirm}>确认 (Enter)</button>](https://github.com/elliotxx/obsidian-simple-todo/blob/1d87a587a041fd5259ff746736a10655193efc5c/components/TodoDiffViewer.tsx#L45-L46)
This should also use the i18n system, like the rest of your code.

**Comment by joethei** [comment]
[new Setting(containerEl)](https://github.com/elliotxx/obsidian-simple-todo/blob/abe29c424823b2e3c6f1940cb6ee1293b447e1ba/src/settings.ts#L25-L41)
Remove this setting and get the current language from `moment.locale()` instead.

[reloadCommands() {](https://github.com/elliotxx/obsidian-simple-todo/blob/abe29c424823b2e3c6f1940cb6ee1293b447e1ba/src/main.ts#L680-L720)
Then remove this code.

**Comment by elliotxx** [comment]
@joethei Excuse me, could you please double check

**Pull request merged**
