### PR TITLE
Add Remote Attachments Plugin

### PR DESCRIPTION
**Pull request by NewYearNewPhil**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/NewYearNewPhil/remote-attachments

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [x]  Android
  - [ ]  iOS
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by NewYearNewPhil** [comment]
I've added some quality of life improvements and enabled compatibility with mobile devices. the latest tag is [1.1.0](https://github.com/NewYearNewPhil/obsidian-nextcloud/releases/tag/1.1.0)

**Comment by joethei** [comment]
[Copyright (c) 2018 tentwentyfour](https://github.com/NewYearNewPhil/obsidian-nextcloud/blob/91760ccb37b6ce39ab0454c54a20fc0bd1e8c13f/LICENSE#L3)
Update this with your own info.

[id: 'nextcloud-download',](https://github.com/NewYearNewPhil/obsidian-nextcloud/blob/91760ccb37b6ce39ab0454c54a20fc0bd1e8c13f/src/main.ts#L27)
Obsidian will automatically prefix the command id with the plugin id,
You don't need to include `nextcloud` in the id here.

[import { PassThrough } from 'stream';](https://github.com/NewYearNewPhil/obsidian-nextcloud/blob/91760ccb37b6ce39ab0454c54a20fc0bd1e8c13f/src/nextcloud.ts#L2)
Have you tested your plugin on mobile?
`stream` is a Node.js library and should not work on mobile.

**Comment by NewYearNewPhil** [comment]
Hi there! I've created a new [release](https://github.com/NewYearNewPhil/obsidian-nextcloud/releases/tag/1.1.1) which implements the requested changes :
- changes copyright info
- removes plugin id prefix from commands
- adds a `fetch` shim to use Obsidian's builtin `requestUrl`

The `stream` library as well as some other node core libraries are polyfilled using `esbuild-plugin-polyfill-node`. Full functionality on mobile has been tested.

**Comment by NewYearNewPhil** [comment]
I've made lots of changes to this plugin, to the point that its now a generic remote attachment plugin.
I've also changed the plugin id and name, as it hasn't been included with its former name I hope this is unproblematic.

**Comment by NewYearNewPhil** [comment]
Applied the requested changes 👍

**Comment by liamcain** [comment]
Can we remove this fetch() shim? It looks like it will impact all plugins that are using fetch()

**Comment by NewYearNewPhil** [comment]
My apologies - somehow it completely slipped my mind that globally overwriting `window.fetch` would affect others 🤦 Will try to get rid of it. Closing here until then.

**Pull request closed without merging**
