### PR TITLE
Add "Center Headers 1 and 2" Snippet

### PR DESCRIPTION
**Pull request by Bluemoondragon07**
Please switch to **Preview** and select one of the following links:

* [Community Plugin](?template=plugin.md)
* [Community Theme](?template=theme.md)

### CODE REVIEW

**Comment by joethei** [comment]
We currently don't offer a way to download snippets in the app, the file still exists in the repo from a previous test.

Your snippet is also missing the `.css` extension.

**Comment by Bluemoondragon07** [comment]
Ah, I see. Does Obsidian have an official collection of snippets elsewhere?

**Comment by joethei** [comment]
No, you can find many on our forum though.

**Comment by Bluemoondragon07** [comment]
Okay. Thank you so much.

**Pull request closed without merging**
