### PR TITLE
New Plugin: ChatGPT MD

### PR DESCRIPTION
**Pull request by bramses**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/bramses/chatgpt-md

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["fundingUrl": "https://www.bramadams.dev/#/portal/",](https://github.com/bramses/chatgpt-md/blob/e8ffcaf0654524e26cd9c8ebabc7132754acf32d/manifest.json#L9)
I don't see any donation links on this page.

**Comment by bramses** [comment]
@joethei its a newsletter -- I dont have a pattern or anything

**Comment by liamcain** [comment]
- [filter](https://github.com/bramses/chatgpt-md/blob/e8ffcaf0654524e26cd9c8ebabc7132754acf32d/main.ts#L440) it would probably be more efficient to use [`getAbstractFileByPath`](https://github.com/obsidianmd/obsidian-api/blob/902badd38ba907689f0917d7b193f7e33d1284fe/obsidian.d.ts#L3612) to get the TFolder, then return the TFolder's children
- [HR](https://github.com/bramses/chatgpt-md/blob/e8ffcaf0654524e26cd9c8ebabc7132754acf32d/main.ts#L376) I'm not sure "HR" is very clear for users that might not be familiar with `hr` html tags. Maybe the command could be more clear if it was called "add new chat block" or something similar?
- [Create New Chat From Template](https://github.com/bramses/chatgpt-md/blob/e8ffcaf0654524e26cd9c8ebabc7132754acf32d/main.ts#L400) nit: commands should be We recommend that all commands use [Sentence case](https://en.wiktionary.org/wiki/sentence_case) for their names. This maximizes readability in the command palette.
- [Create New Chat with Highlighted Text](https://github.com/bramses/chatgpt-md/blob/e8ffcaf0654524e26cd9c8ebabc7132754acf32d/main.ts#L385) same here
- [statusBarItemEl.setText("");](https://github.com/bramses/chatgpt-md/blob/e8ffcaf0654524e26cd9c8ebabc7132754acf32d/main.ts#L366) since you are creating a new statusbBarEl each time the command is called, you should detach the element at the end of the command. The other option is to create the statusbarEl in your onload, then just setText at the beginning of the command. That way you only ever create one statusbar element.

**Comment by bramses** [comment]
@liamcain all addressed in https://github.com/bramses/chatgpt-md/releases/tag/1.0.1! Thanks!

- [filter improvements](https://github.com/bramses/chatgpt-md/blob/master/main.ts#L462-L470)
- [moved status bar to onload](https://github.com/bramses/chatgpt-md/blob/master/main.ts#L322)
- [renamed to sentence case](https://github.com/bramses/chatgpt-md/blob/master/main.ts#L425)
- [used "Add divider" (its more technically correct than chat block)](https://github.com/bramses/chatgpt-md/blob/master/main.ts#L401)

**Pull request merged**
