### PR TITLE
[NEW] Adds czottmann/obsidian-mononote

### PR DESCRIPTION
**Pull request by czottmann**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/czottmann/obsidian-mononote

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[${PLUGIN_INFO.pluginVersion}](https://github.com/czottmann/obsidian-mononote/blob/07196e805e90b127a972ddc61297d81b02e16595/src/main.ts#L10)
You can access this from `this.manifest.version`

**Comment by czottmann** [comment]
> [${PLUGIN_INFO.pluginVersion}](https://github.com/czottmann/obsidian-mononote/blob/07196e805e90b127a972ddc61297d81b02e16595/src/main.ts#L10) You can access this from `this.manifest.version`

Thanks @joethei, good to know! In the context of this review, is this a showstopper or information?

**Comment by joethei** [comment]
In this case, it's information.

**Comment by czottmann** [comment]
@liamcain @joethei Is there anything else I can help you with regarding this review? It's been a month since our last contact…

**Comment by liamcain** [comment]
- [activeLeaf](https://github.com/czottmann/obsidian-mononote/blob/07196e805e90b127a972ddc61297d81b02e16595/src/main.ts#L35) this seems to be making an implicit assumption that the file-open event was fired from the activeLeaf. That's not necessarily true. You can open files in the background
- I'm not sure what the expected behavior is if you follow a link [[someFileThatIsAlreadyOpen]]. Should this cause the current tab to be closed and the old tab to be focused?
- [leaf != activeLeaf](https://github.com/czottmann/obsidian-mononote/blob/07196e805e90b127a972ddc61297d81b02e16595/src/main.ts#L50) `!==`

**Comment by liamcain** [comment]
Since this works okay for the base case, I'm going to merge this in, but I think you should probably reconsider the approach for handling the more complex cases.

**Comment by czottmann** [comment]
@liamcain Thanks for the merge!

> * [activeLeaf](https://github.com/czottmann/obsidian-mononote/blob/07196e805e90b127a972ddc61297d81b02e16595/src/main.ts#L35) this seems to be making an implicit assumption that the file-open event was fired from the activeLeaf. That's not necessarily true. You can open files in the background

How would I get notified about those?

> * I'm not sure what the expected behavior is if you follow a link [[someFileThatIsAlreadyOpen]]. Should this cause the current tab to be closed and the old tab to be focused?

Exactly. That's the whole reason for this plugin. If the file's already open, don't open it in another tab, just focus the existing one.

> * [leaf != activeLeaf](https://github.com/czottmann/obsidian-mononote/blob/07196e805e90b127a972ddc61297d81b02e16595/src/main.ts#L50) `!==`

Typo, will be fixed, thanks! No idea why VS Code didn't complain about that weak check, it's set to do it.

**Comment by liamcain** [comment]
> How would I get notified about those

image

Try with this setting disabled, the file-open event should still fire, but the file won't be the activeLeaf. You'll need to handle that case separately.

> Exactly. That's the whole reason for this plugin. If the file's already open, don't open it in another tab, just focus the existing one.

But in that case, I wouldn't want my current tab to be closed. I would expect it to just refocus the existing tab and my old tab would still be in the same position.

**Comment by czottmann** [comment]
> Try with this setting disabled, the file-open event should still fire, but the file won't be the activeLeaf. You'll need to handle that case separately.

Will try that, thanks!

> But in that case, I wouldn't want my current tab to be closed. I would expect it to just refocus the existing tab and my old tab would still be in the same position.

As an example, let's assume you're coming in via an XCU call, the call opens a note, but that note is already open in another tab. Mononote gets the "file opened" notice for the new tab, so it'll check the list of open tabs, it will find the existing tab from earlier, focus that and close the new opened tab.

**Comment by liamcain** [comment]
What's XCU?

**Comment by czottmann** [comment]
Ah sorry, too many acronyms 😅 XCU = x-callback-url, i.e. `obsidian://`.

**Pull request merged**
