### PR TITLE
Add File Hider plugin to Community Plugin List

### PR DESCRIPTION
**Pull request by Oliver-Akins**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Oliver-Akins/file-hider

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by liamcain** [comment]
https://github.com/Oliver-Akins/file-hider/blob/716e12aa4051af0a2c481839166d75bfdb2501a4/src/utils.ts#L11 you can improve the typing here and make this `createStyleLine(type: "folder" | "file", path: string)`

https://github.com/Oliver-Akins/file-hider/blob/716e12aa4051af0a2c481839166d75bfdb2501a4/src/utils.ts#L24 don't use `var`. This should be `const` instead. Also, don't use `for ... in` to iterate over a list. That's for iterating over the properties of an object. You should use `for ... of` instead.

https://github.com/Oliver-Akins/file-hider/blob/716e12aa4051af0a2c481839166d75bfdb2501a4/src/utils.ts#L24 I think you can add an `id` to your stylesheet, then you don't have to traversal all the stylesheets looking at the contents to find yours. To do that, you can just create your own `<style id="file-hider-styles">` and attach the styles there, rather than relying on the `styles.css` file being loaded.

https://github.com/Oliver-Akins/file-hider/blob/716e12aa4051af0a2c481839166d75bfdb2501a4/src/main.ts#L82 you shouldn't need to save the settings on unload

https://github.com/Oliver-Akins/file-hider/blob/716e12aa4051af0a2c481839166d75bfdb2501a4/src/main.ts#L103 If there's an issue that causes the findStyleSheet to always return `null`, then users could end up in an infinite loop here. I suggest removing this redundancy and instead just initialize the styles inside `layoutReady`.

https://github.com/Oliver-Akins/file-hider/blob/716e12aa4051af0a2c481839166d75bfdb2501a4/src/main.ts#L125-L129 `this.style.disabled = this.settings.hidden;`

https://github.com/Oliver-Akins/file-hider/blob/716e12aa4051af0a2c481839166d75bfdb2501a4/src/main.ts#L126 you also need to assume that `this.style` could be null here.

**Comment by Oliver-Akins** [comment]
@liamcain - I've made the requested changes (sorta), because I tweaked how the system was actually managing the hiding/showing as a whole.

It's now using inline styles on the parent element of the `data-path` element, changing the `display` property. So it's basically the same but it just changes the general behaviour.

If there's any other changes needed let me know.

**Comment by liamcain** [comment]
Really nice job, works great!

Sorry for taking so long to get back to you on this.

**Comment by POTPER** [comment]
excellent！

**Pull request merged**
