### PR TITLE
Add plugin: Personal OS

### PR DESCRIPTION
**Pull request by GengAd**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/GengAd/obsidian-personal-os

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[name:"Start Work",](https://github.com/GengAd/obsidian-personal-os/blob/587a114a19be930c1a10ebeb84d3fa23dbae9fb6/main.ts#L31), [name:"Start Process",](https://github.com/GengAd/obsidian-personal-os/blob/587a114a19be930c1a10ebeb84d3fa23dbae9fb6/main.ts#L38), [name:"Set Focus",](https://github.com/GengAd/obsidian-personal-os/blob/587a114a19be930c1a10ebeb84d3fa23dbae9fb6/main.ts#L45), [name:"Reload Graph",](https://github.com/GengAd/obsidian-personal-os/blob/587a114a19be930c1a10ebeb84d3fa23dbae9fb6/main.ts#L52), [name:"Auto Fail Current File",](https://github.com/GengAd/obsidian-personal-os/blob/587a114a19be930c1a10ebeb84d3fa23dbae9fb6/main.ts#L59), [name:"Auto Fail Work in Progress Files",](https://github.com/GengAd/obsidian-personal-os/blob/587a114a19be930c1a10ebeb84d3fa23dbae9fb6/main.ts#L66), [name:"Snooze Tasks",](https://github.com/GengAd/obsidian-personal-os/blob/587a114a19be930c1a10ebeb84d3fa23dbae9fb6/main.ts#L73)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[const file = this.app.vault.getMarkdownFiles().find(f => f.path == task.path);](https://github.com/GengAd/obsidian-personal-os/blob/587a114a19be930c1a10ebeb84d3fa23dbae9fb6/src/Component/TaskFailer.ts#L18)
[Avoid iterating all files to find a file by its path]https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+iterating+all+files+to+find+a+file+by+its+path

[const button = containerEl.createEl('button', {text: 'Buy me a coffee ❤️'});](https://github.com/GengAd/obsidian-personal-os/blob/587a114a19be930c1a10ebeb84d3fa23dbae9fb6/src/Component/Settings/SettingsTab.ts#L52)
This should be att the end of the settings, not at the very top.

[containerEl.createEl('h1', {text: 'Folders'});](https://github.com/GengAd/obsidian-personal-os/blob/587a114a19be930c1a10ebeb84d3fa23dbae9fb6/src/Component/Settings/SettingsTab.ts#L53), [containerEl.createEl('h3', {text: 'Config Folder'});](https://github.com/GengAd/obsidian-personal-os/blob/587a114a19be930c1a10ebeb84d3fa23dbae9fb6/src/Component/Settings/SettingsTab.ts#L58), [div.createEl('h3', {text: name});](https://github.com/GengAd/obsidian-personal-os/blob/587a114a19be930c1a10ebeb84d3fa23dbae9fb6/src/Component/Settings/ListSetting.ts#L6)
For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```

**Comment by GengAd** [comment]
Hello @joethei 
Thanks for the review !
I have pushed the changes requested 😊

**Comment by GengAd** [comment]
Hello @joethei 
I don't know why, 3 days after the changes the bot didn't go through this PR to update the labels, the previous interractions were fast so I don't know if there is an issue about the bot or if it is normal ? Sorry I didn't see something in the [documentation](https://docs.obsidian.md/Plugins/Releasing/Submit+your+plugin) about the delays after making changes

**Comment by GengAd** [comment]
Thanks @joethei I just modified the manifest.json and the community-plugin.json !

**Comment by GengAd** [comment]
Hello @joethei 

I am commenting to avoid the "stale" label

Everything should be fixed :)

**Pull request merged**
