### PR TITLE
Add TaskPlanner Plugin

### PR DESCRIPTION
**Pull request by eoghano4321**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/eoghano4321/TaskPlanner

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/eoghano4321/TaskPlanner/blob/d695a43e36baaa10fa010b3d915774961eecaa82/src/main.ts#L24
Don't use this - it's a debugging variable that's set for convenience for debugging in the console, but not designed to be used for actual production code. Use the reference you get from `MyPlugin.app`.

https://github.com/eoghano4321/TaskPlanner/blob/d695a43e36baaa10fa010b3d915774961eecaa82/src/main.ts#L66
You should run this code in `Workspace.onLayoutReady`.

https://github.com/eoghano4321/TaskPlanner/blob/d695a43e36baaa10fa010b3d915774961eecaa82/src/main.ts#L79
From a UX perspective I feel like this isn't really necessary.

https://github.com/eoghano4321/TaskPlanner/blob/d695a43e36baaa10fa010b3d915774961eecaa82/src/main.ts#L106
Ok I highly recommend not doing this every 4 seconds. You should instead, watch for file change events and react to the ones that specify the file you're interested in.

Constantly reading file from disk (and perform potentially expensive parsing on them) leads to a resource hog where your plugin does a lot of wasted work (when the file hasn't changed) even if the app is completely idle and nothing is happening.


https://github.com/eoghano4321/TaskPlanner/blob/d695a43e36baaa10fa010b3d915774961eecaa82/src/Parser.ts#L33
You should look for the file using `Vault.getAbstractFileByPath` and then read it with `Vault.cachedRead` instead. By doing that, it would remove the need to re-read the file from disk if it's already cached in memory.

https://github.com/eoghano4321/TaskPlanner/blob/d695a43e36baaa10fa010b3d915774961eecaa82/src/Parser.ts#L137
Same as above.

https://github.com/eoghano4321/TaskPlanner/blob/d695a43e36baaa10fa010b3d915774961eecaa82/src/Parser.ts#L143
A lot of this doesn't require the `await` keyword here.

https://github.com/eoghano4321/TaskPlanner/blob/d695a43e36baaa10fa010b3d915774961eecaa82/src/CreateTaskNote.ts#L63
Here and many more - I see that you're using the `adapter` layer for simplicity - I would highly recommend using `Vault` instead of adapter for all your file creation/existence use because every `adapter` call translates to an underlying file system call, whereas `Vault` is a highly optimized, in-memory mirror of the state on disk, which means a lot of operations will not require an OS level disk read, leading to better performance and less resource usage.

**Comment by eoghano4321** [comment]
I think that I have fixed these issues in the code. I have created a new 0.1.3 release

**Comment by lishid** [comment]
https://github.com/eoghano4321/TaskPlanner/blob/52be1fed6ee8233d94c47fff28661781c3487791/src/main.ts#L67
Should still use onLayoutReady for this.

https://github.com/eoghano4321/TaskPlanner/blob/52be1fed6ee8233d94c47fff28661781c3487791/src/main.ts#L85
This isn't really necessary, plus it'll disappear like immediately because the timeout is in milliseconds.

https://github.com/eoghano4321/TaskPlanner/blob/52be1fed6ee8233d94c47fff28661781c3487791/src/main.ts#L112
This is probably even worse than doing it every 4 seconds - you'll basically run this code for every keystroke the user types.   You're looking for a debounce function, not setTimeout which just delays execution instead of combining multiple function calls into one.

Try using `import {debounce} from 'obsidian';`, the syntax is 
```js
update_tasks = debounce(() => this.parser.update_act_tasks(), 4000);
```

https://github.com/eoghano4321/TaskPlanner/blob/52be1fed6ee8233d94c47fff28661781c3487791/src/main.ts#L113
You also shouldn't be doing this kind of checks, and constructing the file name string twice.

I would suggest using the `Vault.on('change')` event instead, and check if the file in question matches the path you're looking for, then running the debounced function, instead of using `input` and `change`.

https://github.com/eoghano4321/TaskPlanner/blob/52be1fed6ee8233d94c47fff28661781c3487791/src/Parser.ts#L31
You really should make this string concatenation into some kind of helper function so you don't have to copy paste this everywhere in your code.

https://github.com/eoghano4321/TaskPlanner/blob/52be1fed6ee8233d94c47fff28661781c3487791/src/Parser.ts#L35
This is just totally unnecessary and bad for performance - you're asking the vault to generate a list of all files just to see if this variable is in that list. The vault literally just gave you the file from `getAbstractFileByPath`, which means if the file returned exists it must have been in the vault.

Here you should check instead if `task_file instanceof TFile` (the file is not null and is an instance of a file, and not a folder)

https://github.com/eoghano4321/TaskPlanner/blob/52be1fed6ee8233d94c47fff28661781c3487791/src/Parser.ts#L60
await not needed here.

https://github.com/eoghano4321/TaskPlanner/blob/52be1fed6ee8233d94c47fff28661781c3487791/src/CreateTaskNote.ts#L64
Same as above.

https://github.com/eoghano4321/TaskPlanner/blob/52be1fed6ee8233d94c47fff28661781c3487791/src/CreateTaskNote.ts#L66
Again, you keep re-constructing the file paths here. You can use `task_file.path` instead of reconstructing it. Remember that each time you construct the file path, you're creating a new Date object, converting it into a Moment object (which isn't necessary since you can just do `moment()` instead of `moment(new Date())`.

**Comment by lishid** [comment]
Closing this PR for now to keep things tidy, let me know if you still intend to add your plugin to the repo and we can re-open it!

**Pull request closed without merging**
