### PR TITLE
Added Sanguine theme

### PR DESCRIPTION
**Pull request by Satchelmouth**
#I am submitting a new community theme

## Repo URL
Link to my theme: https://github.com/Satchelmouth/Obsidian-Theme-Sanguine

## Theme checklist
 - [x] My repo contains all required files (please do not add them to this obsidian-releases repo).
 - [x] manifest.json
 - [x] theme.css
 - [x] The screenshot file (16:9 aspect ratio, recommended size is 512px by 288px for fast loading).
 - [x] I have indicated which modes (dark, light, or both) are compatible with my theme.
 - [x] I have added a license in the LICENSE file.
 - [x] My project respects and is compatible with the original license of any code from other themes that I'm using. I have given proper attribution to these other themes in my README.md.

* [Community Theme](?template=theme.md)

### CODE REVIEW

**Comment by joethei** [comment]
Please fill the PR template.

**Comment by Satchelmouth** [comment]
@joethei apologies that should all be fixed now. The link to create the PR template didn't populate for some reason

**Comment by joethei** [comment]
The style settings config seems to be taken directly from the minimal theme.
Please update it so it makes sense for your theme.

The theme screenshot is too big the recommended size is 512px by 288px.

**Comment by Satchelmouth** [comment]
@joethei both should be fixed now. Apologies I had the minimal css in there as a reference

**Comment by Satchelmouth** [comment]
@joethei thanks! Quick Q. My readme doesn't appear on the store page for some reason. Any idea why?

**Pull request merged**
