### PR TITLE
Add plugin: Enhance YouTube Links

### PR DESCRIPTION
**Pull request by Git-Sum**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Git-Sum/obsidian-enhance-youtube-links

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [X]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Did you write all the code in the `main.js` ?
If so, please use regular JavaScript and don't use compiled TypeScript as a base.

Otherwise, please upload the actual source file(s) to the repo.

**Comment by Git-Sum** [comment]
> Did you write all the code in the `main.js` ? If so, please use regular JavaScript and don't use compiled TypeScript as a base.
> 
> Otherwise, please upload the actual source file(s) to the repo.

I have uploaded additional files, please let me know if anymore are missing.

**Comment by liamcain** [comment]
- [YT](https://github.com/Git-Sum/obsidian-enhance-youtube-links/blob/89725d5619d822badbb2c2c69691f85de8b9ccf8/main.ts#L43) I suggest avoiding abbreviations here for clarity.
- [indentLevel](https://github.com/Git-Sum/obsidian-enhance-youtube-links/blob/89725d5619d822badbb2c2c69691f85de8b9ccf8/main.ts#L31) looks like the indent code is unused

**Comment by liamcain** [comment]
Added the plugin here: https://github.com/obsidianmd/obsidian-releases/commit/6a82a1eee158b4f86da6bd12bbbb1a1948dc6784

**Pull request closed without merging**
