### PR TITLE
Add Wallabag

### PR DESCRIPTION
**Pull request by huseyz**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/huseyz/obsidian-wallabag

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "Obsidian plugin for syncing Wallabag articles to Obsidian.",](https://github.com/huseyz/obsidian-wallabag/blob/df874c64c6d4393739b522b227c5b04cf0448837/manifest.json#L6)
We have  published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This is a plugin for Obsidian" in your description.

["fundingUrl": "",](https://github.com/huseyz/obsidian-wallabag/blob/df874c64c6d4393739b522b227c5b04cf0448837/manifest.json#L9)
If you don't have one omit this.

[const response = await request(requestOptions);](https://github.com/huseyz/obsidian-wallabag/blob/df874c64c6d4393739b522b227c5b04cf0448837/src/wallabag/WallabagAPI.ts#L65-L66)
You could also do this:
```ts
const response = await requestUrl(requestOptions);
const parsed = response.json();
```

[this.containerEl.createEl('h2', { text: 'General Settings' });](https://github.com/huseyz/obsidian-wallabag/blob/df874c64c6d4393739b522b227c5b04cf0448837/src/settings/WallabagSettingTab.ts#L27)
[Don't use a header for general settings ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)
[Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)


[id = 'wallabag-sync-articles';](https://github.com/huseyz/obsidian-wallabag/blob/df874c64c6d4393739b522b227c5b04cf0448837/src/command/SyncArticlesCommand.ts#L7)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

**Comment by huseyz** [comment]
@joethei Thanks for the comments!
I've addressed them in the new release https://github.com/huseyz/obsidian-wallabag/releases/tag/0.2.4

**Comment by huseyz** [comment]
Quick bug fix on https://github.com/huseyz/obsidian-wallabag/releases/tag/0.2.5

Updated the description in community-plugins.json file and solved the merge conflict.

**Comment by liamcain** [comment]
- [syncedFilePath](https://github.com/huseyz/obsidian-wallabag/blob/c263d26ba4213f6742af3fead8c2e48b50766ef5/src/command/SyncArticlesCommand.ts#L15) why not just save this to plugin settings instead? Storing it as a separate file means it won't sync with the vault.

**Pull request merged**
