### PR TITLE
Added my plugin "Table to CSV Exporter"

### PR DESCRIPTION
**Pull request by metawops**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/metawops/obsidian-table-to-csv-export

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by liamcain** [comment]
Looks good, just a couple small things I noticed!

---

https://github.com/metawops/obsidian-table-to-csv-export/blob/ab42dc6039778dbcba83dfea9d1dcc6df2381ff4/main.ts#L91 Why not just `return False` here? That way the command won't be available outside of reading mode.

https://github.com/metawops/obsidian-table-to-csv-export/blob/ab42dc6039778dbcba83dfea9d1dcc6df2381ff4/main.ts#L122 I think you are better off querying for `"table"` first. Then you can query for `tr`s within that table. That gives you a lot more flexibility if you want to export a single table or just export each table in the file.

**Comment by metawops** [comment]
> Looks good, just a couple small things I noticed!
> 
> https://github.com/metawops/obsidian-table-to-csv-export/blob/ab42dc6039778dbcba83dfea9d1dcc6df2381ff4/main.ts#L91 Why not just `return False` here? That way the command won't be available outside of reading mode.

Yes, I thought about that. However, if the user doesn't realise that a pane in edit mode is active and wants to invoke the command and doesn't find it he/she may be asking him/herself "why isn't this working?". The way I implemented it now let's the user find the command regardless and gives him/her a hint (via the Notice) that it only works on panes in reading mode.
It's a UX decision ... What arguments are pro your suggestion? I'm happy to change it if you have good arguments. 😉 

> 
> https://github.com/metawops/obsidian-table-to-csv-export/blob/ab42dc6039778dbcba83dfea9d1dcc6df2381ff4/main.ts#L122 I think you are better off querying for `"table"` first. Then you can query for `tr`s within that table. That gives you a lot more flexibility if you want to export a single table or just export each table in the file.

Yes, true, it's on my list for the next release to handle multiple tables in a single note better. 
I wanted to release a MVP first (and fast) and then deliver updates frequently.
Or would this be a showstopper?

Thanks for the suggestions!! 👍

**Comment by liamcain** [comment]
> The way I implemented it now let's the user find the command regardless and gives him/her a hint (via the Notice) that it only works on panes in reading mode.
It's a UX decision ... What arguments are pro your suggestion? I'm happy to change it if you have good arguments

I think that's reasonable. Especially if the user has a hotkey for exporting, then your notice gives them immediate feedback. My argument for why to filter it would just be to keep the command palette "clean"–the only items in the list should be applicable to the current situation.

> Yes, true, it's on my list for the next release to handle multiple tables in a single note better.
I wanted to release a MVP first (and fast) and then deliver updates frequently.
Or would this be a showstopper?

I'll leave that up to you. I would probably have the MVP functionality be to only export the first table, that way adding support for multi-tables down the road feels more like a feature/improvement vs a bug fix.

**Comment by metawops** [comment]
> > The way I implemented it now let's the user find the command regardless and gives him/her a hint (via the Notice) that it only works on panes in reading mode.
> > It's a UX decision ... What arguments are pro your suggestion? I'm happy to change it if you have good arguments
> 
> I think that's reasonable. Especially if the user has a hotkey for exporting, then your notice gives them immediate feedback. My argument for why to filter it would just be to keep the command palette "clean"–the only items in the list should be applicable to the current situation.

I see, that's a pretty good argument, too. But I think I'll stick with the current way it's implemented. But I put that on my list to check again if your proposed way makes more sense. Maybe there will be some user feedback on that, too.

> 
> > Yes, true, it's on my list for the next release to handle multiple tables in a single note better.
> > I wanted to release a MVP first (and fast) and then deliver updates frequently.
> > Or would this be a showstopper?
> 
> I'll leave that up to you. I would probably have the MVP functionality be to only export the first table, that way adding support for multi-tables down the road feels more like a feature/improvement vs a bug fix.

That's a good suggestion. I'll work on it. How/where would I submit a fixed version? I'm far away from being a GitHub expert. 🙈

**Comment by liamcain** [comment]
> That's a good suggestion. I'll work on it. How/where would I submit a fixed version? I'm far away from being a GitHub expert.

You can just push the changes to your repo then cut a new Github Release ([instructions for creating a new release](https://github.com/obsidianmd/obsidian-sample-plugin#releasing-new-releases)). Then just comment here in this pull request when you want me to take another look.

**Comment by metawops** [comment]
Hi Liam,
I just created release 0.1.1 with the change we spoke about (just the first table gets exported now, if any).
[Here's a direct link to this 0.1.1 release](https://github.com/metawops/obsidian-table-to-csv-export/releases/tag/0.1.1).
Thanks,
Stefan.

**Comment by metawops** [comment]
Anything else I need to do now? Or is it your turn now, @liamcain? I'm not sure ...

**Comment by metawops** [comment]
Hi @liamcain,
I made a new release, [0.1.3](https://github.com/metawops/obsidian-table-to-csv-export/releases/tag/0.1.3).

**Comment by metawops** [comment]
And here's already the next release, [0.1.4](https://github.com/metawops/obsidian-table-to-csv-export/releases/tag/0.1.4)

Please let me know, @liamcain, if I have an open task here in the review process. 😳 
Thanks! 🙏

**Comment by liamcain** [comment]
Hi @metawops, sorry for the delay! It's been a busy couple weeks behind the scenes so I fell behind on plugin reviews.

Everything looks good to me, but it there's a small issue: your manifest file points to version 0.1.5 but the latest release is 0.1.4. If those versions don't match, Obsidian will fail to install the plugin.

Please ping me when it's fixed so that I can merge this. Thanks!

**Comment by metawops** [comment]
Oh my! How embarrassing! 🙈 My fault, sorry, I was already thinking about a next release and accidentally pushed that `manifest.json` file to the master branch here. 😞 
I corrected this now and am happily looking forward to being included in the official community plugins list. 😊 
Thanks so much for your work/help/effort, @liamcain!! 👍

**Comment by metawops** [comment]
Thanks again, @liamcain! I'm proud to see my first plugin in the official list of all the >600 community plugins! 😊 
Last question: Now that it's official and can be installed via Obsidian I want to remove the part of the `README.md` file that gives installation instructions. – Do I have to create a new release afterwards to make the new readme visible in Obsidian? Or does Obsidian display the `README.md` file directly from the latest branch of my repository?

**Comment by liamcain** [comment]
No need to create a new release for readme changes, only when your generated output changes (so either the manifest.json file or the main.js file)

**Comment by metawops** [comment]
Cool, thanks!! 😊

**Pull request merged**
