### PR TITLE
Add plugin SenGener

### PR DESCRIPTION
**Pull request by zazaji**
# I am submitting a new Community Plugin : obsidian-SenGener

## Repo URL

Link to my plugin: https://github.com/zazaji/obsidian-SenGener

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by zazaji** [comment]
I had updated `community-plugins.json`,put my repo to the end of the list.

**Comment by liamcain** [comment]
Hi @zazaji, it looks like you are modifying the transpiled output of a typescript file. This file is meant to be machine readable, and not really meant to be human readable. I suggest you move your changes over to a clean template file. That can be either a typescript file or a clean javascript file. If the issue is that the sample plugin is typescript only, there are plenty of javascript plugins that you can base your plugin off of. Also, just so you know, even if you're not comfortable with Typescript, you can still use a typescript file and just add javascript to it. It will still work fine.

**Comment by joethei** [comment]
Hi @zazaji,
I just wanted to confirm that you've seen Liams comment with the requested changes.
Do you still intend on submitting this plugin?

**Comment by ericaxu** [comment]
Hi there, to keep things tidy, we're going to temporarily close plugin PRs after a month of inactivity.

Feel free to tell us to re-open it when you're ready to continue. Thanks for your understanding!

**Pull request closed without merging**
