### PR TITLE
Add plugin: Copy Previous Day Note

### PR DESCRIPTION
**Pull request by feiteira**
# I am submitting a new Community Plugin
## Repo URL
Link to my plugin: https://github.com/feiteira/obsidian-copy-previous-day-note

## Release Checklist
* [ ]  I have tested the plugin on
  * [x]   Windows
  * [ ]   macOS
  * [ ]   Linux
  * [ ]   Android _(if applicable)_
  * [ ]   iOS _(if applicable)_
* [x]  My GitHub release contains all required files 
   * [x]  `main.js`
   * [x]  `manifest.json`
   * [ ]  `styles.css` _(optional)_
* [x]  GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
* [x]  The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
* [x]  My README.md describes the plugin's purpose and provides clear usage instructions.
* [x]  I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
* [x]  I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
* [x]  I have added a license in the LICENSE file.
* [x]  My project respects and is compatible with the original license of any code from other plugins that I'm using.
   I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by feiteira** [comment]
I don't get this, any idea what could have caused this error?

**Comment by joethei** [comment]
should be fixed, can you please create a new PR and follow the pull request template this time?

**Comment by feiteira** [comment]
Updated pull request message

**Comment by feiteira** [comment]
I don't get it, the files are there. Why is this complaining?

**Comment by joethei** [comment]
The files are not in the release.

**Comment by joethei** [comment]
Remove the `data.json` file from your repo and add it to the `.gitignore` file.

There is no documentation about the reliance on the Daily notes core plugin, and no error message that is shown to the user if the daily notes plugin is not enabled.
Please add that.


[this.settings = Object.assign({}, { maxDays: 7 });](https://github.com/feiteira/obsidian-copy-previous-day-note/blob/3257ebd9af1b901e48f1c088648fb7fb5ddd00d4/main.js#L8)
Remove this code, the settings object will be overwritten in the `loadSettings` call, so this call is pointless.

[overrideDailyNoteCommand(dailyNotesPlugin) {](https://github.com/feiteira/obsidian-copy-previous-day-note/blob/3257ebd9af1b901e48f1c088648fb7fb5ddd00d4/main.js#L29-L107), [](https://github.com/feiteira/obsidian-copy-previous-day-note/blob/3257ebd9af1b901e48f1c088648fb7fb5ddd00d4/main.js#L120-L133)
Please don't redefine Core commands, add your own.

[console.log('Original daily note command found', originalCommand);](https://github.com/feiteira/obsidian-copy-previous-day-note/blob/3257ebd9af1b901e48f1c088648fb7fb5ddd00d4/main.js#L38), [console.log('Overridden daily note command executed');](https://github.com/feiteira/obsidian-copy-previous-day-note/blob/3257ebd9af1b901e48f1c088648fb7fb5ddd00d4/main.js#L42), [console.log(`Old file content read successfully from ${oldFilePath}`);](https://github.com/feiteira/obsidian-copy-previous-day-note/blob/3257ebd9af1b901e48f1c088648fb7fb5ddd00d4/main.js#L79), [console.log(`No previous note found within ${this.settings.maxDays} days. Creating an empty note.`);](https://github.com/feiteira/obsidian-copy-previous-day-note/blob/3257ebd9af1b901e48f1c088648fb7fb5ddd00d4/main.js#L86), [console.log('Filtered content:', filteredContent);](https://github.com/feiteira/obsidian-copy-previous-day-note/blob/3257ebd9af1b901e48f1c088648fb7fb5ddd00d4/main.js#L90), [console.log('New daily note created successfully with filtered content');](https://github.com/feiteira/obsidian-copy-previous-day-note/blob/3257ebd9af1b901e48f1c088648fb7fb5ddd00d4/main.js#L92), [console.log('Daily note command overridden successfully');](https://github.com/feiteira/obsidian-copy-previous-day-note/blob/3257ebd9af1b901e48f1c088648fb7fb5ddd00d4/main.js#L100), [console.log(`Created directory: ${dirPath}`);](https://github.com/feiteira/obsidian-copy-previous-day-note/blob/3257ebd9af1b901e48f1c088648fb7fb5ddd00d4/main.js#L117), [console.log('Daily note button re-bound to new callback');](https://github.com/feiteira/obsidian-copy-previous-day-note/blob/3257ebd9af1b901e48f1c088648fb7fb5ddd00d4/main.js#L129), [console.log(line,"skip =",skip," level = ",level)](https://github.com/feiteira/obsidian-copy-previous-day-note/blob/3257ebd9af1b901e48f1c088648fb7fb5ddd00d4/main.js#L146), [console.log('Skipping completed task:', line);](https://github.com/feiteira/obsidian-copy-previous-day-note/blob/3257ebd9af1b901e48f1c088648fb7fb5ddd00d4/main.js#L152), [console.log('Skipping nested task:', line);](https://github.com/feiteira/obsidian-copy-previous-day-note/blob/3257ebd9af1b901e48f1c088648fb7fb5ddd00d4/main.js#L157)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.


[containerEl.createEl('h2', { text: 'Settings for Copy Previous Day Note' });](https://github.com/feiteira/obsidian-copy-previous-day-note/blob/3257ebd9af1b901e48f1c088648fb7fb5ddd00d4/main.js#L194)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[.setName('Maximum Days to Look Back')](https://github.com/feiteira/obsidian-copy-previous-day-note/blob/3257ebd9af1b901e48f1c088648fb7fb5ddd00d4/main.js#L197)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Pull request closed without merging**
