### PR TITLE
New plugin - Document Editing Shortcuts

### PR DESCRIPTION
**Pull request by grizzly-sh**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/happy-grizzly/obsidian-document-editing-shortcuts

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by happy-grizzly** [comment]
K I fixed that

**Comment by joethei** [comment]
CodeMirror(the underlying editor engine) already provides some of these shortcuts: <https://codemirror.net/docs/ref/#commands>, they cannot be changed, and as such are not visible from the hotkey menu/command pallete.

[// Remember to rename these classes and interfaces!](https://github.com/happy-grizzly/obsidian-document-editing-shortcuts/blob/c81227ab38263556e8e22d0bc145b06f03b6fbc6/main.ts#L3)
Please actually do this, to avoid conflicts.

[repeatUntilKeyUp(code, this)](https://github.com/happy-grizzly/obsidian-document-editing-shortcuts/blob/c81227ab38263556e8e22d0bc145b06f03b6fbc6/main.ts#L28)
Instead of this you can set the [`repeatable`](https://github.com/obsidianmd/obsidian-api/blob/ff121cd409350d3afe39b08420f468d8aaee925e/obsidian.d.ts#L514) property of the command.

[// If the plugin hooks up any global DOM events (on parts of the app that doesn't belong to this plugin)](https://github.com/happy-grizzly/obsidian-document-editing-shortcuts/blob/c81227ab38263556e8e22d0bc145b06f03b6fbc6/main.ts#L368-L375)
You are not using any of this, you can just remove it.

[function isNormalChar(char: string): number](https://github.com/happy-grizzly/obsidian-document-editing-shortcuts/blob/c81227ab38263556e8e22d0bc145b06f03b6fbc6/main.ts#L393)
Any particular reason you return a number here and not a boolean?

**Comment by ericaxu** [comment]
@grizzly-sh Hi! Do you still intend to submit this plugin? Thanks!

**Comment by grizzly-sh** [comment]
Hi, I already tried to submit it.
I'll respond to joethei:

1. CodeMirror API is out of my control to edit, extension building wise and technical knowledge wise. Therefore the only way I saw to solve this problem is with some "hacky" javascript, the other way one can do it is to configure Vim shortcuts and use the insert mode only...not great, but works.
2. I'll rename them...sure.
3. The repeatable method does not give control over milliseconds for repeatability.
4. Sure I'll remove it you're right.
5. If you take a look where and how this method is implemented, you'll see I configured "modes" for character groups, I preferred to use numbers instead of booleans because I wasn't sure how many types of grouped characters the normal computer kernel differentiates for navigation. As an example press options/control right and left arrow to this word: dkfjgdjfgkh,,,?-?(
Notice how it stops after the normal letters and before the alternative ones. that's what I mean by character types. I replicated this with Javascript.

I'll make the rest of the small changes in the next few days. I need to test that it works on all the OSs before pushing it.

**Comment by grizzly-sh** [comment]
Sorry I just can't find the time to do this.

Hard to find time to solve problems I don't have.
Might keep maintaining the project at a later date,having this itch is welcome to fork and take over.

Closing

**Pull request closed without merging**
