### PR TITLE
Add plugin: Notes Refresher

### PR DESCRIPTION
**Pull request by connorpark24**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/connorpark24/refresher-plugin

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["minAppVersion": "0.0.0",](https://github.com/connorpark24/refresher-plugin/blob/45872fb4aa129be634c0cffa54d120fb8b20483a/manifest.json#L5)
That is way to low, 

[this.addRibbonIcon("clock-4", "Refresh", async () => {](https://github.com/connorpark24/refresher-plugin/blob/45872fb4aa129be634c0cffa54d120fb8b20483a/main.ts#L25)
Refresh what?

[const traverseFolder = (folder: any) => {](https://github.com/connorpark24/refresher-plugin/blob/45872fb4aa129be634c0cffa54d120fb8b20483a/main.ts#L44)
This should not be using `any`


[containerEl.createEl("h2", { text: "Settings for my plugin." });](https://github.com/connorpark24/refresher-plugin/blob/45872fb4aa129be634c0cffa54d120fb8b20483a/main.ts#L136-L137)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)


[.setName("Folder Path")](https://github.com/connorpark24/refresher-plugin/blob/45872fb4aa129be634c0cffa54d120fb8b20483a/main.ts#L139), [.setName("OpenAI API Key")](https://github.com/connorpark24/refresher-plugin/blob/45872fb4aa129be634c0cffa54d120fb8b20483a/main.ts#L152), [contentEl.createEl("h2", { text: "Daily Refresher" });](https://github.com/connorpark24/refresher-plugin/blob/45872fb4aa129be634c0cffa54d120fb8b20483a/RefresherModal.ts#L27)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by connorpark24** [comment]
Thank you for the feedback, I have made the requested changes.

**Comment by joethei** [comment]
[this.addRibbonIcon("clock-4", "Get Note Summaries"](https://github.com/connorpark24/refresher-plugin/blob/5996a28eb3962d1dca40696f06554bff7beacd13/main.ts#L32)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

["minAppVersion": "0.15.0",](https://github.com/connorpark24/refresher-plugin/blob/5996a28eb3962d1dca40696f06554bff7beacd13/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

**Comment by connorpark24** [comment]
I have made the requested changes.

**Pull request merged**
