### PR TITLE
Add plugin: Mxmind Mindmap

### PR DESCRIPTION
**Pull request by webceoboy**
# I am submitting a new Community Plugin

## Repo URL  

Link to my plugin:https://github.com/webceoboy/mxmind-obsidian

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["fundingUrl": "https://mxmind.com/page/pricing",](https://github.com/webceoboy/mxmind-obsidian/blob/05e8cce56779fe45a9495bc09d1e686fb1759180/manifest.json#L9)
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link omit this.
It also leads to a 404.

[const texts = await Promise.all(vault.getMarkdownFiles().filter(f => f == file).map((file) => vault.cachedRead(file)))](https://github.com/webceoboy/mxmind-obsidian/blob/05e8cce56779fe45a9495bc09d1e686fb1759180/main.ts#L99)
This is totally unecessary, you can just do `vault.cachedFile(file)` without any of the filtering and mapping.

**Comment by webceoboy** [comment]
/

> ["fundingUrl": "https://mxmind.com/page/pricing",](https://github.com/webceoboy/mxmind-obsidian/blob/05e8cce56779fe45a9495bc09d1e686fb1759180/manifest.json#L9) This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link omit this. It also leads to a 404.
> 
> [const texts = await Promise.all(vault.getMarkdownFiles().filter(f => f == file).map((file) => vault.cachedRead(file)))](https://github.com/webceoboy/mxmind-obsidian/blob/05e8cce56779fe45a9495bc09d1e686fb1759180/main.ts#L99) This is totally unecessary, you can just do `vault.cachedFile(file)` without any of the filtering and mapping.

I have removed fundingUrl and unecessary code.
@see https://github.com/webceoboy/mxmind-obsidian/commit/15d6a49c803304f49387bfeee047f994edf87ff9

**Comment by webceoboy** [comment]
/

> ["fundingUrl": "https://mxmind.com/page/pricing",](https://github.com/webceoboy/mxmind-obsidian/blob/05e8cce56779fe45a9495bc09d1e686fb1759180/manifest.json#L9) This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link omit this. It also leads to a 404.
> 
> [const texts = await Promise.all(vault.getMarkdownFiles().filter(f => f == file).map((file) => vault.cachedRead(file)))](https://github.com/webceoboy/mxmind-obsidian/blob/05e8cce56779fe45a9495bc09d1e686fb1759180/main.ts#L99) This is totally unecessary, you can just do `vault.cachedFile(file)` without any of the filtering and mapping.

I have removed fundingUrl and unecessary code.
@see https://github.com/webceoboy/mxmind-obsidian/commit/15d6a49c803304f49387bfeee047f994edf87ff9

**Comment by joethei** [comment]
["description": "Mind map for obsidian,mindmap tool.",](https://github.com/webceoboy/mxmind-obsidian/blob/15d6a49c803304f49387bfeee047f994edf87ff9/manifest.json#L6)
Avoid including "for Obsidian" in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[const file=this.app.workspace.getActiveFile() as TFile;](https://github.com/webceoboy/mxmind-obsidian/blob/15d6a49c803304f49387bfeee047f994edf87ff9/main.ts#L99)
This can return null, add some validation.

**Comment by webceoboy** [comment]
> ["description": "Mind map for obsidian,mindmap tool.",](https://github.com/webceoboy/mxmind-obsidian/blob/15d6a49c803304f49387bfeee047f994edf87ff9/manifest.json#L6) Avoid including "for Obsidian" in your description, it should be self-evident that this is a plugin for Obsidian. We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
> 
> [const file=this.app.workspace.getActiveFile() as TFile;](https://github.com/webceoboy/mxmind-obsidian/blob/15d6a49c803304f49387bfeee047f994edf87ff9/main.ts#L99) This can return null, add some validation.

I have change some code
@see https://github.com/webceoboy/mxmind-obsidian/commit/77859bf6fcd3c9a73ed956580fee2491e88a64a0

**Comment by joethei** [comment]
["description": "Mind map,markdown to minding map,minding map tool.",](https://github.com/webceoboy/mxmind-obsidian/blob/77859bf6fcd3c9a73ed956580fee2491e88a64a0/manifest.json#L6)
This is still a bad description, with multiple typos, please read this: <https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple>

**Pull request merged**
