### PR TITLE
Add plugin: FastForwardLink

### PR DESCRIPTION
**Pull request by IdanLib**
with FastForwardLink plugin

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist
- [X] I have tested the plugin on
  - [X]  Windows
  - [ ]  macOS
  - [X]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [X] `main.js`
  - [X] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [X] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[name: "Paste Redirect Syntax onto Selection",](https://github.com/IdanLib/ObsidianFastForwardLinkPlugin/blob/98e43c300218dc647cf8117aca5ffa5ea89a8de1/main.ts#L172), [.setName("Delete the _forwards Folder")](https://github.com/IdanLib/ObsidianFastForwardLinkPlugin/blob/98e43c300218dc647cf8117aca5ffa5ea89a8de1/components/Settings.ts#L44)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by IdanLib** [comment]
@joethei Thank you for the review and commen! I have pushed the correction to my repo, and the automated check passes.

However, Github shows an error message that the branch cannot be rebased due to conflicts. This is despite the fact that I've just manually resolved a conflict. 

How should I proceed? Should I close this PR and open another? 

Thank you!

**Comment by IdanLib** [comment]
No problem, I'll await the review. Thank you!

**Comment by IdanLib** [comment]
Thank you!

**Pull request merged**
