### PR TITLE
Add plugin: Wechat Public Platform

### PR DESCRIPTION
**Pull request by ai-chen2050**
new plugin

# I am submitting a new Community Plugin
Obsidian Wechat public Plugin  is a plugin to release article from your Obsidian Vault.

## Repo URL

Link to my plugin:  https://github.com/ai-chen2050/obsidian-wechat-public-platform

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by ai-chen2050** [comment]
update

**Comment by ai-chen2050** [comment]
Halo， Is there anybody here, @muness @czottmann

**Comment by joethei** [comment]
You have not addressed all the things the bot has flagged.

**Comment by ai-chen2050** [comment]
/skip [[1](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/30cbb4556328816dd25638454393578537989862/src/showModals.ts#L235)][[2](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/30cbb4556328816dd25638454393578537989862/src/showModals.ts#L285)] just for show info, no risk

**Comment by joethei** [comment]
They contain user input, that is extremely risky.

**Comment by ai-chen2050** [comment]
have some suggestions? @joethei , bro. I just learning from other plugins.

**Comment by ai-chen2050** [comment]
I create new elements using document.createElement and set their text content using textContent. Instead of directly using innerHTML.

**Comment by joethei** [comment]
Wait, the bot runs on a timer

**Comment by ai-chen2050** [comment]
hello, bro. Its seem that bot isn't scam after four hours @joethei , what's going on?

**Comment by joethei** [comment]
[Copyright (c) 2021 jsonmartin](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/LICENSE#L3)
Fill this with the correct information.

["description": "Obsidian Wechat public Plugin is a plugin to release article from your Obsidian Vault.",](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/manifest.json#L6)
Avoid including sentences like "This is a plugin for Obsidian that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[interface WeChatPublicSettings {](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/main.ts#L10-L16)
Remove this code.

[id: 'send-all-fans-by-wechatpublic-plugin',](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/main.ts#L52), [id: 'release-article-by-wechatpublic-plugin',](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/main.ts#L66), [id: 'add-draft-by-wechatpublic-plugin',](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/main.ts#L80), [id: 'upload-material-by-wechatpublic-plugin',](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/main.ts#L106), [id: 'download-material-from-wechatpublic',](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/main.ts#L121)
Remove the `-by-wechatpublic-plugin` suffix, Obsidian will make sure that there are no conflicts with other plugins.

[name: 'Send to all fans by WeChatPublic plugin【 normal account one shot a day 】',](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/main.ts#L53), [name: 'Release article by WeChatPublic plugin',](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/main.ts#L67), [name: 'add draft by WeChatPublic plugin',](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/main.ts#L81), [name: 'upload material by WeChatPublic plugin.',](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/main.ts#L107)
Remove the `by WeChatPublic plugin´ text, it's unnecessary duplication, items in the command pallete will already be prefixed by the plugin name.

[name: 'Send to all fans by WeChatPublic plugin【 normal account one shot a day 】',](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/main.ts#L53)
I also think that the word "fans" is incorrect here, 

[async loadFrontMatter(file: TFile): Promise<FrontMatter> {](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/utils/frontmatter.ts#L13-L22)
Use `<appInstance>.metadataCache.getFileCache(file).frontmatter` instead of this function.


[async storeFrontMatter(file: TFile, fm: FrontMatter) {](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/utils/frontmatter.ts#L30-L48)
use the `processFrontMatter` function instead: <https://github.com/obsidianmd/obsidian-api/blob/master/CHANGELOG.md#new-metadata-api>

[// 读取值](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/utils/frontmatter.ts#L49-L64)
Remove these two functions and use the API's recommended above instead.

[import * as crypto from "crypto";](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/utils/cookiesUtil.ts#L2), [import fs from "fs";](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/src/api.ts#L15), [const { remote } = require('electron');](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/src/LoginModas.ts#L12), [const { remote } = require('electron');](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/src/LoginModas.ts#L89)
This import is available from a Node.js runtime, which means that this will throw errors on Mobile (that's a problem since you have `isDesktopOnly` marked as `false` in your manifest.json file.

[contentEl.createEl("h1", { text: "Input Youtube Video Source" });](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/src/showModals.ts#L130), [.setDesc("video-url: 视频链接")](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/src/showModals.ts#L134)
You should be consistent with the language used, some text is in english and some is in Chinese.

[contentEl.createEl("h1", { text: "Input Youtube Video Source" });](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/src/showModals.ts#L130), [contentEl.createEl("h1", { text: "Input Download Details" });](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/src/showModals.ts#L74), [.setName('NoteLocationFolder')](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/src/settingTab.ts#L189), [.setName('DownloadFolder')](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/src/settingTab.ts#L202), [.setName('YoutubeSaveFolder')](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/src/settingTab.ts#L224), and more
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[containerEl.createEl('h2', { text: '🌈 Wechat Public Platform Settings'});](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/src/settingTab.ts#L25)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[containerEl.createEl('h2', { text: '🌎 🌞 Baidu Bjh Platform Settings 🔍'});](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/src/settingTab.ts#L38), [containerEl.createEl('h2', { text: '👉 📺 Youtube Downloader Settings'});](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/src/settingTab.ts#L45)
[Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

[background: url(https://s2.loli.net/2022/01/11/XyHnMBGWCl5Z9DK.png);](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/src/style/codeStyle.ts#L107), [img3.src = 'https://github.com/ai-chen2050/obsidian-wechat-public-platform/raw/master/public/commutity.jpg';](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/src/settingTab.ts#L368), [img4.src = 'https://github.com/ai-chen2050/obsidian-wechat-public-platform/raw/master/public/wechat-motion-qr.png';](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/src/settingTab.ts#L378)
As part of our developer policies, it is not allowed to load remote resources for styling purposes, you need to encode these with base64, if you want them to be included.

[img3.src = 'https://github.com/ai-chen2050/obsidian-wechat-public-platform/raw/master/public/commutity.jpg';](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/src/settingTab.ts#L368)
Also, there should be no animations like this inside of the settings tab.

The download feature for youtube videos makes no sense in this plugin and should be removed.

**Comment by ai-chen2050** [comment]
@joethei thinks you, bro. I have almost updated all of your suggestions.  I need the feature about youtube videos, which may be needed for others.  so I want to keep this feature and leave. I hope you could understand.  Thx again.

Have a good day!

**Comment by ai-chen2050** [comment]
> @joethei thinks you, bro. I have almost updated all of your suggestions. I need the feature about youtube videos, which may be needed for others. so I want to keep this feature and leave. I hope you could understand. Thx again.
> 
> Have a good day! 😄

**Comment by ai-chen2050** [comment]
@joethei Halo, bro. I have addressed all suggestions.

**Comment by joethei** [comment]
[containerEl.createEl('h2', { text: '🌈 Wechat Public Platform Zone'});](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/d8b0a1a515dfda91f37c491f9572644097649a88/src/settingTab.ts#L25), [containerEl.createEl('h2', { text: '🌎 🌞 Baidu Bjh Platform Zone 🔍'});](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/d8b0a1a515dfda91f37c491f9572644097649a88/src/settingTab.ts#L38), [containerEl.createEl('h2', { text: '👉 📺 Youtube Downloader Zone'});](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/d8b0a1a515dfda91f37c491f9572644097649a88/src/settingTab.ts#L45), [.setButtonText('Copy Cookie')](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/d8b0a1a515dfda91f37c491f9572644097649a88/src/settingTab.ts#L146), [containerEl.createEl('h2', { text: '💰 Support 支持 & Funding 赞助 💰'});](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/d8b0a1a515dfda91f37c491f9572644097649a88/src/settingTab.ts#L292)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI) and for section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```


[.setName('NoteLocationFolder')](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/d8b0a1a515dfda91f37c491f9572644097649a88/src/settingTab.ts#L189), [.setName('DownloadFolder')](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/d8b0a1a515dfda91f37c491f9572644097649a88/src/settingTab.ts#L202), [.setName('YoutubeSaveFolder')](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/d8b0a1a515dfda91f37c491f9572644097649a88/src/settingTab.ts#L224)
Use sentence case as above, and add some spaces.

[.setName('Blacklist')](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/d8b0a1a515dfda91f37c491f9572644097649a88/src/settingTab.ts#L245-L246)
Stick to one language, the name is english while the description is chinese.

**Comment by ai-chen2050** [comment]
> [containerEl.createEl('h2', { text: '🌈 Wechat Public Platform Zone'});](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/d8b0a1a515dfda91f37c491f9572644097649a88/src/settingTab.ts#L25), [containerEl.createEl('h2', { text: '🌎 🌞 Baidu Bjh Platform Zone 🔍'});](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/d8b0a1a515dfda91f37c491f9572644097649a88/src/settingTab.ts#L38), [containerEl.createEl('h2', { text: '👉 📺 Youtube Downloader Zone'});](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/d8b0a1a515dfda91f37c491f9572644097649a88/src/settingTab.ts#L45), [.setButtonText('Copy Cookie')](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/d8b0a1a515dfda91f37c491f9572644097649a88/src/settingTab.ts#L146), [containerEl.createEl('h2', { text: '💰 Support 支持 & Funding 赞助 💰'});](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/d8b0a1a515dfda91f37c491f9572644097649a88/src/settingTab.ts#L292) [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI) and for section headings in settings use:
> 
> ```ts
> new Setting(containerEl).setName('name here').setHeading();
> ```
> 
> [.setName('NoteLocationFolder')](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/d8b0a1a515dfda91f37c491f9572644097649a88/src/settingTab.ts#L189), [.setName('DownloadFolder')](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/d8b0a1a515dfda91f37c491f9572644097649a88/src/settingTab.ts#L202), [.setName('YoutubeSaveFolder')](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/d8b0a1a515dfda91f37c491f9572644097649a88/src/settingTab.ts#L224) Use sentence case as above, and add some spaces.
> 
> [.setName('Blacklist')](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/d8b0a1a515dfda91f37c491f9572644097649a88/src/settingTab.ts#L245-L246) Stick to one language, the name is english while the description is chinese.

Fixed again, bro. Have a good day.

**Comment by ai-chen2050** [comment]
> > [containerEl.createEl('h2', { text: '🌈 Wechat Public Platform Zone'});](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/d8b0a1a515dfda91f37c491f9572644097649a88/src/settingTab.ts#L25), [containerEl.createEl('h2', { text: '🌎 🌞 Baidu Bjh Platform Zone 🔍'});](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/d8b0a1a515dfda91f37c491f9572644097649a88/src/settingTab.ts#L38), [containerEl.createEl('h2', { text: '👉 📺 Youtube Downloader Zone'});](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/d8b0a1a515dfda91f37c491f9572644097649a88/src/settingTab.ts#L45), [.setButtonText('Copy Cookie')](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/d8b0a1a515dfda91f37c491f9572644097649a88/src/settingTab.ts#L146), [containerEl.createEl('h2', { text: '💰 Support 支持 & Funding 赞助 💰'});](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/d8b0a1a515dfda91f37c491f9572644097649a88/src/settingTab.ts#L292) [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI) and for section headings in settings use:
> > ```ts
> > new Setting(containerEl).setName('name here').setHeading();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [.setName('NoteLocationFolder')](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/d8b0a1a515dfda91f37c491f9572644097649a88/src/settingTab.ts#L189), [.setName('DownloadFolder')](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/d8b0a1a515dfda91f37c491f9572644097649a88/src/settingTab.ts#L202), [.setName('YoutubeSaveFolder')](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/d8b0a1a515dfda91f37c491f9572644097649a88/src/settingTab.ts#L224) Use sentence case as above, and add some spaces.
> > [.setName('Blacklist')](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/d8b0a1a515dfda91f37c491f9572644097649a88/src/settingTab.ts#L245-L246) Stick to one language, the name is english while the description is chinese.
> 
> Fixed again, bro. Have a good day.

Halo, bro @joethei  👀 👀

**Comment by joethei** [comment]
Stop calling me bro.

And you haven't implemented all the things that have been requested.

**Comment by ai-chen2050** [comment]
> Stop calling me bro.
> 
> And you haven't implemented all the things that have been requested.

Sorry to take up your time, bro.  Actually, I have addressed your issue place. 

Please watch the new commit of the master branch.  Example,  section headings in [settings use this way](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20b7c03de5c0c9b34cf674b9f4f4b030959f1e0e/src/settingTab.ts#L25).    And [Sentence case like this](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20b7c03de5c0c9b34cf674b9f4f4b030959f1e0e/src/settingTab.ts#L189),  and this [one language](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20b7c03de5c0c9b34cf674b9f4f4b030959f1e0e/src/settingTab.ts#L246).

I may have misled you by not updating the code reference link in time.  I used your issued code ref link,  I apologize again.

**Comment by joethei** [comment]
You missed this one:

[background: url(https://s2.loli.net/2022/01/11/XyHnMBGWCl5Z9DK.png);](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/src/style/codeStyle.ts#L107), [img3.src = 'https://github.com/ai-chen2050/obsidian-wechat-public-platform/raw/master/public/commutity.jpg';](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/src/settingTab.ts#L368), [img4.src = 'https://github.com/ai-chen2050/obsidian-wechat-public-platform/raw/master/public/wechat-motion-qr.png';](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/20fdbfe99fd1e2d9f67cff7b473207107a4e397d/src/settingTab.ts#L378)
As part of our developer policies, it is not allowed to load remote resources for styling purposes, you need to encode these with base64, if you want them to be included.

**Comment by ai-chen2050** [comment]
Thanks for pointing out，please see new commit code here, 
- [img3.src = motivation;](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/1eb3112ac73adca3933d10b40fd0ef693a1ad4dc/src/settingTab.ts#L368C3-L368C25), and motivation havd been handle by base64 encode, please see [here](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/1eb3112ac73adca3933d10b40fd0ef693a1ad4dc/src/consts/global.ts#L35)
- and [img4.src = commutity;](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/1eb3112ac73adca3933d10b40fd0ef693a1ad4dc/src/settingTab.ts#L378C3-L378C24), is the same.
- Actually, the above two issues had been handled before.
- about this, [background: url](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/1eb3112ac73adca3933d10b40fd0ef693a1ad4dc/src/style/codeStyle.ts#L107)  have been removed at this time.

**Comment by ai-chen2050** [comment]
Hi, @joethei, is there any other suggestions? 
Looks forward to seeing my plugin onboard at the Obsidian plugin marketplace. Thanks.

**Comment by joethei** [comment]
["description": "Release the article from your obsidian vault to WeChat, Baidu Baijiahao, or another article release platform.",](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/5b441e14f4eb035cf6209597d7b9e5934b5ce708/manifest.json#L6)
Don't include "Obsidian" in the plugin description

**Comment by ai-chen2050** [comment]
Hi, there, @joethei

**Comment by joethei** [comment]
Your readme still contains references to the Youtube feature that was removed.

**Comment by ai-chen2050** [comment]
> Your readme still contains references to the YouTube feature that was removed.

Hi, @joethei. The readme doc has been updated, and the content about the YouTube feature has been removed.

**Comment by joethei** [comment]
Sorry for all of the long delays.

[new Setting(containerEl).setName('🌈 Wechat public platform zone').setHeading();](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/c1e6ed691fed8b8391b7b4a71403b5f6ffc6a2f4/src/settingTab.ts#L25), [new Setting(containerEl).setName('🌎 🌞 Baidu bjh platform zone 🔍').setHeading();](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/c1e6ed691fed8b8391b7b4a71403b5f6ffc6a2f4/src/settingTab.ts#L38)
Remove "zone" here, it's unecessary.

Also, please stay consistent with the UI language, half the text is english, the other half is chinese.
You can also implement multiple languages if you want to, but don't do a mix like you do now.
The plugin UI should either be completely in english, or completely in chinese, but not both at the same time.

**Comment by ai-chen2050** [comment]
Hi, @joethei. Your new suggestions have been addressed. Please review again, thx.

**Comment by joethei** [comment]
[.setName(`Bjh platform haved logined: [ ${get(settingsStore).BjhName} ]`)](https://github.com/ai-chen2050/obsidian-wechat-public-platform/blob/ae40324320651f00db1a3b1c8b9ab43c03dc11a0/src/settingTab.ts#L127)
Thats not valid English, should be "Bjh username" probably.

**Comment by ai-chen2050** [comment]
Hi, @joethei  I have addressed this.

**Pull request merged**
