### PR TITLE
Add System Dark Mode plugin

### PR DESCRIPTION
**Pull request by kepano**

### CODE REVIEW

**Comment by lishid** [comment]
I think your .gitignore is ignoring the .ts file instead of the .js file 😂

**Comment by kepano** [comment]
@lishid that should be fixed, thanks

**Comment by lishid** [comment]
Cool. A couple of things suggest adding/tweaking:
- I don't see a way to disable/unload the plugin, probably a good idea to add that? You can use `this.register(() => ...unload callback...);` to register for an unload inline (inside the onload function) to help you unhook the media watch listener.
- A quick auto-format of your code would help fix the tabs vs spaces mix.
- Would suggest switching the function syntax from `functionname = () => {` to just `functionname() {`

**Comment by kepano** [comment]
@lishid This is done. Thanks for your help!

**Pull request merged**
