### PR TITLE
OZ Calendar Plugin

### PR DESCRIPTION
**Pull request by ozntel**
# I am submitting a new Community Plugin

## Repo URL
https://github.com/ozntel/oz-calendar

## Release Checklist
- [X] I have tested the plugin on
  - [X]  Windows
  - [X]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[this.app.metadataCache.on('changed', this.handleCacheChange);](https://github.com/ozntel/oz-calendar/blob/0234d75dc88a7ac498d088f6c629d7d2c910169e/src/main.ts#L39-L44)
Wrap each of these calls in a `this.registerEvent()`, Obsidian will automatically unload them when the plugin gets disabled.
This also means that your `onunload` function can get removed.

[fileNameInputEl.style.cssText = inputCss;](https://github.com/ozntel/oz-calendar/blob/0234d75dc88a7ac498d088f6c629d7d2c910169e/src/modal.ts#L30)
You should avoid assigning styles via JavaScript and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets

**Comment by ozntel** [comment]
I moved styles to CSS: https://github.com/ozntel/oz-calendar/commit/ffe496a8b5acbde58ceaed3b081ecfd7cf221865

And wrapped Obsidian's event listeners with `this.registerEvent()` https://github.com/ozntel/oz-calendar/commit/883ceb26759816acf2df77422f5400c8f092228c

I just needed to leave the listener I have for the document contextMenu since `this.registerEvent()` expects `EventRef` to be returned from the listener.

**Comment by liamcain** [comment]
- [abstractFile as TFile](https://github.com/ozntel/oz-calendar/blob/964f468f0f3cfb8f07cb07921c9e59ce26a7a6b6/src/components/noteList.tsx#L44) you really shouldn't be casting to TFile, instead you should do an instanceof check.
- [onClick](https://github.com/ozntel/oz-calendar/blob/964f468f0f3cfb8f07cb07921c9e59ce26a7a6b6/src/components/noteList.tsx#L118) you should use [`Keymap.isModEvent`](https://github.com/obsidianmd/obsidian-api/blob/009a10f196df551256a5894ea60fdf9ddaab19a1/obsidian.d.ts#L1639) to be consistent with Obsidian's modifier key => leaf type
- [`Keymap.isModEvent`](https://github.com/obsidianmd/obsidian-api/blob/009a10f196df551256a5894ea60fdf9ddaab19a1/obsidian.d.ts#L1639) this is the "source" so it shoudn't be 'file-explorer' it should be your view type.

**Comment by ozntel** [comment]
Thanks for the feedback. I just made the changes:

https://github.com/ozntel/oz-calendar/commit/8153b30cbd5c43c9cafbf8af0633f6e4f9fdf22d

https://github.com/ozntel/oz-calendar/commit/76a350a628a17d02027418dc84210af77e1b9424

**Pull request merged**
