### PR TITLE
Remove AnuPpuccin theme

### PR DESCRIPTION
**Pull request by AnubisNekhet**

### CODE REVIEW

**Comment by pgyogesh** [comment]
Why did this just happen? It was one of the best theme I was using :(

**Comment by mkpaz** [comment]
Wow, I've found the theme just yesterday evening, decided to try it now just find out that that it's already deleted. Author even removed repo without archiving it. Maybe someone can continue the work. There is [at least one recent fork](https://github.com/search?q=AnuPpuccin+fork%3Aonly+language%3AX&ref=simplesearch).

**Comment by pryley** [comment]
😢

**Comment by pgyogesh** [comment]
I don't want to be toxic here, I was fond of this theme and I just migrated to it from Primary. Was really excited with every updates. I Hope @AnubisNekhet brings it back.

**Comment by pryley** [comment]
As a maintainer of open source, I understand that it can be a lot of work. 

She prefaced the theme's readme with, "Please do note that I've made this theme for myself". So maybe by making it available, she found it was becoming no longer for herself and didn't want to have to deal with everything that that entails.

Whatever the reason, we likely need to respect the decision.

As @mkpaz said, there are forks that are reasonably up to date (within 2 days of the theme being taken down), so maybe someone will have the motivation to pick it up?

I for one will continue to use it.

In either case, you can always show your appreciation here (even if it's not re-released): https://www.buymeacoffee.com/anubisnekhet

**Comment by nevertoday** [comment]
Please be back , so great job U did ~

**Comment by nevertoday** [comment]
> As a maintainer of open source, I understand that it can be a lot of work.
> 
> She prefaced the theme's readme with, "Please do note that I've made this theme for myself". So maybe by making it available, she found it was becoming no longer for herself and didn't want to have to deal with everything that that entails. Since it's not archived, maybe she just made it private for herself.
> 
> Whatever the reason, we likely need to respect the decision.
> 
> As @mkpaz said, there are forks that are reasonably up to date (within 2 days of the theme being taken down), so maybe someone will have the motivation to pick it up?
> 
> I for one will continue to use it.
> 
> In either case, you can always show your appreciation here (even if it's not re-released): https://www.buymeacoffee.com/anubisnekhet

is there a way to get [extended colorschemes](https://github.com/AnubisNekhet/AnuPpuccin/blob/main/snippets/extended-colorschemes.css) files?

**Comment by VKWF** [comment]
What happened? 😭😭😭

**Comment by emisjerry** [comment]
> > As a maintainer of open source, I understand that it can be a lot of work.
> > She prefaced the theme's readme with, "Please do note that I've made this theme for myself". So maybe by making it available, she found it was becoming no longer for herself and didn't want to have to deal with everything that that entails. Since it's not archived, maybe she just made it private for herself.
> > Whatever the reason, we likely need to respect the decision.
> > As @mkpaz said, there are forks that are reasonably up to date (within 2 days of the theme being taken down), so maybe someone will have the motivation to pick it up?
> > I for one will continue to use it.
> > In either case, you can always show your appreciation here (even if it's not re-released): https://www.buymeacoffee.com/anubisnekhet
> 
> is there a way to get [extended colorschemes](https://github.com/AnubisNekhet/AnuPpuccin/blob/main/snippets/extended-colorschemes.css) files?

https://github.com/mkpaz/AnuPpuccin/tree/main/snippets

**Comment by mutachre** [comment]
Sad news, my fav theme ever 😔

**Comment by Rnzi** [comment]
best theme I was using ，sad。

**Pull request merged**
