### PR TITLE
Add power search plugin

### PR DESCRIPTION
**Pull request by aviral-batra**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/aviral-batra/obsidian-power-search

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by lishid** [comment]
Given that your plugin is designed to search Anki notes, I think it would make more sense to name it more appropriately to avoid disappointing users looking for ways to search for notes within Obsidian.

https://github.com/aviral-batra/obsidian-power-search/blob/6df53d1b8bd8ed33941ee9efae4f7b8cf4160f4b/src/main.ts#L18
Please see this tip: https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#avoid-managing-references-to-custom-views

https://github.com/aviral-batra/obsidian-power-search/blob/6df53d1b8bd8ed33941ee9efae4f7b8cf4160f4b/src/search.ts#L66
This may return null and cause an exception.

**Comment by aviral-batra** [comment]
> Given that your plugin is designed to search Anki notes, I think it would make more sense to name it more appropriately to avoid disappointing users looking for ways to search for notes within Obsidian.

Yeah, however, the very next thing I am going to do is make a generalised inheritable/extendable index class to add a variety of types of indexes. Querying the obsidian vault is next on my list so I will include this functionality! I will probably do it tomorrow. I'll also write an api so that others can create their own custom indexes. Anki and Obsidian search will be the "core" searchable  indexes for now. Then each source will have its own toggle in the settings so that it can be added/removed to the content to be searched. 

> https://github.com/aviral-batra/obsidian-power-search/blob/6df53d1b8bd8ed33941ee9efae4f7b8cf4160f4b/src/main.ts#L18 Please see this tip: https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#avoid-managing-references-to-custom-views
> 
> https://github.com/aviral-batra/obsidian-power-search/blob/6df53d1b8bd8ed33941ee9efae4f7b8cf4160f4b/src/search.ts#L66 This may return null and cause an exception.

Whoops, overlooked these and will fix now.

**Comment by aviral-batra** [comment]
@lishid I have now added this functionality!

**Comment by lishid** [comment]
Sounds good!

**Pull request merged**
