### PR TITLE
Add plugin: Things3 Today

### PR DESCRIPTION
**Pull request by wudanyang6**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/wudanyang6/obsidian-things3-today

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "things3 today list in obsidian",](https://github.com/wudanyang6/obsidian-things3-today/blob/4ed6a64d70a653c45cd0818baffca707c9d326de/manifest.json#L6)
Avoid including "in Obsidian" in your description.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[this.app.workspace](https://github.com/wudanyang6/obsidian-things3-today/blob/4ed6a64d70a653c45cd0818baffca707c9d326de/main.ts#L43-L45)
Do not detach leaves with your custom view in `onunload`, this is an antipattern, see: <https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Don't+detach+leaves+in+%60onunload%60>

[this.app.workspace.detachLeavesOfType(VIEW_TYPE_THINGS3);](https://github.com/wudanyang6/obsidian-things3-today/blob/4ed6a64d70a653c45cd0818baffca707c9d326de/main.ts#L49)
Also do not detach leaves here. Instead, only create a new leaf, if there is not one already.

[const relativePath = `${this.app.vault.configDir}/plugins/${this.manifest.id}/${fileName}`;](https://github.com/wudanyang6/obsidian-things3-today/blob/4ed6a64d70a653c45cd0818baffca707c9d326de/main.ts#L110)
Even easier, use `${this.manifest.dir}/${fileName}`

[const relativePath = this.getAbsolutePath('things.js')](https://github.com/wudanyang6/obsidian-things3-today/blob/4ed6a64d70a653c45cd0818baffca707c9d326de/main.ts#L180)
That file will not be downloaded by Obsidian when installing the plugin, either inline the code, or add an additional dependency to handle running AppleScript code.

**Comment by wudanyang6** [comment]
@ObsidianReviewBot rescan

**Comment by wudanyang6** [comment]
My English is not very good, thank you for your patience.

**Comment by joethei** [comment]
["description": "Managing Your Today's Tasks with Things3 Today List",](https://github.com/wudanyang6/obsidian-things3-today/blob/82d606ad1ff42c94d4a22283c01097fd62e85f6c/manifest.json#L6)
A better description would be `Manage today's tasks with Things3`

**Comment by wudanyang6** [comment]
@ObsidianReviewBot rescan

**Comment by wudanyang6** [comment]
@joethei I have made the changes, but the robot did not automatically modify the label.

**Pull request merged**
