### PR TITLE
Add plugin: Giphy

### PR DESCRIPTION
**Pull request by LuCrypto**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by LuCrypto** [comment]
What should I do now ?

**Comment by LuCrypto** [comment]
For "this.app as any", I don't know how else to do it

**Comment by joethei** [comment]
["description": "Plugin to search gifs on Giphy",](https://github.com/LuCrypto/giphy-plugin/blob/c44f5fc2989a43ca0e925e76083dcc8d521ddf00/manifest.json#L6)
Avoid including sentences like "This is a plugin that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[/*](https://github.com/LuCrypto/giphy-plugin/blob/c44f5fc2989a43ca0e925e76083dcc8d521ddf00/styles.css#L1-L8)
Remove this comment.

["Veuillez configurer votre clé API dans les paramètres du plugin.",](https://github.com/LuCrypto/giphy-plugin/blob/c44f5fc2989a43ca0e925e76083dcc8d521ddf00/main.tsx#L38), ["Veuillez configurer votre clé API dans les paramètres du plugin.",](https://github.com/LuCrypto/giphy-plugin/blob/c44f5fc2989a43ca0e925e76083dcc8d521ddf00/main.tsx#L57), ["Veuillez configurer votre clé API dans les paramètres du plugin.",](https://github.com/LuCrypto/giphy-plugin/blob/c44f5fc2989a43ca0e925e76083dcc8d521ddf00/main.tsx#L94), [(this.app as any).setting.openTabById("giphy-plugin");](https://github.com/LuCrypto/giphy-plugin/blob/c44f5fc2989a43ca0e925e76083dcc8d521ddf00/main.tsx#L117), ["Veuillez configurer votre clé API dans les paramètres du plugin."](https://github.com/LuCrypto/giphy-plugin/blob/c44f5fc2989a43ca0e925e76083dcc8d521ddf00/main.tsx#L196)
These error messages should be in english, like the rest of the plugin.

[(this.app as any).setting.openTabById("giphy-plugin");](https://github.com/LuCrypto/giphy-plugin/blob/c44f5fc2989a43ca0e925e76083dcc8d521ddf00/main.tsx#L42), [(this.app as any).setting.openTabById("giphy-plugin");](https://github.com/LuCrypto/giphy-plugin/blob/c44f5fc2989a43ca0e925e76083dcc8d521ddf00/main.tsx#L61)
Wrong plugin id.

[.setName("API Key")](https://github.com/LuCrypto/giphy-plugin/blob/c44f5fc2989a43ca0e925e76083dcc8d521ddf00/main.tsx#L248)

**Comment by LuCrypto** [comment]
Normally, everything is good

**Comment by joethei** [comment]
You forgot to remove the comment.

**Comment by LuCrypto** [comment]
This comment no longer exists

**Pull request merged**
