### PR TITLE
Add plugin: CalcCraft

### PR DESCRIPTION
**Pull request by klaudyu**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/klaudyu/CalcCraft/

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[newCell.innerHTML = index + 1 - this.rowOffset; // Row numbers start from 1](https://github.com/klaudyu/CalcCraft/blob/fe350001409407b777abc86e83f434605031614b/main.ts#L538)
[Avoid using `innerHTML`](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%60innerHTML%60%2C+%60outerHTML%60+and+%60insertAdjacentHTML%60)

[this.containerEl.createEl("h3", {](https://github.com/klaudyu/CalcCraft/blob/fe350001409407b777abc86e83f434605031614b/settings.ts#L47-L49)
[Don't use a "general" heading in your settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by klaudyu** [comment]
Updated. Hope is good now :)

**Comment by liamcain** [comment]
Hi @klaudyu, the plugin looks good, you just need to fix an issue with your 1.1.0 release. @ me here when its resolved and I can merge this.

**Comment by klaudyu** [comment]
> Hi @klaudyu, the plugin looks good, you just need to fix an issue with your 1.1.0 release. @ me here when its resolved and I can merge this.

Thanks [@limcain](https://github.com/liamcain) for pointing out the issue. I've added the manifest.json. Sorry for the oversight. :)"

**Pull request merged**
