### PR TITLE
Add plugin: Daily Note Collector

### PR DESCRIPTION
**Pull request by LA**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/la/obsidian-daily-note-collector

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["minAppVersion": "0.15.0",](https://github.com/LA/obsidian-daily-note-collector/blob/5d7e92f1411e2ff25a5de82c702c57d62799898e/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

**Comment by LA** [comment]
> ["minAppVersion": "0.15.0",](https://github.com/LA/obsidian-daily-note-collector/blob/5d7e92f1411e2ff25a5de82c702c57d62799898e/manifest.json#L5) You are using newer API's, set this to the latest public build number.

I only left what the [sample plugin default is](https://github.com/obsidianmd/obsidian-sample-plugin/blob/master/manifest.json#L5), but I have updated my [minAppVersion to 1.6.7](https://github.com/LA/obsidian-daily-note-collector/blob/master/manifest.json#L5) and created [a new release](https://github.com/LA/obsidian-daily-note-collector/releases/tag/1.0.2).

**Comment by liamcain** [comment]
- [this.app.vault.on("create", this.onCreateFile.bind(this))](https://github.com/LA/obsidian-daily-note-collector/blob/54243029e4f6baacd51dbf7f19f532c29f729803/main.ts#L10) you should not register the 'create' vault event directly in `onload`. This registration should be wrapped inside a [`onLayoutReady`](https://github.com/obsidianmd/obsidian-api/blob/9bb30633586c6649474b2affdf5b87efdd86498f/obsidian.d.ts#L3626) callback. To see why, try restarting Obsidian and opening your daily note. "create" is fired for every note in your vault as part of its initialization process, so you will end up with a link to every note in your vault.
- [const date = new Date();](https://github.com/LA/obsidian-daily-note-collector/blob/54243029e4f6baacd51dbf7f19f532c29f729803/main.ts#L94-L99) The daily note path is configurable. You can't assume that the file path will be YYYY-MM-DD.md. You should use something like <https://github.com/liamcain/obsidian-daily-notes-interface> to get the path to the current daily note.
- [getLink(file: TFile) {](https://github.com/LA/obsidian-daily-note-collector/blob/54243029e4f6baacd51dbf7f19f532c29f729803/main.ts#L80) instead of creating this yourself, you should use generateMarkdownLink (<https://github.com/obsidianmd/obsidian-api/blob/df9434bec6883bd32727f61b1ed1336f7663d0e4/obsidian.d.ts#L1435> which will follow the user's link format settings.

**Comment by LA** [comment]
Thank you @liamcain for your detailed feedback!

I have released a new version that I believe satisfies all of your concerns: https://github.com/LA/obsidian-daily-note-collector/releases/tag/1.0.3

**Pull request merged**
