### PR TITLE
Add obsidian-task-archiver

### PR DESCRIPTION
**Pull request by ivan-lednev**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/ivan-lednev/obsidian-task-archiver

## Release Checklist

- [x] I have tested this on Windows
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/ivan-lednev/obsidian-task-archiver/blob/d769ce7d43a74b5a02b277fdd2527e55f06019b4/main.ts#L32

Please test this variable for null and also make sure that `file.extension === 'md'`.

https://github.com/ivan-lednev/obsidian-task-archiver/blob/d769ce7d43a74b5a02b277fdd2527e55f06019b4/main.ts#L50

This isn't a good idea since you will now replicate the full obsidian configuration file into your plugin's config. Better to just get the specific config you want through `vault.getConfig(key)`.

https://github.com/ivan-lednev/obsidian-task-archiver/blob/d769ce7d43a74b5a02b277fdd2527e55f06019b4/src/archiver.ts#L2
Use `moment` from `obsidian` instead of importing a fresh copy.

https://github.com/ivan-lednev/obsidian-task-archiver/blob/d769ce7d43a74b5a02b277fdd2527e55f06019b4/src/archiver.ts#L14
Need to escape this regex.

**Comment by ivan-lednev** [comment]
Hello, @lishid,
Thank you for your feedback! I fixed the issues you pointed out.

**Comment by ivan-lednev** [comment]
Hello, @lishid 
please let me know if there is anything else I should get done before you merge the plugin.

**Comment by lishid** [comment]
Oops! I fixed the conflict but forgot to merge, sorry about that!

**Pull request merged**
