### PR TITLE
Add plugin: Pia viewer

### PR DESCRIPTION
**Pull request by dldisud**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/dldisud/obsidian-pia-viewer

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[Copyright (c) 2024 exloseur3d](https://github.com/dldisud/obsidian-typography-styles/blob/a53235dd20bbe172b306a534f0b7d7d6d667c7e2/LICENSE.txt#L3)
Wrong name

["description": "A plugin to apply Mobile typography styles",](https://github.com/dldisud/obsidian-typography-styles/blob/a53235dd20bbe172b306a534f0b7d7d6d667c7e2/manifest.json#L6)
Avoid including sentences like "This is a plugin that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.


[containerEl.createEl('h2', { text: 'Custom Typography Settings' });](https://github.com/dldisud/obsidian-typography-styles/blob/a53235dd20bbe172b306a534f0b7d7d6d667c7e2/main.js#L91)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[.setName('Select Typography Style')](https://github.com/dldisud/obsidian-typography-styles/blob/a53235dd20bbe172b306a534f0b7d7d6d667c7e2/main.js#L94)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by dldisud** [comment]
Is it okay?

**Review by dldisud — COMMENTED** [review]
did it?

**Comment by dldisud** [comment]
did it work?

**Pull request merged**
