### PR TITLE
Add plugin: Time Things

### PR DESCRIPTION
**Pull request by DynamicPlayerSector**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/DynamicPlayerSector/timethings

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["authorUrl": "",](https://github.com/DynamicPlayerSector/timethings/blob/5cfcd0798cea3deda64f4510d761e3bbfa66f705/manifest.json#L8)
Put your GitHub profile URL here if you don't have a website.

["fundingUrl": {},](https://github.com/DynamicPlayerSector/timethings/blob/5cfcd0798cea3deda64f4510d761e3bbfa66f705/manifest.json#L9)
Omit this if you don't have such a link.

[// Remember to rename these classes and interfaces!](https://github.com/DynamicPlayerSector/timethings/blob/5cfcd0798cea3deda64f4510d761e3bbfa66f705/main.ts#L4)
Please do rename the example classes.

[setInterval(this.updateStatusBar.bind(this), +this.settings.updateIntervalMilliseconds);](https://github.com/DynamicPlayerSector/timethings/blob/5cfcd0798cea3deda64f4510d761e3bbfa66f705/main.ts#L43)
Don't forget to register this interval, like in the example code below.

[console.log('File has been modified.');](https://github.com/DynamicPlayerSector/timethings/blob/5cfcd0798cea3deda64f4510d761e3bbfa66f705/main.ts#L48)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.


[// If the plugin hooks up any global DOM events (on parts of the app that doesn't belong to this plugin)](https://github.com/DynamicPlayerSector/timethings/blob/5cfcd0798cea3deda64f4510d761e3bbfa66f705/main.ts#L58-L65)
Remove this sample code.

[class SampleModal extends Modal {](https://github.com/DynamicPlayerSector/timethings/blob/5cfcd0798cea3deda64f4510d761e3bbfa66f705/main.ts#L152-L166)
remove this sample code.

[containerEl.createEl('h1', { text: 'Status Bar' });](https://github.com/DynamicPlayerSector/timethings/blob/5cfcd0798cea3deda64f4510d761e3bbfa66f705/main.ts#L193-L194)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[new Setting(containerEl)](https://github.com/DynamicPlayerSector/timethings/blob/5cfcd0798cea3deda64f4510d761e3bbfa66f705/main.ts#L207-L216)
Would recommend taking a look at the `MomentFormatComponent` for this setting: <https://docs.obsidian.md/Reference/TypeScript+API/Setting/addMomentFormat>

[.setPlaceholder('Enter your secret')](https://github.com/DynamicPlayerSector/timethings/blob/5cfcd0798cea3deda64f4510d761e3bbfa66f705/main.ts#L259)
use a different placeholder.

[.setPlaceholder('Enter your secret')](https://github.com/DynamicPlayerSector/timethings/blob/5cfcd0798cea3deda64f4510d761e3bbfa66f705/main.ts#L270)
Same as above.

**Comment by DynamicPlayerSector** [comment]
Changed as requested, except for two moments mentioned below.

> [containerEl.createEl('h1', { text: 'Status Bar' });](https://github.com/DynamicPlayerSector/timethings/blob/5cfcd0798cea3deda64f4510d761e3bbfa66f705/main.ts#L193-L194)
> [Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

Status Bar is not the name of the plugin. It's just a section. Also it has no global variables, so I understand why it might look like it.

> [new Setting(containerEl)](https://github.com/DynamicPlayerSector/timethings/blob/5cfcd0798cea3deda64f4510d761e3bbfa66f705/main.ts#L207-L216)
> Would recommend taking a look at the MomentFormatComponent for this setting: https://docs.obsidian.md/Reference/TypeScript+API/Setting/addMomentFormat

I will, I hope it's fine for now as is.

@joethei please consider those changes.

**Comment by DynamicPlayerSector** [comment]
Did I do something wrong? @joethei

**Comment by liamcain** [comment]
- [const dateNow = moment();](https://github.com/DynamicPlayerSector/timethings/blob/ce0e47dd8cb4beb39118dc856d6dee8a32c791cd/main.ts#L92) do this after the if check, constructing moment() instances isn't cheap, better not waste it
- [editor: Editor = activeView.editor](https://github.com/DynamicPlayerSector/timethings/blob/ce0e47dd8cb4beb39118dc856d6dee8a32c791cd/main.ts#L98) You should also check to see if the editor has focus before continuing. The markdown view might be in reading mode, or the title might be focused.
- [const editor = activeView.editor](https://github.com/DynamicPlayerSector/timethings/blob/ce0e47dd8cb4beb39118dc856d6dee8a32c791cd/main.ts#L84) make sure editor is focused
- [const editor: Editor = activeView.editor](https://github.com/DynamicPlayerSector/timethings/blob/ce0e47dd8cb4beb39118dc856d6dee8a32c791cd/main.ts#L69) make sure editor is focused

**Comment by ericaxu** [comment]
To keep things tidy, we're going to close issues that we don't hear back after a month of inactivity.

Feel free to tell us to re-open it when you're ready to reply and we'll reopen the issue right away. Thanks for your understanding!

**Comment by DynamicPlayerSector** [comment]
> To keep things tidy, we're going to close issues that we don't hear back after a month of inactivity.
> 
> Feel free to tell us to re-open it when you're ready to reply and we'll reopen the issue right away. Thanks for your understanding!

Hello. I added the changes requested. Please re-open this issue. Thanks

**Comment by DynamicPlayerSector** [comment]
Bump?

**Comment by DynamicPlayerSector** [comment]
@joethei any updates?

**Comment by liamcain** [comment]
Thanks for updating this, looks good!

**Pull request merged**
