### PR TITLE
Add Text Snippets plugin

### PR DESCRIPTION
**Pull request by ArianaKhit**
# Text Snippets plugin

## Repo URL
https://github.com/ArianaKhit/text-snippets-obsidian

## Release Checklist
- [x] I have tested this on Windows
- [x] Github release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] Github release name matches the exact version number specified in your manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.

### CODE REVIEW

**Comment by lishid** [comment]
Couple of suggestions:

- Auto-format your code to normalize spacing.

https://github.com/ArianaKhit/text-snippets-obsidian/blob/f94180db9f8926ca6482f8bc086ae5ebe70f65b6/main.ts#L23
Maybe "Run snippet replacement"? "Parse snippet" sounds more like reading something but not doing anything.

https://github.com/ArianaKhit/text-snippets-obsidian/blob/f94180db9f8926ca6482f8bc086ae5ebe70f65b6/main.ts#L40
Use `Object.assign({}, DEFAULT_SETTINGS, await this.loadData());` here.

https://github.com/ArianaKhit/text-snippets-obsidian/blob/f94180db9f8926ca6482f8bc086ae5ebe70f65b6/main.ts#L47
Consider using `CodeMirror.Editor` here instead of `any`. Might need some kind of `import type` which should be erased on compile time without importing a copy of CodeMirror.

https://github.com/ArianaKhit/text-snippets-obsidian/blob/f94180db9f8926ca6482f8bc086ae5ebe70f65b6/main.ts#L111
Same as above, for cursor you might want to use `CodeMirror.Pos`.

Duplicate code:
https://github.com/ArianaKhit/text-snippets-obsidian/blob/f94180db9f8926ca6482f8bc086ae5ebe70f65b6/main.ts#L113
https://github.com/ArianaKhit/text-snippets-obsidian/blob/f94180db9f8926ca6482f8bc086ae5ebe70f65b6/main.ts#L120

**Comment by ArianaKhit** [comment]
Code is auto-formatted, everything is fixed

**Comment by ArianaKhit** [comment]
README.md is updated.

> Maybe "Run snippet replacement"?

Yes, it sounds better. Thank you for your suggestions

**Comment by lishid** [comment]
Looks good, I can merge as soon as the merge conflict is fixed.

**Comment by lishid** [comment]
Looks like your merge duplicated the file content... Can you fix that?

**Comment by ArianaKhit** [comment]
Sorry about that, it was a little bit strange

**Pull request merged**
