### PR TITLE
Add Periodic PARA plugin

### PR DESCRIPTION
**Pull request by quanru**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/quanru/obsidian-periodic-para

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[Copyright (c) 2021 Michael Brenan](https://github.com/quanru/obsidian-periodic-para/blob/ecb9f5cc44296d19ff13a5a4552d58038e56c24a/LICENSE.txt#L3)
Update this with your own info.

["description": "This is a plugin to assist in practicing the PARA system with periodic notes.",](https://github.com/quanru/obsidian-periodic-para/blob/ecb9f5cc44296d19ff13a5a4552d58038e56c24a/manifest.json#L6)
We have recently published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This is a plugin for Obsidian" in your description.

["author": "YiBing Lin <quanruzhuoxiu@gmail.com>",](https://github.com/quanru/obsidian-periodic-para/blob/ecb9f5cc44296d19ff13a5a4552d58038e56c24a/manifest.json#L7)
This field is displayed in the sidebar and in the description for the plugin details page. Are you sure you want to have your email listed so prominently?
image

[if (!isPluginEnabled(app)) {](https://github.com/quanru/obsidian-periodic-para/blob/ecb9f5cc44296d19ff13a5a4552d58038e56c24a/src/main.ts#L35-L38)
Please mention in your readme that Dataview is required.

[containerEl.createEl('h2', { text: 'Settings for Periodic PARA plugin.' });](https://github.com/quanru/obsidian-periodic-para/blob/ecb9f5cc44296d19ff13a5a4552d58038e56c24a/src/main.ts#L148)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)
[Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)


[```periodic-para](https://github.com/quanru/obsidian-periodic-para/blob/ecb9f5cc44296d19ff13a5a4552d58038e56c24a/README.md#L26-L28)
You are using kebab-case, and PascalCase here, please stick to one naming convention.

**Comment by quanru** [comment]
@joethei Hi, I made the changes as requested!

**Comment by liamcain** [comment]
- [component.load](https://github.com/quanru/obsidian-periodic-para/blob/892f91ffea97d2b79361883cbe0d36a81f83af7b/src/periodic/Bullet.ts#L65) don't call load() manually.
- [component = new Component()](https://github.com/quanru/obsidian-periodic-para/blob/892f91ffea97d2b79361883cbe0d36a81f83af7b/src/periodic/Bullet.ts#L31) you need to register this with the MarkdownPostProcessorContext. You should make a subclass of MarkdownRenderChild then call ctx.addChild(component). Same applies for the other files.

**Comment by quanru** [comment]
> * [component.load](https://github.com/quanru/obsidian-periodic-para/blob/892f91ffea97d2b79361883cbe0d36a81f83af7b/src/periodic/Bullet.ts#L65) don't call load() manually.
> * [component = new Component()](https://github.com/quanru/obsidian-periodic-para/blob/892f91ffea97d2b79361883cbe0d36a81f83af7b/src/periodic/Bullet.ts#L31) you need to register this with the MarkdownPostProcessorContext. You should make a subclass of MarkdownRenderChild then call ctx.addChild(component). Same applies for the other files.

Done: https://github.com/quanru/obsidian-periodic-para/commit/c071113870d451d8faca2cd965881c8777ce8b34

**Pull request merged**
