### PR TITLE
Add plugin: Print

### PR DESCRIPTION
**Pull request by marijnbent**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/marijnbent/obsidian-print

Export-1725021591298

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by marijnbent** [comment]
FYI: I have converted my code to TypeScript. Will release a new version later tonight

**Comment by marijnbent** [comment]
0.2.1 is out! Typescript added, and a bunch more modern obsidian api calls. 

Curious the hear what you think!

**Comment by marijnbent** [comment]
I have addressed the issues:
https://github.com/marijnbent/obsidian-print/commit/c3c7e72a7bc027166f5f456f7df1b410b2413cce
https://github.com/marijnbent/obsidian-print/commit/8cfb6edf4a394bdc62e4fe14946c908efb6018be
https://github.com/marijnbent/obsidian-print/commit/90b5ff822e4cf171ecd733777e9421a63f04b16a

The innerHTML is difficult, as I need the HTML content to encode it as URL for Electrons BrowserWindow.

**Comment by marijnbent** [comment]
Addressed this `any` as well https://github.com/marijnbent/obsidian-print/blob/2eda864fa17a37c38a1c6628f1621aacd281fde6/src/printModal.ts#L6

**Comment by marijnbent** [comment]
Actually managed to address the innerHTML issue as well. I removed using the deprecated Electron remote BrowserWindow in favor for the print-js package.

https://github.com/marijnbent/obsidian-print/commit/b66275b01846152490f637bf930b0bd6d15cd943

**Comment by marijnbent** [comment]
Added a way to print all notes in a folder as well ✨

**Comment by marijnbent** [comment]
Hi @joethei,

Thanks for our brief chat on Discord. When you have a chance to review, I'd appreciate your thoughts on the code at https://github.com/marijnbent/obsidian-print/blob/main/src/utils/generatePrintStyles.ts#L24-L40.

Specifically, I'm wondering if you could suggest an alternative approach to getting these styles without using the FileSystemAdapter. The goal is to make the plugin compatible with mobile devices as well.

No rush on this - I know you're likely busy. I'm just looking for ideas whenever you have time to take a look. Thanks!

**Comment by joethei** [comment]
[# Obsidian Print](https://github.com/marijnbent/obsidian-print/blob/2ae33db4f6bba5da5bd4f3d0aa1e382ffe9f3ada/README.md#L1), [The **Obsidian Print** plugin](https://github.com/marijnbent/obsidian-print/blob/2ae33db4f6bba5da5bd4f3d0aa1e382ffe9f3ada/README.md#L3)
Remove "Obsidian" from here, "Obsidian xyz" is reserved for first party creations (like Obsidian Sync or Obsidian Canvas)

["description": "A simple plugin to add a print action.",](https://github.com/marijnbent/obsidian-print/blob/2ae33db4f6bba5da5bd4f3d0aa1e382ffe9f3ada/manifest.json#L6)
Avoid including sentences like "This is a plugin that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[this.addRibbonIcon('printer', 'Print Note', (evt: MouseEvent) => {](https://github.com/marijnbent/obsidian-print/blob/2ae33db4f6bba5da5bd4f3d0aa1e382ffe9f3ada/src/main.ts#L30), [titleElement.textContent = 'Print Note';](https://github.com/marijnbent/obsidian-print/blob/2ae33db4f6bba5da5bd4f3d0aa1e382ffe9f3ada/src/utils/printModal.ts#L17)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[new Setting(containerEl).setName('Print').setHeading();](https://github.com/marijnbent/obsidian-print/blob/2ae33db4f6bba5da5bd4f3d0aa1e382ffe9f3ada/src/settings.ts#L17)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[const adapter = app.vault.adapter as FileSystemAdapter;](https://github.com/marijnbent/obsidian-print/blob/2ae33db4f6bba5da5bd4f3d0aa1e382ffe9f3ada/src/utils/generatePrintStyles.ts#L14-L19)
The regular adapter should be enough here, so remove the `as` cast and the `instanceof` cast.

**Comment by marijnbent** [comment]
Thanks for the review @joethei. The updated plugin is released as a new version.

> [# Obsidian Print](https://github.com/marijnbent/obsidian-print/blob/2ae33db4f6bba5da5bd4f3d0aa1e382ffe9f3ada/README.md#L1), [The **Obsidian Print** plugin](https://github.com/marijnbent/obsidian-print/blob/2ae33db4f6bba5da5bd4f3d0aa1e382ffe9f3ada/README.md#L3) Remove "Obsidian" from here, "Obsidian xyz" is reserved for first party creations (like Obsidian Sync or Obsidian Canvas)

https://github.com/marijnbent/obsidian-print/commit/f22951493945ca4a232398523ed590e924c0bcb4
 
> ["description": "A simple plugin to add a print action.",](https://github.com/marijnbent/obsidian-print/blob/2ae33db4f6bba5da5bd4f3d0aa1e382ffe9f3ada/manifest.json#L6) Avoid including sentences like "This is a plugin that does ..." in your description, it should be self-evident that this is a plugin for Obsidian. We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

https://github.com/marijnbent/obsidian-print/commit/156b0099be0fb00f80653d03eae74df3247bf732

> [this.addRibbonIcon('printer', 'Print Note', (evt: MouseEvent) => {](https://github.com/marijnbent/obsidian-print/blob/2ae33db4f6bba5da5bd4f3d0aa1e382ffe9f3ada/src/main.ts#L30), [titleElement.textContent = 'Print Note';](https://github.com/marijnbent/obsidian-print/blob/2ae33db4f6bba5da5bd4f3d0aa1e382ffe9f3ada/src/utils/printModal.ts#L17) [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

https://github.com/marijnbent/obsidian-print/commit/35593448ed7728784dee56940bcb61f3bb7b348b
https://github.com/marijnbent/obsidian-print/commit/4c6a7f8c20cd57a22010aa0092abdb690a57804e

> [new Setting(containerEl).setName('Print').setHeading();](https://github.com/marijnbent/obsidian-print/blob/2ae33db4f6bba5da5bd4f3d0aa1e382ffe9f3ada/src/settings.ts#L17) [Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

https://github.com/marijnbent/obsidian-print/commit/8e55c3e8ca95d99cccd6563a3628ff7e723b9336

> [const adapter = app.vault.adapter as FileSystemAdapter;](https://github.com/marijnbent/obsidian-print/blob/2ae33db4f6bba5da5bd4f3d0aa1e382ffe9f3ada/src/utils/generatePrintStyles.ts#L14-L19) The regular adapter should be enough here, so remove the `as` cast and the `instanceof` cast.

https://github.com/marijnbent/obsidian-print/commit/c19770fd769c8ffeb21390273aeb2d33d29dee24

**Pull request merged**
