### PR TITLE
Add plugin: Modal Opener

### PR DESCRIPTION
**Pull request by likemuuxi**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/likemuuxi/obsidian-modal-opener

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by likemuuxi** [comment]
/skip [[3](https://github.com/likemuuxi/obsidian-modal-plugin/blob/8aa0c2eea46357f8d8e62df6b425fa587f088279/src/modal.ts#L182)] 
Modifying this style will affect other non plugin modal windows

**Comment by joethei** [comment]
[.modal {](https://github.com/likemuuxi/obsidian-modal-opener/blob/82a45f7591ea41b09053c1b89f2762f586c1075f/styles.css#L36-L45)
These filenames are too generic, add another class/data attribute so it only applies to your plugin.

[this.addCommand({](https://github.com/likemuuxi/obsidian-modal-opener/blob/82a45f7591ea41b09053c1b89f2762f586c1075f/src/main.ts#L49-L52)
This command does nothing.

[private debounceTimeout: NodeJS.Timeout | null = null;](https://github.com/likemuuxi/obsidian-modal-opener/blob/82a45f7591ea41b09053c1b89f2762f586c1075f/src/modal.ts#L15)
Use `Number` as the type here

[const response = await fetch(url, { method: 'HEAD', mode: 'no-cors' });](https://github.com/likemuuxi/obsidian-modal-opener/blob/82a45f7591ea41b09053c1b89f2762f586c1075f/src/modal.ts#L36)
Use the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

["Open in Modal Window": "Open in Modal Window",](https://github.com/likemuuxi/obsidian-modal-opener/blob/82a45f7591ea41b09053c1b89f2762f586c1075f/src/lang/locale/en.ts#L12-L17), ['Current File':'Current File',](https://github.com/likemuuxi/obsidian-modal-opener/blob/82a45f7591ea41b09053c1b89f2762f586c1075f/src/lang/locale/en.ts#L22), ['Enable Animation and Blur':'Enable Animation and Blur',](https://github.com/likemuuxi/obsidian-modal-opener/blob/82a45f7591ea41b09053c1b89f2762f586c1075f/src/lang/locale/en.ts#L35), ['Show File View Header':'Show File View Header',](https://github.com/likemuuxi/obsidian-modal-opener/blob/82a45f7591ea41b09053c1b89f2762f586c1075f/src/lang/locale/en.ts#L37-L38), ['Disable external click Close':'Disable external click Close',](https://github.com/likemuuxi/obsidian-modal-opener/blob/82a45f7591ea41b09053c1b89f2762f586c1075f/src/lang/locale/en.ts#L28), ['Hide Tab Header':'Hide Tab Header',](https://github.com/likemuuxi/obsidian-modal-opener/blob/82a45f7591ea41b09053c1b89f2762f586c1075f/src/lang/locale/en.ts#L43), ['Hide Tab Header':'Hide Tab Header',](https://github.com/likemuuxi/obsidian-modal-opener/blob/82a45f7591ea41b09053c1b89f2762f586c1075f/src/lang/locale/en.ts#L43), ['Custom Commands':'Custom Commands',](https://github.com/likemuuxi/obsidian-modal-opener/blob/82a45f7591ea41b09053c1b89f2762f586c1075f/src/lang/locale/en.ts#L46-L47), ['Description':'Enter File Path or Web Link',](https://github.com/likemuuxi/obsidian-modal-opener/blob/82a45f7591ea41b09053c1b89f2762f586c1075f/src/lang/locale/en.ts#L52)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by likemuuxi** [comment]
Hi joethei,

I've made the requested changes. Could you please review the updates at your convenience? Let me know if there's anything else I need to address.
[this.addCommand](https://github.com/likemuuxi/obsidian-modal-opener/blob/82a45f7591ea41b09053c1b89f2762f586c1075f/src/main.ts#L49-L52) This command binds the shortcut key in the `bindHotkey()` function of `modal.ts` and defines the functionality in the `openInNewTab()` function

Thank you!

**Comment by joethei** [comment]
[this.app.keymap.popScope(this.scope);](https://github.com/likemuuxi/obsidian-modal-opener/blob/97d67088ce0ce60a288a7290e0a2228b196dcb5b/src/modal.ts#L254), [this.app.keymap.pushScope(this.scope);](https://github.com/likemuuxi/obsidian-modal-opener/blob/97d67088ce0ce60a288a7290e0a2228b196dcb5b/src/modal.ts#L283)
Modals already manage the scope automatically, no need to do this here.

[this.scope.register([], 'Escape', (evt: KeyboardEvent) => {](https://github.com/likemuuxi/obsidian-modal-opener/blob/97d67088ce0ce60a288a7290e0a2228b196dcb5b/src/modal.ts#L278-L282)
This is already registered by default

[if (savedHotkeys && savedHotkeys.length > 0) {](https://github.com/likemuuxi/obsidian-modal-opener/blob/97d67088ce0ce60a288a7290e0a2228b196dcb5b/src/modal.ts#L269-L275)
Remove this code, 
You already have a reference to the active modal in the plugin class, use that and a `checkCallback` to only run that command when the modal is open.

You can use
```ts
this.scope = new Scope(this.app.scope); // Allow app commands to work inside modal
```
To allow commands to be ran inside of your modal.
The way you implemented it currently is just too confusing, since there will be a command on the command pallete that won't do anything-

**Comment by likemuuxi** [comment]
Dear joethei,

I hope this message finds you well. I am writing to kindly follow up on the status of my plugin submission. I have made the requested modifications after the initial review, and it has been three weeks since my last update.

Could you please provide an update on the current status or let me know if any further actions are needed on my part?

Thank you for your time and support. I look forward to hearing from you soon.

Best regards!

**Pull request merged**
