### PR TITLE
Add SyncFTP Plugin

### PR DESCRIPTION
**Pull request by alex-donnan**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [https://github.com/alex-donnan/SyncFTP](https://github.com/alex-donnan/SyncFTP)

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by alex-donnan** [comment]
Manifest authorUrl field updated.

**Comment by joethei** [comment]
["description": "This app syncs files to an SFTP, with credentials in settings.",](https://github.com/alex-donnan/SyncFTP/blob/1e0007329edf51dca93c62ad1bfe9124a4e2401b/manifest.json#L6)
This is not an app, it's a plugin.
We have recently published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[Copyright (c) [year] [fullname]](https://github.com/alex-donnan/SyncFTP/blob/1e0007329edf51dca93c62ad1bfe9124a4e2401b/LICENSE#L3)
Please fill this.

[sync = `Local file ${loc_file.name} moved to Obsidian trash.`;](https://github.com/alex-donnan/SyncFTP/blob/1e0007329edf51dca93c62ad1bfe9124a4e2401b/main.ts#L176)
Since you have set the `system` parameter in the function call above to `true` this is incorrect.
The file will be moved to the system trash.

**Comment by alex-donnan** [comment]
Hi, thanks for the review!

I have made the requested changes to the plugin and created a new release with minor changes to the main.js.

**Comment by joethei** [comment]
[this.registerDomEvent(document, 'click', (evt: MouseEvent) => {](https://github.com/alex-donnan/SyncFTP/blob/3a2a3276725898aa1cd36c723b81a341bfb205e1/main.ts#L65-L67)
Remove this.

[.setName('Proxy Port')](https://github.com/alex-donnan/SyncFTP/blob/3a2a3276725898aa1cd36c723b81a341bfb205e1/src/credential.ts#L51)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[.setName('Proxy Port')](https://github.com/alex-donnan/SyncFTP/blob/3a2a3276725898aa1cd36c723b81a341bfb205e1/src/credential.ts#L51-L52)
You can remove the description here, the text is already in the name, no need to duplicate it.

**Comment by alex-donnan** [comment]
Thanks again, I've made the requested updates and updated the release.

**Pull request merged**
