### PR TITLE
Add plugin: Tag Buddy

### PR DESCRIPTION
**Pull request by moremeyou**
# I am submitting a new Community Plugin
## Repo URL
Link to my plugin: https://github.com/moremeyou/Obsidian-Tag-Buddy

## Release Checklist
* [x]  I have tested the plugin on
   
   * [x]   Windows
   * [x]   macOS
   * [ ]   Linux
   * [x]   Android _(if applicable)_
   * [x]   iOS _(if applicable)_
 * [x]  My GitHub release contains all required files
   
   * [x]  `main.js`
   * [x]  `manifest.json`
   * [ ]  `styles.css` _(optional)_
 * [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
 * [x]  The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
 * [x]  My README.md describes the plugin's purpose and provides clear usage instructions.
 * [x]  I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
* [x]  I have added a license in the LICENSE file.
 * [x]  My project respects and is compatible with the original license of any code from other plugins that I'm using.
   I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by moremeyou** [comment]
Updated to 0.6.2

**Comment by joethei** [comment]
["css": "src/styles.css"](https://github.com/moremeyou/Obsidian-Tag-Buddy/blob/c3e259c0b7d2025f88713a55a96e31f4403cfab1/manifest.json#L11-L12)
This is not a valid key, the file needs to be next to the `main.js` and `manifest.json`
Also for it to be downloaded the file needs to be included in the release.

[console.log('accepted:', tag)](https://github.com/moremeyou/Obsidian-Tag-Buddy/blob/c3e259c0b7d2025f88713a55a96e31f4403cfab1/src/main.ts#L336)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[button.title = 'Refresh Tag Summary';](https://github.com/moremeyou/Obsidian-Tag-Buddy/blob/c3e259c0b7d2025f88713a55a96e31f4403cfab1/src/gui.ts#L78)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[donateButton.innerHTML = `Buy Me A Coffee</a>`;](https://github.com/moremeyou/Obsidian-Tag-Buddy/blob/c3e259c0b7d2025f88713a55a96e31f4403cfab1/src/settings.ts#L156)
[Avoid using `innerHTML`](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%60innerHTML%60%2C+%60outerHTML%60+and+%60insertAdjacentHTML%60)

[// Assuming this is the block quote color](https://github.com/moremeyou/Obsidian-Tag-Buddy/blob/c3e259c0b7d2025f88713a55a96e31f4403cfab1/src/styles.css#L12)
Comments in CSS are `/* text */`, everything else will cause parsing to fail.

[export function debounce(](https://github.com/moremeyou/Obsidian-Tag-Buddy/blob/c3e259c0b7d2025f88713a55a96e31f4403cfab1/src/utils.ts#L356-L368)
This is already a function in the Obsidian API.

[navigator.platform.toUpperCase().indexOf('MAC')](https://github.com/moremeyou/Obsidian-Tag-Buddy/blob/c3e259c0b7d2025f88713a55a96e31f4403cfab1/src/utils.ts#L453)
Use `Platform.isMacOS` instead.

[export function htmlToMarkdown(](https://github.com/moremeyou/Obsidian-Tag-Buddy/blob/c3e259c0b7d2025f88713a55a96e31f4403cfab1/src/utils.ts#L459)
This is also already a function in the API.

**Comment by moremeyou** [comment]
Hey @joethei,
Thanks for the feedback. I've addressed your notes an updated the release to 0.6.3. Details below:

> "css": "src/styles.css": This is not a valid key, the file needs to be next to the `main.js` and `manifest.json` Also for it to be downloaded the file needs to be included in the release.

Fixed.

> console.log('accepted:', tag): Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

Removed.

> [button.title = 'Refresh Tag Summary';] Use sentence case in UI 

Fixed.

> donateButton.innerHTML = Avoid using `innerHTML`

Bah! Sorry this slipped in :) Fixed.

> // Assuming this is the block quote color Comments in CSS are `/* text */`, everything else will cause parsing to fail.

Missed this as styles weren't from styles.css yet. But that's been fixed with this issue.

> export function debounce. This is already a function in the Obsidian API.

Fixed! Thanks for letting me know.

> navigator.platform.toUpperCase().indexOf('MAC'): Use `Platform.isMacOS` instead.

Fixed.

> export function htmlToMarkdown: This is also already a function in the API.

Good to know. Completely removed this as it was a previous approach. 

Thanks again,
David

**Comment by moremeyou** [comment]
@joethei Sorry for the countless reopens. I couldn't find a typo in the plugins list patch. I responded to your notes a few checks above.

**Comment by liamcain** [comment]
- [contextmenu](https://github.com/moremeyou/Obsidian-Tag-Buddy/blob/1dcbf6282fbb87fdf68461a4eb3d49ce8a0cd302/src/main.ts#L80) this is making a dangerous assumption that the contextmenu is inside the active view. That is not necessarily the case. It could be in a modal or another interactive element, such as statusbar or ribbon.
- ['click'](https://github.com/moremeyou/Obsidian-Tag-Buddy/blob/1dcbf6282fbb87fdf68461a4eb3d49ce8a0cd302/src/main.ts#L153) You should also make sure that the click event is within the active view

**Comment by moremeyou** [comment]
Hey @liamcain, thanks for the feedback. But I'm not sure I understand. For your first note, I thought I was checking if we're in the active preview.
For contextmenu, line 84:
if ... (view.getMode() == 'preview')

And for 'click', line 213, in the click handler:
if (view.getMode() != 'preview') return;

Sorry if I've misunderstood. If so, can you clarify?
David

**Comment by moremeyou** [comment]
@liamcain Thanks again for the assistance today. 
I've made the revisions where you mentioned and in one other area for mobile. And I've also now tested on android.
New release, 0.6.4.

**Pull request merged**
