### PR TITLE
Add plugin: VARE

### PR DESCRIPTION
**Pull request by 4Source**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/4Source/vare-obsidian-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
What sets your plugin apart from _BRAT_ or _Plugins Galore_

**Comment by 4Source** [comment]
Sure this is a good question. 
- In my opinion _BRAT_ isn't really user friendly, to test Beta versions you need to know the exact naming of the tag and it is not possible to edit existing entries. 
- _Plugins Galore_ I didn't know but I have take a look at it. This also don't have a good user Interface just let you add a plugin but don't allow to select the version to install. 

My plugin gives a overview of all installed plugins and the available versions for this plugin in a drop down to easily switch versions. And let also add unlisted plugins.  
image

**Comment by joethei** [comment]
["minAppVersion": "0.15.0",](https://github.com/4Source/vare-obsidian-plugin/blob/c107edab863f483b61df95d2c900c8906b263a0e/manifest.json#L4)
You are using newer API's than this, set this to the latest public build.

["description": "Now you can easily manage your plugins and themes inside Obsidian. Simply select the version you want to install or install unlisted ones from GitHub. Or if you want to test the new beta of your favorite plugin, simply select the version you want, install it and switch back if necessary.",](https://github.com/4Source/vare-obsidian-plugin/blob/c107edab863f483b61df95d2c900c8906b263a0e/manifest.json#L5)
This description is two long, it should be 250 characters maximum, and remove "Obsidian" from the description.

[// Heading for Profiles](https://github.com/4Source/vare-obsidian-plugin/blob/c107edab863f483b61df95d2c900c8906b263a0e/src/settings/SettingsTab.ts#L67-L70)
There should be no top level heading in settings.

[manifest.dir = plugin.id;](https://github.com/4Source/vare-obsidian-plugin/blob/c107edab863f483b61df95d2c900c8906b263a0e/src/settings/SettingsTab.ts#L195)
This should be `this.app.vault.configDir + '/plugins/' + plugin.id`

**Comment by 4Source** [comment]
> ["minAppVersion": "0.15.0",](https://github.com/4Source/vare-obsidian-plugin/blob/c107edab863f483b61df95d2c900c8906b263a0e/manifest.json#L4) You are using newer API's than this, set this to the latest public build.

Is there  a general guide for selecting correct version haven't seen any 

> [// Heading for Profiles](https://github.com/4Source/vare-obsidian-plugin/blob/c107edab863f483b61df95d2c900c8906b263a0e/src/settings/SettingsTab.ts#L67-L70) There should be no top level heading in settings.

Don't know how to do this while matching the obsidian design. Now it is like the "community plugins list" a Heading with some functions on the right side. If I remove the heading the buttons look out of place.

**Comment by joethei** [comment]
> Is there a general guide for selecting correct version haven't seen any
Just use the latest stable version.

You can ignore the headings change, I had another look at the code and it looks fine in this case.

**Comment by 4Source** [comment]
Ok, good, then I have addressed all the changes mentioned

**Comment by 4Source** [comment]
Or is something missing?

**Pull request merged**
