### PR TITLE
Arcana Plugin

### PR DESCRIPTION
**Pull request by A-F-V**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/A-F-V/obsidian-arcana

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by A-F-V** [comment]
Apologies for spam

**Comment by joethei** [comment]
[id: 'arcana-force-save',](https://github.com/A-F-V/obsidian-arcana/blob/e29e3f23465406d55e78e42ff97264018c390030/src/main.ts#L46)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

[arcana.app.workspace.on('active-leaf-change', async leaf => {](https://github.com/A-F-V/obsidian-arcana/blob/e29e3f23465406d55e78e42ff97264018c390030/src/plugins/SocratesExperiment/SocratesView.tsx#L111-L119)
You should register this listenter, so it gets unloaded properly, surround it with `arcana.registerEvent()`

**Comment by A-F-V** [comment]
Can I politely bump this :) @joethei @marcusolsson ? Many thanks (and sorry for being annoying ;) )

**Comment by marcusolsson** [comment]
[# Security Policy](https://github.com/A-F-V/obsidian-arcana/blob/b71ea913e5edd9e4398045914050e95e72056b22/SECURITY.md#L1)
Seems like the Security Policy was generated from a template and haven't been updated.

[containerEl.createEl('h2', { text: 'Arcana Settings' });](https://github.com/A-F-V/obsidian-arcana/blob/b71ea913e5edd9e4398045914050e95e72056b22/src/components/ArcanaSettingsTab.ts#L17)
Please update the settings according to the [UI guidelines](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#UI+text).

[.setName("Christie's System Message")](https://github.com/A-F-V/obsidian-arcana/blob/b71ea913e5edd9e4398045914050e95e72056b22/src/plugins/Christie/Christie.ts#L69)
https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI

**Comment by A-F-V** [comment]
@marcusolsson Thank you for feedback :) . I have acted upon it

**Comment by A-F-V** [comment]
🫶

**Pull request merged**
