### PR TITLE
Add plugin: Note Companion Folder

### PR DESCRIPTION
**Pull request by vkodocha**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/vkodocha/NoteCompanionFolder

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
What is the purpose for such a companion folder?
Please add some clarification into the readme.

["description": "A Obsidian Plugin providing a way to associate a folder to a note",](https://github.com/vkodocha/NoteCompanionFolder/blob/fd24b2636e0679861ba1cf1d4949571602fbdb19/manifest.json#L6)
Avoid including sentences like "This is a plugin for Obsidian that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[const LABEL = 'Reveal Companion Folder';](https://github.com/vkodocha/NoteCompanionFolder/blob/fd24b2636e0679861ba1cf1d4949571602fbdb19/src/main.ts#L5)

**Comment by vkodocha** [comment]
Thanks you for the feedback @joethei I have made the requested changes.

**Comment by joethei** [comment]
You missed this: [const LABEL = 'Reveal Companion Folder';](https://github.com/vkodocha/NoteCompanionFolder/blob/fd24b2636e0679861ba1cf1d4949571602fbdb19/src/main.ts#L5)

**Comment by vkodocha** [comment]
@joethei done - and sorry.

**Pull request merged**
