### PR TITLE
Add plugin: Fold Properties

### PR DESCRIPTION
**Pull request by itsonlyjames**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/itsonlyjames/obsidian-fold-properties

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "Adds Fold/Unfold Properties Function to Folder Context Menu",](https://github.com/itsonlyjames/obsidian-fold-properties/blob/35a90946973dee9d0e2e56c10d4caa856ff5550a/manifest.json#L6)
This should be using sentence case.

[item.setTitle('Fold Properties')](https://github.com/itsonlyjames/obsidian-fold-properties/blob/35a90946973dee9d0e2e56c10d4caa856ff5550a/main.ts#L21), [item.setTitle('Unfold Properties')](https://github.com/itsonlyjames/obsidian-fold-properties/blob/35a90946973dee9d0e2e56c10d4caa856ff5550a/main.ts#L29), [item.setTitle('Fold Properties')](https://github.com/itsonlyjames/obsidian-fold-properties/blob/35a90946973dee9d0e2e56c10d4caa856ff5550a/main.ts#L37), [item.setTitle('Unfold Properties')](https://github.com/itsonlyjames/obsidian-fold-properties/blob/35a90946973dee9d0e2e56c10d4caa856ff5550a/main.ts#L45)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by itsonlyjames** [comment]
@joethei updated

**Comment by itsonlyjames** [comment]
Fixed.

**Comment by joethei** [comment]
The manifest in your repo also needs to have the description updated.

**Comment by itsonlyjames** [comment]
Apologies.

Fixed.

**Pull request merged**
