### PR TITLE
Add Auto Classifier

### PR DESCRIPTION
**Pull request by HyeonseoNam**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/HyeonseoNam/auto-classifier

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by HyeonseoNam** [comment]
Thank you for reviewing! I replaced all

[replace to tab.setQuery](https://github.com/HyeonseoNam/auto-classifier/commit/5e4dc7181ada7a0fefa73dd2aac8aefe534aadee)

[avoid innerHtml](https://github.com/HyeonseoNam/auto-classifier/commit/310a038fb3d736add2f01e56010b4048b81b56a7)

[replace to requestUrl](https://github.com/HyeonseoNam/auto-classifier/commit/c30359fff31ff073c465e2115290e892f448dc8d)

**Comment by HyeonseoNam** [comment]
Hey @joethei @liamcain, 
Could you let me know if there is any additional feedback or anything else I can do to continue for the release?
Thank you for your time and reviewing 😃

**Comment by liamcain** [comment]
- [await](https://github.com/HyeonseoNam/auto-classifier/blob/c30359fff31ff073c465e2115290e892f448dc8d/src/main.ts#L25) nitpick: await isn't doing anything here so you can omit it. (same for the other commands)
- [Classify tag from Selected Area](https://github.com/HyeonseoNam/auto-classifier/blob/c30359fff31ff073c465e2115290e892f448dc8d/src/main.ts#L23) another nitpick but Obsidian command names are usually [Sentence case](https://en.wiktionary.org/wiki/sentence_case) to maximize readability.

**Comment by liamcain** [comment]
Thanks for your patience as we get around to catching up on plugin reviews. Excited to have this one included in the community plugin list!

**Pull request merged**
