### PR TITLE
Add plugin: Alias from heading

### PR DESCRIPTION
**Pull request by basham**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/basham/obsidian-alias-from-heading

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by basham** [comment]
@liamcain: Thanks for the review! I published [v1.0.8](https://github.com/basham/obsidian-alias-from-heading/releases/tag/1.0.8), and it is ready for you to review again. After some additional testing, I also fixed some bugs with how links are synchronized with headings. In doing so, I changed how the plugin is using `String.replace()`. Before this latest release, using `String.replaceAll()` would make more sense, as you suggested [1]. However, with the new changes, there is no longer an advantage in doing so. If curious, I added two comments ([first](https://github.com/basham/obsidian-alias-from-heading/blob/1.0.8/main.ts#L75-L81), [second](https://github.com/basham/obsidian-alias-from-heading/blob/1.0.8/main.ts#L94-L100)) that explains this new approach, as it is not obvious by reading the code. The [release notes](https://github.com/basham/obsidian-alias-from-heading/releases/tag/1.0.8) also provides a high-level description of the fixes.

[1]: The TypeScript compiler complained about using `String.replaceAll()` until I added `"ES2021"` to the `lib` compiler option in `tsconfig.json`. Perhaps the [Obsidian Sample Plugin](https://github.com/obsidianmd/obsidian-sample-plugin) should be similarly updated, if that configuration change is truly compatible.

**Comment by liamcain** [comment]
- [metadataCache.metadataCache[hash] = updatedCache;](https://github.com/basham/obsidian-alias-from-heading/blob/9aa954d6fe4b0c44c51b320631a96d5f9f82d83d/main.ts#L203-L204) So, I don't love that you're modifying the metadataCache, that's not meant to be modified, especially since the cache gets persisted in IndexDB, so it's not really a good place for ephemeral data. An alternative approach (it's not much better) would be to just monkey patch the `getLinkSuggestions` function  on the metadataCache. That way you only need to insert your aliases when the autocomplete popup is shown.

**Comment by basham** [comment]
I made updates according to your review, in [v1.0.12](https://github.com/basham/obsidian-alias-from-heading/releases/tag/1.0.12).

> Ideally you can just use registerEvent. If I had to guess, the issue might be because you're not calling super.unload()

It turns out, `Plugin.registerEvent()` does work as expected. I just needed to switch from `Plugin.unload()` to `Plugin.onunload()`.

> An alternative approach (it's not much better) would be to just monkey patch the getLinkSuggestions function on the metadataCache. That way you only need to insert your aliases when the autocomplete popup is shown.

That works out nicely! It cleans up a lot of the code. The patch is removed when the plugin unloads.

However, this change introduced one issue. `getLinkSuggestions()` does not affect the behavior of the [Quick Switcher](https://help.obsidian.md/Plugins/Quick+switcher). Do you have a recommendation about that? Is there a way to patch that core plugin, so these implicit heading aliases are included in that list of suggestions?

**Comment by basham** [comment]
I'm just surprised the Quick Switcher (being a core plugin) does not use `getLinkSuggestions()`. Is that a bug or something that should be fixed in that plugin?

**Comment by liamcain** [comment]
> I'm surprised the Quick Switcher (being a core plugin) does not use getLinkSuggestions(). Is that a bug or something that should be fixed in that plugin?

That's a good question, I'm not sure what the reason is. I'll make a note and see if we can use it.

Sorry for taking so long to get back to this. It got buried with some other pull requests and I lost track of it. The changes look great, very excited to see this plugin get included.

**Pull request merged**
