### PR TITLE
Add plugin: Tldraw

### PR DESCRIPTION
**Pull request by holxsam**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [https://github.com/holxsam/tldraw-in-obsidian/](https://github.com/holxsam/tldraw-in-obsidian/)

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by andradei** [comment]
Refers to request on: https://github.com/holxsam/tldraw-in-obsidian/issues/4

**Comment by joethei** [comment]
## required changes

[constructor(app: App, manifest: PluginManifest) {](https://github.com/holxsam/tldraw-in-obsidian/blob/60137bc28bb27b2b5182bc0f627abace83b75477/src/main.ts#L61-L63)
This is not necessary, remove it.

[name: "Toggle View Mode",](https://github.com/holxsam/tldraw-in-obsidian/blob/60137bc28bb27b2b5182bc0f627abace83b75477/src/main.ts#L241)
[.setPlaceholder("Time Format")](https://github.com/holxsam/tldraw-in-obsidian/blob/60137bc28bb27b2b5182bc0f627abace83b75477/src/obsidian/TldrawSettingsTab.ts#L124)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)



---
## suggestions/questions

[const folder = vault.getAbstractFileByPathInsensitive(folderpath);](https://github.com/holxsam/tldraw-in-obsidian/blob/60137bc28bb27b2b5182bc0f627abace83b75477/src/utils/utils.ts#L49)
Why are you using the case-insensitive version here?

[const timeFormatSetting = new Setting(containerEl)](https://github.com/holxsam/tldraw-in-obsidian/blob/60137bc28bb27b2b5182bc0f627abace83b75477/src/obsidian/TldrawSettingsTab.ts#L117-L140)
There is the MomentFormatComponent that can be used to show the current time in the specified format.
here is a sample: <https://github.com/joethei/obsidian-rss/blob/b600e2ead2505d58aa3e4c7898795bbf58fa3cdc/src/settings/FileCreationSettings.ts#L119C23-L139>

**Comment by 0xdevalias** [comment]
@holxsam Any chance of getting the changes needed for this PR finished? Would be great to see it in the community plugins!

**Comment by holxsam** [comment]
> @holxsam Any chance of getting the changes needed for this PR finished? Would be great to see it in the community plugins!

Yeah sorry I've been a bit busy, will knock out the changes this week forsure :)

**Comment by 0xdevalias** [comment]
> will knock out the changes this week forsure :)

@holxsam Awesome, appreciate it! :)

**Comment by holxsam** [comment]
Hey @joethei, I removed the unnecessary contructor call, adjusted all text to be sentence case, and applied your suggestion to use the built-in moment component. The manifest version and release is now updated to [1.0.5](https://github.com/holxsam/tldraw-in-obsidian/releases/tag/1.0.5).

> [const folder = vault.getAbstractFileByPathInsensitive(folderpath);](https://github.com/holxsam/tldraw-in-obsidian/blob/60137bc28bb27b2b5182bc0f627abace83b75477/src/utils/utils.ts#L49) Why are you using the case-insensitive version here?

I got that file utility function from the obsidian-excalidraw plugin where they had this issue: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/658

Let me know if there are anymore issues I need to fix.

**Comment by liamcain** [comment]
Sorry for the delay! The plugin looks great, glad to have this finally merged in.

**Pull request merged**
