### PR TITLE
Add plugin: Contextual note templating

### PR DESCRIPTION
**Pull request by Balibaloo**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Balibaloo/obsidian-local-template-configuration

## Release Checklist
- [X] I have tested the plugin on
  - [X]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [X]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [X] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

Notes:
The plugin is functional but I have struggled to conceptually define it.
I am open to renaming it.

Previous names include:
- local template configuration

### CODE REVIEW

**Comment by Balibaloo** [comment]
Fixed: Assigning element style, casting TAbstractFile, command in commandID

/Skip
Console Logs: The number of logs is large but they only log when the user is interacting with the plugin.
Any casting: This is used to access the APIs of other installed plugins

**Comment by Balibaloo** [comment]
Fixed: Assigning element style, casting TAbstractFile, command in commandID

/Skip
Console Logs: The number of logs is large but they only log when the user is interacting with the plugin.
Any casting: This is used to access the APIs of other installed plugins

**Comment by joethei** [comment]
Please take a look at the console logs flagged by the bot, and remove those that are not in an error state.

[const PLUGIN_LONG_NAME = "Contextual note templating";](https://github.com/Balibaloo/obsidian-local-template-configuration/blob/e91e84683f72a5a0808b0e45fb39f3f4457ecdbe/src/main.ts#L14)
This can be retrieved from `this.manifest.name` inside of the plugin class.

[const selectedNote = await (app as any).plugins.plugins["filtered-opener"].api_getNote(variable.note_filter_set_name);](https://github.com/Balibaloo/obsidian-local-template-configuration/blob/e91e84683f72a5a0808b0e45fb39f3f4457ecdbe/src/variables/providers/note.ts#L16), [const newProjectFolder = await (app as any).plugins.plugins["filtered-opener"].api_getFolder(variable.root_folder, variable.depth, variable.include_roots, variable.folder_filter_set_name);](https://github.com/Balibaloo/obsidian-local-template-configuration/blob/e91e84683f72a5a0808b0e45fb39f3f4457ecdbe/src/variables/providers/folder.ts#L24)
Add some validation and show a error when the other plugin is not installed/enabled.

[app.fileManager.processFrontMatter(note, async fm => {](https://github.com/Balibaloo/obsidian-local-template-configuration/blob/e91e84683f72a5a0808b0e45fb39f3f4457ecdbe/src/intents/frontmatter.ts#L81)
You are not writing to the frontmatter, use `app.metadataCache.getFileCache(file).frontmatter` instead.

[Please install the [Picker plugin](https://github.com/Balibaloo/obsidian-picker](https://github.com/Balibaloo/obsidian-local-template-configuration/blob/e91e84683f72a5a0808b0e45fb39f3f4457ecdbe/README.md#L41)
The plugin name is no longer correct.

**Comment by Balibaloo** [comment]
All fixed in [2.0.7](https://github.com/Balibaloo/obsidian-local-template-configuration/releases/tag/2.0.7).


> Please take a look at the console logs flagged by the bot, and remove those that are not in an error state.

I have disabled all non-error console logs. Are there any best practices for logging?

**Comment by Balibaloo** [comment]
@joethei Thank you for all your help!

**Pull request merged**
