### PR TITLE
Canvas Filter

### PR DESCRIPTION
**Pull request by IKoshelev**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/IKoshelev/Obsidian-Canvas-Filter

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by IKoshelev** [comment]
Is anything missing from this PR?

**Comment by joethei** [comment]
[interface CanvasFilterPluginSettings {](https://github.com/IKoshelev/Obsidian-Canvas-Filter/blob/d20d0d14146bac675d75b339365463e1e22f7306/main.ts#L5-L11)
[async loadSettings() {](https://github.com/IKoshelev/Obsidian-Canvas-Filter/blob/d20d0d14146bac675d75b339365463e1e22f7306/main.ts#L301-L307)
Since you don't use settings you can remove all references.

**Comment by IKoshelev** [comment]
@joethei done.

**Comment by liamcain** [comment]
- [show ALL](https://github.com/IKoshelev/Obsidian-Canvas-Filter/blob/2ef4df35602c4235bd6574d063b57f5ed1ca55f1/main.ts#L137) We recommend that all commands use [Sentence case](https://en.wiktionary.org/wiki/sentence_case) for their names. This maximizes readability in the command palette.
- [show matching COLOR](https://github.com/IKoshelev/Obsidian-Canvas-Filter/blob/2ef4df35602c4235bd6574d063b57f5ed1ca55f1/main.ts#L148) same goes for these

One idea for future improvement: you might want to add something to the screen to indicate that nodes are hidden.

**Comment by liamcain** [comment]
One more thing: you don't need to include a copy of the canvas types here: https://github.com/IKoshelev/Obsidian-Canvas-Filter/blob/2ef4df35602c4235bd6574d063b57f5ed1ca55f1/canvas.ts#L1.

You can already import the types from Obsidian like this:

```
import { CanvasLinkData } from 'obsidian/canvas';
```

**Comment by IKoshelev** [comment]
@liamcain Regarding "Sentence Case", from using the plugin for my own needs, I found it easier to have a single word per command be uppercase, so that my eye catches it when I'm selecting it. Do you think it would be ok to use some Unicode symbols with commands, like bellow? 

color 🌈
arrows in/out ⟶☐⟶
arrows in  ⟶☐
arrows out ☐⟶

Regarding indication on screen - I like the idea, but I'm wondering, how to have an indication that does not conflict with other plugin indications? Do you know of any prescribed mechanism to have something like this?

**Pull request merged**
