### PR TITLE
Add Omnivore plugin

### PR DESCRIPTION
**Pull request by sywhb**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/omnivore-app/obsidian-omnivore

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[// Remember to rename these classes and interfaces!](https://github.com/omnivore-app/obsidian-omnivore/blob/6579dbd8aaf47e3e769aa95759c433fdbca1f18a/src/main.ts#L24)
You can remove this.

[id: "omnivore-sync",](https://github.com/omnivore-app/obsidian-omnivore/blob/6579dbd8aaf47e3e769aa95759c433fdbca1f18a/src/main.ts#L105)
[id: "omnivore-resync",](https://github.com/omnivore-app/obsidian-omnivore/blob/6579dbd8aaf47e3e769aa95759c433fdbca1f18a/src/main.ts#L113)
You don't need to include `omnivore` in the command it, Obsidian will automatically prefix this with the plugin id for storage.

[!(await this.app.vault.adapter.exists(normalizePath(folderName)))](https://github.com/omnivore-app/obsidian-omnivore/blob/6579dbd8aaf47e3e769aa95759c433fdbca1f18a/src/main.ts#L205)
I would recommend checking the return value of `app.vault.getAbstractFileByPath` if it's `instanceof TFolder` instead.

[await this.app.vault.adapter.write(normalizePath(pageName), content);](https://github.com/omnivore-app/obsidian-omnivore/blob/6579dbd8aaf47e3e769aa95759c433fdbca1f18a/src/main.ts#L275)
[Prefer the Vault API](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#prefer-the-vault-api-over-the-adapter-api)

[(documentFragment.createDiv().innerHTML = html)](https://github.com/omnivore-app/obsidian-omnivore/blob/6579dbd8aaf47e3e769aa95759c433fdbca1f18a/src/main.ts#L322)
[Avoid using `innerHTML`]([(documentFragment.createDiv().innerHTML = html)](https://github.com/omnivore-app/obsidian-omnivore/blob/6579dbd8aaf47e3e769aa95759c433fdbca1f18a/src/main.ts#L322))


[console.log("apiKey: " + value);](https://github.com/omnivore-app/obsidian-omnivore/blob/6579dbd8aaf47e3e769aa95759c433fdbca1f18a/src/main.ts#L354)
[console.log("filter: " + value);](https://github.com/omnivore-app/obsidian-omnivore/blob/6579dbd8aaf47e3e769aa95759c433fdbca1f18a/src/main.ts#L368)
[console.log("query: " + value);](https://github.com/omnivore-app/obsidian-omnivore/blob/6579dbd8aaf47e3e769aa95759c433fdbca1f18a/src/main.ts#L388)
[console.log("syncAt: " + value);](https://github.com/omnivore-app/obsidian-omnivore/blob/6579dbd8aaf47e3e769aa95759c433fdbca1f18a/src/main.ts#L403)
[console.log("highlightOrder: " + value);](https://github.com/omnivore-app/obsidian-omnivore/blob/6579dbd8aaf47e3e769aa95759c433fdbca1f18a/src/main.ts#L417)
[console.log("template: " + value);](https://github.com/omnivore-app/obsidian-omnivore/blob/6579dbd8aaf47e3e769aa95759c433fdbca1f18a/src/main.ts#L435)
[console.log("endpoint: " + value);](https://github.com/omnivore-app/obsidian-omnivore/blob/6579dbd8aaf47e3e769aa95759c433fdbca1f18a/src/main.ts#L503)

[const res = await fetch(ENDPOINT, {](https://github.com/omnivore-app/obsidian-omnivore/blob/6579dbd8aaf47e3e769aa95759c433fdbca1f18a/src/util.ts#L97-L101)
I would recommend using the `requestUrl` function from the Obsidian API instead.
[const res = await fetch(endpoint, {](https://github.com/omnivore-app/obsidian-omnivore/blob/6579dbd8aaf47e3e769aa95759c433fdbca1f18a/src/util.ts#L117-L124)
[const res = await fetch(endpoint, {](https://github.com/omnivore-app/obsidian-omnivore/blob/6579dbd8aaf47e3e769aa95759c433fdbca1f18a/src/util.ts#L117-L124)

[class Suggest<T> {](https://github.com/omnivore-app/obsidian-omnivore/blob/6579dbd8aaf47e3e769aa95759c433fdbca1f18a/src/settings/suggest.ts)
[export class FileSuggest extends TextInputSuggest<TFile> {](https://github.com/omnivore-app/obsidian-omnivore/blob/6579dbd8aaf47e3e769aa95759c433fdbca1f18a/src/settings/file-suggest.ts)
Please credit the original source for these files, a short comment at the top is enough.

**Comment by sywhb** [comment]
Hey @joethei, thanks for the feedback ❤️ 

I have made changes to the code base on your feedback here: https://github.com/omnivore-app/obsidian-omnivore/commit/d987f21cd2dba39d5bf6cfe76b1a6258b471c415

Please let me know if there is further changes needed 👍

**Comment by liamcain** [comment]
- [} else {](https://github.com/omnivore-app/obsidian-omnivore/blob/e7f8fffec0998da91e8b4e086d0a2b44e8e2f372/src/main.ts#L274) It's also possible for TAbstractFile to be a TFolder, so this else case should probably be `else if (!omnivoreFile)` just to make sure it's a nonexistent file.

**Comment by sywhb** [comment]
Hey @liamcain, I have fixed the code here: https://github.com/omnivore-app/obsidian-omnivore/commit/b7768ffed335baec2eb841aeaffd283573a14c8d#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3dL274

I have also rebased this pull request on master. Kindly help me to merge. Thanks!

**Comment by sywhb** [comment]
Oh Just saw it was merged. 👍 @liamcain

**Pull request merged**
