### PR TITLE
Add 'Function Plot' (leonhma/obsidian-functionplot)

### PR DESCRIPTION
**Pull request by leonhma**
Render mathematical functions in a markdown codeblock.

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/leonhma/obsidian-functionplot

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by ericaxu** [comment]
Please add your plugin at the bottom instead of at the top, thanks!

**Comment by leonhma** [comment]
I changed the json file as you said. The plugin is now tested on Windows, Linux and Android. Not on apple devices, because I neither own any nor have access to them.

**Comment by leonhma** [comment]
Ready to be merged btw

**Comment by liamcain** [comment]
https://github.com/leonhma/obsidian-functionplot/blob/f2abd7d0525100d90857c858f14f0584f4d02af0/README.md?plain=1#L9 a small trick for avoiding needing the backslash to render the code fence in your readme:

You can use ~~~ as an alternative syntax:

~~~
```functionplot
Check it out
```
~~~

https://github.com/leonhma/obsidian-functionplot/blob/f2abd7d0525100d90857c858f14f0584f4d02af0/src/main.ts#L4 You can use the [`parseYaml`](https://github.com/obsidianmd/obsidian-api/blob/38bd84fd66b6bf59d2eab243f27e33d3031ca51c/obsidian.d.ts#L2323) function exported in the Obsidian API instead of bundling your own version of the yaml package.

https://github.com/leonhma/obsidian-functionplot/blob/f2abd7d0525100d90857c858f14f0584f4d02af0/src/main.ts#L39 You should change this to:
`config = Object.assign({}, config, parse(matches[0].substring(3, matches[0].length - 3)))`. As it stands now, you are mutating the DEFAULT_HEADER_OPTIONS object will cause bugs.

https://github.com/leonhma/obsidian-functionplot/blob/f2abd7d0525100d90857c858f14f0584f4d02af0/src/main.ts#L62 I recommend adding a `[functionplot]` as a prefix to this console.debug to make it easier to filter the console and make it easier for users and other plugin developers to decipher the logs.

**Comment by leonhma** [comment]
Made the changes and re-released.

**Comment by KingPsychopath** [comment]
Great add!

**Comment by liamcain** [comment]
You can remove `without the backslash)` from the readme now 😄 

> https://github.com/leonhma/obsidian-functionplot/blob/f2abd7d0525100d90857c858f14f0584f4d02af0/src/main.ts#L39 You should change this to:
config = Object.assign({}, config, parse(matches[0].substring(3, matches[0].length - 3))). As it stands now, you are mutating the DEFAULT_HEADER_OPTIONS object will cause bugs.

This is still an issue. Object.assign will mutate the left-most argument in the list. So [here](https://github.com/leonhma/obsidian-functionplot/blob/8b60ee207cbff6828aec60d1299f7a179f9598d9/src/main.ts#L33) you will actually be changing the default values.

**Comment by leonhma** [comment]
I just modified the readme. `Object.assign` will not modify it's arguments though, only carry over values from them, right?

**Comment by leonhma** [comment]
I just modified the readme. ~~`Object.assign` will not modify it's arguments though, only carry over values from them, right?~~ oh yeah I'll fix it

**Comment by leonhma** [comment]
Fixed and published now.

**Pull request merged**
