### PR TITLE
Add Image Window plugin

### PR DESCRIPTION
**Pull request by valentine195**
# I am submitting a new Community Plugin

This is a simple plugin that adds the ability to open image files in the vault in a new Obsidian BrowserWindow instance.

## Repo URL

Link to my plugin: https://github.com/valentine195/obsidian-image-window

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/valentine195/obsidian-image-window/blob/3a33dd64873230ab23ec9ff661d4c21972a2d2d7/src/main.ts#L65
You can use `getResourcePath` instead which will give you an `app://local` path on desktop, which resolves to the file:/// path without requiring you to disable webSecurity on the BrowserWindow.

**Comment by lishid** [comment]
You are also running the risk of HTML DOM injection by using an un-sanitized input string, should consider HTML encode the result of the link.

**Comment by valentine195** [comment]
> https://github.com/valentine195/obsidian-image-window/blob/3a33dd64873230ab23ec9ff661d4c21972a2d2d7/src/main.ts#L65 You can use `getResourcePath` instead which will give you an `app://local` path on desktop, which resolves to the file:/// path without requiring you to disable webSecurity on the BrowserWindow.

Thanks, changed. Didn't like disabling the webSecurity, glad there's a workaround :)

> You are also running the risk of HTML DOM injection by using an un-sanitized input string, should consider HTML encode the result of the link.

I added in the DOMPurify santizer (based on a comment you made in the Discord a few weeks ago). Does this work for you?

https://github.com/valentine195/obsidian-image-window/blob/49bfc08e55938b97e5e908903e7cd10bda1aeb38/src/main.ts#L120

**Comment by lishid** [comment]
We do expose the DOM sanitizer in the plugin API now, but I think it's overkill - you only have a single path to protect and it's probably fine to just escape entities (`&<>"`)

**Pull request merged**
