### PR TITLE
add obsidian-structured-plugin

### PR DESCRIPTION
**Pull request by dobrovolsky**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/dobrovolsky/obsidain-structure

## Release Checklist

- [x] I have tested this on Linux
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/dobrovolsky/obsidain-structure/blob/71c8d8f3e1d2206fda76ff8c53369583df8e9061/src/helpers/noteOpener.ts#L8

There's a few things in your plugin that could benefit from [this tip](https://github.com/dobrovolsky/obsidain-structure/blob/71c8d8f3e1d2206fda76ff8c53369583df8e9061/src/helpers/noteOpener.ts#L8).

https://github.com/dobrovolsky/obsidain-structure/blob/71c8d8f3e1d2206fda76ff8c53369583df8e9061/src/helpers/noteCreator.ts#L19
Here you can probably use `cachedRead` for a slight performance boost.

https://github.com/dobrovolsky/obsidain-structure/blob/71c8d8f3e1d2206fda76ff8c53369583df8e9061/src/helpers/noteCreator.ts#L3
See [this tip](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#nodejs-and-electron-api)
(For path resolution in Obsidian, you can use `/` to join the strings and then `normalizePath` from Obsidian to normalize it into a path that Obsidian internally uses.

https://github.com/dobrovolsky/obsidain-structure/blob/71c8d8f3e1d2206fda76ff8c53369583df8e9061/src/helpers/noteFinder.ts#L36
There's a `getMarkdownFiles()` on Vault which does just this.

https://github.com/dobrovolsky/obsidain-structure/blob/71c8d8f3e1d2206fda76ff8c53369583df8e9061/src/helpers/noteFinder.ts#L26
Maybe `startsWith` is a better test?

**Comment by dobrovolsky** [comment]
@lishid thank you for your feedback. I'll check it more deeply. :+1: 

> There's a few things in your plugin that could benefit from this tip.

Could you update link for first tip. It's copy-pasted incorrectly.

**Comment by lishid** [comment]
Apologies I did paste the wrong link. Here it is again: https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#avoid-accessing-workspaceactiveleaf-directly

**Comment by dobrovolsky** [comment]
All changes you suggested are applied https://github.com/dobrovolsky/obsidain-structure/commit/2c11f569c1179bbc954c7bb7f4888122fd91692b

**Pull request merged**
