### PR TITLE
Submit "Chesser" plugin

### PR DESCRIPTION
**Pull request by SilentVoid13**
A chess game viewer/editor.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/SilentVoid13/Chesser/blob/173d7c1f3b9eb07462bf1b56bbd15748d55321cb/src/ChesserSettings.ts#L90

Maybe a toggle here would be better than a dropdown with true or false?

**Comment by SilentVoid13** [comment]
@lishid Very true, I don't know why I did that. Thanks for the review. Fixed now

**Comment by lishid** [comment]
Ok, rebase your PR and I'll have it merged 👍

**Comment by SilentVoid13** [comment]
Done !

**Pull request merged**
