### PR TITLE
Add tab autocomplete community plugin

### PR DESCRIPTION
**Pull request by Geigerkind**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Geigerkind/tab-autocomplete/tree/main

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [X]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[async function wait(timeInMs: number) {](https://github.com/Geigerkind/tab-autocomplete/blob/a83cec2dba02c7447d9a7382eebf43997c8c5885/main.ts#L3-L5)
There is already the `sleep` function in the Obsidian API.

[const innerHTML = selectedSuggestions[0].children[0].children[0].innerHTML](https://github.com/Geigerkind/tab-autocomplete/blob/a83cec2dba02c7447d9a7382eebf43997c8c5885/main.ts#L29-L30)
[Avoid using `innerHTML`](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%60innerHTML%60%2C+%60outerHTML%60+and+%60insertAdjacentHTML%60)

**Comment by Geigerkind** [comment]
@joethei Fixed review comments. Going to rebase now.

**Comment by joethei** [comment]
@Geigerkind please fix the validation errors.

**Comment by liamcain** [comment]
- [selectedSuggestions[0].children[0].children[0].innerText](https://github.com/Geigerkind/tab-autocomplete/blob/ffb9f85eb6b551a94ea1d5f38d861255cd5762a5/main.ts#L25) this is not safe to assume the dom structure like this. It's very likely that this will error out.
- [DOMNodeInserted](https://github.com/Geigerkind/tab-autocomplete/blob/ffb9f85eb6b551a94ea1d5f38d861255cd5762a5/main.ts#L75) this will be very expensive. At the very least you should debounce these event handlers. I'm also not sure why you are doing these checks inside DOMNodeInserted. Why not just check the state _after_ you've detected a Tab keyup event? That seems a lot safer and performant, then you can just check if the activeElement is a modal input element.

**Pull request closed without merging**
