### PR TITLE
Add new RSS feed reader plugin

### PR DESCRIPTION
**Pull request by fjdu**
A new Obsidian plugin added: obsidian-feeds-reader, for reading RSS feeds within Obsidian.

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/fjdu/obsidian-feed

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
I generally recommend moving all code files into a separate `src` folder, that makes it easier to review and maintain.

[// Perform additional things with the ribbon](https://github.com/fjdu/obsidian-feed/blob/ceaae588a4a70d85baecccdfbbbcc9dc5abf2a17/main.ts#L59-L60)
Remove this.

[document.getElementById('naviBar').style.display = 'none';](https://github.com/fjdu/obsidian-feed/blob/ceaae588a4a70d85baecccdfbbbcc9dc5abf2a17/main.ts#L295-L298)
You should avoid assigning styles via JavaScript and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets


[function sanitize(s: string) {](https://github.com/fjdu/obsidian-feed/blob/ceaae588a4a70d85baecccdfbbbcc9dc5abf2a17/main.ts#L1095-L1109)
There is the `sanitizeToDom` function in the Obsidian API for this.

[export namespace Global {](https://github.com/fjdu/obsidian-feed/blob/ceaae588a4a70d85baecccdfbbbcc9dc5abf2a17/globals.ts#L1)

[td {](https://github.com/fjdu/obsidian-feed/blob/ceaae588a4a70d85baecccdfbbbcc9dc5abf2a17/styles.css#L8-L10)
[input[type=text] {](https://github.com/fjdu/obsidian-feed/blob/ceaae588a4a70d85baecccdfbbbcc9dc5abf2a17/styles.css#L198-L200)
Don't overwrite core Obsidian styling.

**Comment by ericaxu** [comment]
Hi there, to keep things tidy, we're going to temporarily close plugin PRs after a month of inactivity.

Feel free to tell us to re-open it when you're ready to continue. Thanks for your understanding!

**Comment by fjdu** [comment]
Hi,

I updated my plugin (https://github.com/fjdu/obsidian-feed); code now moved
to src/ directory.

If possible, could you reopen the pull request?

Thanks!

Fujun Du

**Comment by joethei** [comment]
I recommend you change all instances of `var` to either `const` or `let`. `var` has function-level scope, so it can easily lead to bugs if you're not careful. Here's a pretty good guide with examples of why not to use `var`: [why `var` is obsolete](https://javascript.plainenglish.io/4-reasons-why-var-is-considered-obsolete-in-modern-javascript-a30296b5f08f)

[[export namespace Global {](https://github.com/fjdu/obsidian-feed/blob/ceaae588a4a70d85baecccdfbbbcc9dc5abf2a17/globals.ts#L1)](https://github.com/fjdu/obsidian-feed/blob/ceaae588a4a70d85baecccdfbbbcc9dc5abf2a17/globals.ts#L1)
You should not use global variables whenever possible, read here why: http://wiki.c2.com/?GlobalVariablesAreBad

**Comment by joethei** [comment]
Hi @fjdu,

Do you still intend on submitting this plugin?

**Comment by fjdu** [comment]
Hi,

I just submitted a new release to the community plugin list.

Actually my plugin is based on the one written by Johannes Theiner.  I have
been wondering why Johannes stopped developing it?

Best regards!
Fujun Du

**Comment by joethei** [comment]
There are still way too many global variables in your code, I would prefer it if there would be none at all.

If you have not noticed it, I am the developer of that other RSS reader plugin.
The reason why I did release any updates recently is because I now have a job and not as much time as I used to.
I am still working on a big update to the plugin, but as time is limited it will take a while to be released.

**Comment by fjdu** [comment]
Yes, I know you are the original developer of that plugin!

I understand that there are still too many global variables in my code.  I
will try to remove them.

In the meantime I hope to see your update on your original RSS plugin,
because obviously you are far more of a professional programmer than I am
in JS/TypeScript (and the CSS stuff).

One aspect I like regarding the plugin I wrote is the "fine-grained"
storage of feed data.  I implement this to minimize the data flow for cloud
syncing.  But the approach I took is kind of "crude", hope you will have a
better way to do that.

When the feed data accumulates to a large size, I will also need to
consider how to limit the memory usage.

Another limitation imposed by the mobile version of Obsidian is that iframe
cannot be used for many websites.

**Comment by ericaxu** [comment]
Hi there, to keep things tidy, we're going to temporarily close plugin PRs after a month of inactivity.

Feel free to tell us to re-open it when you're ready to continue. Thanks for your understanding!

**Pull request closed without merging**
