### PR TITLE
Add plugin: Quiz Generator

### PR DESCRIPTION
**Pull request by ECuiDev**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/ECuiDev/obsidian-quiz-generator

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[containerEl.createEl("h3", {text: `${("Generation")}`});](https://github.com/ECuiDev/obsidian-quiz-generator/blob/be9420fc1e42ee3d927ed7a1a6ada66eb01cf374/src/settings.ts#L67), [containerEl.createEl("h3", {text: `${("Saving")}`});](https://github.com/ECuiDev/obsidian-quiz-generator/blob/be9420fc1e42ee3d927ed7a1a6ada66eb01cf374/src/settings.ts#L150)
For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```

**Comment by ECuiDev** [comment]
Fixed!

**Comment by liamcain** [comment]
- [minAppVersion": "0.15.0",](https://github.com/ECuiDev/obsidian-quiz-generator/blob/2269a59bdf1b8bcabe8c4ddf8e57640a7d627678/manifest.json#L5) since you are using the newer APIs, this should be "1.5.0"

**Comment by ECuiDev** [comment]
Fixed!

**Pull request merged**
