### PR TITLE
Add plugin: NodeFlow

### PR DESCRIPTION
**Pull request by LincZero**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/LincZero/obsidian-node-flow

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["repo": "https://github.com/LincZero/obsidian-node-flow",](https://github.com/LincZero/obsidian-node-flow/blob/260b5cb826619a0b2a5b4fbab7ae0018fce58f7a/manifest.json#L9)
Not a thing in the manifest, remove it.

[interface NodeFlowPluginSettings {](https://github.com/LincZero/obsidian-node-flow/blob/260b5cb826619a0b2a5b4fbab7ae0018fce58f7a/src/main.ts#L9-L15), [await this.loadSettings();](https://github.com/LincZero/obsidian-node-flow/blob/260b5cb826619a0b2a5b4fbab7ae0018fce58f7a/src/main.ts#L21), [async loadSettings() {](https://github.com/LincZero/obsidian-node-flow/blob/260b5cb826619a0b2a5b4fbab7ae0018fce58f7a/src/main.ts#L97-L103)
Your plugin does not have settings, so remove the code that would handle them

[const div_leaf: HTMLElement = this.app.workspace.activeLeaf.containerEl](https://github.com/LincZero/obsidian-node-flow/blob/260b5cb826619a0b2a5b4fbab7ae0018fce58f7a/src/main.ts#L53)
`activeLeaf` is deprecated and should not be used.

[return "dice";](https://github.com/LincZero/obsidian-node-flow/blob/260b5cb826619a0b2a5b4fbab7ae0018fce58f7a/src/NodeFlowView.ts#L20)
Use a different icon: https://docs.obsidian.md/Plugins/User+interface/Icons

[<button class="nf-btn-fullScreen" @click="fn_fullScreen()">fullScreen</button>](https://github.com/LincZero/obsidian-node-flow/blob/260b5cb826619a0b2a5b4fbab7ae0018fce58f7a/src/NodeFlow/component/NodeFlowContainerS.vue#L10-L17), [nodesDraggable](https://github.com/LincZero/obsidian-node-flow/blob/260b5cb826619a0b2a5b4fbab7ae0018fce58f7a/src/NodeFlow/component/utils/InteractionControls.vue#L11), [nodesConnectable](https://github.com/LincZero/obsidian-node-flow/blob/260b5cb826619a0b2a5b4fbab7ae0018fce58f7a/src/NodeFlow/component/utils/InteractionControls.vue#L17), [elementsSelectable](https://github.com/LincZero/obsidian-node-flow/blob/260b5cb826619a0b2a5b4fbab7ae0018fce58f7a/src/NodeFlow/component/utils/InteractionControls.vue#L23), [zoomOnScroll](https://github.com/LincZero/obsidian-node-flow/blob/260b5cb826619a0b2a5b4fbab7ae0018fce58f7a/src/NodeFlow/component/utils/InteractionControls.vue#L29), [zoomOnPinch](https://github.com/LincZero/obsidian-node-flow/blob/260b5cb826619a0b2a5b4fbab7ae0018fce58f7a/src/NodeFlow/component/utils/InteractionControls.vue#L35), [panOnScroll](https://github.com/LincZero/obsidian-node-flow/blob/260b5cb826619a0b2a5b4fbab7ae0018fce58f7a/src/NodeFlow/component/utils/InteractionControls.vue#L41), [panOnScrollMode](https://github.com/LincZero/obsidian-node-flow/blob/260b5cb826619a0b2a5b4fbab7ae0018fce58f7a/src/NodeFlow/component/utils/InteractionControls.vue#L47), [zoomOnDoubleClick](https://github.com/LincZero/obsidian-node-flow/blob/260b5cb826619a0b2a5b4fbab7ae0018fce58f7a/src/NodeFlow/component/utils/InteractionControls.vue#L57), [paneMovable](https://github.com/LincZero/obsidian-node-flow/blob/260b5cb826619a0b2a5b4fbab7ae0018fce58f7a/src/NodeFlow/component/utils/InteractionControls.vue#L63), [capture onPaneClick](https://github.com/LincZero/obsidian-node-flow/blob/260b5cb826619a0b2a5b4fbab7ae0018fce58f7a/src/NodeFlow/component/utils/InteractionControls.vue#L69), [capture onPaneScroll](https://github.com/LincZero/obsidian-node-flow/blob/260b5cb826619a0b2a5b4fbab7ae0018fce58f7a/src/NodeFlow/component/utils/InteractionControls.vue#L75), [zoom in](https://github.com/LincZero/obsidian-node-flow/blob/260b5cb826619a0b2a5b4fbab7ae0018fce58f7a/src/NodeFlow/component/utils/InteractionControls.vue#L81), [zoom out](https://github.com/LincZero/obsidian-node-flow/blob/260b5cb826619a0b2a5b4fbab7ae0018fce58f7a/src/NodeFlow/component/utils/InteractionControls.vue#L87)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[console.log('info: 已复制文本');](https://github.com/LincZero/obsidian-node-flow/blob/260b5cb826619a0b2a5b4fbab7ae0018fce58f7a/src/NodeFlow/component/NodeFlowContainerS.vue#L76), [onNodeDragStart((e) => console.log('drag start', e))](https://github.com/LincZero/obsidian-node-flow/blob/260b5cb826619a0b2a5b4fbab7ae0018fce58f7a/src/NodeFlow/component/utils/InteractionControls.vue#L133-L134),

**Comment by LincZero** [comment]
I've already changed the first four points. Do I have to change the fifth? Even though I know browsers are case insensitive, it doesn't seem to matter much.

**Comment by LincZero** [comment]
Is it in the state of waiting for re-manual review? Still need to close before open comment?

**Comment by LincZero** [comment]
It's been five weeks. When will it be ready

**Comment by joethei** [comment]
Please change all UI strings to use sentence case.

**Comment by LincZero** [comment]
Can we ignore this question? 

I didn't write some of the components, and if I change them I can't update them from upstream.

**Comment by LincZero** [comment]
Done.

**Comment by joethei** [comment]
[# Obsidian NodeFlow](https://github.com/LincZero/obsidian-node-flow/blob/0b5308a7196a421ecae00377a5226f4d90173f14/README.md?plain=1#L1)
Naming something "Obsidian xyz" is reserved for first party products we create, please change this header.

**Comment by LincZero** [comment]
Done

**Pull request merged**
