### PR TITLE
Add 🪝 Grappling Hook Plugin to Community Store

### PR DESCRIPTION
**Pull request by chrisgrieser**
# I am submitting a new Community Plugin
The plugin is basically an implementation of vim's alternate buffer (`:buffer #`) as well as a simplified implementation of the [Harpoon plugin for neovim](https://github.com/ThePrimeagen/harpoon).

## Repo URL

Link to my plugin: https://github.com/chrisgrieser/grappling-hook

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[const recentFiles = this.app.workspace.lastOpenFiles;](https://github.com/chrisgrieser/grappling-hook/blob/fef9d47304f608cf7855fee6edca0348e79fd8dd/main.ts#L102)
Use `app.workspace.getLastOpenFiles()` instead.

**Comment by chrisgrieser** [comment]
> [const recentFiles = this.app.workspace.lastOpenFiles;](https://github.com/chrisgrieser/grappling-hook/blob/fef9d47304f608cf7855fee6edca0348e79fd8dd/main.ts#L102)
> Use `app.workspace.getLastOpenFiles()` instead.

done 👍

**Comment by liamcain** [comment]
- [grapplingHookPlugin](https://github.com/chrisgrieser/grappling-hook/blob/92d79b26269b45cdec828f5c264422dd731eca05/main.ts#L28) nit: capitalize your class name :)
- [getLeaf](https://github.com/chrisgrieser/grappling-hook/blob/92d79b26269b45cdec828f5c264422dd731eca05/main.ts#L64) I wouldn't call this helper function "activeLeaf". Get Leaf doesn't always return the active leaf. For example, if the current leaf is pinned, it will create a new leaf. The usage seems fine, I'm just worried about the terms getting conflated.
- [let nextIndex = currentIndex + 1;](https://github.com/chrisgrieser/grappling-hook/blob/92d79b26269b45cdec828f5c264422dd731eca05/main.ts#L91) a trick you could do here is let nextIndex = (currentIndex + 1) % filePathArray.length;
- [pathToTFile](https://github.com/chrisgrieser/grappling-hook/blob/92d79b26269b45cdec828f5c264422dd731eca05/main.ts#L66) I recommend always returning a value from a function instead of relying on the function exiting and returning undefined. It makes it easier to infer the return type of the function. So add `return null` at the end here.
- [nextFile](https://github.com/chrisgrieser/grappling-hook/blob/92d79b26269b45cdec828f5c264422dd731eca05/main.ts#L164) nextFile can be undefined.

**Comment by chrisgrieser** [comment]
Thanks for the thorough review! Being a hobby coder, it's super valuable to get feedback on code I wrote 😊 

All implemented in latest commit (except `nextFile`, since the earlier guard clauses on starred files should already prevent `nextFile` ever returning undefined)

**Pull request merged**
