### PR TITLE
Added theme Aurora

### PR DESCRIPTION
**Pull request by TriDiamond**
# [x] I am submitting a new Community Theme

## Repo URL

https://github.com/auroral-ui/aurora-obsidian-md

# [ ] I am submitting a new Community Plugin

## Release Checklist

- [ ] I have tested this on Windows, macOS, and Linux _(if applicable)_
- [ ] Github release contains all required files
  - [ ] `main.js`
  - [ ] `manifest.json`
  - `styles.css` _(optional)_
- [ ] Github release name matches the exact version number specified in your manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [ ] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [ ] README clearly describes the plugins purpose and provides clear usage instructions.

### CODE REVIEW

**Comment by ericaxu** [comment]
Hmm, looks like there are some conflicts. Do you think you can resolve them?

**Comment by TriDiamond** [comment]
> Hmm, looks like there are some conflicts. Do you think you can resolve them?

Is it due to the repo I have is too old? I probably should re-fork the repo and edit from there.

**Comment by ericaxu** [comment]
I think I got this, thanks! @TriDiamond

**Comment by TriDiamond** [comment]
> I think I got this, thanks! @TriDiamond

Awesome, thanks! :) @ericaxu

**Pull request merged**
