### PR TITLE
Add plugin: Goban SGF

### PR DESCRIPTION
**Pull request by StinsonZhao**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:  https://github.com/StinsonZhao/obsidian-plugin-goban-sgf

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[Copyright (c) 2015-2020 Yichuan Shen](https://github.com/StinsonZhao/obsidian-plugin-goban-sgf/blob/71a54ef7c714a7172cd7064480c9e99103cf920d/LICENSE.md#L3)
Update this.

["description": "Obsidian plugin for recording Go games (SGF format goban).",](https://github.com/StinsonZhao/obsidian-plugin-goban-sgf/blob/71a54ef7c714a7172cd7064480c9e99103cf920d/manifest.json#L6)
Avoid including sentences like "This is a plugin for Obsidian that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[id: 'Create New Goban',](https://github.com/StinsonZhao/obsidian-plugin-goban-sgf/blob/71a54ef7c714a7172cd7064480c9e99103cf920d/src/main.ts#L254), [id: 'Toggle to Markdown or Goban',](https://github.com/StinsonZhao/obsidian-plugin-goban-sgf/blob/71a54ef7c714a7172cd7064480c9e99103cf920d/src/main.ts#L262)
ID's should use kebab-case.

[async saveFile() {](https://github.com/StinsonZhao/obsidian-plugin-goban-sgf/blob/71a54ef7c714a7172cd7064480c9e99103cf920d/src/GobanController.ts#L140-L151)
Frontmatter manipulation should be done with the `processFrontmatter` function.

[CREATE_NEW: "New Goban File",](https://github.com/StinsonZhao/obsidian-plugin-goban-sgf/blob/71a54ef7c714a7172cd7064480c9e99103cf920d/src/lang/locales/en.ts#L2), [FOLDER: "Goban Folder",](https://github.com/StinsonZhao/obsidian-plugin-goban-sgf/blob/71a54ef7c714a7172cd7064480c9e99103cf920d/src/lang/locales/en.ts#L5), [GAME_INFO: "Game Info",](https://github.com/StinsonZhao/obsidian-plugin-goban-sgf/blob/71a54ef7c714a7172cd7064480c9e99103cf920d/src/lang/locales/en.ts#L15), [GAME_NAME: "Game Name",](https://github.com/StinsonZhao/obsidian-plugin-goban-sgf/blob/71a54ef7c714a7172cd7064480c9e99103cf920d/src/lang/locales/en.ts#L21-L22) and more.
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by StinsonZhao** [comment]
> [Copyright (c) 2015-2020 Yichuan Shen](https://github.com/StinsonZhao/obsidian-plugin-goban-sgf/blob/71a54ef7c714a7172cd7064480c9e99103cf920d/LICENSE.md#L3) Update this.
> 
> ["description": "Obsidian plugin for recording Go games (SGF format goban).",](https://github.com/StinsonZhao/obsidian-plugin-goban-sgf/blob/71a54ef7c714a7172cd7064480c9e99103cf920d/manifest.json#L6) Avoid including sentences like "This is a plugin for Obsidian that does ..." in your description, it should be self-evident that this is a plugin for Obsidian. We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
> 
> [id: 'Create New Goban',](https://github.com/StinsonZhao/obsidian-plugin-goban-sgf/blob/71a54ef7c714a7172cd7064480c9e99103cf920d/src/main.ts#L254), [id: 'Toggle to Markdown or Goban',](https://github.com/StinsonZhao/obsidian-plugin-goban-sgf/blob/71a54ef7c714a7172cd7064480c9e99103cf920d/src/main.ts#L262) ID's should use kebab-case.
> 
> [async saveFile() {](https://github.com/StinsonZhao/obsidian-plugin-goban-sgf/blob/71a54ef7c714a7172cd7064480c9e99103cf920d/src/GobanController.ts#L140-L151) Frontmatter manipulation should be done with the `processFrontmatter` function.
> 
> [CREATE_NEW: "New Goban File",](https://github.com/StinsonZhao/obsidian-plugin-goban-sgf/blob/71a54ef7c714a7172cd7064480c9e99103cf920d/src/lang/locales/en.ts#L2), [FOLDER: "Goban Folder",](https://github.com/StinsonZhao/obsidian-plugin-goban-sgf/blob/71a54ef7c714a7172cd7064480c9e99103cf920d/src/lang/locales/en.ts#L5), [GAME_INFO: "Game Info",](https://github.com/StinsonZhao/obsidian-plugin-goban-sgf/blob/71a54ef7c714a7172cd7064480c9e99103cf920d/src/lang/locales/en.ts#L15), [GAME_NAME: "Game Name",](https://github.com/StinsonZhao/obsidian-plugin-goban-sgf/blob/71a54ef7c714a7172cd7064480c9e99103cf920d/src/lang/locales/en.ts#L21-L22) and more. [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

@joethei 

Thank you for the thorough review. I have made all the necessary changes except for the following:  

> [async saveFile() {](https://github.com/StinsonZhao/obsidian-plugin-goban-sgf/blob/71a54ef7c714a7172cd7064480c9e99103cf920d/src/GobanController.ts#L140-L151) Frontmatter manipulation should be done with the `processFrontmatter` function.

This requires me to maintain frontmatter using `processFrontmatter`, but I am using `app.vault.modify` to save the whole file,  which saves changes made to the whole content, including frontmatter. What is the correct way to use this method? 

- First modify the frontmatter using `processFrontmatter`, then stringify the frontmatter along with the file content, and finally call `app.vault.modify` to save?
- Or use `app.vault.modify` to save and then call `processFrontmatter` to modify the frontmatter?
- Or is there any other way that allows me to save the frontmatter and the body at once, and also easily parse out the frontmatter **object** and body from an md file. If not, I think the current processing logic is the most intuitive and logical for me.

**Comment by liamcain** [comment]
- `registerMonkeyAround` mind explaining why you need the monkey patch here? Is there an Obsidian bug you're working around?
- [if (!leaf) {](https://github.com/StinsonZhao/obsidian-plugin-goban-sgf/blob/91bdb234673a0b6ccae27a9e3a0d3bd4aaf8a5ff/src/main.ts#L128) hmm. getLeaf will never return null, this code path should never run

**Comment by StinsonZhao** [comment]
> * `registerMonkeyAround` mind explaining why you need the monkey patch here? Is there an Obsidian bug you're working around?
> * [if (!leaf) {](https://github.com/StinsonZhao/obsidian-plugin-goban-sgf/blob/91bdb234673a0b6ccae27a9e3a0d3bd4aaf8a5ff/src/main.ts#L128) hmm. getLeaf will never return null, this code path should never run

First, I am saving the content of the files in markdown format (which is the content in SGF format), and then using the fields in the frontmatter to indicate that it should be opened by this plugin in a specific view, namely the Goban form, instead of the MD text form.  Therefore, I use `registerMonkeyAround` to ensure that when users open such markdown files, they are using the view registered by this plugin, rather than the regular markdown view.

**Pull request merged**
