### PR TITLE
Add plugin: Storyclock Viewer

### PR DESCRIPTION
**Pull request by jonzfisher**
### Repo URL
Link to my plugin:
https://github.com/jonzfisher/obsidian-chronostory

### Description

The Storyclock is based off of a visual of a time-dependent story where you can fill in gaps in a story or notice symmetries in a story. It is inspired by the Storyclock notebook by [Plot Devices](https://plotdevices.co/). Learn more about the Storyclock Process in this [video](https://www.youtube.com/watch?v=D9viuUvC4f0).

Switch between the codeblock and this interactive React clock viewer

image

(example original codeblock)
```storyclock
runtime::02:10:00
00:05:00 Borden watches Angier's performance, sparking rivalry.
00:10:00 Julia's tragic death during a water tank escape act.
00:20:00 Borden introduces the Transported Man trick.
00:25:00 Angier's obsession grows as he tries to decode Borden’s trick.
00:30:00 Angier travels to Colorado Springs seeking Tesla.
00:35:00 Tesla agrees to build a machine for Angier.
00:45:00 Angier tests the Tesla machine, creating duplicates.
00:55:00 Borden's life unravels due to his secret and obsession.
01:00:00 Angier's New Transported Man debuts to acclaim.
01:05:00 Borden is framed for Angier's 'murder'.
01:10:00 Borden is sentenced to death, losing everything.
01:25:00 Angier lives a double life, just like Borden did.
01:30:00 Borden discovers Angier's secret and plots revenge.
01:40:00 Fallon, Borden's twin, takes their daughter Jess to see Angier.
01:45:00 Cutter deduces Angier’s use of doubles. 
01:50:00 Angier refuses to acknowledge the cost of his obsession.
01:55:00 Fallon sabotages Angier's final performance.
02:00:00 Angier confronts Borden, revealing his duplicity.
02:05:00 Angier dies, his duplicity and obsession coming full-circle.
02:10:00 Borden reunites with Jess, starting anew.
```
I have tested the plugin on

* [x]   Windows
  * [x]   macOS
  * [ ]   Linux
  * [ ]   Android _(if applicable)_
  * [x]   iOS _(if applicable)_
* [x]  My GitHub release contains all required files
   * [x]  `main.js`
   * [x]  `manifest.json`
   * [x]  `styles.css` _(optional)_
* [x]  GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version umber, don't include a prefix `v`_)
* [x]  The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
* [x]  My README.md describes the plugin's purpose and provides clear usage instructions.
* [x]  I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
* [x]  I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
* [x]  I have added a license in the LICENSE file.
* [x]  My project respects and is compatible with the original license of any code from other plugins that I'm using.
   I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[## Releasing new releases](https://github.com/jonzfisher/obsidian-chronostory/blob/6c34bc720ae646a47d12c174a8ea562c054be22d/README.md#L25-L84)
Remove all this from your readme, it's not relevant to the end user.

**Comment by jonzfisher** [comment]
> [## Releasing new releases](https://github.com/jonzfisher/obsidian-chronostory/blob/6c34bc720ae646a47d12c174a8ea562c054be22d/README.md#L25-L84) Remove all this from your readme, it's not relevant to the end user.

The README has been updated to remove the boilerplate ✅

**Comment by jonzfisher** [comment]
Hey @liamcain, thanks for reviewing and merging my plugin! It looks like the following merge overwrote the addition of my plugin in commit https://github.com/obsidianmd/obsidian-releases/commit/3033376a01a00b140c631c2d7a304fc2c205e66d

**Comment by liamcain** [comment]
Oh no! sorry about that. A bad merge on my part. Will fix!

**Comment by liamcain** [comment]
Okay, I readded your plugin in this commit: https://github.com/obsidianmd/obsidian-releases/commit/538024bcbc1c291606371ccce677f20dfce6d47d thanks so much for catching!

**Pull request merged**
