### PR TITLE
Update community-plugins.json to add Invio

### PR DESCRIPTION
**Pull request by walkthunder**
Add Obsidian plugin - Invio
Help user's to sync their docs to COS

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/frontend-engineering/Invio

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by walkthunder** [comment]
All Fixed:
* https://github.com/frontend-engineering/Invio/commit/bbe510b248da4b8ecdbda4263f4cebbc197f2bca
* https://github.com/frontend-engineering/Invio/commit/c29f15a12d3eccfd0e95b54d06bb6baf64f9cd71

---
> ["description": "Invio is a plugin for Obsidian which lets you export docs as HTML websites](https://github.com/frontend-engineering/Invio/blob/f9fbe92479143c391d354e670bb8667a70997582/manifest.json#L6) We have recently published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple. Avoid including sentences like "This is a plugin for Obsidian" in your description.
> 
> [const k = path.posix.normalize(item); // TODO: only unix path now](https://github.com/frontend-engineering/Invio/blob/f9fbe92479143c391d354e670bb8667a70997582/src/misc.ts#L39) You can use the `normalizePath` function from the Obsidian API here, will work across operating systems.
> 
> [const rsp2 = JSON.parse(rsp1);](https://github.com/frontend-engineering/Invio/blob/f9fbe92479143c391d354e670bb8667a70997582/src/remoteForOnedrive.ts#L170) You can also do:
> 
> ```ts
> const response = await requestUrl({...});
> response.json();
> ```
> 
> [const wrapTextWithPasswordHide = (text: TextComponent) => {](https://github.com/frontend-engineering/Invio/blob/f9fbe92479143c391d354e670bb8667a70997582/src/settings.ts#L345-L355) Obsidian already includes lucide icons, you can simpify this code to:
> 
> ```ts
> const wrapTextWithPasswordHide = (text: TextComponent) => {
> 	const hider = text.inputEl.insertAdjacentElement("afterend", createSpan());
> 	hider.setIcon("eye-off");
> 	hider.addEventListener("click", (e) => {
> 	const isText = text.inputEl.getAttribute("type") === "text";
> 	if(isText) {
> 		hider.setIcon("eye-off");
> 		text.inputEl.setAttribute("type", "password");
> 	} else {
> 		hider.setIcon("eye");
> 		text.inputEl.setAttribute("type", "text");
> 	}
>   });
> ```
> 
> You should also [avoid using `innerHTML`](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%60innerHTML%60%2C+%60outerHTML%60+and+%60insertAdjacentHTML%60)
> 
> [header.style.display = 'block';](https://github.com/frontend-engineering/Invio/blob/f9fbe92479143c391d354e670bb8667a70997582/src/settings.ts#L412-L413) You should avoid assigning styles via JavaScript or in HTML and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets.
> 
> [const sleep = (time: number) => {](https://github.com/frontend-engineering/Invio/blob/f9fbe92479143c391d354e670bb8667a70997582/src/utils.ts#L15-L22) Obsidian already includes a function that works the same way.
> 
> [static async delay (ms: number)](https://github.com/frontend-engineering/Invio/blob/f9fbe92479143c391d354e670bb8667a70997582/src/utils/utils.ts#L13-L16) This function does the same thing as the one flagged above.
> 
> Sidenote, you have code for webdav, dropbox and onedrive, but it's not documented anywhere, it also looks like it's not used.

**Comment by joethei** [comment]
1. [AssetHandler.mathStyles.replaceAll("app://obsidian.md/", "https://publish.obsidian.md/").trim();](https://github.com/frontend-engineering/Invio/blob/41df5d05e36ae3fb09b592a28602cfbc96516302/src/html-generation/asset-handler.ts#L148)
2. [cssText = cssText.replaceAll("public/", "https://publish.obsidian.md/public/");](https://github.com/frontend-engineering/Invio/blob/41df5d05e36ae3fb09b592a28602cfbc96516302/src/html-generation/asset-handler.ts#L194-L195)
3. [@font-face](https://github.com/frontend-engineering/Invio/blob/41df5d05e36ae3fb09b592a28602cfbc96516302/assets/obsidian-styles.txt.css#L30-L262)

Don't use resources hosted on Obsidian Publish.

**Comment by walkthunder** [comment]
Thanks @joethei  

Done

[fix-commit](https://github.com/frontend-engineering/Invio/commit/abfd54575e9119f86d3cb951d305f8985a60f38a)

-------

> 1. [AssetHandler.mathStyles.replaceAll("app://obsidian.md/", "https://publish.obsidian.md/").trim();](https://github.com/frontend-engineering/Invio/blob/41df5d05e36ae3fb09b592a28602cfbc96516302/src/html-generation/asset-handler.ts#L148)
> 2. [cssText = cssText.replaceAll("public/", "https://publish.obsidian.md/public/");](https://github.com/frontend-engineering/Invio/blob/41df5d05e36ae3fb09b592a28602cfbc96516302/src/html-generation/asset-handler.ts#L194-L195)
> 3. [@font-face](https://github.com/frontend-engineering/Invio/blob/41df5d05e36ae3fb09b592a28602cfbc96516302/assets/obsidian-styles.txt.css#L30-L262)
> 
> Don't use resources hosted on Obsidian Publish.

**Comment by walkthunder** [comment]
How's it going? Are there any new issues? @joethei

**Comment by walkthunder** [comment]
This plugin has been undergoing review for more than a month. Essentially, it combines the 'Remotely Save Plugin' and 'Obsidian Enhancing Export Plugin', both of which have already been published in the Community Plugins list. I am unsure why the review has been taking such a long time and been reassigned to different reviewers multiple times.

I would appreciate **any feedback** regarding the delays and long review time, in order to help improve the review process going forward.

By the way, I am an active and enthusiastic Obsidian user myself. I truly appreciate and value the fantastic tools that Obsidian provides. This is the first plugin I have created and contributed to the community. I hope this plugin can assist other users, like myself, in keeping all of their data stored in Amazon S3, although only a small percentage of users likely share my habit of storing data there.

**Comment by ericaxu** [comment]
> This plugin has been undergoing review for more than a month. Essentially, it combines the 'Remotely Save Plugin' and 'Obsidian Enhancing Export Plugin', both of which have already been published in the Community Plugins list. I am unsure why the review has been taking such a long time and been reassigned to different reviewers multiple times.
> 
> I would appreciate **any feedback** regarding the delays and long review time, in order to help improve the review process going forward.
> 
> By the way, I am an active and enthusiastic Obsidian user myself. I truly appreciate and value the fantastic tools that Obsidian provides. This is the first plugin I have created and contributed to the community. I hope this plugin can assist other users, like myself, in keeping all of their data stored in Amazon S3, although only a small percentage of users likely share my habit of storing data there.

Hi, thanks for your message!

The main reason of the long delay is that our core team was very busy working on the properties feature. The standard process is to have joethei review it, once it passes it will be assigned to liam for a second pass. I don't believe it has anything to do with the nature of your plugin.

If you check out the other PRs you will see similar timelines. We just recently reduced the queue size from almost 120 to 90, but it's still a lot of work for our small team. I understand your eagerness to get your plugin added to the store, and your frustration with the long process. Just hope you can keep in mind that everyone involved in this code review process has plenty of other work on their plates and might not get back to you as quickly as you want, but joethei and liam are still doing this to help make every plugin in our store better.

Hope it gets reviewed soon! 🙌

**Comment by liamcain** [comment]
- [catch (error)](https://github.com/frontend-engineering/Invio/blob/ab637dd94060656cb87ceee42e4ae09ca00ee50a/src/utils/tab-manager.ts#L23) try catch here is redundant since you're already catching the errors via the chained .catch()
- [app](https://github.com/frontend-engineering/Invio/blob/ab637dd94060656cb87ceee42e4ae09ca00ee50a/src/utils/tab-manager.ts#L8) we discourage use of the global app instance in your plugin. It's currently accessible from the global context for debugging purposes, and might be removed in the future. Instead, you should use the reference to App that you have from your plugin instance. With that said, I'm not sure I understand why you have this wrapping function at all...

**Pull request merged**
