### PR TITLE
Add plugin: Emoji Autocomplete

### PR DESCRIPTION
**Pull request by KraXen72**
Please review my plugin Emoji Autocomplete

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/KraXen72/obsidian-emoji-autocomplete

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[Copyright (c) 2021 Phillip](https://github.com/KraXen72/obsidian-emoji-autocomplete/blob/5604599e20566f3b707def619d330ad36da535da/LICENSE#L3)
Update this, and don't forget to keep a reference to the original author.

[src: url('https://esm.sh/country-flag-emoji-polyfill@0.1.4/dist/TwemojiCountryFlags.woff2') format('woff2');](https://github.com/KraXen72/obsidian-emoji-autocomplete/blob/5604599e20566f3b707def619d330ad36da535da/styles.css#L6)
This should not be requested via the network, but bundled instead, also see: <https://docs.obsidian.md/Themes/App+themes/Embed+fonts+and+images+in+your+theme>

[shortcodeDiv.innerHTML = slimHighlight(suggestion.matchedName, suggestion.range)](https://github.com/KraXen72/obsidian-emoji-autocomplete/blob/5604599e20566f3b707def619d330ad36da535da/src/main.ts#L246), [if (suggestion.isInHistory && this.plugin.settings.considerHistory) shortcodeDiv.createDiv().outerHTML = iconHistory;](https://github.com/KraXen72/obsidian-emoji-autocomplete/blob/5604599e20566f3b707def619d330ad36da535da/src/main.ts#L250), [shortcodeDiv.createDiv({ cls: 'EA-tag-shortcode' }).innerHTML = `${iconChevronsRight} <span class="EA-tag-sc">${suggestion.names[0]}</span>`](https://github.com/KraXen72/obsidian-emoji-autocomplete/blob/5604599e20566f3b707def619d330ad36da535da/src/main.ts#L253), [shortcodeDiv.createDiv().outerHTML = iconTags;](https://github.com/KraXen72/obsidian-emoji-autocomplete/blob/5604599e20566f3b707def619d330ad36da535da/src/main.ts#L255)
[Avoid using `innerHTML` and `outerHTML`](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%60innerHTML%60%2C+%60outerHTML%60+and+%60insertAdjacentHTML%60)

[containerEl.createEl('h2', { text: 'Emoji Autocomplete Plugin' });](https://github.com/KraXen72/obsidian-emoji-autocomplete/blob/5604599e20566f3b707def619d330ad36da535da/src/settings.ts#L49)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[containerEl.createEl('h2', { text: 'Suggestions' });](https://github.com/KraXen72/obsidian-emoji-autocomplete/blob/5604599e20566f3b707def619d330ad36da535da/src/settings.ts#L50)
The first section should not have a heading.

[containerEl.createEl('h2', { text: 'Supported emoji' });](https://github.com/KraXen72/obsidian-emoji-autocomplete/blob/5604599e20566f3b707def619d330ad36da535da/src/settings.ts#L141)
For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```

**Comment by KraXen72** [comment]
okay, i'll make the requested changes. how should i go about updating the copyright? 

like 'Copyright (c) 2023 KraXen72, Phillip and contributors' ?

thanks.

**Comment by KraXen72** [comment]
i implemented requested changes

**Comment by KraXen72** [comment]
i adressed all the requested changes, please take a look @joethei

**Pull request merged**
