### PR TITLE
Add plugin: Daily Note Navbar

### PR DESCRIPTION
**Pull request by karstenpedersen**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/karstenpedersen/obsidian-daily-note-navbar

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "Adds a daily note navbar to quickly navigate between sequential daily notes",](https://github.com/karstenpedersen/obsidian-daily-note-navbar/blob/0da4ff296810ecf75b50d5fc8691311b4cdcae37/manifest.json#L6)
Descriptions often start with an action statement, something like "Navigate between sequential daily notes easily"
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

**Comment by karstenpedersen** [comment]
I have added a new description:

Description: Navigate between sequential daily notes with ease.

**Comment by joethei** [comment]
@karstenpedersen 
You have not made the description change in your manifest, please do so.

**Comment by karstenpedersen** [comment]
> @karstenpedersen You have not made the description change in your manifest, please do so.

I have updated the manifest.json in the [0.1.0 release](https://github.com/karstenpedersen/obsidian-daily-note-navbar/releases/tag/0.1.0) of the plugin.

**Pull request merged**
