### PR TITLE
Add Advanced Paste Plugin

### PR DESCRIPTION
**Pull request by kxxt**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/kxxt/obsidian-advanced-paste

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by kxxt** [comment]
Hi, what other things do I need to do to get this PR merged? It has been almost two week.

**Comment by joethei** [comment]
We review submissions in submission order.
We are currently busy working on the app itself, sorry for the delay.

I would generally recommend moving all code files into a separate `src` folder, that makes it easier to review and maintain.

[id: `advpaste-${transformId}`,](https://github.com/kxxt/obsidian-advanced-paste/blob/e1cb7c8a98e18c9e01ae1f951e6a714b8c88b453/main.ts#L58)
Obsidian will automatically prefix the command id with the plugin id, you don't need to do it yourself.

[`advpaste-custom-${prop}`,](https://github.com/kxxt/obsidian-advanced-paste/blob/e1cb7c8a98e18c9e01ae1f951e6a714b8c88b453/main.ts#L100)
You are also duplicating it here, your commands would now be named `advpaste-advpaste-custom-xyz`.

[const { adapter } = this.app.vault;](https://github.com/kxxt/obsidian-advanced-paste/blob/e1cb7c8a98e18c9e01ae1f951e6a714b8c88b453/main.ts#L71-L77)
I would generally [prefer the Vault API over the Adapter API](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#prefer-the-vault-api-over-the-adapter-api)

**Comment by kxxt** [comment]
> I would generally recommend moving all code files into a separate `src` folder, that makes it easier to review and maintain.

Done.

> [id: `advpaste-${transformId}`,](https://github.com/kxxt/obsidian-advanced-paste/blob/e1cb7c8a98e18c9e01ae1f951e6a714b8c88b453/main.ts#L58) Obsidian will automatically prefix the command id with the plugin id, you don't need to do it yourself.
> 
> [`advpaste-custom-${prop}`,](https://github.com/kxxt/obsidian-advanced-paste/blob/e1cb7c8a98e18c9e01ae1f951e6a714b8c88b453/main.ts#L100) You are also duplicating it here, your commands would now be named `advpaste-advpaste-custom-xyz`.

Fixed.

> [const { adapter } = this.app.vault;](https://github.com/kxxt/obsidian-advanced-paste/blob/e1cb7c8a98e18c9e01ae1f951e6a714b8c88b453/main.ts#L71-L77) I would generally [prefer the Vault API over the Adapter API](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#prefer-the-vault-api-over-the-adapter-api)

I have some doubts about the vault API. I didn't find a way to list the contents of a specific folder with the vault API. To use the vault API, I need to call `getFiles` and iterating through all the files to find the  contents of a specific folder. So I used the adapter API instead.

**Comment by liamcain** [comment]
> To use the vault API, I need to call getFiles and iterating through all the files to find the contents of a specific folder

No need to do that. You would get a folder with [`getAbstractFileByPath`](https://github.com/obsidianmd/obsidian-api/blob/902badd38ba907689f0917d7b193f7e33d1284fe/obsidian.d.ts#L3612), then confirm its instanceof TFolder, then recurse through it by looking at folder.children.

**Pull request merged**
