### PR TITLE
Add ob keywords plugin

### PR DESCRIPTION
**Pull request by tcper**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [ ] `main.js`
  - [ ] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [ ] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [ ] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [ ] My README.md describes the plugin's purpose and provides clear usage instructions.
- [ ] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [ ] I have added a license in the LICENSE file.
- [ ] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Please fill the pull request template.

**Comment by joethei** [comment]
You did not follow the PR template, I've updated your initial message here, please fill it.

**Comment by ericaxu** [comment]
@tcper Could you fill the PR template?

**Comment by liamcain** [comment]
- [insertText](https://github.com/tcper/ob-keywords/blob/533ee4d0c9b559a8aa610a0f4e77c3e7526cd5d3/src/index.ts#L48) there's no reason for this to be in the ViewCreator. I suggest moving this code directly into the KeywordView class
- [markdownView](https://github.com/tcper/ob-keywords/blob/533ee4d0c9b559a8aa610a0f4e77c3e7526cd5d3/src/index.ts#L53) you are not handling the case where the active file isn't a markdown view. This could be null.
- [markdownView.editor](https://github.com/tcper/ob-keywords/blob/533ee4d0c9b559a8aa610a0f4e77c3e7526cd5d3/src/index.ts#L56) you are better off using [`activeEditor`](https://github.com/obsidianmd/obsidian-api/blob/38dd22168d2925086371bfc59e36fd9121527a39/obsidian.d.ts#L4009)
- [keywordView](https://github.com/tcper/ob-keywords/blob/533ee4d0c9b559a8aa610a0f4e77c3e7526cd5d3/src/index.ts#L24) this should be Sentence case since it's displayed to the user in the tooltip when they hover over the tab.
- [reactComponent](https://github.com/tcper/ob-keywords/blob/533ee4d0c9b559a8aa610a0f4e77c3e7526cd5d3/src/index.ts#L12) You need to make sure to unmount your react component when the view closes. Otherwise this will be a memory leak. React components don't automatically clean themselves up.
- [ob_keyowrd_key](https://github.com/tcper/ob-keywords/blob/533ee4d0c9b559a8aa610a0f4e77c3e7526cd5d3/src/ui/KeywordView.tsx#L3) you should use loadData/saveData from the API instead of storing things in local storage. Localstorage will not sync between devices meaning users won't be able to share their settings between their multiple devices.

**Pull request closed without merging**
