### PR TITLE
Add Ultra Lobster Theme

### PR DESCRIPTION
**Pull request by 7368697661**
# I am submitting a new Community Theme
## Repo URL
Link to my theme: <https://github.com/7368697661/Ultra-Lobster>

## Theme checklist

- [x] My repo contains all required files (please do not add them to this obsidian-releases repo).
	- [x] obsidian.css
- [x] The screenshot file.
- [x] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other themes that I'm using.
- [x] I have given proper attribution to these other themes in my README.md.
- [x] If my repo is not using the master branch, please indicate in community-themes.json with "branch": "main".

Please switch to **Preview** and select one of the following links:

* [Community Plugin](?template=plugin.md)
* [Community Theme](?template=theme.md)

### CODE REVIEW

**Comment by 7368697661** [comment]
This might be a bad question, but is it too late to change the name of my theme?

**Comment by ericaxu** [comment]
> This might be a bad question, but is it too late to change the name of my theme?

Nope, feel free to push a commit to update it! You can even change it after you submit it. It's all up to you!

**Comment by ericaxu** [comment]
Great theme btw! Let me know when it's ready to be merged.

**Comment by 7368697661** [comment]
> Contributor

Ah! Sorry, I never got a notification for some reason, even with the ping 😅 Ty so much! That would be awesome! I think the theme should be more or less ready for merge; would I need to make a new request to change the name in the community themes file?

**Comment by 7368697661** [comment]
Ok I think I did that right 😅 Please let me know if that works now, @ericaxu !

**Comment by ericaxu** [comment]
Thank you so much! <3

**Pull request merged**
