### PR TITLE
Add Simple theme

### PR DESCRIPTION
**Pull request by diegoeis**
The Simple is a theme for Obsidian that prioritizes reading and writing.

It has minimal customizations and a simple design to avoid distractions and noise while taking notes and writing long-form texts.

### CODE REVIEW

**Comment by joethei** [comment]
[@import url('https://fonts.googleapis.com/css2?family=Inter:wght@100;300;400;600;700;800&display=swap');](https://github.com/diegoeis/simple-obsidian/blob/5003f050d93da951c6733b8dfcac9a7727d786ce/theme.css#L85-L86)
Themes aren't allowed to include external resources, see how to embed them properly here: <https://docs.obsidian.md/Themes/App+themes/Embed+fonts+and+images+in+your+theme>

**Comment by diegoeis** [comment]
> [@import url('https://fonts.googleapis.com/css2?family=Inter:wght@100;300;400;600;700;800&display=swap');](https://github.com/diegoeis/simple-obsidian/blob/5003f050d93da951c6733b8dfcac9a7727d786ce/theme.css#L85-L86) Themes aren't allowed to include external resources, see how to embed them properly here: https://docs.obsidian.md/Themes/App+themes/Embed+fonts+and+images+in+your+theme

Done... The external resources was removed. Thanks for the docs reference.

**Comment by ericaxu** [comment]
> @joethei anything is all right? There's anything else that I need to do?

Not joethei but please double check your changes to `community-css-themes.json`. Seems like you removed another theme? Was it from a bad marge or a bad conflict resolution?

**Comment by diegoeis** [comment]
@ericaxu this was a bad conflict... that theme was not there before my Pull Request.

I will get the latest `community-css-themes.json` and make another version

**Comment by diegoeis** [comment]
@ericaxu can you check now?

**Comment by joethei** [comment]
That looks good, thanks

**Pull request merged**
