### PR TITLE
Add Tidy Footnotes

### PR DESCRIPTION
**Pull request by charliecm**
# I am submitting a new Community Plugin

## Repo URL

https://github.com/charliecm/obsidian-tidy-footnotes

## Release Checklist

- [x] I have tested this on Windows and macOS
- [x] Github release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
- [x] Github release name matches the exact version number specified in your manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.

### CODE REVIEW

**Comment by lishid** [comment]
Looks like you're using CodeMirror 5's API, which means your plugin can only run on desktop. As such, you should mark your plugin as `isDesktopOnly: true` https://github.com/charliecm/obsidian-tidy-footnotes/blob/df7a3d432b739b64e6a1575c94c78c95bc32b661/manifest.json#L9

**Comment by charliecm** [comment]
@lishid Thanks for reviewing. I'm using CodeMirror for [tests only](https://github.com/charliecm/obsidian-tidy-footnotes/blob/main/src/tidyFootnotes.test.ts), so it's not included in `main.js` (in run-time, it's using Obsidian's global `CodeMirror` instance). Would you recommend a different approach in using the API for testing without needing to set `isDesktopOnly` to true?

**Comment by lishid** [comment]
https://github.com/charliecm/obsidian-tidy-footnotes/blob/df7a3d432b739b64e6a1575c94c78c95bc32b661/src/main.ts#L14
Here you are using `sourceMode.cmEditor` which is CodeMirror 5. You are also using it here: https://github.com/charliecm/obsidian-tidy-footnotes/blob/df7a3d432b739b64e6a1575c94c78c95bc32b661/src/tidyFootnotes.ts#L41

If you are able to use our Editor interface, which bridges CM5 and CM6 functions together, your plugin will work on mobile as well: https://github.com/obsidianmd/obsidian-api/blob/068ff3052f0641baff90856dcb420dc2721680c9/obsidian.d.ts#L682
To start, you'll need to use `MarkdownView.editor` instead of `MarkdownView.sourceMode.cmEditor`.

**Comment by charliecm** [comment]
I'll certainly try to use the new Editor interface when it's ready. Is there an API in Obsidian for getting the indentation of a line? I'm currently using CodeMirror's `StringStream.indentation()`. Otherwise, I may need to know the user's tab preference to check for indents reliably.

**Comment by lishid** [comment]
Pretty sure you can just use a regex to find indentations; you aren't even using the number, just testing that it's larger than 0.

**Comment by charliecm** [comment]
Thanks for the suggestion. I'm using the [regex](https://github.com/charliecm/obsidian-tidy-footnotes/blob/a0dc20aa6bd351f540f401b0d66aed70f955a5dc/src/tidyFootnotes.ts#L41) so the code no longer references CodeMirror. Also, changed `isDesktopOnly` to `true` for now. Will change it to `false` once it's been tested on mobile and is using the Editor API.

**Comment by lishid** [comment]
Cool - the Editor API is just a bridge to CodeMirror 5 on desktop, so you can just swap to use it right away since all the functions you're currently using are already supported (they end up calling cmEditor anyway). Let me know if you want the plugin merged now or after you make the change.

**Comment by charliecm** [comment]
Ah, I thought API v0.12.0 is mapped to the latest Obsidian stable build. I've updated the code to use the Editor API, so it's ready to go 👍

**Pull request merged**
