### PR TITLE
AI Images

### PR DESCRIPTION
**Pull request by microtower00**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/microtower00/obsidian-ai-images/

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by liamcain** [comment]
- [modifiers: ['Mod', 'Shift'],](https://github.com/microtower00/obsidian-ai-images/blob/bd18dd5d840b1ba5cc0f09a00cc58b060fd69b58/src/main.ts#L22-L24) While there's no hard rule against it, we recommend against providing a default hotkey when possible. The reason being that it's easy to pick a hotkey that a user already has configured and they could get confused when that key doesn't do what they expect. Also, it's hard choosing a safe default hotkey that's available for all operating systems.
- [registerDomEvent(document, 'click'](https://github.com/microtower00/obsidian-ai-images/blob/bd18dd5d840b1ba5cc0f09a00cc58b060fd69b58/src/main.ts#L42) this is just meant as example code. You should remove this
- [window.setInterval](https://github.com/microtower00/obsidian-ai-images/blob/bd18dd5d840b1ba5cc0f09a00cc58b060fd69b58/src/main.ts#L46) remove this
- [as unknown as string](https://github.com/microtower00/obsidian-ai-images/blob/bd18dd5d840b1ba5cc0f09a00cc58b060fd69b58/src/main.ts#L73) I suggest explicitly casting to a string instead of using `as` here. `String(Date.now())` should work.

**Comment by joethei** [comment]
Hi @microtower00 do you still intend on submitting this plugin?

**Comment by microtower00** [comment]
Hello, yes but I totally missed the previous email! I'm sorry for the wait.
I will fix it.

Il giorno ven 10 mar 2023 alle ore 10:12 Johannes Theiner <
***@***.***> ha scritto:

**Comment by ericaxu** [comment]
Hi @microtower00 , do you still intend to submit this plugin?

**Comment by ericaxu** [comment]
Hi there, to keep things tidy, we're going to temporarily close plugin PRs after a month of inactivity.

Feel free to tell us to re-open it when you're ready to continue. Thanks for your understanding!

**Pull request closed without merging**
