### PR TITLE
Add Shiba Uni's theme

### PR DESCRIPTION
**Pull request by faroukx**
Hello, I would like to **add a theme** that I personally designed and wanted to **share with the community** because folks were interested. I hope it will be approved.

My biggest greeting.

---
Link to my theme: https://github.com/faroukx/Obsidian-shiba-uni-theme
Screenshot: https://github.com/faroukx/Obsidian-shiba-uni-theme/blob/main/img/Shiba-Uni-Background.jpg

### CODE REVIEW

**Comment by ericaxu** [comment]
Thanks for submitting your theme!

I would strongly recommend using a real screenshot. You can add the Shiba to the screenshot if you want!

Another minor thing: you might want to make the screenshot smaller while keeping the 16:9 aspect ratio. That would make your theme load faster in the theme store. You can still include high resolution screenshots in your README.

We recommend using a screenshot of size 512px by 288px as the featured screenshot to minimize loading time.

**Comment by faroukx** [comment]
Hi, sure.

**screenshot 19:6 with 512x288px : https://github.com/faroukx/Obsidian-shiba-uni-theme/blob/main/img/512x288.png**
screenshot 19:6 with 1920x1080px : https://github.com/faroukx/Obsidian-shiba-uni-theme/blob/main/img/HD.png

and I have a question, can I style the screenshot a bit like this one for example: https://user-images.githubusercontent.com/109313204/210191460-d6272079-931d-4f02-8498-9feadb2794dd.png

**Comment by ericaxu** [comment]
> Hi, sure.
> 
> **screenshot 19:6 with 512x288px : https://github.com/faroukx/Obsidian-shiba-uni-theme/blob/main/img/512x288.png** screenshot 19:6 with 1920x1080px : https://github.com/faroukx/Obsidian-shiba-uni-theme/blob/main/img/HD.png


Thank you! Please update the link in the pull request accordingly so the app knows which screenshot to use.

> and I have a question, can I style the screenshot a bit like this one for example: https://user-images.githubusercontent.com/109313204/210191460-d6272079-931d-4f02-8498-9feadb2794dd.png

Yes you can!

**Comment by faroukx** [comment]
Done.

> Yes you can!
Thank you very much!

**Comment by faroukx** [comment]
Hi, I want to change the name from shiba Uni to Shiba Inu please. Including the image name.

```
    {
        "name": "Shiba Inu",
        "author": "Farouk",
        "repo": "faroukx/Obsidian-shiba-inu-theme",
        "screenshot": "shibainubackgroundshowcase.png",
        "modes": ["dark", "light"]
    },
```

**Comment by faroukx** [comment]
```
{
        "name": "Shiba Inu",
        "author": "Farouk",
        "repo": "faroukx/Obsidian-shiba-uni-theme",
        "screenshot": "shibainubackgroundshowcase.png",
        "modes": ["dark", "light"]
    },
```

To keep the id.

**Pull request merged**
