### PR TITLE
Add plugin: File Flex

### PR DESCRIPTION
**Pull request by 19msb**
This pull request adds the File Flex plugin, which provides customisable undo functionality for file and folder movements and renames within Obsidian. Users can easily revert changes to their vault structure with a single click and/or hotkey.

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/19msb/obsidian-file-flex

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by 19msb** [comment]
Hi @joethei 
Should I move main.js to .gitignore? 
I am confused by the instructions to do so that were followed by them seeming to be revoked.

**Comment by joethei** [comment]
The main.js should be removed from the repo and added to the gitignore, not sure why the bot always ignores that.

**Comment by joethei** [comment]
Where is the actual source code?
Or did you put all of the code into the `main.js`?
In that case the bot should not have flagged it at all, as the code should be in the repo.

**Comment by 19msb** [comment]
> Where is the actual source code? Or did you put all of the code into the `main.js`? In that case the bot should not have flagged it at all, as the code should be in the repo.

Haha, yes. All of the code is in the main.js. 

I've added it back to the repo.

**Comment by joethei** [comment]
[console.log(`Tracked operation: ${changeType} - ${file.path} from ${oldPath}`);](https://github.com/19msb/obsidian-file-flex/blob/38dae823b8964cda70c1dfbaf93f907a5940c256/main.js#L63), [console.log(`Successfully moved ${fileOp.newPath} to ${fileOp.oldPath}`);](https://github.com/19msb/obsidian-file-flex/blob/38dae823b8964cda70c1dfbaf93f907a5940c256/main.js#L83)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[const koFiButton = containerEl.createEl('a', { href: 'https://ko-fi.com/I2I2ZHYPA', target: '_blank' });](https://github.com/19msb/obsidian-file-flex/blob/38dae823b8964cda70c1dfbaf93f907a5940c256/main.js#L127-L131)
This should be at the end, not at the top.

[koFiButton.innerHTML = "Buy Me a Coffee at ko-fi.com";](https://github.com/19msb/obsidian-file-flex/blob/38dae823b8964cda70c1dfbaf93f907a5940c256/main.js#L128)
[Avoid using `innerHTML`](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%60innerHTML%60%2C+%60outerHTML%60+and+%60insertAdjacentHTML%60)

[const title = containerEl.createEl('h1', { text: 'File Flex Settings' });](https://github.com/19msb/obsidian-file-flex/blob/38dae823b8964cda70c1dfbaf93f907a5940c256/main.js#L133)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[.setName('Time Window')](https://github.com/19msb/obsidian-file-flex/blob/38dae823b8964cda70c1dfbaf93f907a5940c256/main.js#L137), [.setName('Clear Cache')](https://github.com/19msb/obsidian-file-flex/blob/38dae823b8964cda70c1dfbaf93f907a5940c256/main.js#L151)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by joethei** [comment]
[ - On Windows: `%APPDATA%/Roaming/obsidian/plugins`](https://github.com/19msb/obsidian-file-flex/blob/357ec08ba0703479c767665ea804b2bb4f1e8448/README.md?plain=1#L16-L18)
These paths are not correct, users can decide where they want to place their vault.

**Comment by 19msb** [comment]
@joethei 
Thank you! 
I've updated the installation details to address customisation of plugins fodler location and the capability of installing through obsidian.

**Pull request merged**
