### PR TITLE
add obsidian-icon-shortcodes

### PR DESCRIPTION
**Pull request by aidenlx**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: <https://github.com/aidenlx/obsidian-icon-shortcodes>

## Release Checklist

- [x] I have tested this on macOS
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by aidenlx** [comment]
Some questions regarding `.obsidian` folder structure: Currently all the custom svg icons is stored in `icons.json` under plugin folder and loaded to memory on load, which can be a problem if bitmap icons are support. I've done some test, and it seems that `app.vault.adapter.getResourcePath(path_to_file_inside_config_dir)` is working, so here is the problem:

1. is it safe to call `app.vault.adapter.getResourcePath(app.vault.configDir+"/icon.png")` or `app.vault.adapter.getResourcePath(plugin.manifest.dir+"/icon.png")` directly? In the API the `manifest.dir` seems to be optional. 
2. Is it okay to add an `icons` folder under `.obsidian`, so that all imported custom icons won't get lost if user remove the plugin? 
3. Is there a location where the icons (svg, png...) can be synced but not being included in vault, that is, indexed and linkable?

**Comment by lishid** [comment]
1. Depends on what you're trying to do - the method is there to provide a URI so that the browser engine can efficiently load the resource, instead of having to `vault.read(file)` and then put the contents into a base64/blob.
2. I think that's fine, you just want to test how it interacts with Obsidian Sync so it behaves what users normally expects
3. Depends on the sync solution. Obsidian ignores any dot folders, but Sync will pick up a few selective places in .obsidian, depending on the config options, but the best place is usually in your plugin's folder.

> so that all imported custom icons won't get lost if user remove the plugin

I'm not exactly sure if this is what we want to achieve - I'm assuming a user uninstalling the plugin usually means they don't have a need for it anymore. Either way - you can also consider the possibility of making this configurable (stored after uninstall or not).

**Comment by lishid** [comment]
> PS: seems that _DS_Store is not excluded in obsidian sync? Is it intentional or something?

Isn't it normally `.DS_Store`?

**Comment by aidenlx** [comment]
> Isn't it normally `.DS_Store`?

sry, just a typo 😂 Here are the logs regarding `.DS_Store`

```log
2021-11-15 11:16 - Connecting to server
2021-11-15 11:22 - Disconnected. Code: 1006 Abnormal Closure
2021-11-15 11:22 - Waiting to connect to server
2021-11-15 11:22 - Connecting to server
2021-11-15 11:22 - Connection successful. Detecting changes...
2021-11-15 11:22 - Server pushed [ALx-MBP.local] .obsidian/plugins/obsidian-codemirror-options/main.js
2021-11-15 11:22 - Deleting remote file .obsidian/plugins/obsidian-codemirror-options/manifest-beta.json
2021-11-15 11:22 - Fully synced
2021-11-15 11:23 - Connecting to server
2021-11-15 11:23 - Waiting to connect to server
2021-11-15 11:23 - Connection successful. Detecting changes...
2021-11-15 11:23 - Fully synced
2021-11-15 11:23 - Uploading file .obsidian/plugins/.DS_Store
2021-11-15 11:23 - Upload complete .obsidian/plugins/.DS_Store
2021-11-15 11:23 - Server pushed [ALx-MBP.local] .obsidian/plugins/.DS_Store
2021-11-15 11:23 - Fully synced
```

**Comment by lishid** [comment]
Oh yeah rip, settings sync are done completely differently including syncing plugin folders. I should fix that soon.

**Comment by aidenlx** [comment]
Another bug report, seems like `vault.adapter.rename` method does not work on unindexed files inside `.obsidian` folder: 

for example: 
`await app.vault.adapter.rename(".obsidian/themes/icons/test_004_sore_throat.svg",".obsidian/themes/icons/test_004_sore_throat2.svg")`

throws: 
```
app.js:formatted:83975 Uncaught TypeError: Cannot read property 'realpath' of undefined
    at e.<anonymous> (app.js:formatted:52090)
    at app.js:formatted:5760
    at Object.next (app.js:formatted:5773)
    at s (app.js:formatted:5658)
```
at here, which seems that it's trying to fetch real path from cached file info: 
image

**Comment by lishid** [comment]
Great find, I will fix that.

**Comment by aidenlx** [comment]
Since 0.13 is publicly available, would it be convenient for you to review this plugin? No rush if you still need more time.

**Comment by lishid** [comment]
Looks good to me. Sorry I somehow missed your plugin thinking I had already reviewed it before.

**Pull request merged**
