### PR TITLE
Add obsidian-babashka

### PR DESCRIPTION
**Pull request by filipesilva**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/filipesilva/obsidian-babashka

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[id: 'obsidian-babashka-eval-codeblock',](https://github.com/filipesilva/obsidian-babashka/blob/991fd90ec8d04328d76845c29b27689d2e66e8d2/main.ts#L386)
You don't need to include your plugin name in the command id,
Obsidian prefix it automatically with the plugin id.

**Comment by filipesilva** [comment]
@joethei thanks for taking a look! I'd removed the prefix in https://github.com/filipesilva/obsidian-babashka/commit/ee368a585edd53cdf74cbd01c9ed32f0c36398e7, and created a 1.0.5 release.

**Comment by liamcain** [comment]
- [if (validateAndSetup(codeblock, view, settings)) {](https://github.com/filipesilva/obsidian-babashka/blob/2ec7e15f8a8e2a87c053a3422efc3c13f46aaab4/main.ts#L276) just a code style suggestion. I recommend changing this to:

> if (codeblock && validateAndSetup(codeblock, view, settings)) {

Then you don't need the type assertion below. If you still want to keep the Notice, then you can move the notice into the caller fn. I think in general you just want to avoid the `as`

**Comment by filipesilva** [comment]
Thanks for the suggestion, I tried it in https://github.com/filipesilva/obsidian-babashka/commit/1cdbe5d04644c76080c39726c70b37d9e29baf5e and it did make the types nicer to work with!

**Pull request merged**
