### PR TITLE
Add plugin: Sticky Headings

### PR DESCRIPTION
**Pull request by imshenshen**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by imshenshen** [comment]
> Thank you for your submission, an automated scan of your plugin code's revealed the following issues:
> 
> [[1](https://github.com/imshenshen/obsidian-sticky-heading/blob/6575aba94d4f6f3cc1293d57f3e80eab634f7fdc/main.ts#L6-L8)][[2](https://github.com/imshenshen/obsidian-sticky-heading/blob/6575aba94d4f6f3cc1293d57f3e80eab634f7fdc/main.ts#L14-L38)][[3](https://github.com/imshenshen/obsidian-sticky-heading/blob/6575aba94d4f6f3cc1293d57f3e80eab634f7fdc/main.ts#L40-L54)][[4](https://github.com/imshenshen/obsidian-sticky-heading/blob/6575aba94d4f6f3cc1293d57f3e80eab634f7fdc/main.ts#L56-L80)]:Remember to rename the sample classes to something that makes sense to your plugin. If there are any errors, Obsidian will spit out this class name, so this will be important for users to debug if they need to.
> 
> Do NOT open a new PR for re-validation. Once you have pushed all of the required changes, the bot will reevaluate your PR within 6 hours. If you think some of these results are incorrect, please include `/skip` in your comment and the reason why you think the results are incorrect.

I have publish 1.0.3

**Comment by imshenshen** [comment]
@joethei  Can you review this?

**Comment by imshenshen** [comment]
@joethei conflicts resolved

**Comment by imshenshen** [comment]
@joethei How many conflicts do I need to resolve? Do I have to have just resolved them by the time you open and decide to merge my PR???

**Comment by imshenshen** [comment]
WTF?

**Comment by joethei** [comment]
You don't need to worry about the conflicts, we will fix those once the review is finished

**Comment by joethei** [comment]
["author": "im.shenshen@qq.com",](https://github.com/imshenshen/obsidian-sticky-heading/blob/d6e5c7ac40b27093422c49ac483481ae906b937a/manifest.json#L7)
This field is displayed in the sidebar and in the description for the plugin details page. Are you sure you want to have your email listed so prominently?
image

[// Remember to rename these classes and interfaces!](https://github.com/imshenshen/obsidian-sticky-heading/blob/d6e5c7ac40b27093422c49ac483481ae906b937a/main.ts#L4)
Remove this comment.

[console.log(`add sticky heading:  from: ${node.from}, to: ${node.to}, node: ${node.type.name}`)](https://github.com/imshenshen/obsidian-sticky-heading/blob/d6e5c7ac40b27093422c49ac483481ae906b937a/src/HeadingPlugin.ts#L50)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

**Comment by imshenshen** [comment]
@joethei follow you suggest https://github.com/imshenshen/obsidian-sticky-heading/commit/154030ed7f4ad5b000145bfdbeb4c74a56a6cf91
published 1.0.4

**Comment by imshenshen** [comment]
https://github.com/imshenshen/obsidian-sticky-heading/releases/tag/1.0.5

**Comment by joethei** [comment]
["author": "",](https://github.com/imshenshen/obsidian-sticky-heading/blob/971fd0723ba1ba7b7e020c99c357b7ce87b8b890/manifest.json#L7)
This should not be empty, use the value from the changes you made to `community-plugins.json`

**Comment by imshenshen** [comment]
> ["author": "",](https://github.com/imshenshen/obsidian-sticky-heading/blob/971fd0723ba1ba7b7e020c99c357b7ce87b8b890/manifest.json#L7) This should not be empty, use the value from the changes you made to `community-plugins.json`

https://github.com/imshenshen/obsidian-sticky-heading/releases/tag/1.0.6

**Pull request merged**
