### PR TITLE
Added MathLinks plugin

### PR DESCRIPTION
**Pull request by zhaoshenzhai**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/zhaoshenzhai/obsidian-mathlinks

## Release Checklist
- [ ] I have tested the plugin on
  - [X]  Windows
  - [ ]  macOS
  - [X]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by zhaoshenzhai** [comment]
I have updated the plugin to `0.1.2` since this merge request. It now uses `this.app.vault.configDir` instead of `.obsidian`.

**Comment by joethei** [comment]
Your plugin ID starts with "obsidian", please don't do that, it will throw of the sorting of the plugin folders, and is unnecessary.

[getMathLink](https://github.com/zhaoshenzhai/obsidian-mathlinks/blob/5f00aa351b413610faba3b109816edec766f23db/src/main.ts#L71)
Use [`this.app.metadataCache.getFileCache(file)?.frontmatter?.mathLink`](https://github.com/obsidianmd/obsidian-api/blob/3770989c2364ead5429eb7e4475e095588bbe914/obsidian.d.ts#L2148) instead to get the value from the frontmatter.

**Comment by zhaoshenzhai** [comment]
Hello! No worries :)

I'm not exactly sure what 'rebasing the pull request' means, could you please elaborate on that?
I have, however, synced the fork of `obsidian-releases` and now my plugin is at the bottom of the new list. Is this what I am supposed to do?

**Comment by liamcain** [comment]
> I'm not exactly sure what 'rebasing the pull request' means, could you please elaborate on that?

What you did is perfect, thanks!

**Pull request merged**
