### PR TITLE
Add plugin: Image to text OCR

### PR DESCRIPTION
**Pull request by dario-baumberger**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/dario-baumberger/obsidian-image-to-text-ocr

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by dario-baumberger** [comment]
In the [plugin guidelines](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+iterating+all+files+to+find+a+file+by+its+path) it's written "Avoid iterating all files to find a file by its path". 

Unfortunately I wasn't able to find a solution with `getAbstractFileByPath` because I don't know the path. It may be different from vault to vault due to user attachment settings: https://github.com/dario-baumberger/obsidian-image-to-text-ocr/blob/master/src/main.ts#L227. If a correction is necessary here, I would be very grateful for further suggestions

**Comment by dario-baumberger** [comment]
/skip

The ObsidianReviewBot detected FileSystemAdapter in the code and says, it's a problem because isDesktopOnly false. On mobile the plugin won't work with Obsidian Image-Tags, but with all other image tags like html img-tag and Markdown image-tag it works. The plugin displays a notice if the adapter wasn't found. I could write a hint, that it doesn't work on mobile devices.  But from my perspective, It would be nice to have this plugin also available on mobile for other image-tags than Obsidian tags.

The logs are all for debugging purposes and are only executed if logging is enabled in the plugin settings.

**Comment by dario-baumberger** [comment]
I just released a new version with a notice if the FileSystemAdapter isn't available (already existed) but added an extra text: Obsidian images are not supported on mobile devices.

It's also written in the readme. 

If this isn't enough to release it with isDesktopOnly: false, please let me know. Then I will change it to true

**Comment by joethei** [comment]
[name: "Image To Text: Replace Selection",](https://github.com/dario-baumberger/obsidian-image-to-text-ocr/blob/fa42ee9f8a8119f2c889bf72867dbce8a9c437e2/src/main.ts#L45), [name: "Image To Text: Replace Selection - custom language",](https://github.com/dario-baumberger/obsidian-image-to-text-ocr/blob/fa42ee9f8a8119f2c889bf72867dbce8a9c437e2/src/main.ts#L80), [name: "Image To Text: Append Selection",](https://github.com/dario-baumberger/obsidian-image-to-text-ocr/blob/fa42ee9f8a8119f2c889bf72867dbce8a9c437e2/src/main.ts#L127), [name: "Image To Text: Append Selection - custom language",](https://github.com/dario-baumberger/obsidian-image-to-text-ocr/blob/fa42ee9f8a8119f2c889bf72867dbce8a9c437e2/src/main.ts#L161)
Remove the "Image To Text" prefix and [use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[const imageFile = files.find((file) => file.name === fileName);](https://github.com/dario-baumberger/obsidian-image-to-text-ocr/blob/fa42ee9f8a8119f2c889bf72867dbce8a9c437e2/src/main.ts#L229)
Use `this.app.metadataCache.getFirstLinkPathDest(filename, '') instead.
<https://docs.obsidian.md/Reference/TypeScript+API/MetadataCache/getFirstLinkpathDest>

[const resourcePath = adapter.getResourcePath(imageFile.path);](https://github.com/dario-baumberger/obsidian-image-to-text-ocr/blob/fa42ee9f8a8119f2c889bf72867dbce8a9c437e2/src/main.ts#L238)
There is also a `getResourcePath` function in the Vault API, no need to use the adapter.
Plus, this will be mobile compatible.

**Comment by dario-baumberger** [comment]
@joethei Thank you very much for the review and the feedback! Especially for the tips regarding `getFirstLinkpathDest` and `getResourcePath`. I didn't find them myself... 

I have made the requested changes and published a new version.

**Pull request merged**
