### PR TITLE
Add plugin: my anime list text exporter

### PR DESCRIPTION
**Pull request by Xmoncoco**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Xmoncoco/my_anime_list_text_exporter

## Release Checklist
- [X] I have tested the plugin on
  - [ ]  Windows
  - [X]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[console.log(element);](https://github.com/Xmoncoco/my_anime_list_text_exporter/blob/230901fc2a08a8fcc2c25ac7d338e0a89a5e3201/main.ts#L81), [console.log(text.createText(await getAnimeData(value), value, aditionaltags));](https://github.com/Xmoncoco/my_anime_list_text_exporter/blob/230901fc2a08a8fcc2c25ac7d338e0a89a5e3201/main.ts#L133), [console.log(response.json.data);](https://github.com/Xmoncoco/my_anime_list_text_exporter/blob/230901fc2a08a8fcc2c25ac7d338e0a89a5e3201/main.ts#L187), [console.log ("listing directory")](https://github.com/Xmoncoco/my_anime_list_text_exporter/blob/230901fc2a08a8fcc2c25ac7d338e0a89a5e3201/filefinder.ts#L4)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[name: 'add a page for an anime',](https://github.com/Xmoncoco/my_anime_list_text_exporter/blob/230901fc2a08a8fcc2c25ac7d338e0a89a5e3201/main.ts#L109)
It would be better to name this `Create note for anime`

[let leaf = this.app.workspace.activeLeaf;](https://github.com/Xmoncoco/my_anime_list_text_exporter/blob/230901fc2a08a8fcc2c25ac7d338e0a89a5e3201/main.ts#L125)
`activeLeaf` is deprecated, use the `getLeaf` function

[let editor = leaf.view.sourceMode.cmEditor;](https://github.com/Xmoncoco/my_anime_list_text_exporter/blob/230901fc2a08a8fcc2c25ac7d338e0a89a5e3201/main.ts#L129)
Replace this with:
```ts
if(leaf.view instanceof MarkdownView) {
	let editor = leaf.view.editor;
	// rest of your code
}

```

[app.vault.getRoot()](https://github.com/Xmoncoco/my_anime_list_text_exporter/blob/230901fc2a08a8fcc2c25ac7d338e0a89a5e3201/filefinder.ts#L3)
It's highly discouraged that you use the global app instance in your plugin. It's currently accessible from the global context for debugging purposes, and might be removed in the future. Instead, you should use the reference to App that you have from your plugin instance.

**Comment by Xmoncoco** [comment]
ok all the changes are applied in 1.1.2

**Comment by joethei** [comment]
["description": "add anime data in obsidian",](https://github.com/Xmoncoco/my_anime_list_text_exporter/blob/2d2f28b8478baf7217d67023e3ce8607e5904375/manifest.json#L6)
Avoid including sentences like "in Obsidian" in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

**Comment by Xmoncoco** [comment]
ok descriptions changed

**Comment by joethei** [comment]
[app.vault.getAbstractFileByPath("/") as TFolder](https://github.com/Xmoncoco/my_anime_list_text_exporter/blob/34c727090b207feb7cd4bc087bd61a53652f1092/filefinder.ts#L3)
`getRoot()` was correct here, the comment was about you accessing the global `app` object.

**Comment by Xmoncoco** [comment]
ok I use the local app variable

**Pull request merged**
