### PR TITLE
Add plugin: Vertical Tabs

### PR DESCRIPTION
**Pull request by oxdc**
# Add plugin: Obsidian Vertical Tabs

## Repo URL

Link to my plugin: https://github.com/oxdc/obsidian-vertical-tabs

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[Copyright (c) delashum](https://github.com/oxdc/obsidian-vertical-tabs/blob/146b391e0df6c1bc3afaf5b64b3119313171f7dc/LICENSE#L3)
Update this, and add the year.

["description": "Yet another vertical tabs plugin.",](https://github.com/oxdc/obsidian-vertical-tabs/blob/146b391e0df6c1bc3afaf5b64b3119313171f7dc/manifest.json#L6)
Please actually describe your plugin, and don't include the word "plugin".

["fundingUrl": null,](https://github.com/oxdc/obsidian-vertical-tabs/blob/146b391e0df6c1bc3afaf5b64b3119313171f7dc/manifest.json#L9)
If you don't have one remove this line.

[This CSS file will be included with your plugin, and](https://github.com/oxdc/obsidian-vertical-tabs/blob/146b391e0df6c1bc3afaf5b64b3119313171f7dc/styles.css#L3-L6)
Remove this comment.

[name: "Open Navigation View",](https://github.com/oxdc/obsidian-vertical-tabs/blob/146b391e0df6c1bc3afaf5b64b3119313171f7dc/main.ts#L17), [return "Vertical Tabs";](https://github.com/oxdc/obsidian-vertical-tabs/blob/146b391e0df6c1bc3afaf5b64b3119313171f7dc/src/ui.ts#L37)

**Comment by oxdc** [comment]
@joethei Thank you! I have resolved all issues listed above and published a new release.

**Comment by joethei** [comment]
[name: "Open Navigation View",](https://github.com/oxdc/obsidian-vertical-tabs/blob/146b391e0df6c1bc3afaf5b64b3119313171f7dc/main.ts#L17),, [return "Navigation View";](https://github.com/oxdc/obsidian-vertical-tabs/blob/393b69a439c06dbb644558234f2da55366be72c9/src/ui.ts#L37)
Don't include view here,

**Comment by oxdc** [comment]
@joethei Thanks! I have renamed these to "Open Vertical Tabs" and "Vertical Tabs", and published a new release. The new names would be more intuitive and unambiguous.

**Comment by joethei** [comment]
[name: "Open Vertical Tabs",](https://github.com/oxdc/obsidian-vertical-tabs/blob/69df873e018130b67a867087ca28ae184feb4424/main.ts#L17), [export const VIEW_TEXT = "Vertical Tabs";](https://github.com/oxdc/obsidian-vertical-tabs/blob/69df873e018130b67a867087ca28ae184feb4424/src/ui.ts#L6), [text: "Grouped Tabs",](https://github.com/oxdc/obsidian-vertical-tabs/blob/69df873e018130b67a867087ca28ae184feb4424/src/ui.ts#L125)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by oxdc** [comment]
@joethei Sorry about this. I have rechecked the Plugin Guideline and updated the code.

**Pull request merged**
