### PR TITLE
Add TagFolder to community plugins.

### PR DESCRIPTION
**Pull request by vrtmrz**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/vrtmrz/obsidian-tagfolder

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/vrtmrz/obsidian-tagfolder/blob/ee9a0f7de2db60074a912479774464b259088bd8/main.ts#L96
Here I think you can access `this.app` directly (it's inherited from View).

https://github.com/vrtmrz/obsidian-tagfolder/blob/ee9a0f7de2db60074a912479774464b259088bd8/main.ts#L521
See the tip at: https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#avoid-managing-references-to-custom-views

https://github.com/vrtmrz/obsidian-tagfolder/blob/ee9a0f7de2db60074a912479774464b259088bd8/main.ts#L566
You may want to break up the function here and possibly make the aggregation part debounced - it could get called pretty often and you risk eating up a lot of extra performance for repeatedly aggregating all the tags for each file changed immediately.

https://github.com/vrtmrz/obsidian-tagfolder/blob/ee9a0f7de2db60074a912479774464b259088bd8/main.ts#L610
This function doesn't need to be async.

**Comment by vrtmrz** [comment]
Thank you for your review! I'd addressed all your advice.
Sorry for misunderstanding the guideline.
Would you please review it again?

**Comment by lishid** [comment]
> Here I think you can access this.app directly (it's inherited from View).

Oops I meant to say "here and every time after" - there's a few more spots that you can make it shorter.

Otherwise, looks good to me!

**Comment by vrtmrz** [comment]
Thank you for merging this! I'll check and fix it later.

**Pull request merged**
