### PR TITLE
Add plugin: Smart Text Mover

### PR DESCRIPTION
**Pull request by Ankush-Chander**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [obsidian-smart-move-text](https://github.com/Ankush-Chander/obsidian-smart-move-text)

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[const winkNLP = require('wink-nlp');](https://github.com/Ankush-Chander/obsidian-smart-move-text/blob/87e9343d41947788f747aeda01ca6e9e54a74273/main.ts#L10-L14)
Stick to one import style.

[containerEl.createEl("h2", {text: "Smart Text Mover"});](https://github.com/Ankush-Chander/obsidian-smart-move-text/blob/87e9343d41947788f747aeda01ca6e9e54a74273/main.ts#L559)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

["": "No Classifier",](https://github.com/Ankush-Chander/obsidian-smart-move-text/blob/87e9343d41947788f747aeda01ca6e9e54a74273/main.ts#L565-L566), [.setName("Model Name")](https://github.com/Ankush-Chander/obsidian-smart-move-text/blob/87e9343d41947788f747aeda01ca6e9e54a74273/main.ts#L598)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by Ankush-Chander** [comment]
Hi @joethei 
Thank you for feedback.

I have made following changes:
- [x] Made import style consistent
- [x] Remove redundant heading from settings 
- [x] Use sentence case in Settings UI

**Comment by joethei** [comment]
["nbc": "Naive bayesian classifier",](https://github.com/Ankush-Chander/obsidian-smart-move-text/blob/33093c17e5a67f7c618cc1e65ff89c190b53f6df/main.ts#L561)
it's written as "Bayesian", since it's named afer a person.

**Comment by Ankush-Chander** [comment]
Hi,
Above changes has been done.
Thanks!

**Pull request merged**
