### PR TITLE
Add plugin: Youtube Summarizer

### PR DESCRIPTION
**Pull request by ozdemir08**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/ozdemir08/youtube-video-summarizer

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by ozdemir08** [comment]
I have added a release with version 1.0.0.

**Comment by ozdemir08** [comment]
I have also enabled `issues` in my repository.

**Comment by ozdemir08** [comment]
Now, the latest release contains `main.js` and `manifest.json`.

**Comment by joethei** [comment]
["description": "A plugin to summarize the transcripts of Youtube videos.",](https://github.com/ozdemir08/youtube-video-summarizer/blob/a63cba379a4080de5ed420610f52341fed0dcd49/manifest.json#L6)
Avoid including sentences like "A plugin that does xyz" in your description.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[openAIApiKey: '<REPLACE_THIS_WITH_YOUR_API_KEY>'](https://github.com/ozdemir08/youtube-video-summarizer/blob/a63cba379a4080de5ed420610f52341fed0dcd49/main.ts#L9)
I don't recommend including this in the default settings. The default API key should just be `''` and you can check that the API key is present before making any API calls.

[console.log(this.settings.openAIApiKey);](https://github.com/ozdemir08/youtube-video-summarizer/blob/a63cba379a4080de5ed420610f52341fed0dcd49/main.ts#L22)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[// If the plugin hooks up any global DOM events (on parts of the app that doesn't belong to this plugin)](https://github.com/ozdemir08/youtube-video-summarizer/blob/a63cba379a4080de5ed420610f52341fed0dcd49/main.ts#L36-L43)
Remove all this sample code.

[.setName('open-ai-api-key')](https://github.com/ozdemir08/youtube-video-summarizer/blob/a63cba379a4080de5ed420610f52341fed0dcd49/main.ts#L73)
Replace this with `OpenAI key` for example.

[.setDesc('Enter your Open AI API Key to be able to generate summaries from transcripts.')](https://github.com/ozdemir08/youtube-video-summarizer/blob/a63cba379a4080de5ed420610f52341fed0dcd49/main.ts#L74), [.setPlaceholder('Enter your API KEY')](https://github.com/ozdemir08/youtube-video-summarizer/blob/a63cba379a4080de5ed420610f52341fed0dcd49/main.ts#L76)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[root.querySelector("title")?.innerHTML || "Title not found";](https://github.com/ozdemir08/youtube-video-summarizer/blob/a63cba379a4080de5ed420610f52341fed0dcd49/src/YoutubeMetadataParser/YoutubeVideoMetadataParser.ts#L66)
You should use `innerText´ instead.

**Comment by ozdemir08** [comment]
Hi Johannes, thanks for the review. I have addressed all your comments. Please, take another look.

**Comment by ozdemir08** [comment]
Hi, when should I expect this to be reviewed? Thanks.

**Comment by ozdemir08** [comment]
Any chance someone looking into this?

**Comment by liamcain** [comment]
- [openAiApiKey == DEFAULT_SETTINGS.openAIApiKey](https://github.com/ozdemir08/youtube-video-summarizer/blob/589e197595f5762f001b9c414e54bb4d43555ac6/main.ts#L24) you can remove this check, you are already checking if it's empty string
- [Open AI](https://github.com/ozdemir08/youtube-video-summarizer/blob/589e197595f5762f001b9c414e54bb4d43555ac6/main.ts#L64) nitpick: OpenAI is one word

**Pull request merged**
