### PR TITLE
Add "Word Splitting for Japanese in Edit Mode" Plugin

### PR DESCRIPTION
**Pull request by sonarAIT**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [cm-japanese-patch](https://github.com/sonarAIT/cm-japanese-patch)

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lishid** [comment]
Can you choose a better plugin ID? The code looks alright, but the plugin ID is rather generic and doesn't reflect what the plugin does well.

**Comment by sonarAIT** [comment]
@lishid
Thanks for the review!
> Can you choose a better plugin ID? The code looks alright, but the plugin ID is rather generic and doesn't reflect what the plugin does well.  

Yes, that's true. I changed the ID to `japanese-word-splitter` and released it again with the version 1.0.0.  
To avoid inconvenience, the name of the repository has not been changed, and it is still `ch-japanese-patch`.  
I can't think of a better ID, but if you can think of one, let me know and I'll fix it.  

I'm new to OSS, so there may be some other mistakes.  
If you do, please don't hesitate to let me know.  

Thank you!

**Comment by sonarAIT** [comment]
Sorry ... I made a mistake.  
By the way, I haven't resolved the conflict yet, so I'll fix it.

**Comment by sonarAIT** [comment]
Sorry ... I made a mistake.
By the way, I forgot to change the ID of my community-plugins.json, so I will do it!

**Comment by sonarAIT** [comment]
All set.
I didn't know if it was OK to resolve conflict. so I'll leave it to you.
I'm sorry I keep making mistakes.🙇

**Pull request merged**
