### PR TITLE
Add Dracula + LYT theme

### PR DESCRIPTION
**Pull request by xRyul**
# I am submitting a new Community Theme

## Repo URL

Link to my theme: 
https://github.com/xRyul/ObsidianMD_Dracula_x_LYT

## Theme checklist

- [ ✔] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo).
  - [✔] `obsidian.css`
  - [✔ ] The screenshot file.
- [✔ ] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [ ✔] I have added a license in the LICENSE file.
- [✔ ] My project respects and is compatible with the original license of any code from other themes that I'm using.
      I have given proper attribution to these other themes in my `README.md`.
- [✔ ] If my repo is not using the `master` branch, please indicate in `community-themes.json` with `"branch": "main"`.

### CODE REVIEW

**Comment by nickmilo** [comment]
Hey there [xRyul](https://github.com/xRyul), really cool mash-up here. Thank you for the attribution as well 🙏 Would you be open to two requests? Could you also directly attribute @ceciliamay ? Also, I would prefer the name of this theme does not start with `LYT`. I think it will create confusion and fragmentation of `LYT Mode` before it really has time to mature. I'd much rather prefer `Dracula (LYT Style)` (or even `Dracula + LYT`). I don't know what's possible, but that is my preference, and I am understanding of any outcome.

**Comment by xRyul** [comment]
- [x] Added Ceciliamay 
- [x] Changed the name to `Dracula + LYT`

**Comment by nickmilo** [comment]
[image: 🙏][image: 🙌]

**Comment by tingmelvin** [comment]
I left this on Discord for the author, but I believe I should here as well, since Discord messages are ephemeral:

LYT + Dracula theme currently has a base64 file for Avenir Next, and I don't recall Avenir Next being licensed under OFL and has to be bought from a foundry. I figured I should bring this up, since there might some implications (legal or otherwise) for Obsidian

**Comment by lishid** [comment]
@tingmelvin Thank you for bringing this to our attention.

If a license holder seeks enforcement with the theme author or whoever, they would usually contact the author (theme author here) and the hosting service (which is GitHub in this case).

We encourage everyone to respect the proper license terms, but we also aren't in a position to police licensing issues for third parties. If a takedown is requested by a license holder, I am happy to look into the matter.

**Pull request merged**
