### PR TITLE
Add Matter to community plugins

### PR DESCRIPTION
**Pull request by hunterclarke**
# I am submitting a new Community Plugin

Hi all! I'm with the [Matter](https://hq.getmatter.app) team. We've received dozens of requests for an Obsidian integration. We can't wait to get this to all of our users. Let me know if there is anything else you need from us.

## Repo URL
Link to my plugin: [obsidian-matter](https://github.com/getmatterapp/obsidian-matter)

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/getmatterapp/obsidian-matter/blob/8c2f5791325340d8b690697567ee5f81220ff7a3/src/main.ts#L38
I would advise running this after `Workspace.onLayoutReady()` so that Obsidian has a chance to pick up the vault files. Also awaiting a long-running process in your plugin's onload function will delay Obsidian's own app loading causing the app to show the loading bar while your plugin does the work behind the scene. Should probably not await for this to finish and just run it in parallel. (Plus if anything fails here your plugin will be deactivated).

Everything else looks fine.

**Comment by hunterclarke** [comment]
@lishid I've addressed your feedback in the master branch and marked a new release (1.0.1). Let me know if there anything else you need.

**Comment by lishid** [comment]
> I was unsure what you were referring to regarding Workspace.onLayoutReady(), I'm not seeing a hook in the API for executing plugin code after. Let me know if running the sync in parallel is insufficient.

There are cases where your plugin may be initialized before the vault has scanned all the files. If your plugin depends on knowing files in the vault then you should delay until the app has finished initial loading.

**Comment by hunterclarke** [comment]
> There are cases where your plugin may be initialized before the vault has scanned all the files. If your plugin depends on knowing files in the vault then you should delay until the app has finished initial loading.

Got it. Thanks for explaining and for the quick turnaround time!

**Pull request merged**
