### PR TITLE
Add plugin:  hamsterbase

### PR DESCRIPTION
**Pull request by CaryTrivett**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/hamsterbase/obsidian-hamsterbase

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[id: 'hamsterbase-sync-highlights',](https://github.com/hamsterbase/obsidian-hamsterbase/blob/57e39bf549e254de72b20f9ebdd160001e619e0f/src/hamsterbase-plugin.ts#L33)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

**Comment by liamcain** [comment]
- [this.app.vault.adapter.read](https://github.com/hamsterbase/obsidian-hamsterbase/blob/57e39bf549e254de72b20f9ebdd160001e619e0f/src/hamsterbase-plugin.ts#L73) [Prefer the Vault API over the Adapter API](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#prefer-the-vault-api-over-the-adapter-api)
- [this.app.vault.adapter.mkdir](https://github.com/hamsterbase/obsidian-hamsterbase/blob/57e39bf549e254de72b20f9ebdd160001e619e0f/src/hamsterbase-plugin.ts#L63) [Prefer the Vault API over the Adapter API](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#prefer-the-vault-api-over-the-adapter-api)
- [initPlugin](https://github.com/hamsterbase/obsidian-hamsterbase/blob/57e39bf549e254de72b20f9ebdd160001e619e0f/src/hamsterbase-plugin.ts#L53) you shouldn't be calling addCommand every time updateSetting gets called.

**Comment by ericaxu** [comment]
Hi there, to keep things tidy, we're going to temporarily close plugin PRs after a month of inactivity.

Feel free to tell us to re-open it when you're ready to continue. Thanks for your understanding!

**Comment by CaryTrivett** [comment]
@joethei Is there anything else that needs to be changed?

**Review by marcusolsson — APPROVED** [review]

**Comment by liamcain** [comment]
LGTM. @CaryTrivett due to the github permissions associated with the org, I can't rebase this pull request on your behalf. Could you rebase the your `hamsterbase` branch and move your plugin entry to the bottom of the community-plugins.json list? Then I can merge this. Thanks!

**Comment by liamcain** [comment]
Once you rebase it, can you @ me on the pull request so I know to merge it before I merge anything else?

**Comment by CaryTrivett** [comment]
@liamcain  i have rebase the project.

**Pull request merged**
