### PR TITLE
add ics plugin

### PR DESCRIPTION
**Pull request by muness**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/muness/obsidian-ics

## Release Checklist
- [X] I have tested the plugin on
  - [X]  Windows
  - [X]  macOS
  - [x]  Linux
  - [X]  Android _(if applicable)_
  - [X]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "This is a ICS plugin for Obsidian.",](https://github.com/muness/obsidian-ics/blob/5b0847186cf9a040c3e49421d69fb007198151ae/manifest.json#L6)
We have  published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This is a plugin for Obsidian" in your description.

["node-ical": "^0.16.1",](https://github.com/muness/obsidian-ics/blob/5b0847186cf9a040c3e49421d69fb007198151ae/package.json#L16)
This library is only available from a nodeJS runtime, which means that this will throw errors on Mobile (that's a problem since you have `isDesktopOnly` marked as `false` in your manifest.json file, or am I missing something?

[callback: async () => {](https://github.com/muness/obsidian-ics/blob/5b0847186cf9a040c3e49421d69fb007198151ae/src/main.ts#L85-L95)
You should use a editor callback here, that way the command will only be available if there is a editor available: <https://docs.obsidian.md/Plugins/User+interface/Commands#Editor+commands>

[const rangeStart = window.moment(dayToMatch);](https://github.com/muness/obsidian-ics/blob/5b0847186cf9a040c3e49421d69fb007198151ae/src/icalUtils.ts#L21)
Would be nicer to use `import {moment} from "obsidian";` here.

[containerEl.createEl("h2", {](https://github.com/muness/obsidian-ics/blob/5b0847186cf9a040c3e49421d69fb007198151ae/src/settings/ICSSettingsTab.ts#L46-L49)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)


[.setName("Add New")](https://github.com/muness/obsidian-ics/blob/5b0847186cf9a040c3e49421d69fb007198151ae/src/settings/ICSSettingsTab.ts#L54)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by muness** [comment]
Thanks for the feedback, @joethei ! I'll work on it, hopefully this weekend.

One thing I am also confused by is this:

> ["node-ical": "^0.16.1",](https://github.com/muness/obsidian-ics/blob/5b0847186cf9a040c3e49421d69fb007198151ae/package.json#L16)
> This library is only available from a nodeJS runtime, which means that this will throw errors on Mobile (that's a problem since you have isDesktopOnly marked as false in your manifest.json file, or am I missing something?

I expected the same issue too, but I've tested on my iPhone, iPad and @TopherMan tested it on [Android](https://github.com/muness/obsidian-ics/pull/46#issue-1818908445) and it works fine.

What do you suggest? Flip it back to desktop only? Or just go with it?

**Comment by muness** [comment]
Applied the feedback suggested in https://github.com/muness/obsidian-ics/pull/52 . The changes are in https://github.com/muness/obsidian-ics/releases/tag/1.0.1 .

Note that I did not disable mobile since the plugin works there. I wonder if this is because the build is [configured](https://github.com/muness/obsidian-ics/blob/5b0847186cf9a040c3e49421d69fb007198151ae/esbuild.config.mjs#L19) to [bundle](https://esbuild.github.io/api/#bundle) dependencies and so they're inlined in main.js?

**Comment by muness** [comment]
Hi @joethei or anyone else, any chance my updates suffice? Thank you!

**Pull request merged**
