### PR TITLE
Add Micro templates plugin

### PR DESCRIPTION
**Pull request by epszaw**
# I am submitting a new Community Plugin 
  
 ## Repo URL 
  
  
 Link to my plugin: 
  
 ## Release Checklist 
 - [x] I have tested the plugin on 
   - [x]  Windows 
   - [x]  macOS 
   - [x]  Linux 
   - [ ]  Android _(if applicable)_ 
   - [ ]  iOS _(if applicable)_ 
 - [x] My GitHub release contains all required files 
   - [x] `main.js` 
   - [x] `manifest.json` 
   - [ ] `styles.css` _(optional)_ 
 - [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_) 
 - [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file. 
 - [x] My README.md describes the plugin's purpose and provides clear usage instructions. 
 - [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls. 
 - [x] I have added a license in the LICENSE file. 
 - [x] My project respects and is compatible with the original license of any code from other plugins that I'm using. 
       I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Please follow the pull request template.

**Comment by epszaw** [comment]
> Please follow the pull request template.

@joethei updated the plugin's link

**Comment by joethei** [comment]
That's not what I am asking for.

When you create a pull request you need to switch to preview and click on one of the links, like it says at the top.
That will give you a bunch of things you need to confirm.

As you have not done so, I inserted the template for you above, please fill it.

**Comment by epszaw** [comment]
The text hasn't been rendered after click. Thank you for the help here!

**Comment by epszaw** [comment]
Tested the extension on windows and linux vm

**Comment by joethei** [comment]
[id: "micro-templates.select-templates-source-dir",](https://github.com/epszaw/obsidian-micro-templates/blob/e05d05c90c4ea37c7350e3e037b285118fed3c76/main.ts#L112)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.


It would be better if you could use the Vault API for file operations, as that would be mobile compatible: <https://docs.obsidian.md/Plugins/Vault>

**Comment by epszaw** [comment]
@joethei done. Now, the plugin uses obsidian API to work with file system

**Comment by joethei** [comment]
> [id: "micro-templates.select-templates-source-dir",](https://github.com/epszaw/obsidian-micro-templates/blob/e05d05c90c4ea37c7350e3e037b285118fed3c76/main.ts#L112)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

This has not been done.

[import { EOL } from "os";](https://github.com/epszaw/obsidian-micro-templates/blob/9326fa4239e1bd84b625cb5591ca7b945bce3cd0/main.ts#L9)
This import will also crash mobile, just use `\n`, you don't need to care about OS differences when using the vault/editor API's.

[rootPath: string;](https://github.com/epszaw/obsidian-micro-templates/blob/9326fa4239e1bd84b625cb5591ca7b945bce3cd0/main.ts#L27)
This variable is unused.

[containerEl.createEl("h2", { text: "Micro templates" });](https://github.com/epszaw/obsidian-micro-templates/blob/9326fa4239e1bd84b625cb5591ca7b945bce3cd0/main.ts#L185)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by epszaw** [comment]
@joethei done

**Comment by epszaw** [comment]
@joethei any news there?

**Comment by joethei** [comment]
> [id: "micro-templates.select-templates-source-dir",](https://github.com/epszaw/obsidian-micro-templates/blob/e05d05c90c4ea37c7350e3e037b285118fed3c76/main.ts#L112)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

This has not been done.

**Comment by epszaw** [comment]
@joethei done

**Comment by OfficerHalf** [comment]
A few minor things I noticed:

-  [onunload()](https://github.com/epszaw/obsidian-micro-templates/blob/master/main.ts#L158C1-L158C16) method is empty and could probably be removed
- Command names should probably [use sentence case](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)
- [getItems code](https://github.com/epszaw/obsidian-micro-templates/blob/master/main.ts#L34) could probably be simplified significantly. It seems like you're just trying to get the directories in the vault, you can just do the following:

`const folders: TFolder[] = this.app.vault.getAllLoadedFiles().filter((f) => f instanceof TFolder) as TFolder[];`

Then your `getText` method can display the item however you'd like, then if you want to mutate the object you can do that after selecting the item.

**Pull request merged**
