### PR TITLE
Add plugin: Export to HTML

### PR DESCRIPTION
**Pull request by kalvn**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/kalvn/obsidian-export-to-html

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by kalvn** [comment]
Hello there, it looks like there's a problem in the automated validation. The repo info is wrong:

```
Run actions/github-script@v6
Repo info: mProjectsCode/obsidian-lemons-search-plugin
Found issue: The newly added entry is not at the end, or you are submitting on someone else's behalf. The last plugin in the list is: `mProjectsCode/obsidian-lemons-search-plugin`. If you are submitting from a GitHub org, you need to be a public member of the org.
Error: Failed to validate plugin
```

**Comment by joethei** [comment]
[const markdownData = await parse(view.data, vault);](https://github.com/kalvn/obsidian-export-to-html/blob/4eb8dc4fa2a7fc6103c3519c54774553b6750f6d/src/main.ts#L49), [return await marked.parse(markdownData);](https://github.com/kalvn/obsidian-export-to-html/blob/4eb8dc4fa2a7fc6103c3519c54774553b6750f6d/src/parser.ts#L95)
Use the `MarkdownRenderer.render` method to get the actual HTML in Obsidian, and not the version marked is producing.
It will also contain HTML produced by plugins.

[currentVault = vault;](https://github.com/kalvn/obsidian-export-to-html/blob/4eb8dc4fa2a7fc6103c3519c54774553b6750f6d/src/parser.ts#L90-L91)
This code serves no purpose, remove it.

**Comment by kalvn** [comment]
Thank you for your feedback and analysis.

I removed `currentVault` in favor of `this.app.vault`.

But about Markdown parsing:
1. I don't get how to use `MarkdownRenderer.render` to get HTML out of Markdown in the context of the editorCallback.
2. It does not allow me to hook into the rendering process to transform images in base 64 for example, so it is not an equivalent.

Can you please advise?

**Comment by joethei** [comment]
You would create a div, render onto that div, get the HTML content of said div, then remove the div.
Afterwards you will need to do some post processing, but you are already doing that with marked.

**Comment by kalvn** [comment]
@joethei I just deployed v1.1.0 that drops the marked library and uses the Obsidian markdown renderer.

https://github.com/kalvn/obsidian-export-to-html/releases/tag/1.1.0

**Comment by kalvn** [comment]
Not sure how to get back the **Ready for review** tag 👀

**Comment by joethei** [comment]
[# Obsidian Export to HTML](https://github.com/kalvn/obsidian-export-to-html/blob/8cecbfe7a547fdc8e4a04553018e7076f4c6d0d2/README.md?plain=1#L1C1-L1C26)
Naming something "Obsidian xyz" is reserved for first party products we create, please change this header.

**Comment by kalvn** [comment]
@joethei Done, I just updated the header and the introduction in the README file, to make it clearer it is a community plugin.

**Pull request merged**
