### PR TITLE
Added folder notes plugin

### PR DESCRIPTION
**Pull request by LostPaul**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/LostPaul/obsidian-folder-notes

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[.nav-folder-title-content {](https://github.com/LostPaul/obsidian-folder-notes/blob/ecad3ddc31fac806118217f2b6e1d586515a6fad/styles.css#L1-L5)
[.nav-folder-title {](https://github.com/LostPaul/obsidian-folder-notes/blob/ecad3ddc31fac806118217f2b6e1d586515a6fad/styles.css#L14-L17)
Don't overwrite core styling with a plugin.

**Comment by LostPaul** [comment]
> [.nav-folder-title-content {](https://github.com/LostPaul/obsidian-folder-notes/blob/ecad3ddc31fac806118217f2b6e1d586515a6fad/styles.css#L1-L5) [.nav-folder-title {](https://github.com/LostPaul/obsidian-folder-notes/blob/ecad3ddc31fac806118217f2b6e1d586515a6fad/styles.css#L14-L17) Don't overwrite core styling with a plugin.

That's needed in order to avoid collapsing the folder when clicking on whitespace or do you have a better solution?

**Comment by LostPaul** [comment]
@joethei Any updates on this?

**Comment by LostPaul** [comment]
Any updates on this? @joethei

**Comment by liamcain** [comment]
- [openFolderNote](https://github.com/LostPaul/obsidian-folder-notes/blob/08c1218a40a3df9982c7890ad938bb0eda876900/src/main.ts#L172) you should pass the MouseEvent into the openFolderNote function then instead of `getLeaf(false)`, do: `getLeaf(Keymap.isModEvent(evt))`. That will let you support opening the file in a new tab/new window without any extra work
- [file?.path](https://github.com/LostPaul/obsidian-folder-notes/blob/08c1218a40a3df9982c7890ad938bb0eda876900/src/commands.ts#L42) shouldn't need the ? here. Looks confusing since it means file is optional here.
- [file?.path](https://github.com/LostPaul/obsidian-folder-notes/blob/08c1218a40a3df9982c7890ad938bb0eda876900/src/commands.ts#L42) don't cast to TFile, instead just add an instanceof check for better type safety. (It's not impossible for a folder to be called `somefolder.md/`

**Comment by LostPaul** [comment]
> * don't cast to TFile, instead just add an instanceof check for better type safety. (It's not impossible for a folder to be called `somefolder.md/`

uh when I don't do that typescript throws an error one line after that I check if it is a TFile or what do you want me to do?

**Comment by liamcain** [comment]
Yes, but since `file` will never be a TFile, I don't see the point in including that

**Comment by liamcain** [comment]
image
since you're reassigning to `file`, I realize what I said might be slightly confusing. I'm talking about this part. Here you're saying `file = the folder note or if the folder doesn't exist, assign file to be the folder`

**Comment by LostPaul** [comment]
> image since you're reassigning to `file`, I realize what I said might be slightly confusing. I'm talking about this part. Here you're saying `file = the folder note or if the folder doesn't exist, assign file to be the folder`

Yes because the file could be also null ts throws an error I could also just let it ignore but ?? file has the same effect as I'm using instanceof to check if it actually is a TFile
image
image

**Pull request closed without merging**
