### PR TITLE
Add theme: Celestial Night

### PR DESCRIPTION
**Pull request by Bluemoondragon07**
# I am submitting a new Community Theme

## Repo URL

Link to my theme: https://github.com/Bluemoondragon07/Obsidian-Celestial-Night-Theme

## Theme checklist

- [x] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo).
  - [x] `manifest.json`
  - [x] `theme.css`
  - [x] The screenshot file (16:9 aspect ratio, recommended size is 512px by 288px for fast loading).
- [x] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [x] I have read the tips in https://docs.obsidian.md/Themes/App+themes/Theme+guidelines and have self-reviewed my theme to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other themes that I'm using. I have given proper attribution to these other themes in my `README.md`.

### CODE REVIEW

**Comment by Bluemoondragon07** [comment]
I'm not entirely sure why it keeps returning errors. A little help here, please?

**Comment by liamcain** [comment]
Hi @Bluemoondragon07, sorry for all the trouble you've been having with the submission process. I fixed the submission entry but looks like there's still some issues on your end of things to take care of.

**Comment by joethei** [comment]
[@import url('https://fonts.googleapis.com/css2?family=Merienda:wght@300;400;500;700&display=swap');](https://github.com/Bluemoondragon07/Obsidian-Celestial-Night-Theme/blob/03b7d07844dad8131d096f4f45f165e78ae274d3/theme.css#L1)
As per our [Developer policies](https://docs.obsidian.md/Developer+policies) themes aren't allowed to load remote content over the network.
Please bundle the font.

**Comment by Bluemoondragon07** [comment]
Thank you for your feedback. The font is now base-encoded!

**Pull request merged**
