### PR TITLE
added Obsidian Mirror plugin. A plugin to sync the active file among different obsidian's instances

### PR DESCRIPTION
**Pull request by wildspecial**

### CODE REVIEW

**Comment by lishid** [comment]
Please update the PR using the provided plugin template 👍

**Comment by wildspecial** [comment]
Sorry @lishid can you point out where I find the plugin template? I generated this plugin using this repo --> https://github.com/obsidianmd/obsidian-sample-plugin

Please let me know!

Thanks

**Comment by lishid** [comment]
> Sorry @lishid can you point out where I find the plugin template? I generated this plugin using this repo -->

In this pull request, it seems that you've deleted the comment text:
image

It doesn't matter thaaaaat much to have, but it helps a lot for us when we review the plugin to submit the pull request with relevant information about your plugin. See an example here: https://github.com/obsidianmd/obsidian-releases/pull/451

When creating a pull request, it should automatically prompt you to use our github pull request template with instructions on how to fill it out.

**Comment by ericaxu** [comment]
@wildspecial The template can also be found here: https://github.com/obsidianmd/obsidian-releases/blob/master/.github/PULL_REQUEST_TEMPLATE/plugin.md (Use the "copy raw contents" option to copy it)

**Comment by ericaxu** [comment]
Hi there, to keep things tidy, we're going to temporarily close plugin PRs after a month of inactivity.

Feel free to tell us to re-open it when you're ready to continue. Thanks for your understanding!

**Pull request closed without merging**
