### PR TITLE
Add plugin: Immersive Translate

### PR DESCRIPTION
**Pull request by imfenghuang**
I am submitting a new Community Plugin
## Repo URL
Link to my plugin: https://github.com/imfenghuang/obsidian-magic-move

## Release Checklist

 - [x]  I have tested the plugin on
   - [ ] Windows
   - [x] macOS
   - [ ] Linux
   - [ ] Android (if applicable)
   - [ ] iOS (if applicable)
- [x] My GitHub release contains all required files
    - [x] main.js
    - [x] manifest.json
    - [ ] styles.css (optional)
- [x] GitHub release name matches the exact version number specified in my manifest.json (Note: Use the exact version number, don't include a prefix v)
- [x] The id in my manifest.json matches the id in the community-plugins.json file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
I have given proper attribution to these other projects in my README.md.

### CODE REVIEW

**Comment by imfenghuang** [comment]
/skip it‘s a shadow-dom which is created by the third party js-sdk. so i can't use the `styles.css` to control it's style.

**Comment by imfenghuang** [comment]
hi @joethei , what else should I do for this PR?

**Comment by joethei** [comment]
['https://download.immersivetranslate.com/immersive-translate-sdk-latest.js';](https://github.com/imfenghuang/obsidian-immersive-translate/blob/41bf41b48041bfebe863ec800d507d793d45ca5e/src/main.ts#L14)
This should be bundled into this plugin, not loaded externally.

[.addText((text) =>](https://github.com/imfenghuang/obsidian-immersive-translate/blob/41bf41b48041bfebe863ec800d507d793d45ca5e/src/setting.ts#L91-L95), [.addText((text) =>](https://github.com/imfenghuang/obsidian-immersive-translate/blob/41bf41b48041bfebe863ec800d507d793d45ca5e/src/setting.ts#L118-L123)
These should use `addTextarea` so that there is more room to see these strings.

[export function debounce<F extends (...args: Parameters<F>) => ReturnType<F>>(](https://github.com/imfenghuang/obsidian-immersive-translate/blob/41bf41b48041bfebe863ec800d507d793d45ca5e/src/utils.ts#L54-L63)
There is already a debounce function in the Obsidian API.

**Comment by imfenghuang** [comment]
> [.addText((text) =>](https://github.com/imfenghuang/obsidian-immersive-translate/blob/41bf41b48041bfebe863ec800d507d793d45ca5e/src/setting.ts#L91-L95), [.addText((text) =>](https://github.com/imfenghuang/obsidian-immersive-translate/blob/41bf41b48041bfebe863ec800d507d793d45ca5e/src/setting.ts#L118-L123) These should use `addTextarea` so that there is more room to see these strings.
> 
> [export function debounce<F extends (...args: Parameters) => ReturnType>(](https://github.com/imfenghuang/obsidian-immersive-translate/blob/41bf41b48041bfebe863ec800d507d793d45ca5e/src/utils.ts#L54-L63) There is already a debounce function in the Obsidian API.

1. `addText` -> `addTextArea`, replace  `debounce` fixed

2. i try to bundle it, but some special characters exist, it causes js error when loadPugin function called (range out of order in character class, this is because of the `immersive-translate-sdk-latest.js` itself), however it can be load externally。

**Comment by liamcain** [comment]
- [mmersiveTranslate](https://github.com/imfenghuang/obsidian-immersive-translate/blob/f7970924e522311601d2a19ba28744f3211fcb99/src/utils.ts#L25) typo

**Pull request merged**
