### PR TITLE
Add plugin: Substitutions

### PR DESCRIPTION
**Pull request by BambusControl**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/BambusControl/obsidian-substitutions

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by BambusControl** [comment]
Fixed it..

**Comment by joethei** [comment]
["minAppVersion": "0.15.0",](https://github.com/BambusControl/obsidian-substitutions/blob/f6edb02d161cb36dc26e05b8a3682d80dd7a00c0/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

[console.info("Creating services");](https://github.com/BambusControl/obsidian-substitutions/blob/f6edb02d161cb36dc26e05b8a3682d80dd7a00c0/src/substitutions/main.ts#L24), [console.info("Adding editor extension");](https://github.com/BambusControl/obsidian-substitutions/blob/f6edb02d161cb36dc26e05b8a3682d80dd7a00c0/src/substitutions/main.ts#L32), [console.info("Adding UI elements");](https://github.com/BambusControl/obsidian-substitutions/blob/f6edb02d161cb36dc26e05b8a3682d80dd7a00c0/src/substitutions/main.ts#L39), [console.info(`Plugin version: ${CURRENT_VERSION}`);](https://github.com/BambusControl/obsidian-substitutions/blob/f6edb02d161cb36dc26e05b8a3682d80dd7a00c0/src/substitutions/services/impl/rootPluginDataStorage.ts#L36-L37), [console.info("Plugin data already initialized");](https://github.com/BambusControl/obsidian-substitutions/blob/f6edb02d161cb36dc26e05b8a3682d80dd7a00c0/src/substitutions/services/impl/newDataInitializer.ts#L19), [console.log("Plugin and Data version mismatch, reinitializing")](https://github.com/BambusControl/obsidian-substitutions/blob/f6edb02d161cb36dc26e05b8a3682d80dd7a00c0/src/substitutions/services/impl/newDataInitializer.ts#L24), [console.info("Flagging local data as initialized");](https://github.com/BambusControl/obsidian-substitutions/blob/f6edb02d161cb36dc26e05b8a3682d80dd7a00c0/src/substitutions/services/impl/newDataInitializer.ts#L30), [console.info("Substitutions data already initialized");](https://github.com/BambusControl/obsidian-substitutions/blob/f6edb02d161cb36dc26e05b8a3682d80dd7a00c0/src/substitutions/services/impl/newDataInitializer.ts#L38), [console.info("Substitutions initialization");](https://github.com/BambusControl/obsidian-substitutions/blob/f6edb02d161cb36dc26e05b8a3682d80dd7a00c0/src/substitutions/services/impl/newDataInitializer.ts#L42), [console.log("Data skeleton already present");](https://github.com/BambusControl/obsidian-substitutions/blob/f6edb02d161cb36dc26e05b8a3682d80dd7a00c0/src/libraries/helpers/importData.ts#L13), [console.log("Creating data skeleton");](https://github.com/BambusControl/obsidian-substitutions/blob/f6edb02d161cb36dc26e05b8a3682d80dd7a00c0/src/libraries/helpers/importData.ts#L17)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

**Comment by BambusControl** [comment]
Thanks for the quick reply! I've fixed the issues.

1. Set min obsidian version to [1.5.12](https://github.com/BambusControl/obsidian-substitutions/blob/ab54b21312c12f7fb56aa47b2f63fcf50103f942/manifest.json#L5)

2. Console logging is dropped via labeled statements for _release_ builds. The released script will not log to the console---tested it out locally.
    - esbuild script: [`dropLabels: prodBuild ? ["DEVELOPMENT"] : []`](https://github.com/BambusControl/obsidian-substitutions/blob/ab54b21312c12f7fb56aa47b2f63fcf50103f942/esbuild.config.mjs#L50C5-L50C49)

    - console logging: [`DEVELOPMENT: console.group("Loading Substitutions plugin");`](https://github.com/BambusControl/obsidian-substitutions/blob/ab54b21312c12f7fb56aa47b2f63fcf50103f942/src/substitutions/main.ts#L21)

**Comment by BambusControl** [comment]
Hey @ObsidianReviewBot; I've fixed the issues

**Comment by BambusControl** [comment]
Thank you!

**Pull request merged**
