### PR TITLE
Add plugin: Wardley Maps

### PR DESCRIPTION
**Pull request by damonsk**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/damonsk/obsidian-wardley-maps

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
To make the manual review process and future plugin maintenance more efficient, we recommend that you move all source code files into a `src` directory.

[# Obsidian Wardley Maps Plugin](https://github.com/damonsk/obsidian-wardley-maps/blob/fd8859b51432df7f9e928587ef3af5dd4a130198/README.md#L1)
Naming something "Obsidian xyz" is reserved for first party products we create, please change this header.

["description": "View and edit Wardley Maps in Obsidian using the Online Wardley Maps format.",](https://github.com/damonsk/obsidian-wardley-maps/blob/fd8859b51432df7f9e928587ef3af5dd4a130198/manifest.json#L6)
Don't include "Obsidian" in the description, that should be a given since this only displayed when browsing plugins in the app / on our website.

[await this.loadSettings();](https://github.com/damonsk/obsidian-wardley-maps/blob/fd8859b51432df7f9e928587ef3af5dd4a130198/main.ts#L18)
Your plugin does not have any settings, so remove this loading code.

**Comment by damonsk** [comment]
Work done thank you.

**Comment by damonsk** [comment]
@joethei mindful it's been a while. Anything more required to progress this?

**Comment by joethei** [comment]
You haven't updated the description

**Comment by damonsk** [comment]
Thanks @joethei, apologies I missed that bit.  All done.

**Pull request merged**
