### PR TITLE
Add plugin: Azure DevOps Linker

### PR DESCRIPTION
**Pull request by srz2**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/srz2/obsidian-azure-devops-linker

## Release Checklist
- [X] I have tested the plugin on
  - [ ]  Windows
  - [X]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[Copyright (c) 2023 Steven Zilberberg](https://github.com/srz2/obsidian-azure-devops-linker/blob/dc59562244ff7127cc989856c11ac555c4b4ab96/LICENSE#L3)
Update the year

["minAppVersion": "0.15.0",](https://github.com/srz2/obsidian-azure-devops-linker/blob/dc59562244ff7127cc989856c11ac555c4b4ab96/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

[.setting-item-info:empty {](https://github.com/srz2/obsidian-azure-devops-linker/blob/dc59562244ff7127cc989856c11ac555c4b4ab96/styles.css#L10)

**Comment by joethei** [comment]
[Copyright (c) 2023 Steven Zilberberg](https://github.com/srz2/obsidian-azure-devops-linker/blob/dc59562244ff7127cc989856c11ac555c4b4ab96/LICENSE#L3)
Update the year

["minAppVersion": "0.15.0",](https://github.com/srz2/obsidian-azure-devops-linker/blob/dc59562244ff7127cc989856c11ac555c4b4ab96/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

[.setting-item-info:empty {](https://github.com/srz2/obsidian-azure-devops-linker/blob/dc59562244ff7127cc989856c11ac555c4b4ab96/styles.css#L10)
Please don't overwrite core styling in a plugin, add another class so it only applies to your plugin.

[id: 'cmd-link-azure-issue',](https://github.com/srz2/obsidian-azure-devops-linker/blob/dc59562244ff7127cc989856c11ac555c4b4ab96/main.ts#L36), [id: 'cmd-link-azure-issue-default-instance',](https://github.com/srz2/obsidian-azure-devops-linker/blob/dc59562244ff7127cc989856c11ac555c4b4ab96/main.ts#L55), [id: 'cmd-link-Azure-issue-info',](https://github.com/srz2/obsidian-azure-devops-linker/blob/dc59562244ff7127cc989856c11ac555c4b4ab96/main.ts#L92)
The `cmd` prefix is unnecessary.

[.setName('Azure DevOps Instances')](https://github.com/srz2/obsidian-azure-devops-linker/blob/dc59562244ff7127cc989856c11ac555c4b4ab96/main.ts#L283), [.setName('Azure DevOps Abbreviations')](https://github.com/srz2/obsidian-azure-devops-linker/blob/dc59562244ff7127cc989856c11ac555c4b4ab96/main.ts#L375), [cb.setPlaceholder('Add an Project Name')](https://github.com/srz2/obsidian-azure-devops-linker/blob/dc59562244ff7127cc989856c11ac555c4b4ab96/main.ts#L387), [cb.setPlaceholder('Example: Project Abbreviation')](https://github.com/srz2/obsidian-azure-devops-linker/blob/dc59562244ff7127cc989856c11ac555c4b4ab96/main.ts#L396), [.setTooltip('delete Project')](https://github.com/srz2/obsidian-azure-devops-linker/blob/dc59562244ff7127cc989856c11ac555c4b4ab96/main.ts#L406), [.setName('Local Issue Path')](https://github.com/srz2/obsidian-azure-devops-linker/blob/dc59562244ff7127cc989856c11ac555c4b4ab96/main.ts#L434), [.setName('Local Issue Main File Name')](https://github.com/srz2/obsidian-azure-devops-linker/blob/dc59562244ff7127cc989856c11ac555c4b4ab96/main.ts#L457), [.setName('New Line Insertion')](https://github.com/srz2/obsidian-azure-devops-linker/blob/dc59562244ff7127cc989856c11ac555c4b4ab96/main.ts#L472), [.setName("Azure DevOp Issue")](https://github.com/srz2/obsidian-azure-devops-linker/blob/dc59562244ff7127cc989856c11ac555c4b4ab96/Modals/AzureIssueInputModal.ts#L48), [.setButtonText("Link Issue")](https://github.com/srz2/obsidian-azure-devops-linker/blob/dc59562244ff7127cc989856c11ac555c4b4ab96/Modals/AzureIssueInputModal.ts#L57)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[this.description = 'Type in a azure issue number';](https://github.com/srz2/obsidian-azure-devops-linker/blob/dc59562244ff7127cc989856c11ac555c4b4ab96/Modals/AzureIssueInputModal.ts#L13)
Make sure that the correct capitalization is used for the brand name "Azure"

**Comment by srz2** [comment]
> ["minAppVersion": "0.15.0",](https://github.com/srz2/obsidian-azure-devops-linker/blob/dc59562244ff7127cc989856c11ac555c4b4ab96/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

What is the latest build number? Where can I find that info? This plugin was made off the obsidian plugin template and that is the minimum version number used

**Comment by joethei** [comment]
<https://obsidian.md/changelog>

**Comment by srz2** [comment]
I have made the suggested changes and ready for re-review

**Comment by srz2** [comment]
@joethei can this be re-reviewed?

**Pull request merged**
