### PR TITLE
added doubleshift

### PR DESCRIPTION
**Pull request by Qwyntex**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Qwyntex/doubleshift

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lishid** [comment]
Possible collaboration effort with this other plugin? https://github.com/mom0aut/obsidian-search-everywhere

**Comment by Qwyntex** [comment]
> Possible collaboration effort with this other plugin? https://github.com/mom0aut/obsidian-search-everywhere

I actually got the idea from this plugin and used its keylistener as a starting point. So i guess you could say that it is a collaboration. Should i add that in my readme then?

**Comment by lishid** [comment]
Ah ok! I guess you should at least credit the original author.

https://github.com/Qwyntex/doubleshift/blob/d65974cd05b841a6997cbbe3ac1ef3f8fb19d795/main.ts#L5
Here you shouldn't store a typed object - it will be destructively converted to JSON string and re-parsed when serialized to disk.

Instead you should store the plugin's ID here as a string.

**Comment by Qwyntex** [comment]
It doesn't show my gifs in the description do you know why that is?

**Comment by lishid** [comment]
You should use the raw.githubusercontent.com links for them to work properly I think

**Pull request merged**
