### PR TITLE
Add plugin: Color cycler

### PR DESCRIPTION
**Pull request by tjbrennan**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/tjbrennan/obsidian-color-cycler

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by tjbrennan** [comment]
> Thank you for your submission, an automated scan of your plugin code's revealed the following issues:
> 
> ### Required
> [[1](https://github.com/tjbrennan/obsidian-color-cycler/blob/7800aaa482a8e61956e2476ab0e215c9fe99ed07/main.ts#L226)][[2](https://github.com/tjbrennan/obsidian-color-cycler/blob/7800aaa482a8e61956e2476ab0e215c9fe99ed07/main.ts#L227)][[3](https://github.com/tjbrennan/obsidian-color-cycler/blob/7800aaa482a8e61956e2476ab0e215c9fe99ed07/main.ts#L228)]:You should avoid assigning styles via JavaScript or in HTML and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets.
> 
> Do NOT open a new PR for re-validation. Once you have pushed all of the required changes, the bot will reevaluate your PR within 6 hours. If you think some of these results are incorrect, please include `/skip` in your comment and the reason why you think the results are incorrect.

/skip

I understand the reasoning of this result, but the purpose of this plugin is to use javascript to override the CSS property `--accent-h` etc. I'm not sure if there's a better way to do that right now.

**Comment by joethei** [comment]
["description": "Dynamically change the accent color of the Obsidian theme.",](https://github.com/tjbrennan/obsidian-color-cycler/blob/4c9a2bd1ce0c781951a92559f57787318fbf907f/manifest.json#L7)
Remove "Obsidian" from the description.

[contentEl.createEl("h3", { text: "Increment" });](https://github.com/tjbrennan/obsidian-color-cycler/blob/4c9a2bd1ce0c781951a92559f57787318fbf907f/main.ts#L435), [contentEl.createEl("h3", { text: "Random" });](https://github.com/tjbrennan/obsidian-color-cycler/blob/4c9a2bd1ce0c781951a92559f57787318fbf907f/main.ts#L515), [contentEl.createEl("h3", { text: "Preset" });](https://github.com/tjbrennan/obsidian-color-cycler/blob/4c9a2bd1ce0c781951a92559f57787318fbf907f/main.ts#L604)
For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```

**Comment by tjbrennan** [comment]
> ["description": "Dynamically change the accent color of the Obsidian theme.",](https://github.com/tjbrennan/obsidian-color-cycler/blob/4c9a2bd1ce0c781951a92559f57787318fbf907f/manifest.json#L7) Remove "Obsidian" from the description.
> 
> [contentEl.createEl("h3", { text: "Increment" });](https://github.com/tjbrennan/obsidian-color-cycler/blob/4c9a2bd1ce0c781951a92559f57787318fbf907f/main.ts#L435), [contentEl.createEl("h3", { text: "Random" });](https://github.com/tjbrennan/obsidian-color-cycler/blob/4c9a2bd1ce0c781951a92559f57787318fbf907f/main.ts#L515), [contentEl.createEl("h3", { text: "Preset" });](https://github.com/tjbrennan/obsidian-color-cycler/blob/4c9a2bd1ce0c781951a92559f57787318fbf907f/main.ts#L604) For section headings in settings use:
> 
> ```ts
> new Setting(containerEl).setName('name here').setHeading();
> ```

@joethei Thanks for the review! I've updated my plugin and this PR accordingly.

**Comment by joethei** [comment]
[updateRibbonIconVisibility() {](https://github.com/tjbrennan/obsidian-color-cycler/blob/aa030f5d8e67c15e97f1abb94df1208a7015ee16/main.ts#L171-L177), [new Setting(containerEl)](https://github.com/tjbrennan/obsidian-color-cycler/blob/aa030f5d8e67c15e97f1abb94df1208a7015ee16/main.ts#L376-L385)
As of v1.1.0 of Obsidian, the ribbon can be customized within Obsidian. So users can choose what items to include and in what order all in one place. Because of this, we're recommending that new plugins avoid introducing their own toggles for ribbon items.

**Comment by tjbrennan** [comment]
> [updateRibbonIconVisibility() {](https://github.com/tjbrennan/obsidian-color-cycler/blob/aa030f5d8e67c15e97f1abb94df1208a7015ee16/main.ts#L171-L177), [new Setting(containerEl)](https://github.com/tjbrennan/obsidian-color-cycler/blob/aa030f5d8e67c15e97f1abb94df1208a7015ee16/main.ts#L376-L385) As of v1.1.0 of Obsidian, the ribbon can be customized within Obsidian. So users can choose what items to include and in what order all in one place. Because of this, we're recommending that new plugins avoid introducing their own toggles for ribbon items.

@joethei Neat, glad to learn about that feature. I've removed the ribbon setting from my plugin. Thanks!

**Pull request merged**
