### PR TITLE
Add Chess Study Plugin

### PR DESCRIPTION
**Pull request by chrislicodes**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/chrislicodes/obsidian-chess-study

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "A chess study helper and PGN viewer for Obsidian.",](https://github.com/chrislicodes/obsidian-chess-study/blob/632e02d92f344a769530aa1e968ebc3ee2b4db4c/manifest.json#L6)
You can omit "for Obsidian" here, see our new guide for plugin descriptions: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[style={{](https://github.com/chrislicodes/obsidian-chess-study/blob/632e02d92f344a769530aa1e968ebc3ee2b4db4c/src/components/react/ChessStudy.tsx#L152-L155)
You should avoid assigning styles via JavaScript or in HTML and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets.

**Comment by chrislicodes** [comment]
Hey @joethei, thanks for the hints, I fixed the styles and the description.

**Comment by chrislicodes** [comment]
Not sure if it matters for your review process but I just released a new version after submitting this plugin: https://github.com/chrislicodes/obsidian-chess-study/releases/tag/1.1.0

**Comment by marcusolsson** [comment]
[containerEl.createEl('h2', { text: 'Obsidian Chess Study Settings' });](https://github.com/chrislicodes/obsidian-chess-study/blob/1fd08ea85deaf0bbd6ef8e78803c4ae8e14803e9/src/components/obsidian/SettingsTab.ts#L27)
https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#UI+text

[.setName('Board Orientation')](https://github.com/chrislicodes/obsidian-chess-study/blob/1fd08ea85deaf0bbd6ef8e78803c4ae8e14803e9/src/components/obsidian/SettingsTab.ts#L30)
https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI

**Comment by chrislicodes** [comment]
@marcusolsson the casing and heading are fixed

**Comment by liamcain** [comment]
Why are you storing the pgn in their own json files instead of just pasting the pgn code into the markdown directly? Using separate JSON files will mean that this plugin won't work with Obsidian Sync.

**Comment by chrislicodes** [comment]
@liamcain Oh, I didn't know that - I assumed that it will also sync the whole vault. I don't only store the PGN but also all information regarding comments and drawn shapes, so the markdown entry could get very long. 🤔

**Pull request merged**
