### PR TITLE
Add plugin: Tabs

### PR DESCRIPTION
**Pull request by xhuajin**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/xhuajin/obsidian-tabs

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[Copyright (c) <year> <copyright holders>](https://github.com/xhuajin/obsidian-tabs/blob/a7eadec20c4b63976c0ffe03189f037e66c23a89/LICENSE#L3)
Fill this.

[item.setTitle("Delete Tab");](https://github.com/xhuajin/obsidian-tabs/blob/a7eadec20c4b63976c0ffe03189f037e66c23a89/src/components/tabs.ts#L139), [item.setTitle("Paste Tab");](https://github.com/xhuajin/obsidian-tabs/blob/a7eadec20c4b63976c0ffe03189f037e66c23a89/src/components/tabs.ts#L194), [let title = "New Tab\n";](https://github.com/xhuajin/obsidian-tabs/blob/a7eadec20c4b63976c0ffe03189f037e66c23a89/src/components/tabs.ts#L210)

[addIcon("circle-plus", circleplus);](https://github.com/xhuajin/obsidian-tabs/blob/a7eadec20c4b63976c0ffe03189f037e66c23a89/src/components/tabnavbutton.ts#L24), [setIcon(strikeButton, "strike");](https://github.com/xhuajin/obsidian-tabs/blob/a7eadec20c4b63976c0ffe03189f037e66c23a89/src/components/tabeditor.ts#L91)
This is not necessary, both of these icons are already part of lucide, and therefore loaded automatically.
`strike` is named `strikethrough` in Lucide.

**Comment by xhuajin** [comment]
> [Copyright (c) ](https://github.com/xhuajin/obsidian-tabs/blob/a7eadec20c4b63976c0ffe03189f037e66c23a89/LICENSE#L3) Fill this.
> 
> [item.setTitle("Delete Tab");](https://github.com/xhuajin/obsidian-tabs/blob/a7eadec20c4b63976c0ffe03189f037e66c23a89/src/components/tabs.ts#L139), [item.setTitle("Paste Tab");](https://github.com/xhuajin/obsidian-tabs/blob/a7eadec20c4b63976c0ffe03189f037e66c23a89/src/components/tabs.ts#L194), [let title = "New Tab\n";](https://github.com/xhuajin/obsidian-tabs/blob/a7eadec20c4b63976c0ffe03189f037e66c23a89/src/components/tabs.ts#L210)
> 
> [addIcon("circle-plus", circleplus);](https://github.com/xhuajin/obsidian-tabs/blob/a7eadec20c4b63976c0ffe03189f037e66c23a89/src/components/tabnavbutton.ts#L24), [setIcon(strikeButton, "strike");](https://github.com/xhuajin/obsidian-tabs/blob/a7eadec20c4b63976c0ffe03189f037e66c23a89/src/components/tabeditor.ts#L91) This is not necessary, both of these icons are already part of lucide, and therefore loaded automatically. `strike` is named `strikethrough` in Lucide.

Hi @joethei, thank you for pointing out those questions.

I have fill the Copyright, change circle-plus and strike to plus and strikethrough which Lucide support. (I‘ve tried using circle-plus directly but it didn't work.) You can see them in Tabs version 1.0.4.

Could you explain the second problem you pointed out more clearly? I will modify it as soon as possible.

**Comment by joethei** [comment]
Oh, must have forgotten to add a desscription.
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by xhuajin** [comment]
You responded so quickly. I fix those UI title and use sentense case.

**Comment by xhuajin** [comment]
@joethei Sorry to bother you, I just noticed that my last modification sent the wrong file, this time it is OK. I have fix the UI.

**Pull request merged**
