### PR TITLE
add todoist-text plugin

### PR DESCRIPTION
**Pull request by wesmoncrief**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/wesmoncrief/obsidian-todoist-text

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by ericaxu** [comment]
Please follow the instruction in the PR template before we can review it, thanks!

**Comment by wesmoncrief** [comment]
> Please follow the instruction in the PR template before we can review it, thanks!

@ericaxu apologies, I opened this a bit earlier than I should have - I think it should be good to go now!

**Comment by lishid** [comment]
https://github.com/wesmoncrief/obsidian-todoist-text/blob/f35740a684a513526067bef2937acc6dea3aafa8/main.ts#L34
Here you should use `app.commands.executeCommandById()` instead.

https://github.com/wesmoncrief/obsidian-todoist-text/blob/f35740a684a513526067bef2937acc6dea3aafa8/src/updateFileFromServer.ts#L15
Here you can reuse the file you got from a few lines earlier (from `getActiveFile()`).

https://github.com/wesmoncrief/obsidian-todoist-text/blob/f35740a684a513526067bef2937acc6dea3aafa8/src/updateFileFromServer.ts#L40
I think contains could lead to problems - instead you should use a regex like `/\s*- \[(.)\]/`.

**Comment by wesmoncrief** [comment]
@lishid thanks for the feedback! Addressed here - https://github.com/wesmoncrief/obsidian-todoist-text/pull/6/files

I created a new github release for it (and configured auto-releases)

Anything else I can do here?

**Comment by wesmoncrief** [comment]
Hey @lishid / @ericaxu - anything I can do to move this along in the review process? 

Thanks in advance 🙂

**Pull request merged**
