### PR TITLE
Update community-plugins.json with cloudinary uploader

### PR DESCRIPTION
**Pull request by jordanhandy**
Update community-plugins.json with cloudinary uploader

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/jordanhandy/obsidian-cloudinary-uploader

## Release Checklist

- [ ] I have tested this on Windows, macOS, and Linux _(if applicable)_
- [ x ] My GitHub release contains all required files
  - [ x ] `main.js`
  - [ x ] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [ x ] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [ x ] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [ x ] README clearly describes the plugins purpose and provides clear usage instructions.
- [ x ] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by lishid** [comment]
Might be worth explaining what Cloudinary is and what your plugin does (uploads images to a remote hosting service) for users unaware.

You should probably follow the same suggestion as here before we continue with the review:
https://github.com/obsidianmd/obsidian-releases/pull/636#issuecomment-968435031

**Comment by jordanhandy** [comment]
Hi @lishid 
I believe I've done as requested: https://github.com/jordanhandy/obsidian-cloudinary-uploader/commit/bcab568330d86e27930768bc067ac591fb18528c

Apologies if incorrect, this is my first time building a plugin for Obsidian.

I have also updated the Readme explaining what Cloudinary is:  https://github.com/jordanhandy/obsidian-cloudinary-uploader/commit/ea482af7ff3318ff7dcece92b934757c7fdfd01a

Please let me know if anything else is needed.  

Thank you

**Comment by lishid** [comment]
> Hi @lishid I believe I've done as requested: [jordanhandy/obsidian-cloudinary-uploader@bcab568](https://github.com/jordanhandy/obsidian-cloudinary-uploader/commit/bcab568330d86e27930768bc067ac591fb18528c)
> 
> Apologies if incorrect, this is my first time building a plugin for Obsidian.

No that's not what I meant - you're hooking up the drop and paste event handlers for CodeMirror (your type definitions doesn't change the fact that you're still hooking them up on CodeMirror).

I'm recommending a refactor of your code to avoid manually managing CodeMirror access and instead use the Workspace events for `editor-drop` and `editor-paste`. That way you can cut out 80% of your code that's managing how to hook/unhook the events and attempt to manage the lifecycle.

**Comment by jordanhandy** [comment]
Hi @lishid ,

Second attempt at doing this.  How does it look? https://github.com/jordanhandy/obsidian-cloudinary-uploader/commit/21aa183dee62fc80b1d086c7710aa48ad3c8c959.

I took out the hooks to CodeMirror and used the Workspace "editor-paste" event.

Thanks

**Comment by lishid** [comment]
Cool that's much better! One last thing I'd recommend is to use the `editor` object passed to your event handler rather than trying to get it manually from the active markdown view:

https://github.com/obsidianmd/obsidian-api/blob/5687a75ecfdb78b6a832127cf6f9229e27e196a0/obsidian.d.ts#L3634

**Comment by jordanhandy** [comment]
@lishid 
Is this what you're looking for? https://github.com/jordanhandy/obsidian-cloudinary-uploader/commit/1bdabb126d9d5d208635e45ef5028c22fc67f4a5#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3dR32-R35

Thanks for your suggestions and help

**Comment by lishid** [comment]
Looks great!

**Pull request merged**
