### PR TITLE
Add Tomorrow Night Bright theme

### PR DESCRIPTION
**Pull request by gbraad**
# I am submitting a new Community Theme

## Repo URL

Link to my theme: 

[gbraad/obsidian-tomorrow-night-bright-theme](https://github.com/gbraad/obsidian-tomorrow-night-bright-theme)

## Theme checklist

- [x] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo).
  - [x] `obsidian.css`
  - [x] The screenshot file.
- [x] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other themes that I'm using.
      I have given proper attribution to these other themes in my `README.md`.

### CODE REVIEW

**Comment by zamsyt** [comment]
Nice---I was wondering how come there aren't any OLED themes!

**Comment by ericaxu** [comment]
@gbraad Are you able to test this theme on 0.16? I can help you set it up if you don't have an insider license. Thanks!

**Comment by gbraad** [comment]
Haven't done so, but can try... Any specifics why?

**Comment by gbraad** [comment]
> Nice---I was wondering how come there aren't any OLED themes!

One of my thoughts too...

**Comment by ericaxu** [comment]
> Haven't done so, but can try... Any specifics why?

Are you on Discord? DM me, I'm Silver on there.

**Comment by ericaxu** [comment]
@gbraad Sorry for the long review process, we've been busy with a big design overhaul in the recently released v1.0 of Obsidian. Now that 1.0 has been released and Obsidian's UI has undergone some sweeping changes, we are asking all theme entries to confirm that their theme is compatible with the latest version of Obsidian.

**Comment by gbraad** [comment]
Haven't used Obsidian for some time, but will have a look

**Comment by gbraad** [comment]
Works as expected.

**Comment by ericaxu** [comment]
> Works as expected.

Looks good, thanks for rebasing it!

**Pull request merged**
