### PR TITLE
Add plugin: e-Daiary

### PR DESCRIPTION
**Pull request by wholetomy**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/wholetomy/obsidian-e-daiary

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["id": "e-daiary",](https://github.com/wholetomy/obsidian-e-daiary/blob/7740493a4a93324475909be0e1e7cd5361040f4d/manifest.json#L2-L3)
Is this a typo or is it supposed to be named like this?

["id": "e-daiary",](https://github.com/wholetomy/obsidian-e-daiary/blob/7740493a4a93324475909be0e1e7cd5361040f4d/manifest.json#L2-L3)
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link remove this line.

[this.addRibbonIcon('create-new', 'Create New Entry', this.createNewEntry.bind(this))](https://github.com/wholetomy/obsidian-e-daiary/blob/7740493a4a93324475909be0e1e7cd5361040f4d/main.ts#L19)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)
Also, you should add a command that does the same thing, the ribbon can be disabled by the user, and will be disabled by default in a future update.

[const yearFolderPath = `${this.settings.baseFolderPath}/${currentYear}`;](https://github.com/wholetomy/obsidian-e-daiary/blob/7740493a4a93324475909be0e1e7cd5361040f4d/main.ts#L29)
[Use `normalizePath` to clean up user defined paths](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+%60normalizePath()%60+to+clean+up+user-defined+paths)

[containerEl.createEl('h2', { text: 'Settings for e-Daiary' });](https://github.com/wholetomy/obsidian-e-daiary/blob/7740493a4a93324475909be0e1e7cd5361040f4d/main.ts#L138)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[.setName('Base Folder Path')](https://github.com/wholetomy/obsidian-e-daiary/blob/7740493a4a93324475909be0e1e7cd5361040f4d/main.ts#L144), [.setName('Custom Base Folder Path')](https://github.com/wholetomy/obsidian-e-daiary/blob/7740493a4a93324475909be0e1e7cd5361040f4d/main.ts#L156)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by wholetomy** [comment]
Changes made: https://github.com/wholetomy/obsidian-e-daiary/commit/c34f8e79955fc6309d9be88f803c6d22e6733c03

**Comment by joethei** [comment]
[name: 'Create New Entry',](https://github.com/wholetomy/obsidian-e-daiary/blob/c34f8e79955fc6309d9be88f803c6d22e6733c03/main.ts#L25)
This is not using sentence case.

**Comment by wholetomy** [comment]
Changes made again: https://github.com/wholetomy/obsidian-e-daiary/commit/12f83a18d6fbe895170c68aa14a83f7657d20d89

**Pull request merged**
