### PR TITLE
Add Vault Chat plugin

### PR DESCRIPTION
**Pull request by kristenbrann**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/exoascension/vault-chat

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [n/a]  Android _(if applicable)_
  - [n/a]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[const activeFile = this.app.workspace.activeEditor?.file](https://github.com/exoascension/vault-chat/blob/6023dc71be9e698ff4856f6d84699791b10a07be/src/main.ts#L77-L78)
Use a `checkCallback` instead, so the command will only show up if there is a active file.
<https://marcus.se.net/obsidian-plugin-docs/user-interface/commands#conditional-commands>


[app?.vault.getAbstractFileByPath(searchResult) as TFile](https://github.com/exoascension/vault-chat/blob/6023dc71be9e698ff4856f6d84699791b10a07be/src/main.ts#L146)
- It's highly discouraged that you use the global app instance in your plugin. It's currently accessible from the global context for debugging purposes, and might be removed in the future. Instead, you should use the reference to App that you have from your plugin instance.
- You don't validate that the file actually exists, or if it's a folder

**Comment by kristenbrann** [comment]
@joethei Thank you, we've addressed your feedback!

**Comment by cpaika** [comment]
@joethei Everything's been updated, let us know if you need anything from us to get this merged, we're excited.

**Comment by cpaika** [comment]
Any other feedback?  We've been waiting to merge this for a while.  We have a bunch of people using this, people clearly like it!

**Comment by liamcain** [comment]
- [layout-change](https://github.com/exoascension/vault-chat/blob/c56dda88ba39b0c818388bd5727f45b9d5047940/src/NoteChatView.tsx#L28)You should listen for [`file-open`](https://github.com/obsidianmd/obsidian-api/blob/ec589e9762a1d7e2faad01f894cb34c41b10ecaf/obsidian.d.ts#L4189) instead.

**Comment by liamcain** [comment]
Hi @kristenbrann, just following up to see if you saw my last message.

**Comment by kristenbrann** [comment]
@liamcain Updated, thank you!

**Comment by liamcain** [comment]
Hi, sorry just getting to this again. Could you rebase again and ping me immediately? I can merge it after.

**Comment by kristenbrann** [comment]
@liamcain all set

**Comment by joethei** [comment]
Hi @kristenbrann,

Can you rebase again and ping both me and Liam?
That should make sure that we can get this merged properly this time.

**Pull request merged**
