### PR TITLE
Add obsidian-pending-notes plugin

### PR DESCRIPTION
**Pull request by ulisesantana**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [https://github.com/ulisesantana/obsidian-pending-notes](https://github.com/ulisesantana/obsidian-pending-notes)

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by ulisesantana** [comment]
Done! I just added your recommendation and resolved conflicts. Thanks!

**Comment by liamcain** [comment]
Sorry, there are merge conflicts again and it appears that I don't have the permissions to rebase https://github.com/ulisesantana/obsidian-releases on your behalf. Do you mind moving the entry to the bottom or just updating the permissions to your fork so that I can rebase it before I merge it? Thanks!

**Comment by ulisesantana** [comment]
I just fixed conflicts and invited you to fork, just in case you need it at some point again.

**Comment by liamcain** [comment]
Thanks, one last thing. In the author field you included your email address. That field is displayed in the sidebar and in the description for the plugin details page. Are you sure you want to have your email listed so prominently?
image

**Comment by ulisesantana** [comment]
Actually I prefer to delete it. Thanks for pointing out.

**Pull request merged**
