### PR TITLE
[Feat] add plugin vanadium23/obsidian-advanced-new-file

### PR DESCRIPTION
**Pull request by vanadium23**
# [x] I am submitting a new Community Plugin

## Repo URL

https://github.com/vanadium23/obsidian-advanced-new-file

## Release Checklist

- [x] I have tested this on Windows, macOS, and Linux _(if applicable)_
- [x] Github release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
- [x] Github release name matches the exact version number specified in your manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/vanadium23/obsidian-advanced-new-file/blob/69eedc3d52e014da0a488b1c39abd93ddfa5e6ab/src/main.ts#L12
I don't think this needs to be in a checkCallback at all, just make it a regular callback with `new ChooseFolderModal(this.app).open()`.

https://github.com/vanadium23/obsidian-advanced-new-file/blob/69eedc3d52e014da0a488b1c39abd93ddfa5e6ab/src/modal.ts#L23
The easier way would be to use 
```ts
Vault.recurseChildren(vault.getRoot(), (file) => {
	if (file instanceof TFolder) {
		folders.add(file);
	}
});
```

https://github.com/vanadium23/obsidian-advanced-new-file/blob/69eedc3d52e014da0a488b1c39abd93ddfa5e6ab/src/modal.ts#L87
Notice takes a string here, but you're passing it an `Error`;  maybe this should be `new Notice(error.message)`.

**Comment by vanadium23** [comment]
Okay, I'll fix it.

**Comment by vanadium23** [comment]
I've updated code, based on your comments.

https://github.com/vanadium23/obsidian-advanced-new-file/commit/a3be04ece33eebc0cd65dfc16c5061579682439d

**Comment by vanadium23** [comment]
@lishid can you take a look?

**Pull request merged**
