### PR TITLE
add plugin: Easy Typing

### PR DESCRIPTION
**Pull request by Yaozhuwa**
# I am submitting a new Community Plugin

## Repo URL

https://github.com/Yaozhuwa/easy-typing-obsidian

showfeature

## Release Checklist

- [x] I have tested this on 
  - [x] Windows10, obsidian v0.11.13
  - [x] ubuntu18.04, obsidian v0.11.13
  - [ ] macOS
- [x] Github release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - `styles.css` _(optional)_
- [x] Github release name matches the exact version number specified in your manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/Yaozhuwa/easy-typing-obsidian/blob/5dff2de9c6a6006d8fbe7fdd402d93983e35ecb2/main.ts#L2
These two imports are unused.

https://github.com/Yaozhuwa/easy-typing-obsidian/blob/5dff2de9c6a6006d8fbe7fdd402d93983e35ecb2/main.ts#L973
You can combine all 3 events into a single `registerCodeMirror`.

https://github.com/Yaozhuwa/easy-typing-obsidian/blob/5dff2de9c6a6006d8fbe7fdd402d93983e35ecb2/main.ts#L1020
You should unhook your 3 events in your unload function using `workspace.iterateCodeMirrors`.

https://github.com/Yaozhuwa/easy-typing-obsidian/blob/5dff2de9c6a6006d8fbe7fdd402d93983e35ecb2/main.ts#L1164
This seems rather expensive to perform for each keyup event. You're getting the whole document and parsing it for every keypress.

https://github.com/Yaozhuwa/easy-typing-obsidian/blob/5dff2de9c6a6006d8fbe7fdd402d93983e35ecb2/manifest.json#L9
Since you're using the CodeMirror 5 API, you must set isDesktopOnly to true, as your plugin will not work on mobile devices.

**Comment by AidenLx** [comment]
You can use CodeMirror's events: https://codemirror.net/doc/manual.html#events

**Comment by Yaozhuwa** [comment]
> https://github.com/Yaozhuwa/easy-typing-obsidian/blob/5dff2de9c6a6006d8fbe7fdd402d93983e35ecb2/main.ts#L2
These two imports are unused.
> https://github.com/Yaozhuwa/easy-typing-obsidian/blob/5dff2de9c6a6006d8fbe7fdd402d93983e35ecb2/main.ts#L973
You can combine all 3 events into a single registerCodeMirror.
> https://github.com/Yaozhuwa/easy-typing-obsidian/blob/5dff2de9c6a6006d8fbe7fdd402d93983e35ecb2/main.ts#L1020
You should unhook your 3 events in your unload function using workspace.iterateCodeMirrors.
> https://github.com/Yaozhuwa/easy-typing-obsidian/blob/5dff2de9c6a6006d8fbe7fdd402d93983e35ecb2/main.ts#L1164
This seems rather expensive to perform for each keyup event. You're getting the whole document and parsing it for every keypress.
> https://github.com/Yaozhuwa/easy-typing-obsidian/blob/5dff2de9c6a6006d8fbe7fdd402d93983e35ecb2/manifest.json#L9
Since you're using the CodeMirror 5 API, you must set isDesktopOnly to true, as your plugin will not work on mobile devices.

Thanks for you revision. I've solved all the issue above. See in my new release v3.1.4: https://github.com/Yaozhuwa/easy-typing-obsidian/releases/tag/3.1.4

**Comment by lishid** [comment]
Ok last thing:
https://github.com/Yaozhuwa/easy-typing-obsidian/blob/b416c2a00c9486dcc893ea54de34d0a68f42aebd/main.ts#L1043
This should be `this.app.workspace.iterateCodeMirrors` instead of `this.registerCodeMirror`.

**Pull request merged**
