### PR TITLE
Added new plugin called quickly.

### PR DESCRIPTION
**Pull request by tmfelwu**
Allows to quickly capture thoughts.

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/tmfelwu/obsidian-inbox

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by tmfelwu** [comment]
Edited

**Comment by joethei** [comment]
[container.style.display = 'flex';](https://github.com/tmfelwu/obsidian-inbox/blob/863346341fca0c03db61f9f879a6b62fa796e486/main.ts#L17-L20)
You should avoid assigning styles via JavaScript and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets

[const selectedNote = this.app.vault.getAbstractFileByPath(`${selectedTitle}.md`);](https://github.com/tmfelwu/obsidian-inbox/blob/863346341fca0c03db61f9f879a6b62fa796e486/main.ts#L60)
This will fail if the file is in a folder, use `this.app.metadataCache.getFirstLinkpathDest(selectedTitle, "");` instead.

[if (existingNote) {](https://github.com/tmfelwu/obsidian-inbox/blob/863346341fca0c03db61f9f879a6b62fa796e486/main.ts#L134)
Check if `existingNote instanceof TFile` instead.

[this.app.workspace.activeLeaf.openFile(existingNote);](https://github.com/tmfelwu/obsidian-inbox/blob/863346341fca0c03db61f9f879a6b62fa796e486/main.ts#L135)
`activeLeaf` could be undefined, use  `this.app.workspace.activeLeaf?.openFile(existingNote);` instead.

**Comment by tmfelwu** [comment]
Made the requisite changes

**Comment by tmfelwu** [comment]
Do I need to fix these conflicts that have emerged due to updates in `community-plugins.json` in the main repo or you will take care of these during merge? @joethei

**Comment by liamcain** [comment]
- [create](https://github.com/tmfelwu/obsidian-inbox/blob/ae7d9ed3960f24658a388a24c5f8f5ad3d8b5b17/main.ts#L186) create returns a Promise<TFile>, you can just call openFile with that instead of relying on navigateToSelectedNote to find the TFile again by name.
- [style.fontSize](https://github.com/tmfelwu/obsidian-inbox/blob/ae7d9ed3960f24658a388a24c5f8f5ad3d8b5b17/main.ts#L124) You should avoid assigning styles via javascript. Instead, just add a class to the element and move all these styles into CSS so that they are more easily adaptable by themes.
- [container](https://github.com/tmfelwu/obsidian-inbox/blob/ae7d9ed3960f24658a388a24c5f8f5ad3d8b5b17/styles.css#L1) these classnames need to be more specific. These css classes are not namespaced so you risk styling elements that are out of the scope of your plugin.
- [notePaths](https://github.com/tmfelwu/obsidian-inbox/blob/ae7d9ed3960f24658a388a24c5f8f5ad3d8b5b17/main.ts#L40) unused

**Comment by tmfelwu** [comment]
Done the requisite chcanges

**Comment by tmfelwu** [comment]
@liamcain done the changes. However there is an error in plugin validation `couldn't find remote ref refs/pull/1862/merge` not sure why. do i need to do anything?

**Pull request merged**
