### PR TITLE
Add plugin: Hugo Publish

### PR DESCRIPTION
**Pull request by kirito41dd**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/kirito41dd/obsidian-hugo-publish

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["fundingUrl": "",](https://github.com/kirito41dd/obsidian-hugo-publish/blob/f1f9ffb09625897f692f504aa25e4b78ddeb7198/manifest.json#L9)
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link omit this.

[this.addRibbonIcon('dice', 'hugo sync', async (evt: MouseEvent) => {](https://github.com/kirito41dd/obsidian-hugo-publish/blob/f1f9ffb09625897f692f504aa25e4b78ddeb7198/src/main.ts#L43)
use a different icon: <https://docs.obsidian.md/Plugins/User+interface/Icons>

[console.log("link", this.app.metadataCache.resolvedLinks);](https://github.com/kirito41dd/obsidian-hugo-publish/blob/f1f9ffb09625897f692f504aa25e4b78ddeb7198/src/main.ts#L123), [console.log("process", f.path, "stat", stat, creat_at);](https://github.com/kirito41dd/obsidian-hugo-publish/blob/f1f9ffb09625897f692f504aa25e4b78ddeb7198/src/main.ts#L141), [console.log("header\n", header, "body\n", body, "hv", hv);](https://github.com/kirito41dd/obsidian-hugo-publish/blob/f1f9ffb09625897f692f504aa25e4b78ddeb7198/src/main.ts#L154), [console.log("ast", ast)](https://github.com/kirito41dd/obsidian-hugo-publish/blob/f1f9ffb09625897f692f504aa25e4b78ddeb7198/src/main.ts#L168), [console.log(`copy ${src} to ${dst}`);](https://github.com/kirito41dd/obsidian-hugo-publish/blob/f1f9ffb09625897f692f504aa25e4b78ddeb7198/src/main.ts#L191), [console.log("this", this);](https://github.com/kirito41dd/obsidian-hugo-publish/blob/f1f9ffb09625897f692f504aa25e4b78ddeb7198/src/main.ts#L209-L210), [console.log(`write ${src} to ${dst}`);](https://github.com/kirito41dd/obsidian-hugo-publish/blob/f1f9ffb09625897f692f504aa25e4b78ddeb7198/src/main.ts#L228)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

**Comment by kirito41dd** [comment]
@joethei thank you, please review again 
https://github.com/kirito41dd/obsidian-hugo-publish/commit/8851c5dd4660a10c046d141e5f2e9818291e8e2f

**Comment by joethei** [comment]
["description": "write blog in obsidian, pubulish to hugo site.",](https://github.com/kirito41dd/obsidian-hugo-publish/blob/8851c5dd4660a10c046d141e5f2e9818291e8e2f/manifest.json#L6)
Remove "Obsidian" from the description, it should be obvious that this is for Obsidian.
Also, you made a typo.

**Comment by kirito41dd** [comment]
@joethei thanks! https://github.com/kirito41dd/obsidian-hugo-publish/commit/0bf34d24bfd44ce86dc08f7aa3333637ffd2a800

**Comment by kirito41dd** [comment]
@joethei Can you continue to review this PR? I create a new tag [1.0.4](https://github.com/kirito41dd/obsidian-hugo-publish/releases/tag/1.0.4) for https://github.com/kirito41dd/obsidian-hugo-publish/commit/0bf34d24bfd44ce86dc08f7aa3333637ffd2a800 . thanks

**Pull request merged**
