### PR TITLE
Add APIRequest plugin

### PR DESCRIPTION
**Pull request by Rooyca**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Rooyca/obsidian-api-request/

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "This is a plugin for Obsidian that allows you to make API requests and get the response in the form of a JSON file",](https://github.com/Rooyca/obsidian-api-request/blob/188a714857bbe1e97b8c75b2417622b968c0a257/manifest.json#L6)
We have recently published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This is a plugin for Obsidian that" in your description.

Please rename your classes to something a bit more meaningful.

[fetch(this.settings.URL)](https://github.com/Rooyca/obsidian-api-request/blob/188a714857bbe1e97b8c75b2417622b968c0a257/main.ts#L32)
Use `requestUrl` from the Obsidian API instead, as that will handle some issues like CORS automatically.

[this.registerDomEvent(document, 'click', (evt: MouseEvent) => {](https://github.com/Rooyca/obsidian-api-request/blob/188a714857bbe1e97b8c75b2417622b968c0a257/main.ts#L50-L54)
Remove these lines.

**Comment by Rooyca** [comment]
Thank you for the advice! 

As you can see it's my first plugin and I still have a lot to learn.

**Comment by marcusolsson** [comment]
[fetch(this.settings.URL, {](https://github.com/Rooyca/obsidian-api-request/blob/00a5ca342b138ab0d35aa94230d61e830bd3d076/main.ts#L38)
Did you have any issues switching to `requestUrl` mentioned in the previous feedback?

[containerEl.createEl('h1', {text: 'General Settings'});](https://github.com/Rooyca/obsidian-api-request/blob/00a5ca342b138ab0d35aa94230d61e830bd3d076/main.ts#L187)
https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#UI+text

**Comment by Rooyca** [comment]
> [fetch(this.settings.URL, {](https://github.com/Rooyca/obsidian-api-request/blob/00a5ca342b138ab0d35aa94230d61e830bd3d076/main.ts#L38) Did you have any issues switching to `requestUrl` mentioned in the previous feedback?

Yes, I couldn't get to work with other types of request like POST or DELETE. Maybe there is a Documentation, but i didn't find it.

**Comment by marcusolsson** [comment]
This didn't work for you? 

```ts
requestUrl({
  url: "https://...",
  method: "POST",
});
```

- https://docs.obsidian.md/Reference/TypeScript+API/requestUrl
- https://docs.obsidian.md/Reference/TypeScript+API/RequestUrlParam/RequestUrlParam

**Comment by marcusolsson** [comment]
Could you share some more details? Are you seeing the same issue with multiple REST APIs, if not, is there a publicly available endpoint that I could test?

Also, what OS are you using while developing?

**Comment by Rooyca** [comment]
I'm a idiot jajaj. I was doing:
```bash
requestUrl("https://...",  {
  method: "POST",
});
```
Instead of:
```bash
requestUrl({
  url: "https://...",
  method: "POST",
});
```
And I was checking (for some reason) if response was not "ok", then `throw new Error('Request failed with status ${response.status}');`. No sure why I did that. But now It looks like its working.

**Review by marcusolsson — APPROVED** [review]

**Comment by liamcain** [comment]
- [registerInterval](https://github.com/Rooyca/obsidian-api-request/blob/0150ea83d3d54e824e06b711d5527b7f5c0a9875/main.ts#L74) remove this

**Comment by Rooyca** [comment]
Ok, thank you

**Pull request merged**
