### PR TITLE
add obsidian-pdf-annotation, a Plugin to extract PDF Annotations

### PR DESCRIPTION
**Pull request by munach**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/munach/obsidian-pdf-annotations

## Release Checklist
- [X] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [X]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by munach** [comment]
Dear reviewer, 
thanks a lot for reviewing my plugin. I hope you'll find everything as expected. 
kind regards
Franz

**Comment by lishid** [comment]
https://github.com/munach/obsidian-pdf-annotations/blob/ab3ce95351a741d2f269474ca71242217c2617c4/main.ts#L234
Here you should always check these conditions even if `checking` is false. Here's an example of  how to do it: https://marcus.se.net/obsidian-plugin-docs/guides/commands#conditional-commands

https://github.com/munach/obsidian-pdf-annotations/blob/ab3ce95351a741d2f269474ca71242217c2617c4/main.ts#L247
getActiveFile may return null causing a crash here.

I suggest writing an anonymous async function here rather than mixing async/await with `.then`.

https://github.com/munach/obsidian-pdf-annotations/blob/ab3ce95351a741d2f269474ca71242217c2617c4/main.ts#L289
Don't need to write the settings back if they haven't changed from default values, right?

**Comment by munach** [comment]
Dear lishid, 
thanks a lot for your suggestions. In fact, the refactoring of the .then notations removed some duplicated code. 
kind regards 
Franz

**Comment by lishid** [comment]
Seems like your pull request is kinda broken - can you fix that on your branch? At the very least it should not modify the releases and stats files.

**Pull request closed without merging**
