### PR TITLE
Add obsidian-tracker plugin

### PR DESCRIPTION
**Pull request by pyrochlore**
# [x] I am submitting a new Community Plugin

## Repo URL

https://github.com/pyrochlore/obsidian-tracker

## Release Checklist

- [x] I have tested this on Windows, macOS
- [x] Github release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] Github release name matches the exact version number specified in your manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.

### CODE REVIEW

**Comment by pyrochlore** [comment]
Update the plugin to version 1.0.1
- Remove dependencies to Node.js modules
- Add example markdown files

**Comment by lishid** [comment]
Seems like you're bundling moment.js in your plugin, which is making it quite large. We have moment.js bundled as well as `window.moment`, you should probably use that one instead of importing your own. 

Here's an example of what you can do: https://github.com/liamcain/obsidian-calendar-plugin/blob/b795a601ed6ed59d0970d0ed1883e207833eeb23/src/main.ts#L16

Also consider auto-formatting your code to normalize spaces vs tabs.

https://github.com/pyrochlore/obsidian-tracker/blob/d9b8795c34f185cd0e566a29b6f3ed1f2f8de88f/src/main.ts#L27
This doesn't seem used.

https://github.com/pyrochlore/obsidian-tracker/blob/d9b8795c34f185cd0e566a29b6f3ed1f2f8de88f/src/main.ts#L35
Here, you should use `this.registerMarkdownCodeBlockProcessor` instead, which will handle the code block automatically for you, as well as unregistering the post processor when your plugin unloads.

https://github.com/pyrochlore/obsidian-tracker/blob/d9b8795c34f185cd0e566a29b6f3ed1f2f8de88f/src/main.ts#L593
This doesn't seem used.

https://github.com/pyrochlore/obsidian-tracker/blob/d9b8795c34f185cd0e566a29b6f3ed1f2f8de88f/src/main.ts#L15
I'd recommend making these instance properties, and making your post processor also an instance function bound to the instance `registerXXX(this.callback.bind(this)`.

**Comment by pyrochlore** [comment]
Thanks for the review.
Fixed in the master branch.
Will release after approval.

**Comment by ericaxu** [comment]
@lishid Please take a look when you have time, thanks!

**Pull request merged**
