### PR TITLE
Added WY Console Theme

### PR DESCRIPTION
**Pull request by Satchelmouth**
A theme for obsidian based on Computer Consoles in popular 80s Sci-fi films

## Repo URL
https://github.com/Satchelmouth/Obsidian-Theme-WYConsole

## Theme Checklist
- [x] My Repo contains all the required files
- [x] Obsidian.css
- [x] Screenshot File
- [x] I have indicated which modes are compatible with my theme
- [x] I have added a LICENSE file
- [x] I have indicated the correct branch for my repo

### CODE REVIEW

**Comment by ericaxu** [comment]
Please fix the JSON formatting issue (missing comma).

Another minor thing: you might want to make the screenshot smaller while keeping the 16:9 aspect ratio. That would make your theme load faster in the theme store. You can still include high resolution screenshots in your README.

We recommend using a screenshot of size 512px by 288px as the featured screenshot to minimize loading time.

**Comment by Satchelmouth** [comment]
Thanks I've updated both now

**Comment by ericaxu** [comment]
Thanks for submitting your theme!

**Comment by Satchelmouth** [comment]
Thanks Erica! 
Do you know when this might appear in the community themes dialogue?

**Comment by Satchelmouth** [comment]
Oh ignore me it's already up :-)

**Pull request merged**
