### PR TITLE
Add plugin OpenGate

### PR DESCRIPTION
**Pull request by nguyenvanduocit**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [OpenGate](https://github.com/nguyenvanduocit/obisdian-open-gate)

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css`
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by WhiteNoiseDev** [comment]
Isn't there already a plugin like this?

I think it's called custom frames. 
Perhaps you wanna collaborate on that?

**Comment by nguyenvanduocit** [comment]
I just saw it. hummmm, this plugin is nice. but ...it's about coding style, and I want to keep my plugin, and push directly to it.

**Comment by nguyenvanduocit** [comment]
I think I release both plugin is better, it's hard for me to contribute to this plugin because of code style, and UX.

**Comment by nguyenvanduocit** [comment]
> ❌ The newly added entry is not at the end, or you are submitting on someone else's behalf. Last plugin in the list is: ptrsvltns/hidden-folder-obsidian

Because my plugin come first but not allowed to be merged

**Comment by nguyenvanduocit** [comment]
@WhiteNoiseDev sorry, but any update on it?

**Comment by WhiteNoiseDev** [comment]
There are 126 pull requests and it's holiday, You are gonna have to wait a while.

**Comment by nguyenvanduocit** [comment]
Happy holiday.

**Comment by liamcain** [comment]
- [onPaneMenu](https://github.com/nguyenvanduocit/obsidian-open-gate/blob/7041fdc45cdc4fe75595051536dd06657e20e9d6/src/GateView.ts#L24) I would suggest keeping the personal plug in the Settings tab instead of adding it to the menu.

**Comment by nguyenvanduocit** [comment]
> * [onPaneMenu](https://github.com/nguyenvanduocit/obsidian-open-gate/blob/7041fdc45cdc4fe75595051536dd06657e20e9d6/src/GateView.ts#L24) I would suggest keeping the personal plug in the Settings tab instead of adding it to the menu.

totaly agree, I will update the plugin

**Pull request merged**
