### PR TITLE
Add plugin: MarkdownSpace Publish

### PR DESCRIPTION
**Pull request by ekrenzin**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/markdown-space/markdownspace-obsidian-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["fundingUrl": "https://vali.ventures",](https://github.com/markdown-space/markdownspace-obsidian-plugin/blob/077fa6e036cffc8cc6e945f92dc748d9f8d90b54/manifest.json#L9)
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link omit this.

[api_key: "INSERT_API_KEY_HERE",](https://github.com/markdown-space/markdownspace-obsidian-plugin/blob/077fa6e036cffc8cc6e945f92dc748d9f8d90b54/main.ts#L19-L22)
These should be empty by default.

[this.app.workspace.detachLeavesOfType(VIEW_TYPE_MARKDOWNSPACE);](https://github.com/markdown-space/markdownspace-obsidian-plugin/blob/077fa6e036cffc8cc6e945f92dc748d9f8d90b54/main.ts#L57)
Do not detach leaves with your custom view here, this is an antipattern, see: <https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Don't+detach+leaves+in+%60onunload%60>
Instead, only create a new leaf, if there is not one already.

[return "markdownspace-view";](https://github.com/markdown-space/markdownspace-obsidian-plugin/blob/077fa6e036cffc8cc6e945f92dc748d9f8d90b54/main.ts#L94), [return "Markdownspace view";](https://github.com/markdown-space/markdownspace-obsidian-plugin/blob/077fa6e036cffc8cc6e945f92dc748d9f8d90b54/main.ts#L98)
Remove the `view` suffix

[`<h1>Project Settings</h1>`](https://github.com/markdown-space/markdownspace-obsidian-plugin/blob/077fa6e036cffc8cc6e945f92dc748d9f8d90b54/src/ProjectSettings.svelte#L9)
[Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)
Also, for section headings in settings use (non Svelte version):
```ts
new Setting(containerEl).setName('name here').setHeading();
```

[Welcome to the Markdownspace Obsidian plugin! This plugin allows you to](https://github.com/markdown-space/markdownspace-obsidian-plugin/blob/077fa6e036cffc8cc6e945f92dc748d9f8d90b54/src/MarkdownspaceApp.svelte#L16-L17)
Avoid including sentences like "This is a plugin for Obsidian that does ..." in your plugin, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[`<h1>Markdownspace Obsidian Plugin!</h1>`](https://github.com/markdown-space/markdownspace-obsidian-plugin/blob/077fa6e036cffc8cc6e945f92dc748d9f8d90b54/src/MarkdownspaceApp.svelte#L14)
Also remove the _Obsidian Plugin_ part here.


[`<h1>File Selector</h1>`](https://github.com/markdown-space/markdownspace-obsidian-plugin/blob/077fa6e036cffc8cc6e945f92dc748d9f8d90b54/src/FileLoader.svelte#L104), [`<h1>Active Document Manager</h1>`](https://github.com/markdown-space/markdownspace-obsidian-plugin/blob/077fa6e036cffc8cc6e945f92dc748d9f8d90b54/src/ActiveDocument.svelte#L46), [<button on:click={publish}>Publish Current File</button>](https://github.com/markdown-space/markdownspace-obsidian-plugin/blob/077fa6e036cffc8cc6e945f92dc748d9f8d90b54/src/ActiveDocument.svelte#L55), [Delete Project](https://github.com/markdown-space/markdownspace-obsidian-plugin/blob/077fa6e036cffc8cc6e945f92dc748d9f8d90b54/src/components/settings/RemoveProjectButton.svelte#L7), [Add Project](https://github.com/markdown-space/markdownspace-obsidian-plugin/blob/077fa6e036cffc8cc6e945f92dc748d9f8d90b54/src/components/settings/AddProjectButton.svelte#L15), [<label for="project-id">Active Project</label>](https://github.com/markdown-space/markdownspace-obsidian-plugin/blob/077fa6e036cffc8cc6e945f92dc748d9f8d90b54/src/components/settings/ActiveProjectSelector.svelte#L22)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by ekrenzin** [comment]
Hey @joethei, thank you for the awesome review! I appreciate your efforts. I made the requested changes, hopefully the MarkdownSpace plugin can be approved now :)

Let me know if there is anything else I need to do. Thanks a million!

**Comment by liamcain** [comment]
Added in this commit: https://github.com/obsidianmd/obsidian-releases/commit/abb1fc09b4cfc864b70b757208e73b521bd1632c

**Comment by joethei** [comment]
Hi @ekrenzin
Could you make sure that the plugin can be installed?
Currently it fails because `v` is not allowed in a release name.

**Pull request closed without merging**
