### PR TITLE
Add plugin: Movie Search

### PR DESCRIPTION
**Pull request by Gubchik123**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Gubchik123/obsidian-movie-search-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
What sets your plugin apart from the MediaDB, Movie or moviegrabber plugin?

[callback: () => this.insert_data(),](https://github.com/Gubchik123/obsidian-movie-search-plugin/blob/bdf2999e60b82a11216dc3e2a7ba503fd6d8bf75/src/main.ts#L41)
Use a `editorCallback` instead, which will make sure that the command only shows up in the command pallete if there is an active editor.
Then pass the editor instance into the insert_data function instead of using the getActiveViewOfType function
<https://docs.obsidian.md/Plugins/User+interface/Commands#Editor+commands>

[contentEl.createEl("h2", { text: "Service Provider Setting" });](https://github.com/Gubchik123/obsidian-movie-search-plugin/blob/bdf2999e60b82a11216dc3e2a7ba503fd6d8bf75/src/views/setting_service_provider_modal.ts#L22)
[Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)
and for section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```

[contentEl.createEl("h2", { text: "Search Movie" });](https://github.com/Gubchik123/obsidian-movie-search-plugin/blob/bdf2999e60b82a11216dc3e2a7ba503fd6d8bf75/src/views/movie_search_modal.ts#L56), [.setName("Service Provider")](https://github.com/Gubchik123/obsidian-movie-search-plugin/blob/bdf2999e60b82a11216dc3e2a7ba503fd6d8bf75/src/settings/settings.ts#L132), [.setName("Include Adult")](https://github.com/Gubchik123/obsidian-movie-search-plugin/blob/bdf2999e60b82a11216dc3e2a7ba503fd6d8bf75/src/settings/settings.ts#L168)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[export function parse_(frontmatter: string) {](https://github.com/Gubchik123/obsidian-movie-search-plugin/blob/bdf2999e60b82a11216dc3e2a7ba503fd6d8bf75/src/utils/utils.ts#L61-L79)
Use the `parseYaml` function from the API instead.

[export function to_string_(frontmatter: object): string {](https://github.com/Gubchik123/obsidian-movie-search-plugin/blob/bdf2999e60b82a11216dc3e2a7ba503fd6d8bf75/src/utils/utils.ts#L81-L95)
Use the `stringifyYaml` function from the API instead.

[createHeader(containerEl, "General Settings");](https://github.com/Gubchik123/obsidian-movie-search-plugin/blob/bdf2999e60b82a11216dc3e2a7ba503fd6d8bf75/src/settings/settings.ts#L63)
[Don't use a "general" heading in your settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by Gubchik123** [comment]
> What sets your plugin apart from the MediaDB, Movie or moviegrabber plugin?

My Movie Search plugin stands out for its robust multilanguage support. Unlike other plugins such as MediaDB, Movie, or Movie Grabber, Movie Search offers users the flexibility to set their preferred language in the settings or opt for automatic detection based on the search query. This means that movie results will be presented in the user's selected language, enhancing the overall user experience and accessibility.

**Update: Minor Changes Implemented**

I've addressed the requested minor changes as per your feedback. You can review the updates in the latest commit [here](https://github.com/Gubchik123/obsidian-movie-search-plugin/commit/35eb9c348b84cec52470836804e1a2fc3469ccb3).

**Comment by joethei** [comment]
[.setName("New File Location")](https://github.com/Gubchik123/obsidian-movie-search-plugin/blob/97229929fecc60a09a33e9c9547c0bd9ca9bfd76/src/settings/settings.ts#L66), [.setName("New File Name Format")](https://github.com/Gubchik123/obsidian-movie-search-plugin/blob/97229929fecc60a09a33e9c9547c0bd9ca9bfd76/src/settings/settings.ts#L92), [text: "Example Template",](https://github.com/Gubchik123/obsidian-movie-search-plugin/blob/97229929fecc60a09a33e9c9547c0bd9ca9bfd76/src/settings/settings.ts#L113), [.setName("Template File")](https://github.com/Gubchik123/obsidian-movie-search-plugin/blob/97229929fecc60a09a33e9c9547c0bd9ca9bfd76/src/settings/settings.ts#L117), [.setName("Preferred Locale")](https://github.com/Gubchik123/obsidian-movie-search-plugin/blob/97229929fecc60a09a33e9c9547c0bd9ca9bfd76/src/settings/settings.ts#L133), [.setName("Open New Movie Note")](https://github.com/Gubchik123/obsidian-movie-search-plugin/blob/97229929fecc60a09a33e9c9547c0bd9ca9bfd76/src/settings/settings.ts#L154), [.setName("Service Provider")](https://github.com/Gubchik123/obsidian-movie-search-plugin/blob/97229929fecc60a09a33e9c9547c0bd9ca9bfd76/src/settings/settings.ts#L163), [.setName("Include Adult")](https://github.com/Gubchik123/obsidian-movie-search-plugin/blob/97229929fecc60a09a33e9c9547c0bd9ca9bfd76/src/settings/settings.ts#L200)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by Gubchik123** [comment]
> [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

Updated the case in the settings as requested. You can review the changes in the latest commit [here](https://github.com/Gubchik123/obsidian-movie-search-plugin/commit/e1fa7268c1ec068514aefbac9af375a0c4dfea0f).

**Pull request merged**
