### PR TITLE
Add text2anki-openai plugin

### PR DESCRIPTION
**Pull request by manibatra**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/manibatra/obsidian-text2anki-openai/releases/tag/1.0.0

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [ ] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[if (!noteFile?.name) return; // Nothing Open](https://github.com/manibatra/obsidian-text2anki-openai/blob/85b49362fd811bbf594da3018f03704e42f0c189/main.ts#L65)
It's better to check `noteFile === null`

[const response = await fetch("http://localhost:8765", {](https://github.com/manibatra/obsidian-text2anki-openai/blob/85b49362fd811bbf594da3018f03704e42f0c189/main.ts#L206-L213)
Use the `requestUrl` function from the Obsidian API instead.

**Comment by manibatra** [comment]
@joethei plugin code and release updated.

**Comment by manibatra** [comment]
@joethei These are the ones requested : 
https://github.com/manibatra/obsidian-text2anki-openai/commit/1905f599b9ef5a07d2b2f09261f4fbc4307c4f50
https://github.com/manibatra/obsidian-text2anki-openai/commit/1db6ea57f8da872720673cb647d16f89b27bc47d

Included in the release.

**Comment by joethei** [comment]
Ah, there

**Pull request merged**
