### PR TITLE
Add "Azure Blob Sync" plugin

### PR DESCRIPTION
**Pull request by notmike101**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/notmike101/obsidian-azure-blob-sync

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[const fileContent = await this.app.vault.cachedRead(fileOrFolder as TFile);](https://github.com/notmike101/obsidian-azure-blob-sync/blob/9cc2ce9014f877b2c9f181c8ec79fb5f24908476/src/main.ts#L122)
You should not cast this here, do a `instanceof` check first.

**Comment by notmike101** [comment]
@joethei Updated to address that in version 1.2.3, please let me know if there's anything else.

**Comment by ericaxu** [comment]
@notmike101 Hi there, are you still working on this plugin? Just checking!

**Comment by notmike101** [comment]
@ericaxu Yes, just haven't had much time lately. Plan to pick it back up this week and make the suggested changes above for review.

**Comment by liamcain** [comment]
Hi @notmike101, the requested changes from a couple months ago look super minor. I think this is safe to merge, but just want to make sure you're okay with this still going in!

**Review by liamcain — APPROVED** [review]

**Comment by liamcain** [comment]
Hi @notmike101, I hope you're doing well. Just wanted to see if you saw my last message regarding getting this merged. Thanks!

**Comment by notmike101** [comment]
Hello all,

My apologies, but I am no longer working on this.

**Pull request closed without merging**
