### PR TITLE
Add plugin: Recipe view

### PR DESCRIPTION
**Pull request by lachholden**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/lachholden/obsidian-recipe-view

## Release Checklist
- [X] I have tested the plugin on
  - [ ]  Windows
  - [X]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [X]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by liamcain** [comment]
- [toggleView(this: RecipeViewPlugin, checking: boolean) {](https://github.com/lachholden/obsidian-recipe-view/blob/6f759423664617de9d274e42a9e3f9c5acda332c/src/main.ts#L48) I recommend avoiding passing `this` as an argument since it shadows the `this` reference to the current plugin and makes it really confusing to trace in the code.
- [this.toggleView(c),](https://github.com/lachholden/obsidian-recipe-view/blob/6f759423664617de9d274e42a9e3f9c5acda332c/src/main.ts#L34) the function call signature looks wrong here since the first argument its expecting is the plugin
- [SampleSettingTab](https://github.com/lachholden/obsidian-recipe-view/blob/6f759423664617de9d274e42a9e3f9c5acda332c/src/main.ts#L94) rename this to something else
- [store.plugin.set(this.plugin);](https://github.com/lachholden/obsidian-recipe-view/blob/6f759423664617de9d274e42a9e3f9c5acda332c/src/recipe-view.ts#L31) this should probably happen in the Plugin itself, not in the View, which could get opened multiple times (and it will stay the same plugin)
- [inNewLeaf](https://github.com/lachholden/obsidian-recipe-view/blob/6f759423664617de9d274e42a9e3f9c5acda332c/src/recipe-view.ts#L47) you can use [`Keymap.isModEvent`](https://github.com/obsidianmd/obsidian-api/blob/009a10f196df551256a5894ea60fdf9ddaab19a1/obsidian.d.ts#L1639) instead

**Comment by lachholden** [comment]
@liamcain Great, thanks for that! I've made those changes and included them in an 0.3.1 release.

**Comment by lachholden** [comment]
@liamcain just checking – is there anything else I need to do to get this re-reviewed? Doesn't look like I can change any of the labels etc.

**Comment by liamcain** [comment]
Looks good, sorry for the delay!

**Comment by lachholden** [comment]
All good, thank you! :)

**Pull request merged**
