### PR TITLE
Add plugin: Ribbon Divider

### PR DESCRIPTION
**Pull request by andrewmcgivery**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/andrewmcgivery/obsidian-ribbon-divider

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "A plugin for Obsidian.MD that allows you to add dividers to the ribbon to space out your icons.",](https://github.com/andrewmcgivery/obsidian-ribbon-divider/blob/11a10f4ddaf048c843951c94539e6a516fc881a7/manifest.json#L6)
Avoid including sentences like "This is a plugin for Obsidian that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[if (process.env.NODE_ENV === "development") {](https://github.com/andrewmcgivery/obsidian-ribbon-divider/blob/11a10f4ddaf048c843951c94539e6a516fc881a7/main.ts#L19-L24)
There is a hot-reload plugin for this, also, it looks like this code is the only reason why this plugin is not mobile compatible.

[containerEl.createEl("h1", { text: "Ribbon Dividers" });](https://github.com/andrewmcgivery/obsidian-ribbon-divider/blob/11a10f4ddaf048c843951c94539e6a516fc881a7/main.ts#L118)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[containerEl.createEl("h2", { text: "Configure Dividers" });](https://github.com/andrewmcgivery/obsidian-ribbon-divider/blob/11a10f4ddaf048c843951c94539e6a516fc881a7/main.ts#L127)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[.createEl("button", { text: "New Divider", cls: "mod-cta" })](https://github.com/andrewmcgivery/obsidian-ribbon-divider/blob/11a10f4ddaf048c843951c94539e6a516fc881a7/main.ts#L151)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by andrewmcgivery** [comment]
> ["description": "A plugin for Obsidian.MD that allows you to add dividers to the ribbon to space out your icons.",](https://github.com/andrewmcgivery/obsidian-ribbon-divider/blob/11a10f4ddaf048c843951c94539e6a516fc881a7/manifest.json#L6)
Avoid including sentences like "This is a plugin for Obsidian that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here:

This is so embarrassing... I actually had fixed this and forgot to push to my branch LOL

Same with all the the settings screen comments x_X Will get that all pushed up now.

**Comment by andrewmcgivery** [comment]
> [if (process.env.NODE_ENV === "development") {](https://github.com/andrewmcgivery/obsidian-ribbon-divider/blob/11a10f4ddaf048c843951c94539e6a516fc881a7/main.ts#L19-L24)
There is a hot-reload plugin for this, also, it looks like this code is the only reason why this plugin is not mobile compatible.

So, it wont actually affect mobile because `minifySyntax` in my esbuild config causes this statement to be tree shaken out of the final js build.

The reason it isn't mobile compatible currently is because of my use of the `crypto` package here: https://github.com/andrewmcgivery/obsidian-ribbon-divider/blob/main/main.ts#L153

Also, I saw the hot reload plugin but prefer this way as for my uses, it is lightweight and "the esbuild way". :)

**Comment by andrewmcgivery** [comment]
Also thank you for the review @joethei! I know you've been going through a pretty big backlog! :) Hope you get some time to rest and relax over the holidays! :)

**Pull request merged**
