### PR TITLE
Add plugin: PopKit

### PR DESCRIPTION
**Pull request by zhouhua**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/zhouhua/obsidian-popkit

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by zhouhua** [comment]
/skip

innerHTML is used in this code, just translating markdown to html. It's unrelated to the content on the Obsidian page and poses no security risks.

```typescript
const div = createDiv();
await MarkdownRenderer.render(
  app,
  selection,
  div,
  '',
  new MarkdownRenderChild(div),
);
const html = div.innerHTML;
div.remove();
```

**Comment by zhouhua** [comment]
Hi @joethei, when I skipped the automatic checks, the GitHub Actions command to assign a reviewer encountered an error, preventing it from automatically requesting your review for this PR.

image

**Comment by joethei** [comment]
[id: "popkit-open-popover",](https://github.com/zhouhua/obsidian-popkit/blob/8fcfdf3398913161230a57e81cc08b17114e809e/src/Plugin.ts#L22), 
Don't prefix the command id with the plugin id, Obsidian will make sure that there are no conflicts with other plugins.

[hotkeys: [{ modifiers: ["Mod"], key: "." }],](https://github.com/zhouhua/obsidian-popkit/blob/8fcfdf3398913161230a57e81cc08b17114e809e/src/Plugin.ts#L24)
We recommend against providing a default hotkey when possible. The reason being that it's easy to pick a hotkey that a user already has configured and they could get confused when that key doesn't do what they expect. Also, it's hard choosing a safe default hotkey that's available for all operating systems & does not conflict with existing plugins.

[handlerString: `](https://github.com/zhouhua/obsidian-popkit/blob/8fcfdf3398913161230a57e81cc08b17114e809e/src/actions/clipboard.ts#L9-L12), [handlerString: `](https://github.com/zhouhua/obsidian-popkit/blob/8fcfdf3398913161230a57e81cc08b17114e809e/src/actions/clipboard.ts#L19-L21), [handlerString: `](https://github.com/zhouhua/obsidian-popkit/blob/8fcfdf3398913161230a57e81cc08b17114e809e/src/actions/clipboard.ts#L27-L30), [const fn = new AsyncFunction("context", action.handlerString);](https://github.com/zhouhua/obsidian-popkit/blob/8fcfdf3398913161230a57e81cc08b17114e809e/src/components/Item.tsx#L93-L94)
This should not be done this way, use actual callbacks and don't use code evaluation.

[name: 'copy HTML',](https://github.com/zhouhua/obsidian-popkit/blob/8fcfdf3398913161230a57e81cc08b17114e809e/src/actions/clipboard.ts#L35)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by zhouhua** [comment]
@joethei Thank you for your review comments. I have already fixed those issues.

I have one issue I'd like to discuss. In my code, I've designed something called ﻿handlerString that receives a string and executes it as code (I've removed the related references for now). The goal is to enable users of this plugin to freely add their own custom tools in the future, rather than only using the built-in tools I've written or submitting MRs to my repository. This definitely introduces some security risks, but I'm not sure if there's a better approach.

**Comment by zhouhua** [comment]
@joethei Could you help review again?

**Comment by zhouhua** [comment]
@joethei Could you help review again?

**Comment by joethei** [comment]
[help: 'Open obsidian help',](https://github.com/zhouhua/obsidian-popkit/blob/45eb65c175a3d904bd14344fff4ebcb8c3c8877d/i18n/en/index.ts#L5-L6), [help: '打开 Obsidian 帮助',](https://github.com/zhouhua/obsidian-popkit/blob/45eb65c175a3d904bd14344fff4ebcb8c3c8877d/i18n/zh/index.ts#L5-L6)
Remove "Obsidian" here.


[customTitle: 'Add Custom Action',](https://github.com/zhouhua/obsidian-popkit/blob/45eb65c175a3d904bd14344fff4ebcb8c3c8877d/i18n/en/index.ts#L57), [plugin: 'Source Plugin: ',](https://github.com/zhouhua/obsidian-popkit/blob/45eb65c175a3d904bd14344fff4ebcb8c3c8877d/i18n/en/index.ts#L59)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[import dayjs from 'dayjs';](https://github.com/zhouhua/obsidian-popkit/blob/45eb65c175a3d904bd14344fff4ebcb8c3c8877d/src/actions/date.ts#L2)
Instead of importing an external library use moment, since that is already bundled with Obsidian: `import {moment} from "obsidian"`

**Comment by zhouhua** [comment]
@joethei Could you help review again?

**Pull request merged**
