### PR TITLE
Add plugin: Journal Folder

### PR DESCRIPTION
**Pull request by chfourie**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[import moment from 'moment/moment'](https://github.com/chfourie/obsidian-journal-folder/blob/a042ebe7b8f33e84ea6cf9a57ca7d962eb230c1e/src/data-access/journal-note.ts#L20)
Use `import {moment} from 'obsidian'` instead.

**Comment by chfourie** [comment]
> [import moment from 'moment/moment'](https://github.com/chfourie/obsidian-journal-folder/blob/a042ebe7b8f33e84ea6cf9a57ca7d962eb230c1e/src/data-access/journal-note.ts#L20) Use `import {moment} from 'obsidian'` instead.

I changed import as requested.  As a result I had to change the function calls moment(...) to window.moment(...).  The IDE now suggests that the above import is unused.  As I noted in the source code...

```typescript
// IDE suggests this is declared but not read.
// Liam Cain seems to suggest using...
// import { Moment } from moment
// ... in combination with ...
// window.window.moment(...)
// refer to:
// - https://publish.obsidian.md/tasks-contributing/Code/How+do+I+use+Moment+in+src
// - https://liamca.in/Obsidian/API+FAQ/third-party/use+momentjs
// I am not sure what I should do here
import { moment } from 'obsidian'
```

**Comment by joethei** [comment]
Lima's site is quite outdated 

The recommendation is to use
```
import { moment } from "obsidian";
```
(see the end of https://docs.obsidian.md/Plugins/Events)

and if neccessary `import type { Moment } from 'moment';`

And it should be possible to remove the `window.`

**Comment by joethei** [comment]
hm, that is strange, it works in my plugins.

**Pull request merged**
