### PR TITLE
Add Oblogger

### PR DESCRIPTION
**Pull request by msphair**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

https://github.com/loftTech/obsidian-oblogger

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
You should include images in your README, to showcase what the plugin does.

["description": "tagger explorer and frontmatter logger plugin for obsidian",](https://github.com/loftTech/obsidian-oblogger/blob/6c581a994a1dcc012da6d20ef46aa24bafeebe2a/manifest.json#L6)
We have recently published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "plugin for Obsidian" in your description.

["author": "loftTech <lofttechinc@gmail.com>",](https://github.com/loftTech/obsidian-oblogger/blob/6c581a994a1dcc012da6d20ef46aa24bafeebe2a/manifest.json#L7)
This field is displayed in the sidebar and in the description for the plugin details page. Are you sure you want to have your email listed so prominently?
image

[id: "open-oblogger-log-logger",](https://github.com/loftTech/obsidian-oblogger/blob/6c581a994a1dcc012da6d20ef46aa24bafeebe2a/src/main.ts#L88)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

[name: "Oblogger Log Logger...",](https://github.com/loftTech/obsidian-oblogger/blob/6c581a994a1dcc012da6d20ef46aa24bafeebe2a/src/main.ts#L89)
Similar thing here, 

[this.registerInterval(window.setTimeout(() => {](https://github.com/loftTech/obsidian-oblogger/blob/6c581a994a1dcc012da6d20ef46aa24bafeebe2a/src/main.ts#L105-L107)
Use this instead:
```ts
this.app.workspace.onLayoutReady(() => {
	this.activateSidePane();
});
```

[this.app.workspace.detachLeavesOfType(VIEW_TYPE_OBLOGGER);](https://github.com/loftTech/obsidian-oblogger/blob/6c581a994a1dcc012da6d20ef46aa24bafeebe2a/src/main.ts#L112)
Do not detach leaves with your custom view in `onunload`, this is an antipattern, see: <https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Don't+detach+leaves+in+%60onunload%60>

[if (adapter instanceof FileSystemAdapter) {](https://github.com/loftTech/obsidian-oblogger/blob/6c581a994a1dcc012da6d20ef46aa24bafeebe2a/src/oblogger_view.ts#L313-L317)
This will only work on desktop, instead check if `this.app.vault.getAbstractFileByPath(this.settings.avatarPath) instanceof TFile`


[const maybeFolder = f as TFolder;](https://github.com/loftTech/obsidian-oblogger/blob/6c581a994a1dcc012da6d20ef46aa24bafeebe2a/src/logger_modal.ts#L65-L66)
You should not cast this, instead do:
```ts
if(f instanceof TFolder) {
	const logType...
}
```

[if (!this.app.vault.getAbstractFileByPath(this.settings.loggingPath)) {](https://github.com/loftTech/obsidian-oblogger/blob/6c581a994a1dcc012da6d20ef46aa24bafeebe2a/src/logger_modal.ts#L350)
You should check if it's actually a folder, and not just a file with no extension.

**Comment by msphair** [comment]
thanks for the feedback!

I've made a new release (0.7.4) that addresses most of your comments and have responded to the individual comments line by line.


> You should include images in your README, to showcase what the plugin does.

it's a good idea. it looks like the image links broke recently. should be fixed now

> Avoid including sentences like "plugin for Obsidian" in your description.

removed.


> This field is displayed in the sidebar and in the description for the plugin details page. Are you sure you want to have your email listed so prominently?

removed.


> `id: "open-oblogger-log-logger",` Obsidian will automatically prefix the command id with the plugin id, you don't need to include it yourself.

the name wasn't to disambiguate, it was to have a fun rhyme


> `name: "Oblogger Log Logger...",` Similar thing here

same thing, just a fun rhyme that we'd rather keep


> `this.registerInterval(window.setTimeout(() => {` Use this instead:

changed.


> `this.app.workspace.detachLeavesOfType(VIEW_TYPE_OBLOGGER);` Do not detach leaves with your custom view in onunload, this is an antipattern, see: https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Don't+detach+leaves+in+%60onunload%60

removed.


> `if (adapter instanceof FileSystemAdapter) {` This will only work on desktop, instead check if `this.app.vault.getAbstractFileByPath(this.settings.avatarPath) instanceof TFile`

changed.


> `const maybeFolder = f as TFolder;` You should not cast this, instead do:

fixed.


> `if (!this.app.vault.getAbstractFileByPath(this.settings.loggingPath)) {` You should check if it's actually a folder, and not just a file with no extension.

I don't think we want to check that because the next step after this check is creating the folder. If we only check if `this.settings.loggingPath` is a folder and if it exists as a file with no extension, then the check will pass (because it isn't a folder) but creation of the folder will fail because the file already exists.

**Comment by msphair** [comment]
released [0.7.5](https://github.com/loftTech/obsidian-oblogger/releases/tag/0.7.5)

**Comment by msphair** [comment]
released [0.7.6](https://github.com/loftTech/obsidian-oblogger/releases/tag/0.7.6)

**Comment by joethei** [comment]
> > `if (!this.app.vault.getAbstractFileByPath(this.settings.loggingPath)) {` You should check if it's actually a folder, and not just a file with no extension.
> 
> I don't think we want to check that because the next step after this check is creating the folder. If we only check if `this.settings.loggingPath` is a folder and if it exists as a file with no extension, then the check will pass (because it isn't a folder) but creation of the folder will fail because the file already exists.

If there is a file with no extension your code will just silently fail, no?

**Comment by msphair** [comment]
>>> if (!this.app.vault.getAbstractFileByPath(this.settings.loggingPath)) { You should check if it's actually a folder, and not just a file with no extension.
>>
>> I don't think we want to check that because the next step after this check is creating the folder. If we only check if this.settings.loggingPath is a folder and if it exists as a file with no extension, then the check will pass (because it isn't a folder) but creation of the folder will fail because the file already exists.
>
> If there is a file with no extension your code will just silently fail, no?

that's a good catch. fix incoming

**Comment by msphair** [comment]
@joethei [0.7.7](https://github.com/loftTech/obsidian-oblogger/releases/tag/0.7.7) released with the fix. thanks for the careful consideration and bug catch! :)

**Comment by robotbrad** [comment]
released [0.7.8](https://github.com/loftTech/obsidian-oblogger/releases/tag/0.7.8)

**Comment by robotbrad** [comment]
released [0.7.9](https://github.com/loftTech/obsidian-oblogger/releases/tag/0.7.9)

**Comment by robotbrad** [comment]
released [0.8.0](https://github.com/loftTech/obsidian-oblogger/releases/tag/0.8.0)

**Comment by msphair** [comment]
@liamcain and @joethei I know you guys are probably busy with the new release, but is there anything else we need to do on this to get it merged? Thanks!

**Comment by liamcain** [comment]
- [await this.getObloggerView()?.requestRender();](https://github.com/loftTech/obsidian-oblogger/blob/42105c2d9dcb79df0b4c7f8d5c3adb69cd646ec2/src/main.ts#L48) I suggest moving these event listeners onto the view itself. More direct and easier data flow than forwarding them along from the plugin -> view.

**Pull request merged**
