### PR TITLE
Add plugin: Folder by tags distributor

### PR DESCRIPTION
**Pull request by l-you**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["name": "Folder By Tags Distributor",](https://github.com/RevoTale/obsidian-folder-by-tags-distributor/blob/cf1b74e3fee3e020e6396e55908246bab7c44111/manifest.json#L3)
This should be using sentence case.

["minAppVersion": "0.15.0",](https://github.com/RevoTale/obsidian-folder-by-tags-distributor/blob/cf1b74e3fee3e020e6396e55908246bab7c44111/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

["description": "Automatically move Obsidian notes into existing folders by tags specified in note.",](https://github.com/RevoTale/obsidian-folder-by-tags-distributor/blob/cf1b74e3fee3e020e6396e55908246bab7c44111/manifest.json#L6)
Don't include the word "Obsidian" here.

[if (this.settings.addRibbon) {](https://github.com/RevoTale/obsidian-folder-by-tags-distributor/blob/cf1b74e3fee3e020e6396e55908246bab7c44111/main.ts#L190-L194), [new Setting(containerEl)](https://github.com/RevoTale/obsidian-folder-by-tags-distributor/blob/cf1b74e3fee3e020e6396e55908246bab7c44111/src/PluginSettingsTab.ts#L18-L29)
As of v1.1.0 of Obsidian, the ribbon can be customized within Obsidian. So users can choose what items to include and in what order all in one place. Because of this, we're recommending that new plugins avoid introducing their own toggles for ribbon items.

[.setName("Use FrontMatter tags for folder resolver")](https://github.com/RevoTale/obsidian-folder-by-tags-distributor/blob/cf1b74e3fee3e020e6396e55908246bab7c44111/src/PluginSettingsTab.ts#L31)
It's called "frontmatter"

**Comment by l-you** [comment]
@joethei I have done your fixes, please review again

**Comment by l-you** [comment]
Hey @joethei , should I open a new PR to proceed the submission?

**Comment by joethei** [comment]
No, I'll take a look soon

**Comment by joethei** [comment]
Sorry for the delay.

**Pull request merged**
