### PR TITLE
Add plugin: mpv links

### PR DESCRIPTION
**Pull request by patsh90**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["name": "Mpv links",](https://github.com/patsh90/mpv-obsidian-plugin/blob/111bc8cc18727ded922b718be452b4730e4fa10e/manifest.json#L3), [# MPV Links Plugin for Obsidian](https://github.com/patsh90/mpv-obsidian-plugin/blob/111bc8cc18727ded922b718be452b4730e4fa10e/README.md#L1)
Use the proper capitalization of the brand name "mpv"

[const {dialog} = require('electron').remote;](https://github.com/patsh90/mpv-obsidian-plugin/blob/111bc8cc18727ded922b718be452b4730e4fa10e/src/main.ts#L168)
Please stick to one import style.

[title: "Select Video Files",](https://github.com/patsh90/mpv-obsidian-plugin/blob/111bc8cc18727ded922b718be452b4730e4fa10e/src/main.ts#L182)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[Notice => new Notice(`3D graph: ${message}`, duration);](https://github.com/patsh90/mpv-obsidian-plugin/blob/111bc8cc18727ded922b718be452b4730e4fa10e/src/util/createNotice.ts#L6-L7)
Wrong text.

[console.log("parsed loaded data successfully");](https://github.com/patsh90/mpv-obsidian-plugin/blob/111bc8cc18727ded922b718be452b4730e4fa10e/src/SettingManager.ts#L142), [console.log("parsed loaded data successfully");](https://github.com/patsh90/mpv-obsidian-plugin/blob/111bc8cc18727ded922b718be452b4730e4fa10e/src/SettingManager.ts#L118), [console.log("loaded: ", loadedData);](https://github.com/patsh90/mpv-obsidian-plugin/blob/111bc8cc18727ded922b718be452b4730e4fa10e/src/SettingManager.ts#L98)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

You aren't making any use of the code from the plugin template you used, remove those.

**Comment by patsh90** [comment]
Changes done.

**Comment by patsh90** [comment]
@joethei Changes done. Removed unused code and turned off logging.

**Comment by joethei** [comment]
The import style was not changed

**Comment by patsh90** [comment]
@joethei  I changed  `const {dialog} = require('electron').remote` to  [`import { dialog } from '@electron/remote';`](https://github.com/patsh90/mpv-obsidian-plugin/blob/9438e430ca873c93ed9e7046a605b2c080b2febb/src/main.ts#L168)  so as per version 1.0.2 all import in main.ts use ES Module import syntax.  So all imports have same style.

**Pull request merged**
