### PR TITLE
Add plugin: Cursor Position on Title Enter

### PR DESCRIPTION
**Pull request by chaintng**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/chaintng/cursor-position-on-title-enter

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [ ] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by chaintng** [comment]
fixed kub

**Comment by Zachatoo** [comment]
[console.log("Cursor Position Plugin Loaded");](https://github.com/chaintng/cursor-position-on-title-enter/blob/dfde1528540074765eedf88b7a86add98fdc778c/main.ts#L16), [console.log("Cursor Position Plugin Unloaded");](https://github.com/chaintng/cursor-position-on-title-enter/blob/dfde1528540074765eedf88b7a86add98fdc778c/main.ts#L53)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

---

[This is a simple Obsidian plugin that lets you set the cursor position after pressing Enter on the note title.](https://github.com/chaintng/cursor-position-on-title-enter/blob/dfde1528540074765eedf88b7a86add98fdc778c/README.md#L5)
I would recommend updating the README to clarify which title your plugin is referring to. It could be referencing either the inline title or the title in the tab title bar. Or I would recommend updating your plugin to support both.
image

**Comment by joethei** [comment]
["description": "A plugin to set the cursor position after pressing Enter on the note title.",](https://github.com/chaintng/cursor-position-on-title-enter/blob/1c46e9dd793340e249618b7e446996b34797e2d1/manifest.json#L6)
Remove the "A plugin to" part of the description, it should be a given since this is only shown when browsing plugins through the app or on our website.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[event.srcElement](https://github.com/chaintng/cursor-position-on-title-enter/blob/1c46e9dd793340e249618b7e446996b34797e2d1/main.ts#L27), [event.srcElement](https://github.com/chaintng/cursor-position-on-title-enter/blob/1c46e9dd793340e249618b7e446996b34797e2d1/main.ts#L27)
`srcElement` has been deprecated for a long time, use `event.target`

["Last Known Cursor](https://github.com/chaintng/cursor-position-on-title-enter/blob/1c46e9dd793340e249618b7e446996b34797e2d1/main.ts#L78), ["Beginning of Note"](https://github.com/chaintng/cursor-position-on-title-enter/blob/1c46e9dd793340e249618b7e446996b34797e2d1/main.ts#L79), ["Last Line of Note"](https://github.com/chaintng/cursor-position-on-title-enter/blob/1c46e9dd793340e249618b7e446996b34797e2d1/main.ts#L80)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by chaintng** [comment]
@joethei would u mind help check ? it didn't tag `Ready for review` automatically

**Comment by joethei** [comment]
You haven't changed the description

**Pull request merged**
