### PR TITLE
Added Commando plugin

### PR DESCRIPTION
**Pull request by qaptoR**
# I am submitting a new Community Plugin
Commando Plugin

Adds a 'Commando Palette' for running commands repeatedly using either the vim numeric prefix buffer, or information requested each time the commando palette is opened (ie. loop count, delay time).

Best used with low-key commands, with determinable outcomes.

## Repo URL

Link to my plugin: 
https://github.com/qaptoR/Commando

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Please fill out the pull request template.

**Comment by qaptoR** [comment]
@joethei 
Thanks for letting me know something is missing. I thought I followed the steps in the obsidian docs.

What is it exactly that I've forgotten to do?

**Comment by joethei** [comment]
In your original message there is a link, please click in to get the template.
Then fill this template.

**Comment by qaptoR** [comment]
@joethei 
I'm not sure what is wrong, but I know what happened. When I originally clicked the link the first time I was filling it out I think I already changed some of the text which might be what is causing the link to not work.

Because when I clicked it then, and when I click it now it just opens this page again with nothing changed.

At the time I just assumed it was generating a link to this page for some internal documentation purpose, but I think whatever automation is supposed to be happening is failing.

I'm using microsoft edge browser, but I've tried clicking the link on another browser and it fails there as well.

**Comment by joethei** [comment]
["fundingUrl": "",](https://github.com/qaptoR/Commando/blob/f7d6a551f5ca8167e2b46ed9f4b996725485a63f/manifest.json#L9)
If you don't have one, remove this.

I generally recommend moving all code files into a separate `src` folder, that makes it easier to review and maintain.

[import { buffer } from 'stream/consumers';](https://github.com/qaptoR/Commando/blob/f7d6a551f5ca8167e2b46ed9f4b996725485a63f/main.ts#L6)
Unused, and using this would break on mobile, as Node.js is not available there.

[return this.app.vault.config.vimMode;](https://github.com/qaptoR/Commando/blob/f7d6a551f5ca8167e2b46ed9f4b996725485a63f/main.ts#L48)
Better to use `this.app.vault.getConfig("vimMode")`, as that will handle defaults.
This function is also not used.

[id: "commando-repeat-command",](https://github.com/qaptoR/Commando/blob/f7d6a551f5ca8167e2b46ed9f4b996725485a63f/main.ts#L114)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

[containerEl.createEl('h2', {text: 'Settings for my awesome plugin.'});](https://github.com/qaptoR/Commando/blob/f7d6a551f5ca8167e2b46ed9f4b996725485a63f/settings.ts#L29)
Change or remove this.

**Comment by qaptoR** [comment]
@joethei 
I've updated the plugin with the changes you mentioned.

**Comment by liamcain** [comment]
- [plguin](https://github.com/qaptoR/Commando/blob/67cae75cd009b17d38b0c23419dffb3c8063a11b/README.md#L5) typo
- [commands](https://github.com/qaptoR/Commando/blob/67cae75cd009b17d38b0c23419dffb3c8063a11b/src/vim-modal.ts#L86) you should use `listCommands()` instead, which properly will work with commands that need to call checkCallback before they should be displayed in the command list.

**Comment by qaptoR** [comment]
@joethei
I've fixes that typo (and all others I could find using Word)
as well as updated the `getItems()` function to now use `listCommands()`

**Pull request merged**
