### PR TITLE
Add Upcoming plugin

### PR DESCRIPTION
**Pull request by charliecm**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/charliecm/obsidian-upcoming

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by ericaxu** [comment]
Please add it to the bottom, thanks!

**Comment by liamcain** [comment]
Hi, sorry for the delay in getting to this review!

---

https://github.com/charliecm/obsidian-upcoming/blob/a90ec055d6ed31f7429246e049e99297f5ea1d64/main.ts#L35 `getActiveViewOfType` can return `null`. You should check before trying to access `.leaf`

https://github.com/charliecm/obsidian-upcoming/blob/a90ec055d6ed31f7429246e049e99297f5ea1d64/main.ts#L36-L37 Why are you accessing `id` here?

https://github.com/charliecm/obsidian-upcoming/blob/a90ec055d6ed31f7429246e049e99297f5ea1d64/main.ts#L43 to check if the active file is a daily note, you're better off using the [`daily-note-interface` package](https://github.com/liamcain/obsidian-daily-notes-interface) which automatically reads the format and folder path from the daily notes plugin and also handles additional edge cases, like users that have nested formats (`YYYY/MM/YYYY-MM-DD`).

https://github.com/charliecm/obsidian-upcoming/blob/a90ec055d6ed31f7429246e049e99297f5ea1d64/main.ts#L71 If you don't want to use the `checking` variable, you should use `callback` here instead of `checkCallback`.

https://github.com/charliecm/obsidian-upcoming/blob/a90ec055d6ed31f7429246e049e99297f5ea1d64/main.ts#L152 Please [avoid](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#avoid-innerhtml-outerhtml-and-insertadjacenthtml) using `.innerHTML` whenever possible.

**Comment by charliecm** [comment]
@liamcain Thanks for the review! I've addressed all of your suggested changes and am using the daily-note-interface for handling daily notes. I've also added a create notes option in the latest commit.

Re: accessing `id`, I'm trying to exclude the active leaf from being closed along with the leaves previously created by the command. Given that `id` isn't in the current type file, is there a recommended way of accessing it?

**Comment by liamcain** [comment]
> Re: accessing id, I'm trying to exclude the active leaf from being closed along with the leaves previously created by the command. Given that id isn't in the current type file, is there a recommended way of accessing it?

Looking back through what you're trying to do, I think what you have is fine.

---

Code LGTM!

**Pull request merged**
