### PR TITLE
add dynamic timetable plugin

### PR DESCRIPTION
**Pull request by L7Cy**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [obsidian-dynamic-timetable](https://github.com/L7Cy/obsidian-dynamic-timetable)

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
@L7Cy could you please fix the error pointed out above.
We will only review submissions that passed this validation.

**Comment by joethei** [comment]
["fundingUrl": "",](https://github.com/L7Cy/obsidian-dynamic-timetable/blob/d109c4e87a7ec634eecb3c33a7a2e0d022706e1c/manifest.json#L9)
Remove this if you don't have one

["authorUrl": "",](https://github.com/L7Cy/obsidian-dynamic-timetable/blob/d109c4e87a7ec634eecb3c33a7a2e0d022706e1c/manifest.json#L8)
Use your GH profile URL if you don't have your own website.

**Comment by liamcain** [comment]
- [==](https://github.com/L7Cy/obsidian-dynamic-timetable/blob/495732b1dab259242fcfbd961f19eb00c2127293/main.ts#L53) === triple equals
- [TimetableView](https://github.com/L7Cy/obsidian-dynamic-timetable/blob/495732b1dab259242fcfbd961f19eb00c2127293/main.ts#L23) - [Avoid managing references to custom views](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#avoid-managing-references-to-custom-views) Doing so can cause memory leaks or unintended consequences. Instead, you should just register an event handler within your view class
- [getAbstractFileByPath](https://github.com/L7Cy/obsidian-dynamic-timetable/blob/495732b1dab259242fcfbd961f19eb00c2127293/main.ts#L85) you should also use instanceof TFile and ensure that the returned file is a file and not a folder
- [registerView](https://github.com/L7Cy/obsidian-dynamic-timetable/blob/495732b1dab259242fcfbd961f19eb00c2127293/main.ts#L76) you should only be registering a view creator once. Move registerView to your onload.

**Comment by liamcain** [comment]
Looks good. I still think it would be better if you move the event listener into your view:

instead of:
```
        this.registerEvent(this.app.vault.on("modify", async (file) => {
            if (file === this.targetFile) {
                for (let leaf of this.app.workspace.getLeavesOfType("Timetable")) {
                    let view = leaf.view;
                    if (view instanceof TimetableView) {
                        await view.update();
                    }
                }
            }
        }));
```

have this inside TimetableView:

```
        plugin.registerEvent(this.app.vault.on("modify", async (file) => {
            if (file === this.plugin.targetFile) {
                this.update();
            }
        }));
```

image

**Pull request merged**
