### PR TITLE
Add Listive theme to repo

### PR DESCRIPTION
**Pull request by efemkay**
# I am submitting a new Community Theme

## Repo URL

Link to my theme: https://github.com/efemkay/obsidian-listive-theme

## Theme checklist

- [x] My repo contains all required files (please do not add them to this `obsidian-releases` repo).
    - [x] `theme.css`
    - [x] The screenshot file.
- [x] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other themes that I'm using.
I have given proper attribution to these other themes in my `README.md`.

### CODE REVIEW

**Comment by ericaxu** [comment]
@efemkay Please complete the submission checklist, thanks!

**Comment by efemkay** [comment]
> @efemkay Please complete the submission checklist, thanks!

sorry about. i had a feeling i was missing sth. updated in the original comment above

**Comment by ericaxu** [comment]
Looks great! Thanks for submitting your plugin Got you two coffees!

I see that you adopted some features from other themes like Obsidian You, would recommend adding a Credit section when you have time. Thanks!

**Comment by efemkay** [comment]
> I see that you adopted some features from other themes like Obsidian You, would recommend adding a Credit section when you have time. Thanks!

yeah. definitely will do (crediting some of the snippets i fork and other inspirations sources (obsidian forum and discord). thanks for approving the theme.

**Pull request merged**
