### PR TITLE
Add plugin: Caret

### PR DESCRIPTION
**Pull request by jcollingj**
Adding a new plugin!

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/jcollingj/caret

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux (Currently asking if any beta testers were on linux)
  - [ ]  Android _(if applicable)_ (Not applicable)
  - [ ]  iOS _(if applicable)_ (Not applicable)
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "Use LLMs in a local-first, private way directly inside your Obsidian vault. With Chat + Canvas functionality.",](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/manifest.json#L6)
Avoid including sentences like "This is a plugin for Obsidian that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

["fundingUrl": "https://twitter.com/JacobColling",](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/manifest.json#L9)
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link remove this line.


[name: "Add Custom Models",](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/main.ts#L251), [name: "Remove Custom Models",](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/main.ts#L259), [name: "Set System Prompt",](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/main.ts#L266), [name: "Create New Workflow",](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/main.ts#L273), [name: "Create Linear Workflow From Canvas",](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/main.ts#L283), [name: "Insert Note",](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/main.ts#L475), [modal.contentEl.createEl("h1", { text: "Canvas Prompt" });](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/main.ts#L579), [name: "Inline Editing",](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/main.ts#L636), [name: "Edit Workflow",](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/main.ts#L653), [name: "Apply Inline Changes",](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/main.ts#L674), [name: "Continue Chat",](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/main.ts#L702), [setTooltip(graphButtonEl, "Create User Message", { placement: "top" });](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/main.ts#L1390), [this.addRibbonIcon("message-square", "Caret Chat", async (evt) => {](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/main.ts#L2535)
[.setName('LLM Provider')](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/settings.ts#L94), [.setName('LLM Provider')](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/settings.ts#L94), [text.setPlaceholder('OpenAI API Key')](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/settings.ts#L169), [.setName('Groq API Key')](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/settings.ts#L180), [text.setPlaceholder('Grok API Key')](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/settings.ts#L183), [.setName('Anthropic API Key')](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/settings.ts#L193), [text.setPlaceholder('Anthropic API Key')](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/settings.ts#L196), [.setName('Open Router API Key')](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/settings.ts#L206), [.setName('Reload after adding API Keys!')](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/settings.ts#L219), [.setName('Chat Folder Path')](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/settings.ts#L239), [.setName('Use Date Format for Subfolders')](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/settings.ts#L250), [.setName('Rename Chats')](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/settings.ts#L261), [.setName('Send Chat Shortcut')](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/settings.ts#L278), [return "Workflow Editor";](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/views/workflowEditor.ts#L29), [const addPromptButton = buttonContainer.createEl("button", { text: "Add New Prompt" });](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/views/workflowEditor.ts#L120), [const save_button = buttonContainer.createEl("button", { text: "Save Workflow" });](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/views/workflowEditor.ts#L126), [new Notice("Workflow Updated!");](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/views/workflowEditor.ts#L213), [new Notice("Workflow Created!");](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/views/workflowEditor.ts#L216), [dropdown_container.createEl("label", { text: "Workflow Type: ", cls: "dropdown-label" });](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/views/workflowEditor.ts#L234), [{ value: "linear", text: "Linear Workflow" },](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/views/workflowEditor.ts#L241-L242), [contentEl.createEl("h2", { text: "Remove Custom Model", cls: "insert-file-header" });](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/modals/removeCustomModel.ts#L14), [text: "Insert File",](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/modals/insertNoteModal.ts#L19), [.setButtonText("Append Output")](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/modals/inlineEditingModal.ts#L37), [contentEl.createEl("h2", { text: "Convert Text to Note" });](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/modals/convertTextToNoteModal.ts#L19), [contentEl.createEl("h2", { text: "Add Custom Model" });](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/modals/addCustomModel.ts#L23), [.setName("Model Name")](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/modals/addCustomModel.ts#L40), [.setName("Function Calling")](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/modals/addCustomModel.ts#L57), [.setName("Context Size")](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/modals/addCustomModel.ts#L66), [.setName("Custom Endpoint")](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/modals/addCustomModel.ts#L75), [.setName("Known Provider")](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/modals/addCustomModel.ts#L93), [<span className="bulk-convert-label">Bulk Convert</span>](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/components/chat.tsx#L279), [<button onClick={bulkConvert}>Bulk Convert to Note</button>](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/components/chat.tsx#L325)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[callback: async () => {](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/main.ts#L284-L289), [callback: async () => {](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/main.ts#L476-L487), [callback: async () => {](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/main.ts#L497-L500), [callback: () => {](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/main.ts#L637-L639), [callback: () => {](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/main.ts#L637-L638), [callback: async () => {](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/main.ts#L654-L656), [callback: () => {](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/main.ts#L675-L677), [.setName("File Name")](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/modals/convertTextToNoteModal.ts#L23), [.setName("Auto Format")](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/modals/convertTextToNoteModal.ts#L32)
This should be `checkCallback`s: <https://docs.obsidian.md/Plugins/User+interface/Commands#Conditional+commands>

[const currentLeaf = this.app.workspace.activeLeaf;](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/main.ts#L477), [const currentLeaf = this.app.workspace.activeLeaf;](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/main.ts#L498) 
Use `getActiveViewOfType` instead of the deprecated `activeLeaf`

[import pdfjs from "@bundled-es-modules/pdfjs-dist/build/pdf";](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/main.ts#L5)
Use `loadPdfJs` to load PDF.js instead.


[new Setting(containerEl).setName('Save Settings').addButton(button => {](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/settings.ts#L224-L233), [new Setting(containerEl)](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/settings.ts#L289-L310)
This servers no purpose, remove it.

[new Setting(containerEl)](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/settings.ts#L289-L310)
The validation should happen once the settings get changed, not in this seperate button.


[.setDesc(`Caret Version: ${this.plugin.settings.caret_version}`);](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/settings.ts#L323)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[const apiTab = tabContainer.createEl('button', { text: 'API Settings', cls: 'tab' });](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/settings.ts#L326-L327)
[Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

[await this.app.fileManager.processFrontMatter(file, (fm) => {](https://github.com/jcollingj/caret/blob/f7a3aa268b8abc75bdae6dc88337617432fc5187/main.ts#L805-L807)
To read frontmatter use `this.app.metadataCache.getFileCache(file)?.frontmatter`

**Comment by jcollingj** [comment]
About half way through the changes. Thanks for the feedback!

**Comment by jcollingj** [comment]
@joethei I believe I've incorporated all of your feedback. Would you mind taking another look when you have a chance?

**Comment by joethei** [comment]
There are 4 strings left that are not using sentence case.
And the PDF.js loading was not changed.

**Comment by jcollingj** [comment]
@joethei I've modified the outstanding strings. Sorry about that, have hopefully gotten them all now.

PDF.js is already loaded like:
`this.pdfjs = await loadPdfJs();`

I believe this is how it's supposed to be done. But if you are looking for something different could you provide some guidance or point me in the direction of documentation for it?

**Comment by jcollingj** [comment]
Sorry the issue with the release version should be fixed now!

**Pull request merged**
