### PR TITLE
Add Steemit plugin to community plugins

### PR DESCRIPTION
**Pull request by anpigon**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/anpigon/obsidian-steemit-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by liamcain** [comment]
Hi @anpigon, it looks like your pull request caused the whole file to get reformatted. Do you mind fixing it so that only your additions are shown in the diff?

Also, could you add a link to the plugin in the pull request description? It makes it a bit easier for passersby to check out what the plugin is.

**Comment by anpigon** [comment]
@liamcain Thank you for the comment. I fixed it.

**Comment by lishid** [comment]
https://github.com/anpigon/obsidian-steemit-plugin/blob/f56c43d1e83c9ac5ba56bfa6cee57f40692772ab/src/steemit-client.ts#L19
Recommend using `cachedRead` for better performance.

https://github.com/anpigon/obsidian-steemit-plugin/blob/f56c43d1e83c9ac5ba56bfa6cee57f40692772ab/src/steemit-client.ts#L20
Recommend using `metadataCache.getFileCache(file)` and using the resulting frontmatter instead of bringing your own frontmatter+yaml parser, which is bloating your plugin to over 1MB.

**Comment by anpigon** [comment]
> Recommend using `metadataCache.getFileCache(file)` and using the resulting frontmatter instead of bringing your own frontmatter+yaml parser, which is bloating your plugin to over 1MB.

@lishid Thanks for the advice. I've fixed it all. 
- [x] Using `cachedRead` for better performance. [05a536a](https://github.com/anpigon/obsidian-steemit-plugin/commit/05a536a5d570393ffcfa1e0db048bcb3e369c211)
- [x] Using `metadataCache.getFileCache(file)` instead of gray-matter package. [2a289fd](https://github.com/anpigon/obsidian-steemit-plugin/commit/2a289fd790b8d4bfa318c379bf55dd74478ad90c)

**Comment by lishid** [comment]
I did a quick survey of your release file and I think a huge portion of it is just lodash and bluebird, but it seems like that's from the upstream library so I don't suppose we have a way to replace them with modern js versions.

**Pull request merged**
