### PR TITLE
Add QuickAdd plugin

### PR DESCRIPTION
**Pull request by chhoumann**
# [x] I am submitting a new Community Plugin

## Repo URL

[QuickAdd](https://github.com/chhoumann/quickadd)

## Release Checklist

- [x] I have tested this on Windows, macOS, and Linux _(if applicable)_
- [x] Github release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] Github release name matches the exact version number specified in your manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/chhoumann/quickadd/blob/e419724f7bc4cc31d10c6e9ec7c0439df91f457f/src/main.ts#L76

Might not be a good idea to await this because it will prevent the app and other plugins from initializing, and prolong the loading time of the app. Or maybe this is intentional?

https://github.com/chhoumann/quickadd/blob/e419724f7bc4cc31d10c6e9ec7c0439df91f457f/src/utility.ts#L42
`app` the global reference is only there for debugging purpose. I suggest you pass the reference from your plugin in case the global reference is changed or removed in the future.

https://github.com/chhoumann/quickadd/blob/e419724f7bc4cc31d10c6e9ec7c0439df91f457f/src/utility.ts#L31
Should use `workspace.getActiveViewOfType(MarkdownView)` and check for null before using the editor.

**Comment by chhoumann** [comment]
> [chhoumann/quickadd@`e419724`/src/main.ts#L76](https://github.com/chhoumann/quickadd/blob/e419724f7bc4cc31d10c6e9ec7c0439df91f457f/src/main.ts#L76)
> 
> Might not be a good idea to await this because it will prevent the app and other plugins from initializing, and prolong the loading time of the app. Or maybe this is intentional?
> 
> [chhoumann/quickadd@`e419724`/src/utility.ts#L42](https://github.com/chhoumann/quickadd/blob/e419724f7bc4cc31d10c6e9ec7c0439df91f457f/src/utility.ts#L42)
> `app` the global reference is only there for debugging purpose. I suggest you pass the reference from your plugin in case the global reference is changed or removed in the future.
> 
> [chhoumann/quickadd@`e419724`/src/utility.ts#L31](https://github.com/chhoumann/quickadd/blob/e419724f7bc4cc31d10c6e9ec7c0439df91f457f/src/utility.ts#L31)
> Should use `workspace.getActiveViewOfType(MarkdownView)` and check for null before using the editor.

Thank you for your review, @lishid. It's very appreciated.

I have addressed the feedback in this commit:
https://github.com/chhoumann/quickadd/commit/89860b89d738e713806789e90c2542c97f03fba1

**Comment by lishid** [comment]
https://github.com/chhoumann/quickadd/blob/3cf2a7e6485e98d7f941dc5081e0be9ace198be8/src/main.ts#L47
This should probably be `workspace.onLayoutReady` instead (which runs your callback if layout is already ready).

**Comment by lishid** [comment]
I'll merge it now, you can fix it once you have time.

**Pull request merged**
