### PR TITLE
Add plugin: Amazing Marvin Integration

### PR DESCRIPTION
**Pull request by muness**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/cloud-atlas-ai/obsidian-am

## Release Checklist
- [X] I have tested the plugin on
  - [X]  Windows
  - [X]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [x] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [X] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
- [x] I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by muness** [comment]
Note: the earlier submission got stuck somehow: https://github.com/obsidianmd/obsidian-releases/pull/2856

**Comment by joethei** [comment]
["name": "Amazing Marvin by Cloud Atlas",](https://github.com/cloud-atlas-ai/obsidian-am/blob/0c58b915577cb872b9060e06df754254f96a70f6/manifest.json#L3)
Plugin names should not contain the author name, since that is already shown elsewhere.

[name: "Create Marvin Task",](https://github.com/cloud-atlas-ai/obsidian-am/blob/0c58b915577cb872b9060e06df754254f96a70f6/src/main.ts#L86), [name: 'Import Categories and Tasks',](https://github.com/cloud-atlas-ai/obsidian-am/blob/0c58b915577cb872b9060e06df754254f96a70f6/src/main.ts#L126), [name: "Import Today's Tasks",](https://github.com/cloud-atlas-ai/obsidian-am/blob/0c58b915577cb872b9060e06df754254f96a70f6/src/main.ts#L139), and more
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[id: 'am-import',](https://github.com/cloud-atlas-ai/obsidian-am/blob/0c58b915577cb872b9060e06df754254f96a70f6/src/main.ts#L125), [id: "am-import-today",](https://github.com/cloud-atlas-ai/obsidian-am/blob/0c58b915577cb872b9060e06df754254f96a70f6/src/main.ts#L138)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

[.then(task => {](https://github.com/cloud-atlas-ai/obsidian-am/blob/0c58b915577cb872b9060e06df754254f96a70f6/src/main.ts#L93), and many more
[Prefer async/await over Promise](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Prefer+async%2Fawait+over+Promise)

[response = await fetch(`https://serv.amazingmarvin.com${endpoint}`, {](https://github.com/cloud-atlas-ai/obsidian-am/blob/0c58b915577cb872b9060e06df754254f96a70f6/src/main.ts#L319)
This should also use `requestUrl` like everywhere else.

**Comment by muness** [comment]
Thanks for the review! Will get these issues addressed soon.

> ["name": "Amazing Marvin by Cloud Atlas",](https://github.com/cloud-atlas-ai/obsidian-am/blob/0c58b915577cb872b9060e06df754254f96a70f6/manifest.json#L3)
> Plugin names should not contain the author name, since that is already shown elsewhere.

There's already an Amazing Marvin plugin that's abandoned. What do you suggest?

**Comment by liamcain** [comment]
-  [toYamlValue](https://github.com/cloud-atlas-ai/obsidian-am/blob/0c58b915577cb872b9060e06df754254f96a70f6/src/main.ts#L538) Please don't implement this yourself. The API provides a stringifyYAML function for this purpose
- [adapter.rmdir](https://github.com/cloud-atlas-ai/obsidian-am/blob/0c58b915577cb872b9060e06df754254f96a70f6/src/main.ts#L343) [Prefer the Vault API over the Adapter API](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#prefer-the-vault-api-over-the-adapter-api)

**Comment by joethei** [comment]
I would recommend a name such as `Amazing Marvin Sync` or `Amazing Marvin Integration` for example.
The other plugin does not quite fit our criteria for removal.

**Comment by muness** [comment]
@joethei , @liamcain - requested changes made. Thanks for the review!

**Comment by joethei** [comment]
Could you rebase this PR?
Thanks!

**Pull request merged**
