### PR TITLE
Add plugin: Highlight Helper

### PR DESCRIPTION
**Pull request by byfun**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/byfun/obsidian-highlight-helper

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "Helper to collect highlight in Obsidian",](https://github.com/byfun/obsidian-highlight-helper/blob/f33ef0080daaf702f7b05ff5611fbd7ea2408eb1/manifest.json#L6)
Don't include "Obsidian" here.

[id: "hh-copy-command",](https://github.com/byfun/obsidian-highlight-helper/blob/f33ef0080daaf702f7b05ff5611fbd7ea2408eb1/src/main.ts#L42)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

[const DEBUG_MODE = true;](https://github.com/byfun/obsidian-highlight-helper/blob/f33ef0080daaf702f7b05ff5611fbd7ea2408eb1/src/helpers.ts#L4)
Set this to false for the releases.

[const mdFile = app.workspace.getActiveFile();](https://github.com/byfun/obsidian-highlight-helper/blob/f33ef0080daaf702f7b05ff5611fbd7ea2408eb1/src/helpers.ts#L14)
It's highly discouraged that you use the global app instance in your plugin. It's currently accessible from the global context for debugging purposes, and might be removed in the future. Instead, you should use the reference to App that you have from your plugin instance.

[text.inputEl.style.width = "300px";](https://github.com/byfun/obsidian-highlight-helper/blob/f33ef0080daaf702f7b05ff5611fbd7ea2408eb1/src/settings.ts#L30-L31), [text.inputEl.style.width = "300px";](https://github.com/byfun/obsidian-highlight-helper/blob/f33ef0080daaf702f7b05ff5611fbd7ea2408eb1/src/settings.ts#L48)
You should avoid assigning styles via JavaScript or in HTML and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets.

**Comment by byfun** [comment]
Thanks for your review. 

I have fixed the issues and created new release with updated version number.
Do I need to create another pull request? or what else?
Please excuse that I'm new to pull-request progress.

the updated version : https://github.com/byfun/obsidian-highlight-helper/releases/tag/1.0.1

**Comment by byfun** [comment]
> ["description": "Helper to collect highlight in Obsidian",](https://github.com/byfun/obsidian-highlight-helper/blob/f33ef0080daaf702f7b05ff5611fbd7ea2408eb1/manifest.json#L6) Don't include "Obsidian" here.
> 
> [id: "hh-copy-command",](https://github.com/byfun/obsidian-highlight-helper/blob/f33ef0080daaf702f7b05ff5611fbd7ea2408eb1/src/main.ts#L42) Obsidian will automatically prefix the command id with the plugin id, you don't need to include it yourself.
> 
> [const DEBUG_MODE = true;](https://github.com/byfun/obsidian-highlight-helper/blob/f33ef0080daaf702f7b05ff5611fbd7ea2408eb1/src/helpers.ts#L4) Set this to false for the releases.
> 
> [const mdFile = app.workspace.getActiveFile();](https://github.com/byfun/obsidian-highlight-helper/blob/f33ef0080daaf702f7b05ff5611fbd7ea2408eb1/src/helpers.ts#L14) It's highly discouraged that you use the global app instance in your plugin. It's currently accessible from the global context for debugging purposes, and might be removed in the future. Instead, you should use the reference to App that you have from your plugin instance.
> 
> [text.inputEl.style.width = "300px";](https://github.com/byfun/obsidian-highlight-helper/blob/f33ef0080daaf702f7b05ff5611fbd7ea2408eb1/src/settings.ts#L30-L31), [text.inputEl.style.width = "300px";](https://github.com/byfun/obsidian-highlight-helper/blob/f33ef0080daaf702f7b05ff5611fbd7ea2408eb1/src/settings.ts#L48) You should avoid assigning styles via JavaScript or in HTML and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets.

---

Thanks for your review.

I have fixed the issues and created new release with updated version number.
Do I need to create another pull request? or what else?
Please excuse that I'm new to pull-request progress.

the updated version : https://github.com/byfun/obsidian-highlight-helper/releases/tag/1.0.1

**Comment by byfun** [comment]
Could you check this PR? the changes-request are applied.

**Comment by liamcain** [comment]
- [onElement](https://github.com/byfun/obsidian-highlight-helper/blob/e85df4e5d804059806d3e0ee4dc400cbd31fa538/src/main.ts#L66) this is unused
- [Copy Marks](https://github.com/byfun/obsidian-highlight-helper/blob/e85df4e5d804059806d3e0ee4dc400cbd31fa538/src/main.ts#L34) We recommend that all commands use [Sentence case](https://en.wiktionary.org/wiki/sentence_case) for their names. This maximizes readability in the command palette.
- [Copy Marks](https://github.com/byfun/obsidian-highlight-helper/blob/e85df4e5d804059806d3e0ee4dc400cbd31fa538/src/main.ts#L43) same here

**Pull request merged**
