### PR TITLE
Add dendron-tree plugin

### PR DESCRIPTION
**Pull request by levirs565**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/levirs565/obsidian-dendron-tree/

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "This plugin add tree for exploring Dendron note.",](https://github.com/levirs565/obsidian-dendron-tree/blob/1e3f8e65d025a340f2e62f3ecf64415209b886c1/manifest.json#L6)
We have recently published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This plugin" in your description.

[this.app.workspace.detachLeavesOfType(VIEW_TYPE_DENDRON);](https://github.com/levirs565/obsidian-dendron-tree/blob/1e3f8e65d025a340f2e62f3ecf64415209b886c1/src/main.ts#L66)
Do not detach leaves with your custom view in `onunload`, this is an antipattern, see: <https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Don't+detach+leaves+in+%60onunload%60>

**Comment by levirs565** [comment]
Done.

**Comment by marcusolsson** [comment]
[hotkeys: [{ modifiers: ["Ctrl"], key: "l" }],](https://github.com/levirs565/obsidian-dendron-tree/blob/77f2b9a8783f825e28dff8149985226bb941c6b7/src/main.ts#L28)
https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+setting+a+default+hotkey+for+commands

[.setName("Auto Generate Fronmatter")](https://github.com/levirs565/obsidian-dendron-tree/blob/77f2b9a8783f825e28dff8149985226bb941c6b7/src/settings.ts#L36)
https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI
Also "frontmatter" is misspelled.

**Comment by levirs565** [comment]
Done

**Comment by liamcain** [comment]
- [generateFronmatter](https://github.com/levirs565/obsidian-dendron-tree/blob/023ae9286d20f7ecc55bce0e5655f457ab4d930e/src/engine/vault.ts#L57) nit: typo in "frontmatter"
- [isInitialized](https://github.com/levirs565/obsidian-dendron-tree/blob/023ae9286d20f7ecc55bce0e5655f457ab4d930e/src/engine/vault.ts#L45) typo "isInitiated"

**Pull request merged**
