### PR TITLE
Add plugin: Incomplete files

### PR DESCRIPTION
**Pull request by HananoshikaYomaru**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/HananoshikaYomaru/obsidian-incomplete-files

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by HananoshikaYomaru** [comment]
The name in License is `Yeung Man Lung Ken` and that is my real name on passport. Don't ask me to change it.

**Comment by joethei** [comment]
[return "Incomplete Files";](https://github.com/HananoshikaYomaru/obsidian-incomplete-files/blob/f1f98775ee8e0892dae39bc6ddaf349fbce55053/src/IncompleteFileView.ts#L28)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[{@html issue.type === INCOMPLETE_ISSUE_TYPE.EMPTY_CONTENT](https://github.com/HananoshikaYomaru/obsidian-incomplete-files/blob/f1f98775ee8e0892dae39bc6ddaf349fbce55053/src/ui/FileItem.svelte#L49), [{@html getIcon(name)?.outerHTML}](https://github.com/HananoshikaYomaru/obsidian-incomplete-files/blob/f1f98775ee8e0892dae39bc6ddaf349fbce55053/src/ui/icon.svelte#L6)
[Avoid using `innerHTML` and similar API's](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%60innerHTML%60%2C+%60outerHTML%60+and+%60insertAdjacentHTML%60)

[obsidian-ex.d.ts](https://github.com/HananoshikaYomaru/obsidian-incomplete-files/blob/f1f98775ee8e0892dae39bc6ddaf349fbce55053/src/typings/obsidian-ex.d.ts#L1)
Please credit the source of this file.

**Comment by HananoshikaYomaru** [comment]
but then what is the correct way for doing the icon thing? given an svg, how can I set it in svelte?

**Comment by joethei** [comment]
here is an example: https://github.com/joethei/obsidian-rss/blob/master/src/view/IconComponent.svelte

**Comment by HananoshikaYomaru** [comment]
but I think the lucide icon collection of obsidian is not updated, many of the icons cannot be found. That's why I don't want to only use iconName but use the full svg string copied from lucide. So there is no workaround?

**Comment by HananoshikaYomaru** [comment]
OK, I guess for second icon issue, I can replace my component with your component because it accepts a icon name which obsidian knows to how to resolve. For the first icon issue, it is a workaround for icon name that obsidian doesn't know how to resolve. I will update it in the future if there is an official workaround. 

I have updated and please review again.

**Pull request merged**
