### PR TITLE
Add plugin: Latex Exporter

### PR DESCRIPTION
**Pull request by mscott99**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/mscott99/latex-exporter

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[Copyright (c) 2023 Matthew Scott](https://github.com/mscott99/Latex-Exporter/blob/b6b4a498a7d992a0552fcf257f22da3716353f0b/LICENSE#L3)
Update the year.

["fs": "^0.0.1-security",](https://github.com/mscott99/Latex-Exporter/blob/b6b4a498a7d992a0552fcf257f22da3716353f0b/package.json#L34)
That is not a valid dependency, remove it.

[console.log("Exporting paper");](https://github.com/mscott99/Latex-Exporter/blob/b6b4a498a7d992a0552fcf257f22da3716353f0b/src/main.ts#L33), [console.log(this.settings.base_output_folder);](https://github.com/mscott99/Latex-Exporter/blob/b6b4a498a7d992a0552fcf257f22da3716353f0b/src/main.ts#L41), [console.log("no preamble file found.");](https://github.com/mscott99/Latex-Exporter/blob/b6b4a498a7d992a0552fcf257f22da3716353f0b/src/main.ts#L71), [console.log("no bib file found.");](https://github.com/mscott99/Latex-Exporter/blob/b6b4a498a7d992a0552fcf257f22da3716353f0b/src/main.ts#L93), [console.log("Exporting with the default template.");](https://github.com/mscott99/Latex-Exporter/blob/b6b4a498a7d992a0552fcf257f22da3716353f0b/src/main.ts#L103), [console.log("Exporting with template.");](https://github.com/mscott99/Latex-Exporter/blob/b6b4a498a7d992a0552fcf257f22da3716353f0b/src/main.ts#L105), [console.log("Creating new output file");](https://github.com/mscott99/Latex-Exporter/blob/b6b4a498a7d992a0552fcf257f22da3716353f0b/src/main.ts#L110), [console.log("Warning before overwriting file");](https://github.com/mscott99/Latex-Exporter/blob/b6b4a498a7d992a0552fcf257f22da3716353f0b/src/main.ts#L123), [console.log("Overwriting without warning");](https://github.com/mscott99/Latex-Exporter/blob/b6b4a498a7d992a0552fcf257f22da3716353f0b/src/main.ts#L139)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[export function find_file(](https://github.com/mscott99/Latex-Exporter/blob/b6b4a498a7d992a0552fcf257f22da3716353f0b/src/export_longform/utils.ts#L29-L61)
[Avoid iterating all files to find a file by its path](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+iterating+all+files+to+find+a+file+by+its+path)

[const yaml_content = match[1];](https://github.com/mscott99/Latex-Exporter/blob/b6b4a498a7d992a0552fcf257f22da3716353f0b/src/export_longform/parseMarkdown.ts#L574-L581)
Use `parseYaml` instead of manual parsing.

**Comment by mscott99** [comment]
I have a concern about the path matching. I do not have access to the path of the file, only to the name of the file as given by wikilinks. I did not find a function in the api which finds files based on name alone. I also tried recursing over folders only and then finding by possible paths, but then this approach corresponds to case-matching the name of files, whereas Obsidian matches files in wikilinks in a case-insensitive way. It is important that I match the behaviour of obsidian when finding files associated with wikilinks. Therefore I do not currently see how to improve on my current approach, to recurse over files until the correct file is found.

**Comment by mscott99** [comment]
I have fixed everything except the issue I discussed in my last comment. Let me know if this is good enough? Thanks!

**Comment by joethei** [comment]
Use: https://docs.obsidian.md/Reference/TypeScript+API/MetadataCache/getFirstLinkpathDest

**Comment by mscott99** [comment]
Thanks for the pointer, I removed the recursive search function.

**Comment by mscott99** [comment]
Anything else I should do?

**Comment by mscott99** [comment]
I am awaiting review.

**Comment by mscott99** [comment]
My mistake, I fixed it now.

**Pull request merged**
