### PR TITLE
Add plugin: Settings profiles

### PR DESCRIPTION
**Pull request by 4Source**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/4Source/SettingsProfiles-Obsidian-Plugin

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by 4Source** [comment]
Updated

**Comment by joethei** [comment]
["name": "SettingsProfiles",](https://github.com/4Source/SettingsProfiles-Obsidian-Plugin/blob/0fb1540ee2038a2348936f528a09a7bdead057ce/manifest.json#L3)
Add a space in between, and [use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[new Notice(`Current Profile: ${this.settings.profile}`);](https://github.com/4Source/SettingsProfiles-Obsidian-Plugin/blob/0fb1540ee2038a2348936f528a09a7bdead057ce/src/main.ts#L71), [.createEl("span", { text: "Current Profile", cls: "suggestion-hotkey" })](https://github.com/4Source/SettingsProfiles-Obsidian-Plugin/blob/0fb1540ee2038a2348936f528a09a7bdead057ce/src/ProfileModal.ts#L80)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[this.containerEl.createEl("h2", { text: "General" });](https://github.com/4Source/SettingsProfiles-Obsidian-Plugin/blob/0fb1540ee2038a2348936f528a09a7bdead057ce/src/Settings.ts#L76)
[Don't use a "general" heading in your settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by 4Source** [comment]
Updated your requests to new release [0.1.1](https://github.com/4Source/SettingsProfiles-Obsidian-Plugin/releases/tag/0.1.1)

**Comment by 4Source** [comment]
Sry for messing around tried to fix the merge conflicts and rebase messed it up

**Pull request merged**
