### PR TITLE
Add plugin: Daily Summary

### PR DESCRIPTION
**Pull request by CSLukkun**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/CSLukkun/ob_daily_summary

## Release Checklist
- [] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[# Obsidian Daily Summary Plugin](https://github.com/CSLukkun/ob_daily_summary/blob/56bfefcfac48da91b50513b9e01057daedc4c003/README.md#L1)
Naming something "Obsidian xyz" is reserved for first party products we create, please change this header.

["id": "ob-daily-summary",](https://github.com/CSLukkun/ob_daily_summary/blob/56bfefcfac48da91b50513b9e01057daedc4c003/manifest.json#L2), ["name": "OB Daily Summary",](https://github.com/CSLukkun/ob_daily_summary/blob/56bfefcfac48da91b50513b9e01057daedc4c003/manifest.json#L3)
Please rename your plugin, and don't use shorthands of "Obsidian"

[import moment from 'moment';](https://github.com/CSLukkun/ob_daily_summary/blob/56bfefcfac48da91b50513b9e01057daedc4c003/main.ts#L3)
Import moment from the Obsidian package instead.

[name: 'Generate Daily Report',](https://github.com/CSLukkun/ob_daily_summary/blob/56bfefcfac48da91b50513b9e01057daedc4c003/main.ts#L16), [name: 'Generate Previous Day Report',](https://github.com/CSLukkun/ob_daily_summary/blob/56bfefcfac48da91b50513b9e01057daedc4c003/main.ts#L22), [.setName('API Key')](https://github.com/CSLukkun/ob_daily_summary/blob/56bfefcfac48da91b50513b9e01057daedc4c003/main.ts#L235), [.setName('API Endpoint')](https://github.com/CSLukkun/ob_daily_summary/blob/56bfefcfac48da91b50513b9e01057daedc4c003/main.ts#L246)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[new Notice(`找到 ${todayNotes.length} 篇笔记`);](https://github.com/CSLukkun/ob_daily_summary/blob/56bfefcfac48da91b50513b9e01057daedc4c003/main.ts#L53), [new Notice('Failed to generate summary');](https://github.com/CSLukkun/ob_daily_summary/blob/56bfefcfac48da91b50513b9e01057daedc4c003/main.ts#L66)
Please stay consistent in the language used across your plugin UI, or implement i18n handling.

[const response = await fetch(this.settings.apiEndpoint, {](https://github.com/CSLukkun/ob_daily_summary/blob/56bfefcfac48da91b50513b9e01057daedc4c003/main.ts#L108)
Use the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

[const fileName = `${this.settings.reportLocation}/Daily Report-${date}.md`.replace('//', '/');](https://github.com/CSLukkun/ob_daily_summary/blob/56bfefcfac48da91b50513b9e01057daedc4c003/main.ts#L145), 
[Use `normalizePath` to clean up user defined paths](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+%60normalizePath()%60+to+clean+up+user-defined+paths)

[console.error('Error logged to:', logFile);](https://github.com/CSLukkun/ob_daily_summary/blob/56bfefcfac48da91b50513b9e01057daedc4c003/main.ts#L214)
Remove this line, it makes no sense being a `console.error`.

**Comment by CSLukkun** [comment]
Hey, joethei, I feel confused about your comment based which commit. 
Because I make some commits based on the current repo. I am not sure if I continue to modify the code based the latest code or the version you review.

**Comment by joethei** [comment]
Just make the changes in your repo.

**Comment by CSLukkun** [comment]
Hi Joethei, Could you have a look my modification? 
Tks, If still has question, I am so glad that you can tell me

**Pull request merged**
