### PR TITLE
Add plugin: sync-db-os

### PR DESCRIPTION
**Pull request by ketd**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:  https://github.com/ketd/obsidian-sync-DB-OS

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Please don't open a new PR to revalidate, closing in favor of #3828

**Comment by ketd** [comment]
> Please don't open a new PR to revalidate, closing in favor of #3828

sry,but that submitted repositories  has been deleted.what should i do?

**Comment by joethei** [comment]
Your README is missing information about the upload to the Tencent platform, please add it

["repo":"ketd/obsidian-sync-DB-OS",](https://github.com/ketd/obsidian-sync-DB-OS/blob/eb4e6483e3cbc7fd02a74bf47dbfff1a5723f83d/manifest.json#L8)
This is not valid in the manifest, remove it.

[This CSS file will be included with your plugin, and](https://github.com/ketd/obsidian-sync-DB-OS/blob/eb4e6483e3cbc7fd02a74bf47dbfff1a5723f83d/styles.css#L3-L6)
Remove this comment.

[console.log('取消按钮被点击')](https://github.com/ketd/obsidian-sync-DB-OS/blob/eb4e6483e3cbc7fd02a74bf47dbfff1a5723f83d/src/main.ts#L102)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[const diff = require('diff');](https://github.com/ketd/obsidian-sync-DB-OS/blob/eb4e6483e3cbc7fd02a74bf47dbfff1a5723f83d/src/util/CompareFiles.ts#L11)
Please stick to one import style.

[http](https://github.com/ketd/obsidian-sync-DB-OS/blob/eb4e6483e3cbc7fd02a74bf47dbfff1a5723f83d/src/util/db/CouchDBServer.ts#L34)
This should be https

[function delay(ms: number) {](https://github.com/ketd/obsidian-sync-DB-OS/blob/eb4e6483e3cbc7fd02a74bf47dbfff1a5723f83d/src/sync/Pull.ts#L53-L55)
The Obsidian API has the `sleep` function for this purpose.

[containerEl.createEl("h1", {text: "同步插件配置"});](https://github.com/ketd/obsidian-sync-DB-OS/blob/eb4e6483e3cbc7fd02a74bf47dbfff1a5723f83d/src/setting/SyncDbOsPluginSettings.ts#L24)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[containerEl.createEl("h2", {text: "默认插入配置"});](https://github.com/ketd/obsidian-sync-DB-OS/blob/eb4e6483e3cbc7fd02a74bf47dbfff1a5723f83d/src/setting/SyncDbOsPluginSettings.ts#L29), [containerEl.createEl("h1", {text: "数据库配置"});](https://github.com/ketd/obsidian-sync-DB-OS/blob/eb4e6483e3cbc7fd02a74bf47dbfff1a5723f83d/src/setting/SyncDbOsPluginSettings.ts#L46), [containerEl.createEl("h2", {text: "对象存储配置"});](https://github.com/ketd/obsidian-sync-DB-OS/blob/eb4e6483e3cbc7fd02a74bf47dbfff1a5723f83d/src/setting/SyncDbOsPluginSettings.ts#L138)
For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```

[containerEl.createEl("h2", {text: "默认插入配置"});](https://github.com/ketd/obsidian-sync-DB-OS/blob/eb4e6483e3cbc7fd02a74bf47dbfff1a5723f83d/src/setting/SyncDbOsPluginSettings.ts#L29), [containerEl.createEl("h1", {text: "数据库配置"});](https://github.com/ketd/obsidian-sync-DB-OS/blob/eb4e6483e3cbc7fd02a74bf47dbfff1a5723f83d/src/setting/SyncDbOsPluginSettings.ts#L46), [containerEl.createEl("h2", {text: "对象存储配置"});](https://github.com/ketd/obsidian-sync-DB-OS/blob/eb4e6483e3cbc7fd02a74bf47dbfff1a5723f83d/src/setting/SyncDbOsPluginSettings.ts#L138)

[Avoid "options/settings/configuration" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

**Comment by ketd** [comment]
> Your README is missing information about the upload to the Tencent platform, please add it
> 
> ["repo":"ketd/obsidian-sync-DB-OS",](https://github.com/ketd/obsidian-sync-DB-OS/blob/eb4e6483e3cbc7fd02a74bf47dbfff1a5723f83d/manifest.json#L8) This is not valid in the manifest, remove it.
> 
> [This CSS file will be included with your plugin, and](https://github.com/ketd/obsidian-sync-DB-OS/blob/eb4e6483e3cbc7fd02a74bf47dbfff1a5723f83d/styles.css#L3-L6) Remove this comment.
> 
> [console.log('取消按钮被点击')](https://github.com/ketd/obsidian-sync-DB-OS/blob/eb4e6483e3cbc7fd02a74bf47dbfff1a5723f83d/src/main.ts#L102) Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.
> 
> [const diff = require('diff');](https://github.com/ketd/obsidian-sync-DB-OS/blob/eb4e6483e3cbc7fd02a74bf47dbfff1a5723f83d/src/util/CompareFiles.ts#L11) Please stick to one import style.
> 
> [http](https://github.com/ketd/obsidian-sync-DB-OS/blob/eb4e6483e3cbc7fd02a74bf47dbfff1a5723f83d/src/util/db/CouchDBServer.ts#L34) This should be https
> 
> [function delay(ms: number) {](https://github.com/ketd/obsidian-sync-DB-OS/blob/eb4e6483e3cbc7fd02a74bf47dbfff1a5723f83d/src/sync/Pull.ts#L53-L55) The Obsidian API has the `sleep` function for this purpose.
> 
> [containerEl.createEl("h1", {text: "同步插件配置"});](https://github.com/ketd/obsidian-sync-DB-OS/blob/eb4e6483e3cbc7fd02a74bf47dbfff1a5723f83d/src/setting/SyncDbOsPluginSettings.ts#L24) [Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)
> 
> [containerEl.createEl("h2", {text: "默认插入配置"});](https://github.com/ketd/obsidian-sync-DB-OS/blob/eb4e6483e3cbc7fd02a74bf47dbfff1a5723f83d/src/setting/SyncDbOsPluginSettings.ts#L29), [containerEl.createEl("h1", {text: "数据库配置"});](https://github.com/ketd/obsidian-sync-DB-OS/blob/eb4e6483e3cbc7fd02a74bf47dbfff1a5723f83d/src/setting/SyncDbOsPluginSettings.ts#L46), [containerEl.createEl("h2", {text: "对象存储配置"});](https://github.com/ketd/obsidian-sync-DB-OS/blob/eb4e6483e3cbc7fd02a74bf47dbfff1a5723f83d/src/setting/SyncDbOsPluginSettings.ts#L138) For section headings in settings use:
> 
> ```ts
> new Setting(containerEl).setName('name here').setHeading();
> ```
> 
> [containerEl.createEl("h2", {text: "默认插入配置"});](https://github.com/ketd/obsidian-sync-DB-OS/blob/eb4e6483e3cbc7fd02a74bf47dbfff1a5723f83d/src/setting/SyncDbOsPluginSettings.ts#L29), [containerEl.createEl("h1", {text: "数据库配置"});](https://github.com/ketd/obsidian-sync-DB-OS/blob/eb4e6483e3cbc7fd02a74bf47dbfff1a5723f83d/src/setting/SyncDbOsPluginSettings.ts#L46), [containerEl.createEl("h2", {text: "对象存储配置"});](https://github.com/ketd/obsidian-sync-DB-OS/blob/eb4e6483e3cbc7fd02a74bf47dbfff1a5723f83d/src/setting/SyncDbOsPluginSettings.ts#L138)
> 
> [Avoid "options/settings/configuration" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

Thank you very much for the review! All issues have been modified as requested, but regarding the [http](https://github.com/ketd/obsidian-sync-DB-OS/blob/eb4e6483e3cbc7fd02a74bf47dbfff1a5723f83d/src/util/db/CouchDBServer.ts#L34)) issue I couldn't confirm that all users have ssl certificates, so there was no way to modify it.

**Comment by ketd** [comment]
updated

**Comment by ketd** [comment]
@joethei Hello, it's been two weeks since my last submission request. I would like to know if my plugin can be published in the community. Thank you.

**Comment by ketd** [comment]
@joethei

**Comment by liamcain** [comment]
Hi, sorry for the delay. I'm taking over plugin review while joethei is on sick leave.

- [// 这将添加一个设置选项卡，以便用户可以配置插件的各个方面](https://github.com/ketd/obsidian-sync-DB-OS/blob/52513262847e34ef1e88fda4b169694df129d664/src/main.ts#L178-L188) consider deleting this instead of leaving this unused code in your repo commented out.

Otherwise it looks good to me. I'll merge this now.

**Pull request merged**
