### PR TITLE
Update community-plugins.json

### PR DESCRIPTION
**Pull request by chrisgrieser**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/chrisgrieser/obsidian-extra-md-commands

This plugin adds commands for alternative syntax like `__bold__` or `<cite>`.

## Release Checklist

- [x] I have tested this on macOS
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by lishid** [comment]
Hmm the code seems fine, but I got confused for a second thinking that this plugin adds "syntax", whereas it just adds commands to generate those syntax. Not sure how the name/description of the plugin could be improved to lessen the chance of a confusion? Let me know if this is the final name/description we want to proceed to merge!

**Comment by chrisgrieser** [comment]
Yeah, I was also quite conflicted about the name and changed it a few times.

Maybe something like `Extra Markdown Commands`? 🤔

**Comment by chrisgrieser** [comment]
Okay, I brainstormed a bit in the Discord, and I decided to rename it "Extra Markdown Commands". Name's not perfect, but I cannot find any better. Added a respective commit to the PR. 

If you also have no idea for a better name, I think you can proceed.

**Comment by lishid** [comment]
LGTM!

**Pull request merged**
