### PR TITLE
Add Smart Random Note

### PR DESCRIPTION
**Pull request by erichalldev**

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/erichalldev/obsidian-smart-random-note/blob/e843ae03e4d7989f98272fc7610cab6feeac0a08/main.ts#L59
Remember your .hasOwnProperty checks for any for...in loops.

https://github.com/erichalldev/obsidian-smart-random-note/blob/e843ae03e4d7989f98272fc7610cab6feeac0a08/main.ts#L55
Don't use fileCache, use `Vault.getMarkdownFiles` and `MetadataCache.getFileCache` together instead. And make sure you null check the cache.

**Comment by lishid** [comment]
Also don't use Settings as a class, make an interface instead.
Actually you aren't even saving any setting, just remove it altogether:
https://github.com/erichalldev/obsidian-smart-random-note/blob/e843ae03e4d7989f98272fc7610cab6feeac0a08/main.ts#L21

**Comment by erichalldev** [comment]
> https://github.com/erichalldev/obsidian-smart-random-note/blob/e843ae03e4d7989f98272fc7610cab6feeac0a08/main.ts#L59
> Remember your .hasOwnProperty checks for any for...in loops.

Thank you for the reminder! It's been awhile since I did TypeScript development and I had forgotten about that quirk. The refactor removed the need for a for...in loop

> https://github.com/erichalldev/obsidian-smart-random-note/blob/e843ae03e4d7989f98272fc7610cab6feeac0a08/main.ts#L55
> Don't use fileCache, use `Vault.getMarkdownFiles` and `MetadataCache.getFileCache` together instead. And make sure you null check the cache.

Ah, I see how these two play together now. Fixed!

> Also don't use Settings as a class, make an interface instead.
> Actually you aren't even saving any setting, just remove it altogether:
> https://github.com/erichalldev/obsidian-smart-random-note/blob/e843ae03e4d7989f98272fc7610cab6feeac0a08/main.ts#L21

I removed the Settings class and tab.

**Comment by lishid** [comment]
Looks great. Your git is configured to use `main` instead of `master`. You can either push a new `master` branch on your end or change this PR to add the `"branch": "main"` option.

Let me know which one you'd like to do and I can merge it right after.

**Comment by erichalldev** [comment]
Just updated to use master. Thanks!

**Pull request merged**
