### PR TITLE
Adding Obsidian Notes Publish

### PR DESCRIPTION
**Pull request by SaraVieira**
# I am submitting a new Community Plugin

## Repo URL

https://github.com/SaraVieira/obsidian-notes-publish-plugin

Link to my plugin:

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

I have used `innerHTML` in my plugin but it takes no user input, all the code is static, let me know if changing will be better

### CODE REVIEW

**Comment by lishid** [comment]
Given your plugin requires Airtable, I suggest adding airtable to the ID, name and description of your plugin to avoid confused users. I'd suggest something like "A plugin that helps you publish your notes online using Airtable and NextJS".

**Comment by SaraVieira** [comment]
Hey!

I changed the description, Do you still think changing the rest makes sense? How would you write it?

**Comment by lishid** [comment]
Hmm I think your patch is kinda broken right now, any chance you can fix the patch of this PR?

**Comment by SaraVieira** [comment]
Sorry about that, patch fixed

**Comment by lishid** [comment]
Weird, now your patch shows that you've reformatted the whole file. Not sure what's going on here.

**Pull request closed without merging**
