### PR TITLE
Add plugin: Folder Periodic Notes

### PR DESCRIPTION
**Pull request by andrewheekin**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/andrewheekin/obsidian-folder-periodic-notes

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [ ] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
- [x] I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
I would not call your plugin "Better," it offers fewer features than periodic notes.

["description": "Simpler, better periodic notes plugin that includes daily notes, monthly notes, and yearly notes.",](https://github.com/andrewheekin/obsidian-better-periodic-notes/blob/3119426630af65ed15eda2422089f76edff9021e/manifest.json#L6)
No comparisons here, and don't include the word "plugin"

[containerEl.createEl("h2", {](https://github.com/andrewheekin/obsidian-better-periodic-notes/blob/3119426630af65ed15eda2422089f76edff9021e/main.ts#L171-L173)
[No top level headings in settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[.setName("Note Folder")](https://github.com/andrewheekin/obsidian-better-periodic-notes/blob/3119426630af65ed15eda2422089f76edff9021e/main.ts#L176)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by andrewheekin** [comment]
Good feedback @joethei ! Renamed from "better-periodic-notes" to "folder-periodic-notes" and addressed feedback in latest commit

**Comment by andrewheekin** [comment]
Moved plugin to be last entry in `community-plugins.json`

**Comment by andrewheekin** [comment]
@joethei Should I close this PR and create a new one, since the plugin name changed?

**Comment by andrewheekin** [comment]
@joethei Please let me know if there are other changes I should make

**Pull request merged**
