### PR TITLE
Add theme: Pxld

### PR DESCRIPTION
**Pull request by Lina674**
Request review for new theme "Pxld". 

# I am submitting a new Community Theme

## Repo URL

Link to my theme: 

https://github.com/Lina674/Pxld-Obsidian-Theme

## Theme checklist

- [x] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo).
  - [x] `manifest.json`
  - [x] `theme.css`
  - [x] The screenshot file (16:9 aspect ratio, recommended size is 512px by 288px for fast loading).
- [x] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my theme's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Themes/App+themes/Theme+guidelines and have self-reviewed my theme to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other themes that I'm using. I have given proper attribution to these other themes in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[pixel_custom_font.css](https://github.com/Lina674/Pxld-Obsidian-Theme/blob/94f79bfd1734aea23399f263be3a961a7a4b2682/pixel_custom_font.css#L1-L25)
This should not be a seperate file.
See this guide how to properly embed the font
https://docs.obsidian.md/Themes/App+themes/Embed+fonts+and+images+in+your+theme

**Comment by Lina674** [comment]
I embedded the font in my `theme.css` file. However, I want to allow for user customization which is why I have this css snippet file. If I cannot have another css file in my repository, I will just put it as a code block in my README.md file. 

Thank you for the review!

**Comment by joethei** [comment]
If Style settings are being used they should be included in the theme by default

**Comment by Lina674** [comment]
It's included now!

Thanks!

**Pull request merged**
