### PR TITLE
Add ling-gloss plugin

### PR DESCRIPTION
**Pull request by Mijyuoon**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Mijyuoon/obsidian-ling-gloss

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Mijyuoon** [comment]
> ❌ Please don't use the word `obsidian` in the plugin ID. The ID is used for your plugin's folder so keeping it short and simple avoids clutter and helps with sorting.

Would've been nice to have that mentioned in the plugin guidelines somewhere. 😐

**Comment by joethei** [comment]
["description": "A plugin for interlinear glosses used in linguistics texts.",](https://github.com/Mijyuoon/obsidian-ling-gloss/blob/bf221a176bbb3e60ba37e07f266ba51e564d5b7e/manifest.json#L6)
We have recently published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "A plugin" in your description.

**Comment by Mijyuoon** [comment]
@joethei Thanks, I have updated the plugin description.

**Comment by liamcain** [comment]
- [@ts-ignore](https://github.com/Mijyuoon/obsidian-ling-gloss/blob/d278755a7358ce350a1dc625713f89b440d7e6fe/src/parse-functions.ts#L44) instead of ts-ignoring, I would just cast the cmdText.toLowerCase() to `keyof CommandType` (same with the other ts-ignore below)

**Pull request merged**
