### PR TITLE
Add plugin: YouTube downloader

### PR DESCRIPTION
**Pull request by ai-chen2050**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/ai-chen2050/obsidian-youtube-downloader

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[| Commands  |](https://github.com/ai-chen2050/obsidian-youtube-downloader/blob/47629971ef5e035cbc4446e721599b2eae6c69f5/README.md#L46)
This screenshot is showing the wrong command.

["name": "youtube downloader",](https://github.com/ai-chen2050/obsidian-youtube-downloader/blob/47629971ef5e035cbc4446e721599b2eae6c69f5/manifest.json#L3), ["description": "Download video from youtube",](https://github.com/ai-chen2050/obsidian-youtube-downloader/blob/47629971ef5e035cbc4446e721599b2eae6c69f5/manifest.json#L6), [name: 'download youtube video',](https://github.com/ai-chen2050/obsidian-youtube-downloader/blob/47629971ef5e035cbc4446e721599b2eae6c69f5/main.ts#L20), [item.setTitle("Download video from youtube")](https://github.com/ai-chen2050/obsidian-youtube-downloader/blob/47629971ef5e035cbc4446e721599b2eae6c69f5/main.ts#L45), [.setName('Youtube save folder')](https://github.com/ai-chen2050/obsidian-youtube-downloader/blob/47629971ef5e035cbc4446e721599b2eae6c69f5/src/settingTab.ts#L35), [.setDesc('Download folder from youtube')](https://github.com/ai-chen2050/obsidian-youtube-downloader/blob/47629971ef5e035cbc4446e721599b2eae6c69f5/src/settingTab.ts#L36), [.setDesc('Proxy IP, proxy ip for download youtube video,empty is directly to download.')](https://github.com/ai-chen2050/obsidian-youtube-downloader/blob/47629971ef5e035cbc4446e721599b2eae6c69f5/src/settingTab.ts#L57), [.setDesc('默认最高分辨率,video resolution from youtube,default is heightest')](https://github.com/ai-chen2050/obsidian-youtube-downloader/blob/47629971ef5e035cbc4446e721599b2eae6c69f5/src/settingTab.ts#L70)
Use the proper capitalization of the word "YouTube"

["minAppVersion": "0.0.2",](https://github.com/ai-chen2050/obsidian-youtube-downloader/blob/47629971ef5e035cbc4446e721599b2eae6c69f5/manifest.json#L5)
This is way too low, you are using newer API's, set this to the latest public build number.

[new Setting(containerEl).setName('👉 📺 Youtube downloader zone').setHeading();](https://github.com/ai-chen2050/obsidian-youtube-downloader/blob/47629971ef5e035cbc4446e721599b2eae6c69f5/src/settingTab.ts#L25)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[.setDesc('Download folder from youtube')](https://github.com/ai-chen2050/obsidian-youtube-downloader/blob/47629971ef5e035cbc4446e721599b2eae6c69f5/src/settingTab.ts#L36)
That description feels wrong, it should be just "Download folder"

**Comment by ai-chen2050** [comment]
Hi, there. update

**Comment by joethei** [comment]
There are still 4 places where the capitalization of YouTube is not correct.

**Comment by ai-chen2050** [comment]
Thx @joethei  for pointing that out, I had been addressed issues about incorrect spelling of YouTube

**Pull request merged**
