### PR TITLE
Add  KR Book Info Plugin

### PR DESCRIPTION
**Pull request by kmsk99**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/kmsk99/kr-book-info-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [ ] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/kmsk99/kr-book-info-plugin/blob/1259cba3d3df1cbf9f2e5f32ee843e042a6df2ef/main.ts#L15
This might return null.

https://github.com/kmsk99/kr-book-info-plugin/blob/1259cba3d3df1cbf9f2e5f32ee843e042a6df2ef/main.ts#L32
Recommend sanitizing the new title in case it contains punctuations or any illegal characters in the file system.

https://github.com/kmsk99/kr-book-info-plugin/blob/1259cba3d3df1cbf9f2e5f32ee843e042a6df2ef/src/crawler.ts#L1
Recommend using Obsidian's built-in `requestUrl` function instead of using an external library.

https://github.com/kmsk99/kr-book-info-plugin/blob/1259cba3d3df1cbf9f2e5f32ee843e042a6df2ef/src/crawler.ts#L2
Recommend using the DOMParser API (https://developer.mozilla.org/en-US/docs/Web/API/DOMParser) instead of using an external library.

https://github.com/kmsk99/kr-book-info-plugin/blob/1259cba3d3df1cbf9f2e5f32ee843e042a6df2ef/src/crawler.ts#L127
Here you should create an object and use `stringifyYAML` to serialize the YAML to avoid issues with formatting characters. https://github.com/obsidianmd/obsidian-api/blob/fc616fa86533d31b1d68b45887f4c9c46da389bf/obsidian.d.ts#L2987

**Comment by kmsk99** [comment]
1. null checked
2. sanitizing filename checked
3. use requestUrl instead of axious checked
4. use DOMParser instead of cheerio checked
5. inserted yaml with stringifyYAML checked

Thanks for commenting.
Checked all of issues, I hope it will be fine.

**Comment by lishid** [comment]
https://github.com/kmsk99/kr-book-info-plugin/blob/99b3f9578283fa9940f41bcbbebd47c441c6a9bd/main.ts#L14
One more thing I forgot - you should check that the file's extension is `md` just to avoid accidentally processing attachments like PDFs and images.

**Comment by kmsk99** [comment]
Fixed extension issue. thanks a lot.

**Pull request merged**
