### PR TITLE
Adding my plugin: S3 Image uploader

### PR DESCRIPTION
**Pull request by jvsteiner**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
[S3 Image Uploader](https://github.com/jvsteiner/s3-image-uploader)

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by jvsteiner** [comment]
Hey @liamcain - I hope this is better - sorry about the previous one...

**Comment by joethei** [comment]
[import { createElement, Eye, EyeOff } from "lucide";](https://github.com/jvsteiner/s3-image-uploader/blob/91efdfe982094382c1706b30f6d50fd5833b5c22/main.ts#L14)
Obsidian already includes Lucide icons.

[MyPlugin](https://github.com/jvsteiner/s3-image-uploader/blob/91efdfe982094382c1706b30f6d50fd5833b5c22/main.ts#L48)
I would recommend renaming this to something more meaningful.

[console.log("paste event is canceled");](https://github.com/jvsteiner/s3-image-uploader/blob/91efdfe982094382c1706b30f6d50fd5833b5c22/main.ts#L80)
This can get removed.

[console.log(err);](https://github.com/jvsteiner/s3-image-uploader/blob/91efdfe982094382c1706b30f6d50fd5833b5c22/main.ts#L189)
Would recommend moving to a `console.error(err)`.

[const wrapTextWithPasswordHide = (text: TextComponent) => {](https://github.com/jvsteiner/s3-image-uploader/blob/91efdfe982094382c1706b30f6d50fd5833b5c22/main.ts#L380-L396)
A better implementation would be:
```ts
const wrapTextWithPasswordHide = (text: TextComponent) => {
	const hider = text.inputEl.createEl('span');
	setIcon(hider, 'eye-off');

	hider.addEventListener("click", ()=> {
		const isText = text.inputEl.getAttribute("type") === "text";
		if(isText) {
			setIcon(hider, 'eye-off');
			text.inputEl.setAttribute("type", "password");
		}else {
			setIcon(hider, 'eye')
			text.inputEl.setAttribute("type", "text");
		};
		text.inputEl.focus();
	});
	text.inputEl.setAttribute("type", "password");
	return text;
};
```
This uses the Obsidian API, so you don't have to include the lucide package

**Comment by jvsteiner** [comment]
Thanks for the code review - please take a look, all requested changes have been made in the latest release 0.2.2

**Comment by jvsteiner** [comment]
@joethei do I need to submit a new PR, or is what I did ok?

**Comment by joethei** [comment]
You don't need to create a new PR, someone else from the team will do a second review soon.

**Pull request merged**
