### PR TITLE
Add plugin: Ink

### PR DESCRIPTION
**Pull request by daledesilva**
# I am submitting a new Community Plugin
## Repo URL
Link to my plugin: https://github.com/daledesilva/obsidian_ink

## Release Checklist
* [x]  I have tested the plugin on
  * [ ]   Windows
  * [x]   macOS
  * [ ]   Linux
  * [ ]   Android _(if applicable)_
  * [x]   iOS _(if applicable)_
* [x]  My GitHub release contains all required files
  
  * [x]  `main.js`
  * [x]  `manifest.json`
  * [x]  `styles.css` _(optional)_
* [x]  GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
* [x]  The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
* [x]  My README.md describes the plugin's purpose and provides clear usage instructions.
* [x]  I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
* [x]  I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
* [x]  I have added a license in the LICENSE file.
* [x]  My project respects and is compatible with the original license of any code from other plugins that I'm using.
* [x]  I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by daledesilva** [comment]
[[1](https://github.com/daledesilva/obsidian_ink/blob/47dbdf904c78371cfa43221b92abc2fd89048760/src/extensions/widgets/drawing-embed-widget.tsx#L48)][[2](https://github.com/daledesilva/obsidian_ink/blob/47dbdf904c78371cfa43221b92abc2fd89048760/src/extensions/widgets/drawing-embed-widget.tsx#L55)][[3](https://github.com/daledesilva/obsidian_ink/blob/47dbdf904c78371cfa43221b92abc2fd89048760/src/extensions/widgets/writing-embed-widget.tsx#L48)][[4](https://github.com/daledesilva/obsidian_ink/blob/47dbdf904c78371cfa43221b92abc2fd89048760/src/extensions/widgets/writing-embed-widget.tsx#L55)][[5](https://github.com/daledesilva/obsidian_ink/blob/47dbdf904c78371cfa43221b92abc2fd89048760/src/utils/file-manipulation.ts#L46)][[6](https://github.com/daledesilva/obsidian_ink/blob/47dbdf904c78371cfa43221b92abc2fd89048760/src/utils/file-manipulation.ts#L104)][[7](https://github.com/daledesilva/obsidian_ink/blob/47dbdf904c78371cfa43221b92abc2fd89048760/src/utils/file-manipulation.ts#L148)]:You should not cast this, instead use a instanceof check to make sure that it's actually a file/folder.
/skip
Some of these have had redundant casts removed, but all left are necessary for typescript validation - (They are also instanceof checked already a line or two after).

[[1](https://github.com/daledesilva/obsidian_ink/blob/47dbdf904c78371cfa43221b92abc2fd89048760/src/tldraw/drawing/tldraw-drawing-editor.tsx#L220)][[2](https://github.com/daledesilva/obsidian_ink/blob/47dbdf904c78371cfa43221b92abc2fd89048760/src/tldraw/primary-menu-bar/primary-menu-bar.tsx#L74)][[3](https://github.com/daledesilva/obsidian_ink/blob/47dbdf904c78371cfa43221b92abc2fd89048760/src/tldraw/primary-menu-bar/primary-menu-bar.tsx#L78)][[4](https://github.com/daledesilva/obsidian_ink/blob/47dbdf904c78371cfa43221b92abc2fd89048760/src/tldraw/primary-menu-bar/primary-menu-bar.tsx#L81)][[5](https://github.com/daledesilva/obsidian_ink/blob/47dbdf904c78371cfa43221b92abc2fd89048760/src/tldraw/writing/tldraw-writing-editor.tsx#L243)]:You should avoid assigning styles via JavaScript or in HTML and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets.
/skip
These all require dynamic calculation at runtime and thus must be implemented from javascript.

**Comment by daledesilva** [comment]
Would like to /unskip the above so it can refresh from the repo and update it's links... but not sure how.
The valid requests things are done, but the links still point to the old versions.

**Comment by joethei** [comment]
[id: 'ddc_create-handwritten-section',](https://github.com/daledesilva/obsidian_ink/blob/75f5c2045325377e44588d4f1c8634c88c231f4b/src/main.ts#L72), [id: 'ddc_embed-writing-file',](https://github.com/daledesilva/obsidian_ink/blob/75f5c2045325377e44588d4f1c8634c88c231f4b/src/main.ts#L77), [id: 'ddc_create-drawing-section',](https://github.com/daledesilva/obsidian_ink/blob/75f5c2045325377e44588d4f1c8634c88c231f4b/src/main.ts#L90), [id: 'ddc_embed-drawing-file',](https://github.com/daledesilva/obsidian_ink/blob/75f5c2045325377e44588d4f1c8634c88c231f4b/src/main.ts#L95)
The prefix is not necessary.

[containerEl.createEl('p', {text: 'The Ink plugin enables embedding and editing handwritten and hand drawn sections directly in your markdown files.'});](https://github.com/daledesilva/obsidian_ink/blob/75f5c2045325377e44588d4f1c8634c88c231f4b/src/tabs/settings-tab/settings-tab.ts#L27-L28)
There should not be any header or description at the top of the settings tab.


[sectionEl.createEl('h2', {text: 'General'});](https://github.com/daledesilva/obsidian_ink/blob/75f5c2045325377e44588d4f1c8634c88c231f4b/src/tabs/settings-tab/settings-tab.ts#L67)
[Don't use a "general" heading in your settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by daledesilva** [comment]
> [id: 'ddc_create-handwritten-section',](https://github.com/daledesilva/obsidian_ink/blob/75f5c2045325377e44588d4f1c8634c88c231f4b/src/main.ts#L72), [id: 'ddc_embed-writing-file',](https://github.com/daledesilva/obsidian_ink/blob/75f5c2045325377e44588d4f1c8634c88c231f4b/src/main.ts#L77), [id: 'ddc_create-drawing-section',](https://github.com/daledesilva/obsidian_ink/blob/75f5c2045325377e44588d4f1c8634c88c231f4b/src/main.ts#L90), [id: 'ddc_embed-drawing-file',](https://github.com/daledesilva/obsidian_ink/blob/75f5c2045325377e44588d4f1c8634c88c231f4b/src/main.ts#L95)
> 
> The prefix is not necessary.
> 
> 
> 
> [containerEl.createEl('p', {text: 'The Ink plugin enables embedding and editing handwritten and hand drawn sections directly in your markdown files.'});](https://github.com/daledesilva/obsidian_ink/blob/75f5c2045325377e44588d4f1c8634c88c231f4b/src/tabs/settings-tab/settings-tab.ts#L27-L28)
> 
> There should not be any header or description at the top of the settings tab.
> 
> 
> 
> 
> 
> [sectionEl.createEl('h2', {text: 'General'});](https://github.com/daledesilva/obsidian_ink/blob/75f5c2045325377e44588d4f1c8634c88c231f4b/src/tabs/settings-tab/settings-tab.ts#L67)
> 
> [Don't use a "general" heading in your settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)
> 
> 
> 
> 
> 
> 

Thankyou, those have been fixed and pushed.

**Pull request merged**
