### PR TITLE
Add plugin: Todoist Project sync

### PR DESCRIPTION
**Pull request by stuporfly**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/stuporfly/ObsidianTodoistProjects

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Remove the Dist folder from the repo, release files should not be mixed with source files, and should only be available from the releases.

["description": "This plugin synchronizes projects from Todoist, creating a note for each. The note created contains a list of tasks for that project (assuming you have the Todoist Plugin). I also recommend that you install the Folder Note plugin, but it is not strictly needed.",](https://github.com/stuporfly/ObsidianTodoistProjects/blob/1c3732754491304fe4ca3a3fed1082e5b8e5c124/manifest.json#L6)
Avoid including sentences like "This is a plugin that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[// Remember to rename these classes and interfaces!](https://github.com/stuporfly/ObsidianTodoistProjects/blob/1c3732754491304fe4ca3a3fed1082e5b8e5c124/main.ts#L2)
Remove this comment.

[const os = require('os');](https://github.com/stuporfly/ObsidianTodoistProjects/blob/1c3732754491304fe4ca3a3fed1082e5b8e5c124/main.ts#L3)
Stick to one import style.

[const filename = this.settings.TodoistProjectFolder +filepath+ '/' + element.name + '.md';](https://github.com/stuporfly/ObsidianTodoistProjects/blob/1c3732754491304fe4ca3a3fed1082e5b8e5c124/main.ts#L67)
[Use `normalizePath` to clean up user defined paths](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+%60normalizePath()%60+to+clean+up+user-defined+paths)

[const isYamlEmpty: boolean = (this.app.metadataCache.getFileCache(file)?.frontmatter === undefined && !fileContent.match(/^-{3}\s*\n*\r*-{3}/));](https://github.com/stuporfly/ObsidianTodoistProjects/blob/1c3732754491304fe4ca3a3fed1082e5b8e5c124/main.ts#L150-L164)
Use the `processFrontmatter` API instead of manually modifiying YAML.

 Your plugin has no settings tab, how are users supposed to input their token and the other settings?
Also, there is a lot of documentation missing.
And please run a code formatter over your code, the indentation is very inconsistent.

**Comment by stuporfly** [comment]
@joethei 
I believe I have fixed everything you mention. 

I'm not sure what you mean by "a lot of documentation missing" - do you mean comments in the code, or something else?

**Comment by joethei** [comment]
Your README is missing a lot of information, that's what I mean by documentation missing.

**Comment by stuporfly** [comment]
@joethei I've added a bit more information about the settings. 

If that is still not enough, I would appreciate it, if you can be more specific in what I need to add to the readme - I've checked https://docs.obsidian.md/Plugins/Releasing/Submit+your+plugin and there is limited information about your requirements.

**Comment by stuporfly** [comment]
@joethei 
After getting advice in the discord, I've fixed what I hope are the only two remaining problems from your review. 

Please let me know if I have overlooked anything, or if I am supposed to do something to update the labels on this PR. 

This is my first time trying to collaborate on github, so I'm still learning the process.

**Comment by liamcain** [comment]
Hi @stuporfly, sorry for the delay. I'm taking over reviews while joethei is on sick leave.

- [corrosponding](https://github.com/stuporfly/ObsidianTodoistProjects/blob/8144777737859eb64fed3fbefdf61a6b3c0d6969/README.md#L5) typo (looks like its misspelled a bunch in this file)
- [Todoist Plugin](https://github.com/stuporfly/ObsidianTodoistProjects/blob/8144777737859eb64fed3fbefdf61a6b3c0d6969/README.md#L17) consider adding a link
- [Folder Note plugin](https://github.com/stuporfly/ObsidianTodoistProjects/blob/8144777737859eb64fed3fbefdf61a6b3c0d6969/README.md#L20) same here
- [default](https://github.com/stuporfly/ObsidianTodoistProjects/blob/8144777737859eb64fed3fbefdf61a6b3c0d6969/main.ts#L13) there shouldn't be a default value for your token. I assume the string "default" doesn't work, in which case, just leave this empty.
- [this.plugin.settings.TodoistSyncFrequency.toString](https://github.com/stuporfly/ObsidianTodoistProjects/blob/8144777737859eb64fed3fbefdf61a6b3c0d6969/main.ts#L230). You are creating the interval in onload and not updating the interval here. What you should do instead is save the interval ID and have a function that calls `clearInterval(this.refreshIntervalId);` then calls `setInterval` with the new refresh interval. Then you should call that function inside onload and again inside the `setValue()` when the interval updates.
- [this.settings.TodoistSyncFrequency * 1000](https://github.com/stuporfly/ObsidianTodoistProjects/blob/8144777737859eb64fed3fbefdf61a6b3c0d6969/main.ts#L40) you'll want to add a check to make sure that the `TodoistSyncFrequency > 0`
- ["/" + parentProj?.name](https://github.com/stuporfly/ObsidianTodoistProjects/blob/8144777737859eb64fed3fbefdf61a6b3c0d6969/main.ts#L141) you are concatenating a nullish value with a string. This has a chance to create a string like `"/undefined"` which I don't think you want. You'll probably want to add an explicit check for parentProj and handle the 2 cases separately: parentProj exists, parentProj doesn't exist.
- [folder](https://github.com/stuporfly/ObsidianTodoistProjects/blob/8144777737859eb64fed3fbefdf61a6b3c0d6969/main.ts#L49) what's this for?
- [api = new TodoistApi(this.settings.TodoistToken);](https://github.com/stuporfly/ObsidianTodoistProjects/blob/8144777737859eb64fed3fbefdf61a6b3c0d6969/main.ts#L50) you probably don't want to create this object every time updateTodoistProjectFiles is called. Consider moving this out and saving to an instance variable.
- [.then((projects: Project[]) => {](https://github.com/stuporfly/ObsidianTodoistProjects/blob/8144777737859eb64fed3fbefdf61a6b3c0d6969/main.ts#L54) consider using `await` instead of `.then().catch()` for code clarity
- [if (os.hostname() === this.settings.PrimarySyncDevice](https://github.com/stuporfly/ObsidianTodoistProjects/blob/8144777737859eb64fed3fbefdf61a6b3c0d6969/main.ts#L44) consider flipping this if-statement logic so that you can early escape instead of having all this code nested inside the if statement
- [getFiles](https://github.com/stuporfly/ObsidianTodoistProjects/blob/8144777737859eb64fed3fbefdf61a6b3c0d6969/main.ts#L56) this should probably be getMarkdownFiles
- [files.filter(file => file.path == filename).length == 0](https://github.com/stuporfly/ObsidianTodoistProjects/blob/8144777737859eb64fed3fbefdf61a6b3c0d6969/main.ts#L74) this is very expensive. You should instead use [`getAbstractFileByPath`](https://github.com/obsidianmd/obsidian-api/blob/902badd38ba907689f0917d7b193f7e33d1284fe/obsidian.d.ts#L3612) to check if the path exists. It's O(1) instead of O(n).

**Comment by stuporfly** [comment]
I'm sorry to hear that he is sick - I hope he gets well soon. 

Great feedback, thanks. 

I believe that I have made all the changes you requested/suggested. 

Please let me know if you spot anything else.

**Comment by liamcain** [comment]
- [parentProj?.name](https://github.com/stuporfly/ObsidianTodoistProjects/blob/bb265567ab03d4b0a7b5dcbc7be04d762dc63a40/main.ts#L151) the `?` is not necessary since you have an if check
- [setRefreshInterval](https://github.com/stuporfly/ObsidianTodoistProjects/blob/bb265567ab03d4b0a7b5dcbc7be04d762dc63a40/main.ts#L40) nitpick: I would suggest having this function responsible for assigning `this.refreshIntervalId` instead of just returning the value. And instead of passing in an ID, just call `this.clearInterval(this.refreshIntervalId)`. That will ensure you don't lose track of the id and fail to unassign it.

**Pull request merged**
