### PR TITLE
Add tgrosinger/ledger-obsidian

### PR DESCRIPTION
**Pull request by tgrosinger**
# I am submitting a new Community Plugin

## Repo URL

https://github.com/tgrosinger/ledger-obsidian

## Release Checklist

- [x] I have tested this on Windows, ~macOS, and Linux~ (I only have a Windows computer)
  - Also tested on Android
- [x] Github release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - `styles.css` _(optional)_
- [x] Github release name matches the exact version number specified in your manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.

### CODE REVIEW

**Comment by mgmeyers** [comment]
Two minor comments:
- https://github.com/tgrosinger/ledger-obsidian/blob/59fb329c490286e1d5c512e97503fa68b1d295b8/src/file-interface.ts#L28-L32
	- Will the leading spaces work ok for users who have "Use tabs" enabled, or have a non-standard "Tab size" in the editor settings?
- https://github.com/tgrosinger/ledger-obsidian/blob/59fb329c490286e1d5c512e97503fa68b1d295b8/src/graphics.ts#L5
	- Not an expert on this one, but according to the API (https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts#L236) svgContent should be: `the content of the SVG, without the <svg>. Must fit viewBox="0 0 100 100"`

Code looks great though. 

One additional thought: as someone who's not familiar with ledger, it might be nice to have some screenshots to show what this plugin does. Maybe I'll become a convert!

**Review by mgmeyers — APPROVED** [review]

**Comment by tgrosinger** [comment]
Thank you very much for the review. I will check on those things.

I'm not sure about the tab size question off-hand. I am completely ignoring that setting because I'm trying to follow the ledger spec instead. Ledger files aren't markdown files, so I'm kind of abusing things to get it working in Obsidian. I just wanted the nice interface and syncing!

**Comment by lishid** [comment]
https://github.com/tgrosinger/ledger-obsidian/blob/808b37daa4629cd8489024d1ba3394897122dd39/src/main.ts#L37
Consider making this `file.path` instead.

https://github.com/tgrosinger/ledger-obsidian/blob/808b37daa4629cd8489024d1ba3394897122dd39/src/main.ts#L67
Consider passing through your plugin's reference instead of txCache so you're always looking at the latest txCache the moment it's used.

Otherwise, great plugin. I'm ready to merge, let me know if you want to make changes to it before the merge, or if you want me to merge it asap.

**Comment by tgrosinger** [comment]
Thanks @lishid. Please go ahead and merge. I'll get those changes worked on tomorrow morning and push another release.

**Pull request merged**
