### PR TITLE
Add plugin: Strava Activities

### PR DESCRIPTION
**Pull request by saadsaifse**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/saadsaifse/strava-obsidian

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[id: 'authenticate-command',](https://github.com/saadsaifse/strava-obsidian/blob/9abda0b462c4e7e533a2c981e7f026a0bf964481/main.ts#L73)
`-command´ is unnecessary.

['Synchronize Strava Activities',](https://github.com/saadsaifse/strava-obsidian/blob/9abda0b462c4e7e533a2c981e7f026a0bf964481/main.ts#L91)
Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[// Perform additional things with the ribbon](https://github.com/saadsaifse/strava-obsidian/blob/9abda0b462c4e7e533a2c981e7f026a0bf964481/main.ts#L108-L109)
Remove this.

---

[export function wait(minutes: number) {](https://github.com/saadsaifse/strava-obsidian/blob/9abda0b462c4e7e533a2c981e7f026a0bf964481/src/utils.ts#L1-L8)
There is the `sleep` function in the Obsidian API that you could use instead.

**Comment by saadsaifse** [comment]
@joethei Thanks for your feedback! I have made the suggested changes!

**Comment by saadsaifse** [comment]
@joethei After some failed attempts, all checks have passed! I hope that this plugin is good to go live now. Thanks!

**Comment by saadsaifse** [comment]
@liamcain Could we please merge this PR. I have resolved the conflicts again. Thank you so much!

**Comment by joethei** [comment]
Please be patient, it will be merged, when it will be merged.
Also, you don't need to fix merge conflicts, we will handle that before the merge.

**Comment by saadsaifse** [comment]
Alright, I will leave you to it! Please feel free to reach out if you need any assistance. Thanks!

**Comment by liamcain** [comment]
- [file](https://github.com/saadsaifse/strava-obsidian/blob/ddad46811bece2d3b4cb4c5daf830c90b1477fc0/main.ts#L129) you will need to add a `file instanceof TFile` check inside the file-menu callback. This callback is also called when you right-click on folders, which might break some assumptions your code is making
- [Number(activityId),](https://github.com/saadsaifse/strava-obsidian/blob/ddad46811bece2d3b4cb4c5daf830c90b1477fc0/main.ts#L141) you should add a check to make sure this is a number and not NaN
- [ribbonIconEl.addClass('my-plugin-ribbon-class')](https://github.com/saadsaifse/strava-obsidian/blob/ddad46811bece2d3b4cb4c5daf830c90b1477fc0/main.ts#L126) remove this, this is just from the sample plugin and isn't doing anything
- [import * as _ from 'lodash'](https://github.com/saadsaifse/strava-obsidian/blob/ddad46811bece2d3b4cb4c5daf830c90b1477fc0/src/fileManager.ts#L3) small thing but you might want to fix your lodash imports so that you can rely on tree-shaking (which would reduce your main.js file size). `import { groupBy } from 'lodash';` should be enough.
- [this.vault.delete(existingFile, true)](https://github.com/saadsaifse/strava-obsidian/blob/ddad46811bece2d3b4cb4c5daf830c90b1477fc0/src/fileManager.ts#L127) why are you deleting instead of just modifying the existing file with new file contents?
- [this.token = Object.assign(this.token, refreshResponse, this.token)](https://github.com/saadsaifse/strava-obsidian/blob/ddad46811bece2d3b4cb4c5daf830c90b1477fc0/src/auth.ts#L37) this line looks wrong. Why are you assigning this.token on top of this.token?

**Pull request closed without merging**
