### PR TITLE
Add obsidian-brainframe to community-plugins.json

### PR DESCRIPTION
**Pull request by pedersen**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: : https://github.com/pedersen/obsidian-brainframe

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [X]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["fundingUrl": "https://obsidian.md/pricing",](https://github.com/pedersen/obsidian-brainframe/blob/f75c62550f09c5fa537413476472ff9928f6345a/manifest.json#L9)
If you don't have a page where users can donate to you please remove this.

[import {clipboard} from 'electron';](https://github.com/pedersen/obsidian-brainframe/blob/f75c62550f09c5fa537413476472ff9928f6345a/main.ts#L11)
Instead of this using the electron API you can use this: <https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard>, then you plugin will also work on mobile.


[hotkeys: [{modifiers: ["Mod", "Shift"], key: hotkey}],](https://github.com/pedersen/obsidian-brainframe/blob/f75c62550f09c5fa537413476472ff9928f6345a/main.ts#L40)
Don't set a hotkey by default: <https://marcus.se.net/obsidian-plugin-docs/user-interface/commands#hot-keys>

[id: 'brainframe-archive-note',](https://github.com/pedersen/obsidian-brainframe/blob/f75c62550f09c5fa537413476472ff9928f6345a/main.ts#L108)
Obsidian will automatically prefix the command id with the plugin id, so you don't need to include `brainframe` here.

[console.log('gitmarks note name: ' + value);](https://github.com/pedersen/obsidian-brainframe/blob/f75c62550f09c5fa537413476472ff9928f6345a/main.ts#L182)
[console.log('products note name: ' + value);](https://github.com/pedersen/obsidian-brainframe/blob/f75c62550f09c5fa537413476472ff9928f6345a/main.ts#L194)
[console.log('archived notes name: ' + value);](https://github.com/pedersen/obsidian-brainframe/blob/f75c62550f09c5fa537413476472ff9928f6345a/main.ts#L206)
Remove this.

**Comment by pedersen** [comment]
I've addressed all of these comments, thank you especially for the note to use navigator.clipboard. Very appreciated!

**Comment by liamcain** [comment]
- [rename](https://github.com/pedersen/obsidian-brainframe/blob/57c125d61a8b670535ca532106ed18514d52d51e/src/main.ts#L82) you should use [`renameFile`](https://github.com/obsidianmd/obsidian-api/blob/38dd22168d2925086371bfc59e36fd9121527a39/obsidian.d.ts#L1215) instead so that you safely rename the file without loosing any links.

**Comment by liamcain** [comment]
We also added some more validation to our plugin submission process so if you don't mind fixing those 2 issues, I can merge this when you're done.

**Comment by pedersen** [comment]
Thank you. I have switched to using renameFile, as well as removed `obsidian-` from the plugin id.

**Pull request merged**
