### PR TITLE
Add Simple Canvasearch

### PR DESCRIPTION
**Pull request by ddalexb**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
[https://github.com/ddalexb/obsidian-simple-canvasearch/](https://github.com/ddalexb/obsidian-simple-canvasearch/)

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "This is a simple plugin for fuzzy searching within a canvas file.",](https://github.com/ddalexb/obsidian-simple-canvasearch/blob/e050fdbcf84904fc10d4d313d75a728fdb7c9ceb/manifest.json#L6)
We have recently published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This is a simple plugin" in your description.

[import { AllCanvasNodeData } from "./canvas";](https://github.com/ddalexb/obsidian-simple-canvasearch/blob/e050fdbcf84904fc10d4d313d75a728fdb7c9ceb/main.ts#L11)
You don't need to keep a copy of the `canvas.d.ts` in your repo, you can import from "obsidian/canvas"

[id: "open-sample-modal-simple",](https://github.com/ddalexb/obsidian-simple-canvasearch/blob/e050fdbcf84904fc10d4d313d75a728fdb7c9ceb/main.ts#L77-L78)
Update the name & id to something more fitting.

[// If the plugin hooks up any global DOM events (on parts of the app that doesn't belong to this plugin)](https://github.com/ddalexb/obsidian-simple-canvasearch/blob/e050fdbcf84904fc10d4d313d75a728fdb7c9ceb/main.ts#L86-L96)
Remove this left-over code from the sample plugin.

[.addDropdown((dropDown) => {](https://github.com/ddalexb/obsidian-simple-canvasearch/blob/e050fdbcf84904fc10d4d313d75a728fdb7c9ceb/main.ts#L190-L198)
It would be better to use a toggle here, and save it as a boolean.

**Comment by ddalexb** [comment]
Thank you for the review @joethei! I implemented all the suggestions [here](https://github.com/ddalexb/obsidian-simple-canvasearch/commit/450781badcf522d8f1506cb5d1785d06257f8a3e) and re-created the release. Let me know if there's anything I missed!

**Comment by liamcain** [comment]
- [getLeaf](https://github.com/ddalexb/obsidian-simple-canvasearch/blob/4408a3c873d125e4dd4172d52c59f2b75212a893/main.ts#L105) don't use getLeaf() for this. getLeaf will actually create a new leaf if it needs to. You're actually after `activeLeaf`. It's marked as deprecated but there's not a suitable replacement for your use case since CanvasView isn't exported (and you can't use getActiveViewOfType(CanvasView)

**Comment by ddalexb** [comment]
Thank you @liamcain ! Didn't realize that's how getLeaf behaves. Applied the change [here](https://github.com/ddalexb/obsidian-simple-canvasearch/commit/4433e27741b79937dc1085c28f154b44b1efcd27) and re-released. Let me know if there's anything else you think could be improved!

**Pull request merged**
