### PR TITLE
add lock screen plugin

### PR DESCRIPTION
**Pull request by ericbiewener**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/ericbiewener/obsidian-lock-screen-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [ ] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by ericbiewener** [comment]
> I have added a license in the LICENSE file.

Can someone clarify this instruction?

**Comment by kometenstaub** [comment]
That means that you added a license to your project:

- [Options](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
- [License chooser](https://choosealicense.com/)
- [How to add a license to a repository](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)

**Comment by ericbiewener** [comment]
Gotcha, wasn't sure if there was something in the obsidian-releases repo that needed to have license information.

**Comment by lishid** [comment]
https://github.com/ericbiewener/obsidian-lock-screen-plugin/blob/c5f18d048f4ed46dbed1d7e90ed5f46bf33547ed/src/main.ts#L11
This shouldn't need to await.

https://github.com/ericbiewener/obsidian-lock-screen-plugin/blob/c5f18d048f4ed46dbed1d7e90ed5f46bf33547ed/src/main.ts#L15
This doesn't seem to do anything.

https://github.com/ericbiewener/obsidian-lock-screen-plugin/blob/c5f18d048f4ed46dbed1d7e90ed5f46bf33547ed/src/main.ts#L1
Should be just `import {Plugin} from obsidian`.

https://github.com/ericbiewener/obsidian-lock-screen-plugin/blob/c5f18d048f4ed46dbed1d7e90ed5f46bf33547ed/src/main.ts#L17
Should implement an onunload function to cleanup any leftover DOM elements when the plugin is disabled.

**Comment by ericbiewener** [comment]
> Should be just `import {Plugin} from obsidian`.

Why is that? The resulting esbuild code is equivalent.

[I have addressed the other comments.](https://github.com/ericbiewener/obsidian-lock-screen-plugin/commit/268175d70f4202f27aae5f5d3225e7186ec0e184)

**Comment by lishid** [comment]
That's fine if you want to leave it like that. I've just seen most conventions to prefer the dereferenced version instead.

**Comment by lishid** [comment]
In regards to the patch: https://github.com/ericbiewener/obsidian-lock-screen-plugin/commit/268175d70f4202f27aae5f5d3225e7186ec0e184

I think this adds a possibility of memory leak in regards to the container elements being kept in memory even after the lock screen is closed.

**Comment by ericbiewener** [comment]
> I think this adds a possibility of memory leak in regards to the container elements being kept in memory even after the lock screen is closed.

Yikes, good call. I've updated the code to simply track string ids in order to re-query the node for removal upon cleanup rather than retaining a reference to the node. See [here](https://github.com/ericbiewener/obsidian-lock-screen-plugin/blob/main/src/show-lock-screen.ts#L12-L16) and [here](https://github.com/ericbiewener/obsidian-lock-screen-plugin/blob/main/src/dom-service.ts).

**Comment by lishid** [comment]
LGTM. Perhaps clear the `ids` list once you finish the cleanup in case the component gets reused (it probably won't though).

**Comment by ericbiewener** [comment]
> LGTM. Perhaps clear the `ids` list once you finish the cleanup in case the component gets reused (it probably won't though).

Done in a patch release.

**Pull request merged**
