### PR TITLE
Add plugin: Image to notes by Photes.IO

### PR DESCRIPTION
**Pull request by islxyqwe**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:https://github.com/Kanaries/photes-io-obsidian-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["author": "kanaries data inc.",](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/manifest.json#L7)
The capitalization is not the same as in your license.

[.setTitle("From Camera")](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/main.ts#L88), [.setTitle("From Gallery")](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/main.ts#L98), [.setTitle("Generate Note from Smartphone")](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/main.ts#L111), [.setTitle("Generate Note from Image")](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/main.ts#L119), [name: "Sync Notes",](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/main.ts#L136), [new Notice("Sync Completed");](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/main.ts#L156), [name: "Upload Image from Mobile",](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/main.ts#L167), [this.statusBarItem.setText(`Photes: Uploading Image...`);](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/main.ts#L230), [this.statusBarItem.setText("Photes: Generating Note...");](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/main.ts#L232), [this.modalButtonItem.setButtonText("Uploading Image...");](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/main.ts#L238), [this.modalButtonItem.setButtonText("Generating Note...");](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/main.ts#L240), [new Notice("Photes: Uploading Image...");](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/main.ts#L244), [new Notice("Photes: Generating Note...");](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/main.ts#L246), [this.modalButtonItem.setButtonText("Generate Note");](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/main.ts#L255), [Please Report this problem](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/main.ts#L310), [Please Report this problem](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/main.ts#L329), ["Login to Generate Note"](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/main.ts#L411), [item.setTitle("Login to Generate Note");](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/main.ts#L490), [item.setTitle("Generating Note...");](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/main.ts#L502), [item.setTitle("Generate Note");](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/main.ts#L513), [new Notice(`Generate Notes Failed. ${e}`);](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/main.ts#L618), [button.setButtonText("Refresh QR Code");](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/qr.ts#L50), [onReport?.(`Sync Completed with ${failed} failed downloads`);](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/service.ts#L286), [onReport?.(`Sync Completed`);](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/service.ts#L288), [new Setting(containerEl).setName("User info").setHeading();](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/settings.ts#L55), [.setName("An Error Occurred")](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/settings.ts#L59), [.setName("Enable Auto Sync")](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/settings.ts#L102), [button.setButtonText("Sync All notes");](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/settings.ts#L135), [: "Not Synced yet"](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/settings.ts#L132), [new Notice("Sync Completed");](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/settings.ts#L153), [new Notice("Sync Completed");](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/settings.ts#L179), [.setName("Sync Path")](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/settings.ts#L199)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)


[id: "photes-sync-notes",](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/main.ts#L135), [id: "photes-upload-from-mobile",](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/main.ts#L166)
Remove the `photes` prefix. 

[this.app.setting.openTabById("photes-io-obsidian-plugin");](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/main.ts#L481)
Wrong plugin ID.

[response = await fetch(`${BASE_URL}/api/plugin/info`, {](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/service.ts#L11), [const resp = await fetch(](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/service.ts#L131), [const resp = await fetch(item.url, {](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/service.ts#L163), [const resp = await fetch(`${BASE_URL}/api/plugin/quick_login`, {](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/service.ts#L311), [const resp = await fetch(](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/sync.ts#L152), [await fetch(image.src, { mode: "no-cors" });](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/helpers.ts#L63-L75)
Use the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

[new Setting(containerEl).setHeading().setName("Sync Settings");](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/settings.ts#L100), [new Setting(containerEl).setName("Path Settings").setHeading();](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/settings.ts#L197)
[Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

[export default function Icon() {](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/0532865ff76f285113fb60addc83c62b6fa93c4c/src/assets/loader.ts#L1-L16)
Obsidian already includes lucide, just do:
```ts
setIcon(div, 'loader-circle')
```

**Comment by islxyqwe** [comment]
Hello, Thank you for your review. I had made changes to the plugin: https://github.com/Kanaries/photes-io-obsidian-plugin/compare/0.2.3...0.2.6.

**Comment by islxyqwe** [comment]
@joethei Hello, what's the status for now?

**Comment by joethei** [comment]
[const blob = await loadImageBlob(](https://github.com/Kanaries/photes-io-obsidian-plugin/blob/10facb34b53bff62c3b80d5979390e7582819ec1/src/helpers.ts#L69-L73)
Remove this fallback code.

**Comment by islxyqwe** [comment]
@joethei Hello, I had removed that fallback.

**Pull request merged**
