### PR TITLE
Add plugin: Canvas Card Background Remover

### PR DESCRIPTION
**Pull request by luxmargos**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[MyPlugin](https://github.com/luxmargos/obsidian-canvas-card-bg-remover/blob/c9308d2250aafb219eb3c0e8a8a85a9f18e6e2dd/main.ts#L96), [MySettingsTab](https://github.com/luxmargos/obsidian-canvas-card-bg-remover/blob/c9308d2250aafb219eb3c0e8a8a85a9f18e6e2dd/main.ts#L193)
[// Remember to rename these classes and interfaces!](https://github.com/luxmargos/obsidian-canvas-card-bg-remover/blob/c9308d2250aafb219eb3c0e8a8a85a9f18e6e2dd/main.ts#L3)

[styleEl.innerHTML = innerHtml;](https://github.com/luxmargos/obsidian-canvas-card-bg-remover/blob/c9308d2250aafb219eb3c0e8a8a85a9f18e6e2dd/main.ts#L133)
[Avoid using `innerHTML`](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%60innerHTML%60%2C+%60outerHTML%60+and+%60insertAdjacentHTML%60)

[id: 'canvas-sub-styler-enable',](https://github.com/luxmargos/obsidian-canvas-card-bg-remover/blob/c9308d2250aafb219eb3c0e8a8a85a9f18e6e2dd/main.ts#L149), [id: 'canvas-sub-styler-disable',](https://github.com/luxmargos/obsidian-canvas-card-bg-remover/blob/c9308d2250aafb219eb3c0e8a8a85a9f18e6e2dd/main.ts#L157)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

[globalSet.setName("Settings");](https://github.com/luxmargos/obsidian-canvas-card-bg-remover/blob/c9308d2250aafb219eb3c0e8a8a85a9f18e6e2dd/main.ts#L229)
[Don't use a "general" heading in your settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[setEnabled.setName("Enabled");](https://github.com/luxmargos/obsidian-canvas-card-bg-remover/blob/c9308d2250aafb219eb3c0e8a8a85a9f18e6e2dd/main.ts#L232-L240)
This should not be a setting, if one does not want to use the plugin they can go to the Community plugins tab and disable it there.

[applyAll.setName("Apply to All Cards");](https://github.com/luxmargos/obsidian-canvas-card-bg-remover/blob/c9308d2250aafb219eb3c0e8a8a85a9f18e6e2dd/main.ts#L246)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[found = document.createElement('style');](https://github.com/luxmargos/obsidian-canvas-card-bg-remover/blob/c9308d2250aafb219eb3c0e8a8a85a9f18e6e2dd/main.ts#L109-L112)
Do not add styles in this way, instead, inlude all the CSS code in your styles.css, and then use data attributes to style only specific cards.

**Comment by luxmargos** [comment]
I have released version 0.1.3 following your guidelines.

**Comment by joethei** [comment]
["authorUrl": "https://github.com/luxmargos/obsidian-canvas-card-bg-remover",](https://github.com/luxmargos/obsidian-canvas-card-bg-remover/blob/860722643a8cd0c41e942fed545213246ca0ee90/manifest.json#L8)
This should not point to the plugin repo, use your GitHub profile url instead.

**Comment by luxmargos** [comment]
I have released version 0.1.4 following your guidelines.

**Pull request merged**
