### PR TITLE
Add plugin: SQLSeal

### PR DESCRIPTION
**Pull request by kulak-at**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/h-sphere/sql-seal

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["id": "hypersphere-sqlseal",](https://github.com/h-sphere/sql-seal/blob/c6ffe7870c25f77cbae7ea3d4f6fb29b19703c45/manifest.json#L2)
This should not have a author name in it.

[import path from 'path'](https://github.com/h-sphere/sql-seal/blob/c6ffe7870c25f77cbae7ea3d4f6fb29b19703c45/src/database.ts#L3), [import fs from 'fs'](https://github.com/h-sphere/sql-seal/blob/c6ffe7870c25f77cbae7ea3d4f6fb29b19703c45/src/database.ts#L6), [import * as crypto from 'crypto';](https://github.com/h-sphere/sql-seal/blob/c6ffe7870c25f77cbae7ea3d4f6fb29b19703c45/src/hash.ts#L1), [import { get } from "https"](https://github.com/h-sphere/sql-seal/blob/c6ffe7870c25f77cbae7ea3d4f6fb29b19703c45/src/utils.ts#L2-L3)
These imports are only available from a Node.js runtime, which means that this will throw errors on Mobile (that's a problem since you have `isDesktopOnly` marked as `false` in your manifest.json file.

[const url = 'https://github.com/h-sphere/sql-seal/releases/download/0.2.0/better_sqlite3.node' // my github release url](https://github.com/h-sphere/sql-seal/blob/c6ffe7870c25f77cbae7ea3d4f6fb29b19703c45/src/database.ts#L87)
This should be bundled into the plugin and not downloaded.

[const gm = GrayMatter(content)](https://github.com/h-sphere/sql-seal/blob/c6ffe7870c25f77cbae7ea3d4f6fb29b19703c45/src/SealFileSync.ts#L10-L12), [const gm = GrayMatter(data)](https://github.com/h-sphere/sql-seal/blob/c6ffe7870c25f77cbae7ea3d4f6fb29b19703c45/src/sqlSeal.ts#L41-L43)
Use `this.app.metadataCache.getFileCache(file).frontmatter` to get the frontmatter data.

[name: 'Reload Vault Database',](https://github.com/h-sphere/sql-seal/blob/c6ffe7870c25f77cbae7ea3d4f6fb29b19703c45/src/SealFileSync.ts#L114), [.setName('File Selector')](https://github.com/h-sphere/sql-seal/blob/c6ffe7870c25f77cbae7ea3d4f6fb29b19703c45/src/settings.ts#L77), [.setPlaceholder('Select File')](https://github.com/h-sphere/sql-seal/blob/c6ffe7870c25f77cbae7ea3d4f6fb29b19703c45/src/settings.ts#L80)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[containerEl.createEl('h2', { text: 'My Plugin Settings' });](https://github.com/h-sphere/sql-seal/blob/c6ffe7870c25f77cbae7ea3d4f6fb29b19703c45/src/settings.ts#L28-L29)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)


[this.app.vault.on('modify', async (file) => {](https://github.com/h-sphere/sql-seal/blob/c6ffe7870c25f77cbae7ea3d4f6fb29b19703c45/src/sqlSeal.ts#L49-L51)
This event is not registered: <https://docs.obsidian.md/Plugins/Events>

[export const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms))](https://github.com/h-sphere/sql-seal/blob/c6ffe7870c25f77cbae7ea3d4f6fb29b19703c45/src/utils.ts#L53)
There is already the `sleep` function in the Obsidian API for this.

**Comment by kulak-at** [comment]
@joethei Thank you for the review, all issues are fixed now!

**Comment by kulak-at** [comment]
@joethei This has been ready for over a month now, please let me know what needs to be done to finally merge it.

**Comment by kulak-at** [comment]
@joethei All fixed now :)

**Pull request merged**
