### PR TITLE
Added Dynamic RTL plugin

### PR DESCRIPTION
**Pull request by mwxgaf**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [Dynamic RTL](https://github.com/mwxgaf/obsidian-dynamic-rtl/)

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by mwxgaf** [comment]
In correction of #1178
* ID & plugin class names are fixed
* But My plugin works both for editing mode & reading mode; I & many other people in different OSs tested this. I can prove it using a GIF if you want. There is no need to change the `README.md` because of this reason.

**Comment by joethei** [comment]
Have you tested it in Live Preview mode?
I don't think that Codemirror would handle this very well, if at all.

**Comment by mwxgaf** [comment]
> Have you tested it in Live Preview mode? I don't think that Codemirror would handle this very well, if at all.

Sure!
I & many other people tested in many devices & they were so happy!
It comes to my mind that you only visit the `main.ts` ;  but as i commented in [`main.ts:9`](https://github.com/mwxgaf/obsidian-dynamic-rtl/blob/master/main.ts#L9) , the registered `MarkdownPostProcessor` only fixes the reading mode + tables & callouts in live editing/preview mode.
Other parts of live editing/preview mode is fixed in `styles.css`  as i commented in [styles.css:3](https://github.com/mwxgaf/obsidian-dynamic-rtl/blob/master/styles.css#L3)

As you can see in video, there is not any considerable problems in both views:

https://user-images.githubusercontent.com/39344217/195393476-ba335cae-694f-458c-aa12-ca0f592174e9.mp4

**Comment by mwxgaf** [comment]
Update!
New version released that fixes conflicts with Obsidian `1.0.0` :point_right: [Version 0.2.0](https://github.com/mwxgaf/obsidian-dynamic-rtl/releases/tag/0.2.0)
& Please see [this](https://github.com/obsidianmd/obsidian-releases/pull/1199#issuecomment-1276419332)

**Pull request merged**
