### PR TITLE
Add plugin ZettelFlow

### PR DESCRIPTION
**Pull request by RafaelGB**
# I am submitting a new Community Plugin

## Repo URL
Link to my plugin: [Obsidian-ZettelFlow](https://github.com/RafaelGB/Obsidian-ZettelFlow)

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by RafaelGB** [comment]
Updated. My fault

**Comment by joethei** [comment]
Please remove the `main.js` from the repo and add it to your .gitignore - compiled release files shouldn't get mixed with source code in your commits and should go to the releases files instead.

[Copyright (c) 2022 Rafael Gómez Bermejo](https://github.com/RafaelGB/Obsidian-ZettlelFlow/blob/4a1d1163f9f0b4bc4ce45b05260a5573eca24818/LICENSE#L3)
Wrong year.

["description": "ZettelFlow is a plugin for Obsidian that helps you to create and manage your notes in a Zettelkasten way via Canvas.",](https://github.com/RafaelGB/Obsidian-ZettlelFlow/blob/4a1d1163f9f0b4bc4ce45b05260a5573eca24818/manifest.json#L6)
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This is a plugin for Obsidian" in your description.

[id: 'zettelflow-open-canvas',](https://github.com/RafaelGB/Obsidian-ZettlelFlow/blob/4a1d1163f9f0b4bc4ce45b05260a5573eca24818/src/starters/zcomponents/SettingsTab.ts#L15)
[id: 'zettelflow-open-workflow',](https://github.com/RafaelGB/Obsidian-ZettlelFlow/blob/4a1d1163f9f0b4bc4ce45b05260a5573eca24818/src/starters/zcomponents/RibbonIcon.ts#L20)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

[constructUI(containerEl: HTMLElement, heading: string) {](https://github.com/RafaelGB/Obsidian-ZettlelFlow/blob/4a1d1163f9f0b4bc4ce45b05260a5573eca24818/src/config/modals/ZettelFlowSettingsTab.ts#L13)
Remove the unused `heading` parameter.

**Comment by RafaelGB** [comment]
changes applied. The heading was not remove but used

**Comment by RafaelGB** [comment]
Thanks for your review, I have to change it in database folder plugin too then.

changes applied with some bugs fixed with a new release ([0.0.4](https://github.com/RafaelGB/Obsidian-ZettlelFlow/releases/tag/0.0.4))

**Comment by RafaelGB** [comment]
Hello @joethei , its been a while!

Is there anything else I can fix or prepare prior to uploading the plugin approval?

**Pull request merged**
