### PR TITLE
Add plugin: Lunar Calendar

### PR DESCRIPTION
**Pull request by WHG555**
# I am submitting a new Community Plugin

## Repo URL
这是一个支持农历的日历插件。
screenshot

Link to my plugin: https://github.com/WHG555/obsidian-releases

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[Copyright (c) 2021 Liam Cain](https://github.com/WHG555/lunar-calendar/blob/f2301c5511019ed553958166a43413717a1fd90e/LICENSE#L3)
Update this with your own info.

[MyPluginSettings](https://github.com/WHG555/lunar-calendar/blob/f2301c5511019ed553958166a43413717a1fd90e/src/main.ts#L11)
[MyPlugin](https://github.com/WHG555/lunar-calendar/blob/f2301c5511019ed553958166a43413717a1fd90e/src/main.ts#L23)
Rename these classes.

[this.app.workspace.detachLeavesOfType(VIEW_TYPE)](https://github.com/WHG555/lunar-calendar/blob/f2301c5511019ed553958166a43413717a1fd90e/src/main.ts#L52)
Do not detach leaves with your custom view in `onunload`, this is an antipattern, see: <https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Don't+detach+leaves+in+%60onunload%60>

[for (let i in filelist){](https://github.com/WHG555/lunar-calendar/blob/f2301c5511019ed553958166a43413717a1fd90e/src/LunarCalendar.vue#L173-L177)
[Avoid iterating all files to find a file by it's path](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+iterating+all+files+to+find+a+file+by+its+path), the `getAbstractFileByPath´ method was already the correct one.

[app.workspace.getUnpinnedLeaf()](https://github.com/WHG555/lunar-calendar/blob/f2301c5511019ed553958166a43413717a1fd90e/src/LunarCalendar.vue#L183)
It's highly discouraged that you use the global app instance in your plugin. It's currently accessible from the global context for debugging purposes, and might be removed in the future. Instead, you should use the reference to App that you have from your plugin instance.
Also, the `getUnpinnedLeaf()` method is deprecated, use `getLeaf(false)` instead.

**Comment by WHG555** [comment]
# It has been modified

MyPluginSettings
MyPlugin
Rename these classes.

this.app.workspace.detachLeavesOfType(VIEW_TYPE)
Do not detach leaves with your custom view in onunload, this is an antipattern, see: https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Don't+detach+leaves+in+%60onunload%60

for (let i in filelist){
Avoid iterating all files to find a file by it's path, the `getAbstractFileByPath´ method was already the correct one.

app.workspace.getUnpinnedLeaf()
Also, the getUnpinnedLeaf() method is deprecated, use getLeaf(false) instead.

# I don't know how to do it.

>It's highly discouraged that you use the global app instance in your plugin. It's currently accessible from the global context for debugging purposes, and might be removed in the future. Instead, you should use the reference to App that you have from your plugin instance.



I want to use the reference to App that you have from your plugin instance.But, I don't know how to do it.

**Comment by joethei** [comment]
You should just be able to pass the reference into the constructor of the class/un the function parameters.

**Comment by WHG555** [comment]
In the VUE file, i can't import plugin instances!

**Comment by WHG555** [comment]
>It's highly discouraged that you use the global app instance in your plugin. It's currently accessible from the global context for debugging purposes, and might be removed in the future. Instead, you should use the reference to App that you have from your plugin instance.

## I've made a revision for this suggestion.

**Pull request merged**
