### PR TITLE
Added obsidian-tab-key

### PR DESCRIPTION
**Pull request by jrymk**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/jrymk/obsidian-tab-key

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["id": "obsidian-tab-key",](https://github.com/jrymk/obsidian-tab-key/blob/31849c5659902c69cb87e1833185d186fce219af/manifest.json#L2-L3)
Don't include the word Obsidian in the plugin id or name.

**Comment by jrymk** [comment]
Updated plugin name and ID as per request. `community-plugins.json` has been updated accordingly.

**Comment by liamcain** [comment]
- [register](https://github.com/jrymk/restore-tab-key/blob/d49bea8f330ba4901f71594ac36557986aae0933/main.ts#L40) you don't need to do any of this. You should be able to just add an editorCallback to the command and have it execute your custom code. No need to add your own scope.

**Comment by jrymk** [comment]
https://github.com/jrymk/restore-tab-key/blob/main/main.ts

Thank you for pointing that out.
Now uses editorCallback, and when we want the default indenting action, `indentMore` is executed.

**Pull request merged**
