### PR TITLE
Add Blur plugin

### PR DESCRIPTION
**Pull request by gapmiss**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/gapmiss/blur

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[interface BlurPluginSettings {](https://github.com/gapmiss/blur/blob/4918025798e9a2a0bd208e3f9d11a15b3ebabc4c/main.ts#L3-L9)
You can remove these as you don't use any settings.

**Comment by gapmiss** [comment]
Thank you.

> [interface BlurPluginSettings {](https://github.com/gapmiss/blur/blob/4918025798e9a2a0bd208e3f9d11a15b3ebabc4c/main.ts#L3-L9)
> You can remove these as you don't use any settings.

Done.

**Review by marcusolsson — APPROVED** [review]

**Comment by liamcain** [comment]
Hi @gapmiss, I merged this before the validation script spit out the validation error on my screen. Do you mind fixing the issue with your manifest.json file and resubmitting the plugin to the list? I'll merge it as soon as that's done. You just have a mismatch between the released version and the version listed in manifest.json.

**Comment by gapmiss** [comment]
I've straightened out the version and re-submitted the plugin. Thx

**Pull request merged**
