### PR TITLE
Add plugin: WikiDocs

### PR DESCRIPTION
**Pull request by pahkey**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/pahkey/obsidian-wikidocs-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[containerEl.createEl("h2", { text: "플러그인 설정" });](https://github.com/pahkey/obsidian-wikidocs-plugin/blob/06d3446be49d61bb492c43a9ee27576aea7520be/main.ts#L373-L374)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[const content = await this.app.vault.read(file);](https://github.com/pahkey/obsidian-wikidocs-plugin/blob/06d3446be49d61bb492c43a9ee27576aea7520be/lib/md.ts#L223-L229), [const lines = frontMatter.split("\n");](https://github.com/pahkey/obsidian-wikidocs-plugin/blob/06d3446be49d61bb492c43a9ee27576aea7520be/lib/md.ts#L40-L48), [const content = await this.app.vault.read(file);](https://github.com/pahkey/obsidian-wikidocs-plugin/blob/06d3446be49d61bb492c43a9ee27576aea7520be/lib/md.ts#L211-L215), [const content = await this.app.vault.read(file);](https://github.com/pahkey/obsidian-wikidocs-plugin/blob/06d3446be49d61bb492c43a9ee27576aea7520be/lib/md.ts#L223-L229), [// Parse Front Matter-style metadata](https://github.com/pahkey/obsidian-wikidocs-plugin/blob/06d3446be49d61bb492c43a9ee27576aea7520be/lib/utils.ts#L46-L58)
Use the MetadataCache API instead of manually parsing the file and the YAML.

[const frontMatterMatch = content.match(/^---[\s\S]*?---\n/);](https://github.com/pahkey/obsidian-wikidocs-plugin/blob/06d3446be49d61bb492c43a9ee27576aea7520be/lib/md.ts#L182-L203)
Use the `processFrontMatter` function to change the frontmatter content.

[export function sanitizeFileName(fileName: string): string {](https://github.com/pahkey/obsidian-wikidocs-plugin/blob/06d3446be49d61bb492c43a9ee27576aea7520be/lib/utils.ts#L4-L6)
Use the `normalizePath` function from the Obsidian API instead.

[const imageRegex = /!\[.*?\]\((.+?)\)/g;](https://github.com/pahkey/obsidian-wikidocs-plugin/blob/06d3446be49d61bb492c43a9ee27576aea7520be/lib/utils.ts#L95-L109)
Use the MetadataCache API to get all the embeds, instead of manually parsing.

**Comment by pahkey** [comment]
I have applied all the changes you suggested.

**Comment by joethei** [comment]
[const content = await file.vault.read(abstractFile);](https://github.com/pahkey/obsidian-wikidocs-plugin/blob/1b50ddc55f963756c692776cc67d4d4f65ca55da/lib/md.ts#L125-L139)
This should also use the MetadataCache API.

[const imageFile = this.app.vault.getAbstractFileByPath(decodedPath);](https://github.com/pahkey/obsidian-wikidocs-plugin/blob/1b50ddc55f963756c692776cc67d4d4f65ca55da/lib/utils.ts#L98)
Use the `getFirstLinkpathDest` function to get the file, the link retrieved from the metadata cache is relative.

**Comment by pahkey** [comment]
I've made the changes you pointed out.

**Pull request merged**
