### PR TITLE
Add plugin: simple-sketch

### PR DESCRIPTION
**Pull request by Yohh**
# I am submitting a new Community Plugin

Link to my plugin:

https://github.com/Yohh/obsidian-simple-sketch

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Yohh** [comment]
> #### Hello!
> 
> **I found the following issues in your plugin submission**
> 
> **Errors:**
> 
> ❌ Your latest Release is missing the `main.js` file. ❌ Your latest Release is missing the `manifest.json` file.
> 
> This check was done automatically. Do NOT open a new PR for re-validation. Instead, to trigger this check again, make a change to your PR and wait a few minutes, or close and re-open it.

done

**Comment by Yohh** [comment]
fixed

**Comment by Yohh** [comment]
sorry for all those bot conversations, I'm not used to managing PRS code changes directly on GitHub

**Comment by Yohh** [comment]
@joethei , sorry but the failed check seems weird to me, I can't see where is the problem

**Comment by joethei** [comment]
Your README is missing a lot of information on how to use the plugin.
Some screenshots/GIFs would also be nice.

[### For Users](https://github.com/Yohh/obsidian-simple-sketch/blob/8dc054e062d9f66fe37ece26c5f880e791623810/README.md#L38-L44)
And these are not the correct installation instructions

["description": "A simple sketch plugin.",](https://github.com/Yohh/obsidian-simple-sketch/blob/8dc054e062d9f66fe37ece26c5f880e791623810/manifest.json#L6)
Avoid including sentences like "A simple ... plugin" in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

**Comment by Yohh** [comment]
> Your README is missing a lot of information on how to use the plugin. Some screenshots/GIFs would also be nice.
> 
> [### For Users](https://github.com/Yohh/obsidian-simple-sketch/blob/8dc054e062d9f66fe37ece26c5f880e791623810/README.md#L38-L44) And these are not the correct installation instructions
> 
> ["description": "A simple sketch plugin.",](https://github.com/Yohh/obsidian-simple-sketch/blob/8dc054e062d9f66fe37ece26c5f880e791623810/manifest.json#L6) Avoid including sentences like "A simple ... plugin" in your description, it should be self-evident that this is a plugin for Obsidian. We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

thanks for the review, it's done

**Pull request merged**
