### PR TITLE
 Add Speech To Text Keyboard Helper

### PR DESCRIPTION
**Pull request by mwoz123**
add Speech To Text Keyboard Helper

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/mwoz123/speech-to-text-keyboard-helper

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My ~~GitHub~~ ~~GitLab~~ Github release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] ~~GitHub~~ ~~GitLab~~ github release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Hi, we currently do not support plugins hosted on services other than GitHub.
Your repository needs to be hosted on GitHub.

**Comment by mwoz123** [comment]
@joethei migrated to github

**Comment by joethei** [comment]
["description": "As Google Speech to Text Android keyboard does not handle _new line_ command, this plugin makes available such commands via Obsidian command pallete (and from there could be added to mobile buttons toolbar).",](https://github.com/mwoz123/speech-to-text-keyboard-helper/blob/e9c58be0e9ede4a34447f9e35381481a6a2b1748/manifest.json#L6-L7)
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[id: "speach2text-kb-prepend-new-line",](https://github.com/mwoz123/speech-to-text-keyboard-helper/blob/e9c58be0e9ede4a34447f9e35381481a6a2b1748/main.ts#L7)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

**Comment by mwoz123** [comment]
@joethei done;)

**Pull request merged**
