### PR TITLE
Add plugin Logstravaganza

### PR DESCRIPTION
**Pull request by czottmann**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/czottmann/obsidian-logstravaganza

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[export function debounce(func: Function, delayInMs: number): Function {](https://github.com/czottmann/obsidian-logstravaganza/blob/2402c051834eaa534983abeb893dc13bae7119e4/src/utils.ts#L10)
Obsidian already exports a `debounce` function.

[window.app.workspace.onLayoutReady(async () => {](https://github.com/czottmann/obsidian-logstravaganza/blob/2402c051834eaa534983abeb893dc13bae7119e4/src/logging.ts#L35)
It's highly discouraged that you use the global app instance in your plugin. It's currently accessible from the global context for debugging purposes, and might be removed in the future. Instead, you should use the reference to App that you have from your plugin instance.

[// Read the current content of the note file](https://github.com/czottmann/obsidian-logstravaganza/blob/2402c051834eaa534983abeb893dc13bae7119e4/src/logging.ts#L77-L82)
I would recommend using the [`process`](https://docs.obsidian.md/Reference/TypeScript+API/Vault/process#Vault.process()+method) method here, to avoid issues.

**Comment by czottmann** [comment]
Hi @joethei, thanks for the input. I've refactored the whole plugin to fix those issue. Thanks for the tip re `Vault.process()`, that was new to me.

**Comment by czottmann** [comment]
Hi @joethei, is there anything else missing here that I can provide, or can I help out with something?

**Comment by czottmann** [comment]
@joethei @marcusolsson Any updates yet? Is there anything else missing here that I need to provide?

I guess you're "just" busy (I'd get that!) but the silence is a bit disconcerting nonetheless.

**Comment by czottmann** [comment]
Thanks, @liamcain!

**Pull request merged**
