### PR TITLE
Add Fluent theme

### PR DESCRIPTION
**Pull request by eth-p**
# I am submitting a new Community Theme

## Repo URL

Link to my theme: 

## Theme checklist

- [x] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo).
  - [x] `obsidian.css`
  - [x] The screenshot file.
- [x] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other themes that I'm using.
      I have given proper attribution to these other themes in my `README.md`.

### CODE REVIEW

**Comment by ericaxu** [comment]
Can't find your theme, could you post a link? Please make sure it's a public repo.

**Comment by eth-p** [comment]
Hi @ericaxu! My bad on that, I forgot that the repo was private. Sorry about the delay to change it, but I found some problems and had to fix them first. Everything should be good now though!

**Comment by ericaxu** [comment]
One minor thing: you might want to make the screenshot smaller while keeping the 16:9 aspect ratio. That would make your theme load faster in the theme store. You can still include high resolution screenshots in your README.

We recommend using a screenshot of size 512px by 288px as the featured screenshot to minimize loading time.

**Comment by joethei** [comment]
Hi @eth-p, do you still intend on submitting this theme?

**Pull request closed without merging**
