### PR TITLE
Add plugin: UUID Generator

### PR DESCRIPTION
**Pull request by taylow**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/taylow/obsidian-uuid

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by taylow** [comment]
I followed [this](https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/Guides/How+to+add+your+plugin+to+the+community+plugin+list) which indicated that I needed a `branch` property, but apparently that isn't the case!

**Comment by joethei** [comment]
["fundingUrl": "https://taylo.dev",](https://github.com/taylow/obsidian-uuid/blob/453ae844616f88bf68fdb981ce432219c36199db/manifest.json#L9)
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link omit this.

[containerEl.createEl("h2", { text: "UUID Generator Settings" });](https://github.com/taylow/obsidian-uuid/blob/453ae844616f88bf68fdb981ce432219c36199db/main.ts#L89)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by ericaxu** [comment]
@taylow Hi, did you see joethei's comment? Those fixes should be simple. Let us know when you've fixed them so we can move forward!

**Comment by ericaxu** [comment]
Hi there, to keep things tidy, we're going to temporarily close plugin PRs after a month of inactivity.

Feel free to tell us to re-open it when you're ready to continue and we'll reopen the PR right away. Thanks for your understanding!

**Comment by taylow** [comment]
Hi, I have made the necessary changes and I'm ready to reopen this PR :)

**Comment by joethei** [comment]
Please remove everything from the README that's not meant for end users.

**Pull request closed without merging**
