### PR TITLE
Add plugin: Enhanced Copy

### PR DESCRIPTION
**Pull request by Lisandra-dev**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Lisandra-dev/obsidian-enhanced-copy

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Lisandra-dev** [comment]
For the part with inner and outer,  I don't think I can switch to Obsidian DOM API... Need I really to use it?

**Comment by Lisandra-dev** [comment]
/skip 
1. Corrected
2. InnerHTML/outerHTML : The plugin never inject HTML onto Obsidian. Instead, it copy the DOM in local, as pure string. I don't know if there is other way to copy the DOM (mainly in the reading view). Maybe using CodeMirror ? But, as I don't edit the DOM, i don't think is valuable here.
3. Error : It's a string name in the translation (`i18next.t("callout.obsidian")`)
4. Hotkeys was set to `[]` but I removed the line completely.

**Comment by joethei** [comment]
[this.settingsPage.createEl("h1", { text: i18next.t("reading.desc") });](https://github.com/Lisandra-dev/obsidian-enhanced-copy/blob/1afe7d24e527c34d2a7585df2b6146d4acd39e5b/src/settings.ts#L40), [this.settingsPage.createEl("h2", { text: i18next.t("other") });](https://github.com/Lisandra-dev/obsidian-enhanced-copy/blob/1afe7d24e527c34d2a7585df2b6146d4acd39e5b/src/settings.ts#L65), [this.settingsPage.createEl("h1", { text: i18next.t("edit.desc") });](https://github.com/Lisandra-dev/obsidian-enhanced-copy/blob/1afe7d24e527c34d2a7585df2b6146d4acd39e5b/src/settings.ts#L85), [this.settingsPage.createEl("h2", { text: i18next.t("unconventionalMarkdown.title") });](https://github.com/Lisandra-dev/obsidian-enhanced-copy/blob/1afe7d24e527c34d2a7585df2b6146d4acd39e5b/src/settings.ts#L130), [this.settingsPage.createEl("h2", { text: i18next.t("other") });](https://github.com/Lisandra-dev/obsidian-enhanced-copy/blob/1afe7d24e527c34d2a7585df2b6146d4acd39e5b/src/settings.ts#L134), [this.settingsPage.createEl("h1", { text: i18next.t("global.title") });](https://github.com/Lisandra-dev/obsidian-enhanced-copy/blob/1afe7d24e527c34d2a7585df2b6146d4acd39e5b/src/settings.ts#L284)
For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```

[console.log("GET SELECTION AS HTML");](https://github.com/Lisandra-dev/obsidian-enhanced-copy/blob/1afe7d24e527c34d2a7585df2b6146d4acd39e5b/src/utils/selection.ts#L16)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

**Comment by Lisandra-dev** [comment]
Hello,
Asked change was made

**Comment by Lisandra-dev** [comment]
Hello! It's been 15 days since I made the change ^^'

**Comment by Lisandra-dev** [comment]
Hello, i'm pretty sorry to bother. I saw some plugin was release before mine, so I want to know if there are some problem!

Have a good day :)

**Pull request merged**
