### PR TITLE
Add plugin: Google Blogger

### PR DESCRIPTION
**Pull request by privet-kitty**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/privet-kitty/obsidian-blogger/

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by privet-kitty** [comment]
> [[1](https://github.com/privet-kitty/obsidian-blogger/blob/f2ae17a794ca777d99e99cea006280903783e3dc/src/markdown-it-mathjax3-plugin.ts#L67)][[2](https://github.com/privet-kitty/obsidian-blogger/blob/f2ae17a794ca777d99e99cea006280903783e3dc/src/markdown-it-mathjax3-plugin.ts#L68)]:Using innerHTML, outerHTML or similar API's is a security risk. Instead, use the DOM API or the Obsidian helper functions: https://docs.obsidian.md/Plugins/User+interface/HTML+elements

/skip These `outerHTML`s are not the property of HTML Element but a method of MathJax, which renders math content to HTML string.

> [[1](https://github.com/privet-kitty/obsidian-blogger/blob/f2ae17a794ca777d99e99cea006280903783e3dc/src/rest-client.ts#L17)][[2](https://github.com/privet-kitty/obsidian-blogger/blob/f2ae17a794ca777d99e99cea006280903783e3dc/src/rest-client.ts#L41)][[3](https://github.com/privet-kitty/obsidian-blogger/blob/f2ae17a794ca777d99e99cea006280903783e3dc/src/rest-client.ts#L51)][[4](https://github.com/privet-kitty/obsidian-blogger/blob/f2ae17a794ca777d99e99cea006280903783e3dc/src/rest-client.ts#L93)][[5](https://github.com/privet-kitty/obsidian-blogger/blob/f2ae17a794ca777d99e99cea006280903783e3dc/src/rest-client.ts#L136)][[6](https://github.com/privet-kitty/obsidian-blogger/blob/f2ae17a794ca777d99e99cea006280903783e3dc/src/oauth2-client.ts#L80)][[7](https://github.com/privet-kitty/obsidian-blogger/blob/f2ae17a794ca777d99e99cea006280903783e3dc/src/oauth2-client.ts#L221)][[8](https://github.com/privet-kitty/obsidian-blogger/blob/f2ae17a794ca777d99e99cea006280903783e3dc/src/blogger-client.ts#L290)][[9](https://github.com/privet-kitty/obsidian-blogger/blob/f2ae17a794ca777d99e99cea006280903783e3dc/src/blogger-client.ts#L370)][[10](https://github.com/privet-kitty/obsidian-blogger/blob/f2ae17a794ca777d99e99cea006280903783e3dc/src/blogger-oauth2-client.ts#L54)][[11](https://github.com/privet-kitty/obsidian-blogger/blob/f2ae17a794ca777d99e99cea006280903783e3dc/src/blogger-profile-modal.ts#L40)][[12](https://github.com/privet-kitty/obsidian-blogger/blob/f2ae17a794ca777d99e99cea006280903783e3dc/src/blogger-profile-modal.ts#L50)][[13](https://github.com/privet-kitty/obsidian-blogger/blob/f2ae17a794ca777d99e99cea006280903783e3dc/src/blogger-profile-manage-modal.ts#L55)][[14](https://github.com/privet-kitty/obsidian-blogger/blob/f2ae17a794ca777d99e99cea006280903783e3dc/src/blogger-profile-manage-modal.ts#L105)][[15](https://github.com/privet-kitty/obsidian-blogger/blob/f2ae17a794ca777d99e99cea006280903783e3dc/src/main.ts#L55)]:You should consider limiting the number of console.logs in your code, to not pollute the dev console.

I removed all and released version 0.9.4.

**Comment by privet-kitty** [comment]
Apart from the resolved validation errors and conflicts, the problem appears to be the failure of a ["Skip on comment" workflow](https://github.com/obsidianmd/obsidian-releases/actions/runs/8205098034/job/22441212605), which ran on https://github.com/obsidianmd/obsidian-releases/pull/3195#issuecomment-1985849273. The error message `failed to update https://github.com/obsidianmd/obsidian-releases/pull/3195: 'ObsidianReviewBot' not found` in the log is enigmatic to me.

**Comment by joethei** [comment]
["description": "A plugin for publishing Obsidian documents to Google Blogger.",](https://github.com/privet-kitty/obsidian-blogger/blob/d34ccecc8d37c3d2f08887afe8132d287b63f3d9/manifest.json#L6)
Remove "Obsidian" from the description, and replace "documents" with notes.

[updateRibbonIcon = () => {](https://github.com/privet-kitty/obsidian-blogger/blob/d34ccecc8d37c3d2f08887afe8132d287b63f3d9/src/main.ts#L124-L138), [new Setting(containerEl)](https://github.com/privet-kitty/obsidian-blogger/blob/d34ccecc8d37c3d2f08887afe8132d287b63f3d9/src/setting-tab.ts#L76-L86)
As of v1.1.0 of Obsidian, the ribbon can be customized within Obsidian. So users can choose what items to include and in what order all in one place. Because of this, we're recommending that new plugins avoid introducing their own toggles for ribbon items.

[containerEl.createEl('h1', { text: t('settings_title') });](https://github.com/privet-kitty/obsidian-blogger/blob/d34ccecc8d37c3d2f08887afe8132d287b63f3d9/src/setting-tab.ts#L39)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.), there should not be a top level header for settings.

["settings_defaultPostStatus": "Default Post Status",](https://github.com/privet-kitty/obsidian-blogger/blob/d34ccecc8d37c3d2f08887afe8132d287b63f3d9/src/i18n/en.json#L48), ["settings_fetchBlogIdButtonText": "Fetch Blog ID",](https://github.com/privet-kitty/obsidian-blogger/blob/d34ccecc8d37c3d2f08887afe8132d287b63f3d9/src/i18n/en.json#L52), ["settings_defaultPostComment": "Default Comment Status",](https://github.com/privet-kitty/obsidian-blogger/blob/d34ccecc8d37c3d2f08887afe8132d287b63f3d9/src/i18n/en.json#L60), ["settings_mathJaxOutputType": "MathJax Output Format",](https://github.com/privet-kitty/obsidian-blogger/blob/d34ccecc8d37c3d2f08887afe8132d287b63f3d9/src/i18n/en.json#L64), ["publishModal_postStatus": "Post Status",](https://github.com/privet-kitty/obsidian-blogger/blob/d34ccecc8d37c3d2f08887afe8132d287b63f3d9/src/i18n/en.json#L75), ["profileModal_setDefault": "Set Default",](https://github.com/privet-kitty/obsidian-blogger/blob/d34ccecc8d37c3d2f08887afe8132d287b63f3d9/src/i18n/en.json#L94), ["profiles_default": "Default Profile",](https://github.com/privet-kitty/obsidian-blogger/blob/d34ccecc8d37c3d2f08887afe8132d287b63f3d9/src/i18n/en.json#L97)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by privet-kitty** [comment]
@joethei Thank you for your review! I believe every point you gave has been addressed in the new version 0.9.5.

---

> ["description": "A plugin for publishing Obsidian documents to Google Blogger.",](https://github.com/privet-kitty/obsidian-blogger/blob/d34ccecc8d37c3d2f08887afe8132d287b63f3d9/manifest.json#L6)
Remove "Obsidian" from the description, and replace "documents" with notes.

https://github.com/privet-kitty/obsidian-blogger/commit/19b24346462a949917ad3b296840ff77e2564f97

> [updateRibbonIcon = () => {](https://github.com/privet-kitty/obsidian-blogger/blob/d34ccecc8d37c3d2f08887afe8132d287b63f3d9/src/main.ts#L124-L138), [new Setting(containerEl)](https://github.com/privet-kitty/obsidian-blogger/blob/d34ccecc8d37c3d2f08887afe8132d287b63f3d9/src/setting-tab.ts#L76-L86)
As of v1.1.0 of Obsidian, the ribbon can be customized within Obsidian. So users can choose what items to include and in what order all in one place. Because of this, we're recommending that new plugins avoid introducing their own toggles for ribbon items.

https://github.com/privet-kitty/obsidian-blogger/commit/e7db617c07b3c414ed6d0ea9733663097bbd3133

> [containerEl.createEl('h1', { text: t('settings_title') });](https://github.com/privet-kitty/obsidian-blogger/blob/d34ccecc8d37c3d2f08887afe8132d287b63f3d9/src/setting-tab.ts#L39)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.), there should not be a top level header for settings.

https://github.com/privet-kitty/obsidian-blogger/commit/96dfafa205c73c5a79ac953862ddeea82e028432

> ["settings_defaultPostStatus": "Default Post Status",](https://github.com/privet-kitty/obsidian-blogger/blob/d34ccecc8d37c3d2f08887afe8132d287b63f3d9/src/i18n/en.json#L48), ["settings_fetchBlogIdButtonText": "Fetch Blog ID",](https://github.com/privet-kitty/obsidian-blogger/blob/d34ccecc8d37c3d2f08887afe8132d287b63f3d9/src/i18n/en.json#L52), ["settings_defaultPostComment": "Default Comment Status",](https://github.com/privet-kitty/obsidian-blogger/blob/d34ccecc8d37c3d2f08887afe8132d287b63f3d9/src/i18n/en.json#L60), ["settings_mathJaxOutputType": "MathJax Output Format",](https://github.com/privet-kitty/obsidian-blogger/blob/d34ccecc8d37c3d2f08887afe8132d287b63f3d9/src/i18n/en.json#L64), ["publishModal_postStatus": "Post Status",](https://github.com/privet-kitty/obsidian-blogger/blob/d34ccecc8d37c3d2f08887afe8132d287b63f3d9/src/i18n/en.json#L75), ["profileModal_setDefault": "Set Default",](https://github.com/privet-kitty/obsidian-blogger/blob/d34ccecc8d37c3d2f08887afe8132d287b63f3d9/src/i18n/en.json#L94), ["profiles_default": "Default Profile",](https://github.com/privet-kitty/obsidian-blogger/blob/d34ccecc8d37c3d2f08887afe8132d287b63f3d9/src/i18n/en.json#L97)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

https://github.com/privet-kitty/obsidian-blogger/commit/1da8a3b9c957e29513bb2f86477c84bba1f83dc9

**Comment by privet-kitty** [comment]
Are there any other remaining tasks?

**Comment by joethei** [comment]
["description": "A plugin for publishing notes to Google Blogger.",](https://github.com/privet-kitty/obsidian-blogger/blob/64a5daa7a36f3572b191e2e49ecd48751b3d6992/manifest.json#L6C3-L6C69)
It should be obvious that this is a plugin, no need to mention it in the description.

**Comment by privet-kitty** [comment]
@joethei thanks! fixed

**Pull request merged**
