### PR TITLE
Add plugin: Better Export PDF

### PR DESCRIPTION
**Pull request by l1xnan**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/l1xnan/obsidian-better-export-pdf

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by MorrowShore** [comment]
Hello! Lovely plugin! Consider adding dark-mode option for export and another hotkey option for instant exporting with previous settings.
你好！ 可爱的项目！ 请考虑添加暗模式选项和用于即时导出的热键选项。

**Comment by l1xnan** [comment]
> Hello! Lovely plugin! Consider adding dark-mode option for export and another hotkey option for instant exporting with previous settings. 你好！ 可爱的项目！ 请考虑添加暗模式选项和用于即时导出的热键选项。

1. In dark mode, PDF export is not good, so the plugin removes `class="theme-dark"`, adds `class="theme-light"` (which is officially implemented), and does nothing else.  So you can add your own dark mode style, note that it can't depend on `class="theme-dark"`.
2. There is currently no default hotkey, you can set it up yourself first.

**Comment by l1xnan** [comment]
1. Some styles need to be handled dynamically, so they are embedded in JS.
2. Since injecting the rendered result into the `webview` requires the `innerHTML` API, it can't use the official HTML elements API, and there's no other good way to do it.
3. The `console.log` issue has been fixed.

/skip

**Comment by CodingWithAnxiety** [comment]
If you would like, I can test this plugin on linux.

**Comment by l1xnan** [comment]
> If you would like, I can test this plugin on linux.

@CodingWithAnxiety Thanks, if you have any issues, please give me feedback.

**Comment by joethei** [comment]
["description": "Obsidian PDF export enhancement plugin that adds the ability to export bookmarks outline and add page numbers to PDF compared to the official PDF export function.",](https://github.com/l1xnan/obsidian-better-export-pdf/blob/c75478fc8ea1145c5db6545da1cdec2b88743f99/manifest.json#L6)
Avoid including sentences like "This is a plugin for Obsidian that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[name: "Export Current file to PDF",](https://github.com/l1xnan/obsidian-better-export-pdf/blob/c75478fc8ea1145c5db6545da1cdec2b88743f99/src/main.ts#L47)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[return;](https://github.com/l1xnan/obsidian-better-export-pdf/blob/c75478fc8ea1145c5db6545da1cdec2b88743f99/src/main.ts#L52)
This should be `return false;´

[new Setting(containerEl).setName("Better Export PDF").setHeading();](https://github.com/l1xnan/obsidian-better-export-pdf/blob/c75478fc8ea1145c5db6545da1cdec2b88743f99/src/setting.ts#L32)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[new Setting(containerEl).setName("General").setHeading();](https://github.com/l1xnan/obsidian-better-export-pdf/blob/c75478fc8ea1145c5db6545da1cdec2b88743f99/src/setting.ts#L41)
[Don't use a "general" heading in your settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by l1xnan** [comment]
@joethei Thanks for the code review, the issues have been fixed.
https://github.com/l1xnan/obsidian-better-export-pdf/commit/e9f6864e939d8ba8e59a388c5a683a63852c8194
https://github.com/l1xnan/obsidian-better-export-pdf/commit/b9968d2e3dd8f3670641684595f081e7b120fdec

**Comment by l1xnan** [comment]
@joethei Do I need to resolve the conflicting files?

**Comment by joethei** [comment]
No, we will do that when merging

**Comment by l1xnan** [comment]
Okay, this plugin has been through several recent iterations, with some code changes. I'm not very familiar with some of the specifications for plugin development. If there are any issues with this plugin, please let me know. Thank you for your review!🙂

**Comment by liamcain** [comment]
- [Export Current File to PDF](https://github.com/l1xnan/obsidian-better-export-pdf/blob/d4eebfadb32dc609b57bffb277d015c4ac4ecfbc/src/main.ts#L56) this should be [Sentence case](https://en.wiktionary.org/wiki/sentence_case)

**Comment by CodingWithAnxiety** [comment]
> > If you would like, I can test this plugin on linux.
> 
> @CodingWithAnxiety Thanks, if you have any issues, please give me feedback.

Appears to be functional in linux. KDE plasma 6 is the DE I am using on arch. I haven't put it through any heavy use / stress testing yet tho

**Pull request merged**
