### PR TITLE
Add note-highlighter plugin

### PR DESCRIPTION
**Pull request by JeremiahKoeiman**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/JeremiahKoeiman/obsidian-note-highlighter

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["This plugin will highlight the notes that have 1 or more todos in them.",](https://github.com/JeremiahKoeiman/obsidian-note-highlighter/blob/ef6fc4c52a9641870009f5f2d083f00fc303d338/manifest.json#L6)
We have recently published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This plugin" in your description.

**Comment by JeremiahKoeiman** [comment]
The descriptions have been updated

**Comment by JeremiahKoeiman** [comment]
Are there any updates on this pr?

**Comment by JeremiahKoeiman** [comment]
@joethei @marcusolsson the plugin is ready to be released.

**Comment by marcusolsson** [comment]
- https://github.com/JeremiahKoeiman/obsidian-note-highlighter/blob/552a04dc295e6b554dde2b8c31e9661d210ff7d7/src/settings.ts#L24
  https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#UI+text

**Comment by ericaxu** [comment]
Hi there, to keep things tidy, we're going to temporarily close plugin PRs after a month of inactivity.

Feel free to tell us to re-open it when you're ready to continue. Thanks for your understanding!

**Pull request closed without merging**
