### PR TITLE
Update community-plugins.json

### PR DESCRIPTION
**Pull request by brainoverflow98**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/brainoverflow98/obsidian-text-to-speech-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lishid** [comment]
Have you considered collaborating with the author of this plugin? https://github.com/joethei/obsidian-tts

**Comment by brainoverflow98** [comment]
> Have you considered collaborating with the author of this plugin? https://github.com/joethei/obsidian-tts

Wow I'haven't realise that there was already a plugin which does the same thing. I looked at some qustions in the forum and thought there wasn't one. Info on the forum entries must be out dated.

Basically it does the same thing as mine so I thing there is no need for mine.
 
Thanks for the info !

**Comment by joethei** [comment]
@brainoverflow98
Since you contributed to my plugin, 
you should probably close this issue, as well as add a note to the README of your plugin
to redirect users to my plugin.
Your plugin has been featured on the roundup and some users might wait indefinitely for this plugin to be released.

**Comment by lishid** [comment]
Seems like you guys are working together? I will close down this PR for now, if @brainoverflow98 decide to work on this plugin further down a different road, feel free to re-open this PR later.

**Pull request closed without merging**
