### PR TITLE
Adding bhagyas/obsidian-postfix-plugin - Update community-plugins.json

### PR DESCRIPTION
**Pull request by bhagyas**
Adding bhagyas/obsidian-postfix-plugin.

Announcement: https://forum.obsidian.md/t/announcing-the-obsidian-postfix-plugin/61752

Please switch to **Preview** and select one of the following links:

* [Community Plugin](?template=plugin.md)
* [Community Theme](?template=theme.md)

### CODE REVIEW

**Review by bhagyas — COMMENTED** [review]
Adding bhagyas/obsidian-postfix-plugin.  Announcement: https://forum.obsidian.md/t/announcing-the-obsidian-postfix-plugin/61752

**Review by bhagyas — COMMENTED** [review]
Adding bhagyas/obsidian-postfix-plugin.  Announcement: https://forum.obsidian.md/t/announcing-the-obsidian-postfix-plugin/61752

**Comment by joethei** [comment]
Please fill the pull request template.

**Comment by bhagyas** [comment]
# I am submitting a new Community Plugin
## Repo URL
Link to my plugin: https://github.com/bhagyas/obsidian-postfix-plugin

## Release Checklist
* [x]  I have tested the plugin on
  
  * [ ]   Windows
  * [x]   macOS
  * [ ]   Linux
  * [ ]   Android _(if applicable)_
  * [ ]   iOS _(if applicable)_
* [x]  My GitHub release contains all required files
  
  * [x]  `main.js`
  * [x]  `manifest.json`
  * [x]  `styles.css` _(optional)_
* [x]  GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
* [x]  The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
* [x]  My README.md describes the plugin's purpose and provides clear usage instructions.
* [x]  I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
* [x]  I have added a license in the LICENSE file.
* [x]  My project respects and is compatible with the original license of any code from other plugins that I'm using.
  I have given proper attribution to these other projects in my `README.md`.

**Comment by bhagyas** [comment]
@joethei Completed the pull request template.

**Comment by joethei** [comment]
Cleanup your readme, most of the content is not relevant to users, these can be removed:
- [This project uses Typescript to provide type checking and documentation.](https://github.com/bhagyas/obsidian-postfix-plugin/blob/69ce01c7ef250e47667fa867750143711a03beca/README.md#L5-L8)
- [## First time developing plugins?](https://github.com/bhagyas/obsidian-postfix-plugin/blob/69ce01c7ef250e47667fa867750143711a03beca/README.md#L39-L118)


["name": "Postfix Plugin",](https://github.com/bhagyas/obsidian-postfix-plugin/blob/69ce01c7ef250e47667fa867750143711a03beca/manifest.json#L3)
Just to reiterate, adding `Plugin` to the plugin name is redundant and adds clutter to the plugin list and command pallete.

["description": "This plugin provides postfix completions for Obsidian. The built-in completions are provided for markdown.",](https://github.com/bhagyas/obsidian-postfix-plugin/blob/69ce01c7ef250e47667fa867750143711a03beca/manifest.json#L6)
We have recently published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This is a plugin ... for Obsidian" in your description.

["LinkedIn": "https://linkedin.com/in/bhagyas"](https://github.com/bhagyas/obsidian-postfix-plugin/blob/69ce01c7ef250e47667fa867750143711a03beca/manifest.json#L11)
This is meant for links to services where users can donate to you, like _Buy me a Coffee_, LinkedIn does not make much sense here.

[export default class MyPlugin extends Plugin {](https://github.com/bhagyas/obsidian-postfix-plugin/blob/69ce01c7ef250e47667fa867750143711a03beca/main.ts#L5)
Please rename this to something more fitting.

[console.log('My plugin has loaded!');](https://github.com/bhagyas/obsidian-postfix-plugin/blob/69ce01c7ef250e47667fa867750143711a03beca/main.ts#L7)
[onunload() {](https://github.com/bhagyas/obsidian-postfix-plugin/blob/69ce01c7ef250e47667fa867750143711a03beca/main.ts#L46-L50)
Remove these.

[const cm  = editor;](https://github.com/bhagyas/obsidian-postfix-plugin/blob/69ce01c7ef250e47667fa867750143711a03beca/main.ts#L24)
You can just do ` this.app.workspace.on('editor-change', (cm) => {` in the line above to rename the variable.

**Comment by bhagyas** [comment]
Hi @joethei ,

I do not think these apply, as the README is intended for the developers or anyone who is hoping to contribute to the plugin. I considered removing and replacing the entire README, but decided to keep as close to the Obsidian Plugin Development starter. 

The TypeScript related suggestions are good, but they are transpiled away as far as the bundling is concerned. Anyone, including you is welcome to contribute to the plugin.

I have also removed the plugin name - from the manifest and any other places  where it is mentioned. 

If you have any questions related to the functionality, I would be happy to address. This is supposed to be an initial version, and I hope it would be improved as time goes by.

//Bhagya

**Comment by joethei** [comment]
You can still include a link to the Obsidian docs on how to develop plugins, but the README is intended for users, and should include documentation on how to use the plugin.
The current README is confusing to users, as there is no clear indication what part is for developing the plugin, and what part is for using it.

**Comment by bhagyas** [comment]
Is there a better way to provide documentation for the users? I do not expect users to visit GitHub and go through the readme. 

I can possibly move the development related documentation to the Wiki, but I don't think it would be ideal.

**Comment by joethei** [comment]
The README is the default place for user-facing documentation.
If you browse through community plugins in app, or through our website(<https://obsidian.md/plugins>) the README is what you see.

You can still keep the dev documentation in the README, but you need to separate it from the user documentation and remove anything that does not make sense to keep, like the "Funding" URL section.
You can just include something like:
> To contribute to this plugin you can read the Obsidian developer documentation here: <https://docs.obsidian.md>

**Comment by bhagyas** [comment]
Rerun the validation

**Comment by bhagyas** [comment]
@joethei I hope the updates address your concerns. Let me know if there is anything else.

**Comment by bhagyas** [comment]
@joethei Any updates?

**Comment by bhagyas** [comment]
@joethei This is not merged yet. Any updates on this?

**Comment by bhagyas** [comment]
@marcusolsson @joethei @liamcain ???

**Comment by joethei** [comment]
You have not made any of the requested changes to the code or the manifest.

**Comment by bhagyas** [comment]
Hi @joethei,

I have made those changes. Can you point to any specifics you are concerned about?

**Comment by joethei** [comment]
These have not been done:
> ["description": "This plugin provides postfix completions for Obsidian. The built-in completions are provided for markdown.",](https://github.com/bhagyas/obsidian-postfix-plugin/blob/69ce01c7ef250e47667fa867750143711a03beca/manifest.json#L6)
We have recently published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This is a plugin ... for Obsidian" in your description.

> ["LinkedIn": "https://linkedin.com/in/bhagyas"](https://github.com/bhagyas/obsidian-postfix-plugin/blob/69ce01c7ef250e47667fa867750143711a03beca/manifest.json#L11)
This is meant for links to services where users can donate to you, like _Buy me a Coffee_, LinkedIn does not make much sense here.

> [export default class MyPlugin extends Plugin {](https://github.com/bhagyas/obsidian-postfix-plugin/blob/69ce01c7ef250e47667fa867750143711a03beca/main.ts#L5)
Please rename this to something more fitting.

> [console.log('My plugin has loaded!');](https://github.com/bhagyas/obsidian-postfix-plugin/blob/69ce01c7ef250e47667fa867750143711a03beca/main.ts#L7)
[onunload() {](https://github.com/bhagyas/obsidian-postfix-plugin/blob/69ce01c7ef250e47667fa867750143711a03beca/main.ts#L46-L50)
Remove these.

> [const cm  = editor;](https://github.com/bhagyas/obsidian-postfix-plugin/blob/69ce01c7ef250e47667fa867750143711a03beca/main.ts#L24)
You can just do ` this.app.workspace.on('editor-change', (cm) => {` in the line above to rename the variable.

**Comment by liamcain** [comment]
Hi @bhagyas, when you get a chance, could you remove the console.log messages? Otherwise it looks fine to me. Thanks!

**Comment by bhagyas** [comment]
Thanks, I have now removed the console.log statements from the code.

**Pull request merged**
