### PR TITLE
Add plugin: Pia viewer

### PR DESCRIPTION
**Pull request by dldisud**
# I am submitting a new Community Plugin

## Repo URL 

Link to my plugin: https://github.com/dldisud/obsidian-pia-viewer

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by dldisud** [comment]
This branch cannot be rebased due to conflicts

I don't know how to fix that error.

**Comment by joethei** [comment]
Ignore it, I'll handle it once the plugin is ready to be added to the list.

**Comment by dldisud** [comment]
I just found a bug and fixed it, should I post PR again?

**Comment by joethei** [comment]
No, just push the update to your repo.

**Comment by dldisud** [comment]
Maybe it's done

**Comment by dldisud** [comment]
I don't know if this is right

I already modified the file two hours ago and posted it on my repository, but I don't know if this is the right one..

**Comment by joethei** [comment]
Please don't create duplicate PR's
Closing this as a duplicate of #3863

**Pull request closed without merging**
