### PR TITLE
Add plugin: Unearthed (Kindle Sync)

### PR DESCRIPTION
**Pull request by cheerscal**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Unearthed-App/unearthed-obsidian

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by cheerscal** [comment]
New release (1.0.4) published with the required changes

**Comment by joethei** [comment]
Remove the `styles.css` file from your release, since it's empty it's just unnecessary bloat.

[if (!plugin.app.vault.getAbstractFileByPath(parentFolderPath)) {](https://github.com/Unearthed-App/unearthed-obsidian/blob/c3ed3f455485a2ade7d3d190395b0ba9555b72f1/main.ts#L129)
Check that this is `instanceof TFolder` instead, your code will also return true if there is a file.

[console.log(`No folder created: ${folderPath}`);](https://github.com/Unearthed-App/unearthed-obsidian/blob/c3ed3f455485a2ade7d3d190395b0ba9555b72f1/main.ts#L155)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[function formatDate(date: Date, format: string): string {](https://github.com/Unearthed-App/unearthed-obsidian/blob/c3ed3f455485a2ade7d3d190395b0ba9555b72f1/main.ts#L219-L231)
Obsidian includes the moment library that should be used instead.

[.setName("Unearthed API Key")](https://github.com/Unearthed-App/unearthed-obsidian/blob/c3ed3f455485a2ade7d3d190395b0ba9555b72f1/main.ts#L352), [.setName("Auto Sync")](https://github.com/Unearthed-App/unearthed-obsidian/blob/c3ed3f455485a2ade7d3d190395b0ba9555b72f1/main.ts#L365), [.setName("Add Daily Reflection to Daily note on startup")](https://github.com/Unearthed-App/unearthed-obsidian/blob/c3ed3f455485a2ade7d3d190395b0ba9555b72f1/main.ts#L377), [.setName("Daily Reflection (Date Format)")](https://github.com/Unearthed-App/unearthed-obsidian/blob/c3ed3f455485a2ade7d3d190395b0ba9555b72f1/main.ts#L391), [.setName("Daily Reflection (New file location)")](https://github.com/Unearthed-App/unearthed-obsidian/blob/c3ed3f455485a2ade7d3d190395b0ba9555b72f1/main.ts#L406), [.setName("Manual Sync")](https://github.com/Unearthed-App/unearthed-obsidian/blob/c3ed3f455485a2ade7d3d190395b0ba9555b72f1/main.ts#L423), [.setName("Manual Daily Reflection Sync")](https://github.com/Unearthed-App/unearthed-obsidian/blob/c3ed3f455485a2ade7d3d190395b0ba9555b72f1/main.ts#L433)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by cheerscal** [comment]
New release (1.0.5) published with the required changes

**Comment by joethei** [comment]
[.setName("Auto Sync")](https://github.com/Unearthed-App/unearthed-obsidian/blob/2a0f68706dd286b11433b0647c326709641a6cd8/main.ts#L364)
This is not using sentence case.

**Comment by cheerscal** [comment]
New release (1.0.6) published with the required changes

**Pull request merged**
