### PR TITLE
Adding Illusion Theme

### PR DESCRIPTION
**Pull request by ZaherAlMajed**
# [x] I am submitting a new Community Theme

## Repo URL

https://github.com/ZaherAlMajed/Illusion-Theme.md

## Theme checklist

- [x] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo)
  - [x] `obsidian.css`
  - [x] The screenshot file
- [x] I have indicated which modes (dark, light, or both) are compatible with my theme
- [x] I have added a license in the LICENSE file
- [ ] If my repo is not using the `master` branch (legacy), please indicate

### CODE REVIEW

**Comment by ericaxu** [comment]
Thanks for your PR! The theme looks really nice.

Two minor things:
1. Please add at the bottom of the file instead of the top;
2. Please specify the `main` branch. Thanks!

**Comment by ZaherAlMajed** [comment]
I have deleted the fork after I submit 
should submit new PR?

**Comment by ZaherAlMajed** [comment]
Also, I don't know what so you mean by specifying the main branch, I am new to gihub. the master is the main branch I think

**Comment by ericaxu** [comment]
> I have deleted the fork after I submit
> should submit new PR?

Opening a new PR is fine, or I can do it for you too.

> Also, I don't know what so you mean by specifying the main branch, I am new to gihub. the master is the main branch I think

Just need to add `"branch": "main"` like some of the existing themes. The directory is quite old and is before GitHub's change to the default branch (from `master` to `main`).

I forgot one question I had: do you want to make your theme available to both light and dark theme? If you only want it to be applicable to light themes, you can leave "dark" out for now and add it later.

**Comment by ZaherAlMajed** [comment]
> Opening a new PR is fine, or I can do it for you too.

I will open new PR just to learn more how to use this app 

> Just need to add "branch": "main" like some of the existing themes. The directory is quite old and is before GitHub's change to the default branch (from master to main).

I will include it in the new PR

>I forgot one question I had: do you want to make your theme available to both light and dark theme? If you only want it to be applicable to light themes, you can leave "dark" out for now and add it later.

I will include Light for now in the new PR, as you said. 

thanks

**Pull request closed without merging**
