### PR TITLE
Add plugin: Favorite Note

### PR DESCRIPTION
**Pull request by mahmudz**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/mahmudz/obsidian-favorite-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Please write a proper readme.

What sets your plugin appart from the core "Bookmarks" plugin?
<https://help.obsidian.md/Plugins/Bookmarks>

[](https://github.com/mahmudz/obsidian-favorite-plugin/blob/a695b384abd2b7a512c8736670fb95eaa62aa64a/styles.css#L9-L14)
Please don't overwrite core styling in a plugin, add another class so it only applies to your plugin.

[private getDataFile(): TFile {](https://github.com/mahmudz/obsidian-favorite-plugin/blob/a695b384abd2b7a512c8736670fb95eaa62aa64a/src/main.ts#L12-L43)
Please use loadData() and saveData from the Obsidian API for storing your data (https://github.com/obsidianmd/obsidian-api/blob/249eb773347588f4e9fec7c600e1904cd9240fcb/obsidian.d.ts#L2982). This allows the data to be compatible with syncing platforms like Obsidian Sync, an example can be found in the sample plugin.


[containerEl.createEl("h1", { text: "Favorites" });](https://github.com/mahmudz/obsidian-favorite-plugin/blob/a695b384abd2b7a512c8736670fb95eaa62aa64a/src/tabs/settings-tab.ts#L19-L20)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[a.innerHTML = ``;](https://github.com/mahmudz/obsidian-favorite-plugin/blob/a695b384abd2b7a512c8736670fb95eaa62aa64a/src/tabs/settings-tab.ts#L54-L55)
[Avoid using `innerHTML`](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%60innerHTML%60%2C+%60outerHTML%60+and+%60insertAdjacentHTML%60)

[export const appIcons: string[] = [](https://github.com/mahmudz/obsidian-favorite-plugin/blob/a695b384abd2b7a512c8736670fb95eaa62aa64a/src/modals/app-icons.ts#L1)
The API already exports a `getIconIDs()` function,

**Comment by mahmudz** [comment]
@joethei Is there any event to detected new note created. I can see app.vault has `create` event. But i'm looking for something like `created`.

**Comment by joethei** [comment]
`create` is the correct event for that.

**Comment by mahmudz** [comment]
Made the suggested changes.

**Comment by liamcain** [comment]
Just a heads up, this plugin looks functional equivalent to Prominent Files <https://github.com/javalent/prominent-files> which reuses the Bookmarks and just highlights the files in the explorer.

- [indexOf](https://github.com/mahmudz/obsidian-favorite-plugin/blob/78b9ecb57aeb615ffda3fca1078cc914745e1d6b/src/main.ts#L33) searching for favorites in a list will get expensive, Consider storing the filepaths in a Set instead
- [import "../styles.css";](https://github.com/mahmudz/obsidian-favorite-plugin/blob/78b9ecb57aeb615ffda3fca1078cc914745e1d6b/src/main.ts#L6) this is unnecessary

**Pull request merged**
