### PR TITLE
New Community Plugin Request: Fantasy Content Generator

### PR DESCRIPTION
**Pull request by Gregory-Jagermeister**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Gregory-Jagermeister/Fantasy-Content-Generator

## Release Checklist
- [ X ] I have tested the plugin on
  - [ X ]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ X ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ X ] My GitHub release contains all required files
  - [ X ] `main.js`
  - [ X ] `manifest.json`
  - [ X ] `styles.css` _(optional)_
- [ X ] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [ X ] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [ X ] My README.md describes the plugin's purpose and provides clear usage instructions.
- [ X ] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [ X ] I have added a license in the LICENSE file.
- [ X ] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[if (view) {](https://github.com/Gregory-Jagermeister/Fantasy-Content-Generator/blob/c1e4a15c6aeb8e9ecde8e166a50f51ec2e73b4c2/main.ts#L21)
Why this check?

[settingsdiv.innerHTML = "";](https://github.com/Gregory-Jagermeister/Fantasy-Content-Generator/blob/c1e4a15c6aeb8e9ecde8e166a50f51ec2e73b4c2/editor/GeneratorModal.ts#L295)
Use `settingsdiv.empty()` instead.



[// Perform additional things with the ribbon](https://github.com/Gregory-Jagermeister/Fantasy-Content-Generator/blob/c1e4a15c6aeb8e9ecde8e166a50f51ec2e73b4c2/main.ts#L51-L52)
[// When registering intervals, this function will automatically clear the interval when the plugin is disabled.](https://github.com/Gregory-Jagermeister/Fantasy-Content-Generator/blob/c1e4a15c6aeb8e9ecde8e166a50f51ec2e73b4c2/main.ts#L57-L58)
[console.log();](https://github.com/Gregory-Jagermeister/Fantasy-Content-Generator/blob/c1e4a15c6aeb8e9ecde8e166a50f51ec2e73b4c2/main.ts#L32)
Remove this

**Comment by Gregory-Jagermeister** [comment]
> [if (view) {](https://github.com/Gregory-Jagermeister/Fantasy-Content-Generator/blob/c1e4a15c6aeb8e9ecde8e166a50f51ec2e73b4c2/main.ts#L21) Why this check?
I Was under the impression that I needed to check that the Markdown view Existed before Registering an EditorSuggest. I just tested removing that and it Looks like I was wrong about that. Other recommended issues fixed happy to fix anything else just let me know

**Comment by liamcain** [comment]
- [registerEditorSuggest](https://github.com/Gregory-Jagermeister/Fantasy-Content-Generator/blob/a105b6f2881a306b35147a6bf27a25c7592bca38/main.ts#L20) this shouldn't need to be called within onLayoutReady
- [eslint-disable-next-line @typescript-eslint/no-unused-vars](https://github.com/Gregory-Jagermeister/Fantasy-Content-Generator/blob/a105b6f2881a306b35147a6bf27a25c7592bca38/main.ts#L24) why disable the warning? you could just not assign to a variable.
- [activeView.editor](https://github.com/Gregory-Jagermeister/Fantasy-Content-Generator/blob/a105b6f2881a306b35147a6bf27a25c7592bca38/editor/InlineGenerator.ts#L206) don't do this. This won't work in Canvas files for example. Instead, you should access the editor instance via `this.ctx.editor`. No need to check the current view.

**Comment by Gregory-Jagermeister** [comment]
Hi I would like to learn More about `this.ctx.editor` however can't seem to find any documentation on this I believe I'm just not looking in the right place? any insight you could share with me

**Pull request merged**
