### PR TITLE
Add plugin: Listen Up!

### PR DESCRIPTION
**Pull request by tejas-hosamani**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/tejas-hosamani/obsidian-plugin-text-to-speech

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "A FREE and Open source plugin to covert text to natural speech LOCALLY - Listen Up!",](https://github.com/tejas-hosamani/obsidian-plugin-text-to-speech/blob/fc2a0fe05ca9bc0df5802429d8cdebb4dd91cd33/manifest.json#L6)
Avoid including sentences like "A plugin that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

["fundingUrl": "https://internetunexplorer.com/",](https://github.com/tejas-hosamani/obsidian-plugin-text-to-speech/blob/fc2a0fe05ca9bc0df5802429d8cdebb4dd91cd33/manifest.json#L9)
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link remove this line.

[name: "Convert Text to Speech",](https://github.com/tejas-hosamani/obsidian-plugin-text-to-speech/blob/fc2a0fe05ca9bc0df5802429d8cdebb4dd91cd33/main.ts#L20), [.setName("Select Model config file")](https://github.com/tejas-hosamani/obsidian-plugin-text-to-speech/blob/fc2a0fe05ca9bc0df5802429d8cdebb4dd91cd33/Settings.ts#L70)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by tejas-hosamani** [comment]
Hey @joethei , I have made changes. Please check them.

1. Description update - https://github.com/obsidianmd/obsidian-releases/pull/3958/files#diff-3ce999c674f451146be9000351de965fbb63c3397f70991ad617d6e9e468e5b7R12734
2. Remove funding URL - https://github.com/tejas-hosamani/obsidian-plugin-text-to-speech/blob/master/manifest.json#L8
3. Sentence case update:
    1. https://github.com/tejas-hosamani/obsidian-plugin-text-to-speech/blob/7b2165651cb360a1315b7dfb3102aa2cbcd6153e/main.ts#L20
    2. https://github.com/tejas-hosamani/obsidian-plugin-text-to-speech/blob/7b2165651cb360a1315b7dfb3102aa2cbcd6153e/Settings.ts#L70

**Comment by joethei** [comment]
Please also update the description in your manifest.

**Comment by liamcain** [comment]
- [editor.setCursor(editor.lastLine())](https://github.com/tejas-hosamani/obsidian-plugin-text-to-speech/blob/7b2165651cb360a1315b7dfb3102aa2cbcd6153e/main.ts#L87) instead of assuming the user wants to be on the last line of the file, consider finding the current position then adding the length of the inserted text and setting the position to be currentOffset + addedText.length.

**Pull request merged**
