### PR TITLE
Add obsidian-metronome-plugin

### PR DESCRIPTION
**Pull request by curtgrimes**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/curtgrimes/obsidian-metronome-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by curtgrimes** [comment]
Published version [0.2.0](https://github.com/curtgrimes/obsidian-metronome-plugin/releases/tag/0.2.0):

- Add size: `xlarge`
- Add styles: `pendulum` and `line`
- Split CSS into Vue components
- Minify production builds

**Comment by curtgrimes** [comment]
Please hold on reviewing this at the moment. I am fixing compatibility issues with the latest version of Obsidian with live preview.

**Comment by curtgrimes** [comment]
Published version [0.3.0](https://github.com/curtgrimes/obsidian-metronome-plugin/releases/tag/0.3.0):

- Add compatibility with Obsidian 13 and live preview mode.
- Fix issue where metronome sound stops if the metronome is scrolled down the page. (https://github.com/curtgrimes/obsidian-metronome-plugin/issues/1)
- Fix issue where animation could become desynchronized from the sound when scrolling the metronome off the page and back on.
- Use Obsidian's native tooltips.
- Properly clean up components when being unloaded.

**Comment by curtgrimes** [comment]
[0.4.0](https://github.com/curtgrimes/obsidian-metronome-plugin/releases/tag/0.4.0)
- Fixed issue where metronome would not start on iOS
- Restored compatibility with Obsidian v0.12.19 which was broken in 0.3.0
- Made metronome more touchscreen-friendly
- Made metronome better follow the current user-selected theme
- Allow metronome sound to continue from a collapsed sidebar

**Comment by curtgrimes** [comment]
[Released 0.5.0](https://github.com/curtgrimes/obsidian-metronome-plugin/releases/tag/0.5.0) with some new features and better community theme compatibility.

**Comment by curtgrimes** [comment]
Released [0.6.0](https://github.com/curtgrimes/obsidian-metronome-plugin/releases/tag/0.6.0) with a new feature and [0.6.1](https://github.com/curtgrimes/obsidian-metronome-plugin/releases/tag/0.6.1) to fix a missing dependency

**Comment by curtgrimes** [comment]
Released [0.7.0](https://github.com/curtgrimes/obsidian-metronome-plugin/releases/tag/0.7.0)
- Add i18n support. [Contributions for new translations](https://github.com/curtgrimes/obsidian-metronome-plugin/tree/master/src/i18n) are welcome!
- Add support for math expressions in bpm value

**Comment by lishid** [comment]
Apologies for the late review, everything looks great!

**Pull request merged**
