### PR TITLE
Add Better PDF 2 Plugin

### PR DESCRIPTION
**Pull request by joleaf**
# I am submitting a new Community Plugin

*NOTE:* The original "[Better PDF](https://github.com/MSzturc/obsidian-better-pdf-plugin)" plugin does not work in the latest obsidian version and the author does not respond to the related [issue](https://github.com/MSzturc/obsidian-better-pdf-plugin/issues/46). Thus, this plugin is an updated fork of this plugin with a new maintainer. **Optional: Delete the original `better-pdf-plugin` from the `community-plugins.json` list?**

## Repo URL

Link to my plugin:
https://github.com/joleaf/obsidian-better-pdf-2-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joleaf** [comment]
Close for now, as there are major bugs

**Comment by joleaf** [comment]
> Close for now, as there are major bugs

Working now

**Comment by joethei** [comment]
As the original "Better PDF" plugin does not have any license, we can't accept this submission.
Please see our [Developer Policies](https://docs.obsidian.md/Developer+policies)

Sorry about that!

**Comment by joleaf** [comment]
> As the original "Better PDF" plugin does not have any license, we can't accept this submission. Please see our [Developer Policies](https://docs.obsidian.md/Developer+policies)
> 
> Sorry about that!

Hey @joethei , I understand. Is there another way that all the users used Better PDF dont need to relay on an old obsidian version to make better pdf functional? Because, with the latest obsidian version, the plugin can not be enabled anymore.

**Comment by joleaf** [comment]
Sry again @joethei , but is there a way we can publish the **Better PDF 2** plugin somehow? The obsidian Developer Policies says that a plugin is removed if a plugin "have become unmaintained or severely broken". [The Better PDF Plugin is broken.](https://github.com/MSzturc/obsidian-better-pdf-plugin/issues/46). Thus can we remove the original PDF plugin and add this here?

**Pull request closed without merging**
