### PR TITLE
Add plugin Check, Please!

### PR DESCRIPTION
**Pull request by DevAndrewGeorge**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/DevAndrewGeorge/obsidian-check-please

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[Copyright (c) [year] [fullname]](https://github.com/DevAndrewGeorge/obsidian-check-please/blob/a58bb42700cdfaac0ad3054ae161d57091ec958c/LICENSE#L3)
Please fill this.

["fundingUrl": "",](https://github.com/DevAndrewGeorge/obsidian-check-please/blob/a58bb42700cdfaac0ad3054ae161d57091ec958c/manifest.json#L9)
If you don't have one, omit this.

**Comment by DevAndrewGeorge** [comment]
I've made the requested changes, @joethei.

**Comment by liamcain** [comment]
- [this.app.workspace.getActiveFile](https://github.com/DevAndrewGeorge/obsidian-check-please/blob/96dc015e95fe5e5772b69db4b10a559ed236e9a0/main.ts#L349) I think you're better off using `context: MarkdownPostProcessorContext`'s sourcePath to find the correct file that's loaded.
- [TODO: this is a hack because editor changes aren't persisted to file](https://github.com/DevAndrewGeorge/obsidian-check-please/blob/96dc015e95fe5e5772b69db4b10a559ed236e9a0/main.ts#L308) what's the issue here? You shouldn't be doing a write on file-open

**Comment by liamcain** [comment]
Hi @DevAndrewGeorge, bumping this in case you didn't see my earlier comment!

**Comment by Tejeev** [comment]
@DevAndrewGeorge bump :)

**Pull request closed without merging**
