### PR TITLE
Add plugin: ExMemo Tools

### PR DESCRIPTION
**Pull request by xieyan0811**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
To make the manual review process and future plugin maintenance more efficient, we recommend that you move all source code files into a `src` directory.

[id: 'exmemo-tools-adjust-meta',](https://github.com/exmemo-ai/obsidian-exmemo-tools/blob/ee71938a26a337a2c8a71a4e213d4e154b5809bc/main.ts#L13), [id: 'exmemo-tools-insert-dir',](https://github.com/exmemo-ai/obsidian-exmemo-tools/blob/ee71938a26a337a2c8a71a4e213d4e154b5809bc/main.ts#L20), [id: 'exmemo-tools-insert-md',](https://github.com/exmemo-ai/obsidian-exmemo-tools/blob/ee71938a26a337a2c8a71a4e213d4e154b5809bc/main.ts#L27), [id: 'exmemo-tools-llm',](https://github.com/exmemo-ai/obsidian-exmemo-tools/blob/ee71938a26a337a2c8a71a4e213d4e154b5809bc/main.ts#L34)
Don't prefix the command id with the plugin id, Obsidian will make sure that there are no conflicts with other plugins.

[export async function getTags(app: App): Promise<Record<string, number>> {](https://github.com/exmemo-ai/obsidian-exmemo-tools/blob/ee71938a26a337a2c8a71a4e213d4e154b5809bc/utils.ts#L24-L43)
This method is not talking tags in frontmatter into account, to access all tags for a file use the `getAllTags` function.

["allFolders": "All Folders",](https://github.com/exmemo-a/workspaces/obsidian-exmemo-tools/settings.tsi/obsidian-exmemo-tools/blob/ee71938a26a337a2c8a71a4e213d4e154b5809bc/lang/locale/en.ts#L8), ["exmemoAdjustMeta": "Generate Meta Data",](https://github.com/exmemo-ai/obsidian-exmemo-tools/blob/ee71938a26a337a2c8a71a4e213d4e154b5809bc/lang/locale/en.ts#L20), ["exmemoLLMAssistant": "LLM Assistant",](https://github.com/exmemo-ai/obsidian-exmemo-tools/blob/ee71938a26a337a2c8a71a4e213d4e154b5809bc/lang/locale/en.ts#L23), ["apiKey": "API Key",](https://github.com/exmemo-ai/obsidian-exmemo-tools/blob/ee71938a26a337a2c8a71a4e213d4e154b5809bc/lang/locale/en.ts#L26), ["modelName": "Model Name",](https://github.com/exmemo-ai/obsidian-exmemo-tools/blob/ee71938a26a337a2c8a71a4e213d4e154b5809bc/lang/locale/en.ts#L28), ["updateMetaOptions": "Update Options",](https://github.com/exmemo-ai/obsidian-exmemo-tools/blob/ee71938a26a337a2c8a71a4e213d4e154b5809bc/lang/locale/en.ts#L31), ["maxContentLength": "Maximum Content Length",](https://github.com/exmemo-ai/obsidian-exmemo-tools/blob/ee71938a26a337a2c8a71a4e213d4e154b5809bc/lang/locale/en.ts#L37), ["truncateMethod": "Truncation Method",](https://github.com/exmemo-ai/obsidian-exmemo-tools/blob/ee71938a26a337a2c8a71a4e213d4e154b5809bc/lang/locale/en.ts#L39), ["extractTags": "Extract Tags",](https://github.com/exmemo-ai/obsidian-exmemo-tools/blob/ee71938a26a337a2c8a71a4e213d4e154b5809bc/lang/locale/en.ts#L46), ["tagList": "Tag List",](https://github.com/exmemo-ai/obsidian-exmemo-tools/blob/ee71938a26a337a2c8a71a4e213d4e154b5809bc/lang/locale/en.ts#L49), ["folderSelectionSetting": "Folder Selection Setting",](https://github.com/exmemo-ai/obsidian-exmemo-tools/blob/ee71938a26a337a2c8a71a4e213d4e154b5809bc/lang/locale/en.ts#L55), ["excludedFolders": "Excluded Folders",](https://github.com/exmemo-ai/obsidian-exmemo-tools/blob/ee71938a26a337a2c8a71a4e213d4e154b5809bc/lang/locale/en.ts#L58)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

["llmSettings": "LLM Settings",](https://github.com/exmemo-ai/obsidian-exmemo-tools/blob/ee71938a26a337a2c8a71a4e213d4e154b5809bc/lang/locale/en.ts#L25), ["metaUpdateSetting": "Update Meta Settings",](https://github.com/exmemo-ai/obsidian-exmemo-tools/blob/ee71938a26a337a2c8a71a4e213d4e154b5809bc/lang/locale/en.ts#L29)
[Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings), ["descriptionDesc": "Settings for automatically generating article descriptions",](https://github.com/exmemo-ai/obsidian-exmemo-tools/blob/ee71938a26a337a2c8a71a4e213d4e154b5809bc/lang/locale/en.ts#L52), ["folderSelectionSetting": "Folder Selection Setting",](https://github.com/exmemo-ai/obsidian-exmemo-tools/blob/ee71938a26a337a2c8a71a4e213d4e154b5809bc/lang/locale/en.ts#L55)
[Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

["general": "General",](https://github.com/exmemo-ai/obsidian-exmemo-tools/blob/ee71938a26a337a2c8a71a4e213d4e154b5809bc/lang/locale/en.ts#L30)
[Don't add a heading in the settings tab, such as "General".](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by xieyan0811** [comment]
I have fixed the above issues  and released 1.0.0. Please check when you have time.

**Comment by xieyan0811** [comment]
@joethei 

Hi Joethei, could you please take a look at my modifications?
Thanks! If still has any questions, I am so glad that you can tell me. 

https://github.com/exmemo-ai/obsidian-exmemo-tools/releases

**Comment by xieyan0811** [comment]
Hi @joethei, I understand you might be busy. Is there any additional information or changes I can provide to help with the review?

**Comment by xieyan0811** [comment]
Upon rechecking, I noticed that the link mentioned in the feedback ["allFolders": "All Folders"](https://github.com/exmemo-a/workspaces/obsidian-exmemo-tools/settings.tsi/obsidian-exmemo-tools/blob/ee71938a26a337a2c8a71a4e213d4e154b5809bc/lang/locale/en.ts#L8) does not open and displays “Not Found.” I’m unsure if this is affecting Bot3’s code review. Alternatively, due to recent feature updates, some strings mentioned in the feedback might no longer exist, which could impact Bot3's verification.

**Comment by xieyan0811** [comment]
Both https://github.com/obsidianmd/obsidian-releases/pull/4548 and https://github.com/obsidianmd/obsidian-releases/pull/4813 originate from the same organization. Initially, the commit for https://github.com/obsidianmd/obsidian-releases/pull/4548 was designed as a comprehensive tool that included modules, such as the LLM assistant and file management. However, during the review process, we were unable to fully identify and address the issues encountered (Please see the comments above).

While waiting for the review, We re-evaluated the tool's design and considered whether integrating multiple features into one plugin made it unnecessarily complex. I decided that splitting the tool into two separate plugins would be more logical from both a functional and user perspective. This change not only facilitates future feature expansions but also makes the tools more intuitive for users. As a result, https://github.com/obsidianmd/obsidian-releases/pull/4813 focuses exclusively on the LLM assistant functionality. Since the two plugins are closely related, the README for https://github.com/obsidianmd/obsidian-releases/pull/4813 is a simplified version of that for https://github.com/obsidianmd/obsidian-releases/pull/4548.

Recently, I noticed that the status of both https://github.com/obsidianmd/obsidian-releases/pull/4548 and https://github.com/obsidianmd/obsidian-releases/pull/4813 has changed. The issues you raised are indeed present in both plugins, so I have made the necessary adjustments to each. I have fixed the above issues and released 1.0.0.

Considering the overall functionality and review timeline, **We are inclined to retain https://github.com/obsidianmd/obsidian-releases/pull/4548**. Thank you again for your review! Please take a look when you have time.

**Pull request merged**
