### PR TITLE
Add plugin: The Queue

### PR DESCRIPTION
**Pull request by koljapluemer**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[this.addRibbonIcon("dice", "Instant Queue", (evt: MouseEvent) => {](https://github.com/koljapluemer/obsidian-the-queue/blob/e61475518349c1655b597d0f68ada7a14450fab9/src/main.ts#L32)
Use a different icon: https://docs.obsidian.md/Plugins/User+interface/Icons

[this.addRibbonIcon("dice", "Instant Queue", (evt: MouseEvent) => {](https://github.com/koljapluemer/obsidian-the-queue/blob/e61475518349c1655b597d0f68ada7a14450fab9/src/main.ts#L32), [appendScoreButton(buttonRow, "Not Now", "not-today");](https://github.com/koljapluemer/obsidian-the-queue/blob/e61475518349c1655b597d0f68ada7a14450fab9/src/utils/renderModalNote.ts#L190), [text: "Let's Go",](https://github.com/koljapluemer/obsidian-the-queue/blob/e61475518349c1655b597d0f68ada7a14450fab9/src/utils/renderModalNote.ts#L193), [appendScoreButton(buttonRow, "Seems Hard", "hard");](https://github.com/koljapluemer/obsidian-the-queue/blob/e61475518349c1655b597d0f68ada7a14450fab9/src/utils/renderModalNote.ts#L215-L217), [} else if (qPrompt.promptType === "dueHabits") {](https://github.com/koljapluemer/obsidian-the-queue/blob/e61475518349c1655b597d0f68ada7a14450fab9/src/utils/renderModalNote.ts#L246-L280), [.setName("Desired Recall Threshold")](https://github.com/koljapluemer/obsidian-the-queue/blob/e61475518349c1655b597d0f68ada7a14450fab9/src/elements/QueueSettingsTab.ts#L19-L22), [.setName("Local Data Logging")](https://github.com/koljapluemer/obsidian-the-queue/blob/e61475518349c1655b597d0f68ada7a14450fab9/src/elements/QueueSettingsTab.ts#L37), [button.setButtonText("Export Logs").onClick(() => {](https://github.com/koljapluemer/obsidian-the-queue/blob/e61475518349c1655b597d0f68ada7a14450fab9/src/elements/QueueSettingsTab.ts#L39), [button.setButtonText("Reset Logs").onClick(() => {](https://github.com/koljapluemer/obsidian-the-queue/blob/e61475518349c1655b597d0f68ada7a14450fab9/src/elements/QueueSettingsTab.ts#L54), [.setName("Active Books")](https://github.com/koljapluemer/obsidian-the-queue/blob/e61475518349c1655b597d0f68ada7a14450fab9/src/elements/QueueSettingsTab.ts#L61), [.setName("Disable Leech Prompts")](https://github.com/koljapluemer/obsidian-the-queue/blob/e61475518349c1655b597d0f68ada7a14450fab9/src/elements/QueueSettingsTab.ts#L76), [.setName("Disable Improvement Prompts")](https://github.com/koljapluemer/obsidian-the-queue/blob/e61475518349c1655b597d0f68ada7a14450fab9/src/elements/QueueSettingsTab.ts#L88), [contentEl.createEl("h2", { text: "Filter Queue" });](https://github.com/koljapluemer/obsidian-the-queue/blob/e61475518349c1655b597d0f68ada7a14450fab9/src/elements/QueueFilterModal.ts#L39), [.setName("Filter by Keyword")](https://github.com/koljapluemer/obsidian-the-queue/blob/e61475518349c1655b597d0f68ada7a14450fab9/src/elements/QueueFilterModal.ts#L47)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)


[this.app.vault.cachedRead(qPrompt.qNote.noteFile).then((content: any) => {](https://github.com/koljapluemer/obsidian-the-queue/blob/e61475518349c1655b597d0f68ada7a14450fab9/src/utils/renderModalNote.ts#L13), [app.vault.read(this.noteFile).then((content) => {](https://github.com/koljapluemer/obsidian-the-queue/blob/e61475518349c1655b597d0f68ada7a14450fab9/src/classes/QueueNote.ts#L268)
It's highly discouraged that you use the global app instance in your plugin. It's currently accessible from the global context for debugging purposes, and might be removed in the future. Instead, you should use the reference to App that you have from your plugin instance.

[MarkdownRenderer.renderMarkdown(](https://github.com/koljapluemer/obsidian-the-queue/blob/e61475518349c1655b597d0f68ada7a14450fab9/src/utils/renderModalNote.ts#L90-L95)
`contentEl` is not a component, this will throw errors during runtime.

**Comment by koljapluemer** [comment]
Thank you for your feedback! I implemented your suggestions and updated the release, specifically:

- changed icon
- corrected title case to sentence case in the mentioned UI elements (and also in some other places)
- replaced references to global app object with `this.app` (I hope I got this right)
- used `this` as a `Component` for the `MarkdownRenderer`

Using `this` in js correctly is not my strongest suit, please let me know if I missed anything or if there's anything else.

**Comment by koljapluemer** [comment]
Hi, quick note; the `Component` problem was not actually fixed — I updated the release again, it should be good now

**Comment by joethei** [comment]
The component should also be unloaded in the modals `onClose()`

**Comment by koljapluemer** [comment]
Alright, I updated the release, component is now getting unloaded on close :)

**Comment by joethei** [comment]
Sorry for all of the delay.

**Comment by koljapluemer** [comment]
Very cool, thank you so much for your work :)

**Pull request merged**
