### PR TITLE
Add plugin: Timeline View

### PR DESCRIPTION
**Pull request by b-camphart**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/b-camphart/timeline-view

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
A screenshot in the readme would be nice.

Please remove the `main.js` file from the repo and add it to your .gitignore - compiled release files shouldn't get mixed with source code in your commits and should go to the releases files instead.

Disable the obfuscation of the release assets, obfuscation is not allowed, see: <https://docs.obsidian.md/Developer+policies>

[this.addRibbonIcon("waves", "Open Timeline View", () => this.openTimelineView())](https://github.com/b-camphart/timeline-view/blob/4f5bfa163b7ea30d545e2f6f401b26f7ccfa89e5/src/obsidian/plugin/main.ts#L28)
Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[export default {](https://github.com/b-camphart/timeline-view/blob/4f5bfa163b7ea30d545e2f6f401b26f7ccfa89e5/src/obsidian/plugin/manifest.ts#L1-L10)
This is already available from the plugin instance via `this.manifest`

**Comment by b-camphart** [comment]
I've made the requested changes, @joethei , but I'm not sure what you mean regarding the manifest.ts file.  I'm generating the manifest.json from the manifest.ts file.  Should that be removed from the repository as well, similar to the `main.js` file?

**Comment by joethei** [comment]
ah, that's fine then.

**Comment by b-camphart** [comment]
I don't want to be pushy, and I recognize that you have a _ton_ of plugin requests to review, I'm just hoping this plugin hasn't been forgotten about @liamcain.  Am I still on the todo list?

**Comment by liamcain** [comment]
- [getStateForLeaf](https://github.com/b-camphart/timeline-view/blob/1198418e5d9cd9dc834e390b9857c9c6687370c2/src/obsidian/plugin/main.ts#L60) Instead of saving leaf state in your plugin data.json, take a look at this guide for how to store your leaf state inside workspace.json, which is a more robust/future proof way to ensure that the data is properly saved/loaded. https://liamca.in/Obsidian/API+FAQ/views/persisting+your+view+state
- [onunload](https://github.com/b-camphart/timeline-view/blob/1198418e5d9cd9dc834e390b9857c9c6687370c2/src/obsidian/plugin/main.ts#L74) we actually started discouraging detaching leaves on plugin unload. The plugin gets unloaded and reloaded when you update a plugin, which causes the workspace to get jumbled. Instead, just leave the leaves behind.

**Pull request merged**
