### PR TITLE
Add plugin: Sheet Plus

### PR DESCRIPTION
**Pull request by ljcoder2015**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/ljcoder2015/obsidian-sheet-plus

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by ljcoder2015** [comment]
/ skip
I need to use `outerHTML` to convert to an HTML string for the copy function

**Comment by ljcoder2015** [comment]
/skip I need to use outerHTML to convert to an HTML string for the copy function

**Comment by joethei** [comment]
What sets your plugin appart from the existing Univer plugin?

[id: 'excel-univer-autocreate',](https://github.com/ljcoder2015/obsidian-excel-plus/blob/2c4df5a65143430df442bb78e7e3537cc47c583f/src/main.ts#L139)
The prefix is unnecessary.

[containerEl.createEl('h1', { text: t('FILE_SETTING') })](https://github.com/ljcoder2015/obsidian-excel-plus/blob/2c4df5a65143430df442bb78e7e3537cc47c583f/src/settingTab.ts#L19), [containerEl.createEl('h1', { text: t('EMBED_LINK_SETTING') })](https://github.com/ljcoder2015/obsidian-excel-plus/blob/2c4df5a65143430df442bb78e7e3537cc47c583f/src/settingTab.ts#L60)
For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```

[CREATE_EXCEL: "Create Excel File",](https://github.com/ljcoder2015/obsidian-excel-plus/blob/2c4df5a65143430df442bb78e7e3537cc47c583f/src/lang/locale/en.ts#L5), [FILENAME_PREFIX: "Filename Prefix",](https://github.com/ljcoder2015/obsidian-excel-plus/blob/2c4df5a65143430df442bb78e7e3537cc47c583f/src/lang/locale/en.ts#L33-L38), [SHEET_SETTING: "Sheet Setting",](https://github.com/ljcoder2015/obsidian-excel-plus/blob/2c4df5a65143430df442bb78e7e3537cc47c583f/src/lang/locale/en.ts#L40-L41), [COLUMN_WIDTH: "Column Width",](https://github.com/ljcoder2015/obsidian-excel-plus/blob/2c4df5a65143430df442bb78e7e3537cc47c583f/src/lang/locale/en.ts#L43), [SHOW_SHEET_BUTTON: "Show Sheet Button",](https://github.com/ljcoder2015/obsidian-excel-plus/blob/2c4df5a65143430df442bb78e7e3537cc47c583f/src/lang/locale/en.ts#L49-L50)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[FILE_SETTING: "File Setting",](https://github.com/ljcoder2015/obsidian-excel-plus/blob/2c4df5a65143430df442bb78e7e3537cc47c583f/src/lang/locale/en.ts#L30), [EMBED_LINK_SETTING: "Embed Link Setting",](https://github.com/ljcoder2015/obsidian-excel-plus/blob/2c4df5a65143430df442bb78e7e3537cc47c583f/src/lang/locale/en.ts#L37), [SHEET_SETTING: "Sheet Setting",](https://github.com/ljcoder2015/obsidian-excel-plus/blob/2c4df5a65143430df442bb78e7e3537cc47c583f/src/lang/locale/en.ts#L40)
[Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

**Comment by ljcoder2015** [comment]
update!
The current plugin supports embedding into other notes.
Supports global search.

**Comment by joethei** [comment]
This change was not made:
[File setting](https://github.com/ljcoder2015/obsidian-excel-plus/blob/8c6ae28f03e168781b32cd9d2a5c0ead60800473/src/lang/locale/en.ts#L27), [Embed link setting](https://github.com/ljcoder2015/obsidian-excel-plus/blob/8c6ae28f03e168781b32cd9d2a5c0ead60800473/src/lang/locale/en.ts#L34), [Sheet setting](https://github.com/ljcoder2015/obsidian-excel-plus/blob/8c6ae28f03e168781b32cd9d2a5c0ead60800473/src/lang/locale/en.ts#L37)
[Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

**Comment by joethei** [comment]
[  "id": "excel-plus",
  "name": "Excel Plus",](https://github.com/ljcoder2015/obsidian-excel-plus/blob/1d769c2f3252eb4e557b4fb50983d1157a77a221/manifest.json#L2C1-L3C24)
 Please rename the plugin, "Excel" is a brand name that should not be used.

**Comment by ljcoder2015** [comment]
Have been updated

**Comment by joethei** [comment]
The name of the repository and the README has not been updated.

**Comment by ljcoder2015** [comment]
Have been updated

**Comment by ljcoder2015** [comment]
@joethei  What else needs to be updated?

**Comment by ljcoder2015** [comment]
Have been updated

**Pull request merged**
