### PR TITLE
Add Annotator Plugin

### PR DESCRIPTION
**Pull request by elias-sundqvist**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/elias-sundqvist/obsidian-annotator

## Release Checklist

- [x] I have tested this on Windows, macOS, and Linux _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by 6-AND-9** [comment]
> I think epub support and maybe even the darkreader stuff isn't necessary for everyone. 

Believe me, dark mode is absolutely critical. 

As for EPUB support, it is a great addition, as I often read EPUB books and mark them up all over the place with various software. If I can integrate everything in Obsidian that'd be awesome. But as Elias said, its size is negligible anyway.

**Comment by lishid** [comment]
We actually do ship PDF.js with Obsidian, it just isn't the most up-to-date version and isn't automatically loaded into the app unless requested - perhaps we can expose an API to load PDF.js on demand? I've seen another plugin use it so that might be helpful.

**Comment by elias-sundqvist** [comment]
Which parts of pdf.js do you ship? 
I bundle both the web.js javascript library as well as the web viewer. 
Would I be able to remove both parts or just the former?
image

**Comment by lishid** [comment]
Ah I see! Currently we only ship `pdf.js` and `pdf.worker.js` (in their minified form too) but we can look into adding the viewer. IIRC mozilla encourage developers to make UI tweaks to the viewer so as to avoid it looking like the one in Firefox? Not sure how much work it would be.

**Comment by lishid** [comment]
PS. Minifying the source codes actually makes a big difference - pdf.js comes un-minified by default.

**Comment by elias-sundqvist** [comment]
I've managed to reduce the plugin to around 8MB now. I'm now out of tricks. 
* The files are minimized before they are zipped. 
* The zip file is now stored as unicode in a multiline comment instead of a base64 string variable. This allows for higher information density. 
   * You said that source code, in particular, takes a lot of ram @lishid. Is this true for comments as well?
* The rollup output is also minimized. 
I could possibly use the built-in `pdf.js` and `pdf.js.worker` files that are bundled. Not sure how much that would help though, and it's kind of nice to have everything self-contained in the plugin.

**Comment by lishid** [comment]
I think that's fine! Some first-pass minimization is reasonable but don't waste too much time trying to squeeze the last few bits.

**Comment by lishid** [comment]
One thing to keep in mind though, we've gotten reports that another plugin which includes its own PDF.js causes PDFs to stop working in Obsidian mobile - once we ship the API for PDF.js it might be a good idea to hook it up if available.

**Pull request merged**
