### PR TITLE
Add plugin: Open in Marked

### PR DESCRIPTION
**Pull request by ttscoff**
Add Marked 2 to community plugins

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/ttscoff/Marked2-obsidian

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Review by ttscoff — COMMENTED** [review]
Updated repo to fix validation

**Comment by joethei** [comment]
[MIT License](https://github.com/ttscoff/Marked2-obsidian/blob/216cbd4b01401e75420824f53ff3ecd5ec75d317/LICENSE#L1-L20)
This license is missing the year and author information

["child_process": "^1.0.2",](https://github.com/ttscoff/Marked2-obsidian/blob/216cbd4b01401e75420824f53ff3ecd5ec75d317/package.json#L25-L26)
These two dependencies are part of Node, they can't be installed through NPM, remove this

["minAppVersion": "0.9.12",](https://github.com/ttscoff/Marked2-obsidian/blob/216cbd4b01401e75420824f53ff3ecd5ec75d317/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

[const { exec } = require('child_process')](https://github.com/ttscoff/Marked2-obsidian/blob/216cbd4b01401e75420824f53ff3ecd5ec75d317/main.ts#L2)
Stick to one import style.

[return false;](https://github.com/ttscoff/Marked2-obsidian/blob/216cbd4b01401e75420824f53ff3ecd5ec75d317/main.ts#L79), [return false;](https://github.com/ttscoff/Marked2-obsidian/blob/216cbd4b01401e75420824f53ff3ecd5ec75d317/main.ts#L98)
This means that your commands will never be available, better would be `return Platform.isMacOS;` so that the command is only available on a Mac.

[new Notice("No active pane. Try again with a note open.");](https://github.com/ttscoff/Marked2-obsidian/blob/216cbd4b01401e75420824f53ff3ecd5ec75d317/main.ts#L95)
And add a check that `activeFile !== undefined` to the `checkCallback` here instead of this notice.

[containerEl.createEl('h2', { text: 'Open in Marked' });](https://github.com/ttscoff/Marked2-obsidian/blob/216cbd4b01401e75420824f53ff3ecd5ec75d317/main.ts#L115)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by ttscoff** [comment]
Was accidentally attaching ts instead of js file to release, this has been fixed in release 1.1.1.

**Comment by ttscoff** [comment]
> Also check this before adding the Ribbon icon to make sure it's only visible when running the plugin on a Mac.

missed this one on the first deploy, 1.1.3 has it. Also avoids adding settings at all if not macOS because the only setting is the ribbon icon color.

**Comment by ttscoff** [comment]
Bump… do I need to fix the merge conflict?

**Comment by joethei** [comment]
No, I'll do that before merging

**Comment by ttscoff** [comment]
I think I've satisfied all change requests, any ETA on getting this into the Community plugins?

**Comment by ttscoff** [comment]
Bump. Any hope of getting this live?

**Pull request closed without merging**
