### PR TITLE
Add Send to Ghost

### PR DESCRIPTION
**Pull request by Southpaw1496**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Southpaw1496/obsidian-send-to-ghost/

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Please follow the pull request template.

**Comment by Southpaw1496** [comment]
Do I have to re-open the pull request for that?

**Comment by joethei** [comment]
No, but replace your first message here with the template and fill it.
You can get the template here: https://raw.githubusercontent.com/obsidianmd/obsidian-releases/master/.github/PULL_REQUEST_TEMPLATE/plugin.md

**Comment by Southpaw1496** [comment]
Done

**Comment by joethei** [comment]
[containerEl.createEl("h2", { text: "Send to Ghost" });](https://github.com/Southpaw1496/obsidian-send-to-ghost/blob/a767ae59fd2a07ca75a597b5a4e6cf6a65c83d53/src/settingTab/index.ts#L16)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[const noteFile = app.workspace.getActiveFile();](https://github.com/Southpaw1496/obsidian-send-to-ghost/blob/a767ae59fd2a07ca75a597b5a4e6cf6a65c83d53/src/methods/publishPost.ts#L38)
It's highly discouraged that you use the global app instance in your plugin. It's currently accessible from the global context for debugging purposes, and might be removed in the future. Instead, you should use the reference to App that you have from your plugin instance.

[const result = await request({](https://github.com/Southpaw1496/obsidian-send-to-ghost/blob/a767ae59fd2a07ca75a597b5a4e6cf6a65c83d53/src/methods/publishPost.ts#L51-L63)
You can use this instead:
```ts
const result = await requestUrl(<same as current code>);
const json = result.json();
```

**Comment by Southpaw1496** [comment]
I've addressed the first and third issue, but the third one is confusing: I'm very new to JS and plugin development and just trying to keep this one alive. Do you know of any relevant documentation I could read or code examples I could use to help me understand it?

**Comment by joethei** [comment]
Generally you would pass in the plugin instance as an additional parameter, and then call `plugin.app.....` in your code.

In the specific case you can take the app from the view though. i.e `view.app.workspace.getActiveFile()`;

**Comment by Southpaw1496** [comment]
I've addressed all of your comments.

**Comment by liamcain** [comment]
- [MarkdownView](https://github.com/Southpaw1496/obsidian-send-to-ghost/blob/05022a1b44eebb87234796a83688dc1b2341776a/src/main.ts#L31) the typing here is wrong. This argument is not always a markdownview. If the active view is a CanvasView, it could be the MarkdownFileInfo for the actively focused card in canvas.
- [Ghostt](https://github.com/Southpaw1496/obsidian-send-to-ghost/blob/05022a1b44eebb87234796a83688dc1b2341776a/src/main.ts#L34) typo
- [requestUrl](https://github.com/Southpaw1496/obsidian-send-to-ghost/blob/05022a1b44eebb87234796a83688dc1b2341776a/src/methods/publishPost.ts#L51) you should wrap this in a try/catch to properly handle errors
- [adminToken](https://github.com/Southpaw1496/obsidian-send-to-ghost/blob/05022a1b44eebb87234796a83688dc1b2341776a/src/methods/publishPost.ts#L26) you should make sure that the token isn't empty

**Comment by Southpaw1496** [comment]
In regards to the third issue, is there any documentation on handling errors from `requestUrl`? The official documentation doesn't have much information about what errors it can throw.

I'd want to mainly catch 404 and 401 errors, as those would be the errors if the user mistyped the API URL or API key, respectively.

**Comment by liamcain** [comment]
requestUrl is basically the same as fetch, except that the requests are funneled through the electron main process, to bypass CORS errors. The error types/response will depend on the API you're hitting, so I'd recommend just testing it locally and seeing what object shape you get back.

**Comment by Southpaw1496** [comment]
I have addressed the second, third, and fourth comments. I haven't yet pushed a new tag, I will do that when all of your comments have been addressed.

In regards to the first comment, would [TextFileView](https://docs.obsidian.md/Reference/TypeScript+API/TextFileView/TextFileView) be the appropriate type to use, or is there something else?

**Comment by Southpaw1496** [comment]
I will wait until the plugin's issues are resolved to add the new tag.

**Comment by liamcain** [comment]
> In regards to the first comment, would [TextFileView](https://docs.obsidian.md/Reference/TypeScript+API/TextFileView/TextFileView) be the appropriate type to use, or is there something else?

Sorry, I missed this comment.

the type is `MarkdownView | MarkdownFileInfo` meaning that you're passed either a markdown view or a markdownfileinfo object. So you can do something like:

```
		this.addCommand({
			id: "publish",
			name: "Send to Ghost",
			editorCallback: (_, view: MarkdownView | MarkdownFileInfo) => {
				if (!(view instanceof MarkdownView)) {
					new Notice(
						"You must open the note that you want to send to Ghostt"
					);
					return;
				}

				publishPost(view, this.settings);
			},
```

**Comment by Southpaw1496** [comment]
I have addressed all your comments

**Pull request merged**
