### PR TITLE
Add plugin ZotLit

### PR DESCRIPTION
**Pull request by aidenlx**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/PKM-er/obsidian-zotlit/tree/master/app/obsidian/

Main page: https://zotlit.aidenlx.top

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["versions": {](https://github.com/PKM-er/obsidian-zotlit/blob/4fc91ef92ac273313a433624dab1e496d3016380/manifest.json#L6-L8)
This is not something Obsidian uses.

[i.setTitle("Copy Template").onClick(() => {](https://github.com/PKM-er/obsidian-zotlit/blob/4fc91ef92ac273313a433624dab1e496d3016380/app/obsidian/src/components/item-details/labelRenderer.tsx#L17)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by aidenlx** [comment]
> ["versions": {](https://github.com/PKM-er/obsidian-zotlit/blob/4fc91ef92ac273313a433624dab1e496d3016380/manifest.json#L6-L8)
This is not something Obsidian uses.

This is used internally to check for minimal binary version required for SQLite database access, similar to [`process.versions`](https://nodejs.org/api/process.html#processversions) in nodejs and electron 

> [i.setTitle("Copy Template").onClick(() => {](https://github.com/PKM-er/obsidian-zotlit/blob/4fc91ef92ac273313a433624dab1e496d3016380/app/obsidian/src/components/item-details/labelRenderer.tsx#L17)

fixed in https://github.com/PKM-er/obsidian-zotlit/commit/a9b1552e861a3e30b065a06a83477d647e675244

**Comment by liamcain** [comment]
- [const unload = around(modal,](https://github.com/PKM-er/obsidian-zotlit/blob/49449da05094001b015f859030cac1e6da507b3c/app/obsidian/src/components/basic/modal.ts#L30) what's this for? Is there any Obsidian bug this is working around?
- [const unload = around(modal,](https://github.com/PKM-er/obsidian-zotlit/blob/49449da05094001b015f859030cac1e6da507b3c/app/obsidian/src/components/basic/modal.ts#L30) typo
- [getActiveWin](https://github.com/PKM-er/obsidian-zotlit/blob/49449da05094001b015f859030cac1e6da507b3c/app/obsidian/src/utils/active-win.ts#L4) feel free to use `activeWindow` instead <https://github.com/obsidianmd/obsidian-api/blob/249eb773347588f4e9fec7c600e1904cd9240fcb/obsidian.d.ts#L259>

**Comment by aidenlx** [comment]
> - [const unload = around(modal,](https://github.com/PKM-er/obsidian-zotlit/blob/49449da05094001b015f859030cac1e6da507b3c/app/obsidian/src/components/basic/modal.ts#L30) what's this for? Is there any Obsidian bug this is working around?

It should be an patch for promisified modal to work in earlier version of obsidian, I'll see if this could be updated or replaced :) 

> - [getActiveWin](https://github.com/PKM-er/obsidian-zotlit/blob/49449da05094001b015f859030cac1e6da507b3c/app/obsidian/src/utils/active-win.ts#L4) feel free to use `activeWindow` instead <https://github.com/obsidianmd/obsidian-api/blob/249eb773347588f4e9fec7c600e1904cd9240fcb/obsidian.d.ts#L259>

That is great! Thanks for the reminder! 

Thanks for the swift review on the plug-in! Much appreciated 😄

**Pull request merged**
