### PR TITLE
Add plugin: Cloud Storage

### PR DESCRIPTION
**Pull request by yingjialong**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/yingjialong/obsidian-CloudStorage

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by yingjialong** [comment]
Hello, @joethei . I was wondering if you could provide an update on its status or could you let me know if there's anything I can do to help move the process along.

**Comment by yingjialong** [comment]
Hi，do you know when the code will be reviewed?

**Comment by joethei** [comment]
[Obsidian Cloud Storage](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/README.md#L1), [Obsidian Cloud Storage](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/README.md#L4), [Obsidian Cloud Storage](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/README.md#L22), ["Obsidian Cloud Storage"](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/README.md#L30), [Obsidian Cloud Storage](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/README.md#L31), [Obsidian Cloud Storage](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/README.md#L37), [Obsidian Cloud Storage](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/README.md#L48), [# Obsidian Cloud Storage](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/README_ZH.md#L1), [Obsidian Cloud Storage](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/README_ZH.md#L4) and a bunch more:
Naming something "Obsidian xyz" is reserved for first party products we create, please remove "Obsidian" from here.

["authorUrl": "https://pay.obcs.top",](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/manifest.json#L8)
This should link to your own website, or your GH profile.

[/*](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/styles.css#L1-L8)
Remove this comment

[.modal-button-container {](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/styles.css#L58-L61)
Please don't overwrite core styling in a plugin, add another class/data attribute so it only applies to your plugin.

[private async readBlobAsArrayBuffer(blob: Blob): Promise<ArrayBuffer> {](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L370-L383)
There is the `getBlobArrayBuffer` in the Obsidian API for this already.

[skiped](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L646)
Typo, should be `skipped`

[accountSection.createEl('h3', { text: 'User Account' });](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L936), [headerContainer.createEl('h3', { text: 'Subscription Features', cls: 'subscription-title' });](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1089), [contactSection.createEl('h3', { text: 'Contact Us' });](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1531)
For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```

[accountSection.createEl('h3', { text: 'User Account' });](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L936), [.setName('S3 Endpoint')](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L955), [.setName('S3 Region')](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L966), [.setName('S3 Access Key')](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L977), [.setName('S3 Secret Key')](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L988), [.setName('S3 Bucket')](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L999), [.setName('Monitored Folders')](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1027), [const addFolderButton = generalSection.createEl('button', { text: 'Add Folder' });](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1034), [.setName('Local File Handling After Upload')](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1041), [.addOption('recycle', 'Move to Recycle Bin')](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1044-L1045), [.setName('Custom Move Folder')](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1055), [.setName('Secure Link')](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1072), [.setName('File Filter Mode')](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1114), [.setName('File Extensions')](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1126), [.setName('Maximum File Size (MB)')](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1137), [.setName('Rename Files in Cloud')](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1149), [.setName('Storage Type')](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1217), [.setName('Membership Expiration Date')](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1240), [.setName('Storage Management')](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1248), [.setName('Bulk File Retrieval')](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1268), [.setName('Change Password')](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1279), [.setName('Email Verification Status');](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1298-L1299), [.setButtonText('Resend Verification Email')](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1309), [.setName('Storage Usage')](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1325), [.setName('Forgot Password')](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1406), [contentEl.createEl('h2', { text: 'Region Selection' });](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1604), [contentEl.createEl('h2', { text: 'Change Password' });](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1689), [.setName('Current Password')](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1692), [.setName('New Password')](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1698), [.setButtonText('Change Password')](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1705)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[generalSection.createEl('h3', { text: 'General Settings' });](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1024)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[private displayUpcomingFeaturesSection(containerEl: HTMLElement) {](https://github.com/yingjialong/obsidian-CloudStorage/blob/bf232dbe8d5dfaa6cf22ecf4e38c6d40c82f3109/main.ts#L1159-L1176)
This should not be part of the settings tab

**Comment by yingjialong** [comment]
The code has been fixed according to the requirements. The version number is 1.1.11. 
Please review it again.

**Pull request merged**
