### PR TITLE
Sheets submission

### PR DESCRIPTION
**Pull request by Canna71**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/Canna71/obsidian-sheets

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[Copyright (c) [2022] [Gabriele Cannata]](https://github.com/Canna71/obsidian-sheets/blob/cbe54b98c7287813196ba9e37c8023508e283151/LICENSE#L3)
This is outdated.

[Copy license text to clipboard](https://github.com/Canna71/obsidian-sheets/blob/cbe54b98c7287813196ba9e37c8023508e283151/LICENSE#L22-L39)
This is not part of the license text.

[if (this.settings.addRibbonIcon) {](https://github.com/Canna71/obsidian-sheets/blob/cbe54b98c7287813196ba9e37c8023508e283151/src/main.ts#L37)
As of v1.1.0 of Obsidian, the ribbon can be customized within Obsidian. So users can choose what items to include and in what order all in one place. Because of this, we're recommending that new plugins avoid introducing their own toggles for ribbon items.

[this.app.workspace.on(](https://github.com/Canna71/obsidian-sheets/blob/cbe54b98c7287813196ba9e37c8023508e283151/src/main.ts#L65-L82)
Don't forget to register these events: https://docs.obsidian.md/Plugins/Events
And what are they for? they look unused for me.

[containerEl.createEl("h2", { text: "Sheetjs Settings" });](https://github.com/Canna71/obsidian-sheets/blob/cbe54b98c7287813196ba9e37c8023508e283151/src/SettingTab.ts#L17)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

["Enable Saving To File",](https://github.com/Canna71/obsidian-sheets/blob/cbe54b98c7287813196ba9e37c8023508e283151/src/SettingTab.ts#L21)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[import moment from "moment";](https://github.com/Canna71/obsidian-sheets/blob/cbe54b98c7287813196ba9e37c8023508e283151/src/Views/SheetView.ts#L26)
Would be better to import from Obsidian: `import { moment } from "obsidian";`

[el.innerHTML = saveIcon;](https://github.com/Canna71/obsidian-sheets/blob/cbe54b98c7287813196ba9e37c8023508e283151/src/Views/SheetView.ts#L150)
[Avoid using `innerHTML`](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%60innerHTML%60%2C+%60outerHTML%60+and+%60insertAdjacentHTML%60), refer to https://docs.obsidian.md/Plugins/User+interface/Icons how to add icons.

**Comment by Canna71** [comment]
Thank you @joethei I will address them ASAP. 
A quick question about the last one (the innerHTML for the icon): that code injects an element into an external widget (it's actually the spreadsheet itself which you can find here: https://github.com/Canna71/x-spreadsheet as a fork) so it's not added to Obsidian itself. I wanted do that in a way that didn't involve changing the x-spreadsheet widget in a backward-incompatible way.
Can this be OK for you?

**Comment by Canna71** [comment]
I fixed the other stuff in the meantime, thank you!

**Comment by liamcain** [comment]
Looks good! Sadly, someone else with the same plugin ID just had their plugin added last week. You'll need to choose a different plugin ID.

**Pull request merged**
