### PR TITLE
Add Various Complements Plugin

### PR DESCRIPTION
**Pull request by tadashi-aikawa**
URL: https://github.com/tadashi-aikawa/obsidian-various-complements-plugin

Best regards.

### CODE REVIEW

**Comment by pglezen** [comment]
The description in `README.md` says

> This plugin for Obsidian enables you to compliments such as an auto-complete.

But it's not clear what this means.  Perhaps with some clarification from the author, we can reword it.

**Comment by liamcain** [comment]
Hi @tadashi-aikawa, I took a quick look at the code and found a small issue and made a couple suggestions [here](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/1). Otherwise, it looks good to me!

**Comment by tadashi-aikawa** [comment]
@pglezen @liamcain 
Thank you for the feedback! I will check and fix them👍 

`Todo`
- [ ] The description makes clarification
- [ ] https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/1

**Comment by tadashi-aikawa** [comment]
@pglezen @liamcain
I have fixed it. Best regards.

**Comment by pglezen** [comment]
Now I get it.  Thanks for the clarification.  There is one minor nit:

```diff
- enables you to complements input
+ enables you to complement input
```

Then I think you're good!

**Comment by tadashi-aikawa** [comment]
@pglezen 
Thanks a lot! 😄  Fixed it. 👍

**Comment by lishid** [comment]
I'm not too familiar with the showHint but pickTokens seems like it could get pretty expensive as it's working getting tokens out of the whole file. At least it's only triggered when you press the hotkey so it should still be ok performance wise?

**Comment by tadashi-aikawa** [comment]
@lishid 

Thank you for your feedback!

> pickTokens seems like it could get pretty expensive as it's working getting tokens out of the whole file. 

Just as you said, pickTokens is slow when the markdown file is too huge. Whereas, in most cases, I think it doesn't seem to be a critical problem for now because it is a plugin.

I measured with two markdown files and create mp4. Could you consider whether it is accepted or not at the first release?

😊 `Not critical case` (4500words, 35000characters)


https://user-images.githubusercontent.com/9500018/107186762-34159d80-6a28-11eb-9f02-f7c2b3c57851.mp4

    reference: https://tools.ietf.org/html/rfc3339

😥 `Critical case` (58000words, 422000characters)

https://user-images.githubusercontent.com/9500018/107186797-4394e680-6a28-11eb-91eb-83442ed60122.mp4

    reference: https://tools.ietf.org/html/rfc2616

And I am very glad if anyone tells me better implementations!😄

**Comment by lishid** [comment]
I think that'll do for now, but for improvements I'd recommend looking into a WebWorker for this kind of expensive sequential tasks. We do that for our WordCount core plugin, which sends the file contents over, and have the WebWorker run a regex on it and return a result.

I don't think it's too much of a problem right now since this only happens when you trigger the hotkey/command.

Let me know if you're ready to have the PR merged.

**Comment by lishid** [comment]
You might need to fix the PR because right now it's rewriting the whole file.

**Comment by tadashi-aikawa** [comment]
@lishid 
>  I'd recommend looking into a WebWorker for this kind of expensive sequential tasks

Thank you! I'll try to use Web Worker and improve the implementation in the future.

> You might need to fix the PR because right now it's rewriting the whole file.

Oh.. 😢  I'll fix the PR.

**Comment by ericaxu** [comment]
In "File changed" it still looks like it's rewriting the entire file... Is there a whitespace issue?

**Comment by tadashi-aikawa** [comment]
@lishid @ericaxu 
I created and edited PR on browser (GitHub) directly. But I don't know why there are entire diffs.

Can I create another new PR that has a link to this PR?

**Comment by lishid** [comment]
Sure yeah feel free to do a new PR.

**Comment by tadashi-aikawa** [comment]
@lishid 
I have created a new PR https://github.com/obsidianmd/obsidian-releases/pull/158.  Please confirm it.🙇

**Comment by liamcain** [comment]
(This PR can be closed now)

**Pull request closed without merging**
