### PR TITLE
Add plugin: BetaX NAS Sync

### PR DESCRIPTION
**Pull request by skye-z**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/skye-z/ons

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by skye-z** [comment]
Problem solved.

Additionally, since I need to exclude configuration file directories on non-Obsidian ends, I cannot obtain the directory location from user settings. Therefore, I have directly excluded directories that start with a `.`

**Comment by joethei** [comment]
["fundingUrl": "https://github.com/skye-z/ons",](https://github.com/skye-z/ons/blob/5c7a360cca0ac4b714bee88ff0cbb2054d8d6edf/manifest.json#L9)
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link remove this line.

[id: 'onsa',](https://github.com/skye-z/ons/blob/5c7a360cca0ac4b714bee88ff0cbb2054d8d6edf/obsidian-plugin/main.ts#L21), [id: 'onsb',](https://github.com/skye-z/ons/blob/5c7a360cca0ac4b714bee88ff0cbb2054d8d6edf/obsidian-plugin/main.ts#L26)
Please use more descriptive ID's and don't include the plugin ID.

[this.initListener();](https://github.com/skye-z/ons/blob/5c7a360cca0ac4b714bee88ff0cbb2054d8d6edf/obsidian-plugin/main.ts#L35)
This should be called inside of `onLayoutReady`, as the `create` event is fired for every file when Obsidian is starting, even if that file has existed before.

[console.log('file', type, name, path, stat, res)](https://github.com/skye-z/ons/blob/5c7a360cca0ac4b714bee88ff0cbb2054d8d6edf/obsidian-plugin/main.ts#L88), [console.log('folder', type, name, path, stat)](https://github.com/skye-z/ons/blob/5c7a360cca0ac4b714bee88ff0cbb2054d8d6edf/obsidian-plugin/main.ts#L91), [console.log('文件同步准备中');](https://github.com/skye-z/ons/blob/5c7a360cca0ac4b714bee88ff0cbb2054d8d6edf/obsidian-plugin/main.ts#L114)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.


[{ urls: 'stun:stun.l.google.com:19302' },](https://github.com/skye-z/ons/blob/5c7a360cca0ac4b714bee88ff0cbb2054d8d6edf/obsidian-plugin/src/peer-manager.ts#L51-L52), [{ urls: 'stun:stun.l.google.com:19302' },](https://github.com/skye-z/ons/blob/5c7a360cca0ac4b714bee88ff0cbb2054d8d6edf/obsidian-plugin/src/peer-manager.ts#L133-L134)
These should also be configurable.

**Comment by skye-z** [comment]
@joethei Thanks review, problems fixed: 
1. [remove funding url 1](https://github.com/skye-z/ons/commit/09709c1b178d72b2805f025f394dc0f84daf2e8c)
2. [clear log output](https://github.com/skye-z/ons/commit/3d68773aa1b80f2e915dba31d10885f86c80c165)
3. [update command id](https://github.com/skye-z/ons/commit/500503da7c5c277941403a414e36992840c9dbba)
4. [add stun setting](https://github.com/skye-z/ons/commit/3e48e4f8ae53e3a44a455efe73499fbb0334cd2f)

Besides that, I would like to ask how to get the current language of Obsidian? 
I'd like the plugin to be able to implement i18n, but I can't find an interface for it in the docs or the community.

**Comment by skye-z** [comment]
Can I open this pull?

**Comment by skye-z** [comment]
I am unable to reopen this pull and have created a new pull

**Pull request closed without merging**
