### PR TITLE
Add plugin: JSON table

### PR DESCRIPTION
**Pull request by dario-baumberger**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/dario-baumberger/obsidian-json-table

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by dario-baumberger** [comment]
I have tested the plugin on iOS. It is a bit cumbersome because you lose the selection in the editor when you open the command palette. But you can add the commands of the plugin to the Mobile Task Bar, that's how it works. I will improve the handling in future versions. I'll carry out the same test on Android soon.

**Comment by dario-baumberger** [comment]
Test now on Android and iOS, works well on both. Tested with a local version with icons in commands. 

Should I merge these changes into 1.0.0, or should I create 1.0.1?

**Comment by joethei** [comment]
Always release new versions, don't overwrite already existing releases.

[const response = await fetch(selection);](https://github.com/dario-baumberger/obsidian-json-table/blob/cbf2895c59f64d5cf1726180611a2a3441b13cc8/src/main.ts#L40)
Use the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.


[containerEl.createEl("h4", {](https://github.com/dario-baumberger/obsidian-json-table/blob/cbf2895c59f64d5cf1726180611a2a3441b13cc8/src/settings.ts#L17-L35)
Remove all the selected code, the commands should be explained in the readme, not in the settings.

[containerEl.createEl("h4", {](https://github.com/dario-baumberger/obsidian-json-table/blob/cbf2895c59f64d5cf1726180611a2a3441b13cc8/src/settings.ts#L37-L39)
Also get rid of this header, the first section should not have one.
(this would be the first header after the removal of the code above)

**Comment by dario-baumberger** [comment]
Thank you for the feedback and the quick review. 

I made the following changes according to your change request: https://github.com/dario-baumberger/obsidian-json-table/pull/1/files?diff=split&w=0

The changes are available in version 1.0.1. 

I asked about the version because I wasn't sure how you would like it. Since this is the first plugin release from the perspective of community plugins, if the pull request is merged.

**Pull request merged**
