### PR TITLE
Add plugin: Painter

### PR DESCRIPTION
**Pull request by KraXen72**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/KraXen72/obsidian-painter

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by KraXen72** [comment]
re-run?

**Comment by KraXen72** [comment]
> You should avoid assigning styles via JavaScript or in HTML and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets. 
  
(1) Ok i'll fix it
(2) Is required, due to it being a color preview - the background color has to be assigned dynamically to preview the current color.

> Using innerHTML, outerHTML or similar API's is a security risk. Instead, use the DOM API or the Obsidian helper functions: https://docs.obsidian.md/Plugins/User+interface/HTML+elements
  
(1) The `addIcon` function takes the svgContent as string, see the [docs](https://docs.obsidian.md/Reference/TypeScript+API/addIcon#addIcon()+function). As far as I'm aware, I cannot pass in the imperatively created svg without reading it's `outerHTML`
(2) we are only *reading* the `innerHTML` of a DOMParser document, as there is no other way to extract it's contents, to preserve html elements somebody added to the markdown. On top of that, all of this is happening in a sandboxed DOMParser.

**Comment by KraXen72** [comment]
well i haven't removed that one textarea.style.resize assignment yet, idk why the bot thinks so. let me know if it's that big of a deal though and i'll replace it with a new class and some css. 
as for the other changes i explained above why i do things like i do them.

**Comment by joethei** [comment]
["minAppVersion": "0.15.0",](https://github.com/KraXen72/obsidian-painter/blob/0c434ff46941c03ce860bbe9080813b0d38f66b4/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

[export const actionMenu = "Open Painter Menu"](https://github.com/KraXen72/obsidian-painter/blob/0c434ff46941c03ce860bbe9080813b0d38f66b4/src/constants.ts#L3), [.setName('Menu Mode')](https://github.com/KraXen72/obsidian-painter/blob/0c434ff46941c03ce860bbe9080813b0d38f66b4/src/settings/settings-tabs.ts#L33), [.setName('Additional CSS Selectors to clear')](https://github.com/KraXen72/obsidian-painter/blob/0c434ff46941c03ce860bbe9080813b0d38f66b4/src/settings/settings-tabs.ts#L67)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[export function debounce(fn: Function, ms = 300) {](https://github.com/KraXen72/obsidian-painter/blob/0c434ff46941c03ce860bbe9080813b0d38f66b4/src/utils/debounce.ts#L1-L7)
There is already a helper function with the same name.

**Comment by KraXen72** [comment]
okay, i implemented the requested changes and made a new release

**Comment by KraXen72** [comment]
thanks!!

**Pull request merged**
