### PR TITLE
Add plugin: Peekaboo

### PR DESCRIPTION
**Pull request by Lio5n**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["authorUrl": "",](https://github.com/Lio5n/peekaboo/blob/33b4dc26aa50514f235245c7f55c4cf72e04c7b7/manifest.json#L8)
This needs to be filled, if you don't have a website use your GitHub profile url.

[if (!this.settings.hideRibbonIcon) {](https://github.com/Lio5n/peekaboo/blob/33b4dc26aa50514f235245c7f55c4cf72e04c7b7/src/main.ts#L27-L31), [new Setting(containerEl)](https://github.com/Lio5n/peekaboo/blob/33b4dc26aa50514f235245c7f55c4cf72e04c7b7/src/settings.ts#L112-L122)
As of v1.1.0 of Obsidian, the ribbon can be customized within Obsidian. So users can choose what items to include and in what order all in one place. Because of this, we're recommending that new plugins avoid introducing their own toggles for ribbon items.


[name: 'Toggle Configured Files Visibility',](https://github.com/Lio5n/peekaboo/blob/33b4dc26aa50514f235245c7f55c4cf72e04c7b7/src/commands.ts#L8), [name: 'Show Specified Note',](https://github.com/Lio5n/peekaboo/blob/33b4dc26aa50514f235245c7f55c4cf72e04c7b7/src/commands.ts#L24), [name: 'Show All Configured Files',](https://github.com/Lio5n/peekaboo/blob/33b4dc26aa50514f235245c7f55c4cf72e04c7b7/src/commands.ts#L48), [name: 'Hide All Configured Files',](https://github.com/Lio5n/peekaboo/blob/33b4dc26aa50514f235245c7f55c4cf72e04c7b7/src/commands.ts#L64), [name: 'Create Folder',](https://github.com/Lio5n/peekaboo/blob/33b4dc26aa50514f235245c7f55c4cf72e04c7b7/src/commands.ts#L80), [contentEl.createEl('h2', { text: 'Enter Folder Name' });](https://github.com/Lio5n/peekaboo/blob/33b4dc26aa50514f235245c7f55c4cf72e04c7b7/src/commands.ts#L95), [contentEl.createEl('h2', { text: 'Enter Password' });](https://github.com/Lio5n/peekaboo/blob/33b4dc26aa50514f235245c7f55c4cf72e04c7b7/src/modals.ts#L13), [contentEl.createEl('h2', { text: 'Incorrect Password' });](https://github.com/Lio5n/peekaboo/blob/33b4dc26aa50514f235245c7f55c4cf72e04c7b7/src/modals.ts#L49), [this.createButton(contentEl, 'Toggle Configured Files Visibility', async () => {](https://github.com/Lio5n/peekaboo/blob/33b4dc26aa50514f235245c7f55c4cf72e04c7b7/src/ribbon.ts#L19), [this.createButton(contentEl, 'Show Specified Note', async () => {](https://github.com/Lio5n/peekaboo/blob/33b4dc26aa50514f235245c7f55c4cf72e04c7b7/src/ribbon.ts#L34), [this.createButton(contentEl, 'Show All Configured Files', async () => {](https://github.com/Lio5n/peekaboo/blob/33b4dc26aa50514f235245c7f55c4cf72e04c7b7/src/ribbon.ts#L57), [this.createButton(contentEl, 'Hide All Configured Files', async () => {](https://github.com/Lio5n/peekaboo/blob/33b4dc26aa50514f235245c7f55c4cf72e04c7b7/src/ribbon.ts#L72), [.setName('Configured Hidden Files')](https://github.com/Lio5n/peekaboo/blob/33b4dc26aa50514f235245c7f55c4cf72e04c7b7/src/settings.ts#L61), [.setName('Configured Exception Files')](https://github.com/Lio5n/peekaboo/blob/33b4dc26aa50514f235245c7f55c4cf72e04c7b7/src/settings.ts#L87), [button.setButtonText('Manage Exception Items')](https://github.com/Lio5n/peekaboo/blob/33b4dc26aa50514f235245c7f55c4cf72e04c7b7/src/settings.ts#L90), [.setDesc("1. About 'Configured Exception Files': For example, when you want to show a note within a hidden folder...");](https://github.com/Lio5n/peekaboo/blob/33b4dc26aa50514f235245c7f55c4cf72e04c7b7/src/settings.ts#L126), [contentEl.createEl('h2', { text: 'Manage Configured Hidden Folders and Files' });](https://github.com/Lio5n/peekaboo/blob/33b4dc26aa50514f235245c7f55c4cf72e04c7b7/src/settings.ts#L166-L167), [contentEl.createEl('h2', { text: 'Manage Configured Exception Folders and Files' });](https://github.com/Lio5n/peekaboo/blob/33b4dc26aa50514f235245c7f55c4cf72e04c7b7/src/settings.ts#L203)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[plugin.ribbonIconEl.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg"....'](https://github.com/Lio5n/peekaboo/blob/33b4dc26aa50514f235245c7f55c4cf72e04c7b7/src/ribbon.ts#L116), [plugin.ribbonIconEl.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg"....';](https://github.com/Lio5n/peekaboo/blob/33b4dc26aa50514f235245c7f55c4cf72e04c7b7/src/ribbon.ts#L119)
Use `setIcon(plugin.ribbonIconEl, 'eye')`/`setIcon(plugin.ribbonIconEl, 'eye-off')` instead


[containerEl.createEl('h2', { text: 'Peekaboo Settings' });](https://github.com/Lio5n/peekaboo/blob/33b4dc26aa50514f235245c7f55c4cf72e04c7b7/src/settings.ts#L45)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by Lio5n** [comment]
Hi ,

I've implemented the changes you suggested to the code. Thank you for the helpful feedback!

Regarding the option to hide the plugin's icon in the ribbon, I'd like to propose keeping this functionality. My testing shows that hiding the ribbon icon provides a cleaner integration with Obsidian: if a user hides the icon and restarts Obsidian, the plugin won't appear in the ribbon's right-click menu. This behavior aligns well with the plugin's intended functionality. Would you be open to reconsidering this aspect of the plugin?

**Comment by joethei** [comment]
That exactly the problem, if the plugin provides a ribbon icon, then it should always be possible to change its visibility from the app settings/right-click.

**Comment by Lio5n** [comment]
@joethei 
Hello! Thank you for reviewing my plugin and for your helpful feedback. I have implemented the changes you suggested and have pushed the update to the GitHub repository. The new version number is [1.2.3]. Please take a look when you have a chance. I appreciate your time and expertise in reviewing my plugin.

**Comment by joethei** [comment]
Sorry for the delay.

[if (this.ribbonIconEl) {](https://github.com/Lio5n/peekaboo/blob/05ff8b4f4719eea4dfca55b12f4964a2cbabd40c/src/main.ts#L40-L42), [if (!plugin.ribbonIconEl) {](https://github.com/Lio5n/peekaboo/blob/05ff8b4f4719eea4dfca55b12f4964a2cbabd40c/src/ribbon.ts#L127-L128)
That is not neccessary, Obsidian already handles that.

[containerEl.createEl('h2', { text: 'Hidden Files' });](https://github.com/Lio5n/peekaboo/blob/05ff8b4f4719eea4dfca55b12f4964a2cbabd40c/src/settings.ts#L45)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[/*](https://github.com/Lio5n/peekaboo/blob/05ff8b4f4719eea4dfca55b12f4964a2cbabd40c/src/settings.ts#L112-L124)
Remove this code entirely instead of commenting it out.

[contentEl.createEl('h2', { text: 'Manage Configured Hidden Folders and Files' });](https://github.com/Lio5n/peekaboo/blob/05ff8b4f4719eea4dfca55b12f4964a2cbabd40c/src/settings.ts#L168), [contentEl.createEl('h2', { text: 'Manage Configured Exception Folders and Files' });](https://github.com/Lio5n/peekaboo/blob/05ff8b4f4719eea4dfca55b12f4964a2cbabd40c/src/settings.ts#L205), [contentEl.createEl('h2', { text: 'Incorrect Password' });](https://github.com/Lio5n/peekaboo/blob/05ff8b4f4719eea4dfca55b12f4964a2cbabd40c/src/modals.ts#L49), [contentEl.createEl('h2', { text: 'Enter Folder Name' });](https://github.com/Lio5n/peekaboo/blob/05ff8b4f4719eea4dfca55b12f4964a2cbabd40c/src/commands.ts#L95)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Pull request closed without merging**
