### PR TITLE
Add plugin: Chronos Timeline

### PR DESCRIPTION
**Pull request by clairefro**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/clairefro/obsidian-plugin-chronos

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [x]  Linux
  
  **I have not tested on mobile yet but am confident it should work, since my only dependency (`vis-timeline`) is mobile compatible**
  
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
    
- [x] I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by clairefro** [comment]
Updated based on all the request above

**Comment by joethei** [comment]
[markdown](https://github.com/clairefro/obsidian-plugin-chronos/blob/f0c921c108e76683e439d93b71e0520de39c458f/manifest.json#L6)
Markdown is a name and is capitalized.

[containerEl.createEl("h2", { text: "Preferred Locale" });](https://github.com/clairefro/obsidian-plugin-chronos/blob/f0c921c108e76683e439d93b71e0520de39c458f/main.ts#L109)
Your settings tab only offers one setting, so there should not be a header here.

[.setName("Select Locale")](https://github.com/clairefro/obsidian-plugin-chronos/blob/f0c921c108e76683e439d93b71e0520de39c458f/main.ts#L132)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)


[containerEl.createEl("h2", { text: "Cheatsheet" });](https://github.com/clairefro/obsidian-plugin-chronos/blob/f0c921c108e76683e439d93b71e0520de39c458f/main.ts#L152)
For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```

**Comment by clairefro** [comment]
Thanks always, @joethei !

I pushed the first three changes and updated `main.js` in release. 

>[containerEl.createEl("h2", { text: "Cheatsheet" });](https://github.com/clairefro/obsidian-plugin-chronos/blob/f0c921c108e76683e439d93b71e0520de39c458f/main.ts#L152)
For section headings in settings use:


I'll note your last suggestion for the future, but not applying in this case since the Cheatsheet is not an Obsidian Setting object, rather a readonly textarea. 

Updated Settings tab 
image

**Comment by clairefro** [comment]
ah, noticed the Settings heading thing works without creating a setting. So I [applied](https://github.com/clairefro/obsidian-plugin-chronos/blob/main/main.ts#L150) your suggestion in the end

**Comment by clairefro** [comment]
@joethei I added a "generate timeline with AI" feature in a new branch, but am debating to merge before or after approval of the above. It uses Obsidian's native `requestUrl` for the API call. 

If there's no problem with the new feature I'll merge it, otherwise I can release the first version without it

https://github.com/clairefro/obsidian-plugin-chronos/pull/1

**Comment by joethei** [comment]
There is only one tiny thing in that PR, left a comment.

**Pull request merged**
