### PR TITLE
Add plugin: LanguageTool

### PR DESCRIPTION
**Pull request by wrenger**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/wrenger/obsidian-languagetool

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by wrenger** [comment]
Hi, I hope I've solved all the issues. I would be glad if you review this extension.

**Comment by joethei** [comment]
Wouldn't it be smarter to submit these changes as a PR to the original plugin?

["description": "Inofficial LanguageTool plugin",](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/manifest.json#L6)
Add some more description what this plugin does.

["author": "Lars Wrenger",](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/manifest.json#L7)
Please also credit the orignal author here.

[id: 'ltcheck-text',](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/src/main.ts#L46), [id: 'ltautocheck-text',](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/src/main.ts#L58), [id: 'ltclear',](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/src/main.ts#L67), [id: 'ltjump-to-next-suggestion',](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/src/main.ts#L79), [id: `ltaccept-suggestion-${n}`,](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/src/main.ts#L111)
Don't prefix the command id with the plugin id, Obsidian will make sure that there are no conflicts with other plugins.

[name: 'Check Text',](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/src/main.ts#L47), [name: 'Toggle Automatic Checking',](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/src/main.ts#L59), [name: 'Clear Suggestions',](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/src/main.ts#L68), [name: 'Jump to next Suggestion',](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/src/main.ts#L80), [text: 'Copy failed Request Logs',](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/src/settingsTab.ts#L113), [.setName('AutoCheck Delay (ms)')](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/src/settingsTab.ts#L216), [.setName('API Username')](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/src/settingsTab.ts#L175), [.setName('Find Synonyms')](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/src/settingsTab.ts#L231), [.setName('Mother Tongue')](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/src/settingsTab.ts#L251), [.setName('Static Language')](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/src/settingsTab.ts#L274), [.addOption('auto', 'Auto Detect')](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/src/settingsTab.ts#L283), [containerEl.createEl('h3', { text: 'Language Varieties' });](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/src/settingsTab.ts#L304), [containerEl.createEl('h3', { text: 'Rule Categories' });](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/src/settingsTab.ts#L401), [.setName('Picky Mode')](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/src/settingsTab.ts#L412), [.setName('Enabled Categories')](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/src/settingsTab.ts#L424), [.setName('Disabled Categories')](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/src/settingsTab.ts#L437), [.setName('Enabled Rules')](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/src/settingsTab.ts#L450)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)
Events need to be registered, so they can be properly unloaded when the plugin is disabled. <https://docs.obsidian.md/Plugins/Events>

[containerEl.createEl('h2', { text: this.plugin.manifest.name });](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/src/settingsTab.ts#L111)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[containerEl.createEl('h3', { text: 'Language Varieties' });](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/src/settingsTab.ts#L304), [containerEl.createEl('h3', { text: 'Rule Categories' });](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/src/settingsTab.ts#L401)
For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```

[res = await fetch(`${settings.serverUrl}/v2/check`, {](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/src/api.ts#L110), [res = await fetch(URL, {](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/src/api.ts#L171)
Use the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

**Comment by wrenger** [comment]
> Wouldn't it be smarter to submit these changes as a PR to the original plugin?

I did until I saw that these changes were probably too big for PRs. Especially, as the original plugin is in maintenance mode and the author doesn't seem to have intentions to develop it further.

**Comment by wrenger** [comment]
> ["author": "Lars Wrenger",](https://github.com/wrenger/obsidian-languagetool/blob/2ea9ecf9d51f8e46d735caaf7097f2984797a557/manifest.json#L7)
> Please also credit the orignal author here.

Does the manifest format accept an array of authors? Or should I just add him to the string like `"author": "Lars Wrenger, Clemens Ertle"`

**Comment by wrenger** [comment]
@joethei, thanks for your feedback. I've addressed all of your points.

**Comment by wrenger** [comment]
The newest release [1.0.4](https://github.com/wrenger/obsidian-languagetool/releases/tag/1.0.4) fixes a rendering issue on iOS. 

I've implemented the requested changes weeks ago. It would be great if this plugin is accepted eventually... ^^"

**Comment by wrenger** [comment]
The plugin is mostly finished including the feedback. So I don't know if there is anything left blocking this from being approved and merged.

**Comment by joethei** [comment]
Sorry for the delay,

["description": "Inofficial plugin that integrates the LanguageTool spell and grammar checker into obsidian.",](https://github.com/wrenger/obsidian-languagetool/blob/a02d5ad1a822bdfbf16aefa8073f42a9fbc619a2/manifest.json#L6C1-L6C111)
Avoid including sentences like "This is a plugin for Obsidian that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

**Comment by wrenger** [comment]
Ok @joethei I've updated the description accordingly 👍🏻

**Pull request merged**
