### PR TITLE
Add Day Planner (OG)

### PR DESCRIPTION
**Pull request by ebullient**
# I am submitting a new Community Plugin

Add the alternate day-planner plugin, with some text modifications to disambiguate between the two (where one is adding new features and capabilities, and the other is hewing closer to the original behavior).

@ivan-lednev .. LMK what you think.

Note: They are now separated in the file, but I still have the proposed changes (with agreement below).

## Repo URL

Link to my plugin: https://github.com/ebullient/obsidian-day-planner-og

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by ivan-lednev** [comment]
@ebullient looks good to me.

**Comment by joethei** [comment]
Please follow the pull request template
Also, all new plugins go to the end of the list.

**Comment by joethei** [comment]
[Copyright (c) 2020 James Lynch](https://github.com/ebullient/obsidian-day-planner-og/blob/a8083f18cfbf5578a2f86d3f89d8cd1cbf526c5b/LICENSE#L3)
Update this,

["author": "ebullient",](https://github.com/ebullient/obsidian-day-planner-og/blob/a8083f18cfbf5578a2f86d3f89d8cd1cbf526c5b/manifest.json#L7)
Credit the original author here too.

["js": "main.js",](https://github.com/ebullient/obsidian-day-planner-og/blob/a8083f18cfbf5578a2f86d3f89d8cd1cbf526c5b/manifest.json#L9-L10)
These two are not used in Obsidian

[id: 'app:add-day-planner-to-note',](https://github.com/ebullient/obsidian-day-planner-og/blob/a8083f18cfbf5578a2f86d3f89d8cd1cbf526c5b/src/main.ts#L51)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.
(The id's can be shorter in general)


[this.app.workspace](https://github.com/ebullient/obsidian-day-planner-og/blob/a8083f18cfbf5578a2f86d3f89d8cd1cbf526c5b/src/main.ts#L189-L191)
Do not detach leaves with your custom view in `onunload`, this is an antipattern, see: <https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Don't+detach+leaves+in+%60onunload%60>


[import moment from 'moment';](https://github.com/ebullient/obsidian-day-planner-og/blob/a8083f18cfbf5578a2f86d3f89d8cd1cbf526c5b/src/moment-date-regex.ts#L2)
Import moment from Obsidian.

[.setName('Day Planner Mode')](https://github.com/ebullient/obsidian-day-planner-og/blob/a8083f18cfbf5578a2f86d3f89d8cd1cbf526c5b/src/settings-tab.ts#L25)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by ebullient** [comment]
> [Copyright (c) 2020 James Lynch](https://github.com/ebullient/obsidian-day-planner-og/blob/a8083f18cfbf5578a2f86d3f89d8cd1cbf526c5b/LICENSE#L3) Update this,

This needs to be fixed in the new version, too: https://github.com/ivan-lednev/obsidian-day-planner/blob/main/LICENSE

> 
> ["author": "ebullient",](https://github.com/ebullient/obsidian-day-planner-og/blob/a8083f18cfbf5578a2f86d3f89d8cd1cbf526c5b/manifest.json#L7) Credit the original author here too.

Wasn't sure (at this point) if it is a free string or a GH id, especially as ack is in the description, but updated.

> 
> ["js": "main.js",](https://github.com/ebullient/obsidian-day-planner-og/blob/a8083f18cfbf5578a2f86d3f89d8cd1cbf526c5b/manifest.json#L9-L10) These two are not used in Obsidian

Left-over from original, removed.

> 
> [id: 'app:add-day-planner-to-note',](https://github.com/ebullient/obsidian-day-planner-og/blob/a8083f18cfbf5578a2f86d3f89d8cd1cbf526c5b/src/main.ts#L51) Obsidian will automatically prefix the command id with the plugin id, you don't need to include it yourself. (The id's can be shorter in general)

Trying to disturb as little as I can right now. It works as it did before. I will review and revise over time (I have to update to newer svelte, e.g.), so I'll fix this when I know the codebase better.

> [this.app.workspace](https://github.com/ebullient/obsidian-day-planner-og/blob/a8083f18cfbf5578a2f86d3f89d8cd1cbf526c5b/src/main.ts#L189-L191) Do not detach leaves with your custom view in `onunload`, this is an antipattern, see: https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Don't+detach+leaves+in+%60onunload%60

This is from the original plugin. Realize this is a fork, not a new thing. I will fix it as I make additional updates (as noted above). Immediate concern is providing continuity for those wanting old behavior as the plugin with previous function has been replaced in the community plugin list.

> [import moment from 'moment';](https://github.com/ebullient/obsidian-day-planner-og/blob/a8083f18cfbf5578a2f86d3f89d8cd1cbf526c5b/src/moment-date-regex.ts#L2) Import moment from Obsidian.

Will fix this in next rev (as I update svelte, etc). 

> [.setName('Day Planner Mode')](https://github.com/ebullient/obsidian-day-planner-og/blob/a8083f18cfbf5578a2f86d3f89d8cd1cbf526c5b/src/settings-tab.ts#L25) [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

Will fix this in next rev.

I get the point of the feedback and review, but this is a fork of an existing plugin. Cleaning it up is in the plan, and I will get there, but this is something of a weird case.

**Comment by ebullient** [comment]
I had time. Raised issues resolved.

**Comment by ebullient** [comment]
Updated to be current with master

**Pull request merged**
