### PR TITLE
Add ai assistant plugin

### PR DESCRIPTION
**Pull request by qgrail**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/qgrail/obsidian-ai-assistant

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
I generally recommend moving all code files into a separate `src` folder, that makes it easier to review and maintain.

[// Remember to rename these classes and interfaces!](https://github.com/qgrail/obsidian-ai-assistant/blob/62454aff600a525bb369f5bfbe12824912d0c5aa/main.ts#L13-L14)
Please do this

[id: "open-ai_assistant-chat",](https://github.com/qgrail/obsidian-ai-assistant/blob/62454aff600a525bb369f5bfbe12824912d0c5aa/main.ts#L49)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

What sets your plugin apart from the other existing Chat-GPT plugins?

**Comment by qgrail** [comment]
Hello @joethei, in the last release, I have:
- Moved the code to a separate src folder,
- Renamed relevant  classes and interfaces of this [file](https://github.com/qgrail/obsidian-ai-assistant/blob/main/src/main.ts),
- Removed the plugin name suffix from my command ids.

Compared to existing Chat-GPT plugins such as [obsidian-textgenerator-plugin](https://github.com/nhaouari/obsidian-textgenerator-plugin), [obsidian-ava](https://github.com/louis030195/obsidian-ava) or [obsidian-gpt](https://github.com/jmilldotdev/obsidian-gpt), this plugin allows you to have contextualized interaction with chat-GPT with multiple rounds of discussion through the chat mode. This feature is not available in the other plugins.

**Comment by qgrail** [comment]
@joethei Any update on this PR?
Thank you.

**Comment by liamcain** [comment]
- [isDesktopOnly](https://github.com/qgrail/obsidian-ai-assistant/blob/1ead947b4284c8604140763ddbae4743449ac892/manifest.json#L8) you have this marked as working on Mobile unfortunately, you are importing both "fs" and "path" which are node.js libraries and not available on mobile. Those imports will cause the plugin to not load.

**Comment by qgrail** [comment]
Hi @liamcain 
I have removed all the dependencies to "fs" and "path" node.js libraries to make it compatible with mobile.
Thank you

**Pull request merged**
