### PR TITLE
Add plugin: Mahjong Renderer

### PR DESCRIPTION
**Pull request by kulak-at**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/h-sphere/obsidian-mahjong-renderer

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[backgroundTile.alt = 'Tile Background'](https://github.com/h-sphere/obsidian-mahjong-renderer/blob/1133b3d06dbd8996473871bc301427af8f1e1306/main.ts#L76)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[console.log('SOURCE', sourceValue)](https://github.com/h-sphere/obsidian-mahjong-renderer/blob/1133b3d06dbd8996473871bc301427af8f1e1306/main.ts#L114)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

**Comment by kulak-at** [comment]
@joethei Thank you for the review. I fixed those now and re-released the package.

**Comment by kulak-at** [comment]
@joethei All should be fixed now, please review at your earliest convenience.

**Comment by liamcain** [comment]
Looks good. Merged, sorry for the delay!

**Comment by kulak-at** [comment]
No worries, thank you!

**Pull request merged**
