### PR TITLE
Add plugin: Auto Tag

### PR DESCRIPTION
**Pull request by CtrlAltFocus**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: 
[https://github.com/CtrlAltFocus/obsidian-plugin-auto-tag](https://github.com/CtrlAltFocus/obsidian-plugin-auto-tag)

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux (update: tested, works fine)
  - [x]  Android _(if applicable)_ 
  - [x]  iOS _(if applicable)_ 
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
  - **Dear reviewer, Please note**: i have taken note of 1 settings subtitle to clean up (remove "settings" from it), and to verify my use of innerhtml for notice display although it should be already secure enough. I will release a patch version update very soon.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.
  - **Dear reviewers, please note**: I will note all direct dependencies and their licenses (they all fit within my own MIT license) in the upcoming patch version update. I use license-checker for this. I will list my own license and dependency licenses at the bottom of the README 👍

### CODE REVIEW

**Comment by CtrlAltFocus** [comment]
updated after testing on mobile devices and on linux

**Comment by CtrlAltFocus** [comment]
thanks @ericaxu , do you know if there is something preventing review or just need to wait longer?

**Comment by joethei** [comment]
[[BETA! Safe to use, features lacking]](https://github.com/CtrlAltFocus/obsidian-plugin-auto-tag/blob/6e102a5bec927c53a473f2b1cc61f4596768da74/manifest.json#L6)
Don't include this in the plugin description, the readme is fine.

[template.innerHTML = htmlString.trim();](https://github.com/CtrlAltFocus/obsidian-plugin-auto-tag/blob/6e102a5bec927c53a473f2b1cc61f4596768da74/src/utils/utils.ts#L3)
[Avoid using `innerHTML`](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%60innerHTML%60%2C+%60outerHTML%60+and+%60insertAdjacentHTML%60)

[const response = await axios.post(](https://github.com/CtrlAltFocus/obsidian-plugin-auto-tag/blob/6e102a5bec927c53a473f2b1cc61f4596768da74/src/services/openai.api.ts#L98)
I recommend using the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

[.setName(`Service provider settings`);](https://github.com/CtrlAltFocus/obsidian-plugin-auto-tag/blob/6e102a5bec927c53a473f2b1cc61f4596768da74/src/plugin/settings/settings.ts#L141)
[Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

[contentEl.createEl('h2', { text: 'Auto Tag Action Menu' });](https://github.com/CtrlAltFocus/obsidian-plugin-auto-tag/blob/6e102a5bec927c53a473f2b1cc61f4596768da74/src/plugin/modals/actionMenuModal.ts#L28)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[id: 'auto-tag--select-text-insert-tags',](https://github.com/CtrlAltFocus/obsidian-plugin-auto-tag/blob/6e102a5bec927c53a473f2b1cc61f4596768da74/src/plugin/commands/commands.ts#L15)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

[export const insertTagsInFrontMatter = (newTags: string[], editor: Editor, settings: AutoTagPluginSettings): boolean => {](https://github.com/CtrlAltFocus/obsidian-plugin-auto-tag/blob/6e102a5bec927c53a473f2b1cc61f4596768da74/src/businesslogic/insertTags.ts#L67-L96)
Use the `processFrontMatter` API instead: <https://github.com/obsidianmd/obsidian-api/blob/master/CHANGELOG.md#new-metadata-api>

**Comment by CtrlAltFocus** [comment]
Hi @joethei,
thank you for the PR review!

I addressed all items (across 3-4 separate commits).
Generated a new release (0.2.7) : https://github.com/CtrlAltFocus/obsidian-plugin-auto-tag/releases/tag/0.2.7

I believe I did not leave anything out, related to your comments but let me know if you see something (new or old).
Thank you for the time spent on this and the detailed helpful review comment.

**Comment by liamcain** [comment]
- [view: MarkdownView](https://github.com/CtrlAltFocus/obsidian-plugin-auto-tag/blob/b418993e3f98f7168d756089c53aa4e22941d7af/src/plugin/commands/commands.ts#L15) the type signature here is incorrect. The second argument is `ctx: MarkdownView | MarkdownFileInfo` which might not be a MarkdownView.

**Comment by CtrlAltFocus** [comment]
thank you @liamcain will verify and improve :-) 
appreciate the merge! will make it easier to test on larger scale

**Pull request merged**
