### PR TITLE
Add plugin: Livecodes Playground

### PR DESCRIPTION
**Pull request by gapmiss**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/gapmiss/livecodes-playground

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by gapmiss** [comment]
> [[1](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/settings/index.ts#L672)][[2](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/modals/StarterSelect.ts#L84)][[3](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/modals/StarterSelect.ts#L85)][[4](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/modals/LanguageSelect.ts#L79)][[6](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/main.ts#L217)][[7](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/main.ts#L220)][[8](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/main.ts#L232)][[9](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/main.ts#L537)][[10](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/main.ts#L555)][[11](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/main.ts#L556)][[12](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/main.ts#L657)][[13](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/main.ts#L658)][[14](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/main.ts#L670)][[15](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/main.ts#L671)][[16](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/main.ts#L682)][[17](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/main.ts#L685)][[18](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/main.ts#L779)][[19](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/main.ts#L793)][[20](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/main.ts#L794)][[21](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/main.ts#L806)][[22](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/main.ts#L807)][[23](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/main.ts#L819)][[24](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/main.ts#L820)][[25](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/main.ts#L827)][[26](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/main.ts#L828)][[27](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/main.ts#L893)][[28](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/main.ts#L894)][[29](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/editor/codeblockProcessor.ts#L10)]:You should avoid assigning styles via JavaScript or in HTML and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets.

/skip
All, except for #[[5](https://github.com/gapmiss/livecodes-playground/blob/f944445a2c19f81a53a25c98d1a37b0f9774a687/src/utils/index.ts#L23)], are JS objects and NOT CSS styles.

**Comment by joethei** [comment]
[cnf.head = blankPlayground.head + '\n<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>';](https://github.com/gapmiss/livecodes-playground/blob/fb05fcedbee0773213f926f742a33652bfb6f238/src/main.ts#L237)
This should be bundled into the plugin.

[this.app.workspace.getLeavesOfType(VIEW_TYPE_PLAYGROUND).forEach((leaf) => {](https://github.com/gapmiss/livecodes-playground/blob/fb05fcedbee0773213f926f742a33652bfb6f238/src/main.ts#L472-L476)
Do not detach leaves with your custom view in `onunload`, this is an antipattern, see: <https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Don't+detach+leaves+in+%60onunload%60>

[this.app.workspace.getLeavesOfType(VIEW_TYPE_PLAYGROUND).forEach((leaf) => {](https://github.com/gapmiss/livecodes-playground/blob/fb05fcedbee0773213f926f742a33652bfb6f238/src/main.ts#L967-L972)
Also don't detach leaves here.

[sleep(ms:number) {](https://github.com/gapmiss/livecodes-playground/blob/fb05fcedbee0773213f926f742a33652bfb6f238/src/main.ts#L1000-L1002)
This is already a function in the Obsidian API.

[async copyStringToClipboard(text:string, topic:string|undefined=undefined) {](https://github.com/gapmiss/livecodes-playground/blob/fb05fcedbee0773213f926f742a33652bfb6f238/src/main.ts#L1004-L1013)
This function is duplicated, it's also in utils.

[suggest.ts](https://github.com/gapmiss/livecodes-playground/blob/fb05fcedbee0773213f926f742a33652bfb6f238/src/settings/suggest.ts)
This should no longer be used, instead implement a `AbstractInputSuggest` instead.

[new Setting(containerEl)](https://github.com/gapmiss/livecodes-playground/blob/fb05fcedbee0773213f926f742a33652bfb6f238/src/settings/index.ts#L57-L67)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[.setName("Plugin settings")](https://github.com/gapmiss/livecodes-playground/blob/fb05fcedbee0773213f926f742a33652bfb6f238/src/settings/index.ts#L69)
Remove this heading, there should not be a top level heading in plugin settings.

[.setName("Sharing settings")](https://github.com/gapmiss/livecodes-playground/blob/fb05fcedbee0773213f926f742a33652bfb6f238/src/settings/index.ts#L166), [.setName("Editor settings")](https://github.com/gapmiss/livecodes-playground/blob/fb05fcedbee0773213f926f742a33652bfb6f238/src/settings/index.ts#L254)
[Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

[import moment from "moment";](https://github.com/gapmiss/livecodes-playground/blob/fb05fcedbee0773213f926f742a33652bfb6f238/src/components/Playground.svelte#L15)
Import moment from the Obsidian API instead.

[const app = this.app;](https://github.com/gapmiss/livecodes-playground/blob/fb05fcedbee0773213f926f742a33652bfb6f238/src/components/Playground.svelte#L20)
It's highly discouraged that you use the global app instance in your plugin. It's currently accessible from the global context for debugging purposes, and might be removed in the future. Instead, you should use the reference to App that you have from your plugin instance.

**Comment by gapmiss** [comment]
> [cnf.head = blankPlayground.head + '\n<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>';](https://github.com/gapmiss/livecodes-playground/blob/fb05fcedbee0773213f926f742a33652bfb6f238/src/main.ts#L237) This should be bundled into the plugin.

The plugin, itself, does not use jQuery. This code adds the jQuery `<script>` to the playground JSON config file and is used inside the playground iframe.

All additional changes requested have been resolved.

Thank you

**Comment by gapmiss** [comment]
@joethei If I push some minor changes and fixes, other than the ones above, and create a new release, will that create a problem with this P.R. ?

Thank you

**Comment by gapmiss** [comment]
@joethei

I have some small fixes and a "feature" update for this plugin. Can I update the repo and NOT effect this P.R.? Or do I need to wait until your approval and merge? Please advise…

Thank you

**Pull request merged**
