### PR TITLE
Add plugin: Prompt ChatGPT

### PR DESCRIPTION
**Pull request by Coduhuey**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [Coduhuey/ChatGPT-Prompt-Plugin-For-Obsidian](https://github.com/Coduhuey/ChatGPT-Prompt-Plugin-For-Obsidian)

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Coduhuey** [comment]
I created a new version (1.0.7) for all the changes the review bot suggested.

**Comment by joethei** [comment]
["authorUrl": "",](https://github.com/Coduhuey/ChatGPT-Prompt-Plugin-For-Obsidian/blob/5a515537633fb38f355d648064c39ebb2296df27/manifest.json#L8)
Add your GitHub profile url here if you don't have a website.

[// Remember to rename these classes and interfaces!](https://github.com/Coduhuey/ChatGPT-Prompt-Plugin-For-Obsidian/blob/5a515537633fb38f355d648064c39ebb2296df27/main.ts#L5)
Remove this comment

[export const VIEW_TYPE_EXAMPLE = "example-view";](https://github.com/Coduhuey/ChatGPT-Prompt-Plugin-For-Obsidian/blob/5a515537633fb38f355d648064c39ebb2296df27/main.ts#L37), [export class ExampleView extends ItemView {](https://github.com/Coduhuey/ChatGPT-Prompt-Plugin-For-Obsidian/blob/5a515537633fb38f355d648064c39ebb2296df27/main.ts#L40)
use proper values & names here.

[window: WorkspaceLeaf;](https://github.com/Coduhuey/ChatGPT-Prompt-Plugin-For-Obsidian/blob/5a515537633fb38f355d648064c39ebb2296df27/main.ts#L165)

[this.addRibbonIcon('dice', 'Show/Hide ChatGPT', () => {](https://github.com/Coduhuey/ChatGPT-Prompt-Plugin-For-Obsidian/blob/5a515537633fb38f355d648064c39ebb2296df27/main.ts#L187)
use a different icon here.


[this.app.workspace.on('file-open', (file) => {](https://github.com/Coduhuey/ChatGPT-Prompt-Plugin-For-Obsidian/blob/5a515537633fb38f355d648064c39ebb2296df27/main.ts#L207)
Events need to be registered, so they can be properly unloaded when the plugin is disabled. <https://docs.obsidian.md/Plugins/Events>

[this.settings.tags.forEach((tag) => {](https://github.com/Coduhuey/ChatGPT-Prompt-Plugin-For-Obsidian/blob/5a515537633fb38f355d648064c39ebb2296df27/main.ts#L233-L264)
If a user has multiple tags on that file, your plugin will call ChatGPT multiple times, please fix this.

**Comment by Coduhuey** [comment]
Thank you for the comments

I added another release (1.0.8) for all the changes requested.

**Comment by liamcain** [comment]
- [let leaf = leaves[0];](https://github.com/Coduhuey/ChatGPT-Prompt-Plugin-For-Obsidian/blob/c6dbbd025269b15446dc344eba59031ef6d97674/main.ts#L342) why are you only detaching the first view you find? Isn't this function supposed to detach all of them?

**Pull request merged**
