### PR TITLE
Add plugin: Semantic Canvas

### PR DESCRIPTION
**Pull request by aarongilly**
Added my plugin for consideration. Adds two commands to Obsidian to enable canvases to update the properties of files with nodes contained in the canvas, based on links and groups drawn in the canvas, and for canvases to be created based on note properties.

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/aarongilly/obsidian-semantic-canvas-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[.setName('Set note properties for connections to Cards ')](https://github.com/aarongilly/obsidian-semantic-canvas-plugin/blob/9abe2c331f62730df0e1172248391f6ec0c86588/main.ts#L476), [.setName('Default Property Label for connections to Cards')](https://github.com/aarongilly/obsidian-semantic-canvas-plugin/blob/9abe2c331f62730df0e1172248391f6ec0c86588/main.ts#L486), [.setName('Set note properties for connections to Web Embeds ')](https://github.com/aarongilly/obsidian-semantic-canvas-plugin/blob/9abe2c331f62730df0e1172248391f6ec0c86588/main.ts#L497), [.setName('Default Property Label for connections to Urls')](https://github.com/aarongilly/obsidian-semantic-canvas-plugin/blob/9abe2c331f62730df0e1172248391f6ec0c86588/main.ts#L507), [.setName('Set note properties for connections to Files')](https://github.com/aarongilly/obsidian-semantic-canvas-plugin/blob/9abe2c331f62730df0e1172248391f6ec0c86588/main.ts#L518), [.setName('Default Property Label for connections to Files')](https://github.com/aarongilly/obsidian-semantic-canvas-plugin/blob/9abe2c331f62730df0e1172248391f6ec0c86588/main.ts#L528), [.setName('Default Property Label for containment in Groups')](https://github.com/aarongilly/obsidian-semantic-canvas-plugin/blob/9abe2c331f62730df0e1172248391f6ec0c86588/main.ts#L550)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by aarongilly** [comment]
Updated to Tag & Release 1.1.0, which addresses the sentence-case issue & adds a new feature that allows you to generate canvases based on the active note's properties. **Do I need to re-submit - or is this comment sufficient?** 
I'm quite new to the Release & submit process.

**Comment by aarongilly** [comment]
Added the unzipped `main.js` & `manifest.json` to my release. Sorry, again very new to the Github releases process. Hopefully this re-triggers the validation.

**Comment by aarongilly** [comment]
Testing another comment, to see if that’s considered a “change” to trigger the validation bot.

**Comment by aarongilly** [comment]
Closing to re-open for a fresh round of validation.

**Comment by aarongilly** [comment]
Re-opening in hopes of triggering the validation bot.

**Pull request merged**
