### PR TITLE
Add plugin: Update Time

### PR DESCRIPTION
**Pull request by dsebastien**
# I am submitting a new Community Plugin

## Repo URL
Link to my plugin: https://github.com/dsebastien/obsidian-update-time

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by dsebastien** [comment]
This plugin is a fork of https://github.com/beaussan/update-time-on-edit-obsidian, focusing on delivering a simpler feature, while fixing the compatibility issue with Obsidian publish.

cfr:
- https://github.com/beaussan/update-time-on-edit-obsidian/issues/75
- https://forum.obsidian.md/t/publish-keeps-throwing-file-hash-mismatch-error/69035/11

**Comment by dsebastien** [comment]
I've renamed the plugin class as requested

**Comment by joethei** [comment]
["description": "Obsidian plugin that updates front matter to include creation and last update times",](https://github.com/dsebastien/obsidian-update-time/blob/905b2b1707569c9cb56c6b0c70c28db9a67cdd40/manifest.json#L4)
Avoid including sentences like "This is a plugin for Obsidian that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

["author": "Sébastien Dubois",](https://github.com/dsebastien/obsidian-update-time/blob/905b2b1707569c9cb56c6b0c70c28db9a67cdd40/manifest.json#L8)
Since your plugin is a fork you need to mention the original author here.

[export function isTFile(value: TAbstractFile): value is TFile {](https://github.com/dsebastien/obsidian-update-time/blob/905b2b1707569c9cb56c6b0c70c28db9a67cdd40/apps/plugin/src/app/utils/is-tfile.fn.ts#L3-L5)
Check that `value instanceof TFile` instead of calling this method.

[export const delay = (ms: number): Promise<void> =>](https://github.com/dsebastien/obsidian-update-time/blob/905b2b1707569c9cb56c6b0c70c28db9a67cdd40/apps/plugin/src/app/utils/delay.ts#L6-L8)
use the `sleep` method from the Obsidian API instead.

[suggest.ts](https://github.com/dsebastien/obsidian-update-time/blob/905b2b1707569c9cb56c6b0c70c28db9a67cdd40/apps/plugin/src/app/settingTab/suggest.ts)
This class should no longer be used, implement a [AbstractInputSuggest](https://docs.obsidian.md/Reference/TypeScript+API/AbstractInputSuggest) instead.

[containerEl.createEl('h1', { text: pluginManifest.name });](https://github.com/dsebastien/obsidian-update-time/blob/905b2b1707569c9cb56c6b0c70c28db9a67cdd40/apps/plugin/src/app/settingTab/index.ts#L24)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[containerEl.createEl('h2', { text: 'Settings' });](https://github.com/dsebastien/obsidian-update-time/blob/905b2b1707569c9cb56c6b0c70c28db9a67cdd40/apps/plugin/src/app/settingTab/index.ts#L26)
[Don't use a "general" heading in your settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[new Setting(containerEl).setName('Enabled').addToggle((toggle) =>](https://github.com/dsebastien/obsidian-update-time/blob/905b2b1707569c9cb56c6b0c70c28db9a67cdd40/apps/plugin/src/app/settingTab/index.ts#L28-L38)
This should not be a setting, if a user wants to disable the plugin it should happen from the "Community plugins" tab.

**Comment by dsebastien** [comment]
Hello,

Thanks for the review. I have release version 1.0.3 accordingly.

- I have updated the description as requested
- I haven't changed the author because my plugin is actually more of a rewrite than an actual fork, and it doesn't seem logical to me to associate it with someone else's name

- I'd prefer to keep the `isTFile` type guard call, as it lets TypeScript narrow-down the type in the rest of the code, which is not the case with instanceof


- I've removed the delay function since it was not used

- I've updated the settings screen as requested
- I'd like to keep the "Enabled" setting in this plugin, because I consider it dangerous to have this plugin make changes as soon as it is enabled, since the user will not have had time (or thought about) correctly configuring it first. This option is a valuable safety net for this type of plugin. I hope you'll agree
- Not sure about what to do to replace `suggest.ts`. Do you have an example I can follow? Is this blocking for the plugin to be accepted?

**Comment by dsebastien** [comment]
I have updated my project to remove the `enabled` setting. After thinking about it, I agree that the problems (if any) should be limited.

**Comment by dsebastien** [comment]
Hello @joethei, is there anything more I can do to help this PR move forward?

**Comment by joethei** [comment]
The `isTFile` function still exists.

The `suggest.ts` file is still in your repo, it needs to be removed.
The API you need to implement instead is `AbstractInputSuggest`.

**Comment by dsebastien** [comment]
Could you take a look at my previous comments?
I do see added value (type-safety wise for `isTFile`), and I don't know how to implement `AbstractInputSuggest`

**Comment by joethei** [comment]
The type-guard you implemented will be broken if we ever add a `stat` to the `TFolder` class.
Having the `instanceof` check is more future-proof.

And the interface of `AbstractInputSuggest` is very similar to the `TextInputSuggest` from Liam's code, just replace the type your `FolderSuggest` extends.

**Comment by dsebastien** [comment]
I've updated the code as requested. I've removed `isTfile` and now use `AbstractInputSuggest`.

**Comment by joethei** [comment]
[this.renderSupportHeader(containerEl);](https://github.com/dsebastien/obsidian-update-time/blob/86081ebb45120b40c5d9a4c7d28035460a862af4/apps/plugin/src/app/settingTab/index.ts#L23)
This should not be the first thing in the settings tab, but rather the last.

[log(`Processing updated file: ${file.path}`);](https://github.com/dsebastien/obsidian-update-time/blob/86081ebb45120b40c5d9a4c7d28035460a862af4/apps/plugin/src/app/plugin.ts#L111), [log('Adding the created property');](https://github.com/dsebastien/obsidian-update-time/blob/86081ebb45120b40c5d9a4c7d28035460a862af4/apps/plugin/src/app/plugin.ts#L131), [log('Adding the updated property');](https://github.com/dsebastien/obsidian-update-time/blob/86081ebb45120b40c5d9a4c7d28035460a862af4/apps/plugin/src/app/plugin.ts#L142), [log('Updating the updated property');](https://github.com/dsebastien/obsidian-update-time/blob/86081ebb45120b40c5d9a4c7d28035460a862af4/apps/plugin/src/app/plugin.ts#L149), [log(](https://github.com/dsebastien/obsidian-update-time/blob/86081ebb45120b40c5d9a4c7d28035460a862af4/apps/plugin/src/app/plugin.ts#L198-L200)
Please avoid unnecessary logging.

[log(](https://github.com/dsebastien/obsidian-update-time/blob/86081ebb45120b40c5d9a4c7d28035460a862af4/apps/plugin/src/app/plugin.ts#L124-L126)
This is missing some information about the file in question.

**Comment by dsebastien** [comment]
I've released a new version with the requested changes. I forgot to add 'debug' to multiple log statements

**Pull request merged**
