### PR TITLE
Add plugin: Smart Second Brain

### PR DESCRIPTION
**Pull request by nicobrauchtgit**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [Smart Second Brain](https://github.com/nicobrauchtgit/obsidian-Smart2Brain)

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by nicobrauchtgit** [comment]
Moved manifest.json to root

**Comment by joethei** [comment]
["authorUrl": "https://github.com/Leo310, https://github.com/nicobrauchtgit",](https://github.com/nicobrauchtgit/obsidian-Smart2Brain/blob/7f9533cf90b3bfd218f38b2f8e3fbb6dc51464be/manifest.json#L6)
This only accepts one URL.

['/plugins/smart-second-brain/' +](https://github.com/nicobrauchtgit/obsidian-Smart2Brain/blob/7f9533cf90b3bfd218f38b2f8e3fbb6dc51464be/src/main.ts#L82)
Use `this.manifest.dir` instead.

[console.log('saving vector store data');](https://github.com/nicobrauchtgit/obsidian-Smart2Brain/blob/7f9533cf90b3bfd218f38b2f8e3fbb6dc51464be/src/main.ts#L90), [console.log('saved vector store data');](https://github.com/nicobrauchtgit/obsidian-Smart2Brain/blob/7f9533cf90b3bfd218f38b2f8e3fbb6dc51464be/src/main.ts#L93)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[this.app.metadataCache.on('changed', async (file: TFile) => {](https://github.com/nicobrauchtgit/obsidian-Smart2Brain/blob/7f9533cf90b3bfd218f38b2f8e3fbb6dc51464be/src/main.ts#L137)
This event is not registered.

[private autoSaveTimer: NodeJS.Timeout;](https://github.com/nicobrauchtgit/obsidian-Smart2Brain/blob/7f9533cf90b3bfd218f38b2f8e3fbb6dc51464be/src/main.ts#L67)
Use a regular number for the type, and use the `window.setTimeout` / `window.clearTimeout` functions where this number is used.

["excludeff": "Exclude Files and Folders",](https://github.com/nicobrauchtgit/obsidian-Smart2Brain/blob/7f9533cf90b3bfd218f38b2f8e3fbb6dc51464be/src/lang/en.json#L3-L5)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[const response = await fetch(get(plugin).data.ollamaGenModel.baseUrl + '/api/tags');](https://github.com/nicobrauchtgit/obsidian-Smart2Brain/blob/7f9533cf90b3bfd218f38b2f8e3fbb6dc51464be/src/controller/Ollama.ts#L18)
Use `requestUrl` instead of fetch here.

[clipboard.writeText(messageText);](https://github.com/nicobrauchtgit/obsidian-Smart2Brain/blob/7f9533cf90b3bfd218f38b2f8e3fbb6dc51464be/src/controller/Messages.ts#L108)
Use the browser based clipboard API instead of the electron one: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API

Together with the change above, the plugin should be mobile compatible then.

**Comment by nicobrauchtgit** [comment]
@joethei we are using fetch to enable streaming responses since we couldn't figure out how to return a ReadableStream object with the requestUrl function. Do you know if it is possible to stream responses with requestUrl?

**Comment by nicobrauchtgit** [comment]
@joethei all other changes are implemented now :)

**Pull request merged**
