### PR TITLE
Add plugin: Graph Link Types

### PR DESCRIPTION
**Pull request by natefrisch01**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [https://github.com/natefrisch01/Graph-Link-Types](https://github.com/natefrisch01/Graph-Link-Types)

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by natefrisch01** [comment]
"Remember to add a comma after the closing brace, }, of the previous entry." from [https://docs.obsidian.md/Plugins/Releasing/Submit+your+plugin](https://docs.obsidian.md/Plugins/Releasing/Submit+your+plugin) lead to the automated check failing, so I removed the comma.

**Comment by natefrisch01** [comment]
@joethei when you do end up taking a look at this, let me know if you have any suggestions for improvement! Working with Obsidian's graph-view seems to requires some pretty hacky solutions, but I did my best to make them safe by adding interfaces, waiting after a layout change to look for the renderer, etc. But perhaps you have some tricks to make it as reliable as possible - thanks for your time!

**Comment by joethei** [comment]
You should move all code files into a separate `src` folder, that makes it easier to review and maintain.

["description": "Link types for Obsidian graph view.",](https://github.com/natefrisch01/Graph-Link-Types/blob/04a66ab91c327a44fa2201aa797c137fdaecffdf/manifest.json#L6)
You don't need to mention Obsidian here.

[console.error("Dataview plugin is not available.");](https://github.com/natefrisch01/Graph-Link-Types/blob/04a66ab91c327a44fa2201aa797c137fdaecffdf/main.ts#L19)
This should also be shown in a notice to the user, not many users will open the console to read the error message (and on mobile it's more complicated to open it)

As for your issue with windows, you need to listen to the `window-open` event.

**Comment by natefrisch01** [comment]
@joethei All fixes (window event, regroup the code into to a source folder, and change description) are present in new release 0.2.4. Thanks!

**Comment by liamcain** [comment]
> To use the Graph Link Types plugin, ensure the [Dataview](https://blacksmithgu.github.io/obsidian-dataview/) plugin is installed in Obsidian

I don't see why this plugin requires dataview. You should also listen for the metadata change events built-in to Obsidian so that it can Natively support properties and not require DV.

**Pull request merged**
