### PR TITLE
Add Quip plugin.

### PR DESCRIPTION
**Pull request by sblakey**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/sblakey/obsidian-quip

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
I would recommend moving all the TypeScript files in a seperate `src` folder, as that makes it easier to review and work with them.

[// Remember to rename these classes and interfaces!](https://github.com/sblakey/obsidian-quip/blob/830445c366ba806f9c164c647494bf76e573587b/main.ts#L6)
Can be removed

[checkCallback](https://github.com/sblakey/obsidian-quip/blob/830445c366ba806f9c164c647494bf76e573587b/main.ts#L23)
You are not returning anything if there is no active markdown view.

[id: 'quip-publish-html',](https://github.com/sblakey/obsidian-quip/blob/830445c366ba806f9c164c647494bf76e573587b/main.ts#L21)
You don't need to prefix your command id with your plugin name, Obsidian will do that automatically.

[console.log(html);](https://github.com/sblakey/obsidian-quip/blob/830445c366ba806f9c164c647494bf76e573587b/main.ts#L69)
[console.log(html);](https://github.com/sblakey/obsidian-quip/blob/830445c366ba806f9c164c647494bf76e573587b/main.ts#L85)
[console.log("Settings", this.settings);](https://github.com/sblakey/obsidian-quip/blob/830445c366ba806f9c164c647494bf76e573587b/main.ts#L101)
Remove this.

[console.log(error);](https://github.com/sblakey/obsidian-quip/blob/830445c366ba806f9c164c647494bf76e573587b/main.ts#L75)
Would recommend using `console.error` instead.

[console.log("Secret path", secret_path);](https://github.com/sblakey/obsidian-quip/blob/830445c366ba806f9c164c647494bf76e573587b/quipapi.ts#L111)
[console.log("To prepend", prepend_html);](https://github.com/sblakey/obsidian-quip/blob/830445c366ba806f9c164c647494bf76e573587b/quipapi.ts#L116)
[console.log("Fragment from Quip", dom);](https://github.com/sblakey/obsidian-quip/blob/830445c366ba806f9c164c647494bf76e573587b/quipapi.ts#L119)
Remove this

[span.innerHTML = '';](https://github.com/sblakey/obsidian-quip/blob/830445c366ba806f9c164c647494bf76e573587b/renderer.ts#L31-L32)
[Avoid using `innerHTML` and `outHTML`](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#avoid-innerhtml-outerhtml-and-insertadjacenthtml)

[const adapter = plugin.app.vault.adapter as FileSystemAdapter;](https://github.com/sblakey/obsidian-quip/blob/830445c366ba806f9c164c647494bf76e573587b/renderer.ts#L28)
[Prefer the Vault API over the Adapter API](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#prefer-the-vault-api-over-the-adapter-api)
This will also allow this code to work on mobile.


[console.log(`Token: ${value}`);](https://github.com/sblakey/obsidian-quip/blob/830445c366ba806f9c164c647494bf76e573587b/settings.ts#L43)
[console.log(`Hostname: ${value}`);](https://github.com/sblakey/obsidian-quip/blob/830445c366ba806f9c164c647494bf76e573587b/settings.ts#L54)
[console.log(`Remove YAML: ${value}`);](https://github.com/sblakey/obsidian-quip/blob/830445c366ba806f9c164c647494bf76e573587b/settings.ts#L64)
[console.log(`Add Link: ${value}`);](https://github.com/sblakey/obsidian-quip/blob/830445c366ba806f9c164c647494bf76e573587b/settings.ts#L74)
[console.log(`Add Link: ${value}`);](https://github.com/sblakey/obsidian-quip/blob/830445c366ba806f9c164c647494bf76e573587b/settings.ts#L84)
Remove this

**Comment by sblakey** [comment]
Thank you for the feedback, @joethei 

I have completed and tested the changes you requested, and am ready for a second pass when you get a chance.

**Comment by liamcain** [comment]
- [This project uses Typescript to provide type checking and documentation](https://github.com/sblakey/obsidian-quip/blob/7af2e00002226b6e9e93b8296f1ebedf6dfc7cd5/README.md#L5) remove this from the README, it's not about your plugin, so it's a bit confusing.
- [markdownView.file](https://github.com/sblakey/obsidian-quip/blob/7af2e00002226b6e9e93b8296f1ebedf6dfc7cd5/src/main.ts#L47) I recommend using [`getActiveFile`](https://github.com/obsidianmd/obsidian-api/blob/38dd22168d2925086371bfc59e36fd9121527a39/obsidian.d.ts#L4146) instead. It handles a couple other small edge cases, like if the command is fired when the file explorer is focused, for example. It also means you'll be able to use the command on files embedded in a Canvas :)
- [var](https://github.com/sblakey/obsidian-quip/blob/7af2e00002226b6e9e93b8296f1ebedf6dfc7cd5/src/quipapi.ts#L121) I recommend you change all instances of `var` to either `const` or `let`. `var` has function-level scope, so it can easily lead to bugs if you're not careful. Here's a pretty good guide with examples of why not to use `var`: [why `var` is obsolete](https://javascript.plainenglish.io/4-reasons-why-var-is-considered-obsolete-in-modern-javascript-a30296b5f08f)
- [standaloneHTML](https://github.com/sblakey/obsidian-quip/blob/7af2e00002226b6e9e93b8296f1ebedf6dfc7cd5/src/renderer.ts#L117) looks like this is unused.

**Comment by sblakey** [comment]
I have implemented the changes recommended by @liamcain

**Pull request merged**
