### PR TITLE
Add plugin: historica

### PR DESCRIPTION
**Pull request by nhannht**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Please follow the pull request template.
I just updated your original comment here with the template, please fill it.

**Comment by joethei** [comment]
["description": "Intelligence generates timeline from your content",](https://github.com/nhannht/obsidian-historica/blob/d8cac4d9dfe93ba35083018f712797baf80c0fa8/manifest.json#L6)
"Intelligence" is the wrong word here.

[async function resolveConfigFile(file:string){](https://github.com/nhannht/obsidian-historica/blob/d8cac4d9dfe93ba35083018f712797baf80c0fa8/main.ts#L13-L35)
Please use loadData() and saveData from the Obsidian API for storing your data (https://github.com/obsidianmd/obsidian-api/blob/249eb773347588f4e9fec7c600e1904cd9240fcb/obsidian.d.ts#L2982). This allows the data to be compatible with syncing platforms like Obsidian Sync, an example can be found in the sample plugin.
It also should allow for your plugin to work on mobile.

**Comment by nhannht** [comment]
Wow, thank you very much, I just gave up about how to make my plugin work on mobile because I have `fs` and `path` from node api. 


> [async function resolveConfigFile(file:string){](https://github.com/nhannht/obsidian-historica/blob/d8cac4d9dfe93ba35083018f712797baf80c0fa8/main.ts#L13-L35) Please use loadData() and saveData from the Obsidian API for storing your data ([obsidianmd/obsidian-api@`249eb77`/obsidian.d.ts#L2982](https://github.com/obsidianmd/obsidian-api/blob/249eb773347588f4e9fec7c600e1904cd9240fcb/obsidian.d.ts#L2982)). This allows the data to be compatible with syncing platforms like Obsidian Sync, an example can be found in the sample plugin. It also should allow for your plugin to work on mobile.

**Comment by nhannht** [comment]
My english is not good (I am also not using grammar checking tool because it so heavy on my poor machine). Can you suggest some better candidates for the descriptions. I will be proud if using your suggestion for my product. 

> ["description": "Intelligence generates timeline from your content",](https://github.com/nhannht/obsidian-historica/blob/d8cac4d9dfe93ba35083018f712797baf80c0fa8/manifest.json#L6) "Intelligence" is the wrong word here.

**Comment by joethei** [comment]
"Intelligently"

**Pull request merged**
