### PR TITLE
Add plugin: Messager

### PR DESCRIPTION
**Pull request by xiaotianhu**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:https://github.com/xiaotianhu/obsidian-messager

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by xiaotianhu** [comment]
Hello bro.Thanks for your time.
I'v pushed my changes: 
https://github.com/xiaotianhu/obsidian-messager/commit/210e45c25cf13be142f0d1d175af081bb59dfd64

And also modified my website https://wechatobsidian.com/. 

Looking forward to your feedback.

**Comment by joethei** [comment]
Update the icons in the screenshot on the website please.
(And in that WeChat account if you haven't already)

**Comment by xiaotianhu** [comment]
Hi bro, updated the website,also the WeChat account.
@joethei 
image

**Comment by xiaotianhu** [comment]
Hello bro, is everything ok? @joethei

**Comment by xiaotianhu** [comment]
Hey buddy, several days have passed. I wanted to check if there has been any progress. Do my changes meet the requirements? 
This plugin is my first attempt as an independent developer, and it is very important to me. I really hope it can be published on the market. Thank you very much for your help.
@joethei

**Comment by joethei** [comment]
[Api key](https://github.com/xiaotianhu/obsidian-messager/blob/210e45c25cf13be142f0d1d175af081bb59dfd64/src/lang.ts#L4), ["Get Api key from wxob.pipebox.pro";](https://github.com/xiaotianhu/obsidian-messager/blob/210e45c25cf13be142f0d1d175af081bb59dfd64/src/lang.ts#L5), ["Enter your Api key";](https://github.com/xiaotianhu/obsidian-messager/blob/210e45c25cf13be142f0d1d175af081bb59dfd64/src/lang.ts#L6), ["Api key verify ok."](https://github.com/xiaotianhu/obsidian-messager/blob/210e45c25cf13be142f0d1d175af081bb59dfd64/src/lang.ts#L24), ["Api key verify err:";](https://github.com/xiaotianhu/obsidian-messager/blob/210e45c25cf13be142f0d1d175af081bb59dfd64/src/lang.ts#L25), ["Verify Api key"](https://github.com/xiaotianhu/obsidian-messager/blob/210e45c25cf13be142f0d1d175af081bb59dfd64/src/lang.ts#L27), ["Check whether Api key is valid";](https://github.com/xiaotianhu/obsidian-messager/blob/210e45c25cf13be142f0d1d175af081bb59dfd64/src/lang.ts#L28), ["Api key not found, user not exist.";](https://github.com/xiaotianhu/obsidian-messager/blob/210e45c25cf13be142f0d1d175af081bb59dfd64/src/lang.ts#L32), ["Api key";](https://github.com/xiaotianhu/obsidian-messager/blob/210e45c25cf13be142f0d1d175af081bb59dfd64/src/lang.ts#L43), [前往wxob.pipebox.pro获取Api key";](https://github.com/xiaotianhu/obsidian-messager/blob/210e45c25cf13be142f0d1d175af081bb59dfd64/src/lang.ts#L44), ["请输入Api key";](https://github.com/xiaotianhu/obsidian-messager/blob/210e45c25cf13be142f0d1d175af081bb59dfd64/src/lang.ts#L45), ["Api key 验证成功！"](https://github.com/xiaotianhu/obsidian-messager/blob/210e45c25cf13be142f0d1d175af081bb59dfd64/src/lang.ts#L63), ["Api key 验证失败:";](https://github.com/xiaotianhu/obsidian-messager/blob/210e45c25cf13be142f0d1d175af081bb59dfd64/src/lang.ts#L64), ["检查Api key";](https://github.com/xiaotianhu/obsidian-messager/blob/210e45c25cf13be142f0d1d175af081bb59dfd64/src/lang.ts#L66), ["测试Api key是否正确";](https://github.com/xiaotianhu/obsidian-messager/blob/210e45c25cf13be142f0d1d175af081bb59dfd64/src/lang.ts#L67)
It's written as `API`

["Message Plugin error:";](https://github.com/xiaotianhu/obsidian-messager/blob/210e45c25cf13be142f0d1d175af081bb59dfd64/src/lang.ts#L30), ["Message Plugin server response error:";](https://github.com/xiaotianhu/obsidian-messager/blob/210e45c25cf13be142f0d1d175af081bb59dfd64/src/lang.ts#L31), ["Message插件错误:](https://github.com/xiaotianhu/obsidian-messager/blob/210e45c25cf13be142f0d1d175af081bb59dfd64/src/lang.ts#L69), ["Message插件服务器错误:"](https://github.com/xiaotianhu/obsidian-messager/blob/210e45c25cf13be142f0d1d175af081bb59dfd64/src/lang.ts#L70)
That is not the plugin name, and remove `Plugin`

**Comment by xiaotianhu** [comment]
https://github.com/xiaotianhu/obsidian-messager/commit/260298fb7e940e5f9d416c5d249a889308511b3d

Hello, I've made the changes. Thank you for your advice and feedback. @joethei

**Pull request merged**
