### PR TITLE
add typing transformer plugin

### PR DESCRIPTION
**Pull request by aptend**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/aptend/typing-transformer-obsidian

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
- [x] I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
The plugin probably requires at least Obsidian 0.15 as the update to version 6.0 of the CodeMirror packages happened there.



Not using semicolons to end statements can lead to rare, hard to debug problems: <https://flaviocopes.com/javascript-automatic-semicolon-insertion/>

[ruleArea.settingEl.setAttribute("style", "display: grid; grid-template-columns: 1fr;")](https://github.com/aptend/typing-transformer-obsidian/blob/f8843aab346524d24999674c53c4c830c7a5a5ff/src/main.ts#L295-L296)
You should put those into your `styles.css` file and just add a class to the `settingEl`, making this available for themes to style.

**Comment by aptend** [comment]
@joethei Thanks for the reivew!

> The plugin probably requires at least Obsidian 0.15 as the update to version 6.0 of the CodeMirror packages happened there.

Now I develop this plugin on Obsidian 0.14.15 , and it works well on Mac and Windows. And it seems that I have on access to Obsidian 0.15…… so what should I do, set min app version 0.14.15 would be enough?

> Not using semicolons to end statements can lead to rare, hard to debug problems: https://flaviocopes.com/javascript-automatic-semicolon-insertion/

Fixed

> [ruleArea.settingEl.setAttribute("style", "display: grid; grid-template-columns: 1fr;")](https://github.com/aptend/typing-transformer-obsidian/blob/f8843aab346524d24999674c53c4c830c7a5a5ff/src/main.ts#L295-L296) You should put those into your `styles.css` file and just add a class to the `settingEl`, making this available for themes to style.

Fixed [.setClass("rules-text-area")](https://github.com/aptend/typing-transformer-obsidian/blob/c6dd0838bce56c0dd164438391c50b643c34ee6a/src/settings.ts#L76)

**Comment by joethei** [comment]
Okay if it works that is fine.
With version 0.15.0 there is a upgrade in the CM version Obsidian is using.
(0.19.x - > 6.0
A few API`s have changed as a result.
As I was not sure which one you tested on I left this warning.

**Comment by aptend** [comment]
I have set min app version 0.14.15 and issued a new version contains all updates. Any other suggestions?

**Comment by liamcain** [comment]
- [await init(wasmbin);](https://github.com/aptend/typing-transformer-obsidian/blob/9978096527b7b49e4f38739f1baa65c5a2d307a7/src/main.ts#L52) Plugin `onload` is a synchronous, so it should exit pretty quickly, is this call expensive? If it is, maybe we can defer the loading or wrap it in a setTimeout so it happens in it's own event loop

---

Otherwise, looks good to me!

**Comment by aptend** [comment]
This call boils down to `WebAssembly.instantiate()`, it costs 2ms on my Mac, while the whole `onload` costs 4ms. I guess it is acceptable for now? Anyway I will keep an eye on this, maybe I can optimize it in next version, thank you~

**Pull request merged**
