### PR TITLE
Add plugin: Super Duper Audio Recorder

### PR DESCRIPTION
**Pull request by madpin**
# I am submitting a new Community Plugin

## Repo URL

https://github.com/madpin/super-duper-audio-recorder
Link to my plugin:

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "A plugin to record audio directly within Obsidian.",](https://github.com/madpin/super-duper-audio-recorder/blob/bd4c12c374aaba16ec72a000a77840055e976c4f/manifest.json#L6)
Avoid including sentences like "This is a plugin for Obsidian that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[canvas {](https://github.com/madpin/super-duper-audio-recorder/blob/bd4c12c374aaba16ec72a000a77840055e976c4f/styles.css#L16-L20)
Please don't overwrite core styling in a plugin, add another class/data attribute so it only applies to your plugin.

[import { join } from 'path';  // Import the join function to handle file paths](https://github.com/madpin/super-duper-audio-recorder/blob/bd4c12c374aaba16ec72a000a77840055e976c4f/main.ts#L3)
Just join them with a simple slash `/`, that is valid across all operating systems when using the Obsidian API.
[const filePath = this.settings.saveFolder](https://github.com/madpin/super-duper-audio-recorder/blob/bd4c12c374aaba16ec72a000a77840055e976c4f/main.ts#L167-L171)
[Use `normalizePath` to clean up user defined paths](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+%60normalizePath()%60+to+clean+up+user-defined+paths)

[contentEl.createEl('h2', { text: 'Select Audio Input Device' });](https://github.com/madpin/super-duper-audio-recorder/blob/bd4c12c374aaba16ec72a000a77840055e976c4f/main.ts#L19), [contentEl.createEl('h2', { text: 'Select Audio Input Device' });](https://github.com/madpin/super-duper-audio-recorder/blob/bd4c12c374aaba16ec72a000a77840055e976c4f/main.ts#L19), [name: 'Pause Recording',](https://github.com/madpin/super-duper-audio-recorder/blob/bd4c12c374aaba16ec72a000a77840055e976c4f/main.ts#L63), [name: 'Resume Recording',](https://github.com/madpin/super-duper-audio-recorder/blob/bd4c12c374aaba16ec72a000a77840055e976c4f/main.ts#L69), [name: 'Select Audio Input Device',](https://github.com/madpin/super-duper-audio-recorder/blob/bd4c12c374aaba16ec72a000a77840055e976c4f/main.ts#L75), [this.addRibbonIcon('microphone', 'Start/Stop Recording', () => {](https://github.com/madpin/super-duper-audio-recorder/blob/bd4c12c374aaba16ec72a000a77840055e976c4f/main.ts#L80), [.setName('Recording Format')](https://github.com/madpin/super-duper-audio-recorder/blob/bd4c12c374aaba16ec72a000a77840055e976c4f/settings-tab.ts#L70), [.setName('Sample Rate')](https://github.com/madpin/super-duper-audio-recorder/blob/bd4c12c374aaba16ec72a000a77840055e976c4f/settings-tab.ts#L84), [.setName('Save Folder')](https://github.com/madpin/super-duper-audio-recorder/blob/bd4c12c374aaba16ec72a000a77840055e976c4f/settings-tab.ts#L99), [containerEl.createEl('h3', { text: 'File Naming' });](https://github.com/madpin/super-duper-audio-recorder/blob/bd4c12c374aaba16ec72a000a77840055e976c4f/settings-tab.ts#L119), [document.createElement('b').appendChild(document.createTextNode('File Prefix')),](https://github.com/madpin/super-duper-audio-recorder/blob/bd4c12c374aaba16ec72a000a77840055e976c4f/settings-tab.ts#L126), [.setName('File Prefix')](https://github.com/madpin/super-duper-audio-recorder/blob/bd4c12c374aaba16ec72a000a77840055e976c4f/settings-tab.ts#L136), [.setName('Audio Input Device')](https://github.com/madpin/super-duper-audio-recorder/blob/bd4c12c374aaba16ec72a000a77840055e976c4f/settings-tab.ts#L151), [).append(](https://github.com/madpin/super-duper-audio-recorder/blob/bd4c12c374aaba16ec72a000a77840055e976c4f/settings-tab.ts#L169-L198)

[containerEl.createEl('h2', { text: 'Audio Recorder Plus Settings' });](https://github.com/madpin/super-duper-audio-recorder/blob/bd4c12c374aaba16ec72a000a77840055e976c4f/settings-tab.ts#L62-L64)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)


[containerEl.createEl('h3', { text: 'Recording Settings' });](https://github.com/madpin/super-duper-audio-recorder/blob/bd4c12c374aaba16ec72a000a77840055e976c4f/settings-tab.ts#L66), [containerEl.createEl('h3', { text: 'File Naming' });](https://github.com/madpin/super-duper-audio-recorder/blob/bd4c12c374aaba16ec72a000a77840055e976c4f/settings-tab.ts#L119), [containerEl.createEl('h3', { text: 'Audio Input Device' });](https://github.com/madpin/super-duper-audio-recorder/blob/bd4c12c374aaba16ec72a000a77840055e976c4f/settings-tab.ts#L146), [containerEl.createEl('h3', { text: 'Documentation' });](https://github.com/madpin/super-duper-audio-recorder/blob/bd4c12c374aaba16ec72a000a77840055e976c4f/settings-tab.ts#L164-L165)
For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```

[containerEl.createEl('h3', { text: 'Recording Settings' });](https://github.com/madpin/super-duper-audio-recorder/blob/bd4c12c374aaba16ec72a000a77840055e976c4f/settings-tab.ts#L66)
[Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

**Comment by madpin** [comment]
Thanks a lot @joethei 
And sorry, this is my first plugin, and to be honest, heavily influenced by Claude.
I was just in need of a plugin like that, so that's my first time writing Js/Ts.

Again, thanks, and I hope to have solved all the problems.

**Comment by joethei** [comment]
The styling change was not done.

**Comment by madpin** [comment]
Shame on me, I had it removed, but then idk what happened.
I just removed it completely now, it should be good.

Thanks and sorry.

**Pull request merged**
