### PR TITLE
Add plugin: iCal

### PR DESCRIPTION
**Pull request by andrewbrereton**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/andrewbrereton/obsidian-to-ical-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[this.registerInterval(](https://github.com/andrewbrereton/obsidian-to-ical-plugin/blob/79be6b376b395cbd635b2601da1d5f1d55287f5d/src/ObsidianIcalPlugin.ts#L87-L93)
Remove this sample code.

[containerEl.createEl('h1', { text: 'Obsidian to iCal'});](https://github.com/andrewbrereton/obsidian-to-ical-plugin/blob/79be6b376b395cbd635b2601da1d5f1d55287f5d/src/ObsidianIcalPlugin.ts#L139-L142)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[return [...markdown.matchAll(this.taskRegExp)]](https://github.com/andrewbrereton/obsidian-to-ical-plugin/blob/79be6b376b395cbd635b2601da1d5f1d55287f5d/src/TaskFinder.ts#L14-L21)
Use the metadataCache instead to look for tasks, your current approach will have performance issues in larger vaults.

---

[import { DateTime } from "luxon";](https://github.com/andrewbrereton/obsidian-to-ical-plugin/blob/79be6b376b395cbd635b2601da1d5f1d55287f5d/src/Model/Task.ts#L3)
Instead of Luxon I would recommend using the `moment` library which is exported by the Obsidian API, this will create a smaller compiled source file.

**Comment by andrewbrereton** [comment]
Thanks for your feedback @joethei.

Your suggestions have been implemented.

https://github.com/andrewbrereton/obsidian-to-ical-plugin/compare/1.0.6...1.1.0

**Comment by andrewbrereton** [comment]
Hi @joethei, sorry to bump this one up. Is this plugin OK to merge now?

**Comment by andrewbrereton** [comment]
Hi @liamcain, is there any further feedback for this? Thanks.

**Comment by liamcain** [comment]
- [import * as path from "path";](https://github.com/andrewbrereton/obsidian-to-ical-plugin/blob/64b1f3589b6a00fe9955b8e6b57207464ea71e0d/src/FileClient.ts#L2) this is a nodejs import so it won't work on mobile. Obsidian will automatically normalize path separators, so just use "/" instead of path.sep here.

**Pull request merged**
