### PR TITLE
Add plugin: IMDb

### PR DESCRIPTION
**Pull request by aaachen**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/aaachen/IMDb-Obsidian/tree/main

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by aaachen** [comment]
> #### Hello!
> 
> **I found the following issues in your plugin submission**
> 
> **Warnings:**
> 
> ⚠️ Please don't use the word `Obsidian` in your plugin name since it's redundant and adds clutter to the plugin list.
> 
> This check was done automatically. Do NOT open a new PR for re-validation. Instead, to trigger this check again, make a change to your PR and wait a few minutes, or close and re-open it.

Removed the [obsidian name from manifest](https://github.com/aaachen/IMDb-Obsidian/releases)

**Comment by aaachen** [comment]
> Thank you for your submission, an automated scan of your plugin code's revealed the following issues:
> 
> [[1](https://github.com/aaachen/IMDb-Obsidian/blob/f95d25b74cd695bcf499b56c958bb4c9b9d9d582/main.ts#L21)]:The command name should not include the plugin name.
> 
> Do NOT open a new PR for re-validation. Once you have pushed all of the required changes, the bot will reevaluate your PR within 6 hours. If you think some of these results are incorrect, please include `/skip` in your comment and the reason why you think the results are incorrect.

/skip

The plugin name is `IMDb`, which imo makes sense because the plugin is an IMDb integration (i.e. fetching data from IMDb to Obsidian), the command name is `IMDb Sync`, which just happens to contain the plugin name itself

imo this is a reasonable command name

**Comment by joethei** [comment]
[Copyright (c) 2022 aaachen](https://github.com/aaachen/IMDb-Obsidian/blob/f95d25b74cd695bcf499b56c958bb4c9b9d9d582/LICENSE.md#L3)
Update this.

["description": "Connect Obsidian to your IMDb.",](https://github.com/aaachen/IMDb-Obsidian/blob/f95d25b74cd695bcf499b56c958bb4c9b9d9d582/manifest.json#L6)
Remove "Obsidian" from the description.

[id: 'imdb-sync',](https://github.com/aaachen/IMDb-Obsidian/blob/f95d25b74cd695bcf499b56c958bb4c9b9d9d582/main.ts#L20)
Remove the `imdb` prefix.

[name: 'IMDb Sync',](https://github.com/aaachen/IMDb-Obsidian/blob/f95d25b74cd695bcf499b56c958bb4c9b9d9d582/main.ts#L21)
In the command pallete, hotkeys etc, this will show up as `IMBd: IMDb Sync`, remove `IMDb` from the command name.

[Suggest.ts](https://github.com/aaachen/IMDb-Obsidian/blob/f95d25b74cd695bcf499b56c958bb4c9b9d9d582/src/Suggest.ts)
The code in this file should no longer be used, implement a `AbstractInputSuggest` instead.

[containerEl.createEl('h3', { text: 'IMDb list sync' })](https://github.com/aaachen/IMDb-Obsidian/blob/f95d25b74cd695bcf499b56c958bb4c9b9d9d582/src/Settings.ts#L18-L23)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)


[containerEl.createEl('h4', { text: 'Lists' })](https://github.com/aaachen/IMDb-Obsidian/blob/f95d25b74cd695bcf499b56c958bb4c9b9d9d582/src/Settings.ts#L49), [listHeader.createEl('h5', { text: 'List' })](https://github.com/aaachen/IMDb-Obsidian/blob/f95d25b74cd695bcf499b56c958bb4c9b9d9d582/src/Settings.ts#L116)
For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```

**Comment by aaachen** [comment]
> [Copyright (c) 2022 aaachen](https://github.com/aaachen/IMDb-Obsidian/blob/f95d25b74cd695bcf499b56c958bb4c9b9d9d582/LICENSE.md#L3) Update this.
> 
> ["description": "Connect Obsidian to your IMDb.",](https://github.com/aaachen/IMDb-Obsidian/blob/f95d25b74cd695bcf499b56c958bb4c9b9d9d582/manifest.json#L6) Remove "Obsidian" from the description.
> 
> [id: 'imdb-sync',](https://github.com/aaachen/IMDb-Obsidian/blob/f95d25b74cd695bcf499b56c958bb4c9b9d9d582/main.ts#L20) Remove the `imdb` prefix.
> 
> [name: 'IMDb Sync',](https://github.com/aaachen/IMDb-Obsidian/blob/f95d25b74cd695bcf499b56c958bb4c9b9d9d582/main.ts#L21) In the command pallete, hotkeys etc, this will show up as `IMBd: IMDb Sync`, remove `IMDb` from the command name.
> 
> [Suggest.ts](https://github.com/aaachen/IMDb-Obsidian/blob/f95d25b74cd695bcf499b56c958bb4c9b9d9d582/src/Suggest.ts) The code in this file should no longer be used, implement a `AbstractInputSuggest` instead.
> 
> [containerEl.createEl('h3', { text: 'IMDb list sync' })](https://github.com/aaachen/IMDb-Obsidian/blob/f95d25b74cd695bcf499b56c958bb4c9b9d9d582/src/Settings.ts#L18-L23) [Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)
> 
> [containerEl.createEl('h4', { text: 'Lists' })](https://github.com/aaachen/IMDb-Obsidian/blob/f95d25b74cd695bcf499b56c958bb4c9b9d9d582/src/Settings.ts#L49), [listHeader.createEl('h5', { text: 'List' })](https://github.com/aaachen/IMDb-Obsidian/blob/f95d25b74cd695bcf499b56c958bb4c9b9d9d582/src/Settings.ts#L116) For section headings in settings use:
> 
> ```ts
> new Setting(containerEl).setName('name here').setHeading();
> ```

Updated

**Pull request merged**
