### PR TITLE
Add Jira Cloud plugin

### PR DESCRIPTION
**Pull request by OfficerHalf**
# I am submitting a new Community Plugin

This is basically a wrapper around the (MIT licensed) [Jira.js](https://github.com/MrRefactoring/jira.js) library. Issue data can be added to frontmatter or the plugin's API used with templater templates or any other plugin that allows executing arbitrary javascript. It requires an active Jira API key. Examples are given in the README.md.

## Repo URL

Link to my plugin: https://github.com/OfficerHalf/obsidian-jira-cloud

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_

  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[containerEl.createEl('h2', { text: 'Jira Cloud settings' });](https://github.com/OfficerHalf/obsidian-jira-cloud/blob/841590455f928e110bd977db82f3f9ec31a50175/src/settings.ts#L59)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)
[Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

[id: 'ojc-yaml-summarize',](https://github.com/OfficerHalf/obsidian-jira-cloud/blob/841590455f928e110bd977db82f3f9ec31a50175/src/commands/yaml.ts#L13)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

**Comment by OfficerHalf** [comment]
Addressed those as well as a few other changes:
- Don't use `innerHTML` for suggest modal
- Corrected the name of the API Key settings
- Added some examples to the repo
- Adjusted search to search both recent issues as well as all issues

**Comment by OfficerHalf** [comment]
Android tested and working.

**Comment by OfficerHalf** [comment]
Just wanted to give this a small bump. 👀 I know this repo is busier than ever. @joethei

**Comment by OfficerHalf** [comment]
Got rid of all those pesky merge commits. 👍 Let me know if there's anything else to be done here.

**Pull request merged**
