### PR TITLE
added obsidian-regex-replace

### PR DESCRIPTION
**Pull request by Gru80**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Gru80/obsidian-regex-replace

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/Gru80/obsidian-regex-replace/blob/3b89f675c038cc3708bd4a9677dd438ef22a510c/src/main.ts#L171
I would suggest just automatically detect whether the user has a selection instead of providing a toggle for it. If there's no selection then use full document.

https://github.com/Gru80/obsidian-regex-replace/blob/3b89f675c038cc3708bd4a9677dd438ef22a510c/src/main.ts#L173
Should store `editor.getValue` in a variable so you don't have to get it multiple times.

**Comment by Gru80** [comment]
Thanks a lot for the review! Since this is my first attempt of a valuable contribution in the domain of TypeScript/JavaScript any feedback is highly appreciated, I'll consider your suggestions accordingly.

**Comment by lishid** [comment]
No worries!

https://github.com/Gru80/obsidian-regex-replace/blob/aa742c1f578aee246099a684e532be3c506ad551/src/main.ts#L176
Here you are attempting a match, then a replace, based off the same regex - this means the code would have to run the regex twice. Instead, what you can do is to perform the replacement and test whether the final result is equal to the original text, and only call `setValue` if the result changed.

https://github.com/Gru80/obsidian-regex-replace/blob/aa742c1f578aee246099a684e532be3c506ad551/src/main.ts#L198
Here you are calling `.split()` twice, which is also double work for something that you can throw in a variable to reuse.

**Comment by Gru80** [comment]
any further steps needed from my side in order to proceed with the pull-request?

**Comment by lishid** [comment]
> https://github.com/Gru80/obsidian-regex-replace/blob/aa742c1f578aee246099a684e532be3c506ad551/src/main.ts#L176
Here you are attempting a match, then a replace, based off the same regex - this means the code would have to run the regex twice. Instead, what you can do is to perform the replacement and test whether the final result is equal to the original text, and only call setValue if the result changed.

I don't think you addressed this one, should be pretty easy to do.

**Comment by Gru80** [comment]
Thanks a lot for the quick response,
Actually I also had a look at the proposed change for the redundant regex-execution - but actually I'm afraid I'd loose some information when following the suggested approach:
Because I'm not using `match()` just for checking if there is _any_ occurance at all, but also to be able to inform the user how many replacements have been made (determined by the length of the array which is returned by `match()`). Since `replace()` just returns the new string with the replaced content, I think I would have no possibility to get information regarding the _number of performed replacements_ this way. And from the User-Interaction point of view I think it is helpfull to be informed about how many changes have been made.

**Comment by lishid** [comment]
Ah you're looking for `rresult.length`.

In this case, what you could do is to use the `replace(regex, callback)` syntax where in the callback you can increment a number and then return the `replaceString`. That should achieve your desired goal and only run the search once.

**Comment by Gru80** [comment]
splendid hint, thanks for that! I wasn't aware of the `replace`-signature with the callback-argument, that should indeed enable a more elegant solution with just one regex-execution - I'll check that out

**Pull request merged**
