### PR TITLE
New Plugin: Asana Sync

### PR DESCRIPTION
**Pull request by Maxymillion**
# I am submitting a new Community Plugin - Asana Sync 

## Repo URL

Link to my plugin:
[https://github.com/Maxymillion/asana-sync-plugin](https://github.com/Maxymillion/asana-sync-plugin)

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by liamcain** [comment]
- [200](https://github.com/Maxymillion/asana-sync-plugin/blob/5bdf6c6dd7baef6756a1963baeff2a44783e0d7c/src/main.ts#L118) this is a really aggressive interval to be reading the file contents line by line. I'm also not sure you really want to be doing this check in an interval. You don't even know if the file has been modified. It probably makes more sense to make the change in the following events:
- [`modify`](https://github.com/obsidianmd/obsidian-api/blob/009a10f196df551256a5894ea60fdf9ddaab19a1/obsidian.d.ts#L3706)
- [`editor-paste`](https://github.com/obsidianmd/obsidian-api/blob/38dd22168d2925086371bfc59e36fd9121527a39/obsidian.d.ts#L4247). Then also wrap your callback function in [debounce](https://github.com/obsidianmd/obsidian-api/blob/1b4f6e2e5753c8ac2d538bc5d55c38f228450cb2/obsidian.d.ts#L772)to make sure that it doesn't get called to frequently.
- [processFrontMatter](https://github.com/Maxymillion/asana-sync-plugin/blob/5bdf6c6dd7baef6756a1963baeff2a44783e0d7c/src/main.ts#L164) this isn't right. Why are you using processFrontMatter here?
- [this.testConnection](https://github.com/Maxymillion/asana-sync-plugin/blob/5bdf6c6dd7baef6756a1963baeff2a44783e0d7c/src/components/Settings/index.ts#L59) style nitpick but I suggest you don't mix promises with async/await. It's a bit awkward since you could just await the testConnection call instead of adding a then()

**Comment by bamsammich** [comment]
@Maxymillion is there possibility of these changes coming soon? Looking forward to using this plugin.

**Comment by Maxymillion** [comment]
@bamsammich, yes! I expect to finish the changes this week.

**Comment by bamsammich** [comment]
@Maxymillion is there an update on this plugin getting updated to be accepted into the community plugins list?

**Comment by Maxymillion** [comment]
> @Maxymillion is there an update on this plugin getting updated to be accepted into the community plugins list?

Changes are ready, needed to do a little bit of a rewrite and due to two other plugins I’ve had changes for it was a little delayed. This week the code will be added and a review will be requested 🙏

**Comment by liamcain** [comment]
Hi @Maxymillion, it looks like you archived the plugin repo. Does that mean you're no longer interested in it being submitted to the community plugin list? Would you like me to close this pull request?

**Comment by Maxymillion** [comment]
@liamcain, well I am reworking the plugin on another repo. I'd learned quite a bit from making a few other plugins and mostly needed to start over (for a clean codebase). I'll be creating another pull request when that one is finished. Thanks

**Comment by liamcain** [comment]
Oh okay, that's great to hear! I'm going to close this pull request then just to avoid confusion. But feel free to create a new pull request to point to the new repo whenever its ready for me to take a look.

**Pull request closed without merging**
