### PR TITLE
Add Import Foundry and Import JSON plug-ins

### PR DESCRIPTION
**Pull request by farling42**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugins:
https://github.com/farling42/obsidian-import-foundry
https://github.com/farling42/obsidian-import-json

## Release Checklist
- [X] I have tested the plugin on
  - [X]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/farling42/obsidian-import-foundry/blob/9949fd00009c4ef305e7ae3cfe5e71d25a22ab43/main.ts#L117
This fails to properly await for the results one at a time (it will run everything in parallel and ignore the process). Use a for loop here instead.

https://github.com/farling42/obsidian-import-foundry/blob/9949fd00009c4ef305e7ae3cfe5e71d25a22ab43/main.ts#L248
I highly suggest avoid mixing `async` `await` and the old callback style `.then()/.catch()` usage. Best to stick to the new async syntax.

**Comment by lishid** [comment]
https://github.com/farling42/obsidian-import-json/blob/6d038f40cb9ae7ad33dad7480f630ad3bded01b0/main.ts#L123
Same problem here.

**Comment by farling42** [comment]
Both plugins have been updated to remove foreach() and then() loops

**Comment by farling42** [comment]
> I noticed that one of your plugin has an `obsidian-` prefix in the ID and the other doesn't. I don't think it matters but may want to normalize that just for consistency.

Oh yeah. I forgot to remove that in the plugin information. I use it as a prefix for the repository name 😁

**Pull request merged**
