### PR TITLE
Add plugin: Swarnam

### PR DESCRIPTION
**Pull request by runofthemillgeek**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/runofthemillgeek/swarnam-obsidian

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by runofthemillgeek** [comment]
I've rebased my changes.

**Comment by joethei** [comment]
["minAppVersion": "0.15.0",](https://github.com/runofthemillgeek/swarnam-obsidian/blob/a8d46f559b310e939237cb317c219434ee983940/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

["description": "A no-frills web playground plugin for Obsidian.",](https://github.com/runofthemillgeek/swarnam-obsidian/blob/a8d46f559b310e939237cb317c219434ee983940/manifest.json#L6)
Don't use the word "Obsidian" in your description.

["fundingUrl": "https://dg.sangeeth.dev",](https://github.com/runofthemillgeek/swarnam-obsidian/blob/a8d46f559b310e939237cb317c219434ee983940/manifest.json#L9)
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link remove this.

[console.log({ text });](https://github.com/runofthemillgeek/swarnam-obsidian/blob/a8d46f559b310e939237cb317c219434ee983940/main.ts#L19), [console.log(console.log(new TextDecoder().decode(base64ToBytes(b64))));](https://github.com/runofthemillgeek/swarnam-obsidian/blob/a8d46f559b310e939237cb317c219434ee983940/main.ts#L21)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

**Comment by runofthemillgeek** [comment]
@joethei addressed the comments. Thanks for the excellent feedback and let me know if I missed anything or if any further thoughts.

**Comment by joethei** [comment]
The description has not been updated.

**Pull request closed without merging**
