### PR TITLE
Add plugin: Zen Mode

### PR DESCRIPTION
**Pull request by paperbenni**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
As the Hider plugin has no license, it's not possible for us to accept any forks as new plugins.

Sorry about that!

**Comment by paperbenni** [comment]
@joethei Hider now has a License. Can this be reopened?
https://github.com/kepano/obsidian-hider/commit/5049e9fb838897c14e523fc497d5f3c9ac8b57fa

**Comment by joethei** [comment]
Some screenshots in the README would be nice

[this.buttonContainer.style.position = "fixed";](https://github.com/paperbenni/obsidian-zenmode/blob/a6df3bc779181b7d998f3f3b94b4ee75c531a727/main.ts#L53-L56)
You should avoid assigning styles via JavaScript or in HTML and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets.

[.setDesc("Hides most UI Elements")](https://github.com/paperbenni/obsidian-zenmode/blob/a6df3bc779181b7d998f3f3b94b4ee75c531a727/main.ts#L159)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by paperbenni** [comment]
> Some screenshots in the README would be nice
> 
> [this.buttonContainer.style.position = "fixed";](https://github.com/paperbenni/obsidian-zenmode/blob/a6df3bc779181b7d998f3f3b94b4ee75c531a727/main.ts#L53-L56) You should avoid assigning styles via JavaScript or in HTML and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets.
> 
> [.setDesc("Hides most UI Elements")](https://github.com/paperbenni/obsidian-zenmode/blob/a6df3bc779181b7d998f3f3b94b4ee75c531a727/main.ts#L159) [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

Thanks for the feedback, I implemented the changes :)
https://github.com/paperbenni/obsidian-zenmode/compare/1.0.7...1.0.8

**Comment by joethei** [comment]
Could you rebase this PR?

**Pull request merged**
