### PR TITLE
Add plugin: Git Integration

### PR DESCRIPTION
**Pull request by noradroid**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/noradroid/obsidian-git-integration

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by noradroid** [comment]
Have switched to use instanceof check instead. Please verify again.

**Comment by noradroid** [comment]
Am not sure why it's still failing as I have deleted and recreated the 0.3.1 tag and release

**Comment by joethei** [comment]
What sets your plugin apart from the existing Git plugin?

[this.registerDomEvent(document, "click", (evt: MouseEvent) => {](https://github.com/noradroid/obsidian-git-integration/blob/689dd7b779208c5f12760082bdfaf4a1b8c5d2ee/src/main.ts#L111-L113)
Remove this sample code.

[id: "git-menu",](https://github.com/noradroid/obsidian-git-integration/blob/689dd7b779208c5f12760082bdfaf4a1b8c5d2ee/src/main.ts#L150), [id: "git-init",](https://github.com/noradroid/obsidian-git-integration/blob/689dd7b779208c5f12760082bdfaf4a1b8c5d2ee/src/main.ts#L160), [id: "git-commit",](https://github.com/noradroid/obsidian-git-integration/blob/689dd7b779208c5f12760082bdfaf4a1b8c5d2ee/src/main.ts#L176), [id: "git-sync",](https://github.com/noradroid/obsidian-git-integration/blob/689dd7b779208c5f12760082bdfaf4a1b8c5d2ee/src/main.ts#L186)
Remove the `git-` prefix, it's not needed.

[name: "Open init repository modal",](https://github.com/noradroid/obsidian-git-integration/blob/689dd7b779208c5f12760082bdfaf4a1b8c5d2ee/src/main.ts#L161), [name: "Open commit changes modal",](https://github.com/noradroid/obsidian-git-integration/blob/689dd7b779208c5f12760082bdfaf4a1b8c5d2ee/src/main.ts#L177)
The "Open ... modal" part of the command names should be removed.

[statusBarItemEl.setText("Git Integration Active");](https://github.com/noradroid/obsidian-git-integration/blob/689dd7b779208c5f12760082bdfaf4a1b8c5d2ee/src/main.ts#L197)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by noradroid** [comment]
@joethei thanks for the detailed review!

> What sets your plugin apart from the existing Git plugin?

This plugin aims to provide a simple interface for just the basic functionalities required to backup a new / existing git repository - changing remote, making commits and push functionalities.

Compared to existing plugins:
1. Git: bundled with too many features and it was difficult to find what I really needed
2. Yet Another Obsidian Synchronizer: simple but does not support initialising a new repository, only viable for vaults pre-cloned from remote

> 
> [this.registerDomEvent(document, "click", (evt: MouseEvent) => {](https://github.com/noradroid/obsidian-git-integration/blob/689dd7b779208c5f12760082bdfaf4a1b8c5d2ee/src/main.ts#L111-L113) Remove this sample code.
> 
> [id: "git-menu",](https://github.com/noradroid/obsidian-git-integration/blob/689dd7b779208c5f12760082bdfaf4a1b8c5d2ee/src/main.ts#L150), [id: "git-init",](https://github.com/noradroid/obsidian-git-integration/blob/689dd7b779208c5f12760082bdfaf4a1b8c5d2ee/src/main.ts#L160), [id: "git-commit",](https://github.com/noradroid/obsidian-git-integration/blob/689dd7b779208c5f12760082bdfaf4a1b8c5d2ee/src/main.ts#L176), [id: "git-sync",](https://github.com/noradroid/obsidian-git-integration/blob/689dd7b779208c5f12760082bdfaf4a1b8c5d2ee/src/main.ts#L186) Remove the `git-` prefix, it's not needed.
> 
> [name: "Open init repository modal",](https://github.com/noradroid/obsidian-git-integration/blob/689dd7b779208c5f12760082bdfaf4a1b8c5d2ee/src/main.ts#L161), [name: "Open commit changes modal",](https://github.com/noradroid/obsidian-git-integration/blob/689dd7b779208c5f12760082bdfaf4a1b8c5d2ee/src/main.ts#L177) The "Open ... modal" part of the command names should be removed.
> 
> [statusBarItemEl.setText("Git Integration Active");](https://github.com/noradroid/obsidian-git-integration/blob/689dd7b779208c5f12760082bdfaf4a1b8c5d2ee/src/main.ts#L197) [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

Have made changes based on the comments as well.

**Pull request merged**
