### PR TITLE
Add Gitlab Issues plugin

### PR DESCRIPTION
**Pull request by benr77**
Add new community plugin, which can import issues from Gitlab into Obsidian.

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/benr77/obsidian-gitlab-issues

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["author": "Ben Roberts <ben@headsnet.com>",](https://github.com/benr77/obsidian-gitlab-issues/blob/76a09d20f4357b5dd928c71a2ae55f06d434127f/manifest.json#L7)
Do you want your email address to be that public?
It will be shown on <https://obsidian.md/plugins> and in the sidebar of the community plugins tab.

[normalize](https://github.com/benr77/obsidian-gitlab-issues/blob/76a09d20f4357b5dd928c71a2ae55f06d434127f/src/path-normalizer.ts#L3)
The Obsidian API provides [`normalizePath`](https://github.com/obsidianmd/obsidian-api/blob/b9bde9e32c007eb28c0fd632cf2c42b01dfd022a/obsidian.d.ts#L2301) for this.

[fetch](https://github.com/benr77/obsidian-gitlab-issues/blob/76a09d20f4357b5dd928c71a2ae55f06d434127f/src/gitlab-api.ts#L9)
The Obsidian API provides ['requestUrl'](https://github.com/obsidianmd/obsidian-api/blob/b9bde9e32c007eb28c0fd632cf2c42b01dfd022a/obsidian.d.ts#L2744) for this.
You can run into CORS issues with `fetch`.

[DataAdapter](https://github.com/benr77/obsidian-gitlab-issues/blob/76a09d20f4357b5dd928c71a2ae55f06d434127f/src/filesystem.ts#L8)
Try to not use that API if possible: <https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#prefer-the-vault-api-over-the-adapter-api>

[/.obsidian/](https://github.com/benr77/obsidian-gitlab-issues/blob/76a09d20f4357b5dd928c71a2ae55f06d434127f/src/filesystem.ts#L59)
That path is not guaranteed, users can overwrite it in "Settings > About".
You can read that setting with `app.vault.configDir`

**Comment by benr77** [comment]
Hello @joethei. Thanks for your helpful pointers. I have now pushed the changes to the master branch of my plugin repository. Please can you review again.

Thanks

**Comment by liamcain** [comment]
- [window.clearInterval(this.startupTimeout);](https://github.com/benr77/obsidian-gitlab-issues/blob/5ffd9ef903e7e07b809a5ab6cbee50c9c7a44f2f/src/main.ts#L59-L60) I think you meant to use `window.clearTimeout` here. You have a timeout and not an interval.

**Comment by benr77** [comment]
> Hi! Sorry for such a long delay. This pull request got buried on the last page of our ever growing list of plugins and I didn't realize it was waiting on me to take a look no_mouth

No problem - thanks for your efforts!

> 
> Everything LGTM, just found a small nit but nothing to stop this from going in.
> 
> * [window.clearInterval(this.startupTimeout);](https://github.com/benr77/obsidian-gitlab-issues/blob/5ffd9ef903e7e07b809a5ab6cbee50c9c7a44f2f/src/main.ts#L59-L60) I think you meant to use `window.clearTimeout` here. You have a timeout and not an interval.

This is now fixed in the latest release.

**Pull request merged**
