### PR TITLE
Add 'Custom Classes' plugin

### PR DESCRIPTION
**Pull request by LilaRest**
# I am submitting a new Community Plugin

## Repo URL
Link to my plugin: https://github.com/LilaRest/obsidian-custom-classes

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows (should work)
  - [x]  macOS (should work)
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lishid** [comment]
If you just changed your plugin ID, remember to change it in the manifest.json in your repo and your latest GitHub release.

**Comment by LilaRest** [comment]
> If you just changed your plugin ID, remember to change it in the manifest.json in your repo and your latest GitHub release.

Thanks for your review. I've tried to change the ID after reading the bot's recommendation :
> :warning: Please don't use the word obsidian in the plugin ID. The ID is used for your plugin's folder so keeping it short and simple avoids clutter and helps with sorting.

But finally I've understood that it would also imply changing the ID in `manifest.json` and reverted the change in [this commit](https://github.com/obsidianmd/obsidian-releases/pull/1576/commits/4f50b7ece38dd675aebd9895a7e34076c7f34ffe).

**Comment by lishid** [comment]
Correct, you should change it in your manifest.json as well for the change to fully take effect. Once you change it there and upload the latest to your github release you can come back and update your PR.

**Comment by LilaRest** [comment]
> Correct, you should change it in your manifest.json as well for the change to fully take effect. Once you change it there and upload the latest to your github release you can come back and update your PR.

Okay ! Should be done in the next hours.

**Comment by LilaRest** [comment]
@lishid I've updated the ID in both `manifest.json` and `community-plugins.json` files. It seems that the PR meets all the bot's recommendations now. 

Do you see any additional thing to improve ? or are we ready to merge ? :slightly_smiling_face:

**Comment by LilaRest** [comment]
@lishid @joethei Any news ? :)

I've continued to work on the plugin those last weeks, it is now pretty stable and well documented.

**Comment by joethei** [comment]
I will review this plugin tomorrow.
Sorry for the delay, we are pretty busy with the next Obsidian release, and review community plugins in submission order.

**Comment by LilaRest** [comment]
> I will review this plugin tomorrow. Sorry for the delay, we are pretty busy with the next Obsidian release, and review community plugins in submission order.

@joethei Oh yes I can understand that. Thanks for your quick answer in such a situation ! :slightly_smiling_face:

**Pull request merged**
