### PR TITLE
Add `extended-context-menu` Plugin

### PR DESCRIPTION
**Pull request by phibr0**
# [x] I am submitting a new Community Plugin

## Repo URL

https://github.com/phibr0/obsidian-extended-context-menu

## Release Checklist

- [x] I have tested this on Windows, Linux _(if applicable)_
- [x] Github release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - `styles.css` _(optional)_
- [x] Github release name matches the exact version number specified in your manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.

### CODE REVIEW

**Review by mgmeyers — COMMENTED** [review]
I'm super excited for this, @phibr0! A couple of things I noticed:

---

I see you're unregistering the context menu handler now. One thing you'll need to update to get this to work is: https://github.com/phibr0/obsidian-extended-context-menu/blob/master/src/main.ts#L16-L18

Should be

```
cm.on('contextmenu', this.handleContextMenu);
```

also, since `handleContextMenu` references `this`, you may need to convert it to an arrow funtion:

```
private handleContextMenu = (instance: CodeMirror.Editor, e: MouseEvent) => {
```

---

Not a big deal, but you could improve perf here by making `setting.states` an object instead of an Array. https://github.com/phibr0/obsidian-extended-context-menu/blob/master/src/main.ts#L105

That way you could do a direct lookup `this.settings.states[getID(entry.pluginName, entry.name)]`. You may also want to handle the case where the state for a given entry doesn't exist in settings.

**Comment by phibr0** [comment]
> You may also want to handle the case where the state for a given entry doesn't exist in settings.

Hmm, but if it doesn't exist yet it will be created while it's being registered in the `registerCommand` Method.

**Comment by phibr0** [comment]
I fixed the unloading, it should now work correctly

**Comment by mgmeyers** [comment]
> Hmm, but if it doesn't exist yet it will be created while it's being registered in the `registerCommand` Method.

Ah! Didn't notice this. 👍

**Review by mgmeyers — APPROVED** [review]

**Comment by lishid** [comment]
LGTM. We will be implementing similar functionality shortly, but I can have this merged meanwhile.

**Pull request merged**
