### PR TITLE
Add Flowershow plugin

### PR DESCRIPTION
**Pull request by olayway**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/datopian/obsidian-flowershow

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by olayway** [comment]
@joethei Can you help me figure out why the validation fails? 🙂

**Comment by Lisandra-dev** [comment]
Your plugin seems to be private (i have 404 error)

**Comment by olayway** [comment]
@Lisandra-dev you're right... 🤦‍♀️ Thank you for the hint!

**Comment by olayway** [comment]
@Lisandra-dev do you have an idea what may be the issue now? 😅

**Comment by joethei** [comment]
That's something that I'll adjust in the validation script.

[callback: async () => {](https://github.com/datopian/obsidian-flowershow/blob/1701f3606978014848a2a3f8bcb8c7094d1b9807/main.ts#L63)
You should use a [`checkCallback`](https://docs.obsidian.md/Plugins/User+interface/Commands#Conditional+commands), the command will only be available if there is a note then.

[const content = await this.vault.cachedRead(this.file);](https://github.com/datopian/obsidian-flowershow/blob/1701f3606978014848a2a3f8bcb8c7094d1b9807/src/ObsidianFrontMatterEngine.ts#L44)
Since you are writing back to the file you should use `read` instead, as `cachedRead` might be slightly out of date.
An even better option is to use the new [`processFrontMatter`](https://github.com/obsidianmd/obsidian-api/blob/master/CHANGELOG.md#new-metadata-api) API.

[const headerContainer = this.modal.contentEl.createEl("div", { attr: { style: "display: flex; justify-content: space-between; margin-bottom: 10px; align-items:center" } });](https://github.com/datopian/obsidian-flowershow/blob/1701f3606978014848a2a3f8bcb8c7094d1b9807/src/PublishStatusModal.ts#L61-L65)
You should avoid assigning styles via JavaScript or in HTML and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets

[this.publishedList.innerHTML = publishedNotes.map(file => `<li>${file.path}</li>`).join("");](https://github.com/datopian/obsidian-flowershow/blob/1701f3606978014848a2a3f8bcb8c7094d1b9807/src/PublishStatusModal.ts#L103)
[Avoid using `innerHTML`](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%60innerHTML%60%2C+%60outerHTML%60+and+%60insertAdjacentHTML%60)

[await axios.get("https://raw.githubusercontent.com/obsidianmd/obsidian-releases/master/community-css-themes.json")](https://github.com/datopian/obsidian-flowershow/blob/1701f3606978014848a2a3f8bcb8c7094d1b9807/src/SettingView.ts#L237)
Use the `requestUrl` function from the Obsidian API instead.

**Comment by lishid** [comment]
The validation checks if the submitter (@olayway) is part of the organization (datopian). You can solve this by simply joining the org as a public member: https://github.com/orgs/datopian/people

**Comment by marcusolsson** [comment]
- https://github.com/datopian/obsidian-flowershow/blob/2de12944092b7828072f8a77272429238958ffd2/main.ts#L37
  I recommend that you use imperative verbs for the tooltip, for example "Publish to Flowershow".
- https://github.com/datopian/obsidian-flowershow/blob/2de12944092b7828072f8a77272429238958ffd2/main.ts#L44
  Limit console logging if you can. Only log if you believe the end user will benefit, for example if an error occurred. Avoid logging normal behavior.
- https://github.com/datopian/obsidian-flowershow/blob/2de12944092b7828072f8a77272429238958ffd2/main.ts#L62
  https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI

**Comment by olayway** [comment]
@marcusolsson Thank you for your review! I've just pushed the updates as per your suggestions (+ cleaned up some other parts). Here are the relevant commits:
1., 3. https://github.com/datopian/obsidian-flowershow/commit/7e60a696f8d274aa7e33bbebf45582ac0995bc68
https://github.com/datopian/obsidian-flowershow/commit/cecc04dd852c5db7c31d5af1c0b79809944822ec
2. https://github.com/datopian/obsidian-flowershow/commit/72e8155b276e6e9500b5662d6a49eb43d657bf4f

Let me know if there is anything else I should fix.

**Comment by marcusolsson** [comment]
Looks good to me! Would you mind resolving the conflicts, and I'll merge this right away?

**Pull request merged**
