### PR TITLE
Add plugin: MostUsed

### PR DESCRIPTION
**Pull request by levi-ivel**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/levi-ivel/MostUsed

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["author": "Obsidian",](https://github.com/levi-ivel/MostUsed/blob/4323685b6f987d80c13c80e450e595c57d901faa/manifest.json#L7)
Update this.

["fundingUrl": "",](https://github.com/levi-ivel/MostUsed/blob/4323685b6f987d80c13c80e450e595c57d901faa/manifest.json#L9)
If you don't have one, remove this line.

[this.addRibbonIcon('document', 'Show Most Used Words Graph', async () => {](https://github.com/levi-ivel/MostUsed/blob/4323685b6f987d80c13c80e450e595c57d901faa/main.ts#L12), [name: 'Show Most Used Words List',](https://github.com/levi-ivel/MostUsed/blob/4323685b6f987d80c13c80e450e595c57d901faa/main.ts#L18)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[this.addRibbonIcon('document', 'Show Most Used Words Graph', async () => {](https://github.com/levi-ivel/MostUsed/blob/4323685b6f987d80c13c80e450e595c57d901faa/main.ts#L12)
It's not a graph, it's a list you are showing.

[this.createdEventListener = this.handleFileCreation.bind(this);](https://github.com/levi-ivel/MostUsed/blob/4323685b6f987d80c13c80e450e595c57d901faa/main.ts#L7-L8), 
[if (this.createdEventListener) {](https://github.com/levi-ivel/MostUsed/blob/4323685b6f987d80c13c80e450e595c57d901faa/main.ts#L88-L91)
This can be removed, and it should just be this:
```ts
this.registerEvent(this.app.vault.on('create', this.handleFileCreation));
```
Also, it's not even used.

[async showMostUsedWordsList() {](https://github.com/levi-ivel/MostUsed/blob/4323685b6f987d80c13c80e450e595c57d901faa/main.ts#L29-L58)
This data should be cached somewhere, once the vault is big enough this will be very slow.

[createPopup(wordList: string[]) {](https://github.com/levi-ivel/MostUsed/blob/4323685b6f987d80c13c80e450e595c57d901faa/main.ts#L61-L85)
This UI looks very bad, it should either be a [View](https://docs.obsidian.md/Plugins/User+interface/Views), where the data updates live or a [Modal](https://docs.obsidian.md/Plugins/User+interface/Modals)

**Comment by levi-ivel** [comment]
Have made all requested changes. Refactored alot of the code though. If there are more issues, let me know.

**Comment by joethei** [comment]
You missed this one:
[this.addRibbonIcon('document', 'Show Most Used Words graph', async () => {](https://github.com/levi-ivel/MostUsed/blob/63c30919cf5a7deb8edf98ad3f90a234021ffd31/main.ts#L9), [name: 'Show Most Used Words graph',](https://github.com/levi-ivel/MostUsed/blob/63c30919cf5a7deb8edf98ad3f90a234021ffd31/main.ts#L15), [return 'Most Used Words';](https://github.com/levi-ivel/MostUsed/blob/63c30919cf5a7deb8edf98ad3f90a234021ffd31/main.ts#L123), [label: 'Word Count',](https://github.com/levi-ivel/MostUsed/blob/63c30919cf5a7deb8edf98ad3f90a234021ffd31/main.ts#L153)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

Also found a few more issues:
[backgroundColor: 'rgba(75, 192, 192, 0.2)',](https://github.com/levi-ivel/MostUsed/blob/63c30919cf5a7deb8edf98ad3f90a234021ffd31/main.ts#L155-L156)
These colors should not be hard-coded, they should use the CSS variables we provide,: https://docs.obsidian.md/Reference/CSS+variables/Foundations/Colors#Semantic+colors

[const leafTitle = this.app.workspace.activeLeaf?.getViewState().type;](https://github.com/levi-ivel/MostUsed/blob/63c30919cf5a7deb8edf98ad3f90a234021ffd31/main.ts#L172-L178)
`activeLeaf` is deprecated and should not be used.

**Comment by levi-ivel** [comment]
Done. If more changes are needed, let me know.

**Comment by joethei** [comment]
[this.addRibbonIcon('document', 'Show Most Used Words Graph', async () => {](https://github.com/levi-ivel/MostUsed/blob/905af1542d11b3e1bb61336df233ab61411a62b2/main.ts#L10), [name: 'Show Most Used Words Graph',](https://github.com/levi-ivel/MostUsed/blob/905af1542d11b3e1bb61336df233ab61411a62b2/main.ts#L16), [return 'Most Used Words Graph';](https://github.com/levi-ivel/MostUsed/blob/905af1542d11b3e1bb61336df233ab61411a62b2/main.ts#L124), [label: 'Most Used Words Graph',](https://github.com/levi-ivel/MostUsed/blob/905af1542d11b3e1bb61336df233ab61411a62b2/main.ts#L154), [const title = 'Most Used Words';](https://github.com/levi-ivel/MostUsed/blob/905af1542d11b3e1bb61336df233ab61411a62b2/main.ts#L172)
This is still not using sentence case.

[const leaf = this.app.workspace.getLeavesOfType('markdown').find(leaf => leaf.view instanceof MostUsedWordsView);](https://github.com/levi-ivel/MostUsed/blob/905af1542d11b3e1bb61336df233ab61411a62b2/main.ts#L170)
You are already in the correct view, no need to find the leaf this way, just remove this line and do `this.leaf` below.

**Comment by levi-ivel** [comment]
Should be all good now.

**Pull request merged**
