### PR TITLE
Add AWS S3 Sync plugin

### PR DESCRIPTION
**Pull request by daaru00**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/daaru00/obsidian-aws-s3-sync/

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
You can remove `obsidian` from the plugin id, it's unnecessary.

[this.app.vault.on('create', this.onLocalFileChanged.bind(this))](https://github.com/daaru00/obsidian-aws-s3-sync/blob/0587dc95a78094f6e77ec9053e3ae4e134c0471b/src/main.ts#L44-L47)
Register these events with `this.registerEvent(<your code>)´
<https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#resource-management>

[Cloud not find any AWS profiles!](https://github.com/daaru00/obsidian-aws-s3-sync/blob/0587dc95a78094f6e77ec9053e3ae4e134c0471b/src/settings-tab.ts#L35)
Typo

**Comment by daaru00** [comment]
Hello @joethei,

I made the required changes

**Comment by liamcain** [comment]
- [await this.awsCredentials.loadProfiles()](https://github.com/daaru00/obsidian-aws-s3-sync/blob/800be31cbcf801c4dc0f424ff97636dba104aac8/src/main.ts#L33), [await this.initFileManager()](https://github.com/daaru00/obsidian-aws-s3-sync/blob/800be31cbcf801c4dc0f424ff97636dba104aac8/src/main.ts#L49), these functions shouldn't be called from within onload. When Obsidian launches, it calls onload for each plugin in serial, and the call is blocking. So it's better to defer any expensive tasks. You can just wrap the expensive function calls in `onLayoutReady`.
- [onRemoteFileChanged](https://github.com/daaru00/obsidian-aws-s3-sync/blob/800be31cbcf801c4dc0f424ff97636dba104aac8/src/main.ts#L169) this function is never called. Also I don't think it would work, since you are reusing the same timeout ref as `onLocalFileChanged`.
- [if (!this.remoteFiles || !this.loadLocalFiles) {](https://github.com/daaru00/obsidian-aws-s3-sync/blob/800be31cbcf801c4dc0f424ff97636dba104aac8/src/lib/filemanager.ts#L259-L261) You are checking if loadLocalFiles exists, but that's a function. I assume this is meant to be `this.localFiles`

**Comment by ericaxu** [comment]
@daaru00 Hi! Do you still intend to submit this plugin? Thanks!

**Comment by joethei** [comment]
Closing PR due to inactivity.

Feel free to reopen this PR if you still intend on submitting this plugin.

**Pull request closed without merging**
