### PR TITLE
Add plugin: Images to Gist

### PR DESCRIPTION
**Pull request by singh-inder**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/singh-inder/obsidian-images-to-gist

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[new Notice("❌ No Server url", 3 * 1000);](https://github.com/singh-inder/obsidian-images-to-gist/blob/51a2254bef5bf2ba6ab9f8d3d8a66fb02fefe673/src/main.ts#L62)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[`${this.app.vault.configDir}/plugins/${this.pluginName}`](https://github.com/singh-inder/obsidian-images-to-gist/blob/51a2254bef5bf2ba6ab9f8d3d8a66fb02fefe673/src/main.ts#L66)
Use `this.manifest.dir` instead.

[new Setting(containerEl).setName("Images To Gist - Settings").setHeading();](https://github.com/singh-inder/obsidian-images-to-gist/blob/51a2254bef5bf2ba6ab9f8d3d8a66fb02fefe673/src/ui/SettingsTab.ts#L38)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

["Learn how to generate github token",](https://github.com/singh-inder/obsidian-images-to-gist/blob/51a2254bef5bf2ba6ab9f8d3d8a66fb02fefe673/src/ui/SettingsTab.ts#L114), [.setName("Github token")](https://github.com/singh-inder/obsidian-images-to-gist/blob/51a2254bef5bf2ba6ab9f8d3d8a66fb02fefe673/src/ui/SettingsTab.ts#L43), [text.setPlaceholder("Enter Github token");](https://github.com/singh-inder/obsidian-images-to-gist/blob/51a2254bef5bf2ba6ab9f8d3d8a66fb02fefe673/src/ui/SettingsTab.ts#L48)
Use the proper capitalization of the brand name "GitHub"

[const response = await fetch("https://api.github.com/gists", {](https://github.com/singh-inder/obsidian-images-to-gist/blob/51a2254bef5bf2ba6ab9f8d3d8a66fb02fefe673/src/lib/utils.ts#L54)
Use the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

**Comment by singh-inder** [comment]
Have made the changes

**Comment by singh-inder** [comment]
> [new Notice("❌ No Server url", 3 * 1000);](https://github.com/singh-inder/obsidian-images-to-gist/blob/51a2254bef5bf2ba6ab9f8d3d8a66fb02fefe673/src/main.ts#L62) [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)
> 
> [`${this.app.vault.configDir}/plugins/${this.pluginName}`](https://github.com/singh-inder/obsidian-images-to-gist/blob/51a2254bef5bf2ba6ab9f8d3d8a66fb02fefe673/src/main.ts#L66) Use `this.manifest.dir` instead.
> 
> [new Setting(containerEl).setName("Images To Gist - Settings").setHeading();](https://github.com/singh-inder/obsidian-images-to-gist/blob/51a2254bef5bf2ba6ab9f8d3d8a66fb02fefe673/src/ui/SettingsTab.ts#L38) [Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)
> 
> ["Learn how to generate github token",](https://github.com/singh-inder/obsidian-images-to-gist/blob/51a2254bef5bf2ba6ab9f8d3d8a66fb02fefe673/src/ui/SettingsTab.ts#L114), [.setName("Github token")](https://github.com/singh-inder/obsidian-images-to-gist/blob/51a2254bef5bf2ba6ab9f8d3d8a66fb02fefe673/src/ui/SettingsTab.ts#L43), [text.setPlaceholder("Enter Github token");](https://github.com/singh-inder/obsidian-images-to-gist/blob/51a2254bef5bf2ba6ab9f8d3d8a66fb02fefe673/src/ui/SettingsTab.ts#L48) Use the proper capitalization of the brand name "GitHub"
> 
> [const response = await fetch("https://api.github.com/gists", {](https://github.com/singh-inder/obsidian-images-to-gist/blob/51a2254bef5bf2ba6ab9f8d3d8a66fb02fefe673/src/lib/utils.ts#L54) Use the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

Fixed.

**Comment by singh-inder** [comment]
> [new Notice("❌ No Server url", 3 * 1000);](https://github.com/singh-inder/obsidian-images-to-gist/blob/51a2254bef5bf2ba6ab9f8d3d8a66fb02fefe673/src/main.ts#L62) [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)
> 
> [`${this.app.vault.configDir}/plugins/${this.pluginName}`](https://github.com/singh-inder/obsidian-images-to-gist/blob/51a2254bef5bf2ba6ab9f8d3d8a66fb02fefe673/src/main.ts#L66) Use `this.manifest.dir` instead.
> 
> [new Setting(containerEl).setName("Images To Gist - Settings").setHeading();](https://github.com/singh-inder/obsidian-images-to-gist/blob/51a2254bef5bf2ba6ab9f8d3d8a66fb02fefe673/src/ui/SettingsTab.ts#L38) [Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)
> 
> ["Learn how to generate github token",](https://github.com/singh-inder/obsidian-images-to-gist/blob/51a2254bef5bf2ba6ab9f8d3d8a66fb02fefe673/src/ui/SettingsTab.ts#L114), [.setName("Github token")](https://github.com/singh-inder/obsidian-images-to-gist/blob/51a2254bef5bf2ba6ab9f8d3d8a66fb02fefe673/src/ui/SettingsTab.ts#L43), [text.setPlaceholder("Enter Github token");](https://github.com/singh-inder/obsidian-images-to-gist/blob/51a2254bef5bf2ba6ab9f8d3d8a66fb02fefe673/src/ui/SettingsTab.ts#L48) Use the proper capitalization of the brand name "GitHub"
> 
> [const response = await fetch("https://api.github.com/gists", {](https://github.com/singh-inder/obsidian-images-to-gist/blob/51a2254bef5bf2ba6ab9f8d3d8a66fb02fefe673/src/lib/utils.ts#L54) Use the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

Fixed.

**Pull request merged**
