### PR TITLE
Add plugin: Note Chain

### PR DESCRIPTION
**Pull request by zigholding**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/zigholding/obsidian-notechain-plugin

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["minAppVersion": "0.15.0",](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

[app.fileManager.processFrontMatter(](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L41), [app.fileManager.processFrontMatter(](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L66), [let zh = await (app as any).plugins.getPlugin("note-chain");](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L290), [let target = await (app as any).plugins.getPlugin("obsidian-tasks-plugin");](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L298)
It's highly discouraged that you use the global app instance in your plugin. It's currently accessible from the global context for debugging purposes, and will be removed in the future. Instead, you should use the reference to App that you have from your plugin instance.


[id: 'sugguster_open_note',](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L99)
Typo, it should be "suggestor"

[this.app.workspace.off('file-open', this.ufunc_on_file_open);](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L284)
This is not necessary, the event is already registered with Obsidian, so it will take care of this.

[let zh = await (app as any).plugins.getPlugin("note-chain");](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L290)
Just use `this.settings` and `this.app` instead of creating this unnecessary variable.

[let target = await (app as any).plugins.getPlugin("obsidian-tasks-plugin");](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L298), [let dv_api = (this.app as any).plugins.getPlugin("dataview");](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/NoteChain.ts#L168)
Add some error handling in case the plugin is not installed.

[let target = await (app as any).plugins.getPlugin("obsidian-tasks-plugin");](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L298)
There is no mention of this plugin in the readme

[["删除链接",'替换链接',"删除段落",],](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L317), [let regs = await this.chain.tp_prompt('要替换的正则表达式');](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L340), [let target = await this.chain.tp_prompt('目标字符串');](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L346)
This is missing the english text.

[.addOption(this.plugin.strings.item_get_brothers,this.plugin.strings.item_get_brothers)](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L494-L502)
The value should not be using the translated strings, instead it should be hardcoded.
Once a user switchers their language of the app, this setting would become invalid.

[export function sleep(ms:number|undefined){](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/utils.ts#L36-L38)
This is already a function in the Obsidian API.

[return "Reset LongForm Secnes by Note Chain.";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L26)
Typo, should be "scenes"

[return "Sort File Explorer by Chain?";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L122), [return "Sort File Explorer Folder First?";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L130), [return "Number of Prev Notes to show?";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L138), [return "Number of Next Notes to show?";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L146), [return `${this.chain_insert_node}:Default Mode`](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L154), [return "Insert Mode(Relate to Anchor).";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L179), [return "Next Note";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L187), [return "Prev Note";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L195), [return "Head of Chain";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L203), [return "Tail of Chain";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L211), [return "Folder As Next";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L219), [return "Notes In Same Folder";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L227), [return "Notes In Same Folder(Recursive)";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L235), [return "All Notes";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L267), [return "Current Note";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L299), [return "Create Next Note";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L307), [return "Create Tail Note";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L315), [return "Create Prev Note";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L323), [return "Create Head Note";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L331), [return "Create Note not in chain";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L339), [return "Input Note Name";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L347)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[return "OutLinks+InLinks";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L243)
There should be some space between the words

[return "Recent (Based on Plugin:recent-files-obsidian)";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L275)
This should be "Recent (Based on recent files plugin)

**Comment by zigholding** [comment]
@joethei Hi, i have fix all your comments. It's OK for my plugins to publish? Thank you for your review.

> ["minAppVersion": "0.15.0",](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/manifest.json#L5) You are using newer API's, set this to the latest public build number.
> 
> [app.fileManager.processFrontMatter(](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L41), [app.fileManager.processFrontMatter(](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L66), [let zh = await (app as any).plugins.getPlugin("note-chain");](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L290), [let target = await (app as any).plugins.getPlugin("obsidian-tasks-plugin");](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L298) It's highly discouraged that you use the global app instance in your plugin. It's currently accessible from the global context for debugging purposes, and will be removed in the future. Instead, you should use the reference to App that you have from your plugin instance.
> 
> [id: 'sugguster_open_note',](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L99) Typo, it should be "suggestor"
> 
> [this.app.workspace.off('file-open', this.ufunc_on_file_open);](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L284) This is not necessary, the event is already registered with Obsidian, so it will take care of this.
> 
> [let zh = await (app as any).plugins.getPlugin("note-chain");](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L290) Just use `this.settings` and `this.app` instead of creating this unnecessary variable.
> 
> [let target = await (app as any).plugins.getPlugin("obsidian-tasks-plugin");](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L298), [let dv_api = (this.app as any).plugins.getPlugin("dataview");](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/NoteChain.ts#L168) Add some error handling in case the plugin is not installed.
> 
> [let target = await (app as any).plugins.getPlugin("obsidian-tasks-plugin");](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L298) There is no mention of this plugin in the readme
> 
> [["删除链接",'替换链接',"删除段落",],](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L317), [let regs = await this.chain.tp_prompt('要替换的正则表达式');](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L340), [let target = await this.chain.tp_prompt('目标字符串');](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L346) This is missing the english text.
> 
> [.addOption(this.plugin.strings.item_get_brothers,this.plugin.strings.item_get_brothers)](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L494-L502) The value should not be using the translated strings, instead it should be hardcoded. Once a user switchers their language of the app, this setting would become invalid.
> 
> [export function sleep(ms:number|undefined){](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/utils.ts#L36-L38) This is already a function in the Obsidian API.
> 
> [return "Reset LongForm Secnes by Note Chain.";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L26) Typo, should be "scenes"
> 
> [return "Sort File Explorer by Chain?";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L122), [return "Sort File Explorer Folder First?";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L130), [return "Number of Prev Notes to show?";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L138), [return "Number of Next Notes to show?";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L146), [return `${this.chain_insert_node}:Default Mode`](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L154), [return "Insert Mode(Relate to Anchor).";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L179), [return "Next Note";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L187), [return "Prev Note";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L195), [return "Head of Chain";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L203), [return "Tail of Chain";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L211), [return "Folder As Next";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L219), [return "Notes In Same Folder";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L227), [return "Notes In Same Folder(Recursive)";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L235), [return "All Notes";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L267), [return "Current Note";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L299), [return "Create Next Note";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L307), [return "Create Tail Note";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L315), [return "Create Prev Note";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L323), [return "Create Head Note";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L331), [return "Create Note not in chain";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L339), [return "Input Note Name";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L347) [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)
> 
> [return "OutLinks+InLinks";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L243) There should be some space between the words
> 
> [return "Recent (Based on Plugin:recent-files-obsidian)";](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/src/strings.ts#L275) This should be "Recent (Based on recent files plugin)

**Comment by joethei** [comment]
You missed this one:
[app.fileManager.processFrontMatter(](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L41)
Don't use the global app object.

And a few strings are not using sentence case.

**Comment by zigholding** [comment]
@joethei  I'm sorry for my carelessness. I have fixed the required change、 updated the code and release it  [here](https://github.com/zigholding/obsidian-notechain-plugin/compare/567ab5c7be3256c2c3997a915c33f5082a0b3684...a5093274494edb2e2735586d0002e32300687ead).


> You missed this one: [app.fileManager.processFrontMatter(](https://github.com/zigholding/obsidian-notechain-plugin/blob/f737d0d13604933db50fe66e700ff212182b1261/main.ts#L41) Don't use the global app object.
> 
> And a few strings are not using sentence case.

**Pull request merged**
