### PR TITLE
Add plugin: Password Audit

### PR DESCRIPTION
**Pull request by prashanthpulisetti**
Created new plugin password-audit

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/prashanthpulisetti/password-audit

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by prashanthpulisetti** [comment]
Hi @ObsidianReviewBot I've modified the code and released new version. Please check.

**Comment by joethei** [comment]
Obsidian is not meant to securely store data, all files are available as plaintext.
Storing passwords in plaintext files is a very bad idea, one should use a proper password manager.
Given that, I don't think it's a good idea to have something like this as a community plugin, with out some proper warnings.

Release tags cannot contain any letters at the start, so "v2.0.1" is invalid.

["description": "A plugin to audit passwords for strength and breaches, and generate secure passwords.",](https://github.com/prashanthpulisetti/password-audit/blob/3ddf19a03d303f7260e7d05e4172e8d6b5f124fa/manifest.json#L6)
Avoid including sentences like "This is a plugin for Obsidian that does ..." in your description, it should be a given since this is only shown when browsing plugins through the app or on our website.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[name: "Open Audit Panel",](https://github.com/prashanthpulisetti/password-audit/blob/3ddf19a03d303f7260e7d05e4172e8d6b5f124fa/main.ts#L17), [name: "Generate Secure Password",](https://github.com/prashanthpulisetti/password-audit/blob/3ddf19a03d303f7260e7d05e4172e8d6b5f124fa/main.ts#L26), [return "Password Audit";](https://github.com/prashanthpulisetti/password-audit/blob/3ddf19a03d303f7260e7d05e4172e8d6b5f124fa/main.ts#L87-L88), [.setName("Analyze a Password")](https://github.com/prashanthpulisetti/password-audit/blob/3ddf19a03d303f7260e7d05e4172e8d6b5f124fa/main.ts#L100), [resultsDiv.createEl("p", { text: `Generated Password: ${password}` });](https://github.com/prashanthpulisetti/password-audit/blob/3ddf19a03d303f7260e7d05e4172e8d6b5f124fa/main.ts#L144)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[const style = document.querySelector("style.password-audit-style");](https://github.com/prashanthpulisetti/password-audit/blob/3ddf19a03d303f7260e7d05e4172e8d6b5f124fa/main.ts#L70-L71), [injectCSS() {](https://github.com/prashanthpulisetti/password-audit/blob/3ddf19a03d303f7260e7d05e4172e8d6b5f124fa/main.ts#L190-L224)
This should be part of the `styles.css` file, not loaded via JS.

**Comment by prashanthpulisetti** [comment]
Hi @joethei,

Thank you for your feedback and for highlighting this important concern. I completely agree that Obsidian is not designed for securely storing sensitive information, such as passwords, given that all files are accessible as plaintext.

To address this, I’ve added clear warnings within the plugin's interface to inform users about the risks of storing sensitive data in Obsidian and explicitly recommend the use of a dedicated password manager for secure storage. Additionally, the plugin is intended as a utility for auditing password strength and checking breaches rather than for managing or storing passwords. This purpose has also been clarified in the plugin description to avoid any misunderstandings.

I truly appreciate your attention to this matter, as it helps ensure that plugins in the community are both useful and responsibly designed. If you have further suggestions or see areas for improvement, I’d be happy to incorporate them!

**Comment by prashanthpulisetti** [comment]
Hi @joethei it looks like someone modified my entries in community plugin and where i resolved the entries properly again and i see the above error; can you look it again?

**Comment by joethei** [comment]
That's just some other PR's being merged.
It shows up because you did not do the rebase properly.
For the next time, you can just ignore these merge conflicts, I'll handle them when merging.

**Pull request merged**
