### PR TITLE
add Obsidiosaurus Plugin

### PR DESCRIPTION
**Pull request by Mat4m0**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/CIMSTA/obsidiosaurus

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["js": "main.js",](https://github.com/CIMSTA/obsidiosaurus/blob/4f860f415ed5edf8081c37044b28d7c1343a540d/manifest.json#L8)
This value is never used.

[const basePath: string = path.dirname(this.app.vault.adapter.basePath);](https://github.com/CIMSTA/obsidiosaurus/blob/4f860f415ed5edf8081c37044b28d7c1343a540d/main.ts#L36)
`adapter.basePath` is only available on desktop and is not included in the typings.
Use this instead:
```ts
if(this.app.vault.adapter instanceof FileSystemAdapter) {
	const basePath = path.dirname(this.app.vault.adapter.getBasePath();
	await obsidiosaurusProcess(basePath);
}

[new Setting(containerEl)](https://github.com/CIMSTA/obsidiosaurus/blob/4f860f415ed5edf8081c37044b28d7c1343a540d/main.ts#L89-L98)
Is this setting used anywhere?

**Comment by Mat4m0** [comment]
Hello Jothei,

1) ["js": "main.js",](https://github.com/CIMSTA/obsidiosaurus/blob/4f860f415ed5edf8081c37044b28d7c1343a540d/manifest.json#L8)

is now removed

2) [const basePath: string = path.dirname(this.app.vault.adapter.basePath);](https://github.com/CIMSTA/obsidiosaurus/blob/4f860f415ed5edf8081c37044b28d7c1343a540d/main.ts#L36)

Has also been changed to your suggestion

3) [new Setting(containerEl)](https://github.com/CIMSTA/obsidiosaurus/blob/4f860f415ed5edf8081c37044b28d7c1343a540d/main.ts#L89-L98)

This setting was never used, so i removed it


Thanks for taking time to review :)

**Comment by Mat4m0** [comment]
@joethei any update on this?

**Comment by Mat4m0** [comment]
@joethei it has been already over a month, can i get an update on this?
Thanks!

**Comment by Mat4m0** [comment]
@joethei, @ericaxu

Can I please get an update on this???

**Comment by ericaxu** [comment]
So sorry for the delay in review times! We'll review this asap when there's bandwidth.

**Comment by liamcain** [comment]
Added manually here: https://github.com/obsidianmd/obsidian-releases/commit/d4ca09fc23520dac33e2c0f26f36b297ce053e61

**Pull request closed without merging**
