### PR TITLE
Add plugin: Everyday Classical Music

### PR DESCRIPTION
**Pull request by Eloliuyx**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Eloliuyx/everyday-classical-music-plugin
This initial release works for apple macOS.

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Eloliuyx** [comment]
/skip 
[[1](https://github.com/Eloliuyx/everyday-classical-music-plugin/blob/8828af1974798c196835a0e53794d573220ba0f0/main.ts#L17)]:Obsidian's configuration directory isn't necessarily .obsidian, it can be configured by the user. You can access the configured value from Vault#configDir

There is a setting that allows a user to change the file path manually, if the configuration directory the user configured is not the default .obsidian. 

Changes are now made to address the other required review items.

**Comment by joethei** [comment]
["css": "styles.css"](https://github.com/Eloliuyx/everyday-classical-music-plugin/blob/5d10777a0bb48c7cfaa5a655dbc60b1fdc8859b7/manifest.json#L10)
This is not a part of the manifest spec, remove it.

[import * as fs from 'fs';](https://github.com/Eloliuyx/everyday-classical-music-plugin/blob/5d10777a0bb48c7cfaa5a655dbc60b1fdc8859b7/main.ts#L2-L3)
These imports are only available from a Node.js runtime, which means that this will throw errors on Mobile (that's a problem since you have `isDesktopOnly` marked as `false` in your manifest.json file.

[import moment from 'moment';](https://github.com/Eloliuyx/everyday-classical-music-plugin/blob/5d10777a0bb48c7cfaa5a655dbc60b1fdc8859b7/main.ts#L4)
Use `import {moment} from "obsidian";` instead.

[jsonFilePath: '.obsidian/plugins/everyday-classical-music/dailyMusicLinks.json'](https://github.com/Eloliuyx/everyday-classical-music-plugin/blob/5d10777a0bb48c7cfaa5a655dbc60b1fdc8859b7/main.ts#L17)
This should not be a setting, the file content should be bundled into the plugin and not loaded as a separate file.

[localStorage.setItem('everydayClassicalMusicEnabledTimestamp', this.pluginEnabledTimestamp.toString());](https://github.com/Eloliuyx/everyday-classical-music-plugin/blob/5d10777a0bb48c7cfaa5a655dbc60b1fdc8859b7/main.ts#L44)
Why are you doing this?

[console.log('Loading JSON file from path:', jsonFilePath); // Debug log](https://github.com/Eloliuyx/everyday-classical-music-plugin/blob/5d10777a0bb48c7cfaa5a655dbc60b1fdc8859b7/main.ts#L76), [console.log('JSON file exists at path:', jsonFilePath);](https://github.com/Eloliuyx/everyday-classical-music-plugin/blob/5d10777a0bb48c7cfaa5a655dbc60b1fdc8859b7/main.ts#L80), [console.log('Raw JSON data:', data); // Debug log](https://github.com/Eloliuyx/everyday-classical-music-plugin/blob/5d10777a0bb48c7cfaa5a655dbc60b1fdc8859b7/main.ts#L84), [console.log('JSON data successfully parsed and loaded'); // Debug log](https://github.com/Eloliuyx/everyday-classical-music-plugin/blob/5d10777a0bb48c7cfaa5a655dbc60b1fdc8859b7/main.ts#L88)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[containerEl.createEl('h2', { text: 'Settings for Everyday Classical Music Plugin' });](https://github.com/Eloliuyx/everyday-classical-music-plugin/blob/5d10777a0bb48c7cfaa5a655dbc60b1fdc8859b7/main.ts#L178)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[.setName('Backfill Existing Notes')](https://github.com/Eloliuyx/everyday-classical-music-plugin/blob/5d10777a0bb48c7cfaa5a655dbc60b1fdc8859b7/main.ts#L181), [.setName('Remove Links Before Date')](https://github.com/Eloliuyx/everyday-classical-music-plugin/blob/5d10777a0bb48c7cfaa5a655dbc60b1fdc8859b7/main.ts#L194), [button.setButtonText('Remove Links')](https://github.com/Eloliuyx/everyday-classical-music-plugin/blob/5d10777a0bb48c7cfaa5a655dbc60b1fdc8859b7/main.ts#L206)

**Comment by Eloliuyx** [comment]
@joethei Thank you for reviewing my code. I have made changes based on your feedback - please let me know if anything else needs to be adjusted.

**Comment by Eloliuyx** [comment]
@joethei Updated - please check thanks!

**Comment by Eloliuyx** [comment]
> [.setName('Backfill Existing Notes')](https://github.com/Eloliuyx/everyday-classical-music-plugin/blob/29b210dd611c58a1144d187ad517f292ada82534/main.ts#L1971), [.setName('Remove Links Before Date')](https://github.com/Eloliuyx/everyday-classical-music-plugin/blob/29b210dd611c58a1144d187ad517f292ada82534/main.ts#L1984), [button.setButtonText('Remove Links')](https://github.com/Eloliuyx/everyday-classical-music-plugin/blob/29b210dd611c58a1144d187ad517f292ada82534/main.ts#L1996) [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

@joethei done - please check thanks

**Comment by joethei** [comment]
It looks like you forgot to push.

**Comment by Eloliuyx** [comment]
> It looks like you forgot to push.

@joethei I'm sorry for the late reply; just came back from a trip where access to the internet is limited. I should have corrected it this time - please let me know if it works. Thank you.

**Pull request merged**
