### PR TITLE
Add plugin: HugoHelper

### PR DESCRIPTION
**Pull request by tignioj**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/tignioj/obsidian-hugo-helper

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Lisandra-dev** [comment]
Hello. What is the difference with the other plugin #3073 ?
User would benefit to have one plugin than two for the same function…

**Comment by tignioj** [comment]
> Hello. What is the difference with the other plugin #3073 ? User would benefit to have one plugin than two for the same function…

Hello, my plugin can help users quickly create documents according to hugo's directory structure, as well as update the document's properties in some friendly ways. It does not help the user to publish the document anywhere, nor does it transform the content, and there is no overlap with the plugin you mentioned.

**Comment by tignioj** [comment]
/skip
tag 1.0.5 updated.

**Comment by tignioj** [comment]
/skip
tag 1.0.5 released

**Comment by tignioj** [comment]
/skip
1.0.5 released url: https://github.com/tignioj/obsidian-hugo-helper/releases/tag/1.0.5

**Comment by tignioj** [comment]
> [Copyright (c) [year] [fullname]](https://github.com/tignioj/obsidian-hugo-helper/blob/90f1f39cbc17519223b778cb75a8b6f1b9c86be0/LICENSE.md#L3) Fill this.
> 
> ["name": "hugo-helper",](https://github.com/tignioj/obsidian-hugo-helper/blob/90f1f39cbc17519223b778cb75a8b6f1b9c86be0/manifest.json#L3) The plugin name should use snetence case and should not contain a `-`
> 
> [const series = (folderOrFile)?.children](https://github.com/tignioj/obsidian-hugo-helper/blob/90f1f39cbc17519223b778cb75a8b6f1b9c86be0/main.ts#L171) You should check that folderOrFile is `instanceof TFolder` before this call.
> 
> [clearTimeout(timeoutId);](https://github.com/tignioj/obsidian-hugo-helper/blob/90f1f39cbc17519223b778cb75a8b6f1b9c86be0/main.ts#L274), [timeoutId = setTimeout(function () {](https://github.com/tignioj/obsidian-hugo-helper/blob/90f1f39cbc17519223b778cb75a8b6f1b9c86be0/main.ts#L277) This is not mobile compatible, use `window.setTimeout` and `window.clearTimeout` instead.

Thanks for your suggestions, all changes has relesed on 1.0.5

**Comment by liamcain** [comment]
- [file instanceof TFile && !callBySystem](https://github.com/tignioj/obsidian-hugo-helper/blob/17e72f54971d693fbcf93d2aee59dcdbc71828e5/main.ts#L275) You need a check here to ensure that the modified file is a markdown file.

**Pull request closed without merging**
