### PR TITLE
Add "Obsidian-Account-Linker" Plugin

### PR DESCRIPTION
**Pull request by qwegat**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:https://github.com/qwegat/Obsidian-Account-Linker

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x]  The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[target.innerHTML +=](https://github.com/qwegat/Obsidian-Account-Linker/blob/f860fac68d30c8c953b4da04c29f01c1af19f814/src/drawing/frontmatterProcessor.ts#L36-L44)
Please don't manipulate `innerHTML` if possible.
You can replace this with this instead.
```ts
const frontmatterSection = target.createDiv({cls: "frontmatter-section"});
frontmatterSection.createDiv({cls: "frontmatter-section-label"});
const section = frontmatterSection.createDiv({cls: "frontmatter-section-accounts"});
```

This will also eliminate the need to use `querySelector` later on, saving a bit of performance.

**Comment by qwegat** [comment]
> [target.innerHTML +=](https://github.com/qwegat/Obsidian-Account-Linker/blob/f860fac68d30c8c953b4da04c29f01c1af19f814/src/drawing/frontmatterProcessor.ts#L36-L44) 
Please don't manipulate `innerHTML` if possible. 
You can replace this with this instead.

done

**Comment by qwegat** [comment]
How about after that?

**Comment by liamcain** [comment]
Hi, sorry for the delay, I didn't realize this was waiting on me to review. I took a quick look now. Nothing that I think should block merging.

---

- [console.log(siteDict)](https://github.com/qwegat/Obsidian-Account-Linker/blob/d28560b2ff10d68277e9f6f5a8234ab00366c42b/src/drawing/frontmatterProcessor.ts#L23) nit: remove this
- [replaceTemplateText](https://github.com/qwegat/Obsidian-Account-Linker/blob/d28560b2ff10d68277e9f6f5a8234ab00366c42b/src/control/utils.ts#L5) I'm struggling to understand this function. Shouldn't it just be `.replace('{{name}}', ctx.text)`? I don't understand why you're using split+join.

**Pull request merged**
