### PR TITLE
Add plugin: Timeline Schedule

### PR DESCRIPTION
**Pull request by Ebonsignori**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Ebonsignori/obsidian-timeline-schedule

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[import moment from "moment";](https://github.com/Ebonsignori/obsidian-timeline-schedule/blob/2cb8f629966da56f459d266f59eff89dbd4ce093/src/utils.ts#L1)
Import moment from Obsidian.

[this.containerEl.appendChild(](https://github.com/Ebonsignori/obsidian-timeline-schedule/blob/2cb8f629966da56f459d266f59eff89dbd4ce093/src/settings/settings.ts#L53-L55)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[(example: ${moment().format(](https://github.com/Ebonsignori/obsidian-timeline-schedule/blob/2cb8f629966da56f459d266f59eff89dbd4ce093/src/settings/settings.ts#L168-L171)
The Obsidian API has a component for this, here is an example: <https://github.com/joethei/obsidian-rss/blob/b600e2ead2505d58aa3e4c7898795bbf58fa3cdc/src/settings/FileCreationSettings.ts#L119C55-L150>

**Comment by ericaxu** [comment]
To keep things tidy, we're going to close issues that we don't hear back after a month of inactivity.

Feel free to tell us to re-open it when you're ready to reply and we'll reopen the issue right away. Thanks for your understanding!

**Comment by Ebonsignori** [comment]
Hi @ericaxu  because I've fixed the code suggestions and added support for callouts in 1.2.0 of https://github.com/Ebonsignori/obsidian-timeline-schedule

**Comment by Ebonsignori** [comment]
Bump to please reopen this @joethei

**Comment by Ebonsignori** [comment]
Hi @liamcain , any update on this?

**Comment by liamcain** [comment]
- [selection.ranges[0]](https://github.com/Ebonsignori/obsidian-timeline-schedule/blob/9924966e8a39f471ca54efd930c28b3ef7b7c5ed/src/codeblock-autofill.ts#L283) you can use `selection.main` instead (The "main" cursor might not be at index 0)
- [activeView](https://github.com/Ebonsignori/obsidian-timeline-schedule/blob/9924966e8a39f471ca54efd930c28b3ef7b7c5ed/src/codeblock-autofill.ts#L244) you are in a Codemirror extension, you shouldn't need to access the active view at all. The scroll position shouldn't update when you dispatch changes via codemirror. What issue are you trying to solve here?

Merging since I don't see any blockers but I'd like to get to the bottom of the scrolling behavior, since this code should be simpler than you have it currently.

**Pull request merged**
