### PR TITLE
Add Solve Plugin

### PR DESCRIPTION
**Pull request by LiamRiddell**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [LiamRiddell/Solve](https://github.com/LiamRiddell/obsidian-solve)

## Release Checklist
- [X] I have tested the plugin on
  - [X]  Windows
  - [ ]  macOS (I do not have a mac)
  - [ ]  Linux (I do not have a linux machine)
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by LiamRiddell** [comment]
License was added after the tag was created. 👍

**Comment by LiamRiddell** [comment]
> [declare global {](https://github.com/LiamRiddell/obsidian-solve/blob/f2e9af81b6a345d3aa376be8fa23f35775f6f349/src/main.ts#L16-L20) Moment is exported as part of the API, you should not take it from window.
> 
> [displayIntroduction() {](https://github.com/LiamRiddell/obsidian-solve/blob/f2e9af81b6a345d3aa376be8fa23f35775f6f349/src/settings/SolveSettingsTab.ts#L22-L32) [Don't include a header with the plugin name in your settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

Thank you for the review @joethei. I do apologise for overlooking these. I've made the changes and they are available under release 0.3.3.

**Comment by liamcain** [comment]
- [import moment from "moment";](https://github.com/LiamRiddell/obsidian-solve/blob/ca6b4269a1252547b3c9c68d7f269bfc983cd3fe/src/utilities/Datetime.ts#L1) you should import the moment instance from the Obsidian API instead.

**Comment by LiamRiddell** [comment]
> - [import moment from "moment";](https://github.com/LiamRiddell/obsidian-solve/blob/ca6b4269a1252547b3c9c68d7f269bfc983cd3fe/src/utilities/Datetime.ts#L1) you should import the moment instance from the Obsidian API instead.

@liamcain I tried and it was working great until it came to trying to run my unit tests which was trying to test code that relied on moment from obsidian module. I couldn't get this to work. So ultimately had to switch to using the moment package instead of the import from obsidian.

Thank you for merging!

**Pull request merged**
