### PR TITLE
Add Apple Reminders Plugin

### PR DESCRIPTION
**Pull request by urishiraval**
Hey,

Please approve my [Plugin](https://github.com/urishiraval/obsidian-apple-reminders-plugin) for the Obsidian Folio.

Warm Regards,
A Huge Fan of your Team's Work.

### CODE REVIEW

**Comment by lishid** [comment]
Hooking recursive mutation observers on the whole workspace might be a performance issue. Might want to find a better way to do things.

**Comment by urishiraval** [comment]
@lishid I see...

I'm basically copying the method that the todoist plugin uses.

But is there any alternative that you can think of that would work better?

**Comment by lishid** [comment]
Hmm just looking at the way it's working, I'm guessing it might not work well in a document that's long enough such that you can scroll the item out of view, and when you do, the renderer will unload itself.

We internally have optimizations in preview mode that removes any elements outside of view range (with a bit of buffer space).

**Comment by lishid** [comment]
To be honest, I can't think of a great solution right now to manage lifecycles of rendered parts yet. I'll think of a better way to help manage lifecycle in the future.

**Comment by urishiraval** [comment]
I see....I'm sure it will be a worthy addition to the Dev environment. Looking forward to it!

Thanks @lishid

**Pull request merged**
