### PR TITLE
Add plugin: CSS Inserter

### PR DESCRIPTION
**Pull request by Erallie**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Erallie/css-inserter

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Erallie** [comment]
/skip This plugin does not assign styles via JavaScript or HTML. The reason why the bot thought that it does is because there are variables for it so that the user can enter in the information they want to enter so that the user can apply the CSS snippet to their text. All of my custom text uses classes to assign styles.

**Comment by joethei** [comment]
[Copyright (c) 2023 Juanjo Arranz](https://github.com/Erallie/css-inserter/blob/b104c5dc55d3a97214c181061f64a5e7434fca1d/LICENSE.txt#L3)
Update this, but keep the original copyright.

["author": "Erika Gozar",](https://github.com/Erallie/css-inserter/blob/b104c5dc55d3a97214c181061f64a5e7434fca1d/manifest.json#L7)
Also credit the original author here.

[containerEl.createEl('span', { text: 'A fork of ', cls: 'instructions' }).createEl('a', { text: 'Style Text', href: 'https://github.com/juanjoarranz/style-text-obsidian-plugin', cls: 'instructions' });](https://github.com/Erallie/css-inserter/blob/b104c5dc55d3a97214c181061f64a5e7434fca1d/settings.ts#L39-L42)
This should be at the end, not at the front.

[const newCSS: CSS = { name: "Yellow Highlight"](https://github.com/Erallie/css-inserter/blob/b104c5dc55d3a97214c181061f64a5e7434fca1d/settings.ts#L99), [.setTooltip("Remove CSS Snippet")](https://github.com/Erallie/css-inserter/blob/b104c5dc55d3a97214c181061f64a5e7434fca1d/settings.ts#L229), [containerInstructions.createEl('p', { text: 'Remove Applied CSS Snippet:', cls: 'instructions' });](https://github.com/Erallie/css-inserter/blob/b104c5dc55d3a97214c181061f64a5e7434fca1d/settings.ts#L300), [openCPUl2.createEl('li', { text: 'Mobile: Swipe Down' });](https://github.com/Erallie/css-inserter/blob/b104c5dc55d3a97214c181061f64a5e7434fca1d/settings.ts#L311-L312)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by Erallie** [comment]
In the manifest, do I just credit both of us as `"author": "Erika Gozar, Juanjo Arranz"`?

**Comment by Erallie** [comment]
I have made the requested changes.

**Comment by liamcain** [comment]
- [executeCommandById](https://github.com/Erallie/css-inserter/blob/4def28ea5b5c58188004bdd9d979c547cb3448b3/main.ts#L88) you can easily avoid calling executeCommandById by just pulling the editorCallbacks into their own functions. You already have an editor instance passed in, so you can call this.removeCss(editor) instead, for example. Relying on executeCommandById is dangerous because the file menu can be opened for tabs that aren't active. This means, you could right-click on a tab, see this command, and clicking it will do something to a different file.

**Comment by Erallie** [comment]
Okay thank you @liamcain ! I have made the necessary edits.

**Pull request merged**
