### PR TITLE
added my plugin

### PR DESCRIPTION
**Pull request by TClark1011**
# [x] I am submitting a new Community Plugin

## Repo URL

https://github.com/TClark1011/obsidian-find-and-replace-in-selection

## Release Checklist

- [x] I have tested this on Windows, macOS, and Linux _(if applicable)_
- [x] Github release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] Github release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.
- [x] I have added a license in the LICENSE file

### CODE REVIEW

**Comment by lishid** [comment]
Please remove main.js from your repo and add it to your .gitignore - compiled sources can stay in your github releases instead.

https://github.com/TClark1011/obsidian-find-and-replace-in-selection/blob/9344444fd5e7ec924bba876a2fff8e24bc27a37d/main.ts#L15
You should remove all the settings-related code if your plugin doesn't use them.

https://github.com/TClark1011/obsidian-find-and-replace-in-selection/blob/9344444fd5e7ec924bba876a2fff8e24bc27a37d/main.ts#L35
You shouldn't be using a check callback here - you just need the editor, and it's provided for you already.

https://github.com/TClark1011/obsidian-find-and-replace-in-selection/blob/9344444fd5e7ec924bba876a2fff8e24bc27a37d/main.ts#L46
Should remove all these unused sample code.

https://github.com/TClark1011/obsidian-find-and-replace-in-selection/blob/9344444fd5e7ec924bba876a2fff8e24bc27a37d/main.ts#L93
Consider learning our shortcuts for working with DOM elements:
`parent.createEl/createDiv/createSpan({cls: 'class-names', text: 'text content'});`

**Comment by TClark1011** [comment]
Hi,
I've made all the suggested changes save for the last one. I did try to implement your shortcuts but ran into some issues and decided, for now, to leave them out and to look into switching to them in a future update. Hope everything is now satisfactory.

**Comment by lishid** [comment]
> I did try to implement your shortcuts but ran into some issues

If you have any questions I'd be happy to help. Whatever issues you run into, it would be good to know for us to improve the API.

**Comment by TClark1011** [comment]
I didn't really get too much of a chance to look honestly, I was just limited on time so when I first tried swapping in the shortcuts and they didn't work immediately I just decided to revert back. I'll let you know when I get a chance to properly try them.

**Pull request merged**
