### PR TITLE
Add plugin: Harper

### PR DESCRIPTION
**Pull request by elijah-potter**
# I am submitting a new Community Plugin

## Repo URL

The plugin's repo is [here](https://github.com/elijah-potter/harper-obsidian-plugin),
but the actual code resides in [here](https://github.com/elijah-potter/harper).

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Remove the ZIP file from the plugin repo, release assets should not be mixed with source code.
The same is true for your monorepo.

**Comment by elijah-potter** [comment]
Alright. I removed the files you pointed out. Let me know if there's anything else I need to do to get this merged.

**Comment by elijah-potter** [comment]
@joethei is there any way to remake the changes requested label? The changes are done.

**Comment by elijah-potter** [comment]
Hey @joethei. I don't mean to rush you, but I'd really like this plugin added before the school year starts, so I can iron out any potential issues.

I appreciate all the work you do, so thank you for reviewing my PR.

**Comment by liamcain** [comment]
Hi, sorry for the delay, joethei has been out sick, so I'm taking over in his absence.

- [clearTimeout](https://github.com/elijah-potter/harper/blob/1c1418f56a60544d8ef70cf380c8a49c45a0bca4/packages/obsidian-plugin/src/lint.ts#L986) For your setTimeout and clearTimeout, you should use `marker.win.setTimeout` and `marker.win.clearTimeout`. This will ensure you are referencing the same window that the marker belongs to. This becomes relevant when the user has a [pop-out windows](https://help.obsidian.md/User+interface/Pop-out+windows) and therefore, multiple Window instances.
- [export const lintKeymap: readonly KeyBinding[] = [](https://github.com/elijah-potter/harper/blob/1c1418f56a60544d8ef70cf380c8a49c45a0bca4/packages/obsidian-plugin/src/lint.ts#L372-L375) instead of using Codemirror keybindings (this doesn't look referenced?), you should consider making these Obsidian commands, so that the hotkeys are user configurable.

**Pull request merged**
