### PR TITLE
Add plugin Brain Assistant

### PR DESCRIPTION
**Pull request by Perledition**
Repo URL

Link to my plugin:https://github.com/Perledition/brain-assistant
Release Checklist

I have tested the plugin on

- [ ] Windows
- [x] macOS
- [x] Linux
- [ ] Android (if applicable)
- [ ] iOS (if applicable)

My GitHub release contains all required files

- [x] main.js
- [x] manifest.json
- [x] styles.css (optional)

I also checked the following points:

- [x] GitHub release name matches the exact version number specified in my manifest.json (Note: Use the exact version number, don't include a prefix v)
- [x] The id in my manifest.json matches the id in the community-plugins.json file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
I have given proper attribution to these other projects in my README.md.

### CODE REVIEW

**Comment by joethei** [comment]
Please follow the pull request template

**Comment by Perledition** [comment]
I made some changes to latest relase to be conform with obsidian. Furthermore I included the checklist above. @joethei

**Comment by joethei** [comment]
["description": "This PlugIn allows you to chat against your documents with an AI like ChatGPT. However, it is based on aleph alpha so you don't need to worry about your data",](https://github.com/Perledition/brain-assistant/blob/f32fcc6a334cf5ee4371e9c26c05a6fb9cb65fcf/manifest.json#L6-L7)
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This plugin does xyz" in your description.

[import * as path from "path";](https://github.com/Perledition/brain-assistant/blob/f32fcc6a334cf5ee4371e9c26c05a6fb9cb65fcf/main.ts#L1)
This import is only available from a Node.js runtime, which means that this will throw errors on Mobile (that's a problem since you have `isDesktopOnly` marked as `false` in your manifest.json file.

[`${this.settings.VaultPath}/.obsidian/plugins/brain-assistant/vector/`,](https://github.com/Perledition/brain-assistant/blob/f32fcc6a334cf5ee4371e9c26c05a6fb9cb65fcf/main.ts#L44)
Having to fill the path to the vault in the plugin settings is not user friendly, also the name of the config folder (`.obsidian`) can be changed in the settings.
The better approach would be:
```ts
if(this.app.vault.adapter instanceof FileSystemAdapter) {
	new LocalIndex(path.join(this.app.vault.adapter.getBasePath(), this.manifest.dir!!, 'vector'))
}
```

[// Listen to file modification](https://github.com/Perledition/brain-assistant/blob/f32fcc6a334cf5ee4371e9c26c05a6fb9cb65fcf/main.ts#L73-L77)
Don't forget to register events: <https://docs.obsidian.md/Plugins/Events>

[console.log(`File "${file.path}" has been modified.`);](https://github.com/Perledition/brain-assistant/blob/f32fcc6a334cf5ee4371e9c26c05a6fb9cb65fcf/main.ts#L75)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

["OPTIONAL: If you know your Credit Budget you can enter it here to have a better spend overview"](https://github.com/Perledition/brain-assistant/blob/f32fcc6a334cf5ee4371e9c26c05a6fb9cb65fcf/components/settings.ts#L50
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[container.createEl("div").innerHTML = `](https://github.com/Perledition/brain-assistant/blob/f32fcc6a334cf5ee4371e9c26c05a6fb9cb65fcf/components/view.ts#L35-L54)
[Avoid using `innerHTML`](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%60innerHTML%60%2C+%60outerHTML%60+and+%60insertAdjacentHTML%60)


[if (!directoryPath.includes(".obsidian")) {](https://github.com/Perledition/brain-assistant/blob/f32fcc6a334cf5ee4371e9c26c05a6fb9cb65fcf/components/file_reader.ts#L154)
This can be changed in the settings, access it from `app.vault.configDir` via the plugin instance.


[let result = await axios(config)](https://github.com/Perledition/brain-assistant/blob/f32fcc6a334cf5ee4371e9c26c05a6fb9cb65fcf/components/aleph_alpha.ts#L42-L50)
I would recommend using the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

**Comment by Perledition** [comment]
Hi there, I adjusted the plugin as suggested.

**Pull request closed without merging**
