### PR TITLE
Add plugin: TimeSaver

### PR DESCRIPTION
**Pull request by odayou**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/odayou/task-processing-extension

## Release Checklist

- [x]  I have tested the plugin on
    - [x]  Windows
    - [ ]  macOS
    - [ ]  Linux
    - [ ]  Android _(if applicable)_
    - [ ]  iOS _(if applicable)_
- [x]  My GitHub release contains all required files
    - [x]  `main.js`
    - [x]  `manifest.json`
    - [ ]  `styles.css` _(optional)_
- [x]  GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don’t include a prefix `v`_)
- [x]  The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x]  My [README.md](http://readme.md/) describes the plugin’s purpose and provides clear usage instructions.
- [x]  I have read the developer policies at [https://docs.obsidian.md/Developer+policies](https://docs.obsidian.md/Developer+policies), and have assessed my plugins’s adherence to these policies.
- [x]  I have read the tips in [https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines) and have self-reviewed my plugin to avoid these common pitfalls.
- [x]  I have added a license in the LICENSE file.
- [x]  My project respects and is compatible with the original license of any code from other plugins that I’m using. I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Please follow the pull request template

**Review by odayou — COMMENTED** [review]
> Please follow the pull request template 

Could you tell me what the correct pull request looks like? I didn't notice where the relevant information is. Can you help me?

**Comment by joethei** [comment]
There are instructions when you create a new PR

**Comment by joethei** [comment]
You did the correct thing.

**Comment by odayou** [comment]
Undo the /skip directive

**Comment by odayou** [comment]
Please continue the ci process

**Comment by odayou** [comment]
> [Copyright (c) 2021 Michael Brenan](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/LICENSE.txt#L3) Update this.
> 
> ["name": "Task extension",](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/manifest.json#L3) It should be obvious that this is a plugin/extension for Obsidian, remove "extension" from the plugin name.
> 
> ["description": "任务处理优化插件 1. 快捷插入todo指令 2.快速统计当前笔记中事项的耗时，及总耗时 \n tasks processing optimization plugin for Obsidian. 1. Quickly insert todo directive. 2. Quickly count the time spent on tasks in the current note and the total time spent.",](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/manifest.json#L6) Avoid including sentences like "This is a plugin for Obsidian that does ..." in your description, it should be self-evident that this is a plugin for Obsidian. We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
> 
> [interface MyPluginSettings {](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/main.ts#L5), [export default class MyPlugin extends Plugin {](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/main.ts#L13) [// Remember to rename these classes and interfaces!](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/main.ts#L3)
> 
> [id: "task-processing-extension-compute-time-total",](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/main.ts#L18), [id: "task-processing-extension-add-checkbox-no-checked",](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/main.ts#L42), [id: "task-processing-extension-add-checkbox-checked",](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/main.ts#L50), [id: "task-processing-extension-insert-time-clock",](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/main.ts#L58) Don't prefix the command id with the plugin id, Obsidian will make sure that there are no conflicts with other plugins.
> 
> [name: "time total",](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/main.ts#L19), [name: "Insert Checkbox noChecked",](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/main.ts#L43), [name: "Insert Checkbox Checked",](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/main.ts#L51), [name: "Insert Now Time Clock",](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/main.ts#L59) [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI) and make sure that they make sense grammatically.
> 
> [const data = editor.editorComponent.view.data;](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/main.ts#L24) Use `editor.getValue()` instead.

If I want to fix the above issue, I would need to change the plugin name at least. So, do I need to modify the fork version of this repository and create a new PR?

**Comment by odayou** [comment]
> [Copyright (c) 2021 Michael Brenan](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/LICENSE.txt#L3) Update this.
> 
> ["name": "Task extension",](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/manifest.json#L3) It should be obvious that this is a plugin/extension for Obsidian, remove "extension" from the plugin name.
> 
> ["description": "任务处理优化插件 1. 快捷插入todo指令 2.快速统计当前笔记中事项的耗时，及总耗时 \n tasks processing optimization plugin for Obsidian. 1. Quickly insert todo directive. 2. Quickly count the time spent on tasks in the current note and the total time spent.",](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/manifest.json#L6) Avoid including sentences like "This is a plugin for Obsidian that does ..." in your description, it should be self-evident that this is a plugin for Obsidian. We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
> 
> [interface MyPluginSettings {](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/main.ts#L5), [export default class MyPlugin extends Plugin {](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/main.ts#L13) [// Remember to rename these classes and interfaces!](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/main.ts#L3)
> 
> [id: "task-processing-extension-compute-time-total",](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/main.ts#L18), [id: "task-processing-extension-add-checkbox-no-checked",](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/main.ts#L42), [id: "task-processing-extension-add-checkbox-checked",](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/main.ts#L50), [id: "task-processing-extension-insert-time-clock",](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/main.ts#L58) Don't prefix the command id with the plugin id, Obsidian will make sure that there are no conflicts with other plugins.
> 
> [name: "time total",](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/main.ts#L19), [name: "Insert Checkbox noChecked",](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/main.ts#L43), [name: "Insert Checkbox Checked",](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/main.ts#L51), [name: "Insert Now Time Clock",](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/main.ts#L59) [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI) and make sure that they make sense grammatically.
> 
> [const data = editor.editorComponent.view.data;](https://github.com/odayou/task-processing-extension/blob/746dbc9942e2ac919018e013ae72abd8a65a3cbe/main.ts#L24) Use `editor.getValue()` instead.

 I've made the requested changes. Please take another look.

**Comment by odayou** [comment]
to

**Comment by odayou** [comment]
to edit pr template

**Comment by odayou** [comment]
@joethei 
Hi joethei,
 I have addressed all the issues regarding this PR, including fixing the PR template format and implementing suggested code modifications. I appreciate your assistance in advancing the plugin review process. Would you please help to review and merge the changes? Thank you for your hard work

**Pull request merged**
