### PR TITLE
Add plugin: Spaced everything

### PR DESCRIPTION
**Pull request by zachmueller**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/zachmueller/spaced-everything

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by zachmueller** [comment]
Shifting this back into a draft while I revamp the plugin towards a broader concept of "spaced everything" (after re-reading many of Andy Matuschak's notes on the topic). See details [here](https://github.com/zachmueller/spaced-writing-practice-obsidian/commit/0b89de12b90adc1a0ccd2d55e7d340c0a8871dda).

**Comment by joethei** [comment]
[new Setting(containerEl).setName('Spacing Methods').setHeading();](https://github.com/zachmueller/spaced-everything/blob/1a1e2b37b43649b523e19a6232a943dc2f2bbf50/main.ts#L438), [.setName(`Spacing Method - #${index + 1}`)](https://github.com/zachmueller/spaced-everything/blob/1a1e2b37b43649b523e19a6232a943dc2f2bbf50/main.ts#L573), [.setName('Review Options')](https://github.com/zachmueller/spaced-everything/blob/1a1e2b37b43649b523e19a6232a943dc2f2bbf50/main.ts#L667)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by zachmueller** [comment]
Updated! I forgot to re-review for sentence case after refactoring my settings 🤦‍♂️ I found a few other instances where I needed to correct for sentence case and updated those as well. 

To double check: there are a couple instances where I make reference to the name of the plugin with both words capitalized (i.e., "Spaced Everything", [example](https://github.com/zachmueller/spaced-everything/blob/a87997dfb8680d61688e66319ddd4996f9d32c79/main.ts#L520)). Is that fine?

**Comment by joethei** [comment]
Yeah, that's fine since it's the name of the plugin.

**Pull request merged**
