### PR TITLE
Add plugin: Noor

### PR DESCRIPTION
**Pull request by MKSherbini**
# I am submitting a new Community Plugin

## Repo URL

https://github.com/MKSherbini/obsidian-noor

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["fundingUrl": "Binance PayID: 713416926",](https://github.com/MKSherbini/obsidian-noor/blob/9821e13b0171308aa3cb2462ba2b4f6b2657498a/manifest.json#L9)
This has to be a valid URL.

[// Remember to rename these classes and interfaces!](https://github.com/MKSherbini/obsidian-noor/blob/9821e13b0171308aa3cb2462ba2b4f6b2657498a/main.ts#L5)
Remove this comment.

[return fetch(url)](https://github.com/MKSherbini/obsidian-noor/blob/9821e13b0171308aa3cb2462ba2b4f6b2657498a/main.ts#L113)
Use the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

[containerEl.createEl('h2', {text: 'Noor Settings'});](https://github.com/MKSherbini/obsidian-noor/blob/9821e13b0171308aa3cb2462ba2b4f6b2657498a/main.ts#L151)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[.setName('Translation Language')](https://github.com/MKSherbini/obsidian-noor/blob/9821e13b0171308aa3cb2462ba2b4f6b2657498a/main.ts#L167), [.setName('Translation Options')](https://github.com/MKSherbini/obsidian-noor/blob/9821e13b0171308aa3cb2462ba2b4f6b2657498a/main.ts#L182)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by MKSherbini** [comment]
@joethei thanks for your detailed review, I've applied the changes.

**Comment by MKSherbini** [comment]
@joethei How does the rest of the process go?

**Comment by joethei** [comment]
[containerEl.createEl('h2', {text: 'General Settings'});](https://github.com/MKSherbini/obsidian-noor/blob/867f194de3bbdbf8c646bb39c8430de88af9dd5a/main.ts#L150)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by MKSherbini** [comment]
@joethei I've removed it

**Pull request merged**
