### PR TITLE
Submit Slide Note Plugin

### PR DESCRIPTION
**Pull request by Phantom1003**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Phantom1003/obsidian-slide-note

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[.markdown-preview-view pre,](https://github.com/Phantom1003/obsidian-slide-note/blob/1e49b0856dd3ad72266a264c4a8156197f74aa9e/styles.css#L5-L15)
Don't overwrite core styling with a plugin, these styles should only apply for your own plugins codeblocks.

**Comment by Phantom1003** [comment]
Sorry, I have removed the relevant code.

**Comment by Phantom1003** [comment]
@joethei ready for review now

**Comment by liamcain** [comment]
- [popover.hover-popover](https://github.com/Phantom1003/obsidian-slide-note/blob/88c6bcff037d3b1fe7dea52d807427f01bdca975/styles.css#L1) this style also overrides Obsidian core styles. I suggest you remove this as well.

**Comment by Phantom1003** [comment]
@liamcain done

**Pull request merged**
