### PR TITLE
Add Unitade plugin

### PR DESCRIPTION
**Pull request by Falcion**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Falcion/UnitadeOBSIDIAN

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[containerEl.createEl('h2', { text: 'Unitade\'s Plugin Settings' });](https://github.com/Falcion/UnitadeOBSIDIAN/blob/6f0f210e42c76ce7dfb7a8914cb8568e9a49401d/main.ts#L57)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by Falcion** [comment]
> [containerEl.createEl('h2', { text: 'Unitade's Plugin Settings' });](https://github.com/Falcion/UnitadeOBSIDIAN/blob/6f0f210e42c76ce7dfb7a8914cb8568e9a49401d/main.ts#L57) [Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

Made! Now in the settings there are just options without headers.

**Comment by joethei** [comment]
One thing you should look into is what happens when you add the extension of a binary filetype, like png for example, and see if that causes problems.

**Comment by Falcion** [comment]
> One thing you should look into is what happens when you add the extension of a binary filetype, like png for example, and see if that causes problems.

Tested on different binaries, the results are as follows: 
- images: just show inside the interface, as I remember obsidian provides for normal image viewing;
- files like .EXE, .MSI, .JAR: runs them directly (maybe in the potential future I'll try to fix this somehow);
- ZIP files open in Explorer;
- all sorts of video files, like MP4, are simply played in the application;

But all sorts of formats, let's say we create a file and rename it to [NAME].dictionary, will open it as a plain text file.

BUT! if we rename the binary file to a custom extension (same .dictionary), then a file will be able to edit the binary

The plugin allows opening files as notes, only those that don't have any default applications to run (or don't run anything themselves).

And thanks for testing reminder!

image
**^this is .EXE file which was renamed into .DICTIONARY file**
image
**^this is image-binaries file, works on JPG, JPEG, PNG**

**Pull request merged**
