### PR TITLE
Add Obsidian Date in Metadata plugin

### PR DESCRIPTION
**Pull request by salmund**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/salmund/obsidian-date-in-metadata

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
What sets your plugin apart from
- <https://obsidian.md/plugins?id=update-time-on-edit>(it also does this, despite the name)

<https://github.com/salmund/obsidian-date-in-metadata/blob/6a552fe27658688b5fb87a8975c80749e80e184a/main.ts#L52>
Obsidian provides methods to parse & stringify yaml:
<https://github.com/obsidianmd/obsidian-api/blob/d4b79f95ccf3838a305915a137a844250766d023/obsidian.d.ts#L3082>

<https://github.com/salmund/obsidian-date-in-metadata/blob/6a552fe27658688b5fb87a8975c80749e80e184a/main.ts#L105-L114>
You can do something like this to have a Preview:
<https://github.com/joethei/obsidian-rss/blob/b7ba9e5b47ded6ff515de01595b40ffd4c92b0b6/src/settings/SettingsTab.ts#L148-L155>(the `t()` part is for translation support)

There are a few places where you are missing semicolons, while that is allowed, we usually recommend against it as it can lead to rare, hard to debug problems: <https://flaviocopes.com/javascript-automatic-semicolon-insertion/>

**Comment by salmund** [comment]
> What sets your plugin apart from
>
>  https://obsidian.md/plugins?id=update-time-on-edit(it also does this, despite the name)

Well I tested it first of course, doesn't quite work for me...

And if you dig a little deeper, then you can see that it's not only me, it really doesn't work properly

- https://github.com/beaussan/update-time-on-edit-obsidian/issues/29

So I tried to fixed that by making a new plugin.

**Comment by liamcain** [comment]
Hi, sorry for the long wait. I didn't realize this pull request was ready for me to take a look.

Did you see joethei's comment above about using the built-in Obsidian APIs for parsing and stringifying YAML?

> https://github.com/salmund/obsidian-date-in-metadata/blob/6a552fe27658688b5fb87a8975c80749e80e184a/main.ts#L52
Obsidian provides methods to parse & stringify yaml:
https://github.com/obsidianmd/obsidian-api/blob/d4b79f95ccf3838a305915a137a844250766d023/obsidian.d.ts#L3082

I think this is fine to go in, but I would suggest replacing the `front-matter` and `js-yaml` packages with the built-in options.

**Comment by joethei** [comment]
Zo @salmund do you still intend to submit this plugin?

**Comment by salmund** [comment]
No, I don't use Obsidian anymore ;)

**Pull request closed without merging**
