### PR TITLE
Add Customizable Menu plugin

### PR DESCRIPTION
**Pull request by kzhovn**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/kzhovn/obsidian-customizable-menu

## Release Checklist

- [x] I have tested this on ~~Windows, macOS,~~ and Linux _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by Caglar1881** [comment]
community-plugins.json

**Comment by kzhovn** [comment]
> community-plugins.json

Sorry, I don't understand this comment.

**Comment by kzhovn** [comment]
I've removed the extra commands (they were in the code of the plugin I forked) and rewrote the display refresh to use the reference to the settings page instead of the event handler.

**Comment by lishid** [comment]
Looks good. One minor thing:

https://github.com/kzhovn/obsidian-customizable-menu/blob/0bcbf06cc921cb22dfaa4fa02b2ca50ace0e8911/src/main.ts#L35
I think a better way to do it would be to register a single event on plugin init, which refers to a list of commands stored in your plugin - then you can dynamically change the list of commands added to the menu without having to reload the app (and also just register a single event).

**Pull request merged**
