### PR TITLE
Add plugin: Password Protect

### PR DESCRIPTION
**Pull request by Aspharmyx**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Aspharmyx/obsidian-password-protect

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Aspharmyx** [comment]
/skip The style I added shouldn't be changed by the themes and snippets. It should overwrite them. And I took the code from File Hider plugin by Oliver-Akins. I thought this way would be better as he resorted to use this code.

I can add "display=none" as a class to styles.css if you want. But this code should overwrite themes or snippets.

**Comment by joethei** [comment]
["authorUrl": "https://www.buymeacoffee.com/aspharmyx",](https://github.com/Aspharmyx/obsidian-password-protect/blob/34a7159d9d12ea3b4216c14119ec557483be624e/manifest.json#L8)
This should be your website or GitHub profile link.

[this.app.workspace.on("active-leaf-change", () => {](https://github.com/Aspharmyx/obsidian-password-protect/blob/34a7159d9d12ea3b4216c14119ec557483be624e/main.ts#L95-L102)
Events need to be registered, so they can be properly unloaded when the plugin is disabled. <https://docs.obsidian.md/Plugins/Events>

[this.app.workspace.on("quit", () => {](https://github.com/Aspharmyx/obsidian-password-protect/blob/34a7159d9d12ea3b4216c14119ec557483be624e/main.ts#L100-L102)
Running these renames in the quit event is dangerous, you only have ~4 seconds, it's not guaranteed to run, does not run on mobile, and will likely screw up other plugins (and possibly Obsidian Sync) because they don't have enough time to react.

**Comment by Aspharmyx** [comment]
Changed "authorUrl" to my GitHub profile link.
Registered one unregistered event with "this.register()".
Removed "on("quit")" event.

**Comment by joethei** [comment]
["authorUrl": "https://github.com/Aspharmyx/obsidian-password-protect",](https://github.com/Aspharmyx/obsidian-password-protect/blob/ddc8ed4d808196830b2d90159c542dcf5da4ad90/manifest.json#L8)
This should link to your GitHub profile, not the repo of the plugin.

["fundingUrl": "https://github.com/Aspharmyx/obsidian-password-protect",](https://github.com/Aspharmyx/obsidian-password-protect/blob/ddc8ed4d808196830b2d90159c542dcf5da4ad90/manifest.json#L9)
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on.

**Comment by Aspharmyx** [comment]
Set authorUrl to my GitHub profile and fundingUrl to "Buy me a coffee" page.

**Pull request merged**
