### PR TITLE
Add ObsidianTweaks

### PR DESCRIPTION
**Pull request by JeppeKlitgaard**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/JeppeKlitgaard/ObsidianTweaks

## Release Checklist
- [X] I have tested the plugin on
  - [X]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by JeppeKlitgaard** [comment]
Resubmitting this since it appears that some people are actually using it!

The Obsidian API now exposes the functionality needed to play around with selections and words such that ObsidianTweaks no longer needs to resort to the underlying CodeMirror instance.

**Comment by lishid** [comment]
One thing you might want to look into is using `editorCallback` rather than `callback` in your command definitions, see examples from here: https://marcus.se.net/obsidian-plugin-docs/guides/commands#editor-commands

Otherwise it looks pretty straightforward.

**Comment by lishid** [comment]
Also I suggest tweaking the description in the listing so users can actually know what your plugin does

**Comment by JeppeKlitgaard** [comment]
Good point - I will probably 'tweak' to better match the current implementation which is mostly focused on improved toggle behaviour and some code editor commands

**Comment by JeppeKlitgaard** [comment]
Both of these suggestions have been implemented in the now released version 0.2.7

**Comment by lishid** [comment]
Do a new PR to update your description in this repo as well.

**Pull request merged**
