### PR TITLE
Add theme: Apex

### PR DESCRIPTION
**Pull request by yoGhastly**
# I am submitting a new Community Theme

## Repo URL

Link to my theme: https://github.com/yoGhastly/poimandres-obsidian

## Theme checklist

- [x] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo).
  - [x] `manifest.json`
  - [x] `theme.css`
  - [x] The screenshot file (16:9 aspect ratio, recommended size is 512px by 288px for fast loading).
- [x] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my theme's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Themes/App+themes/Theme+guidelines and have self-reviewed my theme to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other themes that I'm using. I have given proper attribution to these other themes in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
The two warnings above have now been promoted to be errors, please fix those.

**Comment by clearlysid** [comment]
was this merged by mistake 😓 merging this PR has basically removed my theme without any warning sent my way, and I didn't notice until now since I was running a local copy.

**Comment by joethei** [comment]
@clearlysid I've added your plugin back into the list, not sure how I missed that removal.

**Comment by clearlysid** [comment]
Tysm! 🚀 I wonder if there's a hook or something we can tap into when our themes/plugins change to keep us informed. Only found out about my issue when a user mailed asking how to install my theme and I landed here searching for my own PR 😅

**Pull request merged**
