### PR TITLE
Add Ukiyo and Remove my older themes

### PR DESCRIPTION
**Pull request by kinmury**
# I am submitting a new Community Theme

## Repo URL

Link to my theme: https://github.com/kinmury/obsidian-ukiyo

## Theme checklist

- [x] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo).
  - [x] `obsidian.css`
  - [x] The screenshot file.
- [x] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other themes that I'm using.
      I have given proper attribution to these other themes in my `README.md`.
- [x] If my repo is not using the `master` branch, please indicate in `community-themes.json` with `"branch": "main"`.

### CODE REVIEW

**Comment by kinmury** [comment]
I just wanted to add here that the removed themes are mine, and the reason behind this change is that I implemented and updated those exact themes into this one that I'm submitting right now. 

Thank you for time and I hope the removal of said themes won't case much trouble.

**Comment by danieltomasz** [comment]
Another solution would to choose one color theme in the foreground, and the rest might be overlapping on each other in the background like in the case of minimal https://github.com/kepano/obsidian-minimal/blob/master/assets/minimal-variants.png

**Comment by kinmury** [comment]
I made another version of the Theme Showcase. I hope this version is more suitable that the previews one. If this showcase is still not good enough, then I'll make another one that is only the main theme (Ukiyo), Dark and Light Version, with a diagonal cut in the middle (just as most theme do).

**Comment by kinmury** [comment]
Hi, I see that my pull request now presents conflicts because there is an updated version of the `community-css-themes.json`, making my version of that file deprecated.

I just finished resolving said conflict, so it should be good and ready for merge.

**Comment by ericaxu** [comment]
New showcase image looks much nicer, thanks!

**Pull request merged**
