### PR TITLE
Add plugin: YiDongCloud Publish

### PR DESCRIPTION
**Pull request by ydcteam**
Submit plugin.

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/ydcteam/obsidian-publish-ydcdep

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by ydcteam** [comment]
> Submit plugin.
> 
> # I am submitting a new Community Plugin
> ## Repo URL
> Link to my plugin: https://github.com/ydcteam/obsidian-publish-ydcdep
> 
> ## Release Checklist
> * [ ]  I have tested the plugin on
>   
>   * [x]   Windows
>   * [ ]   macOS
>   * [ ]   Linux
>   * [x]   Android _(if applicable)_
>   * [ ]   iOS _(if applicable)_
> * [x]  My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
>   
>   * [x]  `main.js`
>   * [x]  `manifest.json`
>   * [x ] `styles.css` _(optional)_
> * [x]  GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
> * [x]  The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
> * [x]  My README.md describes the plugin's purpose and provides clear usage instructions.
> * [x]  I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
> * [x]  I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
> * [x]  I have added a license in the LICENSE file.
> * [x]  My project respects and is compatible with the original license of any code from other plugins that I'm using.
>   I have given proper attribution to these other projects in my `README.md`.

**Comment by ydcteam** [comment]
Already fixed @ObsidianReviewBot

**Comment by ydcteam** [comment]
> Thank you for your submission, an automated scan of your plugin code's revealed the following issues:
> 
> ### Required
> [[1](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/1cf98fde89b96985611aaa42d445d969916382e6/src/icons/index.ts#L14)][[2](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/1cf98fde89b96985611aaa42d445d969916382e6/src/icons/index.ts#L15)]:Using `innerHTML`, `outerHTML` or similar API's is a security risk. Instead, use the DOM API or the Obsidian helper functions: https://docs.obsidian.md/Plugins/User+interface/HTML+elements
> 
> ### Optional
> [[1](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/1cf98fde89b96985611aaa42d445d969916382e6/src/http.ts#L126-L130)][[2](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/1cf98fde89b96985611aaa42d445d969916382e6/src/http.ts#L180-L183)][[3](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/1cf98fde89b96985611aaa42d445d969916382e6/src/http.ts#L296-L300)][[4](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/1cf98fde89b96985611aaa42d445d969916382e6/src/http.ts#L380-L384)][[5](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/1cf98fde89b96985611aaa42d445d969916382e6/src/http.ts#L452-L456)][[6](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/1cf98fde89b96985611aaa42d445d969916382e6/src/http.ts#L524-L528)]:Obsidian provides the [`requestUrl`](https://docs.obsidian.md/Reference/TypeScript+API/requestUrl) method, it will make sure that network requests work on every plattform.
> 
> Do NOT open a new PR for re-validation. Once you have pushed all of the required changes to your repo, the bot will update the labels on this PR within 6 hours. If you think some of the required changes are incorrect, please comment with `/skip` and the reason why you think the results are incorrect.

already fixed

**Comment by joethei** [comment]
[The codes or files or sub-folders inside the folder `src` are released under the "Open Source" license: "Apache License, version 2.0", described at: https://www.apache.org/licenses/LICENSE-2.0 .](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/a86fbf8378bcb15a1d5aacc133c05db420d21d87/LICENSE#L1-L2)
This is not the proper way to declare a license, the full license text needs to be in this file.

["authorUrl": "https://web.ydc.show",](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/a86fbf8378bcb15a1d5aacc133c05db420d21d87/manifest.json#L8)
That website is offline for me.

[log(`publishing ${files[i].name} ...`);](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/a86fbf8378bcb15a1d5aacc133c05db420d21d87/src/main.ts#L267), [log(`publishing ${files[i].name} ...`);](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/a86fbf8378bcb15a1d5aacc133c05db420d21d87/src/main.ts#L327)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[div.createEl("h3", { text: this.t("setting_main_title") });](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/a86fbf8378bcb15a1d5aacc133c05db420d21d87/src/setting_tab.ts#L42)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[mainDoc.createEl("h3", { text: this.t("setting_name") });](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/a86fbf8378bcb15a1d5aacc133c05db420d21d87/src/setting_tab.ts#L45), [mainDoc.createEl("h3", { text: this.t("setting_extra_name") });](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/a86fbf8378bcb15a1d5aacc133c05db420d21d87/src/setting_tab.ts#L98-L103),  [mainDoc.createEl("h4", {](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/a86fbf8378bcb15a1d5aacc133c05db420d21d87/src/setting_tab.ts#L130-L132), [mainDoc.createEl("h3", { text: this.t("setting_help_doc_main_title") });](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/a86fbf8378bcb15a1d5aacc133c05db420d21d87/src/setting_tab.ts#L162)
For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```

[mainDoc.createEl("h3", { text: this.t("setting_name") });](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/a86fbf8378bcb15a1d5aacc133c05db420d21d87/src/setting_tab.ts#L45), [mainDoc.createEl("h3", { text: this.t("setting_extra_name") });](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/a86fbf8378bcb15a1d5aacc133c05db420d21d87/src/setting_tab.ts#L98)
[Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)


[function arrayBufferToBase64(buffer: ArrayBuffer) {](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/a86fbf8378bcb15a1d5aacc133c05db420d21d87/src/utils.ts#L29-L37)
There is already a function in the Obsidian API with the same name, use that

[import moment from "moment";](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/a86fbf8378bcb15a1d5aacc133c05db420d21d87/src/http.ts#L6), [import moment from "moment";](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/a86fbf8378bcb15a1d5aacc133c05db420d21d87/src/auth.ts#L1)
Import it through the Obsidian API instead.

[import axios from "axios";](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/a86fbf8378bcb15a1d5aacc133c05db420d21d87/src/http.ts#L2)
Please used the included `requestUrl` function instead of bundling axios.

["setting_yidong_account": "YiDong Account",](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/a86fbf8378bcb15a1d5aacc133c05db420d21d87/src/langs/en.json#L31), 
["setting_yidong_ob_publish_url": "Service Endpoint",](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/a86fbf8378bcb15a1d5aacc133c05db420d21d87/src/langs/en.json#L35), ["setting_yidong_api_key": "Access Key",](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/a86fbf8378bcb15a1d5aacc133c05db420d21d87/src/langs/en.json#L39), ["setting_yidong_api_secret": "Access Key Secret",](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/a86fbf8378bcb15a1d5aacc133c05db420d21d87/src/langs/en.json#L43), ["setting_rename_auto_sync_main_title": "Note Rename Auto-Sync Setting",](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/a86fbf8378bcb15a1d5aacc133c05db420d21d87/src/langs/en.json#L47-L48), ["setting_rename_auto_sync_freq": "Auto Sync Frequency",](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/a86fbf8378bcb15a1d5aacc133c05db420d21d87/src/langs/en.json#L50), ["setting_remove_auto_sync_main_title": "Note Removal Auto-Sync Setting",](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/a86fbf8378bcb15a1d5aacc133c05db420d21d87/src/langs/en.json#L53-L54), ["setting_remove_auto_sync_freq": "Auto Sync Frequency",](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/a86fbf8378bcb15a1d5aacc133c05db420d21d87/src/langs/en.json#L56), ["setting_help_doc_name": "Open Manual",](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/a86fbf8378bcb15a1d5aacc133c05db420d21d87/src/langs/en.json#L61), ["manual_link_text": "Visit YiDong Platform Home Page"](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/a86fbf8378bcb15a1d5aacc133c05db420d21d87/src/langs/en.json#L94)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[import { createElement, FolderSync, FolderUp } from "lucide";](https://github.com/ydcteam/obsidian-publish-ydcdep/blob/a86fbf8378bcb15a1d5aacc133c05db420d21d87/src/icons/index.ts#L1-L24)
Obsidian already includes the Lucide library by default, just do `setIcon(element, 'folder-sync')` / `setIcon(element, 'folder-up')`

**Comment by ydcteam** [comment]
Thank you very much, we're working on these issues.

**Pull request closed without merging**
