### PR TITLE
ADD s3 attachments storage plugin

### PR DESCRIPTION
**Pull request by TechTheAwesome**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/TechTheAwesome/obsidian-s3

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by liamcain** [comment]
- [createServer](https://github.com/TechTheAwesome/obsidian-s3/blob/e73f3806d7a5a9934aee30cec9520c7cb3b8ecc1/src/httpServer.ts#L28) you shouldn't need to create a server at all. Instead, if you need to bypass CORS issues, it's recommended that you call [`requestUrl`](https://github.com/obsidianmd/obsidian-api/blob/9bb30633586c6649474b2affdf5b87efdd86498f/obsidian.d.ts#L2680) (or just [request](https://github.com/obsidianmd/obsidian-api/blob/38dd22168d2925086371bfc59e36fd9121527a39/obsidian.d.ts#L2973))
- [gateway.storjshare.io](https://github.com/TechTheAwesome/obsidian-s3/blob/e73f3806d7a5a9934aee30cec9520c7cb3b8ecc1/src/settings.ts#L156) this looks a bit confusing. This is the s3 client ID, but your placeholder is a URL (to an alternative to s3 afaict)

Everything else LGTM.

**Comment by TechTheAwesome** [comment]
> * [createServer](https://github.com/TechTheAwesome/obsidian-s3/blob/e73f3806d7a5a9934aee30cec9520c7cb3b8ecc1/src/httpServer.ts#L28) you shouldn't need to create a server at all. Instead, if you need to bypass CORS issues, it's recommended that you call [`requestUrl`](https://github.com/obsidianmd/obsidian-api/blob/9bb30633586c6649474b2affdf5b87efdd86498f/obsidian.d.ts#L2680) (or just [request](https://github.com/obsidianmd/obsidian-api/blob/38dd22168d2925086371bfc59e36fd9121527a39/obsidian.d.ts#L2973))

Unfortunately, the local server wasn't meant for bypassing CORS, but as a work-around for the limitation of the S3 API, which wasn't able to generate a permanent link to a resource. Thus the server serves as a "localhost" api endpoint for Obsidian to fetch the resource, through which the s3-client will stream an answer back. Without the need to refresh the links embedded in obsidian's markdown files.

**Comment by TechTheAwesome** [comment]
>     [gateway.storjshare.io](https://github.com/TechTheAwesome/obsidian-s3/blob/e73f3806d7a5a9934aee30cec9520c7cb3b8ecc1/src/settings.ts#L156) this looks a bit confusing. This is the s3 client ID, but your placeholder is a URL (to an alternative to s3 afaict)

This should be fixed on minor version [0.1.1](https://github.com/TechTheAwesome/obsidian-s3/releases/tag/0.1.1) :smile:

**Comment by liamcain** [comment]
> Unfortunately, the local server wasn't meant for bypassing CORS, but as a work-around for the limitation of the S3 API, which wasn't able to generate a permanent link to a resource. Thus the server serves as a "localhost" api endpoint for Obsidian to fetch the resource, through which the s3-client will stream an answer back. Without the need to refresh the links alreadly embedded in obsidian's markdown files.

Ah, okay! Thanks for the explanation, makes sense.


Okay, actually there's one more thing. We've started discouraging plugins from naming themselves "Obsidian X." We believe it is over-saturating the brand name and we would like to reserve the naming for first-party plugins (see: Obsidian Publish, Obsidian Sync). Would you mind renaming the plugin to something else? It could just be something like "S3 Media Storage" or "Attachments in S3." Sorry for not bringing this up earlier!

**Comment by TechTheAwesome** [comment]
> Plugin ID mismatch, the ID in this repo is not the same as the one in your repo.

Ok I don't get why is this an issue :cry: 
My [repo's](https://github.com/TechTheAwesome/obsidian-s3) manifest.json:
```json

{
	"id": "s3-attachments-storage",
	"name": "S3 attachments storage",
	"version": "0.1.1",
	"minAppVersion": "0.15.0",
	"description": "An Obsidian plugin for storage and retrieval of media attachments on S3 compatible services.",
	"author": "TechTheAwesome",
	"authorUrl": "https://github.com/TechTheAwesome",
	"isDesktopOnly": false
}
```

Added metadata:
```json
    {
        "id": "s3-attachments-storage",
        "name": "S3 attachments storage",
        "author": "TechTheAwesome",
        "description": "An Obsidian plugin for storage and retrieval of media attachments on S3 compatible services.",
        "repo": "TechTheAwesome/obsidian-s3",
        "branch": "master"
    }
    ```

**Comment by liamcain** [comment]
Thanks! Looks good. The validation script failed since the pull request wasn't rebased so it was validating the old version of your plugin entry. It passed when I reran it though so it's all good.

**Pull request merged**
