### PR TITLE
Add plugin: Desk

### PR DESCRIPTION
**Pull request by davidlandry93**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/davidlandry93/obsidian-desk

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["author": "David Landry <davidlandry93@gmail.com>",](https://github.com/davidlandry93/obsidian-desk/blob/7d09af3df7bcb16a935f08a80eabdb96d6e1aa5e/manifest.json#L7)
This field is displayed in the sidebar and in the description for the plugin details page. Are you sure you want to have your email listed so prominently?


[// This adds a status bar item to the bottom of the app. Does not work on mobile apps.](https://github.com/davidlandry93/obsidian-desk/blob/7d09af3df7bcb16a935f08a80eabdb96d6e1aa5e/main.ts#L18-L20)
Remove this sample code.

[this.app.workspace.detachLeavesOfType(VIEW_TYPE_DESK)](https://github.com/davidlandry93/obsidian-desk/blob/7d09af3df7bcb16a935f08a80eabdb96d6e1aa5e/main.ts#L40)
Do not detach leaves with your custom view in `onunload`, this is an antipattern, see: <https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Don't+detach+leaves+in+%60onunload%60>

**Comment by davidlandry93** [comment]
Hello Johannes, 
Thanks for the review. I implemented your suggestions.

**Comment by liamcain** [comment]
- [evt.stopPropagation](https://github.com/davidlandry93/obsidian-desk/blob/216c4d3b730d6346ee6c2a7df003d7584cd819e8/main.ts#L20) Please don't do this. What is this for?

**Comment by davidlandry93** [comment]
Hello Liam, thanks for having a look.

Yes indeed that is a little intrusive and I removed it. It didn't even do what I wanted. 

Actually maybe you can help me with this. I don't fully understand the behavior of the escape key. I was trying to prevent the escape key from moving away from my own tab. In my tests this morning, if I accidentally press escape when using the extension, focus moves away from the tab towards the "New Tab" page. During testing I found that I would sometimes want to press escape while I was typing in my filters, so I figure users would do it too.

Cheers

**Comment by liamcain** [comment]
> Actually maybe you can help me with this. I don't fully understand the behavior of the escape key. I was trying to prevent the escape key from moving away from my own tab. In my tests this morning, if I accidentally press escape when using the extension, focus moves away from the tab towards the "New Tab" page. During testing I found that I would sometimes want to press escape while I was typing in my filters, so I figure users would do it too

"escape" will attempt to give focus back to the last active non-sidebar tab. You should be able to override this behavior by registering an event handler to "escape" via Scope.

In your view, do:

```
		this.scope.register([], 'Escape', () => {
                     // This can be left blank, or do something custom. Either way, this will override the focus behavior.
		});
```

**Comment by liamcain** [comment]
> Yes indeed that is a little intrusive and I removed it

I don't see that change yet on your branch. Did you forget to push?

**Comment by davidlandry93** [comment]
Thanks for the advice. Still no luck though, you can see what I tried here:

https://github.com/davidlandry93/obsidian-desk/blob/master/deskview.tsx#L36

With this my handler doesn't fire when I press escape (if I try to print a console log inside).

Did I miss something?
I don't mind that behavior too much though, if it's difficult to go around it I would be happy to publish as is.

**Comment by liamcain** [comment]
You should be registering to the view's scope.

```
this.escapeHandler = this.app.scope.register([], 'Escape', () => { });
```

Change to:

```
this.escapeHandler = this.scope.register([], 'Escape', () => { });
```

Since it's on the view scope, you wouldn't need to unregister it either.

**Comment by davidlandry93** [comment]
Hello Liam, sorry for the delay

I implemented your suggestion but it gives an error message:

```
app.js:1 Failed to open view TypeError: Cannot read properties of undefined (reading 'register')
```

I tried to update my `obsidian` dependency to the latest version. I inspected my view object but could not find a scope property?

You can see what I tried here: 
https://github.com/davidlandry93/obsidian-desk/blob/d9d4c286ae1ea0f31f30d91f0c0e5b5200bf7572/deskview.tsx#L38

Sorry again for the delay, and thanks for any help
David

**Pull request merged**
