### PR TITLE
Added Conditional Random Note Plugin

### PR DESCRIPTION
**Pull request by yizeshen7**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/yizeshen7/obsidian-conditional-random-note

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["Sample Plugin"](https://github.com/yizeshen7/obsidian-conditional-random-note/blob/b66887c1c453c8a705f09e27d7ef3ecebf09afae/main.ts#L20)
I don't think that this is the correct name.

[file.stat.ctime](https://github.com/yizeshen7/obsidian-conditional-random-note/blob/b66887c1c453c8a705f09e27d7ef3ecebf09afae/main.ts#L33)
Depending on the operating system this might be 0, just something to keep in mind.

[ribbonIconEl.addClass("my-plugin-ribbon-class");](https://github.com/yizeshen7/obsidian-conditional-random-note/blob/b66887c1c453c8a705f09e27d7ef3ecebf09afae/main.ts#L47)
Remove this if you are not using any CSS.

[if (typeof Number(value) == "number") {](https://github.com/yizeshen7/obsidian-conditional-random-note/blob/b66887c1c453c8a705f09e27d7ef3ecebf09afae/main.ts#L113)
You should notify the user in case they input a invalid value.
You also only need to save if its valid.

**Comment by yizeshen7** [comment]
Hm accidentally deleted my plugin entry it seems like, @joethei @liamcain wonder if there is a way I can roll back?

**Comment by liamcain** [comment]
@yizeshen7 
The easiest way is probably run `git fetch origin  && git reset --hard origin/master` on your fork of `obsidianmd/obsidian-releases` and just add the plugin to the end of the list.

**Comment by yizeshen7** [comment]
@liamcain Perfect thanks Liam! Was able to update, let me know if there is anything else you all need :).

**Comment by liamcain** [comment]
Hi @yizeshen7, have you tried contributing to the Smart Random Note plugin at all? <https://github.com/erichalldev/obsidian-smart-random-note>. Seems like your plugin has similar goals with slightly different features.

- [word.path.includes(this.settings.destinationFolder)](https://github.com/yizeshen7/obsidian-conditional-random-note/blob/36dd53db3a0f0e35df6b56d905416680e0f5d275/main.ts#L29-L30) Instead of `includes`, this should probably be `startsWith` to avoid bugs
- [const FolderFiles = files.filter((word) =>](https://github.com/yizeshen7/obsidian-conditional-random-note/blob/36dd53db3a0f0e35df6b56d905416680e0f5d275/main.ts#L28-L29) Style nit: I recommend lowercasing keeping variables lowercase and only using uppercase/pascalcase for class names.
- [// When registering intervals, this function will automatically clear the interval when the plugin is disabled.](https://github.com/yizeshen7/obsidian-conditional-random-note/blob/36dd53db3a0f0e35df6b56d905416680e0f5d275/main.ts#L55-L58) You can remove this

**Comment by ericaxu** [comment]
@yizeshen7 Hi! Do you still intend to submit this plugin? Thanks!

**Comment by joethei** [comment]
Closing PR due to inactivity.

Feel free to reopen this PR if you still intend on submitting this plugin.

**Pull request closed without merging**
