### PR TITLE
Plugin Html Server

### PR DESCRIPTION
**Pull request by Pr0dt0s**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [https://github.com/Pr0dt0s/obsidian-html-server](https://github.com/Pr0dt0s/obsidian-html-server)

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[stopButton.style.color = 'var(--text-accent)';](https://github.com/Pr0dt0s/obsidian-html-server/blob/35dc678f40dc6e72508bc9300a5e62b77b93f9ae/src/plugin/uiSetup.ts#L37-L38)
You should avoid assigning styles via JavaScript and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets.

[invalidPortElement.innerHTML =](https://github.com/Pr0dt0s/obsidian-html-server/blob/35dc678f40dc6e72508bc9300a5e62b77b93f9ae/src/plugin/settings/settingsTab.ts#L70-L71)
I know this specific instance is not problemantic, but please [avoid `innerHTML`](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%60innerHTML%60%2C+%60outerHTML%60+and+%60insertAdjacentHTML%60)

**Comment by Pr0dt0s** [comment]
Hi @joethei, Thanks for the review, I just released a new version with the requested changes, please let me know if there is anything else needed to be able to publish the plugin.

**Comment by liamcain** [comment]
- [await new Promise<void>((resolve) =>](https://github.com/Pr0dt0s/obsidian-html-server/blob/9c7c9a0510174c7de43bfd9be2bbb2e5fc5f14b5/src/plugin/main.ts#L17-L19) Looks like this is an attempt to delay the onload until the workspace is finished loading. Don't do this. If there's anything in your onload that needs to happen after the workspace is ready, move it into a thunk inside the onLayoutReady call. But don't delay the onload from completing. Plugins are initialized in series, so any delay where will delay loading other plugins and cause the whole startup to be slower.
- [stopButton](https://github.com/Pr0dt0s/obsidian-html-server/blob/9c7c9a0510174c7de43bfd9be2bbb2e5fc5f14b5/src/plugin/uiSetup.ts#L35) I would suggest just adding your own css classname here, as joethei suggested above.

**Comment by Pr0dt0s** [comment]
Hi @liamcain, I just submitted a new version on my git repo that addressed the requested changes.

Thanks again for the feedback!, and should anything be changed please let me know.

**Pull request merged**
