### PR TITLE
Community Plugin: Language Translator

### PR DESCRIPTION
**Pull request by twentytwokhz**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/twentytwokhz/language-translator

## Release Checklist

- [x] I have tested this on Windows, macOS, and Linux _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/twentytwokhz/language-translator/blob/a77c5461559f5f8c9f135d6dcf96eb1d1d8f8575/src/main.ts#L58
We don't recommend setting default hotkeys because it might conflict with something the user already set for something else.

**Comment by Taitava** [comment]
> https://github.com/twentytwokhz/language-translator/blob/a77c5461559f5f8c9f135d6dcf96eb1d1d8f8575/src/main.ts#L58 We don't recommend setting default hotkeys because it might conflict with something the user already set for something else.

Not only related to this particular plugin, but my opinion is that it would be nice if Obsidian could prevent introducing a new hotkey, if a user has already defined the hotkey to do something else. This would concern both plugins and new versions of Obsidian that introduce new default hotkeys. I have opened [a feature request about it in the forums](https://forum.obsidian.md/t/omit-new-default-hotkeys-if-a-hotkey-is-already-in-use/26380).

Now that you mentioned that assigning default hotkeys is not recommended, I'd also like to suggest that this recommendation would be present in the API documentation in the following places:

- https://github.com/obsidianmd/obsidian-api/blob/5687a75ecfdb78b6a832127cf6f9229e27e196a0/obsidian.d.ts#L1296-L1298
- https://github.com/obsidianmd/obsidian-api/blob/5687a75ecfdb78b6a832127cf6f9229e27e196a0/obsidian.d.ts#L466-L469

Thanks. 🙂

**Comment by lishid** [comment]
Agreed yeah, we'll figure something out!

**Comment by lishid** [comment]
Ok, I have implemented both of your suggestions and they will be live in the app and API in the next release.

**Pull request merged**
