### PR TITLE
Added obsidian-obligator to the community-plugins.json

### PR DESCRIPTION
**Pull request by Newbrict**
As the title states.

# I am submitting a new Community Plugin

## Repo URL

[Link to my plugin](https://github.com/Newbrict/obsidian-obligator)

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Newbrict** [comment]
Closing and re-opening to trigger a new automated check.

**Comment by joethei** [comment]
If there is more than one `.ts` file, I generally recommend moving all code files into a separate `src` folder, that makes it easier to review and maintain.

[containerEl.createEl('h2', {text: 'Daily Note Settings'});](https://github.com/Newbrict/obsidian-obligator/blob/66f9ab02f8f58495dc64309115350f7b0ce8ed51/main.ts#L181)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[const notes_folder = this.app.vault.getAbstractFileByPath(this.settings.note_path);](https://github.com/Newbrict/obsidian-obligator/blob/66f9ab02f8f58495dc64309115350f7b0ce8ed51/main.ts#L45)
You should use the `normalizePath` function before using paths defined by users.

**Comment by Newbrict** [comment]
> If there is more than one `.ts` file, I generally recommend moving all code files into a separate `src` folder, that makes it easier to review and maintain.
> 
> [containerEl.createEl('h2', {text: 'Daily Note Settings'});](https://github.com/Newbrict/obsidian-obligator/blob/66f9ab02f8f58495dc64309115350f7b0ce8ed51/main.ts#L181) [Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)
> 
> [const notes_folder = this.app.vault.getAbstractFileByPath(this.settings.note_path);](https://github.com/Newbrict/obsidian-obligator/blob/66f9ab02f8f58495dc64309115350f7b0ce8ed51/main.ts#L45) You should use the `normalizePath` function before using paths defined by users.

I have adjusted the code according to this feedback, thanks.

**Comment by Newbrict** [comment]
I have just updated my app to release tag 1.2.0, which improves the function and fixes some small bugs.
I also resolved the merge conflict from the other plugin additions.

Thanks.

**Comment by Newbrict** [comment]
@joethei Should I be fixing the merge conflict on the `community-plugins.json` file or just leave it until you guys are ready to merge? It's only because other projects are being merged in.

**Comment by joethei** [comment]
we will take care of the merge conflicts one the reviews are done.

**Pull request merged**
