### PR TITLE
Add plugin: 新枝Newledge

### PR DESCRIPTION
**Pull request by SeekerandLo**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/DepartingAgain/obsidian-newledge

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[this.settings.syncing = false;](https://github.com/DepartingAgain/obsidian-newledge/blob/1e81813a344e17a50d3f8f367a7d0563cffd9cca/src/main.ts#L56-L58)
Why are you modifying the settings here?
They should not be updated here, as onunload is guaranteed to be called.

[containerEl.createEl("h1", { text: "新枝Newledge" });](https://github.com/DepartingAgain/obsidian-newledge/blob/1e81813a344e17a50d3f8f367a7d0563cffd9cca/src/setting.ts#L56)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by SeekerandLo** [comment]
Thank you for your feedback @joethei 

---
> [this.settings.syncing = false;](https://github.com/DepartingAgain/obsidian-newledge/blob/1e81813a344e17a50d3f8f367a7d0563cffd9cca/src/main.ts#L56-L58) Why are you modifying the settings here? They should not be updated here, as onunload is guaranteed to be called.

[The sync method of the plugin is a loop logic](https://github.com/DepartingAgain/obsidian-newledge/blob/1.0.0/src/main.ts#L142), and I want to use the `enable`  to ensure that the loop can be exited in a timely manner when the user disables the plugin.
The `syncing` parameter is used to ensure that the sync method can still execute normally when the user starts the plugin again.

---


> [containerEl.createEl("h1", { text: "新枝Newledge" });](https://github.com/DepartingAgain/obsidian-newledge/blob/1e81813a344e17a50d3f8f367a7d0563cffd9cca/src/setting.ts#L56) [Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

Fixed.

**Comment by SeekerandLo** [comment]
hello @joethei ，Is there anything else I need to do?

**Comment by SeekerandLo** [comment]
Hello @joethei,
Is there anything else I need to improve or refine? Also, could you give me an estimate of when this PR might be merged?
Thank you very much for your review and feedback!

**Comment by SeekerandLo** [comment]
hello @joethei 
When can merge this PR? It's been two weeks without any news...
Thank you very much for your review and feedback!

**Comment by liamcain** [comment]
Hi, the plugin looks good to me! Your usage of `enable` and `syncing` seems okay. Because I didn't have the right permissions on this branch, I rebased and merged your plugin here: https://github.com/obsidianmd/obsidian-releases/commit/38d424ebed538bc19784805c29fb59dce8b9403a

**Pull request closed without merging**
