### PR TITLE
Adding Multi-Column Markdown to community-plugins.

### PR DESCRIPTION
**Pull request by ckRobinson**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [Here](https://github.com/ckRobinson/multi-column_markdown)

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/ckRobinson/multi-column_markdown/blob/69ad38ab5d6f92f6896a848a3deba82bd814649c/src/main.ts#L34
Here you don't need to use an `editorCheckCallback`, and the third parameter is already the markdown view (which you don't really use anyway). Just use a regular `editorCallback`

**Comment by lishid** [comment]
Hmm why not just use the repo name "multi-column-markdown" instead of "multi-column_markdown"?

**Comment by ckRobinson** [comment]
You're right that would make it more consistent. I believe the "_" was inserted automatically by github when creating the repo with a space in the title and I just didn't notice or think of that. If I was to update the repo url should I open a new PR with the change?

**Comment by lishid** [comment]
Yup!

**Comment by ckRobinson** [comment]
PR created #769. Thanks!

**Pull request merged**
