### PR TITLE
Add advanced codeblock plugin

### PR DESCRIPTION
**Pull request by lijyze**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/lijyze/obsidian-advanced-codeblock

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lijyze** [comment]
Thanks for you review. I have finished correction.

1. Rename plugin name to `ObsidianAdvancedCodeblockPlugin`

2. Delete anything concerns setting.

3. This README is copy from another plugin of mine, now already change this line to right description.

**Comment by lijyze** [comment]
I was set tag name to `101` by mistake, I have already change id to `1.0.1`, but I don't know how to make checker rerun.

**Comment by liamcain** [comment]
https://github.com/lijyze/obsidian-advanced-codeblock/blob/05e75a5f6c2616b5bb9b8a445c98256eedf96cdf/src/postProcessor.ts#L20 So I'm _pretty_ sure it's safe to assume this is always non-null. But I'd still suggest that you add another guard here since `getActiveViewOfType(MarkdownView)` can return `null` if there's no active file.

**Comment by lijyze** [comment]
Thank you, that's how it looks now.

```ts
const origin = app.workspace
  .getActiveViewOfType(MarkdownView)
  ?.editor.getLine(codeBlock.lineStart)
  .slice(3);

// not specify anything or no active view
if (!origin) return null;
```

**Pull request merged**
