### PR TITLE
Add plugin: Docxer

### PR DESCRIPTION
**Pull request by Developer-Mike**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/Developer-Mike/obsidian-docxer

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "Import Word files into obsidian. Adds a preview mode for .docx files and the ability to convert them to markdown (.md) files.",](https://github.com/Developer-Mike/obsidian-docxer/blob/f50502cd7141376b3c1aeb53c4f6fcd5e665c22e/manifest.json#L6)
Remove the "into obsidian" part.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[.setName("Delete file after conversion")](https://github.com/Developer-Mike/obsidian-docxer/blob/f50502cd7141376b3c1aeb53c4f6fcd5e665c22e/src/settings.ts#L29-L30)
You should mention which file gets deleted here, it's not obvious if you mean the source file or the generated one.

[.setName("Attachments Folder")](https://github.com/Developer-Mike/obsidian-docxer/blob/f50502cd7141376b3c1aeb53c4f6fcd5e665c22e/src/settings.ts#L41), [.setName("Custom Attachments Folder")](https://github.com/Developer-Mike/obsidian-docxer/blob/f50502cd7141376b3c1aeb53c4f6fcd5e665c22e/src/settings.ts#L59)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[import * as path from "path";](https://github.com/Developer-Mike/obsidian-docxer/blob/f50502cd7141376b3c1aeb53c4f6fcd5e665c22e/src/utils.ts#L2)
This import is available from a Node.js runtime, which means that this will throw errors on Mobile (that's a problem since you have `isDesktopOnly` marked as `false` in your manifest.json file.)

[currentFolder = path.join(currentFolder, folder);](https://github.com/Developer-Mike/obsidian-docxer/blob/f50502cd7141376b3c1aeb53c4f6fcd5e665c22e/src/utils.ts#L19)
Just join them with a `/`.

[const markdownService = new NodeHtmlMarkdown();](https://github.com/Developer-Mike/obsidian-docxer/blob/f50502cd7141376b3c1aeb53c4f6fcd5e665c22e/src/filetypes/docx.ts#L42-L43)
Use the `htmlToMarkdown` function from the Obsidian API.

**Comment by Developer-Mike** [comment]
Fixed 👍🏻

**Comment by liamcain** [comment]
- [import * as path from "path";](https://github.com/Developer-Mike/obsidian-docxer/blob/42c96cf2b0d7c3dd31137ee9af338b2dc80efab6/src/filetypes/convertable-file-view.ts#L2) you never fixed this. You still have isDesktopOnly: false but this import will fail on mobile.

**Comment by Developer-Mike** [comment]
Fixed 👍🏻

**Comment by joethei** [comment]
["minAppVersion": "0.15.0",](https://github.com/Developer-Mike/obsidian-docxer/blob/83ba9f64e497b24e80da3a94cace787bf096a83b/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

**Comment by Developer-Mike** [comment]
Fixed

**Pull request merged**
