### PR TITLE
Add Memorization Plugin to Obsidian Plugins

### PR DESCRIPTION
**Pull request by nwindian**
Please switch to **Preview** and select one of the following links:

* [Community Plugin](?template=plugin.md)

---

# I am submitting a new Community Plugin
Repo URL
Link to my plugin: https://github.com/nwindian/Memorization-Plugin

Release Checklist
 - [x] I have tested the plugin on
     - [x] Windows
     - [x] macOS
     - [ ] Linux
     - [ ] Android (if applicable)
     - [ ] iOS (if applicable)
 - [x] My GitHub release contains all required files
     - [x] main.js
     - [x] manifest.json
     - [x] styles.css (optional)
     - [x] GitHub release name matches the exact version number specified in my manifest.json (Note: Use the exact version number, don't include a prefix v)

 - [x] The id in my manifest.json matches the id in the community-plugins.json file.

 - [x] My README.md describes the plugin's purpose and provides clear usage instructions.

 - [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls. (💡 See below)
    Note: I do use adapter in my project. But only twice to check if a file/folder exists. I decided to continue with this change, but will of course open to feedback from the reviewer.

 - [x] I have added a license in the LICENSE file.

 - [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.

### CODE REVIEW

**Comment by joethei** [comment]
Please fill the pull request template

**Comment by nwindian** [comment]
@joethei Filled out the template 👍

**Comment by joethei** [comment]
["description": "This is an index card plugin for memorizing your notes. This plugin utilizes a spaced repetion (SM-2) algorithm.",](https://github.com/nwindian/Memorization-Plugin/blob/6c90e4fe5af8b606ce20ada9fae63c8c3811edf6/manifest.json#L6)
We have recently published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This is a plugin" in your description.

Your Readme should contain some screenshots.

[const files =  this.app.vault.getMarkdownFiles()](https://github.com/nwindian/Memorization-Plugin/blob/6c90e4fe5af8b606ce20ada9fae63c8c3811edf6/main.ts#L70-L94)
This code is duplicated from above, you should move this into a function.

[containerEl.createEl('h2', {text: 'Settings'});](https://github.com/nwindian/Memorization-Plugin/blob/6c90e4fe5af8b606ce20ada9fae63c8c3811edf6/main.ts#L175)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)


[this.contentEl.style.height = '500px'](https://github.com/nwindian/Memorization-Plugin/blob/6c90e4fe5af8b606ce20ada9fae63c8c3811edf6/src/Modals/PromptModal.ts#L61)
You should avoid assigning styles via JavaScript or in HTML and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets.

[const originalFile = this.app.vault.getAbstractFileByPath(this.originalTitle)](https://github.com/nwindian/Memorization-Plugin/blob/6c90e4fe5af8b606ce20ada9fae63c8c3811edf6/src/StudyNote.ts#L40-L41)
You should check first if `originalFile instanceof TFile`, instead of blindly casting.

In general I would recommend creating a custom view for your plugin, instead of modifying a note, which is a hacky way achieve this.
<https://docs.obsidian.md/Plugins/User+interface/Views>

**Comment by nwindian** [comment]
@joethei Thanks for the feedback 👍 . 
Regarding the recommendation to use a view instead of a note - I actually didn't think it was hacky. I experimented with both a view and a note and I ended up preferring the latter because I thought it was helpful to have my "index cards" stored as notes that I could see and also I'd see them in my graph view under the same tag.

**Comment by nwindian** [comment]
@joethei I updated the repo according to your comments (except for changing the notes to a view).

**Pull request merged**
