### PR TITLE
Add plugin: New Window

### PR DESCRIPTION
**Pull request by ibash**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:https://github.com/ibash/obsidian-new-window

## Release Checklist
- [X] I have tested the plugin on
  - [ ]  Windows
  - [X]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [X] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by ibash** [comment]
Changed

**Comment by joethei** [comment]
["description": "Enables opening new windows.",](https://github.com/ibash/obsidian-new-window/blob/f204bc07b49e5535fa660482eab797cf424cf9cb/manifest.json#L6)
You can already open new windows: <https://help.obsidian.md/User+interface/Pop-out+windows>, the description should describe what is different from the core implementation.

[obsidian-main.js](https://github.com/ibash/obsidian-new-window/blob/f204bc07b49e5535fa660482eab797cf424cf9cb/obsidian-main.js)
This file is taken from our installer, remove it from the repo completely.

**Comment by ibash** [comment]
Updated!

**Comment by joethei** [comment]
Update your readme and describe the differences between the core implementation and your plugin in more detail.
Also remove all information that is not meant for end-users.

The `obsidian-main.js` file is also still available in the git history.

**Pull request closed without merging**
