### PR TITLE
Add plugin: LLM workspace

### PR DESCRIPTION
**Pull request by ofalvai**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/ofalvai/obsidian-llm-workspace

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [X]  macOS
  - [X]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [X] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by ofalvai** [comment]
/skip I fixed some of the findings [here](https://github.com/ofalvai/obsidian-llm-workspace/pull/85), but there are a few false positives I believe:

> [[1](https://github.com/ofalvai/obsidian-llm-workspace/blob/d7b785e05c038571a8ae2064a9b4b3ca8e4cd7ef/src/main.ts#L156)]:The command name should not include the plugin name.

This command name intentionally includes the plugin name, it would sound weird without it.

> [[1](https://github.com/ofalvai/obsidian-llm-workspace/blob/d7b785e05c038571a8ae2064a9b4b3ca8e4cd7ef/src/config/settings.ts#L199)]:You should avoid assigning styles via JavaScript or in HTML and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets.

It sets a single CSS rule and it's not meant to be styleable by themes and snippets.

**Comment by joethei** [comment]
[new Setting(containerEl)](https://github.com/ofalvai/obsidian-llm-workspace/blob/b774913e3b8d599be873925d19d62584f8e769cb/src/config/settings.ts#L60-L62)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by ofalvai** [comment]
@joethei fixed here: https://github.com/ofalvai/obsidian-llm-workspace/commit/5ab1f68bc44416951f90357683be2687bf549852

Should I cut a new release before the plugin gets approved? The changes since 1.0.0 have been accumulating on `main` so far.

**Comment by joethei** [comment]
[# Obsidian LLM Workspace](https://github.com/ofalvai/obsidian-llm-workspace/blob/5ab1f68bc44416951f90357683be2687bf549852/README.md?plain=1#L1C1-L1C25)
Naming something "Obsidian xyz" is reserved for first party products we create, please change this header.

And yes, please create a new release

**Comment by ofalvai** [comment]
@joethei here you go: https://github.com/ofalvai/obsidian-llm-workspace/releases

**Pull request merged**
