### PR TITLE
Add plugin: NotesOn Publish

### PR DESCRIPTION
**Pull request by shapkinaa**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
[link to repo](https://github.com/shapkinaa/noteson-obsidian-plugin/blob/main/manifest.json)
https://github.com/shapkinaa/noteson-obsidian-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by shapkinaa** [comment]
Hi!
Why doesn't merge work, all the checks seem to have passed?

Sorry, Google Translate

**Comment by shapkinaa** [comment]
> [Copyright (c) 2022 Jon Grythe Stødle](https://github.com/shapkinaa/noteson-obsidian-plugin/blob/e67675a72062576e53080d32cdc90ede498d635b/LICENSE#L3) Update this, and please credit the person who created the plugin your code is based on.
> 
> [id: 'noteson.action.create',](https://github.com/shapkinaa/noteson-obsidian-plugin/blob/e67675a72062576e53080d32cdc90ede498d635b/main.ts#L55), [id: 'noteson.action.remove',](https://github.com/shapkinaa/noteson-obsidian-plugin/blob/e67675a72062576e53080d32cdc90ede498d635b/main.ts#L65) Don't prefix the command id with the plugin id, Obsidian will make sure that there are no conflicts with other plugins.
> 
> [resp = await fetch(url, {](https://github.com/shapkinaa/noteson-obsidian-plugin/blob/e67675a72062576e53080d32cdc90ede498d635b/src/http.ts#L21-L25) Use the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.
> 
> [const resp_body = await resp.text();](https://github.com/shapkinaa/noteson-obsidian-plugin/blob/e67675a72062576e53080d32cdc90ede498d635b/src/http.ts#L33-L36) And this should be `resp.json()` then.
> 
> [const file = app.vault.getAbstractFileByPath(path);](https://github.com/shapkinaa/noteson-obsidian-plugin/blob/e67675a72062576e53080d32cdc90ede498d635b/src/modals.ts#L14) It's highly discouraged that you use the global app instance in your plugin. It's currently accessible from the global context for debugging purposes, and might be removed in the future. Instead, you should use the reference to App that you have from your plugin instance.
> 
> [const baseUrl = "http://noteson.ru:8000";](https://github.com/shapkinaa/noteson-obsidian-plugin/blob/e67675a72062576e53080d32cdc90ede498d635b/src/noteson.ts#L4) This should use `https`

Fix all

**Comment by shapkinaa** [comment]
Hi!
Why doesn't merge work, all the checks seem to have passed?

Sorry, Google Translate

**Comment by joethei** [comment]
Merging is manual, and the automated check that validates plugins has some issues sometimes.

**Pull request merged**
