### PR TITLE
Added Crumbs plugin

### PR DESCRIPTION
**Pull request by tgrosinger**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/tgrosinger/crumbs-obsidian

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by tgrosinger** [comment]
Just a draft, I'll work on checking more of these boxes!

**Comment by tgrosinger** [comment]
> ❌ The newly added entry is not at the end, or you are submitting on someone else's behalf. Last plugin in the list is: sbquinlan/obsidian-handlebars

That's true. I put it by my other plugins 🙃

**Comment by joethei** [comment]
Please put it at the end, that is how we sort by age at the moment.

**Comment by tgrosinger** [comment]
Please let me know what is blocking this from being merged now. Thank you

**Comment by liamcain** [comment]
Hey @tgrosinger, sorry for the long wait! Looks like a really cool plugin. I'm glad to see someone exploring the dot-delimited file hierarchy.

**Pull request merged**
