### PR TITLE
Add plugin: Dynamic Text Concealer

### PR DESCRIPTION
**Pull request by mattcoleanderson**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by mattcoleanderson** [comment]
> [[1](https://github.com/mattcoleanderson/obsidian-dynamic-text-concealer/blob/8be3eab3dd8efaed1141cfef3ab2f841fa4d5209/src/markdownPostProcessors/conceal-post-processor.ts#L17)][[2](https://github.com/mattcoleanderson/obsidian-dynamic-text-concealer/blob/8be3eab3dd8efaed1141cfef3ab2f841fa4d5209/src/markdownPostProcessors/conceal-post-processor.ts#L25)][[3](https://github.com/mattcoleanderson/obsidian-dynamic-text-concealer/blob/8be3eab3dd8efaed1141cfef3ab2f841fa4d5209/src/markdownPostProcessors/conceal-post-processor.ts#L30)]:Using `innerHTML`, `outerHTML` or similar API's is a security risk. Instead, use the DOM API or the Obsidian helper functions: https://docs.obsidian.md/Plugins/User+interface/HTML+elements

/skip
[[1](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%60innerHTML%60%2C+%60outerHTML%60+and+%60insertAdjacentHTML%60)] Per Obsidian documentation:

> Building DOM elements from user-defined input, using innerHTML, outerHTML and insertAdjacentHTML can pose a security risk.

The keyword that separates my use case and the recommended rationale is **_user-defined input_**. However, my plugins is not using **_user-defined input_** to build the DOM with `innerHTML`. 

My use case is to wrap the original HTML of a line around a capture group matched by a given REGEX. Meaning, `innerHTML` only receives input of HTML that is already present in the matched line of the note and nothing more. It is not being used to build **new** DOM objects, but to remove unwanted parts. Therefore, a malicious should not be able to feasibly take advantage of my use case for `innerHTML`.

This is the only way I can conceive of to retain **formatting** and **wiki links** of the line during the concealment of the matched capture group. The recommended approach given in the documentation is for creating new DOM elements, not for replacing parts of current elements.

If you have suggestions, I'd love to hear them. However, I feel confident this doesn't pose a security risk.

**Comment by mattcoleanderson** [comment]
> [[1](https://github.com/mattcoleanderson/obsidian-dynamic-text-concealer/blob/8be3eab3dd8efaed1141cfef3ab2f841fa4d5209/src/main.ts#L101)]:Remember to rename the sample classes to something that makes sense to your plugin. If there are any errors, Obsidian will spit out this class name, so this will be important for users to debug if they need to.

Done. I've removed the linked class as it wasn't in use and I've given the main plugin a more specific name: `ConcealPlugin` -> `DynamicTextConcealPlugin`

**Comment by joethei** [comment]
[console.log('Unloading Obsidian ure Conceal Plugin');](https://github.com/mattcoleanderson/obsidian-dynamic-text-concealer/blob/fbfbbbddafd6c2a02f5432b0c40566206e6d6430/src/main.ts#L98)
Typo.

[text: 'List of Community Made Regex',](https://github.com/mattcoleanderson/obsidian-dynamic-text-concealer/blob/fbfbbbddafd6c2a02f5432b0c40566206e6d6430/src/settingsTab.ts#L29)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by mattcoleanderson** [comment]
> [console.log('Unloading Obsidian ure Conceal Plugin');](https://github.com/mattcoleanderson/obsidian-dynamic-text-concealer/blob/fbfbbbddafd6c2a02f5432b0c40566206e6d6430/src/main.ts#L98) Typo.
> 
> [text: 'List of Community Made Regex',](https://github.com/mattcoleanderson/obsidian-dynamic-text-concealer/blob/fbfbbbddafd6c2a02f5432b0c40566206e6d6430/src/settingsTab.ts#L29) [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

Done and Done

**Comment by mattcoleanderson** [comment]
> * [Obsidian Clozure Conceal Plugin](https://github.com/mattcoleanderson/obsidian-dynamic-text-concealer/blob/de231fc56dbd2e1f65dd35dacc3ec5ceab8d0728/src/main.ts#L98) I don't think that's what your plugin is named 🤔
> * [this.saveSettings](https://github.com/mattcoleanderson/obsidian-dynamic-text-concealer/blob/de231fc56dbd2e1f65dd35dacc3ec5ceab8d0728/src/main.ts#L99) you shouldn't need to save settings on unload

Good catch. That was the original name I had for the plugin. I've updated it and removed the save on unload.

**Pull request merged**
