### PR TITLE
Flexible Pomo Obsidian

### PR DESCRIPTION
**Pull request by grassbl8d**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/grassbl8d/flexible-pomo-obsidian

## Release Checklist

- [x] I have tested this on Windows, macOS, and Linux _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by grassbl8d** [comment]
Fixed merge conflict.

**Comment by lishid** [comment]
https://github.com/grassbl8d/flexible-pomo-obsidian/blob/b15a62dbc02d51e423c2022054f2464239606b0a/src/main.ts#L27
This doesn't need to be async.

https://github.com/grassbl8d/flexible-pomo-obsidian/blob/b15a62dbc02d51e423c2022054f2464239606b0a/src/main.ts#L48
It doesn't seem that you're actually using the active leaf for anything. For this, you're probably good with just a regular callback rather than a checkCallback. Same for your other commands,

https://github.com/grassbl8d/flexible-pomo-obsidian/blob/b15a62dbc02d51e423c2022054f2464239606b0a/src/main.ts#L89
Here, you aren't properly performing your check according to the checkCallback conditions. This is your conditional check that should be making a difference on whether you return true or false.

https://github.com/grassbl8d/flexible-pomo-obsidian/blob/b15a62dbc02d51e423c2022054f2464239606b0a/src/main.ts#L218
Remember to stop the playback of your audio here as well.

**Comment by grassbl8d** [comment]
Great, Thanks for this !

I'll handle them within the week. 

Thank You!

**Comment by grassbl8d** [comment]
Hi @lishid 

Thank you for your review. Please see below.


> https://github.com/grassbl8d/flexible-pomo-obsidian/blob/b15a62dbc02d51e423c2022054f2464239606b0a/src/main.ts#L27
> This doesn't need to be async.

Removed async already.

> https://github.com/grassbl8d/flexible-pomo-obsidian/blob/b15a62dbc02d51e423c2022054f2464239606b0a/src/main.ts#L218
> Remember to stop the playback of your audio here as well.

The whitenoise player is already stopping the white noise inside the quittimer method.

https://github.com/grassbl8d/flexible-pomo-obsidian/blob/b15a62dbc02d51e423c2022054f2464239606b0a/src/timer.ts#L154


Also addressed the callbacks and other stuff. 



THanks!

**Comment by lishid** [comment]
Apologies for the long wait. I have merged your PR but I would still advise you to move the white noise audio to a different plugin. It doesn't really need to fit into this plugin, and the way you're managing its state (in my opinion) is error prone and is likely to accidentally cause unintended resource leaks.

Either way, congratulations!

**Comment by grassbl8d** [comment]
Oh great ! @lishid 

More power ! You made some really great software. Thanks

**Pull request merged**
