### PR TITLE
Request to add Soomda plugin

### PR DESCRIPTION
**Pull request by michaellee**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/michaellee/soomda

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by michaellee** [comment]
> #### Hello!
> **I found the following issues in your plugin submission**
> 
> **Warnings:**
> 
> ⚠️ Your repository does not include a license. It is generally recommended for open-source projects to have a license. Go to https://choosealicense.com/ to compare different open source licenses.
> 
> This check was done automatically. Do NOT open a new PR for re-validation. Instead, to trigger this check again, make a change to your PR and wait a few minutes, or close and re-open it.

🤦🏻‍♂️ I thought I had added a LICENSE when creating this PR. I've now added one.

**Comment by joethei** [comment]
What sets your plugin appart from the other plugins that allow hiding the sidebar/panes?

Why is this marked as desktop only?

[addIcon('icon', icon);](https://github.com/michaellee/soomda/blob/fbfb065299c19a94e6b22f44a6c73bba2f47bb52/main.ts#L27)
Would recommend naming the icon `soomda`, `icon` is too generic.

[id: 'soomda-show-sidebars',](https://github.com/michaellee/soomda/blob/fbfb065299c19a94e6b22f44a6c73bba2f47bb52/main.ts#L39)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.


---

As an aside not using semicolons in JavaScript/TypeScript code can lead to rare, hard to debug issues, here is a pretty good article about it:
<https://flaviocopes.com/javascript-automatic-semicolon-insertion>

**Comment by michaellee** [comment]
Hey @joethei Johannes, thanks for taking your time to review my plugin!

> What sets your plugin apart from the other plugins that allow hiding the sidebar/panes?

I didn't realize there were other plugins that did similar things. I did try searching for plugins prior to building this and didn't see anything that stuck out as doing this.

I basically wanted something that toggled the sidebars both at the same time.

One thing I added was an option to remember which pane was last open. In case people don't want for both sidebars to be toggled, but instead be "aware" of last preferred sidebar.

> Why is this marked as desktop only?

Wasn't aware that there were sidebars in mobile? I'm guessing there might be in tablets? Can definitely add support later, I just don't have a tablet to test on at the moment.

Hence why I opted for desktop only.

> Would recommend naming the icon soomda, icon is too generic.

Thanks for calling this out, I've updated this.

> Obsidian will automatically prefix the command id with the plugin id, you don't need to include it yourself.

Noted, I've updated.

> As an aside not using semicolons in JavaScript/TypeScript code can lead to rare

Great article! Not sure if it's too convincing, but a good reminder to run code through formatter. I've run it through Prettier now so that my `"` and `'` are consistent and semi colons are now there :)

Again, thanks, for taking the time to help. Let me know if there's anything else.

**Comment by liamcain** [comment]
> > Would recommend naming the icon soomda, icon is too generic.
> Thanks for calling this out, I've updated this.

joethei's comment here was that the icon name is too generic. It's a bit confusing since the other things are automatically prefixed, but icons are actually all added to the same collection and aren't namespaced. So it would be better to name this something more specific to avoid it overlapping with other plugins.

**Pull request merged**
