### PR TITLE
add speed reader plugin

### PR DESCRIPTION
**Pull request by zetechnomancer**
A plugin that allows you to speed read your notes
Repo URL
https://github.com/zetechnomancer/obsidian-reader

Release Checklist
  I have tested the plugin on

- [X]   Windows
- [ ]   macOS
- [ ]   Linux

- [ ]   Android (if applicable)
- [ ]   iOS (if applicable)

  My GitHub release contains all required files
  main.js
  manifest.json

GitHub release name matches the exact version number specified in my manifest.json
The id in my manifest.json matches the id in the community-plugins.json file.
My README.md describes the plugin's purpose and provides clear usage instructions.
I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.

I have added a license in the LICENSE file.
My project respects and is compatible with the original license of any code from other plugins that I'm using.
I have given proper attribution to these other projects in my README.md.

### CODE REVIEW

**Comment by joethei** [comment]
Please follow the pull request template.

**Comment by zetechnomancer** [comment]
> Please follow the pull request template.

Is this better ?

**Comment by joethei** [comment]
["description": "This is speed reading plugin for Obsidian",](https://github.com/zetechnomancer/obsidian-reader/blob/a13336dbb8fd4d42dffa9de90c7262669222f54a/manifest.json#L6)
We have recently published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This is a plugin for Obsidian" in your description.

["author": "The technomander",](https://github.com/zetechnomancer/obsidian-reader/blob/a13336dbb8fd4d42dffa9de90c7262669222f54a/manifest.json#L7)
I think you have a small typo in your name here.

[// Remember to rename these classes and interfaces!](https://github.com/zetechnomancer/obsidian-reader/blob/a13336dbb8fd4d42dffa9de90c7262669222f54a/main.ts#LL10)
You can remove this comment.

[interval: string | number | NodeJS.Timeout | undefined;](https://github.com/zetechnomancer/obsidian-reader/blob/a13336dbb8fd4d42dffa9de90c7262669222f54a/main.ts#LL24)
This will break on mobile, as Node.js is not available there.

[// When registering intervals, this function will automatically clear the interval when the plugin is disabled.](https://github.com/zetechnomancer/obsidian-reader/blob/a13336dbb8fd4d42dffa9de90c7262669222f54a/main.ts#L47-L50)
Remove this code.



[containerEl.createEl("h2", {](https://github.com/zetechnomancer/obsidian-reader/blob/a13336dbb8fd4d42dffa9de90c7262669222f54a/main.ts#L122-L124)
- [Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)
- [Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

**Comment by ericaxu** [comment]
Hi there, to keep things tidy, we're going to temporarily close plugin PRs after a month of inactivity.

Feel free to tell us to re-open it when you're ready to continue. Thanks for your understanding!

**Pull request closed without merging**
