### PR TITLE
Add plugin: Dinox Sync

### PR DESCRIPTION
**Pull request by ryzencool**
# I am submitting a new Community Plugin
 ## Repo URL
 Link to my plugin: https://github.com/ryzencool/dinox-sync
 
 ## Release Checklist
 * [x]  I have tested the plugin on
   
   * [x]   Windows
   * [x]   macOS
   * [x]   Linux
   * [ ]   Android _(if applicable)_
   * [ ]   iOS _(if applicable)_
 * [x]  My GitHub release contains all required files
   
   * [x]  `main.js`
   * [x]  `manifest.json`
   * [x]  `styles.css` _(optional)_
 * [x]  GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
 * [x]  The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
 * [x]  My README.md describes the plugin's purpose and provides clear usage instructions.
 * [x]  I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
 * [x]  I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
 * [x]  I have added a license in the LICENSE file.
 * [x]  My project respects and is compatible with the original license of any code from other plugins that I'm using.
   I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Review by ryzencool — COMMENTED** [review]
1

**Comment by joethei** [comment]
["minAppVersion": "0.15.0",](https://github.com/ryzencool/dinox-sync/blob/db2d7850a593e1a28ccda8664d7149b0915cfc86/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

[const resp = await fetch(](https://github.com/ryzencool/dinox-sync/blob/db2d7850a593e1a28ccda8664d7149b0915cfc86/main.ts#L37)
Use the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

[setName("Dinox Token")](https://github.com/ryzencool/dinox-sync/blob/db2d7850a593e1a28ccda8664d7149b0915cfc86/main.ts#L130), [.setName("Allow Auto Synchronize")](https://github.com/ryzencool/dinox-sync/blob/db2d7850a593e1a28ccda8664d7149b0915cfc86/main.ts#L144)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[console.log(value);](https://github.com/ryzencool/dinox-sync/blob/db2d7850a593e1a28ccda8664d7149b0915cfc86/main.ts#L137), [console.log("Switch toggled to " + value);](https://github.com/ryzencool/dinox-sync/blob/db2d7850a593e1a28ccda8664d7149b0915cfc86/main.ts#L150)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.


[this.fetchData().then(() => {](https://github.com/ryzencool/dinox-sync/blob/db2d7850a593e1a28ccda8664d7149b0915cfc86/main.ts#L78)
[prefer async/await over Promise](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Prefer%20async/await%20over%20Promise)

**Comment by ryzencool** [comment]
@joethei what should I do next step？

**Comment by joethei** [comment]
You haven't made all the requested changes, and there are some more places in your code with unnecessary `console.log` and not all of the strings are using sentence case either.

**Pull request closed without merging**
