### PR TITLE
Add Emerald theme

### PR DESCRIPTION
**Pull request by gracejoseph1236**
# I am submitting a new Community Theme

## Repo URL

Link to my theme: https://github.com/gracejoseph1236/obsidian-emerald

## Theme checklist

- [x] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo)
  - [x] `obsidian.css`
  - [x] The screenshot file
- [x] I have indicated which modes (dark, light, or both) are compatible with my theme
- [x] I have added a license in the LICENSE file

### CODE REVIEW

**Comment by claremacrae** [comment]
Hi, this is great.

In case it helps, I just noticed one small thing...

## Observation

In the edited file, there is this text:

> "branch": "main"

But looking at your repo, it looks like the branch is called "master"



These need to be consistent.

## Background

Until a year or two ago, the standard branch name was almost always "master", but now more and more repos are using "main" instead.

## What to do

Anyways, because the name of your branch in your theme repo is "master", you will either need to do one of:

- delete that `"branch": "main"` text from your edit, or 
- change the branch name in your changes to be "master"

The text in the pull-request template says:

> If my repo is not using the master branch, please indicate in community-themes.json with "branch": "main".

This suggests that deleting that line may be best...

Anyway, whatever you decide to do, you can do this by adding another commit to your patch-2 branch, and pushing additional the change. It will automatically then get included in this pull request.

I hope this helps.

**Comment by gracejoseph1236** [comment]
I just edited this one and removed that line

**Comment by claremacrae** [comment]
Did you do this?

> Anyway, whatever you decide to do, you can do this by adding another commit to your patch-2 branch, and pushing additional the change. It will automatically then get included in this pull request.

**Comment by gracejoseph1236** [comment]
> When you created this pull request, did you edit “community-css-themes.json” directly on the GitHub web site?

yeah

**Comment by claremacrae** [comment]
> Now there’s just one more tiny change to make… when you delete the last block in that file, you need to remove the comma at the end of the previous line…

What I meant was to delete the comma at the end of this bit:

> "modes": ["dark"],

**Pull request merged**
