### PR TITLE
Add plugin: Scribe

### PR DESCRIPTION
**Pull request by Mikodin**
# I am submitting Scribe a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/Mikodin/obsidian-scribe

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[Api](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/index.ts#L81), [Api](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/index.ts#L83), [Api](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/settings/settings.ts#L45), [.setName('AssemblyAI Api Key')](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/settings/settings.ts#L60)
All characters in `API` are always capitalized

['Scribe: 🎙️ Recording Started'](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/index.ts#L101), ['Scribe: ▶️🎙️ Resuming Recording'](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/index.ts#L111), ['Scribe: ⏸️🎙️ Recording Paused'](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/index.ts#L114), ['Scribe: 🛑️ Recording Cancelled'](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/index.ts#L120), [`Scribe: ✅ Audio File saved ${recordingFile.name}`](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/index.ts#L240), [`Scribe: 🎧 Beginning Transcription w/ ${this.settings.transcriptPlatform}`,](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/index.ts#L248), [`Scribe: 🎧 Completed Transcription  w/ ${this.settings.transcriptPlatform}`,](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/index.ts#L262), [new Notice('Scribe: 🧠 Sending to LLM to Summarize');](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/index.ts#L277), [new Notice('Scribe: 🧠 LLM Summation complete');](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/index.ts#L283-L284), [.setName('Open AI Api Key')](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/settings/settings.ts#L45), ['You can find this in your OpenAI Dev Console](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/settings/settings.ts#L47), [.setName('AssemblyAI Api Key')](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/settings/settings.ts#L60), ['You can find this in your AssemblyAI Dev Console](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/settings/settings.ts#L62), [.setName('LLM Model for creating the Summary')](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/settings/settings.ts#L105), [.setName('Transcript Platform:  Your audio is uploaded to this service')](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/settings/settings.ts#L118), [item.setTitle('🕹️ Open Controls');](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/ribbon/ribbon.ts#L27), [item.setTitle('🛑🎙️ Stop Recording');](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/ribbon/ribbon.ts#L37), [item.setTitle('🎙️ Start Recording');](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/ribbon/ribbon.ts#L44), [LLM Model for creating the Summary](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/modal/components/ModalSettings.tsx#L40), [Transcript Platform](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/modal/components/ModalSettings.tsx#L56), [name: 'Begin Recording',](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/commands/commands.ts#L14), [name: 'Transcribe & Summarize Current File',](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/commands/commands.ts#L22), [name: 'Fix Mermaid Chart',](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/commands/commands.ts#L32)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)


[new Notice('Scribe: 🧠 LLM Summation complete');](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/index.ts#L283-L284)
Looks like you made a typo here.

[export function formatForFilename(input: string): string {](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/util/fileUtils.ts#L143-L162)
Obsidian has the `normalizePath` function for this.

[const statusBarItemEl = plugin.addStatusBarItem();](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/ribbon/ribbon.ts#L18-L19)
Remove this sample code.

[item.setTitle('🕹️ Open Controls');](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/ribbon/ribbon.ts#L27), [item.setTitle('🛑🎙️ Stop Recording');](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/ribbon/ribbon.ts#L37), [item.setTitle('🎙️ Start Recording');](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/ribbon/ribbon.ts#L44)
Instead of the emojis, use the `setIcon` function on the menu items instead.

**Comment by Mikodin** [comment]
> [Api](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/index.ts#L81), [Api](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/index.ts#L83), [Api](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/settings/settings.ts#L45), [.setName('AssemblyAI Api Key')](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/settings/settings.ts#L60) All characters in `API` are capitalized
> 
> ['Scribe: 🎙️ Recording Started'](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/index.ts#L101), ['Scribe: ▶️🎙️ Resuming Recording'](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/index.ts#L111), ['Scribe: ⏸️🎙️ Recording Paused'](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/index.ts#L114), ['Scribe: 🛑️ Recording Cancelled'](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/index.ts#L120), [`Scribe: ✅ Audio File saved ${recordingFile.name}`](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/index.ts#L240), [`Scribe: 🎧 Beginning Transcription w/ ${this.settings.transcriptPlatform}`,](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/index.ts#L248), [`Scribe: 🎧 Completed Transcription w/ ${this.settings.transcriptPlatform}`,](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/index.ts#L262), [new Notice('Scribe: 🧠 Sending to LLM to Summarize');](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/index.ts#L277), [new Notice('Scribe: 🧠 LLM Summation complete');](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/index.ts#L283-L284), [.setName('Open AI Api Key')](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/settings/settings.ts#L45), ['You can find this in your OpenAI Dev Console](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/settings/settings.ts#L47), [.setName('AssemblyAI Api Key')](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/settings/settings.ts#L60), ['You can find this in your AssemblyAI Dev Console](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/settings/settings.ts#L62), [.setName('LLM Model for creating the Summary')](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/settings/settings.ts#L105), [.setName('Transcript Platform: Your audio is uploaded to this service')](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/settings/settings.ts#L118), [item.setTitle('🕹️ Open Controls');](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/ribbon/ribbon.ts#L27), [item.setTitle('🛑🎙️ Stop Recording');](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/ribbon/ribbon.ts#L37), [item.setTitle('🎙️ Start Recording');](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/ribbon/ribbon.ts#L44), [LLM Model for creating the Summary](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/modal/components/ModalSettings.tsx#L40), [Transcript Platform](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/modal/components/ModalSettings.tsx#L56), [name: 'Begin Recording',](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/commands/commands.ts#L14), [name: 'Transcribe & Summarize Current File',](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/commands/commands.ts#L22), [name: 'Fix Mermaid Chart',](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/commands/commands.ts#L32) [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)
> 
> [new Notice('Scribe: 🧠 LLM Summation complete');](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/index.ts#L283-L284) Looks like you made a typo here.
> 
> [export function formatForFilename(input: string): string {](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/util/fileUtils.ts#L143-L162) Obsidian has the `normalizePath` function for this.
> 
> [const statusBarItemEl = plugin.addStatusBarItem();](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/ribbon/ribbon.ts#L18-L19) Remove this sample code.
> 
> [item.setTitle('🕹️ Open Controls');](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/ribbon/ribbon.ts#L27), [item.setTitle('🛑🎙️ Stop Recording');](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/ribbon/ribbon.ts#L37), [item.setTitle('🎙️ Start Recording');](https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/ribbon/ribbon.ts#L44) Instead of the emojis, use the `setIcon` function on the menu items instead.

Thank you for the feedback 🙏 
I've applied all the changes, thanks for the push on using `setIcon` on the menu
I didn't realize that they only render on mobile 👌

**Comment by joethei** [comment]
You missed a couple, mostly in the sentence case section.
And the `formatForFilename` function was also not removed.

**Comment by Mikodin** [comment]
> You missed a couple, mostly in the sentence case section. And the `formatForFilename` function was also not removed.

Thanks @joethei !  Got all the sentence cases and replaced `formatForFilename` with `normalizePath`
🚀

**Comment by joethei** [comment]
I don't see any changes for 5 of the UI strings,

**Comment by Mikodin** [comment]
> I don't see any changes for 5 of the UI strings,

🤔 Hmm, maybe I am misunderstanding the change being asked
It's for sentence casing right?

https://github.com/Mikodin/obsidian-scribe/commit/9be0961c4fdaecf486c63b5a5c3e070d5340ebd5#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R248

https://github.com/Mikodin/obsidian-scribe/commit/9be0961c4fdaecf486c63b5a5c3e070d5340ebd5#diff-9c9d24790e2b8d4f03202dc4d12f8918030d8398322460bb5dd2b74a06a369edR45

https://github.com/Mikodin/obsidian-scribe/commit/9be0961c4fdaecf486c63b5a5c3e070d5340ebd5#diff-9c9d24790e2b8d4f03202dc4d12f8918030d8398322460bb5dd2b74a06a369edR60

And then the settings pane
image

**Comment by Mikodin** [comment]
> I don't see any changes for 5 of the UI strings,

@joethei 
🤔 Hmm, maybe I am misunderstanding the change being asked
It's for sentence casing right?

Sorry for the back and forth, thank you for the review and patience

https://github.com/Mikodin/obsidian-scribe/commit/9be0961c4fdaecf486c63b5a5c3e070d5340ebd5#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R248

https://github.com/Mikodin/obsidian-scribe/commit/9be0961c4fdaecf486c63b5a5c3e070d5340ebd5#diff-9c9d24790e2b8d4f03202dc4d12f8918030d8398322460bb5dd2b74a06a369edR45

https://github.com/Mikodin/obsidian-scribe/commit/9be0961c4fdaecf486c63b5a5c3e070d5340ebd5#diff-9c9d24790e2b8d4f03202dc4d12f8918030d8398322460bb5dd2b74a06a369edR60

And then the settings pane
image

**Comment by joethei** [comment]
- https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/modal/components/ModalSettings.tsx#L40
- https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/commands/commands.ts#L22
- https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/modal/components/ModalSettings.tsx#L56
- https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/commands/commands.ts#L14
- https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/commands/commands.ts#L32

These also need to use sentence case.

**Comment by Mikodin** [comment]
> * https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/modal/components/ModalSettings.tsx#L40
> * https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/commands/commands.ts#L22
> * https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/modal/components/ModalSettings.tsx#L56
> * https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/commands/commands.ts#L14
> * https://github.com/Mikodin/obsidian-scribe/blob/933904b26453e4db09dc0ee31dbe70af4471f976/src/commands/commands.ts#L32
> 
> These also need to use sentence case.

@joethei 
Wow, I'm blind! 😂 

Updated - thank you 

https://github.com/Mikodin/obsidian-scribe/commit/159848cf3a42ca7c84bc8808d7185efaca38ddaa
https://github.com/Mikodin/obsidian-scribe/commit/10c22bb16ee543fe48ade07876630164973ba502

**Pull request merged**
