### PR TITLE
Add plugin: Marker PDF to MD

### PR DESCRIPTION
**Pull request by L3-N0X**
Added my new plugin obsidian-marker which can convert PDFs to rich Markdown, embedding images and recognizing tables, headings and more! Also works on mobile!

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [obsidian-marker](https://github.com/L3-N0X/obsidian-marker)

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[ocr using the marker api",](https://github.com/L3-N0X/obsidian-marker/blob/9be2dc54b07c59071693037402429d677b83093a/manifest.json#L6)
Please make sure that you are using the correct capitalization.

[// Remember to rename these classes and interfaces!](https://github.com/L3-N0X/obsidian-marker/blob/9be2dc54b07c59071693037402429d677b83093a/main.ts#L13)
Remove this comment.

[console.log('active file:', activeFile);](https://github.com/L3-N0X/obsidian-marker/blob/9be2dc54b07c59071693037402429d677b83093a/main.ts#L138), [console.log('folder:', folder);](https://github.com/L3-N0X/obsidian-marker/blob/9be2dc54b07c59071693037402429d677b83093a/main.ts#L161-L163), [console.log('existing file:', existingFile);](https://github.com/L3-N0X/obsidian-marker/blob/9be2dc54b07c59071693037402429d677b83093a/main.ts#L309), [console.log('created file:', file);](https://github.com/L3-N0X/obsidian-marker/blob/9be2dc54b07c59071693037402429d677b83093a/main.ts#L315)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[const content = await this.app.vault.read(file);](https://github.com/L3-N0X/obsidian-marker/blob/9be2dc54b07c59071693037402429d677b83093a/main.ts#L366-L368)
Use the `processFrontmatter` function for this., this will make sure you don't break the existing frontmatter in the process.

[private base64ToArrayBuffer(base64: string): ArrayBuffer {](https://github.com/L3-N0X/obsidian-marker/blob/9be2dc54b07c59071693037402429d677b83093a/main.ts#L426-L433)
This is already a function exported by the Obsidian API, with the same name even.

[// header for the settings tab](https://github.com/L3-N0X/obsidian-marker/blob/9be2dc54b07c59071693037402429d677b83093a/main.ts#L459-L460)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[button.setButtonText('Test Connection').onClick(() => {](https://github.com/L3-N0X/obsidian-marker/blob/9be2dc54b07c59071693037402429d677b83093a/main.ts#L476)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by L3-N0X** [comment]
Hi,
I've now made all the suggested changes and added a eslint rule so I wont forget to remove my temporary console.logs!
I have a question regarding the bot recommendations, I use fetch() in my plugin and I want it to be also useable on mobile. Should I move to requestUrl for my requests or can I stick with fetch() ? In my testing, all worked fine on mobile and I didn't had CORS errors + I didn't managed to use the requestUrl() function for my case because it wont take my formData Object and it doesn't work with a string.

**Comment by joethei** [comment]
It's just a recommendendation, mainly there because a lot of people when they experience CORS issues opt for using a proxy, which is not privacy friendly.

**Comment by L3-N0X** [comment]
Ah okay, thanks for the info and big thanks for merging my plugin!

**Pull request merged**
