### PR TITLE
Added O365 to Obsidian events import plugin

### PR DESCRIPTION
**Pull request by ksdaniel**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/ksdaniel/office2obsidian

## Release Checklist
- [ ] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by liamcain** [comment]
- [MyPlugin](https://github.com/ksdaniel/office2obsidian/blob/9a00df35152bc8cbb84222c45e53aba7f2b0eb1c/main.ts#L24) nitpick: you might want to give a better name to your plugin class
- [this.registerDomEvent(document, "click", (evt: MouseEvent) => {](https://github.com/ksdaniel/office2obsidian/blob/9a00df35152bc8cbb84222c45e53aba7f2b0eb1c/main.ts#L71-L73) remove this
- [this.registerInterval(](https://github.com/ksdaniel/office2obsidian/blob/9a00df35152bc8cbb84222c45e53aba7f2b0eb1c/main.ts#L76-L78) remove this
- [user?.name](https://github.com/ksdaniel/office2obsidian/blob/9a00df35152bc8cbb84222c45e53aba7f2b0eb1c/main.ts#L111) you don't need the ? when you've already checked that user exists.
- [safeStorage](https://github.com/ksdaniel/office2obsidian/blob/9a00df35152bc8cbb84222c45e53aba7f2b0eb1c/TokenCachePlugin.ts#L2) You don't need to bundle your own version of electron remote (I think it's a pretty big package). Instead, you can just access it from the window object (I don't think it's exported via the API, so you'll just need to ts-ignore it), but you can use window.electron.remote.safeStorage.

**Comment by joethei** [comment]
Hi @ksdaniel,
I just wanted to confirm that you've seen Liams comment with the requested changes.
Do you still intend on submitting this plugin?

**Comment by ksdaniel** [comment]
@joethei - yeah, was caught up with some other stuff - will get back to making the changes and do a new PR next week.

**Comment by ericaxu** [comment]
Hi there, to keep things tidy, we're going to temporarily close plugin PRs after a month of inactivity.

Feel free to tell us to re-open it when you're ready to continue. Thanks for your understanding!

**Pull request closed without merging**
