### PR TITLE
Add plugin: Chinese Calendar

### PR DESCRIPTION
**Pull request by DevilRoshan**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[app: App;](https://github.com/DevilRoshan/obsidian-lunar-calendar/blob/dd073fda344a8bd938c9c094bd3be492b58a85bd/src/main.ts#L10)
It's highly discouraged that you use the global app instance in your plugin. It's currently accessible from the global context for debugging purposes, and might be removed completely in a future release. Instead, you should use the reference to App that you have from your plugin instance.

[moment: () => Moment;](https://github.com/DevilRoshan/obsidian-lunar-calendar/blob/dd073fda344a8bd938c9c094bd3be492b58a85bd/src/main.ts#L11), [import moment from "moment";](https://github.com/DevilRoshan/obsidian-lunar-calendar/blob/dd073fda344a8bd938c9c094bd3be492b58a85bd/src/component/Calendar.tsx#L5)
Import moment like this: `import {moment} from "obsidian;" instead

[this.app.workspace](https://github.com/DevilRoshan/obsidian-lunar-calendar/blob/dd073fda344a8bd938c9c094bd3be492b58a85bd/src/main.ts#L78-L80)
Do not detach leaves with your custom view in `onunload`, this is an antipattern, see: <https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Don't+detach+leaves+in+%60onunload%60>

[containerEl.createEl("h3", { text: noteConfigItem.title });](https://github.com/DevilRoshan/obsidian-lunar-calendar/blob/dd073fda344a8bd938c9c094bd3be492b58a85bd/src/view/SettingView.tsx#L71)
For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```

**Comment by DevilRoshan** [comment]
@joethei Fixed all issues.

**Comment by joethei** [comment]
[app: App](https://github.com/DevilRoshan/obsidian-lunar-calendar/blob/f32eb132b981a740cf935697ec42521a1395d759/src/main.ts#L9)
This was not fixed.

**Comment by DevilRoshan** [comment]
> [app: App app：应用](https://github.com/DevilRoshan/obsidian-lunar-calendar/blob/f32eb132b981a740cf935697ec42521a1395d759/src/main.ts#L9) This was not fixed.此问题未修复。

done

**Comment by joethei** [comment]
[(leaf) => (this.view = new CalendarView(leaf))](https://github.com/DevilRoshan/obsidian-lunar-calendar/blob/de33e29394e184f881a2e3ee64d7ce9b1ece39c3/src/main.ts#L23)
[Avoid managing references to custom views](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+managing+references+to+custom+views)

**Comment by DevilRoshan** [comment]
> [(leaf) => (this.view = new CalendarView(leaf))](https://github.com/DevilRoshan/obsidian-lunar-calendar/blob/de33e29394e184f881a2e3ee64d7ce9b1ece39c3/src/main.ts#L23) [Avoid managing references to custom views](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+managing+references+to+custom+views)

done

**Pull request merged**
