### PR TITLE
Add plugin: SystemSculpt AI

### PR DESCRIPTION
**Pull request by SystemSculpt**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/systemsculpt/obsidian-systemsculpt-ai

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by SystemSculpt** [comment]
/skip
I haven't heard back for any update here even after I've made all the necessary updates

**Comment by joethei** [comment]
["description": "Enhance your Obsidian experience with AI-powered tools for note-taking, task management, and more.",](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/manifest.json#L4)
Don't include the word "Obsidian" here.

[const header = contentEl.createEl('h2', { text: 'Generating Title...' });](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modals.ts#L13), [const header = contentEl.createEl('h2', { text: 'Generating Task...' });](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modals.ts#L37), [.setName('Blank Template Prompt')](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/templates/settings/BlankTemplatePromptSetting.ts#L10), [name: 'Add Task',](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/tasks/TasksModule.ts#L34), [name: 'View Tasks',](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/tasks/TasksModule.ts#L42), [contentEl.createEl('h2', { text: 'Add Task' });](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/tasks/views/TaskModal.ts#L18), [.setName('Task Description')](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/tasks/views/TaskModal.ts#L30), [.setName('Tasks Location')](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/tasks/settings/TasksLocationSetting.ts#L11), [.setName('Task Prompt')](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/tasks/settings/TaskPromptSetting.ts#L10), [name: 'Record Audio Note',](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/recorder/RecorderModule.ts#L35), [name: 'Transcribe Selected File',](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/recorder/RecorderModule.ts#L42), [.setName('Transcriptions Path')](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/recorder/settings/transcriptionsPathSetting.ts#L11), [.setName('Save Transcription to File')](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/recorder/settings/saveTranscriptionToFileSetting.ts#L9), [.setName('Save Audio Clips')](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/recorder/settings/saveAudioClipsSetting.ts#L9), [.setName('Recordings Path')](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/recorder/settings/recordingsPathSetting.ts#L11), [.setName('Paste into Active Note')](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/recorder/settings/pasteOnTranscriptionSetting.ts#L9), [.setName('Copy to Clipboard')](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/recorder/settings/copyToClipboardSetting.ts#L9), [text: 'Upcoming Data Features',](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/data/DataModule.ts#L66), [name: 'Generate Title for Current Note',](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/brain/BrainModule.ts#L33), [name: 'Toggle Generation',](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/brain/BrainModule.ts#L41), [name: 'Toggle Model',](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/brain/BrainModule.ts#L50), [name: 'Change Max Tokens',](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/brain/BrainModule.ts#L63), [contentEl.createEl('h2', { text: 'Max Tokens' });](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/brain/views/MaxTokensModal.ts#L17), [.setName('Max Tokens')](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/brain/views/MaxTokensModal.ts#L20), [.setName('Default Model')](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/brain/settings/ModelSetting.ts#L15), [.setName('Max Tokens')](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/brain/settings/MaxTokensSetting.ts#L9), [.setName('Generate Title Prompt')](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/brain/settings/GenerateTitlePromptSetting.ts#L10), [.setName('General Generation Prompt')](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/brain/settings/GeneralGenerationPromptSetting.ts#L10), [text: 'Upcoming Brain Features',](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/brain/settings/BrainSettingTab.ts#L45)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[text: 'Templates Settings',](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/templates/TemplatesModule.ts#L104), [text: 'Tasks Settings',](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/tasks/settings/TasksSettingTab.ts#L20), [text: 'Recorder Settings',](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/recorder/settings/RecorderSettingTab.ts#L27), [text: 'Data Settings',](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/data/DataModule.ts#L55), [text: 'Brain Settings',](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/brain/settings/BrainSettingTab.ts#L23)
[Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings) and for section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```

[console.log('Triggering streaming completion with:');](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/templates/TemplatesModule.ts#L203-L207), [console.log('Received chunk:', chunk);](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/templates/TemplatesModule.ts#L215), [console.log('Received [DONE] marker, stopping');](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/templates/TemplatesModule.ts#L217), [console.log('Streaming completion finished');](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/templates/TemplatesModule.ts#L225), [console.log('Received [DONE] marker, stopping');](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/templates/functions/handleStreamingResponse.ts#L25), [console.log('Incomplete JSON string, waiting for more data');](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/templates/functions/handleStreamingResponse.ts#L52), [console.log('Ignoring non-data line');](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/templates/functions/handleStreamingResponse.ts#L59), [console.log('Triggering streaming continuation with:');](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/brain/functions/generateContinuation.ts#L25-L29), [console.log('Received chunk:', chunk);](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/brain/functions/generateContinuation.ts#L41), [console.log('Streaming continuation finished');](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/brain/functions/generateContinuation.ts#L52), [console.log('Received [DONE] marker, stopping');](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/brain/functions/generateContinuation.ts#L70), [console.log('Incomplete JSON string, waiting for more data');](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/brain/functions/generateContinuation.ts#L95), [console.log('Ignoring non-data line');](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/brain/functions/generateContinuation.ts#L102), [console.log('Using API Key: ', this.client.defaults.headers.Authorization);](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/api/OpenAIService.ts#L59-L61), [console.log('Using API Key: ', currentApiKey);](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/api/OpenAIService.ts#L86-L89)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[export function parseFrontMatter(content: string): FrontMatter {](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/templates/functions/parseFrontMatter.ts#L9-L39)
Don't parse the frontmatter yourself, to read the frontmatter of a file use:
`this.app.metadataCache.getFileCache(file)?.frontmatter`


[const response = await fetch(](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/modules/recorder/functions/transcribeRecording.ts#L17), [this.client = axios.create({](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/64bdbc99f5077c560483402b1b65981cbeee7bd0/src/api/OpenAIService.ts#L14)
Use the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

**Comment by SystemSculpt** [comment]
/skip
Hi, I made all the changes you requested minus a few key places where requestUrl can't cut it (the recorder / audio file being sent is extremely finicky with being used through requestUrl)

but everything else is updated and changed, including most of the requestUrl as I just mentioned

Thanks!

**Comment by joethei** [comment]
[export class UpdateModule {](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/bdb63c6a3a114fe5b1af1a52dd4859148610caa3/src/modules/update/UpdateModule.ts#L6-L37), [export function setupUpdateStatusBar(](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/bdb63c6a3a114fe5b1af1a52dd4859148610caa3/src/modules/update/updateInStatusBar.ts#L4-L28), [export async function updatePlugin(plugin: UpdateModule): Promise<void> {](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/bdb63c6a3a114fe5b1af1a52dd4859148610caa3/src/modules/update/functions/updatePlugin.ts#L7-L107)
Obsidian already has an update mechanism for plugins, remove all of this.

**Comment by SystemSculpt** [comment]
> [export class UpdateModule {](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/bdb63c6a3a114fe5b1af1a52dd4859148610caa3/src/modules/update/UpdateModule.ts#L6-L37), [export function setupUpdateStatusBar(](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/bdb63c6a3a114fe5b1af1a52dd4859148610caa3/src/modules/update/updateInStatusBar.ts#L4-L28), [export async function updatePlugin(plugin: UpdateModule): Promise {](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/bdb63c6a3a114fe5b1af1a52dd4859148610caa3/src/modules/update/functions/updatePlugin.ts#L7-L107) Obsidian already has an update mechanism for plugins, remove all of this.

@joethei just updated, removed entirely and updated the git + latest release :)

**Pull request merged**
