### PR TITLE
Add theme "Kimbie Dark"

### PR DESCRIPTION
**Pull request by devidw**
# I am submitting a new Community Theme

## Repo URL

Link to my theme: https://github.com/devidw/obsidian-kimbie-dark

## Theme checklist

- [x] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo).
  - [x] `theme.css` (https://publish.obsidian.md/hub/04+-+Guides,+Workflows,+%26+Courses/Guides/How+to+add+your+theme+to+the+community+theme+store)
  - [x] The screenshot file.
- [x] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other themes that I'm using.
      I have given proper attribution to these other themes in my `README.md`.

### CODE REVIEW

**Comment by ericaxu** [comment]
Recommendations:
1. Use a more featureful screenshot;
2. Write some things in README like features of your theme, so that other users know why they might want to use it.

**Comment by devidw** [comment]
Hey @joethei 

Apologies for missing it, thank you both for your feedback.

Just updated screenshot and README

NOTE: The material is not full-featured since it's a simple port to bring the colors to Obsidian, nothing heavy re-designed or featured, therefore just a tiny theme for those looking for a familiar color scheme.

Feel free to accept/reject.

Thanks

**Comment by joethei** [comment]
It looks like your theme was made pre Obsidian 1.0,
you should migrate it over to the new theme system, see this for more information:
<https://forum.obsidian.md/t/1-0-theme-migration-guide/42537>

**Comment by ericaxu** [comment]
Hi there, to keep things tidy, we're going to temporarily close theme PRs after a month of inactivity.

Feel free to tell us to re-open it when you're ready to continue. Thanks for your understanding!

**Pull request closed without merging**
