### PR TITLE
Add plugin: Simple File Push

### PR DESCRIPTION
**Pull request by huedaya**
Add `simple-file-push` plugin

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/huedaya/obsidian-simple-file-push

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by huedaya** [comment]
/skip The code that you mentioned is actually not being used and removed in version 0.0.2. 

https://github.com/huedaya/obsidian-simple-file-push/releases/tag/0.0.2

**Comment by joethei** [comment]
["description": "Simple file push blog plugin",](https://github.com/huedaya/obsidian-simple-file-push/blob/d36440af2b692e21a42943713410364f8dbfe01f/manifest.json#L6)
Please follow our guidelines for descriptions: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple

[if (!("extension" in file)) {](https://github.com/huedaya/obsidian-simple-file-push/blob/d36440af2b692e21a42943713410364f8dbfe01f/main.ts#L33-L35)
Check if `file instanceof TFile` instead.

[.setTitle("Sync file to my Blog")](https://github.com/huedaya/obsidian-simple-file-push/blob/d36440af2b692e21a42943713410364f8dbfe01f/main.ts#L42)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[axios.post(url, data, {](https://github.com/huedaya/obsidian-simple-file-push/blob/d36440af2b692e21a42943713410364f8dbfe01f/main.ts#L83-L88)

[containerEl.createEl("h3", { text: "Simple File Push Settings" });](https://github.com/huedaya/obsidian-simple-file-push/blob/d36440af2b692e21a42943713410364f8dbfe01f/main.ts#L124)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)
Use the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

**Comment by huedaya** [comment]
@joethei Oh okay, thanks for feedback, I will fix that tomorrow

**Comment by huedaya** [comment]
Hi @joethei, I just resolve issues you mentioned previously, kindly check. Thanks!

https://github.com/huedaya/obsidian-simple-file-push/releases/tag/0.0.3

**Comment by joethei** [comment]
[console.log('Return data:')](https://github.com/huedaya/obsidian-simple-file-push/blob/f540f9e359a38f8d73c687edb1a5b23f5ec8c017/main.ts#L98-L99)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[containerEl.createEl("h3", { text: "Plugin Settings" });](https://github.com/huedaya/obsidian-simple-file-push/blob/f540f9e359a38f8d73c687edb1a5b23f5ec8c017/main.ts#L136-L137)
[Avoid having a top-level heading in the settings tab](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by huedaya** [comment]
@joethei Oh thanks for the feedback, just updated in v0.0.4

https://github.com/huedaya/obsidian-simple-file-push/releases/tag/0.0.4

**Pull request merged**
