### PR TITLE
Add plugin: Rapid AI

### PR DESCRIPTION
**Pull request by ahmed3developer**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/ahmed3developer/rapid-ai

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Please rename the project and organization on Rapid API, naming something `Obsidian xyz` is reserved for products we create.

["minAppVersion": "0.15.0",](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

["fundingUrl": "https://rapidapi.com/obsidian-api-obsidian-api-default/api/obsidian-ai/pricing",](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/manifest.json#L9)
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link remove this.

[action: "Go to Settings",](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/main.ts#L261), [setStatus(dialog, "Internet Disconnected", "unplug");](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/main.ts#L451), ["Correct Grammar",](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/src/components/SelectionModal.ts#L129), [input_tipEnding.innerText = "to Send";](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/src/components/SelectionModal.ts#L221), [this.sendButton.innerText = "Send Message";](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/src/components/NormalModal.ts#L42), [this.sendButton.innerText = "Send Message";](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/src/components/NormalModal.ts#L111), [this.txtTestStatus.innerText = "It Works Perfctly";](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/src/components/CustomSettingsTab.ts#L112), [manageSubscription.text = "Check Usage & Manage Subscription";](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/src/components/CustomSettingsTab.ts#L143), [manageSubscription.text = "Check Usage & Manage Subscription";](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/src/components/dialogs/SettingsDialog.ts#L123), [txtTitle.innerText = "Plan Quota Limit Reached";](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/src/components/dialogs/QuotaExceededDialog.ts#L27), [manageSubscription.text = "Check Usage & Manage Subscription";](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/src/components/dialogs/QuotaExceededDialog.ts#L43), [this.upgradeButton.innerText = "Upgrade Plan";](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/src/components/dialogs/QuotaExceededDialog.ts#L51)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[setStatus(dialog, "It Works Perfctly", "badge-check");](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/main.ts#L448)
Use sentence case, also typo

[new Notice("Please the prompt");](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/main.ts#L302)
This sentence makes no sense grammatically.

["Fromat",](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/src/components/SelectionModal.ts#L144)
Typo

**Comment by ahmed3developer** [comment]
> Please rename the project and organization on Rapid API, naming something `Obsidian xyz` is reserved for products we create.
> 
> ["minAppVersion": "0.15.0",](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/manifest.json#L5) You are using newer API's, set this to the latest public build number.
> 
> ["fundingUrl": "https://rapidapi.com/obsidian-api-obsidian-api-default/api/obsidian-ai/pricing",](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/manifest.json#L9) This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link remove this.
> 
> [action: "Go to Settings",](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/main.ts#L261), [setStatus(dialog, "Internet Disconnected", "unplug");](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/main.ts#L451), ["Correct Grammar",](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/src/components/SelectionModal.ts#L129), [input_tipEnding.innerText = "to Send";](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/src/components/SelectionModal.ts#L221), [this.sendButton.innerText = "Send Message";](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/src/components/NormalModal.ts#L42), [this.sendButton.innerText = "Send Message";](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/src/components/NormalModal.ts#L111), [this.txtTestStatus.innerText = "It Works Perfctly";](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/src/components/CustomSettingsTab.ts#L112), [manageSubscription.text = "Check Usage & Manage Subscription";](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/src/components/CustomSettingsTab.ts#L143), [manageSubscription.text = "Check Usage & Manage Subscription";](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/src/components/dialogs/SettingsDialog.ts#L123), [txtTitle.innerText = "Plan Quota Limit Reached";](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/src/components/dialogs/QuotaExceededDialog.ts#L27), [manageSubscription.text = "Check Usage & Manage Subscription";](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/src/components/dialogs/QuotaExceededDialog.ts#L43), [this.upgradeButton.innerText = "Upgrade Plan";](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/src/components/dialogs/QuotaExceededDialog.ts#L51) [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)
> 
> [setStatus(dialog, "It Works Perfctly", "badge-check");](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/main.ts#L448) Use sentence case, also typo
> 
> [new Notice("Please the prompt");](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/main.ts#L302) This sentence makes no sense grammatically.
> 
> ["Fromat",](https://github.com/ahmed3developer/rapid-ai/blob/4406f17e14481d3c329ad32b81f554517aab6ca4/src/components/SelectionModal.ts#L144) Typo

Dear Johannes Theiner,
Thank you for your feedback. I have made the required changes.

**Comment by ahmed3developer** [comment]
Also updated the name of the API provider

**Comment by ahmed3developer** [comment]
any further modifications?

**Comment by joethei** [comment]
["fundingUrl": "",](https://github.com/ahmed3developer/rapid-ai/blob/6434213dfd98a372737dd939e44e3cfe50f5d088/manifest.json#L9C2-L9C19)
Remove this line

**Comment by ahmed3developer** [comment]
> ["fundingUrl": "",](https://github.com/ahmed3developer/rapid-ai/blob/6434213dfd98a372737dd939e44e3cfe50f5d088/manifest.json#L9C2-L9C19) Remove this line

@joethei 
Done

**Comment by ahmed3developer** [comment]
any further modifications @joethei ?

**Comment by ahmed3developer** [comment]
Could you check if there are any other modifications needed so we can continue adding more features? We want to keep developing it and add more features, but first, we need to ensure that it is published and already useful

@joethei

**Pull request merged**
