### PR TITLE
Add plugin Writing Goals

### PR DESCRIPTION
**Pull request by lynchjames**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/lynchjames/obsidian-writing-goals

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[Copyright (c) 2020 James Lynch](https://github.com/lynchjames/obsidian-writing-goals/blob/88f8b85babfe4d76fbf18839d187a6b01128b8cd/LICENSE#L3)
Update the year.

[this.saveData(this.settings);](https://github.com/lynchjames/obsidian-writing-goals/blob/88f8b85babfe4d76fbf18839d187a6b01128b8cd/src/main.ts#L47)
This should not be in the onload.

[import moment from "moment";](https://github.com/lynchjames/obsidian-writing-goals/blob/88f8b85babfe4d76fbf18839d187a6b01128b8cd/src/core/goal-history/history.ts#L5)
Import moment from Obsidian, no need to bundle it seperately.

**Comment by lynchjames** [comment]
Thanks for the feedback! 

I have made the amends for the 3 points raised and published in [release 0.9.4](https://github.com/lynchjames/obsidian-writing-goals/releases/tag/0.9.4).

**Comment by liamcain** [comment]
- [goalView](https://github.com/lynchjames/obsidian-writing-goals/blob/7239252b1920b98ab7cdf248000c5649d342c646/src/main.ts#L60) do not save a reference to your view on the plugin instance. If you need to access the view from the Plugin, you can fetch the View off the workspace via getLeavesOfType
- [fileOrFolder](https://github.com/lynchjames/obsidian-writing-goals/blob/7239252b1920b98ab7cdf248000c5649d342c646/src/main.ts#L212) can Folders have goals? Should this have an instanceof TFile check?

**Comment by lynchjames** [comment]
Thanks for the feedback @liamcain.

- _[goalView](https://github.com/lynchjames/obsidian-writing-goals/blob/7239252b1920b98ab7cdf248000c5649d342c646/src/main.ts#L60) do not save a reference to your view on the plugin instance. If you need to access the view from the Plugin, you can fetch the View off the workspace via getLeavesOfType_

This view reference has been removed in the latest release [0.9.5](https://github.com/lynchjames/obsidian-writing-goals/releases/tag/0.9.5).

- _[fileOrFolder](https://github.com/lynchjames/obsidian-writing-goals/blob/7239252b1920b98ab7cdf248000c5649d342c646/src/main.ts#L212) can Folders have goals? Should this have an instanceof TFile check?_

Folders can have goals so there is some code that processes files or folders. There are instanceof TFile checks in place where [code is interacting with frontmatter](https://github.com/lynchjames/obsidian-writing-goals/blob/7239252b1920b98ab7cdf248000c5649d342c646/src/IO/frontmapper-helper.ts#L47) and both instanceof TFile and instanceof TFolder checks where [code is recursively counting files within target folders](https://github.com/lynchjames/obsidian-writing-goals/blob/7239252b1920b98ab7cdf248000c5649d342c646/src/core/goal-helper.ts#L113).

**Pull request merged**
