### PR TITLE
Add plugin: Fuzzy Note Creator

### PR DESCRIPTION
**Pull request by HaloGamer33**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/HaloGamer33/Obsidian-Fuzzy-Note-Creator

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[let dirs = readdirSync(source, { withFileTypes: true })](https://github.com/HaloGamer33/Obsidian-Fuzzy-Note-Creator/blob/965ebb2c46700a92fbf7b0f12d73d35615a3f856/main.ts#L143-L145)
You should use the [Vault](https://docs.obsidian.md/Plugins/Vault) API's instead, that will make your plugin mobile compatible.

[getSuggestions(): string[] {](https://github.com/HaloGamer33/Obsidian-Fuzzy-Note-Creator/blob/965ebb2c46700a92fbf7b0f12d73d35615a3f856/main.ts#L328-L336)
These 3 methods need to be implemented in order for this modal to work properly.

[navigator.userAgent.toLowerCase().contains('windows')](https://github.com/HaloGamer33/Obsidian-Fuzzy-Note-Creator/blob/965ebb2c46700a92fbf7b0f12d73d35615a3f856/main.ts#L221), https://docs.obsidian.md/Reference/TypeScript+API/Platform
Use `Platform.isWindows` instead.

**Comment by HaloGamer33** [comment]
The requested changes were made

**Comment by joethei** [comment]
[class TAbstractExtended extends TAbstractFile {](https://github.com/HaloGamer33/Obsidian-Fuzzy-Note-Creator/blob/5a3bdd518990b7db8caf1d5fc051029beb992bd1/main.ts#L393-L396)
This is wrong, a `TAbstractFile` does not have an extension, only a `TFile` has.

[if (abstractFiles[i].extension === undefined) {](https://github.com/HaloGamer33/Obsidian-Fuzzy-Note-Creator/blob/5a3bdd518990b7db8caf1d5fc051029beb992bd1/main.ts#L145)
Instead of this check use `if (abstractFiles[i] instanceof TFolder) {`

**Comment by HaloGamer33** [comment]
The new release has implemented the fix.

**Comment by HaloGamer33** [comment]
Is there any other action that I need to take?

**Pull request merged**
