### PR TITLE
Add plugin: Solo RPG Toolkit

### PR DESCRIPTION
**Pull request by alexkurowski**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/alexkurowski/solo-toolkit

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["minAppVersion": "0.12.15",](https://github.com/alexkurowski/solo-toolkit/blob/7b91339400612ff31882c0283e80c716851eb969/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

["description": "Solo RPG toolkit for Obsidian.md",](https://github.com/alexkurowski/solo-toolkit/blob/7b91339400612ff31882c0283e80c716851eb969/manifest.json#L6)
Don't include "Obsidian" in the description.

["authorUrl": "",](https://github.com/alexkurowski/solo-toolkit/blob/7b91339400612ff31882c0283e80c716851eb969/manifest.json#L8)
This needs to be filled, you can use your GitHub profile URL.

**Comment by alexkurowski** [comment]
Updated

**Comment by joethei** [comment]
["description": "Solo RPG toolkit",](https://github.com/alexkurowski/solo-toolkit/blob/87cf19702954ffe4c648275ebc317c0ca0477608/manifest.json#L6C5-L6C39)
The description is a bit too minimal, see our guide here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple

**Comment by alexkurowski** [comment]
Updated

**Pull request merged**
