### PR TITLE
Add plugin: Alfonso Money Manager

### PR DESCRIPTION
**Pull request by smartlife-gpt**
# New Community Plugin Submission

## Repo URL
- **Link to my plugin**: [Alfonso Money Manager for Obsidian](https://github.com/smartlife-gpt/alfonso-money-manager-obsidian)

## Release Checklist
- **Compatibility Tests**:
  - [x] Windows
  - [x] macOS
  - [x] Linux

- **Files in GitHub Release**:
  - [x] `main.js`
  - [x] `manifest.json`

- **Versioning**:
  - [x] The GitHub release name matches the exact version number specified in my `manifest.json` (Note: Use the exact version number, don't include a prefix `v`).

- **Plugin ID**:
  - [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.

- **Documentation**:
  - [x] My `README.md` describes the plugin's purpose and provides clear usage instructions.

## Compliance and Quality Assurance
- [x] I have read the developer policies at [Obsidian Developer Policies](https://docs.obsidian.md/Developer+policies), and have assessed my plugin's adherence to these policies.
- [x] I have read the tips in [Obsidian Plugin Guidelines](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines) and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the `LICENSE` file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
- [x] I have given proper attribution to these other projects in my `README.md`.

---

By submitting this plugin for review, I confirm that it meets the quality and compliance standards of the Obsidian community and look forward to contributing to the ecosystem.

### CODE REVIEW

**Comment by smartlife-gpt** [comment]
/skip
i have fixed some of the issues and others are not valid. 
For example the css i use its only for displaying button or hide it dynamically with javascript.

**Comment by joethei** [comment]
Where is the `styles.css` file compiled from?

["description": "A plugin for Alfonso Money Manager to view data in obsidian",](https://github.com/smartlife-gpt/alfonso-money-manager-obsidian/blob/4dec530b417d831754721b8323e3f3fc2a8abef4/manifest.json#L6)
Avoid including sentences like "This is a plugin for Obsidian that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[await app.fileManager.processFrontMatter(file, (fm) => {](https://github.com/smartlife-gpt/alfonso-money-manager-obsidian/blob/4dec530b417d831754721b8323e3f3fc2a8abef4/src/utils.ts#L17-L19)
Use `app.metadataCache.getFileCache(file).frontmatter` instead.

[console.log("handleLocalUrl--", obUrl);](https://github.com/smartlife-gpt/alfonso-money-manager-obsidian/blob/4dec530b417d831754721b8323e3f3fc2a8abef4/src/utils.ts#L24), [console.log("find ob local file");](https://github.com/smartlife-gpt/alfonso-money-manager-obsidian/blob/4dec530b417d831754721b8323e3f3fc2a8abef4/src/utils.ts#L34)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[<div class="setting-item-name">Groyp By Period</div>](https://github.com/smartlife-gpt/alfonso-money-manager-obsidian/blob/4dec530b417d831754721b8323e3f3fc2a8abef4/src/ui/modals/QueryBuilderModal.vue#L198)
Typo and [use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[const response = await fetch("https://www.floatrates.com/daily/eur.json");](https://github.com/smartlife-gpt/alfonso-money-manager-obsidian/blob/4dec530b417d831754721b8323e3f3fc2a8abef4/src/plugin/ExchangeRateService.ts#L19)
Use the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.
Please also mention in your README why this request exists.

[buttonContainer.style.display = "none";](https://github.com/smartlife-gpt/alfonso-money-manager-obsidian/blob/4dec530b417d831754721b8323e3f3fc2a8abef4/src/plugin/CodeBlockProcessor.ts#L148), [buttonContainer.style.display = "block";](https://github.com/smartlife-gpt/alfonso-money-manager-obsidian/blob/4dec530b417d831754721b8323e3f3fc2a8abef4/src/plugin/CodeBlockProcessor.ts#L153), [buttonContainer.style.display = "none";](https://github.com/smartlife-gpt/alfonso-money-manager-obsidian/blob/4dec530b417d831754721b8323e3f3fc2a8abef4/src/plugin/CodeBlockProcessor.ts#L155)
To hide the button, call the `.hide()` function on the element instead, there is also a `.show()` method.

[id: "xxx-id",](https://github.com/smartlife-gpt/alfonso-money-manager-obsidian/blob/4dec530b417d831754721b8323e3f3fc2a8abef4/src/plugin/commands/QueryBuilderModalCommand.ts#L8)
Set a proper ID here.

[name: "Query Builder Window",](https://github.com/smartlife-gpt/alfonso-money-manager-obsidian/blob/4dec530b417d831754721b8323e3f3fc2a8abef4/src/plugin/commands/QueryBuilderModalCommand.ts#L9)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[if (!this.app.vault.getAbstractFileByPath(this.filename)) {](https://github.com/smartlife-gpt/alfonso-money-manager-obsidian/blob/4dec530b417d831754721b8323e3f3fc2a8abef4/src/database/DBLoki.ts#L31)
You should check if the result of the function is `instanceof TFile`, to make sure that it's actually a file, and not a folder.

**Comment by smartlife-gpt** [comment]
@joethei updated the repo with your notes.

**Comment by richard-kovachev** [comment]
/skip
can you check it out?

**Pull request merged**
