### PR TITLE
Add move text plugin

### PR DESCRIPTION
**Pull request by DomasB**
A simple plugin to move line or selection using keyboard shortcuts.
https://github.com/DomasB/obsidian-move-text

### CODE REVIEW

**Comment by lishid** [comment]
Just curious how this is different from the "Swap line up"/"Swap line down" hotkeys that are already present. Sounds like they're similar? They're just not bound to any keys by default.

Let me know 😄

**Comment by DomasB** [comment]
@lishid, not different at all :D
Would say that naming of the built in command is not very discoverable. When searching for this functionality the first word that comes to mind is "move" and "swap" up/down sounds a bit unnatural as a sentence.

Closing this PR.

**Comment by lishid** [comment]
Ah ok! That sounds fair. Sorry you had to go through all the trouble!

**Comment by DomasB** [comment]
No problem :) was good introduction to the API. Might write more plugins later.

**Pull request closed without merging**
