### PR TITLE
Update community-plugins.json to add pubScale

### PR DESCRIPTION
**Pull request by piriwata**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/piriwata/pubScale

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[id: "pubScale.action.publish",](https://github.com/piriwata/pubScale/blob/31f3d797581f611a1f9f965eef05fbe8861d4351/main.ts#L26)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

[editorCallback: (editor, view) => {](https://github.com/piriwata/pubScale/blob/31f3d797581f611a1f9f965eef05fbe8861d4351/main.ts#L28-L34)
use a `editorCheckCallback` instead.
<https://marcus.se.net/obsidian-plugin-docs/user-interface/commands#editor-commands>

**Comment by piriwata** [comment]
Thank you for your feedback. I have fixed in the following two commits.
- https://github.com/piriwata/pubScale/commit/053376bb7b598ba280aea31f4b435430f4e05451
- https://github.com/piriwata/pubScale/commit/05d3e1c091b12bb75bd8d16a95a225722615e881

**Comment by liamcain** [comment]
- [Enter database name](https://github.com/piriwata/pubScale/blob/cef5039bf1db943d32f1e308c16920b598e9ac26/main.ts#L177) consider using the placeholder text as an opportunity to give an example database name instead.
- [editorCheckCallback](https://github.com/piriwata/pubScale/blob/cef5039bf1db943d32f1e308c16920b598e9ac26/main.ts#L38) you might want to use [checkCallback](https://github.com/obsidianmd/obsidian-api/blob/9bb30633586c6649474b2affdf5b87efdd86498f/obsidian.d.ts#L505) instead of editorCheckCallback so that users can publish/delete notes while in Reading mode.

**Comment by piriwata** [comment]
Thanks for the review! I have committed improvements you pointed out in the following:
- https://github.com/piriwata/pubScale/commit/7037ac0a0b5a25fa443fd2de48a58fa65b2eba11
  Using examples for placeholders
- https://github.com/piriwata/pubScale/commit/143251618c176fd3a6f064821c7c4baa4f5c5aa4
  Using `checkCallback` instead of `editorCheckCallback`
- https://github.com/piriwata/pubScale/commit/42de30eb838429ba3e50d5809bdf07e80a981737
  Simplified description

**Pull request merged**
