### PR TITLE
Add plugin: Mermaid Popup

### PR DESCRIPTION
**Pull request by gitcpy**
A plugin to show mermaid diagrams in a draggable and zoomable popup

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by gitcpy** [comment]
A Plugin: Show mermaid diagrams in a draggable and zoomable popup

**Comment by gitcpy** [comment]
Tick styles.css in Checklist

**Comment by gitcpy** [comment]
{

        "id": "ai-latex-generator",
        "name": "AI LaTeX Generator",
        "description": "Convert natural language to LaTeX equations using a local LLM.",
        "author": "Aayush Shah",
        "repo": "aaaaayushh/ai-latex-generator"
    }	
    ----The conflict is that there is some config info inserted from other plugin, so I deleted it.

**Comment by joethei** [comment]
Please don't delete other plugin entries

**Comment by gitcpy** [comment]
Oh my god... The conflict shows there is some config info inserted from other plugin, what shoul I do?






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "obsidianmd/obsidian-releases"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月29日(星期四) 凌晨1:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [obsidianmd/obsidian-releases] Add plugin: Mermaid Popup (PR #4101)





 
Please don't delete other plugin entries

**Comment by joethei** [comment]
Keep it, and add your entry below

**Comment by gitcpy** [comment]
“This branch cannot be rebased due to conflicts”----------------I resolved the conflict, but it is still there. Dose it mean I have to pull request again ?

**Comment by joethei** [comment]
Please add some screenshots/GIF's on how to use your plugin.
In general, the README could be fleshed out a bit.

**Comment by gitcpy** [comment]
Thanks for your advice.
I add a gif to readme.
If there is anything the plugin required, I will try.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "obsidianmd/obsidian-releases"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月11日(星期三) 晚上6:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [obsidianmd/obsidian-releases] Add plugin: Mermaid Popup (PR #4101)





 
Please add some screenshots/GIF's on how to use your plugin.
 In general, the README could be fleshed out a bit.

**Pull request merged**
