### PR TITLE
Add plugin: Smart Memos

### PR DESCRIPTION
**Pull request by Mossy1022**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Mossy1022/smart-transcriptions

## Release Checklist
- [ X] I have tested the plugin on
  - [X]  Windows
  - [X]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Mossy1022** [comment]
Done.

**Comment by joethei** [comment]
Please add some information to your README that mentions that the plugin is using OpenAI and what data is uploaded to their servers.

[.mermaid svg {](https://github.com/Mossy1022/Smart-Transcriptions/blob/d32c5d26fba3221166e4b92c9ef6d0ccf26c2c3f/styles.css#L10-L14)
Why is this necessary in this plugin?

[new Notice('Transcript Generated... Reformatting');](https://github.com/Mossy1022/Smart-Transcriptions/blob/d32c5d26fba3221166e4b92c9ef6d0ccf26c2c3f/main.ts#L111), [.setName('Custom Transcription-To-Notes Prompt')](https://github.com/Mossy1022/Smart-Transcriptions/blob/d32c5d26fba3221166e4b92c9ef6d0ccf26c2c3f/main.ts#L399)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[const activeFile = this.app.workspace.getActiveFile();](https://github.com/Mossy1022/Smart-Transcriptions/blob/d32c5d26fba3221166e4b92c9ef6d0ccf26c2c3f/main.ts#L177-L180)
This is not the way to get the attachment dir, it's `this.app.fileManager.getAvailablePathForAttachment(filenameOfAttachment, currentFilePath)`

[this.app.vault.getFiles().forEach((file) => {](https://github.com/Mossy1022/Smart-Transcriptions/blob/d32c5d26fba3221166e4b92c9ef6d0ccf26c2c3f/main.ts#L217-L222)
[Avoid iterating all files to find a file by its path]https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+iterating+all+files+to+find+a+file+by+its+path


[containerEl.createEl('h2', {text: 'Smart Transcription Settings'});](https://github.com/Mossy1022/Smart-Transcriptions/blob/d32c5d26fba3221166e4b92c9ef6d0ccf26c2c3f/main.ts#L368)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by Mossy1022** [comment]
@joethei  To expedite this, I have resolved all the issues you described including removing the mermaids styling.  A new. release is available.

**Comment by joethei** [comment]
[apiKey: 'sk-as123mkqwenjasdasdj12...',](https://github.com/Mossy1022/Smart-Transcriptions/blob/284f167a70e5d6552ae101708ff15a1c10039259/main.ts#L11)
This should be empty and a placeholder should be used in the settings tab.

**Comment by Mossy1022** [comment]
@joethei  Just updated.  Also changed the plugin name from Smart Transcriptions to Smart Memos. Just pushed the new release so the bot should see it's valid on the next check.

**Pull request merged**
