### PR TITLE
Add plugin: Backtick text selector

### PR DESCRIPTION
**Pull request by cool-RR**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/cool-RR/backtick-text-selector

## Release Checklist
- [X] I have tested the plugin on
  - [X]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [X] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

.

### CODE REVIEW

**Comment by cool-RR** [comment]
__

**Comment by cool-RR** [comment]
@joethei Merge conflict resolved, ready for review.

**Comment by cool-RR** [comment]
@liamcain I'm playing an endless game of rebasing on this PR. What do I need to do in order to get it merged?

**Comment by liamcain** [comment]
There's no need to keep rebasing, we'll rebase it before we merge it. I'll be focused on plugin reviews later today, so I'll try my best to get to this then. Thanks for your patience!

**Comment by liamcain** [comment]
- You can remove the styles.css from the plugin and the plugin release. It's not used.
- [startPos.ch += 0.5;](https://github.com/cool-RR/backtick-text-selector/blob/80e32c35a67154a2587c2dbba8bb269621ecd898/main.js#L72) what is this for? I don't think codemirror supports fractional positions so I'm not sure where this gets rounded (if it works)
- [MyPlugin](https://github.com/cool-RR/backtick-text-selector/blob/80e32c35a67154a2587c2dbba8bb269621ecd898/main.js#L2) please change the name of your plugin. This will be helpful for users if there is an error as the class name will appear in the stack trace
- [console.log("Loading MyPlugin")](https://github.com/cool-RR/backtick-text-selector/blob/80e32c35a67154a2587c2dbba8bb269621ecd898/main.js#L4) Also change the plugin name here and in onunload

**Comment by cool-RR** [comment]
> * You can remove the styles.css from the plugin and the plugin release. It's not used.

Done.

> * [startPos.ch += 0.5;](https://github.com/cool-RR/backtick-text-selector/blob/80e32c35a67154a2587c2dbba8bb269621ecd898/main.js#L72) what is this for? I don't think codemirror supports fractional positions so I'm not sure where this gets rounded (if it works)

I'm not sure why but it didn't work properly without it. 

> * [MyPlugin](https://github.com/cool-RR/backtick-text-selector/blob/80e32c35a67154a2587c2dbba8bb269621ecd898/main.js#L2) please change the name of your plugin. This will be helpful for users if there is an error as the class name will appear in the stack trace

Done.

> * [console.log("Loading MyPlugin")](https://github.com/cool-RR/backtick-text-selector/blob/80e32c35a67154a2587c2dbba8bb269621ecd898/main.js#L4) Also change the plugin name here and in onunload

Done.

**Comment by liamcain** [comment]
Thanks!

> > [startPos.ch += 0.5;](https://github.com/cool-RR/backtick-text-selector/blob/80e32c35a67154a2587c2dbba8bb269621ecd898/main.js#L72) what is this for? I don't think codemirror supports fractional positions so I'm not sure where this gets rounded (if it works)
> 
> I'm not sure why but it didn't work properly without it.

Strange, are you sure `+=1` doesn't work?

Looks like a missed a couple more things in my review yesterday, sorry about that:
- [Select Next Backtick Text](https://github.com/cool-RR/backtick-text-selector/blob/a0110b33f05e7d88672cb5ab439cb48d360aa792/main.js#L15) This should be sentence case to match the [UI guidelines](<https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI>). So "Select next backtick text"
- [Select Previous Backtick Text](https://github.com/cool-RR/backtick-text-selector/blob/a0110b33f05e7d88672cb5ab439cb48d360aa792/main.js#L29) same here

**Comment by cool-RR** [comment]
> Thanks!
> 
> > > [startPos.ch += 0.5;](https://github.com/cool-RR/backtick-text-selector/blob/80e32c35a67154a2587c2dbba8bb269621ecd898/main.js#L72) what is this for? I don't think codemirror supports fractional positions so I'm not sure where this gets rounded (if it works)
> > 
> > 
> > I'm not sure why but it didn't work properly without it.
> 
> Strange, are you sure `+=1` doesn't work?

I spent too long debugging the different cases a while back when I wrote this. I don't remember exactly which case required the `+= 0.5`. Ideally there should be tests for this code that list out the different cases but that's more than I want to invest in this plugin.

> 
> Looks like a missed a couple more things in my review yesterday, sorry about that:
> 
> * [Select Next Backtick Text](https://github.com/cool-RR/backtick-text-selector/blob/a0110b33f05e7d88672cb5ab439cb48d360aa792/main.js#L15) This should be sentence case to match the [UI guidelines](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI). So "Select next backtick text"
> * [Select Previous Backtick Text](https://github.com/cool-RR/backtick-text-selector/blob/a0110b33f05e7d88672cb5ab439cb48d360aa792/main.js#L29) same here

Fixed.

**Comment by cool-RR** [comment]
@liamcain Bump.

**Comment by liamcain** [comment]
> I spent too long debugging the different cases a while back when I wrote this. I don't remember exactly which case required the += 0.5. Ideally there should be tests for this code that list out the different cases but that's more than I want to invest in this plugin.

Okay, I'm worried your plugin might be relying on undocumented behavior of Codemirror and therefore be more prone to break. It's fairly minor but it is still a concern.

**Comment by cool-RR** [comment]
Great, thank you!

**Pull request merged**
