### PR TITLE
Add plugin: Simple Code Formatter

### PR DESCRIPTION
**Pull request by wiop93256**
# Description

This plugin is used for code indentation beautification.

## Repo URL

Link to my plugin: https://github.com/wiop93256/Simple-Code-Formmater

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by wiop93256** [comment]
How to resolve this problem?

**Comment by wiop93256** [comment]
I cant find the different with [document](https://docs.obsidian.md/Plugins/Releasing/Submit+your+plugin).

**Comment by joethei** [comment]
["fundingUrl": "https://github.com/wiop93256/Simple-Code-Formmater",](https://github.com/wiop93256/Simple-Code-Formmater/blob/9dbb7e6ae8fe767c9ecbfbcb70d5ad30f4b3f725/manifest.json#L9)
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link remove this line.

[name: "Let's format the code block where the cursor is!",](https://github.com/wiop93256/Simple-Code-Formmater/blob/9dbb7e6ae8fe767c9ecbfbcb70d5ad30f4b3f725/main.ts#L10)
This should be "Format current code block"

[new Notice("😦No code block found!");](https://github.com/wiop93256/Simple-Code-Formmater/blob/9dbb7e6ae8fe767c9ecbfbcb70d5ad30f4b3f725/main.ts#L14), [new Notice("🎉Code block formatted!");](https://github.com/wiop93256/Simple-Code-Formmater/blob/9dbb7e6ae8fe767c9ecbfbcb70d5ad30f4b3f725/main.ts#L19), ["😂Failed to format code block! Maybe the code block contains syntax errors.\nSee the console for more information."](https://github.com/wiop93256/Simple-Code-Formmater/blob/9dbb7e6ae8fe767c9ecbfbcb70d5ad30f4b3f725/main.ts#L30)
Please remove the emoji, especially the laughing one, that's just impolite to users.

[console.log("当前光标行", cursorLine);](https://github.com/wiop93256/Simple-Code-Formmater/blob/9dbb7e6ae8fe767c9ecbfbcb70d5ad30f4b3f725/main.ts#L47), [console.log(backUp);](https://github.com/wiop93256/Simple-Code-Formmater/blob/9dbb7e6ae8fe767c9ecbfbcb70d5ad30f4b3f725/main.ts#L106), [console.log("language",language);](https://github.com/wiop93256/Simple-Code-Formmater/blob/9dbb7e6ae8fe767c9ecbfbcb70d5ad30f4b3f725/formatter/Web/web-code-formatter.mjs#L16)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

**Comment by wiop93256** [comment]
Thank you for the feedback! I've made the requested changes:

- 1. Removed the `fundingUrl line`, as I dont have a funding link to share at the moment.
- 2. Updated the **plugin name** to "Format current code block".
- 3. **Removed emojis** from the notifications to improve the user experience.
- 4. Adjusted the **console logging** to only appear in development mode.

Please let me know if there's anything else I should adjust.

Thank you for the guildance!

**Pull request merged**
