### PR TITLE
Add plugin: obsidian-ivre-plugin

### PR DESCRIPTION
**Pull request by p-l-**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/ivre/obsidian-ivre-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  ~Android _(if applicable)_~
  - [ ]  ~iOS _(if applicable)_~
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by liamcain** [comment]
- [this.app](https://github.com/ivre/obsidian-ivre-plugin/blob/d2b199e3ca750e536a21abf1a1bce7e0d0503640/main.ts#L158) this is not defined. It might be working but it's falling back to the global scope, which I don't think you should be relying on. It's currently accessible from the global context for debugging purposes, and might be removed in the future. Instead, you should use the reference to App that you have from your plugin instance and just pass that into your functions.
- [this.app](https://github.com/ivre/obsidian-ivre-plugin/blob/d2b199e3ca750e536a21abf1a1bce7e0d0503640/main.ts#L209) same thing
- [this.app](https://github.com/ivre/obsidian-ivre-plugin/blob/d2b199e3ca750e536a21abf1a1bce7e0d0503640/main.ts#L219) here too
- [this.app.vault](https://github.com/ivre/obsidian-ivre-plugin/blob/d2b199e3ca750e536a21abf1a1bce7e0d0503640/main.ts#L225) and here
- [this.app.](https://github.com/ivre/obsidian-ivre-plugin/blob/d2b199e3ca750e536a21abf1a1bce7e0d0503640/main.ts#L240) hmm, okay there's a lot of them. I won't point them all out
- [getActiveFile](https://github.com/ivre/obsidian-ivre-plugin/blob/d2b199e3ca750e536a21abf1a1bce7e0d0503640/main.ts#L792) this can return null. Also, since you're passing in a MarkdownView to this function, you should be comparing it to the view.file and not the active file
- [ivre](https://github.com/ivre/obsidian-ivre-plugin/blob/d2b199e3ca750e536a21abf1a1bce7e0d0503640/main.ts#L890) you don't need to prefix the ID with your plugin name, it will get automatically prefixed with it by the addCommand

**Comment by p-l-** [comment]
Thanks a lot for your comment @liamcain! I'm a total noob to both TypeScript & the Obsidian API. What could I use rather than `this.app`? Is there a clean way to reference the app from the global scope?

**Comment by p-l-** [comment]
@liamcain thanks a lot for your review! Sorry for all the mistakes, I'm a total noob in both TypeScript and the Obsidian API!

Hope it's better now, let me know if there are other things to fix. I'm preparing the next release.

**Comment by liamcain** [comment]
- [this.app.workspace.getActiveFile](https://github.com/ivre/obsidian-ivre-plugin/blob/5175d5d8b476b922fbb72ee1cdce7d914319916e/main.ts#L882) sorry, I might not have been clear here. I was suggesting you don't call getActiveFile. While under normal circumstances, it would be the same as the file in the MarkdownView, you don't really want to make that assumption. So I would change this line to be `view.file` (you have access to file from the FileView (<https://github.com/obsidianmd/obsidian-api/blob/38dd22168d2925086371bfc59e36fd9121527a39/obsidian.d.ts#L1372>)
- [this.app.workspace.getActiveFile](https://github.com/ivre/obsidian-ivre-plugin/blob/5175d5d8b476b922fbb72ee1cdce7d914319916e/main.ts#L935) same here.

**Comment by p-l-** [comment]
Thanks again @liamcain! That's done. Do you see something else that should be done?

**Comment by liamcain** [comment]
LGTM, merged!

**Comment by p-l-** [comment]
Thanks!

**Pull request merged**
