### PR TITLE
Update community-plugins.json adding Pivotal Tracker Integration

### PR DESCRIPTION
**Pull request by JonnyDeates**
# I am submitting a new Community Plugin, to allow for Pivotal Tracker Integration

## Repo URL

Link to my plugin: https://github.com/JonnyDeates/obsidian-pivotal-tracker-integration-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Please add your own plugin at the end of the list, and don't remove a exisiting one.

**Comment by JonnyDeates** [comment]
Fixed it to not remove one, didn't mean to do that.

**Comment by joethei** [comment]
[id: 'pivotal-tracker-retrieve-stories',](https://github.com/JonnyDeates/obsidian-pivotal-tracker-integration-plugin/blob/b849e74623cd159300864fe2d98f9aec8cf2034a/main.ts#L62)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to do it yourself.

[let unstartedStories = JSON.parse(await request(generateConfig(trackerToken, projectId, 'with_state=unstarted')));](https://github.com/JonnyDeates/obsidian-pivotal-tracker-integration-plugin/blob/b849e74623cd159300864fe2d98f9aec8cf2034a/src/apiClient.ts#L34)
You can also use `requestUrl(...).json()`

**Comment by JonnyDeates** [comment]
The id is Pivotal tracker retrieve stories, not plugin tracker retrieve stories. I swear though like I've checked it 100 times and i see plugin and not pivotal. 

Also Ill update and fix it!

**Comment by joethei** [comment]
What I mean is that you can remove the `pivotal-tracker` part from the id.
Under the hood the command id is: `pivotal-tracker-integration:pivotal-tracker-retrieve-stories`.
Obsidian adds the prefix automatically.

**Comment by liamcain** [comment]
- [Tracker User Token](https://github.com/JonnyDeates/obsidian-pivotal-tracker-integration-plugin/blob/b849e74623cd159300864fe2d98f9aec8cf2034a/main.ts#L95) consider using [Sentence case](https://en.wiktionary.org/wiki/sentence_case) for all setting names to be consistent with the Obsidian Style Guide.
- [this.app](https://github.com/JonnyDeates/obsidian-pivotal-tracker-integration-plugin/blob/b849e74623cd159300864fe2d98f9aec8cf2034a/src/writeOutputToFile.ts#L9) your function isn't scoped to a class here so `this` is falling back to `global`. We suggest you don't use the global app instance since it's really only there for debugging purposes. You should pass the `app` instance in from your plugin.
- [this.app](https://github.com/JonnyDeates/obsidian-pivotal-tracker-integration-plugin/blob/b849e74623cd159300864fe2d98f9aec8cf2034a/src/generateFilePath.ts#L5) same issue here

**Pull request merged**
