### PR TITLE
Add Auto Hyperlink

### PR DESCRIPTION
**Pull request by take6**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[mySetting: string;](https://github.com/take6/obsidian-plugin-auto-hyperlink/blob/5893e9564132b79150b84d6f8e9d9012f2a070e5/main.ts#L5)
Remove this settings, since you don't use it.

[const birdIconEl = this.addRibbonIcon('bird', 'AutoHyperlinkPlugin', (evt: MouseEvent) => {](https://github.com/take6/obsidian-plugin-auto-hyperlink/blob/5893e9564132b79150b84d6f8e9d9012f2a070e5/main.ts#L109)
I would use "Auto hyperlink" as the text instead, including "Plugin" is unnecessary.
I also don't see a reason for this ribbon icon to exist.

[containerEl.createEl('h2', {text: 'Setting for AutoHyperlink'});](https://github.com/take6/obsidian-plugin-auto-hyperlink/blob/5893e9564132b79150b84d6f8e9d9012f2a070e5/main.ts#L151)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[console.warn('JSON parse error. Falling back to default setting.');](https://github.com/take6/obsidian-plugin-auto-hyperlink/blob/5893e9564132b79150b84d6f8e9d9012f2a070e5/main.ts#L174-L175)
You should also make this visible to the user.

**Comment by take6** [comment]
Thanks @joethei for review comments. I really appreciate it.

First three comments look trivial. But the last one,

>  [console.warn('JSON parse error. Falling back to default setting.');](https://github.com/take6/obsidian-plugin-auto-hyperlink/blob/5893e9564132b79150b84d6f8e9d9012f2a070e5/main.ts#L174-L175)
> You should also make this visible to the user.

is bit complicated to me because I'm a novice in Javascript/Typescript. Having said that, I totally agree with you that it is useful message for users. Let me consider for a while how to realize what you suggested.

**Comment by take6** [comment]
Hi @joethei, I've released 0.2.0 that (hopefully) address your comments. I would appreciate it if you could review changes.

**Comment by liamcain** [comment]
- [rule: '[]'](https://github.com/take6/obsidian-plugin-auto-hyperlink/blob/e253ad25bfaf8403fbdce9096e8397ba7c21fb67/main.ts#L9) why is rule serialized to a string?
- [parse](https://github.com/take6/obsidian-plugin-auto-hyperlink/blob/e253ad25bfaf8403fbdce9096e8397ba7c21fb67/main.ts#L99) you shouldn't parse each time, just parse it once and only serialize it for saving/loading the settings.

**Comment by take6** [comment]
Thanks @liamcain for merging. And sorry for not responding your review comments. My intention to parse string each time is to notify users when given JSON string is invalid. I will consider your comments in future updates. Opened [issue](https://github.com/take6/obsidian-plugin-auto-hyperlink/issues/1) in my repository.

**Pull request merged**
