### PR TITLE
add mixa-obsidian community plugin

### PR DESCRIPTION
**Pull request by mixasite**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/mixasite/obsidian-mixa

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by mixasite** [comment]
release has both the manifest and main files, not sure why the error. Please let me know

image

**Comment by mixasite** [comment]
@sameersismail Thanks for the details, just fixed it.

**Comment by mixasite** [comment]
Please let us know if the PR needs any changes, thanks!
cc: @ericaxu

**Comment by mixasite** [comment]
Hey team, I know there are million things you’re working on right now, but it’s been over 2 weeks, is there any update on this? Please let us know, thanks 🙏 
@joethei

**Comment by joethei** [comment]
I generally recommend moving all code files into a separate `src` folder, that makes it easier to review and maintain.

["id": "mixa-obsidian",](https://github.com/mixasite/obsidian-mixa/blob/12412b226e30f708a4f43d9816b9964f152c286d/manifest.json#L2)
Don't include `obsidian` here.

[import { join } from 'path'](https://github.com/mixasite/obsidian-mixa/blob/12412b226e30f708a4f43d9816b9964f152c286d/src/sync.ts#L2-L3)
This will break on mobile, as Node.js is not used there.


As an aside not using semicolons in JavaScript/TypeScript code can lead to rare, hard to debug issues, here is a pretty good article about it:
<https://flaviocopes.com/javascript-automatic-semicolon-insertion>

**Comment by mixasite** [comment]
> I generally recommend moving all code files into a separate `src` folder, that makes it easier to review and maintain.
> 
> ["id": "mixa-obsidian",](https://github.com/mixasite/obsidian-mixa/blob/12412b226e30f708a4f43d9816b9964f152c286d/manifest.json#L2) Don't include `obsidian` here.
> 
> [import { join } from 'path'](https://github.com/mixasite/obsidian-mixa/blob/12412b226e30f708a4f43d9816b9964f152c286d/src/sync.ts#L2-L3) This will break on mobile, as Node.js is not used there.
> 
> As an aside not using semicolons in JavaScript/TypeScript code can lead to rare, hard to debug issues, here is a pretty good article about it: https://flaviocopes.com/javascript-automatic-semicolon-insertion

thanks for the feedback @joethei 

1. Moved files to `src` folder
2. id is changed to `mixa` from `mixa-obsidian`
3. added `"isDesktopOnly": true` to manifest since node environment is needed for the plugin
5. Added semicolons

Please let us know if any other change is needed

**Comment by mixasite** [comment]
hey team, it's getting close to a month and we keep resolving the conflicts every other day. We appreciate it if you can at least provide some ETA.

Thanks!
@joethei @ericaxu

**Comment by joethei** [comment]
You don't need to resolve the conflicts, we will do that before merging.
And I can't give you any ETA sorry.

**Comment by liamcain** [comment]
- [syncData](https://github.com/mixasite/obsidian-mixa/blob/19a1f0fb04aad02bf627d418c7e13ee48458915d/src/main.ts#L24) you are missing error handling here. syncData can throw an error. You should surface that to the user
- [new Notice('Publishing your site, hang tight...');](https://github.com/mixasite/obsidian-mixa/blob/19a1f0fb04aad02bf627d418c7e13ee48458915d/src/main.ts#L22) I suggest you check to see if mixa is configured before trying to publish. A nice user experience might be if the mixa isn't configured in settings, clicking the ribbon icon here could open the settings tab.
- [throw err](https://github.com/mixasite/obsidian-mixa/blob/19a1f0fb04aad02bf627d418c7e13ee48458915d/src/sync.ts#L88) this error is totally transparent to the user. This means you'll show a notice that says "your site is live" even if an error occurred.
- [Your site is live](https://github.com/mixasite/obsidian-mixa/blob/19a1f0fb04aad02bf627d418c7e13ee48458915d/src/main.ts#L25) this message implies that it's only the initial sync. Maybe something like "Changes published" would be better and more accurate.

**Comment by mixasite** [comment]
thanks for the suggestions @liamcain 

>syncData you are missing error handling here.

great catch, we added proper messaging for the ribbon icon as well.

>new Notice('Publishing your site, hang tight...');]

Added necessary messaging here as well

>throw err

this one is actually a log+rethrow, so it will not show the success message since error is thrown. caller of the `syncData` will catch it and show a proper message

>Your site is live

Fair point, we changed the message

**Pull request merged**
