### PR TITLE
Adds Zotero Desktop Connector Plugin

### PR DESCRIPTION
**Pull request by mgmeyers**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/mgmeyers/obsidian-zotero-desktop-connector

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [ ] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lishid** [comment]
Might want to disable the github workflow in your fork, and also fix the PR which got into a conflict because of the bot, sorry!

**Comment by mgmeyers** [comment]
Ah, didn't even notice! Fixed 👍

**Comment by lishid** [comment]
https://github.com/mgmeyers/obsidian-zotero-desktop-connector/blob/bf172f8115438da0211fec50dc89a2f92b7dc51f/src/annotations.ts#L74
Hi matt!

https://github.com/mgmeyers/obsidian-zotero-desktop-connector/blob/bf172f8115438da0211fec50dc89a2f92b7dc51f/src/annotations.ts#L67
Don't use `adapter as any` - check if it's FileSystemAdapter and use `getBastPath()`.

https://github.com/mgmeyers/obsidian-zotero-desktop-connector/blob/bf172f8115438da0211fec50dc89a2f92b7dc51f/src/cayw.ts#L5
Should reuse this for the other files.

**Comment by mgmeyers** [comment]
Thanks @lishid I've actually removed `annotations.ts` altogether. That was something I was playing around with that hasn't yet made it into the plugin. Good to know about `getBasePath`!

**Pull request merged**
