### PR TITLE
Add the AI Summary Community Plugin

### PR DESCRIPTION
**Pull request by irbull**
The AI Summary Plugin is a community plugin that will generate a summary of the notes referenced from the current note.  It is a great way to create weekly and monthly summaries of your notes.

This change-set adds the AI Summary Plugin to the
`community-plugins.json`.

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/irbull/obsidian-ai-summary/

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(not applicable)_
  - [x]  iOS _(not applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by irbull** [comment]
Thanks for the review. I've addressed those comments and published a new version with those changes. I've also tracked down a windows box and installed the plugin (from source) and smoke tested it there.

**Comment by irbull** [comment]
I've updated the PR to  remove the conflicts (there was a recent change to the `community-plugins.json`. Is there anything I need to do?

**Comment by liamcain** [comment]
- [extractFrontmatter(md: string): Record<string, string> {](https://github.com/irbull/obsidian-ai-summary/blob/b8fe80755821a7f48673cd2b1a39cd12a9b008a9/main.ts#L114-L129)
> You should read from Obsidian's metadata cache instead:
> 
> > this.app.metadataCache.getFileCache(file)?.frontmatter


This comment was never addressed.

**Comment by irbull** [comment]
Thanks, Sorry I must have missed that comment about the cache. I'll take a look now.

I just published a blog about Obsidian and how I use it, this was great timing :)
https://ianbull.com/posts/how-i-use-obsidian/

**Pull request merged**
