### PR TITLE
Add cMenu Plugin

### PR DESCRIPTION
**Pull request by chetachiezikeuzor**
# I am submitting a new Community Plugin: cMenu

(made edit to plugin ID)

Link to my plugin: https://github.com/chetachiezikeuzor/cMenu-Plugin

## Release Checklist

- [x] I have tested this on Windows, macOS, and Linux _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by lishid** [comment]
Not sure what happened to community themes json, but if you're submitting a theme as well, can you do it through another PR?
That way we can track issues with the submission separately, as well as preventing the merge from being blocked because the plugin/theme isn't ready.

**Comment by lishid** [comment]
Weird... Did you start working on your plugin from the `js` compiled file? It has a lot of compiled code that shouldn't really be there like `__awaiter`.

Since there isn't much, I'd highly suggest migrating your code to a fresh copy of `main.ts` from the sample plugin repo.

- Please rename the class/interface names from the sample `My...` to your plugin's name.
- Consider learning our DOM element shortcuts `parentEl.createEl/Div/Span({cls: 'css-class', text: 'inner text'});` as this would make your code a lot less verbose and easier to read.
- Use `workspace.getActiveViewOfType(MarkdownView)` instead of `activeLeaf`

**Comment by chetachiezikeuzor** [comment]
Thank you so much for the feedback! I'm not quote sure what happened with the themes json either. I forked the repo 2 months ago so I think I made an error while fetching the upstream. Once I make the necessary changes, should I just submit another pull request? Thank you!

**Comment by lishid** [comment]
You can continue to keep discussing in this PR. I think you just need to fix your fork to have just the commit adding the plugin stuff.

**Comment by chetachiezikeuzor** [comment]
Ok, I have made the necessary changes!

**Comment by ericaxu** [comment]
@lishid Please do another review, I think many in the community are eagerly waiting for this plugin! ❤️

**Comment by lishid** [comment]
https://github.com/chetachiezikeuzor/cMenu-Plugin/blob/34cafb814867564dc53ba4e35868d12f5a903c13/main.ts#L86
Use `workspace.getActiveViewOfType(MarkdownView)` here to save some work.

**Comment by chetachiezikeuzor** [comment]
Got it chief! Thanks!

**Pull request merged**
