### PR TITLE
Add plugin: Hash Pasted Image

### PR DESCRIPTION
**Pull request by hardingadonis**
# Note:

I re-create pull request again because after merge #3814, my plugin not included for release to community

---

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/hardingadonis/hash-pasted-image

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
huh, not sure what happened there.

**Comment by SH3LLco** [comment]
your latest json overlapped with my pull request and broke my validation

**Comment by hardingadonis** [comment]
u just resolve this conflict by hand

**Comment by SH3LLco** [comment]
> > your latest json overlapped with my pull request and broke my validation #3832
> 
> u just resolve this conflict by hand

i tried to, but since you pulled after me, it wouldnt let me change it. I got a verification failed error

**Comment by hardingadonis** [comment]
> i tried to, but since you pulled after me, it wouldnt let me change it. I got a verification failed error

i think it will help u

step 1:  sync master branch on your forked repository 

step 2: delete the branch that create your pull request

step 3: check out new branch that have same name that just deleted branch 

step 4: commit and re-open your pull request again

**Comment by SH3LLco** [comment]
> > i tried to, but since you pulled after me, it wouldnt let me change it. I got a verification failed error
> 
> i think it will help u
> 
> step 1: sync master branch on your forked repository
> 
> step 2: delete the branch that create your pull request
> 
> step 3: check out new branch that have same name that just deleted branch
> 
> step 4: commit and re-open your pull request again

i would, but i just made progress on my PR and it specifically said not to open a new pull request. Im gonna try to reach out to support, if no luck ill try this. I appreciate your help.

**Comment by hardingadonis** [comment]
> i would, but i just made progress on my PR and it specifically said not to open a new pull request. Im gonna try to reach out to support, if no luck ill try this. I appreciate your help.

i think u should mention who assigneed in your pr to get help

**Pull request merged**
