### PR TITLE
Add obsidian-emoji-toolbar

### PR DESCRIPTION
**Pull request by oliveryh**
Hi Obsidian creators, 

The following makes use of the current switcher to allow you to search for a insert emojis.

Let me know if you need any other changes before it can be accepted

### CODE REVIEW

**Comment by lishid** [comment]
I got a 404 when opening your repo `oliveryh/obsidian-emoji-toolbar`. Maybe it's set to a private repo?

**Comment by oliveryh** [comment]
My mistake. Made public now!

**Comment by lishid** [comment]
Weird that you have a `.ts` file but no type annotations. Might want to add them for proper type checks :)

**Comment by oliveryh** [comment]
I'm new to TS but that is my next task :) Thanks for merging.

**Comment by lishid** [comment]
Have fun!

**Pull request merged**
