### PR TITLE
Add GitHub theme

### PR DESCRIPTION
**Pull request by krios2146**
# I am submitting a new Community Theme

## Repo URL

Link to my theme: https://github.com/krios2146/obsidian-github

## Theme checklist

- [x] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo).
  - [x] `theme.css`
  - [x] The screenshot file.
- [x] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other themes that I'm using.
      I have given proper attribution to these other themes in my `README.md`.

### CODE REVIEW

**Comment by ericaxu** [comment]
One minor thing: you might want to make the screenshot smaller while keeping the 16:9 aspect ratio. That would make your theme load faster in the theme store. You can still include high resolution screenshots in your README.

We recommend using a screenshot of size 512px by 288px as the featured screenshot to minimize loading time.

**Comment by ericaxu** [comment]
> @ericaxu Summoning you to check if everything is ok

LGTM, merging!

**Comment by krios2146** [comment]
but pull request still open...
sadge

**Comment by joethei** [comment]
Not any more :)

**Comment by joethei** [comment]
@krios2146, I got a report that the theme cannot be installed.
You will have to alter the manifest file in your releases to allow Obsidian to download the theme.
The theme name has to match everywhere (here, your repo, releases in your repo)

**Comment by krios2146** [comment]
Oh, I see
Release will be updated
Thanks

**Pull request merged**
