### PR TITLE
Add Imgbb plugin

### PR DESCRIPTION
**Pull request by notmmaoo**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/notmmaoo/obsidian-imgbb-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
You can remove `obsidian` from the plugin id, its unnecessary.

[// Remember to rename these classes and interfaces!](https://github.com/notmmaoo/obsidian-imgbb-plugin/blob/352c53657e9945b5fcc3856f15091ed36db97245/main.ts#L5)
You forgot to remove this comment

[import { parse, extname } from "path";](https://github.com/notmmaoo/obsidian-imgbb-plugin/blob/352c53657e9945b5fcc3856f15091ed36db97245/main.ts#L3-L4)
[This plugin will not load on mobile](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#nodejs-and-electron-api)

[this.addRibbonIcon('dice'](https://github.com/notmmaoo/obsidian-imgbb-plugin/blob/352c53657e9945b5fcc3856f15091ed36db97245/main.ts#L33)
You probably want a different icon, you can use any icon from <https://lucide.dev/> instead.

[// This adds a status bar item to the bottom of the app. Does not work on mobile apps.](https://github.com/notmmaoo/obsidian-imgbb-plugin/blob/352c53657e9945b5fcc3856f15091ed36db97245/main.ts#L39-L41)
This feels like you forgot to remove this from the sample plugin.

[callback: () => {](https://github.com/notmmaoo/obsidian-imgbb-plugin/blob/352c53657e9945b5fcc3856f15091ed36db97245/main.ts#L46)
Move this into a `editorCallback` this will make sure that the command will only be visible if there is a active editor.
<https://marcus.se.net/obsidian-plugin-docs/user-interface/commands#editor-commands>

[extname(path)](https://github.com/notmmaoo/obsidian-imgbb-plugin/blob/352c53657e9945b5fcc3856f15091ed36db97245/main.ts#L82), [existsSync(path)](https://github.com/notmmaoo/obsidian-imgbb-plugin/blob/352c53657e9945b5fcc3856f15091ed36db97245/main.ts#L86), [readFileSync(localFile);](https://github.com/notmmaoo/obsidian-imgbb-plugin/blob/352c53657e9945b5fcc3856f15091ed36db97245/main.ts#L143)
Use the Vault API instead: <https://marcus.se.net/obsidian-plugin-docs/vault>

[const response = await fetch('https://api.imgbb.com/1/upload', {](https://github.com/notmmaoo/obsidian-imgbb-plugin/blob/352c53657e9945b5fcc3856f15091ed36db97245/main.ts#L150-L153) use the [`requestUrl`](https://github.com/obsidianmd/obsidian-api/blob/1b4f6e2e5753c8ac2d538bc5d55c38f228450cb2/obsidian.d.ts#L2887-L2892) function instead.

[SampleSettingTab](https://github.com/notmmaoo/obsidian-imgbb-plugin/blob/352c53657e9945b5fcc3856f15091ed36db97245/main.ts#L161)
You forgot to rename this.

**Comment by notmmaoo** [comment]
> You can remove obsidian from the plugin id, its unnecessary.

- [x] use `imgbb-plugin` as plugin id

> [// Remember to rename these classes and interfaces!](https://github.com/notmmaoo/obsidian-imgbb-plugin/blob/352c53657e9945b5fcc3856f15091ed36db97245/main.ts#L5)
You forgot to remove this comment

- [x] removed

> [import { parse, extname } from "path";](https://github.com/notmmaoo/obsidian-imgbb-plugin/blob/352c53657e9945b5fcc3856f15091ed36db97245/main.ts#L3-L4)
[This plugin will not load on mobile](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#nodejs-and-electron-api)

- [x] set `"isDesktopOnly": true` in `manifest,json`

> [this.addRibbonIcon('dice'](https://github.com/notmmaoo/obsidian-imgbb-plugin/blob/352c53657e9945b5fcc3856f15091ed36db97245/main.ts#L33)
You probably want a different icon, you can use any icon from https://lucide.dev/ instead.

- [x] use`upload-cloud` now.

> [// This adds a status bar item to the bottom of the app. Does not work on mobile apps.](https://github.com/notmmaoo/obsidian-imgbb-plugin/blob/352c53657e9945b5fcc3856f15091ed36db97245/main.ts#L39-L41)
This feels like you forgot to remove this from the sample plugin.

- [x] removed

> [callback: () => {](https://github.com/notmmaoo/obsidian-imgbb-plugin/blob/352c53657e9945b5fcc3856f15091ed36db97245/main.ts#L46)
Move this into a editorCallback this will make sure that the command will only be visible if there is a active editor.
https://marcus.se.net/obsidian-plugin-docs/user-interface/commands#editor-commands

- [x] use `editorCallback` instead

> [extname(path)](https://github.com/notmmaoo/obsidian-imgbb-plugin/blob/352c53657e9945b5fcc3856f15091ed36db97245/main.ts#L82), [existsSync(path)](https://github.com/notmmaoo/obsidian-imgbb-plugin/blob/352c53657e9945b5fcc3856f15091ed36db97245/main.ts#L86), [readFileSync(localFile);](https://github.com/notmmaoo/obsidian-imgbb-plugin/blob/352c53657e9945b5fcc3856f15091ed36db97245/main.ts#L143)
Use the Vault API instead: https://marcus.se.net/obsidian-plugin-docs/vault

- [x] use `Vault API` instead

> [const response = await fetch('https://api.imgbb.com/1/upload', {](https://github.com/notmmaoo/obsidian-imgbb-plugin/blob/352c53657e9945b5fcc3856f15091ed36db97245/main.ts#L150-L153) use the [requestUrl](https://github.com/obsidianmd/obsidian-api/blob/1b4f6e2e5753c8ac2d538bc5d55c38f228450cb2/obsidian.d.ts#L2887-L2892) function instead.

- [x] use `requestUrl` instead

> [SampleSettingTab](https://github.com/notmmaoo/obsidian-imgbb-plugin/blob/352c53657e9945b5fcc3856f15091ed36db97245/main.ts#L161)
You forgot to rename this.

- [x] use `ImgbbSettingTab` instead

**Comment by joethei** [comment]
Hi @notmmaoo,
I just wanted to confirm that you've seen Liams comment with the requested changes.
Do you still intend on submitting this plugin?

**Comment by liamcain** [comment]
Hi @notmmaoo, it's been a long time since we've heard from you. I'm going to close this pull request just to clear the queue for other plugins, but feel free to resubmit the plugin whenever you want us to take another look. Thanks! 🙏

**Pull request closed without merging**
