### PR TITLE
Add obsidian-pomodoro-plugin

### PR DESCRIPTION
**Pull request by tokuhirom**
# [ ] I am submitting a new Community Theme

## Repo URL

# [x] I am submitting a new Community Plugin

## Repo URL

https://github.com/tokuhirom/obsidian-pomodoro-plugin

## Release Checklist

- [x] I have tested this on Windows _(if applicable)_
- [x] Github release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] Github release name matches the exact version number specified in your manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.

### CODE REVIEW

**Comment by pjeby** [comment]
Looks pretty good.  You may want to include a command to open the pomodoro view (e.g. by calling initLeaf()), since if the user accidentally closes it they would have to reload Obsidian or the plugin to get it back.  So most plugins that provide a view like this have a command like "Show pomodoro timer" to restore the view.  (Like the way Obsidian has "Show file explorer" to restore a closed file explorer view.)

(I also noticed your settings tab class is named `SampleSettingsTab`; you might want to rename that.)

**Comment by tokuhirom** [comment]
@pjeby, thanks for your feedback :)

I did the following things.

- I renamed SampleSettingsTab to PomodoroSettingsTab
- Added "Show Pomodoro timer" command.
- Bumped version and released new version.

**Comment by pjeby** [comment]
Looks good to me.   One of the devs will need to merge, though, assuming they don't have any other feedback for you.

**Comment by lishid** [comment]
https://github.com/tokuhirom/obsidian-pomodoro-plugin/blob/a78e70f06b65183374e7fb06ff7ca8be02d4f134/main.ts#L11
I'd suggest using the built-in moment.js instead of importing your own, that should help reduce your plugin's bundle size.

**Pull request merged**
