### PR TITLE
Add plugin: Explain Selection With AI

### PR DESCRIPTION
**Pull request by BWurster**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/BWurster/obsidian-ai-expander

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["name": "Expand with AI",](https://github.com/BWurster/obsidian-ai-expander/blob/ae2b5c1df5e36498de37efbdbacf71112e994d5d/manifest.json#L3)
This name is not consistent with what the plugin is actually doing, please rename it.

[// Remember to rename these classes and interfaces!](https://github.com/BWurster/obsidian-ai-expander/blob/ae2b5c1df5e36498de37efbdbacf71112e994d5d/main.ts#L11)
Remove this comment

[model: this.endpoint,](https://github.com/BWurster/obsidian-ai-expander/blob/ae2b5c1df5e36498de37efbdbacf71112e994d5d/main.ts#L124)
This makes no sense, is this behaviour of the openai library documented anywhere?

Also, please add some documentation that explains what data is uploaded to OpenAI and how to use a different model.
And some documentation arround the endpoint behaviour would be great.

**Comment by BWurster** [comment]
I made those changes and renamed my repo to be in line with the name criticism. The repo is now called `BWurster/explain-selection-with-ai`. How do I do about pushing these changes? I have updated the files in the original release.

**Comment by joethei** [comment]
Please create a new release with the new changes.

**Comment by BWurster** [comment]
I created the release with the new changes. Is there anything else I need to do to restart the review process?

**Pull request merged**
