### PR TITLE
Add Time Ruler plugin

### PR DESCRIPTION
**Pull request by joshuatazrein**
Please switch to **Preview** and select one of the following links:

* [Community Plugin](?template=plugin.md)
* [Community Theme](?template=theme.md)

## Repo URL

Link to my plugin: https://github.com/joshuatazrein/obsidian-time-ruler

Release Checklist

- [x] I have tested the plugin on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
  - [ ] Android (if applicable)
  - [x] iOS (if applicable)
- [x] My GitHub release contains all required files
  - [x] main.js
  - [x] manifest.json
  - [x] styles.css (optional)
- [x] GitHub release name matches the exact version number specified in my manifest.json (Note: Use the exact version number, don't include a prefix v)
- [x] The id in my manifest.json matches the id in the community-plugins.json file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x]  I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
- [x] I have given proper attribution to these other projects in my README.md.

### CODE REVIEW

**Comment by joethei** [comment]
Please follow the pull request template.

**Comment by joshuatazrein** [comment]
> Please follow the pull request template.

Thanks, I have updated the description.

**Comment by joethei** [comment]
[id: 'obsidian-time-ruler-activate-view',](https://github.com/joshuatazrein/obsidian-time-ruler/blob/0490eab02b68cc63d8e28fc7928c044c7103218c/src/main.ts#L39)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.


[this.app.workspace.detachLeavesOfType(TIME_RULER)](https://github.com/joshuatazrein/obsidian-time-ruler/blob/0490eab02b68cc63d8e28fc7928c044c7103218c/src/main.ts#L87)
Do not detach leaves with your custom view in `onunload`, this is an antipattern, see: <https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Don't+detach+leaves+in+%60onunload%60>

[view.setEphemeralState](https://github.com/joshuatazrein/obsidian-time-ruler/blob/0490eab02b68cc63d8e28fc7928c044c7103218c/src/main.ts#L92)
What is this method call for?

[thisFrame.current.innerHTML = format(formatted)](https://github.com/joshuatazrein/obsidian-time-ruler/blob/0490eab02b68cc63d8e28fc7928c044c7103218c/src/components/Editor.tsx#L76) and [dangerouslySetInnerHTML={{ __html: format(text) }}](https://github.com/joshuatazrein/obsidian-time-ruler/blob/0490eab02b68cc63d8e28fc7928c044c7103218c/src/components/Editor.tsx#L124)
You should try to [avoid using `innerHTML`](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%60innerHTML%60%2C+%60outerHTML%60+and+%60insertAdjacentHTML%60) as much as possible.

[// export const SERVER = 'https://noticenotion.app/server'](https://github.com/joshuatazrein/obsidian-time-ruler/blob/0490eab02b68cc63d8e28fc7928c044c7103218c/src/app/constants.ts#L1-L2)
What are these for?

**Comment by joshuatazrein** [comment]
Hi,

Is there anything I need to fix, or is this plugin ready to be added?

**Comment by liamcain** [comment]
- [window](https://github.com/joshuatazrein/obsidian-time-ruler/blob/09c4a58d5eb09189bea2aed7e5825441c72059e9/src/services/autoScroll.ts#L28) this should be `el.win` instead of window so that the timer is set on the window used by the element (since Obsidian can have multiple window instances)
- [app['isMobile']](https://github.com/joshuatazrein/obsidian-time-ruler/blob/09c4a58d5eb09189bea2aed7e5825441c72059e9/src/components/App.tsx#L217) You should use Platform.isMobile instead

**Comment by joshuatazrein** [comment]
Thanks @liamcain! I have just changed and updated those aspects and loaded new files into the release. Looking forward to getting the plugin onto the Obsidian directory!

**Pull request merged**
