### PR TITLE
add new links plugin

### PR DESCRIPTION
**Pull request by mii-key**
add new plugin that converts and removes links

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/mii-key/obsidian-links

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[id: 'links-editor-remove-link',](https://github.com/mii-key/obsidian-links/blob/80d1e8a3e5c30cd143d7ee698710f5a7a76b98c3/main.ts#L11)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

**Comment by mii-key** [comment]
Thank you for the comment. I've updated command ids per your request.

**Comment by liamcain** [comment]
- [('<a'](https://github.com/mii-key/obsidian-links/blob/ad6e30a610902b8efbd7bb5e3db3dca19f620227/main.ts#L626) this match it's quite accurate enough. It will have false positives for things like `<abbr>` or `<aside>` or `<audio>`.
- [setViewData](https://github.com/mii-key/obsidian-links/blob/ad6e30a610902b8efbd7bb5e3db3dca19f620227/main.ts#L595) setViewData won't actually make any changes to the file if the user is in Reading mode. This will instead just edit the rendered content.

**Comment by mii-key** [comment]
thanks for the review! :)

**Pull request merged**
