### PR TITLE
adding obsidian-excel-to-markdown-table to plugins

### PR DESCRIPTION
**Pull request by ganesshkumar**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/ganesshkumar/obsidian-excel-to-markdown-table

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/ganesshkumar/obsidian-excel-to-markdown-table/blob/3fae8466c2eedf0613fab22e253528e40828fa60/src/main.ts#L9
Ctrl+Shift+V conflicts with the browser engine's "paste as plaintext". You should also use `Mod` instead of `Ctrl` if you want it to become `Cmd` on macOS.

**Comment by ganesshkumar** [comment]
@lishid , what is the suggested option for the conflict with browser engine's paste as plaintext. Can it be Alt+Mod+V?

**Comment by lishid** [comment]
Mod-Alt-V might work, or you can leave it blank and let the user assign something of their preference or only use it from the command palette.

There's also another option - if you want, you can rewrite the plugin to use the Workspace's `editor-paste` event, and try to detect whether the paste is from excel (possibly run a regex for some excel-specific `mso-` tags from the `text/html` blob). That way, your plugin will integrate directly into the paste handler for the editor and won't require an additional hotkey.

**Comment by ganesshkumar** [comment]
Thanks for you input, @lishid . I guess I will add Mod-Alt-V and let the user reassign if needed. This is the same behavior found in excel to markdown plugin in VS Code as well.

**Comment by ganesshkumar** [comment]
Thanks for you input, @li. I guess I will add Mod-Alt-V and let the user reassign if needed. This is the same behavior found in excel to markdown plugin in VS Code as well.

**Comment by ganesshkumar** [comment]
@lishid , I have 
- updated the hotkeys to `Mod-Alt-V`
- added a note in the README.md on how to change the hotkeys.
- updated the version and made a release (0.1.1)

**Comment by lishid** [comment]
I still think it's worth considering using the `editor-paste` event as it will be more integrated, but I think it's already pretty useful as it is right now.

**Comment by ganesshkumar** [comment]
Definitely. Will try to integrate with `editor-paste` event and update the plugin soon 👍

**Pull request merged**
