### PR TITLE
Adding obsidian-enhanced-treemap

### PR DESCRIPTION
**Pull request by erikshelley**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/erikshelley/obsidian-enhanced-treemap

## Release Checklist
- [ ] I have tested the plugin on
  - [X]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "Create enhanced treemaps in Obsidian.",](https://github.com/erikshelley/obsidian-enhanced-treemap/blob/be68b93b3dfc37d812fce10ed408bb1dd75cf217/manifest.json#L6)
We have recently published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This is a plugin for Obsidian" in your description.

[this.app.workspace.off("resize", this.debouncedRefresh );](https://github.com/erikshelley/obsidian-enhanced-treemap/blob/be68b93b3dfc37d812fce10ed408bb1dd75cf217/src/main.ts#L47)
Since you have already registered this event above you can remove this ine.

[var adapter = app.vault.adapter as FileSystemAdapter;](https://github.com/erikshelley/obsidian-enhanced-treemap/blob/be68b93b3dfc37d812fce10ed408bb1dd75cf217/src/settings.ts#L90)
This won't work on mobile, as the `FileSystemAdapter` API is only available on desktop.
You can just remove this setting, see below.

[else return "app://local/" + this.settings.basePath + d.data.image; })](https://github.com/erikshelley/obsidian-enhanced-treemap/blob/be68b93b3dfc37d812fce10ed408bb1dd75cf217/src/enhancedtreemap.ts#L492)
This won't work as of Obsidian 1.2.8, `app://local` was removed.
You should use `this.app.vault.adapter.getResourcePath(d.data.image)` instead, this will work on all platforms.


I recommend you change all instances of `var` to either `const` or `let`. `var` has function-level scope, so it can easily lead to bugs if you're not careful. Here's a pretty good guide with examples of why not to use `var`: [why `var` is obsolete](https://javascript.plainenglish.io/4-reasons-why-var-is-considered-obsolete-in-modern-javascript-a30296b5f08f)

**Comment by marcusolsson** [comment]
[containerEl.createEl('h1', { text: 'Enhanced Treemap Settings' } );](https://github.com/erikshelley/obsidian-enhanced-treemap/blob/02ca263e31133dea89857352a82c984fa4b4e38d/src/settings.ts#L114)
https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#UI+text

[.setName('Aspect Ratio')](https://github.com/erikshelley/obsidian-enhanced-treemap/blob/02ca263e31133dea89857352a82c984fa4b4e38d/src/settings.ts#L130)
https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI

["1.0.0": "0.15.0"](https://github.com/erikshelley/obsidian-enhanced-treemap/blob/02ca263e31133dea89857352a82c984fa4b4e38d/versions.json#L2)
https://docs.obsidian.md/Reference/Versions

**Comment by joethei** [comment]
Hi @erikshelley,

Do you still intend on submitting this plugin?

**Comment by erikshelley** [comment]
Yes I do.

**Comment by ericaxu** [comment]
Hi there, to keep things tidy, we're going to temporarily close plugin PRs after a month of inactivity.

Feel free to tell us to re-open it when you're ready to continue and we'll reopen it right away. Thanks for your understanding!

**Pull request closed without merging**
