### PR TITLE
Add "Carry-Forward" plugin

### PR DESCRIPTION
**Pull request by jglev**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/publicus/obsidian-carry-forward

## Release Checklist

- [ ] I have tested this on Windows, macOS, and Linux _(if applicable)_  
  - I have access to Linux and Windows, and have tested this plugin on both.
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/publicus/obsidian-carry-forward/blob/d626428c5f6f212270a6ceb5a054484d7b4b8d0e/main.ts#L189
You don't need to use an `editorCheckCallback` - instead just use `editorCallback`. The `view` parameter is also of type `MarkdownView`, and you should use the `markdownView.file` instead of `workspace.getActiveFile()` just in case the view wasn't the active view (unlikely, but not guaranteed).

**Comment by publicus** [comment]
@lishid Thank you for your feedback! I appreciate it!

I've incorporated all of your comments just now, and incremented the version number.

**Comment by lishid** [comment]
Looks like you forgot to add the GitHub release for 1.1.0 😅

**Comment by jglev** [comment]
> Looks like you forgot to add the GitHub release for 1.1.0

Lol, thank you for the heads-up. :sweat_smile: I used a script to manage the release, and must have exited partway through the process. The release is there now!

**Pull request merged**
