### PR TITLE
added excalibrain

### PR DESCRIPTION
**Pull request by zsviczian**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/zsviczian/excalibrain

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by claremacrae** [comment]
Sounds intriguing! Any chance you could add the URL to the template above, I’m really curious to see it!

**Comment by zsviczian** [comment]
https://github.com/zsviczian/excalibrain

**Comment by liamcain** [comment]
https://github.com/zsviczian/excalibrain/blob/f7022f5576cc48ff5db88b9665af3d73921e791d/src/main.ts#L178 `app.internalPlugins.getPluginById` can return `null` if the core plugin is disabled

https://github.com/zsviczian/excalibrain/blob/f7022f5576cc48ff5db88b9665af3d73921e791d/src/main.ts#L228 maybe use checkCallback here instead so that the command isn't available if excalidraw isn't available

https://github.com/zsviczian/excalibrain/blob/f7022f5576cc48ff5db88b9665af3d73921e791d/src/main.ts#L252 you should coerce this to a boolean

https://github.com/zsviczian/excalibrain/blob/f7022f5576cc48ff5db88b9665af3d73921e791d/src/main.ts#L284 it's better to use `app.commands.executeCommandById()` here

https://github.com/zsviczian/excalibrain/blob/f7022f5576cc48ff5db88b9665af3d73921e791d/src/main.ts#L300 you could create a [type predicate](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates) so that you won't have to ts-ignore here.  

https://github.com/zsviczian/excalibrain/blob/f7022f5576cc48ff5db88b9665af3d73921e791d/src/utils/fileUtils.ts#L11 you probably want to limit the `lastIndexOf` to only look at the last path segment. Otherwise you'll get false positives from `some/path/with.dots.in.the.path/like-this`

https://github.com/zsviczian/excalibrain/blob/f7022f5576cc48ff5db88b9665af3d73921e791d/src/utils/dataview.ts#L69 I don't think you need to use `any` for dataview objects. I think you can import the typing information from `obsidian-dataview`.

**Comment by zsviczian** [comment]
Thanks! Awesome! I always learn so much from this process (and on OMG). I've implemented the changes.

https://github.com/zsviczian/excalibrain/releases/tag/0.0.18

**Pull request merged**
