### PR TITLE
Add Checklist Reset plugin

### PR DESCRIPTION
**Pull request by lhansford**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/lhansford/obsidian-checklist-reset

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by liamcain** [comment]
- [replaceAll](https://github.com/lhansford/obsidian-checklist-reset/blob/71982e3d3d09726f9b6ab5ebc51330d48ba33e01/main.ts#L10) technically Obsidian checklists can have any non-space character to mark it as completed (e.g. `- [c]`, `- [/]`, etc) so you might want to handle this more generically.
- The current approach is susceptible to a lot of false positives. It's possible that the user has "[x]" in the middle of a line of text and it's not a task. You might want to use a more sophisticated regex to make sure that you're only finding tasks.

**Comment by lhansford** [comment]
@liamcain Thanks for the feedback. I've made those suggested changes.

**Comment by liamcain** [comment]
Looks good. You might still want to ensure that the list item is captured at the start of a new line, to avoid capturing things like `foo - [x] - bar`

**Comment by lhansford** [comment]
Thanks for the suggestion, I'll see if I can patch that.

**Pull request merged**
