### PR TITLE
Add Obsidian-Douban-Plugin

### PR DESCRIPTION
**Pull request by Wanxp**
This is a new plugin for obsidian that user can get some movies, books, musics info to file.

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Wanxp/obsidian-douban

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by ka1tzyu** [comment]
@Wanxp, you left empty link to your plugin

> Link to my plugin:

**Comment by Wanxp** [comment]
> @Wanxp, you left empty link to your plugin
> 
> > Link to my plugin:

Thanks. I added github respository url to comment.

**Review by Wanxp — COMMENTED** [review]
update obsidian-douban description

**Comment by liamcain** [comment]
[douban](https://github.com/Wanxp/obsidian-douban/blob/a176ccecb89963c3d75754099ce7c671b94b7d6b/lang/locale/en.ts#L4) I would suggest using simpler, more concise keys for your i18n files. As it stands now, it will be a bit weird if the values change and no longer match the keys.

[import { get, readStream } from 'tiny-network';](https://github.com/Wanxp/obsidian-douban/blob/7ebf875b4058f5354d532d4543186645d50febb5/douban/search/Search.ts#L3) You can use the [`requestUrl`](https://github.com/obsidianmd/obsidian-api/blob/9bb30633586c6649474b2affdf5b87efdd86498f/obsidian.d.ts#L2680) function from the Obsidian API to make your API calls instead of importing tiny-network. It should work roughly the same way.

[var content](https://github.com/Wanxp/obsidian-douban/blob/ee2dead3937a029eb619f33a46b7e592f85768e8/main.ts#L24) Don't use `var`, use `const` or `let` instead.

[var title =](https://github.com/Wanxp/obsidian-douban/blob/824296a8a7ac7c58cc654e9fd6ed415e281d084c/douban/handler/DoubanBookLoadHandler.ts#L48) Use `const` or `let` instead, for all of these

[var item = data](https://github.com/Wanxp/obsidian-douban/blob/a176ccecb89963c3d75754099ce7c671b94b7d6b/douban/handler/DoubanMovieLoadHandler.ts#L45) use `const` or `let` instead of `var`

[settings_area](https://github.com/Wanxp/obsidian-douban/blob/20f49a685c440b18137a9d86dd8d116250f4e11b/styles.css#L1) I recommend you make all your class names more specific to your plugin to avoid them potentially clashing with another plugin

[HttpUtil](https://github.com/Wanxp/obsidian-douban/blob/20f49a685c440b18137a9d86dd8d116250f4e11b/utils/HttpUtil.ts#L6) this class is unused.

**Comment by liamcain** [comment]
Hi @Wanxp, https://github.com/obsidianmd/obsidian-releases/pull/996#issuecomment-1163076083 have you looked at removing the `tiny-network` dependency? It shouldn't be necessary for this plugin.

**Comment by Wanxp** [comment]
> Hi @Wanxp, it looks like you've been actively making changes to the plugin. Have you taken a look at the suggestions I made above? #996


OK. I will carefully consider your suggestion.

**Comment by Wanxp** [comment]
> 

Those problem has been solved, you can check it out.

**Pull request merged**
