### PR TITLE
Update community-plugins.json

### PR DESCRIPTION
**Pull request by ryanjamurphy**
Adding the DEVONlink plugin.
# [x] I am submitting a new Community Plugin

## Release Checklist

- [x] I have tested this on Windows, macOS, and Linux _(if applicable)_
- [x] Github release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - `styles.css` _(optional)_
- [x] Github release name matches the exact version number specified in your manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/ryanjamurphy/DEVONlink-obsidian/blob/a1df64fe4f59def6cad2590a3e306b38aa65f24c/main.ts#L29
Consider moving all of this into your execution function - `checkCallback: this.openDEVONthinkRecord.bind(this)` and change 
`async openDEVONthinkRecord()` to `async openDEVONthinkRecord(checking: boolean) : boolean`.

https://github.com/ryanjamurphy/DEVONlink-obsidian/blob/a1df64fe4f59def6cad2590a3e306b38aa65f24c/main.ts#L72
Here you should probably make a variable for `this.app.workspace.getActiveFile()`. Make sure you run a truthy check here too.

https://github.com/ryanjamurphy/DEVONlink-obsidian/blob/a1df64fe4f59def6cad2590a3e306b38aa65f24c/main.ts#L73
There's a compile error here because basePath shouldn't be directly accessible. Test for whether the adapter here is FilesystemAdapter and use `getBasePath()`.

https://github.com/ryanjamurphy/DEVONlink-obsidian/blob/a1df64fe4f59def6cad2590a3e306b38aa65f24c/main.ts#L5
If you don't need the settings stuff, consider removing them to keep things clean - you can always get them back from the sample repo or your git history.

**Comment by ryanjamurphy** [comment]
All these suggestions are deal with. Want me to make a new PR?

> Consider moving all of this into your execution function - `checkCallback: this.openDEVONthinkRecord.bind(this)` and change `async openDEVONthinkRecord()` to `async openDEVONthinkRecord(checking: boolean) : boolean`. 
Done!

> Here you should probably make a variable for this.app.workspace.getActiveFile(). Make sure you run a truthy check here too.
Done!

> There's a compile error here because basePath shouldn't be directly accessible. Test for whether the adapter here is FilesystemAdapter and use getBasePath().
I figured out how to do this, implemented it, then realized that I didn't even need the base path anymore. 🙄 

> If you don't need the settings stuff, consider removing them to keep things clean - you can always get them back from the sample repo or your git history.
I added a setting!

**Comment by lishid** [comment]
https://github.com/ryanjamurphy/DEVONlink-obsidian/blob/0251ec9876d45095c0b56fb2652ec2bcbe43c60d/main.ts#L75

Your code actually just need an active file - why do the activeLeaf check anyway? Maybe better to just use the active file status instead?

Otherwise everything else looks good. Once you fix that and resolve the merge conflict I can have it merged.

**Comment by ryanjamurphy** [comment]
Done. 

And I think I resolved the merge conflict correctly. GitHub's merge conflict UI is weird, though...

**Comment by liamcain** [comment]
You might need to do the rebase locally unfortunately @ryanjamurphy

**Comment by ryanjamurphy** [comment]
I'll just run a new PR—one sec!

**Pull request closed without merging**
