### PR TITLE
Add Typomagical to community themes

### PR DESCRIPTION
**Pull request by hungsu**
# I am submitting a new Community Theme

## Repo URL

Link to my theme: https://github.com/hungsu/typomagical-obsidian

## Theme checklist

- [x] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo)
  - [x] `obsidian.css`
  - [x] The screenshot file
- [x] I have indicated which modes (dark, light, or both) are compatible with my theme
- [x] I have added a license in the LICENSE file
- [x] If my repo is not using the `master` branch, please indicate in `community-themes.json` with `"branch": "main"`.

### CODE REVIEW

**Comment by hungsu** [comment]
I didn't realise this was in conflict. Conflict resolved.

**Comment by ericaxu** [comment]
Thanks for your submission! Could you change the screenshot to show the color combination that you want to feature the most? Or you can consider doing a split image between light and dark. It's beautiful but I'm just afraid it's a bit distracting when browsed in the theme store.

**Comment by hungsu** [comment]
That's a very fair point Erica! I'll put together a new screenshot!

**Comment by hungsu** [comment]
Hi Erica! I've added a flat split screenshot. So sorry for the trouble!

**Comment by hungsu** [comment]
Hi Erica, is there anything else I should do? 🙏

**Comment by ericaxu** [comment]
> Hi Erica, is there anything else I should do? 🙏

Sorry! Totally fell through the crack and it's my bad. Merging now!

**Pull request merged**
