### PR TITLE
Add plugin: Cooklang

### PR DESCRIPTION
**Pull request by rveciana**
I am submitting a new Community Plugin
===
Repo URL
---
Link to my plugin:
https://github.com/rveciana/obsidian-cooklang

Release Checklist
---
- [x] I have tested the plugin on
    - [ ] Windows
    - [x] macOS
    - [x] Linux
    - [ ] Android (if applicable)
    - [ ] iOS (if applicable) 
- [x] My GitHub release contains all required files
    - [x] main.js
    - [x] manifest.json
    - [x] styles.css (optional)
- [x] GitHub release name matches the exact version number specified in my manifest.json (Note: Use the exact version number, don't include a prefix v)
- [x] The id in my manifest.json matches the id in the community-plugins.json file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
- [x] I have given proper attribution to these other projects in my README.md.

### CODE REVIEW

**Comment by rveciana** [comment]
The release on github is 0.0.3

**Comment by joethei** [comment]
Please follow the pull request template

**Comment by rveciana** [comment]
Updated

**Comment by joethei** [comment]
And btw, you don't need to handle the merge conflicts.
We will do that once the plugin is reviewed.

**Comment by claremacrae** [comment]
I'm confused... the subect says 'Cooklang' but the link is 'Advanced Canvas':
https://github.com/Developer-Mike/obsidian-advanced-canvas

**Comment by rveciana** [comment]
I copied the wring text, sorry. Now it's corrected. The link is https://github.com/rveciana/obsidian-cooklang

**Comment by joethei** [comment]
[return "microphone";](https://github.com/rveciana/obsidian-cooklang/blob/0c507a9390bbacb7468573a1d5d19b76db222db5/src/starterIndex.ts#L56)
I would recommend the or `chef-hat` icon instead.

[new Setting(containerEl)](https://github.com/rveciana/obsidian-cooklang/blob/0c507a9390bbacb7468573a1d5d19b76db222db5/src/ui/Settings.ts#L17-L19)
There should not be a top level header in settings.

[.setName('Preview Options')](https://github.com/rveciana/obsidian-cooklang/blob/0c507a9390bbacb7468573a1d5d19b76db222db5/src/ui/Settings.ts#L18)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by rveciana** [comment]
I changed the icon and removed the header, since the guidelines say that they only have to be there if there is more than one section: 
https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.
Therefore, the sentence case change is not needed, as the header is not there anymore.

**Pull request merged**
