### PR TITLE
Add obsidian-local-images-plus plugin

### PR DESCRIPTION
**Pull request by Sergei-Korneev**
This repo is a reincarnation of obsidian-local-images plugin which main aim was downloading images in md notes to local storage.

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Review by Sergei-Korneev — COMMENTED** [review]
Sorry, I have made some mistypes.
	"description": "Local Images plus plugin is a reincarnation of obsidian-local-images which main aim was downloading images in md notes to local storage."

**Comment by liamcain** [comment]
- [proccessPage](https://github.com/Sergei-Korneev/obsidian-local-images-plus/blob/0a7c4d9e047684877bd0e6fca7b8ff208f971a2a/src/main.ts#L30) typo: process
- [I could not find the way to access newly pasted content immediatily, after pasting, Plugin's API returns old text for a while.](https://github.com/Sergei-Korneev/obsidian-local-images-plus/blob/0a7c4d9e047684877bd0e6fca7b8ff208f971a2a/src/main.ts#L305) this is probably too much information for a user to need to know. Maybe just gave the relevant info.
- [require](https://github.com/Sergei-Korneev/obsidian-local-images-plus/blob/0a7c4d9e047684877bd0e6fca7b8ff208f971a2a/src/utils.ts#L12) you should use the vault's [`adapter.read`](https://github.com/obsidianmd/obsidian-api/blob/38dd22168d2925086371bfc59e36fd9121527a39/obsidian.d.ts#L732) which will read the file properly across all operating systems (including mobile)

**Comment by Sergei-Korneev** [comment]
Thank you so much. Will be added in 0.14.5

**Comment by liamcain** [comment]
You're referring to this event in the API? https://github.com/obsidianmd/obsidian-api/blob/38dd22168d2925086371bfc59e36fd9121527a39/obsidian.d.ts#L4247. Sorry, mind pointing me at the code that's returning the wrong thing?

**Comment by Sergei-Korneev** [comment]
Yeah, maybe I expressed myself badly, I mean when you try immediately get a note content in the "editor-paste" event e.g. 


this.app.workspace.on(
      "editor-paste",
        ( evt: ClipboardEvent, editor: Editor, info: MarkdownView) => {


const data = this.app.vault.read(this.app.workspace.getActiveFile());
//or
const data = this.app.workspace.activeLeaf.view.data;
}

it returns the previous content, despite the fact, that in editor window we of course can see the actual content. But the event called on timer a second later 
return the actual content with any of those methods.
I presume, it takes some time to write on disk maybe and  expose actual content to the plugin. Am I right?

**Comment by liamcain** [comment]
Oh, yeah. The paste event is fired before the content gets written to the file so that you can intercept it if you want. Maybe it's too much to change from the current implementation, but you do have access to the clipboardData from the PasteEvent. So instead of trying to read the whole file contents, you could just modify the clipboardData before it gets inserted.

**Comment by Sergei-Korneev** [comment]
I thought about that too. Thanks.

**Pull request merged**
