### PR TITLE
Add plugin Lovely-Mindmap

### PR DESCRIPTION
**Pull request by xincan1949**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/xincan1949/lovely-mindmap

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [ ] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by xincan1949** [comment]
Hi @joethei, the source code of #2128 is made public. 
Hope to be adopted soon~

**Comment by joethei** [comment]
[createCanvasInstance() {](https://github.com/xincan1949/lovely-mindmap/blob/ce88cd6b0765dcf3bf9224015bfc0fc56ca1e699/src/main.ts#L25-L37)
Don't do this, just use a regular method to get the current canvas instead.
Your current code waits for a canvas file to be opened, which is horribly inefficient.
It also only works for the very first canvas a user opens in a given session.

[function debounce(delay: number = 100): MethodDecorator {](https://github.com/xincan1949/lovely-mindmap/blob/ce88cd6b0765dcf3bf9224015bfc0fc56ca1e699/src/tool/index.ts#L1-L26)
Obsidian already exports a function of the same name,

[console.log('this:\n', this)](https://github.com/xincan1949/lovely-mindmap/blob/ce88cd6b0765dcf3bf9224015bfc0fc56ca1e699/src/module/keymap.ts#L26-L29)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

**Comment by xincan1949** [comment]
Hey @joethei , thanks for your carefully review, here are my question and answer

1. Is there any API can get canvas instance?

I do it because sometimes when users create canvas, the canvas may not create in first time, so polling is required

2. `@debounce` is not a function, it's decorator in JavaScript Class. 
 
Different with normal debounce(execute the event after N seconds), the `@debounce` decorator execute a event immediately and rest for N seconds. Maybe I should change the decorator name from `@debounce` to `@rest` 🤔

**Comment by liamcain** [comment]
Added here https://github.com/obsidianmd/obsidian-releases/commit/f8a30a360be5d17dae97fe784a10297680764192!

**Pull request closed without merging**
