### PR TITLE
Add obsidian-graphviz plugin

### PR DESCRIPTION
**Pull request by QAMichaelPeng**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/QAMichaelPeng/obsidian-graphviz

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/QAMichaelPeng/obsidian-graphviz/blob/9af1664dd308496621ec491c95f8f4bc8ac48bde/src/main.ts#L20
Since your code runs asynchronously, you should return a promise or use async-await properly here. You can also use `processors.imageProcessor.bind(processors)` directly without having an intermediate function. Just make `imageProcessor` return a promise which resolves when your png rendering is complete (you can promisify the exec/fs actions pretty easily).

Instead of using a base64 URI, you can use a blob URI which is more efficient:
https://stackoverflow.com/a/21206824

**Comment by QAMichaelPeng** [comment]
Thanks for the feedback. Will address it in this week.

**Comment by QAMichaelPeng** [comment]
Most issues pr comments were resolved.
One remaining  is return promise from GraphvizPlugin:onload().

Since typescript will return a promise by default for async, do we need to explicitly return a promise? Could you share an example? I've checked variant plugins and didn't find one returning a promise in onload.

Thanks.

**Comment by lishid** [comment]
Yeah that looks good. One more thing you should do is to convert the `.then()` and `.catch` to await: https://github.com/QAMichaelPeng/obsidian-graphviz/blob/9c32378a15adc5b306405c1c75524f16455f35c3/src/processors.ts#L72

> Since typescript will return a promise by default for async, do we need to explicitly return a promise? Could you share an example? I've checked variant plugins and didn't find one returning a promise in onload.

Yeah, an async function basically returns a promise. In fact, async-await is just some syntactic sugar that automatically wraps your code in different chunks of callback functions with promises and `.then()` and `.catch()`. It's really the new way of writing promises that makes them so much easier to read (just like synchronous code!)

There are some examples at https://developers.google.com/web/fundamentals/primers/async-functions

**Comment by QAMichaelPeng** [comment]
@lishid , thanks for the comments. Code updated.

**Pull request merged**
