### PR TITLE
Mermaid.js Helper

### PR DESCRIPTION
**Pull request by FrancescoDiCursi**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/tree/main

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [ ] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lishid** [comment]
@FrancescoDiCursi Don't keep creating new PRs. You can reuse the existing PR and the bot will re-run the check after you make changes to your own repo.

Your PR spam triggered a block - you won't be able to send another PR or reply here until 24 hours. DM me on discord (`@Licat`) once you read this message and I can unblock you.

**Comment by lishid** [comment]
You need to upload a copy of your manifest.json/main.js to https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/releases/tag/1.0.0

**Comment by joethei** [comment]
["repo": "FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin"](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/2479a39d28dab0d56abc04d2470f297cfd4abcf1/manifest.json#L9)
Unnecessary.

Have you written your code in the `main.js`?
It looks pretty messy.
We have a sample plugin here: https://github.com/obsidianmd/obsidian-sample-plugin

I recommend you change all instances of `var` to either `const` or `let`.
 `var` has function-level scope, so it can easily lead to bugs if you're not careful.
Here's a pretty good guide with examples of why not to use `var`: [why `var` is obsolete](https://javascript.plainenglish.io/4-reasons-why-var-is-considered-obsolete-in-modern-javascript-a30296b5f08f)

Remove all `console.log` calls.

[id: "move-mermaidjs-variable-declarations-up",](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/2479a39d28dab0d56abc04d2470f297cfd4abcf1/main.js#L34)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to do include it here.

[var style_type = selection.split(" ").slice(0, 1);](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/2479a39d28dab0d56abc04d2470f297cfd4abcf1/main.js#L85-L87)
Instead of calling the `split` function all the time save it in a variable.

[var files = this.app.vault.getFiles().map((d) => d.path);](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/2479a39d28dab0d56abc04d2470f297cfd4abcf1/main.js#L129-L137)
This is really not performant.
Check if `this.app.vault.getAbstractFileByPath` returns something instead.


[this.addCommand({](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/2479a39d28dab0d56abc04d2470f297cfd4abcf1/main.js#L140-L161)
I don't see how this command is related to this plugin, there is already one that does this,
but in a much safer way.

[this.addCommand({](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/2479a39d28dab0d56abc04d2470f297cfd4abcf1/main.js#L162-L182)
This also makes no sense in this plugin.

[this.addCommand({](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/2479a39d28dab0d56abc04d2470f297cfd4abcf1/main.js#L183-L212)
This also makes no sense here, better of in a seperate plugin.

[var _a, _b;](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/2479a39d28dab0d56abc04d2470f297cfd4abcf1/main.js#L187)
What are these variables?

**Comment by FrancescoDiCursi** [comment]
> ["repo": "FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin"](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/2479a39d28dab0d56abc04d2470f297cfd4abcf1/manifest.json#L9) Unnecessary.
> 
> Have you written your code in the `main.js`? It looks pretty messy. We have a sample plugin here: https://github.com/obsidianmd/obsidian-sample-plugin
> 
> I recommend you change all instances of `var` to either `const` or `let`. `var` has function-level scope, so it can easily lead to bugs if you're not careful. Here's a pretty good guide with examples of why not to use `var`: [why `var` is obsolete](https://javascript.plainenglish.io/4-reasons-why-var-is-considered-obsolete-in-modern-javascript-a30296b5f08f)
> 
> Remove all `console.log` calls.
> 
> [id: "move-mermaidjs-variable-declarations-up",](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/2479a39d28dab0d56abc04d2470f297cfd4abcf1/main.js#L34) Obsidian will automatically prefix the command id with the plugin id, you don't need to do include it here.
> 
> [var style_type = selection.split(" ").slice(0, 1);](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/2479a39d28dab0d56abc04d2470f297cfd4abcf1/main.js#L85-L87) Instead of calling the `split` function all the time save it in a variable.
> 
> [var files = this.app.vault.getFiles().map((d) => d.path);](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/2479a39d28dab0d56abc04d2470f297cfd4abcf1/main.js#L129-L137) This is really not performant. Check if `this.app.vault.getAbstractFileByPath` returns something instead.
> 
> [this.addCommand({](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/2479a39d28dab0d56abc04d2470f297cfd4abcf1/main.js#L140-L161) I don't see how this command is related to this plugin, there is already one that does this, but in a much safer way.
> 
> [this.addCommand({](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/2479a39d28dab0d56abc04d2470f297cfd4abcf1/main.js#L162-L182) This also makes no sense in this plugin.
> 
> [this.addCommand({](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/2479a39d28dab0d56abc04d2470f297cfd4abcf1/main.js#L183-L212) This also makes no sense here, better of in a seperate plugin.
> 
> [var _a, _b;](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/2479a39d28dab0d56abc04d2470f297cfd4abcf1/main.js#L187) What are these variables?

I wrote it in the main.ts and used npm run build to compile it in main.js. By the way I'll do all the changes you requested as soon as possible. Thank you for the hints.

**Comment by joethei** [comment]
Then please upload the `main.ts` to the repo

**Comment by FrancescoDiCursi** [comment]
Yes, I'm sorry. I'll fix it in few days.

**Comment by FrancescoDiCursi** [comment]
> ["repo": "FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin"](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/2479a39d28dab0d56abc04d2470f297cfd4abcf1/manifest.json#L9) Unnecessary.
> 
> Have you written your code in the `main.js`? It looks pretty messy. We have a sample plugin here: https://github.com/obsidianmd/obsidian-sample-plugin
> 
> I recommend you change all instances of `var` to either `const` or `let`. `var` has function-level scope, so it can easily lead to bugs if you're not careful. Here's a pretty good guide with examples of why not to use `var`: [why `var` is obsolete](https://javascript.plainenglish.io/4-reasons-why-var-is-considered-obsolete-in-modern-javascript-a30296b5f08f)
> 
> Remove all `console.log` calls.
> 
> [id: "move-mermaidjs-variable-declarations-up",](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/2479a39d28dab0d56abc04d2470f297cfd4abcf1/main.js#L34) Obsidian will automatically prefix the command id with the plugin id, you don't need to do include it here.
> 
> [var style_type = selection.split(" ").slice(0, 1);](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/2479a39d28dab0d56abc04d2470f297cfd4abcf1/main.js#L85-L87) Instead of calling the `split` function all the time save it in a variable.
> 
> [var files = this.app.vault.getFiles().map((d) => d.path);](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/2479a39d28dab0d56abc04d2470f297cfd4abcf1/main.js#L129-L137) This is really not performant. Check if `this.app.vault.getAbstractFileByPath` returns something instead.
> 
> [this.addCommand({](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/2479a39d28dab0d56abc04d2470f297cfd4abcf1/main.js#L140-L161) I don't see how this command is related to this plugin, there is already one that does this, but in a much safer way.
> 
> [this.addCommand({](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/2479a39d28dab0d56abc04d2470f297cfd4abcf1/main.js#L162-L182) This also makes no sense in this plugin.
> 
> [this.addCommand({](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/2479a39d28dab0d56abc04d2470f297cfd4abcf1/main.js#L183-L212) This also makes no sense here, better of in a seperate plugin.
> 
> [var _a, _b;](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/2479a39d28dab0d56abc04d2470f297cfd4abcf1/main.js#L187) What are these variables?

All the changes requested have been done.

**Comment by liamcain** [comment]
- [const basePath = (this.app.vault.adapter as any).basePath](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/7640e1c355411af1f502f4e184a4e9d5fcd3c429/main.ts#L119) you should use [`getBasePath`](https://github.com/obsidianmd/obsidian-api/blob/6b2138aa28fb6d6f58f78e6fabec02186fdc0f82/obsidian.d.ts#L1217) instead.
- [files.includes](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/7640e1c355411af1f502f4e184a4e9d5fcd3c429/main.ts#L136) if you're just looking to see if a file exists, use [`getAbstractFileByPath`](https://github.com/obsidianmd/obsidian-api/blob/902badd38ba907689f0917d7b193f7e33d1284fe/obsidian.d.ts#L3612) instead. Then you can check if it's already loaded in the vault. That way you don't need to loop through all the files/folders yourself.
- [document](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/7640e1c355411af1f502f4e184a4e9d5fcd3c429/main.ts#L73) nitpick: `document` usually refers to the window.document, so I suggest renaming this to something like `file` or `activeFile` instead.
- [document_txt = await this.app.vault.read(document)](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/7640e1c355411af1f502f4e184a4e9d5fcd3c429/main.ts#L75) since you already have a reference to `editor` you're actually better off using `editor.getValue()` here instead. That will read the file contents from memory as opposed to .read() which will read the contents from the filesystem.

**Comment by ericaxu** [comment]
@FrancescoDiCursi Hi there, do you still intend to submit this plugin?

**Comment by FrancescoDiCursi** [comment]
> @FrancescoDiCursi Hi there, do you still intend to submit this plugin?

Yes I do but I will very busy up to the first week of July. I will apply the required modifications right after that period.

**Comment by liamcain** [comment]
- [MyPlugin](https://github.com/FrancescoDiCursi/Mermaid.js-Helper-OMH-plugin/blob/7640e1c355411af1f502f4e184a4e9d5fcd3c429/main.ts#L9) you should rename your plugin class to something unique

**Pull request merged**
