### PR TITLE
Add plugin: Custom Image Auto Uploader

### PR DESCRIPTION
**Pull request by haierkeys**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [https://github.com/haierkeys/obsidian-custom-image-auto-uploader](https://github.com/haierkeys/obsidian-custom-image-auto-uploader)

## Release Checklist

- [x]  I have tested the plugin on
    - [x]  Windows
    - [x]  macOS
    - [ ]  Linux
    - [x]  Android
    - [x]  iOS
- [x]  My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
    - [x]  `main.js`
    - [x]  `manifest.json`

- [x]  GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x]  The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x]  My README.md describes the plugin's purpose and provides clear usage instructions.
- [x]  I have read the developer policies at [https://docs.obsidian.md/Developer+policies](https://docs.obsidian.md/Developer+policies), and have assessed my plugins's adherence to these policies.
- [x]  I have read the tips in [https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines) and have self-reviewed my plugin to avoid these common pitfalls.
- [x]  I have added a license in the LICENSE file.
- [x]  My project respects and is compatible with the original license of any code from other plugins that I'm using.  
    I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by haierkeys** [comment]
> #### Hello!
> **I found the following issues in your plugin submission**
> 
> **Errors:**
> 
> ❌ The newly added entry is not at the end, or you are submitting on someone else's behalf. The last plugin in the list is: `yy4382/obsidian-image-upload`. If you are submitting from a GitHub org, you need to be a public member of the org.
> 
> This check was done automatically. Do NOT open a new PR for re-validation. Instead, to trigger this check again, make a change to your PR and wait a few minutes, or close and re-open it.

OK,  It has been modified.

**Comment by joethei** [comment]
[Copyright (c) 2021 Kirill Gavrilov](https://github.com/haierkeys/obsidian-custom-image-auto-uploader/blob/981047e47729a2eb95b2339fae87363aa4015494/LICENSE#L3)
Update this.

[new Setting(set).setName($("通用")).setHeading();](https://github.com/haierkeys/obsidian-custom-image-auto-uploader/blob/981047e47729a2eb95b2339fae87363aa4015494/src/setting.ts#L61)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[src: "https://cdn.ko-fi.com/cdn/kofi3.png?v=3"](https://github.com/haierkeys/obsidian-custom-image-auto-uploader/blob/981047e47729a2eb95b2339fae87363aa4015494/src/setting.ts#L187)
This has to be bundled into the plugin, not loaded from an external source.

[let folder = await plugin.app.fileManager.getAvailablePathForAttachment("");](https://github.com/haierkeys/obsidian-custom-image-auto-uploader/blob/981047e47729a2eb95b2339fae87363aa4015494/src/utils.ts#L60-L62)
Please use the function properly and pass in the filename and the path to the file that's currently open, then return the result of the function, and remove the other two lines.
The way you are currently using the API will result in the wrong folder being used for attachments if the user has configured it in a certain way.

["Image Api Gateway 地址": "Image API Gateway address",](https://github.com/haierkeys/obsidian-custom-image-auto-uploader/blob/981047e47729a2eb95b2339fae87363aa4015494/src/lang/locale/en.ts#L31)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by haierkeys** [comment]
Thanks for the feedback. The requested changes have been made.

**Comment by joethei** [comment]
["minAppVersion": "0.15.0",](https://github.com/haierkeys/obsidian-custom-image-auto-uploader/blob/b345bb93550d4137ca579403847a8f66c37a43ec/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

[let loadedFiles = plugin.app.vault.getAllLoadedFiles();](https://github.com/haierkeys/obsidian-custom-image-auto-uploader/blob/b345bb93550d4137ca579403847a8f66c37a43ec/src/utils.ts#L67-L75)
Use the `getFirstLinkpathDest` instead of iterating over all files.

**Comment by haierkeys** [comment]
> ["minAppVersion": "0.15.0",](https://github.com/haierkeys/obsidian-custom-image-auto-uploader/blob/b345bb93550d4137ca579403847a8f66c37a43ec/manifest.json#L5) You are using newer API's, set this to the latest public build number.
> 
> [let loadedFiles = plugin.app.vault.getAllLoadedFiles();](https://github.com/haierkeys/obsidian-custom-image-auto-uploader/blob/b345bb93550d4137ca579403847a8f66c37a43ec/src/utils.ts#L67-L75) Use the `getFirstLinkpathDest` instead of iterating over all files.

ok, The requested changes have been made

**Comment by haierkeys** [comment]
@ObsidianReviewBot

**Comment by haierkeys** [comment]
> Thank you for your submission, an automated scan of your plugin code's revealed the following issues:
> 
> ### Optional
> [[1](https://github.com/haierkeys/obsidian-custom-image-auto-uploader/blob/ee31879ac0aaf319b23b74b80e4f3b41b3e977bb/src/utils.ts#L215)]:Use `app.fileManager.trashFile(file: TAbstractFile)` instead, this will make sure that the file is deleted according to the users preferences.
> 
> Do NOT open a new PR for re-validation.

ok

**Comment by haierkeys** [comment]
> Thank you for your submission, an automated scan of your plugin code's revealed the following issues:
> 
> ### Optional
> [[1](https://github.com/haierkeys/obsidian-custom-image-auto-uploader/blob/ee31879ac0aaf319b23b74b80e4f3b41b3e977bb/src/utils.ts#L215)]:Use `app.fileManager.trashFile(file: TAbstractFile)` instead, this will make sure that the file is deleted according to the users preferences.
> 
> Do NOT open a new PR for re-validation.

@ObsidianReviewBot  ok

**Comment by haierkeys** [comment]
> It has been modified.

Changes made..

**Comment by haierkeys** [comment]
> Thank you for your submission, an automated scan of your plugin code's revealed the following issues:
> 
> ### Optional
> [[1](https://github.com/haierkeys/obsidian-custom-image-auto-uploader/blob/ee31879ac0aaf319b23b74b80e4f3b41b3e977bb/src/utils.ts#L215)]:Use `app.fileManager.trashFile(file: TAbstractFile)` instead, this will make sure that the file is deleted according to the users preferences.
> 
> Do NOT open a new PR for re-validation.

Changes made.. https://github.com/haierkeys/obsidian-custom-image-auto-uploader/tree/1.5.8

**Comment by haierkeys** [comment]
@joethei  How long will the review take? Is there anything else that needs to be modified?

**Pull request merged**
