### PR TITLE
Add plugin: Smart Connections Visualizer

### PR DESCRIPTION
**Pull request by Mossy1022**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Mossy1022/Smart-Connections-Graph-View

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Mossy1022** [comment]
Hello, this error is incorrect. The plugin id is valid. I'm not sure what the issue is.

**Comment by joethei** [comment]
["description": "A plugin that allows you to view your Smart Connections in a visualized format.",](https://github.com/Mossy1022/Smart-Connections-Visualizer/blob/3ca571bf2a7fdab066791e4c86ce92d5fc628eb0/manifest.json#L6)
Avoid including sentences like "This is a plugin for Obsidian that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

["fundingUrl": "https://github.com/mossy1022",](https://github.com/Mossy1022/Smart-Connections-Visualizer/blob/3ca571bf2a7fdab066791e4c86ce92d5fc628eb0/manifest.json#L9)
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link remove this line.

[interface ScGraphViewSettings {](https://github.com/Mossy1022/Smart-Connections-Visualizer/blob/3ca571bf2a7fdab066791e4c86ce92d5fc628eb0/main.ts#L4-L10).
Remove this code

[getViewType(): string {](https://github.com/Mossy1022/Smart-Connections-Visualizer/blob/3ca571bf2a7fdab066791e4c86ce92d5fc628eb0/main.ts#L90-L92), [this.registerView("Smart Connections Visualizer", (leaf: WorkspaceLeaf) => new ScGraphItemView(leaf));](https://github.com/Mossy1022/Smart-Connections-Visualizer/blob/3ca571bf2a7fdab066791e4c86ce92d5fc628eb0/main.ts#L1790), [type: "Smart Connections Visualizer",](https://github.com/Mossy1022/Smart-Connections-Visualizer/blob/3ca571bf2a7fdab066791e4c86ce92d5fc628eb0/main.ts#L1806)
The view type should not have spaces.

[return "Smart Connections Visualizer";](https://github.com/Mossy1022/Smart-Connections-Visualizer/blob/3ca571bf2a7fdab066791e4c86ce92d5fc628eb0/main.ts#L95). [label.textContent = `Min Relevance: ${(newScoreThreshold * 100).toFixed(0)}%`;](https://github.com/Mossy1022/Smart-Connections-Visualizer/blob/3ca571bf2a7fdab066791e4c86ce92d5fc628eb0/main.ts#L817), ['scoreThresholdLabel': `Min Relevance: ${(this.relevanceScoreThreshold * 100).toFixed(0)}%`,](https://github.com/Mossy1022/Smart-Connections-Visualizer/blob/3ca571bf2a7fdab066791e4c86ce92d5fc628eb0/main.ts#L1061-L1071), [this.registerHoverLinkSource('Smart Connections Visualizer', {](https://github.com/Mossy1022/Smart-Connections-Visualizer/blob/3ca571bf2a7fdab066791e4c86ce92d5fc628eb0/main.ts#L1793), [display: 'Smart Connections Visualizer Hover Link Source',](https://github.com/Mossy1022/Smart-Connections-Visualizer/blob/3ca571bf2a7fdab066791e4c86ce92d5fc628eb0/main.ts#L1794), [this.addRibbonIcon('git-fork', 'Smart Connections Visualizer'](https://github.com/Mossy1022/Smart-Connections-Visualizer/blob/3ca571bf2a7fdab066791e4c86ce92d5fc628eb0/main.ts#L1799)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[debounce(func: Function, wait: number) {](https://github.com/Mossy1022/Smart-Connections-Visualizer/blob/3ca571bf2a7fdab066791e4c86ce92d5fc628eb0/main.ts#L820-L826)
This is already a function in the Obsidian API, no need to reinvent the wheel.

[// This adds a status bar item to the bottom of the app. Does not work on mobile apps.](https://github.com/Mossy1022/Smart-Connections-Visualizer/blob/3ca571bf2a7fdab066791e4c86ce92d5fc628eb0/main.ts#L1811-L1873)
Remove all of the sample code.

**Comment by Mossy1022** [comment]
@joethei Thanks! I made the changes and created a new release.

**Comment by Mossy1022** [comment]
@joethei I have been ensuring the code for community json doesn't have merge conflicts as you add more plugins to it.  However after the latest changes to community json it's getting this weird error.  Even when I revert back to when there was no error, the same error appears.  Hopefully this doens't delay anything, but please let me know.  Everything should be good to go :)

**Comment by joethei** [comment]
[settings: any](https://github.com/Mossy1022/Smart-Connections-Visualizer/blob/b5e6d3af87f8c88cf9f2f82d1d008e45ffdb2e11/main.ts#L1790), [await this.loadSettings();](https://github.com/Mossy1022/Smart-Connections-Visualizer/blob/b5e6d3af87f8c88cf9f2f82d1d008e45ffdb2e11/main.ts#L1793), [async loadSettings()](https://github.com/Mossy1022/Smart-Connections-Visualizer/blob/b5e6d3af87f8c88cf9f2f82d1d008e45ffdb2e11/main.ts#L1819-L1825).
Your plugin does not offer any settings, remove this.

**Comment by Mossy1022** [comment]
@joethei I have removed the settings and added a new release.  Thanks!

**Pull request merged**
