### PR TITLE
Add new plugin `Code Emitter`

### PR DESCRIPTION
**Pull request by mokeyish**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/mokeyish/obsidian-code-emitter

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by liamcain** [comment]
- [class MyPlugin](https://github.com/mokeyish/obsidian-code-emitter/blob/49edc9cb3941f1463ab037a71865ebc92c1e4fbd/src/main.ts#L15) You should rename your plugin class. Obsidian will spit out the plugin class if a plugin fails to load, so this will be important for users to debug if they need to
- [`<div />`](https://github.com/mokeyish/obsidian-code-emitter/blob/49edc9cb3941f1463ab037a71865ebc92c1e4fbd/src/CodeRunning.svelte#L2) I suggest adding a classname to these divs so that you can target them via classname in the CSS. It's a bit faster for the CSS matching algorithm to parse.
- It looks like there's a lot of code in here ripped directly from https://github.com/umijs/qiankun without an attribution. You'll need to include the license for the code that you are using in order to legally include it in your plugin.
- [@import url(https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome@6.x/css/all.css);](https://github.com/mokeyish/obsidian-code-emitter/blob/49edc9cb3941f1463ab037a71865ebc92c1e4fbd/src/app.scss#L1) why are you bundling fortawesome? Is it being used at all?

**Comment by ericaxu** [comment]
@mokeyish Hi! Do you still intend to submit this plugin? Thanks!

**Comment by mokeyish** [comment]
> @mokeyish Hi! Do you still intend to submit this plugin? Thanks!

Hi!, what's the else that I need to update?

**Comment by ericaxu** [comment]
> > @mokeyish Hi! Do you still intend to submit this plugin? Thanks!
> 
> Hi!, what's the else that I need to update?

Please try to resolve the comments from @liamcain above, that would be a start. Thanks!

**Comment by mokeyish** [comment]
@ericaxu Hi, I've solved the issues above, please review again.

**Comment by liamcain** [comment]
Hi @mokeyish, one small issue. You're missing the release for 0.0.8. You need the manifest.json version to match the latest release, otherwise it won't properly get installed when a user downloads the plugin.

**Comment by liamcain** [comment]
Hi @mokeyish, just wanted to check to see if you saw my above message.

**Comment by mokeyish** [comment]
Sorry for late reply, I have add the missing release 0.0.8. please review again. Thanks!

**Pull request merged**
