### PR TITLE
Add Simple Embeds plugin

### PR DESCRIPTION
**Pull request by samwarnick**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/samwarnick/obsidian-simple-embeds/tree/main

## Release Checklist

- [x] I have tested this on Windows, macOS, and Linux _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/samwarnick/obsidian-simple-embeds/blob/5f6fa2b65955f3bfe2e441a354676e8c680900d3/main.ts#L55
Suggest using `a.external-link` here to match external links only.

https://github.com/samwarnick/obsidian-simple-embeds/blob/5f6fa2b65955f3bfe2e441a354676e8c680900d3/main.ts#L92
Might want to add allow fullscreen. Please also add a sandbox restriction.

https://github.com/samwarnick/obsidian-simple-embeds/blob/5f6fa2b65955f3bfe2e441a354676e8c680900d3/main.ts#L30
Consider only loading the twitter script when a twitter embed is detected, rather than on plugin initialize (which runs on startup). This will prevent twitter's script from loading if the user isn't using any twitter embeds (or disabled the feature), and makes app startup slightly faster.

**Comment by samwarnick** [comment]
@lishid Thanks, I've made those changes.

However, the sandbox for the YouTube iframe required `allow-scripts allow-same-origin allow-presentation allow-popups` to work properly, and my understanding is that requiring `allow-scripts` and `allow-same-origin` defeats the purpose of sandboxing. I not very familiar with sandboxing, so any guidance would be appreciated.

I also did not enable fullscreen because there seems to be some sort of bug in Obsidian that automatically closes it under certain conditions. Using just pure iframes and disabling my plugin, fullscreen for the second video does not work:

```md
%%broken.md%%
<iframe
  src="https://www.youtube.com/embed/C4sAUc_ZGMY"
  title="YouTube video player"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; fullscreen"
  sandbox="allow-scripts allow-same-origin allow-presentation allow-popups"
></iframe>

<iframe
  src="https://www.youtube.com/embed/C4sAUc_ZGMY"
  title="YouTube video player"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; fullscreen"
  sandbox="allow-scripts allow-same-origin allow-presentation allow-popups"
></iframe>
```

But if you remove blank line between the iframes, fullscreen on the second video works:

```md
%%works.md%%
<iframe
  src="https://www.youtube.com/embed/C4sAUc_ZGMY"
  title="YouTube video player"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; fullscreen"
  sandbox="allow-scripts allow-same-origin allow-presentation allow-popups"
></iframe>
<iframe
  src="https://www.youtube.com/embed/C4sAUc_ZGMY"
  title="YouTube video player"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; fullscreen"
  sandbox="allow-scripts allow-same-origin allow-presentation allow-popups"
></iframe>
```

When I take the generated HTML and put it in a basic index.html, it also seems to work fine.

**Comment by lishid** [comment]
> However, the sandbox for the YouTube iframe required allow-scripts allow-same-origin allow-presentation allow-popups to work properly, and my understanding is that requiring allow-scripts and allow-same-origin defeats the purpose of sandboxing. I not very familiar with sandboxing, so any guidance would be appreciated.

Just having a sandbox directive also adds protections for a few possible cross-frame access I believe, even if you allowed everything. Obsidian's sanitization by default allows for `allow-forms allow-presentation allow-same-origin allow-scripts allow-modals`.

> I also did not enable fullscreen because there seems to be some sort of bug in Obsidian that automatically closes it under certain conditions. Using just pure iframes and disabling my plugin, fullscreen for the second video does not work:
Your test case seems to work fine for me...

**Comment by samwarnick** [comment]
Thanks for the clarification @lishid.

I'll look into fullscreen more, but I'm still having issues with it in a brand new vault with no plugins enabled. It sometimes even makes Obsidian go fullscreen instead of the video.

**Comment by samwarnick** [comment]
I'm on macOS with version 0.12.15 for both the app and installer.

**Comment by lishid** [comment]
Hmmm that's weird. Perhaps it's broken on MacOS since I'm testing on a Windows 10 machine.

**Pull request merged**
