### PR TITLE
Add plugin: Gamificate your PKM

### PR DESCRIPTION
**Pull request by saertna**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [obsidian-gamified-pkm](https://github.com/saertna/obsidian-gamified-pkm)

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Please remove the `main.js` file from the repo and add it to your .gitignore - compiled release files shouldn't get mixed with source code in your commits and should go to the releases files instead.

["styles": ["styles.css"]](https://github.com/saertna/obsidian-gamified-pkm/blob/6106e3a395c8cdaaac53d68a6e246eaee35f7e6b/manifest.json#L11)
This is not part of the manifest spec.

[const style = document.createElement('style');](https://github.com/saertna/obsidian-gamified-pkm/blob/6106e3a395c8cdaaac53d68a6e246eaee35f7e6b/src/main.ts#L1-L14)
This should be part of the `styles.css` file.

[getSettingString(key: string) {](https://github.com/saertna/obsidian-gamified-pkm/blob/6106e3a395c8cdaaac53d68a6e246eaee35f7e6b/src/main.ts#L64-L112)
Is there a reason why you are encryption the settings values?
It feels pointless, since the data is not confidential.

[name: 'open booter pallete',](https://github.com/saertna/obsidian-gamified-pkm/blob/6106e3a395c8cdaaac53d68a6e246eaee35f7e6b/src/main.ts#L187)
It looks like there is a typo here, as the id is `boosters`

["Calculate Note Maturity"](https://github.com/saertna/obsidian-gamified-pkm/blob/6106e3a395c8cdaaac53d68a6e246eaee35f7e6b/src/main.ts#L194) and many more.
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[console.log(`note-maturity >=1`)](https://github.com/saertna/obsidian-gamified-pkm/blob/6106e3a395c8cdaaac53d68a6e246eaee35f7e6b/src/main.ts#L499) and more
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[fs.readdirSync(dir);](https://github.com/saertna/obsidian-gamified-pkm/blob/6106e3a395c8cdaaac53d68a6e246eaee35f7e6b/src/majuritycalculation.ts#L363)
Instead of using the `fs` API you should use the vault API.

[path.join(dir, file)](https://github.com/saertna/obsidian-gamified-pkm/blob/6106e3a395c8cdaaac53d68a6e246eaee35f7e6b/src/majuritycalculation.ts#L366)
Just join the two with a simple `/`, together with the change above, this code will now be mobile compatible.

[stockInfo.innerHTML += `${this.getIngerementFromName(element).shortName} [${this.remainingStock[this.getIngerementFromName(element).name] || 0}]&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`;](https://github.com/saertna/obsidian-gamified-pkm/blob/6106e3a395c8cdaaac53d68a6e246eaee35f7e6b/src/MultiSelectModal.ts#L217-L218), and more.
[Avoid using `innerHTML`](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%60innerHTML%60%2C+%60outerHTML%60+and+%60insertAdjacentHTML%60)

[const coffeeDiv = containerEl.createDiv("coffee");](https://github.com/saertna/obsidian-gamified-pkm/blob/6106e3a395c8cdaaac53d68a6e246eaee35f7e6b/src/settings.ts#L297-L306)
This should not be the very first thing a user sees.

[containerEl.createEl('h2', { text: 'General' });](https://github.com/saertna/obsidian-gamified-pkm/blob/6106e3a395c8cdaaac53d68a6e246eaee35f7e6b/src/settings.ts#L312)
[Don't use a "general" heading in your settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[export function isTFile(value: TAbstractFile): value is TFile {](https://github.com/saertna/obsidian-gamified-pkm/blob/6106e3a395c8cdaaac53d68a6e246eaee35f7e6b/src/utils.ts#L10)
use a `instanceof` check instead.

**Comment by saertna** [comment]
@joethei, I fixed all you findings. Your listing was of great help to work through the code and improve it. 
You are rigth, data.json contains no confidential data. The gamification get's pointless if you just need to edit the data.json to reach levels, get boosters and so an. To prevent the 'player' looses motivation by just cheating himself, it's encrypted. That's the only backgroud for encrypting data.json.

**Comment by liamcain** [comment]
@saertna No need to keep rebasing the plugin. I will rebase the pull request after it gets approved.

**Comment by saertna** [comment]
Ah, thanks for letting me know @liamcain.

**Pull request merged**
