### PR TITLE
Add NoteTweet plugin

### PR DESCRIPTION
**Pull request by chhoumann**
Hi!

I hope this is useful to Obsidian users.
It allows them to post tweets directly from Obsidian.

Regards,
Christian

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/chhoumann/notetweet_obsidian/blob/4b12e71356776498b12a914ed011bbe4f27f2ae8/src/main.ts#L37

Please use `Workspace.getActiveViewOfType(MarkdownView)` here too.

**Comment by chhoumann** [comment]
Thank you! I've fixed it.

**Comment by lishid** [comment]
Seems like the PR changed the whole file - I suspect github web is the cause. Any chance you can fix the PR?

**Comment by chhoumann** [comment]
Done! Should only include the plugin info now. (and some end-of-lines apparently)

**Comment by lishid** [comment]
Yeah uhhh... your PR is still rewriting the entire file because of the line endings change. Any chance you can force-push a commit to only change the part you're adding? If not you can always open a clean PR and I'll prioritize having that merged.

**Comment by chhoumann** [comment]
Haha alright. I reset and force pushed. Is this fine? Otherwise, I'll just create a new PR. 😄

**Comment by lishid** [comment]
Ok you did force push, but the commit you pushed seems to be old, as in it's missing plugins that got merged in the last few days.
That's why Github isn't letting me merge. Try this: Rebase your commit off latest master, then force-push that one.

**Comment by lishid** [comment]
Here let me commit it in for you instead. https://github.com/obsidianmd/obsidian-releases/commit/afd542626a6297c98dfb2dfa8ca9a05ee22f4c8a

**Pull request closed without merging**
