### PR TITLE
Add plugin: Tag Breakdown Generator

### PR DESCRIPTION
**Pull request by HananoshikaYomaru**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/HananoshikaYomaru/obsidian-tag-generator/tree/1.0.3

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[MyPlugin](https://github.com/HananoshikaYomaru/obsidian-tag-generator/blob/1b32091e4a94ee1fdea566030d88e5f321dcd025/src/main.ts#L16)
Rename this.

---

[Copyright (c) 2023 Yeung Man Lung Ken](https://github.com/HananoshikaYomaru/obsidian-tag-generator/blob/1b32091e4a94ee1fdea566030d88e5f321dcd025/LICENSE#L3)
The name looks to be wrong.

**Comment by HananoshikaYomaru** [comment]
Actually `Yeung Man Lung Ken` is my real name (on my passport). `Hananoshika Yomaru` is my Japanese nickname. Should I use my real name or nickname?

**Comment by liamcain** [comment]
- [eventRefs](https://github.com/HananoshikaYomaru/obsidian-tag-generator/blob/fb1c4a4477c1ea528ef171b00c3b4ed283d2457e/src/main.ts#L17) this looks unused.
- [window.CodeMirrorAdapter.commands.save](https://github.com/HananoshikaYomaru/obsidian-tag-generator/blob/fb1c4a4477c1ea528ef171b00c3b4ed283d2457e/src/main.ts#L90) this doesn't seem related to your plugin?
- [getYAMLText](https://github.com/HananoshikaYomaru/obsidian-tag-generator/blob/fb1c4a4477c1ea528ef171b00c3b4ed283d2457e/src/main.ts#L10) you should use the parseYaml and stringifyYaml commands exported from the Obsidian API instead of reimplementing them yourself.

Also, not sure if you're aware that some of your Diary notes are public on the [linked site](https://yomaru.dev/). Just warning you in case that's not intentional.

**Comment by HananoshikaYomaru** [comment]
@liamcain Yes, this is intentional. All my diary is public.

**Pull request merged**
