### PR TITLE
Add plugin: POWER MODE

### PR DESCRIPTION
**Pull request by zhouhua**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/zhouhua/obsidian-power-mode

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by zhouhua** [comment]
/skip

In this plugin, the majority of static styles have been extracted into CSS, with the code setting styles through JavaScript almost exclusively for dynamic styles, which I believe is reasonable.

**Comment by zhouhua** [comment]
What else do I need to do to enter the review phase?

**Comment by joethei** [comment]
[this.app.workspace.on("editor-change", (editor) => {](https://github.com/zhouhua/obsidian-power-mode/blob/42846e03843bf8650c4af9c68f957002f6e2337d/main.ts#L16)
Events need to be registered, so they can be properly unloaded when the plugin is disabled. <https://docs.obsidian.md/Plugins/Events>

[imageList: ["https://i.imgur.com/iDcBoNm.gif"],](https://github.com/zhouhua/obsidian-power-mode/blob/42846e03843bf8650c4af9c68f957002f6e2337d/src/presets/explosion/pikachu.ts#L15), ["https://nyanpandablog.files.wordpress.com/2016/04/nyan-panda2.gif?w=256",](https://github.com/zhouhua/obsidian-power-mode/blob/42846e03843bf8650c4af9c68f957002f6e2337d/src/presets/explosion/nyan.ts#L16), ["https://media.giphy.com/media/sLMRyFR4eIEgnFe4mK/giphy.gif",](https://github.com/zhouhua/obsidian-power-mode/blob/42846e03843bf8650c4af9c68f957002f6e2337d/src/presets/explosion/lightning.ts#L16-L18), [imageList: ["https://i.imgur.com/CY4UUfd.gif"],](https://github.com/zhouhua/obsidian-power-mode/blob/42846e03843bf8650c4af9c68f957002f6e2337d/src/presets/explosion/emoji.ts#L14), [imageList: ["https://imgur.com/nfgkSBD.gif"],](https://github.com/zhouhua/obsidian-power-mode/blob/42846e03843bf8650c4af9c68f957002f6e2337d/src/presets/explosion/butterfly.ts#L15)
This needs to be bundled like the other images, also make sure that you are allowed to embed these images

[<h3>POWER MODE!</h3>](https://github.com/zhouhua/obsidian-power-mode/blob/42846e03843bf8650c4af9c68f957002f6e2337d/src/components/setting/Panel.tsx#L94-L103) 
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by zhouhua** [comment]
Hi @joethei . Thank you for reviewing my code. I have fixed the issues you raised.

**Comment by zhouhua** [comment]
Hi @joethei, please help to review my code again.

**Comment by zhouhua** [comment]
Hi @joethei, please help to review my code again.

**Comment by khaledkun** [comment]
good job bro

**Comment by zhouhua** [comment]
Hi @joethei, please help to review my code again 🙏 .

**Comment by joethei** [comment]
You missed this part:
> also make sure that you are allowed to embed these images

**Comment by zhouhua** [comment]
@joethei 

Sorry for the long delay. It was very difficult to find and obtain authorization from the original creators of the animations used in my plugin. Therefore, I kept the authorized effects and removed the others.

All animations included in the plugin are covered by one of the following three types of authorization (noted in the code files):

1. Copied from [https://github.com/hoovercj/vscode-power-mode](https://github.com/hoovercj/vscode-power-mode), under the MIT license.
2. Original author granted permission via email.
3. Copied from [https://lottiefiles.com/](https://lottiefiles.com/), under the [Lottie Simple License](https://lottiefiles.com/page/license).

Please help review this again, thanks.

**Pull request merged**
