### PR TITLE
Add plugin: PDF break page

### PR DESCRIPTION
**Pull request by corentin-godefroy**
# I am submitting a new Community Plugin
---
## Repo URL
Link to my plugin: https://github.com/corentin-godefroy/Obsidian-BreakPage

## Release Checklist
 I have tested the plugin on
 - [x] Windows
 - [ ] macOS
 - [ ] Linux
 - [x] Android (if applicable)
 - [ ] iOS (if applicable)

- [x] My GitHub release contains all required files
 - [x] main.js
 - [x] manifest.json
 - [x] styles.css (optional)

- [x] GitHub release name matches the exact version number specified in my manifest.json (Note: Use the exact version number, don't include a prefix v)
- [x] The id in my manifest.json matches the id in the community-plugins.json file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
- [x] I have given proper attribution to these other projects in my README.md.

## What my plugin do

Insert at the cursor position this string : `<div class="page-break" style="page-break-before: always;"></div>\n` to create a break page when we export to pdf the .md file.

When done, it formats the line using "page-break" class defined on the style.css file, to print this line : "Break page. Need at least 1 blank line after.", to point out there are a break page at this line. This line is not exported on pdf and are purely estetics.

### CODE REVIEW

**Comment by corentin-godefroy** [comment]
retry

**Comment by corentin-godefroy** [comment]
Wht is the status of validation for my plugin ?

**Comment by corentin-godefroy** [comment]
/skip The master branch is updated, and no more conflicts on the pr

**Comment by joethei** [comment]
[hotkeys: [{ modifiers: ["Alt"], key: "b" }],](https://github.com/corentin-godefroy/Obsidian-BreakPage/blob/09639dd54c2ed40a437ce529ac216aa777613dfd/main.ts#L8)
We recommend against providing a default hotkey when possible. The reason being that it's easy to pick a hotkey that a user already has configured and they could get confused when that key doesn't do what they expect. Also, it's hard choosing a safe default hotkey that's available for all operating systems & does not conflict with existing plugins.

**Comment by corentin-godefroy** [comment]
> [hotkeys: [{ modifiers: ["Alt"], key: "b" }],](https://github.com/corentin-godefroy/Obsidian-BreakPage/blob/09639dd54c2ed40a437ce529ac216aa777613dfd/main.ts#L8) We recommend against providing a default hotkey when possible. The reason being that it's easy to pick a hotkey that a user already has configured and they could get confused when that key doesn't do what they expect. Also, it's hard choosing a safe default hotkey that's available for all operating systems & does not conflict with existing plugins.

It's updated !

**Pull request merged**
