### PR TITLE
Adding Colorful Note Borders (obsidian-colorful-note-borders) plugin to community-plugins.json

### PR DESCRIPTION
**Pull request by rusi**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/rusi/obsidian-colorful-note-borders

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["main": "main.js"](https://github.com/rusi/obsidian-colorful-note-borders/blob/d736ebf425d98807d615b5fcb2e45ac533b05583/manifest.json#L9)
The Obsidian manifest does not contain this value.

It looks like your plugin will not work with pop-out windows.
See here how to update your plugin to support pop out windows:
<https://forum.obsidian.md/t/plugin-developers-how-to-update-your-plugin-to-support-pop-out-windows/40228>

**Comment by rusi** [comment]
Thanks for the feedback. Are you referring to `manifest.json` that is included in the release? 
Is this (the link below) what you expect to see there? 
https://github.com/rusi/obsidian-colorful-note-borders/blob/master/manifest.json#L9

I also tested the plugin with pop-out windows and the border properly renders (see screenshot). The code uses `this.app.workspace.getActiveViewOfType(MarkdownView);` which is why I think this works in this case. Is there a different, preferred way to do this?

image

**Comment by joethei** [comment]
Sorry, was a bit imprecise.
That `main` key & value should not be in the `manifest.json`, as that is not part of the spec.
 If you look at [our sample plugin](https://github.com/obsidianmd/obsidian-sample-plugin/blob/master/manifest.json) you'll see that it's not there either.

Interesting that it works in pop out windows, looks like Obsidian works a bit different in that regard than I though.
I originally mentioned that because of the calls to `document`, as that only references the main window.

**Comment by rusi** [comment]
Thank you for clarifying and I am sorry I misread your comment. I've removed the "main: main.js" line.

I also fixed how the views are updated so that it works properly when using splits (and popup windows).

**Comment by liamcain** [comment]
- [activeView.containerEl.querySelector(".view-content");](https://github.com/rusi/obsidian-colorful-note-borders/blob/91f980ce90d037934d7961925c4a831f11108651/src/main.ts#L99) this can be view.contentEl instead to avoid querying the dom (might need to cast to `any` if that var is not public
- [document](https://github.com/rusi/obsidian-colorful-note-borders/blob/91f980ce90d037934d7961925c4a831f11108651/src/main.ts#L85) I don't think this will work if you have a [pop-out window](https://help.obsidian.md/User+interface/Pop-out+windows) open.
- [applyRules](https://github.com/rusi/obsidian-colorful-note-borders/blob/91f980ce90d037934d7961925c4a831f11108651/src/main.ts#L93) you should probably [debounce](https://github.com/obsidianmd/obsidian-api/blob/1b4f6e2e5753c8ac2d538bc5d55c38f228450cb2/obsidian.d.ts#L772) applyRules to avoid it getting called to frequently and causing the app to slow down.

**Pull request merged**
