### PR TITLE
Add plugin: doing

### PR DESCRIPTION
**Pull request by Rooyca**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Rooyca** [comment]
> Optional
> [[1](https://github.com/rooyca/doing/blob/2c0882efe8b25561b4bd8d6c5debebef0230aee3/src/ui/doingMenu.ts#L15)]:Casting to any should be avoided as much as possible.

Do I need to change this?

**Comment by joethei** [comment]
[this.statusBarIcon.setAttribute("aria-label", "Doing");](https://github.com/Rooyca/doing/blob/2c0882efe8b25561b4bd8d6c5debebef0230aee3/src/plugin/main.ts#L33-L34)
Replace this with: `setTooltip(this.statusBarIcon, 'Doing');`

[containerEl.createEl("h1", { text: "Doing" });](https://github.com/Rooyca/doing/blob/2c0882efe8b25561b4bd8d6c5debebef0230aee3/src/settings/settingsTab.ts#L20-L25)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by Rooyca** [comment]
Ok, thanks @joethei. I've already changed it.

**Comment by joethei** [comment]
[containerEl.createEl("h2", { text: "Status-bar" });](https://github.com/Rooyca/doing/blob/70206bdc1753d6b6aaa37f1313ddea7041bd1e43/src/settings/settingsTab.ts#L16)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by Rooyca** [comment]
I left it because I thought it looked weird without a title, but I'm going to remove it now.

Thanks.

**Pull request merged**
