### PR TITLE
Update community-plugins.json

### PR DESCRIPTION
**Pull request by phibr0**
# I am submitting a new Community Plugin: Commander

In this PR I also removed my old Customizable Sidebar Plugin. This one is a much improved rewrite with a lot more features!

## Repo URL

Link to my plugin: https://github.com/phibr0/obsidian-commander

image

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by phibr0** [comment]
Fixed! (In all places)

**Comment by liamcain** [comment]
- [document.head.querySelector("style#cmdr")?.remove();](https://github.com/phibr0/obsidian-commander/blob/79d164aef5aa6fa580fa1e6b1afc64f867f063c0/src/main.ts#L74-L75) You should probably remove this from all windows, in case the styles were added to popout windows as well
- Not sure the root cause in code, but horizontal scrolling in the settings tab bar seems to be broken. It automatically scrolls itself back to the far left when scrolling


Otherwise looks great! Nice job

**Comment by phibr0** [comment]
> Not sure the root cause in code, but horizontal scrolling in the settings tab bar seems to be broken. It automatically scrolls itself back to the far left when scrolling

Hmm, it works fine for me. Are you using a touchpad or something?

**Comment by liamcain** [comment]
Yeah, I'm using a macbook trackpad.

**Comment by phibr0** [comment]
It's working fine on my laptop (linux/fedora/gnome). But to make it easier for normal mouse users it's converting vertical scroll to be horizontal. Are you trying to scroll horizontal?

**Comment by liamcain** [comment]
ah, yes. vertical scrolling seems to work fine, but horizontal scrolling is disabled. I see.

**Pull request merged**
