### PR TITLE
Added obsidian-bellboy community plugin.

### PR DESCRIPTION
**Pull request by shakedlokits**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/shakedlokits/obsidian-bellboy

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by ericaxu** [comment]
Indentation of the first line (`id`) seems a bit off. Could you fix that please?

**Comment by lishid** [comment]
Since you are using emoji icons for the file name, I think you should clarify that some file sync services and operating systems don't support emojis in file names. Most notably I think Dropbox doesn't like them and Android doesn't support them.

https://github.com/shakedlokits/obsidian-bellboy/releases/tag/1.0.0
Your release is missing the required files

https://github.com/shakedlokits/obsidian-bellboy/blob/4db3313046aa08a5e195dd7b95fc5c45772333ba/main.ts#L2
I highly suggest just implementing these functions in your code instead of importing an entire utilities library just for these. 

https://github.com/shakedlokits/obsidian-bellboy/blob/4db3313046aa08a5e195dd7b95fc5c45772333ba/main.ts#L4
You don't have to parse the frontmatter yourself, Obsidian already has a parsed version in `metadataCache` for each file. What you'll want to do is to hook the `metadataCache.on('change')` event and process files from there.

https://github.com/shakedlokits/obsidian-bellboy/blob/4db3313046aa08a5e195dd7b95fc5c45772333ba/main.ts#L35
You should check if the new file name is different from the old before attempting to rename it. Renaming files is a pretty resource intensive process since we need to keep track of links often times.

**Comment by shakedlokits** [comment]
Hi @lishid and @ericaxu,

Thank you for your thorough review, I really appreciated it! 
I addressed all your points.

> Your release is missing the required files

Added LICENSE file, also added the [recommended release workflow](https://marcus.se.net/obsidian-plugin-docs/publishing/release-your-plugin-with-github-actions)

> I highly suggest just implementing these functions in your code instead of importing an entire utilities library just for these.

I moved to a direct address import and checked to make sure that it wrangles correctly on build, I'm happy to say only the relevant code was built into the `main.js`

> You don't have to parse the frontmatter yourself, Obsidian already has a parsed version in metadataCache for each file. What you'll want to do is to hook the metadataCache.on('change') event and process files from there.

I didn't find it originally in the documentation(which can have some improvements) and it was a fantastic pointer! You cleaned my code by about a half 👌🏽

> You should check if the new file name is different from the old before attempting to rename it. Renaming files is a pretty resource intensive process since we need to keep track of links often times.

Added the check.

> Indentation of the first line (id) seems a bit off. Could you fix that please?

Fixed.

Thank you again,
And I hope we can push it through this time

**Review by liamcain — APPROVED** [review]

**Comment by liamcain** [comment]
Hi @shakedlokits, before I merge, I just wanted to confirm that you're okay with your email showing up in the author list in the Plugin gallery. It will be visible here:

author-section

**Review by shakedlokits — COMMENTED** [review]
Cleaned up

**Review by shakedlokits — COMMENTED** [review]
Added the new entry to the end

**Review by shakedlokits — COMMENTED** [review]
Added the new entry to the end

**Comment by shakedlokits** [comment]
Hi @liamcain, 
Thanks for the heads-up, fixed.

Sorry for the messy commits, tried the new github.dev for pull requests, its not ready yet😅

**Pull request merged**
