### PR TITLE
Add plugin: TickTickSync

### PR DESCRIPTION
**Pull request by thesamim**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/thesamim/TickTickSync

## Release Checklist
- [X] I have tested the plugin on
  - [X]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [X] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by thesamim** [comment]
Apologies for the multiple pull requests.

**Comment by joethei** [comment]
["authorUrl": "https://github.com/thesamim/TickTickSync",](https://github.com/thesamim/TickTickSync/blob/6584caea2591a627d84732235017a7fe308450d7/manifest.json#L8)
This should point to your website or GitHub profile, not to the plugin repo.

["fundingUrl": "",](https://github.com/thesamim/TickTickSync/blob/6584caea2591a627d84732235017a7fe308450d7/manifest.json#L9)
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link omit this.

["description": "A bidirectional sync plugin for TickTick",](https://github.com/thesamim/TickTickSync/blob/6584caea2591a627d84732235017a7fe308450d7/manifest.json#L6)
Avoid the word "plugin" in your description.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[this.app.workspace.on('active-leaf-change', (leaf) => {](https://github.com/thesamim/TickTickSync/blob/6584caea2591a627d84732235017a7fe308450d7/main.ts#L225-L227)
you forgot to register this event.

[containerEl.createEl('h2', { text: 'Settings for TickTick Sync for Obsidian.' });](https://github.com/thesamim/TickTickSync/blob/6584caea2591a627d84732235017a7fe308450d7/src/settings.ts#L62)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)


[.setName('Automatic Sync Interval Time')](https://github.com/thesamim/TickTickSync/blob/6584caea2591a627d84732235017a7fe308450d7/src/settings.ts#L108) and more.
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by thesamim** [comment]
@joethei : Thank you for the feedback. Am traveling right now, will take care of ASAP. 

Q: When I make and commit my changes, and create a new release, do I need to do a new pull request here?

**Comment by thesamim** [comment]
@joethei Comments addressed. Please see release 1.0.6

**Comment by thesamim** [comment]
Please let me know if I need to do anything else. Thanks.

**Comment by liamcain** [comment]
- [const view = this.app.workspace.getActiveViewOfType(MarkdownView);](https://github.com/thesamim/TickTickSync/blob/7a6b77618c664bcc6a6df29d5ad2c2c281602458/main.ts#L68-L69) these lines are wrong. You should use the same editor that you just checked hasFocus()
- [const view = this.app.workspace.getActiveViewOfType(MarkdownView)](https://github.com/thesamim/TickTickSync/blob/7a6b77618c664bcc6a6df29d5ad2c2c281602458/main.ts#L105-L106) these lines aren't even used
- [target](https://github.com/thesamim/TickTickSync/blob/7a6b77618c664bcc6a6df29d5ad2c2c281602458/main.ts#L113) you also need to check that target exists. It could be null
- [checkModuleClass](https://github.com/thesamim/TickTickSync/blob/7a6b77618c664bcc6a6df29d5ad2c2c281602458/main.ts#L116) shouldn't this happen before anything else in the event listener?
- [view.app.workspace.getActiveViewOfType(MarkdownView)?.app.workspace.activeEditor?.file?.name](https://github.com/thesamim/TickTickSync/blob/7a6b77618c664bcc6a6df29d5ad2c2c281602458/main.ts#L400) this chain of code isn't that cheap. If you need to do the same operation immediately after, you should assign the intermediate value (such as "file") to a variable.

**Comment by thesamim** [comment]
@liamcain : Thanks for the feedback. Changes made.

New release created: 1.0.7

Please let me know if you need anything else.

**Comment by thesamim** [comment]
@liamcain , @joethei : Thanks so much for the feedback and assistance. Much appreciated.

**Pull request merged**
