### PR TITLE
add "Day In The Life" plugin

### PR DESCRIPTION
**Pull request by ohmygaugh-crypto**
Please switch to **Preview** and select one of the following links:

* [Community Plugin](?template=plugin.md)
* [Community Theme](?template=theme.md)

### CODE REVIEW

**Comment by ohmygaugh-crypto** [comment]
update tag to reflect "1.0.0" and included a license standalone file instead of simply placing it in the README.md.

**Comment by ohmygaugh-crypto** [comment]
update tag to reflect "1.0.0" and included a license standalone file instead of simply placing it in the README.md.

**Comment by ohmygaugh-crypto** [comment]
trying to refresh the pull request after seeing that all checks have failed for ID "2446"

**Comment by ohmygaugh-crypto** [comment]
trying to refresh the pull request after seeing that all checks have failed for ID "2446"

**Comment by joethei** [comment]
@ohmygaugh-crypto Please open a new pull request, and follow the pull request template.

**Pull request closed without merging**
