### PR TITLE
Add Inline Frontmatter Sync Plugin

### PR DESCRIPTION
**Pull request by ransurf**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/ransurf/live-sync-inline-to-yaml

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[import moment from 'moment';](https://github.com/ransurf/live-sync-inline-to-yaml/blob/9a472db992eddc5980120ebb853fc601dfb02790/main.ts#L2)
Obsidian already includes moment, just `import {moment} from "obsidian";`

Rename these:
- [MyPluginSettings](https://github.com/ransurf/live-sync-inline-to-yaml/blob/9a472db992eddc5980120ebb853fc601dfb02790/main.ts#L4)
- [MyPlugin](https://github.com/ransurf/live-sync-inline-to-yaml/blob/9a472db992eddc5980120ebb853fc601dfb02790/main.ts#L14)
- [SampleSettingTab](https://github.com/ransurf/live-sync-inline-to-yaml/blob/9a472db992eddc5980120ebb853fc601dfb02790/main.ts#L145)


[console.log('value', value)](https://github.com/ransurf/live-sync-inline-to-yaml/blob/9a472db992eddc5980120ebb853fc601dfb02790/main.ts#L44)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[this.registerDomEvent(document, 'keydown', (evt: KeyboardEvent) => {](https://github.com/ransurf/live-sync-inline-to-yaml/blob/9a472db992eddc5980120ebb853fc601dfb02790/main.ts#L84)
Use commands for this instead, specifically, an editor command.




[// When registering intervals, this function will automatically clear the interval when the plugin is disabled.](https://github.com/ransurf/live-sync-inline-to-yaml/blob/9a472db992eddc5980120ebb853fc601dfb02790/main.ts#L128-L129)
Remove this sample code.

**Comment by ransurf** [comment]
@joethei thank you for the feedback! I just have one question:

> [this.registerDomEvent(document, 'keydown', (evt: KeyboardEvent) => {](https://github.com/ransurf/live-sync-inline-to-yaml/blob/9a472db992eddc5980120ebb853fc601dfb02790/main.ts#L84)
> Use commands for this instead, specifically, an editor command.

I have been looking through dev docs and discord but have not heard of a way to access the most recent keypress event, which is required for my code to exit early if it the keypress was undo command or a modifier. Can you please direct me as to how I can do so?

**Comment by joethei** [comment]
Sorry for the late response, I was on vacation.

You can access `this.app.lastEvent` for that.
<https://github.com/obsidianmd/obsidian-api/blob/249eb773347588f4e9fec7c600e1904cd9240fcb/obsidian.d.ts#L396-L400>

**Comment by liamcain** [comment]
- [const secondLine = editor.getLine](https://github.com/ransurf/live-sync-inline-to-yaml/blob/22de9987b11f6c9652c0a9a6962e287ed8fbfc16/main.ts#L26) this check seems unnecessary. You could just change the i = 2 to i = 1 below and it will be covered by the for loop
- [updateFrontmatterValue](https://github.com/ransurf/live-sync-inline-to-yaml/blob/22de9987b11f6c9652c0a9a6962e287ed8fbfc16/main.ts#L61) You should be using [processFrontmatter](https://github.com/obsidianmd/obsidian-api/blob/249eb773347588f4e9fec7c600e1904cd9240fcb/obsidian.d.ts#L1367) to update frontmatter values instead.
- [wrapInQuotationsIfString](https://github.com/ransurf/live-sync-inline-to-yaml/blob/22de9987b11f6c9652c0a9a6962e287ed8fbfc16/main.ts#L45) this won't be needed if you use processFrontmatter

**Comment by liamcain** [comment]
- [activeView](https://github.com/ransurf/live-sync-inline-to-yaml/blob/22de9987b11f6c9652c0a9a6962e287ed8fbfc16/main.ts#L94) you should also check if activerView.editor.hasFocus() and early exit.

**Comment by liamcain** [comment]
Hi @ransurf, I hope you're doing well! I just wanted to bump this pull request in case you missed my last messages and are still hoping to get this merged in. Thanks!

**Comment by ransurf** [comment]
Hi, Liam!

Thank you for the reminder and the suggestions, I will get to it when I
find the time :)


All the best,

John Mavrick

**Pull request closed without merging**
