### PR TITLE
Add plugin: oBro Productivity Tools

### PR DESCRIPTION
**Pull request by RococoN8R**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by RococoN8R** [comment]
What is the next step to publish the update?

**Comment by RococoN8R** [comment]
I'm new to github. Updates are committed to my master branch. I need to learn how to publish to patch-1 on the noted branch.

**Comment by joethei** [comment]
Not all of the code changes to your plugin are in the plugin repo's main branch.

patch-1 is of your obsidian-releases fork, you don't have to do anything there.

**Comment by RococoN8R** [comment]
Hi, it looks like the community-plugins.json file needs an update (missing braces between my plugin and the next, but it doesn't look like I have needed access to update. Can you help? Thank you!

**Comment by joethei** [comment]
That will be handled when the plugin is merged.

["name": "oBro Productivity Tools",](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/manifest.json#L3)
This name does not describe what the plugin is doing, it's a bit too generic.

["minAppVersion": "0.15.0",](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/manifest.json#L5)
You are using newer API's, set this to the latest public build number.

["author": "RococoN8R - Ray Bellantoni, Copyright 2024, all rights reserved.",](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/manifest.json#L7)
Remove the Copyright part.

[data.json(https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/data.json#L1-L7)
This file should not be in the repository.

And the README file should not be part of the release.

[console.error(`oBro ${this.manifest.version}: DataView plugin not enabled.`);](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L61)
This should also be shown as a notice, not all users open the console, and mobile users can't.

[statusBar.createEl("span", { text: "oBro's ready!" });](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L65)
This is useless.

[if (window.app.plugins.plugins.dataview) {](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L103)
It's highly discouraged that you use the global app instance in your plugin. It's currently accessible from the global context for debugging purposes, and will be removed from the API in the next release. Instead, you should use the reference to App that you have from your plugin instance.


[dv.header(5, "Page Management");](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L140), [["In Progress", "Backlog", "Completed", "Total"],](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L180), ["This Week",](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L210), ["Next Week",](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L215), ["In Progress",](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L220), ["Completed Recently",](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L225), ["Open Questions",](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L244), [dv.header(tsks.headerSize, "Task Management");](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L290), ["Action Items",](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L345), [dv.header(tsks.headerSize, "Tag Management");](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L379), [this.containerEl.createEl("h2", { text: "Search Pages" });](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L529), [.setName("Search Path")](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L531), [.setName("View Hidden Pages")](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L543), [this.containerEl.createEl("h2", { text: "Search Tags" });](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L556), [.setName("Search Tag")](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L558), [.setName("View List")](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L570), [this.containerEl.createEl("h2", { text: "Task Formatting" });](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L581), [.setName("Header Size")](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L583), [`Overdue: ${this.overdue.length}  This Week: ${this.thisWeek.length}`](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L781)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[console.log(getAPI(window.app).pages());](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L378), [console.log(window.location.origin);](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L886)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[console.error(`oBro ${this.manifest.version}: Settings are loaded!`, this.settings);](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L506), [console.error(`oBro ${this.manifest.version}: Settings are saved!`, this.settings);](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L511)
This should not be logged, and especially not as an error.

[this.containerEl.createEl("h1", { text: "General Settings" });](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L525)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[this.containerEl.createEl("h2", { text: "Search Pages" });](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L529),[this.containerEl.createEl("h2", { text: "Search Tags" });](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L556), [this.containerEl.createEl("h2", { text: "Task Formatting" });](https://github.com/RococoN8R/oBro-productivity/blob/0034997cd1f5e02ec9125b269842d690ab098167/main.ts#L581)
For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```

**Comment by RococoN8R** [comment]
Hi Johannes, thanks for all the feedback. Most of the changes are made, but I wanted to plead a little leniency for the name. The intent of this plugin is to build out a number of tools beyond tasks, tags and pages. Think dashboards, easier keyboard shortcuts, URL grabbers... just a variety of tools to help improve some users' ability to work even faster. I'm concerned about calling it oBro Task and Tag Tools for now, because the intent, as noted in the readme, is to go beyond that. Does the oBro Productivity Tools  name make any more sense?

**Comment by joethei** [comment]
Sorry, but we don't accept plugins that do multiple unrelated things anymore.
It should be split into multiple plugins.

**Comment by RococoN8R** [comment]
Hi Johannes, thanks for the feedback. To align with your approach, I plan to rename this plugin oBro Task+Tag Productivity Tool and keep it focused on just that. Later, I'll create an oBro Dashboard Productivity Tool and other similarly named plugins, each focused on just one aspect of productivity. Does that meet your requirements both in naming and organization of the different functionalities?

**Comment by RococoN8R** [comment]
Code changes are completed for your approval.

**Comment by RococoN8R** [comment]
Hi Johannes, could you provide feedback on both the code updates and the naming?

**Comment by joethei** [comment]
It looks like you forgot to push.

Also please don't brand your plugins as part of a collection, each plugin should stand on it's own.

**Pull request closed without merging**
