### PR TITLE
add deeper work theme

### PR DESCRIPTION
**Pull request by lucas-fern**
# I am submitting a new Community Theme

## Repo URL

Link to my theme: https://github.com/lucas-fern/obsidian-deeper-work-theme

## Theme checklist

- [x] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo).
  - [x] `obsidian.css`
  - [x] The screenshot file.
- [x] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other themes that I'm using.
      I have given proper attribution to these other themes in my `README.md`.

### CODE REVIEW

**Comment by ericaxu** [comment]
Hi @lucas-fern ! Thanks so much for submitting Deeper Work.

Just curious, have you talked to the original author and see if you can maintain Deep Work? If that's not a possibility we can certainly add your theme instead. Thanks!

**Comment by lucas-fern** [comment]
Hey @ericaxu, I did consider this, but haven't reached out. While Deeper Work takes a lot of inspiration from Deep Work, it's a fair bit simpler than the original, for example without light mode or any of the animations that it includes.

While I have ported the dark colour scheme directly, most of the remaining CSS here is new (eg. callouts/blockquotes) or has been adapted from other (publicly licenced) themes.

Ultimately I believe it is a better idea to release this as a new theme, as I don't have enough familiarity with the original to confidently update it for Obsidian 1 compatibility, nor do I wish to support all of the same features as the original theme.

Hopefully this makes sense!

**Comment by lucas-fern** [comment]
Ok no problem, I've just pushed a new thumbnail. I made sure it had the same name so I don't think I have to update the PR? Let me know if I do.

**Comment by ericaxu** [comment]
Looks good! Thanks again for submitting your theme.

**Pull request merged**
