### PR TITLE
Add Omni theme.

### PR DESCRIPTION
**Pull request by librity**
# I am submitting a new Community Theme

This is a theme based on [Omni's Color palette](https://github.com/librity/omni-theme#color-palette).
I used Dracula's css layout.

## Repo URL

Link to my theme: https://github.com/librity/omni-obsidian

## Theme checklist

- [x] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo).
  - [x] `obsidian.css`
  - [x] The screenshot file.
- [x] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other themes that I'm using.
      I have given proper attribution to these other themes in my `README.md`.
- [x] If my repo is not using the `master` branch, please indicate in `community-themes.json` with `"branch": "main"`.

### CODE REVIEW

**Comment by librity** [comment]
@lishid @ericaxu Can I get some love?
It's a cool theme I promise 🤗

**Comment by ericaxu** [comment]
@librity Are you able to test this theme on 0.16? I can help you set it up if you don't have an insider license. Thanks!

**Comment by librity** [comment]
> @librity Are you able to test this theme on 0.16? I can help you set it up if you don't have an insider license. Thanks!

I tested it on 0.15.9
I don't have an insider license, how do I get that?

**Comment by librity** [comment]
@ericaxu How do I test it on `0.16`?

**Comment by ericaxu** [comment]
@librity Sorry for the long review process, we've been busy with a big design overhaul in the recently released v1.0 of Obsidian. Now that 1.0 has been released and Obsidian's UI has undergone some sweeping changes, we are asking all theme entries to confirm that their theme is compatible with the latest version of Obsidian.

**Comment by ericaxu** [comment]
Hi @librity , sorry about the wait!

Have you tested your theme on 1.0? If it works please let me know so I can merge it!

One minor thing: you might want to make the screenshot smaller while keeping the 16:9 aspect ratio. That would make your theme load faster in the theme store. You can still include high resolution screenshots in your README.

We recommend using a screenshot of size 512px by 288px as the featured screenshot to minimize loading time.

**Comment by joethei** [comment]
Hi @librity  do you still intent on submitting this theme?

**Pull request closed without merging**
