### PR TITLE
Update community-css-themes.json

### PR DESCRIPTION
**Pull request by Carrie999**
add new theme named comfort

### CODE REVIEW

**Comment by Carrie999** [comment]
> #### Hello!
> **I found the following issues in your theme submission**
> 
> **Warnings:**
> 
> ⚠️ Theme theme screenshot size is not optimal, we generally recommend a size around 512 × 288 pixels. Detected size: 522 x 188 pixels
> 
> This check was done automatically. Do NOT open a new PR for re-validation. Instead, to trigger this check again, make a change to your PR and wait a few minutes, or close and re-open it.

change to  512 × 288 pixels.

**Comment by joethei** [comment]
Please follow the pull request template.

**Comment by Carrie999** [comment]
> Please follow the pull request template.

where I can find the pr template.I can not find 😭

**Comment by Carrie999** [comment]
# I am submitting a new Community Theme

## Repo URL


Link to my theme: https://github.com/Carrie999/comfort

## Theme checklist


- [x] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo).
  - [x] `manifest.json`
  - [x] `theme.css`
  - [x] The screenshot file (16:9 aspect ratio, recommended size is 512px by 288px for fast loading).
- [x] I have indicated light (dark, light, or both) are compatible with my theme.
- [x]  I have added a license in the LICENSE file.
- [x]  My project respects and is compatible with the original license of any code from other themes that I'm using. I have given proper attribution to these other themes in my `README.md`.

**Comment by Carrie999** [comment]
@joethei  can you help me merge？

**Pull request merged**
