### PR TITLE
Add plugin: Vault Size History

### PR DESCRIPTION
**Pull request by wizentex**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/technerium/obsidian-vault-size-history

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[id: "technerium-vshp-open-graph-modal",](https://github.com/technerium/obsidian-vault-size-history/blob/010b156ff8ffa192b381d9351e444d287b42b097/main.ts#L14)
Remove the `technerium-vshp` prefix.

[name: "Open Graph Modal",](https://github.com/technerium/obsidian-vault-size-history/blob/010b156ff8ffa192b381d9351e444d287b42b097/main.ts#L15), [this.addRibbonIcon("area-chart", "Vault Size History Modal", () => {](https://github.com/technerium/obsidian-vault-size-history/blob/010b156ff8ffa192b381d9351e444d287b42b097/main.ts#L21)
Don't include `Modal` here.

[name: "Open Graph Modal",](https://github.com/technerium/obsidian-vault-size-history/blob/010b156ff8ffa192b381d9351e444d287b42b097/main.ts#L15), [this.addRibbonIcon("area-chart", "Vault Size History Modal", () => {](https://github.com/technerium/obsidian-vault-size-history/blob/010b156ff8ffa192b381d9351e444d287b42b097/main.ts#L21), ['Markdown Files': boolean,](https://github.com/technerium/obsidian-vault-size-history/blob/010b156ff8ffa192b381d9351e444d287b42b097/src/view/MainModal.ts#L22-L24), [MarkdownFiles = 'Markdown Files',](https://github.com/technerium/obsidian-vault-size-history/blob/010b156ff8ffa192b381d9351e444d287b42b097/src/view/MainModal.ts#L28-L30), [text: 'Vault Size'](https://github.com/technerium/obsidian-vault-size-history/blob/010b156ff8ffa192b381d9351e444d287b42b097/src/view/MainModal.ts#L117), [data: ['Markdown Files', 'Other Files', 'All Files']](https://github.com/technerium/obsidian-vault-size-history/blob/010b156ff8ffa192b381d9351e444d287b42b097/src/view/MainModal.ts#L123), [.setName('Date Format')](https://github.com/technerium/obsidian-vault-size-history/blob/010b156ff8ffa192b381d9351e444d287b42b097/src/view/Settings.ts#L34)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)


[containerEl.createEl('h2', {text: 'Vault Size History'});](https://github.com/technerium/obsidian-vault-size-history/blob/010b156ff8ffa192b381d9351e444d287b42b097/src/view/Settings.ts#L31)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by wizentex** [comment]
All issues have been resolved as requested: [technerium/obsidian-vault-size-history#5f05fce](https://github.com/technerium/obsidian-vault-size-history/commit/5f05fceea36d13cc0292d9a9987de6a6abaa0b22)

**Comment by joethei** [comment]
Could you please give me permissions to edit this pull request?
Otherwise I won't be able to fix the merge conflict from my end.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by wizentex** [comment]
@joethei thank you for your prompt review. There was no option to allow maintainers of this repo to edit this PR (probably because fork is under an org).

I've rebased the PR as you requested. Next time I will fork obsidian-releases into my personal space to allow PR updates by your group.

**Pull request merged**
