### PR TITLE
Add plugin: NyanBar

### PR DESCRIPTION
**Pull request by xhyabunny**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/xhyabunny/nyanbar

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file. (https://github.com/xhyabunny/nyanbar/blob/master/LICENSE.md)
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by xhyabunny** [comment]
someone added their community plugin and ended up on a merge conflict, please fix.

**Comment by joethei** [comment]
It will be fixed once your plugin is ready to be merged.

**Comment by xhyabunny** [comment]
i am updating my plugin so it has styles.css, however 'width' style for some elements are not able to be placed in the CSS  file because they are dynamic (not static) values changed with the script.

**Comment by xhyabunny** [comment]
updated

**Comment by xhyabunny** [comment]
if 'view: MarkdownView' isnt needed then theres no way for me to check for all the checkboxes on the note.. 😶
you said 'use' but sent something completely invisible.

Also i cant bundle images to the code, because the source folder is not something that comes with the release, unless you actually let me do that, i have changed the paths to access './src/' files but it wont work if that folder is not inside the plugin release, so thats on you.

i have made the other changes.

**Comment by xhyabunny** [comment]
i added the files to the release as well.

**Comment by xhyabunny** [comment]
btw bundled images arent working at all now.

**Comment by joethei** [comment]
Oh, must have not pasted the code snippet, updated the message above.

As for bundling, this is what I mean: https://docs.obsidian.md/Themes/App+themes/Embed+fonts+and+images+in+your+theme, doing that process automatically (via a esbuild script for example) is called bundling.

**Comment by xhyabunny** [comment]
well all those are gifs soooo,, expect a lot of bytes

**Comment by xhyabunny** [comment]
also addClass is not really working on my script

**Comment by xhyabunny** [comment]
aight i added the changes it should be working now.

**Comment by xhyabunny** [comment]
hello?

**Comment by xhyabunny** [comment]
i updated it.

**Comment by xhyabunny** [comment]
...

**Comment by xhyabunny** [comment]
i give up thanks for not responding at all.

**Comment by joethei** [comment]
This has still not been fixed.
 
> [function getCheckboxCompletionPercentage(view: MarkdownView): number {](https://github.com/xhyabunny/nyanbar/blob/296ae381fd255f5b702ccdc56ba1e9b0a267edcc/main.ts#L3-L19) You should not use the view here, any checkboxes that are outside the rendered area will not be counted. Use:
> 
> ```ts
> this.registerMarkdownCodeBlockProcessor('xyz', async(source, el, ctx) => {
> 	if (!ctx.sourcePath) {
> 	    //codeblock rendered in page preview, no source path available.
> 	    return;
> 	}
> 	let checkedTasks = 0;
> 	let totalTasks = 0;
> 	for (const listItem of this.app.metadataCache.getCache(ctx.sourcePath).listItems) {
> 	    if(listItem.task) {
> 	        totalTasks++;
> 	        if(listItem.task === 'x') {
> 	            checkedTasks++;
> 	        }
> 	    }
> 	}
> 	//do the math
> });
> ```

**Comment by xhyabunny** [comment]
that thing does not work.

**Comment by joethei** [comment]
well. what part of it does not work?
Is there a error message?

**Comment by xhyabunny** [comment]
it just says something is possibly null, ill show you a screenshot after im done at my job

**Comment by xhyabunny** [comment]
and no it doesnt fix by adding ? or !! to it

**Comment by xhyabunny** [comment]
image

**Comment by xhyabunny** [comment]
fixed it i think, check it out

**Comment by joethei** [comment]
Please update the banner image according to our brand guidelines:

> Please do not edit, change, distort, recolor, or reconfigure the Obsidian logo.
<https://obsidian.md/brand>

**Comment by xhyabunny** [comment]
there.

**Comment by xhyabunny** [comment]
soo?

**Pull request merged**
