### PR TITLE
Add plugin: Default query in backlinks

### PR DESCRIPTION
**Pull request by Benature**
# I am submitting a new Community Plugin
## Repo URL
Link to my plugin: https://github.com/Benature/obsidian-default-query-in-backlink

## Release Checklist
* [ ]  I have tested the plugin on
  
  * [ ]   Windows
  * [x]   macOS
  * [ ]   Linux
  * [ ]   Android _(if applicable)_
  * [ ]   iOS _(if applicable)_
* [x]  My GitHub release contains all required files
  * [x]  `main.js`
  * [x]  `manifest.json`
  * [ ]  `styles.css` _(optional)_
* [x]  GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
* [x]  The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
* [x]  My README.md describes the plugin's purpose and provides clear usage instructions.
* [x]  I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
* [x]  I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
* [x]  I have added a license in the LICENSE file.
* [x]  My project respects and is compatible with the original license of any code from other plugins that I'm using.
  I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Benature** [comment]
Thanks for reviewing, I've updated the code as required.

**Comment by joethei** [comment]
[this.app.workspace.on('file-open', (file) => {](https://github.com/Benature/obsidian-default-query-in-backlink/blob/9f877fe9aa89d2640544d5aef80369c285ac83df/main.ts#L20)
Events need to be registered, so they can be properly unloaded when the plugin is disabled. <https://docs.obsidian.md/Plugins/Events>

["minAppVersion": "0.15.0",](https://github.com/Benature/obsidian-default-query-in-backlink/blob/9f877fe9aa89d2640544d5aef80369c285ac83df/manifest.json#L5)
Use a newer version here, not everything you use existed back then.

**Comment by Benature** [comment]
>["minAppVersion": "0.15.0",](https://github.com/Benature/obsidian-default-query-in-backlink/blob/9f877fe9aa89d2640544d5aef80369c285ac83df/manifest.json#L5)
>Use a newer version here, not everything you use existed back then.

Hi, is there a document I can refer to so that I can know what newer version is satisfied?

**Comment by joethei** [comment]
Just use the latest stable build.

**Comment by Benature** [comment]
OK, I've updated the code about `registerEvent` and `minAppVersion`.

**Pull request merged**
