### PR TITLE
Add plugin: Templated daily notes

### PR DESCRIPTION
**Pull request by digitorum**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/digitorum/obsidian-templayted-daily-notes

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by digitorum** [comment]
/skip static html markup, no user input, no vulnerability.

**Comment by joethei** [comment]
["name": "Templayted Daily Notes",](https://github.com/digitorum/obsidian-templayted-daily-notes/blob/a117cadcfba355579a9a6031628c202077ee6833/manifest.json#L3)
Shouldn't the plugin be called `Templated daily notes` ?

[root.createEl('h1', { text: this.l18n.get('settings-tab:title') })](https://github.com/digitorum/obsidian-templayted-daily-notes/blob/a117cadcfba355579a9a6031628c202077ee6833/src/classes/settings-tab.ts#L31)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[root.createEl('h3', { text: this.l18n.get('settings-tab:list-title') })](https://github.com/digitorum/obsidian-templayted-daily-notes/blob/a117cadcfba355579a9a6031628c202077ee6833/src/classes/settings-tab.ts#L35)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

**Comment by digitorum** [comment]
fixed in PR https://github.com/digitorum/obsidian-templayted-daily-notes/pull/1

**Comment by liamcain** [comment]
- [RibbonsPlugin](https://github.com/digitorum/obsidian-templayted-daily-notes/blob/4c4fdab2aefec0994b19a4eb93f6dc8caa1f18ff/src/index.ts#L13) wrong plugin name?
- [YYYY-MM-DD](https://github.com/digitorum/obsidian-templayted-daily-notes/blob/4c4fdab2aefec0994b19a4eb93f6dc8caa1f18ff/src/index.ts#L32) this doesn't respect the user's daily note settings at all.

**Pull request merged**
