### PR TITLE
[Plugin] Adding markdown commands

### PR DESCRIPTION
**Pull request by JulesGuesnon**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/JulesGuesnon/obsidian-markdown-commands

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lishid** [comment]
Some feedback for the plugin name: I think "Commands" means a specific thing in Obsidian and you're using it in a different sense that could be confusing to users. I suggest renaming your plugin to something like "markdown shortcuts trigger".

https://github.com/JulesGuesnon/obsidian-markdown-commands/blob/6739debf2d4a0aea7f0fcadf1a2a44435462a654/main.ts#L20
I don't think it makes sense to add commands to toggle your plugin's functionality on or off, without enabling/disabling the plugin itself. Imagine every plugin adds a pair of commands to toggle its functionality on/off without disabling the plugin itself, would make for quite some commands.

**Comment by JulesGuesnon** [comment]
Thanks for the feedback! It totally makes sense and I'll modify everything

**Comment by JulesGuesnon** [comment]
@lishid Done!

**Comment by kometenstaub** [comment]
@JulesGuesnon Your README needs to be called `README.md`, not `readme.md`, otherwise Obsidian will not show it.
<https://github.com/JulesGuesnon/obsidian-markdown-shortcuts/blob/master/readme.md>

There is also a spelling mistake in the name.

image

**Comment by JulesGuesnon** [comment]
@kometenstaub Thanks for telling me! I made a PR (#840) to fix the typo and already updated `readme.md` to `README.md`

**Pull request merged**
