### PR TITLE
Add plugin: Iron Vault

### PR DESCRIPTION
**Pull request by zkat**
# I am submitting a new Community Plugin

Iron Vault is a TTRPG Virtual Tabletop plugin for the Ironsworn/Starforged family of games.

## Repo URL

Link to my plugin: https://github.com/iron-vault-plugin/iron-vault

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
  - [x] I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by zkat** [comment]
Just to head this off...

There are two places where we assign styles using JS: [[1](https://github.com/iron-vault-plugin/iron-vault/blob/main/src/characters/commands.ts#L206-L211)] [[2](https://github.com/iron-vault-plugin/iron-vault/blob/93e0815b094ba3c78872f039b53a1607950a673a/src/sidebar/moves.ts#L70)]

We do this because the specific colors come from activated/dynamic rulesets (which will eventually even be user-configurable), so they can't exist in our static css styles. I hope this is an acceptable exception to the rule.

**Comment by zkat** [comment]
Fixed the lookbehinds, but I'd like to keep the `any` casts, because they're there for good reasons

**Comment by zkat** [comment]
/skip I’d like to keep the anys because they’re workarounds for external stuff

**Comment by zkat** [comment]
I've made all the requested changes, but I see the label's still there. Do I need to do anything else?

**Comment by joethei** [comment]
Remove the `data.json` file from your repo and add it to the `.gitignore`, it should not be there.

[throw new Error("Why did we initialize again");](https://github.com/iron-vault-plugin/iron-vault/blob/d01c52c91967236852664fc0de4ad2f8c15c5831/src/index.ts#L48)
This needs a better message.

[if (this.app.workspace.layoutReady) {](https://github.com/iron-vault-plugin/iron-vault/blob/d01c52c91967236852664fc0de4ad2f8c15c5831/src/index.ts#L95-L99)
This code should be simplified to:
```ts
this.app.workspace.onLayoutReady(() => this.initialize());
```

[suggest.ts](https://github.com/iron-vault-plugin/iron-vault/blob/d01c52c91967236852664fc0de4ad2f8c15c5831/src/utils/ui/suggest.ts)
This code should no longer be used, implement a `AbstractInputSuggest` instead of making use of this.

[new Setting(contentEl).setName("New Progress Track").setHeading();](https://github.com/iron-vault-plugin/iron-vault/blob/d01c52c91967236852664fc0de4ad2f8c15c5831/src/tracks/progress-create.ts#L55), ["Track Name": { cls: "track-name", value: trackName, md: true },](https://github.com/iron-vault-plugin/iron-vault/blob/d01c52c91967236852664fc0de4ad2f8c15c5831/src/mechanics/mechanics-blocks.ts#L381), ["From Boxes": { cls: "from-boxes", value: fromBoxes },](https://github.com/iron-vault-plugin/iron-vault/blob/d01c52c91967236852664fc0de4ad2f8c15c5831/src/mechanics/mechanics-blocks.ts#L387-L390), ["Track Name": { cls: "track-name", value: trackName, md: true },](https://github.com/iron-vault-plugin/iron-vault/blob/d01c52c91967236852664fc0de4ad2f8c15c5831/src/mechanics/mechanics-blocks.ts#L424-L428), [def["New Score"] = { cls: "score", value: newScore };](https://github.com/iron-vault-plugin/iron-vault/blob/d01c52c91967236852664fc0de4ad2f8c15c5831/src/mechanics/mechanics-blocks.ts#L633), [? "In a Bad Spot"](https://github.com/iron-vault-plugin/iron-vault/blob/d01c52c91967236852664fc0de4ad2f8c15c5831/src/mechanics/mechanics-blocks.ts#L691-L698), [name: "Basic Form",](https://github.com/iron-vault-plugin/iron-vault/blob/d01c52c91967236852664fc0de4ad2f8c15c5831/src/entity/specs.ts#L168), [nameA: {](https://github.com/iron-vault-plugin/iron-vault/blob/d01c52c91967236852664fc0de4ad2f8c15c5831/src/entity/specs.ts#L285-L309), [return "Iron Vault Documentation";](https://github.com/iron-vault-plugin/iron-vault/blob/d01c52c91967236852664fc0de4ad2f8c15c5831/src/docs/docs-view.ts#L28), [new Setting(contentEl).setName("New Clock").setHeading();](https://github.com/iron-vault-plugin/iron-vault/blob/d01c52c91967236852664fc0de4ad2f8c15c5831/src/clocks/clock-create-modal.ts#L49), [if (val === true && ruleset.ids.contains("classic")) {](https://github.com/iron-vault-plugin/iron-vault/blob/d01c52c91967236852664fc0de4ad2f8c15c5831/src/characters/commands.ts#L157-L170), [<dt>XP Earned</dt>](https://github.com/iron-vault-plugin/iron-vault/blob/d01c52c91967236852664fc0de4ad2f8c15c5831/src/characters/character-block.ts#L256)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by zkat** [comment]
@joethei Thanks for taking the time to review! I know this isn't exactly a small plugin.

Everything should be addressed as of 1.69.1.

**Pull request merged**
