### PR TITLE
Add plugin: Discord Message Formatter

### PR DESCRIPTION
**Pull request by Emile-Durkheim**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Emile-Durkheim/obsidian_discord_formatter

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[.setName("Show Replies")](https://github.com/Emile-Durkheim/obsidian_discord_formatter/blob/33052d18440c486915201b68eaca3f1c74637212/src/settings.ts#L33)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing, [.setName("Distinguish Headings")](https://github.com/Emile-Durkheim/obsidian_discord_formatter/blob/33052d18440c486915201b68eaca3f1c74637212/src/settings.ts#L46)/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by Emile-Durkheim** [comment]
> [.setName("Show Replies")](https://github.com/Emile-Durkheim/obsidian_discord_formatter/blob/33052d18440c486915201b68eaca3f1c74637212/src/settings.ts#L33) [.setName("Distinguish Headings")](https://github.com/Emile-Durkheim/obsidian_discord_formatter/blob/33052d18440c486915201b68eaca3f1c74637212/src/settings.ts#L46) [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

Thanks for the heads-up, should now be fixed!

**Comment by liamcain** [comment]
- [discordMessages.push(new DiscordSingleMessage(DOM.body));](https://github.com/Emile-Durkheim/obsidian_discord_formatter/blob/3d1730e75898b62b32815ccc2fe2d39000bd1256/src/DiscordConversation.ts#L55) This doesn't seem right. AFAICT, this means any HTML without li elements in it will get interpreted as a single discord message. I think you need a check for "message-content" before making that assumption, otherwise you risk corruption other copied html that's not discord messages.

**Comment by Emile-Durkheim** [comment]
Hey, thanks a bunch for reviewing the code!

You're correct in your assumption here. That said, the check for whether the HTML is coming from Discord (rather than other copied HTML) comes before in the constructor that calls createMessages - there's an isDiscordPaste method that checks for the existence of a <div class="message-content..."> in the paste :)

**Pull request merged**
