### PR TITLE
Add plugin: Linkding Importer

### PR DESCRIPTION
**Pull request by jontstaz**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/jontstaz/obsidian-linkding-importer

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[setInterval(this.loadBookmarks.bind(this), this.settings.updateInterval * 60 * 1000);](https://github.com/jontstaz/obsidian-linkding-importer/blob/23a34e10c1a174739aae0af12e2a61830ba442c7/main.ts#L22)
Register this interval, so it get's properly unloaded, (just`this.registerInterval(<your code>)`)

[await this.saveSettings();](https://github.com/jontstaz/obsidian-linkding-importer/blob/23a34e10c1a174739aae0af12e2a61830ba442c7/main.ts#L33)
This is not necessary.

[containerEl.createEl('h2', { text: 'Linkding Import Settings' });](https://github.com/jontstaz/obsidian-linkding-importer/blob/23a34e10c1a174739aae0af12e2a61830ba442c7/main.ts#L117)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[.setName('Search Query (Optional)')](https://github.com/jontstaz/obsidian-linkding-importer/blob/23a34e10c1a174739aae0af12e2a61830ba442c7/main.ts#L142), [.setName('Results Limit')](https://github.com/jontstaz/obsidian-linkding-importer/blob/23a34e10c1a174739aae0af12e2a61830ba442c7/main.ts#L153), [.setName('Update Interval')](https://github.com/jontstaz/obsidian-linkding-importer/blob/23a34e10c1a174739aae0af12e2a61830ba442c7/main.ts#L196)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by jontstaz** [comment]
@joethei - Thanks. I addressed your comments. I just have 1 query on the `Register this interval, so it get's properly unloaded, (justthis.registerInterval(<your code>))` part. I added the suggested line underneath the existing `setInterval` - is that correct? eg.:
```js
setInterval(this.loadBookmarks.bind(this), this.settings.updateInterval * 60 * 1000);
this.registerInterval(this.settings.updateInterval * 60 * 1000);
```

**Comment by joethei** [comment]
No, like this:
```ts
this.registerInterval(window.setInterval(this.loadBookmarks.bind(this), this.settings.updateInterval * 60 * 1000);)
```

I am also using `window.setInterval` here, to make it clear which `setInterval` function is used.
There is also a `setInterval` function in Node, which we don't want to use due to compatibility.

**Comment by jontstaz** [comment]
@joethei - Ok thanks for the clarification. It's all fixed up now in the latest release. Should be good to go now :)

**Comment by jontstaz** [comment]
@joethei - Hi mate, all good to merge it or are you waiting for any other changes?

**Comment by jontstaz** [comment]
@joethei - Hi mate, just checking in again. All good?

**Comment by jontstaz** [comment]
@joethei - Hi mate what's the status here? Can it be merged?

**Pull request merged**
