### PR TITLE
Add plugin: Chat with Bard

### PR DESCRIPTION
**Pull request by Artel250**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Artel250/Obsidian-Talk-with-Bard

## Release Checklist
- [x ] I have tested the plugin on
  - [x ]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x ] My GitHub release contains all required files
  - [x ] `main.js`
  - [x ] `manifest.json`
  - [x ] `styles.css` _(optional)_
- [x ] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [ x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x ] My README.md describes the plugin's purpose and provides clear usage instructions.
- [ x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x ] I have added a license in the LICENSE file.
- [ x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[// Remember to rename these classes and interfaces!](https://github.com/Artel250/Obsidian-Talk-with-Bard/blob/1e38ea46080ddda1550aa969d3bd0727532b23b3/main.ts#L7)
Remove this comment

[id: "Open-Chat-Modal-Command",](https://github.com/Artel250/Obsidian-Talk-with-Bard/blob/1e38ea46080ddda1550aa969d3bd0727532b23b3/main.ts#L27)
This can be shortened to `open-chat`

[// When registering intervals, this function will automatically clear the interval when the plugin is disabled.](https://github.com/Artel250/Obsidian-Talk-with-Bard/blob/1e38ea46080ddda1550aa969d3bd0727532b23b3/main.ts#L33-L34)
Remove this sample code.

**Comment by joethei** [comment]
Please remove the sample code, not just the comment above it.

**Comment by Artel250** [comment]
Sorry for the misunderstanding!
All sample code should be gone now.

**Comment by liamcain** [comment]
- [Enter your __Secure-1PSID token here](https://github.com/Artel250/Obsidian-Talk-with-Bard/blob/ca21c4936a129f86a02ad06e9fbdd7f120326194/main.ts#L53) you might want to add a bit of basic information here on where a user could find that token.

**Pull request merged**
