### PR TITLE
Add `Obsidian Image Gallery` plugin.

### PR DESCRIPTION
**Pull request by lucaorio**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/lucaorio/obsidian-image-gallery

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
- [x] I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by liamcain** [comment]
https://github.com/lucaorio/obsidian-image-gallery/blob/9f65d10cfdb0caee82f85a7b8e81998c7a7157e8/src/img-gallery-renderer.ts#L39 You might want to consider using a more familiar syntax for configuring your codeblock. Something like YAML or even JSON would be better to be consistent with other plugin codeblocks. Otherwise, it's tricky for users to remember the syntax they need for configuring each plugin.

https://github.com/lucaorio/obsidian-image-gallery/blob/9f65d10cfdb0caee82f85a7b8e81998c7a7157e8/src/img-gallery-renderer.ts#L45 you should surface this error to the user. Maybe show it in the codeblock as a message

https://github.com/lucaorio/obsidian-image-gallery/blob/9f65d10cfdb0caee82f85a7b8e81998c7a7157e8/src/img-gallery-renderer.ts#L64 You probably want to call [`normalizePath`](https://github.com/obsidianmd/obsidian-api/blob/38bd84fd66b6bf59d2eab243f27e33d3031ca51c/obsidian.d.ts#L2237) to sanitize the user input here.

https://github.com/lucaorio/obsidian-image-gallery/blob/9f65d10cfdb0caee82f85a7b8e81998c7a7157e8/src/img-gallery-renderer.ts#L64 I don't see anywhere in this function where you filter the folder to only include images. You probably want to filter out the list by file extension somewhere.

**Comment by lucaorio** [comment]
Hi @liamcain thank you for the suggestions!

I addressed all of the above in the [`Plugin review`](https://github.com/lucaorio/obsidian-image-gallery/pull/1) pull request; please let me know if everything now looks good to you.

**Comment by liamcain** [comment]
https://github.com/lucaorio/obsidian-image-gallery/blob/1cdba095d4ed00bf286817b418044b8fb5e6d3f0/src/img-gallery-renderer.ts#L37 No need to add `js-yaml` to your plugin bundle. The Obsidian API exports a [`parseYaml`](https://github.com/obsidianmd/obsidian-api/blob/9bb30633586c6649474b2affdf5b87efdd86498f/obsidian.d.ts#L2323) function that you can use.

https://github.com/lucaorio/obsidian-image-gallery/blob/1cdba095d4ed00bf286817b418044b8fb5e6d3f0/src/img-gallery-renderer.ts#L8 You might want to initialize this to `[]` just so the typing is correct

https://github.com/lucaorio/obsidian-image-gallery/blob/1cdba095d4ed00bf286817b418044b8fb5e6d3f0/src/img-gallery-renderer.ts#L56-L57 I'm a little concerned that you have some an issue with mixed types here. I think loading these values from YAML will give you a `number` but your fallback values are strings. If they are numbers, then you'll also need to use `??` instead of `||` when providing default values. Otherwise you'll run into bugs where you users can't pass `0` in their config.

**Comment by lucaorio** [comment]
Hey @liamcain, I addressed all your great points [here](https://github.com/lucaorio/obsidian-image-gallery/pull/3).

I switched from `||` to `??`, but also ended up in defaulting to numbers as they go through template literals whenever necessary. 

Please let me know how it looks now, and thanks again for the code review; I'm not an engineer and definitely got out of my comfort zone with this one. :)

**Comment by liamcain** [comment]
https://github.com/lucaorio/obsidian-image-gallery/blob/bf328d9f180727f77b6982b76b3e2d6eb0f529f8/src/img-gallery-renderer.ts#L82 you'll need to remove the `.` in `.tiff` and `.tif` for these to match

https://github.com/lucaorio/obsidian-image-gallery/blob/bf328d9f180727f77b6982b76b3e2d6eb0f529f8/src/img-gallery-renderer.ts#L163 instead of setting `.innerHTML` (which is [dangerous](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#avoid-innerhtml-outerhtml-and-insertadjacenthtml)), you can set the text from within `createEl`:

```ts
wrapper.createEl('p', { text: `(Error) Image Gallery: ${error}` });
```

**Comment by lucaorio** [comment]
Thank you, @liamcain ! I just [finished addressing those](https://github.com/lucaorio/obsidian-image-gallery/pull/4/commits/481b328e86e974f4bf3c5a67ad4180ebca675c0b) too 👍

**Pull request merged**
