### PR TITLE
add: ai mentor to community plugins

### PR DESCRIPTION
**Pull request by clementpoiret**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/clementpoiret/ai-mentor

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by clementpoiret** [comment]
Hi,

I just submitted the plugin, but I got errors that I don't understand. I'd be happy to fix them, but I don't know what are the [0-4] properties

**Comment by joethei** [comment]
Could you update your fork of the releases repo?

**Comment by clementpoiret** [comment]
Thanks for your update @joethei :+1:

**Comment by clementpoiret** [comment]
Thanks for your comment, I updated my repo by changing the funding URL, and the README.

The core difference between ai-mentor and other plugins is this notion of mentorship. Of course, you get basic features such as text enhancement, redaction, etc. But I want this plugin to be a real help to creating or problem-solving while being connected to Obsidian's notes (e.g., by reading several notes you made in a folder, generate a conclusion).
Right now, you can talk to different mentors with different "preset" personalities. One preset for example is very good at criticizing notes from scientific papers, with its settings tuned for fact-checking, while another will help you strengthen your logic by continuously criticizing it using the Socratic method.

In an upcoming version, each of these different "personalities" will be able to generate pictures to illustrate your notes based on some presets, as you would see in scientific journals.

**Pull request merged**
