### PR TITLE
add obsidian save as gist plugin

### PR DESCRIPTION
**Pull request by ghedamat**
# I am submitting a new Community Plugin

## Repo URL

https://github.com/ghedamat/obsidian-save-as-gist

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/ghedamat/obsidian-save-as-gist/blob/f0aa15da903048a363fe595d3b897f3bdf3c1bf0/main.ts#L24
This might return null - you should use a checkCallback to prevent your command from showing up in the list when that happens. You also aren't testing for `file.extension === 'md'`, so a user might trigger this on, say, a pdf file, and you will process it just fine.

At this point, probably easiest to just use editorCallback and use `view.file` for the active file, or `editor.getValue()`.

**Comment by ghedamat** [comment]
hey @lishid thanks for the feedback


I pushed a new version and these are the changes

https://github.com/ghedamat/obsidian-save-as-gist/commit/f49a66d62d90ddbc5ae8382e6d1bcc1635841e99


let me know if I understood your suggestions correctly!

**Comment by lishid** [comment]
One possibility if you wish to consider is to merge both commands into a single one: If the user selected something (`editor.getSelection() !== ''`) then use that selection, and if not, use the whole file.

**Comment by ghedamat** [comment]
Good call @lishid !

Now that I use the same api it might be nicer to do that.

I wonder if it's less confusing for users though. 

Will ponder!

Thanks again for the help!

**Comment by ghedamat** [comment]
@devnoname120 that's a good idea! are you interested in helping with a pr? or could you open an issue on https://github.com/ghedamat/obsidian-save-as-gist so we can track this idea?

**Comment by devnoname120** [comment]
@ghedamat kinda overwhelmed with my own open-source projects right now, so I won't be able to meaningfully contribute. :(

**Comment by ghedamat** [comment]
No worries! I know that feeling! Thanks for the suggestion!

**Pull request merged**
