### PR TITLE
Add plugin: cursor-goaway

### PR DESCRIPTION
**Pull request by liuxingyu521**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/liuxingyu521/obsidian-plugin-cursor-goaway

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[this.app.workspace.on('file-open', (file) => {](https://github.com/liuxingyu521/obsidian-plugin-cursor-goaway/blob/ed8dc64161c240fd0cbb563f37b27e57d9a05937/main.ts#L8)
Events need to be registered, so they can be properly unloaded when the plugin is disabled. <https://docs.obsidian.md/Plugins/Events>

**Comment by liuxingyu521** [comment]
> [this.app.workspace.on('file-open', (file) => {](https://github.com/liuxingyu521/obsidian-plugin-cursor-goaway/blob/ed8dc64161c240fd0cbb563f37b27e57d9a05937/main.ts#L8) Events need to be registered, so they can be properly unloaded when the plugin is disabled. https://docs.obsidian.md/Plugins/Events

@joethei  I corrected and released a new version. https://github.com/liuxingyu521/obsidian-plugin-cursor-goaway/releases/tag/1.1.0

**Comment by liamcain** [comment]
The code for this plugin doesn't do what the plugin description claims to do. It appears you are setting the cursor position to the last line of the file. That will cause the view to be scrolled to the bottom of the file, which I don't think is the intention.

**Comment by liuxingyu521** [comment]
> The code for this plugin doesn't do what the plugin description claims to do. It appears you are setting the cursor position to the last line of the file. That will cause the view to be scrolled to the bottom of the file, which I don't think is the intention.

@liamcain  Sorry, I was busy and forgot to reply some time ago.
It's exactly what you said. If change it this way, it will automatically scroll to the bottom. I've changed it again and can help you take a look please.

code: https://github.com/liuxingyu521/obsidian-plugin-cursor-goaway/tree/1.2.0

**Pull request merged**
