### PR TITLE
Add plugin: Confluence Sync

### PR DESCRIPTION
**Pull request by kerry**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/kerry/obsidian-confluence-sync

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "Sync Obsidian notes with Confluence",](https://github.com/kerry/obsidian-confluence-sync/blob/e54784521bbad41b99cb16cffcaefbe8ed2d5a2c/manifest.json#L6)
Remove "Obsidian" here, it should be obvious that this is for Obsidian.

You should link to the Confluence website in your readme, I instantly though of https://www.atlassian.com/software/confluence and which is not the Confluence this plugin is made for.

[name: 'Sync contents of current page to confluence',](https://github.com/kerry/obsidian-confluence-sync/blob/e54784521bbad41b99cb16cffcaefbe8ed2d5a2c/main.ts#L25)
Use the proper capitalization of the brand name.

**Comment by kerry** [comment]
@joethei I have made the changes as suggested by you. For the second point, it is indeed the Atlassian Confluence software that this plugin syncs notes with.

Let me know if anything else is required.

**Comment by joethei** [comment]
Then this is wrong and should not be the default: [confluenceHost: 'https://confluence.com',](https://github.com/kerry/obsidian-confluence-sync/blob/200182edf69168e202ecc953e9e95872aeb37a06/main.ts#L11)

**Comment by kerry** [comment]
Agreed. Thanks for the input. I have removed the default value altogether.

**Pull request merged**
