### PR TITLE
Add plugin: Smart Completion Plugin for Hexo

### PR DESCRIPTION
**Pull request by Jackie-Li-0228**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:https://github.com/Jackie-Li-0228/obsidian-smart-completion-plugin-for-hexo

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Jackie-Li-0228** [comment]
I have updated the changes for the required operations mentioned below:

> Thank you for your submission, an automated scan of your plugin code's revealed the following issues:
> 
> ### Required
> [[1](https://github.com/Jackie-Li-0228/obsidian-smart-completion-plugin-for-hexo/blob/74cbd0ac6b3b260407e04505636de1bdff8d75f3/main.ts#L3-L5)][[2](https://github.com/Jackie-Li-0228/obsidian-smart-completion-plugin-for-hexo/blob/74cbd0ac6b3b260407e04505636de1bdff8d75f3/main.ts#L11-L36)][[3](https://github.com/Jackie-Li-0228/obsidian-smart-completion-plugin-for-hexo/blob/74cbd0ac6b3b260407e04505636de1bdff8d75f3/main.ts#L37-L61)]:Remember to rename the sample classes to something that makes sense to your plugin. If there are any errors, Obsidian will spit out this class name, so this will be important for users to debug if they need to.
> 
> [[1](https://github.com/Jackie-Li-0228/obsidian-smart-completion-plugin-for-hexo/blob/74cbd0ac6b3b260407e04505636de1bdff8d75f3/main.ts#L21)]:Please remove anything from the sample plugin that you don't need.
> 
> Do NOT open a new PR for re-validation. Once you have pushed all of the required changes to your repo, the bot will update the labels on this PR within 6 hours. If you think some of the required changes are incorrect, please comment with `/skip` and the reason why you think the results are incorrect.

but since then the status of the PR was always `changes requested` and `additional review required`.

The last time I made changes to the repo was because the syntax error happened in community-plugins.json.But I immediately made changes to the file and it should be solved back then.But as the community-plugins.json in branch `main` changing,the file will always be conflicted.I don't know how to solve the problem and push the PR forward.

Can someone give me some suggestions pls???

**Comment by Jackie-Li-0228** [comment]
I updated the .json file again.What else shoule I do?

**Comment by Jackie-Li-0228** [comment]
@ObsidianReviewBot

**Comment by joethei** [comment]
I don't see any of the changes.

**Comment by Jackie-Li-0228** [comment]
Sorry, my bad. 😢 

I made changes in my local git repository, but I always thought they were synchronized to the remote. It just occurred to me that back then, I wanted to test them on my computer before pushing to the remote. After the test was completed, I forgot to synchronize them. 😭 I will submit the new changes to the remote today.

**Comment by Jackie-Li-0228** [comment]
Hi @joethei , it seems like there are no other issues at the moment? Looking forward to your review! ❤️

**Pull request closed without merging**
