### PR TITLE
Add zk-new-pane (Open Zettelkasten in New Pane)

### PR DESCRIPTION
**Pull request by pjeby**
# I am submitting a new Community Plugin
...but this is such a trivial feature that you might want to just add the same functionality to the core plugin for a future release, and it might actually be less work than reviewing this plugin.  :wink:

(Especially since it can just be done by adding a new-pane flag to `onCreateNote()` and passing it through to `getLeaf()`, then adding a second command with an extra bind parameter of true, and making the button handler set the flag based on `Keymap.isModifier(event, "Mod")`.)

So yeah, if you want to implement the functionality in the next insider release, feel free to just close this PR.

## Repo URL
Link to my plugin: [zk-new-pane](/pjeby/zk-new-pane)

## Release Checklist
- [x] I have tested this on Windows, macOS, and Linux _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.

### CODE REVIEW

**Comment by lishid** [comment]
Will be added in next release.

**Comment by lishid** [comment]
(Will follow convention for `Mod` as well as middle click - which will also apply for command palette).

**Comment by pjeby** [comment]
Sorry, didn't quite follow the mod vs. middle click vs. command pallette thing.  I know I forgot about middle click (and now that I've remembered, I probably have other plugins that need some fixing on that front), but was there something else I missed?  Thanks.

**Comment by lishid** [comment]
Oh no, I meant that we'll also add the mod+click/mod+enter and middle click triggers for the command palette, that way it's consistent and also don't require adding a second "open in new pane" command for each one that opens a file.

**Comment by pjeby** [comment]
But how can it be mapped to a hotkey then?  (That was the main point of the plugin, at least for me.)

**Comment by lishid** [comment]
Ahhh you're right! I did not think of that... Let me give it a bit more thought.

**Pull request closed without merging**
