### PR TITLE
Add Multiple Notes Outline plugin

### PR DESCRIPTION
**Pull request by iiz00**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/iiz00/obsidian-multiple-notes-outline
## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["authorUrl": "",](https://github.com/iiz00/obsidian-multiple-notes-outline/blob/3f6827e96531d7d60c053cecd64ff90404c9166d/manifest.json#L8)
Put the link to your GitHub profile here, if you don't have a website.

[id: 'multiple-notes-outline-open-file-view',](https://github.com/iiz00/obsidian-multiple-notes-outline/blob/3f6827e96531d7d60c053cecd64ff90404c9166d/src/main.ts#L348)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

[if (this.app.workspace.layoutReady){](https://github.com/iiz00/obsidian-multiple-notes-outline/blob/3f6827e96531d7d60c053cecd64ff90404c9166d/src/main.ts#L365-L369)
Use this instead:
```ts
this.app.workspace.onLayoutReady(this.checkAllView);
```

[this.app.workspace.detachLeavesOfType(MultipleNotesOutlineViewType);](https://github.com/iiz00/obsidian-multiple-notes-outline/blob/3f6827e96531d7d60c053cecd64ff90404c9166d/src/main.ts#L378-L379)
Do not detach leaves with your custom view in `onunload`, this is an antipattern, see: <https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Don't+detach+leaves+in+%60onunload%60>

[this.containerEl.createEl("h4", {](https://github.com/iiz00/obsidian-multiple-notes-outline/blob/3f6827e96531d7d60c053cecd64ff90404c9166d/src/setting.ts#L18-L21)
[Don't use a heading for your general settings seciton](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[import moment from "moment"](https://github.com/iiz00/obsidian-multiple-notes-outline/blob/3f6827e96531d7d60c053cecd64ff90404c9166d/src/view.ts#L6)
Import moment from the Obsidian package instead.

[setIcon(navActionButton,"arrow-left",20);](https://github.com/iiz00/obsidian-multiple-notes-outline/blob/3f6827e96531d7d60c053cecd64ff90404c9166d/src/view.ts#L309)
There are only two parameters.

[console.log ('time required to draw outlines, file view: ',this.targetFiles.main[0], endTime - midTime, previousY);](https://github.com/iiz00/obsidian-multiple-notes-outline/blob/3f6827e96531d7d60c053cecd64ff90404c9166d/src/fileView.ts#L371-L372)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

**Comment by iiz00** [comment]
Thank you for your review!

> console.log ('time required to draw outlines, file view: ',this.targetFiles.main[0], endTime - midTime, previousY);
> Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

I have commented out this console.log and related sections. But I have a question, this part is not executed unless the user enables "show debug info" in the plugin settings. Would it still be bad to display this?(I would like to keep this option if allowed)

> Do not detach leaves with your custom view in onunload, this is an antipattern

I removed detachLeavesOfType from onunload.

> Import moment from the Obsidian package instead.
> There are only two parameters.

Sorry, view.ts was split into fileView.ts and folderView.ts through development. view.ts (and some other files) are no longer used, but I forgot to delete them from the repository. I deleted them so those parts no longer exist.

I have modified the other parts as you indicated.

**Comment by liamcain** [comment]
> Would it still be bad to display this?(I would like to keep this option if allowed)

If you want to keep the logging, I suggest using console.debug and adding your plugin name to the text as a prefix. That will help other plugin devs if they need to filter out your plugin messages or track down where behavior is coming from.

**Comment by iiz00** [comment]
Thank you for your review! I will follow your advice.

**Pull request merged**
