### PR TITLE
Add plugin: Gay Toolbar

### PR DESCRIPTION
**Pull request by ChasKane**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/ChasKane/gay-toolbar

## Release Checklist
- [-] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by ChasKane** [comment]
Hey @joethei I'm still working on this, may take a few weeks at most -- is there a deadline for this PR where I'll have to submit another one? The process wasn't easy so I'd like to avoid it if possible.

**Comment by ChasKane** [comment]
@joethei this is ready when you are

**Comment by joethei** [comment]
["name": "🏳‍🌈 Gay Toolbar 🏳‍🌈",](https://github.com/ChasKane/gay-toolbar/blob/db6be6b9934d66331c17b45f152f4a21bf45fb70/manifest.json#L3)
Remove the emoji, they will only cause issues on some systems.

["description": "Colorful, customizable toolbar for Obsidian, designed for mobile.",](https://github.com/ChasKane/gay-toolbar/blob/db6be6b9934d66331c17b45f152f4a21bf45fb70/manifest.json#L6)
Avoid including sentences like "... for Obsidian" in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[name: "Toggle Edit Mode",](https://github.com/ChasKane/gay-toolbar/blob/db6be6b9934d66331c17b45f152f4a21bf45fb70/main.tsx#L22), [name: "Load Settings from Backup",](https://github.com/ChasKane/gay-toolbar/blob/db6be6b9934d66331c17b45f152f4a21bf45fb70/main.tsx#L30), [this.setPlaceholder("Choose a Command to add");](https://github.com/ChasKane/gay-toolbar/blob/db6be6b9934d66331c17b45f152f4a21bf45fb70/src/chooseNewCommand.ts#L35), [window.setTimeout(() => reject("No Command selected"), 0);](https://github.com/ChasKane/gay-toolbar/blob/db6be6b9934d66331c17b45f152f4a21bf45fb70/src/chooseNewCommand.ts#L59), [Mobile Only](https://github.com/ChasKane/gay-toolbar/blob/db6be6b9934d66331c17b45f152f4a21bf45fb70/src/Settings/GaySettings.tsx#L120), [label="Row Height"](https://github.com/ChasKane/gay-toolbar/blob/db6be6b9934d66331c17b45f152f4a21bf45fb70/src/Settings/GaySettings.tsx#L126), ["Bullet List Commands",](https://github.com/ChasKane/gay-toolbar/blob/db6be6b9934d66331c17b45f152f4a21bf45fb70/src/Settings/DEFAULT_SETTINGS.ts#L19)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[name: "Load Settings from Backup",](https://github.com/ChasKane/gay-toolbar/blob/db6be6b9934d66331c17b45f152f4a21bf45fb70/main.tsx#L30-L33)
The command name does not fit what the command is actually doing.

[console.log(](https://github.com/ChasKane/gay-toolbar/blob/db6be6b9934d66331c17b45f152f4a21bf45fb70/main.tsx#L78-L82)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.


[public getItems(): string[] {](https://github.com/ChasKane/gay-toolbar/blob/db6be6b9934d66331c17b45f152f4a21bf45fb70/src/ChooseIconModal.ts#L68-L662)
You can get all the icon id's from the `getIconIds()` function in the API.

**Comment by ChasKane** [comment]
I've addressed all these comments in my latest commit to main. Thanks so much for your feedback! I should now create a new release on my repo and update this PR to reflect the new name and release tag, yes?

**Comment by joethei** [comment]
Yes, please create a new release.
Also, you missed the last of the sentence case changes.

**Comment by ChasKane** [comment]
Ok, I added the latest release under the tag `1.1.0`.

The last of the sentence case-change you suggested wasn't a string the user would ever see, but I addressed it anyway just in case.

Lmk if there's anything else blocking this plugin from being published and I'll address it straight away. I'm sooooo excited for my first plugin publishing!

**Pull request merged**
