### PR TITLE
add quail plugin

### PR DESCRIPTION
**Pull request by lyricat**
# I am submitting a new Community Plugin

## Repo URL

https://github.com/quail-ink/obsidian-quail

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lyricat** [comment]
The docs about obsidian-quail: https://docs.quail.ink/writer/obsidian-plugin.html

**Comment by joethei** [comment]
["description": "This is a quail plugin for Obsidian.",](https://github.com/lyricat/obsidian-quail/blob/a6127473fabb18989b377ba4dcf12d04f6cef81f/manifest.json#L6)
We have recently published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This is a plugin for Obsidian" in your description.

["fundingUrl": "https://quail.ink/lyric",](https://github.com/lyricat/obsidian-quail/blob/a6127473fabb18989b377ba4dcf12d04f6cef81f/manifest.json#L9)
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link omit this.

[// This adds a status bar item to the bottom of the app. Does not work on mobile apps.](https://github.com/lyricat/obsidian-quail/blob/a6127473fabb18989b377ba4dcf12d04f6cef81f/main.ts#L25-L27)
Remove this, it's not used.

[containerEl.createEl('h2', {text: 'Settings for plugin of Quail.ink.'});](https://github.com/lyricat/obsidian-quail/blob/a6127473fabb18989b377ba4dcf12d04f6cef81f/main.ts#L74)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)
[Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)


[contentEl.innerHTML  = `<div>](https://github.com/lyricat/obsidian-quail/blob/a6127473fabb18989b377ba4dcf12d04f6cef81f/src/modal.ts#L16-L19)
[Avoid using `innerHTML`](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%60innerHTML%60%2C+%60outerHTML%60+and+%60insertAdjacentHTML%60)


[id: 'quail-publish',](https://github.com/lyricat/obsidian-quail/blob/a6127473fabb18989b377ba4dcf12d04f6cef81f/src/action.ts#L77)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

**Comment by lyricat** [comment]
@joethei Thank you for reviewing. all changes have been fixed.

**Comment by joethei** [comment]
Sorry about the delay

[containerEl.createEl('h2', {text: 'General'});](https://github.com/lyricat/obsidian-quail/blob/20917d4c64cfba3660d9f2b286f8a94c24b3f8b9/main.ts#L70)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[pre.style.marginBottom = '1rem';](https://github.com/lyricat/obsidian-quail/blob/20917d4c64cfba3660d9f2b286f8a94c24b3f8b9/src/modal.ts#L128-L134)
You should avoid assigning styles via JavaScript or in HTML and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets.

**Comment by lyricat** [comment]
> Sorry about the delay
> 
> [containerEl.createEl('h2', {text: 'General'});](https://github.com/lyricat/obsidian-quail/blob/20917d4c64cfba3660d9f2b286f8a94c24b3f8b9/main.ts#L70) [Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)
> 
> [pre.style.marginBottom = '1rem';](https://github.com/lyricat/obsidian-quail/blob/20917d4c64cfba3660d9f2b286f8a94c24b3f8b9/src/modal.ts#L128-L134) You should avoid assigning styles via JavaScript or in HTML and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets.

@joethei Thank you for reviewing. all changes have been fixed.

**Comment by lyricat** [comment]
@liamcain Thank you for telling me that! Will do them in the next release soon.

**Pull request merged**
