### PR TITLE
add open-related-url plugin

### PR DESCRIPTION
**Pull request by dpickett**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/dpickett/open-related-url

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [ ] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Just two tiny things, that you don't have to address:

1. Maybe add a link to the Obsidian documentation on frontmatter in your readmeas not everybody that might find your plugin knows what that is.(<https://help.obsidian.md/Advanced+topics/YAML+front+matter>) 

2. I see that you have "node-notifier" in your dependencies,
I don't see it being used anywhere, if you where it would mean that your plugin would not work on mobile.

**Comment by dpickett** [comment]
great suggestions. I've made both changes and bumped the patch level. thanks!

**Comment by liamcain** [comment]
- [setPlaceholder("separate by commas"](https://github.com/dpickett/open-related-url/blob/a284ec3493cdc5431fb5b82a822b786ed648dec3/src/open-related-url/SettingTab.ts#L40) Small UX nitpick, I suggest putting `(separated by commas)` at the end of your description. Then have the placeholder be something like `e.g. task,file`. I think that would be clearer.
- [Frontmatter Suffix](https://github.com/dpickett/open-related-url/blob/a284ec3493cdc5431fb5b82a822b786ed648dec3/src/open-related-url/SettingTab.ts#L19) Maybe file this under future improvements, but it might be nice to have a UI with rows where you can specify the key and the title separately. I'm guessing you introduced "frontmatter suffix" so that you can still call something "file" but it will look for `fileAddress`. But from a UX perspective, it feels like unnecessary misdirection.

**Comment by liamcain** [comment]
@dpickett, do you mind rebasing this pull request from your end? looks like github is struggling to let me do it via their web ui

**Review by liamcain — APPROVED** [review]

**Comment by dpickett** [comment]
I've adjusted the placeholder per your recommendations. I agree on the setting. I will file an issue for that as a future enhancement. Wow, I am very impressed with how thorough you all are with your plugin review. Thanks!

**Pull request merged**
