### PR TITLE
Add plugin: PF2e Statblocks

### PR DESCRIPTION
**Pull request by pixley**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/pixley/pf2e-statblock-for-obsidian

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by pixley** [comment]
Version 1.0.2 addresses the style-assignment concern.

**Comment by joethei** [comment]
["description": "Allows Obsidian to render Pathfinder 2e statblocks cleanly, using only Markdown-based syntax.",](https://github.com/pixley/pf2e-statblock-for-obsidian/blob/e5bef620da549c6536b745a5666a1e715c871f9d/manifest.json#L6)
Avoid including sentences like "Allows Obsidian to do ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[console.log("Decoration for \"" + transaction.newDoc.sliceString(decorationInfo.start, decorationInfo.end) + "\" added: " + JSON.stringify(decorationInfo.decor.spec));](https://github.com/pixley/pf2e-statblock-for-obsidian/blob/e5bef620da549c6536b745a5666a1e715c871f9d/main.ts#L293)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[this.registerMarkdownPostProcessor((element, context) => {](https://github.com/pixley/pf2e-statblock-for-obsidian/blob/e5bef620da549c6536b745a5666a1e715c871f9d/main.ts#L308)
Use a codeblock post processor: <https://docs.obsidian.md/Plugins/Editor/Markdown+post+processing#Post-process+Markdown+code+blocks>, that should mean that the CodeMirror code is no longer required, if I understand the intend correctly.

**Comment by pixley** [comment]
Hello!  I appreciate the feedback.  The description and codeblock post-processor issues have been addressed in version 1.1.0.  As for the `console.log()` calls, I have switched them over to `console.debug()`.  I also have ESBuild configured to drop all `console` calls under the production profile, but that was already the case when I originally submitted this request.

Regarding the use of CodeMirror, that is specifically for syntax highlighting while working within the codeblock.  I briefly explored using PrismJS before learning that edit mode doesn't support it.

**Comment by liamcain** [comment]
I think you'll want to also provide atomicRanges for your widgets. This will prevent the cursor from going "inside" the ranges via the arrow keys.

**Pull request merged**
