### PR TITLE
Add plugin: Tistory

### PR DESCRIPTION
**Pull request by anpigon**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/anpigon/obsidian-tistory-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by anpigon** [comment]
> #### Hello!
> **I found the following issues in your plugin submission**
> 
> **Warnings:**
> 
> ⚠️ Your repository does not include a license. It is generally recommended for open-source projects to have a license. Go to https://choosealicense.com/ to compare different open source licenses.
> 
> This check was done automatically. Do NOT open a new PR for re-validation. Instead, to trigger this check again, make a change to your PR and wait a few minutes, or close and re-open it.

I just added an MIT license to my repository.

**Comment by joethei** [comment]
[Copyright (c) 2023 Git-Sum](https://github.com/anpigon/obsidian-tistory-plugin/blob/54d5aea17639cde2d3ea0b380cfe55173de5a220/LICENSE#L3)
Update the name.

["description": "A plugin for publishing Obsidian documents to Tistory.",](https://github.com/anpigon/obsidian-tistory-plugin/blob/54d5aea17639cde2d3ea0b380cfe55173de5a220/manifest.json#L6)
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This is a plugin for Obsidian that does ..." in your description.

[id: 'tistory-publish',](https://github.com/anpigon/obsidian-tistory-plugin/blob/54d5aea17639cde2d3ea0b380cfe55173de5a220/src/TistoryPlugin.ts#L56)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

**Comment by anpigon** [comment]
> [joethei](/joethei)

Thank you, @joethei, for providing detailed feedback on what needs to be fixed. 
I have addressed all the issues you pointed out. Please review again.

**Comment by anpigon** [comment]
> #### Hello!
> 
> **I found the following issues in your plugin submission**
> 
> **Errors:**
> 
> :x: The newly added entry is not at the end, or you are submitting on someone else's behalf. The last plugin in the list is: `jeel-shah/todo-wrangler`. If you are submitting from a GitHub org, you need to be a public member of the org.
> 
> ---
> 
> <sup>This check was done automatically. Do <b>NOT</b> open a new PR for re-validation. Instead, to trigger this check again, make a change to your PR and wait a few minutes, or close and re-open it.</sup>

I fixed it.

**Comment by anpigon** [comment]
@joethei I'm having a hard time understanding the error in Validate Plugin Entry, can you help? 🙏🏻

**Comment by liamcain** [comment]
- [cachedRead](https://github.com/anpigon/obsidian-tistory-plugin/blob/de101b5f7768e9cdf4d539f43d84cbf591ae1e67/src/TistoryPlugin.ts#L182) if you are writing back to the file, you should use `read` instead of `cachedRead` here to avoid writing stale data to disk. There is also a `processFrontmatter` API which will read the file + frontmatter from disk and write it back to disk in a single atomic transaction, which would be better.

**Pull request merged**
