### PR TITLE
Add plugin: Pexels Banner

### PR DESCRIPTION
**Pull request by jparkerweb**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/jparkerweb/pexels-banner

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["stylesheets": ["styles.css"]](https://github.com/jparkerweb/pexels-banner/blob/47ffa47980dc26f08f442dc0a6c1452302491d47/manifest.json#L11)
This is not part of the manifest spec, remove it.

[const response = await fetch(`https://api.pexels.com/v1/search?query=${currentKeyword}&per_page=${this.settings.numberOfImages}&size=${this.settings.imageSize}&orientation=${this.settings.imageOrientation}`, {](https://github.com/jparkerweb/pexels-banner/blob/47ffa47980dc26f08f442dc0a6c1452302491d47/src/main.js#L180)
Use the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

[const header = containerEl.createEl('div', {cls: 'pexels-banner-header'});](https://github.com/jparkerweb/pexels-banner/blob/47ffa47980dc26f08f442dc0a6c1452302491d47/src/main.js#L230-L246)
[Don't add a top-level heading in the settings tab, such as "General", "Settings", or the name of your plugin.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[const apiKeySection = mainContent.createEl('div', {cls: 'pexels-banner-section'});](https://github.com/jparkerweb/pexels-banner/blob/47ffa47980dc26f08f442dc0a6c1452302491d47/src/main.js#L254-L264)
This should not be a section, just have this setting at the top without a header above it.

[imageSettingsSection.createEl('h3', {text: 'Image Settings'});](https://github.com/jparkerweb/pexels-banner/blob/47ffa47980dc26f08f442dc0a6c1452302491d47/src/main.js#L283)
For section headings in settings use:
```ts
new Setting(containerEl).setName('name here').setHeading();
```
and [avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

[.setName('Image Size')](https://github.com/jparkerweb/pexels-banner/blob/47ffa47980dc26f08f442dc0a6c1452302491d47/src/main.js#L286), [.setName('Image Orientation')](https://github.com/jparkerweb/pexels-banner/blob/47ffa47980dc26f08f442dc0a6c1452302491d47/src/main.js#L299), [.setName('Number of Images')](https://github.com/jparkerweb/pexels-banner/blob/47ffa47980dc26f08f442dc0a6c1452302491d47/src/main.js#L312), [.setName('Default Keywords')](https://github.com/jparkerweb/pexels-banner/blob/47ffa47980dc26f08f442dc0a6c1452302491d47/src/main.js#L334), [instructionsEl.createEl('h3', {text: 'How to Use'});](https://github.com/jparkerweb/pexels-banner/blob/47ffa47980dc26f08f442dc0a6c1452302491d47/src/main.js#L352)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by jparkerweb** [comment]
@joethei I have addressed your comments.

thank you

**Comment by joethei** [comment]
[// New section: About this plugin](https://github.com/jparkerweb/pexels-banner/blob/5cea7a8c7b07d75f4eb1aa02e9fb6d00ef4cb449/src/main.js#L250-L266)
This entire section should not exist, please take a look at the example in the guidelines I linked above.

**Comment by jparkerweb** [comment]
@joethei 
I removed the about section as requested
should be all good now

thank you!

**Pull request merged**
