### PR TITLE
Update community-plugins.json

### PR DESCRIPTION
**Pull request by ocapraro**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/ocapraro/obsidian-math-plus

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/ocapraro/obsidian-math-plus/blob/86b7f8a472166bd34853159ebb6ae4e24e56c4d8/ExcalidrawCanvas.jsx#L9
Don't think this is used.

https://github.com/ocapraro/obsidian-math-plus/blob/86b7f8a472166bd34853159ebb6ae4e24e56c4d8/ExcalidrawCanvas.jsx#L142
When is this interval cleared?

https://github.com/ocapraro/obsidian-math-plus/blob/86b7f8a472166bd34853159ebb6ae4e24e56c4d8/parser.ts#L117
Unused debugging statement?

https://github.com/ocapraro/obsidian-math-plus/blob/86b7f8a472166bd34853159ebb6ae4e24e56c4d8/main.ts#L54
Suggest putting vault and adapter to variables to improve code readability.

**Comment by ocapraro** [comment]
Ok, should be updated now. Before the interval was only being cleared when the user presses the save drawing button, but now it is also cleared if the block ever gets un-rendered.

**Comment by lishid** [comment]
Maybe auto saving every second is a bit excessive? Any way to check whether the drawing has changed before saving?

**Comment by ocapraro** [comment]
Good point, that has now been added!

**Comment by lishid** [comment]
Hmm you're using local storage for it, but you aren't cleaning it up after use... Maybe just store it in an in-memory Record<string, string> object at the root of your file on line 16?

**Comment by ocapraro** [comment]
I'm using local storage so that the data is saved between renders, or if the application is closed. I'm not exactly sure how I could accomplish the same effect by storing it in memory.

**Comment by lishid** [comment]
Hmm I'm not sure exactly what you're trying to do there - are you using localStorage to store the full image data? Wouldn't that not sync to other devices and get lost if one were to clear Obsidian's cache directory? (Also you aren't taking into account that multiple Obsidian vaults open will share the local storage object, so you're potentially overwriting/sharing with another vault if that vault also runs the same plugin.

**Comment by ocapraro** [comment]
Ah, I was not taking that into account, thanks for letting me know! I've now phased out local storage, and am instead saving the data to json files.

**Comment by lishid** [comment]
Looks good so far, I would still recommend avoid reading the file once per second to check if the file has changed. At the very least you should keep an in-memory copy of last-saved state when the canvas is visible to compare with so you don't have to constantly re-read the file from disk.

**Comment by ocapraro** [comment]
Makes sense, just updated it.

**Comment by lishid** [comment]
https://github.com/ocapraro/obsidian-math-plus/blob/84d0f70b93046eefda3faa72f07e3f60aecb8240/main.ts#L148
I still don't think you are properly managing the lifecycle of this react component - you aren't un-mounting it anywhere are you? If that's the case then you are likely still leaking memory via `window.addEventListener("hashchange")` and `setInterval`.

**Comment by ocapraro** [comment]
Good catch, it's unmounting properly now

**Pull request merged**
