### PR TITLE
Add "reveal-active-file-button" plugin

### PR DESCRIPTION
**Pull request by claremacrae**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/claremacrae/reveal-active-file-button-plugin

Note: this was previously: https://github.com/claremacrae/obsidian-manually-reveal-active-file

## Release Checklist

- [x] I have tested this on Windows, macOS, and Linux _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_ - not used
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] README clearly describes the plugins purpose and provides clear usage instructions.
- [x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by claremacrae** [comment]
Now also tested on Windows 10 - list above updated...

**Comment by claremacrae** [comment]
Now tested on Linux - see https://discord.com/channels/686053708261228577/889616783458304001/904765844649832508

**Comment by OfficerHalf** [comment]
Hey this code looks familiar. 😉

Using `innerHTML` [here](https://github.com/claremacrae/obsidian-manually-reveal-active-file/blob/main/src/plugin.ts#L83) is probably fine from a security perspective since it's not user input. I think I mentioned registering custom icons in the discord if you want to try those (though it might not structure it correctly to get the right styles). There are two function to import directly from `obsidian`: [`addIcon`](https://github.com/obsidianmd/obsidian-api/blob/b0aa06eab03d8c39c0733949da5aa1edc2084b01/obsidian.d.ts#L240) and [`setIcon`](https://github.com/obsidianmd/obsidian-api/blob/b0aa06eab03d8c39c0733949da5aa1edc2084b01/obsidian.d.ts#L2445).

**Comment by claremacrae** [comment]
Hi Nathan, thanks for the OK to re-use your code...

And thanks for the comments..

My current thinking was, when I've stopped working on the Hub repo and making PRs and issues for the Obsidian Docs, that I'll go ahead and do what you suggest... Probably by starting first on your own "good first issue" https://github.com/OfficerHalf/obsidian-collapse-all/issues/14- so you can give me feedback there..

For now, though, I'm rather hoping this PR will be accepted as-is, because the code here does just the same as your already-accepted "Collapse All" plugin!

**Comment by lishid** [comment]
Looks fine to me.

Would appreciate if you can also mention at the beginning of your plugin's README that this functionality does exist in Obsidian as the command "File explorer: Reveal active file in navigation" and the pane menu option "Reveal file in navigation"

**Comment by lishid** [comment]
Oh before I merge this - Maybe consider renaming the plugin to exclude the "manually"? I found that to be pretty weird.

**Comment by claremacrae** [comment]
### README

> Looks fine to me.
> 
> Would appreciate if you can also mention at the beginning of your plugin's README that this functionality does exist in Obsidian as the command "File explorer: Reveal active file in navigation" and the pane menu option "Reveal file in navigation"

Yes of course, I will happily do that - good idea... I'll away feedback on the below for now...

### Plugin Name

> Oh before I merge this - Maybe consider renaming the plugin to exclude the "manually"? I found that to be pretty weird.

Ah yes, I should have explained why I did that...

I really wanted to call it `reveal-active-file`, as you suggest... 

But there is this already, with the ID `"obsidian-reveal-active-file"` - and it calls itself `"Automatically Reveal Active File"`

https://github.com/obsidianmd/obsidian-releases/blob/b98aa1c56e7aeeb1f06ba58a967eba7a4ba9fdc6/community-plugins.json#L463-L469

That's why:

1. I felt I couldn't call mine anything with just `reveal-active-file` in
2. And why I thought of "manually"

(That plugin accidentally interferes with things like viewing multiple search results, hence this one, which behaves more like the JetBrains tools)

Note to self: I should update my README to mention this other plugin

**Comment by lishid** [comment]
Perhaps something like `reveal-active-file-button`? Assuming you won't "expand" the functionality of the plugin later on...

**Comment by claremacrae** [comment]
> Perhaps something like `reveal-active-file-button`? Assuming you won't "expand" the functionality of the plugin later on...

Brilliant, that's really good. I'll change it to that - thanks! Setting PR back to Draft until I can do that...

**Comment by claremacrae** [comment]
> Perhaps something like `reveal-active-file-button`? Assuming you won't "expand" the functionality of the plugin later on...

Done!

In addition to the commits listed above:

- I've done a [2.0.0 release](https://github.com/claremacrae/reveal-active-file-button-plugin/releases/tag/2.0.0) with all the changes for the renaming
- Renamed this PR for the new name and updated its description

**Comment by claremacrae** [comment]
Rats - I forgot to update the version in the manifest file in the plugin... will do that shortly...

**Comment by claremacrae** [comment]
> Rats - I forgot to update the version in the manifest file in the plugin... will do that shortly...

Now done.

**Comment by claremacrae** [comment]
@lishid I think this is now ready for review... 🤞

**Pull request merged**
