### PR TITLE
add new plugin: para-shortcuts

### PR DESCRIPTION
**Pull request by gOATiful**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/gOATiful/para-shortcuts

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lishid** [comment]
Love your username!

https://github.com/gOATiful/para-shortcuts/blob/89db92b94af4d34829ece4189bcaaad0b3df0b37/src/main.ts#L3
Weird that your imports all have `.js`?

https://github.com/gOATiful/para-shortcuts/blob/89db92b94af4d34829ece4189bcaaad0b3df0b37/src/main.ts#L7
Should avoid using NodeJS API if you intent for your plugin to run on mobile. For joining paths you can simply use `/` in between and then run `normalizePath` from `obsidian` to have it normalized to Obsidian internal paths. For dirname probably just do some string operations.

https://github.com/gOATiful/para-shortcuts/blob/89db92b94af4d34829ece4189bcaaad0b3df0b37/src/main.ts#L212
you can use `moment` from `obsidian` for a proper date format.

https://github.com/gOATiful/para-shortcuts/blob/89db92b94af4d34829ece4189bcaaad0b3df0b37/src/main.ts#L56
Recommend using `async`/`await` instead of using `.then()` and `.catch()`. (Applies to other places further down as well)

https://github.com/gOATiful/para-shortcuts/blob/89db92b94af4d34829ece4189bcaaad0b3df0b37/src/main.ts#L124
Here you don't need to wrap this in a Promise, as you're in an async function inside anyway. I also don't recommend using a `while` clause to achieve this because you run the risk of getting stuck (for example, renameFile errors out but createFolder always suceeds).

**Comment by lishid** [comment]
https://github.com/gOATiful/para-shortcuts/blob/89db92b94af4d34829ece4189bcaaad0b3df0b37/src/main.ts#L186
Same here, the promise is not necessary and you can simplify it down to just the for loop without try-catch.

**Comment by gOATiful** [comment]
@lishid thank you for your review! 
I have addressed the following issues:

- [x] `Weird that your imports all have .js?` - fixed
- [x] `run normalizePath from obsidian` - changed
- [x] `moment from obsidian` - changed
- [x] `the risk of getting stuck` - changed control flow, so it can not happen
- [x] `the promise is not necessary` - changed the occurrences accordingly

I also created a new release:
https://github.com/gOATiful/para-shortcuts/releases/tag/1.0.1

**Comment by lishid** [comment]
Looks great!

**Pull request merged**
