### PR TITLE
Add plugin: You and Your Research

### PR DESCRIPTION
**Pull request by neozhang**
Submitting a new plugin with the ID "you-and-your-research".

# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/neozhang/you-and-your-research

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by neozhang** [comment]
> Thank you for your submission, an automated scan of your plugin code's revealed the following issues:
> 
> ### Optional
> [[1](https://github.com/neozhang/you-and-your-research/blob/ff6b63bc84e8ff47ce35769fcc6d3b5532a8ff89/src/utils/generateCards.ts#L32-L66)]:Obsidian provides the [`requestUrl`](https://docs.obsidian.md/Reference/TypeScript+API/requestUrl) method, it will make sure that network requests work on every plattform.
> 
> [[1](https://github.com/neozhang/you-and-your-research/blob/ff6b63bc84e8ff47ce35769fcc6d3b5532a8ff89/src/ui/noteExtractor.tsx#L26)]:Casting to `any` should be avoided as much as possible.
> 
> Do NOT open a new PR for re-validation.

these issues have been resolved in the [latest release](https://github.com/neozhang/you-and-your-research/releases/tag/0.9.7) (0.9.7)

**Comment by joethei** [comment]
[console.log(data.choices[0].message.content);](https://github.com/neozhang/you-and-your-research/blob/2df962a26c86520a8f6feb1ed2ac5ca2b06d5b89/src/utils/generateCards.ts#L85)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

[const yaml = require("js-yaml");](https://github.com/neozhang/you-and-your-research/blob/2df962a26c86520a8f6feb1ed2ac5ca2b06d5b89/src/utils/addProperties.ts#L8-L29)
To change frontmatter use the `processFrontmatter` function.

[new Setting(containerEl).addButton((button) =>](https://github.com/neozhang/you-and-your-research/blob/2df962a26c86520a8f6feb1ed2ac5ca2b06d5b89/src/ui/settings.tsx#L98-L102)
This serves no purpose, remove it.

**Comment by neozhang** [comment]
> [console.log(data.choices[0].message.content);](https://github.com/neozhang/you-and-your-research/blob/2df962a26c86520a8f6feb1ed2ac5ca2b06d5b89/src/utils/generateCards.ts#L85)
> 
> Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.
> 
> 
> 
> [const yaml = require("js-yaml");](https://github.com/neozhang/you-and-your-research/blob/2df962a26c86520a8f6feb1ed2ac5ca2b06d5b89/src/utils/addProperties.ts#L8-L29)
> 
> To change frontmatter use the `processFrontmatter` function.
> 
> 
> 
> [new Setting(containerEl).addButton((button) =>](https://github.com/neozhang/you-and-your-research/blob/2df962a26c86520a8f6feb1ed2ac5ca2b06d5b89/src/ui/settings.tsx#L98-L102)
> 
> This serves no purpose, remove it.
> 
> 
> 
> 

Thanks for the comments. Please review my latest code. I believe that it doesn't include any of the issues as you mentioned. Thank you.

**Comment by neozhang** [comment]
Please check the latest release at: https://github.com/neozhang/you-and-your-research/releases/tag/0.9.8

**Pull request merged**
