### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by sparklau**
Comfort-smooth CSS works well on Obsidian v0.9.15. 
Dark mode only.

### CODE REVIEW

**Comment by ericaxu** [comment]
Hi, this repository is for metadata only, not for the source code.

Please see this PR as an example: https://github.com/obsidianmd/obsidian-releases/pull/44

**Comment by sparklau** [comment]
So you mean I should create a master branch, then put the CSS code there, right? Sorry, I am totally new to this.

**Comment by sparklau** [comment]
But I have found this, "The default branch is set to master. To change this setting, add another branch." So the master branch is there already.

**Comment by lishid** [comment]
Create a github repo for your theme, containing the `obsidian.css` file and an optional screenshot. Then make a pull request here with the name of your github repo like this: https://github.com/obsidianmd/obsidian-releases/pull/44/files

**Pull request closed without merging**
