### PR TITLE
Added Optimize Canvas Connections plugin

### PR DESCRIPTION
**Pull request by felixchenier**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/felixchenier/obsidian-optimize-canvas-connections

## Release Checklist
- [X] I have tested the plugin on
  - [x]  Windows
  - [X]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [X] My GitHub release contains all required files
  - [X] `main.js`
  - [X] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [X] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [X] I have added a license in the LICENSE file.
- [X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by felixchenier** [comment]
Hi there. This PR hadn't conflict, but now that previous PR are being merged, the `community-plugins.json` file now conflicts. Do I have to solve the conflict (which I guess will happen again as you merge other PRs) or will you take care of that when it's my turn? Tx

**Comment by joethei** [comment]
We will fix the merge conflicts before merging.


[if (canvasView?.getViewType() !== "canvas") {](https://github.com/felixchenier/obsidian-optimize-canvas-connections/blob/995d786be119b09c861ac3b67ad20094e92de16b/main.ts#L57-L60)
You should move this check into a `checkCallback`, then the command will only be visible on the command pallete when Canvas is active.
Here are some docs:
<https://marcus.se.net/obsidian-plugin-docs/user-interface/commands#conditional-commands>

**Comment by felixchenier** [comment]
Thank you for your review @joethei 
The requested change is done, it's effectively much better that way.

**Comment by liamcain** [comment]
- [MyPlugin](https://github.com/felixchenier/obsidian-optimize-canvas-connections/blob/d671a944006fba1fe2e39368e3a848ec188fd096/main.ts#L13) please rename your class
- [MyPluginSettingMyPluginSettingss](https://github.com/felixchenier/obsidian-optimize-canvas-connections/blob/d671a944006fba1fe2e39368e3a848ec188fd096/main.ts#L5) remove this since it's unused.
- [Optimize](https://github.com/felixchenier/obsidian-optimize-canvas-connections/blob/d671a944006fba1fe2e39368e3a848ec188fd096/main.ts#L51) style nitpick: I suggest lowercasing your function names.

**Pull request merged**
