### PR TITLE
New plugin: obsidian-external-links-in-document

### PR DESCRIPTION
**Pull request by giselle197**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/giselle197/obsidian-external-links-in-document

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by giselle197** [comment]
Update community-plugins.json, manifest.json in my repo and latest GitHub release.

**Comment by joethei** [comment]
I generally recommend moving all code files into a separate `src` folder, that makes it easier to review and maintain.

[containerEl.createEl("h1", { text: "My Plugin Settings" });](https://github.com/giselle197/obsidian-external-links-in-document/blob/8371b9c0e7e277d75bcb89c7d588a254f8d13c24/settings.ts#L26-L27)
Remove this or change the text.

[element.innerHTML = element.innerHTML.replace(link.outerHTML, `<span style="color: ${this.plugin.settings.internalLinkColor};">${link.textContent}</span>`);](https://github.com/giselle197/obsidian-external-links-in-document/blob/8371b9c0e7e277d75bcb89c7d588a254f8d13c24/view.ts#L336-L338)
[Avoid using `innerHTML`](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#avoid-innerhtml-outerhtml-and-insertadjacenthtml)

**Comment by giselle197** [comment]
1. I moved all code files into the `src` folder
2. change the text of headings in SettingsTab
3. avoid innerHTML

**Comment by liamcain** [comment]
Hi @giselle197, thanks for your patience. I'm just getting around to reviewing this now.

- [this.registerEvent(this.app.workspace.on('file-open', () => {](https://github.com/giselle197/obsidian-external-links-in-document/blob/6a5215ea8b27d00af8f2e0fcf1736c31b9713a31/src/main.ts#L59) I recommend you move this event into ExternalLinksView. In general, your Plugin class should really just handle setup and shouldn't act as a controller or a dispatcher to your custom View class. The way you have things set up currently means that you'll be responding to events even if your view isn't open. It also creates a few other unwanted constraints: such as not being able to have multiple instances of your View open (at least, not easily). 
- [onunload](https://github.com/giselle197/obsidian-external-links-in-document/blob/6a5215ea8b27d00af8f2e0fcf1736c31b9713a31/src/main.ts#L93) I don't recommend detaching leaves on unload. I wrote a little bit about why this isn't best practice [here](https://github.com/liamcain/obsidian-example-custom-view/blob/194d4557abb52a41c0380a2f1ec75334d9ce2775/src/main.ts#L6).
- [this.render();](https://github.com/giselle197/obsidian-external-links-in-document/blob/6a5215ea8b27d00af8f2e0fcf1736c31b9713a31/src/view.ts#L55) I don't recommend having a "refresh" button. It's not a great user experience. Instead I suggest adding a event listener to rerender the view when the metadata cache changes (see: ['changed'](https://github.com/obsidianmd/obsidian-api/blob/bceb489fc25ceba5973119d6e57759d64850f90d/obsidian.d.ts#L2414))
- [renderMarkdown](https://github.com/giselle197/obsidian-external-links-in-document/blob/6a5215ea8b27d00af8f2e0fcf1736c31b9713a31/src/view.ts#L219) this is pretty inefficient, I would probably recommend you just parse the file contents and extract the links from the markdown file without rendering.
- [fontStyle](https://github.com/giselle197/obsidian-external-links-in-document/blob/6a5215ea8b27d00af8f2e0fcf1736c31b9713a31/src/view.ts#L294) You should avoid assigning styles via javascript. Instead, just add a class to the element and move all these styles into CSS so that they are more easily adaptable by themes.
- [read](https://github.com/giselle197/obsidian-external-links-in-document/blob/6a5215ea8b27d00af8f2e0fcf1736c31b9713a31/src/view.ts#L120) you should use cachedRead here to be more efficient. [cachedRead](https://github.com/obsidianmd/obsidian-api/blob/9bb30633586c6649474b2affdf5b87efdd86498f/obsidian.d.ts#L3373)

**Comment by ericaxu** [comment]
Hi @giselle197 , do you still intend to submit this plugin?

**Comment by giselle197** [comment]
Sorry, I have been too busy lately, but I will definitely complete it on some future day!

**Pull request closed without merging**
