### PR TITLE
Add Fantasy name generator plugin

### PR DESCRIPTION
**Pull request by Lukewh**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/lukewh/fantasy-name

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by ericaxu** [comment]
Hi, have you looked at the Fantasy Content Generator plugin? Is your plugin significantly different?

**Comment by Lukewh** [comment]
> Hi, have you looked at the Fantasy Content Generator plugin? Is your plugin significantly different?

Hi! I have looked at the Fantasy Content Generator plugin. On the surface this plugin does indeed seem very similar, however I find the Fantasy Content Generator plugin too heavy handed when I need a quick name, so this plugin provides a no-configuration option :).

**Comment by joethei** [comment]
Please remove the `main.js` from the repo and add it to your .gitignore - compiled release files shouldn't get mixed with source code in your commits and should go to the releases files instead.

[const resp = await fetch("https://fantasyname.lukewh.com?family=t");](https://github.com/Lukewh/fantasy-name/blob/e1b20df9cf96678d7494f48d5eedd6559cfc7944/index.ts#L16)
I would recommend using the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

I personally don't see why the name generation code needs to be hosted on a server.

**Comment by Lukewh** [comment]
> Please remove the `main.js` from the repo and add it to your .gitignore - compiled release files shouldn't get mixed with source code in your commits and should go to the releases files instead.
> 
> [const resp = await fetch("https://fantasyname.lukewh.com?family=t");](https://github.com/Lukewh/fantasy-name/blob/e1b20df9cf96678d7494f48d5eedd6559cfc7944/index.ts#L16) I would recommend using the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.
> 
> I personally don't see why the name generation code needs to be hosted on a server.

Thanks for the review and feedback, I've made the changes you suggested :)!

I'm using an API that I created as it's used by people that don't use Obsidian and honestly, I don't want to duplicate my effort :D!

**Comment by Lukewh** [comment]
Resolved conflict :rocket:

**Pull request merged**
