### PR TITLE
Add obsidian-codeblock-template plugin

### PR DESCRIPTION
**Pull request by sylcool**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/sylcool/obsidian-codeblock-template

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["authorUrl": "",](https://github.com/sylcool/obsidian-codeblock-template/blob/ce0a21e4d0e233e8e622ad77ef34b5681f5b2699/manifest.json#L8)
If you don't have a website use your GH profile here.

["fundingUrl": "",](https://github.com/sylcool/obsidian-codeblock-template/blob/ce0a21e4d0e233e8e622ad77ef34b5681f5b2699/manifest.json#L9)
If you don't have one omit this.

You should prefer the Vault API over the Adapter API: https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Prefer+the+Vault+API+over+the+Adapter+API

[async listAllFile(sourcePath: string, mdPaths: string[]) {](https://github.com/sylcool/obsidian-codeblock-template/blob/ce0a21e4d0e233e8e622ad77ef34b5681f5b2699/src/utils/utils.ts#L92-L105)
This function should be replaced with something like this:
```ts
async getMarkdownFilesFromFolderRecursively(sourcePath: string) {		
		const folder = this.app.vault.getAbstractFileByPath(sourcePath);
		const result: TFile[] = [];
		if (folder instanceof TFolder) {
			Vault.recurseChildren(folder, (file) => {
				if (file instanceof TFile && file.extension === 'md') {
					result.push(file);
				}
			});
		}
		return result;
	}
```
This will return a list of all markdown files under that folder as `TFile`s

[async findMarkdomName(input: string, mdPaths: string[]) {](https://github.com/sylcool/obsidian-codeblock-template/blob/ce0a21e4d0e233e8e622ad77ef34b5681f5b2699/src/utils/utils.ts#L107-L121)
This function is unused and should be removed.

[static readonly reVariableName = /(?<=\$\.\{\s*)[_a-zA-Z]\w*(?=\s*\})/g;](https://github.com/sylcool/obsidian-codeblock-template/blob/ce0a21e4d0e233e8e622ad77ef34b5681f5b2699/src/utils/utils.ts#L157)
This won't work on iOS older than 16.4, as support for lookbehinds was just added recently.

**Comment by sylcool** [comment]
I have made the modifications according to your instructions!
- [x] Modified  the Manifest.json.
- [x] Vault API replacing Adapter API.
- [x] Modified the code for traversing files.
- [x] Deleted abundant code.
- [x] Deleted lookbehinds part.

**Comment by marcusolsson** [comment]
- https://github.com/sylcool/obsidian-codeblock-template/blob/0a50c71fc3913cb5e6f419fffa879babe508f009/manifest.json#L6
  You can shorten the description to something like, "Re-use content within codeblocks using variables."

**Comment by ericaxu** [comment]
@sylcool Hi, have you seen @marcusolsson 's comments?

**Comment by sylcool** [comment]
I'm sorry, I forgot before, but I've changed it now.

**Comment by ericaxu** [comment]
> I'm sorry, I forgot before, but I've changed it now.

Thank you!

@joethei Should we merge this now since that was Marcus's only comment?

**Comment by ericaxu** [comment]
Seems like it hasn't passed validation. Could you try again please? @sylcool

**Pull request merged**
