### PR TITLE
Add plugin Markdown Tabs Syntax

### PR DESCRIPTION
**Pull request by zoodogood**
# I am submitting a new Community Plugin

## Repo URL
https://github.com/zoodogood/obsidian-plugin-markdown-tabs

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [ ] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by zoodogood** [comment]
Ready

**Review by zoodogood — COMMENTED** [review]
Fix tag name from v1.1.6 to 1.1.6

**Comment by joethei** [comment]
["description": "Provides a quick syntax for creating switchable Tabs for Preview Mode and Document",](https://github.com/zoodogood/obsidian-plugin-markdown-tabs/blob/0f47f48a65b58802954bc0a990fe5d9146d71a89/manifest.json#L6)
This should be in sentence case.

---

[import { spawn } from "child_process";](https://github.com/zoodogood/obsidian-plugin-markdown-tabs/blob/0f47f48a65b58802954bc0a990fe5d9146d71a89/src/lib/child-process-utils.ts#L1-L2)
What is this file for?

**Comment by zoodogood** [comment]
import { spawn } from 'child_process';  
  
> esbuild.config.mjs
```js
const { run } = getChildProcessUtils({ root: process.cwd() });
await run("mv", ["build/main.css", "build/styles.css"]).whenEnd;
await run("cp", ["manifest.json", "build/manifest.json"]).whenEnd;
```

It's code launched only in build stage and not included in bunle

**Comment by liamcain** [comment]
- [getLeaf().view as FileView](https://github.com/zoodogood/obsidian-plugin-markdown-tabs/blob/0f47f48a65b58802954bc0a990fe5d9146d71a89/src/components/TabsContainer/index.tsx#L167) This cast won't work. getLeaf can return a leaf with any view type, including an empty view. Looks like you should be using [`getActiveFile`](https://github.com/obsidianmd/obsidian-api/blob/38dd22168d2925086371bfc59e36fd9121527a39/obsidian.d.ts#L4146) instead. For the `component`, you should convert your TabsContainer into a MarkdownRenderChild and use `this`

**Pull request closed without merging**
