### PR TITLE
Add plugin: Import GitHub Readme

### PR DESCRIPTION
**Pull request by chasebank87**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/chasebank87/import-github-readme

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by chasebank87** [comment]
Thank you for you time

**Comment by joethei** [comment]
[Command Pallet](https://github.com/chasebank87/import-github-readme/blob/d49c5154f1757c70bf947b47217afc45a6cf3c0d/README.md#L3)
It's called ["Command palette](https://help.obsidian.md/Plugins/Command+palette)

["description": "Allows you to import a GitHub README file into your vault.",](https://github.com/chasebank87/import-github-readme/blob/d49c5154f1757c70bf947b47217afc45a6cf3c0d/manifest.json#L6)
Avoid sentences like "Allows you to do ..."
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

["fundingUrl": "https://github.com/chasebank87/import-github-readme.git",](https://github.com/chasebank87/import-github-readme/blob/d49c5154f1757c70bf947b47217afc45a6cf3c0d/manifest.json#L9)
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link remove this line.

[const response = await fetch(apiUrl, {](https://github.com/chasebank87/import-github-readme/blob/d49c5154f1757c70bf947b47217afc45a6cf3c0d/main.ts#L37)
Use the `requestUrl` function from the Obsidian API instead, it will handle some things like CORS automatically.

[convertHtmlToMarkdown(content: string): string {](https://github.com/chasebank87/import-github-readme/blob/d49c5154f1757c70bf947b47217afc45a6cf3c0d/main.ts#L54-L98)
Use the `htmlToMarkdown` function from the Obsidian API instead of reinventing the wheel.

**Comment by chasebank87** [comment]
[convertHtmlToMarkdown(content: string): string {](https://github.com/chasebank87/import-github-readme/blob/d49c5154f1757c70bf947b47217afc45a6cf3c0d/main.ts#L54-L98)
Use the htmlToMarkdown function from the Obsidian API instead of reinventing the wheel.

This function was named incorrectly. This function does not convert to markdown, instead it finds html on the page, and checks for markdown inside of the HTML tags. If markdown is present inside of HTML it will convert it to HTML. I did this because obsidian does not render html the same as GitHub.

**Comment by joethei** [comment]
Why are you using marked in that function and not `htmlToMarkdown` ?

**Comment by chasebank87** [comment]
Because the way github allows users to include html. On github you can include markdown in your html tags.  This method of rendering is A not supported in obsidian, B not handled by htmlToMarkdown because when it converts markdown to markdown it messes up the formatting.

**Comment by joethei** [comment]
Okay, but one thing you need to handle here, Marked does not sanitzie the content that gets produced, use the `sanitizeHTMLToDom` function for that.

**Comment by chasebank87** [comment]
Will do! thanks

**Pull request merged**
