### PR TITLE
add obsidian-daily-todo-pro plugin

### PR DESCRIPTION
**Pull request by Die4passion**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: <https://github.com/Die4passion/obsidian-daily-todo-pro>

## Release Checklist

- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Die4passion** [comment]
> https://github.com/Die4passion/obsidian-daily-todo-pro/blob/19a25755232d2860fdea356549d582491a4fea2c/src/index.js#L38 Should rename the class name.
> 
> https://github.com/Die4passion/obsidian-daily-todo-pro/blob/19a25755232d2860fdea356549d582491a4fea2c/src/index.js#L94 Should import `moment` from `obsidian`
> 
> https://github.com/Die4passion/obsidian-daily-todo-pro/blob/19a25755232d2860fdea356549d582491a4fea2c/src/index.js#L99 Should use `getAllMarkdownFiles` instead.
> 
> https://github.com/Die4passion/obsidian-daily-todo-pro/blob/19a25755232d2860fdea356549d582491a4fea2c/src/index.js#L115 This could be fairly expensive when you keep parsing the file dates. You should parse the date once for each file and store the result somewhere to be used when sorting.
> 
> https://github.com/Die4passion/obsidian-daily-todo-pro/blob/19a25755232d2860fdea356549d582491a4fea2c/src/index.js#L126 Should use `cachedRead` instead.
> 
> https://github.com/Die4passion/obsidian-daily-todo-pro/blob/19a25755232d2860fdea356549d582491a4fea2c/src/index.js#L131 Actually, you should use the metadata cache for getting the list of tasks - that way you can avoid reading files that don't have unfinished tasks altogether.
> 
> Details here: https://github.com/obsidianmd/obsidian-api/blob/c01fc3074deeb3dfc6ee02546d113b448735b294/obsidian.d.ts#L1547
> 
> You'll want to get the cache info using `app.metadataCache.getFileCache(file)`
> 
> https://github.com/Die4passion/obsidian-daily-todo-pro/blob/19a25755232d2860fdea356549d582491a4fea2c/src/index.js#L494 `existingFile` can be null here.
> 
> https://github.com/Die4passion/obsidian-daily-todo-pro/blob/19a25755232d2860fdea356549d582491a4fea2c/src/ui/UndoModal.js#L35 https://github.com/Die4passion/obsidian-daily-todo-pro/blob/19a25755232d2860fdea356549d582491a4fea2c/src/ui/UndoModal.js#L50 `!= undefined` is not necessary.
> 
> https://github.com/Die4passion/obsidian-daily-todo-pro/blob/19a25755232d2860fdea356549d582491a4fea2c/src/ui/UndoModal.js#L62 Should close first, then run the actual code.
> 
> https://github.com/Die4passion/obsidian-daily-todo-pro/blob/19a25755232d2860fdea356549d582491a4fea2c/src/ui/RolloverSettingTab.js#L19 Should use cachedRead here.


Thank you very much!
I will try my best to solve these problems.
This is my first time join an open source project.
Thank you for the review and i think i can write better codes.

**Comment by Die4passion** [comment]
@lishid  
I have solved the problems above.
but i failed to use the `app.metadataCache.getFileCache(file)?.listItems`. 
can i use it later the next release that i will add some new features and refactor my code.

thank you very much, i have learned a lot from your review.

then how i can do next to add this plugin to obsidian?

**Comment by lishid** [comment]
https://github.com/Die4passion/obsidian-daily-todo-pro/blob/2dfecadae0e61168312c33fce7b4cb210c8c5f55/src/index.js#L65
I don't think this is a great way - you're defining an array but using really high numbers for indices which usually is inefficient depending on the engine. You should instead store an object of `{file, time}` in the array with `array.push()`.

https://github.com/Die4passion/obsidian-daily-todo-pro/blob/2dfecadae0e61168312c33fce7b4cb210c8c5f55/src/index.js#L148
Here you are still doing regex-based searches. Instead you should use the data from `MetadataCache`'s `listItems`. You can use each item's start/end offsets (and line information should you need it) to find the original text position in the document.

https://github.com/Die4passion/obsidian-daily-todo-pro/blob/2dfecadae0e61168312c33fce7b4cb210c8c5f55/src/ui/UndoModal.js#L19
`${file.basename}.${file.extension}` can be replaced with just `${file.name}`.

**Comment by ericaxu** [comment]
Hi there, to keep things tidy, we're going to temporarily close plugin PRs after a month of inactivity.

Feel free to tell us to re-open it when you're ready to continue. Thanks for your understanding!

**Pull request closed without merging**
