### PR TITLE
Add plugin: Studier

### PR DESCRIPTION
**Pull request by alvaro-cas**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin:
https://github.com/alvaro-cas/studier-obsidian

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
Plöease follow the pull request template.

**Comment by alvaro-cas** [comment]
> Plöease follow the pull request template.

Done

**Comment by joethei** [comment]
[Copyright (c) 2022 https://github.com/alvaro-cas/studier-obsidian/graphs/contributors](https://github.com/alvaro-cas/studier-obsidian/blob/5b988df4132de7f61dce6fd6e25d0bb738229ac1/LICENSE#L3)
Update the year.

[checkCallback: (checking: boolean) => {](https://github.com/alvaro-cas/studier-obsidian/blob/5b988df4132de7f61dce6fd6e25d0bb738229ac1/main.ts#L22-L27)
Use a regular callback, since there is no condition here.

[await this.app.workspace.openLinkText(markdownOpen.basename, '');](https://github.com/alvaro-cas/studier-obsidian/blob/5b988df4132de7f61dce6fd6e25d0bb738229ac1/main.ts#L59-L73)
Instead of opening the note to get the content, I would recommend using the vault API.

[containerEl.createEl('h1', { text: 'Settings: Studier' });](https://github.com/alvaro-cas/studier-obsidian/blob/5b988df4132de7f61dce6fd6e25d0bb738229ac1/src/settings.ts#L28)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.), 

[.setName('Questions Intializer')](https://github.com/alvaro-cas/studier-obsidian/blob/5b988df4132de7f61dce6fd6e25d0bb738229ac1/src/settings.ts#L31), [.setName('Questions Ender')](https://github.com/alvaro-cas/studier-obsidian/blob/5b988df4132de7f61dce6fd6e25d0bb738229ac1/src/settings.ts#L42), [.setName('Starter Question Indicator')](https://github.com/alvaro-cas/studier-obsidian/blob/5b988df4132de7f61dce6fd6e25d0bb738229ac1/src/settings.ts#L53), [.setName('Correct Answer Indicator')](https://github.com/alvaro-cas/studier-obsidian/blob/5b988df4132de7f61dce6fd6e25d0bb738229ac1/src/settings.ts#L64)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[containerEl.createEl('div', {}, div => {](https://github.com/alvaro-cas/studier-obsidian/blob/5b988df4132de7f61dce6fd6e25d0bb738229ac1/src/settings.ts#L77-L83)
[Avoid using `innerHTML`](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%60innerHTML%60%2C+%60outerHTML%60+and+%60insertAdjacentHTML%60)

**Comment by alvaro-cas** [comment]
Hello, and thank you for reviewing my plugin. I have made all changes except for using the vault API. I want my plugin to open the note, so it can be reviewed after the quiz and, if there are no questions, can be added easily.

**Pull request merged**
