### PR TITLE
Add plugin: Task list

### PR DESCRIPTION
**Pull request by ted-marozzi**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/ted-marozzi/task-list

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by ted-marozzi** [comment]
Keen to hear how things could be done better, for example to render my checkbox states in live view, I [this view plugin here](https://github.com/ted-marozzi/task-list/blob/master/src/task_state/task_state_view_plugin.ts), but to render it in reading mode I had to use a [seperate post processor](https://github.com/ted-marozzi/task-list/blob/master/src/task_state/task_state_post_processor.ts). Is there a way to render in both live view and reading view with a view plugin?

**Comment by ted-marozzi** [comment]
Hey @joethei,
Am i meant to keep updating this to try and keep it in sync with master?
It seems like a waste of time...

**Comment by joethei** [comment]
We will handle the merge conflicts once the review is finished

**Comment by ted-marozzi** [comment]
Perfect, thank you.

**Comment by joethei** [comment]
["description": "A simple obsidian plugin enabling better task management via lists.",](https://github.com/ted-marozzi/task-list/blob/73902c460b54d878e30127b4cb823f16e57ade72/manifest.json#L6)
Avoid including sentences like "This is a plugin for Obsidian that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[log("info", "Running command");](https://github.com/ted-marozzi/task-list/blob/73902c460b54d878e30127b4cb823f16e57ade72/src/features/sort_task_list/sort.ts#L17), [this.log("info", `Replacing task directive with ${taskStateDirective}`);](https://github.com/ted-marozzi/task-list/blob/73902c460b54d878e30127b4cb823f16e57ade72/src/features/render_task_state/task_state_widget.ts#L78), [log("info", "Rendering reading view task states.");](https://github.com/ted-marozzi/task-list/blob/73902c460b54d878e30127b4cb823f16e57ade72/src/features/render_task_state/task_state_post_processor.ts#L7)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

**Comment by ted-marozzi** [comment]
Thanks for the review @joethei, I have corrected both issues and recreated the 1.0.0 release with the latest manifest and code changes.

**Comment by ted-marozzi** [comment]
Also understand if its out of scope of the review, but i'd been keen to get some feedback on these questions if possible @joethei 

https://github.com/obsidianmd/obsidian-releases/pull/2954#issuecomment-1901711443

**Comment by joethei** [comment]
1. you have to write for both, that's how it works.
2. Sadly no easy way to do that, our implementation relies on some internal code.

**Comment by ted-marozzi** [comment]
Thanks @joethei for the answers, I have fixed the issue with the latest release missing assets, sorry about that!

**Pull request merged**
