### PR TITLE
Add Vertical Tabs View plugin

### PR DESCRIPTION
**Pull request by hdykokd**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/hdykokd/obsidian-vertical-tabs-view

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "This is plugin for Obsidian that provides a vertical tabs view.",](https://github.com/hdykokd/obsidian-vertical-tabs-view/blob/62e9559195f7617d0850eacfef92610bd90651ae/manifest.json#L6)
We have recently published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This is a plugin for Obsidian" in your description.


[private view: VerticalTabsViewView;](https://github.com/hdykokd/obsidian-vertical-tabs-view/blob/62e9559195f7617d0850eacfef92610bd90651ae/src/main.ts#L9)
[Avoid managing references to custom views](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+managing+references+to+custom+views)

[previewIconWrapper.style.display = 'flex';](https://github.com/hdykokd/obsidian-vertical-tabs-view/blob/62e9559195f7617d0850eacfef92610bd90651ae/src/setting.ts#L122)
You should avoid assigning styles via JavaScript or in HTML and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets.

**Comment by hdykokd** [comment]
> [leaf.setEphemeralState(leaf.getEphemeralState());](https://github.com/hdykokd/obsidian-vertical-tabs-view/blob/57aadb83afa14e4767da93a2565b84cc47b76110/src/util/leaf.ts#L7) what is this hack for?


When switching tabs, the active tab's editor view does not become input-enabled, so this is a hack to make it input-enabled (I'm using Vim key bindings). However, upon checking just now, it seems that this hack may not be necessary... I might have misunderstood something.

**Comment by hdykokd** [comment]
> [getLeavesOfType](https://github.com/hdykokd/obsidian-vertical-tabs-view/blob/57aadb83afa14e4767da93a2565b84cc47b76110/src/view.ts#L135) this approach is way more expensive than it needs to be. You can just use [iterateAllLeaves](https://github.com/obsidianmd/obsidian-api/blob/38dd22168d2925086371bfc59e36fd9121527a39/obsidian.d.ts#L4157).

Thank you for pointing that out. I'll fix it.

**Comment by hdykokd** [comment]
https://github.com/hdykokd/obsidian-vertical-tabs-view/compare/2.0.16...2.0.17

**Comment by liamcain** [comment]
Sorry for the delay, the changes look great! Excited to have it in the plugin directory 😄

**Pull request merged**
