### PR TITLE
Add a new dark theme

### PR DESCRIPTION
**Pull request by MattWilcox**

### CODE REVIEW

**Comment by MattWilcox** [comment]
Please excuse me if this is not right - I've not contributed before and the documentation I could find was more about plugins than themes? Hopefully I've not screwed up!

**Comment by ericaxu** [comment]
> Please excuse me if this is not right - I've not contributed before and the documentation I could find was more about plugins than themes? Hopefully I've not screwed up!

Looks good, did you see a link to the theme template when you started this PR? I've attached it below and you can fill it out.

Oh and also please add it to the end of the file instead of the top, so if people sort themes by "last added" they get the correct result. thanks!

```markdown
<!--- Delete this section if submitting a plugin -->
# I am submitting a new Community Theme

## Repo URL

<!--- Paste a link to your repo here for easy access -->
Link to my theme: 


## Theme checklist

<!--- Confirm that you have done the following before submitting your theme -->
- [ ] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo)
  - [ ] `obsidian.css`
  - [ ] The screenshot file
- [ ] I have indicated which modes (dark, light, or both) are compatible with my theme
- [ ] I have added a license in the LICENSE file
- [ ] If my repo is not using the `master` branch, please indicate in `community-themes.json` with `"branch": "main"`.
```

**Comment by kometenstaub** [comment]
Please also specify that you are using the `main` branch:
>  If my repo is not using the master branch, please indicate in community-themes.json with "branch": "main".

---

A couple remarks regarding the top comments in the CSS:
> 	- Needing to use font-imports means there's a network dependency and latency cost (unless it's smart and caching things on the app level - documentation on themeing is currently lacking).

You can base64 encode the fonts and include them in your CSS file. See this [example](https://github.com/ceciliamay/obsidianmd-theme-primary/blob/main/obsidian.css) and this [resource section](https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/for+Theme+Designers).

> 	- Decorative elements are output as raw SVG in the mark-up instead of added via CSS - so I can't change the iconography.

If you mean changing the icons, you can use ` -webkit-mask-image`. The example theme I linked above also makes use of that.

**Comment by kometenstaub** [comment]
[Here](https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/Guides/How+to+add+your+theme+to+the+community+theme+store) is a guide for adding themes to the store.

**Comment by MattWilcox** [comment]
Thanks so much, sorry I got that wrong.

That guide is great, thanks - I'll be taking a good look into that! Despite looking for things relating to theme making, I've never seen that Obsidian Hub site - must have been looking in the wrong places - now bookmarked that one, looks very useful. I'd only seen https://github.com/obsidianmd/obsidian-releases via some googling, and that didn't seem to point anywhere with more guidance, so that's how I've ended up forking that and going wrong!

I've adjusted the forked file to put mine at the end; pushed that change so hopefully that's part of this issue now.

# I am submitting a new Community Theme

## Repo URL
Link to my theme: https://github.com/MattWilcox/obsidian-wilcox-one

## Theme checklist
- [ x ] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo)
  - [ x ] `obsidian.css`
  - [ x ] The screenshot file
- [ x ] I have indicated which modes (dark, light, or both) are compatible with my theme
- [ x ] I have added a license in the LICENSE file
- [ x ] If my repo is not using the `master` branch, please indicate in `community-themes.json` with `"branch": "main"`.

Confirming I'm using the master branch.

**Comment by kometenstaub** [comment]
> Despite looking for things relating to theme making, I've never seen that Obsidian Hub site - must have been looking in the wrong places - now bookmarked that one, looks very useful.

We've been working on it for some time now, we mostly posted it in the Discord. We've added links to it in the README of this repo now.

**Comment by ericaxu** [comment]
Looks good!

**Pull request merged**
