### PR TITLE
Add Zotero Sync plugin

### PR DESCRIPTION
**Pull request by frthjf**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/frthjf/obsidian-zotero-sync-client

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[export default class MyPlugin](https://github.com/frthjf/obsidian-zotero-sync-client/blob/125cd2d30236c2f1376a84f1fa162644189f244e/main.ts#L109)
Rename this class.

[if (this.settings.show_ribbon_icon) {](https://github.com/frthjf/obsidian-zotero-sync-client/blob/125cd2d30236c2f1376a84f1fa162644189f244e/main.ts#L191)
As of v1.1.0 of Obsidian, the ribbon can be customized within Obsidian. So users can choose what items to include and in what order all in one place. Because of this, we're recommending that new plugins avoid introducing their own toggles for ribbon items.

[await this.app.vault.rename(fn, newPath)](https://github.com/frthjf/obsidian-zotero-sync-client/blob/125cd2d30236c2f1376a84f1fa162644189f244e/main.ts#L402)
I would recommend calling `await this.app.filemanager.renameFile(fn, newPath);` instead.
That will make sure all links to this file are updated.

**Comment by frthjf** [comment]
Thanks for the great feedback!

I've addressed these issues now and released a new version (1.0.7).

**Comment by frthjf** [comment]
I've released a fixed version.

**Comment by liamcain** [comment]
- [borderColor](https://github.com/frthjf/obsidian-zotero-sync-client/blob/8f3ae4339d4501d7b147f92b602476f9aa610029/main.ts#L795) You should avoid assigning styles via javascript. Instead, just add a class to the element and move all these styles into CSS so that they are more easily adaptable by themes.

**Pull request merged**
