### PR TITLE
Add plugin: Front Matter Timestamps

### PR DESCRIPTION
**Pull request by lighthousedino**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/lighthousedino/obsidian-front-matter-timestamps

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lighthousedino** [comment]
A few days ago I submitted a plugin to automatically update modified time in front matter. I decided to also add created time, and it seems fitting to also rename the plugin. I accidently closed the old [pull request](https://github.com/obsidianmd/obsidian-releases/pull/3639).

**Comment by joethei** [comment]
Remove the `styles.css` file from your release, since it's empty it's just unnecessary bloat.

**Comment by lighthousedino** [comment]
Thanks for the quick response. Done.

**Comment by lighthousedino** [comment]
Hello @joethei . I would like to kindly follow up on this pull request. Are there any further changes to be made? Cheers!

**Pull request merged**
