### PR TITLE
Add Social Plugin

### PR DESCRIPTION
**Pull request by ckemmler**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Sekund/sekund-plugin-react

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lishid** [comment]
https://github.com/Sekund/sekund-plugin-react/blob/65453bb2c4839503d96af68add6873495101be2a/src/main.tsx#L221
Here you should use `workspace.getLeaf()` to get an unpinned leaf to open your note. This function gives you a leaf while respecting the pinned status of the pane.

https://github.com/Sekund/sekund-plugin-react/blob/65453bb2c4839503d96af68add6873495101be2a/src/main.tsx#L250
These events aren't tracked for removal when your plugin is disabled. You can use `Plugin.registerDomEvent` to track them for auto removal on plugin disable.

https://github.com/Sekund/sekund-plugin-react/blob/65453bb2c4839503d96af68add6873495101be2a/src/main.tsx#L359
I'm assuming you want to deal with markdown files here - better to use `workspace.getActiveViewOfType(MarkdownView)`. You can also use `view.getState()` instead of `leaf.getViewState()`.

https://github.com/Sekund/sekund-plugin-react/blob/65453bb2c4839503d96af68add6873495101be2a/src/main.tsx#L129
Here you should use `leaf.view.getMode() === 'preview'` which is less expensive than serializing the entire view state just to get the current mode.

**Comment by ckemmler** [comment]
Hey @lishid thank you for your review. Those issues are now fixed.

**Comment by lishid** [comment]
https://github.com/Sekund/sekund-plugin-react/commit/c17d6f882cd2f7619a13e07bf6431c1395770371#diff-1cd8b18798a1a103bfe13bef54354c1f3a3bea29a31c8eea1a0c67a3a839b811R129
You should use `leaf.view instanceof MarkdownView && leaf.view.getMode() === 'Preview'` instead. Always do an `instanceof` check instead of using `as any`.

https://github.com/Sekund/sekund-plugin-react/commit/c17d6f882cd2f7619a13e07bf6431c1395770371#diff-1cd8b18798a1a103bfe13bef54354c1f3a3bea29a31c8eea1a0c67a3a839b811R221
Here you might create new leaves twice. `getLeaf()` also gives you a leaf guaranteed, so you should always get a leaf back.

https://github.com/Sekund/sekund-plugin-react/commit/c17d6f882cd2f7619a13e07bf6431c1395770371#diff-1cd8b18798a1a103bfe13bef54354c1f3a3bea29a31c8eea1a0c67a3a839b811R363
I don't think setting the mode here like that works. Actually I think my bad - you're probably better off using getViewState and setViewState on `view.leaf`.

**Comment by ckemmler** [comment]
That all makes sense. Thank you @lishid. Done

**Comment by lishid** [comment]
Looks good. I need to fix your PR to move your plugin to the last row of the json file as well as follow the spacing convention before merging, however I don't have commit right to your PR branch - can you fix it yourself or give me permission in the PR? Thanks.

**Comment by ckemmler** [comment]
I just added you as a collaborator on my fork. Let me know if that works for you.

**Pull request merged**
