### PR TITLE
Add Clean Slack Paste

### PR DESCRIPTION
**Pull request by Eforen**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Eforen/obsidian-clean-slack-paste/

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by Eforen** [comment]
But it does have those?... not sure why it claims I don't...

**Comment by Eforen** [comment]
Dohhhh the repo is private >.<

**Comment by joethei** [comment]
["description": "A plugin to clean up Slack message pastes/exports",](https://github.com/Eforen/obsidian-clean-slack-paste/blob/3bba4a2678af4a4afd60344bca51071258b9115f/manifest.json#L5)
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This is a plugin" in your description.

["main": "main.js",](https://github.com/Eforen/obsidian-clean-slack-paste/blob/3bba4a2678af4a4afd60344bca51071258b9115f/manifest.json#L6)
This is not something Obsidian uses.

[import "./styles/styles.css";](https://github.com/Eforen/obsidian-clean-slack-paste/blob/3bba4a2678af4a4afd60344bca51071258b9115f/src/main.ts#L2)
Where is this file?
If you don't have any CSS, you can just omit the file from your releases.

[console.log("loading New Zettel");](https://github.com/Eforen/obsidian-clean-slack-paste/blob/3bba4a2678af4a4afd60344bca51071258b9115f/src/main.ts#L21)
That messages makes no sense here.

[console.log(doc.body.innerHTML);](https://github.com/Eforen/obsidian-clean-slack-paste/blob/3bba4a2678af4a4afd60344bca51071258b9115f/src/main.ts#L74)
Please avoid unnecessary logging. If you need it for debugging purposes, add a check to only log during development.

**Comment by ericaxu** [comment]
@Eforen Hi! Have you made the necessary changes? Just checking!

**Comment by Eforen** [comment]
Sorry working in it been really busy of late

**Pull request closed without merging**
