### PR TITLE
Update community-css-themes.json

### PR DESCRIPTION
**Pull request by ChopTV**
Added Theme-That-Shall-Not-Be-Named to community-css-themes.json

# I am submitting a new Community Theme

## Repo URL

Link to my theme: https://github.com/ChopTV/Obsidian-Theme-That-Shall-Not-Be-Named

## Theme checklist

- [x] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo)
  - [x] `obsidian.css`
  - [x] The screenshot file
- [x] I have indicated which modes (dark, light, or both) are compatible with my theme
- [x] I have added a license in the LICENSE file
- [x] If my repo is not using the `master` branch, please indicate in `community-themes.json` with `"branch": "main"`.

### CODE REVIEW

**Comment by ericaxu** [comment]
Would you consider developing this theme a bit more before submitting it? I see the potential but right now it's still quite similar to the default theme.

**Comment by ChopTV** [comment]
Sure not a problem. This is the first theme I've done and I haven't seen any sort of guidelines as to requirements for submission.

**Comment by ericaxu** [comment]
> Sure not a problem. This is the first theme I've done and I haven't seen any sort of guidelines as to requirements for submission.

Thanks for being so understanding! Just update the screenshot and ping me again if you feel like it's ready at some point and I'll take another look :)

**Comment by ChopTV** [comment]
I've done some tweaks and changes after using the theme for a few weeks as a daily driver. I have some more aesthetic changes planned, but I wouldn't be horrified for other people to use it and be able to provide feedback.

**Pull request merged**
