### PR TITLE
Updated the description for Interactivity plugin

### PR DESCRIPTION
**Pull request by ichichikin**
# Updated the description for Interactivity plugin.

## Repo URL
https://github.com/ichichikin/obsidian-plugin-interactivity

### CODE REVIEW

**Comment by joethei** [comment]
Don't include "Obsidian" in the description.

**Comment by ichichikin** [comment]
@joethei fixed

**Comment by ichichikin** [comment]
@joethei, just a quick bump

**Comment by ichichikin** [comment]
@joethei @muness @dpickett @czottmann, sorry for bumping everyone. It looks like something is off with this tiny PR as it's ignored. Could you please help me understand what's wrong?

**Comment by czottmann** [comment]
@ichichikin Thanks for including me out of the blue on this ticket I have no idea about 😉

My personal impression as an outsider, i.e. as somebody who doesn't work at Obsidian, is that they're simply entirely swamped with plugin code reviews, work on Obsidian, and everything. Every time one of my plugins was held up it wasn't out of spite or malice AFAICT but because it was one of many plugins, and had just disappeared back into the pile.

**Comment by ichichikin** [comment]
@czottmann Haha, thanks for sharing your experience! Sorry for bothering you though. I thought you might be part of the Obsidian team since you showed up in the suggestions😃
Gonna wait.

**Pull request merged**
