### PR TITLE
add Rule-folder-template plugin

### PR DESCRIPTION
**Pull request by daoif**
# I am submitting a new Community Plugin

## Repo URL
Link to my plugin:
https://github.com/daoif/obsidian-Rule-folder-template-daoif
## Release Checklist
- [ x ] I have tested the plugin on
  - [ x ]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x ] My GitHub release contains all required files
  - [ x] `main.js`
  - [x ] `manifest.json`
  - [x ] `styles.css` _(optional)_
- [x ] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x ] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x ] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x ] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x ] I have added a license in the LICENSE file.
- [x ] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by lishid** [comment]
Your haven't uploaded the source code of your plugin to the github repo. Could you please do that for review, or do you intend to submit a close sourced plugin? (I suspect it's just forgotten since you used the MIT license).

**Comment by daoif** [comment]
> 您尚未将插件的源代码上传到 github 存储库。您能否这样做以供审核，或者您是否打算提交一个封闭源插件？（我怀疑自从您使用 MIT 许可证以来，它只是被遗忘了）。

已经提交了源代码

**Comment by lishid** [comment]
哈哈哈我还是第一次看到中文写的代码

我感觉这个插件的功能有好几个其他的插件都可以做，而且代码写的还是有很多不严谨的地方（比如说用unsafeCachedData有可能是null）。如果插件是您自己用的其实可以不上传到官方插件库 在自己本地安装就可以用。

**Comment by daoif** [comment]
> 

这个功能与templater 及quickadd之间的区别在于.他们不允许在无活动文档的情况下,调用模板创建新的文档.
实际上,本来我是在templater上写的脚本,但在mind插件中使用时,无法调用,quickadd也是一样的,所以只好自己封装出来了.
关于代码质量问题,的确是没做错误处理,不过我寻思着能用就行(报错了也并不会导致ob或者插件崩溃),没有写.其实细节处有不少没有做好的地方,后续可能会根据实际需要进行改进.
如果是基于功能重复性的考量,我希望这个插件能通过审核.说不定有人会用到.
如果是代码质量问题的话,那就算了,我只是分享出来如果能帮助到他人再好不过.

**Comment by lishid** [comment]
Ok 我来帮你看看具体的可以改进的地方

https://github.com/daoif/obsidian-Rule-folder-template-daoif/blob/e70d6a1cb4dc038a19f63f904fdfbba518fbd6bb/src/main.ts#L162
这里可以用 Moment.js (在文件开头的import加上 `moment`) 然后用moment来format日期

https://github.com/daoif/obsidian-Rule-folder-template-daoif/blob/e70d6a1cb4dc038a19f63f904fdfbba518fbd6bb/src/main.ts#L169
这缺一个await

https://github.com/daoif/obsidian-Rule-folder-template-daoif/blob/e70d6a1cb4dc038a19f63f904fdfbba518fbd6bb/src/main.ts#L180
这最好加一个null check 然后最后用 `await vault.readCached(file)`.

**Comment by lishid** [comment]
Closing this PR for now to keep things tidy, let me know if you still intend to add your plugin to the repo and we can re-open it!

**Pull request closed without merging**
