### PR TITLE
feat: add obsidian-incremental-id declaration

### PR DESCRIPTION
**Pull request by adziok**
# I am submitting a new Community Plugin

## Repo URL
https://github.com/adziok/obsidian-incremental-id

Link to my plugin:
https://github.com/adziok/obsidian-incremental-id

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by adziok** [comment]
Fixed

**Comment by liamcain** [comment]
- [onunload() {](https://github.com/adziok/obsidian-incremental-id/blob/04a439267c7cbbfa605704a544dbaa7209b934ea/src/incremental-id-plugin.ts#L26-L28) You need to remove your app.insertIncrementalId in onunload, otherwise your plugin will remain in memory after it's disabled.
- [app.insertIncrementalId](https://github.com/adziok/obsidian-incremental-id/blob/04a439267c7cbbfa605704a544dbaa7209b934ea/src/incremental-id-plugin.ts#L18) Doesn't templater provide a collection of user scripts? Why not contribute to Templater instead of making this a separate plugin?
- [id: `insert-id:${newIdDefinition.prefix}`,](https://github.com/adziok/obsidian-incremental-id/blob/04a439267c7cbbfa605704a544dbaa7209b934ea/src/command-handler.ts#L21-L22) No need to prefix the ID, it will be prefixed automatically under the hood

**Comment by adziok** [comment]
Hi @liamcain !
I want to have a separate place, to build other functionality related to unique identifiers. I also think this could be part of the Kanban ecosystem in the future (like ids in jira). Flexibility will be needed for this!
Rest is fixed

**Comment by liamcain** [comment]
Hi @adziok, so sorry for the long wait. I totally missed this notification. Looks good. Thanks for your patience.

**Comment by adziok** [comment]
All issues fixed!

**Pull request merged**
