### PR TITLE
Add Plugin: Emoji Magic

### PR DESCRIPTION
**Pull request by SimplGy**
# I am submitting a new Community Plugin

Lightweight, text based emoji, all offline.
It's based on a Chrome extension but that's an extension I built and maintain.

## Repo URL

https://github.com/SimplGy/obsidian-emoji-magic

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by SimplGy** [comment]
Just checking; not sure if I'm in the review queue or the the action item is on me to resolve the merge conflict.

**Comment by joethei** [comment]
We will take care of the merge errors once we approve your plugin.

[MyPlugin](https://github.com/SimplGy/obsidian-emoji-magic/blob/ef7ab9e4d37418a2650accaf2e1cc38e15480c44/src/main.ts#L36)
[MyPluginSettings](https://github.com/SimplGy/obsidian-emoji-magic/blob/ef7ab9e4d37418a2650accaf2e1cc38e15480c44/src/interfaces.ts#L17)
Would recommend renaming that class to something more unique

[id: 'emoji-magic-insert', // should not change over time](https://github.com/SimplGy/obsidian-emoji-magic/blob/ef7ab9e4d37418a2650accaf2e1cc38e15480c44/src/main.ts#L71)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to do it yourself.

[// "what it does"](https://github.com/SimplGy/obsidian-emoji-magic/blob/ef7ab9e4d37418a2650accaf2e1cc38e15480c44/src/main.ts#L120-L137)
[Avoid using `innerHTML`](https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#avoid-innerhtml-outerhtml-and-insertadjacenthtml)

[const CHROME_EXTENSION_URL = 'https://chrome.google.com/webstore/detail/emoji-magic/jfegjdogmpipkpmapflkkjpkhbnfppln';](https://github.com/SimplGy/obsidian-emoji-magic/blob/ef7ab9e4d37418a2650accaf2e1cc38e15480c44/src/search_modal.ts#L27-L28)
These constants are getting declared twice, here and in main.ts

**Comment by SimplGy** [comment]
Thanks for the review.

Made all those changes and bumped the release to `0.1.2`.

- [x] rename `MyPlugin` and `MyPluginSettings`
- [x] remove plugin prefix on command id
- [x] don't use innerHTML
- [x] centralize `cfg` constants

**Comment by liamcain** [comment]
- [Find an emoji and insert it where your cursor is](https://github.com/SimplGy/obsidian-emoji-magic/blob/1e9fa9332c33b9a270708eee2e732681c2e68932/src/main.ts#L67) nit: prefer simpler command names. This could just be called `Insert emoji...` (The ... implying that a subsequent modal will appear with more steps for the user)
- [getActiveViewOfType(MarkdownView](https://github.com/SimplGy/obsidian-emoji-magic/blob/1e9fa9332c33b9a270708eee2e732681c2e68932/src/main.ts#L80) if you want this plugin to work with Canvas, then you can switch this to look for [`activeEditor`](https://github.com/obsidianmd/obsidian-api/blob/38dd22168d2925086371bfc59e36fd9121527a39/obsidian.d.ts#L4009) instead.

**Pull request merged**
