### PR TITLE
Add plugin: TinyChart

### PR DESCRIPTION
**Pull request by alincoop**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/alincoop/obsidian-tinychart/

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by alincoop** [comment]
Added license

**Comment by alincoop** [comment]
Moved license file and updated command names to exclude plugin name.

**Comment by joethei** [comment]
["description": "Dead simple ASCII charts for Obsidian",](https://github.com/alincoop/obsidian-tinychart/blob/44d6db6c2e7e185fabccf58ea06be58f6201ae02/manifest.json#L6)
Avoid including sentences like "This is a plugin for Obsidian that does ..." in your description, it should be self-evident that this is a plugin for Obsidian.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[id: "tinychart-example-hbar",](https://github.com/alincoop/obsidian-tinychart/blob/44d6db6c2e7e185fabccf58ea06be58f6201ae02/src/main.ts#L22)
You can remove `tinychart` here.

[containerEl.createEl("h1", { text: "TinyChart" });](https://github.com/alincoop/obsidian-tinychart/blob/44d6db6c2e7e185fabccf58ea06be58f6201ae02/src/settings/settingsTab.ts#L17)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[containerEl.createEl("h2", {](https://github.com/alincoop/obsidian-tinychart/blob/44d6db6c2e7e185fabccf58ea06be58f6201ae02/src/settings/settingsTab.ts#L18-L20)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)

[.setName("Show Labels")](https://github.com/alincoop/obsidian-tinychart/blob/44d6db6c2e7e185fabccf58ea06be58f6201ae02/src/settings/settingsTab.ts#L123)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by alincoop** [comment]
["description": "Dead simple ASCII charts for Obsidian",](https://github.com/alincoop/obsidian-tinychart/blob/44d6db6c2e7e185fabccf58ea06be58f6201ae02/manifest.json#L6)
Avoid including sentences like "This is a plugin for Obsidian that does ..." in your description, it should be self-evident that this is a plugin for Obsidian. ✅

[id: "tinychart-example-hbar",](https://github.com/alincoop/obsidian-tinychart/blob/44d6db6c2e7e185fabccf58ea06be58f6201ae02/src/main.ts#L22)
You can remove tinychart here. ✅

[this.registerMarkdownCodeBlockProcessor("csv", (source, el) => {](https://github.com/alincoop/obsidian-tinychart/blob/44d6db6c2e7e185fabccf58ea06be58f6201ae02/src/main.ts#L33-L48)
This should not be part of this plugin ✅

[containerEl.createEl("h1", { text: "TinyChart" });](https://github.com/alincoop/obsidian-tinychart/blob/44d6db6c2e7e185fabccf58ea06be58f6201ae02/src/settings/settingsTab.ts#L17)
[Don't include a header with the plugin name in the settings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.) ✅

[containerEl.createEl("h2", {](https://github.com/alincoop/obsidian-tinychart/blob/44d6db6c2e7e185fabccf58ea06be58f6201ae02/src/settings/settingsTab.ts#L18-L20)
[Only use headings under settings if you have more than one section.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.) ✅

[.setName("Show Labels")](https://github.com/alincoop/obsidian-tinychart/blob/44d6db6c2e7e185fabccf58ea06be58f6201ae02/src/settings/settingsTab.ts#L123)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI) ✅

**Comment by alincoop** [comment]
@joethei Thanks for reviewing and merging my plugin.

I have just updated it and created a new release ([0.1.1](https://github.com/alincoop/obsidian-tinychart/releases/tag/0.1.1)). How long will it take to publish in-app? Currently when I "check for updates" in Obsidian it still shows 0.1.0 as the latest available release.

**Pull request merged**
