### PR TITLE
Add plugin: Zettelkasten Outliner

### PR DESCRIPTION
**Pull request by tylersuzukinelson**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/tylersuzukinelson/zettelkasten-outliner/

## Release Checklist
- [ ] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "This plugin provides a list representation for your Zettelkasten.",](https://github.com/tylersuzukinelson/zettelkasten-outliner/blob/7b643696b015f455c369a52a84234703d36bb98b/manifest.json#L6)
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This plugin does xyz" in your description.

["fundingUrl": "https://www.tylersuzukinelson.com",](https://github.com/tylersuzukinelson/zettelkasten-outliner/blob/7b643696b015f455c369a52a84234703d36bb98b/manifest.json#L9)
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link omit this.

[mySetting: string;](https://github.com/tylersuzukinelson/zettelkasten-outliner/blob/7b643696b015f455c369a52a84234703d36bb98b/main.ts#L4)
Since your plugin does not have any settings you should remove all references to them.

[id: 'zettelkasten-outliner-create-outline',](https://github.com/tylersuzukinelson/zettelkasten-outliner/blob/7b643696b015f455c369a52a84234703d36bb98b/main.ts#L18)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

[name: 'Create Zettelkasten Outline',](https://github.com/tylersuzukinelson/zettelkasten-outliner/blob/7b643696b015f455c369a52a84234703d36bb98b/main.ts#L19)

[if (currentFile) {](https://github.com/tylersuzukinelson/zettelkasten-outliner/blob/7b643696b015f455c369a52a84234703d36bb98b/main.ts#L22)
You should be using a conditional command here, <https://docs.obsidian.md/Plugins/User+interface/Commands#Conditional+commands>

**Comment by tylersuzukinelson** [comment]
Hey Johannes,

Thank you for the feedback! I've addressed your feedback except for the `checkCallback` one.

I couldn't figure out how to do this as my command has an async component. It was throwing an error because of the return type mismatch on the signature of `checkCallback`, but it also sounds like `checkCallback` overrides `callback` so I can't implement both to deal with the asynchronous nature of the command.

Any suggestions on how to go about this?

**Comment by joethei** [comment]
In this case it's fine to use the promise based functions.

```ts
checkCallback: checking => {
	const currentFile = this.app.workspace.getActiveFile();
	if(checking) {
		return !!currentFile;
	}
	this.app.vault.create('bla.md', '').then(file => {
		this.parseZettel(file, currentFile, 0);
	});

}
```

**Comment by tylersuzukinelson** [comment]
Hey @joethei, sorry for the delay!

I've moved this over to use the conditional check now :)

**Pull request merged**
