### PR TITLE
Add plugin: Note Gallery

### PR DESCRIPTION
**Pull request by pashashocky**
# I am submitting a new Community Plugin

## Repo URL
Link to my plugin: https://github.com/pashashocky/obsidian-note-gallery

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [x]  Linux
  - [x]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using. I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "A masonry gallery for Obsidian that will visualize your notes, similar to Craft note view.",](https://github.com/pashashocky/obsidian-note-gallery/blob/a61149ff9cfde3327d947e9ed4f40336f1342889/manifest.json#L6)
Don't mention Obsidian or Craft here, it should be obvious that this is for Obsidian.
(And the Craft mention will only work for users that know Craft)
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[id: "note-gallery-drop-database",](https://github.com/pashashocky/obsidian-note-gallery/blob/a61149ff9cfde3327d947e9ed4f40336f1342889/src/main.ts#L100)
Obsidian will automatically prefix the command id with the plugin id,
you don't need to include it yourself.

[<h1>Note Gallery: Indexing Database...</h1>](https://github.com/pashashocky/obsidian-note-gallery/blob/a61149ff9cfde3327d947e9ed4f40336f1342889/src/react/index.tsx#L55)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[div.innerHTML = innerHTML;](https://github.com/pashashocky/obsidian-note-gallery/blob/a61149ff9cfde3327d947e9ed4f40336f1342889/src/react/utils/render-utils.ts#L54)
[Avoid using `innerHTML`](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%60innerHTML%60%2C+%60outerHTML%60+and+%60insertAdjacentHTML%60)

**Comment by pashashocky** [comment]
@joethei thank you for the review! I will address the styling/description and command issues. 

Have a question about the usage of `innerHTML` - mainly how fast is the `MarkdownRenderer.render` function...

I understand the issues but I feel that in this case the usage is warranted. I have a caching layer which uses localforage - it stores the text/markdown of the notes. When the plugin loads no `innerHTML` is stored. 

The plugin will first render all cards using the `MarkdownRenderer` and then store the rendered html into a memory map, in the future if the card has to be reloaded it will be reloaded from cache. Every time a note is modified the rendered html is dropped from the cache. 

If you feel this is still dangerous, let me know and I can remove the `innerHTML` completely, I feel that it does create a speedup, but this would mean that cards would have to rely on `MarkdownRenderer` to render them every time they fall into view.

**Comment by pashashocky** [comment]
@joethei - I've addressed the comments from your review [in this commit](https://github.com/pashashocky/obsidian-note-gallery/commit/dcffee1ba76646b868ad973c1d223ab1fa21a05b)

Please, re-review at your convenience.

**Comment by pashashocky** [comment]
Fixed merge conflict.

**Comment by liamcain** [comment]
- [newLeaf](https://github.com/pashashocky/obsidian-note-gallery/blob/121fa1217c724a00c7072fa06bc032e0c9a3d113/src/react/components/Card.tsx#L22) you can use [`Keymap.isModEvent`](https://github.com/obsidianmd/obsidian-api/blob/009a10f196df551256a5894ea60fdf9ddaab19a1/obsidian.d.ts#L1639) instead

**Pull request merged**
