### PR TITLE
Added lines-swapper plugin to plugins community list

### PR DESCRIPTION
**Pull request by guidolippi94**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/guidolippi94/obsidian-lines-swapper

## Release Checklist

- [ x] I have tested this on Windows, macOS, and Linux _(if applicable)_
- [ x] My GitHub release contains all required files
  - [ x] `main.js`
  - [ x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [ x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [ x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x ] README clearly describes the plugins purpose and provides clear usage instructions.
- [ x] I have added a license in the LICENSE file.

### CODE REVIEW

**Comment by pjeby** [comment]
Obsidian already has builtin commands for "Swap line up" and "Swap line down", they just don't have hotkeys assigned by default.  You can assign them hotkeys by going to "Hotkeys" in your Obsidian settings and typing "swap" in the search box, then click the "asterisk key" button next to each command to add a hotkey.

**Comment by guidolippi94** [comment]
Thank you for your reply and your suggestion.
If the plugin will implement multiline swap (IDE like) could be added to community plugins?
Best

Guido

**Comment by pjeby** [comment]
Perhaps it would be a good idea for you to play with the built-in swap commands in Obsidian first, so you can describe the differences between what they do and what your plugin does?  A clear explanation of the plugin's purpose is one of the requirements for a plugin listing, after all.

(Trying them out will also show you how they behave with multiline or multiple selections, so you can determine whether there is anything they don't do that you would like your plugin to do.  I think, though, that you will find them to be quite IDE-like already: you can use alt-drag to select multiple locations, for example, and then swap them all up or down a line at the same time, in addition to single or multiline selections.)

**Comment by ericaxu** [comment]
Hi there, to keep things tidy, we're going to temporarily close plugin PRs after a month of inactivity.

Feel free to tell us to re-open it when you're ready to continue. Thanks for your understanding!

**Pull request closed without merging**
