### PR TITLE
Add plugin: Tailwind Snippet

### PR DESCRIPTION
**Pull request by nicholas-wilcox**
# I am submitting a new Community Plugin

~~I'm submitting two plugins. I hope that's okay, but I can break them apart into two PRs if necessary.~~

## Repo URL

Link to my plugin: https://github.com/nicholas-wilcox/tailwind-snippet-obsidian-plugin

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by nicholas-wilcox** [comment]
ah, well let me take a break and make dinner while I think about renaming my plugins 😅

**Comment by nicholas-wilcox** [comment]
It's clear that trying to submit two plugins at once is bad and evades automated testing. I'm changing this and creating a new PR for the second plugin before human reviewers get involved.

**Comment by joethei** [comment]
To make the manual review process and future plugin maintenance more efficient, we recommend that you move all source code files into a `src` directory.

[import { id as pluginId } from "./manifest.json";](https://github.com/nicholas-wilcox/tailwind-snippet-obsidian-plugin/blob/37be03ae7b2e8ebf7ab0db8cc4ae44c8783ae2b7/main.ts#L20)
You can get the manifest id this way: `this.manifest.id` inside of the plugin class.

[this.vault.configDir + `/plugins/${pluginId}/preflight.css`,](https://github.com/nicholas-wilcox/tailwind-snippet-obsidian-plugin/blob/37be03ae7b2e8ebf7ab0db8cc4ae44c8783ae2b7/main.ts#L86)
It's better to use `this.manifest.dir` here.

**Comment by nicholas-wilcox** [comment]
I've made the changes above. I also noticed that `this.manifest.dir` is included on the manifest reference page and will submit an issue for that.

**Pull request merged**
