### PR TITLE
Add plugin: Markwhen

### PR DESCRIPTION
**Pull request by kochrt**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: [https://github.com/mark-when/obsidian-plugin](https://github.com/mark-when/obsidian-plugin)

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
[.workspace-leaf-content .view-content {](https://github.com/mark-when/obsidian-plugin/blob/9194d0dc084e55660570cc16899fab781b49d14b/styles.css#L10), [.cm-content {](https://github.com/mark-when/obsidian-plugin/blob/9194d0dc084e55660570cc16899fab781b49d14b/styles.css#L21-L24)
Please don't overwrite core styling in a plugin, add another class/data attribute so it only applies to your plugin.

[calendar.html](https://github.com/mark-when/obsidian-plugin/blob/9194d0dc084e55660570cc16899fab781b49d14b/src/templates/calendar.html#L1-L135), [oneview.html](https://github.com/mark-when/obsidian-plugin/blob/9194d0dc084e55660570cc16899fab781b49d14b/src/templates/oneview.html#L1-L25), [resume.html](https://github.com/mark-when/obsidian-plugin/blob/9194d0dc084e55660570cc16899fab781b49d14b/src/templates/resume.html#L1-L46), [timeline.html](https://github.com/mark-when/obsidian-plugin/blob/9194d0dc084e55660570cc16899fab781b49d14b/src/templates/timeline.html#L1-L174)
Where is all of this code compiled from?
These files should not be part of the repo, but the scripts/tools that where used to generate these files should be, or they should be at least linked in the dev instructions.

**Comment by Acylation** [comment]
Thanks joethei for reviewing! In the lastest build [0.0.2](https://github.com/mark-when/obsidian-plugin/releases/tag/0.0.2) these problems are all stressed.

> [.workspace-leaf-content .view-content {](https://github.com/mark-when/obsidian-plugin/blob/9194d0dc084e55660570cc16899fab781b49d14b/styles.css#L10), [.cm-content {](https://github.com/mark-when/obsidian-plugin/blob/9194d0dc084e55660570cc16899fab781b49d14b/styles.css#L21-L24)
Please don't overwrite core styling in a plugin, add another class/data attribute so it only applies to your plugin.

A custom view class is assigned for styling view content, and the `cm-content` decoration has been removed.

https://github.com/mark-when/obsidian-plugin/blob/386b5f2ec84e5c58f1bbaf62a197e01770362d43/src/MarkwhenView.ts#L232-L237

https://github.com/mark-when/obsidian-plugin/blob/386b5f2ec84e5c58f1bbaf62a197e01770362d43/styles.css#L10-L13

> [calendar.html](https://github.com/mark-when/obsidian-plugin/blob/9194d0dc084e55660570cc16899fab781b49d14b/src/templates/calendar.html#L1-L135), [oneview.html](https://github.com/mark-when/obsidian-plugin/blob/9194d0dc084e55660570cc16899fab781b49d14b/src/templates/oneview.html#L1-L25), [resume.html](https://github.com/mark-when/obsidian-plugin/blob/9194d0dc084e55660570cc16899fab781b49d14b/src/templates/resume.html#L1-L46), [timeline.html](https://github.com/mark-when/obsidian-plugin/blob/9194d0dc084e55660570cc16899fab781b49d14b/src/templates/timeline.html#L1-L174)
Where is all of this code compiled from?

The vue versions are hosted in other repos under @mark-when, e.g. https://github.com/mark-when/timeline. Now the template html files are removed from the plugin repo, and we opted to introduce these from npm distributions instead.

https://github.com/mark-when/obsidian-plugin/blob/386b5f2ec84e5c58f1bbaf62a197e01770362d43/src/templates.ts#L1-L4

**Comment by kochrt** [comment]
(I might have to comment to get the review bot to change the labels?) 

Changes made

**Comment by kochrt** [comment]
@joethei How do we get reviewed again or get the labels updated?

**Pull request merged**
