### PR TITLE
Add plugin: Static Site MD Exporter

### PR DESCRIPTION
**Pull request by yy4382**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/yy4382/obsidian-static-site-export

## Release Checklist
- [x] I have tested the plugin on
  - [x]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by yy4382** [comment]
I've pushed all of the required changes.

**Comment by joethei** [comment]
["fundingUrl": "",](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/manifest.json#L9)
This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link omit this.

[getFrontmatter(noteContent: string): Frontmatter | null {](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/main.ts#L107-L112)
Use `this.app.metadataCache.getFileCache(file).frontmatter` instead.

[YAML.stringify(post.frontmatter) +](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/PostHandle.ts#L142), [`---\n` + YAML.stringify(post.frontmatter) + `---\n\n` + post.article;](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/Upload.ts#L86), [`---\n` + YAML.stringify(post.frontmatter) + `---\n\n` + post.article;](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/Upload.ts#L212)
Use the `stringifyYaml` function from the Obsidian API function instead.

[easyimage_api_endpoint: "https://yourdomain/api/index.php",](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/Settings.ts#L10)
The default should be a empty string.

[.setDesc("us-east-1")](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/Settings.ts#L91)
This does not make sense as a description.

[.setName("Uploader Type")](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/Settings.ts#L61). [.setName("S3 API ENDPOINT")](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/Settings.ts#L77), [.setName("S3 API Region")](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/Settings.ts#L90), [.setName("S3 API Bucket")](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/Settings.ts#L102), [.setName("S3 API Access Key ID")](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/Settings.ts#L114), [.setDesc("Access Key ID")](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/Settings.ts#L115), [.setName("S3 API Secret Access Key")](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/Settings.ts#L126-L127), [.setName("S3 API Test")](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/Settings.ts#L138-L139), [.setName("Git Repo")](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/Settings.ts#L178), [.setName("Git Branch")](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/Settings.ts#L188), [new Setting(containerEl).setName("Git Username").addText((text) =>](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/Settings.ts#L199), [.setName("Git Personal Access Token")](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/Settings.ts#L208), [new Setting(containerEl).setName("Git Commit Message").addText((text) =>](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/Settings.ts#L216), [.setName("Git Author Name")](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/Settings.ts#L225), [.setName("Git Author Email")](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/Settings.ts#L236), [.setName("Post Prefix")](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/Settings.ts#L258), [.setName("Deploy Webhook")](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/Settings.ts#L300), [.setName("Enable Webhook Deploy")](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/Settings.ts#L304), [new Setting(containerEl).setName("Github User").addText((text) =>](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/Settings.ts#L333), [new Setting(containerEl).setName("Github Repo").addText((text) =>](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/Settings.ts#L342), [new Setting(containerEl).setName("Github Webhook Token").addText((text) =>](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/Settings.ts#L351), [.setName("Github Webhook Event Type")](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/src/Settings.ts#L361)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

**Comment by yy4382** [comment]
> ["fundingUrl": "",](https://github.com/yy4382/obsidian-static-site-export/blob/1af6f28e198f5b70803c4f0155bc77b55666c158/manifest.json#L9) This is meant for links to services like _Buy me a coffee_, _GitHub sponsors_ and so on, if you don't have such a link omit this.

I don't have such a link, so "omit this" means i don't need to make changes or i have to remove the full `"fundingUrl": "",` line from the json?

All other changes have been made in the new version of my plugin, leaving the funding url empty.

See: https://github.com/yy4382/obsidian-static-site-export/releases/tag/1.3.2

**Comment by joethei** [comment]
Remove the line.

**Comment by yy4382** [comment]
> Remove the line.

Done.

https://github.com/yy4382/obsidian-static-site-export/releases/tag/1.3.3

**Comment by yy4382** [comment]
@joethei It has been a month since your last comment. Any progress? I've made all the required changes.

**Pull request merged**
