### PR TITLE
Add plugin: Task Director

### PR DESCRIPTION
**Pull request by cybertramp**
# I am submitting a new Community Plugin
## Repo URL
Link to my plugin: [task-director](https://github.com/cybertramp/obsidian-task-director)

## Release Checklist
* [x]   I have tested the plugin on
  * [x]   Windows
  * [x]   macOS
  * [x]   Linux
  * [ ]   Android _(if applicable)_
  * [ ]   iOS _(if applicable)_
* [x]   My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  * [x]   `main.js`
  * [x]   `manifest.json`
  * [x]   `styles.css` _(optional)_
* [x]   GitHub release name matches the exact version number specified in my manifest.json (0.0.1)
* [x]   The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file (cursor-bridge)
* [x]   My README.md describes the plugin's purpose and provides clear usage instructions.
* [x]   I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
* [x]   I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
* [x]   I have added a license in the LICENSE file.
* [x]   My project respects and is compatible with the original license of any code from other plugins that I'm using.
  I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["description": "Manage and Change Tasks Targeting a Specific Page",](https://github.com/cybertramp/obsidian-task-director/blob/287bb56d866a4d470a82324425b3806f3e98b04a/manifest.json#L6), [item.setTitle("TODO Summary")](https://github.com/cybertramp/obsidian-task-director/blob/287bb56d866a4d470a82324425b3806f3e98b04a/main.ts#L72), [.setName("Remove Completed Date")](https://github.com/cybertramp/obsidian-task-director/blob/287bb56d866a4d470a82324425b3806f3e98b04a/main.ts#L263), [contentEl.createEl("h2", { text: "Page Task Statistics" });](https://github.com/cybertramp/obsidian-task-director/blob/287bb56d866a4d470a82324425b3806f3e98b04a/main.ts#L302-L303), [this.addTableRow(table, "Total Tasks", this.totalTodos);](https://github.com/cybertramp/obsidian-task-director/blob/287bb56d866a4d470a82324425b3806f3e98b04a/main.ts#L317), [text: `Completion Rate: ${completionRate}%`,](https://github.com/cybertramp/obsidian-task-director/blob/287bb56d866a4d470a82324425b3806f3e98b04a/main.ts#L328)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[callback: () => this.toggleTasksInCurrentFile(true),](https://github.com/cybertramp/obsidian-task-director/blob/287bb56d866a4d470a82324425b3806f3e98b04a/main.ts#L35), [callback: () => this.toggleTasksInCurrentFile(false),](https://github.com/cybertramp/obsidian-task-director/blob/287bb56d866a4d470a82324425b3806f3e98b04a/main.ts#L42), [callback: () => this.showTodoCountsInCurrentFile(),](https://github.com/cybertramp/obsidian-task-director/blob/287bb56d866a4d470a82324425b3806f3e98b04a/main.ts#L49)
These should be using [conditional commands](https://docs.obsidian.md/Plugins/User+interface/Commands#Conditional+commands)


[await this.app.vault.modify(file, updatedContent);](https://github.com/cybertramp/obsidian-task-director/blob/287bb56d866a4d470a82324425b3806f3e98b04a/main.ts#L107)
It would be better to use the newish `process` function, as that will modify the file atomically.
You will need to increase your `minAppVersion` in the plugin manifest for that.

**Review by cybertramp — COMMENTED** [review]
Update community-plugins.json

**Comment by cybertramp** [comment]
Thanks feedback. 😀

I fix all items.

**Review by cybertramp — COMMENTED** [review]
update community-plugins.json

- update sentense case and add plugin last item

**Pull request merged**
