### PR TITLE
Add plugin: Format with Prettier

### PR DESCRIPTION
**Pull request by alexgavrusev**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: ~~https://github.com/alexgavrusev/obsidian-plugin-prettier-2~~ https://github.com/alexgavrusev/obsidian-format-with-prettier

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [x]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["name": "Prettier Format 2",](https://github.com/alexgavrusev/obsidian-plugin-prettier-2/blob/cd31a320540b808c29aafe4e711162148fe62f1a/manifest.json#L3
You should think of a better name, since this plugin is not related to the other plugin at all.

[private getEditor(): Editor | null {](https://github.com/alexgavrusev/obsidian-plugin-prettier-2/blob/cd31a320540b808c29aafe4e711162148fe62f1a/src/main.ts#L65-L74)
To get the active editor you can do `this.app.workspace.activeEditor` instead.

**Comment by alexgavrusev** [comment]
> ["name": "Prettier Format 2",](https://github.com/alexgavrusev/obsidian-plugin-prettier-2/blob/cd31a320540b808c29aafe4e711162148fe62f1a/manifest.json#L3 You should think of a better name, since this plugin is not related to the other plugin at all.

Well, the plugins are kind of related. I created it to serve as a replacement for the [`obsidian-plugin-prettier`](https://github.com/hipstersmoothie/obsidian-plugin-prettier)

The core feature is the same - formatting notes, on save or with a command, using [prettier](https://prettier.io). The difference is that my plugin:
- [supports mobile by using `prettier/standalone`](https://github.com/alexgavrusev/obsidian-plugin-prettier-2/blob/304f86ed72e8dd7cf6862355c6b7dd69eb86b8e7/src/main.ts#L10)
- [works with vim](https://github.com/alexgavrusev/obsidian-plugin-prettier-2/blob/304f86ed72e8dd7cf6862355c6b7dd69eb86b8e7/src/vim-write-command-patcher.ts#L9)
- takes a different approach with configuration

Would you be fine with me expanding the readme to highlight those similarities and differences? If not, I can rename to "Format with Prettier" (`format-with-prettier`); does that name sound good to you?

> [private getEditor(): Editor | null {](https://github.com/alexgavrusev/obsidian-plugin-prettier-2/blob/cd31a320540b808c29aafe4e711162148fe62f1a/src/main.ts#L65-L74) To get the active editor you can do `this.app.workspace.activeEditor` instead.

Fixed, created [release 0.1.1](https://github.com/alexgavrusev/obsidian-plugin-prettier-2/releases/tag/0.1.1)

**Comment by alexgavrusev** [comment]
@liamcain @joethei ping

**Comment by liamcain** [comment]
Hi, please consider changing the same of the plugin. Adding a numeric to the end of the plugin name will likely cause this plugin to get confused with Prettier Format and users will wrongfully assume that this is a continuation of that project.

**Comment by alexgavrusev** [comment]
@liamcain done in [release 0.2.0](https://github.com/alexgavrusev/obsidian-format-with-prettier/releases/tag/0.2.0)

**Pull request merged**
