### PR TITLE
Add LaTeX Algorithm plugin

### PR DESCRIPTION
**Pull request by SamZhang02**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/SamZhang02/obsidian-latex-algorithms

## Release Checklist
- [x] I have tested the plugin on
  - [ ]  Windows
  - [x]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by SamZhang02** [comment]
Does a comment count as a change to me PR? xD

**Comment by joethei** [comment]
[upon detecting keywords, such as `\If`, `\For`, etc.](https://github.com/SamZhang02/obsidian-latex-algorithms/blob/4d19a3c5f086bd17aa6ab727e9bc8f40e3904039/README.md#L17)
Would recommend putting all supported keywords in the readme.

[import {version as VERSION} from './manifest.json';](https://github.com/SamZhang02/obsidian-latex-algorithms/blob/4d19a3c5f086bd17aa6ab727e9bc8f40e3904039/main.ts#L4)
You don't need to do this, you can instead use `this.plugin.manifest.version`;

**Comment by SamZhang02** [comment]
Thanks for the comment Johannes, 
Sorry for the question, I am slightly new to git still. 
I have made the approriate changes and pushed it into my main, what would be the next step in this case? Should I change my main.js file in my 1.0.0 release, or should I make a new release with the changed js file? 

Thanks again!
Sam

**Comment by joethei** [comment]
You need to create a new release.

**Comment by SamZhang02** [comment]
Hi Johannes,
I have created a new release under the tag `1.0.1` with the suggested changes.
Though it seems like it is not passing the plugin validation, is it an issue on my side?

Thanks,
Sam

**Comment by SamZhang02** [comment]
Hi,
A new release with the suggested changes has been posted as `1.0.1`.

Thanks.

**Pull request merged**
