### PR TITLE
Add plugin: Snippetsaurus

### PR DESCRIPTION
**Pull request by Chrstn67**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/Chrstn67/obsidian-plugin-obsnippets

## Release Checklist
- [x] I have tested the plugin on
  - [x] Windows
  - [ ]  macOS
  - [ ]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
  - [x] `main.js`
  - [x] `manifest.json`
  - [ ] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by joethei** [comment]
["name": "Obsnippets",](https://github.com/Chrstn67/obsidian-plugin-obsnippets/blob/ac9b1f356c19dbbb483d30f07520441baa39ef7d/manifest.json#L3)
Please don't use abbreviations of "Obsidian" in your plugin name.

["description": "Plugin for creating and managing text and code snippets",](https://github.com/Chrstn67/obsidian-plugin-obsnippets/blob/ac9b1f356c19dbbb483d30f07520441baa39ef7d/manifest.json#L6)
Avoid including sentences like "This is a plugin that does ..." in your description, it should be self-evident that this is a plugin.
We have published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.

[.setName("Nom du snippet")](https://github.com/Chrstn67/obsidian-plugin-obsnippets/blob/ac9b1f356c19dbbb483d30f07520441baa39ef7d/main.js#L30), [setButtonText("Insérer")](https://github.com/Chrstn67/obsidian-plugin-obsnippets/blob/ac9b1f356c19dbbb483d30f07520441baa39ef7d/main.js#L147), [new Notice(`Snippet "${snippet.name}" créé !`);](https://github.com/Chrstn67/obsidian-plugin-obsnippets/blob/ac9b1f356c19dbbb483d30f07520441baa39ef7d/main.js#L209)
Please stick to one language, or add i18n capabilities.

[name: "Insert in note and Manage snippets",](https://github.com/Chrstn67/obsidian-plugin-obsnippets/blob/ac9b1f356c19dbbb483d30f07520441baa39ef7d/main.js#L218)
[Avoid "options" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

[this.registerCodeMirror((cm) => {](https://github.com/Chrstn67/obsidian-plugin-obsnippets/blob/ac9b1f356c19dbbb483d30f07520441baa39ef7d/main.js#L234-L256)
This code does nothing, `registerCodeMirror` has been removed in 1.5.0

**Comment by Chrstn67** [comment]
Hello, 

I've corrected what you asked me to do. I hope it works, I can't wait to see it available :)

**Comment by Chrstn67** [comment]
Hello, 

It's been 3 weeks since I've had any news about the release of my plugin. Maybe I forgot to do something... Could you please help me?

**Comment by joethei** [comment]
You have not changed the command name (and it looks like I pasted in the wrong piece of feedback)

**Comment by Chrstn67** [comment]
Are you talking about the id and/or name in my manifest.json code, or about resolving the community-plugins.json conflict?

**Comment by joethei** [comment]
This:
> [name: "Insert in note and Manage snippets",](https://github.com/Chrstn67/obsidian-plugin-obsnippets/blob/ac9b1f356c19dbbb483d30f07520441baa39ef7d/main.js#L218)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

And there are a bunch more strings in your code that don't use sentence case.

**Comment by Chrstn67** [comment]
"Insert in note and Manage snippets" has already been corrected in the last update...

**Comment by joethei** [comment]
I don't see any change, it's hasn't been touched in over a month.

**Comment by Chrstn67** [comment]
Strange...

https://github.com/Chrstn67/obsidian-plugin-obsnippets/releases/tag/1.0.2

**Comment by joethei** [comment]
https://github.com/Chrstn67/obsidian-plugin-obsnippets/blame/main/main.js#L218

This line needs to be updated.

**Comment by joethei** [comment]
[﻿# Obsnippets Plugin](https://github.com/Chrstn67/obsidian-plugin-obsnippets/blob/272a0e3bdd88307c912b11bf5bda7f67474ff993/README.md?plain=1#L1C1-L1C21)
Please also change this header.

**Comment by Chrstn67** [comment]
Changes made

**Comment by Chrstn67** [comment]
Hello 

I noticed after PRing plugin-community.json that the id and name didn't match... I see that the plugin is available in Obsidian but I have a small podal telling me that the ID is wrong, certainly following the modification of the ID...

Do I still have something to correct?

**Comment by joethei** [comment]
Looks like you manually edited the id in your repo after this was merged.
Please undo your change,  as now that this is merged, the id cannot be changed.

**Comment by Chrstn67** [comment]
Okay, but does this imply that I have to revert the previous commit and remove the 1.0.5 release?

**Comment by joethei** [comment]
Yes

**Comment by Chrstn67** [comment]
There, it's done. Can you check that everything is now OK, please?

**Pull request merged**
