### PR TITLE
Add plugin: Tags Routes

### PR DESCRIPTION
**Pull request by kctekn**
# I am submitting a new Community Plugin

## Repo URL

Link to my plugin: https://github.com/kctekn/obsidian-TagsRoutes

## Release Checklist
- [ ] I have tested the plugin on
  - [x]  Windows
  - [ ]  macOS
  - [x]  Linux
  - [ ]  Android _(if applicable)_
  - [ ]  iOS _(if applicable)_
- [x] My GitHub release contains all required files
  - [x] `main.js`
  - [x] `manifest.json`
  - [x] `styles.css` _(optional)_
- [x] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [x] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [x] My README.md describes the plugin's purpose and provides clear usage instructions.
- [x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x] I have added a license in the LICENSE file.
- [x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
      I have given proper attribution to these other projects in my `README.md`.

### CODE REVIEW

**Comment by kctekn** [comment]
/skip[1][2][3][4][5][6][7][8][9][10][11]: as they are dynamic changed for showing and hide, not for display style, so can't be replaced by css style

**Comment by kctekn** [comment]
changes have been made

**Comment by kctekn** [comment]
@joethei I'm new to here, do I need any other operation to nofity that the changes has been made?

**Comment by joethei** [comment]
["description": "For showing the routes of TAGs.",](https://github.com/kctekn/obsidian-TagsRoutes/blob/b90029db70584ef4ab75f914e449d3ba51d951b2/manifest.json#L6)
Don't capitalize tags.

[mySetting: string;](https://github.com/kctekn/obsidian-TagsRoutes/blob/b90029db70584ef4ab75f914e449d3ba51d951b2/main.ts#L8), [mySetting: 'default',](https://github.com/kctekn/obsidian-TagsRoutes/blob/b90029db70584ef4ab75f914e449d3ba51d951b2/main.ts#L28)
Remove this sample code.

[for (let leaf of app.workspace.getLeavesOfType(VIEW_TYPE_TAGS_ROUTES)) {](https://github.com/kctekn/obsidian-TagsRoutes/blob/b90029db70584ef4ab75f914e449d3ba51d951b2/main.ts#L53), [for (let leaf of app.workspace.getLeavesOfType(VIEW_TYPE_TAGS_ROUTES)) {](https://github.com/kctekn/obsidian-TagsRoutes/blob/b90029db70584ef4ab75f914e449d3ba51d951b2/main.ts#L127)
It's highly discouraged that you use the global app instance in your plugin. It's currently accessible from the global context for debugging purposes. Instead, you should use the reference to App that you have from your plugin instance.

[console.log("cache is already ready")](https://github.com/kctekn/obsidian-TagsRoutes/blob/b90029db70584ef4ab75f914e449d3ba51d951b2/main.ts#L61), [console.log("cache is not ready, wait for it")](https://github.com/kctekn/obsidian-TagsRoutes/blob/b90029db70584ef4ab75f914e449d3ba51d951b2/main.ts#L65)

[this.addRibbonIcon("footprints", "Tags Routes", () => {](https://github.com/kctekn/obsidian-TagsRoutes/blob/b90029db70584ef4ab75f914e449d3ba51d951b2/main.ts#L110), [return "Tags' Routes";](https://github.com/kctekn/obsidian-TagsRoutes/blob/b90029db70584ef4ab75f914e449d3ba51d951b2/views/TagsRoutes.ts#L76), [addSlider("Link Width", 1, 5, 1, 1, this.onLinkWidth)](https://github.com/kctekn/obsidian-TagsRoutes/blob/b90029db70584ef4ab75f914e449d3ba51d951b2/views/TagsRoutes.ts#L638-L641)
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

[if (!vault.getAbstractFileByPath("scripts/tag-report.js")) {](https://github.com/kctekn/obsidian-TagsRoutes/blob/b90029db70584ef4ab75f914e449d3ba51d951b2/main.ts#L138-L140)
The script should be bundled into the plugin, not loaded externally.

[.setName('Turn to log file after start')](https://github.com/kctekn/obsidian-TagsRoutes/blob/b90029db70584ef4ab75f914e449d3ba51d951b2/main.ts#L210)
That is not a good settings name.

[while (!(file && file instanceof TFile)) {](https://github.com/kctekn/obsidian-TagsRoutes/blob/b90029db70584ef4ab75f914e449d3ba51d951b2/util/util.ts#L90)
This is bad, if the file does not exist this code will run to infinity.

[await delay(100)](https://github.com/kctekn/obsidian-TagsRoutes/blob/b90029db70584ef4ab75f914e449d3ba51d951b2/util/util.ts#L91)
Why the delay?

[export function delay(ms: number) {](https://github.com/kctekn/obsidian-TagsRoutes/blob/b90029db70584ef4ab75f914e449d3ba51d951b2/util/util.ts#L104-L106)
There is a `sleep` function in the API that should be used instead.

[.addButton("Link borken as star", "graph-button", () => { this.connectBrokenNodes(true) })](https://github.com/kctekn/obsidian-TagsRoutes/blob/b90029db70584ef4ab75f914e449d3ba51d951b2/views/TagsRoutes.ts#L626-L628)
Typos.

[.addButton("Link excalidraw", "graph-button", () => { this.connectExcalidrawNodes() })](https://github.com/kctekn/obsidian-TagsRoutes/blob/b90029db70584ef4ab75f914e449d3ba51d951b2/views/TagsRoutes.ts#L629-L630)
Wrong capitalization of the brand name "Excalidraw"

**Comment by kctekn** [comment]
Hello, thank  you for the review, and  I have made changes for them and other comments below:
- For [if (!vault.getAbstractFileByPath("scripts/tag-report.js")) {](https://github.com/kctekn/obsidian-TagsRoutes/blob/b90029db70584ef4ab75f914e449d3ba51d951b2/main.ts#L138-L140)  , that is used/load by dataview's code block, not by plugin itself. The dataview's code block is used to generate the query result dynamic at each time.
- [await delay(100)](https://github.com/kctekn/obsidian-TagsRoutes/blob/b90029db70584ef4ab75f914e449d3ba51d951b2/util/util.ts#L91) While the log file is first time created, it always have a long time delay about 500ms after it can be read and show.

**Comment by kctekn** [comment]
hello, what's the status for now? @joethei

**Comment by kctekn** [comment]
Modified the code as requested. @joethei

**Pull request merged**
